Repository civicrm/civicrm-core, pull requests merged in 2018-12, with the labels that each got.

#13199 dev/core#125 Fix Doc url to custom fields user documentation
  templates/CRM/Custom/Page/Group.tpl
Labels: master

#13176 Flatten fix
  CRM/Dedupe/Finder.php
  CRM/Utils/Array.php
  tests/phpunit/CRM/Utils/ArrayTest.php
  tests/phpunit/Civi/API/Subscriber/WhitelistSubscriberTest.php
Labels: master

#13195 Update npm dependencies to fix audit issues
  package-lock.json
  package.json
Labels: master

#13198 dev/core#561 Remove jcalendar from the Event Aggregate Custom Search
  CRM/Contact/Form/Search/Custom/EventAggregate.php
  templates/CRM/Contact/Form/Search/Custom/EventDetails.tpl
Labels: master, merge on pass

#13190 dev-core#565: Make subject field of Note, inline editable in contact summary page
  templates/CRM/Contact/Page/View/Note.tpl
Labels: master

#13200 dev/mail#23: Bounce processing doesn't catch pattern 'user doesn't exist'
  CRM/Upgrade/Incremental/sql/5.9.alpha1.mysql.tpl
  sql/civicrm_generated.mysql
  xml/templates/civicrm_data.tpl
Labels: master, merge on pass

#13196 dev/core#561 Replace jacalendar with datepicker in Price Field Form
  CRM/Price/DAO/PriceField.php
  CRM/Price/Form/Field.php
  templates/CRM/Price/Form/Field.tpl
  templates/CRM/Price/Page/Field.tpl
  xml/schema/Price/PriceField.xml
Labels: master, merge on pass

#13206 dev/core#561 Convert Pledge Payment form to use datepicker rather tha…
  CRM/Pledge/DAO/PledgePayment.php
  CRM/Pledge/Form/Payment.php
  CRM/Utils/Date.php
  templates/CRM/Pledge/Form/Payment.tpl
  xml/schema/Pledge/PledgePayment.xml
Labels: master, merge on pass

#13210 [REF] refactor shared search functions in pre-Process
  CRM/Activity/Form/Search.php
  CRM/Campaign/Form/Search.php
  CRM/Case/Form/Search.php
  CRM/Contribute/Form/Search.php
  CRM/Core/Form/Search.php
  CRM/Event/Form/Search.php
  CRM/Grant/Form/Search.php
  CRM/Member/Form/Search.php
  CRM/Pledge/Form/Search.php
Labels: master

#13013 Prototype for metadata based fields on search screens.
  CRM/Activity/BAO/Query.php
  CRM/Activity/Form/Search.php
  CRM/Core/Form/Search.php
Labels: master, merge on pass

#13212 Make world_region translate on advanced search field
  CRM/Core/BAO/Address.php
  CRM/Core/CodeGen/Specification.php
  CRM/Core/DAO/Address.php
  CRM/Core/DAO/Country.php
  CRM/Core/PseudoConstant.php
  xml/schema/Core/Address.xml
  xml/schema/Core/Country.xml
  xml/templates/dao.tpl
Labels: master, merge on pass

#13223 dev/core#573 Fix select2 height on public pages
  css/civicrm.css
Labels: master

#13169 dev/core/482 standardize contact edit form delete block behavior
  templates/CRM/Contact/Form/Edit/Website.tpl
  templates/CRM/Contact/Form/Inline/Website.tpl
Labels: master

#13219 Fix [unreleased] typo from https://github.com/civicrm/civicrm-core/pull/13210
  CRM/Case/Form/Search.php
  CRM/Event/Form/Search.php
Labels: master

#13225 [REF] Rename recently added getUrlVariables getFormVariables function…
  CRM/Activity/Form/Search.php
  CRM/Campaign/Form/Search.php
  CRM/Case/Form/Search.php
  CRM/Contribute/Form/Search.php
  CRM/Core/Form/Search.php
  CRM/Event/Form/Search.php
  CRM/Grant/Form/Search.php
  CRM/Member/Form/Search.php
  CRM/Pledge/Form/Search.php
Labels: master, merge on pass

#13218 Revert "CRM-19115 - Always set the MySQL timezone offset before checking for …"
  CRM/Utils/Check/Component/Env.php
Labels: master

#13220 CRM-19115 - Synchronize PHP=>MySQL active timezone for all backend scripts
  CRM/Utils/System.php
Labels: master

#13209 Add custom search handling for jcalendar converstion.
  CRM/Contact/Form/Search/Custom/ActivitySearch.php
  CRM/Contact/Form/Search/Custom/ContribSYBNT.php
  CRM/Contact/Form/Search/Custom/DateAdded.php
  CRM/Contact/Form/Search/Custom/EventAggregate.php
  CRM/Contact/Form/Search/Custom/TagContributions.php
Labels: master, merge ready

#13227 Fix period_type, duration_unit, duration_frequency to be required on membership type form
  CRM/Member/Form/MembershipType.php
Labels: 5.8, merge on pass

#13229 5.8
  CRM/Member/Form/MembershipType.php
Labels: master

#13217 dev/core#529 open search panes when when reviewing smart groups if they have stuff selected
  templates/CRM/Contact/Form/Search/AdvancedCriteria.tpl
Labels: master, merge on pass

#13188 dev/core#563: Duplicate Case manager role fix
  CRM/Contact/Page/AJAX.php
Labels: master

#13233 Typos, simplify if statement
  CRM/Dedupe/Finder.php
  CRM/Event/Form/Registration/Confirm.php
Labels: master

#13074 5.8.0 release notes
  contributor-key.yml
  release-notes.md
  release-notes/5.5.1.md
  release-notes/5.5.2.md
  release-notes/5.5.3.md
  release-notes/5.6.1.md
  release-notes/5.7.1.md
  release-notes/5.7.2.md
  release-notes/5.8.0.md
Labels: 5.8

#13228 dev/core#572 Revert customData changes in EventInfo template.
  templates/CRM/Event/Form/ManageEvent/EventInfo.tpl
Labels: 5.8

#13235 5.8 to master
  contributor-key.yml
  release-notes.md
  release-notes/5.5.1.md
  release-notes/5.5.2.md
  release-notes/5.5.3.md
  release-notes/5.6.1.md
  release-notes/5.7.1.md
  release-notes/5.7.2.md
  release-notes/5.8.0.md
  templates/CRM/Event/Form/ManageEvent/EventInfo.tpl
Labels: master

#13088 dev/core#518 Fix lybunt performance
  CRM/Report/Form/Contribute/Lybunt.php
  tests/phpunit/api/v3/ReportTemplateTest.php
Labels: master

#13226 dev/core#407 Fix mis-saving of price field values under localisation.
  CRM/Member/Form/MembershipBlock.php
  CRM/Price/BAO/PriceField.php
Labels: master

#13230 Api3 - Add uf_user contact search param
  api/v3/Contact.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/api/v3/ContactTest.php
Labels: has-test, master

#13197 dev/core#442 Fix Style issues on word replacements, credit card expir…
  CRM/Admin/Form/WordReplacements.php
  CRM/Core/Payment.php
  CRM/Core/Payment/Form.php
  templates/CRM/Contact/Form/Edit/TagsAndGroups.tpl
  templates/CRM/Contact/Page/DedupeException.tpl
Labels: master, sig:extension support, sig:user interfacing improvement

#13236 Add release-notes/5.7.3.md
  release-notes/5.7.3.md
Labels: 5.7

#13239 dev/core#576 Fix the generation of DAO files because version comparis…
  CRM/Core/CodeGen/Specification.php
Labels: master

#13231 clean up campaigns for reports
  CRM/Report/Form.php
  CRM/Report/Form/Contribute/Lybunt.php
Labels: master, merge on pass

#13243 campaign cleanup
  CRM/Report/Form/Contribute/Summary.php
Labels: master, merge on pass

#13245 Standardize letter case
  CRM/Case/Task.php
Labels: master, merge on pass

#13246 (RFC) Fix Locale Test by re-setting the locale used to en_US and by resetting the I18n singleton
  CRM/Core/I18n.php
  tests/phpunit/CRM/Core/I18n/LocaleTest.php
Labels: 5.9

#13248 5.9 to master
  CRM/Core/I18n.php
  tests/phpunit/CRM/Core/I18n/LocaleTest.php
Labels: master

#13247 (NFC) Fix PHP7.2 Count error on test testImportParserWtihEmployeeOfRelation…
  tests/phpunit/CRM/Contact/Import/Parser/ContactTest.php
Labels: master, merge on pass

#13249 dev/core#582 - Search Builder: Switch to new date/timepicker widget
  CRM/Contact/Form/Search/Builder.php
  templates/CRM/Contact/Form/Search/Builder.js
Labels: 5.9

#13253 5.9 to master
  CRM/Contact/Form/Search/Builder.php
  templates/CRM/Contact/Form/Search/Builder.js
Labels: master

#13254 5.8 backport of #13249
  CRM/Contact/Form/Search/Builder.php
  templates/CRM/Contact/Form/Search/Builder.js
Labels: 5.8

#13240 dev/translation#13 Enable users to choose their own language for accessing CiviCRM
  CRM/Admin/Form/Setting/Localization.php
  CRM/Core/BAO/ConfigSetting.php
  CRM/Core/I18n.php
  CRM/Core/Smarty.php
  settings/Localization.setting.php
  sql/civicrm_generated.mysql
  templates/CRM/Admin/Form/Setting/Localization.js
  templates/CRM/Admin/Form/Setting/Localization.tpl
  tests/phpunit/CRM/Core/I18n/LocaleTest.php
Labels: master, merge on pass

#13256 dev/core#589 - Fix saving autocomplete search preferences
  CRM/Admin/Form/Setting.php
  CRM/Admin/Form/Setting/Search.php
  settings/Core.setting.php
Labels: 5.9, merge on pass

#13260 5.9 to master
  CRM/Admin/Form/Setting.php
  CRM/Admin/Form/Setting/Search.php
  settings/Core.setting.php
Labels: master

#13264 5.9 to master
  CRM/Core/DAO.php
Labels: master

#13261 dev/core#589 - Fix saving autocomplete search preferences
  CRM/Admin/Form/Setting.php
  CRM/Admin/Form/Setting/Search.php
  settings/Core.setting.php
Labels: 5.8, merge on pass

#13265 dev/core#588 fix "CiviMail Draft" appears twice in non-Mosaico test emails
  ang/crmMailing/services.js
Labels: 5.9, merge on pass

#13266 dev/core#588 fix "CiviMail Draft" appears twice in non-Mosaico test emails
  ang/crmMailing/services.js
Labels: 5.8, merge on pass

#13268 (NFC) Update Copyright in FiveTen upgrade file to be 2019
  CRM/Upgrade/Incremental/php/FiveTen.php
Labels: master, merge on pass

#13271 (NFC) whitespace header fixes
  CRM/Core/Form/EntityFormTrait.php
  CRM/Core/Payment/eWAY.php
  CRM/Financial/Form/SalesTaxTrait.php
  tests/phpunit/CRM/Mailing/BAO/MailingJobTest.php
  tests/phpunit/CiviTest/CiviTestSMSProvider.php
  tools/bin/scripts/replace.sh
Labels: 5.9, merge on pass

#13213 [REF] Build single array of information about output specifications when exporting
  CRM/Export/BAO/Export.php
  CRM/Export/BAO/ExportProcessor.php
  tests/phpunit/CRM/Export/BAO/ExportTest.php
Labels: master

#13274 5.9 to master
  CRM/Core/Form/EntityFormTrait.php
  CRM/Core/Payment/eWAY.php
  CRM/Financial/Form/SalesTaxTrait.php
  tests/phpunit/CRM/Mailing/BAO/MailingJobTest.php
  tests/phpunit/CiviTest/CiviTestSMSProvider.php
  tools/bin/scripts/replace.sh
Labels: master

#13272 dev/core#595 Fix label default not being set on membership status form
  CRM/Core/Form/EntityFormTrait.php
Labels: 5.9

#13216 [REF] Export cleanup - filter at point of query on postal exports
  CRM/Contact/BAO/Query.php
  CRM/Export/BAO/Export.php
  CRM/Export/BAO/ExportProcessor.php
  tests/phpunit/CRM/Export/BAO/ExportTest.php
Labels: master

#13269 [REF] Minor Test clean up
  tests/phpunit/CRMTraits/ACL/PermissionTrait.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/api/v3/ACLPermissionTest.php
  tests/phpunit/api/v3/EntityTagACLTest.php
  tests/phpunit/api/v3/ReportTemplateTest.php
Labels: master

#13295 Fix PHP 7 strict warnings CRM_Core_DAO::getContactIDsFromComponent passed by reference
  CRM/Core/Form/Task.php
  CRM/Event/Form/Task.php
  CRM/Grant/Form/Task.php
  CRM/Member/Form/Task.php
  CRM/Pledge/Form/Task.php
Labels: master

#13294 dev/joomla#3 CRM-21780 Fix Mailings Recipients box incompatabilites …
  ang/crmMailing/Recipients.js
Labels: master

#12344 dev/core#192 - Search builder fails for != smart group filter
  CRM/Contact/BAO/Query.php
  tests/phpunit/CRM/Contact/BAO/GroupContactCacheTest.php
Labels: has-test, master, sig:bug

#13290 Declare 'amount' as required on ContributionRecur api
  api/v3/ContributionRecur.php
Labels: master, sig:bug

#13273 dev/core#597 Fix broken api get filter on financial_type
  CRM/Contribute/Page/ManagePremiums.php
  CRM/Contribute/Page/Premium.php
  CRM/Financial/DAO/FinancialType.php
  api/v3/FinancialType.php
  tests/phpunit/api/v3/FinancialTypeTest.php
  xml/schema/Financial/FinancialType.xml
Labels: 5.9

#13277 Fix netAmount null object on freeze
  CRM/Contribute/Form/AdditionalInfo.php
Labels: 5.9, merge on pass

#13275 [REF] Export add test for phone details, fix phone_type_id
  CRM/Export/BAO/ExportProcessor.php
  tests/phpunit/CRM/Export/BAO/ExportTest.php
Labels: master

#13300 Fix netAmount null object on freeze
  CRM/Contribute/Form/AdditionalInfo.php
Labels: 5.8, merge on pass

#13302 Fix broken api get filter on financial_type
  CRM/Contribute/Page/ManagePremiums.php
  CRM/Contribute/Page/Premium.php
  CRM/Financial/DAO/FinancialType.php
  api/v3/FinancialType.php
  tests/phpunit/api/v3/FinancialTypeTest.php
  xml/schema/Financial/FinancialType.xml
Labels: 5.8, merge on pass

#13303 dev/core#593 - Fix quicksearch by email
  api/v3/Contact.php
  tests/phpunit/api/v3/ContactTest.php
Labels: 5.9, merge on pass

#13301 5.9
  CRM/Contribute/Form/AdditionalInfo.php
  CRM/Contribute/Page/ManagePremiums.php
  CRM/Contribute/Page/Premium.php
  CRM/Core/Form/EntityFormTrait.php
  CRM/Financial/DAO/FinancialType.php
  api/v3/Contact.php
  api/v3/FinancialType.php
  tests/phpunit/api/v3/ContactTest.php
  tests/phpunit/api/v3/FinancialTypeTest.php
  xml/schema/Financial/FinancialType.xml
Labels: master

#13297 dev/core#593 - Fix quicksearch by email
  api/v3/Contact.php
Labels: 5.8

#13304 dev/core#585 Fix setting target contact on activities when creating a case with activity sequence.
  CRM/Case/Form/CaseView.php
  CRM/Case/XMLProcessor/Process.php
  Civi/CCase/SequenceListener.php
Labels: 5.9

#13305 dev/core#585 Fix setting target contact on activities when creating a case with activity sequence.
  CRM/Case/Form/CaseView.php
  CRM/Case/XMLProcessor/Process.php
  Civi/CCase/SequenceListener.php
Labels: 5.8

#13306 5.9 to master
  CRM/Case/Form/CaseView.php
  CRM/Case/XMLProcessor/Process.php
  Civi/CCase/SequenceListener.php
Labels: master

#13307 Update 5.8 to 5.8.2. Add release notes.
  CRM/Upgrade/Incremental/sql/5.8.2.mysql.tpl
  release-notes/5.8.2.md
  sql/civicrm_generated.mysql
  xml/version.xml
Labels: 5.8

#13308 Add release notes for 5.8.2 & 5.8.1
  release-notes/5.8.1.md
  release-notes/5.8.2.md
Labels: 5.9

#13296 dev/core#603 not set default value yes/no for active relationship filters
  CRM/Report/Form/Case/Summary.php
Labels: master

#13309 Bump Minimum Required PHP to be 5.6
  CRM/Upgrade/Form.php
  CRM/Upgrade/Incremental/General.php
Labels: master, merge on pass

#13312 dev/core#606: Don't redirect to the Option Groups page when page is displayed in a modal
  templates/CRM/Admin/Page/Options.tpl
Labels: 5.9

#13170 dev/core/485 Website type should be required as other type values are
  CRM/Contact/Form/Edit/Website.php
Labels: master

#12995 dev/core/454 rationalise activity case permissions & code
  CRM/Activity/BAO/Activity.php
  tests/phpunit/api/v3/ACLPermissionTest.php
Labels: master

#13315 Fix PHP7.2 Count error on test testImportParserWtihEmployeeOfRelation…
  tests/phpunit/CRM/Contact/Import/Parser/ContactTest.php
Labels: 5.9, merge on pass

#13313 Search Builder fails with an error when searching for State if the location type differs from the display name.
  CRM/Contact/BAO/Query.php
  tests/phpunit/CRM/Contact/BAO/QueryTest.php
Labels: master

#13326 installer: PHP 7.2 compatibility fixes
  install/index.php
Labels: master

#13322 dev/report#5 - Fix mailing report unique count issue
  CRM/Mailing/BAO/Mailing.php
  CRM/Report/Form/Mailing/Opened.php
  templates/CRM/Mailing/Page/Report.tpl
  tests/phpunit/api/v3/ReportTemplateTest.php
Labels: has-test, master

#12669 Fix duplicate merge to not disregard zero values.
  CRM/Dedupe/Merger.php
  tests/phpunit/api/v3/JobTest.php
Labels: master

#13323 Unit test for PR#12699
  tests/phpunit/api/v3/JobTest.php
Labels: master, merge on pass

#13321 campaign cleanup for sybunt report and show disabled campaigns as well
  CRM/Report/Form/Contribute/Sybunt.php
Labels: master

#13337 NFC: Improved documentation of crmPageTitle directive.
  ang/crmUi.js
Labels: master

#13311 Support customdata subtype on entityform (for activity/relationship types)
  CRM/Core/Form/EntityFormTrait.php
  CRM/Custom/Form/CustomData.php
Labels: master

#13281 campaign cleanup for household summary
  CRM/Report/Form/Contribute/HouseholdSummary.php
Labels: master

#13241 dev/core#561 Convert Scheduled Reminders Form to use datepicker and e…
  CRM/Admin/Form/ScheduleReminders.php
  templates/CRM/Admin/Form/ScheduleReminders.tpl
Labels: master

#13250 #469 - Error on action "Email - schedule/send via CiviMail" with mult…
  CRM/Contact/BAO/Group.php
  CRM/Contact/Form/Search/Advanced.php
  tests/phpunit/CRM/Contact/BAO/GroupTest.php
Labels: master

#13329 [REF] Add caching to function to determine if activity type is permitted.
  CRM/Activity/BAO/Activity.php
Labels: master

#13291 Add default of TRUE for is_active on PaymentProcessor.create api.
  api/v3/PaymentProcessor.php
  tests/phpunit/api/v3/PaymentProcessorTest.php
Labels: master

#13341 add suport for order by clause for campaign and clean up
  CRM/Report/Form.php
  CRM/Report/Form/Contribute/Detail.php
Labels: master, merge on pass

#13348 (dev/core#491) campaign cleanup for contribution (org) report and sho…
  CRM/Report/Form/Contribute/OrganizationSummary.php
Labels: master

#13349 fix verbiage for Dashboard title
  CRM/Contact/Page/View/UserDashBoard.php
Labels: master

#13347 optimize CRM_Utils_String::ellipsify() method
  CRM/Utils/String.php
Labels: master

#13339 (dev/core#610) Page title displays twice on Activity form
  CRM/Activity/Form/Activity.php
Labels: master

#13352 fix verbiage for Edit Contact Information title
  CRM/Contact/Page/View/UserDashBoard.php
Labels: master

#13351 (dev/core#491) campaign cleanup for soft credit report and show disab…
  CRM/Report/Form/Contribute/SoftCredit.php
Labels: master

#13316 On the Contribution Detail Report link the Amount field to the contribution
  CRM/Report/Form/Contribute/Detail.php
Labels: master

#13355 dev/core#621 Ensure that only 2 decimal places are dispalyed for opti…
  CRM/Price/Form/Option.php
Labels: master

#13356 (dev/core#491) campaign cleanup for pledge detail report and show dis…
  CRM/Report/Form/Pledge/Detail.php
Labels: master, merge on pass

#13354 dev/mail#35 Ensure that Public View link is visible in Scheduled and …
  CRM/Mailing/Selector/Browse.php
Labels: master

#13350 #620 - Unable to show custom fields on Repeat Contributions Report
  CRM/Report/Form/Contribute/Repeat.php
Labels: master

#13215 Display self-service links in email receipts based on payment processor capabilities
  CRM/Core/Payment.php
  CRM/Core/Payment/Dummy.php
  CRM/Upgrade/Incremental/MessageTemplates.php
  xml/templates/message_templates/contribution_online_receipt_html.tpl
  xml/templates/message_templates/contribution_online_receipt_text.tpl
  xml/templates/message_templates/contribution_recurring_notify_html.tpl
  xml/templates/message_templates/contribution_recurring_notify_text.tpl
  xml/templates/message_templates/membership_online_receipt_html.tpl
  xml/templates/message_templates/membership_online_receipt_text.tpl
Labels: master

#13362 dev/core#623 add in upgrade step to update Away type hold threshold t…
  CRM/Upgrade/Incremental/sql/5.10.alpha1.mysql.tpl
Labels: master

#13299 Activity date fields -> datepicker
  CRM/Activity/Form/Activity.php
  CRM/Case/Form/Activity.php
  CRM/Case/Form/Activity/ChangeCaseStartDate.php
  CRM/Case/Form/Activity/OpenCase.php
  templates/CRM/Activity/Form/Activity.tpl
  templates/CRM/Case/Form/Activity.tpl
  templates/CRM/Case/Form/Activity/ChangeCaseStartDate.tpl
  templates/CRM/Case/Form/Activity/OpenCase.tpl
Labels: master, merge on pass

#13366 dev/core#623 Refine the upgrade statement to only those of the old st…
  CRM/Upgrade/Incremental/sql/5.10.alpha1.mysql.tpl
Labels: merge on pass

#13328 [REF] genericise function to add pseudoconstant data to fields to process
  CRM/Contribute/BAO/Contribution.php
  CRM/Core/BAO/Mapping.php
  CRM/Core/DAO.php
Labels: master

#13359 (dev/core#625) DB error on Case Summary report
  CRM/Report/Form/Case/Summary.php
Labels: master

#13368 Cache case count when getting list of cases so query is executed once instead of three times
  CRM/Case/BAO/Case.php
Labels: merge on pass

#13367 NFC tidy up comments, remove unused variables in customfield classes
  CRM/Core/BAO/CustomField.php
  CRM/Core/BAO/CustomGroup.php
  api/v3/CustomValue.php
Labels: merge on pass

#13370 [REF] extract internals of Payment.create into function on BAO class.
  CRM/Contribute/BAO/Contribution.php
  api/v3/Payment.php
Labels: master, merge on pass
