Repository civicrm/civicrm-core, pull requests merged in 2018-05, with the labels that each got.

#12064 Rename function enableFullGroupByMode to be reenableFullGroupByMode t…
  CRM/Core/DAO.php
  CRM/Export/BAO/Export.php
  CRM/Mailing/Event/BAO/TrackableURLOpen.php
  CRM/Report/Form.php
Labels: master, merge on pass

#12058 (dev/core/91) Search Builder Improvements
  CRM/Contact/Form/Search/Builder.php
  CRM/Core/SelectValues.php
  templates/CRM/Contact/Form/Search/Builder.js
Labels: master, sig:bug

#12069 5.1.0 release notes
  CONTRIBUTORS.txt
  contributor-key.yml
  release-notes.md
  release-notes/5.0.1.md
  release-notes/5.0.2.md
  release-notes/5.1.0.md
Labels: 5.1, merge on pass

#12071 core-94 - Advanced Search Display Results As always displays contact …
  CRM/Contact/Form/Search.php
  CRM/Contact/StateMachine/Search.php
Labels: merge on pass

#12072 5.1 merge to master
  CONTRIBUTORS.txt
  CRM/Contact/Form/Search.php
  CRM/Contact/StateMachine/Search.php
  contributor-key.yml
  release-notes.md
  release-notes/5.0.1.md
  release-notes/5.0.2.md
  release-notes/5.1.0.md
Labels: master

#12056 Fix Soft credit personal note ton limit to 255 characters (DB limit).
  CRM/Contribute/Form/Contribution/Confirm.php
  CRM/Contribute/Form/Contribution/Main.php
  CRM/Core/Form.php
  CRM/PCP/BAO/PCP.php
  CRM/PCP/Form/Campaign.php
  CRM/PCP/Page/PCPInfo.php
Labels: master

#12050 CRM-20459: Actively deprecate CRM_Core_OptionGroup::getValue[Sub PR 2]
  CRM/Contribute/Form/Task/Status.php
  CRM/Contribute/Form/UpdateBilling.php
  CRM/Contribute/Import/Parser/Contribution.php
  CRM/Core/BAO/ActionSchedule.php
  CRM/Core/BAO/UFGroup.php
  CRM/Event/BAO/Participant.php
  CRM/Event/Cart/Form/Checkout/Payment.php
Labels: master, merge on pass

#12082 5.1.0 release notes: updated synopsis
  release-notes/5.1.0.md
Labels: master

#12083 Payflow Pro not payflo
  CRM/Core/Payment/PayflowPro.php
Labels: master, merge on pass

#12076 (dev/core/99) Search builder doesn't retain selected (boolean) option after searching
  templates/CRM/Contact/Form/Search/Builder.js
Labels: master

#12087 (NFC) Update karma conf for more recent karma
  karma.conf.js
Labels: master

#12081 (dev/core/98) Searching by any Address fields with location type other than primary throw DB error
  CRM/Contact/BAO/Query.php
  tests/phpunit/CRM/Contact/SelectorTest.php
Labels: 5.2

#12086 (NFC) Change use createMock in tests otherwise stick with getMock to fix deprecated warning…
  tests/phpunit/CRM/Core/CommunityMessagesTest.php
  tests/phpunit/CRM/Core/JobManagerTest.php
  tests/phpunit/CRM/Extension/ManagerTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/api/v3/ContactTest.php
Labels: master

#11868 CRM-20922 fix support for passing custom date values via url
  CRM/Core/BAO/CustomGroup.php
  tests/phpunit/CRM/Core/BAO/CustomGroupTest.php
Labels: master

#12075 CRM-20459: Actively deprecate CRM_Core_OptionGroup::getValue
  CRM/Contribute/Form/Contribution/Main.php
  CRM/Core/BAO/UFGroup.php
  CRM/Core/DAO/CustomGroup.php
  CRM/Event/Form/Registration/AdditionalParticipant.php
  CRM/Event/Form/Registration/Register.php
  xml/schema/Core/CustomGroup.xml
Labels: master

#11920 (dev/core/40) Show List of Contributions On Recurring Contribution View
  CRM/Contribute/Form/Task.php
  CRM/Contribute/Form/UpdateSubscription.php
  CRM/Contribute/Page/ContributionRecur.php
  CRM/Contribute/Page/ContributionRecurPayments.php
  CRM/Contribute/xml/Menu/Contribute.xml
  templates/CRM/Contribute/Page/ContributionRecur.tpl
  templates/CRM/Contribute/Page/ContributionRecurPayments.tpl
Labels: master

#12090 Fix e-notice
  CRM/Core/Form.php
Labels: master, merge on pass

#12092 CRM-20459: Actively deprecate CRM_Core_OptionGroup::getValue
  CRM/Event/Page/ParticipantListing.php
  CRM/Mailing/BAO/MailingJob.php
  CRM/Mailing/Form/Approve.php
  CRM/PCP/BAO/PCP.php
  CRM/PCP/Form/Campaign.php
  CRM/Profile/Form.php
  CRM/Upgrade/Incremental/php/FourFour.php
  CRM/Utils/DeprecatedUtils.php
Labels: master

#12094 Fix Fatal error on membership detail report (with ACLs enabled) dev/core/#100
  CRM/Report/Form/Member/Detail.php
  tests/phpunit/api/v3/ReportTemplateTest.php
Labels: master, merge on pass

#12080 Fix (unreleased) regression on report pager
  CRM/Report/Form.php
Labels: 5.2

#12095 Function extraction (Move towards generic custom data support for all entities)
  CRM/Custom/Form/CustomData.php
  CRM/Event/Form/Participant.php
  CRM/Member/Form.php
  CRM/Member/Form/Membership.php
Labels: master, merge on pass

#12099 5.2 to master
  CRM/Report/Form.php
Labels: master

#12084 Run master tests using phpunit5
  Civi/Test/CiviTestListener.php
  tools/scripts/phpunit
Labels: master

#12097 Fix Relationship Type form to use the metadata for fields & api in postProcess
  CRM/Admin/Form/RelationshipType.php
  CRM/Contact/DAO/RelationshipType.php
  xml/schema/Contact/RelationshipType.xml
Labels: master

#12101 Upgrade Karma phantomjs launcher to latest version
  package-lock.json
  package.json
Labels: master

#12070 Fix fatal error on logging tab when hook alters logging tables.
  CRM/Core/DAO.php
  CRM/Logging/ReportSummary.php
  CRM/Logging/Schema.php
  CRM/Report/Form/Contact/LoggingSummary.php
  CRM/Utils/SQL.php
  tests/phpunit/api/v3/ReportTemplateTest.php
Labels: master

#12105 karma.conf.js - Switch singleRun back to `false` default
  karma.conf.js
Labels: master, merge on pass

#12104 dev/core#108 reset address array when setting new event location
  CRM/Event/Form/ManageEvent/Location.php
Labels: master

#12108 ApiExplorer - Output short array syntax
  templates/CRM/Admin/Page/APIExplorer.js
Labels: master

#11903 dev/core#38 Show Recurring Contributions on Membership Modal View
  CRM/Contribute/xml/Menu/Contribute.xml
  CRM/Member/Form/MembershipView.php
  CRM/Member/Page/RecurringContributions.php
  Civi/Test/Api3TestTrait.php
  templates/CRM/Member/Form/Membership.tpl
  templates/CRM/Member/Form/MembershipView.tpl
  templates/CRM/Member/Page/RecurringContributions.tpl
Labels: master

#11996 (dev/core/68) Fix DB Error on 'Find Participant' page when MySQL FULL_GROUP_BY_MODE is enabled
  CRM/Contact/BAO/Query.php
Labels: master, merge ready

#12110 Re-Fix Case form task (export/print not working) (replace quick fix with proper fix)
  CRM/Case/Form/Task.php
  CRM/Case/Form/Task/Delete.php
  CRM/Case/Form/Task/PDF.php
  CRM/Case/Form/Task/Restore.php
  CRM/Case/Form/Task/SearchTaskHookSample.php
  CRM/Core/DAO.php
  CRM/Core/Form/Task.php
  CRM/Export/Form/Select.php
Labels: 5.2, merge on pass

#12085 (NFC) Add unit test of submitting the Pledge Search Form
  CRM/Pledge/Selector/Search.php
  tests/phpunit/CRM/Pledge/Form/SearchTest.php
Labels: master

#12120 Fgb
  CRM/Contact/BAO/Query.php
Labels: 5.2, merge on pass

#12112 dev/translation#9 Create API Action to rebuild Multilingual Schema
  api/v3/System.php
Labels: 5.1, merge on pass

#11908 Support hooks for MembershipType entity
  CRM/Member/BAO/MembershipType.php
Labels: master

#12122 tpl extraction of shared code for customDataBlock
  templates/CRM/Member/Form/Membership.tpl
  templates/CRM/common/customDataBlock.tpl
Labels: master, merge on pass

#12123 Preliminary tidy up of MembershipType form (towards custom data support)
  CRM/Member/Form/MembershipConfig.php
  CRM/Member/Form/MembershipType.php
Labels: master, merge on pass

#12126 Preliminary cleanup for Custom data support for MembershipType form
  CRM/Core/Payment.php
  CRM/Financial/BAO/PaymentProcessor.php
  CRM/Member/Form/MembershipType.php
Labels: master, merge on pass

#12116 Add DB default of 0 for custom_group.is_multiple - CRM-21853
  CRM/Upgrade/Incremental/sql/5.3.alpha1.mysql.tpl
  xml/schema/Core/CustomGroup.xml
Labels: master

#12131 Set Default values on is_active, is_searchable, is_view and is_active…
  CRM/Core/DAO/CustomField.php
  CRM/Core/DAO/CustomGroup.php
  CRM/Upgrade/Incremental/sql/5.3.alpha1.mysql.tpl
  xml/schema/Core/CustomField.xml
Labels: master, merge on pass

#12113 (dev/drupal#10) Make civicrm-version.php self-sufficient
  .gitignore
  CRM/Core/CodeGen/Main.php
  CRM/Core/CodeGen/Version.php
  civicrm-version.php
  distmaker/dists/common.sh
Labels: master

#12133 (dev/core/98) Searching by any Address fields with location type other than primary throw DB error
  CRM/Contact/BAO/Query.php
  tests/phpunit/CRM/Contact/SelectorTest.php
Labels: 5.1, merge on pass

#12127 Use getter function for entity id as on some forms is protected.
  CRM/Custom/Form/CustomData.php
  CRM/Member/Form/Membership.php
Labels: master

#12004 dev/core#30 export of contact master_id name only if there is a master_id given (rebase)
  CRM/Contact/BAO/Contact.php
  CRM/Export/BAO/Export.php
  tests/phpunit/CRM/Export/BAO/ExportTest.php
Labels: master

#11877 CRM-21853: Do not change 'is_multiple' unless included in the params
  CRM/Core/BAO/CustomGroup.php
Labels: master, merge on pass

#12134 dev/financial#11 email invoice fails with validation error
  CRM/Contribute/Form/Task/Invoice.php
Labels: 5.1, merge on pass

#12136 (NFC) Disable tests performing quick search with no orderby as provin…
  CRM/Utils/SQL.php
  tests/phpunit/api/v3/ContactTest.php
Labels: merge on pass

#12132 Add labels to membership type metadata, allowing for addField method to be used
  CRM/Core/CodeGen/Specification.php
  CRM/Core/Form.php
  CRM/Core/I18n/SchemaStructure.php
  CRM/Member/DAO/MembershipType.php
  CRM/Member/Form/MembershipType.php
  xml/schema/Member/MembershipType.xml
  xml/templates/dao.tpl
Labels: master, merge on pass

#12106 [NFC] Cleanup on ActivityTest class.
  api/v3/Activity.php
  tests/phpunit/api/v3/ActivityTest.php
Labels: master

#12103 (NFC) Update view issues and report bugs link in footer to point to the lab
  templates/CRM/common/footer.tpl
Labels: master

#12139 (dev/drupal/17) Add Drupal8 support for getUFLocale()
  CRM/Utils/System/Drupal8.php
  CRM/Utils/System/DrupalBase.php
Labels: master

#12142 (NFC) Add release notes for 5.1.1
  release-notes.md
  release-notes/5.1.1.md
Labels: 5.1

#12141 Fix file perms on files back to 664
  CRM/Core/I18n/SchemaStructure.php
  install/langs.php
  js/crm.insert-shortcode.js
  tests/phpunit/CRM/Price/BAO/PriceFieldValueTest.php
  tests/phpunit/CRM/Price/Form/FieldTest.php
  tests/phpunit/CRM/Price/Form/OptionTest.php
Labels: master

#12140 (NFC) fix file permissions on civicrm-version.php
  civicrm-version.php
Labels: master

#12135 added unit test
  CRM/Contact/Selector.php
  tests/phpunit/CRM/Contact/SelectorTest.php
Labels: master

#11962 Hide Adding Option Value for Locked Groups
  CRM/Admin/Page/Options.php
  CRM/Core/BAO/CustomOption.php
  CRM/Core/OptionValue.php
  CRM/Custom/Page/Option.php
  templates/CRM/Custom/Page/Option.tpl
Labels: master, merge on pass

#12143 (NFC) Add in 5.1.0 and 5.1.1 mysql upgrade files
  CRM/Upgrade/Incremental/sql/5.1.0.mysql.tpl
  CRM/Upgrade/Incremental/sql/5.1.1.mysql.tpl
Labels: 5.2

#12145 5.2 merge to master
  CRM/Upgrade/Incremental/sql/5.1.0.mysql.tpl
  CRM/Upgrade/Incremental/sql/5.1.1.mysql.tpl
  release-notes.md
  release-notes/5.1.1.md
Labels: master

#12011 dev/financial#12 move soft credit item count to object property
  CRM/Contribute/Form/Contribution.php
  CRM/Contribute/Form/SoftCredit.php
Labels: master

#12003 code/dev/69: Change Approach For Setting state_province_name
  CRM/Utils/Address.php
  tests/phpunit/CRM/Utils/AddressTest.php
Labels: has-test, master

#12000 Add inplace edit for timeline name
  ang/crmCaseType.css
  ang/crmCaseType.js
  ang/crmCaseType/activitySetDetails.html
  ang/crmCaseType/edit.html
  tests/karma/unit/crmCaseTypeSpec.js
Labels: master, merge on pass

#11772 CRM-21821 respect nav item weight
  CRM/Core/BAO/Navigation.php
Labels: master

#11629 CRM-21675: scheduled reminders: limit to group doesn't support parent groups
  CRM/Contact/BAO/Group.php
  Civi/ActionSchedule/RecipientBuilder.php
  tests/phpunit/CRM/Core/BAO/ActionScheduleTest.php
Labels: has-test, master

#12148 Add release notes and version bump for 5.1.2
  CRM/Upgrade/Incremental/sql/5.1.2.mysql.tpl
  release-notes.md
  release-notes/5.1.2.md
  sql/civicrm_generated.mysql
  xml/version.xml
Labels: 5.1

#12149 Fix (unreleased) regression on report pager
  CRM/Report/Form.php
Labels: 5.1

#12150 Fix Fatal error on membership detail report (with ACLs enabled) dev/core/#100
  CRM/Report/Form/Member/Detail.php
  tests/phpunit/api/v3/ReportTemplateTest.php
Labels: 5.2, merge on pass

#12151 Fix Fatal error on membership detail report (with ACLs enabled) dev/core/#100
  CRM/Report/Form/Member/Detail.php
  tests/phpunit/api/v3/ReportTemplateTest.php
Labels: 5.1, merge on pass

#12154 dev/core#122 Wrong Action Links Shown for Reserved and Locked Option Groups
  CRM/Core/BAO/CustomOption.php
  CRM/Core/OptionValue.php
Labels: master

#12165 dev/core#117 Replace deprecated each with foreach in CRM/Activity/BAO…
  CRM/Activity/BAO/Query.php
Labels: master

#12164 dev/core#130 Remove deprecated create_function from RegionTest in fav…
  tests/phpunit/CRM/Core/RegionTest.php
Labels: master

#12168 dev/core#131 Add in missing UK state Monmouthshire
  CRM/Upgrade/Incremental/sql/5.3.alpha1.mysql.tpl
  sql/civicrm_generated.mysql
  xml/templates/civicrm_state_province.tpl
Labels: master

#12166 dev/core#117 Replace deprecated each with foreach in CRM/Utils/Token.php
  CRM/Utils/Token.php
Labels: master

#12157 Remove pass by reference for some mailing functions
  CRM/Mailing/BAO/MailingJob.php
  CRM/Utils/Mail.php
Labels: master

#12162 dev/core#118 Fix issue using count on non array in Group query builder
  CRM/Contact/BAO/Query.php
Labels: master

#12156 Fix issue where non numeric number was encounted in running unit test…
  CRM/Contribute/BAO/Contribution.php
Labels: master

#12159 dev/core#123 Retrieve existing participant custom fields for import
  CRM/Event/Import/Parser/Participant.php
Labels: master

#11679 CRM-21776: Ensure from clause adds custom table when search query is …
  CRM/Contact/BAO/Query.php
  tests/phpunit/CRM/Contact/SelectorTest.php
Labels: has-test, master

#12171 Towards dev/financial/#16 Paypal unreliable getting payment processor type
  CRM/Core/Payment/PayPalImpl.php
Labels: master, merge on pass

#11737 CRM-21816 Fix Relative dates in search bug
  CRM/Contact/BAO/Query.php
  tests/phpunit/CRM/Contact/BAO/QueryTest.php
Labels: has-test, master

#12153 dev/core#116 Search builder searches on primary addresses are producing unexpected results
  CRM/Contact/BAO/Query.php
  tests/phpunit/CRM/Contact/SelectorTest.php
Labels: master

#12172 dev/core#126 Add support for contact id as a basic report filter.
  CRM/Report/Form.php
Labels: master

#12155 dev/core#117 Replace use of Deprecated function each in CRM/Member/BA…
  CRM/Member/BAO/Membership.php
Labels: master

#11944 (accessibility/misc-core-fixes/issues/3) Remove CMS specific print header templates that share same code
  templates/CRM/common/CMSPrint.tpl
  templates/CRM/common/backdrop.tpl
  templates/CRM/common/drupal.tpl
  templates/CRM/common/drupal6.tpl
  templates/CRM/common/drupal8.tpl
  templates/CRM/common/unittests.tpl
  templates/CRM/common/wordpress.tpl
Labels: master, merge on pass

#12175 dev/core#35 Avoid variable leakage on recurring contribution receipts.
  CRM/Contribute/BAO/Contribution.php
  CRM/Core/BAO/UFJoin.php
  tests/phpunit/CRM/Core/Payment/AuthorizeNetIPNTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: has-test, master

#11732 CRM-21811: Optimize advanced search by relationship with target g…
  CRM/Contact/BAO/Query.php
  tests/phpunit/CRM/Contact/BAO/QueryTest.php
Labels: has-test

#12170 dev/core#117 Fix use of each in CRM/Pledge
  CRM/Pledge/BAO/Pledge.php
  CRM/Pledge/BAO/PledgeBlock.php
Labels: master

#12169 Update variable name as per upgraded Mime_mail package to support PHP7.2
  api/v3/Mailing.php
Labels: master

#12182 only add a closing quote if it is not already present
  CRM/Mailing/BAO/Mailing.php
Labels: master, merge on pass

#12137 Extend fiscal year relative options to better match other periods
  CRM/Utils/Date.php
  tests/phpunit/CRM/Utils/DateTest.php
Labels: has-test, master

#12187 Add utils for finding nested array items
  CRM/Utils/Array.php
  tests/phpunit/CRM/Utils/ArrayTest.php
Labels: master, merge on pass

#12189 Dev/Core#117 Fix use of each() function in Recur Report
  CRM/Report/Form/Contribute/Recur.php
Labels: master, merge on pass

#12190 dev/core#135 Fix first of 2 non numeric issues in CRM_Batch_form_entr…
  CRM/Batch/Form/Entry.php
Labels: merge on pass

#12188 dev/core#43 - Update geocoding setting text to reflect need for Google API key
  api/v3/examples/Setting/GetFields.php
  settings/Map.setting.php
  templates/CRM/Admin/Form/Setting/Mapping.tpl
Labels: master, merge on pass

#12191 dev/core#135 Fix remaining non well formed numeric number problems in…
  CRM/Batch/Form/Entry.php
Labels: merge on pass

#12180 Removing related memberships if parent membership type is changed which does not have relation type associated.
  CRM/Member/BAO/Membership.php
  tests/phpunit/CRM/Member/BAO/MembershipTest.php
Labels: has-test, master

#12177 [NFC] code changes for export with merge household
  CRM/Export/BAO/Export.php
  tests/phpunit/CRM/Export/BAO/ExportTest.php
Labels: master

#12021 More robust managed entity deletion
  CRM/Core/ManagedEntities.php
  tests/phpunit/CRM/Core/ManagedEntitiesTest.php
Labels: master

#12196 CRM-21632 - {membership.fee} prints out in documents with 9 decimal p…
  CRM/Utils/Token.php
Labels: merge on pass

#12201 dev/core#117 Replace usage of deprecated each() in Activity Summary R…
  CRM/Report/Form/ActivitySummary.php
Labels: master, merge on pass

#12202 dev/core#117 Replace deprecated each in CiviEvent Participant registr…
  CRM/Event/Form/Participant.php
Labels: master, merge on pass

#12199 dev/core#117 Replace deprecated each() function in CiviCase
  CRM/Case/XMLProcessor/Report.php
Labels: master

#12203 dev/core#38 Fix inappropriate limit on participant.getcount
  api/v3/utils.php
  tests/phpunit/api/v3/ParticipantTest.php
Labels: has-test, master

#11951 Adjust creation of markup for Open Flash Chart
  templates/CRM/common/openFlashChart.tpl
Labels: master, merge on pass

#12204 [NFC] test clean up.
  tests/phpunit/api/v3/ParticipantTest.php
Labels: master, merge on pass

#12208 dev/accessiblity#3 Add aria-label to datepicker element
  CRM/Core/Form.php
  js/Common.js
Labels: master

#12192 Further additional utility function for handling odd array structure
  CRM/Utils/Array.php
  tests/phpunit/CRM/Utils/ArrayTest.php
Labels: has-test, master

#12210 dev/core#117 Replace useage of deprecated each() in MembershpView
  CRM/Member/Form/MembershipView.php
Labels: master

#12174 Towards dev/financial/#16 Paypal unreliable getting payment processor type
  CRM/Core/Payment.php
  CRM/Core/Payment/PayPalImpl.php
Labels: master

#12219 dev/core#137 Fix Find Deleted Cases
  CRM/Case/Form/Search.php
Labels: 5.2, master

#12216 dev/core#128 Add deprecated warning helper function
  CRM/Contact/BAO/Contact/Location.php
  CRM/Contact/Form/Task/EmailCommon.php
  CRM/Contribute/BAO/ContributionRecur.php
  CRM/Core/Error.php
  CRM/Core/OptionGroup.php
  CRM/Core/PseudoConstant.php
  CRM/Member/BAO/MembershipType.php
  CRM/Report/Form.php
  CRM/Utils/Hook.php
Labels: master

#12214 dev/core#143 Contact 'World Region' Field not functioning properly in Search Builder
  templates/CRM/Contact/Form/Search/Builder.js
Labels: master

#12222 Fix re-delcare issue
  tests/phpunit/api/v3/ReportTemplateTest.php
Labels: master

#12206 [NFC] minor function tidy up - stop using $ids array
  CRM/Admin/Form/Options.php
  CRM/Core/OptionValue.php
  CRM/Report/Form/Register.php
Labels: master

#12215 CRM-21120 Add environment check for existence of mcrypt function
  CRM/Utils/Check/Component/Env.php
Labels: master

#11739 CRM-19948: Store Attachment uploader information
  CRM/Core/BAO/File.php
  CRM/Core/DAO/AllCoreTables.data.php
  CRM/Core/DAO/File.php
  CRM/Upgrade/Incremental/php/FiveThree.php
  api/v3/Attachment.php
  sql/civicrm_generated.mysql
  tests/phpunit/CRM/Dedupe/MergerTest.php
  tests/phpunit/api/v3/AttachmentTest.php
  xml/schema/Core/File.xml
Labels: has-test, master

#10909 CRM-21111 Refactor include/exclude activity types into it's own function and im…
  CRM/Activity/BAO/Activity.php
  CRM/Core/PseudoConstant.php
Labels: master, merge on pass

#12205 dev/core#139 Fail more gracefully on contribution detail report with invalid combination
  CRM/Report/Form/Contribute/Detail.php
Labels: master, merge on pass, sig:bug

#12232 dev/core#43 - [Update] to Update geocoding setting text to reflect need for Google API key
  api/v3/examples/Setting/GetFields.php
  settings/Map.setting.php
  templates/CRM/Admin/Form/Setting/Mapping.tpl
Labels: master

#12221 Add api testing / custom data support for MailingJob.
  CRM/Mailing/BAO/MailingJob.php
  api/v3/Mailing.php
  api/v3/MailingJob.php
  tests/phpunit/api/v3/MailingTest.php
  tests/phpunit/api/v3/SyntaxConformanceTest.php
Labels: master

#12212 Code cleanup on export
  CRM/Export/BAO/Export.php
  tests/phpunit/CRM/Export/BAO/ExportTest.php
Labels: master

#12229 Allow saving of new option value with value = 0.
  CRM/Admin/Form/Options.php
  CRM/Core/OptionValue.php
Labels: master

#12234 Change custom contact ref groups selector to use select2
  CRM/Custom/Form/Field.php
  templates/CRM/Custom/Form/Field.tpl
Labels: master

#11974 dev/core#61 Split Edit Message Templates Permission
  CRM/Admin/Form/MessageTemplates.php
  CRM/Admin/Page/MessageTemplates.php
  CRM/Core/Permission.php
  CRM/Core/xml/Menu/Admin.xml
  CRM/Upgrade/Incremental/php/FiveTwo.php
  templates/CRM/Admin/Page/MessageTemplates.tpl
Labels: master

#11672 CRM-21769: Show 'unsupported locale for parsing' warning only when enabling address parsing
  CRM/Admin/Form/Preferences/Address.php
  CRM/Core/BAO/Address.php
  CRM/Utils/Check/Component/AddressParsing.php
  tests/phpunit/CRM/Core/BAO/AddressTest.php
Labels: has-test, master

#12158 Accessibility #4: Make alerts accessible, Added new setting under misc.
  CRM/Admin/Form/Setting/Miscellaneous.php
  CRM/Core/Resources.php
  api/v3/examples/Setting/GetFields.php
  js/Common.js
  settings/Core.setting.php
  templates/CRM/Admin/Form/Setting/Miscellaneous.tpl
  templates/CRM/common/l10n.js.tpl
  templates/CRM/common/notifications.tpl
Labels: master

#12211 Preliminary tidy up on PriceSet form.
  CRM/Price/Form/Set.php
Labels: master
