Repository civicrm/civicrm-core, pull requests merged in 2018-04, with the labels that each got.

#11909 NFC Minor comments cleanup on MembershipType
  CRM/Member/Form/MembershipType.php
Labels: master, merge on pass

#11905 CRM-21244 Ensure consistancy with previous behavior where user emails …
  CRM/Core/BAO/Email.php
  tests/phpunit/CRM/Core/BAO/EmailTest.php
Labels: 5.0

#11906 (dev/mail/6) On multilingual mode, choosing mailing group doesn't affect recipient count and list
  CRM/Mailing/BAO/Mailing.php
Labels: 5.0

#11915 5.0
  CRM/Contact/Selector.php
  CRM/Core/BAO/Email.php
  CRM/Core/Task.php
  CRM/Export/Form/Select.php
  CRM/Mailing/BAO/Mailing.php
  ang/crmMailing/BlockReview.html
  ang/crmMailing/services.js
  templates/CRM/Export/Form/Select.tpl
  tests/phpunit/CRM/Core/BAO/EmailTest.php
Labels: master

#11914 CRM-21244 Update documetnation so it makes sense when setting is disabled
  CRM/Admin/Page/Options.php
  templates/CRM/Admin/Page/Options.tpl
  templates/CRM/Contact/Form/Task/Email.hlp
  templates/CRM/Contact/Form/Task/Email.tpl
Labels: 5.0

#11814 CRM-21677 - Report improvements
  CRM/Report/Form.php
  CRM/Report/Form/Contribute/Lybunt.php
  CRM/Report/Form/Contribute/RecurSummary.php
  CRM/Report/Form/Contribute/Summary.php
  CRM/Report/Form/Contribute/Sybunt.php
  CRM/Report/Form/Contribute/TopDonor.php
Labels: master

#11918 Extract fetchRelationshipDetails function
  CRM/Export/BAO/Export.php
Labels: master

#11919 Fix fatal on topDonor report
  CRM/Report/Form.php
  CRM/Report/Form/Contribute/TopDonor.php
  tests/phpunit/api/v3/ReportTemplateTest.php
Labels: 5.0

#11917 CRM-21831 & dev/report/issues/1 Fix regressions in contribution detail report relating to soft credits
  CRM/Report/Form/Contribute/Detail.php
Labels: 5.0, master

#11921 5.0 merge to master
  CRM/Admin/Page/Options.php
  CRM/Report/Form.php
  CRM/Report/Form/Contribute/Detail.php
  CRM/Report/Form/Contribute/TopDonor.php
  templates/CRM/Admin/Page/Options.tpl
  templates/CRM/Contact/Form/Task/Email.hlp
  templates/CRM/Contact/Form/Task/Email.tpl
  tests/phpunit/api/v3/ReportTemplateTest.php
Labels: master

#11885 Handle eq (equals) operator in the report url
  CRM/Report/Utils/Get.php
Labels: master

#11927 (NFC) make (includes taxes) translation work
  templates/CRM/Contribute/Form/Contribution/Main.tpl
  templates/CRM/Price/Form/PriceSet.tpl
Labels: master

#11928 Re Add CRM_Case_Form_Task::PreProcessCommon()
  CRM/Case/Form/Task.php
Labels: 5.0, master

#11929 5.0 merge to master
  CRM/Case/Form/Task.php
Labels: master

#11932 Core/8 - Fix fatal error on Print/Merge Document for cases
  CRM/Case/Form/Task.php
  CRM/Case/Form/Task/PDF.php
  CRM/Core/DAO.php
Labels: 5.0

#11933 5.0 to master
  CRM/Case/Form/Task.php
  CRM/Case/Form/Task/PDF.php
  CRM/Core/DAO.php
Labels: master

#11865 Fix Core/Dev 18# where logging fails if the AUTO INCREMENT column is …
  CRM/Logging/Schema.php
  tests/phpunit/CRM/Logging/SchemaTest.php
Labels: master

#11666 CRM-21753 add json validation for incoming criteria
  CRM/Contact/Page/DedupeFind.php
  CRM/Core/BAO/PrevNextCache.php
  CRM/Utils/Rule.php
  CRM/Utils/Type.php
  tests/phpunit/CRM/Utils/TypeTest.php
Labels: master

#11931 5.0.0 release notes
  CONTRIBUTORS.txt
  contributor-key.yml
  release-notes.md
  release-notes/5.0.0.md
Labels: 5.0, master

#11935 5.0 to master
  CONTRIBUTORS.txt
  contributor-key.yml
  release-notes.md
  release-notes/5.0.0.md
Labels: master

#11930 Phone: standardize appearance and translation of extension label
  templates/CRM/Contact/Form/Edit/Phone.tpl
  templates/CRM/Contact/Form/Inline/Phone.tpl
  templates/CRM/Event/Form/ManageEvent/Location.tpl
Labels: master

#11934 Fix fatal error when selecting a $0 price option in change fee selection
  CRM/Price/BAO/LineItem.php
Labels: master

#11940 5.0.0 release notes: last-minute change merged
  CONTRIBUTORS.txt
  contributor-key.yml
  release-notes/5.0.0.md
Labels: 5.0

#11941 5.0 to master
  CONTRIBUTORS.txt
  contributor-key.yml
  release-notes/5.0.0.md
Labels: master

#11924 (dev/mail/6) Fix recipient calculation when system has mixed records. Add multilingual test.
  CRM/Mailing/BAO/Mailing.php
  tests/phpunit/CRM/Mailing/BAO/MailingTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/api/v3/MultilingualTest.php
Labels: 5.0

#11942 5.0 merge to master
  CRM/Mailing/BAO/Mailing.php
  tests/phpunit/CRM/Mailing/BAO/MailingTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/api/v3/MultilingualTest.php
Labels: master

#11900 Simple function extraction on editing Address (within main contact edit)
  CRM/Contact/Form/Edit/Address.php
Labels: master

#11950 Extract custom data edit template code to shared template
  templates/CRM/Contribute/Form/Contribution.tpl
  templates/CRM/Custom/Form/Edit.tpl
Labels: master

#11957 dev/Core#53 Add in stats to AB tests and add in clickthrough and open…
  CRM/Mailing/BAO/Mailing.php
  ang/crmMailingAB/EditCtrl/report.html
  ang/crmMailingAB/ReportCtrl.js
  api/v3/Mailing.php
  templates/CRM/Mailing/Page/Report.tpl
  tests/phpunit/api/v3/MailingTest.php
Labels: merge on pass

#11959 [nfc] Consistently specify whether to clean money when calling from test suite
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/api/v3/ContactTest.php
  tests/phpunit/api/v3/ContributionTest.php
Labels: master

#11377 CRM-21523 add form rule for repetition fields in scheduled reminder form
  CRM/Admin/Form/ScheduleReminders.php
  templates/CRM/Admin/Form/ScheduleReminders.tpl
Labels: master, merge on pass

#11902 Fix template for widget
  templates/CRM/Contribute/Form/ContributionPage/Widget.tpl
Labels: master

#11958 Drupal8 loadBootStrap: fix user variable
  CRM/Utils/System/Drupal8.php
Labels: master, merge ready

#11961 CRM-21843 - Fix export of case activities
  CRM/Export/BAO/Export.php
Labels: master

#11954 Fix contribution detail report to work with FULL GROUP BY mode
  CRM/Report/Form.php
  CRM/Report/Form/Contribute/Detail.php
Labels: master

#10898 CRM-21100 Convert list of test groups into AJAX based select2 like r…
  CRM/Mailing/Info.php
  ang/crmMailing/BlockMailing.html
  ang/crmMailing/BlockPreview.html
  ang/crmMailing/BlockPreview.js
Labels: master

#11970 Fix API template
  templates/CRM/Admin/Page/APIExplorer.tpl
Labels: master

#11947 Add 'addToDeveloperTab' in more places to expose sql in use (permission limited)
  CRM/Logging/ReportSummary.php
Labels: master

#11965 CRM-21855 - Clean up and standardize relationshipType BAO
  CRM/Admin/Form/RelationshipType.php
  CRM/Contact/BAO/RelationshipType.php
  tests/phpunit/CRM/Contact/BAO/ContactType/RelationshipTest.php
Labels: master

#11657 CRM-19752 Fix slow query on contribution dash.
  CRM/Contribute/BAO/Contribution.php
Labels: master

#11658 CRM-21753 add pass-through support for criteria in urls on dedupe pages
  CRM/Contact/Form/Merge.php
  CRM/Contact/Page/AJAX.php
  CRM/Contact/Page/DedupeFind.php
  CRM/Contact/Page/DedupeMerge.php
  templates/CRM/Contact/Page/DedupeFind.tpl
Labels: master

#11953 Prevent hard-fail when section header / group by option chosen on logging report
  CRM/Report/Form/Contact/LoggingSummary.php
Labels: bug-fix, master

#11755 AllCoreTables - Generate file every time
  CRM/Core/CodeGen/Reflection.php
  CRM/Core/CodeGen/Util/Template.php
  CRM/Core/DAO/AllCoreTables.data.php
  xml/templates/listAll.tpl
Labels: master

#11978 CRM-20598 Phone ext in profile edit mode is messing up with address
  CRM/Contact/BAO/Contact.php
  tests/phpunit/CRM/Contact/BAO/ContactTest.php
Labels: master, merge on pass

#11887 CRM-21148 - Refactor two near-identical date functions into one
  CRM/Report/Form.php
  CRM/Utils/Date.php
  tests/phpunit/CRM/Report/FormTest.php
  tests/phpunit/CRM/Utils/DateTest.php
Labels: master

#11981 issue 63 clarify permission descriptions
  CRM/Core/Permission.php
Labels: master

#11982 E-notice fix
  CRM/Core/Payment/PayPalImpl.php
Labels: master

#11976 Fix failure to render dedupe page
  CRM/Contact/Page/DedupeFind.php
Labels: 5.1, master

#11973 dev/core#59 scheduled reminder email validation
  CRM/Admin/Form/ScheduleReminders.php
Labels: master

#11985 dev/core#48 Fix PDF Letter only generates a single letter when multiple contact IDs are specified
  CRM/Case/Form/Task/PDF.php
  CRM/Contact/Form/Task/EmailCommon.php
Labels: master, merge on pass

#11975 Fix failure to render dedupe page
  CRM/Contact/Page/DedupeFind.php
Labels: 5.0

#11988 translate strings
  CRM/Grant/BAO/Query.php
Labels: master

#11979 Fix select2 value updation for crmAddName Directive
  ang/crmCaseType.js
  tests/karma/unit/crmCaseTypeSpec.js
Labels: master

#11984 Fix trigger generation for modified_date on custom data
  CRM/Core/BAO/CustomGroup.php
  tests/phpunit/CRM/Logging/SchemaTest.php
Labels: 5.1, bug-fix, has-test

#11963 (dev/mail/8) Using ACL to restrict mailing recipients leads to fatal error
  CRM/Contact/BAO/Contact/Permission.php
  CRM/Mailing/BAO/Mailing.php
  tests/phpunit/CRM/Mailing/BAO/MailingTest.php
Labels: 5.1, bug-fix

#11995 Fix intermittant test bug
  tests/phpunit/CRM/Contact/BAO/ContactTest.php
Labels: master, merge on pass

#11853 CRM-21849: Inline Relationship Type Edit
  CRM/Contact/BAO/Relationship.php
  CRM/Contact/Form/Relationship.php
  CRM/Core/Form.php
  api/v3/Generic.php
  api/v3/Relationship.php
  js/crm.optionEdit.js
  templates/CRM/Contact/Form/Relationship.tpl
  templates/CRM/common/enableDisableApi.tpl
  tests/phpunit/CRM/Contact/BAO/RelationshipTest.php
Labels: has-test, master

#11986 Namespace exception in test
  Civi/Test/Api3TestTrait.php
Labels: master

#11991 VersionCheck - Get more nuanced messages from latest.civicrm.org
  CRM/Utils/Check/Component/Env.php
  CRM/Utils/VersionCheck.php
  tests/phpunit/CRM/Utils/versionCheckTest.php
Labels: 5.1

#11992 Fix the contact merge form on Drupal 8
  CRM/Contact/Form/Merge.php
  CRM/Utils/System/Drupal8.php
  CRM/Utils/System/Joomla.php
Labels: master

#12001 core/issues/64 - In custom searches, column headings are being ignored
  CRM/Contact/StateMachine/Search.php
Labels: master

#12005 core/issues/64 - In custom searches, column headings are being ignored
  CRM/Contact/StateMachine/Search.php
Labels: 5.1

#11967 dev/translation#9 Create API Action to rebuild Multilingual Schema
  api/v3/System.php
Labels: master

#11993 Standardise Address code in Contact summary report & enable links
  CRM/Report/Form.php
  CRM/Report/Form/Contact/Summary.php
Labels: master

#11972 CRM-19885 / dev/core/issues/36 fix fatal error on scheduled reminders due to no default
  CRM/Upgrade/Incremental/sql/5.2.alpha1.mysql.tpl
  xml/schema/Core/ActionSchedule.xml
Labels: bug-fix, master

#11990 Add New API Call To Get All Unique Fields For Given Entity
  api/v3/Generic/Getunique.php
  tests/phpunit/api/v3/ContactTest.php
  tests/phpunit/api/v3/ContributionTest.php
Labels: master

#12008 footer.tpl - Change the URL formula pointing to the release notes
  templates/CRM/common/footer.tpl
Labels: 5.1

#12018 5.1
  templates/CRM/common/footer.tpl
Labels: master

#12014 dev/core#65 Fix issue where source for participant could be entered w…
  CRM/Event/DAO/Participant.php
  CRM/Event/Form/Participant.php
  xml/schema/Event/Participant.xml
Labels: master

#12017 Improve input handling in get-cases AJAX API
  CRM/Case/Page/AJAX.php
Labels: master

#12010 (dev/core/issues/70) On any custom search 'Print selected rows' action doesn't retain columns/values
  CRM/Contact/Form/Task/Print.php
  CRM/Contact/Selector/Custom.php
  templates/CRM/Contact/Form/Task/Print.tpl
Labels: master

#12023 Add missing case type tests
  ang/crmCaseType.js
  tests/karma/unit/crmCaseTypeSpec.js
Labels: master, merge on pass

#12009 Translate strings in "Report" UI, et al
  CRM/Case/Form/Case.php
  CRM/Grant/BAO/Query.php
  CRM/Price/Page/Set.php
  CRM/Profile/Form.php
  CRM/Report/Form/Contact/Relationship.php
  CRM/Report/Form/Contribute/Summary.php
  CRM/Report/Form/Contribute/Sybunt.php
  CRM/Report/Form/Event/IncomeCountSummary.php
  CRM/Report/Form/Event/Summary.php
  CRM/Report/Form/Mailing/Bounce.php
  CRM/Report/Form/Mailing/Clicks.php
  CRM/Report/Form/Mailing/Detail.php
  CRM/Report/Form/Member/Summary.php
Labels: master

#12028 Fix release notes for 5.0.x
  CRM/Upgrade/Incremental/sql/5.0.2.mysql.tpl
  release-notes/5.0.1.md
  release-notes/5.0.2.md
  sql/civicrm_generated.mysql
  templates/CRM/common/footer.tpl
  xml/version.xml
Labels: 5.0, merge on pass

#12031 Move help section outside the container
  templates/CRM/Contact/Form/DedupeFind.tpl
Labels: master

#10695 CRM-20879: Extend self-service event registration transfer to backend
  CRM/Event/Form/ParticipantView.php
  CRM/Event/Form/SelfSvcTransfer.php
  CRM/Event/Form/SelfSvcUpdate.php
  CRM/Event/Selector/Search.php
  templates/CRM/Event/Form/ParticipantView.tpl
  templates/CRM/Event/Form/SelfSvcTransfer.tpl
Labels: master

#12034 Flush versionCheck cache when upgrading
  CRM/Upgrade/Form.php
  CRM/Utils/VersionCheck.php
Labels: 5.1

#12020 core/issues/73 - Add invoice number to bookkeeping report
  CRM/Report/Form/Contribute/Bookkeeping.php
Labels: master

#12027 core/issues/75 - warning message after an activity is created
  settings/Core.setting.php
Labels: master

#12039 Remove usage of deprecated paymentProcessorType function
  CRM/Contribute/Form/ContributionPage/Amount.php
  CRM/Financial/BAO/PaymentProcessor.php
  CRM/Utils/VersionCheck.php
Labels: master, merge on pass

#12046 [NFC] Add metadata to describe personal note field
  CRM/Contribute/DAO/ContributionSoft.php
  CRM/PCP/BAO/PCP.php
  xml/schema/Contribute/ContributionSoft.xml
Labels: master, merge on pass

#12047 Dev/Core#90 Apply disabling Full Group By to reports
  CRM/Report/Form.php
  CRM/Report/Form/Contribute/Lybunt.php
  CRM/Report/Form/Contribute/SoftCredit.php
  CRM/Report/Form/Mailing/Opened.php
Labels: master, merge on pass

#12045 Fix regression whereby relationship types option no longer in adv search
  CRM/Contact/Form/Search.php
  CRM/Contact/Form/Search/Criteria.php
  templates/CRM/Contact/Form/Search/AdvancedCriteria.tpl
Labels: 5.1, merge on pass

#12048 Add unit test to event batch update (includes function extraction to support this)
  CRM/Event/Form/Task/Batch.php
  tests/phpunit/CRM/Event/Form/Task/BatchTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: master, merge on pass

#12037 dev/core#86 Notify admin when testing email if CIVICRM_MAIL_LOG_AND_SEND is set
  CRM/Admin/Form/Setting/Smtp.php
  templates/CRM/common/civicrm.settings.php.template
Labels: master, merge on pass

#12051 Fix: Batch update participants with checkboxes fails
  CRM/Activity/Form/Task/Batch.php
  CRM/Case/Form/Task/Batch.php
  CRM/Contact/Form/Task/Batch.php
  CRM/Contribute/Form/Task/Batch.php
  CRM/Event/Form/Task/Batch.php
  CRM/Member/Form/Task/Batch.php
  tests/phpunit/CRM/Event/Form/Task/BatchTest.php
Labels: master

#12054 Remove unused code in CRM_Contribute_Form_ContributionPage_Amount::formRule
  CRM/Contribute/Form/ContributionPage/Amount.php
Labels: master, merge on pass

#10946 CRM-21037 activity sendsms unittests
  CRM/Activity/BAO/Activity.php
  CRM/SMS/Provider.php
  CRM/Utils/Token.php
  tests/phpunit/CRM/Activity/BAO/ActivityTest.php
  tests/phpunit/CRM/SMS/ProviderTest.php
  tests/phpunit/CiviTest/CiviTestSMSProvider.php
Labels: has-test, master

#12049 CRM-20459: Actively deprecate CRM_Core_OptionGroup::getValue[Sub PR 1]
  CRM/Badge/BAO/Layout.php
  CRM/Campaign/BAO/Petition.php
  CRM/Campaign/BAO/Survey.php
  CRM/Campaign/Form/Survey/Results.php
  CRM/Case/BAO/Case.php
  CRM/Case/Form/Activity/ChangeCaseStartDate.php
  CRM/Case/Form/Activity/ChangeCaseStatus.php
  CRM/Case/Form/Activity/ChangeCaseType.php
  CRM/Contribute/BAO/ContributionSoft.php
Labels: master, merge on pass

#12019 core/issues/72 fix payflow bug for amount
  CRM/Core/Payment/PayflowPro.php
Labels: master

#12030 core/issues/78 - Incorrect Payment Processor for Recurring Payments
  CRM/Core/Payment/AuthorizeNetIPN.php
  tests/phpunit/CRM/Core/Payment/AuthorizeNetIPNTest.php
Labels: merge on pass

#12060 Mark Accent String Tests as incomplete if on a database that is not utf8
  CRM/Utils/SQL.php
  tests/phpunit/api/v3/ContactTest.php
Labels: master, merge on pass

#12059 Fix for check number no longer exposed dev/core/issues/60
  CRM/Event/Form/EventFees.php
  templates/CRM/Event/Form/EventFees.tpl
Labels: master, sig:bug

#12062 [NFC] FIx indenting in eventFees template
  templates/CRM/Event/Form/EventFees.tpl
Labels: master, merge on pass
