Repository civicrm/civicrm-core, pull requests merged in 2018-09, with the labels that each got.

#12694 Deduplicate setting of mailSent message
  CRM/Member/Form.php
  CRM/Member/Form/Membership.php
  tests/phpunit/CRM/Member/Form/MembershipTest.php
Labels: master, merge on pass

#12756 infrastructure/ops#842 Fix Getting Started and Blog dashlets caching.
  CRM/Dashlet/Page/Blog.php
  CRM/Dashlet/Page/GettingStarted.php
Labels: 5.5

#12759 5.5 to master
  CRM/Dashlet/Page/Blog.php
  CRM/Dashlet/Page/GettingStarted.php
Labels: master

#12763 5.5
  CRM/Report/Form.php
Labels: 5.5, merge on pass

#12766 dev/core#326: Fix for fatal error in section headers.
  CRM/Report/Form/Contribute/Detail.php
  tests/phpunit/api/v3/ReportTemplateTest.php
Labels: 5.5

#12786 CRM_Utils_StringTest - Fix false-negative on systems with non-standard HTTP port
  tests/phpunit/CRM/Utils/StringTest.php
Labels: merge on pass

#12707 fixing batch search by payment method
  CRM/Batch/BAO/Batch.php
  CRM/Financial/Form/BatchTransaction.php
  tests/phpunit/CRM/Batch/BAO/BatchTest.php
Labels: master

#12805 v5.5.1 - Bump number. Draft release notes.
  CRM/Upgrade/Incremental/sql/5.5.1.mysql.tpl
  release-notes/5.5.1.md
  sql/civicrm_generated.mysql
  xml/version.xml
Labels: 5.5

#12803 Handle smart groups created in previous Civi's which include relation_permission
  CRM/Contact/BAO/Query.php
Labels: 5.5

#12799 Display tables correctly on import wizard/membership dashboard when using drupal bootstrap based theme
  templates/CRM/Activity/Import/Form/Preview.tpl
  templates/CRM/Activity/Import/Form/Summary.tpl
  templates/CRM/Contact/Import/Form/Preview.tpl
  templates/CRM/Contact/Import/Form/Summary.tpl
  templates/CRM/Contribute/Import/Form/Preview.tpl
  templates/CRM/Contribute/Import/Form/Summary.tpl
  templates/CRM/Event/Import/Form/Preview.tpl
  templates/CRM/Event/Import/Form/Summary.tpl
  templates/CRM/Member/Import/Form/Preview.tpl
  templates/CRM/Member/Import/Form/Summary.tpl
  templates/CRM/Member/Page/DashBoard.tpl
Labels: master, merge on pass, sig:extension support

#12798 Rename variable in MembershipRenewal form to make a merge with Membership form in future easier
  CRM/Member/Form/MembershipRenewal.php
Labels: master, merge on pass, sig:code maintenance readability testability

#12794 Just a test.
  tests/phpunit/CRM/Member/Form/MembershipRenewalTest.php
Labels: has-test, master, merge on pass

#12781 Allow to specify template_id on URL when creating a new event
  CRM/Event/Form/ManageEvent/EventInfo.php
Labels: master, merge on pass

#12721 Allow descriptions for payment fields
  CRM/Core/Payment.php
  CRM/Core/Payment/Form.php
  templates/CRM/Core/BillingBlock.tpl
Labels: master, merge on pass

#12746 Convert RecurringEntity form to datepicker
  CRM/Core/Form/RecurringEntity.php
  templates/CRM/Core/Form/RecurringEntity.tpl
Labels: master, merge on pass

#12778 dev/core#379 Activity View: only nl2br Inbound Email.
  templates/CRM/Activity/Form/Activity.tpl
Labels: master, merge on pass

#12771 Switch grant form to use crmDatepicker instead of jCalendar
  CRM/Grant/Form/Grant.php
  templates/CRM/Grant/Form/Grant.tpl
Labels: master, merge on pass

#12770 NFC: Rename variable in RecurringEntityPreview
  CRM/Core/Page/RecurringEntityPreview.php
Labels: master, merge on pass

#12808 closes reporting#6 - can't sort by Street Name
  CRM/Report/Form.php
Labels: master

#12809 Report Template test for SelectWhere - add test
  tests/phpunit/api/v3/ReportTemplateTest.php
Labels: master, merge on pass

#12815 Alter Test to ensure that order of city is output doesn't mater in th…
  tests/phpunit/CRM/Report/Form/ActivityTest.php
Labels: master, merge on pass

#12772 Fixes to Contact Detail report
  CRM/Report/Form/Contact/Detail.php
  tests/phpunit/api/v3/ReportTemplateTest.php
Labels: master, merge on pass, sig:extension support

#12776 Convert "Info and Settings" tab on ManageEvent to use datepicker
  CRM/Event/Form/ManageEvent/EventInfo.php
  templates/CRM/Event/Form/ManageEvent/EventInfo.tpl
Labels: master, merge on pass

#12762 Add new paymentprocessor supportsX methods to replace remaining isSupported methods
  CRM/Contribute/Form/UpdateBilling.php
  CRM/Contribute/Form/UpdateSubscription.php
  CRM/Core/Payment.php
  CRM/Member/Page/Tab.php
Labels: master

#12768 Don't show 'Register Participant' on the manage events page if the logged in user does not have 'Edit Event Participants' permission
  CRM/Event/Page/ManageEvent.php
  templates/CRM/Event/Page/ManageEvent.tpl
Labels: master, merge on pass

#12825 Fix api profile.submit to work with tag & note fields
  api/v3/EntityTag.php
  api/v3/Profile.php
  tests/phpunit/api/v3/ProfileTest.php
Labels: master

#12734 Remove duplicate payment processor select on Membership Renewal form
  templates/CRM/Member/Form/MembershipRenewal.tpl
Labels: master

#12827 Better title for note field
  CRM/Contact/BAO/Contact.php
Labels: master, merge on pass

#12832 groupContact BAO - standardize add function
  CRM/Contact/BAO/GroupContact.php
Labels: 5.6, merge on pass

#12830 Allow profile.submit api for tags
  api/v3/EntityTag.php
  api/v3/Profile.php
  tests/phpunit/api/v3/ProfileTest.php
Labels: 5.6, merge on pass

#12838 NFC: fix grammar/punctuation in help
  templates/CRM/Admin/Form/Preferences/Display.hlp
Labels: master

#12837 Fix html wrapper on basic summary block
  templates/CRM/Contact/Page/Inline/Basic.tpl
  templates/CRM/Contact/Page/View/Summary.tpl
Labels: 5.6

#12774 Cleanup pledge form to use datepicker
  CRM/Core/Form/Renderer.php
  CRM/Core/Resources.php
  CRM/Pledge/Form/Pledge.php
  js/crm.datepicker.js
  templates/CRM/Pledge/Form/Pledge.tpl
Labels: master

#12842 (dev/core#107) Fix regression which prevents editing CiviCase configuration
  CRM/Upgrade/Incremental/php/FiveFive.php
  CRM/Upgrade/Incremental/sql/5.5.2.mysql.tpl
  sql/civicrm_generated.mysql
  xml/templates/civicrm_data.tpl
  xml/version.xml
Labels: 5.5, merge on pass

#12844 (dev/core#107) Fix regression which prevents editing CiviCase configuration
  CRM/Upgrade/Incremental/php/FiveSix.php
  CRM/Upgrade/Incremental/sql/5.6.beta2.mysql.tpl
  sql/civicrm_generated.mysql
  xml/templates/civicrm_data.tpl
  xml/version.xml
Labels: 5.6

#12846 [NFC] Add unit test to cover component ACLs.
  CRM/Activity/BAO/Activity.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/api/v3/ACLPermissionTest.php
  tests/phpunit/api/v3/ActivityTest.php
Labels: master, merge on pass

#12748 dev/core#370: No new tasks and documents get added to workflow
  ang/crmCaseType.js
Labels: master

#12773 Use cached function for financialAccount retrieval.
  CRM/Contribute/BAO/Contribution.php
  CRM/Contribute/PseudoConstant.php
  CRM/Core/BAO/FinancialTrxn.php
  CRM/Financial/BAO/FinancialAccount.php
  CRM/Financial/BAO/FinancialItem.php
  CRM/Financial/BAO/FinancialTypeAccount.php
  tests/phpunit/CRM/Contribute/PseudoConstantTest.php
Labels: master, merge on pass

#12800 Improve display of relationships tab
  templates/CRM/Contact/Page/View/Relationship.tpl
Labels: master

#12856 dev/core#281 Fix invoice number in message template
  CRM/Upgrade/Incremental/MessageTemplates.php
  xml/templates/message_templates/contribution_invoice_receipt_html.tpl
Labels: merge on pass

#12847 Add span to amount label in Confirm.tpl
  templates/CRM/Contribute/Form/Contribution/Confirm.tpl
Labels: sig:extension support

#12861 Fix typo in 5.5 upgrade script
  CRM/Upgrade/Incremental/sql/5.5.3.mysql.tpl
Labels: 5.6

#12672 Export code improvement
  CRM/Export/BAO/Export.php
Labels: master

#12728 Renamed Mailing Component entity
  CRM/Admin/Page/AJAX.php
  CRM/Core/DAO/AllCoreTables.data.php
  CRM/Core/DAO/Component.php
  CRM/Mailing/BAO/Component.php
  CRM/Mailing/BAO/Mailing.php
  CRM/Mailing/BAO/MailingComponent.php
  CRM/Mailing/DAO/Mailing.php
  CRM/Mailing/DAO/MailingComponent.php
  CRM/Mailing/Event/BAO/Confirm.php
  CRM/Mailing/Event/BAO/Reply.php
  CRM/Mailing/Event/BAO/Resubscribe.php
  CRM/Mailing/Event/BAO/Subscribe.php
  CRM/Mailing/Event/BAO/Unsubscribe.php
  CRM/Mailing/Form/Component.php
  CRM/Mailing/Page/Component.php
  CRM/Mailing/PseudoConstant.php
  api/v3/MailingComponent.php
  api/v3/utils.php
  tests/phpunit/CRM/Core/PseudoConstantTest.php
  tests/phpunit/api/v3/SyntaxConformanceTest.php
  xml/schema/Core/Component.xml
  xml/schema/Mailing/Component.xml
Labels: master, merge on pass

#12833 dev/399 Fix saving of relationship permissions when relationship is b_a on form
  CRM/Contact/Form/Relationship.php
  templates/CRM/Contact/Form/Relationship.tpl
Labels: 5.6, merge on pass

#12866 5.5.3 - Set version; add release notes; add more data-cleanup
  CRM/Upgrade/Incremental/sql/5.5.3.mysql.tpl
  release-notes/5.5.3.md
  sql/civicrm_generated.mysql
  xml/version.xml
Labels: merge on pass

#12855 dev/core#391 - Fix saving tags in profile
  CRM/Contact/BAO/Contact.php
Labels: 5.6, merge on pass

#12870 dev/core#391 - Fix saving tags in profile (5.5 backport)
  CRM/Contact/BAO/Contact.php
Labels: merge on pass

#12874 dev/core#410 Ensure that Email related fields in Scheduled Reminders …
  CRM/Admin/Form/ScheduleReminders.php
Labels: master

#12790 dev/core#362 fix search functionality of contact reference fields in On Behalf Profiles
  CRM/Core/BAO/CustomField.php
  templates/CRM/Custom/Form/ContactReference.tpl
Labels: master, sig:bug

#12877 Regenerate MailingComponent DAO file to reflect recent changes
  CRM/Mailing/DAO/MailingComponent.php
Labels: merge on pass

#12878 Add icons to top-level navigation menu
  CRM/Upgrade/Incremental/sql/5.7.alpha1.mysql.tpl
  sql/civicrm_generated.mysql
  xml/templates/civicrm_navigation.tpl
Labels: merge on pass

#12879 (DX) Civi::contactSettings - Add a facade for working with the logged-in user's settings
  CRM/Activity/Form/ActivityFilter.php
  CRM/Activity/Page/AJAX.php
  Civi.php
  Civi/Core/SettingsManager.php
  tests/phpunit/Civi/Core/CiviFacadeTest.php
Labels: merge on pass

#12876 Don't mess up fragment links in nav menu
  CRM/Core/BAO/Navigation.php
Labels: master
