Repository civicrm/civicrm-core, pull requests merged in 2018-07, with the labels that each got.

#12380 (dev/core#174) Memcache(d) - Updates to comply with PSR-16
  CRM/Utils/Cache/Memcache.php
  CRM/Utils/Cache/Memcached.php
Labels: master

#12381 (dev/core#174) APCcache - Updates to comply with PSR-16
  CRM/Utils/Cache/APCcache.php
  tests/phpunit/E2E/Cache/APCcacheTest.php
Labels: master

#12356 dev/core/issues/202, check if default currency is set
  CRM/Core/Form.php
Labels: master

#12365 dev/financial/issues/24, Add unit test for Link payment method to financial account when created using api
  tests/phpunit/api/v3/OptionValueTest.php
Labels: master

#12382 Fix mis-reporting of false booleans in reports
  CRM/Report/Form.php
Labels: 5.3

#12383 5.3 to master
  CRM/Report/Form.php
Labels: master

#12345 dev/core#195 Add Contribution Counts to Sub-tabs
  templates/CRM/Contribute/Page/Tab.tpl
Labels: master, sig:user interfacing improvement

#12305 Re-instate Dedupe limit functionality & fix select toggle functionality
  CRM/Contact/Page/AJAX.php
  CRM/Contact/Page/DedupeFind.php
  CRM/Dedupe/Finder.php
  CRM/Dedupe/Merger.php
  templates/CRM/Contact/Page/DedupeFind.tpl
Labels: 5.3, sig:bug

#12386 NFC code cleanup for AuthNet, Paypal, PaypalPro IPNs
  CRM/Core/Payment/AuthorizeNetIPN.php
  CRM/Core/Payment/PayPalIPN.php
  CRM/Core/Payment/PayPalProIPN.php
Labels: master, merge on pass

#12379 (dev/core#174) Full PSR-16 compliance for SqlGroup
  CRM/Core/BAO/Cache.php
  CRM/Utils/Cache/SqlGroup.php
  api/v3/Job.php
  tests/phpunit/CRM/Utils/Cache/SqlGroupTest.php
  tests/phpunit/E2E/Cache/SqlGroupTest.php
Labels: master, sig:code maintenance readability testability

#12390 (dev/core#220) State province/country doesn't show properly in the…
  CRM/Report/Form/Contribute/History.php
Labels: merge on pass

#12340 Move DAO function to DAO class, call it from Merge class
  CRM/Core/DAO.php
  CRM/Dedupe/Merger.php
  CRM/Logging/Schema.php
Labels: master, sig:code maintenance readability testability

#12389 (dev/core#174) Add test to prevent hidden interactions among caches
  tests/phpunit/E2E/Cache/ConfiguredMemoryTest.php
  tests/phpunit/E2E/Cache/TwoInstancesTest.php
Labels: master, merge on pass

#12394 (dev/core#223) Expose prefix and suffix in reports
  CRM/Report/Form.php
Labels: master

#12400 dev/core#227 Fix issue where on some extened groups the multiple reco…
  CRM/Core/BAO/CustomGroup.php
  tests/phpunit/api/v3/CustomGroupTest.php
Labels: 5.3, merge on pass

#12391 Revert change to BillingBlock to support hidden fields.
  CRM/Core/Payment.php
  templates/CRM/Core/BillingBlock.tpl
Labels: master

#12362 (dev/core#174) Forms/Sessions - Store state via Civi::cache('session')
  CRM/Admin/Form/Setting.php
  CRM/Admin/Form/Setting/UpdateConfigBackend.php
  CRM/Core/BAO/Cache.php
  CRM/Core/BAO/ConfigSetting.php
  CRM/Core/Config.php
  CRM/Core/Session.php
  Civi/Core/Container.php
Labels: master, merge ready

#12399 dev/core/#/229 Fix fatal error on send test mail
  api/v3/Mailing.php
  tests/phpunit/api/v3/MailingTest.php
Labels: 5.3, master, merge on pass

#12408 Add location_id if missing CRM-20711.
  CRM/Upgrade/Incremental/php/FiveFour.php
Labels: master, merge on pass

#12296 Use email_greeting where possible in receipts
  CRM/Upgrade/Incremental/MessageTemplates.php
  xml/templates/message_templates/contribution_online_receipt_html.tpl
  xml/templates/message_templates/contribution_online_receipt_text.tpl
  xml/templates/message_templates/event_online_receipt_html.tpl
  xml/templates/message_templates/event_online_receipt_text.tpl
  xml/templates/message_templates/membership_online_receipt_html.tpl
  xml/templates/message_templates/membership_online_receipt_text.tpl
Labels: master, sig:user interfacing improvement

#12233 dev/core#155 Improve Option Groups form
  CRM/Admin/Form/OptionGroup.php
  templates/CRM/Admin/Page/OptionGroup.tpl
Labels: master, sig:user interfacing improvement

#12409 dev/core/issues/211 Fix mis-allocation of financial transactions when editing payment method on a completed payment
  CRM/Financial/Form/PaymentEdit.php
  tests/phpunit/CRM/Financial/Form/PaymentEditTest.php
Labels: 5.3, merge on pass

#12403 5.3
  CRM/Contact/Page/AJAX.php
  CRM/Contact/Page/DedupeFind.php
  CRM/Core/BAO/CustomGroup.php
  CRM/Dedupe/Finder.php
  CRM/Dedupe/Merger.php
  CRM/Financial/Form/PaymentEdit.php
  api/v3/Mailing.php
  contributor-key.yml
  release-notes.md
  release-notes/5.2.1.md
  release-notes/5.2.2.md
  release-notes/5.3.0.md
  templates/CRM/Contact/Page/DedupeFind.tpl
  tests/phpunit/CRM/Financial/Form/PaymentEditTest.php
  tests/phpunit/api/v3/CustomGroupTest.php
  tests/phpunit/api/v3/MailingTest.php
Labels: master

#12411 Fix sample custom data is_reserved=0
  sql/civicrm_sample_custom_data.mysql
Labels: master, merge on pass

#11998 dev/core#107: Add default assignee when creating cases
  CRM/Case/XMLProcessor/Process.php
  CRM/Core/BAO/OptionValue.php
  CRM/Upgrade/Incremental/php/FiveFour.php
  ang/crmCaseType.js
  ang/crmCaseType/timelineTable.html
  tests/karma/unit/crmCaseTypeSpec.js
  tests/phpunit/CRM/Case/XMLProcessor/ProcessTest.php
  tests/phpunit/CRM/Core/BAO/OptionValueTest.php
Labels: master, sig:user interfacing improvement

#12419 Ensure that the .mysql.tpl file is run for 5.3.alpha1
  CRM/Upgrade/Incremental/php/FiveThree.php
Labels: 5.3, merge on pass

#12420 dev/core#234 Move all steps from 5.3.alpha1.mysql.tpl to 5.3.0.mysql.tpl due to upgrade issues
  CRM/Upgrade/Incremental/sql/5.3.0.mysql.tpl
  CRM/Upgrade/Incremental/sql/5.3.alpha1.mysql.tpl
Labels: 5.3

#12418 CRM_Core_BAO_PrevNextCache - Remove unused buildSelectedContactPager()
  CRM/Core/BAO/PrevNextCache.php
Labels: master, merge on pass, sig:code maintenance readability testability

#12414 Simplify input params on OptionValue::addOptionValue
  CRM/Admin/Form/Options.php
  CRM/Campaign/Form/SurveyType.php
  CRM/Core/OptionValue.php
  CRM/Report/Form/Register.php
  api/v3/ActivityType.php
Labels: master

#12412 Enable syntaxConformance on entities that now succeed
  tests/phpunit/api/v3/SyntaxConformanceTest.php
Labels: master

#12425 Ensure db updates are run for 5.3.alpha1
  CRM/Upgrade/Incremental/php/FiveThree.php
Labels: 5.4, merge on pass

#12426 Change default for CIVICRM_CONTAINER_CACHE to simplify admin/developer experience
  Civi/Core/Container.php
Labels: 5.4, merge on pass

#12417 Follow up to PR 12160 to update the DB version of the templates
  CRM/Upgrade/Incremental/MessageTemplates.php
Labels: 5.4, master, merge on pass

#12428 5.4
  CRM/Upgrade/Incremental/MessageTemplates.php
  CRM/Upgrade/Incremental/php/FiveThree.php
  Civi/Core/Container.php
Labels: master

#12427 (dev/core#174) CRM_Utils_Cache_SqlGroup - Refine trivial TTL handling to stabilize tests
  CRM/Utils/Cache/SqlGroup.php
Labels: master

#12429 [NFC] Update comment link
  CRM/Core/PseudoConstant.php
Labels: master

#12422 dev/core#176 Odd / Even street number sort column missing from Reports
  CRM/Report/Form.php
  CRM/Report/Form/Walklist/Walklist.php
  tests/phpunit/CRM/Report/Form/ContactSummaryTest.php
Labels: has-test, master

#12430 dev/core#239 : Fix title dialog box on hovering form element on Event's configuration backend form
  templates/CRM/Event/Form/ManageEvent/Registration.hlp
Labels: master

#12438 (dev/core#217) CRM_Contact_Selector::getRows() - Use generator instead of DAO loop
  CRM/Contact/Selector.php
  CRM/Core/DAO.php
  tests/phpunit/CRM/Core/DAOTest.php
Labels: master

#12443 Fix potential undefined array index
  CRM/Core/BAO/UFField.php
Labels: master

#12442 Remove old deprecated crmeditable.tpl
  templates/CRM/common/crmeditable.tpl
Labels: master

#12384 dev/core#218 : On Case Type listing page, for reserved ones the, 'More' link don't show any options
  ang/crmCaseType/list.html
Labels: master

#12447 dev/core#249 Fix crash when performing export all contacts from search
  CRM/Contact/Form/Task.php
Labels: 5.4, master, merge ready

#12373 dev/accessibility#3: Add accessible label on Contact Edit form elements and helpicon
  CRM/Contact/Form/Edit/Email.php
  CRM/Contact/Form/Edit/IM.php
  CRM/Contact/Form/Edit/Phone.php
  CRM/Contact/Form/Edit/Website.php
  CRM/Core/Smarty/plugins/function.help.php
  js/model/crm.uf.js
Labels: master, sig:accessibility

#12410 dev/core/issues/228 fix OptionGroup create action to not disable on update
  CRM/Core/BAO/OptionGroup.php
  CRM/Upgrade/Incremental/sql/5.5.alpha1.mysql.tpl
  xml/schema/Core/OptionGroup.xml
Labels: master

#12448 5.4
  CRM/Contact/Form/Task.php
Labels: master

#12392 dev/core#221, check if the grouptree is not empty
  CRM/Custom/Form/Preview.php
Labels: master

#12450 [NFC] Comment fixes
  CRM/Contribute/BAO/ManagePremiums.php
  CRM/Financial/BAO/FinancialType.php
Labels: master, merge on pass

#12451 Deprecate array on ManagePremiums
  CRM/Contribute/BAO/ManagePremiums.php
Labels: master

#12458 PriceField: show pre/post help if not empty, not if isset.
  CRM/Price/BAO/PriceField.php
Labels: master

#12436 dev/core#241 Fix Manage Premiums UI
  CRM/Contribute/BAO/Premium.php
  CRM/Contribute/Page/ManagePremiums.php
  CRM/Contribute/Page/Premium.php
  CRM/Financial/DAO/FinancialType.php
  api/v3/FinancialType.php
  templates/CRM/Contribute/Form/ContributionPage/AddProduct.hlp
  templates/CRM/Contribute/Form/ContributionPage/AddProduct.tpl
  templates/CRM/Contribute/Page/ManagePremiums.tpl
  templates/CRM/Contribute/Page/Premium.tpl
  xml/schema/Financial/FinancialType.xml
Labels: master

#12449 CustomValue gettree api - More accurate permission check
  CRM/Core/Permission.php
  api/v3/CustomValue.php
Labels: master

#12346 dev/mail/15 deal better with spaces in from email address
  CRM/Admin/Form/Options.php
  ang/crmMailing/services.js
  tests/phpunit/CRM/Core/OptionGroupTest.php
Labels: master, merge on pass, sig:bug

#11838 CiviMail: Fix logic for handling SMTP socket errors, temporary failures and permanent failures
  CRM/Mailing/BAO/MailingJob.php
  tests/phpunit/CRM/Mailing/BAO/MailingJobTest.php
Labels: has-test, master

#10673 CRM-20845: create alterMailingRecipients hook
  CRM/Mailing/BAO/Mailing.php
  CRM/Utils/Hook.php
  CRM/Utils/SQL/Select.php
  tests/phpunit/CRM/Mailing/BAO/MailingTest.php
Labels: has-test, master, sig:extension support

#12456 Issue #93 Update CRM_Utils_Rule::mysqlOrderBy() to accommodate more than 2 joins
  CRM/Utils/Rule.php
Labels: master, merge on pass

#12290 Export class code readability - Reduce passing of variable, define on class
  CRM/Export/BAO/Export.php
  tests/phpunit/CRM/Export/BAO/ExportTest.php
Labels: master, sig:code maintenance readability testability

#12320 Non functional changes towards shared functions in Core_Form_Task
  CRM/Case/Form/Task.php
  CRM/Contact/Form/Task.php
  CRM/Core/Form/Task.php
  CRM/Export/Form/Select.php
Labels: master

#12465 dev/core#256 - use unsigned int for temporary recipient ids
  CRM/Mailing/BAO/Recipients.php
Labels: master

#12472 Remove unused variables & comment cleanup
  CRM/Contribute/Form/ContributionPage/AddProduct.php
  CRM/Core/BAO/FinancialTrxn.php
  CRM/Financial/BAO/FinancialItem.php
Labels: master, merge on pass

#12461 Make domain_id optional in membership_type api.
  api/v3/MembershipType.php
  tests/phpunit/api/v3/MembershipTypeTest.php
Labels: master, sig:extension support

#12312 Disable inline-edit of multi-record custom fields in profiles
  CRM/Profile/Page/MultipleRecordFieldsListing.php
  templates/CRM/Profile/Page/MultipleRecordFieldsListing.tpl
Labels: master, merge on pass

#12476 BAO_Navigation: Respect domain_id param
  CRM/Core/BAO/Navigation.php
  api/v3/Navigation.php
  tests/phpunit/api/v3/NavigationTest.php
Labels: master

#12478 (NFC) Regenerate OptionGroup DAO file
  CRM/Core/DAO/OptionGroup.php
Labels: master

#12477 (NFC) Update comment on membership type domain_id API Test
  tests/phpunit/api/v3/MembershipTypeTest.php
Labels: master

#12315 Only auto-renew membership when contribution status is completed
  CRM/Contribute/BAO/Contribution.php
  tests/phpunit/api/v3/ContributionTest.php
Labels: master, sig:bug

#12352 dev/core#188: Fix Floating Point Precision Comparison Exception
  CRM/Contribute/BAO/Contribution.php
  CRM/Contribute/Exception/CheckLineItemsException.php
  CRM/Utils/Money.php
  tests/phpunit/CRM/Contribute/BAO/ContributionTest.php
  tests/phpunit/CRM/Utils/MoneyTest.php
Labels: has-test, master, sig:bug

#12423 dev/core#155 Fix optiongroup is_reserved data and use when selecting option group for custom fields
  CRM/Core/BAO/CustomField.php
  CRM/Custom/Form/Field.php
  CRM/Upgrade/Incremental/sql/5.5.alpha1.mysql.tpl
  xml/templates/civicrm_data.tpl
Labels: master

#12453 Fix activity report to bring it under standardised report testing
  CRM/Report/Form.php
  CRM/Report/Form/Activity.php
  tests/phpunit/api/v3/ReportTemplateTest.php
Labels: master, merge on pass

#12479 Export class code cleanup Start building export processor class.
  CRM/Export/BAO/Export.php
  CRM/Export/BAO/ExportProcessor.php
Labels: master

#11660 CRM-21754: Duplicate rows in Activity Details report when address fields are displayed
  CRM/Report/Form.php
  CRM/Report/Form/Activity.php
  tests/phpunit/CRM/Report/Form/ActivityTest.php
Labels: has-test, master

#12484 Export code tidy up Use queryFields rather than query. Look to stop passing around query.
  CRM/Export/BAO/Export.php
Labels: master, merge on pass

#12460 Fix false negatives in checkResourceUrl()
  CRM/Utils/Check/Component/Env.php
Labels: master, merge on pass, sig:bug

#12452 Cleanup redundant array functions
  CRM/Utils/Array.php
Labels: master

#12415 core-34 Add view-only option on permissioned relationships
  CRM/Contact/BAO/Contact/Permission.php
  CRM/Contact/BAO/Query.php
  CRM/Contact/BAO/Relationship.php
  CRM/Contact/DAO/Relationship.php
  CRM/Contact/Form/Relationship.php
  CRM/Contact/Form/Search/Criteria.php
  CRM/Core/SelectValues.php
  CRM/Report/Form/Contact/Relationship.php
  templates/CRM/Contact/Form/Relationship.tpl
  templates/CRM/Contact/Page/View/Relationship.tpl
  tests/phpunit/CRM/ACL/ListTest.php
  xml/schema/Contact/Relationship.xml
Labels: has-test, master

#12466 NFC Ignore temp dir
  .gitignore
Labels: 4.6

#12486 dev/core#230 : set mapping id null on delete action
  CRM/Contact/DAO/SavedSearch.php
  xml/schema/Contact/SavedSearch.xml
Labels: master, merge on pass

#12482 NFC cleanup to financial classes
  CRM/Contribute/BAO/Contribution.php
  CRM/Core/BAO/FinancialTrxn.php
  CRM/Financial/BAO/FinancialAccount.php
  CRM/Financial/BAO/FinancialItem.php
Labels: master, merge on pass

#12468 Minor refactor preparatory to function extraction
  CRM/Export/BAO/Export.php
Labels: master

#12485 Export cleanup - pass processor object rather than the query object
  CRM/Export/BAO/Export.php
  CRM/Export/BAO/ExportProcessor.php
  tests/phpunit/CRM/Export/BAO/ExportTest.php
Labels: master

#12490 Test fix, use separate emails so distinct doesn't meld them
  tests/phpunit/api/v3/ReportTemplateTest.php
Labels: master, merge on pass

#12500 dev/financial/issues/28, Financial Account cannot be change to non de…
  CRM/Financial/Form/FinancialAccount.php
Labels: sig:user interfacing improvement

#12507 Fix enotice in test
  tests/phpunit/api/v3/ReportTemplateTest.php
Labels: master

#12489 dev/core/#/233 Expose information about where a contact has been merged to
  CRM/Contact/Page/View.php
  api/v3/Contact.php
  tests/phpunit/api/v3/ContactTest.php
Labels: master, merge on pass

#12469 Export cleanup Extract bulk of the transformation for each field to its own function
  CRM/Export/BAO/Export.php
  tests/phpunit/CRM/Export/BAO/ExportTest.php
Labels: master

#12506 Prevent financial transactions from being saved with no payment instrument
  CRM/Contribute/BAO/Contribution.php
Labels: 5.3

#12502 Prevent financial transactions from being saved with no payment instr…
  CRM/Contribute/BAO/Contribution.php
Labels: 5.4

#12508 5.4 to master
  CRM/Contribute/BAO/Contribution.php
Labels: master

#12499 Allow Drupal 8 vendor folder outside webroot
  CRM/Utils/System/Drupal8.php
Labels: master, merge ready, sig:compatibility drupal

#11197 CRM-21104: Forcing reCaptcha on Contribution pages(with online payments) which have no Profile associated with them.
  CRM/Admin/Form/Setting/Miscellaneous.php
  CRM/Contribute/Form/Contribution/Main.php
  CRM/Contribute/Form/ContributionBase.php
  CRM/Core/Config/MagicMerge.php
  CRM/Utils/ReCAPTCHA.php
  settings/Core.setting.php
  templates/CRM/Admin/Form/Setting/Miscellaneous.tpl
  templates/CRM/Contribute/Form/Contribution/Main.tpl
Labels: master, sig:user interfacing improvement

#12492 dev/core/#/258 Fix message update routine.
  CRM/Upgrade/Incremental/MessageTemplates.php
  tests/phpunit/CRM/Upgrade/Incremental/BaseTest.php
Labels: 5.4

#12504 Fix misformatted start_date default on new contribution page
  CRM/Contribute/Form/ContributionPage.php
  CRM/Contribute/Form/ContributionPage/Settings.php
Labels: 5.4

#12503 Remove LOWER from street_address search, rely on mysql to handle.
  CRM/Contact/BAO/Query.php
  tests/phpunit/CRM/Contact/BAO/QueryTest.php
Labels: master

#12513 Update 5.3.1 Release Notes to include final SA
  release-notes/5.3.1.md
Labels: 5.3

#12514 Update 5.3.1 Release Notes to include final SA
  release-notes/5.3.1.md
Labels: 5.4

#12515 5.4 to master
  release-notes/5.3.1.md
Labels: master

#12519 (Forward port) Add Smarty modifier to purify HTML
  CRM/Core/Smarty/plugins/modifier.purify.php
Labels: 5.4

#12517 Fix regression on case export from recent export fix
  CRM/Case/Task.php
  CRM/Core/Form/Task.php
  CRM/Export/Form/Select.php
  CRM/Export/Form/Select/Case.php
Labels: master, merge on pass

#12520 5.4
  CRM/Core/Smarty/plugins/modifier.purify.php
Labels: master

#12291 Minor fix to 46 test bootstrap
  tests/phpunit/CiviTest/bootstrap.php
Labels: 4.6

#12207 dev/accessiblity#3 Add aria-label to form elements of contribution page which don't have accessible labels
  CRM/Contribute/Form/Contribution/Main.php
  CRM/Pledge/BAO/PledgeBlock.php
  templates/CRM/Core/BillingBlock.tpl
  templates/CRM/Price/Form/Calculate.tpl
Labels: master, sig:accessibility

#12518 Export : Add a lot of unit tests. Fix an enotice
  CRM/Export/BAO/Export.php
  tests/phpunit/CRM/Export/BAO/ExportTest.php
Labels: master

#12524 Shoreditch support: Fix following change in core that resulted in visual regression in shoreditch in advanced search
  templates/CRM/Grant/Form/Search/Common.tpl
Labels: master, merge on pass

#12523 Fix signature on BAO_Product::add to make ids optional
  CRM/Contribute/BAO/ManagePremiums.php
  CRM/Contribute/BAO/Product.php
  CRM/Contribute/Form/ManagePremiums.php
  tests/phpunit/CRM/Contribute/BAO/ContributionTest.php
  tests/phpunit/CRM/Contribute/BAO/ProductTest.php
Labels: master, merge on pass

#12505 Extract code for getting additional return properties, test
  CRM/Activity/BAO/Activity.php
  CRM/Export/BAO/Export.php
  CRM/Export/BAO/ExportProcessor.php
  tests/phpunit/CRM/Export/BAO/ExportTest.php
Labels: master, merge on pass

#12528 (dev/core#217) Add skeletal PrevNextCache service
  CRM/Core/PrevNextCache/Interface.php
  CRM/Core/PrevNextCache/Sql.php
  Civi/Core/Container.php
Labels: master, merge on pass

#12526 Icons in colored boxes for relationship permissions
  CRM/Contact/BAO/Relationship.php
  css/civicrm.css
  templates/CRM/Contact/Form/Relationship.tpl
  templates/CRM/Contact/Page/View/Relationship.tpl
  templates/CRM/Contact/Page/View/RelationshipPerm.tpl
Labels: master, merge on pass

#12533 dev/core#272 : Fatal Error (Regression) on PCP pages associated with Events
  CRM/Event/Form/Registration.php
Labels: 5.4

#12531 (NFC) Convert files to use linux line endings not windows
  CRM/Contribute/Page/ContributionRecurPayments.php
  templates/CRM/Admin/Form/Preferences/Display.hlp
  templates/CRM/Contribute/Form/Task/Invoice.hlp
  templates/CRM/Contribute/Page/ContributionRecurPayments.tpl
  templates/CRM/Event/Form/ManageEvent/ConfirmRepeatMode.tpl
  templates/CRM/Member/Page/RecurringContributions.tpl
Labels: 5.4, merge on pass

#12529 (NFC) Deprecate redundant array util function
  CRM/Admin/Page/AJAX.php
  CRM/Utils/Array.php
Labels: master

#12473 dev/core#259 OptionGroup Admin UI workflow improvements
  CRM/Admin/Form/OptionGroup.php
  templates/CRM/Admin/Form/OptionGroup.tpl
  templates/CRM/Admin/Page/OptionGroup.tpl
  templates/CRM/Admin/Page/Options.tpl
Labels: master, merge on pass

#12532 dev/core#272 : Fatal Error (Regression) on PCP pages associated with Events
  CRM/Event/Form/Registration.php
Labels: 5.3

#12539 (NFC) Remove deprecated recursive array utils
  CRM/Utils/Array.php
  tests/phpunit/CRM/Utils/ArrayTest.php
Labels: master, merge on pass

#12540 Link to option group page from option group menu item
  CRM/Upgrade/Incremental/sql/5.5.alpha1.mysql.tpl
  xml/templates/civicrm_navigation.tpl
Labels: master

#12387 dev/financial#27 Paypal_Standard recurring IPNs don't work
  CRM/Core/Payment/PayPalIPN.php
  CRM/Core/Payment/PayPalProIPN.php
  tests/phpunit/CRM/Core/Payment/PayPalIPNTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: master, merge on pass

#12437 dev/core#242 Fix display of premiums on contribution page
  CRM/Contribute/BAO/ManagePremiums.php
  CRM/Contribute/BAO/Premium.php
  CRM/Contribute/BAO/Product.php
  CRM/Contribute/Form/ManagePremiums.php
  tests/phpunit/CRM/Contribute/BAO/ContributionTest.php
  tests/phpunit/CRM/Contribute/BAO/ProductTest.php
Labels: master, merge on pass

#12541 Update navigation menu items to use FontAwesome
  css/civicrmNavigation.css
  templates/CRM/common/navigation.js.tpl
Labels: master

#12549 5.4
  CRM/Contribute/Page/ContributionRecurPayments.php
  CRM/Upgrade/Incremental/sql/5.3.alpha1.mysql.tpl
  templates/CRM/Admin/Form/Preferences/Display.hlp
  templates/CRM/Contribute/Form/Task/Invoice.hlp
  templates/CRM/Contribute/Page/ContributionRecurPayments.tpl
  templates/CRM/Event/Form/ManageEvent/ConfirmRepeatMode.tpl
  templates/CRM/Member/Page/RecurringContributions.tpl
Labels: master

#12551 Included missed 5.3 commits
  CRM/Core/BAO/CustomGroup.php
Labels: 5.4

#12536 Theme layer Fix search for Shoreditch compatibility
  templates/CRM/common/navigation.js.tpl
Labels: master

#12385 dev/core#219 Improve consistency displaying "Test Transactions"
  CRM/Contribute/Page/Tab.php
  CRM/Member/Page/Tab.php
  templates/CRM/Contribute/Form/ContributionView.tpl
  templates/CRM/Contribute/Page/ContributionRecur.tpl
  templates/CRM/Contribute/Page/Tab.tpl
  templates/CRM/Member/Form/MembershipView.tpl
  templates/CRM/Member/Form/Selector.tpl
  templates/CRM/Member/Page/Tab.tpl
Labels: master, sig:user interfacing improvement

#12550 5.3 - Handle 'Check for Matching Contact(s)' button with ajax
  api/v3/Contact.php
  templates/CRM/Contact/Form/Contact.tpl
Labels: 5.3

#12546 Reduce config required to use Redis.
  templates/CRM/common/civicrm.settings.php.template
Labels: master, merge on pass

#12545 (dev/core#217) PrevNext - Define and use fillWithSql()/fillWithArray()
  CRM/Campaign/Selector/Search.php
  CRM/Contact/Selector.php
  CRM/Core/PrevNextCache/Interface.php
  CRM/Core/PrevNextCache/Sql.php
Labels: master, merge on pass

#12544 (dev/core#217) CRM_Utils_Cache_Redis::connect() - Allow pooling connections
  CRM/Utils/Cache/Redis.php
Labels: master, merge on pass

#12521 Move relationship return properties to the processor class to fix leakage related test fail
  CRM/Export/BAO/Export.php
  CRM/Export/BAO/ExportProcessor.php
  tests/phpunit/CRM/Export/BAO/ExportTest.php
Labels: has-test, master

#12439 dev/core#111 Support Custom Data for MembershipType entity
  CRM/Member/Form/MembershipType.php
  templates/CRM/Member/Form/MembershipType.tpl
Labels: master, merge on pass

#12440 dev/core#244 Allow use of custom fields of type select without specifying an optiongroup
  CRM/Core/BAO/CustomField.php
Labels: master, merge ready

#11949 Event Info: show waitinglist statusline only when registration is open
  CRM/Event/Page/EventInfo.php
Labels: master, sig:bug

#12552 Handle 'Check for Matching Contact(s)' button with ajax
  CRM/Contact/Form/Contact.php
  api/v3/Contact.php
  templates/CRM/Contact/Form/Contact.tpl
Labels: 5.4

#12555 5.4 to master
  CRM/Contact/Form/Contact.php
  CRM/Core/BAO/CustomGroup.php
  api/v3/Contact.php
  templates/CRM/Contact/Form/Contact.tpl
Labels: master

#12543 (dev/core#217) PrevNext - Probe for best available implementation (memory-backed or SQL-backed)
  CRM/Utils/Cache.php
  Civi/Core/Container.php
Labels: master

#12364 dev/core#210: Regex filter broken in Search Builder
  CRM/Contact/BAO/Query.php
  tests/phpunit/CRM/Contact/SelectorTest.php
Labels: has-test, master

#12185 Entity form : Establish methodology to allow default values to be passed in on the url
  CRM/Core/Form/EntityFormTrait.php
  CRM/Member/Form/MembershipStatus.php
Labels: master, sig:code maintenance readability testability, sig:extension support

#12564 dev/core#276 enotice fix
  CRM/Member/Form/Membership.php
Labels: 5.3, merge on pass

#12563 dev/core#276 enotice fix
  CRM/Member/Form/Membership.php
Labels: 5.4

#12566 dev/279 - When Merging two contacts flip, prev, next not working
  templates/CRM/Contact/Form/Merge.tpl
Labels: 5.3, merge on pass

#12569 5.4
  CRM/Member/Form/Membership.php
  templates/CRM/Contact/Form/Merge.tpl
Labels: master

#12367 [reviewed, pending rebase] CRM-20703 - Event Contribution Created When No Payment Option Provided
  CRM/Contribute/Form/ContributionPage/Amount.php
  CRM/Event/Form/ManageEvent/Fee.php
Labels: master, sig:user interfacing improvement

#12570 Add 5.3.2 release notes
  release-notes/5.3.2.md
Labels: 5.4, merge on pass

#12571 Add 5.3.2 release notes (#12570)
  release-notes/5.3.2.md
Labels: master

#12556 (dev/core#217) PrevNext - Migrate selection methods
  CRM/Campaign/Form/Task.php
  CRM/Contact/Form/Search.php
  CRM/Contact/Form/Task.php
  CRM/Contact/Page/AJAX.php
  CRM/Core/BAO/PrevNextCache.php
  CRM/Core/PrevNextCache/Interface.php
  CRM/Core/PrevNextCache/Sql.php
Labels: master

#12416 dev/core/issues/232, Some smart groups and some searches not returning any contacts
  CRM/Contact/BAO/Query.php
  CRM/Contact/Form/Search/Custom/MultipleValues.php
  tests/phpunit/CRM/Contact/Form/Search/SearchContactTest.php
Labels: master

#12388 dev/financial/issues/24, Moved code from form layer to BAO and used api instead of BAO function
  CRM/Admin/Form/Options.php
  CRM/Core/BAO/OptionValue.php
Labels: master

#12573 Added code to throw exception on getvalue api call
  Civi/Test/Api3TestTrait.php
Labels: master, merge on pass

#12530 crmRouteBinder - Don't convert arrays to objects
  ang/crmRouteBinder.js
Labels: master, merge on pass

#12577 Export clean up sql columns
  CRM/Export/BAO/Export.php
  CRM/Export/BAO/ExportProcessor.php
Labels: master, merge on pass

#12578 (NFC) Update readme to link to GitLab instead of JIRA
  README.md
Labels: master, merge on pass

#12589 dev/core#291 Allow for field size to be set for password fields
  CRM/Core/Form.php
Labels: master, merge on pass

#12590 (dev/core#284) System::flushCache - Reproduce legacy cache behavior. Improve test performance.
  CRM/Utils/System.php
Labels: 5.4, merge on pass
