Repository civicrm/civicrm-core, pull requests merged in 2018-06, with the labels that each got.

#12242 Move upgrade message to right file
  CRM/Upgrade/Incremental/php/FiveThree.php
  CRM/Upgrade/Incremental/php/FiveTwo.php
Labels: master, merge on pass

#12240 Only set defaults when creating a custom field (not when editing one)
  CRM/Core/BAO/CustomField.php
  tests/phpunit/api/v3/CustomFieldTest.php
Labels: master

#12225 dev/core#149 - Fatal Error on customvalue get api
  api/v3/CustomValue.php
  tests/phpunit/api/v3/CustomValueTest.php
Labels: has-test, master

#11407 CRM-21553 : profile duplicate field validation for field with primary location type
  CRM/Core/BAO/UFField.php
  CRM/UF/Form/Field.php
Labels: master

#12247 dev/mail#12 Incorrect Total Count on mail summary report
  CRM/Report/Form/Mailing/Summary.php
Labels: master

#12245 getCaseRoles not working when supplied relationship id. civicrm_relationship table name changed to alias name rel because its changed in the actual query
  CRM/Case/BAO/Case.php
Labels: master, merge on pass

#12226 dev/core#147 Use location type machine name as table alias instead of label
  CRM/Contact/BAO/Query.php
  CRM/Contact/Selector.php
  CRM/Core/BAO/Mapping.php
  tests/phpunit/CRM/Contact/SelectorTest.php
Labels: has-test, master, merge on pass

#12114 dev/membership#2 - Add membership start date and registration start/end date to schedule reminder
  CRM/Event/ActionMapping.php
  CRM/Member/ActionMapping.php
  tests/phpunit/CRM/Core/BAO/ActionScheduleTest.php
Labels: has-test, master, merge on pass

#12249 fix of issue dev/core#127 (at gitlab), incorrect cache records for smart groups
  CRM/Contact/BAO/Query.php
  contributor-key.yml
  tests/phpunit/api/v3/ContactTest.php
Labels: master, merge on pass

#12248 Auto-open tagest fields
  CRM/Core/Form/Tag.php
Labels: master

#12250 Upgrade Karma and associated dependencies
  karma.conf.js
  package-lock.json
  package.json
Labels: 4.6

#11227 CIVICRM-706: Making front-end CVV always required, regardless of the CVV required for back office option.
  CRM/Core/Payment.php
  CRM/Core/Payment/Form.php
  tests/phpunit/CRM/Core/PaymentTest.php
Labels: 4.6

#12057 CIVICRM-807: Request nethod in Mark selection of contact search changed to POST.
  js/crm.searchForm.js
Labels: 4.6

#12179 Removing related memberships if parent membership type is changed which does not have relation type associated.
  CRM/Member/BAO/Membership.php
  tests/phpunit/CRM/Member/BAO/MembershipTest.php
Labels: 4.6

#11977 CIVICRM-836: PR 11580 backported which fixes logging not be able to be enabled on Maria10.2
  CRM/Logging/Schema.php
  tests/phpunit/CRM/Logging/SchemaTest.php
Labels: 4.6

#12241 ensure that the indexed column is not an FK before deleting the index
  CRM/Core/BAO/SchemaHandler.php
  tests/phpunit/api/v3/CustomFieldTest.php
Labels: master, merge on pass

#11730 RM385-65: Membership end date incremented twice by duration when pending contribution with amount 0.0
  CRM/Member/BAO/Membership.php
Labels: 4.6

#12254 dev/core#162 - Use checksum to access user dashboard
  CRM/Contact/Page/View/UserDashBoard.php
Labels: master

#12256 CRM-20621 - Initial cleanup toward performance improvements
  CRM/Admin/Page/AJAX.php
  templates/CRM/Tag/Page/Tag.tpl
Labels: master, merge on pass

#12252 dev/core#160 Set the import progress widget to poll the server every …
  templates/CRM/common/importProgress.tpl
Labels: master

#12243 Fix enotice when updating a custom group with is_multiple = 1
  CRM/Core/BAO/CustomGroup.php
  tests/phpunit/api/v3/CustomGroupTest.php
Labels: master

#12238 dev/core/#152 - Remove AdvMulti-Select custom field type
  CRM/Contact/Import/Parser/Contact.php
  CRM/Core/BAO/CustomField.php
  CRM/Core/BAO/CustomGroup.php
  CRM/Core/BAO/CustomOption.php
  CRM/Core/BAO/UFGroup.php
  CRM/Core/Page/AJAX/Location.php
  CRM/Core/SelectValues.php
  CRM/Custom/Form/ChangeFieldType.php
  CRM/Custom/Form/Field.php
  CRM/Custom/Form/Option.php
  CRM/Dedupe/Merger.php
  CRM/Member/Import/Parser/Membership.php
  CRM/Upgrade/Incremental/sql/5.3.alpha1.mysql.tpl
  CRM/Utils/DeprecatedUtils.php
  api/v3/CustomField.php
  templates/CRM/Custom/Form/ChangeFieldType.tpl
  templates/CRM/Custom/Form/Field.tpl
  tests/phpunit/WebTest/Import/AddressImportTest.php
  tests/phpunit/api/v3/CustomValueTest.php
Labels: master

#12258 Add 'Alphanumeric' rule type
  CRM/Utils/Rule.php
  CRM/Utils/Type.php
  tests/phpunit/CRM/Utils/RuleTest.php
Labels: master, merge on pass

#12257 Fix unreleased regression - fatal when editing relationship type Employer
  CRM/Admin/Form/RelationshipType.php
  CRM/Core/Form/EntityFormTrait.php
Labels: master

#10341 CRM-20565 - Improve ajax dedupe lookups on contact add form
  CRM/Admin/Form/Preferences/Display.php
  CRM/Contact/Form/Contact.php
  CRM/Contact/Form/Edit/Household.php
  CRM/Contact/Form/Edit/Individual.php
  CRM/Contact/Form/Edit/Organization.php
  api/v3/Contact.php
  settings/Core.setting.php
  templates/CRM/Admin/Form/Preferences/Display.tpl
  templates/CRM/Admin/Page/APIExplorer.js
  templates/CRM/Contact/Form/Contact.tpl
  templates/CRM/Contact/Form/Edit/Individual.tpl
Labels: master, merge on pass

#12255 fix related to issue dev/core#127, in depth overlap of filter related contacts
  CRM/Contact/BAO/Query.php
  tests/phpunit/api/v3/ContactTest.php
Labels: master

#12262 dev/mail#13 - All members should not be excluded from Smart unsubscribe group
  CRM/Mailing/BAO/Mailing.php
  tests/phpunit/CRM/Mailing/BAO/MailingTest.php
Labels: 5.2, has-test, merge on pass

#12264 5.2 merge to maste
  CRM/Mailing/BAO/Mailing.php
  tests/phpunit/CRM/Mailing/BAO/MailingTest.php
Labels: master

#12265 Accessibility #9: Regression - js error due to alertDismissal setting fixed.
  CRM/Core/Resources.php
  templates/CRM/common/l10n.js.tpl
Labels: master, merge on pass

#12267 dev/core/#152 - AdvMulti-Select cleanup
  CRM/Contact/Import/Parser.php
Labels: master, merge on pass

#12259 dev/core#163 Fix issue where disabling a group would block access to …
  CRM/Mailing/BAO/Mailing.php
  tests/phpunit/CRM/Mailing/BAO/MailingTest.php
Labels: merge on pass

#12100 5.2.0 release notes
  contributor-key.yml
  release-notes.md
  release-notes/5.1.2.md
  release-notes/5.2.0.md
Labels: 5.2

#12269 5.2.0 merge to master
  contributor-key.yml
  release-notes.md
  release-notes/5.1.2.md
  release-notes/5.2.0.md
Labels: master

#10630 CRM-20841 - Dedupe - Show on_hold, is_bulkmail or signature merge…
  CRM/Dedupe/Merger.php
  CRM/Utils/Mail.php
  templates/CRM/Contact/Form/Merge.tpl
Labels: master

#12266 dev/core#154 - Can't edit related records when current employer has a…
  CRM/Contact/BAO/Relationship.php
  tests/phpunit/api/v3/MembershipTest.php
Labels: master, merge on pass

#12273 dev/core#158 group contacts list and export limits results to 500 records
  CRM/Export/Form/Select.php
Labels: 5.2

#12274 5.2 to master
  CRM/Export/Form/Select.php
Labels: master

#12193 Fix non-display of conflicts after batch dedupe from dedupe screen
  CRM/Contact/Page/AJAX.php
  CRM/Contact/Page/DedupeFind.php
  CRM/Contact/Page/DedupeMerge.php
  CRM/Dedupe/Merger.php
  templates/CRM/Contact/Page/DedupeFind.tpl
Labels: master, sig:bug

#12275 dev/mail#11 add CRM_Mailing_BAO_MailingJob::del()
  CRM/Mailing/BAO/Mailing.php
  CRM/Mailing/BAO/MailingJob.php
  CRM/Mailing/Form/Approve.php
  api/v3/MailingJob.php
Labels: master

#12272 Towards fixing household merge export, extract function, add test, fix prev
  CRM/Export/BAO/Export.php
  tests/phpunit/CRM/Export/BAO/ExportTest.php
Labels: master

#12278 Fix incorrect operator on previous Export fix
  CRM/Export/BAO/Export.php
Labels: 5.3, merge on pass

#12209 dev/accessiblity#3 Remove orphan label tag from Event pages
  templates/CRM/Event/Form/Registration/EventInfoBlock.tpl
  templates/CRM/Event/Page/EventInfo.tpl
Labels: master

#12195 dev/core#140 add missing pseudoconstant for option_group_id in CustomField.xml
  CRM/Core/DAO/CustomField.php
  tests/phpunit/api/v3/CustomFieldTest.php
  xml/schema/Core/CustomField.xml
Labels: master, sig:code maintenance readability testability, sig:extension support

#11803 Mail#1 - Add pause/resume functionality to civicrm bulk mailing
  CRM/Mailing/BAO/MailingJob.php
  CRM/Mailing/Form/Browse.php
  CRM/Mailing/Form/Search.php
  CRM/Mailing/Page/Browse.php
  CRM/Mailing/Selector/Browse.php
  tests/phpunit/api/v3/JobProcessMailingTest.php
Labels: master

#12280 [NFC] Fix line endings (Jenkins where were you)
  CRM/Member/Page/RecurringContributions.php
Labels: master, merge on pass

#12181 dev/core#134 Search Builder broken filter for Source Contact ID
  CRM/Activity/BAO/Activity.php
  CRM/Activity/BAO/Query.php
  tests/phpunit/CRM/Contact/SelectorTest.php
Labels: has-test, master

#12279 dev/core#165 - Fix case activity breadcrumb
  CRM/Case/Form/ActivityView.php
Labels: master, sig:bug

#12282 core/#170 minimal fix for fatal on soft_credit field
  CRM/Report/Form/Contribute/Detail.php
Labels: master, merge on pass

#12283 Add unit test for CRM_Core_BAO_CustomField::getCustomFieldID
  tests/phpunit/CRM/Core/BAO/CustomFieldTest.php
Labels: master, sig:code maintenance readability testability

#12271 Partial refactor of completeMembershipFromContribution
  CRM/Contribute/BAO/Contribution.php
Labels: master, sig:code maintenance readability testability

#12284 dev/mail#1 - Modify message text for pause mailing
  CRM/Mailing/Page/Browse.php
Labels: master, merge on pass

#12286 core/#170 minimal fix for fatal on soft_credit field
  CRM/Report/Form/Contribute/Detail.php
Labels: 5.2, merge on pass

#11724 CRM-21779 - ang\crmMailing - Fix adding empty mailing to recipients field
  ang/crmMailing/Recipients.js
Labels: master

#12287 core/#170 minimal fix for fatal on soft_credit field
  CRM/Report/Form/Contribute/Detail.php
Labels: 5.3, master, merge on pass

#11840 CiviMail: If SMTP connection error is detected, disconnect so we can reconnect and retry
  CRM/Mailing/BAO/MailingJob.php
Labels: master

#12078 dev/core/#101: Allow further customization of search form in hooks
  CRM/Contact/Form/Search/Criteria.php
  css/searchForm.css
  templates/CRM/Contact/Form/Search/Criteria/Basic.tpl
  templates/CRM/Contact/Form/Search/Criteria/Fields/group.tpl
  templates/CRM/Contact/Form/Search/Criteria/Fields/preferred_communication_method.tpl
  templates/CRM/Contact/Form/Search/Criteria/Fields/privacy_toggle.tpl
  templates/CRM/Contact/Form/Search/Criteria/Fields/tag_set.tpl
Labels: master, merge on pass, sig:code maintenance readability testability, sig:extension support

#11956 (dev/core/50) Add Separate Sub-tabs for Contributions and Recurring Contributions
  CRM/Contribute/BAO/ContributionRecur.php
  CRM/Contribute/Page/Tab.php
  templates/CRM/Contribute/Page/Tab.tpl
Labels: master

#12067 Make Send SMS permission independent of Edit Contact permission
  CRM/Contact/Task.php
Labels: master, sig:permission nuancing

#11945 dev/core#47 Add clone scheduled job functionality
  CRM/Admin/Page/Job.php
  CRM/Core/BAO/Job.php
  api/v3/Job.php
  tests/phpunit/api/v3/JobTest.php
Labels: has-test, master

#11337 CRM-21460 Add job execution hooks
  CRM/Core/JobManager.php
  CRM/Utils/Hook.php
Labels: master

#12107 CRM-20430 - Permission 'save Report Criteria'.
  CRM/Core/Permission.php
  CRM/Report/BAO/ReportInstance.php
  CRM/Report/Info.php
  CRM/Upgrade/Incremental/php/FiveFour.php
  tools/drupal/modules/civicrm_webtest/civicrm_webtest.install
Labels: master, merge on pass, sig:permission nuancing

#11726 CRM-21808 Install custom group for Contribution or ContributioRecur s…
  CRM/Utils/Migrate/Import.php
Labels: master

#12289 Partial code cleanup & testability improvement towards CRM-21177
  CRM/Contribute/Form/Contribution/Confirm.php
  tests/phpunit/api/v3/ContributionPageTest.php
Labels: master, merge on pass, sig:code maintenance readability testability

#12288 Function extraction BAO_Export class
  CRM/Export/BAO/Export.php
  tests/phpunit/CRM/Export/BAO/ExportTest.php
Labels: master

#12224 Add upgrade function for message templates that does not involve copying the whole template
  CRM/Upgrade/Form.php
  CRM/Upgrade/Incremental/Base.php
  CRM/Upgrade/Incremental/General.php
  CRM/Upgrade/Incremental/MessageTemplates.php
  tests/phpunit/CRM/Upgrade/Incremental/BaseTest.php
  xml/templates/message_templates/membership_online_receipt_text.tpl
Labels: master, sig:code maintenance readability testability

#12293 Improve CRM_Utils_Array::recursiveBuild to work with existing arrays.
  CRM/Utils/Array.php
  tests/phpunit/CRM/Utils/ArrayTest.php
Labels: 5.3, merge on pass

#12294 Remove unused function getRecuringTransactionStatus from PayflowPro c…
  CRM/Core/Payment/PayflowPro.php
Labels: master, merge on pass

#12295 Confirm & lock in group.get handling of is_active
  tests/phpunit/api/v3/GroupTest.php
Labels: master, merge on pass

#12277 dev/core#163 Improve inclusion of disabled groups when getting all ma…
  CRM/Mailing/BAO/Mailing.php
Labels: merge on pass, sig:bug

#12300 5.3
  CRM/Mailing/BAO/Mailing.php
Labels: master

#11964 (dev/core/56) Cancel Recurring Contribution activity should has a source record id
  CRM/Contribute/BAO/ContributionRecur.php
Labels: master, merge on pass, sig:user interfacing improvement

#12299 Remove unused code variable
  CRM/Contribute/BAO/ContributionRecur.php
  CRM/Contribute/Form/CancelSubscription.php
  api/v3/ContributionRecur.php
  tests/phpunit/CRM/Contribute/BAO/ContributionRecurTest.php
Labels: master

#11883 core-32 - Add option to disable cancel button on a profile form
  CRM/Core/DAO/UFGroup.php
  CRM/Profile/Form/Edit.php
  CRM/UF/Form/AdvanceSetting.php
  CRM/UF/Form/Group.php
  CRM/Upgrade/Incremental/php/FiveFour.php
  templates/CRM/Profile/Form/Dynamic.tpl
  templates/CRM/UF/Form/AdvanceSetting.tpl
  templates/CRM/UF/Form/Group.hlp
  xml/schema/Core/UFGroup.xml
Labels: master, sig:user interfacing improvement

#12281 Add testing to contribution detail report, covering dev/core/issues#170
  CRM/Report/Form.php
  CRM/Report/Form/Contribute/Detail.php
  api/v3/ReportTemplate.php
  tests/phpunit/api/v3/ReportTemplateTest.php
Labels: master

#12301 dev/core#175 - Smart group involving relationship type filter display…
  CRM/Contact/BAO/Query.php
  tests/phpunit/CRM/Contact/BAO/QueryTest.php
Labels: has-test

#12302 (dev/core#177) Redis::get() should return NULL for undefined cache keys
  CRM/Utils/Cache/Redis.php
Labels: master, merge on pass, sig:performance

#12276 CRM-19798 fix memory leak on EntityTag.get & other calls in the DB (generic fix)
  CRM/Contact/BAO/Contact.php
  CRM/Contact/Import/Parser.php
  CRM/Core/BAO/RecurringEntity.php
  CRM/Core/DAO.php
  CRM/Dedupe/Merger.php
  tests/phpunit/CRM/Core/DAOTest.php
  tests/phpunit/api/v3/EntityTagTest.php
Labels: master, sig:performance

#11481 CRM-21622: Allow multiple parents to be created from 'New Group' form.
  CRM/Group/Form/Edit.php
Labels: master

#11830 dev/core#24 Passing an array for contact_id/client_id to Case.Create API when updating an existing case causes case to be "reassigned"
  CRM/Case/BAO/Case.php
  api/v3/Case.php
Labels: master, sig:extension support

#12304 (dev/core#179) Redis - Only send AUTH if there's a password
  CRM/Utils/Cache/Redis.php
Labels: master, sig:performance

#12308 Only treat a request as a get request (and hence use GET) if it starts with get
  js/crm.ajax.js
Labels: master, merge on pass, sig:extension support

#11733 Fix access to scheduled reminders for admins without event access
  CRM/Admin/Form/ScheduleReminders.php
  CRM/Core/Form.php
Labels: master, sig:bug

#12309 Fix for #180: passing the entity ID to the custom hook when deleting a custom value
  CRM/Core/BAO/CustomValue.php
Labels: master

#11881 CRM-21854 - Contribution start date and end dates are not respected
  CRM/Contribute/Exception/FutureContributionPageException.php
  CRM/Contribute/Exception/PastContributionPageException.php
  CRM/Contribute/Form/ContributionBase.php
  CRM/Contribute/Form/ContributionPage.php
  CRM/Contribute/Form/ContributionPage/Settings.php
  templates/CRM/Contribute/Form/ContributionPage/Settings.tpl
Labels: master

#12303 (dev/core#178) Redis - Report error messages
  CRM/Utils/Cache/Redis.php
Labels: master, sig:performance

#11907 dev/core#88 Make sure financial_type_id is set when contribution is created
  CRM/Contribute/BAO/Contribution/Utils.php
  CRM/Contribute/Form/Contribution/Confirm.php
  tests/phpunit/CRM/Contribute/Form/Contribution/ConfirmTest.php
Labels: master, merge on pass

#11495 CRM-21637 - Search Criteria for Card Type ID and Card Number not resp…
  CRM/Batch/BAO/Batch.php
  CRM/Financial/Page/AJAX.php
Labels: master

#11578 CRM-20697 - Online pay now anomalies (contribution transfer to new contact)
  CRM/Contribute/Form/Contribution/Main.php
Labels: master

#12218 dev/core#144 getCustomFieldID switch to API, add caching, add full string return option
  CRM/Core/BAO/CustomField.php
Labels: master, sig:performance

#12318 Make all form tasks inherit from Core_Form_Task
  CRM/Activity/Form/Task.php
  CRM/Campaign/Form/Task.php
  CRM/Contact/Form/Task.php
  CRM/Contribute/Form/Task.php
  CRM/Event/Form/Task.php
  CRM/Export/Form/Select.php
  CRM/Grant/Form/Task.php
  CRM/Mailing/Form/Task.php
  CRM/Member/Form/Task.php
  CRM/Pledge/Form/Task.php
Labels: master

#12314 Cleanup recordAdditionalPayment towards #11556
  CRM/Contribute/BAO/Contribution.php
Labels: master, sig:code maintenance readability testability

#12321 (dev/core#174) api_v3_SettingTest - Remove dead code
  tests/phpunit/api/v3/SettingTest.php
Labels: master, merge on pass, sig:code maintenance readability testability

#12324 Fix typo in api explorer sample code
  templates/CRM/Admin/Page/APIExplorer.js
Labels: master

#12323 (NFC) dev/core#174 - CRM_Utils_System::flushCache - Remove dead code
  CRM/Admin/Form/Job.php
  CRM/Admin/Form/LocationType.php
  CRM/Admin/Form/PaymentProcessorType.php
  CRM/Group/Form/Edit.php
  CRM/SMS/Form/Provider.php
  CRM/Tag/Form/Tag.php
Labels: master, sig:code maintenance readability testability

#12160 dev/core#124 Enhancements for events requiring approval
  CRM/Event/Form/Registration/Confirm.php
  xml/templates/message_templates/event_online_receipt_html.tpl
  xml/templates/message_templates/event_online_receipt_subject.tpl
  xml/templates/message_templates/event_online_receipt_text.tpl
Labels: master, sig:bug, sig:user interfacing improvement

#12311 (dev/core#183) Temporary tables should follow consistent naming convention
  CRM/Activity/BAO/Activity.php
  CRM/Contact/Form/Search/Custom/ContribSYBNT.php
  CRM/Contact/Form/Search/Custom/DateAdded.php
  CRM/Contact/Form/Task.php
  CRM/Core/Config.php
  CRM/Core/DAO.php
  CRM/Export/BAO/Export.php
  CRM/Report/Form.php
  CRM/Report/Form/Contribute/Lybunt.php
  CRM/Utils/SQL/TempTable.php
Labels: master

#12313 Cleanup of api_v3_membership_create towards #11556
  api/v3/Membership.php
Labels: master

#12329 [NFC] Stop passing no-longer-part-of-signature variable
  CRM/Contact/Form/Contact.php
  CRM/Contribute/BAO/Contribution.php
  CRM/Member/BAO/Membership.php
Labels: master, merge on pass, sig:code maintenance readability testability

#12176 dev/core/#133 Make Conditions Stricter When Checking If Reply-To Field Is Empty
  CRM/Mailing/BAO/Mailing.php
Labels: master, sig:bug

#12333 dev/core/issues/189, fixed smarty error
  templates/CRM/Event/Form/EventFees.tpl
Labels: 5.3

#12335 5.3 merge to master
  templates/CRM/Event/Form/EventFees.tpl
Labels: master

#12334 dev/core/issues/189, fixed smarty error
  templates/CRM/Event/Form/EventFees.tpl
Labels: 5.2, merge on pass

#12013 Add in bootstrap button classes to CiviMail interface
  ang/crmMailing/BlockPreview.html
  ang/crmMailing/EditMailingCtrl/2step.html
  ang/crmMailing/EditMailingCtrl/unified.html
  ang/crmMailing/EditMailingCtrl/unified2.html
  ang/crmMailing/EditMailingCtrl/wizard.html
  ang/crmMailing/EditMailingCtrl/workflow.html
  ang/crmUi/wizard.html
Labels: master, merge on pass, sig:extension support

#12270 Towards CRM-17753 - consolidate code location for do-not-reply@mydomain.com
  CRM/Campaign/BAO/Petition.php
  CRM/Core/BAO/Domain.php
  CRM/Mailing/Event/BAO/Confirm.php
  CRM/Mailing/Event/BAO/Reply.php
  CRM/Mailing/Event/BAO/Resubscribe.php
  CRM/Mailing/Event/BAO/Subscribe.php
  CRM/Mailing/Event/BAO/Unsubscribe.php
Labels: master, sig:code maintenance readability testability

#12338 Ensure classes are the same across all workflow templates
  ang/crmMailing/EditMailingCtrl/workflow.html
Labels: master, merge on pass

#12330 (dev/core#174) CRM_Utils_Cache_Redis::flush() - Respect prefixes
  CRM/Utils/Cache/Memcache.php
  CRM/Utils/Cache/Memcached.php
  CRM/Utils/Cache/Redis.php
Labels: master

#12316 NFC Code cleanup to core task class
  CRM/Case/Form/Task.php
  CRM/Core/Form/Task.php
Labels: master

#12339 Use html5 color input for contribution page widget
  CRM/Contribute/Form/ContributionPage/Widget.php
  templates/CRM/Contribute/Form/ContributionPage/Widget.tpl
Labels: master, merge ready, sig:user interfacing improvement

#12341 Remove unused instances of usedTable
  CRM/Activity/Form/Task.php
  CRM/Contact/Form/Task.php
  CRM/Contribute/Form/Task.php
  CRM/Event/Form/Task.php
  CRM/Grant/Form/Task.php
  CRM/Mailing/Form/Task.php
  CRM/Member/Form/Task.php
  CRM/Pledge/Form/Task.php
Labels: master, merge on pass, sig:code maintenance readability testability

#12178 dev/membership#4 - Admin Membership type is displayed on Public contr…
  CRM/Member/BAO/MembershipType.php
  templates/CRM/Member/Form/MembershipType.tpl
  tests/phpunit/api/v3/MembershipTypeTest.php
Labels: has-test, master, sig:user interfacing improvement

#12331 (dev/core#174) CRM_Utils_Cache - Always use a prefix. Standardize delimiter
  CRM/Cxn/CiviCxnHttp.php
  CRM/Utils/Cache.php
  CRM/Utils/Cache/SqlGroup.php
  CRM/Utils/System.php
Labels: master, sig:code maintenance readability testability, sig:extension support

#12347 (NFC) CiviUnitTestCase - Fix edge-case for mis-reported error
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: master, merge on pass

#12317 dev/core#187 Fix typo in CRM_Grant_Form_Task that prevents retrieving session key from URL
  CRM/Grant/Form/Task.php
Labels: master, sig:bug

#12351 dev/core#41: Search Builder: Not empty with date or integer custom fields gives a sql warning
  CRM/Contact/BAO/Query.php
  CRM/Contact/Form/Search/Builder.php
  CRM/Core/BAO/CustomField.php
  CRM/Core/BAO/CustomQuery.php
  templates/CRM/Contact/Form/Search/Builder.js
Labels: master

#11241 CRM-21392 Allow viewing groups/smartgroups as as other entities (eg. memberships, events)
  CRM/Contact/BAO/Group.php
  CRM/Group/Form/Search.php
  CRM/Group/Page/AJAX.php
  CRM/Member/Task.php
  templates/CRM/Group/Form/Search.tpl
  tests/phpunit/CRM/Group/Page/AjaxTest.php
Labels: master, sig:user interfacing improvement

#12332 Add support for hidden fields in general (and 'token' specifically) on the payment form.
  CRM/Contribute/Form/ContributionBase.php
  CRM/Core/Payment.php
  CRM/Core/Payment/Form.php
  templates/CRM/Core/BillingBlock.tpl
Labels: master, sig:extension support

#12357 dev/core/issues/203, removed cruft code
  CRM/Core/BAO/OptionGroup.php
Labels: master

#12363 dev/core#41: Added unit test
  CRM/Core/BAO/CustomField.php
  api/v3/utils.php
  tests/phpunit/CRM/Contact/SelectorTest.php
Labels: master

#12354 (dev/core#174) civicrm_cache - Allow storage of binary data
  CRM/Core/BAO/Cache.php
  tests/phpunit/CRM/Core/BAO/CacheTest.php
Labels: master

#12348 (dev/core#174) Cache-keys for CRM_Utils_Cache_* should avoid reserved chars
  CRM/ACL/BAO/ACL.php
  CRM/Contact/BAO/ContactType.php
  CRM/Core/BAO/Cache.php
  CRM/Core/OptionGroup.php
  CRM/Core/PseudoConstant.php
  CRM/Cxn/CiviCxnHttp.php
  CRM/Extension/Mapper.php
  Civi/Angular/Manager.php
  Civi/Core/SettingsManager.php
  tests/phpunit/CRM/Core/BAO/CacheTest.php
  tests/phpunit/Civi/Core/SettingsManagerTest.php
Labels: master, merge on pass

#12355 CRM-21574 NFC code cleanup of CRM_Friend_BAO_Friend class
  CRM/Friend/BAO/Friend.php
  CRM/Friend/Form.php
Labels: master

#12368 (dev/core#174) civicrm_cache - Finish transition from DATETIME to TIMESTAMP
  CRM/Upgrade/Incremental/sql/5.4.alpha1.mysql.tpl
Labels: master

#12376 (dev/core#174) Add various utilities to support PSR-16
  CRM/Utils/Cache.php
  CRM/Utils/Cache/CacheException.php
  CRM/Utils/Cache/InvalidArgumentException.php
  CRM/Utils/Cache/NaiveMultipleTrait.php
  CRM/Utils/Date.php
  templates/CRM/common/civicrm.settings.php.template
  tests/phpunit/E2E/Cache/CacheTestCase.php
Labels: master

#12236 CiviCase, added reference of activities from different timelines.
  CRM/Case/BAO/CaseType.php
  ang/crmCaseType.js
  ang/crmCaseType/timelineTable.html
  tests/phpunit/CRM/Case/BAO/CaseTypeTest.php
  tests/phpunit/api/v3/CaseTypeTest.php
Labels: master, sig:user interfacing improvement
