Repository civicrm/civicrm-core, pull requests merged in 2018-03, with the labels that each got.

#11735 CRM-21814: Fixed text wrapping
  templates/CRM/Event/Form/ManageEvent/Fee.tpl
Labels: master

#11747 CKEditorConfig - Fix double-escaped slashes
  CRM/Admin/Page/CKEditorConfig.php
Labels: master

#11748 CRM-20610 make it possible to enable the payment form
  CRM/Contribute/Form/Contribution.php
  CRM/Financial/Form/PaymentEdit.php
  templates/CRM/Contribute/Form/Contribution.tpl
Labels: master

#11750 CRM-21823: Fix structure and style glitches
  templates/CRM/Admin/Form/Setting/Date.tpl
  templates/CRM/Admin/Form/Setting/Localization.tpl
  templates/CRM/Member/Form/MembershipType.tpl
Labels: master

#11746 CRM-21806 Search builder NOT Empty does not work
  CRM/Contact/BAO/Query.php
  CRM/Contact/Selector.php
Labels: master

#11630 CRM-20554: Error when running activity report
  CRM/Report/Form/Activity.php
Labels: master

#11751 CRM-21806: Added Unit test
  tests/phpunit/CRM/Contact/SelectorTest.php
Labels: master

#11752 CKEditor Advanced Options - Better validation of options
  CRM/Admin/Page/CKEditorConfig.php
  css/civicrm.css
  js/wysiwyg/admin.ckeditor-configurator.js
  templates/CRM/Admin/Page/CKEditorConfig.tpl
Labels: master

#11691 CRM-21773 Fix merging multi-value custom fields
  CRM/Dedupe/Merger.php
  tests/phpunit/CRM/Dedupe/MergerTest.php
Labels: master

#11722 CRM-21733: Set status override end date to null if no 'Override until selected date' is not selected
  CRM/Member/Form/Membership.php
Labels: master

#11758 CRM-21391 Convert Campaign to use core Task class
  CRM/Campaign/Form/Search.php
  CRM/Campaign/Task.php
Labels: master, merge on pass

#11745 Fix upgrade failures from zero value `trxn_date`
  CRM/Upgrade/Incremental/sql/4.7.19.mysql.tpl
Labels: master

#11759 CRM-21391 Convert Case to use core Task class
  CRM/Case/Form/Search.php
  CRM/Case/Task.php
Labels: master

#11766 Fixed template structure issues
  templates/CRM/Admin/Form/Setting/Component.tpl
  templates/CRM/Admin/Form/Setting/Debugging.tpl
  templates/CRM/Admin/Form/Setting/Mapping.tpl
  templates/CRM/Admin/Form/Setting/Path.tpl
  templates/CRM/Admin/Form/Setting/UF.tpl
  templates/CRM/Admin/Form/Setting/UpdateConfigBackend.tpl
  templates/CRM/Admin/Form/Setting/Url.tpl
  templates/CRM/Badge/Form/Layout.tpl
Labels: master

#11760 CRM-21391 Convert Grant to use core Task class
  CRM/Grant/Form/Search.php
  CRM/Grant/Form/Task.php
  CRM/Grant/Task.php
Labels: master

#11453 Update minimum php version to 5.5
  CRM/Upgrade/Form.php
  CRM/Upgrade/Incremental/General.php
Labels: master, merge on pass

#11768 ensure correct payment_instrument_id
  CRM/Core/Payment/AuthorizeNetIPN.php
  tests/phpunit/CRM/Core/Payment/AuthorizeNetIPNTest.php
Labels: master

#11757 CRM-21819 - Do not load 'Submit Credit Card Contribution' button if only pseudo-manual processor exists
  CRM/Financial/BAO/PaymentProcessor.php
Labels: master

#11770 Add 'huge' class to html textarea to match plaintext textarea
  templates/CRM/Admin/Form/MessageTemplates.tpl
Labels: master

#11749 CRM-21771: error when viewing event registration with linked contribu…
  CRM/Contribute/BAO/Contribution.php
  tests/phpunit/api/v3/ParticipantPaymentTest.php
Labels: 4.7.31-rc

#11775 CiviMember: use `fa-ban`, proper `crm-i` class for canceled auto-renew
  templates/CRM/Member/Form/Selector.tpl
  templates/CRM/Member/Page/Tab.tpl
Labels: master

#11734 CRM-21813 : Parameter list mismatch
  CRM/Event/BAO/Participant.php
Labels: master

#11774 NFC - Minor code cleanup in CKEditorConfig.php
  CRM/Admin/Page/CKEditorConfig.php
Labels: master

#11779 Fix template structure
  templates/CRM/Admin/Page/Mapping.tpl
  templates/CRM/Financial/Form/FinancialType.tpl
  templates/CRM/Grant/Page/DashBoard.tpl
Labels: master

#11788 Make template structure proper
  templates/CRM/Campaign/Form/Survey/Results.tpl
  templates/CRM/Pledge/Form/Pledge.tpl
Labels: master

#11791 4.7.31 rc
  CONTRIBUTORS.txt
  contributor-key.yml
  release-notes.md
  release-notes/4.7.31.md
Labels: master

#11793 Refs CRM-21837 - Missing states for Gabon
  CRM/Upgrade/Incremental/sql/4.7.32.mysql.tpl
  sql/civicrm_generated.mysql
  xml/templates/civicrm_state_province.tpl
Labels: master

#11792 Fix style glitches
  templates/CRM/Batch/Form/Entry.tpl
  templates/CRM/Batch/Form/Search.tpl
  templates/CRM/Event/Form/ManageEvent/Location.tpl
  templates/CRM/Financial/Form/Search.tpl
  templates/CRM/Pledge/Form/Pledge.tpl
  templates/CRM/Pledge/Form/Search/Common.tpl
Labels: master

#11790 dev/core#12: Added auto-scroll-up functionality between steps to crmUiWizard
  ang/crmUi.js
Labels: master

#11769 [REGRESSION] CRM-21806: Fix issues is search form when FULL_GROUP_BY_MODE enabled
  CRM/Contact/BAO/Query.php
  CRM/Contact/Selector.php
Labels: master

#11764 CRM-21391 Convert Contact to use core Task class
  CRM/Contact/Form/Task.php
  CRM/Contact/Task.php
  CRM/Core/Component.php
Labels: master

#11600 CRM-21720 Cleanup search classes to use enumerators instead of hardcoded values
  CRM/Contact/BAO/Query.php
  CRM/Contact/Form/Search.php
  CRM/Contact/Form/Search/Advanced.php
  CRM/Contact/Form/Search/Basic.php
  CRM/Contact/Form/Search/Criteria.php
  CRM/Contact/Form/Task/SaveSearch.php
  CRM/Contact/StateMachine/Search.php
Labels: master

#11763 CRM-21391 Convert Pledge to use core Task class
  CRM/Pledge/Form/Search.php
  CRM/Pledge/Task.php
Labels: master

#11780 CRM-21756: Freeze total amount field on Edit Contribution if related to Membership or Event registration
  CRM/Contribute/Form/Contribution.php
  templates/CRM/Contribute/Form/Contribution.tpl
  templates/CRM/Contribute/Page/Tab.hlp
Labels: master

#11762 CRM-21391 Convert Member to use core Task class
  CRM/Member/Form/Search.php
  CRM/Member/Form/Task.php
  CRM/Member/Task.php
Labels: master

#11761 CRM-21391 Convert Mailing to use core Task class
  CRM/Mailing/Task.php
Labels: master

#11680 CRM-21777 - Set readonly for the fields initialised in civicrm_settings.php
  CRM/Admin/Form/Setting.php
Labels: master

#11798 Update test to NOT accept a failure in the api call.
  tests/phpunit/CRM/Contribute/Form/ContributionTest.php
Labels: master

#11777 CRM-20608: IPN thinks Paypal Pro is Standard.
  CRM/Core/Payment/PayPalImpl.php
Labels: master

#11800 CRM-21667: Fix for timezone handoff from Drupal6 should take DST into account.
  CRM/Utils/System/Drupal6.php
Labels: master, merge on pass

#11799 E-notice fix.
  CRM/Contribute/Form/AbstractEditPayment.php
  CRM/Contribute/Form/AdditionalPayment.php
Labels: master, merge on pass

#11781 Remove hacks from CRM_Core_Menu for old unsupported versions
  CRM/Core/Menu.php
Labels: master

#11802 CRM-21777 - add ts to the message string
  CRM/Admin/Form/Setting.php
Labels: master

#11801 Add test for api money, fix net_amount calc
  CRM/Contribute/BAO/Contribution.php
  api/v3/Contribution.php
  tests/phpunit/api/v3/ContributionTest.php
Labels: has-test, master

#11796 Fix html template structure with classes, divs & tags
  CRM/Grant/BAO/Query.php
  templates/CRM/Grant/Form/Grant.tpl
  templates/CRM/Grant/Form/Search/Common.tpl
  templates/CRM/Grant/Form/Task/Delete.tpl
  templates/CRM/Profile/Page/Overlay.tpl
Labels: master

#11590 CRM-21576 Add a 'send SMS' permission
  CRM/Activity/BAO/Activity.php
  CRM/Activity/Form/ActivityLinks.php
  CRM/Contact/Task.php
  CRM/Core/Permission.php
  CRM/Core/xml/Menu/Admin.xml
  CRM/Core/xml/Menu/Contact.xml
  CRM/Mailing/Page/Browse.php
  CRM/Mailing/xml/Menu/Mailing.xml
  CRM/Upgrade/Incremental/php/FourSeven.php
  tests/phpunit/CRM/Activity/BAO/ActivityTest.php
  xml/templates/civicrm_navigation.tpl
Labels: has-test, master

#11721 Fix relationshipType, paymentProcessorType, Note & jobLog apis to support custom data
  CRM/Contact/BAO/RelationshipType.php
  CRM/Core/BAO/Note.php
  api/v3/JobLog.php
  api/v3/PaymentProcessorType.php
  api/v3/RelationshipType.php
  tests/phpunit/api/v3/SyntaxConformanceTest.php
Labels: master

#11808 CRM-21391 Fix for "Find Respondents" Search
  CRM/Campaign/Form/Search.php
Labels: master

#11704 dev/release/1 - Change numbering to 5.x.x
  CRM/Upgrade/Incremental/php/FiveZero.php
  CRM/Upgrade/Incremental/sql/5.0.0.mysql.tpl
  sql/civicrm_generated.mysql
  xml/version.xml
Labels: master

#11811 Fix transaction template
  templates/CRM/Financial/Form/BatchTransaction.tpl
Labels: master

#11813 Add pre and post hooks to the Survey entity
  CRM/Campaign/BAO/Survey.php
Labels: master

#11519 CRM-21659 - Add hook to CRM_Utils_System::redirect
  CRM/Utils/Hook.php
  CRM/Utils/System.php
  CRM/Utils/Url.php
  composer.json
  composer.lock
  tests/phpunit/CRM/Utils/SystemTest.php
Labels: master, merge on pass

#11815 Activity Form - Fix recently introduced warning
  CRM/Activity/Form/Activity.php
Labels: master, merge on pass

#11818 Fix template in pledge and batch
  templates/CRM/Batch/Form/Entry.tpl
  templates/CRM/Pledge/Form/Selector.tpl
Labels: master

#11797 CRM-21838 strip html tags from alerts when crm-notification-container div is not present
  js/Common.js
Labels: master

#11809 dev/core/17 Convert interview task to use Pseudoconstants
  CRM/Campaign/Form/Task/Interview.php
  CRM/Core/OptionGroup.php
Labels: master

#11827 Fix page layout for wordpress (dev/core/issues/21)
  templates/CRM/Contribute/Form/Contribution/Main.tpl
Labels: 5.0, master

#11820 CRM-21264 - Fix tabular formatting of contributions in merged letters grouped by contact
  CRM/Contribute/Form/Task/PDFLetterCommon.php
  tests/phpunit/CRM/Contribute/Form/Task/PDFLetterCommonTest.php
Labels: master

#11727 CRM-21807 - Deleted contacts included by default in Membership and co…
  CRM/Report/Form/Contribute/Detail.php
  CRM/Report/Form/Member/Detail.php
Labels: master

#11831 Version check test: in alphas don't test for site stats not provided for alphas
  tests/phpunit/CRM/Utils/versionCheckTest.php
Labels: master, merge on pass

#11786 CRM-21835 Gracefully switch Log Table Engines if Archive is not avali…
  CRM/Logging/Schema.php
  tests/phpunit/CRM/Logging/SchemaTest.php
Labels: has-test, master

#10403 CRM-20624
  CRM/Core/BAO/CustomOption.php
  CRM/Custom/Form/Option.php
  CRM/Custom/Page/AJAX.php
  templates/CRM/Custom/Form/Option.tpl
  templates/CRM/Custom/Page/Option.tpl
Labels: master

#11841 core/issues/26 - On behalf form fails to create new organisation
  CRM/Contribute/Form/Contribution/Confirm.php
Labels: master

#10783 CRM-20981 - Allow custom base-pages with less `crmApp` boilerplate
  Civi/Angular/AngularLoader.php
  Civi/Angular/Page/Main.php
Labels: master

#11819 CRM-21840: Show Options Edit Link for Radio and Checkbox Groups
  CRM/Core/BAO/CustomField.php
  CRM/Core/Form.php
  CRM/Core/Form/Renderer.php
  js/crm.optionEdit.js
Labels: master

#11199 CRM-21348: Don't hide the "edit" link from logged-in users in profile listings in joomla front-end
  CRM/Profile/Selector/Listings.php
Labels: master, wip

#11843 CRM-20790: Unit test to ensure relationships are created on import.
  CRM/Contact/Import/Parser/Contact.php
  tests/phpunit/CRM/Contact/Import/Parser/ContactTest.php
Labels: master

#11586 CRM-21711 When updating multiple memberships thru a contribution page custom fields are only updated on one
  CRM/Contribute/Form/Contribution/Confirm.php
  tests/phpunit/CRM/Contribute/Form/ContributionTest.php
Labels: has-test, master

#11848 CRM-21848 - Add unit test for on_hold mailing recipients
  tests/phpunit/api/v3/MailingTest.php
Labels: 5.0, merge on pass

#11844 Meld Address custom field display template with main custom field template
  templates/CRM/Contact/Form/Edit/Address/CustomData.tpl
  templates/CRM/Contact/Form/Edit/Address/CustomField.tpl
  templates/CRM/Custom/Form/CustomData.tpl
  templates/CRM/Custom/Form/CustomField.tpl
  templates/CRM/Custom/Form/Edit/CustomField.tpl
Labels: master

#11852 merge 5.0 to master
  CRM/Core/BAO/RecurringEntity.php
  CRM/Core/Page/AJAX/RecurringEntity.php
  tests/phpunit/api/v3/MailingTest.php
Labels: master

#11858 [NFC] fix line endings, using windows line endings, change to 'unix
  templates/CRM/Core/Form/RecurringEntity.tpl
Labels: master

#11855 CRM-21677 - reduce unnecessary address joins on activity & contact detail reports
  CRM/Report/Form.php
  CRM/Report/Form/Activity.php
  CRM/Report/Form/ActivitySummary.php
  CRM/Report/Form/Contact/Detail.php
  CRM/Report/Form/Contact/Summary.php
Labels: master, merge on pass

#11860 [nfc] Minor test tidy ups
  tests/phpunit/CRM/Contribute/BAO/ContributionRecurTest.php
  tests/phpunit/CRM/Contribute/Form/SearchTest.php
Labels: master, merge on pass

#11298 CRM-19151: Add the ability to merge memberships without data loss
  CRM/Dedupe/Merger.php
  CRM/Member/BAO/Membership.php
Labels: master

#11856 Fix ajax error on rendering multi custom data tab when field limit reached
  CRM/Profile/Page/MultipleRecordFieldsListing.php
Labels: master

#11861 Fix bugs with hook params, functionality on contact searches
  CRM/Core/Task.php
Labels: 5.0

#11857 Consolidate CustomData code into shared tpl
  templates/CRM/Contact/Form/Edit/Address/CustomData.tpl
  templates/CRM/Contact/Form/Edit/CustomData.tpl
  templates/CRM/Custom/Form/CustomData.tpl
  templates/CRM/Custom/Form/Edit/CustomData.tpl
Labels: master

#10496 CRM-20719 : Show warning on system status page if reply_id for mailing is not set to any default
  CRM/Utils/Check/Component/Env.php
Labels: master

#11862 Fix template structure
  CRM/Contact/Form/Merge.php
  templates/CRM/Activity/Form/Search/Common.tpl
  templates/CRM/Campaign/Form/Search.tpl
  templates/CRM/Group/Form/Edit.tpl
Labels: master

#11828 Revert "CRM-8140: Not possible to select fields for export when using Custom Searches"
  CRM/Export/Form/Select.php
  templates/CRM/Export/Form/Select.tpl
Labels: 5.0

#11836 Dev/Core 25 Wrap the mailing split_job function in a transaction to e…
  CRM/Mailing/BAO/MailingJob.php
Labels: master, merge on pass

#11829 Fix regression on CiviRules search due to exception handling
  CRM/Contact/Selector.php
Labels: 5.0

#11824 CRM-21682 Membership Renewal Tests
  tests/phpunit/CRM/Core/Payment/PayPalIPNTest.php
  tests/phpunit/CRM/Core/Payment/PayPalProIPNTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/api/v3/ContributionPageTest.php
Labels: master

#11816 core/issues/15 Line item fix with attempt to determine how it is hit
  CRM/Price/BAO/LineItem.php
  tests/phpunit/api/v3/ContributionTest.php
Labels: master

#11825 Add commenting to explain +1/-1 days for membership dates calc
  CRM/Member/BAO/MembershipType.php
Labels: master

#11087 CRM-19850 - Add a offline membership without 'record payment' option,…
  CRM/Contribute/Form/Search.php
  templates/CRM/Member/Form/MembershipCommon.tpl
Labels: master

#11086 CRM-21277: Suppress warnings while finding install directory.
  CRM/Utils/System/WordPress.php
Labels: master

#11609 CRM-21203 revisited - Joomla 3.8 extra fixes for cli.php
  CRM/Utils/System/Joomla.php
Labels: master

#11869 Fix template structures
  templates/CRM/Admin/Form/MessageTemplates.tpl
  templates/CRM/Admin/Form/Setting/Mail.tpl
  templates/CRM/Admin/Page/MailSettings.tpl
  templates/CRM/Contribute/Form/Contribution.tpl
  templates/CRM/Contribute/Form/ContributionPage/Amount.tpl
  templates/CRM/Contribute/Form/SoftCredit.tpl
  templates/CRM/Custom/Form/Group.tpl
  templates/CRM/Friend/Form/Friend.tpl
Labels: master

#11864 Increment minimum upgradable version
  CRM/Core/BAO/Setting.php
  CRM/Core/I18n/SchemaStructure_2_2_0.php
  CRM/Core/I18n/SchemaStructure_3_0_alpha1.php
  CRM/Core/I18n/SchemaStructure_3_0_beta1.php
  CRM/Core/I18n/SchemaStructure_3_0_beta4.php
  CRM/Core/I18n/SchemaStructure_3_1_alpha1.php
  CRM/Core/I18n/SchemaStructure_3_1_beta2.php
  CRM/Core/I18n/SchemaStructure_3_2_beta4.php
  CRM/Core/I18n/SchemaStructure_3_3_beta1.php
  CRM/Core/I18n/SchemaStructure_3_4_0.php
  CRM/Core/I18n/SchemaStructure_3_4_beta2.php
  CRM/Core/I18n/SchemaStructure_3_4_beta3.php
  CRM/Core/I18n/SchemaStructure_4_1_0.php
  CRM/Core/I18n/SchemaStructure_4_1_alpha1.php
  CRM/Upgrade/4.1.alpha1.msg_template/civicrm_msg_template.tpl
  CRM/Upgrade/4.1.alpha1.msg_template/message_templates/contribution_online_receipt_html.tpl
  CRM/Upgrade/4.1.alpha1.msg_template/message_templates/event_online_receipt_html.tpl
  CRM/Upgrade/4.1.alpha1.msg_template/message_templates/event_online_receipt_text.tpl
  CRM/Upgrade/Form.php
  CRM/Upgrade/Incremental/php/FourOne.php
  CRM/Upgrade/Incremental/sql/4.1.0.mysql.tpl
  CRM/Upgrade/Incremental/sql/4.1.1.mysql.tpl
  CRM/Upgrade/Incremental/sql/4.1.2.mysql.tpl
  CRM/Upgrade/Incremental/sql/4.1.3.mysql.tpl
  CRM/Upgrade/Incremental/sql/4.1.alpha1.mysql.tpl
  CRM/Upgrade/Incremental/sql/4.1.alpha2.mysql.tpl
  CRM/Upgrade/Incremental/sql/4.1.beta1.mysql.tpl
  CRM/Upgrade/Incremental/sql/4.1.beta2.mysql.tpl
  CRM/Upgrade/Incremental/sql/4.1.beta3.mysql.tpl
  Civi/Core/SettingsBag.php
Labels: master

#11867 CRM-21677 reduce unnecessary joins in membership reports
  CRM/Report/Form/Member/ContributionDetail.php
  CRM/Report/Form/Member/Detail.php
  CRM/Report/Form/Member/Lapse.php
Labels: master

#11697 CRM-21784 Display custom data when viewing recurring contributions
  CRM/Contribute/BAO/ContributionRecur.php
  CRM/Contribute/Form/UpdateSubscription.php
  CRM/Contribute/Page/ContributionRecur.php
  CRM/Contribute/Page/Tab.php
  CRM/Core/BAO/CustomGroup.php
  CRM/Financial/BAO/PaymentProcessor.php
  templates/CRM/Contribute/Form/Selector.tpl
  templates/CRM/Contribute/Form/UpdateSubscription.tpl
  templates/CRM/Contribute/Page/ContributionRecur.tpl
  templates/CRM/Contribute/Page/ContributionTotals.tpl
  templates/CRM/Contribute/Page/Tab.tpl
Labels: master

#11872 CiviUnitTestCase - Extract Api3TestTrait and Api3DocTrait
  Civi/Test/Api3DocTrait.php
  Civi/Test/Api3TestTrait.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: master, merge on pass

#11879 CRM-21842 - Fix links to documentation
  templates/CRM/Contact/Form/Contact.hlp
  templates/CRM/Contact/Form/OnBehalfOf.tpl
Labels: master, merge on pass

#11863 Tweak layout on contribution view screen to make payments clearer
  CRM/Contribute/Form/ContributionView.php
  templates/CRM/Contribute/Form/ContributionView.tpl
  templates/CRM/Contribute/Page/PaymentInfo.tpl
Labels: master

#11336 CRM-21489 document new constant in civicrm.settings.php
  templates/CRM/common/civicrm.settings.php.template
Labels: master

#11807 "hold_date" not updated if civimail_multiple_bulk_emails is true + test
  CRM/Core/BAO/Email.php
  tests/phpunit/api/v3/EmailTest.php
Labels: has-test, master

#11886 [NFC] Fix mispelled variable and simplify a couple of other vars
  CRM/Event/BAO/Participant.php
Labels: master, merge on pass

#11888 NFC Fix function name typo
  CRM/Utils/Rule.php
  CRM/Utils/Type.php
  tests/phpunit/CRM/Utils/RuleTest.php
Labels: master, merge on pass

#11891 CRM-21434: Add activities to recent items stack
  CRM/Activity/Form/Activity.php
  CRM/Activity/Form/ActivityView.php
Labels: master

#11703 Remove cloning hack from export and add unit tests
  CRM/Export/BAO/Export.php
  api/v3/Campaign.php
  tests/phpunit/CRM/Export/BAO/ExportTest.php
Labels: master

#11889 CRM-21677 reduce unnecessary joins in reports
  CRM/Report/Form/Contact/CurrentEmployer.php
  CRM/Report/Form/Contribute/Bookkeeping.php
  CRM/Report/Form/Event/ParticipantListCount.php
  CRM/Report/Form/Event/ParticipantListing.php
  CRM/Report/Form/Membership/Summary.php
Labels: master

#11878 CRM-21791 Use name for comparison instead of label (alternative)
  CRM/Financial/Form/FinancialBatch.php
Labels: master

#11898 CRM-21677 reduce unnecessary joins in reports
  CRM/Report/Form/Contribute/Detail.php
  CRM/Report/Form/Contribute/History.php
  CRM/Report/Form/Contribute/HouseholdSummary.php
  CRM/Report/Form/Contribute/OrganizationSummary.php
  CRM/Report/Form/Contribute/Recur.php
Labels: master

#11904 (dev/mail/5) "New Mailing" - Previews should not schedule real blasts
  ang/crmMailing/services.js
Labels: 5.0

#11911 (dev/mail/7) On 'New Mailing' review page, it doesn't show recipients count
  ang/crmMailing/BlockReview.html
Labels: 5.0

#11668 CRM-21763 Util to subtract currencies using integers for precision
  CRM/Core/BAO/FinancialTrxn.php
  CRM/Utils/Money.php
  tests/phpunit/CRM/Core/BAO/FinancialTrxnTest.php
  tests/phpunit/CRM/Utils/MoneyTest.php
Labels: master
