Repository civicrm/civicrm-core, pull requests merged in 2019-02, with the labels that each got.

#13518 l10n.js - Reload when logging in as new user
  CRM/Core/Resources.php
Labels: master

#13520 use number widget for weight fields in all forms
  CRM/Admin/Form/LabelFormats.php
  CRM/Admin/Form/ParticipantStatusType.php
  CRM/Admin/Form/PdfFormats.php
  CRM/Campaign/Form/Survey/Results.php
  CRM/Campaign/Form/SurveyType.php
  CRM/Custom/Form/Field.php
  CRM/Custom/Form/Group.php
  CRM/Custom/Form/Option.php
  CRM/Member/Form/MembershipStatus.php
  CRM/Price/Form/Field.php
  CRM/Price/Form/Option.php
  CRM/Report/Form/Register.php
  CRM/UF/Form/Field.php
  CRM/UF/Form/Group.php
Labels: master

#13401 dev/mail#32 - Further checks - making mailing test email non-case-sensitive
  api/v3/Mailing.php
Labels: master

#13524 Revert fix causing unreleased regression
  CRM/Contact/BAO/Group.php
  CRM/Contact/Form/Search/Advanced.php
  tests/phpunit/CRM/Contact/BAO/GroupTest.php
Labels: 5.10, merge on pass

#13525 5.10
  CRM/Contact/BAO/Group.php
  CRM/Contact/Form/Search/Advanced.php
  tests/phpunit/CRM/Contact/BAO/GroupTest.php
Labels: master

#13527 dev/core#693 : On contact summary page, on submitting a 'New Case' form doesn't redirect to 'Manage Case' screen
  templates/CRM/Case/Page/Tab.tpl
Labels: master

#13522 Performance fix for alternate getActivity listing function
  CRM/Activity/BAO/Activity.php
  tests/phpunit/CRM/Activity/BAO/ActivityTest.php
Labels: has-test, master, sig:performance

#13489 (dev/core#635) Deprecate CRM_Core_BAO_Cache for I/O. Optionally redirect I/O to Redis or Memcache.
  CRM/Core/BAO/Cache.php
  CRM/Core/BAO/Cache/Psr16.php
  CRM/Core/Config.php
  templates/CRM/common/civicrm.settings.php.template
Labels: master

#13526 use number widget for weight and other numeric fields in more forms
  CRM/Admin/Form/Options.php
  CRM/Event/Form/ManageEvent/EventInfo.php
  CRM/Member/Form/Membership.php
  CRM/Member/Form/MembershipRenewal.php
  CRM/PCP/BAO/PCP.php
  CRM/Pledge/Form/Pledge.php
  CRM/Price/Form/Option.php
Labels: master, merge on pass

#12834 Respect pre hook for relationship to alter id in $params
  CRM/Contact/BAO/Relationship.php
Labels: master, merge on pass, sig:extension support

#13533 Prev next
  CRM/Contact/BAO/Query.php
  CRM/Contact/Selector.php
Labels: 5.10, merge on pass

#13535 5.10 to master
  CRM/Contact/BAO/Query.php
  CRM/Contact/Selector.php
Labels: master

#13390 fixes core#609 - view 'Advanced Search' links without 'view all conta…
  CRM/Mailing/BAO/Mailing.php
Labels: master, merge ready

#13537 dev/core#680 make receive_date required on backoffice contribution form
  CRM/Contribute/Form/Contribution.php
  api/v3/Contribution.php
Labels: 5.10, merge on pass

#13546 5.10 to master
  CRM/Contribute/Form/Contribution.php
  api/v3/Contribution.php
Labels: master

#13547 Re-run gencode for fix on PriceField DAO
  CRM/Price/DAO/PriceFieldValue.php
Labels: master, merge on pass

#13536 dev/core#651 Fix group by on export soft credits (possible recent regression, clearly wrong).
  CRM/Export/BAO/Export.php
Labels: 5.10

#13548 5.10 to master
  CRM/Export/BAO/Export.php
Labels: master

#13544 core/issues/698, send correct MIME type for .jpg files
  CRM/Utils/File.php
Labels: master

#13494 5.10.0 release notes
  contributor-key.yml
  release-notes.md
  release-notes/5.10.0.md
  release-notes/5.9.1.md
Labels: 5.10

#13550 5.10
  contributor-key.yml
  release-notes.md
  release-notes/5.10.0.md
  release-notes/5.9.1.md
Labels: master

#13552 Update 5.10.0.md
  release-notes/5.10.0.md
Labels: master, merge on pass

#13529 dev/core#690 - Civi\API - Fix entity permission check for trusted calls
  CRM/Core/DAO/AllCoreTables.php
  Civi/API/Subscriber/DynamicFKAuthorization.php
  tests/phpunit/CRM/Core/DAO/AllCoreTablesTest.php
  tests/phpunit/Civi/API/Subscriber/DynamicFKAuthorizationTest.php
  tests/phpunit/api/v3/AttachmentTest.php
Labels: has-test, master, merge on pass

#13333 Make submitOnce() button js into a button parameter
  CRM/Case/Form/Activity/OpenCase.php
  CRM/Core/Form.php
Labels: master

#13549 dev/core/issues/700, Show Qill when searched using contact id
  CRM/Contact/BAO/Query.php
Labels: master

#13555 CRM.loadScript improvements
  ang/crmUtil.js
  js/Common.js
Labels: master, merge on pass

#13187 Optimize CRM_Core_BAO_FinancialTrxn::getTotalPayment
  CRM/Contribute/BAO/Contribution.php
  CRM/Core/BAO/FinancialTrxn.php
Labels: master

#13287 (REF) Rename variables and adjust variable definitions for Event Register form
  CRM/Event/Form/Registration/Register.php
Labels: master

#13404 Show Add to group on create new report after refresh of result
  CRM/Report/Form.php
Labels: master, ok-without-test

#13327 Used buildoptions function to get all groups
  api/v3/Contact.php
  tests/phpunit/api/v3/ContactTest.php
Labels: has-test, master

#13560 dev/core#562 Remove free calls from Activity and Member sections of CRM
  CRM/Activity/BAO/Activity.php
  CRM/Activity/Page/AJAX.php
  CRM/Member/BAO/Membership.php
  CRM/Member/BAO/MembershipLog.php
  CRM/Member/BAO/MembershipStatus.php
  CRM/Member/BAO/MembershipType.php
Labels: master, merge on pass

#13558 Add unit test on getContributionBalance fn (#13187)
  tests/phpunit/CRM/Event/BAO/ChangeFeeSelectionTest.php
Labels: master, merge on pass

#13569 Fix contact ID help on advanced search
  templates/CRM/Contact/Form/Contact.hlp
  templates/CRM/Contact/Form/Contact.tpl
Labels: master

#13564 Remove hurty free calls from campaign and case
  CRM/Campaign/BAO/Campaign.php
  CRM/Campaign/BAO/Survey.php
  CRM/Campaign/Form/Task/Interview.php
  CRM/Case/BAO/Case.php
Labels: master

#13570 Fix regression whereby making receive_date required breaks back office cc
  CRM/Contribute/Form/Contribution.php
Labels: 5.10, merge on pass

#13572 Fix regression whereby making receive_date required breaks back offic…
  CRM/Contribute/Form/Contribution.php
Labels: 5.11, merge on pass

#13574 Release notes for 5.10.1 release
  release-notes/5.10.1.md
Labels: 5.10, merge on pass

#13575 Release notes for 5.10.1 release
  release-notes/5.10.1.md
Labels: 5.11

#13576 5.11 to master
  CRM/Contribute/Form/Contribution.php
  release-notes/5.10.1.md
Labels: master

#13577 Fix typo and space
  CRM/Contribute/BAO/ContributionRecur.php
  CRM/Contribute/Form/ContributionView.php
Labels: master

#13581 dev/core#715 - Fix delete action on RelationshipType form
  CRM/Core/Form.php
  CRM/Core/Form/EntityFormTrait.php
Labels: 5.11

#13585 5.11 to master
  CRM/Core/Form.php
  CRM/Core/Form/EntityFormTrait.php
Labels: master

#13342 Remove activitystatus js. Add submitOnce handler for activity create
  CRM/Activity/Form/Activity.php
  templates/CRM/Activity/Form/Activity.tpl
  templates/CRM/Activity/Form/ActivityJs.tpl
  templates/CRM/Case/Form/Activity.tpl
Labels: master, merge on pass, ok-without-test

#13562 [REF] Minor readability cleanup
  tests/phpunit/CRM/Event/BAO/AdditionalPaymentTest.php
Labels: master, merge on pass

#13583 [REF] switch from (undeclared) class property to local variable.
  CRM/Contact/Page/View/UserDashBoard.php
Labels: master

#13523 dev/core#691 Make default country optional on setting form
  CRM/Admin/Form/SettingTrait.php
  settings/Localization.setting.php
  tests/phpunit/CRM/Contact/Import/Parser/ContactTest.php
  tests/phpunit/api/v3/ProfileTest.php
Labels: master

#13573 dev/core/issues/714, Inline edit should be disabled if user doesn't have edit group permission
  templates/CRM/Group/Form/Search.tpl
Labels: master, ok-without-test, sig:bug

#13590 dev/core#715 - Fix delete action on RelationshipType form
  CRM/Core/Form.php
  CRM/Core/Form/EntityFormTrait.php
Labels: 5.10, merge on pass, sig:bug

#13557 Improves styling on Joomla! upgrade screen
  css/joomla.css
Labels: master

#13538 dev/core#397 Dedupe for Individual Birth Date Results in Error
  CRM/Dedupe/BAO/Rule.php
  tests/phpunit/CRM/Dedupe/DedupeFinderTest.php
  tests/phpunit/CRM/Member/Form/MembershipTest.php
Labels: master, merge ready

#13584 [REF} User api rather than selector for rendering contributions on user dashboard
  CRM/Contribute/Page/UserDashboard.php
  templates/CRM/Contribute/Page/UserDashboard.tpl
  tests/phpunit/CRM/Contact/Page/View/UserDashBoardTest.php
Labels: has-test, master

#13539 dev/core#469 Fix Error on action 'Email - schedule/send via CiviMail' with multiple event names filter
  CRM/Contact/Form/Task.php
Labels: master

#13528 dev/core#684 - Case Manager not updating correctly
  CRM/Case/XMLProcessor/Process.php
  tests/phpunit/CRM/Case/BAO/CaseTypeForkTest.php
Labels: has-test, master

#13571 dev/report#7 fix trxn_date on bookkeeping report
  CRM/Report/Form/Contribute/Bookkeeping.php
Labels: master, sig:bug

#13517 Find Contributions columns/headers not aligned when "Contributions OR Soft Credits?" filter set to "Soft Credits Only"
  templates/CRM/Contribute/Form/Selector.tpl
Labels: master, ok-without-test, sig:bug

#13561 Add new Payment.sendconfirmation api
  CRM/Contribute/BAO/Contribution.php
  CRM/Core/BAO/FinancialTrxn.php
  CRM/Financial/BAO/Payment.php
  api/v3/Payment.php
  tests/phpunit/api/v3/PaymentTest.php
Labels: master

#13595 dev/core#681 Fatal Error on submitting "Change Case Status" activity form
  CRM/Case/Form/Activity/ChangeCaseStatus.php
Labels: 5.10

#13592 (dev/core#705) Disabling Alphabetical Pager is not respected for cont…
  CRM/Contribute/Page/ContributionPage.php
Labels: easy-review, master, ok-without-test, sig:bug

#13593 dev/core#721 Fix regression on refreshing group_contact cache before checking acls
  CRM/ACL/BAO/ACL.php
Labels: 5.11, merge on pass

#13597 dev/core#721 Fix regression on refreshing group_contact cache before checking acls
  CRM/ACL/BAO/ACL.php
Labels: 5.10, merge on pass

#13598 Add in release notes for 5.10.2
  release-notes/5.10.2.md
Labels: 5.10, merge on pass

#13599 Add in release notes for 5.10.2
  release-notes/5.10.2.md
Labels: 5.11

#13602 5.11 to master
  CRM/ACL/BAO/ACL.php
  release-notes/5.10.2.md
Labels: master

#13432 dev/core#657 - Add filter for country on Repeat Contributions Report
  CRM/Report/Form/Contribute/Repeat.php
Labels: master, ok-without-test

#13600 [REF] extract chunk of code to a separate function
  CRM/Profile/Form.php
Labels: master, merge on pass

#13605 dev/core#720 add unit test, remove legacy code style.
  CRM/Contact/BAO/Query.php
  tests/phpunit/CRM/Contact/BAO/QueryTest.php
  tests/phpunit/CRMTraits/Financial/FinancialACLTrait.php
  tests/phpunit/CRMTraits/Financial/PriceSetTrait.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: has-test, master, merge on pass

#13591 fixes dev/core#683 Incorrectly encoded state and country names
  CRM/Upgrade/Incremental/sql/5.12.alpha1.mysql.tpl
Labels: master, merge ready

#13611 Add in Exception API to support the refactor of Dedupe Exception Page
  CRM/Dedupe/DAO/Exception.php
  api/v3/Exception.php
  xml/schema/Dedupe/Exception.xml
Labels: master

#13563 [REF] Fix silly function to do less handling of non-existent scenarios
  CRM/Contribute/BAO/Contribution.php
  CRM/Core/BAO/FinancialTrxn.php
  tests/phpunit/CRM/Financial/BAO/FinancialAccountTest.php
Labels: master, ok-without-test, sig:code maintenance readability testability

#13587 [REF] Move addSelectWhere-like function to be located on BAO_Contribution
  CRM/Contribute/BAO/Contribution.php
  CRM/Financial/BAO/FinancialType.php
Labels: master

#13608 [REF] extract calculation of basic stats
  CRM/Contact/BAO/Query.php
Labels: has-test, master

#13425 Add install and runtime status warnings if MySQL utf8mb4 is not supported
  CRM/Utils/Check/Component/Env.php
  Civi/Install/Requirements.php
  install/index.php
Labels: master

#13612 Move l10n.js to coreResourcesList
  CRM/Core/Resources.php
  tests/phpunit/CRM/Core/ResourcesTest.php
Labels: has-test, master

#13373 fixes core#580 - view all groups when appropriately permissioned
  CRM/ACL/BAO/ACL.php
  CRM/Contact/BAO/Group.php
  CRM/Contact/BAO/GroupContact.php
  CRM/Core/PseudoConstant.php
  tests/phpunit/CRM/Group/Page/AjaxTest.php
Labels: has-test, master

#13613 Auto-open campaign widget and sort by start date
  CRM/Campaign/BAO/Campaign.php
  CRM/Campaign/Form/Petition.php
  CRM/Campaign/Form/Survey/Main.php
  api/v3/Campaign.php
Labels: 5.11, merge on pass

#13615 5.11 to master
  CRM/Campaign/BAO/Campaign.php
  CRM/Campaign/Form/Petition.php
  CRM/Campaign/Form/Survey/Main.php
  api/v3/Campaign.php
Labels: master

#13614 [REF] extract calculation of mode stat
  CRM/Contact/BAO/Query.php
Labels: has-test, master, merge on pass

#13606 Fix (sometimes serious) performance problem on submitting profiles for specified contacts
  CRM/Profile/Form.php
Labels: master

#13617 Remove tests that no longer work due to dead service
  tests/phpunit/CRM/Utils/GeocodeTest.php
Labels: master, merge on pass

#13616 [REF] extract add median to stats
  CRM/Contact/BAO/Query.php
Labels: has-test, master, merge on pass

#13618 [Test support] Add extra output info when getsingle fails as this seems to be common in intermittant fails
  Civi/Test/Api3TestTrait.php
Labels: master

#13499 If a profile is used to create a contact with a subtype the contact will not have any existing subtypes
  CRM/Contact/BAO/Contact.php
Labels: master

#13601 Always load recaptcha JS over HTTPS
  CRM/Utils/ReCAPTCHA.php
Labels: master

#13623 Remove long block of commented out code from 4 years ago
  CRM/Member/Page/DashBoard.php
Labels: master

#13619 [REF] Remove unused function parameter
  CRM/Contribute/Form/Contribution/Confirm.php
Labels: master

#13621 [code cleanup] Default wrong declared
  CRM/Activity/Form/Search.php
  CRM/Case/Form/Search.php
  CRM/Contribute/Form/Search.php
  CRM/Event/Form/Search.php
  CRM/Grant/Form/Search.php
  CRM/Member/Form/Search.php
  CRM/Pledge/Form/Search.php
Labels: master

#13622 [REF] extract basic soft credit stats to separate function
  CRM/Contact/BAO/Query.php
Labels: master

#13626 [REF] extract cancelled stats to own function
  CRM/Contact/BAO/Query.php
Labels: has-test, master, merge on pass

#13624 [Code cleanup] Remove unused $stationery_path parameter
  CRM/Utils/PDF/Utils.php
Labels: master, merge on pass

#13628 Standardize format for entityRef create links
  CRM/Campaign/BAO/Campaign.php
  CRM/Contact/BAO/Contact.php
  CRM/Contact/Form/Edit/Address.php
  CRM/Core/BAO/UFGroup.php
  CRM/Core/Form.php
  CRM/Core/Resources.php
  js/Common.js
Labels: master, merge on pass

#13607 dev/core#720 [REF] refactor out components of contributionSummary function
  CRM/Contact/BAO/Query.php
Labels: has-test, master

#13579 Contribution/ContributionRecur metadata updates for EntityForm
  CRM/Contribute/DAO/ContributionRecur.php
  xml/schema/Contribute/Contribution.xml
  xml/schema/Contribute/ContributionRecur.xml
Labels: master, sig:code maintenance readability testability

#13632 [REF] Remove useless class CRM_Report_Form_Event
  CRM/Report/Form/Event.php
  CRM/Report/Form/Event/Income.php
  CRM/Report/Form/Event/IncomeCountSummary.php
  CRM/Report/Form/Event/ParticipantListCount.php
  CRM/Report/Form/Event/ParticipantListing.php
  CRM/Report/Form/Event/Summary.php
Labels: master, merge on pass

#13631 EntityRef - standardize on PascalCase for entity name and fix minor bug
  CRM/Campaign/BAO/Campaign.php
  CRM/Campaign/Form/Petition.php
  CRM/Campaign/Form/Survey/Main.php
  CRM/Case/BAO/Case.php
  CRM/Case/Form/AddToCaseAsRole.php
  CRM/Contact/BAO/Contact.php
  CRM/Core/BAO/CustomField.php
  CRM/Core/Form.php
  CRM/Core/Form/Renderer.php
  CRM/Core/Form/Tag.php
  CRM/Core/Resources.php
  CRM/Event/BAO/Query.php
  CRM/Event/Form/ManageEvent/Conference.php
  CRM/Event/Form/Participant.php
  CRM/Report/Form/Event/ParticipantListCount.php
  CRM/Report/Form/Event/ParticipantListing.php
  js/Common.js
  settings/Multisite.setting.php
Labels: master, merge on pass

#13543 Fix html2pdf default PDF format when multiple pdf_format are available.
  CRM/Utils/PDF/Utils.php
Labels: master

#13629 [Test changes] Mailing job test use
  tests/phpunit/api/v3/MailingTest.php
Labels: master

#13630 dev/core#720 Remove median & mode stats from contribution summary in order to improve performance
  CRM/Contact/BAO/Query.php
  CRM/Contribute/BAO/Contribution.php
  CRM/Report/Form/Contribute/Summary.php
  templates/CRM/Contribute/Page/ContributionTotals.tpl
  tests/phpunit/CRM/Contact/BAO/QueryTest.php
Labels: master

#13637 dev/core#737 - SMS not sent if 'Send Immediately' option is chosen on…
  CRM/SMS/Form/Schedule.php
Labels: 5.11, merge on pass

#13636 Remove another instance of 'lower'
  CRM/Contribute/BAO/Query.php
Labels: master, merge on pass

#13639 5.11
  CRM/SMS/Form/Schedule.php
Labels: master

#13534 (dev/core#696) Changes to copied event phone and email reflects in or…
  CRM/Event/Form/ManageEvent/Location.php
Labels: master, merge ready

#13609 Payment.sendconfirmation api - add further tpl variables.
  CRM/Contribute/BAO/Contribution.php
  CRM/Financial/BAO/Payment.php
  tests/phpunit/api/v3/PaymentTest.php
Labels: has-test, master

#13620 [unused code cleanup] Remove unused 'signupType' url support
  CRM/Activity/Form/Search.php
  CRM/Member/Page/DashBoard.php
Labels: master

#13641 dev/core#737 - SMS not sent if 'Send Immediately' option is chosen on
  CRM/SMS/Form/Schedule.php
Labels: 5.10, merge on pass

#13642 Authorizenet test - reduce chance of intermittent fails
  tests/phpunit/CRM/Core/Payment/AuthorizeNetTest.php
Labels: master

#13610 Payment.sendconfirmation api - add further tpl variables.
  CRM/Financial/BAO/Payment.php
  tests/phpunit/api/v3/PaymentTest.php
Labels: master

#13655 Update Payment Notification to use greeting, remove text to 'Please print this confirmation for your records.
  CRM/Contribute/Form/AdditionalPayment.php
  CRM/Financial/BAO/Payment.php
  CRM/Upgrade/Incremental/MessageTemplates.php
  tests/phpunit/CRM/Contribute/Form/AdditionalPaymentTest.php
  tests/phpunit/api/v3/PaymentTest.php
  xml/templates/message_templates/payment_or_refund_notification_html.tpl
  xml/templates/message_templates/payment_or_refund_notification_text.tpl
Labels: master

#13656 [REF] minor cleanup of groupBy definition.
  CRM/Contact/BAO/Query.php
Labels: master

#13650 [REF] minor code cleanup - do not build order var just to hurt brains
  CRM/Contact/BAO/Query.php
Labels: master

#13659 /dev/core#716 - Add decimals in Contribution Amount on Repeat Contrib…
  CRM/Report/Form/Contribute/Repeat.php
Labels: master, merge on pass

#13660 5.11 - merge in security
  CRM/Batch/BAO/Batch.php
  CRM/Campaign/Selector/Search.php
  CRM/Contact/BAO/Contact/Utils.php
  CRM/Contact/BAO/Query.php
  CRM/Contact/Selector.php
  CRM/Core/BAO/CustomField.php
  CRM/Core/BAO/CustomGroup.php
  CRM/Core/BAO/File.php
  CRM/Core/Form/Renderer.php
  CRM/Core/Page/File.php
  CRM/Core/PrevNextCache/Interface.php
  CRM/Core/PrevNextCache/Redis.php
  CRM/Core/PrevNextCache/Sql.php
  CRM/PCP/Page/PCPInfo.php
  CRM/Profile/Form.php
  CRM/Utils/Money.php
  api/v3/Attachment.php
  js/Common.js
  release-notes/5.10.3.md
  templates/CRM/Logging/ReportDetail.tpl
  tests/phpunit/CRM/Core/Smarty/plugins/CrmMoneyTest.php
  tests/phpunit/CRM/Utils/MoneyTest.php
  tests/phpunit/E2E/Core/PrevNextTest.php
  tests/phpunit/api/v3/AttachmentTest.php
  tests/phpunit/api/v3/ContactTest.php
Labels: 5.11, merge on pass

#13661 5.11 to master
  CRM/Batch/BAO/Batch.php
  CRM/Campaign/Selector/Search.php
  CRM/Contact/BAO/Contact/Utils.php
  CRM/Contact/BAO/Query.php
  CRM/Contact/Selector.php
  CRM/Core/BAO/CustomField.php
  CRM/Core/BAO/CustomGroup.php
  CRM/Core/BAO/File.php
  CRM/Core/Form/Renderer.php
  CRM/Core/Page/File.php
  CRM/Core/PrevNextCache/Interface.php
  CRM/Core/PrevNextCache/Redis.php
  CRM/Core/PrevNextCache/Sql.php
  CRM/PCP/Page/PCPInfo.php
  CRM/Profile/Form.php
  CRM/Utils/Money.php
  api/v3/Attachment.php
  js/Common.js
  release-notes/5.10.3.md
  templates/CRM/Logging/ReportDetail.tpl
  tests/phpunit/CRM/Core/Smarty/plugins/CrmMoneyTest.php
  tests/phpunit/CRM/Utils/MoneyTest.php
  tests/phpunit/E2E/Core/PrevNextTest.php
  tests/phpunit/api/v3/AttachmentTest.php
  tests/phpunit/api/v3/ContactTest.php
Labels: master

#13662 Deploy hotfix to fix dev/core#746 until tests can be written for fix
  CRM/Contact/BAO/Query.php
  tests/phpunit/CRM/Contact/BAO/GroupContactCacheTest.php
Labels: 5.11, merge on pass

#13667 Deploy hotfix to fix dev/core#746 until tests can be written for fix
  CRM/Contact/BAO/Query.php
  tests/phpunit/CRM/Contact/BAO/GroupContactCacheTest.php
Labels: 5.10

#13649 Switch additional payment form to use Payment.sendconfirmation api
  CRM/Contribute/Form/AdditionalPayment.php
  tests/phpunit/CRM/Contribute/Form/AdditionalPaymentTest.php
Labels: master

#13364 REF Convert deprecated functions to buildOptions for case
  CRM/Activity/Selector/Activity.php
  CRM/Activity/Selector/Search.php
  CRM/Case/BAO/Case.php
  Civi/CCase/Analyzer.php
  Civi/CCase/SequenceListener.php
Labels: master, merge ready

#13670 reporting#10 - fix pagination on Contribution Detail report
  CRM/Report/Form/Contribute/Detail.php
Labels: 5.11, merge on pass

#13676 5.11 to master
  CRM/Contact/BAO/Query.php
  CRM/Report/Form/Contribute/Detail.php
  tests/phpunit/CRM/Contact/BAO/GroupContactCacheTest.php
Labels: master

#13671 reporting-11 - fix Soft Credit report with full group by
  CRM/Report/Form/Contribute/SoftCredit.php
Labels: master

#13674 Remove tests that no longer work due to dead service
  tests/phpunit/CRM/Utils/GeocodeTest.php
Labels: 5.10

#13677 reporting#10 - fix pagination on Contribution Detail report
  CRM/Report/Form/Contribute/Detail.php
Labels: 5.10, merge on pass

#13663 Hotfix for dev/core#747 To fix generation of contact image urls
  CRM/Core/Page/File.php
  CRM/Utils/File.php
  tests/phpunit/CRM/Utils/FileTest.php
Labels: 5.11, merge on pass

#13678 test for reporting#10
  tests/phpunit/CRM/Report/Form/Contribute/DetailTest.php
Labels: master, merge on pass

#13673 Remove tests that no longer work due to dead service
  tests/phpunit/CRM/Utils/GeocodeTest.php
Labels: 5.11

#13675 CRM/Logging - Fix log table exceptions
  CRM/Logging/Schema.php
  tests/phpunit/CRM/Logging/SchemaTest.php
Labels: has-test, master

#13679 Fix loading of contact images on contact summary
  CRM/Core/Page/File.php
  CRM/Utils/File.php
  tests/phpunit/CRM/Utils/FileTest.php
Labels: 5.10, merge on pass

#13669 Payment notification formatting, move greeting into table
  xml/templates/message_templates/payment_or_refund_notification_html.tpl
Labels: master

#13681 Add in 5.10.4 Release notes
  release-notes/5.10.4.md
Labels: 5.10

#13683 Add in 5.10.4 Release notes
  release-notes/5.10.4.md
Labels: 5.11

#13685 dev/core#746 Add in unit tests to ensure that where clause is as is w…
  CRM/Contact/BAO/Query.php
  tests/phpunit/CRM/Contact/BAO/GroupContactCacheTest.php
Labels: master, merge on pass

#13644 Refactor CRM_Utils_SQL_TempTable::build()->createWithQuery($sql) interface to support MEMORY tabls
  CRM/Utils/SQL/TempTable.php
Labels: master, merge ready

#13634 [NFC, test class] formatting, remove unused variables
  tests/phpunit/CRM/Contribute/Form/SearchTest.php
Labels: master

#13687 Minor code cleanup
  CRM/Case/Form/Activity.php
Labels: master, merge on pass

#13682 Force utf8mb4 query to throw exception as the check expects
  CRM/Utils/Check/Component/Env.php
Labels: master

#13441 CRM/Logging - Fix various bugs in schema parsing
  CRM/Logging/Schema.php
  tests/phpunit/CRM/Logging/SchemaTest.php
Labels: has-test, master

#12337 dev/core#190 / CRM-21643 ensure custom data multi record profile returns correct …
  CRM/Core/BAO/UFGroup.php
Labels: sig:user interfacing improvement

#12641 CiviMail: Fix reply forwarding for mailers with From: and Return-path: limitations
  CRM/Mailing/Event/BAO/Reply.php
Labels: master

#13042 only set custom field to null if it is really null, not string 'null'
  CRM/Core/BAO/CustomValueTable.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: has-test, master

#13654 dev/core#742 Fix XML parasing by swapping & for ,
  CRM/Core/xml/Menu/Activity.xml
Labels: master

#13657 reporting#9: parity between getContactFields and getBasicContactFields
  CRM/Report/Form.php
Labels: master

#13588 dev/core#631 - Enable 'add new' by default on merge screen
  CRM/Dedupe/Merger.php
  tests/phpunit/CRM/Dedupe/MergerTest.php
Labels: has-test, master, merge ready, needs-concept-approval

#13578 Towards supporting EntityForm for 'View Action'
  CRM/Core/Form/EntityFormTrait.php
  CRM/Custom/Form/CustomData.php
  templates/CRM/Core/Form/Field.tpl
Labels: master, sig:code maintenance readability testability

#13346 geocode job: Do not return more messages than can fit in the log data column
  CRM/Utils/Address/BatchUpdate.php
  CRM/Utils/Type.php
Labels: master

#13276 Record change log entry when contact is moved to or restored from trash
  CRM/Contact/BAO/Contact.php
Labels: master

#13688 Use CRM_Utils_SQL_TempTable to drop and create table.
  CRM/Export/BAO/Export.php
Labels: has-test, master, merge on pass

#13668 [REF] Extract getSearchSQL from getSearchQuery.
  CRM/Campaign/Selector/Search.php
  CRM/Contact/BAO/Query.php
Labels: master

#13340 Do not attempt to store out-of-range street number
  CRM/Core/BAO/Address.php
  CRM/Utils/Type.php
  tests/phpunit/CRM/Core/BAO/AddressTest.php
Labels: has-test, master, merge on pass

#13289 Move pear/mail from packages to composer.json
  composer.json
  composer.lock
  tools/scripts/composer/patches/pear-mail.patch.txt
  tools/scripts/composer/pear-mail-fix.sh
Labels: master

#13691 [REF] Extract record refund function
  CRM/Financial/BAO/Payment.php
  CRM/Financial/BAO/Payment/Contribution.php
Labels: master

#13693 Revert "[REF] Extract record refund function"
  CRM/Contribute/BAO/Contribution.php
  CRM/Financial/BAO/Payment.php
Labels: master
