Repository civicrm/civicrm-core, pull requests merged in 2019-06, with the labels that each got.

#14384 Wysiwyg support for i18n event fields
  xml/schema/Event/Event.xml
Labels: master

#14392 CRM_Extension_System - Only allow `test.*` extensions during headless testing. Hide from regular users.
  CRM/Extension/Container/Basic.php
  CRM/Extension/System.php
Labels: master

#14317 Switch to calling Payment.create api when processing a refund from AdditionalPayment form
  CRM/Contribute/BAO/Contribution.php
  CRM/Contribute/Form/AdditionalPayment.php
  CRM/Financial/BAO/Payment.php
Labels: master

#14353 [REF] Remove reference to 'changePaymentInstrument' from updateFinancialAccounts as never passed in
  CRM/Contribute/BAO/Contribution.php
  tests/phpunit/CRM/Contribute/BAO/ContributionTest.php
Labels: master

#14386 dev/core#389 [preliminary cleanup] Standardise metadata for custom field use
  CRM/Core/BAO/CustomField.php
  CRM/Core/BAO/CustomQuery.php
  tests/phpunit/CRM/Core/BAO/CustomQueryTest.php
Labels: master

#14225 dev/core#953 Add test for updating email via import & ensuring it is primary
  CRM/Core/BAO/Block.php
  tests/phpunit/CRM/Contact/Import/Parser/ContactTest.php
Labels: master

#14097 Deprecate creating recipients from MailingJob.create.
  CRM/Mailing/BAO/MailingJob.php
  api/v3/Mailing.php
Labels: master

#14330 [code-quality] [jcalendar] remove jcalendar usage from participant_register_date on event search
  CRM/Contact/BAO/Query.php
  CRM/Contact/BAO/SavedSearch.php
  CRM/Core/Form/Search.php
  CRM/Event/BAO/Query.php
  CRM/Event/Form/Search.php
  CRM/Upgrade/Incremental/php/FiveFifteen.php
  templates/CRM/Event/Form/Search/Common.tpl
Labels: master

#14370 [REF] dev/core#998 make processDupes testable & add test
  CRM/Contact/Page/AJAX.php
  tests/phpunit/CRM/Contact/Page/AjaxTest.php
Labels: master

#14396 Regenerate Event DAO for i18n
  CRM/Core/I18n/SchemaStructure.php
  CRM/Event/DAO/Event.php
Labels: master

#14153 Use data provider to test both api versions
  Civi/Test/Api3DocTrait.php
  Civi/Test/Api3TestTrait.php
  Civi/Test/ContactTestTrait.php
  tests/phpunit/CRM/Contact/Import/Parser/ContactTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/api/v3/ACLCachingTest.php
  tests/phpunit/api/v3/ACLPermissionTest.php
  tests/phpunit/api/v3/ActionScheduleTest.php
  tests/phpunit/api/v3/ActivityContactTest.php
  tests/phpunit/api/v3/ActivityTest.php
  tests/phpunit/api/v3/AddressTest.php
  tests/phpunit/api/v3/CampaignTest.php
  tests/phpunit/api/v3/ConstantTest.php
  tests/phpunit/api/v3/ContactTest.php
  tests/phpunit/api/v3/ContactTypeTest.php
  tests/phpunit/api/v3/ContributionPageTest.php
  tests/phpunit/api/v3/DomainTest.php
  tests/phpunit/api/v3/EmailTest.php
  tests/phpunit/api/v3/EntityTagTest.php
  tests/phpunit/api/v3/EventTest.php
  tests/phpunit/api/v3/GroupTest.php
  tests/phpunit/api/v3/ImTest.php
  tests/phpunit/api/v3/MailSettingsTest.php
  tests/phpunit/api/v3/NavigationTest.php
  tests/phpunit/api/v3/NoteTest.php
  tests/phpunit/api/v3/OpenIDTest.php
  tests/phpunit/api/v3/PhoneTest.php
  tests/phpunit/api/v3/RelationshipTest.php
  tests/phpunit/api/v3/RelationshipTypeTest.php
  tests/phpunit/api/v3/SettingTest.php
  tests/phpunit/api/v3/SystemCheckTest.php
  tests/phpunit/api/v3/TagTest.php
  tests/phpunit/api/v3/UFFieldTest.php
  tests/phpunit/api/v3/UFGroupTest.php
  tests/phpunit/api/v3/UFJoinTest.php
  tests/phpunit/api/v3/UFMatchTest.php
  tests/phpunit/api/v3/WebsiteTest.php
Labels: master

#14398 Set new inactive statuses as 'Chargeback' does not exist on new installs and that breaks Contributionrecur.create API
  CRM/Contribute/BAO/ContributionRecur.php
Labels: master, sig:bug

#14347 Set title properly on Move/Copy/File on Case popup
  CRM/Case/Form/ActivityToCase.php
  templates/CRM/Case/Form/ActivityToCase.tpl
Labels: master

#14400 Add missing 'submit credit card event registration' link to standalone event registration form
  templates/CRM/Event/Form/Participant.tpl
Labels: master

#14387 Update test files to use PHPUnit6 notiation for classes
  Civi/Test/CiviTestListener.php
  Civi/Test/Legacy/CiviTestListener.php
  composer.json
  composer.lock
  tests/phpunit/CRM/Core/CommunityMessagesTest.php
  tests/phpunit/CRM/Core/ComposerConfigTest.php
  tests/phpunit/CRM/Core/Payment/AuthorizeNetTest.php
  tests/phpunit/CRM/Report/Form/TestCaseTest.php
  tests/phpunit/Civi/Test/ExampleHookTest.php
  tests/phpunit/Civi/Test/ExampleTransactionalTest.php
  tests/phpunit/CiviTest/CiviEndToEndTestCase.php
  tests/phpunit/CiviTest/CiviMailUtils.php
  tests/phpunit/CiviTest/CiviTestSuite.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/EnvTests.php
  tests/phpunit/HelloTest.php
  tests/phpunit/api/v3/ACLPermissionTest.php
  tests/phpunit/api/v3/ReportTemplateTest.php
  tests/phpunit/api/v3/SyntaxConformanceTest.php
Labels: master

#14337 [REF] Stop passing cacheKey to refillCache
  CRM/Core/BAO/PrevNextCache.php
  CRM/Dedupe/Merger.php
Labels: master

#14402 [NFC] PHPCS fixes.
  CRM/Case/XMLProcessor.php
  CRM/Contact/BAO/Query.php
  CRM/Contact/Form/Search/Custom/DateAdded.php
  CRM/Contact/Page/AJAX.php
  CRM/Core/BAO/Cache.php
  CRM/Core/BAO/Mapping.php
  CRM/Core/BAO/OptionGroup.php
  CRM/Core/CodeGen/Main.php
  CRM/Core/CodeGen/Specification.php
  CRM/Core/Payment/PayJunction.php
  CRM/Core/SelectValues.php
  CRM/Custom/Form/CustomData.php
  CRM/Cxn/CiviCxnHttp.php
  CRM/Event/Form/Task/ParticipantStatus.php
  CRM/Export/BAO/ExportProcessor.php
  CRM/Extension/Container/Collection.php
  CRM/Extension/Manager.php
  CRM/Extension/Manager/Base.php
  CRM/Queue/Service.php
  CRM/Report/Form/ActivitySummary.php
  CRM/Utils/Cache/SqlGroup.php
  CRM/Utils/Hook/DrupalBase.php
  CRM/Utils/QueryFormatter.php
Labels: master

#14406 dev/drupal#66 Fix legacy IPN endpoint for Drupal (gitlab issue 973)
  extern/ipn.php
Labels: 5.14, merge on pass

#14399 Add EntityPageTrait
  CRM/Contact/Page/View/Relationship.php
  CRM/Core/Page/EntityPageTrait.php
Labels: master

#14405 dev/core#985 Fix trailing slash for urls on Windows
  CRM/Utils/System/Base.php
Labels: master, merge on pass

#14401 dev/core#389 [preliminary cleanup+ test] Standardise metadat for custom field
  CRM/Core/BAO/CustomField.php
  tests/phpunit/CRM/Core/BAO/CustomFieldTest.php
  tests/phpunit/CRM/Core/BAO/CustomQueryTest.php
  tests/phpunit/CRMTraits/Custom/CustomDataTrait.php
Labels: master

#14412 Fix test / possible live error on submitting credit card renewals
  CRM/Member/Form/MembershipRenewal.php
Labels: 5.14, merge on pass

#14393 dev/core#1004 Fix regression causing notices on components screen
  CRM/Admin/Form/Setting.php
  CRM/Admin/Form/Setting/Component.php
  CRM/Admin/Form/SettingTrait.php
  CRM/Case/Info.php
  CRM/Core/Component.php
  CRM/Core/SelectValues.php
  settings/Core.setting.php
  templates/CRM/Admin/Form/Setting/Component.tpl
Labels: master

#14409 dev/core#1002 fix fatal on searching on related contacts.
  CRM/Contact/BAO/Query.php
  tests/phpunit/CRM/Contact/SelectorTest.php
  tests/phpunit/api/v3/ContactTest.php
Labels: 5.14

#14414 Add angular-xeditable to angular
  bower.json
Labels: master, merge on pass

#14417 5.14
  CRM/Contact/BAO/Query.php
  tests/phpunit/CRM/Contact/SelectorTest.php
  tests/phpunit/api/v3/ContactTest.php
Labels: master

#14416 dev/Core#785: Extend addField to support select2 widget
  CRM/Core/Form.php
Labels: master, merge on pass

#14389 Force link in confirmation email to be front-end
  CRM/Mailing/Event/BAO/Subscribe.php
Labels: master, merge on pass

#14348 Allow updating ENGINE_CONFIG for System.updatelogtables
  CRM/Logging/Schema.php
  api/v3/System.php
Labels: master, merge ready

#14395 dev/core#905 Add contribution recur statuses 'Processing' and 'Failing'
  CRM/Upgrade/Incremental/sql/5.15.alpha1.mysql.tpl
  sql/civicrm_generated.mysql
  xml/templates/civicrm_data.tpl
Labels: master

#14404 Try running unit tests on phpunit6
  tools/scripts/phpunit
Labels: master

#14420 dev/core#1012 Fix selection of quicksearch options
  css/crm-menubar.css
Labels: 5.14

#14422 5.14 to master
  css/crm-menubar.css
Labels: master

#14421 phpunit6 - Implement TAP printer
  Civi/Test/TAP.php
  tools/scripts/phpunit
Labels: master, merge ready

#14423 Caches - Normalize dependency on php-cache integration-tests
  composer.json
  composer.lock
  tests/phpunit/E2E/Cache/CacheTestCase.php
Labels: master, merge on pass

#14419 Improve formatting for settings checkboxes
  CRM/Admin/Form/Setting/Component.php
  CRM/Admin/Form/Setting/Search.php
  CRM/Admin/Form/SettingTrait.php
  css/civicrm.css
  settings/Core.setting.php
  settings/Search.setting.php
  templates/CRM/Admin/Form/Preferences/Display.tpl
  templates/CRM/Admin/Form/Setting/Component.tpl
  templates/CRM/Admin/Form/Setting/Search.tpl
  templates/CRM/Admin/Form/Setting/SettingForm.tpl
Labels: master, merge on pass

#14424 Fix running of CRM_Utils_MoneyTest on PHPUnit6+
  tests/phpunit/CRM/Utils/MoneyTest.php
Labels: master, merge on pass

#14430 dev/core#1017: Always bootstrap CRM_Utils_System against 5.14
  extern/ipn.php
Labels: 5.14

#14432 5.14 to master
  extern/ipn.php
Labels: master

#14434 [REF] Activity form - very minor tidy up
  CRM/Activity/Form/Activity.php
Labels: master

#14247 Change Activity tag to use select2
  CRM/Activity/BAO/Query.php
  templates/CRM/Activity/Form/Search/Common.tpl
Labels: master

#14426 dev/core#1014 fix e-notice regression
  CRM/Core/Form/Search.php
Labels: master

#14437 Minimum supported PHP version is 7.0
  CRM/Upgrade/Form.php
  CRM/Upgrade/Incremental/General.php
Labels: 5.14

#14245 5.14.0 release notes
  contributor-key.yml
  release-notes.md
  release-notes/5.14.0.md
Labels: 5.14

#14435 Revert "Create contribution before taking payment, per contribution page workflow"
  CRM/Event/Form/Registration/Confirm.php
Labels: 5.14

#14407 Fix checksum failure on editing recurring contributions
  CRM/Contribute/Form/CancelSubscription.php
  CRM/Contribute/Form/ContributionRecur.php
  CRM/Contribute/Form/UpdateBilling.php
  CRM/Contribute/Form/UpdateSubscription.php
Labels: 5.14, merge on pass

#14363 Avoid logging error message if status check query fails.
  CRM/Utils/Check/Component/Env.php
Labels: master

#14438 (dev/core#1000) Fixes contact's displayname not appearing in membership edit, if no registered email is found
  CRM/Contact/BAO/Contact/Location.php
  tests/phpunit/CRM/Contact/BAO/ContactTest.php
Labels: 5.14, merge on pass

#14411 Add api for Dedupe.getduplicates
  api/v3/Dedupe.php
  tests/phpunit/CRM/Dedupe/MergerTest.php
Labels: master, merge on pass

#14441 dev/core#628 - Make Quicksearch options sortable
  CRM/Admin/Form/Setting/Search.php
  CRM/Admin/Form/SettingTrait.php
  CRM/Admin/Page/AJAX.php
  css/civicrm.css
  js/Common.js
  js/crm.menubar.js
  settings/Core.setting.php
  settings/Search.setting.php
Labels: master

#14453 dev/core#1015 fix regression on exporting soft credits
  CRM/Contact/BAO/Query.php
Labels: 5.14

#14454 (NFC) Remove without param tests
  tests/phpunit/api/v3/SyntaxConformanceTest.php
Labels: master, merge on pass

#14455 5.14 to master
  CRM/Contact/BAO/Contact/Location.php
  CRM/Contact/BAO/Query.php
  CRM/Contribute/Form/CancelSubscription.php
  CRM/Contribute/Form/ContributionRecur.php
  CRM/Contribute/Form/UpdateBilling.php
  CRM/Contribute/Form/UpdateSubscription.php
  CRM/Event/Form/Registration/Confirm.php
  CRM/Upgrade/Form.php
  CRM/Upgrade/Incremental/General.php
  contributor-key.yml
  release-notes.md
  release-notes/5.14.0.md
  tests/phpunit/CRM/Contact/BAO/ContactTest.php
Labels: master

#14439 Update 5.14.0 release notes with latest changes
  release-notes/5.14.0.md
Labels: 5.14

#14212 Fix AssetBuilderTest by altering error_reporting level to match Dru…
  tests/phpunit/E2E/Core/AssetBuilderTest.php
Labels: 5.14, merge on pass

#14445 dev/core#1022 - Manage Case deleted activities search filter no longer working
  templates/CRM/Case/Form/ActivityTab.tpl
Labels: master

#14457 5.14
  release-notes/5.14.0.md
  tests/phpunit/E2E/Core/AssetBuilderTest.php
Labels: master

#14449 dev/core#1023 - E_NOTICE when creating bulk SMS
  api/v3/Mailing.php
  tests/phpunit/CRM/SMS/PreviewTest.php
Labels: master, merge on pass

#14201 Fix AssetBuilderTest when running on WordPress. Use Guzzle.
  tests/phpunit/E2E/Core/AssetBuilderTest.php
Labels: 5.14

#14458 Test tweaks that *might* help with intermittant test weirdness
  tests/phpunit/E2E/Core/PrevNextTest.php
Labels: master, merge on pass

#14451 [NFC] array formatting in api_v3_paymentTest class
  tests/phpunit/api/v3/PaymentTest.php
Labels: master, merge on pass

#14394 Add Contact.get_merge_conflicts api
  CRM/Dedupe/Merger.php
  Civi/Test/ContactTestTrait.php
  api/v3/Contact.php
  tests/phpunit/CRMTraits/Custom/CustomDataTrait.php
  tests/phpunit/api/v3/ContactTest.php
Labels: master

#14463 5.14
  install/index.php
  release-notes/5.14.0.md
  tests/phpunit/E2E/Core/AssetBuilderTest.php
Labels: master

#14466 5.14.0.md - Add missing credit
  release-notes/5.14.0.md
Labels: 5.14

#14464 Don't run search when editing smartgroup criteria
  templates/CRM/Contact/Form/Search/Intro.tpl
  templates/CRM/Group/Form/Edit.tpl
Labels: master

#14442 Conditionally use Drupal's jQuery only if available
  js/crm.drupal8.js
Labels: master, merge on pass

#14465 dev/core#1010 pledge_acknowledge template - capitalization and greeting
  CRM/Upgrade/Incremental/MessageTemplates.php
  xml/templates/message_templates/pledge_acknowledge_html.tpl
  xml/templates/message_templates/pledge_acknowledge_text.tpl
Labels: master

#14467 Misc translation 'ts' fixes
  CRM/Contact/BAO/Relationship.php
  CRM/Contact/Form/Merge.php
  CRM/Contact/Form/Search/Criteria.php
  CRM/Contact/Form/Task/AddToParentClass.php
  CRM/Core/DAO/CustomField.php
  CRM/Core/Exception.php
  CRM/Core/Form/Task/Batch.php
  CRM/Core/Payment/Form.php
  CRM/Core/Payment/PaymentExpressIPN.php
  CRM/Report/Form.php
Labels: master, merge on pass

#14427 Fix upgrade on participant_register date
  CRM/Upgrade/Incremental/SmartGroups.php
Labels: master, sig-b4-rc

#14433 [Outbound mail admin form] fix some more notices resulting from recent change
  CRM/Admin/Form/Setting/Smtp.php
Labels: master, sig-b4-rc

#14450 Wrap titles in metadata in ts on payment.create api
  api/v3/Payment.php
Labels: master

#14461 Use crm-checkbox-list styling in display prefs tpl
  css/civicrm.css
  templates/CRM/Admin/Form/Preferences/Display.tpl
Labels: master

#14469 Fix version for pledge message update, also remove 'please print'
  CRM/Upgrade/Incremental/MessageTemplates.php
  xml/templates/message_templates/pledge_acknowledge_html.tpl
  xml/templates/message_templates/pledge_acknowledge_text.tpl
Labels: master, merge on pass

#14476 [REF] Move retrieval of basicSearchFields to 'get' fn
  CRM/Contact/Form/Search/Criteria.php
Labels: master, merge on pass

#14475 Permit sort_name as a url parameter on advanced search
  CRM/Activity/Form/Search.php
  CRM/Contact/Form/Search/Advanced.php
  CRM/Contact/Form/Search/Criteria.php
  CRM/Core/Form/Search.php
Labels: master

#14447 Fix Exception to remove result from duplicates
  CRM/Dedupe/BAO/Exception.php
  tests/phpunit/api/v3/ExceptionTest.php
Labels: has-test, master

#14473 dev/core#1025 fix unreleased regression on contact.get with custom fields
  CRM/Core/BAO/CustomQuery.php
  tests/phpunit/CRMTraits/Custom/CustomDataTrait.php
  tests/phpunit/api/v3/ContactTest.php
Labels: has-test, master, sig-b4-rc

#14448 Fix Exception api to save lower id number as contact 1
  CRM/Contact/Page/AJAX.php
  CRM/Dedupe/BAO/Exception.php
  tests/phpunit/api/v3/ExceptionTest.php
Labels: has-test, master

#14470 [NFC][test-fix] centralise use of assertLike for comparing sql
  tests/phpunit/CRM/Contact/BAO/QueryTest.php
  tests/phpunit/CRM/Contact/SelectorTest.php
  tests/phpunit/CRM/Utils/SQL/InsertTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: easy-review, has-test, master

#14472 [nfc] [test] Skip testGetFromTo on date transition
  tests/phpunit/CRM/Report/FormTest.php
Labels: easy-review, has-test, master

#14482 [NFC] Update Exception DAO class
  CRM/Dedupe/DAO/Exception.php
Labels: 5.15, merge on pass

#14468 Add CRM_Utils_System::sendResponse(). Fix AssetBuilder's status-code on WP.
  CRM/Utils/System.php
  CRM/Utils/System/Base.php
  CRM/Utils/System/WordPress.php
  Civi/Core/AssetBuilder.php
Labels: 5.15, has-test, merge on pass

#14483 5.15
  CRM/Dedupe/DAO/Exception.php
  CRM/Utils/System.php
  CRM/Utils/System/Base.php
  CRM/Utils/System/WordPress.php
  Civi/Core/AssetBuilder.php
Labels: master

#14425 [Form cleanup] remove form classes & tpls for Event Component settings & Multisite
  CRM/Admin/Form/Preferences/Campaign.php
  CRM/Admin/Form/Preferences/Multisite.php
  CRM/Campaign/xml/Menu/Campaign.xml
  CRM/Core/xml/Menu/Admin.xml
  settings/Campaign.setting.php
  settings/Multisite.setting.php
  templates/CRM/Admin/Form/Preferences/Campaign.tpl
  templates/CRM/Admin/Form/Preferences/Multisite.tpl
Labels: master

#14103 dev/core#889 - Refund throws a fatal error if the main contribution a…
  CRM/Financial/BAO/Payment.php
Labels: has-test, master, sig:bug

#14488 dev/core#889 Add test for changing fee selection to 0 and then record…
  tests/phpunit/CRM/Event/BAO/ChangeFeeSelectionTest.php
Labels: master, merge on pass

#14491 Object id is always NULL in ore hook in update activity mode
  CRM/Activity/BAO/Activity.php
Labels: master, merge on pass

#14489 Fix core#1026 where an email address synced from a CMS contact is created with no location field.
  CRM/Core/BAO/UFMatch.php
  api/v3/Email.php
  tests/phpunit/api/v3/EmailTest.php
Labels: master, merge on pass

#14290 financial#55: support IPN logging on processors that send JSON data as POST
  CRM/Core/Payment.php
  CRM/Utils/JSON.php
Labels: master, ok-without-test

#14431 dev/core#561 Convert pledge search form to use metadata functions
  CRM/Pledge/BAO/Query.php
  CRM/Pledge/DAO/Pledge.php
  CRM/Pledge/Form/Search.php
  xml/schema/Pledge/Pledge.xml
Labels: master

#14485 Add in uniqueness to cache keys to mitigate clashes on multisite inst…
  CRM/Contact/BAO/Contact.php
  CRM/Core/BAO/CustomField.php
  CRM/Core/BAO/Navigation.php
Labels: master

#14493 Remove more free calls
  CRM/Core/BAO/ActionSchedule.php
  CRM/Core/BAO/File.php
  CRM/Core/BAO/Mapping.php
  CRM/Core/BAO/MessageTemplate.php
  CRM/Core/BAO/UFGroup.php
  CRM/Core/BAO/UFMatch.php
  CRM/Core/BAO/Website.php
  CRM/Core/OptionGroup.php
  CRM/Friend/Form.php
  CRM/Mailing/BAO/Mailing.php
  CRM/Mailing/BAO/MailingJob.php
  CRM/Pledge/BAO/PledgePayment.php
  CRM/Profile/Form.php
  CRM/Queue/Queue/Sql.php
  CRM/Report/BAO/ReportInstance.php
  CRM/Utils/Address/BatchUpdate.php
  CRM/Utils/Cache/SqlGroup.php
  CRM/Utils/Check/Component/Timestamps.php
  CRM/Utils/Migrate/ExportJSON.php
  sql/GenerateData.php
Labels: master, merge on pass

#14478 [REF] Move sort_name definition to searchFieldMetadata
  CRM/Contact/Form/Search/Criteria.php
Labels: master

#14452 Create payment activity when creating a payment via the api, test
  CRM/Financial/BAO/Payment.php
  tests/phpunit/api/v3/PaymentTest.php
Labels: has-test, master

#13916 dev/core#530 Make a_b relationships available as case roles
  CRM/Activity/Page/AJAX.php
  CRM/Case/BAO/Case.php
  CRM/Case/BAO/Query.php
  CRM/Case/Form/AddToCaseAsRole.php
  CRM/Case/Form/CaseView.php
  CRM/Case/Info.php
  CRM/Case/ManagedEntities.php
  CRM/Case/XMLProcessor.php
  CRM/Case/XMLProcessor/Process.php
  CRM/Case/XMLProcessor/Report.php
  CRM/Case/XMLRepository.php
  CRM/Report/Form/Case/Summary.php
  ang/crmCaseType.ang.php
  ang/crmCaseType.js
  ang/crmCaseType/rolesTable.html
  tests/karma/unit/crmCaseTypeSpec.js
  tests/phpunit/CRM/Case/BAO/CaseTypeForkTest.php
Labels: master

#14494 Add a couple customField pseudoconstants
  CRM/Core/DAO/CustomField.php
  tests/phpunit/CRM/Contact/BAO/SavedSearchTest.php
  xml/schema/Core/CustomField.xml
Labels: master, merge on pass

#14474 dev/drupal#21 Remove asterisks from placeholder url
  CRM/Utils/System/Drupal8.php
  CRM/Utils/System/WordPress.php
  js/crm.ajax.js
  templates/CRM/common/l10n.js.tpl
  tests/karma/unit/crmMailingSpec.js
Labels: master, merge on pass, ok-without-test

#14497 NFC Comments and formatting only
  CRM/Contact/BAO/Contact.php
  CRM/Core/Form.php
  CRM/Event/Form/Registration.php
  CRM/Event/Form/Registration/Confirm.php
Labels: master

#14498 REF: Extract preProcess paypalexpress
  CRM/Event/Form/Registration/Confirm.php
Labels: master

#14436 Fix proportional test to test Payment.create & for the test to make more sense
  tests/phpunit/CRM/Contribute/BAO/ContributionTest.php
Labels: master

#14444 [REF] Minor code cleanup on string concatenation
  CRM/Export/BAO/Export.php
Labels: master

#14496 REF Extract override default currency function
  CRM/Contribute/BAO/Contribution.php
  CRM/Contribute/BAO/Contribution/Utils.php
  CRM/Contribute/Form/ContributionBase.php
  CRM/Event/Form/Registration.php
  CRM/Event/Page/EventInfo.php
Labels: master, merge on pass

#14492 Fix deletion of contact sub_type in api4
  CRM/Contact/BAO/Contact.php
  tests/phpunit/CRM/Contact/BAO/ContactType/ContactTest.php
  tests/phpunit/api/v3/ContactTest.php
Labels: has-test, master, merge on pass

#14504 Remove duplicated code in contribution recur search build function
  CRM/Contribute/BAO/ContributionRecur.php
Labels: master

#14500 REF Deduplicate recaptcha handling code
  CRM/Campaign/Form/Petition/Signature.php
  CRM/Contribute/Form/ContributionBase.php
  CRM/Event/Form/Registration.php
  CRM/Mailing/Form/Subscribe.php
  CRM/Profile/Form.php
  CRM/Utils/ReCAPTCHA.php
Labels: master

#14507 Expose Primary member only/Non primary member only filter in membersh…
  CRM/Report/Form/Member/Detail.php
  CRM/Report/Form/Member/Summary.php
Labels: master, merge on pass

#13959 dev/drupal#63 Drupal8: override setMessage(), because drupal_set_message is deprecated
  CRM/Utils/System/Drupal8.php
Labels: master

#14510 Civi\Angular\ChangeSet - Relax debug-mode consistency check
  Civi/Angular/ChangeSet.php
Labels: master, merge on pass

#14506 dev/core#1039 Make the contact details in the contact summary screen …
  css/civicrm.css
Labels: master, merge ready

#14508 Bugfix - getting id from hash
  CRM/Mailing/BAO/Mailing.php
  CRM/Mailing/Page/View.php
Labels: master

#14250 CRM_Utils_SQL_* - Properly interpolate NULL values
  CRM/Utils/SQL/BaseParamQuery.php
  tests/phpunit/CRM/Utils/SQL/DeleteTest.php
  tests/phpunit/CRM/Utils/SQL/InsertTest.php
  tests/phpunit/CRM/Utils/SQL/SelectTest.php
Labels: master

#13966 Fixed visibility logic on Price field options.
  CRM/Price/Form/Option.php
Labels: master

#14516 [test] Add PrematureExitException to support unit testing where the code would otherwise exit
  CRM/Core/Exception/PrematureExitException.php
  CRM/Utils/System.php
Labels: 5.15

#14154 Fix placeholder font in Quicksearch
  css/crm-menubar.css
Labels: master

#14484 Improve I18n schema by including comments and default and NOT NULL or…
  CRM/Core/CodeGen/I18n.php
  CRM/Core/I18n/SchemaStructure.php
  tests/phpunit/CRM/Core/I18n/SchemaTest.php
Labels: master

#14520 5.15
  CRM/Core/Exception/PrematureExitException.php
  CRM/Utils/System.php
Labels: master

#14471 [NFC] test cleanup. Uses CRM_Core_Exceptions, properly outputs unfiltered results
  Civi/Test/Api3TestTrait.php
  Civi/Test/ContactTestTrait.php
Labels: easy-review, has-test, master

#14517 Fix test which fails when run in isolation.
  tests/phpunit/CRM/Contribute/Page/AjaxTest.php
Labels: master, merge on pass

#14518 dev/core#965 Fix destination in payment edit
  CRM/Financial/Form/PaymentEdit.php
Labels: master, merge on pass

#14513 dev/core#1015 fix regression on exporting soft credits - more robust …
  CRM/Contact/BAO/Query.php
Labels: master

#14501 Display description next to 'paperclip' file icon - usually the filename
  CRM/Core/BAO/CustomField.php
Labels: master

#14505 Update PSR16 handling for multisite extension legacy caching group
  CRM/Core/BAO/Cache/Psr16.php
Labels: master, merge on pass

#14527 (REF) Convert YAML fixtures to JSON. Reset symfony/yaml dependency.
  composer.json
  composer.lock
  tests/fixtures/case.json
  tests/fixtures/case.yaml
  tests/fixtures/case_contact.json
  tests/fixtures/case_contact.yaml
  tests/fixtures/case_relationships.json
  tests/fixtures/case_relationships.yaml
  tests/fixtures/case_types.json
  tests/fixtures/case_types.yaml
  tests/fixtures/contacts.json
  tests/fixtures/contacts.yaml
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: 5.15, merge on pass

#14526 [NFC] Fix indenting in Misc Setting Template
  templates/CRM/Admin/Form/Setting/Miscellaneous.tpl
Labels: master

#14528 5.15
  composer.json
  composer.lock
  tests/fixtures/case.json
  tests/fixtures/case.yaml
  tests/fixtures/case_contact.json
  tests/fixtures/case_contact.yaml
  tests/fixtures/case_relationships.json
  tests/fixtures/case_relationships.yaml
  tests/fixtures/case_types.json
  tests/fixtures/case_types.yaml
  tests/fixtures/contacts.json
  tests/fixtures/contacts.yaml
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: master

#14523 CiviDist fails on BSD flavor of 'cp' with '-r -p' switch to '-R -p'
  distmaker/dists/joomla_php5.sh
Labels: master

#14532 Adding myself to the contributors file
  contributor-key.yml
Labels: master

#14530 Expose Primary member only/Non primary member only filter in membersh…
  CRM/Report/Form/Member/ContributionDetail.php
Labels: master, merge on pass

#14531 Php 7.2 notices fix on import
  CRM/Contribute/Import/Parser/Contribution.php
Labels: master

#14486 [REF] dev/core#561 Convert Contribution Date field to use date picker…
  CRM/Contact/Form/Search/Custom/ContributionAggregate.php
  CRM/Contribute/BAO/Query.php
  CRM/Contribute/DAO/Contribution.php
  CRM/Contribute/Tokens.php
  CRM/Report/Form/Contribute/DeferredRevenue.php
  CRM/Report/Form/Contribute/Detail.php
  CRM/Upgrade/Incremental/SmartGroups.php
  CRM/Upgrade/Incremental/php/FiveSixteen.php
  CRM/Upgrade/Incremental/sql/5.16.alpha1.mysql.tpl
  api/v3/Contribution.php
  api/v3/utils.php
  templates/CRM/Contact/Form/Search/Custom/ContributionAggregate.tpl
  templates/CRM/Contribute/Form/Search/Common.tpl
  tests/phpunit/CRM/Contribute/Form/SearchTest.php
  tests/phpunit/CRM/Export/BAO/ExportTest.php
  tests/phpunit/api/v3/ContributionTest.php
  xml/schema/Contribute/Contribution.xml
Labels: master

#14512 [REF] CRM_Case_BAO_Case::addcaseActivityLinks to CRM_Case_Selector_Search
  CRM/Case/BAO/Case.php
  CRM/Case/Selector/Search.php
Labels: master

#14522 ActivityForm - Redirect to contact page or activity view in standalone mode
  CRM/Activity/Form/Activity.php
Labels: master

#14511 Add Unit test for testing smart group flow
  tests/phpunit/CRM/Mailing/Form/Task/AdhocMailingTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: 5.15

#14536 5.15 to master
  tests/phpunit/CRM/Mailing/Form/Task/AdhocMailingTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: master

#14539 Civi/Test/TAP - Replace Symfony YAML dependency
  Civi/Test/TAP.php
  tools/scripts/phpunit
Labels: 5.15

#14541 5.15 to master
  Civi/Test/TAP.php
  tools/scripts/phpunit
Labels: master

#14535 Address BAO - Handle standard 'custom' param as well as individual fields
  CRM/Core/BAO/Address.php
Labels: master, merge on pass

#14538 [test] truncate pledge block when cleaning up financial entities
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: master

#14524 Add csv reader package
  composer.json
  composer.lock
Labels: master

#14537 Add CRM_Utils_JS::decode function for decoding js objects
  CRM/Utils/JS.php
  tests/phpunit/CRM/Utils/JSTest.php
Labels: master

#14533 Deprecate contribution_date as a parameter
  CRM/Contribute/BAO/Query.php
Labels: master

#14540 Fix A.net to resolve time when using default
  CRM/Core/Payment/AuthorizeNetIPN.php
Labels: master

#14544 (dev/core#1044) Extension/MIME matching should be case insensitive
  CRM/Core/Page/File.php
Labels: 5.15, merge on pass

#14547 5.15 to master
  CRM/Core/Page/File.php
Labels: master

#14548 [NFC] Fix Test function delcaration to match change in CiviUnitTestCa…
  tests/phpunit/CRM/Contact/Import/Form/MapFieldTest.php
Labels: master, merge on pass

#14542 [TEST] Fix intermittent test fail on NULL array getting contaminated
  CRM/Contact/BAO/Contact.php
  CRM/Dedupe/Merger.php
Labels: master

#12929 CRM-18792, dev/core#378 - Create CSS theming subsystem
  CRM/Admin/Form/Preferences/Display.php
  CRM/Core/Resources.php
  CRM/Utils/Hook.php
  Civi/Core/Container.php
  Civi/Core/Themes.php
  Civi/Core/Themes/Resolvers.php
  settings/Core.setting.php
  templates/CRM/Admin/Form/Preferences/Display.hlp
  templates/CRM/Admin/Form/Preferences/Display.tpl
  tests/extensions/test.extension.uitest/files/foo.css
  tests/extensions/test.extension.uitest/files/ignoreme.css
  tests/extensions/test.extension.uitest/info.xml
  tests/extensions/test.extension.uitest/uitest.php
  tests/phpunit/Civi/Core/Theme/judy/css/bootstrap.css
  tests/phpunit/Civi/Core/Theme/judy/css/civicrm.css
  tests/phpunit/Civi/Core/Theme/liza/css/bootstrap.css
  tests/phpunit/Civi/Core/Theme/liza/css/civicrm.css
  tests/phpunit/Civi/Core/Theme/liza/css/civicrm.min.css
  tests/phpunit/Civi/Core/Theme/liza/test.extension.uitest-files/foo.css
  tests/phpunit/Civi/Core/ThemesTest.php
Labels: merge on pass, sig:extension support

#14525 dev/core#1035 Add in new setting http_timeout to set how long in seco…
  CRM/Utils/Check/Component.php
  settings/Core.setting.php
Labels: 5.15, merge on pass

#14549 5.15
  CRM/Utils/Check/Component.php
  settings/Core.setting.php
Labels: master

#14443 Fix duplicate households on 'Merge same household' exports
  CRM/Export/BAO/Export.php
  CRM/Export/BAO/ExportProcessor.php
  tests/phpunit/CRM/Export/BAO/ExportTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: has-test, master
