Repository civicrm/civicrm-core, pull requests merged in 2019-12, with the labels that each got.

#15995 Remove calls to deprecated pseudoconstant activityType, test
  CRM/Contact/BAO/Query.php
  tests/phpunit/CRM/Contact/BAO/QueryTest.php
Labels: master

#15996 Add testing for various params that pass through Contact_BAO_Query::optionValueQuery
  CRM/Contact/BAO/Query.php
  tests/phpunit/CRM/Contact/BAO/QueryTest.php
  tests/phpunit/CRM/Mailing/BaseMailingSystemTest.php
Labels: master, merge on pass

#16002 Fix regression from fixing relative key handling where custom field no longer exists in the database
  CRM/Contact/BAO/Query.php
  tests/phpunit/CRM/Contact/BAO/SavedSearchTest.php
Labels: 5.20, merge on pass

#16003 Handle custom field deleted 519
  CRM/Contact/BAO/Query.php
  tests/phpunit/CRM/Contact/BAO/SavedSearchTest.php
Labels: 5.19

#16000 dev/core#1434 Fix table alias used in select when ouputting as a chart
  CRM/Report/Form/Mailing/Clicks.php
Labels: master

#16004 5.20
  CRM/Contact/BAO/Query.php
  tests/phpunit/CRM/Contact/BAO/SavedSearchTest.php
Labels: master

#15937 dev/core#1405 Strip any spaces from Option Group name parameter and r…
  CRM/Admin/Form/OptionGroup.php
  CRM/Core/BAO/OptionGroup.php
  CRM/Upgrade/Incremental/php/FiveTwentyOne.php
  tests/phpunit/CRM/Core/BAO/OptionGroupTest.php
  tests/phpunit/CRM/Upgrade/Incremental/BaseTest.php
  tests/phpunit/api/v3/OptionGroupTest.php
  tests/phpunit/api/v3/OptionValueTest.php
Labels: master

#16001 Code style, remove typo, double ;; from code where it makes sense to do so
  CRM/Contact/Form/Search/Custom/FullText/Activity.php
  CRM/Contact/Form/Task/HookSample.php
  CRM/Contribute/ActionMapping/ByPage.php
  CRM/Contribute/ActionMapping/ByType.php
  CRM/Core/BAO/CustomQuery.php
  CRM/Core/BAO/OptionGroup.php
  CRM/Core/BAO/UFField.php
  CRM/Core/Payment/Elavon.php
  CRM/Custom/Page/Group.php
  CRM/Event/ActionMapping.php
  CRM/Event/BAO/Participant.php
  CRM/Event/Import/Parser/Participant.php
  CRM/Member/BAO/Membership.php
  CRM/Price/Form/Option.php
  CRM/UF/Form/Preview.php
  CRM/Upgrade/Incremental/SmartGroups.php
  CRM/Utils/Date.php
  templates/CRM/Admin/Page/Admin.tpl
  templates/CRM/common/additionalBlocks.tpl
  tests/phpunit/CRM/Event/Form/ParticipantTest.php
  tests/phpunit/CiviTest/CiviMailUtils.php
  tests/phpunit/api/v3/SystemCheckTest.php
Labels: master, merge on pass

#15970 [REF] clean up merge array.
  CRM/Export/BAO/ExportProcessor.php
Labels: master

#16007 Add release-notes/5.19.3.md
  release-notes.md
  release-notes/5.19.3.md
Labels: 5.20

#16008 5.20
  release-notes.md
  release-notes/5.19.3.md
Labels: master

#15997 dev/core#1166 Update the name of Macedonia, Republic of to North Macedonia
  CRM/Upgrade/Incremental/sql/5.21.alpha1.mysql.tpl
  sql/civicrm_generated.mysql
  xml/templates/civicrm_country.tpl
Labels: master

#15908 [Test] fix test setup on ANet tests
  CRM/Member/BAO/Membership.php
  api/v3/Order.php
  tests/phpunit/CRM/Core/Payment/PayPalProIPNTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: master

#15974 Make else statement more legible
  CRM/Core/Report/Excel.php
Labels: master

#15946 Make utf8mb4 status check language more for the general consumer
  CRM/Utils/Check/Component/Env.php
Labels: master

#15971 dev/report#23 - Fix contact sub-type 'is not one of' filtering
  CRM/Report/Form.php
  tests/phpunit/api/v3/ReportTemplateTest.php
Labels: has-test, master

#15523 Update PayPalImpl.php
  CRM/Core/Payment/PayPalImpl.php
Labels: master

#16010 [NFC] Remove dinosaur function
  CRM/Case/BAO/Case.php
Labels: master

#15989 dev/core#523 get the Lybunt charts working again
  CRM/Report/Form/Contribute/Lybunt.php
  sql/civicrm_generated.mysql
  xml/templates/civicrm_navigation.tpl
Labels: master

#16013 dev/core#1435 Fix lack of filtering in Contribution tab on Membership or Participant View
  CRM/Contribute/Form/Search.php
Labels: 5.20

#16016 5.20
  CRM/Contribute/Form/Search.php
Labels: master

#16015 5.20
  CRM/Contribute/Form/Search.php
Labels: master

#16014 dev/core#1435 Fix lack of filtering in Contribution tab on Membership…
  CRM/Contribute/Form/Search.php
Labels: 5.19

#16019 Remove unused cancelledStatus assign on contributionView
  CRM/Contribute/Form/ContributionView.php
Labels: master

#16023 [NFC] Fix camelCase variable name following fix for dev/core#1435
  CRM/Contribute/Form/Search.php
Labels: master, merge on pass

#16024 allow PCP report to filter on contribution status
  CRM/Report/Form/Contribute/PCP.php
Labels: master

#16021 Always display amount paid even if it is 0.00. Blank looks like it's missing data rather than nothing paid
  templates/CRM/Contribute/Page/PaymentInfo.tpl
Labels: master

#16027 5.20.0 release notes: final edits
  release-notes.md
  release-notes/5.20.0.md
Labels: 5.20

#16026 [NFC] code cleanup in test class.
  tests/phpunit/CRM/Member/Form/MembershipTest.php
Labels: master

#16028 5.20
  release-notes.md
  release-notes/5.20.0.md
Labels: master

#16006 dev/core#1426 Return correct manager role info during Case api get
  CRM/Case/BAO/Case.php
  tests/phpunit/api/v3/CaseTest.php
Labels: master

#16031 Fix typo, Mailign should be Mailing
  CRM/Group/Form/Edit.php
  templates/CRM/Group/Form/Edit.tpl
Labels: master

#16036 5.21.0 release notes: initial run
  release-notes.md
  release-notes/5.21.0.md
Labels: 5.21

#16037 5.21
  release-notes.md
  release-notes/5.21.0.md
Labels: master

#15975 dev/core#1425 More aggressively deprecate old setItem & setOptionValue functions on BAO_Setting
  CRM/Core/BAO/Setting.php
  tests/phpunit/CRM/Core/BAO/PreferencesTest.php
Labels: master

#16033 dev/core#1447 Fix hard fail on upgrade due to duplicate names in the …
  CRM/Upgrade/Incremental/php/FiveTwentyOne.php
  tests/phpunit/CRM/Upgrade/Incremental/BaseTest.php
Labels: 5.21, merge ready

#16040 5.21
  CRM/Upgrade/Incremental/php/FiveTwentyOne.php
  tests/phpunit/CRM/Upgrade/Incremental/BaseTest.php
Labels: master

#16043 Update Smart Group form unsets the existing Group Types
  CRM/Contact/Form/Task/SaveSearch/Update.php
Labels: master

#16042 Update Smart Group form uses different labels for Group Title and Group Description
  CRM/Contact/Form/Task/SaveSearch.php
Labels: master

#16044 [REF] Replace Deprecated function CRM_Core_BAO_Setting::setItem with …
  CRM/Core/BAO/Navigation.php
Labels: master, merge on pass

#16045 [NFC] Add in a unit test of passing an array into the Civi::settings …
  tests/phpunit/Civi/Core/SettingsManagerTest.php
Labels: master

#16034 dev/core#1449 Do not dispatch pre/post hooks during upgrade
  CRM/Utils/Hook.php
Labels: 5.21, merge on pass

#16046 dev/core#1449 Do not dispatch pre and post hooks whilst we are in an …
  CRM/Utils/Hook.php
Labels: 5.20, merge on pass

#16038 Proper Fix for dev/core#1422
  CRM/Event/Form/Search.php
Labels: master

#16049 5.21
  CRM/Utils/Hook.php
Labels: master

#16047 dev/membership#21 Fix regression causing transfer of membership to another contact if they paid
  CRM/Member/Form/Membership.php
Labels: 5.21

#15927 [REF] Move wrangling of Front end form contribution param for autoRenew back to form
  CRM/Contribute/Form/Contribution.php
  CRM/Contribute/Form/Contribution/Confirm.php
  CRM/Contribute/Form/Contribution/Main.php
  CRM/Contribute/Form/ContributionBase.php
  CRM/Event/Form/Registration/Confirm.php
  CRM/Member/Form/Membership.php
  CRM/Member/Form/MembershipRenewal.php
  CRM/Price/BAO/PriceSet.php
Labels: master

#16048 dev/membership#21 Fix regression on transferring member to another contact if they paid
  CRM/Member/Form/Membership.php
Labels: 5.20

#16051 5.21
  CRM/Member/Form/Membership.php
Labels: master

#15942 Add in searchFieldMetadata for contact_tags, contact_type, group and …
  CRM/Activity/Form/Search.php
  CRM/Case/Form/Search.php
  CRM/Core/Form/Search.php
  CRM/Grant/Form/Search.php
Labels: master, merge on pass

#16050 [NFC] code cleanup
  CRM/Contribute/BAO/Contribution.php
  CRM/Member/Form/Membership.php
Labels: master, merge on pass

#16055 [REF] Refactor Campaign Search form to use standardised getSortID fun…
  CRM/Campaign/Form/Search.php
Labels: master

#16053 [REF] Refactor Activity Search to use parent getSortID function
  CRM/Activity/Form/Search.php
Labels: master, merge on pass

#16054 [REF] Refactor Contact Search form to use standardised getSortID func…
  CRM/Contact/Form/Search.php
Labels: master

#16056 [REF] Minor simplification on additional_participants checks
  CRM/Event/Form/Registration/Register.php
Labels: master

#16058 Fix js error on choosing membership type
  CRM/Member/Form.php
  templates/CRM/Member/Form/Membership.tpl
Labels: master

#16061 dev/core#1460 move post hook to avoid errors with custom fields created in the hook
  CRM/Contribute/BAO/Contribution.php
Labels: 5.21

#16064 5.21
  CRM/Contribute/BAO/Contribution.php
Labels: master

#16066 5.21
  Civi/Payment/PropertyBag.php
  tests/phpunit/Civi/Payment/PropertyBagTest.php
Labels: master

#16063 [NFC] Add in unit test for dev/core#1460
  tests/phpunit/CRMTraits/Custom/CustomDataTrait.php
  tests/phpunit/api/v3/ContributionTest.php
Labels: master, merge on pass

#16068 5.20.1 - Version bump. Add release notes.
  CRM/Upgrade/Incremental/sql/5.20.1.mysql.tpl
  release-notes.md
  release-notes/5.20.1.md
  sql/civicrm_generated.mysql
  xml/version.xml
Labels: 5.20

#16069 Add release-notes/5.20.1
  release-notes.md
  release-notes/5.20.1.md
Labels: 5.21

#16070 5.21
  release-notes.md
  release-notes/5.20.1.md
Labels: master

#16073 dev/core#1463 rc Fix record payment form errors
  CRM/Contribute/Form/AdditionalPayment.php
Labels: 5.20

#16071 dev/core#1463 Fix record payment form errors
  CRM/Contribute/Form/AdditionalPayment.php
Labels: 5.21, merge on pass

#16067 Swap out fatal for statusBounce for disabled or unpermitted forms
  CRM/Activity/Form/ActivityView.php
  CRM/Admin/Form/Options.php
  CRM/Admin/Page/ScheduleReminders.php
  CRM/Campaign/Form/Petition/Signature.php
  CRM/Campaign/Form/SurveyType.php
  CRM/Case/Form/ActivityView.php
  CRM/Case/Form/Search.php
  CRM/Case/Form/Task/Delete.php
  CRM/Case/Page/DashBoard.php
  CRM/Case/Page/Tab.php
  CRM/Contact/Page/View/UserDashBoard.php
  CRM/Contribute/Form/Contribution.php
  CRM/Contribute/Form/ContributionBase.php
  CRM/Contribute/Form/ContributionPage.php
  CRM/Contribute/Form/ContributionPage/Delete.php
  CRM/Contribute/Form/Task/Delete.php
  CRM/Core/Page/Basic.php
  CRM/Dashlet/Page/AllCases.php
  CRM/Dashlet/Page/CaseDashboard.php
  CRM/Dashlet/Page/MyCases.php
  CRM/Event/Form/ManageEvent/Delete.php
  CRM/Event/Form/Registration.php
  CRM/Event/Form/Task/Delete.php
  CRM/Event/Page/ParticipantListing.php
  CRM/Event/Page/ParticipantListing/NameStatusAndDate.php
  CRM/Financial/Form/FinancialType.php
  CRM/Financial/Page/FinancialType.php
  CRM/Friend/Form.php
  CRM/Grant/Form/Grant.php
  CRM/Grant/Form/Task/Delete.php
  CRM/Grant/Form/Task/Update.php
  CRM/Member/Form.php
  CRM/Member/Form/Task/Delete.php
  CRM/Pledge/Form/Payment.php
  CRM/Pledge/Form/Pledge.php
  CRM/Pledge/Form/Task/Delete.php
  CRM/Price/BAO/PriceSet.php
  CRM/UF/Form/Inline/Preview.php
  CRM/UF/Form/Inline/PreviewById.php
  tests/phpunit/CRM/Financial/BAO/FinancialTypeTest.php
Labels: master, merge on pass

#16074 5.21
  CRM/Contribute/Form/AdditionalPayment.php
Labels: master

#16075 [REF] Convert more petition signature fatals to status bounce
  CRM/Campaign/Form/Petition/Signature.php
Labels: master, merge on pass

#16076 5.21 Release notes: First Pass
  contributor-key.yml
  release-notes/5.21.0.md
Labels: 5.21

#16077 5.21
  contributor-key.yml
  release-notes/5.21.0.md
Labels: master

#16072 Code cleanup Update Paypal invokeApi to only throw exceptions.
  CRM/Core/Payment/PayPalImpl.php
Labels: master, merge on pass

#16087 dev/core#1467 - Multiple participant registration sends only p1 amoun…
  CRM/Event/Form/Registration.php
Labels: 5.21, merge on pass

#16082 dev/core#1467 - Multiple participant registration sends only p1 amoun…
  CRM/Event/Form/Registration.php
Labels: 5.20

#16086 5.21
  CRM/Event/Form/Registration.php
  Civi/Payment/PropertyBag.php
  tests/phpunit/Civi/Payment/PropertyBagTest.php
Labels: master

#16080 Remove unnecessary query when updating org, if no name update.
  CRM/Contact/BAO/Contact.php
  CRM/Contact/BAO/Contact/Utils.php
Labels: master

#16089 Set version and release-notes for 5.20.2
  CRM/Upgrade/Incremental/sql/5.20.2.mysql.tpl
  release-notes.md
  release-notes/5.20.2.md
  sql/civicrm_generated.mysql
  xml/version.xml
Labels: 5.20

#16090 Add release-notes/5.20.2
  release-notes.md
  release-notes/5.20.2.md
Labels: 5.21

#16057 dev/core#1444 Permit activities with campaigns on contact tab for con…
  CRM/Activity/BAO/Activity.php
Labels: 5.21

#16091 5.21
  CRM/Activity/BAO/Activity.php
  release-notes.md
  release-notes/5.20.2.md
Labels: master

#16092 Fix Release note header
  release-notes/5.20.2.md
Labels: 5.21

#16093 5.21
  release-notes/5.20.2.md
Labels: master

#16094 dev/core/issues/1470, show labels instead name for activity type
  ang/crmCaseType/activityTypesTable.html
Labels: master

#16088 Paypal class cleanup
  CRM/Core/Payment/PayPalImpl.php
Labels: master

#16078 Allow Angular modules to provide dynamic HTML snippets
  CRM/Utils/Hook.php
  Civi/Angular/Manager.php
Labels: master, merge on pass

#16096 E notice fix on Price set form
  CRM/Price/Form/Field.php
  CRM/Price/Form/Set.php
Labels: master

#16052 Fix unreleased regression where processors using getPaymentDescription get a fatal
  CRM/Core/Payment.php
  CRM/Core/Payment/Dummy.php
  Civi/Payment/PropertyBag.php
  tests/phpunit/api/v3/PaymentProcessorTest.php
Labels: 5.21

#16103 5.21 to master
  CRM/Core/Payment.php
  CRM/Core/Payment/Dummy.php
  Civi/Payment/PropertyBag.php
  tests/phpunit/api/v3/PaymentProcessorTest.php
Labels: master

#16107 dev/core#1477 Fix fatal error when editing reserved option group settings
  CRM/Admin/Form/OptionGroup.php
Labels: 5.21, merge on pass

#16108 5.21
  CRM/Admin/Form/OptionGroup.php
Labels: master

#16110 Add in Country and StateProvince APIv4 Entities
  Civi/Api4/Country.php
  Civi/Api4/StateProvince.php
  tests/phpunit/api/v3/CountryTest.php
  tests/phpunit/api/v3/StateProvinceTest.php
Labels: master, merge on pass

#16109 [REF] Switch CRM_Utils_Error::fatal calls for CRM_Core_Exception in G…
  CRM/Grant/BAO/Grant.php
  CRM/Utils/Hook.php
  CRM/Utils/HttpClient.php
  CRM/Utils/Mail.php
  CRM/Utils/Mail/EmailProcessor.php
  CRM/Utils/Migrate/Export.php
  CRM/Utils/Migrate/Import.php
  CRM/Utils/System.php
  CRM/Utils/Type.php
  CRM/Utils/Weight.php
  Civi/Angular/Page/Modules.php
  bin/ContributionProcessor.php
Labels: master

#16111 dev/core#1472 fix price field money clean
  CRM/Price/Form/Field.php
Labels: master

#16114 [NFC] cleanup to declared exceptions, quotes, strict mode.
  Civi/API/Kernel.php
Labels: master, merge on pass

#16115 Remove vestige of apiv2
  Civi/API/Kernel.php
Labels: master

#16101 dev/core#1474 - (On Hold) text missing from email column when custom …
  CRM/Contact/Selector.php
  tests/phpunit/CRM/Contact/SelectorTest.php
Labels: master

#15972 report#24 - Case Detail report - fix 'Active role?' when no relationships
  CRM/Report/Form/Case/Detail.php
  CRM/Report/Form/Case/Summary.php
Labels: master

#15968 dev/core#1424 Support MS Excel for diacritic characters when exporting to csv
  CRM/Export/BAO/ExportProcessor.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: master, merge ready

#16119 [Ref] Remove php4 support from BAO_Acl class
  CRM/ACL/BAO/ACL.php
Labels: master, merge on pass

#16121 dev/core#1490 Fix syntax error in Membership Receipt
  CRM/Upgrade/Incremental/MessageTemplates.php
  xml/templates/message_templates/membership_online_receipt_html.tpl
Labels: 5.21

#16123 5.21 to master
  CRM/Upgrade/Incremental/MessageTemplates.php
  xml/templates/message_templates/membership_online_receipt_html.tpl
Labels: master

#16120 dev/core#1485 Fix field name for join_date to be membership_join_date…
  CRM/Member/Import/Parser/Membership.php
Labels: 5.21

#16126 5.21 to master
  CRM/Member/Import/Parser/Membership.php
Labels: master

#16127 Unit test for https://github.com/civicrm/civicrm-core/pull/16120
  tests/phpunit/CRM/Member/Import/Parser/MembershipTest.php
Labels: master, merge on pass

#16124 Remove function marked as deprecated & unused by core nearly a year ago
  CRM/ACL/BAO/ACL.php
Labels: master

#16128 backports from rc
  CRM/Member/Import/Parser/Membership.php
  CRM/Upgrade/Incremental/MessageTemplates.php
  xml/templates/message_templates/membership_online_receipt_html.tpl
Labels: 5.20

#16125 dev/core#1482 Remove lines of code that appear to relate to legacy logic
  CRM/Contact/BAO/Contact.php
Labels: master

#16130 Fix output display in api4 explorer
  ang/api4Explorer/Explorer.js
Labels: master

#16133 [NFC] Test clean up.
  tests/phpunit/api/v3/JobTest.php
Labels: master, merge on pass

#16137 [REF] Minor cleanup - declare exceptions, use single quotes, strict comparison
  CRM/Contact/BAO/Relationship.php
  CRM/Member/BAO/Membership.php
  tests/phpunit/api/v3/ContributionTest.php
Labels: master

#16138 Switch static var to using Civi::statics
  CRM/Member/BAO/Membership.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: master

#16122 [NFC] If statement is always true
  CRM/Report/Form/Instance.php
Labels: master

#16134 Remove legacy_redirect_path handling
  CRM/Core/LegacyErrorHandler.php
  CRM/Member/BAO/Membership.php
Labels: master

#16132 [REF] step towards wiping out $ids array in membership bao functions
  CRM/Member/BAO/Membership.php
  CRM/Member/Form/Task/Batch.php
  tests/phpunit/api/v3/MembershipTest.php
Labels: master

#16141 dev/core#560 Remove instances of fatal errors
  CRM/Contact/BAO/Contact/Utils.php
Labels: master, merge on pass

#16142 [NFC] Declare exceptions, use single quotes where possible, use strict comparison
  api/v3/utils.php
Labels: master, merge on pass

#16143 Fix misleading error message on deadlock
  api/v3/utils.php
  tests/phpunit/api/v3/UtilsTest.php
Labels: master, merge on pass

#16144 dev/core#1486 Add index to civicrm_acl_cache.modified_date
  CRM/ACL/DAO/ACLCache.php
  xml/schema/ACL/Cache.xml
Labels: master, merge on pass

#16145 Add api to check for missing indices
  CRM/Utils/Check/Component/Schema.php
  api/v3/System.php
  tests/phpunit/CRM/Core/BAO/SchemaHandlerTest.php
Labels: master, merge on pass

#16136 [REF] remove CRM_Core_Error check
  CRM/Member/BAO/Membership.php
Labels: master

#16140 dev/event#25 Fix regression on billing name overwrite
  CRM/Event/Form/Registration/Confirm.php
  CRM/Event/Form/Registration/Register.php
Labels: 5.21

#16147 dev/event#25 Fix regression on billing name overwrite
  CRM/Event/Form/Registration/Confirm.php
  CRM/Event/Form/Registration/Register.php
Labels: 5.20, merge on pass

#16112 Remove unneeded zendframwork/zend-validator and zendframwork/zend-stdlib packages as not required by …
  composer.lock
Labels: master

#16131 [Ref] improve readability of acl code
  CRM/ACL/BAO/ACL.php
Labels: master

#16151 [REF] extract member form batch update & add test
  CRM/Member/Form/Task/Batch.php
  tests/phpunit/CRM/Member/Form/Task/BatchTest.php
Labels: master

#16135 [REF] simplify recordAdjustedAmt function
  CRM/Price/BAO/LineItem.php
Labels: master

#16079 Remove unnecessary, and possibly incorrect query from email update
  CRM/Core/BAO/Email.php
  tests/phpunit/CRM/Core/BAO/EmailTest.php
  tests/phpunit/api/v3/EmailTest.php
Labels: master

#15135 Add case activity action links to activity report
  CRM/Report/Form/Activity.php
Labels: master, merge ready

#16152 Api4 - Fix auto serialize array input for CheckBox/MultiSelect fields
  CRM/Core/BAO/CustomField.php
  CRM/Core/BAO/CustomValueTable.php
  tests/phpunit/api/v4/Action/CustomValueTest.php
Labels: master

#16155 dev/core#183 Ensure that having a rule where each field is the same w…
  CRM/Dedupe/BAO/RuleGroup.php
  tests/phpunit/CRM/Dedupe/DedupeFinderTest.php
Labels: 5.21, has-test

#16156 5.21
  CRM/Dedupe/BAO/RuleGroup.php
  CRM/Event/Form/Registration/Confirm.php
  CRM/Event/Form/Registration/Register.php
  tests/phpunit/CRM/Dedupe/DedupeFinderTest.php
Labels: master

#16157 dev/drupal#99 Fix E-notice on undefined property id of non object
  CRM/Core/BAO/UFMatch.php
Labels: master

#16159 Bump to 5.20.3. Add release notes.
  CRM/Upgrade/Incremental/sql/5.20.3.mysql.tpl
  release-notes.md
  release-notes/5.20.3.md
  sql/civicrm_generated.mysql
  xml/version.xml
Labels: 5.20

#16160 5.20.3 Release Notes
  release-notes.md
  release-notes/5.20.3.md
Labels: 5.21

#16161 5.21
  release-notes.md
  release-notes/5.20.3.md
Labels: master

#16154 Allow values to be passed to api4 GetFields
  Civi/Api4/Action/CustomValue/GetFields.php
  Civi/Api4/Generic/BasicGetFieldsAction.php
  Civi/Api4/Generic/DAOGetFieldsAction.php
  Civi/Api4/Service/Spec/SpecGatherer.php
  ang/api4Explorer/Explorer.html
  ang/api4Explorer/Explorer.js
  tests/phpunit/api/v4/Action/BaseCustomValueTest.php
  tests/phpunit/api/v4/Action/BasicCustomFieldTest.php
Labels: has-test, master

#16117 dev/core#1424 Support MS Excel for Diacritic Characters when exporting a report to CSV
  CRM/Report/Utils/Report.php
Labels: master

#16149 dev/core#1489 do not reconcile managed entities whilst in upgrade mod…
  CRM/Core/ManagedEntities.php
  CRM/Upgrade/Form.php
  CRM/Utils/Hook.php
Labels: master

#16163 [NFC] Clean up unit test
  tests/phpunit/CRM/Member/BAO/MembershipLogTest.php
Labels: master, merge on pass

#16164 Add controlField metadata for ChainSelect fields
  CRM/Core/CodeGen/Specification.php
  CRM/Core/DAO/Address.php
  xml/schema/Core/Address.xml
Labels: master

#16165 [NFC] Extract duplicated code lines in test
  tests/phpunit/CRM/Member/BAO/MembershipTest.php
Labels: master

#16169 Final 5.21.0 release notes
  CONTRIBUTORS.txt
  contributor-key.yml
  release-notes/5.10.2.md
  release-notes/5.10.4.md
  release-notes/5.11.0.md
  release-notes/5.13.1.md
  release-notes/5.13.2.md
  release-notes/5.13.5.md
  release-notes/5.14.0.md
  release-notes/5.16.1.md
  release-notes/5.18.0.md
  release-notes/5.19.0.md
  release-notes/5.20.1.md
  release-notes/5.21.0.md
Labels: master

#16170 5.21.0 releasenotes final
  CONTRIBUTORS.txt
  contributor-key.yml
  release-notes/5.10.2.md
  release-notes/5.10.4.md
  release-notes/5.11.0.md
  release-notes/5.13.1.md
  release-notes/5.13.2.md
  release-notes/5.13.5.md
  release-notes/5.14.0.md
  release-notes/5.16.1.md
  release-notes/5.18.0.md
  release-notes/5.19.0.md
  release-notes/5.20.1.md
  release-notes/5.21.0.md
Labels: 5.21
