Repository civicrm/civicrm-core, pull requests merged in 2019-03, with the labels that each got.

#13728 dev/core#769 - Fix for ZipArchive->open() PHP bug
  CRM/Financial/BAO/ExportFormat.php
Labels: master

#13736 CiviCRM Membership Detail report, add column to display if membership is Primary or Inherited
  CRM/Report/Form/Member/Detail.php
Labels: master, merge on pass

#13724 Status of test contribution is not fetched on ThankYou page.
  CRM/Contribute/Form/Contribution/ThankYou.php
  tests/phpunit/CRM/Contribute/Form/Contribution/ThankYouTest.php
Labels: master

#13737 Fix up e-notice error when using a user from email address same issue…
  CRM/Contribute/Form/Task/PDF.php
Labels: 5.11, merge on pass

#13738 dev/core#768 - Fix fatal error on group search
  CRM/Contact/BAO/Query.php
Labels: 5.11, merge on pass

#13740 5.11
  CRM/Contact/BAO/Query.php
  CRM/Contribute/Form/Task/PDF.php
Labels: master

#13718 Decommision getPartialPaymentTrxn function
  CRM/Core/BAO/FinancialTrxn.php
  CRM/Financial/BAO/Payment.php
  tests/phpunit/CRM/Core/BAO/FinancialTrxnTest.php
Labels: master

#13734 dev/membership#10 fix incorrect validation error saying Start date must be the same or later than Member since
  CRM/Member/Form/Membership.php
Labels: 5.11

#13739 Fix the invocation of post hook for ParticipantPayment ensuring that …
  CRM/Event/BAO/ParticipantPayment.php
Labels: master, merge on pass

#13566 dev/core#708, Fix Qill for Added by and Modified By
  CRM/Contact/BAO/Query.php
Labels: master

#13744 Upgrader: Don't abort if state_province already exists
  CRM/Upgrade/Incremental/sql/4.7.30.mysql.tpl
  CRM/Upgrade/Incremental/sql/4.7.32.mysql.tpl
Labels: master

#13743 CRM/Contact - Fix fatal error on tag search
  CRM/Contact/BAO/Query.php
Labels: 5.11

#13745 Allow viewing of cancelled recurring contributions
  CRM/Contribute/Page/Tab.php
Labels: master

#13731 dev/core#731 Add upgrade routine to convert on_hold to an array for sites with
  CRM/Upgrade/Incremental/SmartGroups.php
  CRM/Upgrade/Incremental/php/FiveEleven.php
  tests/phpunit/CRM/Upgrade/Incremental/BaseTest.php
Labels: 5.11, merge on pass

#13747 merge 5.11 to master
  CRM/Contact/BAO/Query.php
  CRM/Member/Form/Membership.php
  CRM/Upgrade/Incremental/SmartGroups.php
  CRM/Upgrade/Incremental/php/FiveEleven.php
  tests/phpunit/CRM/Upgrade/Incremental/BaseTest.php
Labels: master

#13400 fix broken logic in CRM_Utils_System_DrupalBase::formatResourceUrl()
  CRM/Utils/System/DrupalBase.php
Labels: master

#13690 Clean up Payment.create function
  CRM/Financial/BAO/Payment.php
Labels: master

#13741 dev/core#770 - View Case Activity page displays disabled custom fields
  CRM/Case/XMLProcessor/Report.php
Labels: master, merge on pass

#13753 Fix Custom post outer div class on event registration form
  templates/CRM/Event/Form/Registration/Register.tpl
Labels: master, merge on pass

#13695 [ref] Extract activity payment creation
  CRM/Contribute/BAO/Contribution.php
Labels: master

#13755 dev/core#766 fix loss of custom fields when creating an event from template
  CRM/Core/DAO.php
Labels: 5.11

#13757 [REF] extract getToFinancialAccount from CRM_Contribute_PseudoConstantt::contributionStatus
  CRM/Contribute/BAO/Contribution.php
Labels: master, merge on pass

#13653 reporting#8 - add thank-you dates to Contribution Summary/Detail reports
  CRM/Report/Form/Contribute/Detail.php
  CRM/Report/Form/Contribute/Summary.php
Labels: master

#13760 5.11
  CRM/Core/DAO.php
Labels: master

#13726 dev/core#767 Add 'Cancelled / Refunded Date' and 'Cancellation / Refund Reason'
  CRM/Report/Form/Contribute/Detail.php
Labels: master

#13761 report clean up - remove redundant code
  CRM/Report/Form/Event/ParticipantListing.php
Labels: master

#13664 Rationalise Activity api ACLs for consistency, to respect the hook & improve performance
  CRM/Activity/BAO/Activity.php
  CRM/Core/Permission.php
  api/v3/Activity.php
  tests/phpunit/CRMTraits/ACL/PermissionTrait.php
  tests/phpunit/api/v3/ACLPermissionTest.php
Labels: master

#13751 Upgrade Karma version to latest version
  package-lock.json
  package.json
Labels: master, merge on pass

#13765 Try and add data set example where email_on_hold / on_hold is NULL in…
  tests/phpunit/CRM/Contact/BAO/SavedSearchDataSets/251_empty_email_on_hold.sql
Labels: master, merge on pass

#13720 Speed up contribution results by removing join on civicrm_financial_type table when rendering search results.
  CRM/Contact/BAO/Query.php
  CRM/Contribute/BAO/Contribution.php
  CRM/Contribute/BAO/Query.php
  CRM/Core/DAO.php
  tests/phpunit/CRM/Contribute/BAO/QueryTest.php
  tests/phpunit/CRM/Export/BAO/ExportTest.php
Labels: has-test, master, merge on pass

#13746 Convert activity_date_time field to datepicker and add support for url input
  CRM/Activity/BAO/Query.php
  CRM/Activity/Form/Search.php
  CRM/Contact/BAO/Query.php
  CRM/Contact/Form/Search/Basic.php
  CRM/Core/Form.php
  CRM/Core/Form/Search.php
  CRM/Pledge/Form/Search.php
  CRM/Upgrade/Incremental/SmartGroups.php
  CRM/Upgrade/Incremental/php/FiveTwelve.php
  templates/CRM/Activity/Form/Search/Common.tpl
  tests/phpunit/CRM/Upgrade/Incremental/BaseTest.php
Labels: master, merge on pass

#13735 Extract getSearchSQLParts function
  CRM/Campaign/Selector/Search.php
  CRM/Contact/BAO/GroupContactCache.php
  CRM/Contact/BAO/Query.php
Labels: master

#13759 [REF] towards cleanup of update membership code
  CRM/Contribute/BAO/Contribution.php
Labels: master

#13758 Do not load membership contribution as updateMembershipBasedOnCompletionOfContribution loads it within the function
  CRM/Financial/BAO/Payment.php
Labels: master

#13769 Removes redundant IF
  CRM/Contribute/BAO/Contribution.php
Labels: master, merge on pass

#13771 Fix typo in comments
  CRM/Core/BAO/OptionValue.php
Labels: master, merge on pass

#13754 dev/core#745 do not filter on 'on_hold' if it is an empty string
  CRM/Contact/BAO/Query.php
Labels: 5.11

#13756 [REF] separate financial handling & component transitioning in Payment.create
  CRM/Financial/BAO/Payment.php
Labels: master

#13776 dev/core#644 fix from address before calling hook
  CRM/Core/BAO/MessageTemplate.php
Labels: master

#13283 Render Note field tokens correctly - they are already HTML.
  Civi/Token/TokenRow.php
Labels: master

#13766 Fix api bug whereby 0 & '0' are not accepted as range parameters for BETWEEN
  CRM/Core/DAO.php
  tests/phpunit/api/v3/ContactTest.php
Labels: has-test, master

#13770 Remove mcrypt system status check
  CRM/Utils/Check/Component/Env.php
Labels: master

#13773 dev/core#745 Further on_hold fix - it has been suggested the value might be an array like ['']
  CRM/Contact/BAO/Query.php
Labels: 5.11

#13594 5.11.0 release notes
  contributor-key.yml
  release-notes.md
  release-notes/5.10.2.md
  release-notes/5.10.3.md
  release-notes/5.10.4.md
  release-notes/5.11.0.md
Labels: 5.11

#13777 Merge forward 5.11 => master
  CRM/Contact/BAO/Query.php
  CRM/Upgrade/Incremental/sql/5.11.0.mysql.tpl
  contributor-key.yml
  release-notes.md
  release-notes/5.10.2.md
  release-notes/5.10.3.md
  release-notes/5.10.4.md
  release-notes/5.11.0.md
Labels: master

#13780 CRM-21677 - report clean up
  CRM/Report/Form/Contact/Summary.php
Labels: master

#13782 [NFC] template whitespace cleanup
  templates/CRM/Contribute/Form/Contribution/Confirm.tpl
Labels: master, merge on pass

#13784 Remove reference to google checkout
  templates/CRM/Event/Form/Registration/Confirm.tpl
Labels: master

#13786 dev/core#562 remove more instances of ->free()
  CRM/Contribute/BAO/Contribution.php
  CRM/Core/BAO/Cache.php
  CRM/Core/BAO/SchemaHandler.php
  CRM/Core/PrevNextCache/Redis.php
Labels: master, merge on pass

#13774 Fatal error to exception on Membership BAO
  CRM/Member/BAO/Membership.php
Labels: master

#13790 CRM-21677 - report clean up
  CRM/Report/Form/Contribute/Lybunt.php
Labels: master, merge on pass

#13792 CRM-21677 - sybunt report clean up
  CRM/Report/Form/Contribute/Sybunt.php
Labels: master

#13700 CRM-21008 - Checkbox to explicitly change employer when sharing address
  CRM/Contact/BAO/Contact/Utils.php
  CRM/Contact/Form/Edit/Address.php
  CRM/Core/BAO/Address.php
  templates/CRM/Contact/Form/Contact.hlp
  templates/CRM/Contact/Form/ShareAddress.tpl
  tests/phpunit/api/v3/AddressTest.php
Labels: has-test, master

#13781 Standardise setTitle method on forms
  CRM/Contribute/Form/ContributionBase.php
  CRM/Core/Form.php
  CRM/Event/Form/Registration.php
Labels: master

#13791 Attempted test fix
  tests/phpunit/api/v3/LoggingTest.php
Labels: master

#13783 [REF] minor code simplification - remove over-handling of amount comp with zero
  CRM/Contribute/Form/Contribution/Confirm.php
Labels: master

#13805 checkEditInboundEmailsPermissions should be a static function
  CRM/Activity/BAO/Activity.php
Labels: master, merge on pass

#13803 civicrm/admin/setting/uf - Fix advice about Backdrop Views ($database_prefix)
  CRM/Admin/Form/Setting/UF.php
  templates/CRM/Admin/Form/Setting/UF.tpl
Labels: master, merge on pass

#13806 [NFC] reformat Contact api file to switch to new array formatting
  api/v3/Contact.php
Labels: master

#13808 (ops#878) (Fast)ArrayDecorator - Emit expected exception when using WP and strict PSR-16
  CRM/Utils/Cache/ArrayDecorator.php
  CRM/Utils/Cache/FastArrayDecorator.php
Labels: 5.12

#13817 5.12 to master
  CRM/Utils/Cache/ArrayDecorator.php
  CRM/Utils/Cache/FastArrayDecorator.php
Labels: master

#13812 Add comments about usage for doPayment() function
  CRM/Core/Payment.php
Labels: master

#13814 Add a class to handle test entities consistently
  CRM/Activity/Selector/Search.php
  CRM/Contribute/BAO/ContributionSoft.php
  CRM/Contribute/Page/ContributionRecurPayments.php
  CRM/Core/TestEntity.php
  CRM/Event/Form/ParticipantView.php
  CRM/Event/Selector/Search.php
  CRM/Member/Form/MembershipView.php
  CRM/Member/Selector/Search.php
  CRM/Pledge/Selector/Search.php
  tests/phpunit/WebTest/Event/AddParticipationTest.php
Labels: master

#13383 (dev/core#491) Standardise the adding of campaign fields on the maili…
  CRM/Report/Form/Mailing/Summary.php
  CRM/Upgrade/Incremental/php/FiveThirteen.php
Labels: master, merge on pass, ok-without-test

#13801 Fix unrelased regression where activity date relative filters are ingnored in the rc
  CRM/Contact/BAO/Query.php
  tests/phpunit/CRM/Activity/Form/SearchTest.php
Labels: 5.12

#13811 (ops#878) Enforce common signature for CRM_Utils_System::loadBootStrap(). Fix WP E2E error.
  CRM/Utils/System/Base.php
  CRM/Utils/System/Soap.php
  CRM/Utils/System/UnitTests.php
  CRM/Utils/System/WordPress.php
Labels: master

#13810 (ops#878) phpunit.xml.dist - Prevent conflict in WordPress E2E with "stderr=true"
  phpunit.xml.dist
Labels: master, merge on pass

#13818 5.12 to master
  CRM/Contact/BAO/Query.php
  tests/phpunit/CRM/Activity/Form/SearchTest.php
Labels: master

#13703 Use temp table methods; provide TempTable::getCreateSql() method for debugging
  CRM/Contact/Form/Search/Custom/DateAdded.php
  CRM/Contact/Form/Task.php
  CRM/Utils/SQL/TempTable.php
Labels: master

#13802 Membership form address fields for payment processors
  CRM/Member/Form/Membership.php
Labels: master

#13799 Upgrade zetacomponents/base and zetacomponents/mail
  CRM/Utils/Mail/EmailProcessor.php
  composer.json
  composer.lock
  tests/phpunit/CRM/Utils/Mail/data/bounces/test_nested_message.eml
Labels: master

#13778 [REF] small cleanups on payment.create flow.
  CRM/Contribute/BAO/Contribution.php
  CRM/Financial/BAO/Payment.php
Labels: master

#13816 core#798 - fix rendering of public-facing prefix/suffix select2
  css/civicrm.css
Labels: master, ok-without-test, sig:bug

#13822 Update lockfile to take into account of civicrm/zetacomponents-mail#4…
  composer.lock
Labels: master, merge on pass

#13797 Further cleanup on getRelatedMemberships - just get them with the api
  CRM/Contribute/BAO/Contribution.php
Labels: master

#13796 dev/core#659 Catch payment processor exceptions, log, hide, do not return 500 error
  CRM/Core/Payment.php
Labels: 5.12, merge on pass

#13828 5.12 to master
  CRM/Core/Payment.php
Labels: master

#13829 [nfc] Attempt to improve false negatives on Logging test
  tests/phpunit/api/v3/LoggingTest.php
Labels: has-test, master

#13824 Make cacheCode optional in CRM.loadScript
  js/Common.js
Labels: master, merge on pass

#13779 Display test contributions when viewing contributions related to a test recurring contribution
  CRM/Contribute/Page/ContributionRecurPayments.php
Labels: master, merge on pass

#13830 NFC Whitespace cleanup MembershipBlock.tpl
  templates/CRM/Contribute/Form/Contribution/MembershipBlock.tpl
Labels: master

#13826 (NFC, infra/ops#878) AssetBuilderTest - Relax getUrl() assertion for WP compat
  tests/phpunit/E2E/Core/AssetBuilderTest.php
Labels: master

#13820 dev/core#790 - Exclue menubar on frontend pages
  CRM/Core/Resources.php
Labels: 5.12, merge ready

#13833 5.12 to master
  CRM/Core/Resources.php
Labels: master

#13825 dev/core#801 Fix from email on PDF Letters, such as Thank You Letters.
  CRM/Contribute/Form/Task/PDFLetterCommon.php
Labels: 5.12

#13834 5.12
  CRM/Contribute/Form/Task/PDFLetterCommon.php
Labels: master

#13793 REF Extract case action links into a separate function to facilitate refactoring
  CRM/Case/BAO/Case.php
Labels: master

#13823 Import date test
  CRM/Contact/Import/Parser/Contact.php
  CRM/Contribute/Import/Parser/Contribution.php
  tests/phpunit/CRM/Contribute/Import/Parser/ContributionTest.php
Labels: has-test, master

#13832 Logging - attempt to fix tests
  tests/phpunit/api/v3/LoggingTest.php
Labels: master

#13836 [NFC] remove unnecessary variable
  CRM/Event/Form/Registration/Confirm.php
Labels: master, merge on pass

#13841 Remove amavisd now that it is removed from the packages repository
  distmaker/dists/common.sh
Labels: master, merge on pass

#13835 Deploy PEAR Log package and upgrade to latest version in the process
  composer.json
  composer.lock
Labels: master

#13838 Minor code cleanup - remove unnecessary ids declaration
  CRM/Event/Form/Registration/Confirm.php
Labels: master

#13839 Minor code cleanup
  CRM/Contribute/Form/Contribution/ThankYou.php
  CRM/Event/Form/Registration/ThankYou.php
  CRM/Invoicing/Utils.php
Labels: master

#13807 Fix contact.merge api to pass check_permissions parameter through to the deeper layer
  api/v3/Contact.php
Labels: master

#13842 Remove Log.php require_once statements
  CRM/Core/Config.php
  CRM/Core/Error.php
  CRM/Utils/Check/Component/Source.php
Labels: master

#13845 Add in tests of purifying HTML output
  CRM/Utils/String.php
  tests/phpunit/CRM/Utils/StringTest.php
Labels: master, merge on pass

#13603 dev/core/issues/726, Fixed fatal error when searched using group type
  CRM/Contact/BAO/Query.php
Labels: easy-review, master, sig:bug

#13847 Use TempTable methods - bookkeeping report
  CRM/Report/Form/Contribute/Bookkeeping.php
Labels: master, merge on pass

#13800 dev/core#789 - Bug fix for event reg error when skipping participants
  CRM/Event/Form/Registration/Confirm.php
Labels: master

#13462 dev/core#664 - CRM/Logging - Add indexes when updating log schema
  CRM/Logging/Schema.php
  tests/phpunit/api/v3/LoggingTest.php
Labels: has-test, master

#13848 Use TempTable methods - contribution detail
  CRM/Report/Form/Contribute/Detail.php
  tests/phpunit/CRM/Report/Form/ActivityTest.php
  tests/phpunit/CRM/Report/Form/Contribute/DetailTest.php
  tests/phpunit/CRM/Report/Form/TestCaseTest.php
Labels: master, merge on pass

#13554 dev/core#706 Edit contribution : wrong decimal separator on total_amount for participant(s)
  CRM/Contribute/Form/Contribution.php
Labels: master, merge on pass, ok-without-test, sig:bug

#13237 core#571 - check logged in OR checksum user permissions to edit recur…
  CRM/Contribute/Form/CancelSubscription.php
  CRM/Contribute/Form/UpdateBilling.php
  CRM/Contribute/Form/UpdateSubscription.php
Labels: master

#13508 Core-688 - Contacts - New Email Fix Smarty/plugins/function.crmSettin…
  CRM/Core/Smarty/plugins/function.crmSetting.php
Labels: master

#13742 dev/core#771 - Smart group with uf_group_id does not load contacts wi…
  CRM/Contact/BAO/SavedSearch.php
  tests/phpunit/CRM/Contact/BAO/SavedSearchTest.php
Labels: has-test, master

#13795 refs issue 788 fix Warning: A non-numeric value encountered in ...
  CRM/Contribute/Form/Contribution/Main.php
  CRM/Event/Form/Registration/Register.php
Labels: master

#13851 Code cleanup on membership block loop
  CRM/Contribute/Form/ContributionBase.php
Labels: master, merge on pass

#13545 "Contact Sub Type" dropdown disappears when fields validation occurs
  templates/CRM/Contact/Form/Edit/Household.tpl
  templates/CRM/Contact/Form/Edit/Organization.tpl
Labels: master, ok-without-test

#13259 Disabling or deleting Expired status breaks membership status update
  CRM/Member/BAO/Membership.php
  tests/phpunit/CRM/Member/BAO/MembershipStatusTest.php
Labels: has-test, master, merge on pass

#13768 Activity tab performance fix - switch to faster getActivities & getActivitiesCount
  CRM/Activity/BAO/Activity.php
  CRM/Activity/Form/ActivityFilter.php
  CRM/Activity/Page/AJAX.php
  CRM/Activity/Selector/Activity.php
  CRM/Contact/BAO/Contact.php
  CRM/Utils/Date.php
  templates/CRM/Activity/Selector/Selector.tpl
  tests/phpunit/CRM/Activity/BAO/ActivityTest.php
Labels: has-test, master

#13849 [NFC] Code reformatting
  tests/phpunit/api/v3/ACLPermissionTest.php
Labels: master

#13846 [NFC] code formatting only
  CRM/Core/Payment.php
Labels: master

#13843 Add FrontEndPaymentFormTrait to start to share functionality between Event and Contribution forms
  CRM/Contribute/Form/Contribution/Confirm.php
  CRM/Financial/Form/FrontEndPaymentFormTrait.php
Labels: master

#13858 dev/core#795 Fix PHP warning when updating a multiselect country field.
  CRM/Core/BAO/CustomValueTable.php
Labels: easy-review, master, merge on pass

#13860 Fixing formatting of contributors section
  release-notes/5.11.0.md
Labels: master

#13856 Test fix
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: master, merge on pass

#13859 dev/core#811 - Autocomplete only enabled options
  CRM/Core/BAO/CustomField.php
Labels: master

#13748 Fix bug whereby sorting by state province gives an error in search builder
  CRM/Contact/BAO/Query.php
  CRM/Contact/Selector.php
  tests/phpunit/CRM/Contact/BAO/QueryTest.php
  tests/phpunit/CRM/Contact/SelectorTest.php
Labels: master, merge on pass

#13398 dev/core/issues/570, Check Dedupe fails for limited permission user
  CRM/Core/Permission.php
Labels: master

#13866 Update test to reflect recently merged PR lower permission to access dedupecheck
  tests/phpunit/api/v3/ACLPermissionTest.php
Labels: master, merge on pass

#13869 Add ID / Test ID for payment processors to list - makes setup of IPNs much easier!
  CRM/Admin/Page/PaymentProcessor.php
  templates/CRM/Admin/Page/PaymentProcessor.tpl
Labels: master

#13870 Try Reverting commit removing require once to see if it fixes the pro…
  CRM/Core/Config.php
  CRM/Core/Error.php
Labels: master

#13862 Reformat test files for array format
  tests/phpunit/CRM/Contact/BAO/ContactType/ContactSearchTest.php
  tests/phpunit/CRM/Contact/BAO/ContactType/ContactTest.php
  tests/phpunit/CRM/Contact/BAO/ContactType/ContactTypeTest.php
  tests/phpunit/CRM/Contact/BAO/ContactType/RelationshipTest.php
Labels: master

#13234 Add hook findDuplicates
  CRM/Contact/BAO/Contact.php
  CRM/Event/Form/Registration/Register.php
  CRM/Utils/Hook.php
  tests/phpunit/CRM/Dedupe/DedupeFinderTest.php
Labels: master

#13772 dev/core#748 Switch alphabetQuery to use new getSearchSQLParts() function
  CRM/Contact/BAO/Query.php
Labels: master, merge on pass

#13874 Remove now-obsolete additionalFromClause parameter from prepareOrderBy
  CRM/Contact/BAO/Query.php
Labels: master

#13875 BAO_Participant - Use default status if not specified for create
  CRM/Event/BAO/Participant.php
Labels: master

#13865 Use tempTable class in creation of dedupe table.
  CRM/Dedupe/BAO/RuleGroup.php
Labels: has-test, master

#13697 CRM/Event - Fix participant note search parameter being ignored
  CRM/Event/BAO/Query.php
  tests/phpunit/CRM/Event/BAO/QueryTest.php
Labels: has-test, master

#13876 dev/core#814 Fix menu restore link
  js/crm.menubar.js
Labels: 5.12, merge on pass

#13541 dev/core#641: Case Activity Assignment Restriction
  CRM/Case/BAO/CaseType.php
  CRM/Case/Form/Activity.php
  ang/crmCaseType.js
  ang/crmCaseType/caseTypeDetails.html
  templates/CRM/Case/CaseType.hlp
Labels: master, merge on pass

#13879 5.12 to master
  js/crm.menubar.js
Labels: master

#13877 Fix php 7.2 count notice
  CRM/Contact/Import/ImportJob.php
Labels: master, merge on pass

#13878 [nfc] Reset entire session object between tests
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: master, merge on pass

#13880 Use TempTable methods.
  CRM/Report/Form.php
  CRM/Report/Form/Contribute/Repeat.php
  tests/phpunit/api/v3/ReportTemplateTest.php
Labels: master

#13872 Fix up composer for composer 2.0 compatibility
  composer.json
  composer.lock
Labels: master

#13798 Improve ContributionPage.validate api
  api/v3/ContributionPage.php
  tests/phpunit/api/v3/ContributionPageTest.php
Labels: has-test, master

#13881 dev/core#812 - Fix null display of contribution row on …
  CRM/Contribute/BAO/Query.php
  CRM/Contribute/Selector/Search.php
  tests/phpunit/CRM/Contribute/Form/SearchTest.php
Labels: 5.12, merge on pass

#13882 5.12 to master
  CRM/Contribute/BAO/Query.php
  CRM/Contribute/Selector/Search.php
  tests/phpunit/CRM/Contribute/Form/SearchTest.php
Labels: master

#12639 dev/core#314 Event self-service Transfer picks up the deleted contact ID basically transferring to the wrong contact
  CRM/Event/Form/SelfSvcTransfer.php
Labels: master

#13068 send action links on any page that extends CRM_Core_Page_basic thru hook_civicrm_links
  CRM/Core/Page/Basic.php
Labels: master

#13850 dev/core#560 Update Cancel Billing & update billing to use status bounce rather than fatal
  CRM/Contribute/Form/CancelSubscription.php
  CRM/Contribute/Form/UpdateBilling.php
Labels: master

#13640 dev/core/issues/740, Show form on validation error
  templates/CRM/Note/Form/Note.tpl
Labels: easy-review, master, ok-without-test, sig:bug

#13785 dev/core#784 - On civicase case type editing screen creating a new relationship type on the fly inserts a blank row
  ang/crmCaseType.js
Labels: master, merge on pass

#13884 dev/core#502 fix bug on sorting by address fields when viewing search results by profile
  CRM/Contact/BAO/Query.php
  CRM/Contact/Selector.php
  tests/phpunit/CRM/Contact/BAO/QueryTest.php
Labels: master

#13885 Use label not name for payment processor type
  CRM/Admin/Page/PaymentProcessor.php
Labels: master

#13886 Remove switch statement that no longer switches
  CRM/Contact/BAO/Query.php
Labels: master, merge on pass

#13888 Added unit test for dev/core/issues/726
  tests/phpunit/CRM/Contact/Form/Search/SearchContactTest.php
Labels: master

#13567 dev/core#709, fixed date filter for custom fields
  CRM/Report/Form.php
Labels: master, sig:bug
