Repository civicrm/civicrm-core, pull requests merged in 2019-07, with the labels that each got.

#14681 [NFC][test] reformat jobTest class
  tests/phpunit/api/v3/ContactTest.php
  tests/phpunit/api/v3/JobTest.php
Labels: master

#14683 Block classes in unserialize field for IDE cheer
  CRM/Core/BAO/PrevNextCache.php
  CRM/Core/DAO.php
  api/v3/Dedupe.php
Labels: master, merge on pass

#14682 dev/core#1086 - Mismatched div and /div tags in caseTypeDetails.html
  ang/crmCaseType/caseTypeDetails.html
Labels: master

#14654 dev-core#1079: Improper character encoding breaks xml processor
  templates/CRM/Case/XMLProcessor/Report.tpl
Labels: master

#14686 Fix failing test by changing expected date format
  tests/phpunit/CRM/Contribute/Form/SearchTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: master

#14587 Fixing the display of checkboxes in event confirm / thank you (dev/core#1058)
  CRM/Event/BAO/Event.php
Labels: master

#14244 dev/financial#50 - Fix contributions and participants getting overwritten
  CRM/Contribute/Form/Contribution.php
  CRM/Event/Form/Participant.php
Labels: master, merge ready

#14687 Deprecate some deprecated address functions: defaultCurrencySymbol
  CRM/Admin/Form/Preferences/Contribute.php
  CRM/Batch/Form/Entry.php
  CRM/Contribute/BAO/Widget.php
  CRM/Core/BAO/Country.php
  CRM/Core/Config.php
  CRM/Core/Page.php
  CRM/Event/Form/ParticipantFeeSelection.php
  CRM/Member/Form/Membership.php
  CRM/Utils/OpenFlashChart.php
  templates/CRM/Batch/Form/Entry.tpl
  templates/CRM/common/jsortable.tpl
Labels: master, merge on pass

#14671 [REF] transform the setting of defaults in CustomField::create to be like (some) other entities
  CRM/Core/BAO/CustomField.php
Labels: master

#14688 Fix erroneous variable passed to callAPISuccessGetValue
  tests/phpunit/api/v3/LoggingTest.php
Labels: master

#14692 dev/joomla#13 lower-case C on CRM_Core_PseudoConstant breaks 5.14 upgrade on Joomla w/ CiviCase
  CRM/Batch/Form/Entry.php
  CRM/Case/BAO/Case.php
  CRM/Core/BAO/CustomField.php
  CRM/Core/BAO/FinancialTrxn.php
  CRM/Core/OptionGroup.php
  CRM/Core/Payment/PayPalIPN.php
  CRM/Core/Payment/PayPalProIPN.php
  CRM/Report/Form/Contact/Relationship.php
  api/v3/Activity.php
  api/v3/Campaign.php
  api/v3/Event.php
  tests/phpunit/CRM/Contribute/Form/SearchTest.php
  tests/phpunit/CRM/Member/Form/MembershipTest.php
Labels: 5.15, merge on pass

#14698 5.15 to master
  CRM/Batch/Form/Entry.php
  CRM/Case/BAO/Case.php
  CRM/Core/BAO/CustomField.php
  CRM/Core/BAO/FinancialTrxn.php
  CRM/Core/OptionGroup.php
  CRM/Core/Payment/PayPalIPN.php
  CRM/Core/Payment/PayPalProIPN.php
  CRM/Report/Form/Contact/Relationship.php
  api/v3/Activity.php
  api/v3/Campaign.php
  api/v3/Event.php
  tests/phpunit/CRM/Contribute/Form/SearchTest.php
  tests/phpunit/CRM/Member/Form/MembershipTest.php
Labels: master

#14695 Remove failing assertion
  tests/phpunit/api/v3/LoggingTest.php
Labels: master

#14691 dev/joomla#13 lower-case C on CRM_Core_PseudoConstant breaks 5.14 upgrade on Joomla w/ CiviCase
  CRM/Batch/Form/Entry.php
  CRM/Case/BAO/Case.php
  CRM/Contribute/BAO/Contribution.php
  CRM/Core/BAO/CustomField.php
  CRM/Core/BAO/FinancialTrxn.php
  CRM/Core/OptionGroup.php
  CRM/Core/Payment/PayPalIPN.php
  CRM/Core/Payment/PayPalProIPN.php
  CRM/Report/Form/Contact/Relationship.php
  api/v3/Activity.php
  api/v3/Campaign.php
  api/v3/Event.php
  tests/phpunit/CRM/Contribute/Form/SearchTest.php
  tests/phpunit/CRM/Member/Form/MembershipTest.php
Labels: 5.14

#14700 [NFC][test] code formatting only
  tests/phpunit/CRM/Contact/BAO/QueryTest.php
  tests/phpunit/CRM/Contact/SelectorTest.php
Labels: master

#14699 [NFC][test] reformat activity search test
  tests/phpunit/CRM/Contact/BAO/ActivitySearchTest.php
Labels: master

#14689 [REF] extract prepareCreate from CustomField.create
  CRM/Core/BAO/CustomField.php
Labels: master

#14702 dev/joomla#13 - followup - Some class names have wrong upper/lower case spelling
  CRM/Admin/Page/CKEditorConfig.php
  CRM/Grant/Page/Tab.php
  CRM/Logging/Schema.php
  CRM/Price/BAO/LineItem.php
  CRM/Utils/Cache.php
  CRM/Utils/Cache/ArrayCache.php
  CRM/Utils/System.php
  CRM/Utils/VersionCheck.php
  Civi/Angular/Manager.php
Labels: master

#14503 $this->_selectedTables is not populated incase of boleen filters
  CRM/Report/Form.php
Labels: master

#14693 [REF] remove instances of pass-by-reference where no change takes place
  CRM/Core/BAO/SchemaHandler.php
Labels: master

#14685 Consolidate handling of conflicts between the batch job and get_conflicts api
  CRM/Core/BAO/PrevNextCache.php
  CRM/Dedupe/Merger.php
  Civi/Test/Api3TestTrait.php
  api/v3/Contact.php
  tests/phpunit/api/v3/ContactTest.php
  tests/phpunit/api/v3/JobTest.php
Labels: master

#14704 Grab contribution status id from database
  CRM/PCP/BAO/PCP.php
Labels: master, merge on pass

#14710 dev/joomla#13 - followup 5 - Some class names have wrong upper/lower case spelling
  CRM/Contact/Form/Task/AddToGroup.php
  CRM/Contribute/BAO/Contribution.php
  CRM/Event/Form/Registration.php
Labels: master

#14709 dev/joomla#13 - followup 4 - Some class names have wrong upper/lower case spelling
  CRM/Core/Payment/Dummy.php
  CRM/Core/Payment/Elavon.php
  CRM/Core/PseudoConstant.php
Labels: master, merge on pass

#14708 dev/joomla#13 - followup 3 - Some class names have wrong upper/lower case spelling
  CRM/Activity/BAO/Query.php
  CRM/Contribute/BAO/Query.php
  CRM/Event/BAO/Query.php
  CRM/Mailing/BAO/Query.php
  CRM/Member/BAO/Query.php
  CRM/Pledge/BAO/Query.php
Labels: master, merge on pass

#14707 dev/joomla#13 - followup 2 - Some class names have wrong upper/lower case spelling
  CRM/Mailing/Event/BAO/Bounce.php
  CRM/Mailing/Event/BAO/Delivered.php
  CRM/Mailing/Event/BAO/Forward.php
  CRM/Mailing/Event/BAO/Opened.php
  CRM/Mailing/Event/BAO/Queue.php
  CRM/Mailing/Event/BAO/Reply.php
  CRM/Mailing/Event/BAO/TrackableURLOpen.php
  CRM/Mailing/Event/BAO/Unsubscribe.php
Labels: master, merge on pass

#14608 [test] convert export test to handle exception rather than early return
  CRM/Core/Exception/PrematureExitException.php
  CRM/Export/BAO/Export.php
  CRM/Export/BAO/ExportProcessor.php
  CRM/Utils/System.php
  tests/phpunit/CRM/Export/BAO/ExportTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: master

#14713 Grab contribution status id from database
  CRM/PCP/BAO/PCP.php
Labels: master, merge on pass

#14690 dev/core#1088 Fix fatal error when copying profile with civirules enabled
  CRM/Core/DAO.php
Labels: 5.15

#14714 5.15 to master
  CRM/Core/DAO.php
Labels: master

#14717 (dev/cloud-native#3) SerializeCache - Remove unused, incomplete cache-driver
  CRM/Utils/Cache/SerializeCache.php
Labels: master, merge on pass

#14723 Extract code converting a date object to local timezone object to own…
  CRM/Core/Payment/PayPalIPN.php
  CRM/Utils/Date.php
Labels: master, merge on pass

#14730 5.15.0 releasenotes
  CRM/Upgrade/Incremental/sql/5.15.0.mysql.tpl
  contributor-key.yml
  release-notes.md
  release-notes/5.15.0.md
  sql/civicrm_generated.mysql
  xml/version.xml
Labels: 5.15

#14721 dev/core#1097 - Ensure consistent count on Groups tab
  CRM/Contact/BAO/Contact.php
Labels: master

#14726 [REF] simple extraction of prepareCreateParams
  CRM/Core/BAO/CustomField.php
Labels: master

#14701 Activity search - convert priority_id to a metadata field and add location as a searchable field
  CRM/Activity/BAO/Query.php
  templates/CRM/Activity/Form/Search/Common.tpl
Labels: master

#14736 Updated Circle-Interactive developers info
  contributor-key.yml
Labels: master, merge on pass

#14731 Fix some test leakage
  CRM/Contribute/BAO/Query.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: master, merge on pass

#14724 [REF] clarify variable (very minor change with good test cover)
  CRM/Core/BAO/CustomField.php
Labels: master

#14697 [REF] Cleanup fixSchemaDifferencesFor()
  CRM/Core/BAO/SchemaHandler.php
  CRM/Logging/Schema.php
  api/v3/System.php
  tests/phpunit/CRM/Logging/LoggingTest.php
Labels: master

#14614 Improve handling of 'Manage Event' title
  CRM/Event/Form/ManageEvent.php
Labels: master

#14733 Fix refund payment not recording from additional payment form
  CRM/Contribute/BAO/Contribution.php
  CRM/Contribute/Form/AdditionalPayment.php
Labels: 5.16

#14732 dev/report#16 Unreleased regression - fee levels incorrectly show sol…
  CRM/Event/Form/EventFees.php
  CRM/Event/Form/Participant.php
  templates/CRM/Event/Form/Participant.tpl
Labels: 5.16

#14738 5.16 to master
  CRM/Contribute/BAO/Contribution.php
  CRM/Contribute/Form/AdditionalPayment.php
  CRM/Event/Form/EventFees.php
  CRM/Event/Form/Participant.php
  templates/CRM/Event/Form/Participant.tpl
Labels: master

#14725 [REF] extract portion that creates the custom field record
  CRM/Core/BAO/CustomField.php
Labels: master, merge on pass

#14589 Fix creation of additional zero value line item when changing fee selection in edge case
  CRM/Price/BAO/LineItem.php
  CRM/Price/BAO/PriceField.php
  CRM/Price/BAO/PriceFieldValue.php
  tests/phpunit/CRM/Event/Form/ParticipantTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: master, merge ready

#14739 Fix refund payment not recording from additional payment form
  CRM/Contribute/BAO/Contribution.php
  CRM/Contribute/Form/AdditionalPayment.php
Labels: 5.15, merge on pass

#14727 [REF] simple extraction of getFieldAlterSQL
  CRM/Core/BAO/SchemaHandler.php
Labels: master, merge on pass

#14741 [REF] Simple function extraction for buildMappingForm
  CRM/Core/BAO/Mapping.php
Labels: master

#14743 [REF] Further cleanup & extraction in getMappingFieds
  CRM/Core/BAO/Mapping.php
Labels: master

#13540 dev/core/issues/577: Activity Summary report fix for db column count error with section header (without ONLY_FULL_GROUP_BY)
  CRM/Report/Form/ActivitySummary.php
Labels: has-test, master

#14746 dev/core#1081 fix for error on contribution detail when using custom data order by without select
  CRM/Report/Form.php
  CRM/Report/Form/Contribute/Summary.php
  tests/phpunit/CRMTraits/Custom/CustomDataTrait.php
  tests/phpunit/api/v3/ReportTemplateTest.php
Labels: 5.16

#14749 5.16 to master
  CRM/Report/Form.php
  CRM/Report/Form/Contribute/Summary.php
  tests/phpunit/CRMTraits/Custom/CustomDataTrait.php
  tests/phpunit/api/v3/ReportTemplateTest.php
Labels: master

#14720 Removed hardcoded activity status and used Activity create
  CRM/Mailing/BAO/MailingJob.php
  tests/phpunit/CRM/Mailing/MailingSystemTest.php
Labels: master

#14616 REF Simple cleanup of tabset code for contributionpages
  CRM/Contribute/Form/ContributionPage/TabHeader.php
Labels: master, merge on pass

#14744 dev/report#17 fix postal_code_suffix col
  CRM/Report/Form.php
Labels: master

#14751 [REF] Extract CRM_Core_BAO_Mapping::addComponentFields
  CRM/Core/BAO/Mapping.php
Labels: master, merge on pass

#14514 dev/core#1015 Unit test for fix regression on exporting soft credits
  CRM/Utils/System.php
  tests/phpunit/CRM/Export/BAO/ExportTest.php
Labels: master

#14752 [REF] Move function onto the processor class
  CRM/Export/BAO/Export.php
  CRM/Export/BAO/ExportProcessor.php
Labels: master, merge on pass

#14742 [REF] un-extract createProportionalFinancialEntities
  CRM/Financial/BAO/Payment.php
Labels: master

#14755 [REF] Remove call to getMappingFields in favour of api call.
  CRM/Activity/Import/Form/MapField.php
  CRM/Core/BAO/Mapping.php
Labels: master, merge on pass

#14754 Fix obscure bug on updating custom fields (not necessarily hittable via UI)
  CRM/Core/BAO/CustomField.php
  tests/phpunit/api/v3/CustomFieldTest.php
Labels: master

#14753 NFC - reformat test class
  tests/phpunit/api/v3/CustomFieldTest.php
Labels: master

#14756 Extract field wrangling to determineReturnProperties
  CRM/Export/BAO/Export.php
  CRM/Export/BAO/ExportProcessor.php
Labels: master, merge on pass

#14729 e-notice fix & unit test
  CRM/Logging/Schema.php
  tests/phpunit/CRM/Logging/SchemaTest.php
Labels: master

#14757 [REF] Extract saveMapping Field
  CRM/Contact/Import/Form/MapField.php
Labels: master, merge on pass

#14758 [REF] export code simplification
  CRM/Export/BAO/Export.php
  tests/phpunit/CRM/Export/BAO/ExportTest.php
Labels: master

#14706 expose smarty's compile_check to be overridden in civicrm.settings.php
  CRM/Core/Smarty.php
  templates/CRM/common/civicrm.settings.php.template
Labels: master

#14762 [REF] Extract mapping converter function, kinda brutally
  CRM/Core/BAO/Mapping.php
  tests/phpunit/CRM/Core/BAO/MappingTest.php
Labels: master, merge on pass

#14759 Remove unecessary pass-by-reference
  CRM/Core/BAO/Mapping.php
  tests/phpunit/CRM/Core/BAO/MappingTest.php
Labels: master

#14615 Set title using standard form method and use for success message on contributionpage
  CRM/Contribute/Form/ContributionPage.php
Labels: master

#14745 dev/core#578 follow up fix on activity summary report
  CRM/Report/Form/ActivitySummary.php
Labels: master

#14765 [REF] Update export test to new function
  tests/phpunit/CRM/Export/BAO/ExportTest.php
Labels: master, merge on pass

#14768 [REF] [export] . Move greeting params retrieval to the place in the code where it is used
  CRM/Export/BAO/Export.php
  CRM/Export/Form/Map.php
  CRM/Export/Form/Select.php
Labels: master, merge on pass

#14772 dev/drupal#75 Drupal8: fix call to languageNegotiationURL() when called from cv
  CRM/Utils/System/Drupal8.php
Labels: master

#14778 (dev/cloud-native#3) CRM_Utils_File - Deprecate baseFilePath() et al
  CRM/Utils/File.php
Labels: master

#14777 GenCode, Cache::cleanKey() - Fix deploop during clean initialization
  CRM/ACL/BAO/ACL.php
  CRM/Contact/BAO/ContactType.php
  CRM/Core/BAO/Cache.php
  CRM/Core/BAO/Cache/Psr16.php
  CRM/Core/BAO/PrevNextCache.php
  CRM/Core/PseudoConstant.php
  CRM/Utils/Cache.php
  CRM/Utils/Cache/SqlGroup.php
  tests/phpunit/CRM/Core/BAO/CacheTest.php
Labels: master

#14696 Migrate CivicrmHelper::parseUrl() to CRM_Utils_System_Drupal8::parseUrl().
  CRM/Utils/System/Drupal8.php
Labels: master

#14770 Finish removing references to Config.IDS.ini
  CRM/Admin/Form/Setting.php
  install/index.php
Labels: master

#14750 Fix enotice on formatting credit card details
  CRM/Contribute/Form/AbstractEditPayment.php
Labels: master

#14779 [ref] [export] [test] Improve csv test to test final output rather than the csv
  tests/phpunit/CRM/Export/BAO/ExportTest.php
Labels: master

#14775 dev/drupal#75 Drupal8: fix call to languageNegotiationURL() when called from cv
  CRM/Utils/System/Drupal8.php
Labels: 5.16

#14776 dev/drupal#75 Drupal8: fix call to languageNegotiationURL() when called from cv
  CRM/Utils/System/Drupal8.php
Labels: 5.15

#14769 [REF] simplify & add tests on getMappingParams
  CRM/Core/BAO/Mapping.php
  tests/phpunit/CRM/Core/BAO/MappingTest.php
Labels: master

#14767 [REF] initial extraction of loading saved mapping to qf format
  CRM/Core/BAO/Mapping.php
Labels: master

#14761 dev/core#1108 Use api call to retrieve mailing_id
  CRM/Mailing/Event/BAO/Unsubscribe.php
Labels: master

#14774 [REF] [export] Cleaner handling of additional return properties
  CRM/Export/BAO/Export.php
  CRM/Export/BAO/ExportProcessor.php
Labels: master

#14773 [REF] [export] remove chunk of non-functional code
  CRM/Export/BAO/Export.php
Labels: master

#14783 5.16.0 release notes first run
  contributor-key.yml
  release-notes.md
  release-notes/5.16.0.md
Labels: 5.16

#14786 5.16 to master
  contributor-key.yml
  release-notes.md
  release-notes/5.16.0.md
Labels: master

#14785 [EXPORT] Minor fixes to the export form
  CRM/Core/BAO/Mapping.php
Labels: master

#14788 [REF] [EXPORT] partial cleanup on adding fields to returnProperties based on usage
  CRM/Export/BAO/Export.php
  CRM/Export/BAO/ExportProcessor.php
Labels: master

#14780 [NFC] [REF] [TEST] [EXPORT] Update various export tests to test csv output with new functions
  tests/phpunit/CRM/Export/BAO/ExportTest.php
Labels: master

#14771 dev/core#1081 fix for error on contribution detail when using custom data order by without select
  CRM/Report/Form.php
  CRM/Report/Form/Contribute/Summary.php
  tests/phpunit/CRMTraits/Custom/CustomDataTrait.php
  tests/phpunit/api/v3/ReportTemplateTest.php
Labels: 5.15

#14791 Bump to 5.15.1. Add release notes.
  CRM/Upgrade/Incremental/sql/5.15.1.mysql.tpl
  release-notes.md
  release-notes/5.15.1.md
  sql/civicrm_generated.mysql
  xml/version.xml
Labels: 5.15

#14787 [REF][Export] Minor cleanup on household merge properties
  CRM/Export/BAO/Export.php
  CRM/Export/BAO/ExportProcessor.php
Labels: master

#14792 [REF] [EXPORT] [TLA] Update handling of input fields so that the mapping format is accepted.
  CRM/Core/BAO/Mapping.php
  CRM/Export/BAO/Export.php
  CRM/Export/BAO/ExportProcessor.php
Labels: master

#14790 [REF] [EXPORT] cleanup setting of additional postal fields
  CRM/Export/BAO/Export.php
  CRM/Export/BAO/ExportProcessor.php
Labels: master

#14794 Use select2 to display field mappings
  CRM/Core/BAO/Mapping.php
  CRM/Export/Form/Select.php
Labels: master

#14694 dev/core#1093 add a bulkCreate action for many customFields in one go
  CRM/Core/BAO/CustomField.php
  CRM/Core/BAO/SchemaHandler.php
  CRM/Utils/Migrate/Import.php
  tests/phpunit/CRM/Core/BAO/CustomFieldTest.php
  tests/phpunit/CRM/Core/BAO/SchemaHandlerTest.php
  tests/phpunit/api/v3/CustomFieldTest.php
Labels: has-test, master

#14796 [REF] [EXPORT] Minor consolidation of weird mergeSameAddreess nightmare code
  CRM/Export/BAO/Export.php
Labels: master

#14797 [REF] [Export] Move function that parses tokens to address processor
  CRM/Export/BAO/Export.php
  CRM/Export/BAO/ExportProcessor.php
Labels: master

#14795 [REF] [EXPORT] Stop passing return Properties
  CRM/Export/BAO/Export.php
  CRM/Export/BAO/ExportProcessor.php
  tests/phpunit/CRM/Export/BAO/ExportTest.php
Labels: master, merge on pass

#14799 [REF] [Export] Move replace merge tokens to processor class
  CRM/Export/BAO/Export.php
  CRM/Export/BAO/ExportProcessor.php
Labels: master, merge on pass

#14801 [REF] [Export] Minor code relocation
  CRM/Export/BAO/Export.php
Labels: master, merge on pass

#14789 Ensure recently converted groups cache matches previous behabiour my …
  Civi/Core/Container.php
Labels: 5.16

#14805 5.16 to master
  Civi/Core/Container.php
Labels: master

#14802 [REF] [Export] Move setting of household properties to processor
  CRM/Export/BAO/Export.php
  CRM/Export/BAO/ExportProcessor.php
Labels: master

#14804 [REF] [Export] Remove code that seems unused
  CRM/Export/BAO/Export.php
Labels: master

#14803 [REF] [Export] move build master copy array to ExportProcessor
  CRM/Export/BAO/Export.php
  CRM/Export/BAO/ExportProcessor.php
Labels: master

#13487 (dev/core#285) Fixed second membership reminder
  CRM/Contribute/ActionMapping/ByPage.php
  CRM/Contribute/ActionMapping/ByType.php
  CRM/Event/ActionMapping.php
  CRM/Member/ActionMapping.php
  CRM/Upgrade/Incremental/sql/5.14.alpha1.mysql.tpl
  Civi/ActionSchedule/Mapping.php
  Civi/ActionSchedule/MappingInterface.php
  Civi/ActionSchedule/RecipientBuilder.php
  tests/phpunit/CRM/Core/BAO/ActionScheduleTest.php
  xml/schema/Core/ActionLog.xml
Labels: has-test, master

#14800 [REF] [EXPORT] Alter CRM_Export_BAO_Export::exportComponents
  CRM/Export/BAO/Export.php
  CRM/Export/BAO/ExportProcessor.php
  CRM/Export/Form/Map.php
  tests/phpunit/CRM/Export/BAO/ExportTest.php
Labels: master, merge on pass

#14728 [REF] final cleanup - call bulkCreate from migrate_utils
  CRM/Core/BAO/CustomField.php
  CRM/Core/BAO/SchemaHandler.php
  CRM/Utils/Migrate/Import.php
  tests/phpunit/CRM/Utils/Migrate/ImportExportTest.php
Labels: master

#14806 [REF] [Export] further code cleanup
  CRM/Export/BAO/Export.php
  CRM/Export/BAO/ExportProcessor.php
Labels: master, merge on pass

#14764 dev/report/15 Add fix and tests for contact subtype report filter
  CRM/Report/Form.php
  tests/phpunit/api/v3/ReportTemplateTest.php
Labels: 5.16

#14807 5.16 to master
  CRM/Report/Form.php
  tests/phpunit/api/v3/ReportTemplateTest.php
Labels: master

#14793 [TEST][EXPORT] Improve unit test on export.
  tests/phpunit/CRM/Export/BAO/ExportTest.php
Labels: master, merge on pass

#14809 [REF] [Export] move mergeSameAddress to processor class
  CRM/Export/BAO/Export.php
  CRM/Export/BAO/ExportProcessor.php
Labels: master, merge on pass

#14808 [REF] [Export] Further cleanup - construct sql more concisely
  CRM/Export/BAO/Export.php
  CRM/Export/BAO/ExportProcessor.php
Labels: master, merge on pass

#14810 Fix upgrade for membership second reminder
  CRM/Upgrade/Incremental/sql/5.14.alpha1.mysql.tpl
  CRM/Upgrade/Incremental/sql/5.17.alpha1.mysql.tpl
Labels: master

#14813 [REF] [TEST] [Export] Update export tests to reflect new format
  Civi/Test/ContactTestTrait.php
  tests/phpunit/CRM/Export/BAO/ExportTest.php
Labels: master

#14812 [REF] [Export] More export Structure arrays to processor
  CRM/Export/BAO/Export.php
  CRM/Export/BAO/ExportProcessor.php
  tests/phpunit/CRM/Export/BAO/ExportTest.php
Labels: master

#14811 [REF] [Export] clean up incorporation of order by & group by into ExportProcessor
  CRM/Export/BAO/Export.php
  CRM/Export/BAO/ExportProcessor.php
Labels: master

#14782 [EXPORT] add getPreview function
  CRM/Export/BAO/ExportProcessor.php
  tests/phpunit/CRM/Export/BAO/ExportTest.php
Labels: master

#14818 MagicMerge - Fix ephemeral overrides for aliased properties
  CRM/Core/Config/MagicMerge.php
  tests/phpunit/CRM/Core/Config/MagicMergeTest.php
Labels: master

#14817 [TEST] export - add unit test covering merge to same address addressee handling
  CRM/Export/BAO/ExportProcessor.php
  tests/phpunit/CRM/Export/BAO/ExportTest.php
Labels: master

#14581 Convert Navigation cache group to current cache defition system
  CRM/Admin/Form/Setting/Localization.php
  CRM/Core/BAO/Cache/Psr16.php
  CRM/Core/BAO/ConfigSetting.php
  CRM/Core/BAO/Navigation.php
  CRM/Utils/System.php
  Civi/Core/Container.php
Labels: master

#14675 [REF] Cleanup usage of CRM_Core_BAO_PrevNextCache::setItem and deprec…
  CRM/Core/BAO/PrevNextCache.php
  CRM/Dedupe/Finder.php
  CRM/Dedupe/Merger.php
  tests/phpunit/CRM/Core/BAO/PrevNextCacheTest.php
Labels: master

#14815 Remove the only two defined fonts from selectors
  css/civicrm.css
Labels: concept approved, master, ok-without-test

#14816 dev/event#8 Event Cart: save Participant custom field data
  CRM/Event/Cart/Form/Checkout/ParticipantsAndPrices.php
Labels: master

#14722 Fix public URL link with hashed URLs in mailing browse screen
  CRM/Mailing/Selector/Browse.php
Labels: 5.16

#14819 [REF] [Export] Stop passing export params to the merge function
  CRM/Export/BAO/ExportProcessor.php
Labels: master

#14821 5.16 to master
  CRM/Mailing/Selector/Browse.php
Labels: master

#14582 Convert Custom Data cache group to be using standard cache backend
  CRM/Core/BAO/Cache/Psr16.php
  CRM/Core/BAO/CustomGroup.php
  CRM/Utils/System.php
  Civi/Core/Container.php
Labels: master, merge on pass

#14583 Convert the contact fields cache group to standard cache backend
  CRM/ACL/BAO/ACL.php
  CRM/ACL/Form/ACL.php
  CRM/Admin/Form/Setting/Localization.php
  CRM/Contact/BAO/Contact.php
  CRM/Core/BAO/Cache/Psr16.php
  CRM/Core/BAO/CustomField.php
  CRM/Core/BAO/CustomGroup.php
  CRM/Custom/Form/ChangeFieldType.php
  CRM/Custom/Form/Field.php
  CRM/Custom/Form/Group.php
  CRM/Utils/System.php
  Civi/Core/Container.php
Labels: master

#14814 dev/report/15 Add fix and tests for contact subtype report filter
  CRM/Report/Form.php
  tests/phpunit/api/v3/ReportTemplateTest.php
Labels: 5.15

#14823 Remove additional custom fields deletegroup functions
  sql/GenerateData.php
  sql/GenerateReportData.php
Labels: master, merge on pass

#14825 [REF] Cleanup up handling of dates for Recurring & Contribution date fields in query class
  CRM/Contribute/BAO/Query.php
  tests/phpunit/CRM/Contribute/Form/SearchTest.php
Labels: master

#14822 [REF] [Export] remove another confusing parameter
  CRM/Export/BAO/ExportProcessor.php
Labels: master

#14824 dev/core#1115 - fix invalid url in singleton/max_instances warning in civicase
  CRM/Case/Form/Activity.php
  CRM/Case/PseudoConstant.php
  tests/phpunit/CRM/Case/BAO/CaseTest.php
Labels: has-test, master

#14737 [REF] Convert contribution_recur dates to datepicker from jcalendar
  CRM/Contribute/BAO/ContributionRecur.php
  CRM/Contribute/BAO/Query.php
  CRM/Contribute/Form/Search.php
  CRM/Core/Form/Search.php
  CRM/Upgrade/Incremental/php/FiveSeventeen.php
  templates/CRM/Contribute/Form/Search/ContributionRecur.tpl
  templates/CRM/Core/DatePickerRange.tpl
  templates/CRM/Core/DatePickerRangeWrapper.tpl
Labels: master

#14829 dev/core#1093 Make bulkSave defaults optional and ensure correct post hook is called
  CRM/Core/BAO/CustomField.php
Labels: master

#14828 Add in Deprecation warnings on Cache functons
  CRM/Core/BAO/Cache.php
  tests/phpunit/CRM/Core/BAO/CacheTest.php
  tests/phpunit/api/v3/SystemTest.php
Labels: master, merge on pass

#14832 Use singleton to get session instead of relying on ->_session being set elsewhere
  CRM/Profile/Form.php
Labels: master

#14831 [NFC] [TEST] Reformat arrays in test classes
  tests/phpunit/CRM/Event/BAO/AdditionalPaymentTest.php
  tests/phpunit/CRM/Event/BAO/ChangeFeeSelectionTest.php
  tests/phpunit/CRM/Event/BAO/ParticipantTest.php
  tests/phpunit/CRM/Event/Form/ParticipantTest.php
  tests/phpunit/CRM/Price/Form/OptionTest.php
  tests/phpunit/api/v3/GroupTest.php
  tests/phpunit/api/v3/ImTest.php
  tests/phpunit/api/v3/LocBlockTest.php
  tests/phpunit/api/v3/MailSettingsTest.php
  tests/phpunit/api/v3/OptionGroupTest.php
Labels: master, merge on pass

#14830 dev/core#1120 remove multiple export handling
  CRM/Export/BAO/ExportProcessor.php
  CRM/Export/Form/Select.php
Labels: master

#14834 dev/core#1056 Remove unneded schema file
  xml/schema/Event/EventPage.xml
Labels: master

#14835 [REF] [Export] Simplify setting of address strings
  CRM/Export/BAO/Export.php
  CRM/Export/BAO/ExportProcessor.php
Labels: master

#14839 Menubar - Improve flexibility & remove hardcoded values
  css/crm-menubar.css
  js/crm.menubar.js
Labels: master, merge ready

#14841 dev/core#1133 Payment method name is displayed instead of label in payment block for Manual payment
  CRM/Core/Payment/Manual.php
Labels: master
