Repository civicrm/civicrm-core, pull requests merged in 2019-05, with the labels that each got.

#14163 (flexmailer#29) civicrm/mailing/view - Use Mailing.preview API. Fix compatibility with Flexmailer.
  CRM/Mailing/Page/View.php
  api/v3/Mailing.php
  tests/phpunit/api/v3/MailingTest.php
Labels: 5.13, merge on pass

#14166 5.13
  CRM/Contribute/BAO/ContributionRecur.php
  CRM/Mailing/Page/View.php
  api/v3/Mailing.php
  tests/phpunit/api/v3/MailingTest.php
Labels: master

#14168 dev/core#918 enotice fix part 2 #14165
  CRM/Utils/Check/Component/FinancialTypeAcls.php
Labels: master

#14169 Event Cart: fix start_date formatting in line items during checkout
  templates/CRM/Event/Cart/Form/Checkout/Payment.tpl
Labels: easy-review, master, merge on pass

#14174 Event Cart: honor the allow_same_participant_emails setting
  CRM/Event/Cart/Form/Checkout/ParticipantsAndPrices.php
Labels: master

#14175 Event Cart: add support for the Credit Card type icons
  CRM/Event/Cart/Form/Checkout/Payment.php
Labels: master

#14170 Event Cart: fix sending of email receipts
  CRM/Event/Cart/Form/Checkout/Payment.php
Labels: master

#14173 Event Cart: pass the contactID to fix payment on Stripe
  CRM/Event/Cart/Form/Checkout/Payment.php
Labels: master

#14056 5.13.0 release notes
  contributor-key.yml
  release-notes.md
  release-notes/5.13.0.md
Labels: 5.13

#14176 5.13
  contributor-key.yml
  release-notes.md
  release-notes/5.13.0.md
Labels: master

#14179 dev/core#562 [cleanup] remove some more instances of ->free()
  CRM/Batch/BAO/Batch.php
  CRM/Core/BAO/Address.php
  CRM/Core/BAO/Block.php
  CRM/Core/BAO/CustomField.php
  CRM/Core/BAO/CustomOption.php
  CRM/Core/BAO/CustomValueTable.php
  CRM/Core/BAO/Location.php
  CRM/Core/BAO/Note.php
  CRM/Core/BAO/OptionValue.php
  CRM/Core/BAO/Tag.php
  CRM/Core/PseudoConstant.php
  CRM/Financial/BAO/ExportFormat/IIF.php
  CRM/Report/Form/Campaign/SurveyDetails.php
  CRM/Report/Form/Contribute/Sybunt.php
Labels: master, merge on pass

#14178 [cleanup] Remove deprecated pattern &CRM_Core_Config::singleton()
  CRM/Activity/BAO/ICalendar.php
  CRM/Utils/System.php
  CRM/Utils/System/Base.php
  tests/phpunit/CRM/Activity/BAO/ActivityTest.php
  tools/bin/scripts/cli.php
  tools/bin/scripts/memcache.php
  tools/scripts/civimail-spooler/civimail-spooler.php
  tools/scripts/solr/createSolrJSON.php
  tools/scripts/solr/createSolrXML.php
  tools/scripts/solr/createSyncJSON.php
Labels: master, merge on pass

#14152 dev/translation#26 Fix Notice errors caused by l10n rewriting of quer…
  CRM/Core/DAO.php
Labels: master

#14171 [ref] Move copyCustomFields function from Event to Core_DAO for re-usablibilty
  CRM/Core/DAO.php
  CRM/Event/BAO/Event.php
Labels: master

#14188 Resolve dev/core#931 by not doing translation on the query if field e…
  CRM/Upgrade/Incremental/Base.php
Labels: 5.14, merge on pass

#14187 Resolve dev/core#931 by not doing translation on the query if field e…
  CRM/Upgrade/Incremental/Base.php
Labels: 5.13, merge on pass

#14189 wordpress#26 - fix REST
  CRM/Utils/System/WordPress.php
Labels: 5.14, merge on pass

#14186 Fix REST on WordPress
  CRM/Utils/System/WordPress.php
Labels: 5.13, merge on pass

#14135 Hook to alter menubar css variables & fix breakpoint in WP
  CRM/Core/Resources.php
  CRM/Utils/Hook.php
  CRM/Utils/System.php
  CRM/Utils/System/Base.php
  CRM/Utils/System/WordPress.php
  Civi/Core/AssetBuilder.php
  Civi/Core/Container.php
  css/crm-menubar.css
  css/menubar-backdrop.css
  css/menubar-drupal7.css
  css/menubar-drupal8.css
  css/menubar-joomla.css
  css/menubar-wordpress.css
Labels: 5.14, merge on pass

#14074 Don't call session_start() before CMS bootstrap (PHP 7.2 compat)
  extern/rest.php
Labels: master

#14190 Add in 5.13.1 release notes and increment version to 5.13.1
  CRM/Upgrade/Incremental/sql/5.13.1.mysql.tpl
  release-notes.md
  release-notes/5.13.1.md
  sql/civicrm_generated.mysql
  xml/version.xml
Labels: 5.13

#14191 Add in release notes for 5.13.1 drop
  release-notes.md
  release-notes/5.13.1.md
Labels: 5.14

#14192 5.14
  CRM/Core/Resources.php
  CRM/Upgrade/Incremental/Base.php
  CRM/Utils/Hook.php
  CRM/Utils/System.php
  CRM/Utils/System/Base.php
  CRM/Utils/System/WordPress.php
  Civi/Core/AssetBuilder.php
  Civi/Core/Container.php
  css/crm-menubar.css
  css/menubar-backdrop.css
  css/menubar-drupal7.css
  css/menubar-drupal8.css
  css/menubar-joomla.css
  css/menubar-wordpress.css
  release-notes.md
  release-notes/5.13.1.md
Labels: master

#14193 On PHP 7.2 we cannot start session until it has been configured by Dr…
  extern/rest.php
Labels: 5.14, merge on pass

#14180 Enotice fix on creating a smart group
  CRM/Contact/Form/Task/SaveSearch.php
Labels: master

#14177 IDE re-format of tools directory
  tools/bin/scripts/ImportTags.php
  tools/bin/scripts/NormalizePhone.php
  tools/bin/scripts/ckeditorConfigScraper.php
  tools/bin/scripts/cli.php
  tools/bin/scripts/memcache.php
  tools/bin/scripts/set-version.php
  tools/bin/scripts/testProcess.php
  tools/bin/scripts/updateNameCache.php
  tools/drupal/modules/civicrm_webtest/civicrm_webtest.install
  tools/extensions/org.civicrm.angularex/angularex.civix.php
  tools/extensions/org.civicrm.angularex/angularex.php
  tools/extensions/org.civicrm.demoqueue/CRM/Demoqueue/Page/DemoQueue.php
  tools/extensions/org.civicrm.demoqueue/CRM/Demoqueue/Page/DemoQueueDone.php
  tools/extensions/org.civicrm.demoqueue/demoqueue.civix.php
  tools/scripts/check-angular.php
  tools/scripts/civimail-spooler/civimail-spooler.php
  tools/scripts/solr/createSolrJSON.php
  tools/scripts/solr/createSolrXML.php
  tools/scripts/solr/createSyncJSON.php
  tools/scripts/tpl-lint
Labels: master

#14194 dev/core#934 Fix regression on sorting activity tab by 'Added by'
  api/v3/Activity.php
  tests/phpunit/CRM/Activity/BAO/ActivityTest.php
Labels: 5.14

#14200 contributor-keys file - jira/lab.c.o username fix
  contributor-key.yml
Labels: master

#14199 Stop overriding is_active default when saving new relationship
  CRM/Contact/BAO/Relationship.php
Labels: master

#14204 (dev/core#934; followup) Fix escaping on new query code
  api/v3/Activity.php
Labels: 5.14, merge on pass

#14197 dev/core#927 [ref] Extract contribution.cancel function
  CRM/Contribute/BAO/Contribution.php
Labels: master

#14198 [REF+ test] start process of cleaning up payment activity handling
  CRM/Contribute/BAO/Contribution.php
  tests/phpunit/CRM/Contribute/Form/AdditionalPaymentTest.php
Labels: master

#14208 (dev/core#940) Fix regression involving Email Processor filing and ".unknown" attachments
  tools/scripts/composer/patches/civicrm-custom-patches-zetacompoents-mail.patch
Labels: 5.14, merge on pass

#14207 (dev/core#940) Fix regression involving Email Processor and ".unknown" attachments
  tools/scripts/composer/patches/civicrm-custom-patches-zetacompoents-mail.patch
Labels: 5.13, merge on pass

#14209 (dev/core#940) Update release notes
  release-notes.md
  release-notes/5.13.2.md
Labels: 5.13, merge on pass

#14210 Add 5.13.2 release notes
  release-notes.md
  release-notes/5.13.2.md
Labels: 5.14, merge on pass

#14205 5.14
  api/v3/Activity.php
  release-notes.md
  release-notes/5.13.2.md
  tools/scripts/composer/patches/civicrm-custom-patches-zetacompoents-mail.patch
Labels: master

#14183 Fix CRM-21832 - Recurring activities don't carry over custom datas & add test provided by Agileware
  CRM/Contribute/BAO/ContributionPage.php
  CRM/Core/BAO/Job.php
  CRM/Core/BAO/Location.php
  CRM/Core/BAO/UFGroup.php
  CRM/Core/DAO.php
  CRM/Event/BAO/Event.php
  CRM/Price/BAO/PriceSet.php
  tests/phpunit/CRM/Core/BAO/RecurringEntityTest.php
Labels: master

#14203 (dev/core#705) Disabling Alphabetical Pager is not respected for events
  CRM/Event/Page/ManageEvent.php
Labels: master

#14185 Pass the RFC 3164 severity level thru to drupal watchdog.
  CRM/Core/Error.php
Labels: master

#14004 Remove CIVICRM_TEMP_FORCE_UTF8; deprecate TempTable::setUtf8()
  CRM/Contact/Form/Search/Custom/FullText.php
  CRM/Contact/Form/Task.php
  CRM/Export/BAO/Export.php
  CRM/Report/Form.php
  CRM/Utils/SQL/TempTable.php
Labels: master

#14217 dev/core#945 - fix use of $this error in static method
  CRM/Contact/Import/ImportJob.php
Labels: master

#14219 dev/core#950 Remove deprecated :hover jQuery selector
  js/crm.menubar.js
Labels: 5.14, merge on pass

#14221 Add in Wrapper template around DatePickerRange template to have bette…
  templates/CRM/Activity/Form/Search/Common.tpl
  templates/CRM/Core/DatePickerRangeWrapper.tpl
Labels: 5.14

#14214 Add select2 to input field of datepicker
  CRM/Core/Form.php
Labels: 5.14, merge ready

#14227 5.14 to master
  CRM/Core/Form.php
  js/crm.menubar.js
  templates/CRM/Activity/Form/Search/Common.tpl
  templates/CRM/Core/DatePickerRangeWrapper.tpl
Labels: master

#14228 Remove deprecated :hover jQuery selector
  js/crm.menubar.js
Labels: 5.13

#14216 When creating relationship types don't munge names
  CRM/Admin/Form/RelationshipType.php
Labels: master

#14220 core/issues/923, Fixed notice error when creating/editing profile
  CRM/UF/Form/Group.php
Labels: 5.14, merge on pass

#14229 core/issues/923, Fixed notice error when creating/editing profile
  CRM/UF/Form/Group.php
Labels: 5.13, merge on pass

#14230 Fixes to layout on activity date time on search page
  CRM/Core/Form.php
  templates/CRM/Activity/Form/Search/Common.tpl
  templates/CRM/Core/DatePickerRangeWrapper.tpl
Labels: 5.13, merge on pass

#14233 dev/core#956 Fix hard breakage in find participants form when you do a filter on o…
  CRM/Event/Form/Search.php
Labels: 5.14, merge on pass

#14223 dev/core#942 fix failure to render names for some activities
  CRM/Activity/BAO/Activity.php
  api/v3/Activity.php
  tests/phpunit/CRM/Activity/BAO/ActivityTest.php
Labels: 5.14, merge on pass

#14234 dev/core#956 Fix hard breakage in find participants form when you do a filter on o…
  CRM/Event/Form/Search.php
Labels: 5.13, merge on pass

#14236 Fix Failing Activity Test
  CRM/Activity/BAO/Activity.php
Labels: 5.14

#14118 Fix financial acl permissions to respect check_permissions
  CRM/Contact/BAO/Query.php
  CRM/Contribute/BAO/Query.php
  tests/phpunit/api/v3/FinancialTypeACLTest.php
Labels: master

#14231 dev/core#942 fix failure to render names for some activities
  CRM/Activity/BAO/Activity.php
  api/v3/Activity.php
  tests/phpunit/CRM/Activity/BAO/ActivityTest.php
Labels: 5.13

#14238 5.14
  CRM/Activity/BAO/Activity.php
  CRM/Event/Form/Search.php
  CRM/UF/Form/Group.php
  api/v3/Activity.php
  tests/phpunit/CRM/Activity/BAO/ActivityTest.php
Labels: master

#14232 Add in release notes for 5.13.3 and bump version to 5.13.3
  CRM/Upgrade/Incremental/sql/5.13.3.mysql.tpl
  release-notes.md
  release-notes/5.13.3.md
  sql/civicrm_generated.mysql
  xml/version.xml
Labels: 5.13

#14226 Update testGetActivityAccessCiviCRMEnough test for clarity
  tests/phpunit/api/v3/ACLPermissionTest.php
Labels: master

#14206 REF Refactor to reduce duplication on payment forms
  CRM/Core/Form.php
  CRM/Core/Payment/ProcessorForm.php
  CRM/Financial/Form/Payment.php
Labels: master

#14160 dev/core#896 - fix notice warning on closing a case
  CRM/Case/Form/Activity.php
  CRM/Case/Form/Activity/ChangeCaseStatus.php
  tests/phpunit/CRM/Case/BAO/CaseTest.php
Labels: master

#14195 dev/core#932 Fix dedupe contacts flip selection
  CRM/Contact/Page/AJAX.php
  templates/CRM/Contact/Page/DedupeFind.tpl
Labels: master

#14181 dev/core#926 [ref] adds a test & does a preliminary extraction
  CRM/Contact/BAO/Query.php
  tests/phpunit/CRM/Contact/BAO/QueryTest.php
Labels: master

#14239 Remove broken delete from customGroupCreate
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: master

#14246 5.13.3 Release Notes
  contributor-key.yml
  release-notes.md
  release-notes/5.13.3.md
Labels: 5.14

#14248 5.14
  contributor-key.yml
  release-notes.md
  release-notes/5.13.3.md
Labels: master

#14257 5.14
  CRM/Core/BAO/Address.php
  CRM/Core/BAO/CustomField.php
  CRM/Core/BAO/CustomQuery.php
  CRM/Core/Page/File.php
  CRM/Event/Page/ManageEvent.php
  CRM/Utils/AutoClean.php
  CRM/Utils/File.php
  CRM/Utils/Rule.php
  api/v3/Generic.php
  bower.json
  composer.json
  composer.lock
  install/index.php
  release-notes.md
  release-notes/5.13.3.md
  release-notes/5.13.4.md
  settings/Core.setting.php
  tests/phpunit/CRM/Utils/FileTest.php
  tests/phpunit/api/v3/AddressTest.php
Labels: master

#14258 [REF] Super Minor code readability fix
  CRM/Dedupe/Merger.php
Labels: master

#14261 [REF] Remove extraneous variable
  CRM/Core/BAO/PrevNextCache.php
  CRM/Dedupe/Merger.php
Labels: master

#14263 dev/core/966 skip urlencode for email in elavon xml
  CRM/Core/Payment/Elavon.php
Labels: master

#14262 dev/core#964 Add start date and end date values on page contribution widget ajax response
  CRM/Contribute/BAO/Widget.php
Labels: master

#14259 Remove wasteful double-caching of settings metadata
  Civi/Core/SettingsMetadata.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/api/v3/SettingTest.php
Labels: master

#14264 [REF] Centralize logic for resolving settings pseudoconstants
  CRM/Admin/Form/SettingTrait.php
  Civi/Core/SettingsMetadata.php
  api/v3/Setting.php
Labels: master

#14260 [REF+test] clean up code for getting labels for merge screen, stdise
  CRM/Dedupe/Merger.php
  tests/phpunit/CRM/Dedupe/MergerTest.php
Labels: master

#14137 [REF][Test] Remove call to CRM_Contribute_BAO_Contribution::recordAdditionalPayment in favour of payment create
  CRM/Contribute/BAO/Contribution.php
  CRM/Financial/BAO/Payment.php
  tests/phpunit/CRM/Event/BAO/AdditionalPaymentTest.php
  tests/phpunit/CRM/Event/BAO/ChangeFeeSelectionTest.php
Labels: master

#14270 [ref] Remove reference symbol from 2 variables
  CRM/Contact/BAO/Contact.php
Labels: master

#14255 Rename agpl-3.0.txt to License
  LICENSE
Labels: master

#14254 add developer tab for summary report
  CRM/Report/Form/Contribute/Summary.php
Labels: master

#14273 [NFC] array formatting in CRM_Dedupe_MergerTest
  tests/phpunit/CRM/Dedupe/MergerTest.php
Labels: master, merge on pass

#14271 [TEST SUITE] Remove some use of dbunit from tests
  tests/phpunit/CRM/Utils/DeprecatedUtilsTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/api/v3/ContactTest.php
  tests/phpunit/api/v3/CustomValueTest.php
  tests/phpunit/api/v3/GroupNestingTest.php
  tests/phpunit/api/v3/dataset/email_contact_17.xml
Labels: master

#14266 dev/core#369 Prevent hard fail of API Job when SMS provider has been deleted
  CRM/Core/BAO/ActionSchedule.php
  tests/phpunit/CRM/Activity/BAO/ActivityTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/api/v3/JobTest.php
Labels: has-test, master

#14241 Try enabling api4 extension in test suite
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: master

#14276 Test cleanup to remove references to discontinued package dbunit
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/api/v3/ContactTest.php
  tests/phpunit/api/v3/MailingContactTest.php
Labels: master

#14278 [NFC] Update Language to be more user friendly when checking logs
  CRM/Core/BAO/ActionSchedule.php
  tests/phpunit/api/v3/JobTest.php
Labels: master, merge on pass

#12152 dev/drupal#19 Drupal8: Implement set UF locale/language (affects mailing tokens)
  CRM/Mailing/BAO/MailingJob.php
  CRM/Utils/System/Drupal8.php
Labels: master, sig:compatibility drupal

#14277 Remove htmlpurifier from composer and move it back to within IDS to f…
  CRM/Core/ClassLoader.php
  CRM/Core/IDS.php
  composer.json
  composer.lock
Labels: 5.14, merge on pass

#14287 Fix is_override logic in membership processing
  CRM/Member/BAO/Membership.php
Labels: 5.13

#14285 5.14 to master
  CRM/Core/ClassLoader.php
  CRM/Core/IDS.php
  composer.json
  composer.lock
Labels: master

#14284 dev/core#976 Remove htmlpurifier from composer and move it back to within IDS to f…
  CRM/Core/ClassLoader.php
  CRM/Core/IDS.php
  composer.json
  composer.lock
Labels: 5.13

#14289 Fix deprecation notice on manage events page
  CRM/Event/BAO/Event.php
Labels: master

#14267 dev/financial#54 Fix mishandling of deferred revenue settings
  CRM/Contribute/BAO/Contribution.php
  CRM/Contribute/Form/Contribution.php
  CRM/Event/Form/ManageEvent/Fee.php
  CRM/Event/Form/Participant.php
  CRM/Event/Form/Registration/Confirm.php
  CRM/Financial/BAO/FinancialAccount.php
  CRM/Member/Form/MembershipType.php
  CRM/Upgrade/Incremental/Base.php
  CRM/Upgrade/Incremental/php/FiveFifteen.php
  tests/phpunit/CRM/Contribute/BAO/ContributionTest.php
  tests/phpunit/CRM/Financial/BAO/FinancialAccountTest.php
  tests/phpunit/CRM/Upgrade/Incremental/BaseTest.php
Labels: has-test, master

#14288 [REF] Simplify ACL page template
  templates/CRM/Admin/Page/Access.tpl
Labels: master

#14291 [NFC] array formatting, some comments
  CRM/Contribute/BAO/Contribution.php
Labels: master

#14283 dev/core#980 [dbunit] QueryTest Remove dbunit dependency on discontinued dbunit
  tests/phpunit/CRM/Contact/BAO/QueryTest.php
  tests/phpunit/api/v3/ReportTemplateTest.php
Labels: master

#14297 [code-cleanup] remove orderBy param from getDuplicatePairs, it is not used
  CRM/Contact/Page/DedupeFind.php
  CRM/Dedupe/Merger.php
Labels: master

#14296 [NFC] fix docblock types from boolean to bool
  CRM/Admin/Page/Options.php
  CRM/Case/Form/Search.php
  CRM/Case/Form/Task/Delete.php
  CRM/Case/Form/Task/Restore.php
  CRM/Case/Selector/Search.php
  CRM/Case/XMLProcessor/Report.php
  CRM/Contact/BAO/Query.php
  CRM/Contribute/Form/AbstractEditPayment.php
  CRM/Contribute/Form/Contribution.php
  CRM/Contribute/Form/ContributionBase.php
  CRM/Contribute/Form/Search.php
  CRM/Contribute/Form/Task.php
  CRM/Contribute/Form/Task/Delete.php
  CRM/Contribute/Form/Task/Email.php
  CRM/Contribute/Form/Task/Invoice.php
  CRM/Contribute/Form/Task/PDF.php
  CRM/Contribute/Form/Task/Status.php
  CRM/Contribute/Import/Field.php
  CRM/Contribute/Import/Parser.php
  CRM/Contribute/Selector/Search.php
  CRM/Core/Form/Search.php
  CRM/Core/Page.php
  CRM/Core/Permission/Backdrop.php
  CRM/Core/Permission/Drupal.php
  CRM/Core/Permission/Drupal6.php
  CRM/Core/Permission/DrupalBase.php
  CRM/Core/Region.php
  CRM/Mailing/Page/Browse.php
  CRM/PCP/Form/PCPAccount.php
  CRM/Pledge/Form/Search.php
  CRM/Pledge/Form/Task/Delete.php
  CRM/Pledge/Selector/Search.php
  CRM/Price/Page/Field.php
  CRM/Price/Page/Option.php
  CRM/Profile/Selector/Listings.php
  CRM/Report/Form.php
  CRM/UF/Form/Field.php
  CRM/Upgrade/Form.php
Labels: master

#14294 [NFC] Fix variable types in DAO doc blocks
  CRM/ACL/DAO/ACL.php
  CRM/Core/CodeGen/Specification.php
Labels: master

#14300 [REF] Fix pointless use of CRM_Utils_Array::value in Campaign BAO
  CRM/Campaign/BAO/Campaign.php
Labels: master, merge on pass

#14295 [NFC] Add trailing comma to pseudoconstant array in DAOs
  CRM/ACL/DAO/ACL.php
  xml/templates/dao.tpl
Labels: master

#14282 [NFC] ProfileTest class - formatting & general cleanup
  Civi/Test/ContactTestTrait.php
  tests/phpunit/api/v3/ProfileTest.php
Labels: master

#14305 [NFC] fix more places where var is declared as boolean rather than bool
  CRM/Activity/Form/Activity.php
  CRM/Activity/Form/Search.php
  CRM/Activity/Form/Task/Delete.php
  CRM/Activity/Form/Task/Email.php
  CRM/Activity/Form/Task/SMS.php
  CRM/Activity/Import/Field.php
  CRM/Activity/Import/Parser.php
  CRM/Activity/Selector/Search.php
  CRM/Campaign/Form/Search.php
  CRM/Campaign/Selector/Search.php
  CRM/Contact/Form/Task/Delete.php
  CRM/Contact/Form/Task/Email.php
  CRM/Contact/Form/Task/Map.php
  CRM/Contact/Form/Task/SMS.php
  CRM/Contact/Import/Field.php
  CRM/Contribute/Form/ContributionPage.php
  CRM/Core/BAO/CustomQuery.php
  CRM/Core/Controller.php
  CRM/Custom/Import/Parser.php
  CRM/Event/Form/ManageEvent.php
  CRM/Event/Form/Participant.php
  CRM/Event/Form/Registration.php
  CRM/Event/Form/Registration/Register.php
  CRM/Event/Form/Search.php
  CRM/Event/Form/Task/Badge.php
  CRM/Event/Form/Task/Delete.php
  CRM/Event/Form/Task/Email.php
  CRM/Event/Form/Task/PDF.php
  CRM/Event/Import/Parser.php
  CRM/Event/Selector/Search.php
  CRM/Financial/BAO/ExportFormat.php
  CRM/Financial/Form/FinancialAccount.php
  CRM/Financial/Form/FinancialTypeAccount.php
  CRM/Grant/Form/Search.php
  CRM/Grant/Form/Task/Delete.php
  CRM/Grant/Selector/Search.php
  CRM/Mailing/Selector/Search.php
  CRM/Member/Form/Task/Delete.php
  CRM/Member/Form/Task/Email.php
  CRM/Member/Import/Field.php
  CRM/Member/Import/Parser.php
  CRM/Member/Selector/Search.php
  CRM/Profile/Page/Dynamic.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/api/v3/custom_api/MailingProviderData.php
Labels: master, merge on pass

#14306 [NFC] fix comment blocks capitalising null
  CRM/Case/XMLRepository.php
  CRM/Core/CodeGen/Main.php
  CRM/Core/Component/Info.php
  CRM/Report/Form.php
  Civi/ActionSchedule/Mapping.php
  Civi/Angular/AngularLoader.php
  Civi/Angular/Manager.php
  Civi/Core/SettingsBag.php
  Civi/Core/SettingsManager.php
  Civi/Core/SqlTriggers.php
  Civi/Test/CiviEnvBuilder.php
Labels: master, merge on pass

#14102 dev/core#888 - Backoffice participant transfer form does not populate…
  CRM/Event/Form/SelfSvcUpdate.php
Labels: master

#14301 [REF] Test class cleanup - Extract function to create nuanced custom fields to a trait
  tests/phpunit/CRMTraits/Custom/CustomDataTrait.php
  tests/phpunit/api/v3/RelationshipTest.php
Labels: master

#14303 [REF] extract buildGroupTree function
  CRM/Core/BAO/CustomGroup.php
Labels: master

#14211 crmRouteBinder - Remove params from url if they equal their defaults
  ang/crmRouteBinder.js
Labels: master

#14311 Make apiRequst nextId accessible for api4 constructor
  Civi/API/Request.php
Labels: master

#14308 [NFC] reformat UFFieldTest
  tests/phpunit/api/v3/UFFieldTest.php
Labels: master

#14307 NFC Fix DAO Style issues
  CRM/Batch/DAO/Batch.php
  CRM/Campaign/DAO/Campaign.php
  CRM/Contact/DAO/Contact.php
  CRM/Contact/DAO/RelationshipType.php
  CRM/Contribute/DAO/Contribution.php
  CRM/Contribute/DAO/ContributionPage.php
  CRM/Contribute/DAO/ContributionRecur.php
  CRM/Contribute/DAO/ContributionSoft.php
  CRM/Contribute/DAO/Product.php
  CRM/Core/CodeGen/Specification.php
  CRM/Core/DAO/Address.php
  CRM/Core/DAO/Component.php
  CRM/Core/DAO/MappingField.php
  CRM/Event/DAO/Event.php
  CRM/Event/DAO/Participant.php
  CRM/Financial/DAO/EntityFinancialTrxn.php
  CRM/Financial/DAO/FinancialAccount.php
  CRM/Financial/DAO/FinancialItem.php
  CRM/Financial/DAO/FinancialTrxn.php
  CRM/Grant/DAO/Grant.php
  CRM/Member/DAO/MembershipType.php
  CRM/PCP/DAO/PCP.php
  CRM/Pledge/DAO/Pledge.php
  CRM/Pledge/DAO/PledgePayment.php
  CRM/Price/DAO/LineItem.php
  CRM/Price/DAO/PriceFieldValue.php
  xml/schema/Contact/Contact.xml
  xml/schema/Contact/RelationshipType.xml
  xml/schema/Core/Address.xml
  xml/schema/Core/Component.xml
  xml/schema/Core/MappingField.xml
  xml/schema/Event/Participant.xml
  xml/templates/dao.tpl
Labels: master, merge on pass

#14312 dev/joomla#11 Fix php warning when viewing profiles
  CRM/Contact/BAO/Contact/Utils.php
Labels: master

#14309 dev/financial#56 Fix inappropriate sales tax row addition
  CRM/Contribute/BAO/Contribution.php
  tests/phpunit/CRM/Contribute/BAO/ContributionTest.php
Labels: has-test, master

#14313 dev/core#981 Sorting participants ignored search values.
  CRM/Event/Form/Search.php
Labels: master

#14302 dev/drupal#19 Drupal8: fix bootstrap when used by the REST API
  CRM/Utils/System/Drupal8.php
Labels: master

#14279 dev/core#980 [test-dbunit] Cleanup profile test to not use discontinuted dbunit
  tests/phpunit/api/v3/ProfileTest.php
Labels: master

#14269 [REF] Cleanup input & output on paymentActivityCreate & improve test
  CRM/Contribute/BAO/Contribution.php
  tests/phpunit/CRM/Contribute/Form/AdditionalPaymentTest.php
Labels: has-test, master

#14249 (dev/core#959) Expose contribution page in Contribution Summary report
  CRM/Report/Form/Contribute/Summary.php
Labels: master

#14265 NFC - Changed release notes info about Jira to GitLab
  release-notes.md
Labels: master

#14315 [dbunit] remove dbunit dependency from MembershipRenewalTest
  tests/phpunit/CRM/Member/Form/MembershipRenewalTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: master

#14319 [dbunit] remove dependencies on discontinued dbunit test package
  tests/phpunit/CRM/Activity/BAO/ActivityTest.php
  tests/phpunit/CRM/Contact/Form/Search/Custom/GroupTest.php
  tests/phpunit/CRM/Contact/Form/Search/Custom/SampleTest.php
  tests/phpunit/CRM/Core/BAO/IMTest.php
  tests/phpunit/CRM/Mailing/BAO/QueryTest.php
  tests/phpunit/CRM/Member/Form/MembershipTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/api/v3/ReportTemplateTest.php
  tests/phpunit/api/v3/UFFieldTest.php
  tests/phpunit/api/v3/UFJoinTest.php
  tests/phpunit/api/v3/UFMatchTest.php
Labels: master

#14314 [NFC] Fix comment block for variable declarations
  CRM/Contact/BAO/Query.php
  CRM/Contact/Form/Search.php
  CRM/Contact/Form/Search/Custom/FullText.php
  CRM/Contact/Form/Search/Custom/Group.php
  CRM/Contact/Import/Parser.php
  CRM/Contact/Page/ImageFile.php
  CRM/Contact/Page/View/ContactSmartGroup.php
  CRM/Contribute/Form/Contribution.php
  CRM/Contribute/Form/ContributionBase.php
  CRM/Core/Action.php
  CRM/Custom/Import/Parser.php
  CRM/Event/Form/ManageEvent.php
  CRM/Event/Form/Registration/Register.php
  CRM/Event/Import/Parser.php
  CRM/Financial/Form/Payment.php
  CRM/Mailing/Page/View.php
  CRM/Member/Import/Parser.php
  CRM/Report/Form.php
  CRM/SMS/Message.php
  CRM/UF/Form/Field.php
  CRM/Upgrade/Incremental/Base.php
  Civi/Angular/Page/Main.php
  tests/phpunit/CRM/Batch/Form/EntryTest.php
  tests/phpunit/CRM/Contact/BAO/QueryTestDataProvider.php
  tests/phpunit/CRM/Contact/Form/Search/Custom/GroupTestDataProvider.php
  tests/phpunit/CRM/Contact/Form/Search/Custom/SampleTestDataProvider.php
  tests/phpunit/CRM/Group/Page/AjaxTest.php
  tests/phpunit/CRM/Mailing/BAO/QueryTestDataProvider.php
  tests/phpunit/CRM/Member/Import/Parser/MembershipTest.php
  tests/phpunit/api/v3/RelationshipTest.php
  tests/phpunit/api/v3/TagTest.php
Labels: master

#14310 Add unit test for merge handling on custom data.
  CRM/Dedupe/Merger.php
  tests/phpunit/CRMTraits/Custom/CustomDataTrait.php
  tests/phpunit/api/v3/ContactTest.php
  tests/phpunit/api/v3/RelationshipTest.php
Labels: has-test, master

#14322 fixes issue #981: sort participants did not remember search criteria
  CRM/Event/Form/Search.php
Labels: 5.14, merge on pass

#14327 [NFC] Fix issue with Job Manager Test giving out a warning
  tests/phpunit/CRM/Core/JobManagerTest.php
Labels: master

#14082 dev/core/issues/743, Donot join relationship table when not required
  CRM/Report/Form/Case/Summary.php
Labels: master

#14087 (NFC) Update node package versions to latest ones
  package-lock.json
  package.json
Labels: master

#14321 dev/core#980 [dbunit] remove dependency on discontinued dbunit
  tests/fixtures/contacts.yaml
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: master

#13997 dev/core#830 Expose cancel_reason field by cleaning up the cancel template to use entity field template
  CRM/Contribute/Form/CancelSubscription.php
  CRM/Contribute/Form/ContributionRecur.php
  CRM/Core/Form/EntityFormTrait.php
  templates/CRM/Contribute/Form/CancelSubscription.tpl
  templates/CRM/Contribute/Page/ContributionRecur.tpl
Labels: master

#14329 dev/core#879 SMTP help text is misleading - references the wrong admin screen
  CRM/Admin/Form/Setting/Smtp.php
Labels: master

#14323 [NFC] Docblock fixes
  CRM/Case/BAO/Case.php
  CRM/Contact/BAO/Contact.php
  CRM/Contact/BAO/Contact/Permission.php
  CRM/Contact/BAO/Contact/Utils.php
  CRM/Contact/BAO/Group.php
  CRM/Contact/BAO/GroupContact.php
  CRM/Contact/BAO/Query/Hook.php
  CRM/Contact/BAO/Relationship.php
  CRM/Contact/Form/Search/Custom/FullText/AbstractPartialQuery.php
  CRM/Contact/Form/Task/AddToParentClass.php
  CRM/Contact/Import/Parser.php
  CRM/Core/BAO/ActionSchedule.php
  CRM/Core/BAO/Cache.php
  CRM/Core/BAO/Note.php
  CRM/Core/BAO/UFMatch.php
  CRM/Core/ClassLoader.php
  CRM/Core/CommunityMessages.php
  CRM/Core/Controller.php
  CRM/Core/DAO.php
  CRM/Core/Form.php
  CRM/Core/Form/Task/Batch.php
  CRM/Core/I18n.php
  CRM/Core/InnoDBIndexer.php
  CRM/Core/JobManager.php
  CRM/Core/Module.php
  CRM/Core/Page/AJAX.php
  CRM/Core/Payment/PayPalProIPN.php
  CRM/Core/Payment/PaymentExpressIPN.php
  CRM/Core/PrevNextCache/Interface.php
  CRM/Core/PrevNextCache/Sql.php
  CRM/Core/PseudoConstant.php
  CRM/Core/Reference/OptionValue.php
  CRM/Core/Region.php
  CRM/Core/Resources.php
  CRM/Core/Resources/Strings.php
  CRM/Core/Session.php
  CRM/Core/Smarty.php
  CRM/Extension/Container/Collection.php
  CRM/Extension/System.php
  CRM/Price/BAO/LineItem.php
  CRM/Price/BAO/PriceSet.php
  CRM/Utils/Hook.php
  CRM/Utils/Hook/WordPress.php
  CRM/Utils/Http.php
  CRM/Utils/HttpClient.php
  CRM/Utils/System/Backdrop.php
  CRM/Utils/System/Drupal.php
  CRM/Utils/System/Drupal6.php
  CRM/Utils/System/Drupal8.php
  CRM/Utils/System/WordPress.php
  Civi/API/Subscriber/DynamicFKAuthorization.php
  Civi/Core/Event/PostEvent.php
  Civi/Core/Event/PreEvent.php
  Civi/Core/Lock/LockInterface.php
  Civi/Core/Lock/LockManager.php
  Civi/Core/Lock/NullLock.php
  Civi/Core/SettingsBag.php
  Civi/Core/SettingsManager.php
  api/v3/utils.php
Labels: master

#14318 [REF] minor code re-org
  CRM/Contribute/BAO/Contribution.php
Labels: master

#14324 [REF] Extract function to get cached duplicate matches
  CRM/Dedupe/Merger.php
Labels: master

#14316 Fix test / possible live error on submitting credit card renewals
  CRM/Member/Form/MembershipRenewal.php
Labels: master

#14292 Reduce cache bypasses - do not bypass custom metadata cache in setGroupTree
  CRM/Custom/Form/CustomData.php
Labels: master, ok-without-test

#14328 [dbunit test] remove dbunit dependency
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: master

#14158 dev/core#913 - update autogenerated .htaccess for apache 2.4
  CRM/Utils/File.php
Labels: master

#14138 dev/core#898: use user.login route for D8 login URL instead of user.page
  CRM/Utils/System/Drupal8.php
  contributor-key.yml
Labels: master

#14338 [REF] use generic loadStandardSearchOptionsFromUrl
  CRM/Contact/Form/Search.php
Labels: master, merge on pass

#14340 Unit test for FGB error in #14331
  tests/phpunit/CRM/Contact/SelectorTest.php
Labels: master

#14331 Fix fatal error when full group by mysql mode enabled & selecting contacts
  CRM/Contact/BAO/Query.php
Labels: master, merge on pass

#14344 [NFC] Further tests tidy up following removing of dbunit
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tools/scripts/phpunit-ls
Labels: master, merge on pass

#14336 [REF] extract isLiveMode
  CRM/Contact/Form/Task/PDFLetterCommon.php
Labels: master

#14341 Remove never-called function _civicrm_api3_deprecated_contact_check_custom_params
  CRM/Utils/DeprecatedUtils.php
Labels: master

#14334 [REF] extract updateFinancialAccountsOnContributionStatusChange
  CRM/Contribute/BAO/Contribution.php
Labels: master

#14332 dev/core#968 Fix javascript error on public pages
  js/crm.drupal8.js
Labels: 5.14

#14335 [NFC] phpdoc cleanup
  CRM/Contribute/BAO/Contribution.php
  CRM/Contribute/Form/AbstractEditPayment.php
  CRM/Contribute/Form/Contribution.php
  CRM/Contribute/Form/ContributionRecur.php
  CRM/Contribute/Page/UserDashboard.php
  CRM/Core/BAO/ActionSchedule.php
  CRM/Core/DAO/permissions.php
  CRM/Core/Payment/FirstData.php
  CRM/Core/Payment/eWAY.php
  CRM/Core/Reference/OptionValue.php
Labels: master

#14342 [REF] Remove input format function from deprecated utils to the only place that calls it
  CRM/Contribute/Import/Parser/Contribution.php
  CRM/Utils/DeprecatedUtils.php
Labels: master

#13374 correct syntax "IS NOT NULL" to get pledge payment count
  CRM/Pledge/BAO/Pledge.php
Labels: master, needs-test

#14345 Remove duplicate line in case BAO
  CRM/Case/BAO/Case.php
Labels: master, merge on pass

#14350 dev/core#627 Extend a unit test to verify fix made by Sunil
  tests/phpunit/CRM/Pledge/BAO/PledgePaymentTest.php
  tests/phpunit/CRM/Pledge/BAO/PledgeTest.php
Labels: master, merge on pass
