Repository civicrm/civicrm-core, pull requests merged in 2019-08, with the labels that each got.

#14320 dev/core#987 Reporthook
  CRM/Report/Form.php
Labels: master

#14734 (dev/core#1104) make admin panels hookable
  CRM/Admin/Page/Admin.php
  CRM/Utils/Hook.php
Labels: master, needs-documentation

#14942 [Report] Fix handling of location type in Reports
  CRM/Report/Form.php
  tests/phpunit/CRM/Report/Form/ContactSummaryTest.php
Labels: master, merge on pass

#14941 [REPORT] Allow extensions to join address, email and phone tables without limi…
  CRM/Report/Form.php
  tests/phpunit/CRM/Report/Form/ContactSummaryTest.php
Labels: master, merge on pass

#14940 Fix mishandling of renamed membership status labels on membership import
  CRM/Contribute/Import/Parser/Contribution.php
  CRM/Core/PseudoConstant.php
  CRM/Import/Parser.php
  CRM/Member/Import/Parser/Membership.php
  CRM/Member/PseudoConstant.php
  tests/phpunit/CRM/Member/Import/Parser/MembershipTest.php
Labels: master

#14930 Catch Payment Processor Exception if thrown when registering via bac…
  CRM/Event/Form/Participant.php
Labels: master

#14252 dev/core#961 - Contribution page including 2 email fields does not re…
  CRM/Dedupe/Finder.php
  tests/phpunit/CRM/Dedupe/DedupeFinderTest.php
Labels: has-test, master

#14944 Better support for hookable menubar colors
  CRM/Core/Resources.php
  CRM/Utils/Color.php
  bower.json
  settings/Core.setting.php
  tests/phpunit/CRM/Utils/ColorTest.php
Labels: 5.16, has-test

#14948 5.16 to master
  CRM/Core/Resources.php
  CRM/Utils/Color.php
  bower.json
  settings/Core.setting.php
  tests/phpunit/CRM/Utils/ColorTest.php
Labels: master

#14947 dev/core#1162 [TEST] [Mailing] add in unit test checking that no bulk email flag is re…
  tests/phpunit/CRM/Mailing/BAO/MailingTest.php
Labels: master, merge on pass

#14949 [NFC] Formatting in BAO_Relationship class
  CRM/Contact/BAO/Relationship.php
Labels: master, merge on pass

#14946 Add test for failed payment
  CRM/Core/Payment/Dummy.php
  tests/phpunit/CRM/Event/Form/ParticipantTest.php
Labels: master, merge on pass

#14952 [NFC] dev/core#1116 - document where activityTypeName is name and where it's label
  CRM/Financial/Form/FinancialBatch.php
  templates/CRM/Activity/Form/Activity.tpl
  templates/CRM/Case/Form/Activity.tpl
  tests/phpunit/CRM/Core/BAO/MessageTemplateTest.php
  tools/bin/scripts/testProcess.php
Labels: master

#14840 core#1130 - allow search views to show contact subtype
  CRM/Contact/Selector.php
  templates/CRM/Contact/Form/Selector.tpl
Labels: master

#14933 [REF] [Test] [Export] Convert some more tests to use the newer function
  CRM/Export/BAO/ExportProcessor.php
  tests/phpunit/CRM/Export/BAO/ExportTest.php
Labels: has-test, master

#14937 dev/core#439 [Export] [Ref] Convert custom data export test to use newer function.
  CRM/Core/BAO/CustomField.php
  CRM/Export/BAO/ExportProcessor.php
  tests/phpunit/CRM/Core/BAO/CustomFieldTest.php
  tests/phpunit/CRM/Export/BAO/ExportTest.php
  tests/phpunit/CRMTraits/Custom/CustomDataTrait.php
Labels: has-test, master

#14950 Move the code to add employer from relationship backoffice form to BAO
  CRM/Contact/BAO/Contact/Utils.php
  CRM/Contact/BAO/Relationship.php
  CRM/Contact/Form/Relationship.php
  api/v3/Relationship.php
  tests/phpunit/api/v3/RelationshipTest.php
Labels: has-test, master

#14953 [TEST] [REF] [Export] Convert a couple more tests
  tests/phpunit/CRM/Export/BAO/ExportTest.php
Labels: has-test, master, merge on pass

#14945 Add missing is_public flags to public paths
  CRM/Core/xml/Menu/Admin.xml
  CRM/Core/xml/Menu/Misc.xml
  CRM/Event/xml/Menu/Event.xml
  CRM/Report/xml/Menu/Report.xml
Labels: master

#14954 Add serialization metadata for MembershipType api
  CRM/Member/DAO/MembershipType.php
  tests/phpunit/CRM/Contact/BAO/RelationshipTest.php
  xml/schema/Member/MembershipType.xml
Labels: has-test, master, merge on pass

#14921 Core/dev#692 support for some additional url params
  CRM/Contact/Form/Search/Advanced.php
  CRM/Contact/Form/Search/Criteria.php
  CRM/Core/Form/Search.php
Labels: master

#14961 [REF] simple extraction of function to check required fields are present
  CRM/Contribute/Import/Form/MapField.php
Labels: master, merge on pass

#14963 [REF] Move Self service handlng to shared function to allow for use i…
  CRM/Contribute/Form/CancelSubscription.php
  CRM/Contribute/Form/ContributionRecur.php
Labels: master, merge on pass

#14951 dev/core#470: Current employer disapears when disabling expired relationships
  CRM/Contact/BAO/Relationship.php
  tests/phpunit/api/v3/RelationshipTest.php
Labels: has-test, master

#14844 dev/core#1135 Participants having multiple roles affects maximum event registration count
  CRM/Event/BAO/Participant.php
Labels: master

#14943 Fix removeNullContactTokens compatibility with custom tokens
  CRM/Utils/Token.php
  tests/phpunit/CRM/Utils/TokenTest.php
Labels: master

#14962 [REF] minor code cleanup on import mapping
  CRM/Contribute/Import/Form/MapField.php
Labels: master

#14970 [NFC] dev/core#1116 - seek and document where activityTypeName is name and where it's label
  CRM/Activity/Form/ActivityView.php
Labels: master

#14957 [NFC] minor cleanup
  CRM/Event/Form/Registration/Confirm.php
Labels: master

#14959 Minor cleanup around invoicing on event code
  CRM/Event/Form/Registration/Confirm.php
Labels: master

#14973 5.16.0 release notes - late changes
  contributor-key.yml
  release-notes.md
  release-notes/5.15.1.md
  release-notes/5.15.2.md
  release-notes/5.16.0.md
Labels: 5.16, merge on pass

#14974 5.16.0 to master
  contributor-key.yml
  release-notes.md
  release-notes/5.15.1.md
  release-notes/5.15.2.md
  release-notes/5.16.0.md
Labels: master

#14971 Translation 'ts' usage fixes.
  CRM/Admin/Form/Options.php
  CRM/Admin/Form/Preferences/Contribute.php
  CRM/Admin/Form/SettingTrait.php
  CRM/Batch/Form/Entry.php
  CRM/Contribute/BAO/Contribution.php
  CRM/Contribute/Exception/FutureContributionPageException.php
  CRM/Contribute/Exception/InactiveContributionPageException.php
  CRM/Contribute/Exception/PastContributionPageException.php
  CRM/Contribute/Form/AbstractEditPayment.php
  CRM/Contribute/Form/Contribution/Main.php
  CRM/Contribute/Form/ContributionBase.php
  CRM/Event/Form/SelfSvcTransfer.php
  CRM/Event/Page/ParticipantListing/NameStatusAndDate.php
  CRM/Financial/BAO/FinancialType.php
  CRM/Utils/Mail/Incoming.php
  CRM/Utils/System/Backdrop.php
  tests/phpunit/CRM/Financial/BAO/FinancialTypeTest.php
Labels: master, merge on pass

#14964 dev/core#1061 Ensure that custom data is not loaded on update subscription form when in self service mode and re-use shared function
  CRM/Contribute/Form/UpdateSubscription.php
  templates/CRM/Contribute/Form/UpdateSubscription.tpl
Labels: master

#14965 [REF] Update selfService in updateBilling to use shared function
  CRM/Contribute/Form/ContributionRecur.php
  CRM/Contribute/Form/UpdateBilling.php
Labels: master, merge on pass

#14969 Use metadata for getOptions abbreviation & include currency symbol
  CRM/Contribute/DAO/Contribution.php
  CRM/Contribute/DAO/ContributionPage.php
  CRM/Contribute/DAO/ContributionRecur.php
  CRM/Contribute/DAO/ContributionSoft.php
  CRM/Contribute/DAO/Product.php
  CRM/Core/CodeGen/Specification.php
  CRM/Core/DAO/Address.php
  CRM/Core/PseudoConstant.php
  CRM/Event/DAO/Event.php
  CRM/Event/DAO/Participant.php
  CRM/Financial/DAO/FinancialItem.php
  CRM/Financial/DAO/FinancialTrxn.php
  CRM/Grant/DAO/Grant.php
  CRM/PCP/DAO/PCP.php
  CRM/Pledge/DAO/Pledge.php
  CRM/Pledge/DAO/PledgePayment.php
  tests/phpunit/api/v3/AddressTest.php
  tests/phpunit/api/v3/ContributionTest.php
  xml/schema/Contribute/Contribution.xml
  xml/schema/Contribute/ContributionPage.xml
  xml/schema/Contribute/ContributionRecur.xml
  xml/schema/Contribute/ContributionSoft.xml
  xml/schema/Contribute/Product.xml
  xml/schema/Core/Address.xml
  xml/schema/Event/Event.xml
  xml/schema/Event/Participant.xml
  xml/schema/Financial/FinancialItem.xml
  xml/schema/Financial/FinancialTrxn.xml
  xml/schema/Grant/Grant.xml
  xml/schema/PCP/PCP.xml
  xml/schema/Pledge/Pledge.xml
  xml/schema/Pledge/PledgePayment.xml
Labels: has-test, master

#14977 [NFC] code formatting only
  CRM/Contact/Import/Form/MapField.php
Labels: master, merge on pass

#14975 Add pseudoconstant metadata to mapping_field.location_type_id
  CRM/Core/DAO/MappingField.php
  xml/schema/Core/MappingField.xml
Labels: master, merge on pass

#14956 [Test] Add test cover for Member_BAO_Query auto_renew field
  tests/phpunit/CRM/Export/BAO/ExportTest.php
  tests/phpunit/CRM/Member/Selector/SearchTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: has-test, master

#14976 [REF][Import] very minor cleanup - 3 lines of code to one
  CRM/Contact/Import/Parser.php
Labels: master, merge on pass

#14979 [REF] [Import] extract function that sets field metadata
  CRM/Contact/Import/Parser/Contact.php
  CRM/Import/Parser.php
Labels: master, merge on pass

#14960 dev/drupal#72 Ensure front end profile title is used in event confirmation emails
  CRM/Contribute/BAO/Contribution.php
  CRM/Core/BAO/UFGroup.php
  CRM/Event/BAO/Event.php
  CRM/Event/Form/Registration/Confirm.php
  api/api.php
  tests/phpunit/CRM/Event/Form/Registration/ConfirmTest.php
  tests/phpunit/CRMTraits/Profile/ProfileTrait.php
  tests/phpunit/api/v3/ContributionTest.php
Labels: has-test, master, merge on pass

#14986 [REF][Import] add formatted parameter to formatInput
  CRM/Contribute/Import/Parser/Contribution.php
Labels: 5.16

#14987 5.16 to master
  CRM/Contribute/Import/Parser/Contribution.php
Labels: master

#14978 Fix (unreleased regression) e-notices on import form
  CRM/Contact/Import/Form/MapField.php
  CRM/Import/Form/MapField.php
Labels: master

#14983 dev/core#1109 - Fix merge not updating ContactReference fields
  CRM/Core/DAO.php
  CRM/Dedupe/Merger.php
  tests/phpunit/CRM/Dedupe/MergerTest.php
Labels: has-test, master

#14985 Issue 1170
  CRM/Utils/System/Backdrop.php
Labels: master

#14222 Error log improvements: Provide severity level and use Civi::log()
  CRM/Core/Error.php
  CRM/Core/Error/Log.php
Labels: master

#14991 Further e-notice regression fix
  CRM/Contact/Import/Form/MapField.php
Labels: master

#14927 Remove template field if using Mosaico in non shoreditch mode
  ang/crmMailing/BlockMailing.html
  ang/crmMailingAB/BlockMailing.html
Labels: master

#14990 Remove ?last? instances of ->free() dev/core#562
  CRM/Core/DAO.php
  CRM/Utils/System/Backdrop.php
  CRM/Utils/System/Drupal.php
  CRM/Utils/System/Drupal6.php
  CRM/Utils/System/Drupal8.php
  CRM/Utils/System/Joomla.php
  CRM/Utils/System/WordPress.php
  tools/scripts/solr/createSyncJSON.php
Labels: master

#14996 Revert #14222 on RC branch
  CRM/Core/Error.php
  CRM/Core/Error/Log.php
Labels: 5.17

#14997 5.17 to master
  CRM/Core/Error.php
  CRM/Core/Error/Log.php
Labels: master

#14980 [clean up][ export] Remove membership_auto_renew from defaultReturn properties
  CRM/Member/BAO/Query.php
  tests/phpunit/CRM/Export/BAO/ExportTest.php
Labels: master

#14955 [REF] Extract chunk of code relating to whether to disabled an inherited relationship
  CRM/Contact/BAO/Relationship.php
  tests/phpunit/CRM/Contact/BAO/RelationshipTest.php
Labels: has-test, master

#14998 Allow Manual Geo Code flag to be exported
  CRM/Core/DAO/Address.php
  tests/phpunit/CRM/Export/BAO/ExportTest.php
  xml/schema/Core/Address.xml
Labels: master, merge on pass

#14715 Rewrite subTypeInfo to use caching mechanism
  CRM/Contact/BAO/ContactType.php
  CRM/Utils/System.php
  Civi/Core/Container.php
  tests/phpunit/CRM/Contact/BAO/ContactType/ContactTypeTest.php
Labels: has-test, master, merge on pass

#14995 Error log improvements: Provide priority level
  CRM/Core/Error.php
Labels: master

#15007 core#1175 - fix custom searches
  CRM/Core/DAO.php
Labels: 5.17, merge on pass

#15008 5.17
  CRM/Core/DAO.php
Labels: master

#15009 core#1175 - fix custom searches
  CRM/Core/DAO.php
Labels: 5.16, merge on pass

#15010 Event confirm - (very) minor cleanup + test
  CRM/Event/BAO/Event.php
  CRM/Event/Form/Registration/Confirm.php
  tests/phpunit/CRM/Event/Form/Registration/ConfirmTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/api/v3/PaymentTest.php
Labels: master, merge on pass

#15013 [Import] Minor cleanup on membership import
  CRM/Member/Import/Parser/Membership.php
Labels: master, merge on pass

#15019 core#1182 - revert crm.menubar.js changes
  js/crm.menubar.js
Labels: master

#15005 Swap CRM_Utils_Array::value for empty() in conditionals
  CRM/Activity/BAO/Activity.php
  CRM/Admin/Form/Extensions.php
  CRM/Admin/Form/ScheduleReminders.php
  CRM/Admin/Form/Setting/Localization.php
  CRM/Badge/BAO/Badge.php
  CRM/Case/Form/Activity/ChangeCaseType.php
  CRM/Contact/Form/DedupeRules.php
  CRM/Contact/Form/Task/ProximityCommon.php
  CRM/Contribute/BAO/Contribution.php
  CRM/Contribute/Form/Contribution.php
  CRM/Contribute/Form/Contribution/Confirm.php
  CRM/Contribute/Form/Contribution/Main.php
  CRM/Contribute/Form/ContributionPage.php
  CRM/Contribute/Form/ContributionPage/Amount.php
  CRM/Core/BAO/Location.php
  CRM/Core/BAO/RecurringEntity.php
  CRM/Core/BAO/Setting.php
  CRM/Core/BAO/StatusPreference.php
  CRM/Core/BAO/UFField.php
  CRM/Core/DAO/AllCoreTables.php
  CRM/Core/Form/RecurringEntity.php
  CRM/Core/Form/Search.php
  CRM/Core/Page/AJAX.php
  CRM/Core/Page/AJAX/RecurringEntity.php
  CRM/Custom/Form/Preview.php
  CRM/Event/Cart/Form/Checkout/Payment.php
  CRM/Event/Form/ManageEvent/Repeat.php
  CRM/Event/Form/Registration.php
  CRM/Event/Form/Registration/Confirm.php
  CRM/Event/Form/Registration/Register.php
  CRM/Financial/BAO/FinancialType.php
  CRM/Financial/BAO/Payment.php
  CRM/Financial/Form/FinancialAccount.php
  CRM/Member/BAO/Membership.php
  CRM/Member/Form/Membership.php
  CRM/Pledge/BAO/Pledge.php
  CRM/Pledge/BAO/PledgeBlock.php
  CRM/Price/BAO/LineItem.php
  CRM/Price/BAO/PriceSet.php
  CRM/Price/Form/Field.php
  CRM/Report/Form/Contribute/Detail.php
  CRM/Report/Form/Event/Summary.php
  CRM/Utils/API/ReloadOption.php
  CRM/Utils/Address.php
  api/v3/LineItem.php
  api/v3/Order.php
  api/v3/Payment.php
Labels: master

#15021 core#1182 - revert crm.menubar.js changes
  js/crm.menubar.js
Labels: 5.17, merge on pass

#15022 core#1182 - revert crm.menubar.js changes
  js/crm.menubar.js
Labels: 5.16, merge on pass

#15023 Bump Version to 5.16.1 and add in release notes
  CRM/Upgrade/Incremental/sql/5.16.1.mysql.tpl
  release-notes.md
  release-notes/5.16.1.md
  sql/civicrm_generated.mysql
  xml/version.xml
Labels: 5.16

#15016 [NFC] [Test] dev/core#1098 Add unit test & code comments relating to the slow activity search
  CRM/Activity/BAO/Activity.php
  CRM/Activity/Selector/Search.php
  tests/phpunit/CRM/Activity/Selector/SearchTest.php
Labels: has-test, master

#15025 5.16.1 release notes
  release-notes.md
  release-notes/5.16.1.md
Labels: 5.17

#15026 5.17 to master
  release-notes.md
  release-notes/5.16.1.md
Labels: master

#14999 dev/core#1116 - just rename local var activityTName
  CRM/Activity/Form/Activity.php
Labels: master, merge on pass

#14988 Unit test for custom date parsing
  tests/phpunit/CRM/Contribute/Import/Parser/ContributionTest.php
  tests/phpunit/CRMTraits/Custom/CustomDataTrait.php
Labels: has-test, master

#15012 dev/core#752 Add cid parameter when loading custom data via backend f…
  CRM/Activity/Form/Activity.php
  CRM/Custom/Form/CustomData.php
  CRM/Custom/Form/CustomDataByType.php
  templates/CRM/common/customData.tpl
  templates/CRM/common/customDataBlock.tpl
Labels: master

#15027 [Test] Demonstrate the truthiness of CRM_Utils_System::isNull
  tests/phpunit/CRM/Utils/SystemTest.php
Labels: master

#15031 Fix upgrade version for #13487
  xml/schema/Core/ActionLog.xml
Labels: master

#15000 dev/core#1116 - rename local var activityName
  CRM/Activity/Form/Activity.php
Labels: master

#15033 Remove silly dumb unreachable lines
  CRM/Contact/Import/Form/MapField.php
Labels: master

#15036 Add myself to the contributor list
  contributor-key.yml
Labels: master

#15037 dev/financial#65 - Revert recent changes that cause financial account edit form to be blank
  CRM/Financial/BAO/FinancialAccount.php
Labels: 5.17, merge on pass

#15038 5.17 to master
  CRM/Financial/BAO/FinancialAccount.php
Labels: master

#15039 dev/financial#65
  CRM/Financial/BAO/FinancialAccount.php
Labels: 5.16

#15040 Set version 5.16.2. Add release notes.
  CRM/Upgrade/Incremental/sql/5.16.2.mysql.tpl
  release-notes.md
  release-notes/5.16.2.md
  sql/civicrm_generated.mysql
  xml/version.xml
Labels: 5.16

#15041 Add release-notes/5.16.2.md
  release-notes.md
  release-notes/5.16.2.md
Labels: 5.17, merge on pass

#15042 5.17
  release-notes.md
  release-notes/5.16.2.md
Labels: master

#14992 Membership fee token fix dev/core/#377
  CRM/Member/Tokens.php
Labels: master, merge ready

#15035 Display only own assignees contact(s) on batch activity form
  CRM/Activity/Form/Task/Batch.php
Labels: easy-review, master, ok-without-test

#15045 Enable view/revert delete action for detail logging
  CRM/Report/Form/Contact/LoggingSummary.php
Labels: master

#15032 dev/core#1116 - towards fixing activity type name vs label
  CRM/Activity/Form/Activity.php
Labels: master

#15028 [Test] [Ref] [Import]Add wrapper class for importProcessor
  CRM/Contact/Import/Parser/Contact.php
  CRM/Import/ImportProcessor.php
  tests/phpunit/CRM/Contact/Import/Parser/ContactTest.php
Labels: has-test, master

#14981 [Import] [Cleanup] remove unused parameters
  CRM/Contribute/Import/Form/MapField.php
Labels: master

#15017 [REF] [Import] extract saved mapping code to parent class
  CRM/Contribute/Import/Form/MapField.php
  CRM/Import/Form/MapField.php
Labels: master

#15015 [REF] [Import] Minor cleanup on status setting.
  CRM/Contact/Import/Form/MapField.php
Labels: master

#15029 Allow for the deselection of sorting filters
  templates/CRM/Report/Form/Tabs/OrderBy.tpl
Labels: easy-review, master, ok-without-test

#15047 dev/core#1190 Add pptx to safe file types
  CRM/Upgrade/Incremental/php/FiveSeventeen.php
  sql/civicrm_generated.mysql
  xml/templates/civicrm_data.tpl
Labels: 5.17

#15054 Update select2 to latest 3.x + patches
  bower.json
Labels: master

#15056 5.17
  CRM/Upgrade/Incremental/php/FiveSeventeen.php
  sql/civicrm_generated.mysql
  xml/templates/civicrm_data.tpl
Labels: master

#15046 Do not show Activity Separation on when viewing an Activity
  CRM/Activity/Form/Activity.php
  templates/CRM/Activity/Form/Activity.tpl
Labels: master

#15055 dev/core#1186 - ignore exception if no description field
  CRM/Core/BAO/CustomField.php
Labels: 5.17

#15057 [NFC] Update Upgrade Template to use short array syntax
  CRM/Upgrade/Incremental/php/Template.php
Labels: master, merge on pass

#15058 dev/core#1186 add in unit test to lock in fix from dmeritcowboy in #1…
  tests/phpunit/CRM/Core/BAO/CustomFieldTest.php
Labels: 5.17, merge on pass

#15060 dev/event#10 - Prevent old notes from being exposed in event confirmation email
  CRM/Event/BAO/Event.php
  CRM/Event/Form/Registration/Confirm.php
  tests/phpunit/CRM/Event/Form/Registration/ConfirmTest.php
Labels: has-test, master

#15059 5.17
  CRM/Core/BAO/CustomField.php
  tests/phpunit/CRM/Core/BAO/CustomFieldTest.php
Labels: master

#15043 dev/core#1188 Fix API v3 error Class or interface CiviCRM_API3_Exception does not exist
  CRM/Core/ClassLoader.php
Labels: master

#15048 Fix unreleased regression on import
  CRM/Contact/Import/Parser.php
Labels: 5.17

#15018 [Ref] [Import] move metadata calculations to a trait
  CRM/Contact/Import/MetadataTrait.php
  CRM/Contact/Import/Parser/Contact.php
Labels: master

#15065 5.17
  CRM/Contact/Import/Parser.php
Labels: master

#15049 [NFC] swap instances where double = is used but it should be triple =
  CRM/Contact/Import/Form/MapField.php
  tests/phpunit/CRM/Contact/Import/Form/MapFieldTest.php
Labels: master

#15067 [NFC] Fix test syntax
  tests/phpunit/CRM/Event/Form/Registration/ConfirmTest.php
Labels: master, merge on pass

#15066 Stabalize Attachment API Test
  tests/phpunit/api/v3/AttachmentTest.php
Labels: master, merge on pass

#15050 [Import] [Test] Initial test on loadSavedMapping function.
  CRM/Contact/Import/Form/MapField.php
  tests/phpunit/CRM/Contact/Import/Form/MapFieldTest.php
Labels: master, merge on pass

#15071 (NFC) GenericAssertionsTrait - Improve docblocks
  Civi/Test/GenericAssertionsTrait.php
Labels: master, merge on pass

#14673 Further work on payment.create consolidation - always handle financials from payment.create
  CRM/Contribute/BAO/Contribution.php
  CRM/Financial/BAO/Payment.php
  api/v3/Contribution.php
Labels: has-test, master

#15074 dev/core#1077 Fixes making report listing actions links hookable
  CRM/Report/Page/InstanceList.php
Labels: master

#15075 Fixes for taking dynamic form name in grant search
  CRM/Grant/Form/Task.php
Labels: master

#15077 [NFC] Update the APIv3 documentation links.
  tests/templates/documentFunction.tpl
Labels: master

#15076 dev/core#870 priceset hook
  CRM/Price/BAO/PriceField.php
  CRM/Price/BAO/PriceFieldValue.php
  CRM/Price/BAO/PriceSet.php
Labels: master

#15052 Manage Group search message fix
  templates/CRM/Group/Form/Search.tpl
Labels: master

#15079 dev/core#1192 - E_NOTICE on using Add Activity action on contact search results
  CRM/Core/Form/RecurringEntity.php
Labels: master, merge on pass

#15080 catch exception when no description
  CRM/Core/BAO/CustomField.php
Labels: 5.16

#15051 Remove "Copy Case custom data" code (circa 2013)
  CRM/Case/BAO/Case.php
  tests/phpunit/CRM/Case/BAO/CaseTest.php
Labels: 5.17, merge on pass

#15082 (dev/drupal#79) CRM_Upgrade_Form - Raise MINIMUM_PHP_VERSION from 5.6 to 7.0
  CRM/Upgrade/Form.php
Labels: 5.17, merge on pass

#15083 5.17
  CRM/Case/BAO/Case.php
  CRM/Upgrade/Form.php
  tests/phpunit/CRM/Case/BAO/CaseTest.php
Labels: master

#15070 Remove deprecated unused function.
  CRM/Member/BAO/MembershipType.php
Labels: master, merge ready

#15078 Remove a few unused scripts from tools/bin/scripts
  tools/bin/scripts/ImportTags.php
  tools/bin/scripts/create-pot-files
  tools/bin/scripts/createdoc.sh
  tools/bin/scripts/delete.sh
  tools/bin/scripts/drop-closing-php-tags.sh
  tools/bin/scripts/ircbot-civi.py
  tools/bin/scripts/memcache.php
  tools/bin/scripts/runStressTest.sh.txt
Labels: master, merge ready

#15084 Backport of PR #15051 to 5.16
  CRM/Case/BAO/Case.php
  tests/phpunit/CRM/Case/BAO/CaseTest.php
Labels: 5.16, merge on pass

#14916 Fix metadata on member export
  CRM/Core/BAO/UFField.php
  CRM/Member/DAO/Membership.php
  CRM/Member/Import/Parser/Membership.php
  CRM/Upgrade/Incremental/php/FiveEighteen.php
  tests/phpunit/CRM/Export/BAO/ExportTest.php
  tests/phpunit/CRM/Member/Import/Parser/MembershipTest.php
  tests/phpunit/api/v3/MembershipTest.php
  xml/schema/Member/Membership.xml
Labels: master

#15087 5.17.0 release notes - initial run
  release-notes.md
  release-notes/5.17.0.md
Labels: 5.17

#15088 5.17 to master
  release-notes.md
  release-notes/5.17.0.md
Labels: master

#15090 (dev/drupal#79) CRM_Upgrade_Form - Raise MINIMUM_PHP_VERSION from 5.6 to 7.0
  CRM/Upgrade/Form.php
Labels: 5.16

#15069 [Test] Tolerance parameter in attachmenttest needs to be one higher for integers
  tests/phpunit/api/v3/AttachmentTest.php
Labels: master

#15091 Remove unused method CRM_Contact_BAO_Contact_Utils::maxLocations
  CRM/Contact/BAO/Contact/Utils.php
Labels: master

#15092 Fix recursion in crmInArray()
  CRM/Utils/Array.php
Labels: master

#14989 dev/core#1001 Fix count notice warnings in php 7.2 [Import]
  CRM/Contribute/Import/Parser.php
  tests/phpunit/CRM/Contribute/Import/Parser/ContributionTest.php
Labels: master

#15002 dev/core#1116 - refactor/rename activityTypeName
  CRM/Activity/Form/Activity.php
  tests/phpunit/CRM/Activity/Form/ActivityTest.php
Labels: master

#15093 Fix wrong variable in check for profiles on contributionpage
  CRM/Contribute/BAO/ContributionPage.php
Labels: master, merge on pass

#15072 [NFC] Add ImportProcessor class & unit tests + extend existing cover
  CRM/Import/ImportProcessor.php
  tests/phpunit/CRM/Contact/Import/Form/MapFieldTest.php
Labels: master

#15068 [REF] minor code refactor on import - Pass ProcessorObject into loadSavedMapping & use it to load the formName
  CRM/Contact/Import/Form/MapField.php
  tests/phpunit/CRM/Contact/Import/Form/MapFieldTest.php
Labels: master

#15061 Fix readability & caching on CRM_Contact_BAO_Relationship::isInheritedMembershipInvalidated
  CRM/Contact/BAO/Relationship.php
  CRM/Member/BAO/MembershipType.php
  CRM/Utils/System.php
  Civi/Core/Container.php
  api/v3/MembershipType.php
Labels: master

#15089 (dev/drupal#79) Fail more gracefully when attempting to install on PHP 5.x
  composer.json
  composer.lock
  install/index.php
  tests/phpunit/CRM/Upgrade/FormTest.php
Labels: 5.17

#15098 5.17
  composer.json
  composer.lock
  install/index.php
  tests/phpunit/CRM/Upgrade/FormTest.php
Labels: master

#15095 [Test] [NFC] upgrade remaining export tests
  CRM/Export/BAO/Export.php
  tests/phpunit/CRM/Export/BAO/ExportTest.php
Labels: master

#15064 CRM-17182 Fix Search on fee_level_id and ensure that participant.fee_amount isn't updated when label changes
  CRM/Event/BAO/Query.php
  CRM/Price/BAO/PriceFieldValue.php
  CRM/Price/Form/Option.php
  tests/phpunit/CRM/Event/Form/SearchTest.php
  tests/phpunit/api/v3/ParticipantTest.php
Labels: master

#15106 5.17.0 release notes: first pass at sorting and annotating
  contributor-key.yml
  release-notes/5.17.0.md
Labels: 5.17

#15110 Bump version to 5.16.3 and add in release notes
  CRM/Upgrade/Incremental/sql/5.16.3.mysql.tpl
  release-notes.md
  release-notes/5.16.3.md
  sql/civicrm_generated.mysql
  xml/version.xml
Labels: 5.16

#15104 Add `pre` and `post` hooks to Domain create and edit operations
  CRM/Core/BAO/Domain.php
Labels: master

#15105 dev/financial#66 - Fix missing contribution ID for AdditionalInfo
  templates/CRM/Contribute/Form/Contribution.tpl
Labels: 5.17, merge ready

#15108 dev/financial#66 - Fix missing contribution ID for AdditionalInfo
  templates/CRM/Contribute/Form/Contribution.tpl
Labels: 5.16

#15111 Add in release notes for 5.16.3 drop
  release-notes.md
  release-notes/5.16.3.md
Labels: 5.17

#15109 5.17
  contributor-key.yml
  release-notes.md
  release-notes/5.16.3.md
  release-notes/5.17.0.md
  templates/CRM/Contribute/Form/Contribution.tpl
Labels: master
