Repository civicrm/civicrm-core, pull requests merged in 2019-09, with the labels that each got.

#15179 Extend loadSavedMapping to check defaults
  CRM/Contact/Import/Form/MapField.php
  tests/phpunit/CRM/Contact/Import/Form/MapFieldTest.php
Labels: master

#15180 Update Pledge XML to support date picker conversion
  CRM/Pledge/BAO/Query.php
  CRM/Pledge/DAO/Pledge.php
  tests/phpunit/CRM/Export/BAO/ExportTest.php
  xml/schema/Pledge/Pledge.xml
  xml/schema/Pledge/PledgePayment.xml
Labels: master, merge on pass

#15170 Convert pledge date fields to use datepicker rather than jcalendar
  CRM/Contact/BAO/Query.php
  CRM/Pledge/BAO/Query.php
  CRM/Pledge/DAO/PledgePayment.php
  CRM/Pledge/Form/Search.php
  CRM/Upgrade/Incremental/php/FiveEighteen.php
  templates/CRM/Pledge/Form/Search/Common.tpl
  xml/schema/Pledge/PledgePayment.xml
Labels: master, merge on pass

#15183 [REF] Import - minor cleanup - generate js on the processor class
  CRM/Contact/Import/Form/MapField.php
  CRM/Import/ImportProcessor.php
Labels: has-test, master

#15182 dev/core#1046 - allow for the real "name" to be specified in xml
  CRM/Case/XMLProcessor/Process.php
  tests/phpunit/CRM/Case/XMLProcessor/ProcessTest.php
Labels: master

#15186 Update XML files for membership fields to support date picker conversion
  CRM/Member/BAO/Query.php
  CRM/Member/DAO/Membership.php
  CRM/Member/Selector/Search.php
  CRM/Upgrade/Incremental/php/FiveEighteen.php
  sql/civicrm_generated.mysql
  tests/phpunit/CRM/Core/BAO/UFFieldTest.php
  tests/phpunit/CRM/Export/BAO/ExportTest.php
  tests/phpunit/CRM/Member/Selector/SearchTest.php
  tests/phpunit/api/v3/UtilsTest.php
  xml/schema/Member/Membership.xml
  xml/templates/civicrm_data.tpl
Labels: master, merge on pass

#15192 dev/core#1046 - simplify logic
  CRM/Case/XMLProcessor/Process.php
Labels: master

#15191 Use metadata for pledgeDateRange fields
  CRM/Contact/BAO/Query.php
  CRM/Pledge/BAO/Query.php
Labels: master

#15160 Fix inconsistencies in duplicate retrieval
  CRM/Core/BAO/PrevNextCache.php
  CRM/Dedupe/Finder.php
  tests/phpunit/CRM/Dedupe/MergerTest.php
Labels: master

#15185 Incorporate searchLimit in dedupe cacheKey
  CRM/Contact/Form/Merge.php
  CRM/Contact/Page/AJAX.php
  CRM/Contact/Page/DedupeFind.php
  CRM/Contact/Page/DedupeMerge.php
  CRM/Core/BAO/PrevNextCache.php
  CRM/Dedupe/Merger.php
  api/v3/Dedupe.php
  api/v3/Job.php
  tests/phpunit/CRM/Dedupe/MergerTest.php
Labels: master, sig:bug

#15177 [Date picker][REF] Convert jcalendar date fields to date picker on me…
  CRM/Batch/Form/Entry.php
  CRM/Contact/BAO/Query.php
  CRM/Member/BAO/Query.php
  CRM/Member/Form/Search.php
  CRM/Member/Form/Task/Batch.php
  CRM/Member/Selector/Search.php
  CRM/Report/Form/Member/ContributionDetail.php
  CRM/Report/Form/Member/Detail.php
  CRM/Report/Form/Member/Summary.php
  CRM/Report/Form/Membership/Summary.php
  CRM/Upgrade/Incremental/SmartGroups.php
  CRM/Upgrade/Incremental/php/FiveEighteen.php
  templates/CRM/Member/Form/Search/Common.tpl
  templates/CRM/Member/Form/Selector.tpl
  tests/phpunit/CRM/Batch/Form/EntryTest.php
  tests/phpunit/CRM/Upgrade/Incremental/BaseTest.php
Labels: master, merge on pass, sig-markup

#15194 Fix failure to save relative dates on legacy fields
  CRM/Contact/BAO/SavedSearch.php
  tests/phpunit/api/v3/EventTest.php
Labels: 5.17, merge on pass, sig:bug

#15197 [NFC] comment fixes
  CRM/Event/BAO/Event.php
  api/v3/Event.php
Labels: 5.17

#15199 5.17 to master
  CRM/Contact/BAO/SavedSearch.php
  CRM/Event/BAO/Event.php
  api/v3/Event.php
  tests/phpunit/api/v3/EventTest.php
Labels: master

#15201 (dev/core#1226) Fix regression where new groups created on 5.16 with relative dates save 'fixed dates'
  CRM/Contact/BAO/SavedSearch.php
  tests/phpunit/CRM/Contact/BAO/SavedSearchTest.php
  tests/phpunit/api/v3/EventTest.php
Labels: 5.16, merge on pass

#15200 Re-remove pledge & member fields from the legacy date list
  CRM/Contact/BAO/SavedSearch.php
Labels: master, merge on pass

#15202 Set version 5.16.4. Add release notes.
  CRM/Upgrade/Incremental/sql/5.16.4.mysql.tpl
  release-notes.md
  release-notes/5.16.4.md
  sql/civicrm_generated.mysql
  xml/version.xml
Labels: 5.16

#15198 Ensure all report templates switch the filter field_name from join_da…
  CRM/Upgrade/Incremental/php/FiveEighteen.php
Labels: master

#15196 dev/core#1230 [Dedupe] Add new api option to getduplicates, permitting a new search to be forced.
  CRM/Dedupe/Merger.php
  api/v3/Dedupe.php
Labels: master

#15204 Added field title for Cache table
  CRM/Core/DAO/Cache.php
  xml/schema/Core/Cache.xml
Labels: master

#15156 Replace some calls to CRM_Core_Error::fatal with exceptions
  CRM/Dedupe/Finder.php
Labels: master

#15205 Set contact communication_style_id as importable
  CRM/Contact/DAO/Contact.php
  tests/phpunit/CRM/Dedupe/BAO/RuleGroupTest.php
  xml/schema/Contact/Contact.xml
Labels: master, merge on pass

#15193 Changed ClassName for ACL cache
  CRM/ACL/BAO/Cache.php
  CRM/ACL/DAO/ACLCache.php
  CRM/Core/DAO/AllCoreTables.data.php
  xml/schema/ACL/Cache.xml
Labels: master

#15165 SMTP help text and URL are misleading to Organization Address and Contact Info instead of leading to From Email Addresses; see also #14055 and #14329
  CRM/Admin/Form/Setting/Smtp.php
Labels: master

#15203 Add index to civicrm_contact.created_date & modified_date
  CRM/Contact/DAO/Contact.php
  xml/schema/Contact/Contact.xml
Labels: master, merge on pass

#15207 [NFC] Bring up 5.16.4 release notes into 5.17
  release-notes.md
  release-notes/5.16.4.md
Labels: 5.17, merge on pass

#15208 5.17 to master
  release-notes.md
  release-notes/5.16.4.md
Labels: master

#15209 (dev/core#1065) Grant in Edit mode doesn't show the associated contact
  CRM/Grant/Form/Grant.php
  templates/CRM/Grant/Form/Grant.tpl
Labels: master

#15211 Add ts() to deceased string
  CRM/Contact/Form/Contact.php
  CRM/Contact/Page/View.php
Labels: master

#15189 [Import][ref] Minor code improvement - move setDefaults to processor
  CRM/Contact/Import/Form/MapField.php
  CRM/Import/ImportProcessor.php
Labels: master, sig:code maintenance readability testability

#15213 5.17.0 release notes: late changes and tidy-up
  release-notes.md
  release-notes/5.17.0.md
Labels: 5.17

#15214 5.17
  release-notes.md
  release-notes/5.17.0.md
Labels: master

#15212 Fix search for case tags that are part of tag sets
  CRM/Case/BAO/Query.php
Labels: master, merge on pass

#14621 Use api to create activity and removed hardcoded status id
  CRM/Financial/BAO/ExportFormat.php
Labels: master, merge on pass

#15215 [Ref] Import use process for relationship defaults, add test
  CRM/Contact/Import/Form/MapField.php
  CRM/Import/ImportProcessor.php
  tests/phpunit/CRM/Contact/Import/Form/MapFieldTest.php
Labels: master, merge on pass

#15053 dev/membership#13 Add handling for missing MembershipPayment record.
  CRM/Contribute/BAO/Contribution.php
  CRM/Core/Payment/PayPalIPN.php
  api/v3/Contribution.php
  tests/phpunit/CRM/Core/Payment/PayPalIPNTest.php
Labels: master, merge on pass

#15181 [Datepicker][REF] Convert mailing date field on mailing search screen…
  CRM/Mailing/Form/Search.php
  CRM/Mailing/Selector/Browse.php
  templates/CRM/Mailing/Form/Search.tpl
Labels: master, merge on pass

#15216 dev/core#938 - remove duplicate lines
  tests/phpunit/api/v3/AttachmentTest.php
Labels: master, merge on pass

#15218 [REF] Move calculation of js for import fields WITH relationship keys to processor.
  CRM/Contact/Import/Form/MapField.php
  CRM/Import/ImportProcessor.php
Labels: master

#15118 Fix export header for 'Contact ID'
  CRM/Export/BAO/ExportProcessor.php
  tests/phpunit/CRM/Export/BAO/ExportTest.php
Labels: master

#15217 [TEST] Enable apiv4 testing for GroupNesting and GroupOrganization entities
  tests/phpunit/api/v3/GroupNestingTest.php
  tests/phpunit/api/v3/GroupOrganizationTest.php
Labels: master

#15102 Fix an HTML error in Calculate.tpl
  templates/CRM/Price/Form/Calculate.tpl
Labels: easy-review, master

#15159 (dev/joomla#10) Remove Joomla-specific error display and use native CiviCRM
  CRM/Core/Error.php
  CRM/Utils/System/Joomla.php
  templates/CRM/common/fatal.tpl
Labels: master

#15190 dev/core#1187 Fix bug where import will not do 2 phone types of the same location
  CRM/Contact/Import/Parser.php
  CRM/Import/ImportProcessor.php
  tests/phpunit/CRM/Contact/Import/Parser/ContactTest.php
Labels: has-test, master, sig:bug

#15115 Fix fatal when saving import mapping with a relationship but 'Primary' location type
  CRM/Contact/Import/Form/MapField.php
Labels: easy-review, master, sig:bug

#15222 Fixes inconsitency between constituency summary and constituency detail
  templates/CRM/Report/Form/Contact/Detail.tpl
Labels: master

#15188 dev/core#1230 Dedupe permissions - allow safe mode merging based on 'merge duplicate contacts'
  CRM/Core/Permission.php
  CRM/Dedupe/Merger.php
  tests/phpunit/api/v3/JobTest.php
Labels: master, sig:permission nuancing

#15187 dev/core#1230 Loosen permissions to Dedupe.getstatistics api
  CRM/Core/Permission.php
Labels: master, sig:permission nuancing

#15219 [Ref] [Import] more code cleanup
  CRM/Contact/Import/Form/MapField.php
Labels: master

#15117 [REF] extract send receipt in MembershipRenewal fn
  CRM/Member/Form/MembershipRenewal.php
Labels: master

#15147 dev/core#1123 - Changing the label for Inbound Email bypasses edit permission
  CRM/Activity/BAO/ActivityType.php
  CRM/Activity/Form/Activity.php
  templates/CRM/Activity/Form/Activity.tpl
  tests/phpunit/CRM/Activity/BAO/ActivityTypeTest.php
  tests/phpunit/CRM/Activity/Form/ActivityTest.php
Labels: master

#15220 [Import] [REF] code cleanup & test on the code to 'guess the intended field from the column name'
  CRM/Contact/Import/Form/MapField.php
  CRM/Contact/Import/Parser.php
  tests/phpunit/CRM/Contact/Import/Form/MapFieldTest.php
Labels: master, merge on pass

#15137 (dev/joomla#24) Stop CiviCRM's joomla.css from modifying Joomla 4 header background colour
  css/joomla.css
Labels: master

#15154 dev/core#1230 [Dedupe] Do not geocode while merging, rely on existing values
  CRM/Dedupe/Merger.php
Labels: master

#15224 Use metadata for dataPatterns
  CRM/Contact/Import/Form/MapField.php
  CRM/Contact/Import/Parser.php
  tests/phpunit/CRM/Contact/Import/Form/MapFieldTest.php
Labels: master

#15171 dev/core#1222 Clear static DAO cache when writing to DAO
  CRM/Core/DAO.php
Labels: master, merge on pass

#15143 Stop adding a refund payment from creating extraneous financial items
  CRM/Financial/BAO/Payment.php
  tests/phpunit/api/v3/PaymentTest.php
Labels: master, merge on pass

#15226 [Ref] [Import] Final round in the cleanup Load Mapping form epic
  CRM/Contact/Import/Form/MapField.php
  CRM/Import/ImportProcessor.php
  tests/phpunit/CRM/Contact/Import/Form/MapFieldTest.php
Labels: master, merge on pass

#15227 dev/core#1230 Permission nuancing, fix another place where merge duplicate contacts should be enough
  CRM/Core/Permission.php
Labels: master, merge on pass

#15230 CRM-21677 - report clean up
  CRM/Report/Form/Contribute/Bookkeeping.php
Labels: master

#15210 Add unique name to mailing_job.start_date
  CRM/Mailing/DAO/MailingJob.php
  xml/schema/Mailing/MailingJob.xml
Labels: master, merge ready

#15142 Prevent error on price set membership update
  CRM/Member/BAO/MembershipPayment.php
  CRM/Price/BAO/LineItem.php
  tests/phpunit/CRM/Member/BAO/MembershipTest.php
Labels: has-test, master, merge on pass

#15233 dev/core#1233 Fix deleting of campaigns and saving of custom data for campaign and …
  CRM/Campaign/Form/Campaign.php
  CRM/Utils/API/HTMLInputCoder.php
  tests/phpunit/CRM/Campaign/Form/CampaignTest.php
Labels: 5.18, merge on pass

#15234 SyntaxConformanceTest::testSqlOperators - Skip "Dedupe" entity on MySQL 5.5
  tests/phpunit/api/v3/SyntaxConformanceTest.php
Labels: 5.18

#15236 dev/core#1236 fix miscasting on setContactSubType
  CRM/Import/ImportProcessor.php
Labels: 5.18

#15238 (dev/core#1065) fix condition so that the contact field appears for s…
  CRM/Grant/Form/Grant.php
Labels: 5.18

#15237 5.18
  CRM/Campaign/Form/Campaign.php
  CRM/Grant/Form/Grant.php
  CRM/Import/ImportProcessor.php
  CRM/Utils/API/HTMLInputCoder.php
  tests/phpunit/CRM/Campaign/Form/CampaignTest.php
  tests/phpunit/api/v3/SyntaxConformanceTest.php
Labels: master

#15231 Updated entityRefFilters hook to support alter form create links
  CRM/Core/Resources.php
  CRM/Utils/Hook.php
  tests/phpunit/CRM/Core/ResourcesTest.php
Labels: master

#15240 dev/core#1123 - avoid possible variable name clash
  CRM/Activity/Form/Activity.php
  templates/CRM/Activity/Form/Activity.tpl
  tests/phpunit/CRM/Activity/Form/ActivityTest.php
Labels: 5.18

#15178 Fix php 7.2+ deprecation error
  bin/cli.class.php
Labels: master

#15239 dev/core#1190 - typo in original version of upgrade function
  CRM/Upgrade/Incremental/php/FiveSeventeen.php
Labels: 5.18

#15241 5.18 to master
  CRM/Activity/Form/Activity.php
  CRM/Upgrade/Incremental/php/FiveSeventeen.php
  templates/CRM/Activity/Form/Activity.tpl
  tests/phpunit/CRM/Activity/Form/ActivityTest.php
Labels: master

#15243 Declare metadata for component payment fields on export
  CRM/Export/BAO/ExportProcessor.php
  tests/phpunit/CRM/Export/BAO/ExportTest.php
Labels: master

#15242 5.17 port of https://github.com/civicrm/civicrm-core/pull/15239
  CRM/Upgrade/Incremental/php/FiveSeventeen.php
Labels: 5.17

#15245 dev/core#1240 Ensure that Options are not duplicated when saving a co…
  CRM/Price/BAO/PriceField.php
  tests/phpunit/CRM/Price/BAO/PriceFieldTest.php
Labels: 5.18, has-test

#15247 [NFC] Update Default report instances that filter on join date to be …
  CRM/Report/Form/Member/Summary.php
  sql/civicrm_generated.mysql
  xml/templates/civicrm_navigation.tpl
Labels: 5.18

#15249 5.18 to master
  CRM/Price/BAO/PriceField.php
  CRM/Report/Form/Member/Summary.php
  sql/civicrm_generated.mysql
  tests/phpunit/CRM/Price/BAO/PriceFieldTest.php
  xml/templates/civicrm_navigation.tpl
Labels: master

#15246 5.17 bump version and add in release notes
  CRM/Upgrade/Incremental/sql/5.17.1.mysql.tpl
  release-notes.md
  release-notes/5.17.1.md
  sql/civicrm_generated.mysql
  xml/version.xml
Labels: 5.17, merge on pass

#15250 [NFC] array formatting:
  CRM/Contact/BAO/Contact.php
  CRM/Contact/BAO/Individual.php
Labels: master, merge on pass

#15251 CRM-21677 - report clean up for participant reports
  CRM/Report/Form/Event/ParticipantListCount.php
  CRM/Report/Form/Event/ParticipantListing.php
Labels: master

#15244 dev/core#1233 Fix deleting of campaigns and saving of custom data for campaign and …
  CRM/Campaign/Form/Campaign.php
  CRM/Utils/API/HTMLInputCoder.php
  tests/phpunit/CRM/Campaign/Form/CampaignTest.php
Labels: 5.17

#15132 (dev/joomla#22) Fix deprecated JRequest for Joomla 4.0
  CRM/Utils/System/Joomla.php
Labels: master

#15253 Add in 5.17.1 Release notes and migrate .tpl file for 5.17.1 to 5.18 to support upgrade
  CRM/Upgrade/Incremental/sql/5.17.1.mysql.tpl
  release-notes.md
  release-notes/5.17.1.md
Labels: 5.18, merge on pass

#15255 dev/core#1244 Fix regression on searching by email in advanced search
  CRM/Contact/BAO/Query.php
  tests/phpunit/api/v3/ContactTest.php
Labels: 5.18

#15256 5.18
  CRM/Contact/BAO/Query.php
  CRM/Upgrade/Incremental/sql/5.17.1.mysql.tpl
  release-notes.md
  release-notes/5.17.1.md
  tests/phpunit/api/v3/ContactTest.php
Labels: master

#15257 dev/core#1244 Fix regression on searching by contact in advanced search
  CRM/Contact/BAO/Query.php
  tests/phpunit/api/v3/ContactTest.php
Labels: 5.17, merge on pass

#15258 Bump Version to 5.17.2 and add in release notes
  CRM/Upgrade/Incremental/sql/5.17.2.mysql.tpl
  release-notes.md
  release-notes/5.17.2.md
  sql/civicrm_generated.mysql
  xml/version.xml
Labels: 5.17

#15260 (NFC) 5 17 2 release notes
  release-notes.md
  release-notes/5.17.2.md
Labels: 5.18

#15261 Remove is_public flag from report paths
  CRM/Report/xml/Menu/Report.xml
Labels: 5.18, merge on pass

#15268 dev/drupal#52 Partial fix for Deprecated q variable
  CRM/Utils/System/DrupalBase.php
Labels: 5.18, merge on pass

#15274 (REF) Remove unused functions, setTemplateMenuValues() and getNavigation()
  CRM/Core/Block.php
  CRM/Core/Menu.php
Labels: master, merge on pass

#15273 Fix unreleased regression on batch merge through the UI
  CRM/Dedupe/Merger.php
Labels: 5.18, merge on pass

#15271 dev/drupal#52 Partial fix for Deprecated q variable
  CRM/Utils/System/DrupalBase.php
Labels: 5.17, merge on pass

#15269 Remove is_public flag from report paths
  CRM/Report/xml/Menu/Report.xml
Labels: 5.17, merge on pass

#15276 Ensure filtering on email via the api looks for an exact match
  api/v3/Contact.php
  tests/phpunit/api/v3/ContactTest.php
Labels: 5.18, merge on pass

#15275 Trim form values when adding LIKE operator
  CRM/Core/Form/Search.php
Labels: 5.18, merge on pass

#15270 5.18
  CRM/Core/Form/Search.php
  CRM/Dedupe/Merger.php
  CRM/Report/xml/Menu/Report.xml
  CRM/Utils/System/DrupalBase.php
  api/v3/Contact.php
  release-notes.md
  release-notes/5.17.2.md
  tests/phpunit/api/v3/ContactTest.php
Labels: master

#15277 Email search fixes
  CRM/Core/Form/Search.php
  api/v3/Contact.php
  tests/phpunit/api/v3/ContactTest.php
Labels: 5.17

#15278 Bump to 5.17.3. Add release notes.
  CRM/Upgrade/Incremental/sql/5.17.3.mysql.tpl
  release-notes.md
  release-notes/5.17.3.md
  sql/civicrm_generated.mysql
  xml/version.xml
Labels: 5.17

#15272 dev/financial#68 Ensure that check number is correctly passed through…
  CRM/Batch/Form/Entry.php
  tests/phpunit/CRM/Batch/Form/EntryTest.php
  tests/phpunit/api/v3/ContributionTest.php
Labels: master, merge on pass

#15263 financial#67 : Check number doesn't show up if payment method name - Check changed to Cheque
  templates/CRM/Contribute/Form/ContributionView.tpl
Labels: master

#15094 dev/core#792 Fix Contributions not recording if selected membership is none when using a membership priceset
  CRM/Contribute/Form/Contribution/Confirm.php
Labels: has-test, master

#15280 REF Make the formatParamsForPaymentProcessor function more generic so it can be used more
  CRM/Contribute/Form/Contribution/Confirm.php
  CRM/Core/Form.php
Labels: master, merge on pass

#15288 Add release notes for 5.17.3
  release-notes.md
  release-notes/5.17.3.md
Labels: 5.18

#15228 Unit test for #15094 fix
  CRM/Contribute/Form/Contribution/Confirm.php
  tests/phpunit/CRM/Contribute/Form/ContributionTest.php
Labels: has-test, master, merge on pass

#15282 Ensure Dashboard domain ID is set even when passed as a param
  CRM/Core/BAO/Dashboard.php
Labels: master

#15285 Add CRM_Utils_JS::encode function
  CRM/Utils/JS.php
  tests/phpunit/CRM/Utils/JSTest.php
Labels: master

#15287 Fix for core#1247 - export hook doesn't work
  CRM/Export/BAO/Export.php
  CRM/Export/BAO/ExportProcessor.php
Labels: 5.18

#15289 dev/core#1246 fix fatal error on search builder if a core contact type is disabled
  CRM/Core/BAO/Mapping.php
Labels: 5.18, merge on pass

#15284 dev/core#1246 fix fatal error on search builder if a core contact type is disabled
  CRM/Core/BAO/Mapping.php
Labels: 5.17, merge on pass

#15290 5.18
  CRM/Core/BAO/Mapping.php
  CRM/Export/BAO/Export.php
  CRM/Export/BAO/ExportProcessor.php
  release-notes.md
  release-notes/5.17.3.md
Labels: master

#15303 Update CiviCRM contributors.txt
  CONTRIBUTORS.txt
  contributor-key.yml
Labels: master

#15308 [NFC] Reword event docs to clarify priority vs weight
  Civi/API/Events.php
Labels: master

#15295 CRM_Utils_JS - Improve encode handling of strings
  CRM/Utils/JS.php
  tests/phpunit/CRM/Utils/JSTest.php
Labels: master

#15262 CRM-21677 - report clean up for contribution reports
  CRM/Report/Form/Contribute/History.php
  CRM/Report/Form/Contribute/SoftCredit.php
  CRM/Report/Form/Contribute/TopDonor.php
Labels: master

#15302 Stop passing exportMode, componentTable and ids by reference in export hook
  CRM/Export/BAO/ExportProcessor.php
  CRM/Utils/Hook.php
Labels: master

#15168 core#1225 fix Event Info and Contribution Page Settings templates
  templates/CRM/Contribute/Form/ContributionPage/Settings.tpl
  templates/CRM/Event/Form/ManageEvent/EventInfo.tpl
Labels: master, sig-markup

#15317 dev/core/1259 update config checklist contribution section
  CRM/Admin/Page/ConfigTaskList.php
  templates/CRM/Admin/Page/ConfigTaskList.tpl
Labels: master

#15319 dev/core#1262 - Fix case status order in case type settings page
  ang/crmCaseType.js
Labels: master

#15320 dev/core#1264 - Fix notice error on contribution page
  CRM/Contribute/BAO/Contribution.php
Labels: master

#15325 Mailing API - Expose option list for `header_id` and `footer_id`
  CRM/Mailing/DAO/Mailing.php
  tests/phpunit/api/v3/MailingTest.php
  xml/schema/Mailing/Mailing.xml
Labels: master

#15331 Api3TestTrait - Only run api4 tests if api4 is present
  Civi/Test/Api3TestTrait.php
Labels: master, merge on pass

#15332 5.18.0 release notes initial run
  release-notes.md
  release-notes/5.18.0.md
Labels: 5.18

#15333 5.18
  release-notes.md
  release-notes/5.18.0.md
Labels: master

#15343 Upgrader: handle missing obsolete extensions
  CRM/Upgrade/Form.php
Labels: master

#15342 Update spelling of htmlpurifier to be correct spelling
  CRM/Core/ClassLoader.php
Labels: master, merge on pass

#15313 CRM-21677 - report clean up for employer report
  CRM/Report/Form/Contact/CurrentEmployer.php
Labels: master

#15337 Sorting and Annotating Release notes for 5.18
  contributor-key.yml
  release-notes/5.18.0.md
Labels: 5.18

#15334 dev/membership/#16 Fix duplicate lineitems when creating a recurring membership via backend
  CRM/Member/BAO/Membership.php
Labels: 5.18

#15348 5.18
  CRM/Member/BAO/Membership.php
  contributor-key.yml
  release-notes/5.18.0.md
Labels: master

#15346 dev/core#1272 - PHP 7.3 warning message on import contribution
  CRM/Contribute/Import/Parser/Contribution.php
Labels: master

#15350 Ensure that price_field_value rows aren't duplicated when editing pri…
  CRM/Price/BAO/PriceField.php
Labels: 5.18

#15354 Fix membership/issues#16 Duplicate lineitems when creating a recurrin…
  CRM/Member/BAO/Membership.php
Labels: 5.17

#15351 5.18
  CRM/Price/BAO/PriceField.php
Labels: master

#15355 Bump up to 5.17.5
  CRM/Upgrade/Incremental/sql/5.17.5.mysql.tpl
  release-notes.md
  release-notes/5.17.5.md
  sql/civicrm_generated.mysql
  xml/version.xml
Labels: 5.17

#15356 release-notes - Add 5.17.5
  release-notes.md
  release-notes/5.17.5.md
Labels: 5.18

#15357 5.18
  release-notes.md
  release-notes/5.17.5.md
Labels: master

#15335 Add getdisplayvalue api with unit test.
  api/v3/CustomValue.php
  tests/phpunit/api/v3/CustomValueTest.php
Labels: master

#15305 CRM-21777 - Set readonly for the smtp fields initialised in civicrm_s…
  CRM/Admin/Form/Setting/Smtp.php
Labels: master

#15360 [REF] Fix path to htmlpurifier in IDS file
  CRM/Core/IDS.php
Labels: master
