Repository civicrm/civicrm-core, pull requests merged in 2019-11, with the labels that each got.

#15677 Add in upgrade step for upgrading Event date and Relationship Active Date smart groups
  CRM/Upgrade/Incremental/SmartGroups.php
  CRM/Upgrade/Incremental/php/FiveTwenty.php
  tests/phpunit/CRM/Upgrade/Incremental/BaseTest.php
Labels: master, merge on pass

#15681 [NFC] define variable type
  api/v3/ReportTemplate.php
Labels: master

#15683 [NFC] test cleanup
  tests/phpunit/CRM/Financial/BAO/FinancialAccountTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/api/v3/OrderTest.php
  tests/phpunit/api/v3/PaymentTest.php
Labels: master, merge on pass

#15638 dev/core#1282 unit test for bug
  CRM/Core/BAO/CustomField.php
  CRM/Core/BAO/UFGroup.php
  api/v3/Profile.php
  tests/phpunit/api/v3/ProfileTest.php
Labels: master

#15682 dev/core#1344 Re-work if statements and remove excess ifs
  xml/templates/message_templates/contribution_online_receipt_text.tpl
  xml/templates/message_templates/membership_online_receipt_text.tpl
Labels: master, merge on pass

#15690 [NFC] Fix AuthorizeNet Test failure due to credit card being expired
  tests/phpunit/CRM/Core/Payment/AuthorizeNetTest.php
Labels: 5.19, merge on pass

#15691 5.19
  tests/phpunit/CRM/Core/Payment/AuthorizeNetTest.php
Labels: master

#15688 Fix BillingName to be assigned in email receipts IF available
  CRM/Contribute/BAO/Contribution.php
  api/v3/PaymentProcessor.php
  tests/phpunit/api/v3/ContributionTest.php
Labels: master, merge on pass

#15679 dev/event#19 remove obsolete scriptFee & scriptArray
  CRM/Event/Form/Registration/AdditionalParticipant.php
  CRM/Event/Form/Registration/Register.php
  tests/phpunit/CRM/Event/Form/Registration/ConfirmTest.php
Labels: master

#15592 [REF] Refactor ACL Contact Cache generation to be more efficient
  CRM/Contact/BAO/Contact/Permission.php
Labels: master

#15588 [REF] Refactor Smart Group Cache population code to be less intensive
  CRM/Contact/BAO/GroupContactCache.php
Labels: master

#15651 dev/core#1344 Fix logic for displaying BillingName and Credit Card De…
  tests/phpunit/api/v3/ContributionTest.php
  xml/templates/message_templates/contribution_online_receipt_html.tpl
Labels: master, merge on pass

#15641 [REF] Move calls to CRM_Core_BAO_FinancialTrxn::createDeferredTrxn back to the calling functions.
  CRM/Contribute/BAO/Contribution.php
Labels: master

#15632 Partial conversion of Payment form to use the EntityFormTrait & add title
  CRM/Admin/Form/PaymentProcessor.php
  CRM/Financial/DAO/PaymentProcessor.php
  templates/CRM/Admin/Form/PaymentProcessor.tpl
  xml/schema/Financial/PaymentProcessor.xml
Labels: master

#15687 Cleanup date handling on Payment.create
  CRM/Contribute/Form/AdditionalPayment.php
  CRM/Financial/BAO/Payment.php
  api/v3/Payment.php
  tests/phpunit/CRM/Contribute/Form/AdditionalPaymentTest.php
Labels: master

#15617 dev/financial#2 Support payment processor title if configured on Contribution & Event Pages
  CRM/Contribute/Form/Contribution/Confirm.php
  CRM/Contribute/Form/Contribution/Main.php
  CRM/Contribute/Form/ContributionBase.php
  CRM/Event/Form/Registration.php
  CRM/Event/Form/Registration/Confirm.php
  CRM/Event/Form/Registration/Register.php
  CRM/Event/Form/Registration/ThankYou.php
  CRM/Financial/Form/FrontEndPaymentFormTrait.php
  tests/phpunit/CRM/Contribute/Form/ContributionTest.php
  tests/phpunit/api/v3/ContributionPageTest.php
Labels: master

#15698 Fix loading of profile fields on additional participant form
  CRM/Event/Form/Registration/AdditionalParticipant.php
Labels: master

#15685 [NFC] Test class preliminary clean up
  tests/phpunit/api/v3/PaymentTest.php
Labels: master, merge on pass

#15415 dev/core#1297 If start/end date is empty, results are empty
  CRM/Contact/Form/Search/Custom/ContributionAggregate.php
Labels: master

#15704 Civi\Core\Container - Fix warning about Symfony 3=>4 and boot services
  Civi/Core/Container.php
Labels: master

#15693 Replace log_date with created_date & modified_date in advanced search
  CRM/Contact/BAO/Query.php
  CRM/Contact/BAO/SavedSearch.php
  CRM/Contact/Form/Search/Criteria.php
  CRM/Contact/Form/Task/SaveSearch.php
  templates/CRM/Contact/Form/Search/Criteria/ChangeLog.tpl
  tests/phpunit/CRM/Contact/BAO/QueryTest.php
  tests/phpunit/CRM/Contact/BAO/SavedSearchTest.php
Labels: master, merge on pass

#15702 dev/core#561 Add in Upgrade routine to convert log_date smart group s…
  CRM/Upgrade/Incremental/SmartGroups.php
  CRM/Upgrade/Incremental/php/FiveTwenty.php
  tests/phpunit/CRM/Upgrade/Incremental/BaseTest.php
Labels: master

#15711 Minor refactors to support converting custom fields to datepicker fields
  CRM/Contact/BAO/Query.php
Labels: master, merge on pass

#15712 Re-arrange change log advanced search panel so both modified fields a…
  templates/CRM/Contact/Form/Search/Criteria/ChangeLog.tpl
Labels: master, merge on pass

#15701 Add in method to allow extensions to opt out of using temporary table…
  CRM/Contact/BAO/Contact/Permission.php
Labels: master

#15571 Backdrop support for adding roles and perms
  tools/drupal/modules/civicrm_webtest/civicrm_webtest.install
Labels: master

#15713 [NFC] various code cleanup on CRM_Contact_BAO_Query
  CRM/Contact/BAO/Query.php
  CRM/Utils/Type.php
Labels: master, merge on pass

#15062 Agile fixFix inherited membership being deleted when there is still a valid … …relationship
  CRM/Contact/BAO/Contact.php
  CRM/Contact/BAO/Relationship.php
  tests/phpunit/CRM/Contact/BAO/RelationshipTest.php
  tests/phpunit/api/v3/MembershipTest.php
  tests/phpunit/api/v3/RelationshipTest.php
Labels: master

#15716 [NFC] Fix exception thrown to std CRM_Core_Exception
  CRM/Core/BAO/CustomField.php
Labels: master, merge on pass

#15717 [NFC] Allow users on backdrop to trigger regen.sh
  bin/setup.lib.sh
Labels: master, merge on pass

#15715 Add test to lock in obscure custom join handling
  tests/phpunit/CRM/Contact/BAO/QueryTest.php
  tests/phpunit/CRM/Core/BAO/CustomFieldTest.php
  tests/phpunit/CRM/Core/BAO/CustomQueryTest.php
  tests/phpunit/CRMTraits/Custom/CustomDataTrait.php
Labels: master

#15714 [REF] remove as a return Param of getHierContactDetails
  CRM/Contact/BAO/Contact.php
  CRM/Core/BAO/UFGroup.php
  CRM/Profile/Form.php
Labels: master

#15718 [REF] Remove early return on joinTable
  CRM/Core/BAO/CustomQuery.php
Labels: master

#15720 Test improvements
  tests/phpunit/CRM/Core/BAO/CustomQueryTest.php
Labels: master, merge on pass

#15721 Remove early return on joinTable
  CRM/Core/BAO/CustomQuery.php
Labels: master

#15723 Eliminate silly parameter
  CRM/Contact/BAO/Relationship.php
  CRM/Member/BAO/Membership.php
Labels: master

#15722 [REF] minor tidy ups on very nasty function
  CRM/Contact/BAO/Relationship.php
  tests/phpunit/CRM/Contact/BAO/RelationshipTest.php
Labels: master

#15724 dev/core#1360: Fix Programatic Installation Of Multiple Extensions on v5.19
  CRM/Logging/Schema.php
Labels: 5.19

#15719 Fix Custom field date query builder to work with 'raw' high & low params
  CRM/Contact/BAO/Query.php
  CRM/Core/BAO/CustomQuery.php
  tests/phpunit/CRM/Core/BAO/CustomFieldTest.php
  tests/phpunit/CRM/Core/BAO/CustomQueryTest.php
  tests/phpunit/CRMTraits/Custom/CustomDataTrait.php
Labels: master

#15727 5.19
  CRM/Logging/Schema.php
Labels: master

#15726 dev/core#1093: Fix Installation of Custom Fields with Option Values From XML
  CRM/Utils/Migrate/Import.php
Labels: 5.19

#15729 5.19 to master
  CRM/Utils/Migrate/Import.php
Labels: master

#14349 Convert case activity links to 'actionLinks'
  CRM/Activity/BAO/Activity.php
  CRM/Case/BAO/Case.php
  CRM/Case/Form/ActivityView.php
  CRM/Case/Selector/Search.php
  templates/CRM/Case/Form/ActivityView.tpl
  templates/CRM/common/formButtons.tpl
Labels: master, merge ready

#15710 dev/core#561 Add in routine to convert custom date fields in smart groups to datep…
  CRM/Upgrade/Incremental/SmartGroups.php
  CRM/Upgrade/Incremental/php/FiveTwenty.php
  tests/phpunit/CRM/Upgrade/Incremental/BaseTest.php
Labels: master, merge on pass

#15707 dev/financial#82 revert added setters
  CRM/Contribute/Form/CancelSubscription.php
  CRM/Core/Payment.php
  CRM/Core/Payment/PayPalImpl.php
  api/v3/PaymentProcessor.php
  tests/phpunit/api/v3/PaymentProcessorTest.php
Labels: master

#15728 [REF] minor code simplification
  CRM/Contact/BAO/Relationship.php
Labels: master, merge on pass

#15730 Add in xkerman/restricted-unserialize package
  composer.json
  composer.lock
Labels: master, merge on pass

#15732 composer.{json,lock} - Make the "tplaner/when" exception for old PHP reproducible
  composer.json
  composer.lock
Labels: master, merge on pass

#15640 Fix Payment.create bug whereby payment_processor_id is not being used for the to_account_id
  CRM/Contribute/BAO/Contribution.php
  CRM/Financial/BAO/Payment.php
  CRM/Financial/BAO/PaymentProcessor.php
  api/v3/Payment.php
  api/v3/PaymentProcessor.php
  tests/phpunit/api/v3/PaymentTest.php
Labels: master

#15684 Remove recordPayment function.
  CRM/Financial/BAO/Payment.php
Labels: master

#15736 (NFC) Remove windows-specific debugging code from 11 years ago
  CRM/Case/Audit/Audit.php
Labels: master, merge on pass

#15705 Fix Payment.create with a negative value to create the correct financial items
  CRM/Financial/BAO/Payment.php
  api/v3/Payment.php
  tests/phpunit/CRM/Contribute/Form/AdditionalPaymentTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/api/v3/PaymentTest.php
Labels: master

#15737 Php 7.3 fix - don't mis-use continue
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/api/v3/CustomValueTest.php
Labels: master, merge on pass

#15733 Schema changes for PaymentProcessor and PaymentProcessorType to suppo…
  CRM/Financial/DAO/PaymentProcessor.php
  CRM/Financial/DAO/PaymentProcessorType.php
  tests/phpunit/CRM/Financial/BAO/PaymentProcessorTypeTest.php
  xml/schema/Financial/PaymentProcessor.xml
  xml/schema/Financial/PaymentProcessorType.xml
Labels: master

#15735 dev/core#1367 - Incorrect line items recorded with contribution repea…
  CRM/Contribute/BAO/ContributionRecur.php
  tests/phpunit/api/v3/ContributionTest.php
Labels: master

#15556 Upgrade script for dev/core#1046
  CRM/Upgrade/Incremental/php/FiveTwenty.php
  tests/phpunit/CRM/Upgrade/Incremental/php/FiveTwentyTest.php
Labels: has-test, master

#15731 dev/core#1361 Fix bug where 2 memberships created for same relationship
  CRM/Contact/BAO/Relationship.php
  CRM/Member/Utils/RelationshipProcessor.php
  tests/phpunit/CRM/Contact/BAO/RelationshipTest.php
Labels: master

#15738 Fix the relationship direction in testSingleMembershipForTwoRelationships
  tests/phpunit/CRM/Contact/BAO/RelationshipTest.php
Labels: master, merge on pass

#15743 Fix test to be more valid
  tests/phpunit/CRM/Contribute/Form/ContributionTest.php
  tests/phpunit/api/v3/ContributionPageTest.php
Labels: master

#15741 (dev/core#1093) Fix regression during extension activation
  CRM/Utils/Migrate/Import.php
Labels: 5.19, merge on pass

#15746 5.19
  CRM/Utils/Migrate/Import.php
Labels: master

#15749 Additional fixes to workflow templates
  tests/phpunit/CRM/Contribute/Form/AdditionalPaymentTest.php
  tests/phpunit/api/v3/PaymentTest.php
  xml/templates/message_templates/case_activity_html.tpl
  xml/templates/message_templates/contribution_dupalert_html.tpl
  xml/templates/message_templates/contribution_offline_receipt_html.tpl
  xml/templates/message_templates/contribution_online_receipt_html.tpl
  xml/templates/message_templates/contribution_recurring_billing_html.tpl
  xml/templates/message_templates/contribution_recurring_cancelled_html.tpl
  xml/templates/message_templates/contribution_recurring_edit_html.tpl
  xml/templates/message_templates/contribution_recurring_notify_html.tpl
  xml/templates/message_templates/event_offline_receipt_html.tpl
  xml/templates/message_templates/event_offline_receipt_text.tpl
  xml/templates/message_templates/event_online_receipt_html.tpl
  xml/templates/message_templates/event_registration_receipt_html.tpl
  xml/templates/message_templates/friend_html.tpl
  xml/templates/message_templates/membership_autorenew_billing_html.tpl
  xml/templates/message_templates/membership_autorenew_cancelled_html.tpl
  xml/templates/message_templates/membership_offline_receipt_html.tpl
  xml/templates/message_templates/membership_online_receipt_html.tpl
  xml/templates/message_templates/participant_cancelled_html.tpl
  xml/templates/message_templates/participant_confirm_html.tpl
  xml/templates/message_templates/participant_expired_html.tpl
  xml/templates/message_templates/participant_transferred_html.tpl
  xml/templates/message_templates/payment_or_refund_notification_html.tpl
  xml/templates/message_templates/payment_or_refund_notification_text.tpl
  xml/templates/message_templates/pcp_notify_html.tpl
  xml/templates/message_templates/pcp_owner_notify_html.tpl
  xml/templates/message_templates/pcp_status_change_html.tpl
  xml/templates/message_templates/pcp_supporter_notify_html.tpl
  xml/templates/message_templates/pledge_acknowledge_html.tpl
  xml/templates/message_templates/pledge_reminder_html.tpl
  xml/templates/message_templates/test_preview_html.tpl
  xml/templates/message_templates/uf_notify_html.tpl
Labels: master, merge on pass

#15742 Additional fixes to workflow templates
  xml/templates/message_templates/case_activity_html.tpl
  xml/templates/message_templates/contribution_dupalert_html.tpl
  xml/templates/message_templates/contribution_offline_receipt_html.tpl
  xml/templates/message_templates/contribution_online_receipt_html.tpl
  xml/templates/message_templates/contribution_recurring_billing_html.tpl
  xml/templates/message_templates/contribution_recurring_cancelled_html.tpl
  xml/templates/message_templates/contribution_recurring_edit_html.tpl
  xml/templates/message_templates/contribution_recurring_notify_html.tpl
  xml/templates/message_templates/event_offline_receipt_html.tpl
  xml/templates/message_templates/event_offline_receipt_text.tpl
  xml/templates/message_templates/event_online_receipt_html.tpl
  xml/templates/message_templates/event_registration_receipt_html.tpl
  xml/templates/message_templates/friend_html.tpl
  xml/templates/message_templates/membership_autorenew_billing_html.tpl
  xml/templates/message_templates/membership_autorenew_cancelled_html.tpl
  xml/templates/message_templates/membership_offline_receipt_html.tpl
  xml/templates/message_templates/membership_online_receipt_html.tpl
  xml/templates/message_templates/participant_cancelled_html.tpl
  xml/templates/message_templates/participant_confirm_html.tpl
  xml/templates/message_templates/participant_expired_html.tpl
  xml/templates/message_templates/participant_transferred_html.tpl
  xml/templates/message_templates/payment_or_refund_notification_html.tpl
  xml/templates/message_templates/payment_or_refund_notification_text.tpl
  xml/templates/message_templates/pcp_notify_html.tpl
  xml/templates/message_templates/pcp_owner_notify_html.tpl
  xml/templates/message_templates/pcp_status_change_html.tpl
  xml/templates/message_templates/pcp_supporter_notify_html.tpl
  xml/templates/message_templates/pledge_acknowledge_html.tpl
  xml/templates/message_templates/pledge_reminder_html.tpl
  xml/templates/message_templates/test_preview_html.tpl
  xml/templates/message_templates/uf_notify_html.tpl
Labels: master, merge on pass

#15744 (dev/core#1065) Participant in Edit mode needs to be shown consistently
  CRM/Event/Form/Participant.php
  templates/CRM/Event/Form/Participant.tpl
Labels: master

#15750 [NFC] Cleanup on exceptions
  CRM/Core/Resources.php
  CRM/Core/Resources/Strings.php
  CRM/Member/Form/Membership.php
  tests/phpunit/CRM/Member/Form/MembershipTest.php
Labels: master, merge on pass

#15745 Update template upgrade list as per PR #15742
  CRM/Upgrade/Incremental/MessageTemplates.php
Labels: master, merge on pass

#15740 dev/financial#40 Fix for non-allocation of payment to fully reversed checkboxes option
  CRM/Financial/BAO/Payment.php
Labels: master

#15748 Provide precautionary handling for theoretical error scenario.
  CRM/Financial/BAO/Payment.php
  tests/phpunit/api/v3/ContributionTest.php
  tests/phpunit/api/v3/PaymentTest.php
Labels: master, merge on pass

#15751 changed wording to Total Fee & Total Paid
  tests/phpunit/CRM/Contribute/Form/AdditionalPaymentTest.php
  tests/phpunit/api/v3/PaymentTest.php
  xml/templates/message_templates/payment_or_refund_notification_html.tpl
  xml/templates/message_templates/payment_or_refund_notification_text.tpl
Labels: master, merge on pass

#15752 5.19.0 release notes: added late changes
  release-notes/5.19.0.md
Labels: 5.19

#15754 5.19
  release-notes/5.19.0.md
Labels: master

#15739 Update dompdf (0.8.0=>0.8.3) & dependencies
  composer.lock
Labels: master

#15595 dev/core#1339 Dedupe screen check to carry across any data where the other contact has none by default.
  CRM/Contact/Form/Merge.php
  CRM/Dedupe/Merger.php
Labels: master

#15758 add contributor name
  CONTRIBUTORS.txt
Labels: master

#15762 dev/core#1371 Fix e-notice caused by trying to pass in known to the …
  api/v3/Extension.php
Labels: 5.20, merge on pass

#15248 reporting#19 - Performance improvements on report display/export
  CRM/Core/BAO/CustomField.php
  CRM/Report/Form.php
Labels: master

#15763 dev/core#1371 Fix e-notice caused by trying to pass in known info to …
  api/v3/Extension.php
Labels: 5.19, merge on pass

#15761 Fix cachekey string
  CRM/Contact/BAO/Contact.php
Labels: master, merge on pass

#15764 5.20
  api/v3/Extension.php
Labels: master

#15765 dev/core#1376 Catch Invalid Argument Exception when looking for APIv4…
  CRM/Api4/Services.php
Labels: 5.20

#15766 dev/core#1376 Catch Invalid Argument Exception when looking for APIv4…
  CRM/Api4/Services.php
Labels: 5.19

#15768 5.20 to master
  CRM/Api4/Services.php
Labels: master

#15666 modified shared address note under contact dashboard
  templates/CRM/Contact/Form/ShareAddress.tpl
Labels: master

#15769 Improve link title in shared address as per Mathieu
  templates/CRM/Contact/Form/ShareAddress.tpl
Labels: master, merge on pass

#15757 (dev/core#1065) Contribution in Edit mode needs to be shown consistently
  CRM/Contribute/Form/Contribution.php
  templates/CRM/Contribute/Form/Contribution.tpl
Labels: master

#15772 5.20.0 release notes initial run
  release-notes.md
  release-notes/5.20.0.md
Labels: 5.20

#15770 Swap some fatals on form & page classes for statusBounces
  CRM/Batch/Form/Entry.php
  CRM/Campaign/Form/Search.php
  CRM/Case/Form/Activity.php
  CRM/Case/Form/Case.php
  CRM/Contribute/Form/ContributionView.php
  CRM/Event/Cart/Page/AddToCart.php
  CRM/Event/Form/ManageEvent.php
  CRM/Event/Form/Participant.php
  CRM/Event/Page/EventInfo.php
  CRM/PCP/Form/PCP.php
  CRM/Profile/Form/Edit.php
Labels: master

#15774 Add in translation function around newly converted statusBounce messages
  CRM/Campaign/Form/Search.php
  CRM/Case/Form/Activity.php
Labels: master, merge on pass

#15776 [NFC] comment fixes - exceptions & don't declare NULL
  CRM/Core/Form/Search.php
Labels: master, merge on pass

#15775 Converts using deprecated fatal function for exception in CRM/Utils/Sys…
  CRM/Utils/Cache.php
  CRM/Utils/Request.php
  CRM/Utils/System/Backdrop.php
  CRM/Utils/System/Base.php
  CRM/Utils/System/Drupal.php
  CRM/Utils/System/Drupal6.php
  CRM/Utils/System/Joomla.php
  CRM/Utils/System/WordPress.php
Labels: master, merge on pass

#15773 5.20
  release-notes.md
  release-notes/5.20.0.md
Labels: master

#15779 dev/mailing#56 dev/mailing#57 Ensure that we don't pass in any namesp…
  CRM/Mailing/BAO/Mailing.php
Labels: 5.20, merge on pass

#15780 dev/mailing#56 dev/mailing#57 Ensure that we don't pass in any namesp…
  CRM/Mailing/BAO/Mailing.php
Labels: 5.19, merge on pass

#15777 [NFC] Reformat Contact_Form_Search_Advanced
  CRM/Contact/Form/Search/Advanced.php
Labels: master, merge on pass

#15782 Add in unit test for dev/mailing#56 and dev/mailing#57 and also fix i…
  CRM/Mailing/BAO/Mailing.php
  tests/phpunit/api/v3/JobProcessMailingTest.php
Labels: 5.20, merge on pass

#15781 dev/core#1374 Fix search formValue handling on contribution search
  CRM/Contact/Form/Search/Advanced.php
  CRM/Contribute/Form/Search.php
  CRM/Core/Form/Search.php
  tests/phpunit/CRM/Contact/BAO/SavedSearchTest.php
Labels: 5.20, merge on pass

#15784 5.20
  CRM/Contact/Form/Search/Advanced.php
  CRM/Contribute/Form/Search.php
  CRM/Core/Form/Search.php
  CRM/Mailing/BAO/Mailing.php
  tests/phpunit/CRM/Contact/BAO/SavedSearchTest.php
  tests/phpunit/api/v3/JobProcessMailingTest.php
Labels: master

#15786 Remove obsolete warning
  CRM/Contribute/BAO/Query.php
Labels: master, merge on pass

#15788 Bump version and add in release notes for a 5.19.1 drop
  CRM/Upgrade/Incremental/sql/5.19.1.mysql.tpl
  release-notes.md
  release-notes/5.19.1.md
  sql/civicrm_generated.mysql
  xml/version.xml
Labels: 5.19

#15783 [REF] replace copy & paste with shared getSortID function.
  CRM/Case/Form/Search.php
  CRM/Contribute/Form/Search.php
  CRM/Core/Form/Search.php
  CRM/Event/Form/Search.php
  CRM/Grant/Form/Search.php
  CRM/Member/Form/Search.php
  CRM/Pledge/Form/Search.php
Labels: master, merge on pass

#15789 5.19.1 Version Release Notes
  release-notes.md
  release-notes/5.19.1.md
Labels: 5.20, merge on pass

#15665 Create a GitLab general issue template
  .gitlab/issue_templates/improvement.md
  .gitlab/issue_templates/problem.md
Labels: master

#15787 Remove unhelpful alert from contribution search
  CRM/Contribute/BAO/Query.php
Labels: 5.20, merge on pass

#15790 5.20
  CRM/Contribute/BAO/Query.php
  release-notes.md
  release-notes/5.19.1.md
Labels: master

#15798 dev/core#183 Convert database testing to use CRM_Utils_SQL_TempTable …
  CRM/Contact/Import/Form/DataSource.php
  CRM/Contact/Import/ImportJob.php
  CRM/Contact/Import/Importer.php
  tests/phpunit/CRM/Import/DataSource/CsvTest.php
Labels: master, merge on pass

#15801 [NFC] reformat CiviUnitTestCase.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: master, merge on pass

#15795 dev/core#183 Convert creating of temp table in mailing test to use st…
  tests/phpunit/api/v3/MailingTest.php
Labels: master, merge on pass

#15804 dev/core#1381 fix fatal on case search (unreleased regression
  CRM/Core/Form/Search.php
Labels: 5.20

#15808 5.20
  CRM/Core/Form/Search.php
Labels: master

#15799 FinancialTrxnTest - Fix unit test to be 'legit'
  tests/phpunit/CRM/Core/BAO/FinancialTrxnTest.php
Labels: master

#15805 [REF] extract setDeprecatedDefaults
  CRM/Contribute/Form/Search.php
Labels: master, merge on pass

#15806 [REF] Add setSearchMetadata to each of the classes that extend CRM_Core_Form_Search
  CRM/Activity/Form/Search.php
  CRM/Event/Form/Search.php
  CRM/Grant/Form/Search.php
  CRM/Member/Form/Search.php
  CRM/Pledge/Form/Search.php
Labels: master, merge on pass

#15699 Don't pass \$input to completeOrder by reference - return values are never used
  CRM/Contribute/BAO/Contribution.php
Labels: master

#15809 [NFC] declare thrown exceptions
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/api/v3/ContributionPageTest.php
Labels: master

#15812 Convert fee selection test to use Order api
  tests/phpunit/CRM/Event/BAO/ChangeFeeSelectionTest.php
Labels: master, merge on pass

#15791 Fix Participant Search in force mode to support query parameters in URL
  CRM/Contact/Form/Search.php
Labels: master, merge on pass

#15803 Add unit test for searching by participant_status_id & switch to generic function
  CRM/Contact/BAO/Query.php
  CRM/Event/BAO/Query.php
  tests/phpunit/CRM/Event/BAO/QueryTest.php
Labels: master, merge on pass

#15822 Fix LabelFormat class to throw exceptions rather than fatals
  CRM/Core/BAO/LabelFormat.php
Labels: master, merge on pass

#15823 dev/core#183 Convert creating of temporary tables in CRM/Mailing file…
  CRM/Mailing/BAO/Mailing.php
  CRM/Mailing/BAO/Recipients.php
  CRM/Mailing/Event/BAO/Delivered.php
Labels: master

#15832 [NFC] minimal test for Mailing.update_email_resetdate
  CRM/Core/DAO.php
  CRM/Mailing/Event/BAO/Delivered.php
  Civi/Test/DbTestTrait.php
  tests/phpunit/api/v3/MailingTest.php
Labels: master, merge on pass

#15756 [REF] very minor tidy up
  CRM/Dedupe/Merger.php
Labels: master

#15835 [NFC] Remove unused variable not used since v4.4
  CRM/Case/Form/CaseView.php
Labels: master, merge on pass

#15833 (dev/core#1065) Contact missing in membership renewal form
  CRM/Member/Form/MembershipRenewal.php
  templates/CRM/Member/Form/MembershipRenewal.tpl
Labels: master

#15771 dev/financial#100 Remove 'partially paid' as a contribution status option for 'record p…ayment'
  CRM/Contribute/BAO/Contribution/Utils.php
  tests/phpunit/CRM/Member/Form/MembershipTest.php
Labels: master, merge ready

#15839 CiviCase - Make static function `allActivityTypes()` static
  CRM/Case/XMLProcessor.php
Labels: master

#15649 core#1346: Tagsets should display vertically in activity/new case forms
  templates/CRM/Activity/Form/Activity.tpl
  templates/CRM/Case/Form/Case.tpl
  templates/CRM/common/Tagset.tpl
Labels: master, sig-markup

#15825 dev/core#183 Convert Logging report summary report to using CRM_Utils…
  CRM/Logging/ReportSummary.php
Labels: master

#15838 [REF] XMLProcessor/Report - Extract method to make it more testable
  CRM/Case/XMLProcessor/Report.php
Labels: master, merge on pass

#15844 marketing/civicrm-website#163 Mitigate potential upgrade errors on missing msg_templates
  CRM/Upgrade/Incremental/MessageTemplates.php
Labels: 5.20

#15850 5.20 to master
  CRM/Upgrade/Incremental/MessageTemplates.php
Labels: master

#15810 [REF] calculate 'amount' on ContributionPage in a shared way in one scenario
  CRM/Contribute/Form/Contribution/Confirm.php
  CRM/Contribute/Form/Contribution/Main.php
  CRM/Contribute/Form/ContributionBase.php
  tests/phpunit/api/v3/ContributionPageTest.php
Labels: master

#15830 [REF] refactor on nasty Dedupe function
  CRM/Dedupe/MergeHandler.php
  CRM/Dedupe/Merger.php
Labels: master

#15851 [NFC] dev/core#1352 - Add comments why there's two custom blocks on new case form
  templates/CRM/Case/Form/Case.tpl
Labels: master, merge on pass

#15813 Fix CRM/Event/BAO/AdditionalPaymentTest.php to use Order.create
  CRM/Price/BAO/LineItem.php
  tests/phpunit/CRM/Contribute/Form/ContributionTest.php
  tests/phpunit/CRM/Event/BAO/AdditionalPaymentTest.php
  tests/phpunit/CRM/Event/BAO/ChangeFeeSelectionTest.php
Labels: master

#15828 [REF] minor refactor - move handling of 'skipMerge' to the skipMerge function
  CRM/Dedupe/Merger.php
Labels: master

#15858 translate strings
  CRM/Extension/Downloader.php
  CRM/Extension/Manager/Payment.php
  CRM/Extension/Manager/Report.php
  CRM/Extension/Manager/Search.php
Labels: master

#15852 Add $params type declaration to global API functions.
  api/api.php
  tests/phpunit/api/v3/ContributionTest.php
  tests/phpunit/api/v3/CustomFieldTest.php
  tests/phpunit/api/v3/CustomGroupTest.php
  tests/phpunit/api/v3/EventTest.php
  tests/phpunit/api/v3/GroupOrganizationTest.php
  tests/phpunit/api/v3/JobProcessMailingTest.php
  tests/phpunit/api/v3/MailingContactTest.php
  tests/phpunit/api/v3/MembershipPaymentTest.php
  tests/phpunit/api/v3/MembershipTest.php
  tests/phpunit/api/v3/ParticipantPaymentTest.php
  tests/phpunit/api/v3/ParticipantTest.php
  tests/phpunit/api/v3/PaymentProcessorTypeTest.php
  tests/phpunit/api/v3/RelationshipTypeTest.php
  tests/phpunit/api/v3/SyntaxConformanceTest.php
  tests/phpunit/api/v3/UFJoinTest.php
  tests/phpunit/api/v3/UFMatchTest.php
Labels: master, merge on pass

#15840 dev/core#1065 Change verbiage in accordance with context
  CRM/Member/Form/Membership.php
  CRM/Member/Form/MembershipRenewal.php
  CRM/Pledge/Form/Pledge.php
Labels: master

#15837 (NFC) PULL_REQUEST_TEMPLATE.md - Improve suggestions for under-the-hood/non-UI changes
  .github/PULL_REQUEST_TEMPLATE.md
Labels: master

#15794 Implement drupal_get_user_timezone()
  CRM/Utils/System/Drupal8.php
Labels: master

#15818 Field metadata cleanup: Contact & Activity & Custom
  CRM/Activity/BAO/Activity.php
  CRM/Activity/DAO/Activity.php
  CRM/Contact/DAO/Contact.php
  Civi/Api4/Generic/DAOGetFieldsAction.php
  Civi/Api4/Service/Spec/FieldSpec.php
  Civi/Api4/Service/Spec/SpecFormatter.php
  Civi/Api4/Service/Spec/SpecGatherer.php
  xml/schema/Activity/Activity.xml
  xml/schema/Contact/Contact.xml
Labels: master, merge ready

#15848 Improve datePicker placeholder/icons
  css/civicrm.css
  js/crm.datepicker.js
Labels: master, merge on pass

#13232 (dev/core#574) Prevent memory exhaustion when generating large PDFs
  CRM/Utils/PDF/Utils.php
Labels: master

#15868 Upgrade ui-sortable angular library to v0.19.0
  composer.json
Labels: master

#15820 dev/core#183 Finish converting contrib sybnt custom search to using t…
  CRM/Contact/Form/Search/Custom/ContribSYBNT.php
Labels: master

#15867 [NFC] fix test to correctly set up partially paid contribution
  tests/phpunit/CRM/Member/Form/MembershipTest.php
Labels: master

#15865 Fix incorrect reference on extracted function
  CRM/Contact/BAO/Query.php
Labels: master

#15873 dev/core#1377 Fix bug where search action doesn't work.
  templates/CRM/Contact/Form/Search/ResultTasks.tpl
Labels: 5.20, merge on pass

#15872 Fix Sybunt to select mark rows as selected
  CRM/Contact/Form/Search/Custom/ContribSYBNT.php
  CRM/Contact/Selector.php
Labels: 5.20

#15875 5.20
  CRM/Contact/Form/Search/Custom/ContribSYBNT.php
  CRM/Contact/Selector.php
  templates/CRM/Contact/Form/Search/ResultTasks.tpl
Labels: master
