Repository civicrm/civicrm-core, pull requests merged in 2020-10, with the labels that each got.

#18646 (REF) Switch to composer-compile-lib
  Civi/Compile/Scss.php
  composer.json
  composer.lock
  ext/greenwich/composer.compile.json
Labels: master, merge on pass

#18416 dev/core#2003 Use Brick/Money to ensure that we display all possible …
  CRM/Price/Form/Option.php
  CRM/Utils/Money.php
Labels: master, schedule-discussion

#18640 dev/core#2073 Improve cleanup on syntax conformance test
  tests/phpunit/api/v3/SyntaxConformanceTest.php
Labels: master

#18652 Fix patently silly code
  CRM/Grant/BAO/Query.php
Labels: master

#18655 dev/core#2079 [REF] Fix some more calls to getTokens to make it clear only the first return value is used
  api/v3/Mailing.php
  tests/phpunit/CRM/Utils/TokenTest.php
Labels: master, merge on pass

#18608 [REF] Follow up cleanup from Event Location
  CRM/Core/BAO/Address.php
  CRM/Core/BAO/Block.php
  tests/phpunit/CRM/Core/BAO/AddressTest.php
Labels: master

#18606 dev/core#2046 Ensure location BAOs have create actions, deprecate add…
  CRM/Core/BAO/Block.php
  CRM/Core/BAO/IM.php
  CRM/Core/BAO/OpenID.php
  tests/phpunit/CRM/Core/BAO/IMTest.php
  tests/phpunit/CRM/Core/BAO/OpenIDTest.php
Labels: master

#18656 dev/core#2079 [REF] Remove reference to second param returned from CRM_Contact_BAO_Query::apiQuery
  CRM/Contact/BAO/Group.php
  CRM/Contact/BAO/GroupContact.php
  CRM/Core/BAO/MessageTemplate.php
  Civi/Token/TokenCompatSubscriber.php
  tests/phpunit/CRM/Contact/BAO/QueryTest.php
Labels: master, merge on pass

#18643 Fix cache bypass
  CRM/ACL/BAO/ACL.php
Labels: master

#18625 dev/core#2057 Remove extraneous activity contact queries on activity update
  CRM/Activity/BAO/Activity.php
Labels: master

#18659 dev/core#1393 - distmaker - Skip new file "vendor/bin/cssmin"
  distmaker/dists/common.sh
Labels: master, merge on pass

#18636 dev/core#2057 - Failing unit test for passing in activity contacts as scalars to Activity::create()
  tests/phpunit/CRM/Activity/BAO/ActivityTest.php
Labels: has-test, master, merge on pass

#18635 dev/core#1818 Upgrade AngularJS from 1.5.11 to 1.8
  ang/crmApp.js
  composer.json
  composer.lock
  ext/afform/docs/quickstart.md
  ext/afform/gui/ang/afGuiList.aff.html
  ext/afform/html/ang/afHtmlEditor.aff.html
  ext/afform/html/ang/afHtmlList.aff.html
  js/angular-crmResource/all.js
  tests/karma/unit/crmCaseTypeSpec.js
Labels: master

#18660 (REF) Make it easier for extensions to define basic bundles
  CRM/Core/Resources/Bundle.php
  CRM/Core/Resources/Common.php
  tests/phpunit/CRM/Core/Resources/BundleTest.php
  tests/phpunit/CRM/Core/ResourcesTest.php
Labels: master, merge on pass

#18648 dev/core#1920 - Fix smarty error and missing mail setting help
  settings/Mailing.setting.php
  templates/CRM/Admin/Form/Setting/Mail.hlp
  templates/CRM/Mailing/Form/Settings.hlp
Labels: 5.30

#18666 5.30 to master
  settings/Mailing.setting.php
  templates/CRM/Admin/Form/Setting/Mail.hlp
  templates/CRM/Mailing/Form/Settings.hlp
Labels: master

#18669 dev/core#2090 - Undefined index on contact's activity tab when there's an activity that has no With Contact
  CRM/Activity/BAO/Activity.php
  tests/phpunit/CRM/Activity/BAO/ActivityTest.php
Labels: master

#18647 [REF] Add in css classes to make the save and preview button on the C…
  CRM/Contribute/Form/ContributionPage/Widget.php
Labels: master

#18670 composer.json - Update compile-lib and compile-plugin
  composer.json
  composer.lock
Labels: master, merge on pass

#18644 Search ext: support complex joins & HAVING clause in api4 smart groups
  CRM/Contact/BAO/GroupContactCache.php
  CRM/Utils/API/HTMLInputCoder.php
  ext/search/CRM/Search/Page/Ang.php
  ext/search/ang/search.module.js
  ext/search/ang/search/SaveSmartGroup.ctrl.js
  ext/search/ang/search/crmSearch.component.js
  ext/search/ang/search/crmSearchActions.component.js
  ext/search/ang/search/crmSearchFunction.component.js
  ext/search/ang/search/saveSmartGroup.html
  tests/phpunit/api/v4/Entity/SavedSearchTest.php
Labels: has-test, master, merge on pass

#17675 Select field fixes for screen reader
  CRM/ACL/Form/ACL.php
  CRM/ACL/Form/EntityRole.php
  CRM/Activity/BAO/Query.php
  CRM/Activity/Form/Activity.php
  CRM/Admin/Form/Job.php
  CRM/Admin/Form/MessageTemplates.php
  CRM/Admin/Form/PdfFormats.php
  CRM/Contact/Form/Task/EmailTrait.php
  CRM/Contribute/Form/ContributionPage/Premium.php
  CRM/Contribute/Form/ManagePremiums.php
  CRM/Core/BAO/CustomField.php
  CRM/Core/BAO/UFGroup.php
  CRM/Core/DAO/StateProvince.php
  CRM/Core/Form.php
  CRM/Import/DataSource/SQL.php
  CRM/Price/Form/Field.php
  CRM/SMS/Form/Provider.php
  xml/schema/Core/StateProvince.xml
Labels: master, ok-without-test, sig:accessibility, sig:user interfacing improvement

#18671 fix labels on new admin permissions
  CRM/Core/Permission.php
Labels: master

#18649 Ensure that the crm-error class on the field is also remove when field is changed
  js/Common.js
Labels: master, merge on pass

#18610 dev/drupal#119 - Avoid crash from recursion on unhandled exceptions
  CRM/Core/Error.php
  composer.json
  composer.lock
Labels: master

#18611 Add modified_date to list of activity tokens
  CRM/Activity/Tokens.php
Labels: master

#18143 Move membership tab add/submit membership buttons to PHP layer
  CRM/Member/Page/Tab.php
  templates/CRM/Member/Page/Tab.tpl
Labels: master

#18674 [REF] Fix adding in the accessKey based on the button array
  templates/CRM/common/formButtons.tpl
Labels: master, merge on pass

#18675 dev/core#2087 move uf_match check above the primary check
  CRM/Core/BAO/UFMatch.php
Labels: master, merge on pass

#18673 When exporting for composer-style deployment, exclude the `.gitignore` file
  .gitattributes
Labels: master

#18676 [REF] Remove XML_Util dependancy within ewaysingle extension
  ext/ewaysingle/lib/XML/Util.php
  ext/ewaysingle/lib/eWAY/eWAY_GatewayRequest.php
Labels: master, merge on pass

#18657 dev/core#2079 do not return never-used, query-wasting variable
  CRM/Utils/Token.php
Labels: master

#18665 dev/core#2079 [REF] clean up call to apiQuery
  CRM/Contact/Form/Task/Label.php
  tests/phpunit/CRM/Contact/Form/Task/PrintMailingLabelTest.php
Labels: master

#18678 dev/core#2093 - Fix red error box on new individual form and ltrim typos and doubling-up of class attribute
  CRM/Core/BAO/CustomField.php
  tests/phpunit/CRM/Contact/Form/IndividualTest.php
Labels: master

#18677 change civicrm_price_set.min_amount to float
  CRM/Price/DAO/PriceSet.php
  CRM/Upgrade/Incremental/sql/5.31.alpha1.mysql.tpl
  xml/schema/Price/PriceSet.xml
Labels: master

#18664 dev/core#2079 [REF] clean up call to apiQuery
  CRM/Contact/Form/Task/LabelCommon.php
  CRM/Member/Task.php
  tests/phpunit/CRM/Member/Form/Task/LabelTest.php
Labels: has-test, master

#18661 dev/core#2046 Fix blockDelete to delete while ensuring is_primary is valid
  CRM/Core/BAO/Block.php
  tests/phpunit/CRM/Contact/Import/Parser/ContactTest.php
Labels: has-test, master

#18658 dev/core#2046 Migrate BAO_Address::create towards standardisation
  CRM/Contact/Form/Inline/Address.php
  CRM/Core/BAO/Address.php
  CRM/Core/BAO/Location.php
  tests/phpunit/CRM/Core/BAO/AddressTest.php
Labels: master

#18679 [REF] Fix compatability with Drupal 9 installing of var_dumper
  composer.json
  composer.lock
Labels: master, merge on pass

#18672 Search ext: rename to Search Kit, mark as beta
  ext/search/CRM/Search/Upgrader.php
  ext/search/README.md
  ext/search/ang/search/crmSearch.html
  ext/search/info.xml
Labels: master, merge ready

#18684 dev/core#2039 Call del directly - rather than now-deprecated blockDelete
  CRM/Core/BAO/Block.php
Labels: master

#18623 dev/core#1790 - Contact Card - Email Links
  CRM/Contact/BAO/Contact/Utils.php
  CRM/Profile/Page/Dynamic.php
  CRM/Profile/Page/View.php
  tests/phpunit/CRM/Activity/Form/SearchTest.php
  tests/phpunit/CRM/Financial/Page/AjaxTest.php
  tests/phpunit/CRM/Member/Selector/SearchTest.php
  tests/phpunit/CRM/Pledge/Form/SearchTest.php
Labels: master

#18685 [REF] Fix error when creating new AB test mailing because domain_id i…
  ang/crmMailingAB/services.js
Labels: 5.30, merge on pass

#18689 [NFC] Update Checksum on CustomField DAO
  CRM/Core/DAO/CustomField.php
Labels: 5.30, merge on pass

#18694 5.30
  ang/crmMailingAB/services.js
Labels: master

#18692 dev/core#2073 Remove memory leak in heavily tested (merge) code
  CRM/Dedupe/BAO/RuleGroup.php
  CRM/Dedupe/Finder.php
Labels: master, merge on pass

#18690 dev/translation#54 Ensure that Component titles are translated in lin…
  CRM/Admin/Page/ConfigTaskList.php
  templates/CRM/Admin/Page/ConfigTaskList.tpl
Labels: master

#18682 dev/core#2046 Fix api to call Address.create now it is standardised
  Civi/Api4/Generic/Traits/DAOActionTrait.php
  api/v3/Address.php
  tests/phpunit/api/v4/Action/IsPrimaryTest.php
Labels: has-test, master

#18140 Remove ajax timeout from contribution page on behalf of
  templates/CRM/Contribute/Form/Contribution/OnBehalfOf.tpl
Labels: master, ok-without-test

#18683 Search ext & APIv4 Explorer: Refactor clause from directive to component
  ang/api4Explorer/Clause.html
  ang/api4Explorer/Explorer.html
  ang/api4Explorer/Explorer.js
  css/api4-explorer.css
  ext/search/ang/search/crmSearch/criteria.html
  ext/search/ang/search/crmSearchClause.component.js
  ext/search/ang/search/crmSearchClause.directive.js
  ext/search/ang/search/crmSearchClause.html
  ext/search/css/search.css
Labels: master, merge on pass

#18693 dev/core#2073 Fix memory leak in well tested code
  CRM/Contact/BAO/Relationship.php
Labels: has-test, master

#18662 dev/core#2017 Deprecate an unused function
  CRM/Core/BAO/Location.php
Labels: master

#18663 dev/core#2039 Remove extraneous location queries from contact.create->Location::block path
  CRM/Core/BAO/Block.php
  CRM/Core/BAO/Location.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/api/v3/JobTest.php
  tests/phpunit/api/v3/SyntaxConformanceTest.php
Labels: has-test, master

#18650 Fix complexity on cache key
  CRM/Core/BAO/CustomField.php
Labels: master

#18500 dev/core#2047 [Ref] Remove obsolete check
  CRM/Dedupe/Merger.php
Labels: master

#18695 Exclude api4 from IDS check
  CRM/Core/IDS.php
Labels: master

#18556 dev/core#2056 Only retrieve pcp & soft_credit info when needed
  CRM/Contribute/BAO/ContributionSoft.php
  tests/phpunit/CRM/Contribute/Form/ContributionTest.php
  tests/phpunit/CRM/PCP/BAO/PCPTest.php
  tests/phpunit/CRMTraits/PCP/PCPTestTrait.php
Labels: master

#18696 Greenwich - fix conflict btw bootstrap & jQuery UI button
  ext/greenwich/greenwich.php
  ext/greenwich/js/noConflict.js
Labels: master

#18667 dev/core#2087 Remove extraneous CRM_Core_BAO_UFMatch::updateUFName call
  CRM/Contact/BAO/Contact.php
Labels: master

#18653 dev/core#2079 [Ref] Clarify calls to CRM_Utils_Token::getTokenDetails
  CRM/Contribute/Form/Task/PDFLetterCommon.php
  CRM/Mailing/BAO/MailingJob.php
  tests/phpunit/CRM/Utils/TokenTest.php
Labels: master

#18654 dev/core#2079 [REF] Fix some more calls to getTokens to make it clear only the first return value is used
  CRM/Mailing/Page/Preview.php
  CRM/Pledge/BAO/Pledge.php
Labels: master

#18698 [NFC] dev/core#2053 Extend nextedGroup test to show that it will retu…
  tests/phpunit/CRM/Contact/BAO/GroupTest.php
Labels: has-test, master, merge on pass

#18700 dev/core#2073 Fix use of legacy leaky method in tested code
  CRM/Contact/BAO/GroupContact.php
Labels: master, merge on pass

#18705 5.30.0 release notes: updated with late changes
  release-notes/5.30.0.md
Labels: 5.30

#18680 dev/financial#151 Paypal express validation fix on event
  CRM/Core/Payment/PayPalImpl.php
Labels: 5.30, merge on pass

#18706 5.30
  CRM/Core/Payment/PayPalImpl.php
  release-notes/5.30.0.md
Labels: master

#18493 Fix default report permissions when creating reports from CiviCampaign
  CRM/Campaign/Form/Survey/Results.php
Labels: master

#18699 dev/core#2073 Fix use of legacy leaky method in tested code
  CRM/Contact/Import/Form/MapField.php
Labels: master, merge on pass

#18704 ParticipantListing Report: only display the View link for web, unhardcode others
  CRM/Report/Form/Event/ParticipantListing.php
Labels: master, merge on pass

#18702 dev/core#2073 Fix use of legacy leaky method in tested code
  CRM/Contribute/BAO/Contribution.php
Labels: master, merge on pass

#18707 Enotice fix
  CRM/Report/Form/Instance.php
Labels: master, merge on pass

#18701 dev/core#2073 Fix use of legacy leaky method in tested code
  CRM/Import/DataSource/CSV.php
Labels: master, merge on pass

#18324 Display url_site and url_recur based on if the form elements exist
  templates/CRM/Admin/Form/PaymentProcessor.tpl
Labels: master, ok-without-test, sig:user interfacing improvement

#18360 Fix way of identityfing custom serialized fields
  CRM/Core/BAO/UFGroup.php
Labels: master

#18624 Add options to Mail Account settings to improve inbound mail processing
  CRM/Admin/Form/MailSettings.php
  CRM/Upgrade/Incremental/php/FiveThirtyOne.php
  CRM/Utils/Hook.php
  CRM/Utils/Mail/CaseMail.php
  CRM/Utils/Mail/EmailProcessor.php
  CRM/Utils/Mail/Incoming.php
  templates/CRM/Admin/Form/MailSettings.tpl
  templates/CRM/Admin/Page/MailSettings.hlp
  tests/phpunit/CRM/Utils/Mail/EmailProcessorTest.php
  tests/phpunit/CRM/Utils/Mail/data/inbound/test_cases_email.eml
  tests/phpunit/CRM/Utils/Mail/data/inbound/test_non_cases_email.eml
  xml/schema/Core/MailSettings.xml
Labels: has-test, master

#18711 Move to alpha1 stage
  CRM/Core/DAO/MailSettings.php
  CRM/Upgrade/Incremental/php/FiveThirtyOne.php
  sql/civicrm_generated.mysql
Labels: master, merge on pass

#18709 [NFC] Regen after #18624
  CRM/Core/DAO/MailSettings.php
  sql/civicrm_generated.mysql
Labels: master, merge on pass

#18708 Add unit test that ultimately failed to hit the desired code but does add cover
  tests/phpunit/CRM/Member/Form/MembershipRenewalTest.php
  tests/phpunit/CRMTraits/Custom/CustomDataTrait.php
Labels: has-test, master

#18710 dev/core#2096 Fix in-master-only regression on creating new events
  CRM/Event/Form/ManageEvent/Location.php
Labels: master

#18688 [REF] Upgrade DomPDF to v0.8.6
  composer.lock
Labels: master

#18714 Financial#111: Contribution tokens always display amount with default…
  CRM/Utils/Token.php
Labels: master

#18715 dev/financial#11 Expand unit test to ensure that the correct currency…
  tests/phpunit/CRM/Contribute/BAO/ContributionTest.php
Labels: has-test, master, merge on pass

#18716 dev/core#2108 fix deprecation notice
  CRM/Core/Form/Task/PDFLetterCommon.php
  templates/CRM/Contact/Form/Task/PDFLetterCommon.tpl
Labels: 5.31

#18719 core#2105: Groups children now get shown with SPAN CSS error
  CRM/Contact/Form/Edit/TagsAndGroups.php
  CRM/Contact/Form/Search/Basic.php
  CRM/Contact/Form/Search/Criteria.php
Labels: 5.31

#18724 core#2105: Groups children now get shown with SPAN CSS error
  CRM/Contact/Form/Edit/TagsAndGroups.php
  CRM/Contact/Form/Search/Basic.php
  CRM/Contact/Form/Search/Criteria.php
Labels: 5.30

#18723 Search ext: misc cleanup & fixes
  Civi/Api4/Action/Entity/Get.php
  ext/search/CRM/Search/Page/Ang.php
  ext/search/ang/search.module.js
  ext/search/ang/search/crmSearch.component.js
  ext/search/ang/search/crmSearch/controls.html
  ext/search/ang/search/crmSearchActions.component.js
  ext/search/ang/search/crmSearchActions.html
  ext/search/ang/search/crmSearchActions/crmSearchActionUpdate.ctrl.js
  ext/search/ang/search/crmSearchActions/crmSearchActionUpdate.html
Labels: 5.31, merge on pass

#18713 dev/core#2102 Fix hang on event edit
  CRM/Event/Form/ManageEvent/Location.php
  tests/phpunit/CRM/Event/Form/ManageEvent/LocationTest.php
Labels: 5.31, has-test

#18717 dev/core#2108 fix deprecation notice take 2
  CRM/Core/Form.php
Labels: 5.31

#18725 5.31
  CRM/Contact/Form/Edit/TagsAndGroups.php
  CRM/Contact/Form/Search/Basic.php
  CRM/Contact/Form/Search/Criteria.php
  CRM/Core/Form.php
  CRM/Core/Form/Task/PDFLetterCommon.php
  CRM/Event/Form/ManageEvent/Location.php
  Civi/Api4/Action/Entity/Get.php
  ext/search/CRM/Search/Page/Ang.php
  ext/search/ang/search.module.js
  ext/search/ang/search/crmSearch.component.js
  ext/search/ang/search/crmSearch/controls.html
  ext/search/ang/search/crmSearchActions.component.js
  ext/search/ang/search/crmSearchActions.html
  ext/search/ang/search/crmSearchActions/crmSearchActionUpdate.ctrl.js
  ext/search/ang/search/crmSearchActions/crmSearchActionUpdate.html
  templates/CRM/Contact/Form/Task/PDFLetterCommon.tpl
  tests/phpunit/CRM/Event/Form/ManageEvent/LocationTest.php
Labels: master

#17969 dev/cloud-native#16 Migrate Contribution Page widget extern url to us…
  CRM/Contribute/Page/Widget.php
  CRM/Contribute/xml/Menu/Contribute.xml
  CRM/Utils/System.php
  sql/civicrm_generated.mysql
  tests/phpunit/E2E/Extern/WidgetTest.php
Labels: has-test, master

#18629 dev/financial#152 [REF] Parse ids before sending to recur function (minor simplification)
  CRM/Core/Payment/AuthorizeNetIPN.php
Labels: master

#18631 dev/financial#152 [REF] Parse ids before sending to single function (minor simplification)
  CRM/Core/Payment/PayPalProIPN.php
Labels: master

#18726 dev/core#2110 - Warning "Non-static method CRM_Contact_Page_AJAX::pdfFormat() should not be called statically" when changing the page format on print/merge document
  CRM/Contact/Page/AJAX.php
Labels: master

#18729 dev/financial#152 Clean up & test contributionPageID handling
  CRM/Core/Payment/AuthorizeNetIPN.php
  tests/phpunit/CRM/Core/Payment/AuthorizeNetIPNTest.php
Labels: has-test, master, merge on pass

#18730 dev/financial#152 Remove unused parameters from BaseIPN->cancelled signature
  CRM/Core/Payment/BaseIPN.php
  tests/phpunit/CRM/Core/Payment/BaseIPNTest.php
Labels: master, merge on pass

#18732 dev/financial#152 Remove unused parameters from BaseIPN->failed signature
  CRM/Core/Payment/BaseIPN.php
  tests/phpunit/CRM/Core/Payment/BaseIPNTest.php
Labels: master, merge on pass

#18727 [Test] Ensure all APIv4 entities have basic info
  tests/phpunit/api/v4/Entity/ConformanceTest.php
Labels: master

#18734 dev/financial#152 Remove unreachable code
  CRM/Core/Payment/PayPalProIPN.php
Labels: master

#18733 dev/financial#152 [REF] Extract getMembershipID
  CRM/Core/Payment/AuthorizeNetIPN.php
Labels: master

#18728 dev/financial#152 Pass contribution directly to completeOrder
  CRM/Contribute/BAO/Contribution.php
  CRM/Core/Payment/AuthorizeNetIPN.php
  CRM/Core/Payment/BaseIPN.php
  CRM/Core/Payment/PayPalIPN.php
  CRM/Core/Payment/PayPalProIPN.php
  CRM/Event/Form/Task/Batch.php
  api/v3/Contribution.php
Labels: master

#18651 [REF] Minor simplification - don't use a variable for table name
  CRM/Core/BAO/CustomField.php
Labels: master

#18737 dev/financial#152 remove unused parameter
  CRM/Core/Payment/PayPalIPN.php
  CRM/Core/Payment/PayPalProIPN.php
Labels: master, merge on pass

#18555 dev/core#2047 Fix merge code so that deleted contacts are not left without a primary address
  CRM/Dedupe/MergeHandler.php
  CRM/Dedupe/Merger.php
  tests/phpunit/api/v3/JobTest.php
Labels: has-test, master

#18668 dev/core#2079 Eliminate unused query on CRM_Core_BAO_CustomQuery::_construct
  CRM/Contact/BAO/Query.php
  CRM/Contact/Selector.php
  CRM/Core/BAO/CustomQuery.php
  CRM/Profile/Selector/Listings.php
Labels: master

#18736 dev/financial#152 simplify passed parameters
  CRM/Core/Payment/PayPalIPN.php
Labels: master

#18735 dev/financial#152 simplify interaction with membership, deprecate function
  CRM/Contribute/BAO/ContributionRecur.php
  CRM/Core/Payment/AuthorizeNetIPN.php
  tests/phpunit/CRM/Core/Payment/AuthorizeNetIPNTest.php
Labels: master

#18738 dev/core#2115 remove reference to financialACLs in bounce
  CRM/Member/Form/Membership.php
Labels: master

#18742 Fix main contact uf url on merge screen
  CRM/Dedupe/Merger.php
Labels: master

#18743 More accurate language around social media sharing
  CRM/Campaign/Form/Petition.php
  CRM/Contribute/Form/ContributionPage/Settings.php
  CRM/Event/Form/ManageEvent/EventInfo.php
Labels: master, merge on pass

#18744 dev/financial#152 simplify passed parameters
  CRM/Core/Payment/AuthorizeNetIPN.php
Labels: master, merge on pass

#18747 [REF] Replace long if block with early return
  CRM/Core/Payment/AuthorizeNetIPN.php
Labels: master, merge on pass

#18731 AngularLoader: Support 'settingsFactory' callbacks in angular modules.
  Civi/Angular/AngularLoader.php
  Civi/Angular/Manager.php
  tests/phpunit/Civi/Angular/LoaderTest.php
Labels: has-test, master, merge ready

#18749 crmMailing - Only load Angular settings if they're needed
  CRM/Mailing/Info.php
  ang/crmMailing.ang.php
Labels: master, merge on pass, ok-without-test

#18750 Extract setNextUrl
  CRM/Core/Form/Task.php
Labels: master, merge on pass

#18756 5.31 to master
  CRM/Contact/BAO/RelationshipCache.php
  CRM/Core/BAO/SchemaHandler.php
Labels: master

#18753 dev/core#2118 supply better automatic placeholders for select (5.31 intra-rc)
  CRM/Contact/Form/Edit/Address.php
  CRM/Core/Form.php
Labels: 5.31

#18754 Angular Loader: Allow modules to specify permissions to add client-side
  CRM/Mailing/Info.php
  Civi/Angular/AngularLoader.php
  Civi/Angular/Manager.php
  ang/crmMailing.ang.php
  tests/phpunit/Civi/Angular/LoaderTest.php
Labels: has-test, master

#18757 5.31
  CRM/Contact/Form/Edit/Address.php
  CRM/Core/Form.php
Labels: master

#18758 dev/event#43 Contact Dashboard: fix Event Participations
  CRM/Event/Page/UserDashboard.php
Labels: 5.31

#18762 Typo in call to fixSchemaDifferencesForAll
  CRM/Logging/Schema.php
Labels: master, merge on pass

#18581 dev/drupal#137 - Alternate PR - On drupal status report need different check when civi is already installed
  setup/plugins/installFiles/InstallSettingsFile.civi-setup.php
Labels: master

#18764 5.31
  CRM/Event/Page/UserDashboard.php
Labels: master

#18449 Allow custom fields of type Autocomplete-Select to be multivalued
  CRM/Core/BAO/CustomField.php
  CRM/Custom/Form/Field.php
  templates/CRM/Custom/Form/Field.tpl
  tests/phpunit/CRM/Core/BAO/CustomFieldTest.php
  tests/phpunit/CRM/Export/BAO/ExportTest.php
  tests/phpunit/CRMTraits/Custom/CustomDataTrait.php
Labels: has-test, master

#18763 dev/core#2119 Fix mailing code to exclude deleted recipients
  CRM/Mailing/BAO/Recipients.php
  tests/phpunit/api/v3/JobProcessMailingTest.php
Labels: 5.31, has-test

#18767 dev/core#2066 Use shared function to set the next url
  CRM/Activity/Form/Task.php
  CRM/Contribute/Form/Task.php
  CRM/Core/Form/Task.php
Labels: master

#18768 dev/core#2066 Extract getSelectedIDs
  CRM/Activity/Form/Task.php
  CRM/Contribute/Form/Task.php
  CRM/Core/Form/Task.php
Labels: master

#18770 5.31
  CRM/Mailing/BAO/Recipients.php
  tests/phpunit/api/v3/JobProcessMailingTest.php
Labels: master

#18761 Test for event#43
  tests/phpunit/CRM/Contact/Page/View/UserDashBoardTest.php
Labels: master

#18765 dev/core#2117 - Add compatibility aliases for 'scriptFile' and 'styleFile' resources
  CRM/Core/Resources/CollectionInterface.php
  CRM/Core/Resources/CollectionTrait.php
  tests/phpunit/CRM/Core/Resources/CollectionTestTrait.php
Labels: 5.31

#18774 5.31 to master
  CRM/Core/Resources/CollectionInterface.php
  CRM/Core/Resources/CollectionTrait.php
  tests/phpunit/CRM/Core/Resources/CollectionTestTrait.php
Labels: master

#18400 class.api.php: In remote api calls, allow referer and useragent to be set.
  api/class.api.php
Labels: master

#18411 CRM-9362: PCP 'Your Message' should use WYSIWYG
  CRM/PCP/Form/Campaign.php
Labels: master

#18776 dev/core#2125 Ensure that the id that is used in the field is the gro…
  CRM/Contact/Form/Edit/TagsAndGroups.php
Labels: 5.31

#18777 5.31
  CRM/Contact/Form/Edit/TagsAndGroups.php
Labels: master

#18771 530
  CRM/Contact/BAO/RelationshipCache.php
  CRM/Contact/Form/Edit/TagsAndGroups.php
  CRM/Core/BAO/SchemaHandler.php
  CRM/Event/Page/UserDashboard.php
  CRM/Mailing/BAO/Recipients.php
  tests/phpunit/api/v3/JobProcessMailingTest.php
Labels: 5.30

#18778 Fix pluralize function for words like 'display'
  CRM/Utils/String.php
  ang/api4Explorer/Explorer.js
Labels: master

#17568 Contribution confirmation page should not display the name of payment processor type
  CRM/Core/Payment.php
Labels: master, merge on pass, sig:user interfacing improvement

#18783 dev/core#2066 Further cleanup on search actions
  CRM/Activity/Export/Form/Select.php
  CRM/Contact/Export/Form/Select.php
  CRM/Contribute/Export/Form/Select.php
  CRM/Core/Form/Task.php
  CRM/Event/Export/Form/Select.php
  CRM/Export/Form/Select.php
  CRM/Export/Form/Select/Case.php
  CRM/Grant/Export/Form/Select.php
  CRM/Member/Export/Form/Select.php
  CRM/Pledge/Export/Form/Select.php
Labels: master

#18773 dev/core#2066 Use shared function to set the next url
  CRM/Campaign/Form/Task.php
  CRM/Event/Form/Task.php
  CRM/Grant/Form/Task.php
  CRM/Member/Form/Task.php
  CRM/Pledge/Form/Task.php
Labels: master

#18766 Fix unreleased regression on search tasks from basic search
  CRM/Activity/Controller/Search.php
  CRM/Campaign/Controller/Search.php
  CRM/Case/Controller/Search.php
  CRM/Contact/Controller/Search.php
  CRM/Contribute/Controller/Search.php
  CRM/Event/Controller/Search.php
  CRM/Grant/Controller/Search.php
  CRM/Member/Controller/Search.php
  CRM/Pledge/Controller/Search.php
Labels: 5.31

#18540 dev/core#2034 Fix paypal standard cancel url
  CRM/Core/Payment.php
  CRM/Core/Payment/PayPalImpl.php
  tests/phpunit/CRM/Core/Payment/PayPalIPNTest.php
Labels: has-test, master

#18788 5.31
  CRM/Activity/Controller/Search.php
  CRM/Campaign/Controller/Search.php
  CRM/Case/Controller/Search.php
  CRM/Contact/Controller/Search.php
  CRM/Contribute/Controller/Search.php
  CRM/Event/Controller/Search.php
  CRM/Grant/Controller/Search.php
  CRM/Member/Controller/Search.php
  CRM/Pledge/Controller/Search.php
Labels: master

#18739 [Ref] Minor code extraction
  CRM/Price/BAO/PriceSet.php
Labels: master

#18791 Remove instances of variable variables
  CRM/Batch/Form/Entry.php
  CRM/Core/BAO/UFGroup.php
  tests/phpunit/CRM/Batch/Form/EntryTest.php
Labels: master, merge on pass

#18795 [Test] - Fix some tests to call API not BAO
  tests/phpunit/CRM/Member/BAO/MembershipTypeTest.php
  tests/phpunit/api/v3/MembershipTest.php
Labels: master

#18789 Fix sendconfirmation api to override receipt params
  CRM/Contribute/BAO/Contribution.php
  tests/phpunit/api/v3/ContributionTest.php
Labels: has-test, master

#18785 unit test for #18306 - order create api test for contribution
  tests/phpunit/CRMTraits/Financial/OrderTrait.php
  tests/phpunit/api/v3/ContributionTest.php
Labels: has-test, master

#18796 Switch to calling the api
  CRM/Member/BAO/Membership.php
Labels: master, merge on pass

#18797 Switch to calling api
  CRM/Contact/BAO/Relationship.php
Labels: master, merge on pass

#18798 Replace BAO calls with api calls in test class
  tests/phpunit/CRM/Member/BAO/MembershipTest.php
Labels: master, merge on pass

#18790 Add test for recurring links and clean up method of retrieving recurring
  CRM/Contribute/BAO/ContributionRecur.php
  CRM/Contribute/Page/Tab.php
  Civi/Payment/System.php
  tests/phpunit/CRM/Contribute/Page/TabTest.php
Labels: master, merge on pass
