Repository civicrm/civicrm-core, pull requests merged in 2020-08, with the labels that each got.

#18012 SQL temp table not using utf8mb4 if server default already set to utf8mb4
  CRM/Utils/SQL/TempTable.php
Labels: master

#17990 CIVICRM_BAO_CACHE_ADAPTER - Remove obsolete option
  CRM/Core/BAO/Cache/Psr16.php
  CRM/Core/Config.php
  templates/CRM/common/civicrm.settings.php.template
Labels: master, merge on pass

#17984 [REF] Remove pass-by-reference & always empty param
  CRM/Contribute/BAO/Contribution.php
  CRM/Contribute/Form/Task/PDF.php
  api/v3/Contribution.php
Labels: has-test, master, merge on pass

#17999 Cache loader - remove legacy handling, handle null result from setting
  Civi/Core/Container.php
Labels: master

#18017 dev/mail#72 Remove call to custom fatal error handler from CRM_Core_E…
  CRM/Core/Error.php
Labels: 5.28

#18023 5.28 to master
  CRM/Core/Error.php
  CRM/Upgrade/Incremental/php/FiveTwentyEight.php
  CRM/Utils/System/WordPress.php
Labels: master

#18021 Remove unused parameter ids['billing']
  CRM/Core/Payment/AuthorizeNetIPN.php
  CRM/Core/Payment/PayPalIPN.php
  CRM/Core/Payment/PayPalProIPN.php
Labels: master, merge on pass

#18020 [REF] Stop instantiating transaction in PaypalIPN
  CRM/Core/Payment/BaseIPN.php
  CRM/Core/Payment/PayPalIPN.php
Labels: master, merge on pass

#18024 dev/mail#72 Remove call to custom fatal error handler from CRM_Core_E…
  CRM/Core/Error.php
Labels: 5.27, merge on pass

#18026 [Ref] Remove transaction instantiation in PaypalPro
  CRM/Core/Payment/PayPalProIPN.php
Labels: master, merge on pass

#18010 Remove main PaymentExpress class
  CRM/Core/Payment/PaymentExpress.php
  CRM/Core/Payment/PaymentExpressUtils.php
Labels: master

#18031 Remove invalid use of crmMoney formatter
  templates/CRM/Contribute/Form/ContributionPage/Amount.tpl
Labels: master

#18036 Fix for failing test
  tests/phpunit/CRM/Contribute/BAO/ContributionRecurTest.php
Labels: has-test, master

#17943 dev/core#1906 - Allow payment create api to record payment on Failed …
  CRM/Contribute/BAO/Contribution.php
  CRM/Financial/BAO/Payment.php
  tests/phpunit/api/v3/PaymentTest.php
Labels: has-test, master

#18019 [REF] [Test] Minor simplification on test
  tests/phpunit/CRM/Contribute/BAO/ContributionTest.php
  tests/phpunit/CRM/Event/Form/ParticipantTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: has-test, master, merge on pass

#17912 Update flexmailer release information
  ext/flexmailer/info.xml
Labels: master

#18029 [Ref] Simplify is_email_receipt in sendMail
  CRM/Contribute/BAO/Contribution.php
  api/v3/Contribution.php
Labels: master

#18015 dev/core#1919 - Missing resubscribe url in text/plain version of unsubscribe confirmation email
  CRM/Upgrade/Incremental/sql/5.29.alpha1.mysql.tpl
  sql/civicrm_generated.mysql
  xml/templates/civicrm_data.tpl
Labels: master

#18041 Fix qill typo
  CRM/Case/BAO/Query.php
  tests/phpunit/CRM/Case/BAO/QueryTest.php
Labels: master

#18037 Add test on status calculation
  CRM/Contribute/BAO/Contribution.php
  tests/phpunit/api/v3/ContributionTest.php
Labels: has-test, master, merge on pass

#18028 Add testing to Authorize.net and remove the lines that are repeated
  CRM/Core/Payment/AuthorizeNetIPN.php
  tests/phpunit/CRM/Core/Payment/AuthorizeNetIPNTest.php
Labels: has-test, master, merge on pass

#17824 SystemCheck: add ability to efficiently run only specified checks
  CRM/Upgrade/Incremental/sql/5.29.alpha1.mysql.tpl
  CRM/Utils/Check.php
  CRM/Utils/Check/Component.php
  CRM/Utils/Check/Component/Env.php
  CRM/Utils/Hook.php
  Civi/Api4/Action/System/Check.php
  Civi/Api4/Generic/AbstractGetAction.php
  tests/phpunit/api/v4/Entity/SystemTest.php
Labels: has-test, master, merge ready

#18043 dev/core#1916 - Fix naming of case export fields / remove ones that aren't true
  CRM/Activity/BAO/Activity.php
  CRM/Case/BAO/Query.php
  tests/phpunit/CRM/Case/BAO/QueryTest.php
  tests/phpunit/CRM/Export/BAO/ExportTest.php
Labels: has-test, master, merge on pass

#17972 Do not overwrite values saved from the repeatContribution routine
  CRM/Contribute/BAO/Contribution.php
  tests/phpunit/CRM/Contribute/BAO/ContributionRecurTest.php
Labels: has-test, master, merge on pass

#17700 Remove url-tracking in mass sms. dev/core#1843
  CRM/Mailing/BAO/Mailing.php
Labels: master, ok-without-test

#18042 [REF] Remove transaction from BaseIPN completeTransaction call
  CRM/Core/Payment/BaseIPN.php
Labels: master

#18038 Test - attempt to replicate #17852
  tests/phpunit/CRM/Event/BAO/EventPermissionsTest.php
  tests/phpunit/CRMTraits/ACL/PermissionTrait.php
Labels: master

#17706 dev/core#1137 - Allow ssl connection to mysql by specifying in DSN
  CRM/Core/DAO.php
Labels: master, needs-documentation, ok-without-test

#18045 [Test fix] We might need this to ensure really quick test runs don't fail
  tests/phpunit/CRM/Core/Payment/AuthorizeNetIPNTest.php
Labels: master, merge on pass

#17966 Wrap multi record custom field inside a div
  templates/CRM/Profile/Form/Dynamic.tpl
Labels: master, ok-without-test, sig:user interfacing improvement

#18046 [REF] Remove transaction from completeOrder signature
  CRM/Contribute/BAO/Contribution.php
  api/v3/Contribution.php
Labels: master, merge on pass

#18033 Use saved contribution's line items rather than the primaryContributionID
  CRM/Contribute/BAO/Contribution.php
  tests/phpunit/api/v3/ContributionTest.php
Labels: has-test, master

#18032 [REF] Clean up handling of financial_type_id override
  CRM/Contribute/BAO/Contribution.php
  CRM/Contribute/BAO/ContributionRecur.php
  tests/phpunit/CRM/Event/Form/Task/ParticipantStatusTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/api/v3/ContributionTest.php
Labels: has-test, master

#18018 Remove requirement to pass 'contribution_status_id' => Pending from order.create
  api/v3/Order.php
  tests/phpunit/CRM/Contribute/BAO/ContributionRecurTest.php
  tests/phpunit/CRM/Contribute/Form/Task/InvoiceTest.php
Labels: has-test, master

#18044 Fix PaypalIPN single function to not receive-by-reference
  CRM/Core/Payment/PayPalIPN.php
Labels: master

#18030 [REF] Simplify membership status date handling
  CRM/Member/BAO/MembershipStatus.php
Labels: concept approved, master

#17937 Fix JQuery Validation for radios
  CRM/Core/Form.php
  js/Common.js
  templates/CRM/common/l10n.js.tpl
Labels: master, merge ready, ok-without-test

#18048 5.27.4 - Add release notes. Bump version.
  CRM/Upgrade/Incremental/sql/5.27.4.mysql.tpl
  release-notes.md
  release-notes/5.27.4.md
  sql/civicrm_generated.mysql
  xml/version.xml
Labels: 5.27

#16877 Remove ORDER BY and GROUP BY from alphabetQuery to improve performance
  CRM/Contact/BAO/Query.php
Labels: master

#18052 dev/core#1665 Remove the having clause as well as having needs a group by
  CRM/Contact/BAO/Query.php
Labels: master, merge on pass

#18025 dev/core#1921 [Ref] remove isoToMysql
  CRM/Core/Payment/BaseIPN.php
Labels: has-test, master

#17915 dev/drupal#127 - require email for the Useradd task and errors not showing
  CRM/Contact/Form/Task/Useradd.php
  CRM/Utils/System/Drupal8.php
  tests/phpunit/CRM/Contact/Form/Task/UseraddTest.php
Labels: has-test, master

#17993 Fix obscure dedupe scenario where 'bad' location data can overwrite good data
  CRM/Dedupe/Merger.php
  tests/phpunit/api/v3/ContactTest.php
Labels: has-test, master

#18051 [REF] Simplify getMembershipStatusByDate more
  CRM/Member/BAO/MembershipStatus.php
  tests/phpunit/CRM/Member/BAO/MembershipStatusTest.php
Labels: master

#18057 [REF] Do not pass by reference to the recur function
  CRM/Core/Payment/PayPalProIPN.php
Labels: master, merge on pass

#18053 [NFC] Port some recent test fixes from master to 5.28
  tests/phpunit/CRM/Activity/Form/SearchTest.php
  tests/phpunit/CRM/Contribute/BAO/ContributionRecurTest.php
  tests/phpunit/api/v3/TaxContributionPageTest.php
  tests/phpunit/api/v3/WebsiteTest.php
Labels: 5.28, merge on pass

#17951 [REF] Simplify location metadata handling in Export class
  CRM/Export/BAO/Export.php
  CRM/Export/BAO/ExportProcessor.php
  tests/phpunit/CRM/Export/BAO/ExportTest.php
Labels: has-test, master

#18060 release-notes.md - Small copy-edits
  release-notes.md
  release-notes/5.27.4.md
Labels: 5.27

#18062 Improve error handling on IPN
  CRM/Core/Payment.php
Labels: 5.28, merge on pass

#18061 [NFC] 5.27.4 Release Notes
  release-notes.md
  release-notes/5.27.4.md
Labels: 5.28

#18054 Why not make the buttons flat?
  css/civicrm.css
  i/crm-button-bg.gif
Labels: master

#18040 event#35: move statusBounce out of BAO layer; don't allow self-service when dis…
  CRM/Event/BAO/Participant.php
  CRM/Event/Form/SelfSvcTransfer.php
  CRM/Event/Form/SelfSvcUpdate.php
  tests/phpunit/CRM/Event/BAO/ParticipantTest.php
Labels: has-test, master

#17995 CRM_Utils_Hook: deprecation warning and short array syntax
  CRM/Utils/Hook.php
Labels: master

#17942 dev/core#1905 Add configure icons on public pages
  CRM/Event/Form/Registration/Register.php
  CRM/Price/BAO/PriceSet.php
  templates/CRM/Contribute/Form/Contribution/Main.tpl
  templates/CRM/Event/Form/Registration/Register.tpl
  templates/CRM/Price/Form/PriceSet.tpl
Labels: master, ok-without-test

#18063 5.28
  CRM/Core/Payment.php
  release-notes.md
  release-notes/5.27.4.md
Labels: master

#18055 [REF] remove first attempt to set currency in repeattransaction flow
  CRM/Contribute/BAO/Contribution.php
  tests/phpunit/CRM/Contribute/BAO/ContributionRecurTest.php
Labels: has-test, master

#18039 Extract code to set isEmailReceipt in Contribution.completeOrder
  CRM/Contribute/BAO/Contribution.php
Labels: master

#18064 dev/core#1905 rework #17942 with simpler ts strings
  templates/CRM/Contribute/Form/Contribution/Main.tpl
  templates/CRM/Event/Form/Registration/Register.tpl
  templates/CRM/Price/Form/PriceSet.tpl
Labels: master

#18058 [REF] Even less variable variables
  CRM/Member/BAO/MembershipStatus.php
Labels: master

#18005 Fix buggy placement of icons on buttons
  CRM/Core/Controller.php
  CRM/Core/Smarty/plugins/block.crmButton.php
  ang/crmMailingAB/EditCtrl/report.html
  ang/crmUi.js
  css/civicrm.css
  js/crm.ajax.js
  templates/CRM/Admin/Form/Preferences/Display.tpl
  templates/CRM/Admin/Page/APIExplorer.tpl
  templates/CRM/Admin/Page/CKEditorConfig.tpl
  templates/CRM/Contact/Form/Search/Custom/FullText.tpl
  templates/CRM/Event/Form/ParticipantFeeSelection.tpl
  templates/CRM/Event/Page/DashBoard.tpl
  templates/CRM/Report/Form/Actions.tpl
  templates/CRM/Tag/Page/Tag.tpl
  templates/CRM/common/formButtons.tpl
Labels: master, ok-without-test

#18066 dev/drupal#131 Ensure that the General class exists
  Civi/Install/Requirements.php
Labels: 5.28, merge on pass

#18056 Use correct pdf package to generate pdf file on invoice download/email activity
  CRM/Contribute/Form/Task/Invoice.php
Labels: master

#18070 dev/core#1927 Ensure that the contents of the database table are fixe…
  CRM/Upgrade/Incremental/php/FiveTwentyEight.php
Labels: 5.28, merge on pass

#18069 5.28
  CRM/Upgrade/Incremental/php/FiveTwentyEight.php
  Civi/Install/Requirements.php
Labels: master

#18065 Show cron warning on Scheduled Jobs admin page
  CRM/Admin/Page/Job.php
  CRM/Utils/Check/Component/Env.php
  CRM/Utils/REST.php
  CRM/Utils/System.php
  Civi/Api4/Generic/Traits/ArrayQueryActionTrait.php
Labels: master, merge on pass

#18049 Refactor "applyLocale" and remove references to "language" column in UFMatch table
  CRM/Admin/Form/Setting/Localization.php
  CRM/Core/BAO/ConfigSetting.php
Labels: master

#18072 dev/financial#135 Remove unreachable doDirectPayment from manual processor
  CRM/Core/Payment/Manual.php
Labels: master

#18071 Do not pass-by-reference to recur function
  CRM/Core/Payment/AuthorizeNetIPN.php
Labels: master

#17981 [REF] Move handling of form elements back to the Form
  CRM/Contact/Form/Merge.php
  CRM/Dedupe/Merger.php
Labels: master

#18073 [NFC] Fix provider unit test on PHP7.4
  tests/phpunit/CiviTest/CiviTestSMSProvider.php
Labels: has-test, master, merge on pass

#18074 5.28.0 release notes final edits
  release-notes/5.28.0.md
Labels: 5.28

#18000 Fix button name on updated form
  CRM/Contribute/Form/Task/Status.php
Labels: master

#18077 5.28
  release-notes/5.28.0.md
Labels: master

#18078 dev/financial#135 Remove stub function from payflowPro
  CRM/Core/Payment/PayflowPro.php
Labels: master

#18079 dev/core#1930 fix for move-related checkbox being overridden to true …
  CRM/Contact/Form/Merge.php
Labels: 5.28, merge on pass, ok-without-test

#18082 5.28
  CRM/Contact/Form/Merge.php
Labels: master, merge on pass

#18081 5.28
  CRM/Contact/Form/Merge.php
Labels: master

#18083 (NFC) 5.28.0.md - Describe last minute PR. Random copyedits.
  release-notes/5.28.0.md
Labels: 5.28

#18084 5.28
  release-notes/5.28.0.md
Labels: master

#18080 dev/core#1928 Fix HTML5 error due to required attribute being set swi…
  CRM/Core/Form.php
Labels: master, merge on pass

#18027 [REF] Deploy Pear DB package using composer
  composer.json
  composer.lock
Labels: master, merge ready, ok-without-test

#18085 dev/core#1932 - Make status-checks more polite during upgrade
  CRM/Utils/Check/Component.php
  CRM/Utils/Check/Component/Env.php
  CRM/Utils/Check/Component/OptionGroups.php
  CRM/Utils/Check/Message.php
Labels: 5.29

#18089 APIv4 Explorer: Generate short cv code
  ang/api4Explorer/Explorer.js
Labels: master, merge on pass, ok-without-test

#18088 dev/core#1905 force backend links for new "configure" buttons
  templates/CRM/Contribute/Form/Contribution/Main.tpl
  templates/CRM/Event/Form/Registration/Register.tpl
  templates/CRM/Price/Form/PriceSet.tpl
Labels: 5.29, merge on pass, ok-without-test

#17950 dev/core#1895 fix first/last name adv search
  CRM/Contact/Form/Search/Criteria.php
  templates/CRM/Contact/Form/Search/Criteria/Basic.tpl
  templates/CRM/Contact/Form/Search/Criteria/Fields/sort_name.tpl
Labels: 5.29, merge on pass, ok-without-test

#18090 5.29
  CRM/Contact/Form/Search/Criteria.php
  CRM/Utils/Check/Component.php
  CRM/Utils/Check/Component/Env.php
  CRM/Utils/Check/Component/OptionGroups.php
  CRM/Utils/Check/Message.php
  templates/CRM/Contact/Form/Search/Criteria/Basic.tpl
  templates/CRM/Contact/Form/Search/Criteria/Fields/sort_name.tpl
  templates/CRM/Contribute/Form/Contribution/Main.tpl
  templates/CRM/Event/Form/Registration/Register.tpl
  templates/CRM/Price/Form/PriceSet.tpl
Labels: master

#18047 [REF] Fix metadata label for contribution_page_id
  CRM/Contribute/DAO/Contribution.php
  templates/CRM/Contribute/Form/Search/Common.tpl
  xml/schema/Contribute/Contribution.xml
Labels: master

#17934 [REF] Update subtypeInfo function to leverage getAllContactTypes
  CRM/Contact/BAO/ContactType.php
  tests/phpunit/CRM/Contact/BAO/ContactType/ContactTypeTest.php
Labels: has-test, master

#18093 APIv4 Explorer - Fix possible undefined index
  ang/api4Explorer/Explorer.js
Labels: master, merge on pass

#17919 [NFC] Update locale over-ride documentation to mention that it is mos…
  templates/CRM/common/civicrm.settings.php.template
Labels: master

#18092 [REF] Fix jquery validation for on behalf of fields when combined wit…
  templates/CRM/Contribute/Form/Contribution/PremiumBlock.tpl
Labels: 5.29

#18098 5.29 to master
  templates/CRM/Contribute/Form/Contribution/PremiumBlock.tpl
Labels: master

#18097 There is no "I" in mysqli - oh wait there is
  templates/CRM/common/civicrm.settings.php.template
Labels: master, merge on pass

#18068 dev/wordpress#66 Re-instate newer variables but with more support for…
  CRM/Utils/System/WordPress.php
Labels: 5.29

#18100 5.29
  CRM/Utils/System/WordPress.php
Labels: master

#18099 [REF] Fix jquery validation for on behalf of fields when combined wit…
  templates/CRM/Contribute/Form/Contribution/PremiumBlock.tpl
Labels: 5.28

#18101 dev/event#40 - EventCart - Check legacy setting until extension is public
  ext/eventcart/eventcart.php
Labels: 5.29, merge on pass

#18102 [REF] Fix jquery validation for on behalf of fields when combined wit…
  templates/CRM/Contribute/Form/Contribution/OnBehalfOf.tpl
  templates/CRM/Contribute/Form/Contribution/PremiumBlock.tpl
  templates/CRM/common/l10n.js.tpl
Labels: 5.27, merge on pass

#18104 5.29
  ext/eventcart/eventcart.php
Labels: master

#18108 Remove unused variable
  ext/eventcart/CRM/Event/Cart/StateMachine/Checkout.php
Labels: master, merge on pass, sig:code maintenance readability testability

#18109 [NFC] Array formatting
  CRM/Event/Form/Registration.php
Labels: master, merge on pass

#18110 Add Serialize key to payment_processor field for Event & Contribution Page
  CRM/Contribute/DAO/ContributionPage.php
  CRM/Contribute/Form/ContributionPage/Amount.php
  CRM/Event/DAO/Event.php
  CRM/Event/Form/ManageEvent/Fee.php
  xml/schema/Contribute/ContributionPage.xml
  xml/schema/Event/Event.xml
Labels: master, merge on pass, sig:code maintenance readability testability

#18112 [NFC] [Test] Initial testing on event payment forms.
  tests/phpunit/CRM/Core/Payment/AuthorizeNetTest.php
  tests/phpunit/CRM/Core/Payment/AuthorizeNetTrait.php
  tests/phpunit/CRM/Financial/Form/PaymentFormsTest.php
  tests/phpunit/CRM/Mailing/Form/Task/AdhocMailingTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: has-test, master, merge on pass

#18091 Swap out button/submit inputs for button elements
  CRM/Admin/Form/Preferences/Display.php
  CRM/Admin/Form/Setting/Smtp.php
  CRM/Batch/Form/Entry.php
  CRM/Case/Form/CaseView.php
  CRM/Contact/Form/Contact.php
  CRM/Contact/Form/Search.php
  CRM/Contact/Form/Task/AddToParentClass.php
  CRM/Contribute/Form/ContributionPage.php
  CRM/Contribute/Form/ContributionPage/Widget.php
  CRM/Contribute/Import/Form/DataSource.php
  CRM/Core/BAO/Mapping.php
  CRM/Core/Form.php
  CRM/Custom/Form/Field.php
  CRM/Custom/Form/Group.php
  CRM/Custom/Form/Option.php
  CRM/Event/Form/ManageEvent/Fee.php
  CRM/Financial/Form/BatchTransaction.php
  CRM/Financial/Form/Search.php
  CRM/Price/Form/Field.php
  CRM/Profile/Form.php
  CRM/Profile/Form/Edit.php
  CRM/Report/Form.php
  CRM/UF/Form/Field.php
  CRM/UF/Form/Group.php
  css/civicrm.css
  css/joomla.css
  install/template.html
  js/Common.js
  js/crm.ajax.js
  js/crm.searchForm.js
  js/jquery/jquery.dashboard.js
  setup/plugins/blocks/advanced.tpl.php
  setup/plugins/blocks/install.tpl.php
  setup/plugins/blocks/requirements.tpl.php
  setup/res/template.css
  setup/src/Setup/UI/SetupController.php
  templates/CRM/Admin/Form/Preferences/Display.tpl
  templates/CRM/Admin/Page/APIExplorer.tpl
  templates/CRM/Admin/Page/CKEditorConfig.tpl
  templates/CRM/Batch/Form/Entry.tpl
  templates/CRM/Block/Add.tpl
  templates/CRM/Block/FullTextSearch.tpl
  templates/CRM/Contact/Form/Contact.tpl
  templates/CRM/Contact/Form/Search/Builder.js
  templates/CRM/Contact/Page/View/Print.tpl
  templates/CRM/Contribute/Form/Contribution/PremiumBlock.tpl
  templates/CRM/Event/Form/ManageEvent/Registration.tpl
  templates/CRM/Mailing/Page/Event.tpl
  templates/CRM/Mailing/Page/Resubscribe.tpl
  templates/CRM/Profile/Form/Dynamic.tpl
  templates/CRM/Report/Form/Layout/Graph.tpl
  templates/CRM/common/TabHeader.js
  templates/CRM/common/deferredFinancialType.tpl
  templates/CRM/common/formButtons.tpl
  templates/CRM/common/navigation.js.tpl
Labels: 5.29

#18117 5.29 to master
  CRM/Admin/Form/Preferences/Display.php
  CRM/Admin/Form/Setting/Smtp.php
  CRM/Batch/Form/Entry.php
  CRM/Case/Form/CaseView.php
  CRM/Contact/Form/Contact.php
  CRM/Contact/Form/Search.php
  CRM/Contact/Form/Task/AddToParentClass.php
  CRM/Contribute/Form/ContributionPage.php
  CRM/Contribute/Form/ContributionPage/Widget.php
  CRM/Contribute/Import/Form/DataSource.php
  CRM/Core/BAO/Mapping.php
  CRM/Core/Form.php
  CRM/Custom/Form/Field.php
  CRM/Custom/Form/Group.php
  CRM/Custom/Form/Option.php
  CRM/Event/Form/ManageEvent/Fee.php
  CRM/Financial/Form/BatchTransaction.php
  CRM/Financial/Form/Search.php
  CRM/Price/Form/Field.php
  CRM/Profile/Form.php
  CRM/Profile/Form/Edit.php
  CRM/Report/Form.php
  CRM/UF/Form/Field.php
  CRM/UF/Form/Group.php
  css/civicrm.css
  css/joomla.css
  install/template.html
  js/Common.js
  js/crm.ajax.js
  js/crm.searchForm.js
  js/jquery/jquery.dashboard.js
  setup/plugins/blocks/advanced.tpl.php
  setup/plugins/blocks/install.tpl.php
  setup/plugins/blocks/requirements.tpl.php
  setup/res/template.css
  setup/src/Setup/UI/SetupController.php
  templates/CRM/Admin/Form/Preferences/Display.tpl
  templates/CRM/Admin/Page/APIExplorer.tpl
  templates/CRM/Admin/Page/CKEditorConfig.tpl
  templates/CRM/Batch/Form/Entry.tpl
  templates/CRM/Block/Add.tpl
  templates/CRM/Block/FullTextSearch.tpl
  templates/CRM/Contact/Form/Contact.tpl
  templates/CRM/Contact/Form/Search/Builder.js
  templates/CRM/Contact/Page/View/Print.tpl
  templates/CRM/Contribute/Form/Contribution/PremiumBlock.tpl
  templates/CRM/Event/Form/ManageEvent/Registration.tpl
  templates/CRM/Mailing/Page/Event.tpl
  templates/CRM/Mailing/Page/Resubscribe.tpl
  templates/CRM/Profile/Form/Dynamic.tpl
  templates/CRM/Report/Form/Layout/Graph.tpl
  templates/CRM/common/TabHeader.js
  templates/CRM/common/deferredFinancialType.tpl
  templates/CRM/common/formButtons.tpl
  templates/CRM/common/navigation.js.tpl
Labels: master

#18115 dev/core#1943 add functionality to add civicrm log into Drupal access log
  CRM/Core/Error.php
Labels: master

#18119 [NFC] Add code comments about hidden but still used buttons
  CRM/Case/Form/CaseView.php
  templates/CRM/Case/Form/CaseView.tpl
Labels: master, merge on pass

#18116 Fix PHP notice on contribution page
  CRM/Contribute/Form/ContributionPage/Amount.php
Labels: master

#18095 dev/core#1926 - Towards supporting SSL for mysql connections - remove DB::connect that doesn't add anything
  CRM/Utils/System.php
Labels: master

#18123 dev/core#1936 Make the price field value label field not required
  CRM/Core/I18n/SchemaStructure.php
  CRM/Price/DAO/PriceFieldValue.php
  CRM/Upgrade/Incremental/php/FiveTwentyNine.php
  Civi/Api4/Service/Spec/Provider/PriceFieldValueCreationSpecProvider.php
  tests/phpunit/CRM/Price/BAO/PriceFieldValueTest.php
  xml/schema/Price/PriceFieldValue.xml
Labels: 5.29, merge on pass

#18127 dev/core#1936 Make the label column on price_field_value table not re…
  CRM/Core/I18n/SchemaStructure.php
  CRM/Price/DAO/PriceFieldValue.php
  CRM/Upgrade/Incremental/php/FiveTwentyEight.php
  Civi/Api4/Service/Spec/Provider/PriceFieldValueCreationSpecProvider.php
  tests/phpunit/CRM/Price/BAO/PriceFieldValueTest.php
  xml/schema/Price/PriceFieldValue.xml
Labels: 5.28, merge on pass

#18126 dev/core#1934 fix regression on merging contacts with settings using contact_id
  CRM/Dedupe/Merger.php
Labels: 5.29, merge on pass

#18124 dev/core#1936 Make the label field on price_field_value non required …
  CRM/Core/I18n/SchemaStructure.php
  CRM/Price/DAO/PriceFieldValue.php
  CRM/Upgrade/Incremental/php/FiveTwentySeven.php
  Civi/Api4/Service/Spec/Provider/PriceFieldValueCreationSpecProvider.php
  tests/phpunit/CRM/Price/BAO/PriceFieldValueTest.php
  xml/schema/Price/PriceFieldValue.xml
Labels: 5.27, merge on pass

#18129 dev/core#1934 fix regression on merging contacts with settings using …
  CRM/Dedupe/Merger.php
Labels: 5.28, merge on pass

#18128 5.29
  CRM/Core/I18n/SchemaStructure.php
  CRM/Dedupe/Merger.php
  CRM/Price/DAO/PriceFieldValue.php
  CRM/Upgrade/Incremental/php/FiveTwentyNine.php
  Civi/Api4/Service/Spec/Provider/PriceFieldValueCreationSpecProvider.php
  tests/phpunit/CRM/Price/BAO/PriceFieldValueTest.php
  xml/schema/Price/PriceFieldValue.xml
Labels: master

#18130 dev/core#1934 fix regression on merging contacts with settings using contact_id
  CRM/Dedupe/Merger.php
Labels: 5.27, merge on pass

#18094 CodeGen - Add use statement to extensions DAO files
  CRM/Core/CodeGen/DAO.php
  CRM/Core/CodeGen/Util/Template.php
  xml/templates/dao.tpl
Labels: master, merge on pass

#18132 (dev/core#1944) Add new columns to mailing summary report
  CRM/Report/Form/Mailing/Summary.php
Labels: master

#18134 Deprecate/remove unused checkVersion() functions
  CRM/Core/DAO.php
  CRM/Upgrade/Form.php
Labels: master

#18131 [REF] Move isSSLDSN() function to avoid potential problems
  CRM/Core/DAO.php
  CRM/Utils/SQL.php
  tests/phpunit/CRM/Utils/SQLTest.php
Labels: master

#17956 dev/core#1661 Allow phones with types longer than 16 chars to export
  CRM/Contact/BAO/Contact.php
  CRM/Contact/BAO/Query.php
  CRM/Core/DAO/Phone.php
  CRM/Export/BAO/ExportProcessor.php
  tests/phpunit/CRM/Export/BAO/ExportTest.php
  xml/schema/Core/Phone.xml
Labels: has-test, master

#18139 (REF) CRM_Core_Region - Remove unused bits
  CRM/Core/Region.php
Labels: master

#18138 Deprecate 'trapException' in DAO::executeQuery
  CRM/Core/DAO.php
  CRM/Core/PrevNextCache/Sql.php
Labels: master

#18144 dev/core#1953 Ensure that Contribution pages do not fail validation o…
  CRM/Core/Payment.php
  CRM/Core/Payment/Form.php
  templates/CRM/Core/BillingBlock.tpl
Labels: 5.29, merge on pass

#18145 dev/core#1953 Ensure that Contribution pages do not fail validation o…
  CRM/Core/Payment.php
  CRM/Core/Payment/Form.php
  templates/CRM/Core/BillingBlock.tpl
Labels: 5.28, merge on pass

#18149 dev/core#1952 Remove uncessary component checking when exporting all …
  CRM/Activity/Form/Task.php
Labels: 5.29

#18151 Use more appropriate money format function
  CRM/Campaign/Form/Campaign.php
Labels: master, merge on pass

#18148 5.29
  CRM/Activity/Form/Task.php
  CRM/Core/Payment.php
  CRM/Core/Payment/Form.php
  templates/CRM/Core/BillingBlock.tpl
Labels: master

#18142 [REF] Remove usages of CRM_Utils_Money::format that pass in a blank s…
  CRM/Contribute/BAO/Query.php
  CRM/Contribute/Form/ContributionPage/Amount.php
  CRM/Contribute/Form/ContributionPage/Settings.php
  CRM/Event/Form/ManageEvent/Fee.php
  CRM/Grant/BAO/Query.php
  CRM/Pledge/BAO/Query.php
  CRM/Report/Form/Contribute/History.php
Labels: master, merge on pass

#18152 dev/core#1952 Remove uncessary component checking when exporting all …
  CRM/Activity/Form/Task.php
Labels: 5.28, merge on pass

#18156 Remove deprecated code ids['userId']
  CRM/Member/BAO/Membership.php
Labels: master

#18155 Remove legacy handling for 'fixing' line_item.entity_id
  CRM/Price/BAO/LineItem.php
  tests/phpunit/CRMTraits/Financial/OrderTrait.php
  tests/phpunit/api/v3/MembershipTest.php
Labels: master

#18133 Fix 5.29 (unreleased) regression using temp tables
  CRM/Core/BAO/SchemaHandler.php
  CRM/Utils/SQL/TempTable.php
  tests/phpunit/api/v3/ReportTemplateTest.php
Labels: 5.29, has-test

#18159 5.29
  CRM/Core/BAO/SchemaHandler.php
  CRM/Utils/SQL/TempTable.php
  tests/phpunit/api/v3/ReportTemplateTest.php
Labels: master

#18163 [REF] Remove unnecessary comma
  CRM/Core/Payment.php
Labels: 5.29, merge on pass

#18164 [REF] Remove unnecessary comma
  CRM/Core/Payment.php
Labels: 5.28, merge on pass

#18157 Replace CRM_Utils_Array::value in contribution/confirm and bao/membership
  CRM/Contribute/Form/Contribution/Confirm.php
  CRM/Member/BAO/Membership.php
Labels: master, merge on pass, sig-Refactor

#18165 5.29
  CRM/Core/Payment.php
Labels: master

#18172 [REF] Update recent replacement for CRM_Utils_Array::value
  CRM/Contribute/Form/Contribution/Confirm.php
  CRM/Member/BAO/Membership.php
Labels: master

#18154 Mass SMS: Limit group selection to mailing groups
  CRM/SMS/Form/Group.php
Labels: master

#18166 cvv required html attribute should depend on backoffice setting
  CRM/Core/Payment.php
Labels: 5.29

#18167 cvv required html attribute should depend on backoffice setting
  CRM/Core/Payment.php
Labels: 5.28

#18171 [REF] Deprecate unused SQL temptable functions
  CRM/Utils/SQL/TempTable.php
Labels: master

#18170 Minor cleanup in test class
  tests/phpunit/api/v3/MembershipTypeTest.php
Labels: has-test, master

#18175 Installation doclinks not getting url-rewritten
  CRM/Utils/System.php
Labels: 5.29, merge on pass

#18176 {contribution.receipt_date} token does not use any CiviCRM date formatter, output in YYYY-MM-DD HH:MM:SS format and {contribution.receive_date} also uses a non-standard format
  CRM/Utils/Token.php
  tests/phpunit/CRM/Contribute/BAO/ContributionTest.php
Labels: has-test, master, merge on pass

#18173 5.29
  CRM/Core/Payment.php
  CRM/Utils/System.php
Labels: master

#18177 Processors - remove gross_amount param from processors
  CRM/Core/Payment/AuthorizeNet.php
  CRM/Core/Payment/Dummy.php
  CRM/Core/Payment/PayJunction.php
  CRM/Core/Payment/PayPalImpl.php
  CRM/Core/Payment/Realex.php
  CRM/Core/Payment/eWAY.php
Labels: master

#18181 Upgrade screen - show success instead of error if already upgraded
  CRM/Upgrade/Page/Upgrade.php
Labels: master, merge on pass

#18169 E_WARNING when saving event fees admin page if there's no discounts set
  CRM/Event/Form/ManageEvent/Fee.php
Labels: master
