Repository civicrm/civicrm-core, pull requests merged in 2020-12, with the labels that each got.

#19078 [NFC] Add in an Emoji test for APIv3 as per Eileen's PR
  tests/phpunit/api/v3/ContactTest.php
Labels: master

#19084 dev/drupal#148 Fix product form such that it is possible to unseletc …
  CRM/Contribute/Form/ManagePremiums.php
Labels: 5.32, merge on pass

#19082 dev/core#1790: Add short delay before closing tooltip elements
  js/Common.js
Labels: master

#19087 5.32
  CRM/Contribute/Form/ManagePremiums.php
Labels: master

#19053 Afform - Update fields and HTML mode in web-based editors
  CRM/Utils/Monaco.php
  Civi/Angular/Manager.php
  ang/crmMonaco.ang.php
  ang/crmMonaco.css
  ang/crmMonaco.js
  composer.json
  ext/afform/core/Civi/Api4/Action/Afform/Convert.php
  ext/afform/core/Civi/Api4/Afform.php
  ext/afform/core/afform.php
  ext/afform/gui/ang/afGuiEditor.ang.php
  ext/afform/gui/ang/afGuiEditor.css
  ext/afform/gui/ang/afGuiEditor.js
  ext/afform/gui/ang/afGuiEditor/canvas.html
  ext/afform/gui/ang/afGuiEditor/config-form.html
  ext/afform/html/afform_html.php
  ext/afform/html/ang/afHtmlAdmin.aff.html
  ext/afform/html/ang/afHtmlEditor.aff.html
  ext/afform/html/ang/afMonaco.ang.php
  ext/afform/html/ang/afMonaco.css
  ext/afform/mock/tests/phpunit/api/v4/AfformTest.php
Labels: has-test, master

#19088 Ensure that the is_deleted filter is added correctly if we are not se…
  CRM/Contact/BAO/Query.php
  tests/phpunit/CRM/Contact/BAO/QueryTest.php
  tests/phpunit/CRM/Contact/SelectorTest.php
Labels: 5.32, has-test, merge on pass

#19014 dev/core#927 Add test demonstrating that an extraneous activity is being created & fix
  CRM/Contribute/BAO/Contribution.php
  ext/contributioncancelactions/contributioncancelactions.php
  ext/contributioncancelactions/tests/phpunit/CancelTest.php
  tests/phpunit/CRM/Member/Form/MembershipTest.php
  tests/phpunit/CRMTraits/Financial/OrderTrait.php
  tests/phpunit/api/v3/MembershipTest.php
Labels: master

#19090 5.32
  CRM/Contact/BAO/Query.php
  tests/phpunit/CRM/Contact/BAO/QueryTest.php
  tests/phpunit/CRM/Contact/SelectorTest.php
Labels: master

#19091 Fix fatal error on payment edit form
  CRM/Financial/Form/PaymentEdit.php
Labels: 5.32, merge on pass

#19092 dev/core#2228 Fix issue where by changing location type tries to pass…
  ang/crmMailing/EditRecipOptionsDialogCtrl.html
  ang/crmMailingAB/BlockMailing.html
  ang/crmMailingAB/ListCtrl.html
Labels: 5.32

#19094 (NFC) release-notes/5.32.0 - Add RC-stage updates
  release-notes/5.32.0.md
Labels: 5.32

#19093 5.32
  CRM/Financial/Form/PaymentEdit.php
  ang/crmMailing/EditRecipOptionsDialogCtrl.html
  ang/crmMailingAB/BlockMailing.html
  ang/crmMailingAB/ListCtrl.html
  release-notes/5.32.0.md
Labels: master

#19067 Quick fix on summary actions conflict
  CRM/Contact/BAO/Contact.php
  tests/phpunit/CRM/Contact/Form/Search/CriteriaTest.php
Labels: master

#18939 Fix updating custom field schema when toggling search or multiple
  CRM/Core/BAO/CustomField.php
  CRM/Core/BAO/SchemaHandler.php
  tests/phpunit/CRM/Core/BAO/SchemaHandlerTest.php
  tests/phpunit/api/v4/Action/CustomFieldAlterTest.php
Labels: has-test, master

#19095 Issue#537: Fix syntax to check pcp_id is NULL in api params
  CRM/Contribute/Form/Contribution.php
Labels: master

#19102 [REF] use early return for errors rather than confusing assignment
  CRM/Contact/Import/Parser/Contact.php
Labels: master, merge on pass

#19101 Improve APIv4 metadata for RelationshipCache and Bridge entities in general
  CRM/Contact/DAO/RelationshipCache.php
  CRM/Core/DAO.php
  Civi/Api4/Entity.php
  Civi/Api4/Generic/AbstractEntity.php
  Civi/Api4/Generic/DAOEntity.php
  Civi/Api4/Generic/Traits/EntityBridge.php
  Civi/Api4/GroupContact.php
  Civi/Api4/RelationshipCache.php
  Civi/Api4/Utils/ReflectionUtils.php
  xml/schema/Contact/RelationshipCache.xml
Labels: 5.33

#19098 [REF] Duplicate possibly-used parts of createProfileContact onto Parser_Contact
  CRM/Contact/Import/Parser/Contact.php
Labels: has-test, master, merge on pass

#19104 Unable to export contacts in Civi 5.32+
  CRM/Export/BAO/ExportProcessor.php
Labels: 5.33

#19108 Remove obsolete IF
  CRM/Contact/Import/Parser/Contact.php
Labels: master, merge on pass

#19107 Unhide oauth extension
  ext/oauth-client/info.xml
Labels: 5.33, merge on pass

#19112 Potential fix for 5.32+ unable to export contacts
  CRM/Export/BAO/ExportProcessor.php
Labels: 5.32, merge on pass

#19072 dev/financial#157 [REF] Extract functions
  CRM/Admin/Form/PaymentProcessor.php
Labels: master

#19066 Fix dev/core#2215 & remove the tab selection inline script from TabHeader.tpl
  CRM/Admin/Page/MessageTemplates.php
  CRM/Core/Form.php
  templates/CRM/Admin/Page/MessageTemplates.tpl
  templates/CRM/common/TabHeader.tpl
  templates/CRM/common/TabSelected.tpl
  tests/phpunit/CRM/Contribute/Form/ContributionTest.php
Labels: master

#19103 [REF] Extract duplicate handling code
  CRM/Contact/Import/Parser/Contact.php
  tests/phpunit/CRM/Contact/Import/Parser/ContactTest.php
Labels: master, merge on pass

#19083 Add ContributionSoft v4 api
  Civi/Api4/ContributionSoft.php
  tests/phpunit/api/v4/DataSets/ConformanceTest.json
  tests/phpunit/api/v4/Entity/ConformanceTest.php
Labels: master

#19061 Prevent "add_action" from being called multiple times
  CRM/Utils/System/WordPress.php
Labels: master, merge ready

#19105 Search Kit: Support robust joins in UI
  ext/search/CRM/Search/Page/Admin.php
  ext/search/Civi/Search/Admin.php
  ext/search/ang/crmSearchAdmin.ang.php
  ext/search/ang/crmSearchAdmin.module.js
  ext/search/ang/crmSearchAdmin/compose/criteria.html
  ext/search/ang/crmSearchAdmin/crmSearchAdmin.component.js
  ext/search/ang/crmSearchAdmin/searchList.controller.js
Labels: 5.33

#19119 dev/core#2231 fix failure to calculate next_scheduled_date
  CRM/Contribute/BAO/Contribution.php
  CRM/Contribute/BAO/ContributionRecur.php
Labels: 5.33, merge on pass

#19123 dev/core#2188 - Upgrader - Cleanup any invalid combinations of is_search_range
  CRM/Upgrade/Incremental/sql/5.33.beta2.mysql.tpl
  sql/civicrm_generated.mysql
  sql/test_data_second_domain.mysql
  xml/version.xml
Labels: 5.33

#19124 dev/core#2231 - Fix failure to calculate next_scheduled_date
  CRM/Contribute/BAO/Contribution.php
  CRM/Contribute/BAO/ContributionRecur.php
Labels: 5.32, merge on pass

#19121 dev/core#2188 fix default 'is searchable' to prevent breaking advanced search
  CRM/Custom/Form/Field.php
  CRM/Upgrade/Incremental/sql/5.32.1.mysql.tpl
  sql/civicrm_generated.mysql
  sql/test_data_second_domain.mysql
  xml/version.xml
Labels: 5.32, merge on pass

#19128 (NFC) Add release-notes/5.32.1
  release-notes.md
  release-notes/5.32.1.md
Labels: 5.32

#19130 Fix extensions tabs following deprecation of old tab code
  CRM/Admin/Page/Extensions.php
Labels: master, merge on pass

#19129 Allow Sendconfirmation api to override pay later receipt text
  CRM/Contribute/BAO/Contribution.php
  api/v3/Contribution.php
  tests/phpunit/api/v3/ContributionTest.php
Labels: has-test, master

#18096 Allow overriding participant_status_id in Order API
  CRM/Event/BAO/ParticipantStatusType.php
  api/v3/Order.php
  tests/phpunit/api/v3/OrderTest.php
Labels: has-test, master, merge on pass

#19131 dev/core#2234 - Don't display the word 'null' after adding a new tagset
  templates/CRM/Tag/Page/Tag.tpl
Labels: master

#19132 5.33
  CRM/Contact/DAO/RelationshipCache.php
  CRM/Contribute/BAO/Contribution.php
  CRM/Contribute/BAO/ContributionRecur.php
  CRM/Core/DAO.php
  CRM/Export/BAO/ExportProcessor.php
  CRM/Upgrade/Incremental/sql/5.33.beta2.mysql.tpl
  Civi/Api4/Entity.php
  Civi/Api4/Generic/AbstractEntity.php
  Civi/Api4/Generic/DAOEntity.php
  Civi/Api4/Generic/Traits/EntityBridge.php
  Civi/Api4/GroupContact.php
  Civi/Api4/RelationshipCache.php
  Civi/Api4/Utils/ReflectionUtils.php
  ext/oauth-client/info.xml
  ext/search/CRM/Search/Page/Admin.php
  ext/search/Civi/Search/Admin.php
  ext/search/ang/crmSearchAdmin.ang.php
  ext/search/ang/crmSearchAdmin.module.js
  ext/search/ang/crmSearchAdmin/compose/criteria.html
  ext/search/ang/crmSearchAdmin/crmSearchAdmin.component.js
  ext/search/ang/crmSearchAdmin/searchList.controller.js
  xml/schema/Contact/RelationshipCache.xml
Labels: master

#19086 CIVICRM-1617: Only make line_item array if it doesn't exist already.
  CRM/Contribute/BAO/Contribution.php
Labels: master

#19134 Fix mglaman mapping
  contributor-key.yml
Labels: 5.33, merge on pass

#19137 Manage Event: avoid E_NOTICE in smarty
  CRM/Event/Form/ManageEvent/Registration.php
Labels: master

#19135 5.33
  contributor-key.yml
Labels: master

#19099 [REF] Deprecate passing a blank currecny to CRM_Utils_Money::format a…
  CRM/Core/Error.php
  CRM/Utils/Money.php
  tests/phpunit/CRM/Utils/MoneyTest.php
Labels: master, merge ready

#19139 [NFC] dev/core#2235 Fix url link to the OrderAPI Documenation
  api/v3/Contribution/Transact.php
Labels: 5.33, merge on pass

#19138 dev/core#2233 - Fix broken tabs on profiles admin page
  CRM/UF/Page/Group.php
Labels: master, merge on pass, ok-without-test

#18941 Add support for multi-value contact reference custom fields
  CRM/Core/BAO/CustomField.php
  CRM/Core/BAO/CustomGroup.php
  CRM/Core/BAO/CustomQuery.php
  CRM/Core/BAO/CustomValueTable.php
  CRM/Core/Form/Renderer.php
  CRM/Custom/Form/Field.php
  templates/CRM/Contact/Page/View/CustomDataFieldView.tpl
  templates/CRM/Custom/Form/ContactReference.tpl
  templates/CRM/Custom/Form/Field.tpl
  templates/CRM/Custom/Page/CustomDataView.tpl
  tests/phpunit/CRM/Custom/Form/FieldTest.php
  tests/phpunit/api/v4/Action/CustomFieldAlterTest.php
Labels: has-test, master, merge on pass

#19140 5.33
  api/v3/Contribution/Transact.php
Labels: master

#19142 Minor typos in schema files
  xml/templates/drop.tpl
  xml/templates/schema.tpl
Labels: master, merge on pass

#19117 Add test to check pcp notification is sent
  Civi/Api4/PCPBlock.php
  api/v3/utils.php
  tests/phpunit/CRM/Contribute/Form/ContributionTest.php
  tests/phpunit/CRMTraits/PCP/PCPTestTrait.php
  tests/phpunit/CiviTest/CiviMailUtils.php
Labels: master

#19110 Preliminary cleanup -remove unused params from function signature
  CRM/Activity/Import/Parser/Activity.php
Labels: master

#19023 Extend test to cover membership logs
  tests/phpunit/api/v3/ContributionTest.php
Labels: master

#19141 dev/core#2232 Permit hook_civicrm_container and some other prebootish…
  CRM/Upgrade/DispatchPolicy.php
  CRM/Upgrade/Form.php
Labels: 5.33, merge on pass

#19147 5.33
  CRM/Upgrade/DispatchPolicy.php
  CRM/Upgrade/Form.php
Labels: master

#19125 CiviEvent - Error registering participants via search task
  CRM/Event/Form/Participant.php
  CRM/Event/Form/Task/Register.php
  CRM/Event/Page/Tab.php
  templates/CRM/Event/Form/Task/Register.tpl
Labels: 5.33

#19127 CiviEvent - Error registering through advanced search task
  CRM/Event/Form/Participant.php
  CRM/Event/Form/Task/Register.php
  CRM/Event/Page/Tab.php
  templates/CRM/Event/Form/Task/Register.tpl
Labels: 5.32

#18995 Add pre() and post() hooks for ufgroup entity
  CRM/Core/BAO/UFGroup.php
  tests/phpunit/CRM/Core/BAO/UFGroupTest.php
Labels: has-test, master

#19148 5.33
  CRM/Event/Form/Participant.php
  CRM/Event/Form/Task/Register.php
  CRM/Event/Page/Tab.php
  templates/CRM/Event/Form/Task/Register.tpl
Labels: master

#19150 Search kit joins
  ext/search/Civi/Search/Admin.php
  ext/search/ang/crmSearchAdmin.module.js
  ext/search/ang/crmSearchAdmin/compose/criteria.html
  ext/search/ang/crmSearchAdmin/crmSearchAdmin.component.js
  ext/search/ang/crmSearchAdmin/crmSearchAdmin.html
  ext/search/ang/crmSearchAdmin/group.html
  ext/search/css/search.css
  ext/search/info.xml
Labels: 5.33

#19153 5.33
  ext/search/Civi/Search/Admin.php
  ext/search/ang/crmSearchAdmin.module.js
  ext/search/ang/crmSearchAdmin/compose/criteria.html
  ext/search/ang/crmSearchAdmin/crmSearchAdmin.component.js
  ext/search/ang/crmSearchAdmin/crmSearchAdmin.html
  ext/search/ang/crmSearchAdmin/group.html
  ext/search/css/search.css
  ext/search/info.xml
Labels: master

#19109 Remove extraneous handling duplicated from createProfileContact
  CRM/Contact/Import/Parser/Contact.php
Labels: master, merge on pass

#19149 Fix notice error on using max() with only one variable
  CRM/Utils/Pager.php
Labels: master

#19120 Handle possibility of fee_amount = ''
  CRM/Contribute/BAO/Contribution.php
Labels: 5.33

#18838 dev/core#2024 extra line item issue on membership renewal
  CRM/Member/Form/MembershipRenewal.php
  tests/phpunit/CRM/Contribute/BAO/ContributionTest.php
  tests/phpunit/CRM/Contribute/Form/ContributionTest.php
  tests/phpunit/CRM/Financial/BAO/FinancialItemTest.php
  tests/phpunit/CRM/Member/Form/MembershipRenewalTest.php
  tests/phpunit/CRM/Member/Form/MembershipTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/api/v3/ContributionPageTest.php
  tests/phpunit/api/v3/ContributionTest.php
  tests/phpunit/api/v3/LineItemTest.php
Labels: has-test, master

#19146 core#2174: Activity Summary report is missing pagination
  CRM/Report/Form/ActivitySummary.php
Labels: master

#18794 Membership BAO - do not require date fields to be passed in on update
  CRM/Member/BAO/Membership.php
  CRM/Member/Form/MembershipRenewal.php
Labels: master

#19115 APIv4 - Add "Permission.get" for listing available permissions
  CRM/Core/Permission/Backdrop.php
  CRM/Core/Permission/Base.php
  CRM/Core/Permission/Drupal.php
  CRM/Core/Permission/Drupal8.php
  CRM/Core/Permission/List.php
  CRM/Core/Permission/WordPress.php
  CRM/Utils/Hook.php
  Civi/Api4/Action/Permission/Get.php
  Civi/Api4/Permission.php
  Civi/Core/Container.php
  ext/afform/core/afform.php
  tests/phpunit/E2E/Api4/PermissionTest.php
Labels: has-test, master, merge on pass, needs-documentation

#19154 5.33
  CRM/Contribute/BAO/Contribution.php
Labels: master

#18855 [REF] Simplify membership form code towards simplifying BAO
  CRM/Member/BAO/Membership.php
  CRM/Member/Form/Membership.php
  tests/phpunit/CRM/Member/Form/MembershipTest.php
Labels: has-test, master, merge on pass

#19156 Remove some unused variables
  CRM/Mailing/Event/BAO/Forward.php
Labels: master

#19155 Remove meaningless calls to ignoreException
  CRM/Core/DAO.php
  CRM/Logging/Schema.php
Labels: master

#19158 Remove code deprecated +1 year ago - case_from_XX / case_to_XXX search parameters
  CRM/Case/BAO/Query.php
Labels: master

#19157 Add missing state for South Korea
  CRM/Upgrade/Incremental/sql/5.34.alpha1.mysql.tpl
  sql/civicrm_generated.mysql
  xml/templates/civicrm_state_province.tpl
Labels: master

#19152 financial#160 - set correct from_financial_account_id on an edited fee amount FinancialTrxn
  CRM/Contribute/BAO/Contribution.php
  tests/phpunit/CRM/Core/BAO/FinancialTrxnTest.php
Labels: has-test, master, merge on pass

#19161 Add release-notes/5.32.1
  release-notes.md
  release-notes/5.32.1.md
Labels: 5.33

#19159 APIv4 - Fix dynamic bridge joins (used by Search Kit)
  CRM/Core/DAO/AllCoreTables.php
  CRM/Core/Reference/Basic.php
  CRM/Core/Reference/Dynamic.php
  Civi/Api4/Query/Api4SelectQuery.php
  ext/search/Civi/Search/Admin.php
  tests/phpunit/api/v4/Action/FkJoinTest.php
Labels: 5.33, has-test

#18905 dev/core#2159 Handle exceptions in Mail:send class
  CRM/Utils/Mail.php
  tests/phpunit/CRM/Utils/MailTest.php
Labels: has-test, master

#19162 5.33
  CRM/Core/DAO/AllCoreTables.php
  CRM/Core/Reference/Basic.php
  CRM/Core/Reference/Dynamic.php
  Civi/Api4/Query/Api4SelectQuery.php
  ext/search/Civi/Search/Admin.php
  release-notes.md
  release-notes/5.32.1.md
  tests/phpunit/api/v4/Action/FkJoinTest.php
Labels: master

#18854 [REF] Extract function to retrieve the membership labels.
  CRM/Member/Form/Membership.php
  tests/phpunit/CRM/Member/Form/MembershipTest.php
Labels: master, merge on pass

#19017 dev/financial#152 remove determination of source
  CRM/Contribute/BAO/Contribution.php
  tests/phpunit/CRM/Core/Payment/AuthorizeNetIPNTest.php
  tests/phpunit/CRMTraits/Financial/OrderTrait.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/api/v3/ContributionTest.php
Labels: master

#19168 Remove extraneous elses
  CRM/Activity/Import/Parser/Activity.php
Labels: master

#19170 dev/core#2232 Permit hook_civicrm_container and some other prebootish…
  CRM/Upgrade/DispatchPolicy.php
  CRM/Upgrade/Form.php
Labels: 5.32

#19169 Rename internal references to contributionTypeId
  CRM/Contribute/BAO/ContributionPage.php
Labels: master

#19166 dev/financial#163 Rename / remove internal references to contributionTypeID
  CRM/Event/Form/Participant.php
  tests/phpunit/CRM/Core/Payment/AuthorizeNetTest.php
  tests/phpunit/api/v3/MembershipPaymentTest.php
  tests/phpunit/api/v3/MembershipStatusTest.php
Labels: master

#19164 Switch to non-static functions
  CRM/Member/Form.php
  CRM/Member/Form/Membership.php
  CRM/Member/Form/MembershipRenewal.php
Labels: master

#19173 dev/core#2244 Simplify and consistently apply checking of whether financial acls are enabled
  ext/financialacls/financialacls.php
Labels: 5.33, merge on pass

#19178 5.33 to master
  ext/financialacls/financialacls.php
Labels: master

#19171 Remove extraneous elses
  CRM/Contribute/Import/Parser/Contribution.php
Labels: master, merge on pass

#19175 dev/core#2244 Simplify and consistently apply checking of whether fin…
  ext/financialacls/financialacls.php
Labels: 5.32

#19167 Unused writeLegacyWarnings() in PropertyBag
  Civi/Payment/PropertyBag.php
Labels: master

#19172 [REF] extract getIdsOfMatchingContact
  CRM/Contact/Import/Parser/Contact.php
  CRM/Import/Parser.php
  tests/phpunit/CRM/Contact/Import/Parser/ContactTest.php
Labels: master, merge on pass

#19176 dev/core#2246 Fix failure to filter exports
  CRM/Export/BAO/ExportProcessor.php
Labels: 5.33, merge on pass

#19177 dev/core#2246 Fix failure to filter exports
  CRM/Export/BAO/ExportProcessor.php
Labels: 5.32, merge on pass

#19179 [NFC] Convert civi.tag-deprecated to use central function
  CRM/Contribute/BAO/Contribution.php
  CRM/Core/BAO/PrevNextCache.php
  CRM/Core/BAO/Setting.php
  CRM/Core/BAO/UFGroup.php
  CRM/Core/Form.php
  CRM/Dedupe/Merger.php
  CRM/Mailing/BAO/Mailing.php
  CRM/Member/BAO/Membership.php
  CRM/Member/BAO/Query.php
  CRM/Utils/Geocode.php
  CRM/Utils/Hook.php
Labels: master, merge on pass

#19180 5.33
  CRM/Export/BAO/ExportProcessor.php
Labels: master

#19085 dev/financial#158 change UI parts of contribution soft schema to soft credit
  CRM/Contribute/DAO/ContributionSoft.php
  xml/schema/Contribute/ContributionSoft.xml
Labels: master

#19182 Remove extraneous elses
  CRM/Contact/Import/Parser/Contact.php
Labels: master

#19184 dev/core#2248 Ensure variables are assigned to tpl for urls
  CRM/Event/Form/Participant.php
Labels: 5.32, merge on pass

#19183 dev/core#2248 Ensure variables are assigned to tpl for urls
  CRM/Event/Form/Participant.php
Labels: 5.33, merge on pass

#19186 dev/core#1019 Fix currency formatting of Total Amount on Event and Co…
  CRM/Contribute/Form/Contribution/Main.php
  CRM/Event/Form/Registration/Register.php
  templates/CRM/Price/Form/Calculate.tpl
Labels: 5.32, merge on pass

#19185 dev/core#1019 Fix currency formatting of Total Amount on Event and Contribution pages (with multi-currency form support)
  CRM/Contribute/Form/Contribution/Main.php
  CRM/Event/Form/Registration/Register.php
  templates/CRM/Price/Form/Calculate.tpl
Labels: 5.33, merge on pass

#19189 Fix failure to assign view tpl variables to view page if context=search is in the url
  CRM/Event/Page/Tab.php
Labels: 5.33

#19188 Fix failure to assign view tpl variables to view page if context=search is in the url
  CRM/Event/Page/Tab.php
Labels: 5.32

#19194 5.32.2 - Set version. Add notes.
  CRM/Upgrade/Incremental/sql/5.32.2.mysql.tpl
  release-notes.md
  release-notes/5.32.2.md
  sql/civicrm_generated.mysql
  sql/test_data_second_domain.mysql
  xml/version.xml
Labels: 5.32

#19195 Add release-notes/5.32.2.md
  release-notes.md
  release-notes/5.32.2.md
Labels: 5.33

#19191 Remove some deprecated code chunks
  CRM/Contact/Import/Parser.php
Labels: master, merge on pass

#19160 Clean up error handling in legacy functions in import parser
  CRM/Contact/Import/Parser/Contact.php
  CRM/Utils/DeprecatedUtils.php
  tests/phpunit/CRM/Contact/Import/Parser/ContactTest.php
  tests/phpunit/CRM/Utils/DeprecatedUtilsTest.php
Labels: master, merge on pass

#19192 dev/core#2232 - Upgrade UI contaminates cache via l10n-js. Consolidate isUpgradeMode().
  CRM/Core/Config.php
  CRM/Upgrade/DispatchPolicy.php
  CRM/Utils/System.php
Labels: 5.33, merge on pass

#19193 [REF] Extract determination of subscription status information
  CRM/Core/Payment/PayPalIPN.php
Labels: master, merge on pass

#19145 CRM_Core_Key - Provide more debugging hints about mismatched`qfKey`s
  CRM/Core/Key.php
  tests/phpunit/CRM/Core/KeyTest.php
Labels: master

#19187 5.33
  CRM/Contribute/Form/Contribution/Main.php
  CRM/Core/Config.php
  CRM/Event/Form/Participant.php
  CRM/Event/Form/Registration/Register.php
  CRM/Event/Page/Tab.php
  CRM/Upgrade/DispatchPolicy.php
  CRM/Utils/System.php
  release-notes.md
  release-notes/5.32.2.md
  templates/CRM/Price/Form/Calculate.tpl
Labels: master

#19197 [NFC] Update comments in CRM/Core/Key
  CRM/Core/Key.php
Labels: master

#19190 Squash 2 if clauses into 1
  CRM/Contact/Import/Parser/Contact.php
Labels: master

#19198 NFC When printing out the result of the correctly update in single va…
  tests/phpunit/api/v3/SyntaxConformanceTest.php
Labels: master

#19196 REF Allow for fields of type Blob or Mediumblob in Apiv4
  Civi/Api4/Service/Spec/FieldSpec.php
Labels: master

#19201 Enotice fix
  CRM/Contribute/BAO/Contribution.php
Labels: master

#19203 Remove unreachable code.
  CRM/Contact/Import/Parser.php
  CRM/Utils/DeprecatedUtils.php
Labels: master

#19204 Stop passing ids as reference
  CRM/Member/BAO/Membership.php
Labels: master, merge on pass

#19068 Add column created_date to action_schedule
  CRM/Core/DAO/ActionSchedule.php
  CRM/Upgrade/Incremental/php/FiveThirtyFour.php
  tests/phpunit/api/v3/SyntaxConformanceTest.php
  xml/schema/Core/ActionSchedule.xml
Labels: master, merge on pass

#19205 [REF] Move function to shared parent so MemberForm can use it too
  CRM/Member/Form.php
  CRM/Member/Form/MembershipRenewal.php
Labels: master, merge on pass

#19206 #REF Migrate the print_array smarty plugin from in packages into core…
  CRM/Core/Smarty/plugins/modifier.print_array.php
Labels: master, merge on pass

#19181 APIv4: Support relative date range input
  CRM/Utils/Date.php
  Civi/Api4/Query/Api4SelectQuery.php
  Civi/Api4/Utils/FormattingUtil.php
  tests/phpunit/api/v4/Action/DateTest.php
  tests/phpunit/api/v4/Entity/ParticipantTest.php
Labels: master

#19208 Remove some more variable variables + some test cleanup
  CRM/Member/Form/Membership.php
  Civi/Test/ContactTestTrait.php
  tests/phpunit/CRM/Member/Form/MembershipTest.php
  tests/phpunit/CRMTraits/Financial/PriceSetTrait.php
Labels: master

#19213 Remove deprecated function
  CRM/Activity/BAO/Activity.php
Labels: master

#19215 (NFC) DispatchPolicy - Add comments to docblock
  CRM/Upgrade/DispatchPolicy.php
Labels: master, merge on pass

#19212 Move processConfirm function from Utils file back to form class
  CRM/Contribute/BAO/Contribution/Utils.php
  CRM/Contribute/Form/Contribution/Confirm.php
  tests/phpunit/CRM/Contribute/Form/Contribution/ConfirmTest.php
Labels: master

#19207 [REF] Clean up on $ids['contribution']
  CRM/Member/BAO/Membership.php
Labels: master

#19019 dev/core#927 Fully remove cancel & fail from Contribution BAO
  CRM/Contribute/BAO/Contribution.php
Labels: master

#19211 Duplicate processFormContribution only Membership form
  CRM/Contribute/Form/Contribution/Confirm.php
  CRM/Member/Form/Membership.php
Labels: master, merge on pass

#19217 DispatchPolicy - Actively report any upgrade problems with hook_civicrm_permission
  CRM/Upgrade/DispatchPolicy.php
Labels: 5.33, merge on pass

#19221 5.33
  CRM/Upgrade/DispatchPolicy.php
Labels: master

#19219 Fix Invalid argument PHP warning
  CRM/Core/Reference/Dynamic.php
Labels: 5.33, merge on pass

#19222 Remove all handling related to pledge, cms user from newly separated function
  CRM/Member/Form/Membership.php
Labels: master, merge on pass

#19220 Minor code cleanup
  CRM/Contribute/Form/Contribution/Confirm.php
Labels: master, merge on pass

#19223 5.33
  CRM/Core/Reference/Dynamic.php
Labels: master

#19216 dev/core#2211 Make sure addressee field fits column
  CRM/Export/BAO/ExportProcessor.php
Labels: master, merge on pass

#19230 composer.json - Update civicrm-cxn-rpc and phpseclib
  composer.json
  composer.lock
Labels: 5.33, merge on pass

#19233 5.33
  composer.json
  composer.lock
Labels: master

#19226 Remove unused tpl assigns
  CRM/Member/Form/Membership.php
Labels: master

#19234 Only do cms account create from the one relevant place
  CRM/Contribute/Form/Contribution/Confirm.php
Labels: master

#19231 Convert previously shared function from static to non-static
  CRM/Contribute/Form/Contribution/Confirm.php
  tests/phpunit/CRM/Contribute/Form/Contribution/ConfirmTest.php
Labels: master

#19228 Remove duplicated tax assignments from copied code
  CRM/Member/Form/Membership.php
Labels: master

#19214 Remove functions from EmailCommon that were moved to the trait
  CRM/Contact/Form/Task/EmailCommon.php
Labels: master

#19240 (NFC) Fix issue reporting link to go to the corresponding `core` project.
  README.md
Labels: master

#19235 Add min-width to flex columns for responsive layout on small screens
  css/civicrm.css
  css/dashboard.css
  ext/search/ang/crmSearchAdmin/compose/criteria.html
  ext/search/css/search.css
Labels: master

#19209 Add a unique event ID so we can match pre/post Insert/Update
  CRM/Core/DAO.php
Labels: master

#19229 Search kit: Rewrite input widget to support IN sets, relative dates, BETWEEN groups, etc.
  ext/search/Civi/Search/Actions.php
  ext/search/Civi/Search/Admin.php
  ext/search/ang/crmSearchActions.ang.php
  ext/search/ang/crmSearchActions.module.js
  ext/search/ang/crmSearchActions/crmSearchActionDelete.html
  ext/search/ang/crmSearchActions/crmSearchActionUpdate.html
  ext/search/ang/crmSearchActions/crmSearchInput/boolean.html
  ext/search/ang/crmSearchActions/crmSearchInput/crmMultiSelectDate.directive.js
  ext/search/ang/crmSearchActions/crmSearchInput/crmSearchInput.component.js
  ext/search/ang/crmSearchActions/crmSearchInput/crmSearchInput.html
  ext/search/ang/crmSearchActions/crmSearchInput/crmSearchInputVal.component.js
  ext/search/ang/crmSearchActions/crmSearchInput/date.html
  ext/search/ang/crmSearchActions/crmSearchInput/entityRef.html
  ext/search/ang/crmSearchActions/crmSearchInput/integer.html
  ext/search/ang/crmSearchActions/crmSearchInput/select.html
  ext/search/ang/crmSearchActions/crmSearchInput/text.html
  ext/search/ang/crmSearchAdmin.ang.php
  ext/search/ang/crmSearchAdmin/crmSearchClause.component.js
  ext/search/ang/crmSearchAdmin/crmSearchClause.html
  ext/search/ang/crmSearchKit.ang.php
  ext/search/ang/crmSearchKit.module.js
  ext/search/ang/crmSearchKit/crmSearchValue.directive.js
  ext/search/css/search.css
Labels: master

#19237 APIv4: Normalize option list descriptions as plain text
  Civi/Api4/Service/Spec/FieldSpec.php
Labels: master

#19244 dev/core#2252 remove all handling of strict mode as it has aged out of relevance
  CRM/Core/DAO.php
  CRM/Utils/File.php
  CRM/Utils/System.php
  distmaker/utils/joomlaxml.php
  templates/CRM/common/civicrm.settings.php.template
Labels: master

#19225 Greenwich: Fix Select2 free-tagging css bug
  ext/greenwich/scss/_tweaks.scss
Labels: master

#19165 dev/financial#162 Simplify decision as to whether to use a pdf on membership emails
  CRM/Member/Form/Membership.php
Labels: master
