Repository civicrm/civicrm-core, pull requests merged in 2020-02, with the labels that each got.

#16450 [NFC] Minor test cleanup.
  tests/phpunit/CRM/Event/Form/ParticipantTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: master, merge on pass

#16452 NFC Fix TokenRow docblock
  Civi/Token/TokenRow.php
Labels: master, merge on pass

#16454 APIv4 Explorer - Better UI for defaults param
  ang/api4Explorer/Explorer.html
  ang/api4Explorer/Explorer.js
Labels: master

#16449 APIv4 - Variable substution in docblocks
  Civi/Api4/Action/Entity/Get.php
  Civi/Api4/Action/GetActions.php
  Civi/Api4/Generic/AbstractAction.php
  Civi/Api4/Generic/AbstractBatchAction.php
  Civi/Api4/Generic/AbstractCreateAction.php
  Civi/Api4/Generic/AbstractGetAction.php
  Civi/Api4/Generic/AbstractQueryAction.php
  Civi/Api4/Generic/AbstractSaveAction.php
  Civi/Api4/Generic/AbstractUpdateAction.php
  Civi/Api4/Generic/BasicBatchAction.php
  Civi/Api4/Generic/BasicCreateAction.php
  Civi/Api4/Generic/BasicGetAction.php
  Civi/Api4/Generic/BasicGetFieldsAction.php
  Civi/Api4/Generic/BasicReplaceAction.php
  Civi/Api4/Generic/BasicSaveAction.php
  Civi/Api4/Generic/BasicUpdateAction.php
  Civi/Api4/Generic/DAOCreateAction.php
  Civi/Api4/Generic/DAODeleteAction.php
  Civi/Api4/Generic/DAOGetAction.php
  Civi/Api4/Generic/DAOSaveAction.php
  Civi/Api4/Generic/DAOUpdateAction.php
  Civi/Api4/Utils/ReflectionUtils.php
  ang/api4Explorer/Explorer.html
  ang/api4Explorer/Explorer.js
  tests/phpunit/api/v4/Entity/ParticipantTest.php
  tests/phpunit/api/v4/Mock/MockV4ReflectionBase.php
  tests/phpunit/api/v4/Mock/MockV4ReflectionGrandchild.php
  tests/phpunit/api/v4/Utils/ReflectionUtilsTest.php
Labels: master

#16397 dev/core#1558 retrieve setting credit_notes_prefix as a 'real' setting.
  CRM/Contribute/BAO/Contribution.php
  api/v3/examples/Setting/GetFields.ex.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/api/v3/ContributionTest.php
Labels: master

#16446 Pass language code to CiviCRM for Wordpress
  CRM/Utils/System/WordPress.php
Labels: master

#16441 [REF] Interim code cleanup - make the usage of addPayments clearer
  CRM/Contribute/BAO/Contribution.php
  CRM/Core/BAO/CustomField.php
  CRM/Event/Form/Participant.php
  tests/phpunit/CRM/Contribute/BAO/ContributionTest.php
Labels: master

#16461 Add require_once to api3TestTrait
  Civi/Test/Api3TestTrait.php
Labels: master

#16463 Fix obscure bug
  CRM/Utils/XML.php
Labels: master

#16464 dev/core#1564 Fix category name for a/b test temporary table
  CRM/Mailing/BAO/Recipients.php
  CRM/Utils/SQL/TempTable.php
Labels: 5.22, merge on pass

#16469 5.22 to master
  CRM/Mailing/BAO/Recipients.php
  CRM/Utils/SQL/TempTable.php
Labels: master

#16458 Fix for #1573: Extra columns for Contribution Detail report.
  CRM/Report/Form.php
  CRM/Report/Form/Contribute/Detail.php
  tests/phpunit/CRM/Report/Form/Contribute/DetailTest.php
Labels: master

#16460 APIv3 - Only scan files for deprecation checks in Entity.get
  api/v3/Entity.php
  api/v3/utils.php
Labels: master

#16471 composer.json - Relax psr/log constraint. Improve D8 compatibility.
  composer.json
  composer.lock
Labels: master, merge on pass

#16466 Call hook_civicrm_copy for RecurringEntity
  CRM/Core/BAO/RecurringEntity.php
Labels: master

#16472 Revert "Remove unreachable code lines."
  CRM/Contribute/BAO/Contribution.php
  CRM/Contribute/Form/Task/Invoice.php
Labels: master

#16457 APIv4 documentation & code cleanup
  CRM/Utils/String.php
  Civi/Api4/Action/Entity/Get.php
  Civi/Api4/Action/GetActions.php
  Civi/Api4/Event/Subscriber/PostSelectQuerySubscriber.php
  Civi/Api4/Generic/AbstractAction.php
  Civi/Api4/Generic/AbstractBatchAction.php
  Civi/Api4/Generic/AbstractGetAction.php
  Civi/Api4/Generic/AbstractQueryAction.php
  Civi/Api4/Generic/AbstractSaveAction.php
  Civi/Api4/Generic/AbstractUpdateAction.php
  Civi/Api4/Generic/BasicBatchAction.php
  Civi/Api4/Generic/BasicCreateAction.php
  Civi/Api4/Generic/BasicGetAction.php
  Civi/Api4/Generic/BasicReplaceAction.php
  Civi/Api4/Generic/BasicSaveAction.php
  Civi/Api4/Generic/DAOCreateAction.php
  Civi/Api4/Generic/DAODeleteAction.php
  Civi/Api4/Generic/DAOGetAction.php
  Civi/Api4/Generic/DAOSaveAction.php
  Civi/Api4/Query/Api4SelectQuery.php
  Civi/Api4/Utils/ReflectionUtils.php
  ang/api4Explorer/Explorer.js
  tests/phpunit/api/v4/Utils/ReflectionUtilsTest.php
Labels: master

#16476 release-notes: Late changes for 5.22 release notes
  release-notes/5.22.0.md
Labels: 5.22

#16485 release-notes: Late changes for 5.22 release notes
  release-notes/5.22.0.md
Labels: master

#16486 Fix year typo.
  release-notes/5.21.1.md
Labels: master

#16459 Make php 7.3 the recommended php version
  CRM/Upgrade/Incremental/General.php
Labels: master

#13078 Improve activity query performance in Constituent Detail Report
  CRM/Report/Form/Contact/Detail.php
Labels: master, needs-test

#16483 [NFC] Skip utf8mb4 test on MySQL versions lower than 5.7
  tests/phpunit/api/v3/SystemTest.php
Labels: 5.23, merge on pass

#16489 5.23
  tests/phpunit/api/v3/SystemTest.php
Labels: master

#16490 [REF] Remove patch from dompdf cleanup script that is no longer needed
  tools/scripts/composer/dompdf-cleanup.sh
  tools/scripts/composer/patches/dompdf_no_block_level_parent_fix.patch
Labels: master

#16492 fix headers
  CRM/Core/Exception/ResourceConflictException.php
  Civi/Api4/Service/Spec/Provider/PaymentProcessorTypeCreationSpecProvider.php
  templates/CRM/common/civicrm.settings.php.template
  tests/phpunit/E2E/Extern/CliRunnerTest.php
  tests/phpunit/api/v4/Entity/ContactInterchangeTest.php
Labels: master

#16493 Remove unused code
  CRM/Core/BAO/CustomField.php
Labels: master, merge on pass

#16494 Enable jQuery validate on register/contribution forms
  templates/CRM/Contribute/Form/Contribution/Main.tpl
  templates/CRM/Event/Form/Registration/Register.tpl
Labels: master, merge on pass

#16465 Throwing API_Exception is file fails to copy when creating attachment…
  api/v3/Attachment.php
Labels: master

#16475 dev/core#1577 : Custom Group Types not filterable
  templates/CRM/Group/Form/Search.tpl
Labels: master

#16500 Remove fatal from form
  CRM/Contribute/Form/CancelSubscription.php
Labels: master, merge on pass

#16442 Fix backoffice participant partial payments to be stdised & not miscalculate net_amount
  CRM/Contribute/BAO/Contribution.php
  CRM/Event/Form/Participant.php
  CRM/Financial/BAO/Payment.php
  Civi/Test/ContactTestTrait.php
  api/v3/Participant.php
  tests/phpunit/CRM/Contribute/BAO/ContributionTest.php
  tests/phpunit/CRM/Event/Form/ParticipantTest.php
Labels: master

#16487 dev/core#1019 Calculate.tpl: fix the Total Amount currency formatting.
  templates/CRM/Price/Form/Calculate.tpl
Labels: master

#16502 remove unnecessary file
  tests/phpunit/CRMTraits/ACL/PermissionTrait.phpx
Labels: master, merge on pass

#15410 dev/cloud-native#21 Don't cache the full path of extensions so they don't break with dynamic paths
  CRM/Extension/Mapper.php
Labels: master, merge ready

#16497 (REF) Move CIVICRM_MAIL_LOG logic from patch-files to wrapper-class
  CRM/Admin/Form/Setting/Smtp.php
  CRM/Utils/Mail.php
  CRM/Utils/Mail/FilteredPearMailer.php
  CRM/Utils/Mail/Logger.php
  tests/phpunit/CRM/Utils/Mail/FilteredPearMailerTest.php
  tools/scripts/composer/patches/pear-mail.patch.txt
Labels: master, merge on pass

#16505 Add deprecation notices on PartialAmount params
  CRM/Contribute/BAO/Contribution.php
Labels: master

#16499 Added conditional check so that it can be altered by hook
  templates/CRM/Case/Audit/Report.tpl
Labels: master

#16504 dev/financial#117 - Add link metadata for payment edit link
  CRM/Contribute/BAO/Contribution.php
Labels: master

#16507 dev/core#1587 Select2 - Use description as title for each option
  js/Common.js
Labels: master

#16508 Common.js - remove duplicate function
  js/Common.js
  js/jquery/jquery.dashboard.js
Labels: master, merge on pass

#16510 crmSelect2 - fix whitespace in tooltip
  js/Common.js
Labels: master

#15859 dev/mem#17 - Deleting memberships does not delete its related line item
  CRM/Member/BAO/Membership.php
  tests/phpunit/CRM/Member/BAO/MembershipTest.php
Labels: master

#16511 API Kernel - cleanup deprecated fn & unused param
  CRM/Admin/Form/Job.php
  Civi/API/Kernel.php
  Civi/API/Request.php
  Civi/API/Subscriber/ChainSubscriber.php
  Civi/API/Subscriber/DynamicFKAuthorization.php
  tests/phpunit/Civi/API/Event/PrepareEventTest.php
  tests/phpunit/Civi/API/KernelTest.php
  tests/phpunit/Civi/API/RequestTest.php
  tests/phpunit/Civi/API/Subscriber/DynamicFKAuthorizationTest.php
  tests/phpunit/Civi/API/Subscriber/WhitelistSubscriberTest.php
  tests/phpunit/api/v3/UtilsTest.php
Labels: master

#16513 Move settings definition on contribution settings form to metadata.
  CRM/Admin/Form/Generic.php
  CRM/Admin/Form/Preferences/Contribute.php
  CRM/Admin/Form/SettingTrait.php
  settings/Contribute.setting.php
Labels: master, merge on pass

#16518 dev/mail#59 - Fix use of useXOAUTH2 constant instead of var
  CRM/Mailing/MailStore/Imap.php
Labels: 5.23

#16517 5.23.0 release notes: initial run
  release-notes.md
  release-notes/5.23.0.md
Labels: master

#16520 5.23.0 release notes
  release-notes.md
  release-notes/5.23.0.md
Labels: 5.23

#16512 Relationship report - add sort order for end date
  CRM/Report/Form/Contact/Relationship.php
Labels: master

#16522 dev/core#1562 - composer.json - Fix E2E tests run on D8 build (via "patches") #16427
  composer.json
  composer.lock
  tools/scripts/composer/patches/civicrm-custom-patches-zetacompoents-mail.patch
  tools/scripts/composer/patches/phpoffice-common-xml-entity-fix.patch
  tools/scripts/composer/patches/phpword-libxml-fix-global-handling.patch
Labels: master, merge on pass

#16477 [TEST] dev/core#1572 Unit test environment not working on windows after recent CodeGen updates
  Civi/Test.php
Labels: master

#16521 dev/core#1489 Include hook_civicrm_managed into the list of upgrade f…
  CRM/Utils/Hook.php
Labels: 5.23

#16530 5.23
  CRM/Utils/Hook.php
Labels: master

#16526 Fix calls to Request::retrieve
  CRM/Api4/Page/AJAX.php
  CRM/Contact/Page/Inline/CommunicationPreferences.php
  CRM/Contact/Page/Inline/OpenID.php
  CRM/Contact/Page/Inline/Phone.php
  CRM/Contact/Page/Inline/Website.php
  CRM/Contribute/Form/AdditionalPayment.php
  CRM/Core/BAO/ConfigSetting.php
  CRM/Core/BAO/Log.php
  CRM/Core/Page/AJAX/Location.php
  CRM/SMS/Controller/Send.php
Labels: master, merge on pass

#16534 dev/core#1551 regression fix
  CRM/Contact/BAO/Query.php
Labels: 5.23

#15330 Fix issues with retrieving supportsTestMode/supportsLiveMode for payment processors
  CRM/Contribute/Form/AbstractEditPayment.php
  CRM/Core/Form.php
  CRM/Core/Payment.php
  CRM/Core/Payment/Dummy.php
  CRM/Core/Payment/Manual.php
  CRM/Financial/BAO/PaymentProcessor.php
  tests/phpunit/CRM/Financial/BAO/PaymentProcessorTest.php
Labels: has-test, master, merge ready

#16535 dev/core#1592 fix regression on relation active period
  CRM/Contact/BAO/Query.php
Labels: 5.23, merge on pass

#16451 Settings Fix setting readonly attribute
  CRM/Admin/Form/SettingTrait.php
Labels: master

#16467 fix contribution summary report's statistics when grouping and having
  CRM/Report/Form/Contribute/Summary.php
Labels: master

#15824 Speed boost for civicrm/ajax/checkemail
  CRM/Contact/Page/AJAX.php
Labels: master

#16537 5.23
  CRM/Contact/BAO/Query.php
Labels: master

#16523 add column for report
  CRM/Report/Form/Contact/Relationship.php
Labels: master

#16516 APIv4 - merge ActionUtil with Request::create
  Civi/API/Kernel.php
  Civi/API/Request.php
  Civi/Api4/Action/GetActions.php
  Civi/Api4/Generic/AbstractAction.php
  Civi/Api4/Generic/BasicGetFieldsAction.php
  Civi/Api4/Generic/BasicReplaceAction.php
  Civi/Api4/Generic/BasicSaveAction.php
  Civi/Api4/Generic/DAOGetFieldsAction.php
  Civi/Api4/Utils/ActionUtil.php
  api/api.php
  api/v3/Contact.php
  api/v3/utils.php
  tests/phpunit/Civi/API/Subscriber/WhitelistSubscriberTest.php
  tests/phpunit/api/v3/UtilsTest.php
Labels: master

#15390 Check email when creating a user in drupal 8
  CRM/Utils/System/Drupal8.php
Labels: master

#16527 Change "Added By" to "Added by"
  CRM/Activity/Form/Activity.php
  CRM/Activity/Form/Task/Batch.php
  CRM/Activity/Selector/Activity.php
  CRM/Activity/Selector/Search.php
  CRM/Report/Form/Contact/Detail.php
  templates/CRM/Activity/Form/ActivityView.tpl
  templates/CRM/Activity/Form/Task/Print.tpl
  templates/CRM/Activity/Page/UserDashboard.tpl
  templates/CRM/Activity/Selector/Selector.tpl
  templates/CRM/Contact/Form/Search/Custom/FullText.tpl
  templates/CRM/Mailing/Page/Tab.tpl
  tests/phpunit/CRM/Activity/Selector/SearchTest.php
Labels: master

#16540 [REF] Remove never used property
  CRM/Event/Form/Participant.php
Labels: master, merge on pass

#16542 Update CONTRIBUTORS.txt
  CONTRIBUTORS.txt
Labels: 5.23

#16539 Remove reference to mysql 5.0 & 5.1
  CRM/Logging/Schema.php
  templates/CRM/Admin/Form/Setting/Localization.tpl
Labels: master, merge on pass

#15998 dev/core#1366 Bypass nonfunctioning case audit interactive screen and go straight to report
  CRM/Case/Form/Report.php
  CRM/Case/XMLProcessor/Report.php
  tests/phpunit/CRM/Case/XMLProcessor/ReportTest.php
Labels: master

#16543 dev/core#1589 avoid error when merging record with null create date
  CRM/Dedupe/Merger.php
Labels: master

#16544 dev/core#1594 [TEST] Fix running of unit tests within an extension
  Civi/Test.php
Labels: master, merge on pass

#16532 dev/core#1588 Fix regression where empty string is passed to PropertyBag
  CRM/Contribute/Form/Contribution/Confirm.php
  Civi/Payment/PropertyBag.php
Labels: 5.23

#16549 [NFC] Fix style error
  Civi/Payment/PropertyBag.php
Labels: 5.23

#16547 [NFC] Ensure that annon permissions are correctly assigned when enabl…
  tools/drupal/modules/civicrm_webtest/civicrm_webtest.install
Labels: 5.23, merge on pass

#16548 5.23
  CONTRIBUTORS.txt
  CRM/Contribute/Form/Contribution/Confirm.php
  Civi/Payment/PropertyBag.php
  tools/drupal/modules/civicrm_webtest/civicrm_webtest.install
Labels: master

#16533 Do not fatally fail on angular pages if an extension is missing
  CRM/Extension/Container/Interface.php
  CRM/Extension/Mapper.php
Labels: master

#16515 Fix a PHP notice for users with limited permissions when loading cont…
  CRM/Core/BAO/Note.php
Labels: master

#16468 REF Refactor ActivityTokens to use a trait that can be shared with other entities
  CRM/Activity/Tokens.php
  CRM/Core/TokenTrait.php
Labels: master

#16525 Allow any casting done in Type::validate to bubble up to Request::retrieveValue
  CRM/Utils/Request.php
Labels: master

#16536 dev/core#1489 Include hook_civicrm_managed into the list of upgrade freindly hooks
  CRM/Utils/Hook.php
Labels: 5.22

#16553 Backport patches for regressions merged to 5.23
  CRM/Contact/BAO/Query.php
  CRM/Contribute/Form/Contribution/Confirm.php
  Civi/Payment/PropertyBag.php
Labels: 5.22

#16554 dev/core#1593 and dev/core#1536 - Remove unused code causing E_WARNING
  templates/CRM/Tag/Form/Edit.tpl
  tests/phpunit/CRM/Core/FormTest.php
Labels: master

#16551 info.xml - Allow extensions to define a list of tags
  CRM/Extension/Info.php
  CRM/Extension/Mapper.php
  tests/extensions/test.extension.manager.moduletest/info.xml
  tests/extensions/test.extension.manager.paymenttest/info.xml
  tests/phpunit/CRM/Extension/MapperTest.php
  tests/phpunit/api/v3/ExtensionTest.php
Labels: master, merge ready

#16552 [REF] Fix static call to non-static function.
  CRM/Event/BAO/Participant.php
  CRM/Event/Form/Participant.php
Labels: master

#16498 Upgrade Net_SMTP Package and remove now unneded patches and mov…
  composer.json
  composer.lock
  tools/scripts/composer/net-smtp-fix.sh
  tools/scripts/composer/patches/net-smtp-patch.txt
  tools/scripts/composer/patches/net-smtp-php7-patch.txt
  tools/scripts/composer/patches/net-smtp-ref-patch.txt
  tools/scripts/composer/patches/net-smtp-tls-patch.txt
Labels: master, merge on pass

#16557 [NFC] Preliminary cleanup
  CRM/Dedupe/BAO/Rule.php
  CRM/Dedupe/Finder.php
  tests/phpunit/CRM/Dedupe/DedupeFinderTest.php
Labels: master, merge on pass

#15856 dev/financial#104 Use rounding and integers to compare monetary values…
  CRM/Utils/Money.php
  tests/phpunit/CRM/Utils/MoneyTest.php
Labels: master

#14928 dev/core#1158 mailing labels: explicitly set primary flag
  CRM/Contact/Form/Task/Label.php
Labels: master, needs-test

#16455 core#1568: Show recipientListing to non-admins
  CRM/Core/xml/Menu/Admin.xml
Labels: master

#16491 Resolve notices if first donation amount and date columns were disabled
  CRM/Report/Form/Member/ContributionDetail.php
Labels: master

#16568 Update 5.23.0.md
  release-notes/5.23.0.md
Labels: 5.23

#16565 dev/financial#118 Move source & receive date to the top on contribution view page
  templates/CRM/Contribute/Form/ContributionView.tpl
Labels: master

#16035 dev/core#1451 Incorrect dropdown action choices on case type listing screen
  ang/crmCaseType/list.html
  tests/karma/unit/crmCaseTypeSpec.js
Labels: master

#16009 dev/core#1438 Enable matching on contact phone when importing contributions
  CRM/Dedupe/BAO/Rule.php
  CRM/Dedupe/BAO/RuleGroup.php
  tests/phpunit/CRM/Contribute/Import/Parser/ContributionTest.php
Labels: master

#16506 Count refunds when calculating amount due for an invoice
  CRM/Contribute/Form/Task/Invoice.php
Labels: master, sig:bug

#16572 5.23
  release-notes/5.23.0.md
Labels: master

#16567 Fix theoretical regression
  CRM/Event/BAO/Participant.php
  CRM/Event/Form/Participant.php
  CRM/Event/Form/Registration.php
Labels: 5.23

#16574 5.23
  CRM/Event/BAO/Participant.php
  CRM/Event/Form/Participant.php
  CRM/Event/Form/Registration.php
Labels: master

#16095 dev/core#1450 Try reducing the size of the temporary table so it only…
  CRM/Contact/BAO/Contact/Permission.php
Labels: master

#16571 (NFC) Fix typo - no hyphen in 'override'
  templates/CRM/Member/Form/Membership.tpl
Labels: master

#16564 dev/financial#102 Extend test to check status
  tests/phpunit/CRM/Event/BAO/AdditionalPaymentTest.php
Labels: master

#16445 CRM-21541 CRM.moneyFormat can't handle values with zero or one decimals
  js/Common.js
Labels: master

#16558 dev/core#1597 & dev/core#1595 fix regression when deduping on custom fields
  CRM/Dedupe/BAO/Rule.php
  tests/phpunit/CRM/Dedupe/DedupeFinderTest.php
Labels: 5.23, merge on pass

#16577 5.23 to master
  CRM/Dedupe/BAO/Rule.php
  tests/phpunit/CRM/Dedupe/DedupeFinderTest.php
Labels: master

#16563 [NFC] Minor code cleanup
  CRM/Event/Form/SelfSvcTransfer.php
  CRM/Event/Form/SelfSvcUpdate.php
Labels: master

#16578 dev/core#1602 Fix join date filtering in search builder by standardis…
  CRM/Member/BAO/Query.php
  tests/phpunit/CRM/Member/BAO/QueryTest.php
Labels: 5.23, has-test, merge on pass

#16579 dev/core#1602 Fix join date filtering in search builder by standardis…
  CRM/Member/BAO/Query.php
  tests/phpunit/CRM/Member/BAO/QueryTest.php
Labels: 5.22, merge on pass

#16576 dev/core#1597 & dev/core#1595 fix regression when deduping on custom …
  CRM/Dedupe/BAO/Rule.php
  tests/phpunit/CRM/Dedupe/DedupeFinderTest.php
Labels: 5.22

#16528 Remove old defines for flexmailer that haven't been required since CiviCRM 5.x
  Civi/Core/Container.php
Labels: master

#16531 dev/financial#84 Move sequential credit notes from 'deeply embeded functions to separate structure
  CRM/Admin/Page/Extensions.php
  CRM/Contribute/BAO/Contribution.php
  CRM/Contribute/Form/Task/Invoice.php
  CRM/Extension/Mapper.php
  CRM/Upgrade/Incremental/php/FiveTwentyFour.php
  CoreExtensions/Financial/sequentialcreditnotes/README.md
  CoreExtensions/Financial/sequentialcreditnotes/info.xml
  CoreExtensions/Financial/sequentialcreditnotes/phpunit.xml.dist
  CoreExtensions/Financial/sequentialcreditnotes/sequentialcreditnotes.civix.php
  CoreExtensions/Financial/sequentialcreditnotes/sequentialcreditnotes.php
  CoreExtensions/Financial/sequentialcreditnotes/settings/creditnote.setting.php
  CoreExtensions/Financial/sequentialcreditnotes/tests/phpunit/SequentialcreditnotesTest.php
  CoreExtensions/Financial/sequentialcreditnotes/tests/phpunit/bootstrap.php
  settings/Contribute.setting.php
  tests/phpunit/CRM/Contribute/BAO/ContributionTest.php
  tests/phpunit/api/v3/ContributionTest.php
Labels: master

#16582 (NFC) Remove `$Id$` from header
  CRM/Core/BAO/File.php
  header.txt
Labels: master, merge on pass

#16586 5.22.1 - Add release notes. Set version.
  CRM/Upgrade/Incremental/sql/5.22.1.mysql.tpl
  release-notes.md
  release-notes/5.22.1.md
  sql/civicrm_generated.mysql
  xml/version.xml
Labels: 5.22

#16583 xml/GenCode.php - Fix execution in default locale (without l10n data)
  xml/GenCode.php
Labels: 5.23, merge on pass

#16575 Make savedSearch bao sane
  CRM/Contact/BAO/Group.php
  CRM/Contact/BAO/SavedSearch.php
  api/v3/SavedSearch.php
  tests/phpunit/CRM/Core/BAO/ActionScheduleTest.php
  tests/phpunit/CRM/Mailing/BAO/MailingTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/api/v3/ContactTest.php
  tests/phpunit/api/v3/SyntaxConformanceTest.php
Labels: master, merge on pass

#16587 Add release-notes/5.22.1.md
  release-notes.md
  release-notes/5.22.1.md
Labels: 5.23

#16581 [NFC] Test cleanup.
  tests/phpunit/api/v3/SystemCheckTest.php
Labels: master

#16585 Add deprecation notice
  CRM/Event/Form/Participant.php
Labels: master

#16589 Cleanup copyValues DAO function
  CRM/Contact/BAO/Group.php
  CRM/Contact/BAO/SavedSearch.php
  CRM/Core/BAO/Domain.php
  CRM/Core/BAO/Mapping.php
  CRM/Core/BAO/UFJoin.php
  CRM/Core/DAO.php
  CRM/Mailing/BAO/MailingJob.php
  CRM/Member/BAO/MembershipBlock.php
  CRM/Report/BAO/ReportInstance.php
  Civi/Api4/Generic/Traits/DAOActionTrait.php
  api/v3/utils.php
Labels: master

#16588 Fix enotice regression (unreleased)
  CRM/Event/Form/Participant.php
Labels: 5.23

#16580 5.23
  CRM/Event/Form/Participant.php
  CRM/Member/BAO/Query.php
  release-notes.md
  release-notes/5.22.1.md
  tests/phpunit/CRM/Member/BAO/QueryTest.php
  xml/GenCode.php
Labels: master

#16005 dev/core#1436 Do not CC or BCC Contribution invoice
  CRM/Contribute/Form/Task/Invoice.php
Labels: master

#16359 dev/core#1547 Add DT_RowClass CSS classes to nested group markup
  templates/CRM/Group/Form/Search.tpl
Labels: master

#15884 Related / Inherited Memberships: Custom fields not filled with data
  CRM/Member/BAO/Membership.php
Labels: master

#15316 Secondarily order campaign dashboard by id
  CRM/Campaign/BAO/Campaign.php
Labels: master

#15940 dev/financial#105 Add CSS class onto the radio button payment processor options
  CRM/Contribute/Form/Contribution/Main.php
  CRM/Core/Form.php
  CRM/Event/Form/Registration/Register.php
Labels: master

#16085 [NFC] dev/core#1466 Update Documentation URLS to be the correct links…
  CRM/Utils/Check/Component/Security.php
Labels: master

#16529 Pass template_type through to alterMailing hook
  CRM/Mailing/BAO/Mailing.php
Labels: needs-documentation

#16594 First pass at release notes for 5.23
  contributor-key.yml
  release-notes/5.23.0.md
Labels: 5.23

#16596 5.23
  contributor-key.yml
  release-notes/5.23.0.md
Labels: master

#16562 Move determination of year & month to formatCreditCardDetails
  CRM/Contribute/Form/AbstractEditPayment.php
Labels: master

#16599 dev/translation#36 Ensure that we are only passing integers to the ng…
  CRM/Core/I18n.php
Labels: 5.23

#16362 Do not enable core payment processor types that we believe likely don't work on new installs
  xml/templates/civicrm_data.tpl
Labels: master

#16600 Remove hardcoded settings from form and use SettingForm.tpl for Case settings
  templates/CRM/Admin/Form/Setting/Case.tpl
Labels: master, merge on pass

#16602 Add description to params for api3 Payment.get
  api/v3/Payment.php
Labels: master

#16604 5.23
  CRM/Core/I18n.php
Labels: master

#16605 [REF] Update civicrm_generated following merge of #16362
  sql/civicrm_generated.mysql
Labels: master

#16606 Fix two more php-finding regexes
  Civi/Api4/Action/Entity/Get.php
  Civi/Api4/Action/GetActions.php
Labels: master

#16545 [REF] Extract function to getTransactionInfo
  CRM/Contribute/BAO/Contribution.php
Labels: master

#16607 Update recently-added PathUrlTest to be more representative
  tests/phpunit/E2E/Core/PathUrlTest.php
Labels: 5.23

#16608 5.23
  tests/phpunit/E2E/Core/PathUrlTest.php
Labels: master

#15834 dev/core#1386 Allow advanced search for contributions without a soft credit related
  CRM/Contribute/BAO/Query.php
Labels: master

#16613 [NFC] Convert Custom Field BAO file to use short array syntax
  CRM/Core/BAO/CustomField.php
Labels: master, merge on pass

#16616 Move sequentialcreditnotes under `ext/` folder
  .gitignore
  ext/sequentialcreditnotes/README.md
  ext/sequentialcreditnotes/info.xml
  ext/sequentialcreditnotes/phpunit.xml.dist
  ext/sequentialcreditnotes/sequentialcreditnotes.civix.php
  ext/sequentialcreditnotes/sequentialcreditnotes.php
  ext/sequentialcreditnotes/settings/creditnote.setting.php
  ext/sequentialcreditnotes/tests/phpunit/SequentialcreditnotesTest.php
  ext/sequentialcreditnotes/tests/phpunit/bootstrap.php
Labels: master

#16619 dev/translation#37 - Remove hardcoded translations from 13 years ago that no longer do anything
  CRM/Activity/Selector/Activity.php
Labels: master

#16622 dev/core#1386 Add in unit test for #15834
  tests/phpunit/CRM/Contribute/BAO/QueryTest.php
Labels: master, merge on pass

#16621 dev/core#1615 - Fix for recently migrated civicrm-setup
  setup/civicrm-setup-autoload.php
Labels: master, merge on pass

#16598 Enable the "sequentialcreditnotes" extension on new installations
  bin/regen.sh
  ext/sequentialcreditnotes/sequentialcreditnotes.php
  sql/civicrm_generated.mysql
  tests/phpunit/api/v3/PaymentTest.php
  xml/templates/civicrm_data.tpl
Labels: master

#16338 Convert civicrm_note.modified_date to timestamp
  CRM/Contribute/BAO/Contribution.php
  CRM/Contribute/Form/Contribution/Confirm.php
  CRM/Core/BAO/Note.php
  CRM/Core/DAO/Note.php
  CRM/Event/BAO/Participant.php
  CRM/Event/Form/ParticipantFeeSelection.php
  CRM/Grant/BAO/Grant.php
  CRM/Upgrade/Incremental/sql/5.24.alpha1.mysql.tpl
  tests/phpunit/api/v3/NoteTest.php
  xml/schema/Core/Note.xml
Labels: master, merge ready

#16503 dev/core#1584 Add function to specify whether payment processor requires email address
  CRM/Core/Payment.php
  CRM/Core/Payment/Manual.php
  tests/phpunit/CRM/Financial/BAO/PaymentProcessorTest.php
Labels: master

#16560 dev/core#1596 fix (unreleased) regression on contribution summary
  CRM/Report/Form.php
  CRM/Report/Form/Contribute/Summary.php
  api/v3/ReportTemplate.php
  tests/phpunit/api/v3/ReportTemplateTest.php
Labels: master
