Repository civicrm/civicrm-core, pull requests merged in 2020-07, with the labels that each got.

#17719 5.27
  contributor-key.yml
  release-notes.md
  release-notes/5.27.0.md
Labels: master

#17602 REF Access the method not the property directly to check if a payment processor supports recurring
  CRM/Contribute/Form/AbstractEditPayment.php
Labels: master

#17701 dev/wordpress#61 - Financial Account by Relationship lookup is incorrectly using label not name
  CRM/Core/PseudoConstant.php
  CRM/Financial/BAO/FinancialAccount.php
  tests/phpunit/CRM/Financial/BAO/FinancialAccountTest.php
Labels: has-test, master

#17726 Remove obsolete function formatWikiURL
  CRM/Case/XMLProcessor/Report.php
  CRM/Utils/Check/Component/Env.php
  CRM/Utils/System.php
Labels: master

#17728 dev/translation#48: fix up system check grammar and add pre-upgrade message.
  CRM/Upgrade/Incremental/php/FiveTwentySeven.php
  CRM/Utils/Check/Component/Env.php
Labels: 5.27

#17727 [NFC] Fix contributor key for Lighthouse Consulting and Design
  contributor-key.yml
Labels: master

#17730 dev/core#1494 System check for moneyvalueformat: grammar & clarity
  CRM/Utils/Check/Component/Schema.php
Labels: 5.27, merge on pass

#17669 [REF] Ship Flexmailer extension with Core
  .gitignore
  ext/flexmailer/CHANGELOG.md
  ext/flexmailer/LICENSE.txt
  ext/flexmailer/README.md
  ext/flexmailer/docs/develop/CheckSendableEvent.md
  ext/flexmailer/docs/develop/ComposeBatchEvent.md
  ext/flexmailer/docs/develop/RunEvent.md
  ext/flexmailer/docs/develop/SendBatchEvent.md
  ext/flexmailer/docs/develop/WalkBatchesEvent.md
  ext/flexmailer/docs/develop/index.md
  ext/flexmailer/docs/index.md
  ext/flexmailer/docs/install.md
  ext/flexmailer/flexmailer.civix.php
  ext/flexmailer/flexmailer.php
  ext/flexmailer/info.xml
  ext/flexmailer/mkdocs.yml
  ext/flexmailer/phpunit.xml.dist
  ext/flexmailer/settings/flexmailer.setting.php
  ext/flexmailer/src/API/MailingPreview.php
  ext/flexmailer/src/ClickTracker/ClickTrackerInterface.php
  ext/flexmailer/src/ClickTracker/HtmlClickTracker.php
  ext/flexmailer/src/ClickTracker/TextClickTracker.php
  ext/flexmailer/src/Event/BaseEvent.php
  ext/flexmailer/src/Event/CheckSendableEvent.php
  ext/flexmailer/src/Event/ComposeBatchEvent.php
  ext/flexmailer/src/Event/RunEvent.php
  ext/flexmailer/src/Event/SendBatchEvent.php
  ext/flexmailer/src/Event/WalkBatchesEvent.php
  ext/flexmailer/src/FlexMailer.php
  ext/flexmailer/src/FlexMailerTask.php
  ext/flexmailer/src/Listener/Abdicator.php
  ext/flexmailer/src/Listener/Attachments.php
  ext/flexmailer/src/Listener/BaseListener.php
  ext/flexmailer/src/Listener/BasicHeaders.php
  ext/flexmailer/src/Listener/BounceTracker.php
  ext/flexmailer/src/Listener/DefaultBatcher.php
  ext/flexmailer/src/Listener/DefaultComposer.php
  ext/flexmailer/src/Listener/DefaultSender.php
  ext/flexmailer/src/Listener/HookAdapter.php
  ext/flexmailer/src/Listener/OpenTracker.php
  ext/flexmailer/src/Listener/RequiredFields.php
  ext/flexmailer/src/Listener/RequiredTokens.php
  ext/flexmailer/src/Listener/SimpleFilter.php
  ext/flexmailer/src/Listener/TestPrefix.php
  ext/flexmailer/src/Listener/ToHeader.php
  ext/flexmailer/src/MailParams.php
  ext/flexmailer/src/Services.php
  ext/flexmailer/src/Validator.php
  ext/flexmailer/tests/phpunit/Civi/FlexMailer/ClickTracker/HtmlClickTrackerTest.php
  ext/flexmailer/tests/phpunit/Civi/FlexMailer/ClickTracker/TextClickTrackerTest.php
  ext/flexmailer/tests/phpunit/Civi/FlexMailer/ConcurrentDeliveryTest.php
  ext/flexmailer/tests/phpunit/Civi/FlexMailer/FlexMailerSystemTest.php
  ext/flexmailer/tests/phpunit/Civi/FlexMailer/Listener/SimpleFilterTest.php
  ext/flexmailer/tests/phpunit/Civi/FlexMailer/MailingPreviewTest.php
  ext/flexmailer/tests/phpunit/Civi/FlexMailer/ValidatorTest.php
  ext/flexmailer/tests/phpunit/bootstrap.php
  ext/flexmailer/xml/Menu/flexmailer.xml
Labels: master

#17725 Ensure pricefield value label column is not null on upgrade
  CRM/Upgrade/Incremental/php/FiveTwentySeven.php
Labels: 5.27, merge on pass

#17722 dev/core#1846 Regression (sorta) Hacks to avoid failure on upgrade due to new field not yet being in the DB
  CRM/Core/BAO/CustomField.php
  CRM/Core/BAO/Domain.php
  CRM/Utils/Check/Component/Env.php
  CRM/Utils/Check/Component/Schema.php
  api/v3/CustomField.php
  sql/test_data_second_domain.mysql
  xml/schema/Core/CustomField.xml
Labels: 5.27

#17732 5.27
  CRM/Core/BAO/CustomField.php
  CRM/Core/BAO/Domain.php
  CRM/Upgrade/Incremental/php/FiveTwentySeven.php
  CRM/Utils/Check/Component/Env.php
  CRM/Utils/Check/Component/Schema.php
  api/v3/CustomField.php
  sql/test_data_second_domain.mysql
  xml/schema/Core/CustomField.xml
Labels: master

#17736 5.27
  release-notes/5.27.0.md
Labels: master

#17737 Fix saving of State/Province Multi-select values
  CRM/Core/BAO/CustomGroup.php
Labels: master

#17739 [NFC] Fix some outdated wiki links
  CRM/Core/Form.php
  CRM/Core/Resources.php
  CRM/Upgrade/Page/Cleanup.php
  ang/crmUtil.js
  js/crm.ajax.js
  js/crm.datepicker.js
  templates/CRM/common/civicrm.settings.php.template
Labels: master, merge on pass

#17738 dev/core#1852 Ensure all domains have the same value for locales
  CRM/Upgrade/Incremental/sql/5.28.alpha1.mysql.tpl
Labels: master

#17721 Add permission metadata to contact is_deleted field
  CRM/Contact/DAO/Contact.php
  CRM/Core/DAO/CustomField.php
  xml/schema/Contact/Contact.xml
Labels: master, merge ready

#17740 (dev/core#1846) Ensure that the `Container` is always fresh when upgrading
  CRM/Core/Config/Runtime.php
Labels: 5.27

#17733 Set locales for all domains when enabling multilingual
  CRM/Core/I18n/Schema.php
  tests/phpunit/CRM/Core/I18n/SchemaTest.php
Labels: master, merge on pass

#17741 Add eventcart shell
  .gitignore
  ext/eventcart/LICENSE.txt
  ext/eventcart/README.md
  ext/eventcart/eventcart.civix.php
  ext/eventcart/eventcart.php
  ext/eventcart/images/screenshot.png
  ext/eventcart/info.xml
Labels: master

#17747 Fix typo in templates/CRM/Report/Form/Tabs/GroupBy.tpl
  templates/CRM/Report/Form/Tabs/GroupBy.tpl
Labels: master

#17748 Pre-upgrade message for php-intl shows twice
  CRM/Upgrade/Incremental/php/FiveTwentySeven.php
Labels: 5.28

#17684 Teach CRM.utils.formatDate to also show time
  js/Common.js
  tests/qunit/common-js/test.js
  tests/qunit/common-js/test.php
Labels: has-test, master, merge on pass

#17751 5.28
  CRM/Upgrade/Incremental/php/FiveTwentySeven.php
Labels: master

#17753 Unused functions in GenCode
  CRM/Core/CodeGen/Main.php
  CRM/Core/CodeGen/Util/File.php
Labels: master

#17655 dev/core#1827 activity search - fixing search by tags
  CRM/Activity/BAO/Query.php
Labels: has-test, master

#17757 Convert CRM.utils.formatDate tests to karma
  tests/karma/unit/dateSpec.js
  tests/qunit/common-js/test.js
  tests/qunit/common-js/test.php
Labels: master, merge on pass

#17755 [Unit Test] dev/core#1173 and dev/core#1827 - Test for activity tag search - PR 17655
  tests/phpunit/CRM/Contact/BAO/ActivitySearchTest.php
Labels: has-test, master, merge on pass

#17645 core#1826: Ignore location_type_id when deduping postal address
  CRM/Dedupe/BAO/Rule.php
  tests/phpunit/CRM/Contact/Import/Parser/ContactTest.php
  tests/phpunit/CRM/Dedupe/DedupeFinderTest.php
  tests/phpunit/CRM/Dedupe/MergerTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: has-test, master, merge on pass

#17758 Fix PHP notice on wordpress permissions form
  CRM/ACL/Form/WordPress/Permissions.php
Labels: master

#17756 More unused functions in GenCode
  CRM/Core/CodeGen/Util/File.php
Labels: master

#17746 APIv4 Explorer: Improve selection of fields for HAVING
  ang/api4Explorer/Explorer.js
Labels: master

#17752 Pre-upgrade message for php-intl shows twice
  CRM/Upgrade/Incremental/php/FiveTwentySeven.php
Labels: 5.27

#17761 Remove unused, deprecated functions
  CRM/ACL/BAO/ACL.php
Labels: master

#17764 update to pr 16559
  CRM/Case/XMLProcessor/Process.php
Labels: master

#17256 [TEST] Failing test for PR 16559
  tests/phpunit/CRM/Case/XMLProcessor/ProcessTest.php
Labels: master, merge on pass

#17767 [REF] Unused interface CRM_Report_Interface
  CRM/Report/Interface.php
Labels: master

#17754 dev/drupal#114 and dev/core#1647 - Remove resource url status check
  CRM/Utils/Check/Component/Env.php
Labels: master

#17768 [NFC] Include flexmailer in distmaker
  distmaker/dists/common.sh
Labels: 5.28

#17770 5.28 to master
  distmaker/dists/common.sh
Labels: master

#17760 Ensure that when normal routing trackable urls and opens in Joomla go…
  CRM/Utils/System.php
  CRM/Utils/System/Base.php
  CRM/Utils/System/Drupal8.php
  CRM/Utils/System/DrupalBase.php
  CRM/Utils/System/Joomla.php
  CRM/Utils/System/Soap.php
  CRM/Utils/System/UnitTests.php
  CRM/Utils/System/WordPress.php
Labels: 5.28

#17776 Status Checks - Use more specific label regarding "Domain"/"Organization" check
  CRM/Utils/Check/Component/Env.php
Labels: master, merge on pass

#17772 dev/core#1860 Fix installing on PHP7.3 Ubuntu 20.04 and MariaDB 10.3
  install/index.php
Labels: 5.28, merge on pass

#17773 Ensure that when normal routing trackable urls and opens in Joomla go to the frontend not administrator site
  CRM/Utils/System.php
  CRM/Utils/System/Base.php
  CRM/Utils/System/Drupal8.php
  CRM/Utils/System/DrupalBase.php
  CRM/Utils/System/Joomla.php
  CRM/Utils/System/Soap.php
  CRM/Utils/System/UnitTests.php
  CRM/Utils/System/WordPress.php
Labels: 5.27

#17763 Remove PaymentExpress ipn class
  CRM/Core/Payment/PaymentExpress.php
  CRM/Core/Payment/PaymentExpressIPN.php
  extern/pxIPN.php
  sql/civicrm_generated.mysql
  templates/CRM/Admin/Page/PaymentProcessor.hlp
  xml/templates/civicrm_data.tpl
Labels: master

#17636 [dev/core#750] Don't check server variables if we're running in CLI
  Civi/Install/Requirements.php
Labels: master, ok-without-test

#17775 Add search extension
  .gitignore
  ext/search/CRM/Search/Page/Build.php
  ext/search/CRM/Search/Upgrader.php
  ext/search/CRM/Search/Upgrader/Base.php
  ext/search/README.md
  ext/search/ang/search.ang.php
  ext/search/ang/search.module.js
  ext/search/ang/search/SaveSmartGroup.ctrl.js
  ext/search/ang/search/crmSearchActions.component.js
  ext/search/ang/search/crmSearchActions.html
  ext/search/ang/search/crmSearchActions/crmSearchActionDelete.ctrl.js
  ext/search/ang/search/crmSearchActions/crmSearchActionDelete.html
  ext/search/ang/search/crmSearchActions/crmSearchActionUpdate.ctrl.js
  ext/search/ang/search/crmSearchActions/crmSearchActionUpdate.html
  ext/search/ang/search/crmSearchBuild.component.js
  ext/search/ang/search/crmSearchBuild.html
  ext/search/ang/search/crmSearchBuild/build.html
  ext/search/ang/search/crmSearchBuild/controls.html
  ext/search/ang/search/crmSearchBuild/debug.html
  ext/search/ang/search/crmSearchBuild/pager.html
  ext/search/ang/search/crmSearchBuild/results.html
  ext/search/ang/search/crmSearchClause.directive.js
  ext/search/ang/search/crmSearchClause.html
  ext/search/ang/search/crmSearchFunction.component.js
  ext/search/ang/search/crmSearchFunction.html
  ext/search/ang/search/crmSearchValue.directive.js
  ext/search/ang/search/saveSmartGroup.html
  ext/search/css/search.css
  ext/search/info.xml
  ext/search/search.civix.php
  ext/search/search.php
  ext/search/templates/CRM/Search/Page/Build.tpl
  ext/search/xml/Menu/search.xml
Labels: has-test, master, merge on pass

#17765 dev/core#1853 - Fix validation errors when removing contact subtype
  CRM/Contact/Form/Contact.php
Labels: master

#17774 5.28
  CRM/Utils/System.php
  CRM/Utils/System/Base.php
  CRM/Utils/System/Drupal8.php
  CRM/Utils/System/DrupalBase.php
  CRM/Utils/System/Joomla.php
  CRM/Utils/System/Soap.php
  CRM/Utils/System/UnitTests.php
  CRM/Utils/System/WordPress.php
  install/index.php
Labels: master

#17779 [NFC] Update flexmailer to be PHP7.4 compatible
  ext/flexmailer/src/Listener/DefaultSender.php
  ext/flexmailer/src/Listener/RequiredFields.php
Labels: 5.28

#17749 Support for installing CiviCRM-Backdrop via "setup" UI
  setup/plugins/init/Drupal.civi-setup.php
  setup/plugins/installDatabase/FlushBackdrop.civi-setup.php
  setup/plugins/installDatabase/FlushDrupal.civi-setup.php
  setup/plugins/installDatabase/SetLanguage.civi-setup.php
  setup/res/error.html
  setup/res/finished.Backdrop.php
  setup/res/finished.Drupal.php
  setup/res/installer.tpl.php
  setup/res/page.tpl.php
  setup/res/template.css
  setup/res/template.php
  setup/src/Setup.php
  setup/src/Setup/BasicRunner.php
  setup/src/Setup/LocaleUtil.php
  setup/src/Setup/UI/SetupController.php
  setup/src/Setup/UI/SetupResponse.php
Labels: master

#17744 dev/core#1679: Ensure Paypal IPN always updates the next scheduled payment date
  CRM/Contribute/BAO/ContributionRecur.php
  tests/phpunit/api/v3/ContributionTest.php
Labels: master

#17782 5.28
  ext/flexmailer/src/Listener/DefaultSender.php
  ext/flexmailer/src/Listener/RequiredFields.php
Labels: master

#17783 getLoggedInContactID() is a static function
  CRM/ACL/API.php
  CRM/Contact/Form/Merge.php
  CRM/Contact/Form/Task/PDFLetterCommon.php
  CRM/Contact/Page/View/UserDashBoard.php
  CRM/Contribute/Form/ContributionBase.php
  CRM/Core/BAO/Domain.php
  CRM/Core/BAO/Email.php
  CRM/Core/BAO/Note.php
  CRM/Event/BAO/Participant.php
  CRM/Profile/Selector/Listings.php
Labels: master, merge on pass

#17784 5.27.1 - Add notes. Update version.
  CRM/Upgrade/Incremental/sql/5.27.1.mysql.tpl
  release-notes.md
  release-notes/5.27.1.md
  sql/civicrm_generated.mysql
  xml/version.xml
Labels: 5.27

#17787 Fixed notice error on Relationships report
  CRM/Report/Form/Contact/Relationship.php
Labels: master, ok-without-test

#17786 dev/core#1868 - Regression - Description field is always blank on profiles admin page and slew of E_NOTICES
  CRM/Core/BAO/UFGroup.php
Labels: master

#17698 Add system check to ensure WP base page exists
  CRM/Utils/Check/Component/Cms.php
Labels: master, merge ready, ok-without-test

#17791 APIv4 - Fix saving custom fields with same name
  Civi/Api4/Generic/Traits/DAOActionTrait.php
  tests/phpunit/api/v4/Action/BasicCustomFieldTest.php
Labels: has-test, master

#17683 Add auto-renew status to membership detail report
  CRM/Report/Form/Member/Detail.php
  tests/phpunit/CRM/Report/Form/Member/DetailTest.php
Labels: has-test, master

#17795 [REF] Do or do not - there is no try
  CRM/Report/Form.php
  tests/phpunit/CiviTest/CiviReportTestCase.php
Labels: master

#17792 5.28.0 release notes initial run
  release-notes.md
  release-notes/5.28.0.md
Labels: 5.28

#17794 Sort permittedActivityTypes
  CRM/Activity/BAO/Activity.php
Labels: master

#17796 dev/core#1864 - 5.27 backport for search is always including deleted contacts
  CRM/ACL/API.php
  tests/phpunit/CRM/Contact/BAO/QueryTest.php
  tests/phpunit/CRM/Contact/SelectorTest.php
  tests/phpunit/api/v3/ACLPermissionTest.php
Labels: 5.27

#17801 REF - Cleanup StatusPreference BAO to be more standard
  CRM/Core/BAO/StatusPreference.php
Labels: master, merge on pass

#17798 dev/core#1864 Ensure that when search in trash is not checked that on…
  CRM/Contact/BAO/Query.php
  tests/phpunit/CRM/Contact/BAO/QueryTest.php
  tests/phpunit/CRM/Contact/SelectorTest.php
Labels: 5.28, has-test, merge on pass

#17769 dev/core#1858 Prevent Duplicate contact records being created and har…
  CRM/Core/BAO/UFMatch.php
Labels: has-test, master, merge on pass

#17723 [REF] Remove ACL join on temp table creation in Member ContributionDe…
  CRM/Report/Form/Member/ContributionDetail.php
Labels: master

#17788 [REF] Follow up cleanup
  CRM/Contribute/Form/CancelSubscription.php
  CRM/Contribute/Form/ContributionRecur.php
Labels: master

#17789 Add hidden tag to search extension
  ext/search/info.xml
Labels: master

#17802 dev/core#1864 Revert changes to ACL test and ACL API class and update…
  CRM/ACL/API.php
  CRM/Contact/BAO/Query.php
  tests/phpunit/api/v3/ACLPermissionTest.php
Labels: 5.27, merge on pass

#17762 dev/core#1847 Fix datepicker to respect the searchDate offsets
  CRM/Core/Form.php
Labels: 5.28, has-test

#15435 reporting#21 - don't multiple contribution details when a 1-to-many r…
  CRM/Report/Form/Contribute/Detail.php
Labels: has-test, master

#17797 dev/core#1865 Remove civiwp and option query strings from redirected …
  CRM/Mailing/Page/Url.php
Labels: 5.28, merge on pass

#17805 dev/core#1865 Remove civiwp and option query strings from redirected …
  CRM/Mailing/Page/Url.php
Labels: 5.27, merge on pass

#17804 dev/core#1847 Fix datepicker to respect the searchDate offsets
  CRM/Core/Form.php
Labels: 5.27, merge on pass

#17803 dev/core#1862 Skip cache tables during merge, rely on cache management processes
  CRM/Dedupe/Merger.php
  tests/phpunit/CRM/Dedupe/MergerTest.php
  tests/phpunit/api/v3/JobTest.php
Labels: 5.28, has-test, merge on pass

#17807 dev/core#1863 Downgrade checkEnvironment level and skip non-prod checks
  CRM/Utils/Check/Component/Env.php
Labels: master, merge ready

#17812 dev/core#1861 fix failure to unset location_type_id when saving uffield
  CRM/UF/Form/Field.php
Labels: master

#17816 Fix 'Undefined variable: jsSet in CRM_Core_BAO_Mapping::loadSavedMapping()'
  CRM/Core/BAO/Mapping.php
Labels: master

#17800 CheckEnv - Give new installs a grace period before 'Cron Not Running' msg
  CRM/Core/JobManager.php
  CRM/Utils/Check/Component/Env.php
Labels: master, merge ready

#17814 Fix dedupe on same-activity-connection
  CRM/Dedupe/Merger.php
  tests/phpunit/api/v3/JobTest.php
Labels: 5.28, has-test

#17818 Dedupe, report date backports
  CRM/Dedupe/Merger.php
  CRM/Report/Form.php
  tests/phpunit/CRM/Dedupe/MergerTest.php
  tests/phpunit/api/v3/JobTest.php
Labels: 5.27

#17811 dev/core#1867 CiviReport filters: Fix incorrect defaulting to the beginning rather than end the to-range day
  CRM/Report/Form.php
Labels: 5.28

#17780 CRM_Utils_SQL - Add "onDuplicate()" and "syncInto()" helpers
  CRM/Utils/SQL/Select.php
  tests/phpunit/CRM/Utils/SQL/SelectTest.php
Labels: has-test, master

#17820 dev/core#1867 Ensure that the qill matches the filter when no time is…
  CRM/Report/Form.php
Labels: 5.28, merge on pass, ok-without-test

#17799 5.28
  CRM/Contact/BAO/Query.php
  CRM/Core/Form.php
  CRM/Dedupe/Merger.php
  CRM/Mailing/Page/Url.php
  CRM/Report/Form.php
  release-notes.md
  release-notes/5.28.0.md
  tests/phpunit/CRM/Contact/BAO/QueryTest.php
  tests/phpunit/CRM/Contact/SelectorTest.php
  tests/phpunit/CRM/Dedupe/MergerTest.php
  tests/phpunit/api/v3/JobTest.php
Labels: master

#17729 Make api get upgrade-safe
  CRM/Core/DAO.php
  Civi/Api4/Service/Spec/SpecGatherer.php
  api/v3/Setting.php
  api/v3/utils.php
  sql/test_data_second_domain.mysql
  tests/phpunit/CRM/Core/DAOTest.php
  tests/phpunit/api/v3/SettingTest.php
Labels: has-test, master

#17822 dev/core#1871 - require_once's that include "packages/" in the path don't work on drupal 8
  CRM/Utils/PDF/Utils.php
  CRM/Utils/ReCAPTCHA.php
Labels: master, merge on pass, ok-without-test

#17821 dev/core#1867 Ensure that the qill matches the filter when no time is…
  CRM/Report/Form.php
Labels: 5.27, merge on pass, ok-without-test

#17809 Test for https://github.com/civicrm/civicrm-core/pull/15435
  CRM/Report/Form.php
  CRM/Report/Form/Contribute/Detail.php
  api/v3/ReportTemplate.php
  tests/phpunit/CRM/Report/Form/Contribute/DetailTest.php
  tests/phpunit/CiviTest/CiviReportTestCase.php
Labels: has-test, master, merge on pass

#17813 Make new email open and url routes 'public'
  CRM/Mailing/xml/Menu/Mailing.xml
Labels: master, ok-without-test

#17709 dev/core#1768 - Add CiviMail synchronisation frequency setting.
  CRM/Admin/Form/Setting/Mail.php
  CRM/Mailing/BAO/MailingJob.php
  CRM/Mailing/Config.php
  settings/Mailing.setting.php
  templates/CRM/Mailing/Form/Settings.hlp
Labels: concept approved, master, ok-without-test

#17513 core#1795: Searchable Parent tags
  CRM/Contact/BAO/Query.php
  tests/phpunit/CRM/Contact/BAO/QueryTest.php
  tests/phpunit/CRM/Contact/BAO/QueryTestDataProvider.php
Labels: has-test, master, needs-concept-approval, schedule-discussion

#17695 event#38 fix wording on event reg page
  templates/CRM/Event/Form/Registration/Register.tpl
Labels: easy-review, master, merge on pass, ok-without-test

#17569 core#1805: Autocomplete-select custom field is not searchable
  CRM/Activity/Form/Search.php
  CRM/Case/Form/Search.php
  CRM/Contact/BAO/Query.php
  CRM/Contact/Form/Search/Advanced.php
  CRM/Contribute/Form/Search.php
  CRM/Core/BAO/CustomValue.php
  CRM/Event/Form/Search.php
  CRM/Grant/Form/Search.php
  CRM/Member/Form/Search.php
  tests/phpunit/CRM/Core/BAO/CustomValueTest.php
Labels: has-test, master, merge on pass

#17825 Adjust mysql SET NAMES in remaining places as we agreed this was the go
  sql/civicrm_generated.mysql
  tests/phpunit/CRM/Report/Form/Contribute/fixtures/dataset-ascii.sql
  xml/templates/civicrm_country.tpl
  xml/templates/civicrm_state_province.tpl
Labels: master, merge on pass

#17766 APIv4 - Add activity contacts to APIv4 field spec
  Civi/Api4/Service/Spec/Provider/ActivityCreationSpecProvider.php
  Civi/Api4/Service/Spec/Provider/ActivitySpecProvider.php
  tests/phpunit/api/v3/ActivityTest.php
Labels: master, merge ready

#13958 dev/core#785 Differentiate smart group from regular group using icon in select2 field
  CRM/Contact/BAO/Group.php
  CRM/Contact/Form/Contact.php
  CRM/Contact/Form/Edit/TagsAndGroups.php
  CRM/Contact/Form/GroupContact.php
  CRM/Contact/Form/Search/Basic.php
  CRM/Contact/Form/Search/Criteria.php
  ang/crmMailing/Recipients.js
  tests/phpunit/CRM/Contact/Page/View/UserDashboard/GroupContactTest.php
Labels: has-test, master, ready for review

#17815 dev/core#1812 Missing view when logging set in a non-US English instance
  CRM/Admin/Form/Setting/Miscellaneous.php
  CRM/Logging/Schema.php
  templates/CRM/Admin/Form/Setting/Miscellaneous.tpl
Labels: master, merge ready, ok-without-test

#17833 (REF) WebsiteTest - Mitigate flaky failures
  tests/phpunit/api/v3/WebsiteTest.php
Labels: master

#17826 Remove hard coded charset.
  CRM/Contact/BAO/Contact.php
Labels: master

#17830 MembershipRenewalTest - Fix failure
  tests/phpunit/CRM/Member/Form/MembershipRenewalTest.php
Labels: master

#17838 Revert "dev/core#1847 Fix datepicker to respect the searchDate offsets"
  CRM/Core/Form.php
Labels: 5.27, merge on pass

#17837 5.27.2 - Add release notes. Bump version.
  CRM/Upgrade/Incremental/sql/5.27.2.mysql.tpl
  release-notes.md
  release-notes/5.27.2.md
  sql/civicrm_generated.mysql
  xml/version.xml
Labels: 5.27

#17839 Update regen.sh with new & upcoming core extensions
  bin/regen.sh
Labels: master, merge on pass

#17743 Move BAO and template files into event cart
  CRM/Upgrade/Incremental/php/FiveTwentyNine.php
  distmaker/dists/common.sh
  ext/eventcart/CRM/Event/Cart/BAO/Cart.php
  ext/eventcart/CRM/Event/Cart/BAO/Conference.php
  ext/eventcart/CRM/Event/Cart/BAO/EventInCart.php
  ext/eventcart/CRM/Event/Cart/BAO/MerParticipant.php
  ext/eventcart/CRM/Event/Cart/Controller/Checkout.php
  ext/eventcart/CRM/Event/Cart/Form/Cart.php
  ext/eventcart/CRM/Event/Cart/Form/Checkout/ConferenceEvents.php
  ext/eventcart/CRM/Event/Cart/Form/Checkout/ParticipantsAndPrices.php
  ext/eventcart/CRM/Event/Cart/Form/Checkout/Payment.php
  ext/eventcart/CRM/Event/Cart/Form/Checkout/ThankYou.php
  ext/eventcart/CRM/Event/Cart/Form/MerParticipant.php
  ext/eventcart/CRM/Event/Cart/Page/AddToCart.php
  ext/eventcart/CRM/Event/Cart/Page/CheckoutAJAX.php
  ext/eventcart/CRM/Event/Cart/Page/RemoveFromCart.php
  ext/eventcart/CRM/Event/Cart/Page/ViewCart.php
  ext/eventcart/CRM/Event/Cart/StateMachine/Checkout.php
  ext/eventcart/info.xml
  ext/eventcart/templates/CRM/Event/Cart/Form/Checkout/ConferenceEvents.tpl
  ext/eventcart/templates/CRM/Event/Cart/Form/Checkout/Participant.tpl
  ext/eventcart/templates/CRM/Event/Cart/Form/Checkout/ParticipantsAndPrices.tpl
  ext/eventcart/templates/CRM/Event/Cart/Form/Checkout/Payment.tpl
  ext/eventcart/templates/CRM/Event/Cart/Form/Checkout/ThankYou.tpl
  ext/eventcart/templates/CRM/Event/Cart/Form/viewCartLink.tpl
  ext/eventcart/templates/CRM/Event/Cart/Page/AddToCart.tpl
  ext/eventcart/templates/CRM/Event/Cart/Page/ViewCart.tpl
  sql/civicrm_generated.mysql
  xml/templates/civicrm_data.tpl
Labels: master, merge on pass, ok-without-test

#17840 5.27.1 and 5.27.2 Release Notes
  release-notes.md
  release-notes/5.27.1.md
  release-notes/5.27.2.md
Labels: 5.28, merge on pass

#17843 5.28
  release-notes.md
  release-notes/5.27.1.md
  release-notes/5.27.2.md
Labels: master

#17842 [NFC] Re run regen after recent merges
  sql/civicrm_generated.mysql
Labels: master, merge on pass

#17844 dev/core#1872 - Packages and vendor path calculation used in system check is outdated
  CRM/Utils/Check/Component/Security.php
Labels: master, merge on pass

#17845 (REF) APIv4 ConformanceTest - Split apart into per-entity sub-tests
  tests/phpunit/api/v4/Entity/ConformanceTest.php
Labels: master

#17848 dev/core#1880 add backticks to custom field insertions
  CRM/Core/BAO/CustomField.php
  CRM/Core/BAO/CustomValueTable.php
Labels: master, merge on pass

#17847 API tests - label versions in dataprovider versionThreeAndFour
  Civi/Test/Api3TestTrait.php
Labels: has-test, master, merge on pass

#17850 [REF] Only printOnly once
  CRM/Report/Form.php
Labels: master

#17849 handlePaymentNotification() should not be declared as a static method
  CRM/Core/Payment/AuthorizeNet.php
  CRM/Core/Payment/PayPalImpl.php
Labels: master, merge on pass, ok-without-test

#17853 dev/wordpress#62 Update adrienrn/php-mimetyper gitignore file to ensu…
  composer.json
  composer.lock
Labels: 5.28, ok-without-test

#17854 dev/core#1882 - Missing version number in status check message about db version vs code version
  CRM/Utils/Check/Component/Env.php
Labels: 5.28, merge on pass

#17857 [Test framework] - Backport of membership test fix
  tests/phpunit/CRM/Member/Form/MembershipRenewalTest.php
Labels: 5.28, merge on pass

#17851 [NFC] 5.28 Release Notes First Pass
  contributor-key.yml
  release-notes/5.28.0.md
Labels: 5.28

#17841 [REF] Migrate Event Cart Setting into the Extension
  ext/eventcart/settings/Eventcart.setting.php
  settings/Event.setting.php
Labels: master, ok-without-test

#17836 dev/core#1874 Fix fatal error by passing through the string formatTyp…
  CRM/Batch/DAO/Batch.php
  CRM/Campaign/DAO/Campaign.php
  CRM/Core/Form.php
  CRM/Mailing/DAO/MailingAB.php
  CRM/Member/DAO/Membership.php
  CRM/Pledge/DAO/Pledge.php
  CRM/Queue/DAO/QueueItem.php
  xml/schema/Batch/Batch.xml
  xml/schema/Campaign/Campaign.xml
  xml/schema/Mailing/MailingAB.xml
  xml/schema/Member/Membership.xml
  xml/schema/Pledge/Pledge.xml
  xml/schema/Queue/QueueItem.xml
Labels: 5.28

#17859 5.28
  CRM/Batch/DAO/Batch.php
  CRM/Campaign/DAO/Campaign.php
  CRM/Core/Form.php
  CRM/Mailing/DAO/MailingAB.php
  CRM/Member/DAO/Membership.php
  CRM/Pledge/DAO/Pledge.php
  CRM/Queue/DAO/QueueItem.php
  xml/schema/Batch/Batch.xml
  xml/schema/Campaign/Campaign.xml
  xml/schema/Mailing/MailingAB.xml
  xml/schema/Member/Membership.xml
  xml/schema/Pledge/Pledge.xml
  xml/schema/Queue/QueueItem.xml
Labels: master

#17835 dev/core#1874 - Failing test for new Individual form
  tests/phpunit/CRM/Contact/Form/IndividualTest.php
Labels: has-test, master

#17855 dev/core#1090 Update extendedSerializeData to use the Backbone namesp…
  js/view/crm.designer.js
Labels: master, merge on pass, ok-without-test

#17862 [REF] ScheduledJob cleanup, remove unused var
  CRM/Core/ScheduledJob.php
Labels: master

#17861 EventCart - Resolve BAO identity and uncommitted DAO changes
  CRM/Core/CodeGen/Specification.php
  xml/schema/Event/Cart/Cart.xml
  xml/schema/Event/Cart/EventInCart.xml
Labels: master, merge on pass

#17864 Search Ext: fix loading options and parsing custom field names
  ext/search/ang/search.module.js
  ext/search/ang/search/crmSearch.component.js
Labels: master, merge on pass

#17865 Fix potential js error on summary screen when reloading blocks
  templates/CRM/Contact/Page/View/Summary.js
Labels: master

#16626 Fixed DB Error: syntax error if line item refers to civicrm_case
  CRM/Price/BAO/LineItem.php
Labels: master

#17860 api_v3_TaxContributionPageTest fix - remove hard coded processor id
  tests/phpunit/api/v3/TaxContributionPageTest.php
Labels: has-test, master, merge on pass

#17458 dev/core#1725 Only export primary address fields
  CRM/Export/BAO/ExportProcessor.php
Labels: has-test, master

#17863 dev/report#43 - Icon after saving a civireport instance is misleading
  CRM/Report/Form/Instance.php
  tests/phpunit/CRM/Report/Form/SampleForm.php
  tests/phpunit/CRM/Report/FormTest.php
Labels: has-test, master

#16429 dev/core#1113 - Decimal Separator - Invalid value "total_amount" (NaN,N) creating or editing a membership
  CRM/Member/Form/Membership.php
Labels: master

#17870 Use PrematureExit exception instead of weird hack in tests
  CRM/Activity/Page/AJAX.php
  CRM/Custom/Page/AJAX.php
  CRM/Group/Page/AJAX.php
  tests/phpunit/CRM/Activity/BAO/ActivityTest.php
  tests/phpunit/CRM/Custom/Page/AJAXTest.php
  tests/phpunit/CRM/Group/Page/AjaxTest.php
Labels: has-test, master, merge on pass

#17834 APIv4 - Add shorthand for setCheckPermissions()
  Civi/Api4/Address.php
  Civi/Api4/Campaign.php
  Civi/Api4/Contact.php
  Civi/Api4/CustomValue.php
  Civi/Api4/Domain.php
  Civi/Api4/Entity.php
  Civi/Api4/Event.php
  Civi/Api4/Generic/AbstractAction.php
  Civi/Api4/Generic/AbstractEntity.php
  Civi/Api4/Generic/DAOEntity.php
  Civi/Api4/GroupContact.php
  Civi/Api4/Relationship.php
  Civi/Api4/Route.php
  Civi/Api4/Setting.php
  Civi/Api4/System.php
  ang/api4Explorer/Explorer.js
  tests/phpunit/api/v4/Action/ContactApiKeyTest.php
  tests/phpunit/api/v4/Entity/ConformanceTest.php
Labels: has-test, master

#17831 Hooks/Dispatcher - Close loopholes that occur around "preboot" hooks
  CRM/Extension/Manager/Report.php
  CRM/Extension/Manager/Search.php
  CRM/Utils/Hook.php
  Civi.php
  Civi/Core/CiviEventDispatcher.php
  Civi/Core/Container.php
Labels: master

#17871 [REF] Fix a couple of jQuery errors that have cropped up
  js/Common.js
  templates/CRM/Contact/Page/View/Summary.js
Labels: master, merge on pass, ok-without-test

#17781 RelationshipCache - Add a high-level index to facilitate relationship queries (more fields)
  CRM/Contact/BAO/RelationshipCache.php
  CRM/Contact/DAO/RelationshipCache.php
  CRM/Core/DAO/AllCoreTables.data.php
  CRM/Upgrade/Incremental/php/FiveTwentyNine.php
  CRM/Upgrade/Incremental/sql/5.29.alpha1.mysql.tpl
  CRM/Utils/String.php
  Civi/Core/Container.php
  ang/api4Explorer/Explorer.js
  sql/civicrm_generated.mysql
  tests/phpunit/CRM/Contact/BAO/RelationshipCacheTest.php
  tests/phpunit/CRM/Dedupe/MergerTest.php
  xml/schema/Contact/RelationshipCache.xml
  xml/schema/Contact/files.xml
Labels: has-test, master, merge on pass

#17703 Fix currency symbol for Total Amount on contribution page
  templates/CRM/Price/Form/Calculate.tpl
Labels: master, ready for review

#16298 dev/membership#18 Enhance parameters for Job.process_membership
  CRM/Member/BAO/Membership.php
  api/v3/Job.php
  tests/phpunit/CRM/Member/BAO/MembershipTest.php
  tests/phpunit/api/v3/JobProcessMembershipTest.php
Labels: has-test, master, merge on pass

#17526 Disable frequency/interval fields if not required. Mark required if they are so they are validated before submit
  templates/CRM/Contribute/Form/Contribution/Main.tpl
Labels: concept approved, master, ok-without-test, ready for review

#17524 REF Extract addToRecentItems from membership create
  CRM/Member/BAO/Membership.php
Labels: Refactor, master

#17872 [NFC] Comment block cleanup
  CRM/Core/Key.php
  CRM/Core/Lock.php
  CRM/Core/Page/AJAX.php
  CRM/Core/Page/File.php
  CRM/Core/Page/Inline/Help.php
  CRM/Core/Permission/Drupal.php
  CRM/Core/Permission/Joomla.php
  CRM/Core/Permission/Soap.php
  CRM/Core/Permission/Temp.php
  CRM/Core/Permission/UnitTests.php
  CRM/Core/Smarty/plugins/block.crmButton.php
  CRM/Core/Smarty/plugins/modifier.crmNumberFormat.php
  CRM/Core/Smarty/plugins/modifier.crmReplace.php
  CRM/Core/Transaction.php
  CRM/Custom/Form/ChangeFieldType.php
  CRM/Custom/Form/Preview.php
  CRM/Custom/Import/Form/DataSource.php
  CRM/Dedupe/BAO/RuleGroup.php
  Civi/Api4/Domain.php
  Civi/Api4/Email.php
  Civi/Api4/Entity.php
  Civi/Api4/Event.php
  Civi/Api4/Event/Events.php
  Civi/Api4/Event/PostSelectQueryEvent.php
  Civi/Api4/GroupContact.php
  Civi/Api4/GroupNesting.php
  Civi/Api4/MappingField.php
  Civi/Api4/OptionValue.php
  Civi/Api4/Service/Spec/Provider/CustomGroupCreationSpecProvider.php
  Civi/Api4/Service/Spec/Provider/CustomValueSpecProvider.php
  Civi/Api4/Service/Spec/Provider/DefaultLocationTypeProvider.php
  Civi/Api4/Service/Spec/Provider/EmailCreationSpecProvider.php
  Civi/Api4/Service/Spec/Provider/EntityTagCreationSpecProvider.php
  Civi/Api4/Service/Spec/Provider/EventCreationSpecProvider.php
  Civi/Api4/Service/Spec/Provider/Generic/SpecProviderInterface.php
  Civi/Api4/Service/Spec/Provider/GetActionDefaultsProvider.php
  Civi/Api4/UFMatch.php
  Civi/Api4/Utils/FormattingUtil.php
  tests/phpunit/api/v4/Traits/OptionCleanupTrait.php
  tests/phpunit/api/v4/Traits/QueryCounterTrait.php
Labels: master, merge on pass

#16838 dev/core#1280 Fix ContributionPage soft_credit translation
  CRM/Contribute/BAO/ContributionPage.php
  CRM/Contribute/Form/ContributionPage/Settings.php
  tests/phpunit/CRM/Contribute/Form/ContributionPageTranslationTest.php
Labels: has-test, master, merge on pass

#17875 Ensure serialize field exists before adding to query
  CRM/Core/BAO/CustomGroup.php
Labels: 5.28

#17806 dev/core#1869 - Include BOM in attachment when sending CSV CiviReport via mail_report job
  CRM/Report/Form.php
  CRM/Report/Utils/Report.php
  CRM/Utils/Mail.php
  tests/phpunit/CRM/Report/Form/Contribute/fixtures/DetailPostalCodeTest-ascii.csv
  tests/phpunit/CRM/Report/Form/Contribute/fixtures/report-ascii.csv
  tests/phpunit/CRM/Report/Form/Contribute/fixtures/report.csv
  tests/phpunit/CRM/Report/Form/TestCaseTest.php
  tests/phpunit/CRM/Report/Utils/ReportTest.php
  tests/phpunit/api/v3/JobTest.php
Labels: concept approved, easy-review, has-test, master, merge ready

#17846 Simplify flushing group contact cache query to reduce table locking and improve performance
  CRM/Contact/BAO/GroupContactCache.php
Labels: master

#17878 5.28
  CRM/Core/BAO/CustomGroup.php
Labels: master

#17874 Use new checkPermissions shorthand in api calls
  CRM/Contact/BAO/ContactType.php
  CRM/Contact/BAO/SavedSearch.php
  CRM/Contribute/BAO/ContributionRecur.php
  CRM/Core/BAO/MessageTemplate.php
  CRM/Dedupe/Merger.php
  CRM/Upgrade/Incremental/php/FiveTwentyEight.php
  CRM/Upgrade/Incremental/php/FiveTwentyOne.php
  CRM/Utils/Check/Component.php
  CRM/Utils/Migrate/Import.php
  Civi/Api4/Action/Setting/AbstractSettingAction.php
  Civi/Api4/Event/Subscriber/ActivityPreCreationSubscriber.php
  Civi/Api4/Event/Subscriber/OptionValuePreCreationSubscriber.php
  Civi/Api4/Generic/Traits/DAOActionTrait.php
  Civi/Api4/Service/Schema/Joinable/CustomGroupJoinable.php
  Civi/Api4/Service/Schema/SchemaMapBuilder.php
  Civi/Api4/Service/Spec/SpecGatherer.php
  ext/search/CRM/Search/Upgrader.php
  ext/sequentialcreditnotes/sequentialcreditnotes.php
  tests/phpunit/CRM/Contact/Form/Task/EmailCommonTest.php
  tests/phpunit/CRM/Core/BAO/ActionScheduleTest.php
  tests/phpunit/CRMTraits/Custom/CustomDataTrait.php
  tests/phpunit/api/v3/ACLPermissionTest.php
  tests/phpunit/api/v4/Action/BasicCustomFieldTest.php
  tests/phpunit/api/v4/Action/ComplexQueryTest.php
  tests/phpunit/api/v4/Action/ContactChecksumTest.php
  tests/phpunit/api/v4/Action/ContactGetTest.php
  tests/phpunit/api/v4/Action/CreateCustomValueTest.php
  tests/phpunit/api/v4/Action/CreateWithOptionGroupTest.php
  tests/phpunit/api/v4/Action/CustomValuePerformanceTest.php
  tests/phpunit/api/v4/Action/CustomValueTest.php
  tests/phpunit/api/v4/Action/ExtendFromIndividualTest.php
  tests/phpunit/api/v4/Action/FkJoinTest.php
  tests/phpunit/api/v4/Action/GetExtraFieldsTest.php
  tests/phpunit/api/v4/Action/NullValueTest.php
  tests/phpunit/api/v4/Action/PseudoconstantTest.php
  tests/phpunit/api/v4/Action/ReplaceTest.php
  tests/phpunit/api/v4/Action/ResultTest.php
  tests/phpunit/api/v4/Action/SqlFunctionTest.php
  tests/phpunit/api/v4/Action/UpdateContactTest.php
  tests/phpunit/api/v4/Action/UpdateCustomValueTest.php
  tests/phpunit/api/v4/Entity/ConformanceTest.php
  tests/phpunit/api/v4/Entity/ContactTypeTest.php
  tests/phpunit/api/v4/Entity/EntityTest.php
  tests/phpunit/api/v4/Entity/ParticipantTest.php
  tests/phpunit/api/v4/Entity/SavedSearchTest.php
  tests/phpunit/api/v4/Spec/SpecGathererTest.php
Labels: has-test, master

#17480 dev/core#1751: [Create Email] Only Show Update/Save Template when User has Permission to Edit Templates
  templates/CRM/Contact/Form/Task/EmailCommon.tpl
  templates/CRM/Mailing/Form/InsertTokens.tpl
Labels: master
