Repository civicrm/civicrm-core, pull requests merged in 2020-09, with the labels that each got.

#18301 dev/core#1982 - 5.29 version of PR 18282
  CRM/Case/XMLProcessor/Process.php
  tests/phpunit/api/v3/CaseTest.php
Labels: 5.29, merge on pass

#18302 5.29 to master
  CRM/Case/XMLProcessor/Process.php
  tests/phpunit/api/v3/CaseTest.php
Labels: master

#18237 Remove 'hack' that overwrites result of searchColumns hook in mailings list
  CRM/Mailing/Page/Browse.php
Labels: master, ok-without-test

#17810 [REF] Fix financial item allocation of negative payments against completed payments
  CRM/Financial/BAO/Payment.php
  tests/phpunit/api/v3/PaymentTest.php
Labels: has-test, master, merge on pass

#18290 dev/core#1983 Fix to tax calculation on multi-line-item
  CRM/Price/BAO/LineItem.php
  CRM/Price/BAO/PriceSet.php
  tests/phpunit/CRM/Event/BAO/ChangeFeeSelectionTest.php
  tests/phpunit/CRM/Member/Form/MembershipTest.php
Labels: 5.29

#18293 Move LineItem acl handling from v3 api to financialacls core extension
  CRM/Price/BAO/LineItem.php
  api/v3/LineItem.php
  ext/financialacls/financialacls.php
Labels: has-test, master

#18305 5.29
  CRM/Price/BAO/LineItem.php
  CRM/Price/BAO/PriceSet.php
  tests/phpunit/CRM/Event/BAO/ChangeFeeSelectionTest.php
  tests/phpunit/CRM/Member/Form/MembershipTest.php
Labels: master

#18294 [REF] Separate and move line-item specific portion of checkTaxAmount to LineItem api
  CRM/Contribute/BAO/Contribution.php
  api/v3/LineItem.php
Labels: has-test, master

#18279 Fix test set up to call Order.create to create the correct line items
  tests/phpunit/api/v3/ContributionTest.php
Labels: has-test, master

#18303 [REF] Clean up return variables on updateContributionStatus, updatePendingOnlineContribution
  CRM/Event/Form/Task/Batch.php
Labels: master

#18304 dev/core#1974: correct UI regression on custom field edit
  templates/CRM/Custom/Form/Field.tpl
Labels: 5.29

#18308 5.28 backports
  CRM/Case/XMLProcessor/Process.php
  CRM/Custom/Form/ChangeFieldType.php
  CRM/Price/BAO/LineItem.php
  CRM/Price/BAO/PriceSet.php
  templates/CRM/Custom/Form/Field.tpl
  tests/phpunit/CRM/Event/BAO/ChangeFeeSelectionTest.php
  tests/phpunit/CRM/Member/Form/MembershipTest.php
  tests/phpunit/api/v3/CaseTest.php
Labels: 5.28

#18311 REF Remove unused passbyreference and var from ipn_process_transaction
  api/v3/Contribution.php
Labels: master, merge on pass, sig-Refactor

#18310 Revert #18005 Fix buggy placement of icons
  CRM/Core/Controller.php
  CRM/Core/Smarty/plugins/block.crmButton.php
  ang/crmMailingAB/EditCtrl/report.html
  ang/crmUi.js
  css/civicrm.css
  js/crm.ajax.js
  templates/CRM/Admin/Form/Preferences/Display.tpl
  templates/CRM/Admin/Page/APIExplorer.tpl
  templates/CRM/Contact/Form/Search/Custom/FullText.tpl
  templates/CRM/Event/Form/ParticipantFeeSelection.tpl
  templates/CRM/Event/Page/DashBoard.tpl
  templates/CRM/Report/Form/Actions.tpl
  templates/CRM/Tag/Page/Tag.tpl
  templates/CRM/common/formButtons.tpl
Labels: 5.29

#18307 5.29.0 release notes initial run
  release-notes.md
  release-notes/5.29.0.md
Labels: 5.29

#18272 dev/core#1974 Fix incorrect handling of serialize key when changing custom field type
  CRM/Custom/Form/ChangeFieldType.php
Labels: 5.29, merge on pass

#18316 5.29 to master
  CRM/Core/Controller.php
  CRM/Core/Smarty/plugins/block.crmButton.php
  CRM/Custom/Form/ChangeFieldType.php
  ang/crmMailingAB/EditCtrl/report.html
  ang/crmUi.js
  css/civicrm.css
  js/crm.ajax.js
  release-notes.md
  release-notes/5.29.0.md
  templates/CRM/Admin/Form/Preferences/Display.tpl
  templates/CRM/Admin/Page/APIExplorer.tpl
  templates/CRM/Contact/Form/Search/Custom/FullText.tpl
  templates/CRM/Custom/Form/Field.tpl
  templates/CRM/Event/Form/ParticipantFeeSelection.tpl
  templates/CRM/Event/Page/DashBoard.tpl
  templates/CRM/Report/Form/Actions.tpl
  templates/CRM/Tag/Page/Tag.tpl
  templates/CRM/common/formButtons.tpl
Labels: master

#18312 dev/core#1974 - ChangeFieldType - "Select (w/serialize)" field should be treated like older "Multi-Select" fields
  CRM/Custom/Form/ChangeFieldType.php
Labels: 5.28, merge on pass

#18314 Update to 5.28.4. Add release notes.
  CRM/Upgrade/Incremental/sql/5.28.4.mysql.tpl
  release-notes.md
  release-notes/5.28.3.md
  release-notes/5.28.4.md
  sql/civicrm_generated.mysql
  xml/version.xml
Labels: 5.28

#18295 Test & remove handling for max_related in renewal form
  CRM/Member/Form/MembershipRenewal.php
  tests/phpunit/CRM/Member/Form/MembershipRenewalTest.php
Labels: has-test, master, sig-Refactor

#18315 [REF] Remove most interaction with $objects in completeOrder
  CRM/Contribute/BAO/Contribution.php
  CRM/Core/Payment/BaseIPN.php
  CRM/Event/Form/Task/Batch.php
  api/v3/Contribution.php
Labels: master, sig:code maintenance readability testability

#18319 5.28.4 release notes
  release-notes.md
  release-notes/5.28.3.md
  release-notes/5.28.4.md
Labels: 5.29

#18320 5.29
  release-notes.md
  release-notes/5.28.3.md
  release-notes/5.28.4.md
Labels: master

#18326 5.29.0 release notes final
  contributor-key.yml
  release-notes/5.29.0.md
Labels: 5.29

#18325 dev/mail#24, item 1 - Fix spec labels MailingEventSubscribe.create
  api/v3/MailingEventSubscribe.php
Labels: master, merge on pass

#18327 5.29
  contributor-key.yml
  release-notes/5.29.0.md
Labels: master

#18323 dev/core#1956 - Typo in call to nestedGroup on scheduled reminders admin form
  CRM/Admin/Form/ScheduleReminders.php
  CRM/Core/PseudoConstant.php
  tests/phpunit/CRM/Contact/BAO/GroupTest.php
Labels: has-test, master

#17980 [REF] Move function to delete merged contacts to the Merger class and include all instances of the pair
  CRM/Core/BAO/PrevNextCache.php
  CRM/Dedupe/Merger.php
Labels: master

#18332 dev/wordpress#73 - Be more forgiving about slash in wpBasePage
  CRM/Core/Config/MagicMerge.php
  CRM/Utils/System/WordPress.php
Labels: 5.29, merge on pass

#18333 (NFC) 5.29.0.md - Small updates
  release-notes/5.29.0.md
Labels: 5.29

#18335 Add ability to enable query logging per process
  CRM/Core/Error.php
Labels: master, merge ready

#18318 [REF] Add test for existing Participant batch update cancel and fix to not call BaseIPN->cancelled
  CRM/Core/Payment/BaseIPN.php
  CRM/Event/Form/Task/Batch.php
  tests/phpunit/CRM/Event/Form/Task/BatchTest.php
  tests/phpunit/CRMTraits/Financial/OrderTrait.php
Labels: has-test, master, sig:code maintenance readability testability

#18337 Remove pass-by-ref in PaypalProIPN::single
  CRM/Core/Payment/PayPalProIPN.php
Labels: master

#18329 Do not block user incase 'Require approval' is checked
  CRM/Utils/System/Drupal8.php
Labels: master

#18342 5.30.0 release notes initial run
  release-notes.md
  release-notes/5.30.0.md
Labels: 5.30

#18328 Remove unused deprecated handling for partial_amount_to_pay
  CRM/Contribute/BAO/Contribution.php
Labels: master

#18321 REF Filter params in completetransaction
  api/v3/Contribution.php
Labels: master, ok-without-test, sig:code maintenance readability testability

#18262 Take the guesswork out of rendering clientside CRM variables
  CRM/Core/Resources.php
Labels: master, merge ready

#18339 Move ACls on LineItem create to financialacls core extension
  CRM/Price/BAO/LineItem.php
  ext/financialacls/financialacls.php
  ext/financialacls/tests/phpunit/LineItemTest.php
  tests/phpunit/api/v3/FinancialTypeACLTest.php
Labels: master, merge on pass

#18344 5.30
  release-notes.md
  release-notes/5.30.0.md
Labels: master

#18264 dev/core#1926 - Try to autodetect mysql ssl settings from the CMS config
  setup/plugins/init/Backdrop.civi-setup.php
  setup/plugins/init/Drupal.civi-setup.php
  setup/plugins/init/Drupal8.civi-setup.php
  setup/plugins/installFiles/InstallSettingsFile.civi-setup.php
  setup/src/Setup/DrupalUtil.php
  templates/CRM/common/civicrm.settings.php.template
  tests/phpunit/Civi/Setup/DrupalUtilTest.php
Labels: has-test, master

#18247 Add higher-level support for "bundles" and "collections" of resources
  CRM/Core/Region.php
  CRM/Core/Resources.php
  CRM/Core/Resources/Bundle.php
  CRM/Core/Resources/CollectionAdderInterface.php
  CRM/Core/Resources/CollectionAdderTrait.php
  CRM/Core/Resources/CollectionInterface.php
  CRM/Core/Resources/CollectionTrait.php
  CRM/Core/Resources/Common.php
  CRM/Utils/Hook.php
  Civi/Core/Container.php
  tests/phpunit/CRM/Core/RegionTest.php
  tests/phpunit/CRM/Core/Resources/BundleTest.php
  tests/phpunit/CRM/Core/Resources/CollectionTestTrait.php
  tests/phpunit/CRM/Core/ResourcesTest.php
Labels: has-test, master

#18346 Preliminary cleanup on test
  tests/phpunit/api/v3/LineItemTest.php
Labels: master, merge on pass

#18343 Minor code cleanup - this is only ever called from one place so component is always event
  CRM/Event/Form/Task/Batch.php
Labels: master

#18331 Stop passing / using object when all we need is the id
  CRM/Contribute/BAO/Contribution.php
Labels: master, sig:code maintenance readability testability

#18348 Fix test to use validateAllContributions
  CRM/Contribute/Form/Contribution/Confirm.php
  CRM/Financial/BAO/Order.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/api/v3/ContributionPageTest.php
  tests/phpunit/api/v3/ContributionTest.php
Labels: has-test, master, merge on pass

#18347 Fix customField legacy handling in APIv3
  CRM/Core/DAO/CustomField.php
  CRM/Upgrade/Incremental/sql/5.29.1.mysql.tpl
  api/v3/CustomField.php
  tests/phpunit/CRM/Core/BAO/CustomFieldTest.php
  tests/phpunit/CRM/Core/BAO/CustomQueryTest.php
  tests/phpunit/CRM/Utils/Migrate/fixtures/Activity-text.xml
  tests/phpunit/CRM/Utils/Migrate/fixtures/ActivityMeeting-text.xml
  tests/phpunit/CRM/Utils/Migrate/fixtures/Contact-text.xml
  tests/phpunit/CRM/Utils/Migrate/fixtures/Individual-text.xml
  tests/phpunit/CRM/Utils/Migrate/fixtures/IndividualStudent-text.xml
  tests/phpunit/api/v3/CustomFieldTest.php
  tests/phpunit/api/v4/Action/CustomValueTest.php
  xml/schema/Core/CustomField.xml
Labels: 5.29, has-test

#18353 dev/core#1998 Address dedupe clash on dashboard contact
  CRM/Dedupe/Merger.php
Labels: 5.29

#18147 Improve consistency of metadata type declarations
  CRM/Contact/BAO/Contact.php
  CRM/Export/BAO/ExportProcessor.php
  tests/phpunit/CRM/Export/BAO/ExportTest.php
Labels: has-test, master

#18246 report#45 Ability to Search Smart or Normal Group using additional filter on Manage Group page
  CRM/Contact/BAO/Group.php
  CRM/Group/Form/Search.php
  CRM/Group/Page/AJAX.php
  templates/CRM/Group/Form/Search.tpl
  tests/phpunit/CRM/Group/Page/AjaxTest.php
Labels: master

#18359 dev/core#1921 Remove some places where the ghost of 2014 is getting special love
  CRM/Contribute/BAO/ContributionRecur.php
  CRM/Core/Payment/BaseIPN.php
Labels: master, merge on pass

#18361 [NFC] Update Event DAO Checksum
  CRM/Event/DAO/Event.php
Labels: 5.30, merge on pass

#18354 dev/user-interface#27 - Define a "bootstrap3" bundle (skeleton)
  CRM/Api4/Page/Api4Explorer.php
  CRM/Core/Resources/Common.php
  Civi/Core/Container.php
  ang/api4Explorer/Explorer.html
Labels: master, merge ready, ok-without-test

#18358 Use eventID rather than the object in completeTransaction
  CRM/Contribute/BAO/Contribution.php
  tests/phpunit/api/v3/ContributionTest.php
Labels: master

#18350 dev/financial#143 Convert Paypal Pro to use Guzzle
  CRM/Core/Payment/PayPalImpl.php
  tests/phpunit/CRM/Core/Payment/PaypalProTest.php
  tests/phpunit/CRM/Core/Payment/PaypalProTrait.php
Labels: has-test, master

#18363 Forward-merge 5.29 -> 5.30
  CRM/Core/DAO/CustomField.php
  CRM/Dedupe/Merger.php
  CRM/Upgrade/Incremental/sql/5.29.1.mysql.tpl
  api/v3/CustomField.php
  tests/phpunit/CRM/Core/BAO/CustomFieldTest.php
  tests/phpunit/CRM/Core/BAO/CustomQueryTest.php
  tests/phpunit/CRM/Utils/Migrate/fixtures/Activity-text.xml
  tests/phpunit/CRM/Utils/Migrate/fixtures/ActivityMeeting-text.xml
  tests/phpunit/CRM/Utils/Migrate/fixtures/Contact-text.xml
  tests/phpunit/CRM/Utils/Migrate/fixtures/Individual-text.xml
  tests/phpunit/CRM/Utils/Migrate/fixtures/IndividualStudent-text.xml
  tests/phpunit/api/v3/CustomFieldTest.php
  tests/phpunit/api/v4/Action/CustomValueTest.php
  xml/schema/Core/CustomField.xml
Labels: 5.30, merge on pass

#18340 Fixed pre hook params for LineItem
  CRM/Price/BAO/LineItem.php
Labels: master, merge on pass, ok-without-test

#18357 [REF] Simplify logic on calling self::updateContributionStatus
  CRM/Event/Form/Task/Batch.php
Labels: master

#18366 [NFC] Enable APIv4 Testing on the statusPrefence API Tests
  tests/phpunit/api/v3/StatusPreferenceTest.php
Labels: has-test, master, merge on pass

#18349 Migrate Eway(Single Currency) Payment Processor Type out into its own…
  .gitignore
  CRM/Event/DAO/Event.php
  CRM/Upgrade/Incremental/php/FiveThirtyOne.php
  distmaker/dists/common.sh
  ext/ewaysingle/CRM/Core/Payment/eWAY.mgd.php
  ext/ewaysingle/CRM/Core/Payment/eWAY.php
  ext/ewaysingle/LICENSE.txt
  ext/ewaysingle/README.md
  ext/ewaysingle/ewaysingle.civix.php
  ext/ewaysingle/ewaysingle.php
  ext/ewaysingle/images/screenshot.png
  ext/ewaysingle/info.xml
  ext/ewaysingle/lib/XML/Util.php
  ext/ewaysingle/lib/eWAY/eWAY_GatewayRequest.php
  ext/ewaysingle/lib/eWAY/eWAY_GatewayResponse.php
  ext/ewaysingle/phpunit.xml.dist
  ext/ewaysingle/tests/phpunit/CRM/Core/Payment/EwayTest.php
  ext/ewaysingle/tests/phpunit/bootstrap.php
  sql/civicrm_generated.mysql
  xml/templates/civicrm_data.tpl
Labels: has-test, master, merge on pass

#18368 [REF] Ensure that all bundle container services are public for Symfon…
  Civi/Core/Container.php
Labels: master, merge on pass

#18370 Tidy up testSubmitContributionPageWithPriceSetQuantity
  tests/phpunit/api/v3/ContributionPageTest.php
Labels: has-test, master, merge on pass

#18374 dev/core#1921 Further removal of iso date handling
  CRM/Core/Payment/PayPalIPN.php
Labels: master, merge on pass

#18376 Load event title from participantID
  CRM/Contribute/BAO/Contribution.php
Labels: has-test, master, merge on pass

#18375 Remove deprecated ids param
  CRM/Contribute/BAO/Contribution.php
Labels: master, merge on pass

#18377 [REF] Hide eway extension in UI and only install it if the original e…
  CRM/Upgrade/Incremental/php/FiveThirtyOne.php
  ext/ewaysingle/info.xml
Labels: master, merge on pass

#18351 Add test to cover existing v3 api setting of tax_amount on line items
  CRM/Financial/BAO/FinancialTypeAccount.php
  tests/phpunit/api/v3/LineItemTest.php
Labels: has-test, master

#18379 report#45 Switch out function call CRM_Utils_Array::value and extend …
  CRM/Contact/BAO/Group.php
  tests/phpunit/CRM/Group/Page/AjaxTest.php
Labels: has-test, master, merge on pass

#18352 dev/core#1980 Move tax handling from line item api to BAO to make it available from apiv4
  CRM/Price/BAO/LineItem.php
  api/v3/LineItem.php
Labels: has-test, master

#18386 dev/core#1989 - E_WARNING when editing custom field with logging turned on
  CRM/Logging/Schema.php
  tests/phpunit/CRM/Logging/SchemaTest.php
Labels: master

#18384 Add try catch to main loops on core ipn classes
  CRM/Core/Payment/AuthorizeNetIPN.php
  CRM/Core/Payment/PayPalIPN.php
  CRM/Core/Payment/PayPalProIPN.php
  tests/phpunit/CRM/Core/Payment/PayPalProIPNTest.php
Labels: master

#18383 dev/core#1921 Fix legacy date handling
  CRM/Contribute/BAO/Contribution.php
Labels: master

#18371 Rename variable $key to $participantID to make it clear what it is
  CRM/Event/Form/Task/Batch.php
Labels: master

#18369 Remove inaccessible call to baseIPN failed
  CRM/Core/Payment/BaseIPN.php
  CRM/Event/Form/Task/Batch.php
Labels: master

#18389 [REF] Remove unused lines from loadObjects
  CRM/Core/Payment/BaseIPN.php
Labels: master, merge on pass

#18391 [REF] Swap out CRM_Utils_Array::value() - partial pull out from PR 18207
  CRM/Contribute/BAO/Contribution.php
Labels: master, merge on pass

#18392 [NFC/Test framework] Make class name match file name
  tests/phpunit/CRM/Contact/AllTests.php
  tests/phpunit/CRM/Contact/BAO/RelationshipCacheTest.php
Labels: master, merge on pass

#18394 [NFC] Aim to reduce memory usage in create single value alter test by…
  tests/phpunit/api/v3/SyntaxConformanceTest.php
Labels: master

#18387 [REF] Mark CRM_Contribute_BAO_Contribution_Utils::formatAmount deprec…
  CRM/Contribute/BAO/Contribution.php
  CRM/Contribute/BAO/Contribution/Utils.php
Labels: has-test, master

#18338 Change wording on the Opt Out and Unsubscribe pages
  CRM/Mailing/Form/Optout.php
  CRM/Mailing/Form/Unsubscribe.php
Labels: master, ok-without-test

#18367 Remove unnecessary call to 'validateData' from pdf generator
  CRM/Contribute/Form/Task/PDF.php
Labels: master

#18385 [REF] simplify interaction with objects in complete order
  CRM/Contribute/BAO/Contribution.php
  tests/phpunit/CRM/Member/BAO/MembershipTest.php
Labels: master

#18373 [REF] Simplify loading of related objects in transition components
  CRM/Contribute/BAO/Contribution.php
Labels: master

#18372 Fix Invoice class to not call validateData
  CRM/Contribute/Form/Task/Invoice.php
  tests/phpunit/CRM/Contribute/Form/Task/InvoiceTest.php
Labels: has-test, master

#18381 Finish deprecating BaseIPN->completeTransaction
  CRM/Core/Payment/AuthorizeNetIPN.php
  CRM/Core/Payment/BaseIPN.php
  CRM/Core/Payment/PayPalIPN.php
  CRM/Core/Payment/PayPalProIPN.php
Labels: master

#18309 dev/core#1979 - Incorrect comparison of status_id when changing status of linked cases
  CRM/Case/BAO/Case.php
  tests/phpunit/CRM/Case/BAO/CaseTest.php
Labels: has-test, master

#18396 dev/core#1987: Enable frontend and backend theme configuration in display preference page for Drupal CMS
  templates/CRM/Admin/Form/Preferences/Display.tpl
Labels: master, merge on pass, ok-without-test

#18245 Fix for ongoing issues with static upsetting the apple cart
  CRM/Contribute/BAO/Contribution.php
  CRM/Member/BAO/Membership.php
  tests/phpunit/CRM/Member/Form/MembershipTest.php
  tests/phpunit/api/v3/JobTest.php
  tests/phpunit/api/v3/MembershipTest.php
Labels: has-test, master

#18399 Contact form task delete php spelling fix
  CRM/Contact/Form/Task/Delete.php
Labels: master, merge on pass

#18378 Remove redundant custom field types
  CRM/Core/BAO/CustomField.php
  CRM/Core/SelectValues.php
  CRM/Custom/Form/Field.php
  CRM/Profile/Page/MultipleRecordFieldsListing.php
  CRM/Upgrade/Incremental/sql/5.31.alpha1.mysql.tpl
  Civi/Api4/Service/Spec/SpecFormatter.php
  api/v3/CustomField.php
  tests/phpunit/CRM/Core/BAO/CustomFieldTest.php
  tests/phpunit/CRM/Core/BAO/CustomValueTableTest.php
  tests/phpunit/api/v3/CustomFieldTest.php
Labels: has-test, master

#18401 [REF] Improve the human readable name of the eway upgrade step to be …
  CRM/Upgrade/Incremental/php/FiveThirtyOne.php
Labels: master, merge on pass

#18365 [REF] Code cleanup on membership renewal & test
  CRM/Member/Form/MembershipRenewal.php
  tests/phpunit/CRM/Member/Form/MembershipRenewalTest.php
Labels: has-test, master

#18408 [NFC] 5.30 release-notes: first stab at annotating and sorting release notes
  contributor-key.yml
  release-notes/5.30.0.md
Labels: 5.30

#18402 Fix search extension excluded from tarball
  distmaker/dists/common.sh
Labels: 5.30, merge on pass

#18409 Fix formatLocaleNumericRoundedByCurrency
  CRM/Utils/Money.php
  tests/phpunit/CRM/Utils/MoneyTest.php
Labels: master, merge on pass

#18412 5.30
  contributor-key.yml
  distmaker/dists/common.sh
  release-notes/5.30.0.md
Labels: master

#18317 Add postAssert to check payments and contributions are valid on all tests.
  CRM/Contribute/Form/Contribution/Confirm.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/api/v3/ACLPermissionTest.php
  tests/phpunit/api/v3/ContributionPageTest.php
Labels: has-test, master

#18297 dev/core#2003 Civicrm_price_field_value.amount truncation when localisation in play
  CRM/Price/Form/Field.php
  CRM/Price/Form/Option.php
Labels: has-test, master

#18076 [REF] change deprecated function to API4 call
  CRM/Contribute/Form/Contribution/Confirm.php
  tests/phpunit/CRM/Contribute/BAO/ContributionTest.php
Labels: has-test, master

#18415 [REF] Minor readability fix
  CRM/ACL/BAO/ACL.php
Labels: master, merge on pass

#18414 [REF] Refactor price field form to allow for unit testing of the form
  CRM/Price/Form/Field.php
  tests/phpunit/CRM/Price/Form/FieldTest.php
Labels: master, merge on pass

#18413 Membership form test cleanup, date cleanup on form
  CRM/Member/Form/Membership.php
  tests/phpunit/CRM/Member/Form/MembershipTest.php
  tests/phpunit/CRM/Member/Form/dataset/data.xml
Labels: master, merge on pass

#18232 dev/core#1942 handle multiple membership of same membership type to u…
  CRM/Contribute/BAO/Contribution.php
  tests/phpunit/CRM/Core/Payment/BaseIPNTest.php
  tests/phpunit/api/v3/MembershipTest.php
Labels: has-test, master

#17641 dev/core#1590: Don't send reminders on deleted events
  CRM/Activity/ActionMapping.php
  CRM/Contact/ActionMapping.php
  CRM/Contribute/ActionMapping/ByPage.php
  CRM/Contribute/ActionMapping/ByType.php
  CRM/Event/ActionMapping.php
  CRM/Member/ActionMapping.php
  Civi/ActionSchedule/Mapping.php
  Civi/ActionSchedule/MappingInterface.php
  Civi/ActionSchedule/RecipientBuilder.php
  tests/phpunit/api/v3/JobTest.php
Labels: has-test, master

#16482 Implement more nuanced 'Administer CiviCRM permisions
  CRM/Core/Permission.php
  CRM/Core/xml/Menu/Admin.xml
  CRM/Event/Form/ManageEvent.php
  CRM/Event/Form/ManageEvent/TabHeader.php
  CRM/Event/Form/Registration/Register.php
  CRM/Event/Page/ManageEvent.php
  CRM/Grant/Page/DashBoard.php
  CRM/UF/Form/Inline/Preview.php
  CRM/Utils/Check.php
  tests/phpunit/CRM/Core/Permission/BaseTest.php
Labels: has-test, master

#18418 [ref] Extract failContribution code
  CRM/Contribute/BAO/Contribution.php
Labels: master, merge on pass

#18146 Export fix on long custom fields
  CRM/Export/BAO/ExportProcessor.php
  tests/phpunit/CRM/Export/BAO/ExportTest.php
  tests/phpunit/CRMTraits/Custom/CustomDataTrait.php
Labels: has-test, master

#18420 report#49: add contact type custom fields to contribution details
  CRM/Report/Form/Member/ContributionDetail.php
Labels: master, merge on pass

#18422 dev/core#1921 Remove more instances of civi 4.2 date handling
  CRM/Member/BAO/Membership.php
Labels: master

#18424 Remove CRM_Contact_BAO_Contact::getPrimaryOpenId
  CRM/Contact/BAO/Contact.php
  tests/phpunit/CRM/Contact/BAO/ContactTest.php
Labels: master, merge on pass

#18421 Minor code simplification on date handling in getMembershipStatusByDate
  CRM/Contribute/BAO/Contribution.php
  CRM/Member/BAO/Membership.php
  CRM/Member/BAO/MembershipStatus.php
  CRM/Member/Form/Membership.php
  CRM/Member/Import/Parser/Membership.php
  api/v3/MembershipStatus.php
  tests/phpunit/CRM/Member/BAO/MembershipStatusTest.php
  tests/phpunit/CRM/Member/Form/MembershipTest.php
Labels: master, merge on pass

#18393 Remove error handling from loadObjects
  CRM/Contribute/BAO/Contribution.php
  CRM/Core/Payment/BaseIPN.php
  tests/phpunit/CRM/Core/Payment/BaseIPNTest.php
Labels: master

#18406 Use title instead name in status message
  CRM/Admin/Form/OptionGroup.php
Labels: master

#17742 dev/core#1854: Fix Calculation of Overridden Membership Status
  CRM/Member/BAO/Membership.php
  tests/phpunit/CRM/Member/BAO/MembershipTest.php
Labels: has-test, master, sig:bug

#18395 Make period_type mandatory for MembershipType
  CRM/Core/DAO/CustomField.php
  CRM/Member/DAO/MembershipType.php
  CRM/Upgrade/Incremental/sql/5.31.alpha1.mysql.tpl
  Civi/Test/Api3TestTrait.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/api/v3/MembershipTypeTest.php
  tests/phpunit/api/v3/PaymentProcessorTypeTest.php
  xml/schema/Member/MembershipType.xml
Labels: master

#17595 PropertyBag - add cardNumber to getters
  Civi/Payment/PropertyBag.php
Labels: has-test, master

#18404 Switch frontend contribution form to cached/non-deprecated functions for membershipTypes
  CRM/Contribute/Form/Contribution/Main.php
Labels: master

#18388 dev/core#1980 Add v4 api LineItem entity
  Civi/Api4/LineItem.php
  tests/phpunit/api/v3/LineItemTest.php
Labels: has-test, master

#18426 NFC Clarify what CRM_Price_BAO_Priceset::getMembershipCount does
  CRM/Price/BAO/PriceSet.php
  tests/phpunit/CRM/Price/BAO/PriceSetTest.php
Labels: Non-functional-change (NFC), master, merge on pass

#18425 Revert "PropertyBag - add cardNumber to getters"
  Civi/Payment/PropertyBag.php
Labels: master, merge on pass

#18428 dev/core#2009 filter grant dashboard to exclude trashed contacts
  CRM/Grant/BAO/Grant.php
Labels: master, merge on pass

#18405 Replace & to and in button label
  CRM/Financial/Form/BatchTransaction.php
Labels: master, merge on pass

#18419 Custom field form reform
  CRM/Core/BAO/CustomField.php
  CRM/Core/DAO/AllCoreTables.php
  CRM/Core/DAO/CustomField.php
  CRM/Core/SelectValues.php
  CRM/Core/xml/Menu/Admin.xml
  CRM/Custom/Form/ChangeFieldType.php
  CRM/Custom/Form/Field.php
  Civi/Api4/Generic/AbstractAction.php
  Civi/Api4/Generic/Traits/DAOActionTrait.php
  Civi/Api4/Query/Api4SelectQuery.php
  Civi/Api4/Service/Schema/Joinable/CustomGroupJoinable.php
  Civi/Api4/Service/Schema/Joinable/Joinable.php
  Civi/Api4/Utils/FormattingUtil.php
  js/Common.js
  templates/CRM/Custom/Form/ChangeFieldType.tpl
  templates/CRM/Custom/Form/Field.tpl
  tests/phpunit/api/v3/CustomFieldTest.php
  tests/phpunit/api/v3/CustomValueTest.php
  tests/phpunit/api/v4/Action/CustomFieldAlterTest.php
  xml/schema/Core/CustomField.xml
Labels: has-test, master, merge on pass

#18433 dev/core#2017 Remove unused property, override function that just calls parent
  CRM/Member/BAO/MembershipStatus.php
Labels: master

#18438 [REF] Folllow up cleanup - remove now unused param
  CRM/Financial/BAO/Order.php
  CRM/Price/BAO/PriceSet.php
Labels: master

#18437 dev/core#2008 APIv4 - Map specific action names to more generic versions
  Civi/Api4/Generic/AbstractAction.php
Labels: 5.30

#18440 5.30 to master
  Civi/Api4/Generic/AbstractAction.php
Labels: master

#18441 APIv4 - Map specific action names to more generic versions
  Civi/Api4/Generic/AbstractAction.php
Labels: 5.29

#18443 Make symfony aliased services public
  Civi/Core/Container.php
Labels: master, merge on pass

#18446 Remove unnecessary debug from tests which messes up array output
  Civi/Test/Api3TestTrait.php
Labels: master, merge on pass

#18453 E_NOTICE on contribution confirm page
  CRM/Contribute/Form/Contribution/Confirm.php
Labels: 5.30, merge on pass, ok-without-test

#18455 5.30 to master
  CRM/Contribute/Form/Contribution/Confirm.php
Labels: master

#18454 dev/financial#149 Add permission = false to apiv4 call to address unreleased regression
  CRM/Contribute/BAO/Contribution.php
  CRM/Contribute/Form/Contribution/Confirm.php
  tests/phpunit/CRM/Contribute/Form/Contribution/ConfirmTest.php
  tests/phpunit/CRM/Event/Form/Registration/ConfirmTest.php
Labels: has-test, master, merge on pass

#18452 Move definition of userName to where it is used and remove an unused parameter
  CRM/Member/Form/MembershipRenewal.php
  tests/phpunit/CRM/Member/Form/MembershipRenewalTest.php
Labels: has-test, master, merge on pass

#18450 Pass in activity type rather than calculate it
  CRM/Event/BAO/Participant.php
Labels: master

#18435 [REF] minor tidy up on membershipStatus::create & add
  CRM/Member/BAO/MembershipStatus.php
  tests/phpunit/CRM/Member/BAO/MembershipStatusTest.php
Labels: master

#18457 dev/core#1921 remove isoToMysql
  CRM/Mailing/BAO/MailingJob.php
  tests/phpunit/api/v3/MailingTest.php
Labels: master, merge on pass

#18432 [REF] Simplify array construction
  CRM/Member/BAO/Membership.php
Labels: master

#18456 dev/core#1921 remove isoToMysql
  CRM/Activity/BAO/Activity.php
  CRM/Financial/BAO/FinancialItem.php
Labels: master, merge on pass

#18459 dev/financial#147 Ensure that jQuery Validation doesn't execute when …
  CRM/Core/Payment/PayPalImpl.php
Labels: 5.30, merge on pass, ok-without-test

#18462 5.30 to master
  CRM/Core/Payment/PayPalImpl.php
Labels: master

#18460 Update code comments
  CRM/Contribute/Form/ContributionBase.php
Labels: master, merge on pass

#18467 Fix parameters for MembershipTest
  tests/phpunit/CRM/Member/Form/MembershipTest.php
Labels: master

#18431 Search extension: edit smart groups
  CRM/Contact/BAO/SavedSearch.php
  CRM/Contact/Form/Search.php
  CRM/Group/Form/Edit.php
  ang/api4Explorer/Explorer.js
  ext/search/CRM/Search/Page/Ang.php
  ext/search/ang/search.module.js
  ext/search/ang/search/SaveSmartGroup.ctrl.js
  ext/search/ang/search/crmSearch.component.js
  ext/search/ang/search/crmSearch/criteria.html
  templates/CRM/Contact/Form/Search/Basic.hlp
  templates/CRM/Contact/Form/Search/Intro.tpl
  templates/CRM/Contact/Form/Search/ResultTasks.tpl
  templates/CRM/Group/Form/Edit.tpl
Labels: master, merge on pass, ok-without-test

#18469 dev/core#1921 Further removal of iso date handling
  CRM/Case/BAO/Case.php
  tests/phpunit/api/v3/CaseTest.php
Labels: master

#18472 dev/core#1393 - distmaker - Fix URL-based installation on D7/BD
  distmaker/dists/backdrop_php5.sh
  distmaker/dists/common.sh
  distmaker/dists/drupal6_php5.sh
  distmaker/dists/drupal_php5.sh
  distmaker/dists/drupal_sk_php5.sh
Labels: master

#18461 dev/drupal#138 - Drupal 9 deprecations
  CRM/Utils/System/Drupal8.php
Labels: master

#18473 dev/core#2036 - PEAR::DB is no longer in packages, now autoloaded from vendor
  install/civicrm.php
Labels: 5.30

#18474 5.30
  install/civicrm.php
Labels: master

#18468 dev/core#1921 Remove iso convert
  CRM/Activity/Page/AJAX.php
Labels: master
