Repository civicrm/civicrm-core, pull requests merged in 2020-06, with the labels that each got.

#17437 [NFC/TEST] dev/core#1784 - Unit tests for contact delete/restore
  tests/phpunit/CRM/Contact/Form/Task/DeleteTest.php
Labels: master, merge on pass

#17420 [REF] Refactor to switch from pear HTTP Request class to using Guzzle
  CRM/Utils/Address/USPS.php
  CRM/Utils/Geocode/Google.php
Labels: master

#17435 Revert Matt's fix for dev/membership#24 as it is incomplete and add a…
  CRM/Member/BAO/Membership.php
  CRM/Member/Page/Tab.php
  tests/phpunit/api/v3/FinancialTypeACLTest.php
Labels: master, merge on pass

#17436 [REF] Simplify subject code.
  CRM/Contact/Form/Task/EmailTrait.php
Labels: master, merge on pass

#17439 [NFC] Update Karma to be latest version
  package-lock.json
  package.json
Labels: master

#17441 [REF] Simplify contributionIDs code
  CRM/Contact/Form/Task/EmailTrait.php
  tests/phpunit/CRM/Activity/BAO/ActivityTest.php
Labels: master

#17425 APIv4 - Fix entity name on custom groups in schemaMapper
  Civi/Api4/Action/Entity/GetLinks.php
  Civi/Api4/Query/Api4SelectQuery.php
  Civi/Api4/Service/Schema/Joinable/CustomGroupJoinable.php
  Civi/Api4/Service/Schema/SchemaMapBuilder.php
Labels: master, merge on pass

#17451 Navigation menu: fix translation of new-subtype entries
  CRM/Contact/BAO/ContactType.php
Labels: master

#17449 [REF] Convert one of the http calls in Authorize.net class to use guzzle.
  CRM/Core/Payment/AuthorizeNet.php
  Civi/Test/GuzzleTestTrait.php
  tests/phpunit/CRM/Core/Payment/AuthorizeNetTest.php
Labels: master, merge on pass

#17457 5.26.0 release notes initial run
  release-notes.md
  release-notes/5.26.0.md
Labels: 5.26

#17438 dev/core#1747 don't drop temp tables on class destruct.
  CRM/Contact/Form/Search/Custom/DateAdded.php
Labels: 5.26

#17459 5.26 to master
  CRM/Contact/Form/Search/Custom/DateAdded.php
  release-notes.md
  release-notes/5.26.0.md
Labels: master

#17463 Update MembershipType.name to be a required field
  CRM/Core/I18n/SchemaStructure.php
  CRM/Member/DAO/MembershipType.php
  xml/schema/Member/MembershipType.xml
Labels: master, merge on pass

#17460 [REF] Bump Pear Log version to fix compatability with Drupal 8 / Drup…
  composer.json
  composer.lock
Labels: master, merge on pass

#17298 dev/core#1753 - Attachments aren't deleted when deleting activity
  CRM/Activity/BAO/Activity.php
  tests/phpunit/CRM/Activity/Form/ActivityTest.php
Labels: has-test, master, merge ready

#17430 Nuance cancel options for processors
  CRM/Contribute/Form/CancelSubscription.php
  CRM/Core/Payment.php
  CRM/Core/Payment/Manual.php
  Civi/Payment/PropertyBag.php
  templates/CRM/Contribute/Form/CancelSubscription.tpl
Labels: master, ready for review

#17443 [REF] Minor simplification
  CRM/Member/Form/MembershipRenewal.php
Labels: master

#17424 Add Upgrade Warning. Limit to WP Only.
  CRM/Upgrade/Incremental/php/FiveTwentySix.php
Labels: 5.26, merge on pass

#17462 dev/core#1780 Fix bug where non-household merge contacts were being skipped
  CRM/Export/BAO/ExportProcessor.php
Labels: 5.26

#17465 [REF] Implement required fields database changes that have occured du…
  CRM/Upgrade/Incremental/php/FiveTwentySeven.php
Labels: master, merge on pass

#17466 Add actual field name for processor_id to getSubscriptionDetails
  CRM/Contribute/BAO/ContributionRecur.php
  CRM/Contribute/Form/CancelSubscription.php
  CRM/Contribute/Form/UpdateBilling.php
  CRM/Contribute/Form/UpdateSubscription.php
Labels: master, merge on pass

#17467 5.26
  CRM/Export/BAO/ExportProcessor.php
  CRM/Upgrade/Incremental/php/FiveTwentySix.php
Labels: master

#17413 Allow bidirectional assignment of relationships from search results
  CRM/Case/Form/AddToCaseAsRole.php
  CRM/Contact/BAO/Relationship.php
Labels: master

#17372 Add more search options
  CRM/Contact/BAO/Contact.php
Labels: master

#17469 [REF] Fix serialized membership field handling in RelationshipTest
  tests/phpunit/api/v3/RelationshipTest.php
Labels: master, merge on pass

#17472 Annotated 5.26 release notes
  contributor-key.yml
  release-notes/5.26.0.md
Labels: 5.26

#17471 APIv4 - Improve custom field spec gathering
  Civi/Api4/Service/Schema/Joinable/CustomGroupJoinable.php
  Civi/Api4/Service/Spec/SpecGatherer.php
Labels: master

#17447 Don't allow Contribution.repeattransaction to be used without a recurring contribution
  api/v3/Contribution.php
Labels: master, ready for review

#17464 [REF] Remove never-passed params from function signature
  CRM/Member/Form/MembershipRenewal.php
Labels: master, merge on pass

#17446 Fixed hide show of start date
  templates/CRM/Contribute/Form/Contribution.tpl
Labels: master

#17442 [REF] Switch to an api call to get the contact details.
  CRM/Contact/Form/Task/EmailTrait.php
Labels: master

#17444 dev/core#1725 Remove groups, tags and notes from the returned data fo…
  CRM/Export/Form/Map.php
Labels: 5.26

#17468 Remove unused singleton from core payment processors
  CRM/Core/Payment/AuthorizeNet.php
  CRM/Core/Payment/Dummy.php
  CRM/Core/Payment/Elavon.php
  CRM/Core/Payment/FirstData.php
  CRM/Core/Payment/PayJunction.php
  CRM/Core/Payment/PayflowPro.php
  CRM/Core/Payment/PaymentExpress.php
  CRM/Core/Payment/PaymentExpressIPN.php
  CRM/Core/Payment/Realex.php
  CRM/Core/Payment/eWAY.php
Labels: master

#17474 Remove last reference to Payment->_processorName in core & remove from processors
  CRM/Contribute/Form/UpdateBilling.php
  CRM/Core/Payment.php
  CRM/Core/Payment/AuthorizeNet.php
  CRM/Core/Payment/Dummy.php
  CRM/Core/Payment/Elavon.php
  CRM/Core/Payment/PayJunction.php
  CRM/Core/Payment/PayPalImpl.php
  CRM/Core/Payment/PayflowPro.php
  CRM/Core/Payment/PaymentExpress.php
  CRM/Core/Payment/Realex.php
  CRM/Core/Payment/eWAY.php
Labels: master

#17470 NFC - Change array() to short syntax []
  CRM/Admin/Page/ConfigTaskList.php
  CRM/Admin/Page/Job.php
  CRM/Admin/Page/JobLog.php
  CRM/Admin/Page/PaymentProcessor.php
  CRM/Campaign/Form/Search.php
  CRM/Case/XMLProcessor/Report.php
  CRM/Contact/Form/Task/SaveSearch/Update.php
  CRM/Contact/Import/Form/Preview.php
  CRM/Contact/Import/ImportJob.php
  CRM/Contact/Page/View/Relationship.php
  CRM/Contact/Page/View/Summary.php
  CRM/Contact/Task.php
  CRM/Contribute/Form/UpdateBilling.php
  CRM/Contribute/Page/ContributionPage.php
  CRM/Core/Action.php
  CRM/Core/BAO/CustomField.php
  CRM/Core/BAO/Note.php
  CRM/Core/Block.php
  CRM/Core/Menu.php
  CRM/Event/Form/Registration.php
  CRM/Event/Import/Form/MapField.php
  CRM/Extension/Browser.php
  CRM/Extension/Container/Default.php
  CRM/Extension/Downloader.php
  CRM/Group/Form/Edit.php
  CRM/Mailing/Event/BAO/Bounce.php
  CRM/Member/Import/Form/MapField.php
  CRM/Member/Page/DashBoard.php
  CRM/Pledge/BAO/Pledge.php
  CRM/Pledge/BAO/PledgeBlock.php
  CRM/Report/Form/Campaign/SurveyDetails.php
  CRM/Report/Form/Contact/Summary.php
  CRM/Report/Form/Contribute/Repeat.php
  CRM/Report/Form/Event/ParticipantListing.php
  CRM/SMS/Page/Provider.php
  CRM/SMS/Provider.php
  Civi.php
  Civi/Core/Themes.php
  Civi/Test/DbTestTrait.php
  Civi/Test/GenericAssertionsTrait.php
  Civi/Test/MailingTestTrait.php
  install/civicrm.php
  tests/extensions/test.extension.manager.paymenttest/main.php
  tests/extensions/test.extension.manager.searchtest/main.php
  tests/phpunit/CiviTest/CiviDBAssert.php
  tests/phpunit/CiviTest/CiviMailUtils.php
  tests/phpunit/CiviTest/CiviReportTestCase.php
  tests/phpunit/CiviTest/CiviTestSMSProvider.php
  tests/phpunit/CiviTest/CiviTestSuite.php
  tests/phpunit/E2E/Core/AssetBuilderTest.php
  tests/phpunit/E2E/Extern/RestTest.php
  tests/phpunit/E2E/Extern/SoapTest.php
Labels: master

#17478 Document recent merge in regards to select fields for export screen a…
  release-notes/5.26.0.md
Labels: 5.26

#17476 5.26
  CRM/Export/Form/Map.php
  contributor-key.yml
  release-notes/5.26.0.md
Labels: master

#17481 [REF] Extract createFollowUpActivities
  CRM/Contact/Form/Task/EmailTrait.php
Labels: master

#17482 APIv4 - Support pseudoconstant suffixes in orderBy clause
  Civi/Api4/Query/Api4SelectQuery.php
  ang/api4Explorer/Explorer.html
  ang/api4Explorer/Explorer.js
  tests/phpunit/api/v4/Action/BasicActionsTest.php
  tests/phpunit/api/v4/Action/PseudoconstantTest.php
Labels: has-test, master

#17483 5.26.0 release notes final
  release-notes/5.26.0.md
Labels: 5.26

#17484 5.26
  release-notes/5.26.0.md
Labels: master

#17485 5.26.0 - Small edits
  CRM/Upgrade/Incremental/sql/5.26.0.mysql.tpl
  release-notes/5.26.0.md
  sql/civicrm_generated.mysql
  xml/version.xml
Labels: 5.26

#17486 5.26
  release-notes/5.26.0.md
Labels: master

#17493 dev/core/-/issues/1794, changed int to tinyint for boolean fields
  CRM/Core/DAO/CustomGroup.php
  CRM/Upgrade/Incremental/sql/5.27.alpha1.mysql.tpl
  sql/civicrm_generated.mysql
  xml/schema/Core/CustomGroup.xml
Labels: master

#17488 Test fixes to support apiv4 add of MembershipType
  tests/phpunit/api/v3/RelationshipTest.php
Labels: master

#17492 [NFC] Fix use of single quotes, strict operator
  CRM/Contact/BAO/Query.php
Labels: master, merge on pass

#17426 Make reCAPTCHA settings clearer
  settings/Core.setting.php
  templates/CRM/Admin/Form/Setting/Miscellaneous.tpl
Labels: master, ready for review, sig:user interfacing improvement

#17490 [Ref] remove calls to, and deprecate, pending function
  CRM/Core/Payment/BaseIPN.php
  CRM/Core/Payment/PayPalIPN.php
  CRM/Core/Payment/PayPalProIPN.php
Labels: master

#17494 set boolean fields to false if not set.
  CRM/Admin/Form/ScheduleReminders.php
Labels: master, merge on pass

#17473 Convert remaining Authorize.net test to use guzzle
  CRM/Core/Payment/AuthorizeNet.php
  tests/phpunit/CRM/Core/Payment/AuthorizeNetTest.php
Labels: master

#17448 Add MembershipType to Api4
  Civi/Api4/MembershipType.php
Labels: master, merge on pass

#17497 dev/core#1797 Fix jquery Credit card validation on front end contribu…
  CRM/Core/Resources.php
Labels: master

#17498 dev/core#1797 Fix jquery Credit card validation on front end contribu…
  CRM/Core/Resources.php
Labels: 5.26

#17495 dev/core#1794 Fix issue where unchecking a checkbox may not get reflected in the database
  CRM/Admin/Form/ScheduleReminders.php
  CRM/Core/DAO/CustomGroup.php
  CRM/Upgrade/Incremental/sql/5.26.1.mysql.tpl
  sql/civicrm_generated.mysql
  xml/schema/Core/CustomGroup.xml
Labels: 5.26

#17489 [REF] Remove always NULL param modified_id
  CRM/Member/Form/MembershipRenewal.php
Labels: master

#17496 dev/core#1681 Add in notice about 5.28 Dropping MySQL 5.5 Support
  CRM/Upgrade/Incremental/General.php
  CRM/Utils/Check/Component/Env.php
Labels: master, merge on pass

#17505 Payment PropertyBag - Fix setAmount
  Civi/Payment/PropertyBag.php
Labels: master, merge on pass

#17452 [REF] Start to convert Dummy processor to use PropertyBag
  CRM/Core/Payment/Dummy.php
  CRM/Utils/Hook.php
  Civi/Payment/PropertyBag.php
Labels: master

#17519 (Backport) dev/core#1681 - Update MySQL version notices
  CRM/Upgrade/Incremental/General.php
  CRM/Utils/Check/Component/Env.php
Labels: 5.26, merge on pass

#17518 dev/core#1681 - Copy-edits on MySQL version notices
  CRM/Upgrade/Incremental/General.php
  CRM/Utils/Check/Component/Env.php
Labels: master, merge on pass

#17520 5.26.1 - Bump version. Add notes.
  release-notes.md
  release-notes/5.26.1.md
  sql/civicrm_generated.mysql
  xml/version.xml
Labels: 5.26

#17521 Add release-notes/5.26.1.md
  release-notes.md
  release-notes/5.26.1.md
Labels: master

#17529 CommunityMessages - Define more consistent behavior in the face of slow execution
  CRM/Core/CommunityMessages.php
  tests/phpunit/CRM/Core/CommunityMessagesTest.php
Labels: 5.27

#17360 WP - Change definitions of `cms.root`, `civicrm.root`
  CRM/Utils/System/WordPress.php
  Civi/Core/Paths.php
Labels: 5.27, merge on pass

#17530 5.27
  CRM/Core/CommunityMessages.php
  CRM/Utils/System/WordPress.php
  Civi/Core/Paths.php
  tests/phpunit/CRM/Core/CommunityMessagesTest.php
Labels: master

#17510 Payment instrument ID is not required at processorform level
  CRM/Core/Payment/ProcessorForm.php
Labels: master, needs-concept-approval

#17532 QueueTest - Be more forgiving about slow execution
  tests/phpunit/CRM/Queue/QueueTest.php
Labels: 5.27, merge on pass

#17502 Fix probably-unused core payment processors to throw extensions
  CRM/Core/Payment/FirstData.php
  CRM/Core/Payment/PayJunction.php
Labels: master

#17538 5.27
  tests/phpunit/CRM/Queue/QueueTest.php
Labels: master

#17536 [Ref] Remove some instances of fatal in BAO classes
  CRM/Batch/BAO/Batch.php
  CRM/Campaign/BAO/Petition.php
  CRM/Cxn/CiviCxnHttp.php
  CRM/Financial/BAO/PaymentProcessor.php
  CRM/Financial/BAO/PaymentProcessorType.php
  CRM/Member/BAO/Membership.php
  CRM/Utils/HttpClient.php
Labels: master, merge on pass

#17528 [NFC] Update existing APIv3 MembershipType Tests to also test against…
  tests/phpunit/api/v3/MembershipTypeTest.php
Labels: master, merge on pass

#17535 Remove unused deprecated class
  CRM/Admin/Page/Setting.php
Labels: master, merge on pass

#17534 Remove instances of fatal from upgrade folder
  CRM/Upgrade/Form.php
  CRM/Upgrade/Incremental/php/FourThree.php
  CRM/Upgrade/Page/Upgrade.php
Labels: master, merge on pass

#17511 Add isBackOffice, isPayLater, getPaymentMode helpers to frontendpaymentformtrait
  CRM/Event/Form/Registration.php
  CRM/Event/Form/Registration/Register.php
  CRM/Financial/Form/FrontEndPaymentFormTrait.php
Labels: master, merge on pass

#17541 dev/core#560 Replace deprecated CRM_Core_Erorr::fatal with Exceptions…
  CRM/Contact/BAO/SearchCustom.php
  CRM/Contact/Form/Search/Custom/PriceSet.php
  CRM/Contact/Import/ImportJob.php
  CRM/Contribute/BAO/Contribution.php
  CRM/Contribute/Form/AbstractEditPayment.php
  CRM/Contribute/Form/Contribution/Main.php
  CRM/Contribute/Form/Task/Invoice.php
  CRM/Contribute/Form/Task/Status.php
  CRM/Contribute/Import/Parser.php
  CRM/Import/DataSource/CSV.php
  CRM/Report/Form.php
  CRM/Report/Form/Activity.php
  CRM/Report/Page/Options.php
  tools/extensions/org.civicrm.angularex/angularex.civix.php
Labels: master, merge on pass

#17539 Replace calls to fatal with statusBounces
  CRM/Activity/Page/Tab.php
  CRM/Admin/Form/Extensions.php
  CRM/Campaign/Form/Survey/Delete.php
  CRM/Campaign/Page/Petition/Confirm.php
  CRM/Custom/Form/Group.php
  CRM/UF/Form/Inline/Preview.php
Labels: master, merge on pass

#17504 [REF] Remove handling for 2 fields not on the form
  CRM/Member/Form/MembershipRenewal.php
Labels: master

#17499 [Ref] Remove calls to, and deprecate, unhandled function
  CRM/Core/Payment/BaseIPN.php
  CRM/Core/Payment/PayPalIPN.php
  CRM/Core/Payment/PayPalProIPN.php
Labels: master

#17500 [Ref] Throw exceptions from Authorize.net rather than return errors
  CRM/Core/Payment/AuthorizeNet.php
Labels: master

#17491 [Ref] Simplify the replacing of the email with the email from the url
  CRM/Contact/Form/Task/EmailTrait.php
Labels: master

#17540 APIv4 - filter getActions results based on user permissions
  Civi/Api4/Action/GetActions.php
Labels: master

#17533 [REF] Replace some instances of fatal with thrown exceptions.
  CRM/Bridge/OG/CiviCRM.php
  CRM/Bridge/OG/Drupal.php
  CRM/Bridge/OG/Utils.php
  CRM/Extension/Manager/Payment.php
  CRM/Extension/Manager/Search.php
  CRM/Financial/BAO/FinancialType.php
  CRM/PCP/BAO/PCP.php
  CRM/Pledge/BAO/Pledge.php
  CRM/Pledge/BAO/PledgeBlock.php
  CRM/Price/BAO/PriceSet.php
  tests/phpunit/CRM/Financial/BAO/FinancialTypeTest.php
Labels: master, merge on pass

#17542 dev/financial#131 Fix Eway processor to throw exceptions rather than return errors
  CRM/Core/Payment/eWAY.php
Labels: master, merge on pass

#17544 Fix validateAll to no longer support unused abort param
  CRM/Contact/BAO/Query.php
  CRM/Utils/Type.php
Labels: master, merge on pass

#17545 dev/core#560 Convert final CRM_Core_Error::fatal to statusBounces or …
  CRM/Activity/BAO/Activity.php
  CRM/Activity/Import/Parser.php
  CRM/Contact/BAO/Query.php
  CRM/Contribute/BAO/Contribution.php
  CRM/Core/Controller.php
  CRM/Core/IDS.php
  CRM/Core/JobManager.php
  CRM/Core/Page/AJAX.php
  CRM/Core/Page/Redirect.php
  CRM/Core/Permission.php
  CRM/Core/Region.php
  CRM/Core/Selector/Base.php
  CRM/Custom/Form/ChangeFieldType.php
  CRM/Custom/Form/Field.php
  CRM/Custom/Form/Option.php
  CRM/Custom/Import/Parser.php
  CRM/Custom/Page/Field.php
  CRM/Custom/Page/Option.php
  CRM/Event/BAO/Participant.php
  CRM/Event/BAO/ParticipantPayment.php
  CRM/Event/Cart/BAO/Cart.php
  CRM/Event/Cart/BAO/EventInCart.php
  CRM/Event/Form/ManageEvent/Repeat.php
  CRM/Event/Form/ManageEvent/TabHeader.php
  CRM/Event/Form/Registration.php
  CRM/Event/Import/Parser.php
  CRM/Event/Page/ParticipantListing.php
  CRM/Financial/Page/FinancialTypeAccount.php
  CRM/Member/Form/Task/Batch.php
  CRM/Member/Import/Parser.php
  CRM/Member/Page/DashBoard.php
  CRM/PCP/BAO/PCP.php
  CRM/PCP/Form/Campaign.php
  CRM/PCP/Form/PCPAccount.php
  CRM/Price/Form/Option.php
  CRM/Profile/Form.php
  CRM/Profile/Page/Dynamic.php
  CRM/Profile/Page/Listings.php
  CRM/Profile/Page/View.php
  CRM/Queue/Page/Runner.php
  CRM/Queue/Queue/Sql.php
  CRM/UF/Page/ProfileEditor.php
Labels: master, merge on pass

#17546 Remove isThrowException from CRM_Utils_Type::validate() signature
  CRM/Contact/BAO/Query.php
  CRM/Utils/Check/Component/OptionGroups.php
  CRM/Utils/Type.php
Labels: master, merge on pass

#17543 [Ref] Readability extraction in Dummy class
  CRM/Core/Payment/Dummy.php
Labels: master, merge on pass

#17549 [Ref] Remove another instance of fatal()
  CRM/Friend/Form.php
Labels: master, merge on pass

#17523 Zip code range search only supports numeric zip codes
  CRM/Contact/Form/Search/Custom/ZipCodeRange.php
Labels: master

#17512 dev/core#1798 - "End of yesterday" Relative Date Filter
  CRM/Utils/Date.php
  tests/phpunit/CRM/Utils/DateTest.php
Labels: has-test, master, ok-without-test

#17179 Add payment processor to details on list of recurring contributions
  templates/CRM/Contribute/Page/ContributionRecurSelector.tpl
Labels: master, ready for review

#17374 CRM_Core_I18n::setLocale() - Fix bug with repeated usage
  CRM/Core/I18n.php
  tests/phpunit/CRM/Core/I18n/LocaleTest.php
Labels: master

#16514 Fix PHP notice when we don't have credit card params
  CRM/Contribute/Form/AbstractEditPayment.php
  CRM/Contribute/Form/AdditionalInfo.php
  CRM/Contribute/Form/Contribution/Confirm.php
  CRM/Contribute/Form/UpdateBilling.php
  CRM/Core/Form.php
  CRM/Event/Form/Participant.php
  CRM/Member/Form/Membership.php
Labels: master, ready for review

#16610 Allow adding datepicker to metadata based settings pages
  CRM/Admin/Form/SettingTrait.php
  CRM/Core/Form.php
Labels: master, needs-work

#17550 Remove last instance of CRM_Core_Error::fatal....
  CRM/Utils/Request.php
Labels: master, merge on pass

#17553 Update contributor-key.yml
  contributor-key.yml
Labels: master

#17552 Support passing old method name into deprecatedFunctionWarning
  CRM/Core/Error.php
Labels: master, merge on pass

#17506 Payment Propertybag remove warning
  Civi/Payment/PropertyBag.php
  tests/phpunit/Civi/Payment/PropertyBagTest.php
Labels: master, merge on pass

#17554 Fix "Undefined variable: entryFound" notice on Bookkeeping report
  CRM/Report/Form/Contribute/Bookkeeping.php
Labels: master

#17501 [Ref] Convert Authorize.net doDirectPayment to use guzzle & add test
  CRM/Core/Payment/AuthorizeNet.php
  tests/phpunit/CRM/Core/Payment/AuthorizeNetTest.php
Labels: master

#17450 dev/core#1782 Set activity_date_time and created_date to default to current_timestamp
  CRM/Activity/DAO/Activity.php
  CRM/Upgrade/Incremental/General.php
  CRM/Upgrade/Incremental/sql/5.28.alpha1.mysql.tpl
  xml/schema/Activity/Activity.xml
Labels: master, merge on pass

#17555 dev/core#560 Add in deprecated function warning now that fatal is dep…
  CRM/Core/Error.php
Labels: master, merge on pass

#17515 [REF] Replace the deprecated system_rebuild_module_data function with…
  CRM/Utils/System/Drupal8.php
  setup/plugins/installDatabase/FlushDrupal8.civi-setup.php
Labels: master, merge on pass, ok-without-test

#17557 dev/core#1801 Fix hardcoded activity priority by label
  CRM/Activity/Form/Activity.php
Labels: master, merge on pass

#17559 dev/financial#131 Fix Realex processor to correctly throw an exception
  CRM/Core/Payment/Realex.php
Labels: master, merge on pass

#17556 [Ref] Remove never reachable lines.
  CRM/Member/Form/MembershipRenewal.php
Labels: master, merge on pass

#17525 Remove deprecated billingID from baseIPN
  CRM/Core/Payment/AuthorizeNetIPN.php
  CRM/Core/Payment/BaseIPN.php
  CRM/Core/Payment/PayPalIPN.php
  CRM/Core/Payment/PayPalProIPN.php
Labels: master, merge on pass

#17566 [NFC] Minor code cleanup
  CRM/Contact/Page/DedupeMerge.php
  CRM/Dedupe/Merger.php
Labels: master, merge on pass

#17548 Set ContactType.name as required in the schema.
  CRM/Admin/Form/ContactType.php
  CRM/Contact/BAO/ContactType.php
  CRM/Contact/DAO/ContactType.php
  CRM/Upgrade/Incremental/sql/5.28.alpha1.mysql.tpl
  sql/civicrm_generated.mysql
  xml/schema/Contact/ContactType.xml
Labels: master

#17570 [REF] Add in upgrade step to populate missing contact_type.name field
  CRM/Upgrade/Incremental/php/FiveTwentyEight.php
  CRM/Upgrade/Incremental/sql/5.28.alpha1.mysql.tpl
  tests/phpunit/CRM/Upgrade/Incremental/BaseTest.php
Labels: master, merge on pass

#17575 [REF] Using ternary operation without nesting is deprecated and also …
  CRM/Core/Form.php
  tests/phpunit/CRM/Activity/BAO/ActivityTest.php
Labels: master, merge on pass

#17440 dev/core#1749 Fix missing parameter in link to logging detail
  CRM/Logging/ReportSummary.php
  CRM/Report/Form/Contact/LoggingSummary.php
Labels: master

#17574 [REF] Using {} to access string or array offsets has been deprecated …
  CRM/Mailing/BAO/MailingJob.php
  CRM/Utils/SQL/Insert.php
  Civi/Core/Resolver.php
  ext/sequentialcreditnotes/sequentialcreditnotes.civix.php
Labels: master, merge on pass

#15796 dev/core#183 Use CRM_Utils_SQL_TempTable for generating temp table na…
  Civi/Install/Requirements.php
  install/index.php
Labels: master

#17573 [REF] Replace incorrect usages of array_key_exists when the variable …
  CRM/Contact/BAO/Contact.php
  CRM/Core/PseudoConstant.php
  api/v3/Membership.php
  api/v3/utils.php
Labels: master, merge on pass

#17578 (dev/core#1787) Regression : File fields export results in DB error
  CRM/Export/BAO/ExportProcessor.php
Labels: master

#17576 APIv4 - Skip empty leaves in WHERE clause
  Civi/Api4/Query/Api4SelectQuery.php
Labels: master

#17531 Add icons to multi-valued custom groups and display on contact tab
  CRM/Contact/Page/View/Summary.php
  CRM/Core/BAO/CustomGroup.php
  CRM/Core/DAO/CustomGroup.php
  CRM/Custom/Form/Group.php
  CRM/Upgrade/Incremental/php/FiveTwentyEight.php
  Civi/Api4/Action/Entity/Get.php
  templates/CRM/Custom/Form/Group.tpl
  xml/schema/Core/CustomGroup.xml
Labels: master

#17565 dev/financial#131 Fix Elavon processor to throw exceptions
  CRM/Core/Payment/Elavon.php
Labels: master

#17567 Dedupe performance - hard-remove financial_item from list of dymnamic refs to contact table
  CRM/Core/DAO.php
  CRM/Dedupe/MergeHandler.php
Labels: 5.27

#17577 Add in deprecation notice and status check for a money value format co…
  CRM/Utils/Check/Component/Schema.php
  CRM/Utils/Money.php
  templates/CRM/Admin/Form/Setting/Localization.tpl
Labels: 5.27, merge on pass

#17582 Fix duplicate upgrade function
  CRM/Upgrade/Incremental/php/FiveTwentyEight.php
Labels: master, merge on pass

#17584 Fix fatal error regression in master
  CRM/Contribute/Form/UpdateBilling.php
Labels: master, merge on pass

#17583 5.27
  CRM/Core/DAO.php
  CRM/Dedupe/MergeHandler.php
  CRM/Utils/Check/Component/Schema.php
  CRM/Utils/Money.php
  templates/CRM/Admin/Form/Setting/Localization.tpl
Labels: master

#17586 [REF] Fix unit test failures on MySQL 5.6 due to Custom Field table being created without Dynamic Row Format
  CRM/Core/BAO/CustomField.php
Labels: 5.27, merge on pass

#17587 5.27
  CRM/Core/BAO/CustomField.php
Labels: master

#17581 EventInfo template cleanup
  templates/CRM/Event/Page/EventInfo.tpl
Labels: master, sig:user interfacing improvement

#17563 Remove unreachable lines
  CRM/Member/BAO/Membership.php
  CRM/Member/Form/MembershipRenewal.php
Labels: master

#17144 dev/core#1716 add customPre hook
  CRM/Core/BAO/CustomValueTable.php
  CRM/Utils/Hook.php
Labels: master

#17487 [Ref] Mark unused date functions as deprecated
  CRM/Core/Form/Date.php
Labels: master

#17585 [Ref] Convert Authorize.net to use Guzzle for update subscription class, add test
  CRM/Core/Payment/AuthorizeNet.php
  tests/phpunit/CRM/Core/Payment/AuthorizeNetTest.php
Labels: master

#17579 Update has_separator field in civicrm_navigation
  CRM/Admin/Form/Navigation.php
  CRM/Core/CodeGen/Specification.php
  CRM/Core/DAO/Navigation.php
  CRM/Core/SelectValues.php
  CRM/Upgrade/Incremental/sql/5.28.alpha1.mysql.tpl
  css/crm-menubar.css
  xml/schema/Core/Navigation.xml
Labels: master

#17591 5.26 backports from 5.27
  CRM/Core/BAO/CustomField.php
  CRM/Core/DAO.php
  CRM/Dedupe/MergeHandler.php
  CRM/Utils/Check/Component/Schema.php
  CRM/Utils/Money.php
  templates/CRM/Admin/Form/Setting/Localization.tpl
Labels: 5.26, merge on pass

#17592 dev/financial#131 Remove legacy error handling from Paypal code.
  CRM/Core/Payment/PayJunction.php
  CRM/Core/Payment/PayflowPro.php
Labels: master, merge on pass

#17593 Fix retrieving MySQL version for checking as part of install requirem…
  Civi/Install/Requirements.php
Labels: master

#17522 [REF] Remove deprecated methods of booting drupal container and getti…
  CRM/Utils/System/Drupal8.php
Labels: master

#17551 dev/core#1803 Update guzzlehttp, psr7, psrlog, cxn-pc
  composer.lock
Labels: master

#16918 Add smarty error event
  Civi/Core/Event/SmartyErrorEvent.php
Labels: master, ready for review

#17603 NFC Formatting cleanup on contribution/recur templates
  templates/CRM/Contribute/Form/AdditionalInfo/Payment.tpl
  templates/CRM/Contribute/Form/Contribution.tpl
  templates/CRM/Contribute/Form/Contribution/Main.tpl
Labels: Non-functional-change (NFC), master

#17599 [REF] Fix some additional issues where curly braces were being used t…
  CRM/Custom/Form/Field.php
  CRM/Utils/Number.php
  Civi/Core/Themes.php
Labels: master

#17601 [REF] Fix another couple of uses of array_key_exists when the variabl…
  CRM/Core/Page/Basic.php
Labels: master

#17598 [REF] Update packages to work with PHP7.4
  composer.json
  composer.lock
Labels: master

#17564 [REF] Add test for renewing old expired membership via form
  CRM/Member/Form/MembershipRenewal.php
  tests/phpunit/CRM/Member/Form/MembershipRenewalTest.php
Labels: master

#17597 dev/financial#131 Remove last places where Core Processors return error object
  CRM/Core/Payment/AuthorizeNet.php
Labels: master

#17596 dev/financial#131 Give deprecation notice if the payment processor returns an error
  CRM/Core/Payment.php
Labels: master

#17606 [NFC] Update mocking to use getMockBuilder instead instead of createMock
  tests/phpunit/CRM/Core/CommunityMessagesTest.php
  tests/phpunit/CRM/Core/JobManagerTest.php
  tests/phpunit/CRM/Extension/ManagerTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/api/v3/ContactTest.php
Labels: master, merge on pass

#17605 [NFC] Add assertions to existing test to lock in current behaviour
  tests/phpunit/CRM/Member/Form/MembershipRenewalTest.php
Labels: master, merge on pass

#17604 [REF] Replace incorrect usage of array_key_exists with property_exist…
  CRM/Contact/BAO/Group.php
Labels: master, merge on pass

#17600 [REF] Fix issue with using array access tools on NULL values
  CRM/Contact/BAO/Query.php
  CRM/Contact/Page/AJAX.php
  CRM/Contribute/Form/Contribution/Confirm.php
  CRM/Contribute/Form/Contribution/Main.php
  CRM/Group/Form/Edit.php
  CRM/Mailing/ActionTokens.php
  CRM/Profile/Page/MultipleRecordFieldsListing.php
  CRM/Report/Form.php
  tests/phpunit/api/v4/Entity/ParticipantTest.php
Labels: master, merge on pass

#17607 Fix payment instrument bug by using correct payment instrument
  CRM/Contribute/Form/AbstractEditPayment.php
Labels: 5.27
