Repository civicrm/civicrm-core, pull requests merged in 2020-04, with the labels that each got.

#16930 dev/core#1677 Fix multisite regression on domain membership types
  CRM/Member/BAO/MembershipType.php
Labels: 5.24

#16933 dev/user-interface#14 Fix membership_status_id url handling (recent regression).
  CRM/Member/BAO/Membership.php
  CRM/Member/BAO/Query.php
  CRM/Member/Form/Search.php
  CRM/Member/Page/DashBoard.php
Labels: 5.24

#16937 [REF] Fix handling of owner url parameter from Membership Dashboard
  CRM/Member/Form/Search.php
Labels: 5.24

#16938 5.24
  CRM/Member/BAO/Membership.php
  CRM/Member/BAO/MembershipType.php
  CRM/Member/BAO/Query.php
  CRM/Member/Form/Search.php
  CRM/Member/Page/DashBoard.php
  templates/CRM/Mailing/Form/Search/Common.tpl
Labels: master

#16921 Add hook to alter display value or Custom field value
  CRM/Core/BAO/CustomField.php
  CRM/Utils/Hook.php
  tests/phpunit/CRM/Core/BAO/CustomFieldTest.php
Labels: master

#16885 [NFC/TEST] Resurrect unfinished test for getRelatedCases()
  CRM/Case/Form/Activity/LinkCases.php
  tests/phpunit/CRM/Case/BAO/CaseTest.php
Labels: master

#16935 [REF] Start transitioning EmailCommon class to a trait
  CRM/Activity/Form/Task/Email.php
  CRM/Contact/Form/Task/Email.php
  CRM/Contact/Form/Task/EmailTrait.php
  CRM/Contribute/Form/Task/Email.php
  CRM/Event/Form/Task/Email.php
  CRM/Member/Form/Task/Email.php
Labels: master

#16944 [NFC] adding late changes to release notes for 5.24
  release-notes/5.24.0.md
Labels: 5.24

#16946 5.24
  release-notes/5.24.0.md
Labels: master

#16945 fixes dev/core#1683 set profile frontend title
  CRM/Profile/Form/Edit.php
Labels: master

#16941 Follow up PR for #16845 - Fix form error when variable is NULL
  CRM/Core/Form.php
Labels: master

#16940 [REF] Move properties to Trait
  CRM/Contact/Form/Task/Email.php
  CRM/Contact/Form/Task/EmailTrait.php
Labels: master

#16919 dev/core#1674: fix rebuilding of container on every request
  CRM/Api4/Services.php
Labels: master

#16943 dev/core#1682 - Invalid currency on sending offline membership receipt.
  CRM/Member/Form/Membership.php
  templates/CRM/Member/Form/Membership.tpl
Labels: master

#16947 APIv4 - Support GROUP BY and aggregate functions
  Civi/Api4/Generic/AbstractGetAction.php
  Civi/Api4/Generic/DAOGetAction.php
  Civi/Api4/Generic/DAOGetFieldsAction.php
  Civi/Api4/Generic/Traits/DAOActionTrait.php
  Civi/Api4/Query/Api4SelectQuery.php
  Civi/Api4/Query/SqlExpression.php
  Civi/Api4/Query/SqlField.php
  Civi/Api4/Query/SqlFunction.php
  Civi/Api4/Query/SqlFunctionAVG.php
  Civi/Api4/Query/SqlFunctionCOUNT.php
  Civi/Api4/Query/SqlFunctionMAX.php
  Civi/Api4/Query/SqlFunctionMIN.php
  Civi/Api4/Query/SqlFunctionSUM.php
  Civi/Api4/Query/SqlNull.php
  Civi/Api4/Query/SqlNumber.php
  Civi/Api4/Query/SqlString.php
  Civi/Api4/Query/SqlWild.php
  ang/api4Explorer/Explorer.html
  ang/api4Explorer/Explorer.js
  tests/phpunit/api/v4/Action/SqlExpressionTest.php
  tests/phpunit/api/v4/Action/SqlFunctionTest.php
  tests/phpunit/api/v4/Query/SqlExpressionParserTest.php
  tests/phpunit/api/v4/UnitTestCase.php
Labels: has-test, master, merge on pass

#16950 Remove deprecated cleaning of money in the BAO layer
  CRM/Contribute/BAO/Contribution.php
Labels: master

#16951 Revert "APIv4 - Fix contribution create"
  Civi/Api4/Generic/Traits/DAOActionTrait.php
Labels: master, merge on pass

#16948 [REF] move buildQuickForm function to the trait
  CRM/Activity/Form/Task/Email.php
  CRM/Contact/Form/Task/Email.php
  CRM/Contact/Form/Task/EmailTrait.php
  CRM/Contribute/Form/Task/Email.php
  CRM/Event/Form/Task/Email.php
  CRM/Member/Form/Task/Email.php
Labels: master

#16753 dev/core#1528 - Consolidate to single constant for minimum PHP version
  CRM/Upgrade/Form.php
  CRM/Upgrade/Incremental/General.php
  CRM/Utils/Check/Component/Env.php
  install/index.php
  tests/phpunit/CRM/Upgrade/FormTest.php
Labels: master, ok-without-test

#16700 Fix WordPress support for Get UF Locale
  CRM/Utils/System/WordPress.php
Labels: master, merge ready, ok-without-test

#16961 core#1688 - false positive on missing custom field check
  CRM/Utils/Check/Component/Schema.php
Labels: 5.25

#16962 5.25
  CRM/Utils/Check/Component/Schema.php
Labels: master

#16964 Update FinancialTrxn.php
  CRM/Financial/DAO/FinancialTrxn.php
Labels: master

#16963 core#1688 - false positive on missing custom field check
  CRM/Utils/Check/Component/Schema.php
Labels: 5.24

#16965 Code cleanup - replace overcomplicated test for null with isset
  CRM/Core/BAO/CustomGroup.php
  CRM/Core/DAO.php
Labels: master

#16969 [REF] Update XML file to match updated title in DAO File
  CRM/Financial/DAO/FinancialTrxn.php
  xml/schema/Financial/FinancialTrxn.xml
Labels: master, merge on pass

#16971 dev/financial#84 - Fix upgrade failure. Thin-out activation logic for `sequentialcreditnotes`.
  CRM/Upgrade/Incremental/php/FiveTwentyFour.php
Labels: 5.25, merge on pass

#16972 dev/financial#84 - Fix upgrade failure. Thin-out activation logic for `sequentialcreditnotes`.
  CRM/Upgrade/Incremental/php/FiveTwentyFour.php
Labels: 5.24, merge on pass

#16974 5.25
  CRM/Upgrade/Incremental/php/FiveTwentyFour.php
Labels: master

#16973 Capitalise PAN truncation
  api/v3/Payment.php
Labels: master, merge on pass

#16975 [REF] CustomField - Remove pointless caching and move form variable to form class
  CRM/Core/BAO/CustomField.php
  CRM/Custom/Form/Field.php
  tests/phpunit/api/v3/CustomFieldTest.php
  tests/phpunit/api/v3/CustomValueTest.php
Labels: master

#16977 Set version to 5.24.1. Add notes.
  CRM/Upgrade/Incremental/sql/5.24.1.mysql.tpl
  release-notes.md
  release-notes/5.24.1.md
  sql/civicrm_generated.mysql
  xml/version.xml
Labels: 5.24

#16970 [REF] CustomGroup - cleanup handling of serialized fields in old function
  CRM/Core/BAO/CustomGroup.php
Labels: master

#16966 dev/translation#4 - Add nl_BE language
  install/langs.php
  sql/civicrm_generated.mysql
  xml/templates/languages.tpl
Labels: master

#16979 Use isSerialized function rather guessing from html_type
  CRM/Contribute/Import/Parser/Contribution.php
  CRM/Event/Import/Parser/Participant.php
  CRM/Member/Import/Parser/Membership.php
  CRM/Utils/DeprecatedUtils.php
Labels: master, merge on pass

#16980 [REF] Call makeCSVTable function directly from writeRows
  CRM/Export/BAO/ExportProcessor.php
Labels: master

#16978 Add release-notes/5.24.1
  release-notes.md
  release-notes/5.24.1.md
Labels: 5.25

#16981 Fix multiselect/checkbox custom field defaults on registration profile
  CRM/Event/BAO/Participant.php
Labels: master

#16991 Fix multiselect/checkbox custom field defaults on contribution online form
  CRM/Contribute/Form/Contribution/Main.php
Labels: master

#16988 5.25
  release-notes.md
  release-notes/5.24.1.md
Labels: master

#16990 [REF] Cleanup CustomField BAO to use its own isSerialized function
  CRM/Core/BAO/CustomField.php
Labels: master

#16984 Cleanup custom field handling in ufGroup BAO
  CRM/Core/BAO/UFGroup.php
Labels: master

#16989 [REF] Cleanup custom field handling... twice
  CRM/Contact/Import/Parser.php
  CRM/Utils/DeprecatedUtils.php
Labels: master

#16623 Fix values passed to tokenValues hook
  CRM/Contact/Form/Task/Label.php
  CRM/Contact/Form/Task/LabelCommon.php
  CRM/Mailing/BAO/Mailing.php
  CRM/Mailing/Page/Preview.php
  CRM/Utils/Hook.php
  CRM/Utils/Token.php
  Civi/Token/TokenCompatSubscriber.php
Labels: master

#16953 dev/core#1685 - Search builder returns DB error on Group => Empty filter
  CRM/Contact/BAO/Query.php
  tests/phpunit/CRM/Contact/BAO/QueryTest.php
Labels: master

#16901 Fix bug on handling 'is_required'
  CRM/Admin/Form/SettingTrait.php
Labels: master

#16997 Fix setting custom field TextArea attributes
  CRM/Core/BAO/CustomField.php
Labels: master, merge on pass

#16986 [REF] Update custom data handing in contact import
  CRM/Contact/Import/Parser.php
Labels: master

#17000 [NFC] Add Comment to avoid someone removing field only used in CiviCase extension
  CRM/Case/Form/Case.php
  xml/schema/Case/Case.xml
Labels: master

#17001 dev/core#1673 Ensure that SQL statements are not duplicated in the de…
  CRM/Report/Form.php
Labels: master, merge on pass

#16996 [REF] Cleanup customField prepareCreate function
  CRM/Core/BAO/CustomField.php
Labels: master

#17002 [NFC][Test] Minor cleanup in test class
  tests/phpunit/api/v3/JobTest.php
Labels: master

#16968 [REF] CustomField code cleanup
  CRM/Contribute/Form/Contribution/Confirm.php
  CRM/Core/BAO/CustomGroup.php
Labels: master

#17009 [REF] CustomField code cleanup to use isSerialized method
  CRM/Core/BAO/CustomField.php
Labels: master, merge on pass

#17012 [REF] Formatting and use bool instead of boolean
  CRM/Case/XMLProcessor/Process.php
Labels: master, merge on pass

#17013 [REF] Use bool instead of boolean
  CRM/Core/Permission.php
  CRM/Event/Page/List.php
  CRM/Report/Form/Grant/Statistics.php
Labels: master, merge on pass

#17016 [REF] Clarify variable & tighten use.
  CRM/Dedupe/Merger.php
  tests/phpunit/api/v3/JobTestCustomDataTest.php
Labels: master, merge on pass

#17014 add nl_BE language
  install/langs.php
  sql/civicrm_generated.mysql
  xml/templates/languages.tpl
Labels: 5.25

#16837 dev/core#1659: Fix Case.get API returning Case Clients As Part of Related Contacts
  CRM/Case/BAO/Case.php
  tests/phpunit/api/v3/CaseTest.php
Labels: master, merge on pass, needs-test

#17017 add nl_BE language
  install/langs.php
  sql/civicrm_generated.mysql
  xml/templates/languages.tpl
Labels: 5.24, merge on pass

#17019 [NFC] Minor code cleanups
  CRM/Dedupe/Merger.php
Labels: master, merge on pass

#17004 Fixed fatal error for class not found when managed hook is invoked du…
  CRM/Utils/Hook.php
Labels: 5.25, merge on pass

#17023 5.25 to master
  CRM/Utils/Hook.php
Labels: master

#17010 Fixed fatal error for class not found when managed hook is invoked during upgrade
  CRM/Utils/Hook.php
Labels: 5.24, merge on pass

#16954 [REF] Move generic preProcess function to the trait
  CRM/Activity/Form/Task/Email.php
  CRM/Contact/Form/Task/EmailTrait.php
  CRM/Contribute/Form/Task/Email.php
  CRM/Event/Form/Task/Email.php
  CRM/Member/Form/Task/Email.php
Labels: master

#17022 [NFC][Test] cleanup on customDataTrait for tests
  tests/phpunit/CRM/Core/BAO/CustomFieldTest.php
  tests/phpunit/CRMTraits/Custom/CustomDataTrait.php
  tests/phpunit/api/v3/ContactTest.php
  tests/phpunit/api/v3/ContributionTest.php
Labels: master, merge on pass

#16899 Mailing Report: hide the HTML preview
  templates/CRM/Mailing/Page/Report.tpl
Labels: master

#17020 Start using apiv4 in test setup
  tests/phpunit/CRMTraits/Custom/CustomDataTrait.php
Labels: master, merge on pass

#17021 CRM_Core_I18n - Provide a better label for new/unknown locales
  CRM/Core/I18n.php
Labels: 5.25

#16959 Add email link in case summary
  templates/CRM/Case/Form/CaseView.tpl
Labels: master

#17029 [REF] Move generic instances of listTokens to trait
  CRM/Activity/Form/Task/Email.php
  CRM/Contact/Form/Task/Email.php
  CRM/Contact/Form/Task/EmailTrait.php
  CRM/Event/Form/Task/Email.php
  CRM/Member/Form/Task/Email.php
Labels: master, merge on pass

#17033 Revert "temp workaround for dev/core#1675"
  CRM/Case/XMLProcessor/Process.php
Labels: 5.25, merge on pass

#17015 APIv4 - Add support for HAVING clause
  Civi/Api4/Generic/DAOGetAction.php
  Civi/Api4/Query/Api4SelectQuery.php
  Civi/Api4/Query/SqlExpression.php
  Civi/Api4/Query/SqlField.php
  Civi/Api4/Query/SqlFunction.php
  Civi/Api4/Query/SqlNumber.php
  Civi/Api4/Query/SqlString.php
  tests/phpunit/api/v4/Action/SqlFunctionTest.php
  tests/phpunit/api/v4/Query/SqlExpressionParserTest.php
Labels: master, merge on pass

#17035 5.25
  CRM/Case/XMLProcessor/Process.php
  CRM/Core/I18n.php
Labels: master

#17031 [REF] Update Contact email form to use the trait for EmailCommon functions
  CRM/Contact/Form/Task/Email.php
  CRM/Contact/Form/Task/EmailTrait.php
Labels: master

#17034 REF Remove redundant param from completeOrder
  CRM/Activity/BAO/Activity.php
  CRM/Contribute/BAO/Contribution.php
  CRM/Core/Payment/BaseIPN.php
  api/v3/Contribution.php
Labels: master, merge on pass

#16993 Add / make fit for purpose email.getlist api call
  api/v3/Email.php
  api/v3/Generic/Getlist.php
  tests/phpunit/CRM/Contact/Form/Task/EmailCommonTest.php
  tests/phpunit/api/v3/ContactTest.php
  tests/phpunit/api/v3/EmailTest.php
Labels: has-test, master

#17036 CRM_Core_I18n - Provide a better label for new/unknown locales
  CRM/Core/I18n.php
Labels: 5.24

#16903 Allow setting metadata to use the `table` option. Update example setting `default_invoice_page`.
  Civi/Core/SettingsMetadata.php
  settings/Contribute.setting.php
  tests/phpunit/CRM/Core/BAO/SettingTest.php
Labels: has-test, master

#16976 [REF] Extract transferParticipantRegistration function
  CRM/Event/Form/SelfSvcTransfer.php
  tests/phpunit/CRM/Event/Form/ParticipantTest.php
Labels: master

#17039 Revert "temp workaround for dev/core#1675"
  CRM/Case/XMLProcessor/Process.php
Labels: 5.24, merge on pass

#17041 Add release-notes/5.24.2
  release-notes.md
  release-notes/5.24.2.md
Labels: 5.25

#17040 Update to 5.24.2. Add release notes.
  CRM/Upgrade/Incremental/sql/5.24.2.mysql.tpl
  release-notes.md
  release-notes/5.24.2.md
  sql/civicrm_generated.mysql
  xml/version.xml
Labels: 5.24

#17042 5.25
  release-notes.md
  release-notes/5.24.2.md
Labels: master

#16888 Allow adding variables to CRM.vars in any region
  CRM/Core/Resources.php
Labels: master

#17038 Mitigate flaky test failure about "CRM_Utils_Check_Component_Env->checkVersion()"
  CRM/Utils/Check/Component/Env.php
Labels: master

#17025 set is_deceased to not null in schema and upgrade script dev/core#1697
  CRM/Contact/DAO/Contact.php
  CRM/Upgrade/Incremental/sql/5.26.alpha1.mysql.tpl
  xml/schema/Contact/Contact.xml
Labels: master, merge on pass

#17024 dev/core#1696 - Update attachment message on mailing form.
  ang/crmAttachment.js
  ang/crmAttachment/attachments.html
Labels: master

#16987 Add missing translations to case activity revisions
  templates/CRM/Case/Form/ActivityView.tpl
Labels: master

#17011 Simplify groupContactCache - remove redundant query
  CRM/Contact/BAO/GroupContactCache.php
Labels: master

#17027 dev/translation#4 - Upgrade script for nl_BE
  CRM/Upgrade/Incremental/php/FiveTwentySix.php
Labels: master

#17046 core#1700 - Fix Financial ACL Report check
  CRM/Utils/Check/Component/FinancialTypeAcls.php
Labels: easy-review, master

#17043 Update 5.24.2.md - Fix version number in title.
  release-notes/5.24.2.md
Labels: master

#17047 dev/report#31 - Api4 Explorer: Support SQL functions and HAVING clause
  CRM/Api4/Page/Api4Explorer.php
  Civi/Api4/Generic/AbstractQueryAction.php
  Civi/Api4/Query/SqlFunction.php
  ang/api4Explorer/Clause.html
  ang/api4Explorer/Explorer.html
  ang/api4Explorer/Explorer.js
  css/api4-explorer.css
  tests/phpunit/api/v4/Action/SqlFunctionTest.php
Labels: has-test, master, merge on pass

#16772 Fix bug where tax_amount is miscalculated on membership renewals
  CRM/Financial/BAO/Order.php
  CRM/Member/Form.php
  CRM/Member/Form/MembershipRenewal.php
  CRM/Price/BAO/PriceSet.php
  tests/phpunit/CRM/Member/Form/MembershipRenewalTest.php
  tests/phpunit/CRM/Member/Form/MembershipTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: has-test, master

#17048 dev/translation#4 - Refine upgrade steps for modifying nl_NL
  CRM/Upgrade/Incremental/php/FiveTwentySix.php
  CRM/Utils/SQL.php
  tests/phpunit/CRM/Utils/SQLTest.php
Labels: master

#17044 add filter for receipt date in contribution reports
  CRM/Report/Form/Contribute/Bookkeeping.php
  CRM/Report/Form/Contribute/DeferredRevenue.php
  CRM/Report/Form/Contribute/History.php
  CRM/Report/Form/Contribute/HouseholdSummary.php
  CRM/Report/Form/Contribute/OrganizationSummary.php
  CRM/Report/Form/Contribute/SoftCredit.php
  CRM/Report/Form/Contribute/Summary.php
  CRM/Report/Form/Contribute/TopDonor.php
Labels: master

#17049 [NFC] Fix use of pattern-hated-by-Coleman
  CRM/Core/BAO/Phone.php
Labels: master, merge on pass

#16957 fixed mapping when using custom field for contact sub type
  CRM/Contact/Import/Form/MapField.php
Labels: master

#17037 [Test] Extend custom field test trait & some related tests
  tests/phpunit/CRM/Contact/Import/Form/MapFieldTest.php
  tests/phpunit/CRM/Core/BAO/CustomFieldTest.php
  tests/phpunit/CRM/Core/BAO/CustomQueryTest.php
  tests/phpunit/CRMTraits/Custom/CustomDataTrait.php
  tests/phpunit/api/v3/ContactTest.php
Labels: master, merge on pass

#17053 Make transaction param optional in completeOrder
  CRM/Contribute/BAO/Contribution.php
  CRM/Core/Payment/BaseIPN.php
  api/v3/Contribution.php
Labels: master

#17052 Duplicate EmailCommon::buildQuickForm onto the trait
  CRM/Contact/Form/Task/EmailCommon.php
  CRM/Contact/Form/Task/EmailTrait.php
  tests/phpunit/CRM/Contact/Form/Task/EmailCommonTest.php
Labels: master

#17050 Improve AngularJS performance with one-time binding for static strings
  ang/api4Explorer/Chain.html
  ang/api4Explorer/Clause.html
  ang/api4Explorer/Explorer.html
  ang/api4Explorer/SaveSearch.html
  ang/crmAttachment/attachments.html
  ang/crmCaseType/activityTypesTable.html
  ang/crmCaseType/caseTypeDetails.html
  ang/crmCaseType/edit.html
  ang/crmCaseType/list.html
  ang/crmCaseType/rolesTable.html
  ang/crmCaseType/sequenceTable.html
  ang/crmCaseType/statusTable.html
  ang/crmCaseType/timelineTable.html
  ang/crmCxn/AdvTable.html
  ang/crmCxn/ConfirmReconnectCtrl.html
  ang/crmCxn/Connectivity.html
  ang/crmCxn/ManageCtrl.html
  ang/crmCxn/PermTable.html
  ang/crmExample/example.html
  ang/crmMailing/BlockPreview.html
  ang/crmMailing/BlockRecipients.html
  ang/crmMailing/BlockReview.html
  ang/crmMailing/BlockSchedule.html
  ang/crmMailing/BlockTemplates.html
  ang/crmMailing/BodyHtml.html
  ang/crmMailing/BodyText.html
  ang/crmMailing/EditMailingCtrl/2step.html
  ang/crmMailing/EditMailingCtrl/base.html
  ang/crmMailing/EditMailingCtrl/unified.html
  ang/crmMailing/EditMailingCtrl/unified2.html
  ang/crmMailing/EditMailingCtrl/wizard.html
  ang/crmMailing/EditMailingCtrl/workflow.html
  ang/crmMailing/EditRecipOptionsDialogCtrl.html
  ang/crmMailing/EmailBodyCtrl/tokenAlert.html
  ang/crmMailing/PreviewComponentDialogCtrl.html
  ang/crmMailing/PreviewRecipCtrl.html
  ang/crmMailing/SaveMsgTemplateDialogCtrl.html
  ang/crmMailingAB/BlockMailing.html
  ang/crmMailingAB/BlockSetup.html
  ang/crmMailingAB/EditCtrl/edit.html
  ang/crmMailingAB/EditCtrl/report.html
  ang/crmMailingAB/ListCtrl.html
  ang/crmMailingAB/Slider.html
  ang/crmMailingAB/WinnerDialogCtrl.html
  ang/crmStatusPage/SnoozeOptions.html
  ang/crmStatusPage/StatusPage.html
  ang/crmUi/wizard.html
  ang/exportui/export.html
  tests/phpunit/CRM/Utils/HTMLTest.php
  tools/extensions/org.civicrm.angularex/partials/example.html
Labels: has-test, master

#17058 [NFC] Code cleanup around comments, strict comparison, formatting
  CRM/Member/Form/Membership.php
  CRM/Member/Form/MembershipRenewal.php
Labels: master

#17057 [REF] move all functions associated with the submit function onto the Trait
  CRM/Contact/Form/Task/EmailCommon.php
  CRM/Contact/Form/Task/EmailTrait.php
  tests/phpunit/CRM/Contact/Form/Task/EmailCommonTest.php
Labels: master, merge on pass

#17063 APIv4 - Fix setting offset with no limit
  Civi/Api4/Query/Api4SelectQuery.php
  tests/phpunit/api/v4/Action/ContactGetTest.php
Labels: has-test, master

#17060 Dupe improve custom data handling
  CRM/Core/DAO.php
  CRM/Dedupe/Merger.php
  tests/phpunit/CRM/Dedupe/MergerTest.php
Labels: master

#17070 [NFC] Remove a handful of legacy svn notations
  Civi/Api4/Action/Campaign/Get.php
  Civi/Api4/Action/CustomValue/Create.php
  Civi/Api4/Action/CustomValue/Get.php
  Civi/Api4/Mapping.php
  Civi/Api4/RelationshipType.php
  Civi/Api4/Service/Spec/Provider/GroupCreationSpecProvider.php
  Civi/Api4/Service/Spec/Provider/MappingCreationSpecProvider.php
  Civi/Api4/Service/Spec/Provider/NavigationSpecProvider.php
  Civi/Api4/Service/Spec/Provider/NoteCreationSpecProvider.php
  Civi/Api4/Service/Spec/Provider/PaymentProcessorTypeCreationSpecProvider.php
  Civi/Api4/Service/Spec/Provider/PhoneCreationSpecProvider.php
  Civi/Api4/Service/Spec/Provider/RelationshipTypeCreationSpecProvider.php
  Civi/Api4/Service/Spec/Provider/TagCreationSpecProvider.php
  Civi/Api4/Service/Spec/Provider/UFFieldCreationSpecProvider.php
  Civi/Api4/Service/Spec/RequestSpec.php
  Civi/Api4/Service/Spec/SpecFormatter.php
  Civi/Api4/StateProvince.php
  Civi/Api4/StatusPreference.php
  Civi/Api4/System.php
  Civi/Api4/Tag.php
  Civi/Api4/UFField.php
  Civi/Api4/UFGroup.php
  Civi/Api4/UFJoin.php
  Civi/Api4/Website.php
Labels: master, merge on pass

#16998 dev/core#1693 inline text title override
  CRM/Core/Smarty/plugins/function.help.php
Labels: master

#17077 Follow up fix on change to merge sqls
  CRM/Dedupe/Merger.php
Labels: master

#16756 [NFC] Improve cleanup on membershipStatus to cope with undeleted memberships
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/api/v3/MembershipStatusTest.php
Labels: has-test, master

#17076 Export: use X icon `fa-times` for closing things
  CRM/Export/Form/Map.php
Labels: master

#17055 Add ID to custom group/field admin forms
  templates/CRM/Custom/Page/Field.tpl
  templates/CRM/Custom/Page/Group.tpl
Labels: master

#17066 Fix 'selectedChild' parameter for pages with tabs
  templates/CRM/Admin/Page/Extensions.tpl
  templates/CRM/Admin/Page/MessageTemplates.tpl
  templates/CRM/Event/Form/ManageEvent/Tab.tpl
  templates/CRM/UF/Page/Group.tpl
  templates/CRM/common/TabHeader.tpl
Labels: master, merge on pass, ok-without-test

#17083 5.25
  CRM/Activity/BAO/Activity.php
  CRM/Admin/Form/Job.php
  CRM/Admin/Page/Job.php
  CRM/Campaign/BAO/Campaign.php
  CRM/Case/XMLProcessor/Report.php
  CRM/Contact/BAO/Query.php
  CRM/Core/Invoke.php
  CRM/Core/Page/QUnit.php
  CRM/Upgrade/Incremental/sql/5.25.beta2.mysql.tpl
  Civi/Core/Security/PharExtensionInterceptor.php
  api/api.php
  api/v3/Contact.php
  composer.json
  composer.lock
  release-notes.md
  release-notes/5.24.3.md
  templates/CRM/Admin/Form/Job.tpl
  templates/CRM/Admin/Page/Job.tpl
  templates/CRM/Case/Form/ActivityView.tpl
  tests/phpunit/CRM/Activity/BAO/ActivityTest.php
  tests/phpunit/CRM/Campaign/BAO/CampaignTest.php
  tests/phpunit/api/v3/ContactTest.php
  tests/phpunit/api/v3/UtilsTest.php
Labels: master

#17062 [REF] APIv4 Explorer - improve performance
  ang/api4Explorer/Explorer.html
  ang/api4Explorer/Explorer.js
Labels: master

#17074 Archive text
  CONTRIBUTORS.txt
Labels: master

#17073 Add MessageTemplate api to v4
  CRM/Admin/Form/MessageTemplates.php
  Civi/Api4/MessageTemplate.php
Labels: master, merge on pass

#17088 [NFC] Remove all the places where tests unnecessarily pass to Membership::create
  tests/phpunit/CRM/Member/BAO/MembershipTest.php
  tests/phpunit/CRM/Member/BAO/MembershipTypeTest.php
  tests/phpunit/api/v3/MembershipTest.php
Labels: master

#17081 Fix unsubscribe regression
  CRM/Mailing/Event/BAO/Unsubscribe.php
  CRM/Mailing/Form/Unsubscribe.php
Labels: 5.25

#17090 [REF] SavedSearch - additional cleanup & bugfixes
  CRM/Contact/BAO/GroupContactCache.php
  CRM/Contact/BAO/SearchCustom.php
Labels: master

#17092 5.25
  CRM/Mailing/Event/BAO/Unsubscribe.php
  CRM/Mailing/Form/Unsubscribe.php
Labels: master

#17085 Generalise typo3/phar-stream-wrapper so CiviCRM can be installed on d…
  composer.json
  composer.lock
Labels: 5.25

#17094 5.24
  CRM/Mailing/Event/BAO/Unsubscribe.php
  CRM/Mailing/Form/Unsubscribe.php
  composer.json
  composer.lock
Labels: 5.24, merge on pass

#17096 Set version 5.24.4. Add notes.
  CRM/Upgrade/Incremental/sql/5.24.4.mysql.tpl
  release-notes.md
  release-notes/5.24.4.md
  sql/civicrm_generated.mysql
  xml/version.xml
Labels: 5.24

#17097 Add release-notes/5.24.4.md
  release-notes.md
  release-notes/5.24.4.md
Labels: 5.25

#17095 5.25
  composer.json
  composer.lock
  release-notes.md
  release-notes/5.24.4.md
Labels: master

#17089 [REF] get rid of variable variable structure
  CRM/Member/BAO/Membership.php
  tests/phpunit/api/v3/ContactTest.php
Labels: master

#17086 Don't pass empty ids parameter, fix fatal
  CRM/Member/Form/MembershipView.php
Labels: master

#17087 [REF] Stop passing ids to membership::create from createRelatedMemberships
  CRM/Member/BAO/Membership.php
Labels: master

#17102 Remove var that is defined on parent
  CRM/Financial/Form/Payment.php
Labels: master

#17051 Remove outputHeader as a param for writeCSVFile as it is always true
  CRM/Core/Report/Excel.php
Labels: master, merge on pass

#17098 Remove unused parameter from function
  CRM/Admin/Page/Job.php
  CRM/Admin/Page/JobLog.php
Labels: master

#17101 (NFC) Gitlab Template - Request more detail about upgrade problems
  .gitlab/issue_templates/problem.md
Labels: master

#17080 [REF] Import - extract duplicate code to function
  CRM/Contribute/Import/Parser/Contribution.php
  CRM/Event/Import/Parser/Participant.php
  CRM/Import/Parser.php
  CRM/Member/Import/Parser/Membership.php
  CRM/Utils/DeprecatedUtils.php
Labels: master

#17069 [REF] Remove duplicate checks for an array key existing
  CRM/Contact/Form/Edit/CustomData.php
  CRM/Contact/Page/Inline/CommunicationPreferences.php
  CRM/Contact/Page/Inline/Demographics.php
  CRM/Contact/Page/View/Summary.php
  CRM/Contact/Page/View/Vcard.php
  CRM/Contribute/BAO/ContributionSoft.php
  CRM/Contribute/Form/Contribution/Confirm.php
  CRM/Contribute/Form/ContributionView.php
  CRM/Core/BAO/Address.php
  CRM/Core/BAO/UFJoin.php
  CRM/Event/Form/Registration/Confirm.php
  CRM/Report/BAO/ReportInstance.php
  CRM/Report/Form/Grant/Statistics.php
  api/v3/Contact.php
  extern/url.php
Labels: master

#17108 Revert #16947 from 5.25RC
  Civi/Api4/Generic/AbstractGetAction.php
  Civi/Api4/Generic/DAOGetAction.php
  Civi/Api4/Generic/DAOGetFieldsAction.php
  Civi/Api4/Query/Api4SelectQuery.php
  Civi/Api4/Query/SqlExpression.php
  Civi/Api4/Query/SqlField.php
  Civi/Api4/Query/SqlFunction.php
  Civi/Api4/Query/SqlFunctionAVG.php
  Civi/Api4/Query/SqlFunctionCOUNT.php
  Civi/Api4/Query/SqlFunctionMAX.php
  Civi/Api4/Query/SqlFunctionMIN.php
  Civi/Api4/Query/SqlFunctionSUM.php
  Civi/Api4/Query/SqlNull.php
  Civi/Api4/Query/SqlNumber.php
  Civi/Api4/Query/SqlString.php
  Civi/Api4/Query/SqlWild.php
  ang/api4Explorer/Explorer.html
  ang/api4Explorer/Explorer.js
  tests/phpunit/api/v4/Action/SqlExpressionTest.php
  tests/phpunit/api/v4/Action/SqlFunctionTest.php
  tests/phpunit/api/v4/Query/SqlExpressionParserTest.php
  tests/phpunit/api/v4/UnitTestCase.php
Labels: 5.25

#17093 [NFC] Remove calculation of unused parameter
  CRM/Contribute/Form/AdditionalInfo.php
Labels: master

#17111 5.25
  Civi/Api4/Generic/AbstractGetAction.php
  Civi/Api4/Generic/DAOGetAction.php
  Civi/Api4/Generic/DAOGetFieldsAction.php
  Civi/Api4/Query/Api4SelectQuery.php
  Civi/Api4/Query/SqlExpression.php
  Civi/Api4/Query/SqlField.php
  Civi/Api4/Query/SqlFunction.php
  Civi/Api4/Query/SqlFunctionAVG.php
  Civi/Api4/Query/SqlFunctionCOUNT.php
  Civi/Api4/Query/SqlFunctionMAX.php
  Civi/Api4/Query/SqlFunctionMIN.php
  Civi/Api4/Query/SqlFunctionSUM.php
  Civi/Api4/Query/SqlNull.php
  Civi/Api4/Query/SqlNumber.php
  Civi/Api4/Query/SqlString.php
  Civi/Api4/Query/SqlWild.php
  ang/api4Explorer/Explorer.html
  ang/api4Explorer/Explorer.js
  tests/phpunit/api/v4/Action/SqlExpressionTest.php
  tests/phpunit/api/v4/Action/SqlFunctionTest.php
  tests/phpunit/api/v4/Query/SqlExpressionParserTest.php
  tests/phpunit/api/v4/UnitTestCase.php
Labels: master

#17110 5.25
  Civi/Api4/Generic/AbstractGetAction.php
  Civi/Api4/Generic/DAOGetAction.php
  Civi/Api4/Generic/DAOGetFieldsAction.php
  Civi/Api4/Query/Api4SelectQuery.php
  Civi/Api4/Query/SqlExpression.php
  Civi/Api4/Query/SqlField.php
  Civi/Api4/Query/SqlFunction.php
  Civi/Api4/Query/SqlFunctionAVG.php
  Civi/Api4/Query/SqlFunctionCOUNT.php
  Civi/Api4/Query/SqlFunctionMAX.php
  Civi/Api4/Query/SqlFunctionMIN.php
  Civi/Api4/Query/SqlFunctionSUM.php
  Civi/Api4/Query/SqlNull.php
  Civi/Api4/Query/SqlNumber.php
  Civi/Api4/Query/SqlString.php
  Civi/Api4/Query/SqlWild.php
  ang/api4Explorer/Explorer.html
  ang/api4Explorer/Explorer.js
  tests/phpunit/api/v4/Action/SqlExpressionTest.php
  tests/phpunit/api/v4/Action/SqlFunctionTest.php
  tests/phpunit/api/v4/Query/SqlExpressionParserTest.php
  tests/phpunit/api/v4/UnitTestCase.php
Labels: master

#17113 Restore #16947 - APIv4 support for sql functions and grouping
  Civi/Api4/Generic/AbstractGetAction.php
  Civi/Api4/Generic/DAOGetAction.php
  Civi/Api4/Generic/DAOGetFieldsAction.php
  Civi/Api4/Query/Api4SelectQuery.php
  Civi/Api4/Query/SqlExpression.php
  Civi/Api4/Query/SqlField.php
  Civi/Api4/Query/SqlFunction.php
  Civi/Api4/Query/SqlFunctionAVG.php
  Civi/Api4/Query/SqlFunctionCOUNT.php
  Civi/Api4/Query/SqlFunctionMAX.php
  Civi/Api4/Query/SqlFunctionMIN.php
  Civi/Api4/Query/SqlFunctionSUM.php
  Civi/Api4/Query/SqlNull.php
  Civi/Api4/Query/SqlNumber.php
  Civi/Api4/Query/SqlString.php
  Civi/Api4/Query/SqlWild.php
  ang/api4Explorer/Explorer.html
  ang/api4Explorer/Explorer.js
  tests/phpunit/api/v4/Action/SqlExpressionTest.php
  tests/phpunit/api/v4/Action/SqlFunctionTest.php
  tests/phpunit/api/v4/Query/SqlExpressionParserTest.php
  tests/phpunit/api/v4/UnitTestCase.php
Labels: master, merge on pass

#17109 APIv4 - Prevent field alias conflicts.
  CRM/Contact/BAO/GroupContactCache.php
  Civi/Api4/Query/Api4SelectQuery.php
  Civi/Api4/Query/SqlField.php
  tests/phpunit/api/v4/Action/SqlExpressionTest.php
Labels: has-test, master

#17106 Update Colmbra state/province to Coimbra
  CRM/Upgrade/Incremental/sql/5.26.alpha1.mysql.tpl
  sql/civicrm_generated.mysql
  xml/templates/civicrm_state_province.tpl
Labels: master

#17121 [REF] Minor var simplification
  CRM/Contribute/BAO/Contribution.php
  CRM/Core/BAO/FinancialTrxn.php
Labels: master

#17064 Convert bcc field to use an entity reference.
  CRM/Contact/Form/Task/EmailTrait.php
  CRM/Core/BAO/Email.php
  api/v3/Email.php
  templates/CRM/Contact/Form/Task/Email.tpl
  tests/phpunit/CRM/Contact/Form/Task/EmailCommonTest.php
Labels: master

#17119 5.25.0 release notes first run
  release-notes.md
  release-notes/5.25.0.md
Labels: 5.25

#17099 dev/core#1718 membership batch entry join date fix
  templates/CRM/Batch/Form/Entry.tpl
Labels: master

#17123 5.25
  release-notes.md
  release-notes/5.25.0.md
Labels: master

#17135 dev/user-interface#19 - Remove leftover description text on contribution form mistakenly left in
  templates/CRM/Contribute/Form/AdditionalInfo/AdditionalDetail.tpl
Labels: master

#16716 Add contributor email address to cancelSubscription form so it is cle…
  CRM/Contribute/Form/CancelSubscription.php
  CRM/Core/Form.php
Labels: master, ready for review
