Repository civicrm/civicrm-core, pull requests merged in 2021-11, with the labels that each got.

#21951 Ensure communityMessages is assigned to the template.
  CRM/Contact/Page/DashBoard.php
  templates/CRM/Contact/Page/DashBoardDashlet.tpl
Labels: master, merge on pass

#21949 Avoid harcoded text in setStatus calls; make translatable
  CRM/Admin/Form/PaymentProcessor.php
  CRM/Admin/Form/Setting/Smtp.php
  CRM/Core/BAO/RecurringEntity.php
  CRM/Event/Form/Task/PickProfile.php
Labels: master, merge on pass

#21954 Don't hardcode Period Type in Manage Premiums template.
  CRM/Contribute/Form/ManagePremiums.php
Labels: master

#21948 Avoid hardcoded text in error strings; make translatable
  CRM/Admin/Form/Setting/Mapping.php
  CRM/Admin/Form/Setting/Smtp.php
  CRM/Contact/Form/Edit/Household.php
  CRM/Contact/Form/Edit/Organization.php
  CRM/Core/BAO/CustomField.php
  CRM/Core/Form/Task/PDFLetterCommon.php
  CRM/Report/Form.php
  CRM/Utils/System/WordPress.php
Labels: master, merge on pass

#21952 Handling for intermittent Im->getfields error
  CRM/Contact/Tokens.php
Labels: master

#21934 Ensure no_licence is assigned for drop.tpl
  CRM/Core/CodeGen/Schema.php
  xml/templates/drop.tpl
  xml/templates/schema.tpl
Labels: master, merge on pass

#21958 [REF] Fix pseduoconstant token rendering for contributions via legacy…
  CRM/Utils/Token.php
Labels: merge on pass, 5.43

#21959 5.43
  CRM/Utils/Token.php
Labels: master

#21929 SearchKit - default displays and ACL-aware links
  Civi/Api4/Generic/AbstractGetAction.php
  Civi/Api4/Generic/Traits/SelectParamTrait.php
  Civi/Api4/Query/Api4SelectQuery.php
  Civi/Api4/Query/SqlFunction.php
  ext/afform/admin/Civi/Api4/Action/Afform/LoadAdminData.php
  ext/afform/admin/ang/afAdmin/afAdminList.controller.js
  ext/afform/admin/ang/afAdmin/afAdminList.html
  ext/afform/admin/ang/afGuiEditor.js
  ext/afform/admin/ang/afGuiEditor/afGuiEditor.component.js
  ext/afform/admin/ang/afGuiEditor/afGuiSearch.component.js
  ext/afform/admin/ang/afGuiEditor/elements/afGuiContainer.component.js
  ext/afform/admin/ang/afGuiEditor/elements/afGuiSearchDisplay.component.js
  ext/afform/core/Civi/Api4/Action/Afform/Get.php
  ext/search_kit/Civi/Api4/Action/SearchDisplay/AbstractRunAction.php
  ext/search_kit/Civi/Api4/Action/SearchDisplay/Download.php
  ext/search_kit/Civi/Api4/Action/SearchDisplay/GetDefault.php
  ext/search_kit/Civi/Api4/Action/SearchDisplay/Run.php
  ext/search_kit/Civi/Api4/Action/SearchDisplay/SavedSearchInspectorTrait.php
  ext/search_kit/Civi/Api4/SearchDisplay.php
  ext/search_kit/Civi/Search/Admin.php
  ext/search_kit/Civi/Search/Display.php
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdmin.component.js
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdmin.html
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdminDisplay.component.js
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdminDisplay.html
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdminLinkGroup.component.js
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdminLinkGroup.html
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdminLinkSelect.component.js
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdminLinkSelect.html
  ext/search_kit/ang/crmSearchAdmin/displays/colType/field.html
  ext/search_kit/ang/crmSearchAdmin/displays/searchAdminDisplayTable.component.js
  ext/search_kit/ang/crmSearchAdmin/resultsTable/crmSearchAdminResultsTable.component.js
  ext/search_kit/ang/crmSearchAdmin/searchListing/afforms.html
  ext/search_kit/ang/crmSearchAdmin/searchListing/buttons.html
  ext/search_kit/ang/crmSearchAdmin/searchListing/crmSearchAdminSearchListing.component.js
  ext/search_kit/ang/crmSearchAdmin/searchListing/crmSearchAdminSearchListing.html
  ext/search_kit/ang/crmSearchAdmin/searchListing/displays.html
  ext/search_kit/ang/crmSearchDisplayTable/crmSearchDisplayTableBody.html
  ext/search_kit/ang/crmSearchPage.module.js
  ext/search_kit/ang/crmSearchTasks/traits/searchDisplayTasksTrait.service.js
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/SearchDisplayTest.php
Labels: master, has-test

#21955 APIv4 - Add managed entity functionality
  CRM/Core/ManagedEntities.php
  Civi/Api4/Entity.php
  Civi/Api4/Generic/Traits/ManagedEntity.php
  Civi/Api4/SavedSearch.php
  Civi/Api4/Service/Spec/Provider/ManagedEntitySpecProvider.php
  ext/search_kit/Civi/Api4/SearchDisplay.php
  tests/phpunit/api/v4/Entity/ManagedEntityTest.php
Labels: master, has-test

#21961 [REF] Update date formatting in the html template to match the text t…
  sql/civicrm_generated.mysql
  xml/templates/message_templates/participant_cancelled_html.tpl
Labels: master, merge on pass

#21962 [NFC] Update Tests to match case in the latest l10n files
  tests/phpunit/CRM/Utils/DateTest.php
  tests/phpunit/Civi/Token/TokenProcessorTest.php
Labels: merge on pass, 5.43

#21965 5.43
  tests/phpunit/CRM/Utils/DateTest.php
  tests/phpunit/Civi/Token/TokenProcessorTest.php
Labels: master

#21963 Remove remaining usages of contact & domain values in participant templates
  CRM/Event/BAO/Participant.php
  CRM/Upgrade/Incremental/MessageTemplates.php
  xml/templates/message_templates/participant_confirm_html.tpl
  xml/templates/message_templates/participant_confirm_text.tpl
  xml/templates/message_templates/participant_expired_html.tpl
  xml/templates/message_templates/participant_expired_text.tpl
Labels: master, merge on pass

#21969 5.43.0 release notes: final updates
  release-notes/5.43.0.md
Labels: 5.43

#21964 Remove calls to CRM_Utils_Token::getDomainTokenReplacement
  CRM/Event/BAO/Participant.php
  CRM/Event/Form/SelfSvcTransfer.php
  CRM/Event/Form/SelfSvcUpdate.php
Labels: master, merge on pass

#21970 [REF] Regenerate generated civicrm file after recent template updates
  package-lock.json
  sql/civicrm_generated.mysql
Labels: master, merge on pass

#21953 User experience improvement - CiviCRM Manage Events page, expand the Find Events criteria by default
  templates/CRM/Event/Form/SearchEvent.tpl
Labels: master, merge ready

#21971 5.43
  release-notes/5.43.0.md
Labels: master

#21942 GroupContactCache: Drop temp table *after* releasing lock
  CRM/Contact/BAO/GroupContactCache.php
Labels: master

#21957 Use null variables rather than isset in Core_Block
  CRM/Core/Block.php
  CRM/Core/Smarty.php
  templates/CRM/Block/LangSwitch.tpl
Labels: master, merge on pass

#21947 SearchKit - Conditional style rules for rows/cells
  Civi/Api4/Generic/Traits/ArrayQueryActionTrait.php
  css/civicrm.css
  ext/search_kit/Civi/Api4/Action/SearchDisplay/AbstractRunAction.php
  ext/search_kit/ang/crmSearchAdmin.module.js
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdminLinkSelect.component.js
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdminLinkSelect.html
  ext/search_kit/ang/crmSearchAdmin/displays/colType/field.html
  ext/search_kit/ang/crmSearchAdmin/displays/common/searchAdminCssRules.component.js
  ext/search_kit/ang/crmSearchAdmin/displays/common/searchAdminCssRules.html
  ext/search_kit/ang/crmSearchAdmin/displays/searchAdminDisplayTable.component.js
  ext/search_kit/ang/crmSearchAdmin/displays/searchAdminDisplayTable.html
  ext/search_kit/ang/crmSearchDisplayGrid/crmSearchDisplayGridItems.html
  ext/search_kit/ang/crmSearchDisplayList/crmSearchDisplayListItems.html
  ext/search_kit/ang/crmSearchDisplayTable/crmSearchDisplayTableBody.html
  ext/search_kit/css/crmSearchAdmin.css
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/SearchRunTest.php
Labels: master, has-test

#21967 SearchKit - Fix incorrect pager count when using filters
  CRM/Utils/Array.php
  Civi/Api4/Generic/BasicGetAction.php
  Civi/Api4/Generic/Traits/CustomValueActionTrait.php
  Civi/Api4/Generic/Traits/DAOActionTrait.php
  Civi/Api4/Query/Api4SelectQuery.php
  Civi/Api4/Utils/FormattingUtil.php
  ext/search_kit/Civi/Api4/Action/SearchDisplay/AbstractRunAction.php
  ext/search_kit/Civi/Api4/Action/SearchDisplay/Download.php
  ext/search_kit/Civi/Api4/Action/SearchDisplay/GetDefault.php
  ext/search_kit/Civi/Api4/Action/SearchDisplay/Run.php
  ext/search_kit/Civi/Api4/Action/SearchDisplay/SavedSearchInspectorTrait.php
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/SearchDisplayTest.php
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/SearchRunTest.php
Labels: master, has-test

#21972 Remove call to getTokenDetails
  CRM/Event/BAO/Participant.php
  CRM/Utils/Token.php
Labels: master, merge on pass

#21974 dev/core#2909 - Repair the option value label for nb_NO language
  CRM/Upgrade/Incremental/php/FiveFortyFour.php
Labels: merge on pass, 5.44

#21976 5.44
  CRM/Upgrade/Incremental/php/FiveFortyFour.php
Labels: master

#21912 Move responsibilty for ensuring greeting parameters are set to `ensureGreetingParamsAreSet`
  CRM/Contact/BAO/Contact.php
  CRM/Core/DAO.php
Labels: master

#21977 SearchKit - Fix permission to access default display and download spreadsheets
  ext/search_kit/Civi/Api4/SearchDisplay.php
Labels: 5.44

#21980 dev/core#2942 regression fix
  CRM/Contact/Form/Task/Map.php
Labels: merge on pass, 5.44

#21982 5.44
  CRM/Contact/Form/Task/Map.php
  ext/search_kit/Civi/Api4/SearchDisplay.php
Labels: master

#21981 543
  CRM/Contact/Form/Task/Map.php
Labels: 5.43

#21835 Run scheduled reminder job hourly
  sql/civicrm_generated.mysql
  sql/test_data_second_domain.mysql
  xml/templates/civicrm_data.tpl
Labels: master

#21985 [Unreleased regression] SearchKit - Fix display of image fields
  ext/search_kit/Civi/Api4/Action/SearchDisplay/AbstractRunAction.php
Labels: 5.44

#21990 5.44 to master
  ext/search_kit/Civi/Api4/Action/SearchDisplay/AbstractRunAction.php
Labels: master

#21956 dev/core#1328 Add define to optionally enable escape-on-output
  CRM/Core/Smarty.php
  templates/CRM/common/civicrm.settings.php.template
Labels: master

#21987 Enotice fixes
  CRM/Event/Page/ManageEvent.php
Labels: master, merge on pass

#21988 Remove isset from Datasource.tpl
  CRM/Contact/Import/Form/DataSource.php
  CRM/Core/Form.php
  templates/CRM/Contact/Import/Form/DataSource.tpl
Labels: master

#21933 Remove unused variable
  templates/CRM/common/CMSPrint.tpl
Labels: master

#21994 Make more hardcoded strings available for translation
  CRM/Batch/Form/Entry.php
  CRM/Case/Form/Activity.php
  CRM/Contact/Form/Edit/Individual.php
  CRM/Contribute/Form/ContributionCharts.php
  CRM/Core/SelectValues.php
  CRM/Event/BAO/Query.php
  CRM/Report/Form/Case/Detail.php
  templates/CRM/Admin/Form/ScheduleReminders.tpl
  templates/CRM/Admin/Page/Options.tpl
  templates/CRM/Contact/Page/DedupeFind.tpl
Labels: master

#21979 Fix isForm to be always assigned, remove checks
  CRM/Core/Page.php
  templates/CRM/common/CMSPrint.tpl
  templates/CRM/common/joomla.tpl
  templates/CRM/common/print.tpl
  templates/CRM/common/printBody.tpl
Labels: master

#21940 Enotice fixes in debug.tpl that are compatible with default escaping
  templates/CRM/common/debug.tpl
Labels: master

#21975 Reporting #18: Fix sorting with > 10 participant roles
  CRM/Report/Form/Event/ParticipantListing.php
Labels: master

#21998 Guard against passing empty values to CRM_Core_DAO::getFieldValue()
  CRM/Core/BAO/CustomField.php
Labels: master, merge on pass

#21995 Tidy up title attributes
  templates/CRM/Activity/Form/Selector.tpl
  templates/CRM/Activity/Selector/Activity.tpl
  templates/CRM/Campaign/Form/Selector.tpl
  templates/CRM/Case/Form/Selector.tpl
  templates/CRM/Contact/Form/Selector.tpl
  templates/CRM/Contact/Page/Inline/Basic.tpl
  templates/CRM/Contribute/Form/Selector.tpl
  templates/CRM/Contribute/Page/DashBoard.tpl
  templates/CRM/Custom/Form/Field.tpl
  templates/CRM/Event/Form/Selector.tpl
  templates/CRM/Event/Page/ManageEvent.tpl
  templates/CRM/Grant/Form/Selector.tpl
  templates/CRM/Mailing/Form/Count.tpl
  templates/CRM/Mailing/Form/Selector.tpl
  templates/CRM/Member/Form/Selector.tpl
  templates/CRM/Member/Page/DashBoard.tpl
  templates/CRM/PCP/Page/PCPInfo.tpl
  templates/CRM/Pledge/Form/Selector.tpl
Labels: master, merge on pass

#20811 Check the billing fields returned by each payment processor
  CRM/Core/BAO/UFField.php
  CRM/Core/Payment/ProcessorForm.php
  tests/phpunit/CRM/Core/Payment/ProcessorFormTest.php
Labels: master, has-test

#21997 dev/core#2550 Fix possible upgrade failures
  CRM/Core/DAO.php
Labels: merge on pass, 5.44

#21999 Fix possible upgrade failures when writing to db fields which may not…
  CRM/Core/DAO.php
Labels: 5.43

#21960 Afform - Display the extension in which an Afform is packaged
  CRM/Extension/Mapper.php
  Civi/Api4/Generic/BasicGetAction.php
  ext/afform/admin/ang/afAdmin.js
  ext/afform/admin/ang/afAdmin/afAdminList.controller.js
  ext/afform/admin/ang/afAdmin/afAdminList.html
  ext/afform/core/CRM/Afform/AfformScanner.php
  ext/afform/core/Civi/Api4/Action/Afform/Get.php
  ext/afform/core/Civi/Api4/Afform.php
  ext/afform/core/tests/phpunit/Civi/Afform/AfformGetTest.php
  ext/afform/mock/tests/phpunit/api/v4/AfformTest.php
  tests/phpunit/api/v4/Action/BasicActionsTest.php
  tests/phpunit/api/v4/Action/GetFromArrayTest.php
Labels: master

#22003 5.44
  CRM/Core/DAO.php
Labels: master

#22005 [REF] Add in missing province for Philippines and update names to matc…
  CRM/Upgrade/Incremental/sql/5.45.alpha1.mysql.tpl
  sql/civicrm_generated.mysql
  xml/templates/civicrm_state_province.tpl
Labels: master, merge on pass

#22010 APIv4 Explorer - Optionally view results in PHP format
  ang/api4Explorer/Explorer.html
  ang/api4Explorer/Explorer.js
  css/api4-explorer.css
Labels: master

#21983 Handle activity creation for emails directed to organization contacts
  CRM/Utils/Mail/Incoming.php
  tests/phpunit/CRM/Utils/Mail/IncomingTest.php
Labels: master

#22011 don't overfill the prevnext cache when reserving for a survey.
  CRM/Campaign/Selector/Search.php
Labels: master

#22002 Extract getGroupOrganizationUrl & ensure always assigned
  CRM/Contact/Page/View.php
  templates/CRM/Contact/Page/View/Summary.tpl
Labels: master

#21991 Ensure that keys are set in tabValues before hitting smarty
  CRM/Contact/Page/View/Summary.php
  templates/CRM/Contact/Page/View/Summary.tpl
Labels: master

#22016 dev/report#77 - Unused variable in contribute/history civireport
  CRM/Report/Form/Contribute/History.php
Labels: master, merge on pass

#22001 Ensure hookContentPlacement is assigned
  CRM/Core/Page.php
  templates/CRM/Contact/Page/View/Summary-tab.tpl
Labels: master

#22018 Ensure smarty variable formTpl is set
  CRM/Core/Controller.php
Labels: master, merge on pass

#22015 [NFC] dev/report#77 - contribute/history civireport seems ok to run during reporttemplatetest
  tests/phpunit/api/v3/ReportTemplateTest.php
Labels: master, merge on pass

#22020 [NFC] Fix test issue about trying to do array offset on NULL in Payme…
  tests/phpunit/CRM/Core/Payment/ProcessorFormTest.php
Labels: master

#22021 CRM_Utils_File::isChildPath - Fix checking of non-existent paths
  CRM/Utils/File.php
  tests/phpunit/CRM/Utils/FileTest.php
Labels: master

#22000 Ensure beginHookFormElements is assigned
  CRM/Core/Form.php
  templates/CRM/Form/body.tpl
Labels: master

#22017 dev/core#1529 fix event repeat functionality
  CRM/Event/Form/ManageEvent/Repeat.php
Labels: master

#22026 REF: Switch to debug level logging for lock debugging
  CRM/Core/Lock.php
Labels: master, merge on pass

#22023 [NFC] php8 - fix test fails for CRM_Contact_Page_View_UserDashBoardTest
  tests/phpunit/CRM/Contact/Page/View/UserDashBoardTest.php
Labels: master

#22027 Flip logic for determining if $section variable is set.
  templates/CRM/Report/Form/Layout/Graph.tpl
Labels: master, merge on pass

#22028 Remove use of isset for info.tpl
  CRM/Core/Form.php
  CRM/Core/Page.php
  templates/CRM/common/footer.tpl
  templates/CRM/common/info.tpl
Labels: master, merge on pass

#21986 SearchKit - tabbed display for custom vs packaged searches
  CRM/Core/ManagedEntities.php
  ext/search_kit/Civi/Api4/SearchDisplay.php
  ext/search_kit/Civi/Search/Admin.php
  ext/search_kit/ang/crmSearchAdmin/searchListing/buttons.html
  ext/search_kit/ang/crmSearchAdmin/searchListing/crmSearchAdminSearchListing.component.js
  ext/search_kit/ang/crmSearchAdmin/searchListing/crmSearchAdminSearchListing.html
Labels: master

#22029 Ensure action is set when loading contactFooter
  CRM/Contact/Form/Inline.php
  templates/CRM/common/contactFooter.tpl
Labels: master, merge on pass

#22024 [NFC] dev/report#77 - Remove useless comment in contribute/history civireport
  CRM/Report/Form/Contribute/History.php
Labels: master

#22025 dev/report#77 - Smarty warning about relationship in contribute/history civireport
  CRM/Report/Form/Contribute/History.php
Labels: master

#22019 SearchKit - Animated loading skeleton
  ext/search_kit/ang/crmSearchAdmin/resultsTable/crmSearchAdminResultsTable.html
  ext/search_kit/ang/crmSearchDisplay.ang.php
  ext/search_kit/ang/crmSearchDisplayGrid/crmSearchDisplayGrid.html
  ext/search_kit/ang/crmSearchDisplayGrid/crmSearchDisplayGridLoading.html
  ext/search_kit/ang/crmSearchDisplayList/crmSearchDisplayList.html
  ext/search_kit/ang/crmSearchDisplayList/crmSearchDisplayListLoading.html
  ext/search_kit/ang/crmSearchDisplayTable/crmSearchDisplayTable.html
  ext/search_kit/ang/crmSearchDisplayTable/crmSearchDisplayTableLoading.html
  ext/search_kit/css/crmSearchDisplay.css
  ext/search_kit/css/crmSearchTasks.css
Labels: master

#22033 Do not smarty encode quicksearch html
  templates/CRM/common/l10n.js.tpl
Labels: master, merge on pass

#22034 [NFC] Additional Fix on UserDashBoard Tests to assign action value to…
  tests/phpunit/CRM/Contact/Page/View/UserDashBoardTest.php
Labels: master, merge on pass

#22036 Escape-on-output-proof enotice fixes
  CRM/Core/Form.php
  templates/CRM/Form/body.tpl
  templates/CRM/Form/default.tpl
  templates/CRM/common/CMSPrint.tpl
  templates/CRM/common/fatal.tpl
Labels: master, merge on pass

#22037 [REF] Fix Pledge Test failing on php8 by ensuring all payments have a…
  CRM/Pledge/BAO/Pledge.php
  tests/phpunit/CRM/Pledge/Form/PledgeTest.php
Labels: master, merge on pass

#22031 Ensure imageUrl is always set
  CRM/Contact/Form/Contact.php
  CRM/Contact/Page/View.php
  templates/CRM/Contact/Page/View/Summary-tab.tpl
Labels: master

#21936 dev/core#2912 : Can't save extra custom fields when inline and required
  CRM/Contact/Form/Contact.php
Labels: master

#22040 Fix tabs getting overwritten by double foreach loop
  CRM/Contact/Page/View/Summary.php
Labels: master, merge on pass

#22041 dev/report#77 - Make contribution filters work for contribute/history civireport
  CRM/Report/Form/Contribute/History.php
  tests/phpunit/api/v3/ReportTemplateTest.php
Labels: master, has-test

#22038 (dev/core#2951) expose contribution custom fields in lybunt report
  CRM/Report/Form/Contribute/Lybunt.php
Labels: master

#22042 Ensure userRecordUrl is always set- fixes enotice with escape-on-output
  CRM/Contact/Page/View.php
  templates/CRM/Contact/Page/Inline/Basic.tpl
Labels: master

#21989 ManagedEntities - Track modification and auto-update
  CRM/Core/BAO/Managed.php
  CRM/Core/BAO/OptionValue.php
  CRM/Core/DAO.php
  CRM/Core/DAO/Managed.php
  CRM/Core/ManagedEntities.php
  CRM/Upgrade/Incremental/php/FiveFortyFive.php
  Civi/Api4/Service/Spec/Provider/ManagedEntitySpecProvider.php
  Civi/Api4/Utils/CoreUtil.php
  ext/afform/core/afform.php
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/ManagedSearchTest.php
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/SearchAfformTest.php
  tests/phpunit/CRM/Core/BAO/dataset/im_test.xml
  tests/phpunit/CRM/Core/ManagedEntitiesTest.php
  tests/phpunit/api/v4/Entity/ManagedEntityTest.php
  xml/schema/Core/Managed.xml
Labels: master, has-test

#22048 [NFC] php8 - set smarty null defaults for CRM_Core_SessionTest
  tests/phpunit/CRM/Core/SessionTest.php
Labels: master, merge on pass

#22043 [REF] Skip testCutesyTokenData on php8 for the moment
  CRM/Pledge/BAO/Pledge.php
  tests/phpunit/CRM/Core/TokenSmartyTest.php
  tests/phpunit/CRM/Pledge/Form/PledgeTest.php
Labels: merge on pass, 5.44

#22047 Ensure gender_display is always set
  CRM/Contact/Page/View/Summary.php
  templates/CRM/Contact/Page/Inline/Demographics.tpl
Labels: master, merge on pass

#22050 (dev/core#2947) Tokens - Auto-enable {event.*} if participantId is present
  CRM/Core/SelectValues.php
  Civi/Core/Container.php
  Civi/Token/ImpliedContextSubscriber.php
  Civi/Token/TokenProcessor.php
  tests/phpunit/CRM/Utils/TokenConsistencyTest.php
  tests/phpunit/Civi/Token/ImpliedContextSubscriberTest.php
Labels: merge on pass, 5.43

#22046 (dev/core#2947) Tokens - Auto-enable `{event.*}` if `participantId` is present
  CRM/Core/SelectValues.php
  Civi/Core/Container.php
  Civi/Token/ImpliedContextSubscriber.php
  Civi/Token/TokenProcessor.php
  tests/phpunit/CRM/Utils/TokenConsistencyTest.php
  tests/phpunit/Civi/Token/ImpliedContextSubscriberTest.php
Labels: merge on pass, has-test, 5.44

#22044 Mark a few more token functions as deprected
  CRM/Utils/Token.php
Labels: master, merge on pass

#22051 APIv4 - Add backticks around fields in join criteria
  Civi/Api4/Service/Schema/Joinable/Joinable.php
Labels: 5.44

#22054 APIv4 - Add backticks around fields in join criteria
  Civi/Api4/Service/Schema/Joinable/Joinable.php
Labels: 5.43

#22059 php8 - fix for breadcrumb fails during tests
  CRM/Core/Form.php
  CRM/Core/Page.php
Labels: master

#22052 5.43.1 - Bump version. Add notes.
  ext/afform/admin/info.xml
  ext/afform/core/info.xml
  ext/afform/html/info.xml
  ext/afform/mock/info.xml
  ext/authx/info.xml
  ext/ckeditor4/info.xml
  ext/contributioncancelactions/info.xml
  ext/eventcart/info.xml
  ext/ewaysingle/info.xml
  ext/financialacls/info.xml
  ext/flexmailer/info.xml
  ext/greenwich/info.xml
  ext/legacycustomsearches/info.xml
  ext/message_admin/info.xml
  ext/oauth-client/info.xml
  ext/payflowpro/info.xml
  ext/recaptcha/info.xml
  ext/search_kit/info.xml
  ext/sequentialcreditnotes/info.xml
  release-notes.md
  release-notes/5.43.1.md
  sql/civicrm_generated.mysql
  sql/test_data_second_domain.mysql
  xml/version.xml
Labels: 5.43

#22057 5.44
  CRM/Core/SelectValues.php
  Civi/Api4/Service/Schema/Joinable/Joinable.php
  Civi/Core/Container.php
  Civi/Token/ImpliedContextSubscriber.php
  Civi/Token/TokenProcessor.php
  tests/phpunit/CRM/Utils/TokenConsistencyTest.php
  tests/phpunit/Civi/Token/ImpliedContextSubscriberTest.php
Labels: master

#22055 Ensure contactTag is always set
  CRM/Contact/Page/View/Summary.php
  templates/CRM/Contact/Page/Inline/Basic.tpl
Labels: master

#21909 [REF] Preliminary cleanup in update greeting
  CRM/Contact/BAO/Contact.php
  tests/phpunit/api/v3/CustomValueTest.php
Labels: master, merge on pass

#22056 Ensure context is always set
  CRM/Core/Page.php
  templates/CRM/Contact/Page/View/Summary.tpl
Labels: master

#22062 release-notes/5.43.1.md - Add recent patch
  release-notes/5.43.1.md
Labels: 5.43

#22061 [NFC] php8 assign formTpl in HookTest test
  tests/phpunit/CRM/Core/Page/HookTest.php
Labels: master, merge on pass

#22065 [NFC] ENsure that formTpl is assigned in CRM_Custom_Form_OptionTest
  tests/phpunit/CRM/Custom/Form/OptionTest.php
Labels: master, merge on pass

#22045 [NFC] dev/mail#103 Add in unit test to demonstate issue with API…
  tests/phpunit/api/v4/Entity/ContactCustomJoinTest.php
Labels: master, merge on pass

#22066 Fix typo in smarty template "gender_display"
  templates/CRM/Contact/Page/Inline/Demographics.tpl
Labels: master

#22030 Fix all the issets that affect ability to load contact summary page
  CRM/Contact/Page/View/Summary.php
  templates/CRM/Contact/Page/Inline/Basic.tpl
  templates/CRM/Contact/Page/Inline/CommunicationPreferences.tpl
  templates/CRM/Contact/Page/Inline/ContactInfo.tpl
  templates/CRM/Contact/Page/Inline/Demographics.tpl
Labels: master, merge on pass

#22067 [NFC] Array formatting
  CRM/Contact/Page/View/Summary.php
Labels: master, merge on pass

#22069 Do not check is context is set, should always be
  templates/CRM/Contact/Form/Edit/TagsAndGroups.tpl
  templates/CRM/Form/attachmentjs.tpl
Labels: master

#22073 [NFC] Add missing calls to parent::setUp and tearDown in unit tests
  tests/phpunit/CRM/Activity/Form/ActivityViewTest.php
  tests/phpunit/CRM/Activity/Form/SearchTest.php
  tests/phpunit/CRM/Contact/BAO/ActivitySearchTest.php
  tests/phpunit/CRM/Contact/BAO/ContactType/ContactTest.php
  tests/phpunit/CRM/Contact/BAO/ContactType/RelationshipTest.php
  tests/phpunit/CRM/Contact/BAO/GroupTest.php
  tests/phpunit/CRM/Contact/BAO/SavedSearchTest.php
  tests/phpunit/CRM/Contact/Page/View/UserDashBoardTest.php
  tests/phpunit/CRM/Contribute/BAO/ContributionTypeTest.php
  tests/phpunit/CRM/Contribute/Form/Contribution/ConfirmTest.php
  tests/phpunit/CRM/Contribute/Form/ContributionPageTranslationTest.php
  tests/phpunit/CRM/Contribute/Form/ContributionTest.php
  tests/phpunit/CRM/Contribute/Form/Task/StatusTest.php
  tests/phpunit/CRM/Core/BAO/LocationTest.php
  tests/phpunit/CRM/Core/Payment/AuthorizeNetTest.php
  tests/phpunit/CRM/Core/Payment/BaseIPNTest.php
  tests/phpunit/CRM/Core/Payment/PayPalProIPNTest.php
  tests/phpunit/CRM/Core/SessionTest.php
  tests/phpunit/CRM/Event/BAO/AdditionalPaymentTest.php
  tests/phpunit/CRM/Event/BAO/ChangeFeeSelectionTest.php
  tests/phpunit/CRM/Financial/BAO/FinancialTypeTest.php
  tests/phpunit/CRM/Mailing/BAO/QueryTest.php
  tests/phpunit/CRM/Member/BAO/MembershipTypeTest.php
  tests/phpunit/CRM/Member/Form/MembershipRenewalTest.php
  tests/phpunit/CRM/Member/Form/MembershipTest.php
  tests/phpunit/CRM/Member/Form/Task/BatchTest.php
  tests/phpunit/CRM/Member/Form/Task/PDFLetterTest.php
  tests/phpunit/CRM/Member/Import/Parser/MembershipTest.php
  tests/phpunit/CRM/Queue/Queue/SqlTest.php
  tests/phpunit/CRM/Queue/QueueTest.php
  tests/phpunit/CRM/Queue/RunnerTest.php
  tests/phpunit/CRM/Utils/Migrate/ImportExportTest.php
  tests/phpunit/Civi/Test/ExampleHookTest.php
  tests/phpunit/Civi/Test/ExampleSubscriberTest.php
  tests/phpunit/Civi/Test/ExampleTransactionalTest.php
  tests/phpunit/CiviTest/CiviCaseTestCase.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/E2E/Core/PrevNextTest.php
  tests/phpunit/E2E/Extern/SoapTest.php
  tests/phpunit/api/v4/Traits/OptionCleanupTrait.php
Labels: master, merge on pass

#22071 dev/drupal#169 - Fix for session_id() change in Drupal 9.2
  CRM/Core/Key.php
  CRM/Utils/System/Base.php
  CRM/Utils/System/Drupal8.php
Labels: merge ready, 5.44

#22075 Ensure paramSubType is always set
  CRM/Contact/Form/Contact.php
  templates/CRM/Contact/Form/Contact.tpl
Labels: master

#22077 5.44
  CRM/Core/Key.php
  CRM/Utils/System/Base.php
  CRM/Utils/System/Drupal8.php
Labels: master

#22078 dev/drupal#169 - Fix for session_id() change in Drupal 9.2
  CRM/Core/Key.php
  CRM/Utils/System/Base.php
  CRM/Utils/System/Drupal8.php
Labels: merge on pass, 5.43

#22068 APIv4 - Opt-in more ManagedEntity types
  CRM/Core/DAO.php
  CRM/Core/Reference/Interface.php
  Civi/Api4/ContactType.php
  Civi/Api4/CustomField.php
  Civi/Api4/CustomGroup.php
  Civi/Api4/Membership.php
  Civi/Api4/MembershipStatus.php
  Civi/Api4/MembershipType.php
  Civi/Api4/OptionGroup.php
  Civi/Api4/OptionValue.php
  Civi/Api4/PaymentProcessorType.php
  Civi/Api4/RelationshipType.php
  tests/phpunit/api/v4/Entity/ManagedEntityTest.php
Labels: master, has-test

#22076 Ensure masterAddress is always assigned
  CRM/Contact/Form/Edit/Address.php
  templates/CRM/Contact/Form/Edit/Address.tpl
Labels: master

#22022 Fix for dev/core#2948
  CRM/Event/Form/Registration.php
Labels: master, merge ready

#22032 CiviCRM Membership Status can never be deleted when logging is enabled
  CRM/Member/BAO/MembershipStatus.php
Labels: master, merge ready

#22083 5.43.2 - Add notes. Bump version.
  ext/afform/admin/info.xml
  ext/afform/core/info.xml
  ext/afform/html/info.xml
  ext/afform/mock/info.xml
  ext/authx/info.xml
  ext/ckeditor4/info.xml
  ext/contributioncancelactions/info.xml
  ext/eventcart/info.xml
  ext/ewaysingle/info.xml
  ext/financialacls/info.xml
  ext/flexmailer/info.xml
  ext/greenwich/info.xml
  ext/legacycustomsearches/info.xml
  ext/message_admin/info.xml
  ext/oauth-client/info.xml
  ext/payflowpro/info.xml
  ext/recaptcha/info.xml
  ext/search_kit/info.xml
  ext/sequentialcreditnotes/info.xml
  release-notes.md
  release-notes/5.43.2.md
  sql/civicrm_generated.mysql
  sql/test_data_second_domain.mysql
  xml/version.xml
Labels: 5.43

#22085 Add in 5.43.1 and 5.43.2 Release Notes
  release-notes.md
  release-notes/5.43.1.md
  release-notes/5.43.2.md
Labels: 5.44

#22086 5.44
  release-notes.md
  release-notes/5.43.1.md
  release-notes/5.43.2.md
Labels: master

#22080 [REF] dev/drupal#169 Replace other usages of session_id with CRM_Core…
  CRM/Core/IDS.php
  CRM/Report/Form.php
Labels: master

#22082 Use smarty:nodefaults with smarty.get
  templates/CRM/Form/validate.tpl
Labels: master

#22088 dev/core#2894 - Crash when viewing a contact with a website
  CRM/Contact/Page/View/Summary.php
Labels: master

#21854 dev/core#2919 Hidden submit buttons are confussing for keyboard users
  js/crm.ajax.js
Labels: master, merge ready

#21966 Fix missing currency for event registration when configured via "quick config"
  CRM/Price/BAO/PriceField.php
  api/v3/utils.php
Labels: master, merge ready

#22089 OptionValue - Fix incorrect update of `is_default`
  CRM/Core/BAO/OptionValue.php
  tests/phpunit/api/v4/Entity/OptionValueTest.php
Labels: master, merge on pass, has-test

#22091 Contribution amounts configuration page is borked when translation contains apostrophe
  templates/CRM/Contribute/Form/ContributionPage/Amount.tpl
Labels: master

#22093 EventChecker - Fix recent regression
  Civi/Test/EventChecker.php
Labels: merge on pass, 5.44

#22097 Fix two English strings
  settings/Core.setting.php
  templates/CRM/Report/Page/InstanceList.tpl
Labels: master

#22095 OptionValue - Fix checking if domain is set
  CRM/Core/BAO/OptionValue.php
  tests/phpunit/api/v4/Entity/ManagedEntityTest.php
Labels: master, has-test

#22098 Fix dev/core#2959: some PDFs hard-code format to "a3 landscape", overriding default PDF format
  CRM/Core/Page.php
Labels: master

#22094 5.44
  Civi/Test/EventChecker.php
Labels: master

#22084 Remove smarty isset in favour of always set
  CRM/Contact/Import/Form/DataSource.php
  CRM/Core/Form.php
  CRM/Group/Form/Search.php
  templates/CRM/Group/Form/Search.tpl
  tests/phpunit/CRM/Core/Page/HookTest.php
Labels: master

#22099 5.44
  composer.json
  composer.lock
Labels: master

#22035 Escape-on-output: Cleanup addCampaignToSearch, remove isset
  CRM/Campaign/BAO/Campaign.php
  templates/CRM/Activity/Form/Search/Common.tpl
  templates/CRM/Campaign/Form/addCampaignToComponent.tpl
  templates/CRM/Campaign/Form/addCampaignToSearch.tpl
  templates/CRM/Contribute/Form/Search/Common.tpl
  templates/CRM/Contribute/Form/SearchContribution.tpl
  templates/CRM/Event/Form/Search/Common.tpl
  templates/CRM/Event/Form/SearchEvent.tpl
  templates/CRM/Mailing/Form/Search.tpl
  templates/CRM/Mailing/Form/Search/Common.tpl
  templates/CRM/Member/Form/Search/Common.tpl
  templates/CRM/Pledge/Form/Search/Common.tpl
Labels: master, merge on pass

#21908 [REF] Remove support for not-passed 'pledge' value
  CRM/Contribute/BAO/Contribution/Utils.php
Labels: master, merge on pass

#22009 Afform - Add table of submission results
  ext/afform/admin/Civi/AfformAdmin/AfformAdminMeta.php
  ext/afform/admin/ang/afAdmin/afAdminList.controller.js
  ext/afform/admin/ang/afAdmin/afAdminList.html
  ext/afform/admin/ang/afAdminFormSubmissionList.aff.html
  ext/afform/admin/ang/afAdminFormSubmissionList.aff.json
  ext/afform/admin/info.xml
  ext/afform/admin/managed/FormSubmissionSavedSearch.mgd.php
  ext/afform/core/managed/AfformType.mgd.php
Labels: master

#22102 Remove obsolete showVisibility
  templates/CRM/Admin/Page/Options.tpl
Labels: master, merge on pass

#22103 5.44.0 release notes initial run
  release-notes.md
  release-notes/5.44.0.md
Labels: 5.44

#22104 5.44
  release-notes.md
  release-notes/5.44.0.md
Labels: master

#22106 Allow "Download chart" text to be translated.
  templates/CRM/common/chart.tpl
Labels: master, merge on pass

#22108 SearchKit - Fix default displays in Afforms and multiple displays per page
  ext/search_kit/Civi/Search/AfformSearchMetadataInjector.php
  ext/search_kit/ang/crmSearchDisplay/traits/searchDisplayBaseTrait.service.js
Labels: 5.44

#22090 APIv4 - Fix checkAccess for CiviCase or other entities with nonstandard class names
  Civi/Api4/Generic/AbstractEntity.php
Labels: master

#22109 5.44
  ext/search_kit/Civi/Search/AfformSearchMetadataInjector.php
  ext/search_kit/ang/crmSearchDisplay/traits/searchDisplayBaseTrait.service.js
Labels: master

#22113 Remove broken dynamic title from event template
  templates/CRM/Event/Form/ManageEvent/Tab.tpl
Labels: master

#22110 CiviCRM Message Template, HTML Format and Text Format fields are listed in a different order on the Default Message Template
  templates/CRM/Admin/Page/MessageTemplates.tpl
Labels: master

#22111 Remove a bunch of isset from options.tpl
  CRM/Admin/Page/Options.php
  templates/CRM/Admin/Page/Options.tpl
Labels: master

#22112 Update PayPalImpl.php - action on style test failure
  CRM/Core/Payment/PayPalImpl.php
Labels: master

#22105 Update PayPalImpl.php
  CRM/Core/Payment/PayPalImpl.php
Labels: master

#21944 fix unit plural in contribution page
  CRM/Contribute/BAO/Contribution.php
  CRM/Contribute/Form/Contribution/Main.php
Labels: master

#22070 Throw spaghetti
  CRM/Report/Form.php
  CRM/Report/Utils/Report.php
  templates/CRM/Report/Form.tpl
  templates/CRM/Report/Form/Contact/Detail.tpl
  templates/CRM/Report/Form/Contribute/DeferredRevenue.tpl
  templates/CRM/Report/Form/Event/Income.tpl
  templates/CRM/Report/Form/Layout/Graph.tpl
  templates/CRM/Report/Form/Layout/Table.tpl
  templates/CRM/Report/Form/Statistics.tpl
  tests/phpunit/CRM/Report/Form/Contribute/DetailTest.php
  tests/phpunit/CRM/Report/Utils/ReportTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/api/v3/ReportTemplateTest.php
Labels: master

#22079 Remove issets from Options.tpl
  CRM/Admin/Page/Options.php
  templates/CRM/Admin/Page/Options.tpl
Labels: master

#22120 Do not use default escaping on address display
  templates/CRM/Contact/Page/Inline/Address.tpl
Labels: master, merge on pass
