Repository civicrm/civicrm-core, pull requests merged in 2021-06, with the labels that each got.

#20448 Mark test class as having invalid financials
  tests/phpunit/CRM/Report/Form/TestCaseTest.php
  tests/phpunit/CiviTest/CiviReportTestCase.php
Labels: master

#20455 Make functions protected
  CRM/Contact/BAO/GroupContactCache.php
Labels: master, merge on pass

#20456 [Ref] remove never-passed param
  CRM/Contact/BAO/GroupContactCache.php
Labels: master, merge on pass

#20433 dev/core#2486 Add in FinancialItem APIv4 Entity
  Civi/Api4/FinancialItem.php
Labels: master

#20463 Don't pass doPayment by reference in Contribution.transact API
  api/v3/Contribution/Transact.php
Labels: master, merge on pass

#20464 dev/core#2486 Add pseudoconstant callback for LineItem and Financial item entity
  CRM/Financial/BAO/FinancialItem.php
  CRM/Financial/DAO/FinancialItem.php
  CRM/Price/BAO/LineItem.php
  CRM/Price/DAO/LineItem.php
  xml/schema/Financial/FinancialItem.xml
  xml/schema/Price/LineItem.xml
Labels: master, merge ready

#20457 APIv4 - Return id_field as part of Entity.get
  Civi/Api4/Entity.php
  Civi/Api4/Generic/AbstractEntity.php
  Civi/Api4/Generic/BasicEntity.php
  ext/afform/core/Civi/Api4/Afform.php
  tests/phpunit/api/v4/Action/BasicActionsTest.php
  tests/phpunit/api/v4/Mock/Api4/MockBasicEntity.php
  tests/phpunit/api/v4/Mock/MockEntityDataStorage.php
Labels: master

#20459 [Ref] Remove function parameter only used from test
  CRM/Logging/Schema.php
  tests/phpunit/api/v3/LoggingTest.php
Labels: master

#20468 [NFC] 5.38 Release notes First pass
  contributor-key.yml
  release-notes/5.38.0.md
Labels: 5.38

#20460 [Ref] [tests only] replace direct calls to enable logging with calls to the setting
  tests/phpunit/CRM/Core/BAO/SchemaHandlerTest.php
  tests/phpunit/CRM/Logging/LoggingTest.php
  tests/phpunit/CRM/Logging/SchemaTest.php
Labels: master, merge on pass

#20467 SearchKit - Update `hook_civicrm_searchKitTasks` signature
  ext/search_kit/Civi/Api4/Action/SearchDisplay/GetSearchTasks.php
  ext/search_kit/search_kit.php
Labels: master

#20465 Bump DOMPDF to `~1.0.0`
  composer.json
  composer.lock
Labels: master

#20469 5.38
  contributor-key.yml
  release-notes/5.38.0.md
Labels: master

#20473 [php8-compat] Fix deprecation error where by required function parame…
  CRM/Activity/BAO/Activity.php
  CRM/Batch/BAO/Batch.php
  CRM/Case/BAO/Case.php
  CRM/Contribute/BAO/ContributionPage.php
  CRM/Core/BAO/Setting.php
  CRM/Mailing/BAO/Mailing.php
  CRM/Mailing/Event/BAO/TrackableURLOpen.php
  CRM/Mailing/Event/BAO/Unsubscribe.php
  CRM/Price/BAO/LineItem.php
Labels: master

#20477 [php8-compat][phpunit8][NFC] Fix PHPUnit Warnings and fix a php error on f…
  ext/afform/mock/ang/mockPublicForm.test.php
  ext/afform/mock/tests/phpunit/Civi/AfformMock/FormTestCase.php
  ext/flexmailer/tests/phpunit/Civi/FlexMailer/MailingPreviewTest.php
Labels: master, merge on pass

#20475 Remove pass-by-ref as param not altered
  Civi/Core/SqlTriggers.php
Labels: master, merge on pass

#20481 APIv4 - Fix getFields to respect default_value from getFields
  CRM/Core/DAO/CustomGroup.php
  Civi/Api4/Generic/BasicGetFieldsAction.php
  xml/schema/Core/CustomGroup.xml
Labels: master

#20458 Extract code that populates temp table for an individual group
  CRM/Contact/BAO/GroupContactCache.php
Labels: master

#20480 Afform - Fix custom field handling and add tests
  CRM/Custom/Form/Group.php
  Civi/Api4/Service/Spec/SpecFormatter.php
  ext/afform/core/CRM/Afform/AfformScanner.php
  ext/afform/core/Civi/Api4/Action/Afform/Submit.php
  ext/afform/mock/tests/phpunit/api/v4/AfformContactUsageTest.php
  ext/afform/mock/tests/phpunit/api/v4/AfformCustomFieldUsageTest.php
  ext/afform/mock/tests/phpunit/api/v4/AfformUsageTestCase.php
  tests/phpunit/api/v4/Utils/CoreUtilTest.php
Labels: has-test, master

#20484 5.38.0 release notes: added late changes
  release-notes/5.38.0.md
Labels: 5.38

#20483 [php8-compat][NFC] Ensure that the 2nd parameter of hash_equals is a …
  ext/authx/Civi/Authx/Authenticator.php
Labels: master, merge on pass

#20486 5.38
  release-notes/5.38.0.md
Labels: master

#20485 [php8-compat][REF] Fix php8 error on undefined constant CIVICRM_DISAB…
  CRM/Core/Resources/Common.php
Labels: master, merge on pass

#20487 Remove some unused variables
  CRM/Core/BAO/CustomValueTable.php
Labels: master

#20489 APIv4 - Cleanup getFields, add @internal flag for non-public field attributes
  Civi/Api4/Generic/AbstractAction.php
  Civi/Api4/Generic/BasicGetFieldsAction.php
  Civi/Api4/Service/Spec/FieldSpec.php
  Civi/Api4/Service/Spec/Provider/CustomValueSpecProvider.php
  Civi/Api4/Service/Spec/SpecFormatter.php
  tests/phpunit/api/v4/Action/GetFieldsTest.php
Labels: has-test, master

#20478 dev/translation#67 - Define "Translation" table. Add during installation/upgrade.
  CRM/Core/BAO/Translation.php
  CRM/Core/DAO/AllCoreTables.data.php
  CRM/Core/DAO/Translation.php
  CRM/Upgrade/Incremental/sql/5.39.alpha1.mysql.tpl
  CRM/Utils/Hook.php
  xml/schema/Core/Translation.xml
  xml/schema/Core/files.xml
Labels: master

#20490 [REF][php8-compat] Further fixes where there is a required paramater …
  CRM/Contact/BAO/Query.php
  CRM/Utils/Weight.php
  api/v3/Profile.php
  tests/phpunit/CiviTest/CiviMailUtils.php
Labels: master, merge on pass

#20491 [php8-compat] Fix undefined property on Array Cache class in wordpres…
  CRM/Utils/Cache/ArrayCache.php
Labels: master, merge on pass

#20492 Cleanup references to old dedupe class names
  CRM/Activity/BAO/Activity.php
  CRM/Activity/Import/Parser/Activity.php
  CRM/Contact/BAO/Contact/Utils.php
  CRM/Contact/Form/Contact.php
  CRM/Contact/Form/DedupeRules.php
  CRM/Contact/Form/Merge.php
  CRM/Contact/Import/Form/MapField.php
  CRM/Contact/Page/AJAX.php
  CRM/Contact/Page/DedupeFind.php
  CRM/Contact/Page/DedupeRules.php
  CRM/Contribute/BAO/Contribution.php
  CRM/Contribute/Import/Form/MapField.php
  CRM/Contribute/Import/Parser/Contribution.php
  CRM/Dedupe/BAO/DedupeException.php
  CRM/Dedupe/BAO/DedupeRule.php
  CRM/Dedupe/BAO/DedupeRuleGroup.php
  CRM/Dedupe/Finder.php
  CRM/Dedupe/Merger.php
  CRM/Event/BAO/Participant.php
  CRM/Event/Form/ManageEvent/Registration.php
  CRM/Event/Import/Parser/Participant.php
  CRM/Import/Form/MapField.php
  CRM/Member/BAO/Membership.php
  CRM/Member/Import/Form/MapField.php
  CRM/Member/Import/Parser/Membership.php
  Civi/Api4/DedupeException.php
  Civi/Api4/DedupeRule.php
  Civi/Api4/DedupeRuleGroup.php
  tests/phpunit/CRM/Core/PseudoConstantTest.php
  tests/phpunit/CRM/Dedupe/BAO/RuleGroupTest.php
  tests/phpunit/CRM/Dedupe/MergerTest.php
Labels: master

#20470 APIv4 Entity.get refactor to be more efficient
  Civi/Api4/Action/Entity/Get.php
  Civi/Api4/Entity.php
  Civi/Api4/Event/Subscriber/ValidateFieldsSubscriber.php
  ang/api4Explorer/Explorer.js
Labels: master

#20375 Prevent adding duplicate dashlet if present with same name and label
  CRM/Core/BAO/Dashboard.php
Labels: master, merge ready

#20479 dev/core#2636 - Authx - Undefined function in drupal 9
  ext/authx/Civi/Authx/Drupal8.php
Labels: master

#20488 Clarify types on `hook_custom` and `hook_customPre`
  CRM/Core/BAO/CustomValue.php
  CRM/Core/BAO/CustomValueTable.php
  CRM/Utils/Hook.php
Labels: master, merge ready

#20497 [REF][php8-compat] Fix more instances of where there is a required pa…
  CRM/Core/Permission/UnitTests.php
  CRM/Core/Reference/OptionValue.php
  CRM/Utils/Pager.php
  Civi/Payment/PropertyBag.php
  tests/phpunit/CRM/Contact/BAO/RelationshipTest.php
Labels: master, merge on pass

#20496 [php8-compat][NFC] Fix issue where by we are tryiing to access array keys …
  tests/phpunit/CRM/Core/BAO/ActionScheduleTest.php
Labels: master, merge on pass

#20501 Add APIv4 Batch.create spec
  Civi/Api4/Service/Spec/Provider/BatchCreationSpecProvider.php
  api/v3/Batch.php
Labels: master, merge on pass

#20506 APIv4 - Delete undocumented deprecated activityType lookup
  Civi/Api4/Event/Subscriber/ActivityPreCreationSubscriber.php
Labels: master

#20498 [REF] Fix Authx tests on Druapl 8/9 by ensuring that we only return a…
  ext/authx/Civi/Authx/Drupal8.php
Labels: master

#20503 [php8-compat] fix Upgrade call back issues by making functions static…
  CRM/Extension/Manager.php
  CRM/Upgrade/Incremental/Base.php
  CRM/Upgrade/Incremental/php/FiveSeventeen.php
  CRM/Upgrade/Incremental/php/FiveTwentySeven.php
  CRM/Upgrade/Incremental/php/FiveTwentySix.php
Labels: master, merge on pass

#20504 ACLEntityRole BAO tidy fixes
  CRM/ACL/BAO/ACLEntityRole.php
Labels: master

#20500 [php8-compat][NFC] Fix using ZipArchive::open on an empty file
  CRM/Utils/Zip.php
Labels: master

#20502 [php8-compat] Fix issue with returning bool from uasort by using the …
  CRM/Core/BAO/Dashboard.php
  CRM/Utils/Check.php
  api/v3/Profile.php
Labels: master, merge on pass

#20508 [php8-compat] Fix issue in APIv3 Where by because product has a colum…
  api/v3/Generic.php
Labels: master, merge on pass

#20509 [php8-compat] Fix php beautifier notice by conditionally assinging dy…
  CRM/Core/CodeGen/Specification.php
Labels: master, merge on pass

#20331 Allow legacy warnings to be fully suppressed in PropertyBag
  Civi/Payment/PropertyBag.php
Labels: master

#20515 [php8-compat] Fix some more examples of where required parameters are…
  CRM/Activity/Import/Parser.php
  CRM/Campaign/Form/Campaign.php
  CRM/Contribute/Import/Parser.php
  CRM/Core/Smarty/plugins/block.localize.php
  CRM/Event/Form/Registration.php
  CRM/Event/Import/Parser.php
  CRM/Member/Import/Parser.php
Labels: master, merge on pass

#20512 [php8-compat] Update smarty templates and some php files to get the a…
  CRM/Contribute/BAO/ContributionPage.php
  CRM/Contribute/Form/Contribution/Confirm.php
  CRM/Core/Payment/AuthorizeNet.php
  CRM/Event/BAO/Event.php
  tests/templates/message_templates/contribution_online_receipt_html.tpl
  tests/templates/message_templates/event_online_receipt_text.tpl
  xml/templates/message_templates/contribution_invoice_receipt_html.tpl
  xml/templates/message_templates/contribution_offline_receipt_html.tpl
  xml/templates/message_templates/contribution_offline_receipt_text.tpl
  xml/templates/message_templates/contribution_online_receipt_html.tpl
  xml/templates/message_templates/contribution_online_receipt_text.tpl
  xml/templates/message_templates/event_offline_receipt_html.tpl
  xml/templates/message_templates/event_offline_receipt_text.tpl
  xml/templates/message_templates/event_online_receipt_html.tpl
  xml/templates/message_templates/event_online_receipt_subject.tpl
  xml/templates/message_templates/event_online_receipt_text.tpl
  xml/templates/message_templates/event_registration_receipt_html.tpl
  xml/templates/message_templates/event_registration_receipt_text.tpl
  xml/templates/message_templates/membership_offline_receipt_html.tpl
  xml/templates/message_templates/membership_offline_receipt_text.tpl
  xml/templates/message_templates/membership_online_receipt_html.tpl
  xml/templates/message_templates/membership_online_receipt_text.tpl
  xml/templates/message_templates/payment_or_refund_notification_html.tpl
Labels: master, merge on pass

#20517 [php8-compat][REF] Fix more php8 test failures caused by template issues
  tests/templates/message_templates/event_online_receipt_text.tpl
  xml/templates/message_templates/contribution_invoice_receipt_html.tpl
  xml/templates/message_templates/contribution_offline_receipt_html.tpl
  xml/templates/message_templates/contribution_offline_receipt_text.tpl
  xml/templates/message_templates/event_offline_receipt_html.tpl
  xml/templates/message_templates/event_offline_receipt_text.tpl
  xml/templates/message_templates/event_online_receipt_html.tpl
  xml/templates/message_templates/event_online_receipt_text.tpl
  xml/templates/message_templates/event_registration_receipt_html.tpl
  xml/templates/message_templates/event_registration_receipt_text.tpl
  xml/templates/message_templates/membership_offline_receipt_html.tpl
  xml/templates/message_templates/membership_offline_receipt_text.tpl
Labels: master

#20518 [php8-compat][REF] Fix api_v3_contributionpagetest on php8
  xml/templates/message_templates/contribution_invoice_receipt_html.tpl
  xml/templates/message_templates/contribution_offline_receipt_html.tpl
  xml/templates/message_templates/contribution_offline_receipt_text.tpl
  xml/templates/message_templates/contribution_online_receipt_html.tpl
  xml/templates/message_templates/contribution_online_receipt_text.tpl
  xml/templates/message_templates/event_offline_receipt_html.tpl
  xml/templates/message_templates/event_offline_receipt_text.tpl
  xml/templates/message_templates/event_online_receipt_html.tpl
  xml/templates/message_templates/event_online_receipt_text.tpl
  xml/templates/message_templates/membership_offline_receipt_html.tpl
  xml/templates/message_templates/membership_offline_receipt_text.tpl
  xml/templates/message_templates/membership_online_receipt_html.tpl
  xml/templates/message_templates/membership_online_receipt_text.tpl
Labels: master

#20516 [php8-compat][REF] Fix some more test failures in php8
  CRM/Campaign/BAO/Petition.php
  CRM/Event/Form/Participant.php
  CRM/Member/Form/Membership.php
  templates/CRM/common/CMSPrint.tpl
  templates/CRM/common/accesskeys.tpl
  templates/CRM/common/joomla.tpl
  templates/CRM/common/status.tpl
Labels: master

#20513 dev/core#1549 - Malleate civicrm_generated so that long lines are split
  bin/regen.sh
  sql/civicrm_generated.mysql
Labels: master

#20499 dev/core#2486 - Use read-only permissions for FinancialItem API
  CRM/Core/Permission.php
  Civi/Api4/FinancialItem.php
Labels: master

#20520 [php8-compat] Fix api_v3_PaymentTest failures by putting in more guar…
  xml/templates/message_templates/event_offline_receipt_html.tpl
  xml/templates/message_templates/event_offline_receipt_text.tpl
  xml/templates/message_templates/event_online_receipt_html.tpl
  xml/templates/message_templates/event_online_receipt_text.tpl
  xml/templates/message_templates/membership_offline_receipt_html.tpl
  xml/templates/message_templates/payment_or_refund_notification_html.tpl
  xml/templates/message_templates/payment_or_refund_notification_text.tpl
Labels: master, merge on pass

#20507 SearchKit - Add API filter for contacts in groups and smart groups
  CRM/Contact/BAO/GroupContactCache.php
  Civi/Api4/Action/CustomValue/GetFields.php
  Civi/Api4/Generic/AbstractAction.php
  Civi/Api4/Generic/BasicGetFieldsAction.php
  Civi/Api4/Generic/DAOGetFieldsAction.php
  Civi/Api4/Query/Api4SelectQuery.php
  Civi/Api4/Service/Spec/CustomFieldSpec.php
  Civi/Api4/Service/Spec/FieldSpec.php
  Civi/Api4/Service/Spec/Provider/ContactGetSpecProvider.php
  Civi/Api4/Service/Spec/Provider/CustomValueSpecProvider.php
  Civi/Api4/Service/Spec/SpecFormatter.php
  ext/afform/admin/Civi/AfformAdmin/AfformAdminMeta.php
  ext/search_kit/Civi/Search/Admin.php
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdmin.component.js
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdminDisplay.component.js
  ext/search_kit/ang/crmSearchAdmin/crmSearchClause.component.js
  ext/search_kit/ang/crmSearchAdmin/crmSearchClause.html
  tests/phpunit/api/v4/Action/BasicCustomFieldTest.php
  tests/phpunit/api/v4/Action/CustomValueTest.php
  tests/phpunit/api/v4/Action/GetExtraFieldsTest.php
  tests/phpunit/api/v4/Action/PseudoconstantTest.php
  tests/phpunit/api/v4/Action/ResultTest.php
  tests/phpunit/api/v4/Entity/ConformanceTest.php
  tests/phpunit/api/v4/Entity/SavedSearchTest.php
Labels: has-test, master

#20521 Test fix up for AdditionalPaymentTest
  tests/phpunit/CRM/Contribute/Form/AdditionalPaymentTest.php
  tests/phpunit/CRM/Member/Form/MembershipTest.php
  tests/phpunit/CRMTraits/Financial/OrderTrait.php
  tests/phpunit/api/v3/ContributionTest.php
  tests/phpunit/api/v3/MembershipTest.php
Labels: master

#20357 Fix for tax rates being mangled on contribution update
  CRM/Contribute/BAO/Contribution.php
  CRM/Price/BAO/LineItem.php
  api/v3/examples/Contribution/Create.ex.php
  tests/phpunit/CRM/Contribute/Form/ContributionTest.php
  tests/phpunit/CRM/Event/Form/Task/BatchTest.php
  tests/phpunit/api/v3/ContributionPageTest.php
  tests/phpunit/api/v3/OrderTest.php
  tests/phpunit/api/v3/TaxContributionPageTest.php
Labels: has-test, master

#20524 [php8-compat][REF] Fix Case and Custom data tests by adding guards in…
  templates/CRM/Activity/Form/Activity.tpl
  templates/CRM/Campaign/Form/addCampaignToComponent.tpl
  templates/CRM/Custom/Form/CustomData.tpl
  templates/CRM/Custom/Form/Edit/CustomField.tpl
  templates/CRM/Event/Form/ManageEvent/ConfirmRepeatMode.tpl
  templates/CRM/Form/attachmentjs.tpl
  templates/CRM/common/formButtons.tpl
  xml/templates/message_templates/case_activity_html.tpl
  xml/templates/message_templates/case_activity_subject.tpl
  xml/templates/message_templates/case_activity_text.tpl
Labels: master, merge on pass

#20527 [php8-compact][REF] Fix api_v3_PaymentTokenTest to work on php8
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: master, merge on pass

#20526 [php8-compact][REF] Fix another couple of places where by there are r…
  CRM/Core/Form/RecurringEntity.php
  CRM/Utils/Mail/Incoming.php
Labels: master, merge on pass

#20528 dev/report#67 Fix standalone export classes
  CRM/Export/Controller/Standalone.php
Labels: master, merge on pass, sig:regression, sig:search-kit

#20525 [php8-compat][REF] Fix Date unit tests in php8 by passing in 00 inste…
  CRM/Utils/Date.php
Labels: master

#20529 Fix standalone export classes
  CRM/Export/Controller/Standalone.php
Labels: 5.38, merge on pass

#20534 Dedupe DAO is out of date
  CRM/Dedupe/DAO/DedupeException.php
Labels: master

#20535 Switch table mapping to square bracket array syntax.
  CRM/Admin/Form/Setting/UF.php
Labels: master

#20538 [php8-compat] Fix Resources Test issue due to undefined array key add…
  CRM/Core/Smarty/plugins/function.crmResURL.php
Labels: master, merge on pass

#20537 SearchKit - Fix link target selection
  ext/search_kit/ang/crmSearchAdmin/displays/colType/field.html
  ext/search_kit/ang/crmSearchDisplay.module.js
  ext/search_kit/ang/crmSearchDisplay/colType/buttons.html
  ext/search_kit/ang/crmSearchDisplay/colType/field.html
  ext/search_kit/ang/crmSearchDisplay/colType/links.html
  ext/search_kit/ang/crmSearchDisplay/colType/menu.html
  js/crm.ajax.js
Labels: master

#20539 [php8-compat] Fix Include/Exclude Group Custom Search Tests by better…
  CRM/Contact/Form/Search/Custom/Group.php
Labels: master, merge on pass

#20541 Sort trigger data before processing
  CRM/Logging/Schema.php
  Civi/Core/SqlTriggers.php
Labels: master, merge on pass

#20530 Fix v3 api payment test to validate on postAssert
  tests/phpunit/api/v3/PaymentTest.php
Labels: master

#20555 (REF) dev/core#1744 - Simplify Afform event naming
  ext/afform/core/Civi/Api4/Action/Afform/Submit.php
  ext/afform/core/afform.php
Labels: master, merge on pass

#20559 dev/core#2486 - Add WordReplacement APIv4 entity
  Civi/Api4/WordReplacement.php
Labels: master

#20558 SearchKit - allow searches based on relationships
  CRM/Contact/DAO/Relationship.php
  CRM/Contact/DAO/RelationshipCache.php
  Civi/Api4/ActivityContact.php
  Civi/Api4/CaseActivity.php
  Civi/Api4/CaseContact.php
  Civi/Api4/DashboardContact.php
  Civi/Api4/Entity.php
  Civi/Api4/EntityFinancialAccount.php
  Civi/Api4/EntityFinancialTrxn.php
  Civi/Api4/EntityTag.php
  Civi/Api4/GroupContact.php
  Civi/Api4/RelationshipCache.php
  ext/search_kit/Civi/Api4/Action/SearchDisplay/Run.php
  ext/search_kit/Civi/Search/Admin.php
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdmin.component.js
  ext/search_kit/ang/crmSearchAdmin/crmSearchClause.component.js
  tests/phpunit/api/v4/Entity/ConformanceTest.php
  xml/schema/Contact/Relationship.xml
  xml/schema/Contact/RelationshipCache.xml
Labels: master

#20540 [php8-compat] Upgrade TCPDF version to support php8
  composer.json
  composer.lock
Labels: master

#20549 [php8-compact] Fix Report tests failing on php8
  templates/CRM/Report/Form.tpl
  templates/CRM/Report/Form/Layout/Graph.tpl
  templates/CRM/Report/Form/Layout/Table.tpl
  templates/CRM/Report/Form/Statistics.tpl
Labels: master

#20542 [php8-compact] Add in guards into various templates to fix hook tests…
  templates/CRM/Admin/Form/ParticipantStatusType.tpl
  templates/CRM/Admin/Page/ContactType.tpl
  templates/CRM/Admin/Page/Job.tpl
  templates/CRM/Admin/Page/JobLog.tpl
  templates/CRM/Admin/Page/LocationType.tpl
  templates/CRM/Admin/Page/MailSettings.tpl
Labels: master

#20557 [NFC/Unit Test] Failing test for civicrm-packages PR 324
  tests/phpunit/CRM/Core/I18n/LocaleTest.php
Labels: has-test, master, merge on pass

#20548 Fix the populateTempTable to be more direct
  CRM/Contact/BAO/GroupContactCache.php
  tests/phpunit/api/v3/ReportTemplateTest.php
  tests/phpunit/api/v4/Entity/SavedSearchTest.php
Labels: master

#20545 [php8-compat] Partial Fix of hook tests for php8
  CRM/Contact/Page/DedupeMerge.php
  CRM/Event/Page/ManageEvent.php
  templates/CRM/Admin/Form/ContactType.tpl
  templates/CRM/Admin/Form/OptionGroup.tpl
  templates/CRM/Admin/Form/Options.tpl
  tests/phpunit/CRM/Core/Page/HookTest.php
Labels: master

#20560 APIv4 - Make the @searchable flag explicit for OptionList type entities.
  Civi/Api4/CaseType.php
  Civi/Api4/ContactType.php
  Civi/Api4/Country.php
  Civi/Api4/FinancialType.php
  Civi/Api4/Generic/AbstractEntity.php
  Civi/Api4/Generic/Traits/OptionList.php
  Civi/Api4/LocationType.php
  Civi/Api4/MembershipType.php
  Civi/Api4/OptionGroup.php
  Civi/Api4/OptionValue.php
  Civi/Api4/PaymentProcessor.php
  Civi/Api4/PaymentProcessorType.php
  Civi/Api4/PaymentToken.php
  Civi/Api4/RelationshipType.php
  Civi/Api4/StateProvince.php
Labels: master, merge on pass

#20059 dev/core#2479 Adjust generic copy for localizable fields
  CRM/Core/DAO.php
  tests/phpunit/CRM/Core/CopyTest.php
Labels: master, merge ready

#20562 [REF] CRM_Contact_Task - Use short array syntax
  CRM/Contact/Task.php
Labels: master

#20563 REF - Cleanup array key checking to use array_key_exists
  CRM/Admin/Form/ContactType.php
  CRM/Admin/Page/MessageTemplates.php
  CRM/Contact/BAO/Query.php
  CRM/Contact/Form/Search/Advanced.php
  CRM/Contact/Import/Parser/Contact.php
  CRM/Contribute/BAO/Contribution.php
  CRM/Core/BAO/CustomField.php
  CRM/Core/BAO/UFGroup.php
  CRM/Core/I18n/Schema.php
  CRM/Event/Import/Parser/Participant.php
  CRM/Logging/Reverter.php
  CRM/Price/BAO/PriceField.php
  CRM/Report/Form.php
  CRM/Report/Form/Contact/Relationship.php
  api/v3/Contribution.php
  ext/financialacls/financialacls.php
  tests/phpunit/CRM/Contact/SelectorTest.php
  tests/phpunit/CRM/Core/BAO/SchemaHandlerTest.php
Labels: master

#20493 Fix for dev/membership#37
  CRM/Contact/BAO/Relationship.php
  tests/phpunit/CRM/Member/BAO/MembershipTest.php
Labels: has-test, master

#20564 dev/core#2646 juice up the error a little
  CRM/Core/ManagedEntities.php
Labels: master, merge on pass

#20552 Mark DetailTest as having invalid financials
  CRM/Core/Payment/PayPalImpl.php
  CRM/Utils/Hook/UnitTests.php
  tests/phpunit/CRM/Report/Form/Contribute/DetailTest.php
Labels: master

#20532 Fix Financial item test to validate Financials
  tests/phpunit/CRM/Financial/BAO/FinancialItemTest.php
Labels: master

#19973 (dev/core#365) Scheduled Reminders - Add effective end and start date, extend unit test
  Civi/ActionSchedule/RecipientBuilder.php
  tests/phpunit/CRM/Core/BAO/ActionScheduleTest.php
Labels: has-test, master

#20432 (dev/core#365) Scheduled Reminders - Add effective start and end date to admin UI
  CRM/Admin/Form/ScheduleReminders.php
  templates/CRM/Admin/Form/ScheduleReminders.tpl
Labels: master

#20565 Throw exception rather than allow php fail
  Civi/API/SelectQuery.php
Labels: master

#20566 Add pseudoconstant to acl_entity_role
  CRM/ACL/DAO/ACLEntityRole.php
  xml/schema/ACL/ACLEntityRole.xml
Labels: master

#20567 [NFC] Fix phpunit9 deprecation issues on using assertType instead of …
  tests/phpunit/CRM/Utils/versionCheckTest.php
Labels: 5.39, merge on pass

#20568 5.39
  tests/phpunit/CRM/Utils/versionCheckTest.php
Labels: master

#20543 [php8-compact] Add in guards into common templates to assit with fixi…
  templates/CRM/Core/Form/Field.tpl
  templates/CRM/Form/validate.tpl
  templates/CRM/common/Tagset.tpl
  templates/CRM/common/WizardHeader.tpl
  templates/CRM/common/customData.tpl
  templates/CRM/common/customDataBlock.tpl
  templates/CRM/common/formButtons.tpl
  templates/CRM/common/jsortable.tpl
  templates/CRM/common/showHide.tpl
Labels: master, merge on pass

#20571 Update civicrm_generated (5.39 version)
  sql/civicrm_generated.mysql
Labels: 5.39, merge on pass

#20576 5.39 to master
  sql/civicrm_generated.mysql
Labels: master

#20547 [php8-compact] Add in protection for unset variables in admin smarty …
  templates/CRM/Admin/Form/MessageTemplates.tpl
  templates/CRM/Admin/Form/ScheduleReminders.tpl
  templates/CRM/Admin/Page/MessageTemplates.tpl
  templates/CRM/Admin/Page/Options.tpl
  templates/CRM/Admin/Page/ParticipantStatusType.tpl
  templates/CRM/Admin/Page/PaymentProcessorType.tpl
  templates/CRM/Admin/Page/RelationshipType.tpl
  templates/CRM/Admin/Page/ScheduleReminders.tpl
Labels: master, merge on pass

#20546 [php8-compact] Add in more protection for unset variables in various …
  templates/CRM/Batch/Form/Search.tpl
  templates/CRM/Campaign/Page/SurveyType.tpl
  templates/CRM/Contact/Form/DedupeRules.tpl
  templates/CRM/Contact/Form/Task/Email.hlp
  templates/CRM/Contact/Form/Task/EmailCommon.tpl
  templates/CRM/Contribute/Form/ManagePremiums.tpl
  templates/CRM/Contribute/Page/UserDashboard.tpl
  templates/CRM/Event/Page/UserDashboard.tpl
  templates/CRM/Financial/Form/Search.tpl
  templates/CRM/Financial/Page/FinancialAccount.tpl
  templates/CRM/Financial/Page/FinancialType.tpl
  tests/phpunit/CRM/Contact/Page/View/UserDashBoardTest.php
Labels: master, merge on pass

#20544 [php8-compact] Add in guards into various templates to fix issues in …
  templates/CRM/Group/Form/Edit.tpl
  templates/CRM/Group/Form/GroupsCommon.tpl
  templates/CRM/Group/Form/Search.tpl
  templates/CRM/Mailing/Form/InsertTokens.tpl
  templates/CRM/Member/Page/MembershipStatus.tpl
  templates/CRM/Pledge/Page/UserDashboard.tpl
  templates/CRM/Report/Page/Options.tpl
Labels: master, merge on pass

#20575 [php8-compact] Fix Dashboard Tests by adding in if guards into smarty…
  templates/CRM/Case/Form/Search/Common.tpl
  templates/CRM/Contact/Form/GroupContact.tpl
  templates/CRM/Contact/Page/View/RelationshipSelector.tpl
  templates/CRM/Contact/Page/View/UserDashBoard/GroupContact.tpl
  templates/CRM/Contribute/Page/PcpUserDashboard.tpl
  templates/CRM/Core/DatePickerRangeWrapper.tpl
  templates/CRM/Form/validate.tpl
  templates/CRM/Pledge/Page/UserDashboard.tpl
  templates/CRM/common/contactFooter.tpl
Labels: master, merge on pass

#20581 [php8-compact] Fixes test failures in the CRM_Contribute_Form_Contrib…
  sql/civicrm_generated.mysql
  xml/templates/message_templates/contribution_offline_receipt_html.tpl
  xml/templates/message_templates/contribution_offline_receipt_text.tpl
Labels: master, merge on pass

#20579 [php8-compact] Add in guards into various templates to fix the CRM_Co…
  templates/CRM/Contact/Form/Contact.tpl
  templates/CRM/Contact/Form/Edit/Address.tpl
  templates/CRM/Contact/Form/Edit/Individual.tpl
  templates/CRM/Contact/Form/Edit/TagsAndGroups.tpl
  templates/CRM/Custom/Form/Edit/CustomData.tpl
  templates/CRM/common/CMSPrint.tpl
  templates/CRM/common/TabHeader.tpl
  templates/CRM/common/additionalBlocks.tpl
Labels: master, merge on pass

#20580 dev/core#2649 - Make 5.39 upgrade more robust
  CRM/Upgrade/Incremental/sql/5.39.alpha1.mysql.tpl
Labels: 5.39, merge on pass

#20585 5.39
  CRM/Upgrade/Incremental/sql/5.39.alpha1.mysql.tpl
Labels: master

#20584 dev/translation#67 - Add APIv4 support for "Translation" entity.
  CRM/Core/BAO/Translation.php
  CRM/Core/DynamicFKAccessTrait.php
  Civi/Api4/Translation.php
  tests/phpunit/api/v4/Entity/TranslationTest.php
  tests/phpunit/api/v4/Service/TestCreationParameterProvider.php
Labels: has-test, master

#20589 SearchKit - Show Pledge as a primary entity
  Civi/Api4/Pledge.php
Labels: master

#20591 [php8-compact] Fix PDF Letter Test by ensuring that all actual DB fi…
  CRM/Utils/Token.php
  tests/phpunit/CRM/Contribute/Form/Task/PDFLetterCommonTest.php
Labels: master, merge on pass

#20574 Reduce test api calls with no 'return'
  tests/phpunit/api/v3/ContactTest.php
Labels: master, merge on pass

#20592 [php8-compact] Fix Case Activity Message Template to fix test failure…
  sql/civicrm_generated.mysql
  xml/templates/message_templates/case_activity_html.tpl
  xml/templates/message_templates/case_activity_text.tpl
Labels: master, merge on pass

#20577 Fix a few more undefined template vars
  CRM/Core/Block.php
  templates/CRM/common/debug.tpl
Labels: master, merge on pass

#20593 [php8-compact] Fix Session Test errors in php8
  templates/CRM/common/info.tpl
Labels: master

#20595 [php8-compact] Fix failing CRM_Core_InvokeTest on php8
  templates/CRM/Contact/Page/DashBoardDashlet.tpl
  templates/CRM/Form/body.tpl
  templates/CRM/Form/default.tpl
Labels: master

#20596 [php8-compact] Fix failing AuthorizeNetIPN tests on php8
  templates/CRM/Contribute/Form/Contribution/AuthorizeNetARB.tpl
Labels: master

#20523 Send pcp notification only when the contribution is completed
  CRM/Contribute/BAO/Contribution.php
  CRM/Contribute/BAO/ContributionSoft.php
  CRM/Contribute/Form/Contribution/Confirm.php
Labels: master

#20522 [REF] Move pcpNotifyOwner to ContributionSoft
  CRM/Contribute/BAO/ContributionSoft.php
  CRM/Contribute/Form/Contribution/Confirm.php
Labels: master

#20597 [php8-compact] Further test fixes for php8
  CRM/Core/Form/Date.php
  templates/CRM/Form/body.tpl
Labels: master

#20599 [NFC] - update code comment
  templates/CRM/Form/body.tpl
Labels: master

#20594 [php8-compact] Fix apiv4 tests in php8 by not incrementing an array
  Civi/Api4/Query/SqlFunction.php
Labels: master

#20603 [php8-compat] Alternate to the alternate for testOpeningForms
  CRM/Contact/Form/Search/Custom/FullText.php
  templates/CRM/Contact/Form/Search/Custom/FullText.tpl
  templates/CRM/Price/Page/Field.tpl
  templates/CRM/Tag/Form/Edit.tpl
  tests/phpunit/CRM/Core/FormTest.php
Labels: master, merge on pass

#20605 [NFC] Fix test failure on MySQL8 because of lack of order in API
  tests/phpunit/api/v3/ContactTest.php
Labels: master, merge on pass

#20606 dev/translation#67 - Allow translation of fields which lack an explicit HTML type
  CRM/Core/BAO/Translation.php
Labels: master, merge on pass

#20573 APIv4 - Add filter for entity tags
  CRM/Core/BAO/EntityTag.php
  CRM/Core/DAO/EntityTag.php
  CRM/Core/PseudoConstant.php
  CRM/Upgrade/Incremental/sql/5.40.alpha1.mysql.tpl
  Civi/Api4/Query/Api4SelectQuery.php
  Civi/Api4/Service/Spec/Provider/ContactGetSpecProvider.php
  Civi/Api4/Service/Spec/Provider/EntityTagFilterSpecProvider.php
  api/v3/utils.php
  sql/civicrm_generated.mysql
  tests/phpunit/api/v4/Action/FkJoinTest.php
  tests/phpunit/api/v4/Action/GetExtraFieldsTest.php
  tests/phpunit/api/v4/Entity/TagTest.php
  xml/schema/Core/EntityTag.xml
  xml/templates/civicrm_data.tpl
Labels: has-test, master

#20611 Fix unreleased api change to more logical variant
  CRM/Member/Form/Membership.php
  api/v3/Order.php
  tests/phpunit/CRMTraits/Financial/OrderTrait.php
Labels: 5.39, merge on pass

#20609 APIv4 - Make LineItem, EntityFinancialTrxn and FinancialTrxn read-only
  Civi/Api4/EntityFinancialTrxn.php
  Civi/Api4/FinancialItem.php
  Civi/Api4/FinancialTrxn.php
  Civi/Api4/Generic/Traits/ReadOnly.php
  Civi/Api4/LineItem.php
  ext/financialacls/tests/phpunit/Civi/Financialacls/LineItemTest.php
  tests/phpunit/api/v4/Entity/ConformanceTest.php
Labels: 5.39, has-test, merge on pass

#20612 5.39
  CRM/Member/Form/Membership.php
  Civi/Api4/EntityFinancialTrxn.php
  Civi/Api4/FinancialItem.php
  Civi/Api4/FinancialTrxn.php
  Civi/Api4/Generic/Traits/ReadOnly.php
  Civi/Api4/LineItem.php
  api/v3/Order.php
  ext/financialacls/tests/phpunit/Civi/Financialacls/LineItemTest.php
  tests/phpunit/CRMTraits/Financial/OrderTrait.php
  tests/phpunit/api/v4/Entity/ConformanceTest.php
Labels: master

#20570 Test cleanup - specify return
  tests/phpunit/CRM/Activity/BAO/ActivityTest.php
Labels: master

#20613 [php8-compact] Fix issues with participant message templates causing…
  sql/civicrm_generated.mysql
  xml/templates/message_templates/participant_cancelled_html.tpl
  xml/templates/message_templates/participant_cancelled_text.tpl
  xml/templates/message_templates/participant_expired_html.tpl
  xml/templates/message_templates/participant_expired_text.tpl
  xml/templates/message_templates/participant_transferred_html.tpl
  xml/templates/message_templates/participant_transferred_text.tpl
Labels: master, merge on pass

#20608 [php8-compact] Fix Array to String in formButtons in CRM_Core_FormTest
  templates/CRM/Contact/Form/Search/BasicCriteria.tpl
Labels: master, merge on pass

#20614 [NFC] Fix test setup on a couple of tests to make them pass in php8
  tests/phpunit/CRM/Contact/Page/AjaxTest.php
  tests/phpunit/api/v3/ACLPermissionTest.php
Labels: master, merge on pass

#20615 [NFC] Afform - Regenerate civix files
  ext/afform/admin/afform_admin.civix.php
  ext/afform/core/afform.civix.php
  ext/afform/html/afform_html.civix.php
  ext/afform/mock/afform_mock.civix.php
Labels: master, merge on pass

#20536 mailing#96: Warn on invalid mailing options
  CRM/Mailing/BAO/Mailing.php
Labels: master, merge on pass

#20610 dev/report#68 Fix smart group crash when ordering by aggregated column
  CRM/Contact/BAO/GroupContactCache.php
Labels: 5.39, merge on pass

#20624 [php8-compact][NFC] Update testGroupClause unit test to work on php8
  tests/phpunit/CRM/Contact/BAO/QueryTest.php
Labels: master

#20618 dev/core#1191 Try adding a strict return function to getAndCheck
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/api/v3/ActivityTest.php
  tests/phpunit/api/v3/AddressTest.php
  tests/phpunit/api/v3/ParticipantTest.php
  tests/phpunit/api/v3/PaymentTokenTest.php
Labels: master

#20629 5.39
  CRM/Contact/BAO/GroupContactCache.php
Labels: master

#20617 Improve CustomGroupTest
  tests/phpunit/CRM/Core/BAO/CustomFieldTest.php
  tests/phpunit/CRM/Core/BAO/CustomGroupTest.php
  tests/phpunit/CRM/Dedupe/MergerTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/api/v3/CustomFieldTest.php
  tests/phpunit/api/v3/JobTest.php
Labels: master, merge on pass

#20622 dev/core#1191 [TEST][NFC] Increase setting of return in tests
  tests/phpunit/CRM/ACL/ListTest.php
  tests/phpunit/CRM/Activity/BAO/ActivityTest.php
  tests/phpunit/api/v3/ACLPermissionTest.php
  tests/phpunit/api/v3/ActivityTest.php
Labels: master

#20628 AngularLoader - Emit warning when setModules method is used.
  Civi/Angular/AngularLoader.php
  tests/phpunit/Civi/Angular/LoaderTest.php
Labels: master

#20632 [NFC] [Test] Specify return values on get calls
  ext/contributioncancelactions/tests/phpunit/CancelTest.php
  tests/phpunit/api/v3/ACLPermissionTest.php
Labels: master, merge on pass

#20630 Use mysql to set mailing.created_date
  CRM/Mailing/DAO/Mailing.php
  CRM/Upgrade/Incremental/sql/5.40.alpha1.mysql.tpl
  Civi/Core/Container.php
  xml/schema/Mailing/Mailing.xml
Labels: master, merge on pass

#20634 replace unnecessary function call with string literal
  CRM/Member/Form/MembershipBlock.php
Labels: master

#20607 SearchKit - Allow super admins to disable Search Display access checks
  CRM/Core/Permission.php
  Civi/Api4/Query/SqlFunctionCOUNT.php
  Civi/Api4/Query/SqlFunctionGROUP_CONCAT.php
  Civi/Api4/Utils/CoreUtil.php
  Civi/Api4/Utils/FormattingUtil.php
  css/civicrm.css
  ext/search_kit/CRM/Search/BAO/SearchDisplay.php
  ext/search_kit/CRM/Search/DAO/SearchDisplay.php
  ext/search_kit/CRM/Search/Upgrader.php
  ext/search_kit/Civi/Api4/Action/SearchDisplay/Run.php
  ext/search_kit/Civi/Api4/SearchDisplay.php
  ext/search_kit/ang/crmSearchAdmin.ang.php
  ext/search_kit/ang/crmSearchAdmin.module.js
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdminDisplay.component.js
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdminDisplay.html
  ext/search_kit/ang/crmSearchAdmin/searchList.controller.js
  ext/search_kit/ang/crmSearchAdmin/searchList.html
  ext/search_kit/css/crmSearchAdmin.css
  ext/search_kit/search_kit.civix.php
  ext/search_kit/search_kit.php
  ext/search_kit/sql/auto_install.sql
  ext/search_kit/sql/auto_uninstall.sql
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/SearchRunTest.php
  ext/search_kit/xml/schema/CRM/Search/SearchDisplay.xml
  tests/phpunit/api/v4/Action/SqlFunctionTest.php
  tests/phpunit/api/v4/Traits/CheckAccessTrait.php
Labels: has-test, master, sig:search-kit

#20635 [NFC] [TEST] cleanup, more use of return in AddressTest
  tests/phpunit/api/v3/AddressTest.php
Labels: master

#20640 Show smarty E-notices when in debug mode
  CRM/Core/Smarty.php
Labels: master, merge on pass

#20641 Fixed url
  CRM/Financial/Form/PaymentEdit.php
Labels: master, merge on pass

#20643 Move upgrade code to correct version
  CRM/Upgrade/Incremental/php/FiveForty.php
  CRM/Upgrade/Incremental/php/FiveThirtyNine.php
Labels: master, merge on pass

#20642 Remove unreachable code from admin page
  CRM/Admin/Page/Admin.php
  templates/CRM/Admin/Page/Admin.tpl
Labels: master, merge on pass

#20645 5.39.0 release notes initial run
  release-notes.md
  release-notes/5.39.0.md
Labels: 5.39

#20554 Convert Notes to use option_group instead of hardcoded list
  CRM/Core/BAO/Note.php
  CRM/Core/DAO/Note.php
  CRM/Upgrade/Incremental/php/FiveForty.php
  sql/civicrm_generated.mysql
  xml/schema/Core/Note.xml
  xml/templates/civicrm_data.tpl
Labels: master, merge on pass

#20646 5.39
  release-notes.md
  release-notes/5.39.0.md
Labels: master

#20644 dev/core#2657 trigger pre hook on LineItem delete
  CRM/Price/BAO/LineItem.php
Labels: master
