Repository civicrm/civicrm-core, pull requests merged in 2021-09, with the labels that each got.

#21333 SearchKit - Fix pager count and add 'None Found' text in empty tables
  ext/search_kit/ang/crmSearchDisplay/Pager.html
  ext/search_kit/ang/crmSearchDisplay/SearchButton.html
  ext/search_kit/ang/crmSearchDisplay/traits/searchDisplayBaseTrait.service.js
  ext/search_kit/ang/crmSearchDisplayTable/crmSearchDisplayTableBody.html
Labels: master, merge on pass

#21270 SearchKit - Use a search display to display searches
  CRM/Contact/DAO/SavedSearch.php
  Civi/Api4/SavedSearch.php
  ext/search_kit/ang/crmSearchAdmin.module.js
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdminDisplay.component.js
  ext/search_kit/ang/crmSearchAdmin/displays/colType/include.html
  ext/search_kit/ang/crmSearchAdmin/searchList.controller.js
  ext/search_kit/ang/crmSearchAdmin/searchList.html
  ext/search_kit/ang/crmSearchAdmin/searchListing/afforms.html
  ext/search_kit/ang/crmSearchAdmin/searchListing/buttons.html
  ext/search_kit/ang/crmSearchAdmin/searchListing/crmSearchAdminSearchListing.component.js
  ext/search_kit/ang/crmSearchAdmin/searchListing/crmSearchAdminSearchListing.html
  ext/search_kit/ang/crmSearchAdmin/searchListing/displays.html
  ext/search_kit/ang/crmSearchDisplay/colType/include.html
  ext/search_kit/ang/crmSearchDisplayTable/crmSearchDisplayTable.html
  ext/search_kit/css/crmSearchAdmin.css
  xml/schema/Contact/SavedSearch.xml
Labels: master, merge on pass

#21286 Fixes unusable modals in Joomla 4
  css/joomla.css
Labels: master, merge ready

#21316 Afform - Optimize Get by checking type
  ext/afform/core/Civi/Api4/Action/Afform/Get.php
Labels: master

#21334 [REF] dev/core#2790 deprecate preProcessSingle
  CRM/Contact/Form/Task/PDF.php
  CRM/Contact/Form/Task/PDFLetterCommon.php
Labels: master

#21341 [NFC/Unit test] Update flaky test CRM_Utils_TokenConsistencyTest::testCaseTokenConsistency
  tests/phpunit/CRM/Utils/TokenConsistencyTest.php
Labels: master, merge on pass

#21337 dev/core#2806 Fix accidental exposure of v4 tokens
  CRM/Core/EntityTokens.php
Labels: master, merge ready

#21340 [NFC] Cleanup boilerplate code in extension upgrader classes
  ext/afform/admin/CRM/AfformAdmin/Upgrader.php
  ext/afform/core/CRM/Afform/Upgrader.php
  ext/ckeditor4/CRM/Ckeditor4/Upgrader.php
  ext/oauth-client/CRM/OAuth/Upgrader.php
  ext/search_kit/CRM/Search/Upgrader.php
Labels: master

#21285 Simplify ContributionView form. Always display "lineitems"
  CRM/Contribute/Form/ContributionView.php
  templates/CRM/Contribute/Form/ContributionView.tpl
Labels: merge ready

#21342 Tidies Joomla 4 integration (menu, padding) after final release
  css/joomla.css
  css/menubar-joomla.css
Labels: master, merge ready

#21344 [REF] Fix Page Hook test on php8 by putting in guard into customDataB…
  templates/CRM/common/customDataBlock.tpl
Labels: master, merge on pass

#21345 [NFC] Fix E-notice in Afform unit tests
  ext/afform/core/Civi/Api4/Action/Afform/Get.php
Labels: master, merge on pass

#21287 Afform - Fix button appearance and block form during submission
  ext/afform/admin/Civi/AfformAdmin/AfformAdminMeta.php
  ext/afform/core/ang/af/afForm.component.js
  ext/afform/core/ang/afCore.css
Labels: master

#21279 [Ref] Deprecate Core_Error handling
  CRM/Contribute/Form/UpdateSubscription.php
Labels: master

#21336 TokenProcessor - Allow defining Smarty variables which are populated via token
  Civi/Token/TokenCompatSubscriber.php
  Civi/Token/TokenProcessor.php
  tests/phpunit/Civi/Token/TokenProcessorTest.php
Labels: master, merge on pass, has-test

#21328 SearchKit - Add download CSV action
  ext/search_kit/Civi/Api4/Action/SearchDisplay/AbstractRunAction.php
  ext/search_kit/Civi/Api4/Action/SearchDisplay/Download.php
  ext/search_kit/Civi/Api4/Action/SearchDisplay/GetSearchTasks.php
  ext/search_kit/ang/crmSearchAdmin/resultsTable/crmSearchAdminResultsTable.component.js
  ext/search_kit/ang/crmSearchAdmin/resultsTable/crmSearchAdminResultsTable.html
  ext/search_kit/ang/crmSearchDisplayTable/crmSearchDisplayTable.html
  ext/search_kit/ang/crmSearchTasks/crmSearchTaskDownload.ctrl.js
  ext/search_kit/ang/crmSearchTasks/crmSearchTaskDownload.html
  ext/search_kit/ang/crmSearchTasks/crmSearchTasks.component.js
  ext/search_kit/ang/crmSearchTasks/crmSearchTasks.html
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/SearchDownloadTest.php
Labels: master, merge on pass, has-test

#21135 dev/core#1618 Trigger a reconciliation of logging tables after Extens…
  CRM/Extension/Upgrades.php
Labels: master

#21311 [REF] Do not set input['line_item'] pointlessly
  CRM/Contribute/BAO/Contribution.php
Labels: master

#20856 dev/core#2716 [REF] Stop 'distributing' the main flow
  CRM/Core/Payment/PayPalIPN.php
Labels: master

#21349 NFC Clarify description for ckeditor4 plugin
  ext/ckeditor4/info.xml
Labels: master, merge on pass

#21202 Switch to CRM_Core_Form::setTitle() instead of CRM_Utils_System::setTitle() part 2
  CRM/Case/Form/ActivityToCase.php
  CRM/Case/Form/ActivityView.php
  CRM/Case/Form/Case.php
  CRM/Case/Form/CaseView.php
  CRM/Case/Form/CustomData.php
  CRM/Contact/Form/Contact.php
  CRM/Contact/Form/CustomData.php
  CRM/Contact/Form/Domain.php
  CRM/Contact/Form/Merge.php
  CRM/Contact/Form/RelatedContact.php
  CRM/Contact/Form/Relationship.php
  CRM/Contact/Form/Search.php
  CRM/Contact/Form/Task/AddToGroup.php
  CRM/Contact/Form/Task/AddToParentClass.php
  CRM/Contact/Form/Task/Batch.php
  CRM/Contact/Form/Task/Delete.php
  CRM/Contact/Form/Task/Email.php
  CRM/Contact/Form/Task/Label.php
  CRM/Contact/Form/Task/Map.php
  CRM/Contact/Form/Task/PDFLetterCommon.php
  CRM/Contact/Form/Task/PickProfile.php
  CRM/Contact/Form/Task/RemoveFromGroup.php
  CRM/Contact/Form/Task/Useradd.php
  CRM/Contribute/Form/AdditionalPayment.php
  CRM/Contribute/Form/CancelSubscription.php
  CRM/Contribute/Form/Contribution.php
  CRM/Contribute/Form/Contribution/ThankYou.php
  CRM/Contribute/Form/ContributionPage/Settings.php
  CRM/Contribute/Form/ContributionView.php
  CRM/Contribute/Form/Task/Batch.php
  CRM/Contribute/Form/Task/Invoice.php
  CRM/Contribute/Form/Task/PDF.php
  CRM/Contribute/Form/Task/PickProfile.php
  CRM/Contribute/Form/UpdateSubscription.php
Labels: master

#21352 Switch to CRM_Core_Form::setTitle() instead of CRM_Utils_System::setTitle() part 3
  CRM/Core/Form.php
  CRM/Core/Form/Task/Batch.php
  CRM/Core/Form/Task/PDFLetterCommon.php
  CRM/Core/Form/Task/PickProfile.php
  CRM/Core/I18n/Form.php
  CRM/Custom/Form/DeleteField.php
  CRM/Custom/Form/DeleteGroup.php
  CRM/Custom/Form/Field.php
  CRM/Custom/Form/Group.php
  CRM/Custom/Form/MoveField.php
  CRM/Event/Form/ParticipantFeeSelection.php
  CRM/Event/Form/ParticipantView.php
  CRM/Event/Form/Registration/AdditionalParticipant.php
  CRM/Event/Form/Registration/Confirm.php
  CRM/Event/Form/Registration/ThankYou.php
  CRM/Event/Form/Task/AddToGroup.php
  CRM/Event/Form/Task/Badge.php
  CRM/Event/Form/Task/Batch.php
  CRM/Event/Form/Task/Cancel.php
  CRM/Event/Form/Task/PickProfile.php
  CRM/Event/Form/Task/SaveSearch.php
  CRM/Financial/Form/BatchTransaction.php
  CRM/Financial/Form/FinancialBatch.php
  CRM/Financial/Form/FinancialTypeAccount.php
  CRM/Financial/Form/PaymentEdit.php
  CRM/Friend/Form.php
  CRM/Group/Form/Edit.php
  CRM/Mailing/Form/Approve.php
  CRM/Mailing/Form/ForwardMailing.php
  CRM/Mailing/Form/Optout.php
  CRM/Mailing/Form/Subscribe.php
  CRM/Mailing/Form/Unsubscribe.php
Labels: master, merge on pass

#21210 [REF] Deprecate 2 del() functions in favor of generics and hooks (dev/core#2757)
  CRM/Campaign/BAO/Survey.php
  CRM/Report/BAO/ReportInstance.php
Labels: master

#21318 activity import: prepend custom group title to custom fields
  CRM/Activity/Import/Parser/Activity.php
Labels: master

#21362 [REF] Fix form to call this->setTitle()
  CRM/Profile/Form/Edit.php
Labels: master, merge on pass

#21358 Remove deprecated function
  CRM/Contribute/BAO/ContributionRecur.php
Labels: master

#21360 Remove testing hack
  CRM/Contribute/Form/Task/PDFLetter.php
  CRM/Utils/PDF/Document.php
  tests/phpunit/CRM/Contribute/Form/Task/PDFLetterCommonTest.php
Labels: master

#21355 dev/core#2486 Add survey v4 api
  CRM/Campaign/DAO/Survey.php
  Civi/Api4/Survey.php
  tests/phpunit/api/v3/SyntaxConformanceTest.php
  xml/schema/Campaign/Survey.xml
Labels: master

#21359 [REF] dev/core#2790 Follow on on code move, make not static
  CRM/Member/Form/Task/PDFLetter.php
  tests/phpunit/CRM/Member/Form/Task/LabelTest.php
  tests/phpunit/CRM/Member/Form/Task/PDFLetterCommonTest.php
Labels: master

#21361 Remove deprecated function
  CRM/Core/BAO/MessageTemplate.php
Labels: master

#20985 dev/core#2715 [REF] Move another 2 functions to the financial processor class
  CRM/Contribute/BAO/Contribution.php
  CRM/Contribute/BAO/FinancialProcessor.php
Labels: master, merge ready

#21363 SearchKit - Add 'array' option to download API and add test
  ext/search_kit/Civi/Api4/Action/SearchDisplay/Download.php
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/SearchDownloadTest.php
Labels: master, has-test

#21301 Add SqlFunction support in addWhere
  Civi/Api4/Generic/DAOGetAction.php
  Civi/Api4/Query/Api4SelectQuery.php
  Civi/Api4/Query/SqlFunctionBINARY.php
  tests/phpunit/api/v4/Action/ContactGetTest.php
  tests/phpunit/api/v4/Action/FkJoinTest.php
  tests/phpunit/api/v4/Action/SqlFunctionTest.php
Labels: master, merge on pass, has-test

#21369 [NFC/Unit test] - Fix secondary issue with case token consistency test
  tests/phpunit/CRM/Utils/TokenConsistencyTest.php
Labels: master, merge on pass, has-test

#21157 dev/translation#71 getFullMonthNames: do not rely on the OS for translation
  CRM/Report/Form.php
  CRM/Utils/Date.php
Labels: master, merge on pass

#21371 Remove unused private function
  CRM/Mailing/BAO/Mailing.php
Labels: master, merge on pass

#21372 Remove deprecated input variable
  CRM/Mailing/BAO/Mailing.php
Labels: master

#21368 Switch to CRM_Core_Form::setTitle() instead of CRM_Utils_System::setTitle() part 4
  CRM/Member/Form/MembershipRenewal.php
  CRM/Member/Form/MembershipView.php
  CRM/Member/Form/Task/Batch.php
  CRM/Member/Form/Task/PickProfile.php
  CRM/PCP/Form/Campaign.php
  CRM/PCP/Form/Event.php
  CRM/PCP/Form/PCPAccount.php
  CRM/Pledge/Form/Payment.php
  CRM/Pledge/Form/PledgeView.php
  CRM/Price/Form/DeleteField.php
  CRM/Price/Form/Set.php
  CRM/Report/Form/Register.php
  CRM/UF/Form/Group.php
  CRM/Upgrade/Form.php
  tests/extensions/test.extension.manager.searchtest/main.php
Labels: master

#21375 Update use of CRM_Utils_System::setTitle() for legacycustomsearches
  ext/legacycustomsearches/CRM/Contact/Form/Search/Custom/ActivitySearch.php
  ext/legacycustomsearches/CRM/Contact/Form/Search/Custom/Base.php
  ext/legacycustomsearches/CRM/Contact/Form/Search/Custom/ContribSYBNT.php
  ext/legacycustomsearches/CRM/Contact/Form/Search/Custom/ContributionAggregate.php
  ext/legacycustomsearches/CRM/Contact/Form/Search/Custom/DateAdded.php
  ext/legacycustomsearches/CRM/Contact/Form/Search/Custom/EventAggregate.php
  ext/legacycustomsearches/CRM/Contact/Form/Search/Custom/FullText.php
  ext/legacycustomsearches/CRM/Contact/Form/Search/Custom/Group.php
  ext/legacycustomsearches/CRM/Contact/Form/Search/Custom/PriceSet.php
  ext/legacycustomsearches/CRM/Contact/Form/Search/Custom/Proximity.php
  ext/legacycustomsearches/CRM/Contact/Form/Search/Custom/RandomSegment.php
  ext/legacycustomsearches/CRM/Contact/Form/Search/Custom/Sample.php
  ext/legacycustomsearches/CRM/Contact/Form/Search/Custom/TagContributions.php
  ext/legacycustomsearches/CRM/Contact/Form/Search/Custom/ZipCodeRange.php
Labels: master

#21373 Fix test to test trait not deprecated function
  tests/phpunit/CRM/Contact/Form/Task/EmailCommonTest.php
Labels: master

#21335 [REF] dev/core#2790 dev/core#2814 Start migration to MessageTemplate::render
  CRM/Contact/Form/Task/PDFLetterCommon.php
  tests/phpunit/CRM/Contact/Form/Task/PDFLetterCommonTest.php
Labels: master

#21364 dev/core#2814 Fix profile edit to use messagetemplate:render
  CRM/Profile/Form/Edit.php
  tests/phpunit/CRM/Profile/Form/EditTest.php
Labels: master, has-test

#21367 dev/core#2814 migrate export processor to use MessageRender
  CRM/Export/BAO/ExportProcessor.php
  tests/phpunit/CRM/Export/BAO/ExportTest.php
Labels: master

#21365 dev/core#2814 Fix activity:sendEmail to use renderTemplate
  CRM/Activity/BAO/Activity.php
  tests/phpunit/CRM/Activity/BAO/ActivityTest.php
Labels: master, has-test

#21366 [REF] dev/core#2790 Move pdf getFileName functionality to the trait
  CRM/Activity/Form/Task/PDF.php
  CRM/Contact/Form/Task/PDFLetterCommon.php
  CRM/Contact/Form/Task/PDFTrait.php
  CRM/Contribute/Form/Task/PDFLetter.php
  CRM/Member/Form/Task/PDFLetter.php
  tests/phpunit/CRM/Utils/TokenTest.php
Labels: master

#21357 [REF] Extract code to get the from address for a recurring contribution.
  CRM/Contribute/BAO/ContributionRecur.php
  CRM/Contribute/Form/UpdateSubscription.php
  tests/phpunit/CRM/Contribute/Form/UpdateSubscriptionTest.php
Labels: master

#21376 SearchKit - enable tags for Saved Searches
  ext/search_kit/Civi/Api4/Action/SearchDisplay/AbstractRunAction.php
  ext/search_kit/Civi/Search/Admin.php
  ext/search_kit/ang/crmSearchAdmin.module.js
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdmin.component.js
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdminTags.component.js
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdminTags.html
  ext/search_kit/ang/crmSearchAdmin/searchListing/crmSearchAdminSearchListing.component.js
  ext/search_kit/ang/crmSearchAdmin/searchListing/crmSearchAdminSearchListing.html
  ext/search_kit/ang/crmSearchAdmin/searchListing/tags.html
  ext/search_kit/ang/crmSearchAdmin/tabs.html
  ext/search_kit/css/crmSearchAdmin.css
  ext/search_kit/managed/TagUsedFor.mgd.php
Labels: master, merge on pass

#21378 dev/core#2814 Fix test to use renderTemplate
  tests/phpunit/CRM/Contact/Form/Task/PrintDocumentTest.php
Labels: master, merge on pass

#21377 dev/core#2814 Fix activity:sendSMS to use renderTemplate
  CRM/Activity/BAO/Activity.php
  tests/phpunit/CRM/Activity/BAO/ActivityTest.php
  tests/phpunit/CiviTest/CiviTestSMSProvider.php
Labels: master, merge on pass, has-test

#21199 [REF] Cleanup BAO::del() functions with unnecessary FK checks (dev/core#2757)
  CRM/Contribute/BAO/Product.php
  CRM/Core/BAO/Tag.php
  CRM/Core/DAO.php
Labels: master

#21370 dev/core#2715 Move 2 more functions to financial processor class
  CRM/Contribute/BAO/Contribution.php
  CRM/Contribute/BAO/FinancialProcessor.php
Labels: master

#21175 Remove requirement to enter email address on unsubscribe
  CRM/Admin/Form/Preferences/Mailing.php
  CRM/Mailing/Form/Unsubscribe.php
  templates/CRM/Mailing/Form/Unsubscribe.tpl
Labels: master

#21288 dev/core#2793 - Add REGEXP/NOT REGEXP SQL operators
  Civi/Api4/Generic/Traits/ArrayQueryActionTrait.php
  Civi/Api4/Query/Api4SelectQuery.php
  Civi/Api4/Utils/CoreUtil.php
  ext/search_kit/Civi/Search/Admin.php
  tests/phpunit/api/v4/Action/BasicActionsTest.php
  tests/phpunit/api/v4/Action/ContactGetTest.php
  tests/phpunit/api/v4/Action/GetFromArrayTest.php
Labels: master, has-test

#21379 dev/core#2814 Fix membership pdf to use renderTemplate
  CRM/Member/Form/Task/PDFLetter.php
  CRM/Member/Form/Task/PDFLetterCommon.php
  tests/phpunit/CRM/Member/Form/Task/PDFLetterCommonTest.php
Labels: master, has-test

#21354 Change Do Not SMS privacy icon
  CRM/Core/Smarty/plugins/function.privacyFlag.php
Labels: master

#21385 dev/core#2814 Fix activity:sendEmail follow up
  CRM/Activity/BAO/Activity.php
Labels: master

#21382 Don't specify character set for civicrm_relationship_cache table
  CRM/Upgrade/Incremental/sql/5.29.alpha1.mysql.tpl
Labels: master

#21390 [NFC] Add in type hints to template upgrade functions
  CRM/Upgrade/Incremental/php/Template.php
Labels: master, merge on pass

#21386 [NFC] Extend send email test to cover for contact tokens being replaced
  tests/phpunit/CRM/Activity/BAO/ActivityTest.php
Labels: master, merge on pass

#21380 dev/core#2817 towards deprecating legacy `replaceCaseTokens`
  CRM/Core/SelectValues.php
  CRM/Utils/Token.php
  tests/phpunit/CRM/Utils/TokenConsistencyTest.php
Labels: master

#21389 [REF] Add in upgrade step to align the relationship cache table colla…
  CRM/Upgrade/Incremental/php/FiveFortyThree.php
  tests/phpunit/CRM/Upgrade/Incremental/BaseTest.php
Labels: master, has-test

#20822 [REF] Update Product Create to use hooks and also switch the manage p…
  CRM/Contribute/BAO/Product.php
  CRM/Contribute/Form/ManagePremiums.php
  CRM/Core/Permission.php
Labels: master

#21186 dev/core#2772 - Don't crash for custom fields of type int that are multi-select
  CRM/Core/BAO/CustomField.php
  CRM/Core/BAO/CustomValueTable.php
  tests/phpunit/CRM/Core/BAO/CustomValueTableTest.php
Labels: master, has-test

#20995 Import csv-Fix not importing extension in phones
  CRM/Contact/Import/Form/MapField.php
  CRM/Contact/Import/ImportJob.php
Labels: master, merge ready

#21395 dev/core#2823 Make protected functions non-static
  CRM/Core/ManagedEntities.php
Labels: master, merge on pass

#21396 Fix Upgrade step to ensure all fields are converted correctly as well
  CRM/Upgrade/Incremental/php/FiveFortyThree.php
Labels: merge on pass

#21398 [NFC] Put back email test without tokens and enhance a little
  tests/phpunit/CRM/Activity/BAO/ActivityTest.php
Labels: master, merge on pass

#21388 SearchKit - Filter search listing by creator
  ext/search_kit/Civi/Api4/Action/SearchDisplay/AbstractRunAction.php
  ext/search_kit/ang/crmSearchAdmin/searchListing/crmSearchAdminSearchListing.component.js
  ext/search_kit/ang/crmSearchAdmin/searchListing/crmSearchAdminSearchListing.html
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/SearchRunTest.php
Labels: master, has-test

#21394 SearchKit - Prevent race conditions in search display loading
  ext/search_kit/ang/crmSearchDisplay/traits/searchDisplayBaseTrait.service.js
Labels: master

#21381 dev/core#2817 Block submission of pdf with text including token format that is ambiguous with the processor
  CRM/Contact/Form/Task/EmailTrait.php
  CRM/Core/Form/Task/PDFLetterCommon.php
Labels: master, merge on pass

#21397 SearchKit - Support bootstrap styles in search display tables
  ext/search_kit/ang/crmSearchAdmin/displays/searchAdminDisplayTable.component.js
  ext/search_kit/ang/crmSearchAdmin/displays/searchAdminDisplayTable.html
  ext/search_kit/ang/crmSearchDisplayTable/crmSearchDisplayTable.html
Labels: master

#21348 dev/core#2812 Fix issue where having a processor configured with a se…
  CRM/Core/ClassLoader.php
Labels: 5.41

#21404 Fixes dev/core#2826 SearchKit - Fix delete search confirm dialog
  ext/search_kit/ang/crmSearchAdmin/searchListing/buttons.html
Labels: master

#21406 [search kit] Semicolon vs comma
  ext/search_kit/ang/crmSearchDisplay/traits/searchDisplayBaseTrait.service.js
Labels: master, merge on pass

#21405 SearchKit & Afform - Use Bootstrap table styles on admin screens
  ext/afform/admin/ang/afAdmin/afAdminList.html
  ext/search_kit/ang/crmSearchAdmin/resultsTable/crmSearchAdminResultsTable.component.js
  ext/search_kit/ang/crmSearchAdmin/resultsTable/crmSearchAdminResultsTable.html
  ext/search_kit/ang/crmSearchAdmin/searchListing/crmSearchAdminSearchListing.component.js
Labels: master

#21409 Remove duplicate global declaration in civicrm.settings.php template
  templates/CRM/common/civicrm.settings.php.template
Labels: master, merge on pass

#21410 Smarty warning about missing contact subtype on New Individual
  templates/CRM/Contact/Form/Edit/Individual.tpl
Labels: master, merge on pass

#21174 Mailing Unsubscribe Form: Show if email is already unsubscribed
  CRM/Mailing/Form/Unsubscribe.php
Labels: master, merge on pass

#21412 dev/core#2823 update function visibility to protected
  CRM/Core/ManagedEntities.php
Labels: master

#21059 dev/core#2748 Remove unused token assigns
  CRM/Contribute/BAO/Contribution.php
  CRM/Upgrade/Incremental/php/FiveFortyThree.php
  CRM/Utils/Token.php
  tests/phpunit/api/v3/ContributionTest.php
  tests/templates/message_templates/contribution_online_receipt_html.tpl
Labels: master, merge on pass

#21417 Follow up on removing contributeMode from templates
  CRM/Contribute/BAO/Contribution.php
Labels: master

#21421 Smarty notice on Find Activities / Find Cases
  templates/CRM/common/Tagset.tpl
Labels: master

#21418 [REF] Remove cruft
  Civi/Token/TokenCompatSubscriber.php
Labels: master

#21422 Smarty notices on Find Activities results page
  templates/CRM/Activity/Form/Selector.tpl
Labels: master, merge on pass

#21414 dev/core#2814 Remove redundant call to `replaceContactTokens`
  Civi/Token/TokenCompatSubscriber.php
Labels: master, merge on pass

#21425 Remove error handling for core error being returned
  Civi/Token/TokenCompatSubscriber.php
Labels: master, merge on pass

#21408 Bump minimum upgradable version to 4.5.9
  CRM/Core/EntityReference.php
  CRM/Upgrade/4.5.0.msg_template/civicrm_msg_template.tpl
  CRM/Upgrade/4.5.0.msg_template/message_templates/contribution_recurring_edit_html.tpl
  CRM/Upgrade/4.5.0.msg_template/message_templates/contribution_recurring_edit_text.tpl
  CRM/Upgrade/4.5.0.msg_template/message_templates/contribution_recurring_notify_html.tpl
  CRM/Upgrade/4.5.0.msg_template/message_templates/contribution_recurring_notify_text.tpl
  CRM/Upgrade/4.5.alpha1.msg_template/civicrm_msg_template.tpl
  CRM/Upgrade/4.5.alpha1.msg_template/message_templates/contribution_offline_receipt_html.tpl
  CRM/Upgrade/4.5.alpha1.msg_template/message_templates/contribution_offline_receipt_text.tpl
  CRM/Upgrade/4.5.alpha1.msg_template/message_templates/contribution_online_receipt_html.tpl
  CRM/Upgrade/4.5.alpha1.msg_template/message_templates/contribution_online_receipt_text.tpl
  CRM/Upgrade/4.5.alpha1.msg_template/message_templates/event_offline_receipt_html.tpl
  CRM/Upgrade/4.5.alpha1.msg_template/message_templates/event_offline_receipt_text.tpl
  CRM/Upgrade/4.5.alpha1.msg_template/message_templates/event_online_receipt_html.tpl
  CRM/Upgrade/4.5.alpha1.msg_template/message_templates/event_online_receipt_text.tpl
  CRM/Upgrade/4.5.alpha1.msg_template/message_templates/membership_online_receipt_html.tpl
  CRM/Upgrade/4.5.alpha1.msg_template/message_templates/membership_online_receipt_text.tpl
  CRM/Upgrade/4.5.alpha1.msg_template/message_templates/participant_cancelled_html.tpl
  CRM/Upgrade/4.5.alpha1.msg_template/message_templates/participant_cancelled_text.tpl
  CRM/Upgrade/4.5.alpha1.msg_template/message_templates/participant_confirm_html.tpl
  CRM/Upgrade/4.5.alpha1.msg_template/message_templates/participant_confirm_text.tpl
  CRM/Upgrade/4.5.alpha1.msg_template/message_templates/participant_expired_html.tpl
  CRM/Upgrade/4.5.alpha1.msg_template/message_templates/participant_expired_text.tpl
  CRM/Upgrade/4.5.alpha1.msg_template/message_templates/payment_or_refund_notification_html.tpl
  CRM/Upgrade/4.5.alpha1.msg_template/message_templates/payment_or_refund_notification_subject.tpl
  CRM/Upgrade/4.5.alpha1.msg_template/message_templates/payment_or_refund_notification_text.tpl
  CRM/Upgrade/4.5.alpha1.msg_template/message_templates/pledge_acknowledge_html.tpl
  CRM/Upgrade/4.5.alpha1.msg_template/message_templates/pledge_acknowledge_text.tpl
  CRM/Upgrade/4.5.beta2.msg_template/civicrm_msg_template.tpl
  CRM/Upgrade/4.5.beta2.msg_template/message_templates/membership_offline_receipt_html.tpl
  CRM/Upgrade/4.5.beta2.msg_template/message_templates/membership_offline_receipt_text.tpl
  CRM/Upgrade/4.5.beta2.msg_template/message_templates/sample/Sample Responsive Design Newsletter - Single Column.tpl
  CRM/Upgrade/4.5.beta2.msg_template/message_templates/sample/Sample Responsive Design Newsletter - Two Column.tpl
  CRM/Upgrade/Form.php
  CRM/Upgrade/Incremental/php/FourFive.php
  CRM/Upgrade/Incremental/sql/4.5.0.mysql.tpl
  CRM/Upgrade/Incremental/sql/4.5.1.mysql.tpl
  CRM/Upgrade/Incremental/sql/4.5.2.mysql.tpl
  CRM/Upgrade/Incremental/sql/4.5.3.mysql.tpl
  CRM/Upgrade/Incremental/sql/4.5.4.mysql.tpl
  CRM/Upgrade/Incremental/sql/4.5.5.mysql.tpl
  CRM/Upgrade/Incremental/sql/4.5.6.mysql.tpl
  CRM/Upgrade/Incremental/sql/4.5.7.mysql.tpl
  CRM/Upgrade/Incremental/sql/4.5.8.mysql.tpl
  CRM/Upgrade/Incremental/sql/4.5.9.mysql.tpl
  CRM/Upgrade/Incremental/sql/4.5.alpha1.mysql.tpl
  CRM/Upgrade/Incremental/sql/4.5.alpha2.mysql.tpl
  CRM/Upgrade/Incremental/sql/4.5.beta1.mysql.tpl
  CRM/Upgrade/Incremental/sql/4.5.beta2.mysql.tpl
  CRM/Upgrade/Incremental/sql/4.5.beta3.mysql.tpl
  CRM/Upgrade/Incremental/sql/4.5.beta4.mysql.tpl
  CRM/Upgrade/Incremental/sql/4.5.beta5.mysql.tpl
  CRM/Upgrade/Incremental/sql/4.5.beta6.mysql.tpl
  CRM/Upgrade/Incremental/sql/4.5.beta7.mysql.tpl
  CRM/Upgrade/Incremental/sql/4.5.beta8.mysql.tpl
  CRM/Upgrade/Incremental/sql/4.5.beta9.mysql.tpl
Labels: master, merge on pass

#21416 [REF] Extract function to getDomainTokens
  CRM/Utils/Token.php
  tests/phpunit/CRM/Core/BAO/MessageTemplateTest.php
Labels: master

#21198 [REF] Mapping - Check FK on delete with SQL instead of PHP (dev/core#2757)
  CRM/Core/BAO/Mapping.php
  CRM/Core/DAO/MappingField.php
  CRM/Upgrade/Incremental/php/FiveFortyThree.php
  xml/schema/Core/MappingField.xml
Labels: master, merge on pass

#21431 SearchKit - Fix alignment in table headers
  ext/search_kit/ang/crmSearchAdmin/resultsTable/crmSearchAdminResultsTable.html
  ext/search_kit/css/crmSearchTasks.css
Labels: master

#21424 SearchKit - Support custom fields in bridge join entities
  Civi/Api4/Query/Api4SelectQuery.php
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdmin.component.js
  tests/phpunit/api/v4/Action/BasicCustomFieldTest.php
Labels: master, has-test, comp:search-kit

#21211 [REF] Move Email, Address, etc. is_primary handling on delete to a hook (dev/core#2757)
  CRM/Contact/BAO/Contact.php
  CRM/Core/BAO/Address.php
  CRM/Core/BAO/Email.php
  CRM/Core/BAO/IM.php
  CRM/Core/BAO/OpenID.php
  CRM/Core/BAO/Phone.php
  CRM/Core/DAO.php
  tests/phpunit/api/v4/Entity/AddressTest.php
Labels: master, merge on pass, has-test

#21434 dev/core#2828 - Make up for message template text version update from 5.20 that never happened
  CRM/Upgrade/Incremental/MessageTemplates.php
Labels: master, merge on pass

#21400 dev/core#2823 Move validation into validation function
  CRM/Core/ManagedEntities.php
Labels: master

#21399 dev/core#2823 Extract code to load the declarations and call from the constructor
  CRM/Core/ManagedEntities.php
Labels: master

#21437 dev/core#2829 - unit test for nonempty dashboard
  tests/phpunit/CRM/Core/InvokeTest.php
Labels: master, has-test

#21440 dev/core#2823 fix test to be more like real function usage
  CRM/Core/ManagedEntities.php
  tests/phpunit/CRM/Core/ManagedEntitiesTest.php
Labels: master

#21428 TokenProcessor - Allow basic filter/modifier expressions
  Civi/Token/TokenProcessor.php
  tests/phpunit/Civi/Token/TokenProcessorTest.php
Labels: master, merge ready, has-test

#21443 Alternate to https://github.com/civicrm/civicrm-core/pull/21442
  CRM/Core/BAO/MessageTemplate.php
Labels: master

#21441 dev/core#2829 - "Trying to access array offset on value of type null" on dashboard
  Civi/Api4/Query/Api4SelectQuery.php
Labels: master, has-test

#21383 dev/core#2817 Add CaseToken processor
  CRM/Case/Tokens.php
  CRM/Contribute/RecurTokens.php
  CRM/Core/EntityTokens.php
  CRM/Core/SelectValues.php
  CRM/Upgrade/Incremental/php/FiveFortyThree.php
  CRM/Utils/Token.php
  Civi/Core/Container.php
  tests/phpunit/CRM/Contribute/ActionMapping/ByTypeTest.php
  tests/phpunit/CRM/Utils/TokenConsistencyTest.php
Labels: master, merge ready, has-test

#21429 Consolidate building of contact token list
  CRM/Core/SelectValues.php
  Civi/Token/TokenCompatSubscriber.php
  tests/phpunit/CRM/Core/BAO/MessageTemplateTest.php
Labels: master, has-test

#21427 Extend test cover on token fields
  CRM/Core/SelectValues.php
  tests/phpunit/CRM/Core/BAO/MessageTemplateTest.php
Labels: master, has-test

#20807 Wordpress Profile User Creation Sign On (v2)
  CRM/Utils/System/WordPress.php
Labels: master

#21401 dev/core#2823 Restructure determination of required actions.
  CRM/Core/ManagedEntities.php
Labels: master

#21453 dev/core#2832 Add test for legacy membership tokens, add support for preferred tokens
  CRM/Utils/Token.php
  tests/phpunit/CRM/Utils/TokenConsistencyTest.php
Labels: master, merge on pass

#21439 Authx: README: add note about CMS permissions
  ext/authx/README.md
Labels: master, merge ready

#21450 [REF] Extract code to load the contact in tokenCompat
  Civi/Token/TokenCompatSubscriber.php
Labels: master

#21451 [REF] Remove unused variable
  CRM/Member/Form/Task/PDFLetter.php
Labels: master

#21448 [REF] Remove unused parameter
  CRM/Utils/Token.php
Labels: master

#21438 APIv4 - Default select clause to exclude "Extra" fields
  Civi/Api4/Generic/AbstractGetAction.php
  Civi/Api4/Generic/DAOGetAction.php
  ext/afform/core/Civi/Api4/Action/Afform/Get.php
  ext/afform/core/Civi/Api4/Afform.php
  ext/afform/core/tests/phpunit/Civi/Afform/AfformGetTest.php
  ext/afform/mock/tests/phpunit/api/v4/AfformCustomFieldUsageTest.php
  ext/afform/mock/tests/phpunit/api/v4/AfformTest.php
  ext/oauth-client/Civi/Api4/OAuthProvider.php
  tests/phpunit/api/v4/Action/BasicActionsTest.php
  tests/phpunit/api/v4/Action/CurrentFilterTest.php
  tests/phpunit/api/v4/Mock/Api4/MockBasicEntity.php
Labels: master, merge on pass, has-test

#21456 dev/core#2835 - Activity export broken in 5.41
  CRM/Activity/Task.php
  tests/phpunit/CRM/Activity/Form/SearchTest.php
Labels: has-test, 5.42

#21444 SearchKit - Fix deleting search displays
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdmin.component.js
Labels: 5.42

#21460 5.42 to master
  CRM/Activity/Task.php
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdmin.component.js
  tests/phpunit/CRM/Activity/Form/SearchTest.php
Labels: master

#21452 dev/core#2832 Improvements to test on membership letter task
  tests/phpunit/CRM/Member/Form/Task/PDFLetterTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: master, has-test

#21436 Afform - gracefully handle missing html files
  ext/afform/core/Civi/Afform/AngularDependencyMapper.php
Labels: master

#21461 Ensure TokenSmary::render returns an array
  CRM/Core/TokenSmarty.php
Labels: master, merge on pass

#21459 [Ref] Remove no-longer-used variables
  CRM/Member/Form/Task/PDFLetter.php
Labels: master, merge on pass

#21042 [REF] Use OO when determining what to suggest for settings.php prefixes for drupal/backdrop views, instead of scattered "if cms =="
  CRM/Admin/Form/Setting/UF.php
  CRM/Utils/System/Backdrop.php
  CRM/Utils/System/Base.php
Labels: master, merge on pass

#21458 dev/core#2834 Preliminary test on badge
  CRM/Badge/BAO/Badge.php
  tests/phpunit/CRM/Core/BAO/CustomFieldTest.php
  tests/phpunit/CRM/Event/Form/Task/BadgeTest.php
  tests/phpunit/CRMTraits/Custom/CustomDataTrait.php
Labels: master, merge on pass, has-test

#21462 5.41 backport of 21456
  CRM/Activity/Task.php
  tests/phpunit/CRM/Activity/Form/SearchTest.php
Labels: merge on pass, 5.41

#21463 [Ref] Remove unnecessary pass-by-reference
  CRM/Core/BAO/PdfFormat.php
Labels: master, merge on pass

#21338 (dev/mail#83) Introduce WorkflowMessage APIs with CaseActivity example
  CRM/Core/Permission.php
  Civi/Api4/Action/ExampleData/Get.php
  Civi/Api4/Action/WorkflowMessage/GetTemplateFields.php
  Civi/Api4/Action/WorkflowMessage/Render.php
  Civi/Api4/ExampleData.php
  Civi/Api4/WorkflowMessage.php
  Civi/Test.php
  Civi/Test/ExampleDataInterface.php
  Civi/Test/ExampleDataLoader.php
  Civi/Test/WorkflowMessageTestTrait.php
  Civi/Token/TokenCompatSubscriber.php
  Civi/WorkflowMessage/GenericWorkflowMessage.php
  Civi/WorkflowMessage/GenericWorkflowMessage/Alex.ex.php
  Civi/WorkflowMessage/WorkflowMessage.php
  Civi/WorkflowMessage/WorkflowMessageExample.php
  tests/phpunit/CRM/Case/WorkflowMessage/CaseActivity.php
  tests/phpunit/CRM/Case/WorkflowMessage/CaseActivity/CaseAdhocExample.ex.php
  tests/phpunit/CRM/Case/WorkflowMessage/CaseActivity/CaseModelExample.ex.php
  tests/phpunit/CRM/Case/WorkflowMessage/CaseActivityTest.php
  tests/phpunit/CRM/Core/BAO/MessageTemplateTest.php
  tests/phpunit/api/v4/Entity/ExampleDataTest.php
  tests/phpunit/api/v4/Entity/WorkflowMessageTest.php
Labels: master, merge on pass

#21466 [Ref] Remove pass-by-reference
  CRM/Core/BAO/PdfFormat.php
Labels: master

#21465 [Ref] Cleanup on SelectValues::contributeTokens
  CRM/Core/EntityTokens.php
  CRM/Core/SelectValues.php
Labels: master

#21445 dev/core#2817 Use token processor to resolve caseTokens for pdfs
  CRM/Contact/Form/Task/PDFLetterCommon.php
  CRM/Core/EntityTokens.php
  tests/phpunit/CRM/Contact/Form/Task/PDFLetterCommonTest.php
Labels: master, merge on pass, has-test

#21468 flushCaches should respect permitCacheFlushMode
  CRM/Contact/BAO/GroupContactCache.php
Labels: master, merge on pass

#21464 dev/core#2650 dev/core#2832 add support & testing for preferred token format
  CRM/Member/Tokens.php
  tests/phpunit/CRM/Utils/TokenConsistencyTest.php
Labels: master, has-test

#21474 fixes core#2318: fix cancel button when sending an individual email
  CRM/Contact/Form/Task/EmailTrait.php
Labels: master, merge on pass

#21475 dev/core#2817 remove call to getTokenDetails
  CRM/Contact/Form/Task/PDFLetterCommon.php
Labels: master, merge on pass

#21477 dev/core#2650 upgrade membership tokens to the new format
  CRM/Core/Form/Task/PDFLetterCommon.php
  CRM/Core/SelectValues.php
  CRM/Member/Tokens.php
  CRM/Upgrade/Incremental/php/FiveFortyThree.php
  tests/phpunit/CRM/Utils/TokenConsistencyTest.php
Labels: master

#21480 (dev/mail#83) ExampleDataLoader - Multiple fixes for quirky examples
  Civi/Test/ExampleDataLoader.php
  tests/phpunit/CRM/Case/WorkflowMessage/CaseActivity/CaseAdhocExample.ex.php
  tests/phpunit/CRM/Case/WorkflowMessage/CaseActivity/CaseModelExample.ex.php
Labels: master, merge on pass, has-test

#21481 [REF] simplify member_tokens
  CRM/Member/Tokens.php
  tests/phpunit/CRM/Utils/TokenConsistencyTest.php
Labels: master, has-test

#21420 SearchKit - Fix display of links in aggregated columns
  ext/search_kit/Civi/Api4/Action/SearchDisplay/AbstractRunAction.php
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdmin.component.js
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdminDisplay.component.js
  ext/search_kit/ang/crmSearchAdmin/crmSearchFunction.component.js
  ext/search_kit/ang/crmSearchAdmin/displays/colType/field.html
  ext/search_kit/ang/crmSearchAdmin/resultsTable/crmSearchAdminResultsTable.component.js
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/SearchAfformTest.php
Labels: master

#21482 SearchKit - Fix links to non-aggregage join fields
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdmin.component.js
Labels: master, merge on pass

#21486 (dev/mail#83) EntityTokens - Allow using mocked data
  CRM/Core/EntityTokens.php
  tests/phpunit/Civi/Token/TokenProcessorTest.php
Labels: master, merge on pass, has-test

#21447 dev/core#2817 Remove last core calls to `replaceCaseTokens`
  CRM/Activity/BAO/Activity.php
  CRM/Utils/Token.php
  tests/phpunit/CRM/Activity/BAO/ActivityTest.php
  tests/phpunit/CRM/Contact/Form/Task/EmailCommonTest.php
Labels: master, has-test

#21478 dev/core#2790 Move pdf postProcess function to the trait
  CRM/Case/Form/Task/PDF.php
  CRM/Contact/Form/Task/PDF.php
  CRM/Contact/Form/Task/PDFLetterCommon.php
  CRM/Contact/Form/Task/PDFTrait.php
  CRM/Contribute/Form/Task/PDFLetter.php
  CRM/Event/Form/Task/PDF.php
  CRM/Member/Form/Task/PDFLetter.php
Labels: master

#21487 [NFC] Fix Fatal error on php 8 due to mis matched function declaration
  tests/phpunit/CRM/Contact/Import/Form/MapFieldTest.php
Labels: master, merge on pass

#21488 SearchKit - Fix search display pager when using default pager settings
  ext/search_kit/Civi/Api4/Action/SearchDisplay/Run.php
Labels: sig:regression, 5.42

#21347 dev/core#2812 Fix issue where having a processor configured with a se…
  CRM/Core/ClassLoader.php
Labels: 5.42

#21491 5.42 to master
  CRM/Core/ClassLoader.php
  ext/search_kit/Civi/Api4/Action/SearchDisplay/Run.php
Labels: master

#21435 SearchKit - Add pseudo-fields for row number and current user
  ext/search_kit/Civi/Api4/Action/SearchDisplay/AbstractRunAction.php
  ext/search_kit/Civi/Search/Admin.php
  ext/search_kit/ang/crmSearchAdmin.module.js
  ext/search_kit/ang/crmSearchAdmin/compose.html
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdmin.component.js
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdminTokenSelect.component.js
  ext/search_kit/ang/crmSearchAdmin/displays/searchAdminDisplayTable.component.js
  ext/search_kit/ang/crmSearchAdmin/resultsTable/crmSearchAdminResultsTable.component.js
  ext/search_kit/ang/crmSearchAdmin/resultsTable/crmSearchAdminResultsTable.html
  ext/search_kit/ang/crmSearchDisplay/traits/searchDisplaySortableTrait.service.js
  ext/search_kit/ang/crmSearchDisplayTable/crmSearchDisplayTable.html
Labels: master

#21485 SearchKit - Correctly process filters passed through Afform from js
  ext/search_kit/Civi/Api4/Action/SearchDisplay/AbstractRunAction.php
Labels: master

#21449 dev/core#2814 TokenCompatSubscriber - Evaluate tokens during "civi.token.eval" phase
  CRM/Core/BAO/ActionSchedule.php
  Civi/Token/TokenCompatSubscriber.php
  tests/phpunit/CRM/Core/BAO/MessageTemplateTest.php
Labels: master, has-test

#21492 Fixes dev/core#2840 bug in recent items sidebar/menu
  CRM/Utils/Recent.php
  tests/phpunit/api/v4/Action/RecentItemsTest.php
Labels: merge on pass, has-test, sig:regression, 5.42

#21496 5.42 to master
  CRM/Utils/Recent.php
  tests/phpunit/api/v4/Action/RecentItemsTest.php
Labels: master

#21499 Revert "dev/core#2812 Fix issue where having a processor configured w…
  CRM/Core/ClassLoader.php
Labels: master, merge on pass

#21498 [NFC] [test] minor cleanup in test
  tests/phpunit/CRM/Core/Payment/AuthorizeNetIPNTest.php
  tests/phpunit/CRMTraits/Financial/OrderTrait.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: master, merge on pass

#21500 dev/core#2486 Add printLabel v4 api
  Civi/Api4/PrintLabel.php
Labels: master
