Repository civicrm/civicrm-core, pull requests merged in 2021-05, with the labels that each got.

#20200 fix capitalization to allow proper access to 'access AJAX API' perm.
  CRM/Api4/Permission.php
  CRM/Core/Permission.php
Labels: master

#20198 [NFC] Release Notes 5.37
  contributor-key.yml
  release-notes/5.37.0.md
Labels: 5.37

#20201 5.37 to master
  contributor-key.yml
  release-notes/5.37.0.md
Labels: master

#20195 dev/core#2577 Fix regression - payment edit to new type failing
  CRM/Financial/Form/PaymentEdit.php
Labels: 5.37

#20186 SearchKit - Pass-thu permission checks from SearchDisplay::run to api.get
  ext/search/Civi/Api4/Action/SearchDisplay/Run.php
  ext/search/Civi/Api4/SearchDisplay.php
  ext/search/tests/phpunit/api/v4/SearchDisplay/SearchRunTest.php
  tests/phpunit/CRMTraits/ACL/PermissionTrait.php
Labels: 5.37, has-test, merge on pass

#20207 5.37
  CRM/Financial/Form/PaymentEdit.php
  ext/search_kit/Civi/Api4/Action/SearchDisplay/Run.php
  ext/search_kit/Civi/Api4/SearchDisplay.php
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/SearchRunTest.php
  tests/phpunit/CRMTraits/ACL/PermissionTrait.php
Labels: master

#20202 5.37
  CRM/Financial/Form/PaymentEdit.php
  ext/search_kit/Civi/Api4/Action/SearchDisplay/Run.php
  ext/search_kit/Civi/Api4/SearchDisplay.php
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/SearchRunTest.php
  tests/phpunit/CRMTraits/ACL/PermissionTrait.php
Labels: master

#20203 dev/core#2582 Fix PCP and Pledge template urls in message templates t…
  CRM/Upgrade/Incremental/MessageTemplates.php
  xml/templates/message_templates/pcp_notify_html.tpl
  xml/templates/message_templates/pcp_notify_text.tpl
  xml/templates/message_templates/pledge_reminder_html.tpl
  xml/templates/message_templates/pledge_reminder_text.tpl
Labels: master

#20153 [REF] Cleanup interaction with membership & membership id
  CRM/Member/Form/Membership.php
Labels: master

#20212 dev/core#2583 - Fix fatal error on membership renewal
  CRM/Member/Form/MembershipRenewal.php
Labels: 5.37, merge on pass

#20213 5.37 to master
  CRM/Member/Form/MembershipRenewal.php
Labels: master

#20156 SearchKit - Exclude serialized fields from implicit join selection
  ext/search_kit/Civi/Search/Admin.php
Labels: master

#20188 dev/core#2568 Enotice fix + test
  CRM/Contribute/BAO/Contribution.php
  CRM/Contribute/Form/Task.php
  CRM/Contribute/Form/Task/PDFLetter.php
  CRM/Contribute/Form/Task/Status.php
  tests/phpunit/CRM/Contribute/Form/Task/PDFLetterCommonTest.php
  tests/phpunit/CRM/Contribute/Form/Task/StatusTest.php
Labels: master

#20123 Fixed dev/core#2505 fix formatting of numbers in civireport
  CRM/Core/BAO/CustomField.php
  CRM/Utils/Number.php
  tests/phpunit/CRM/Core/BAO/CustomQueryTest.php
Labels: has-test, master, merge ready

#20063 Fix PayPal IPN URL and WordPress URLs when Permalinks are set to "Plain"
  CRM/Core/Payment.php
  CRM/Utils/System.php
  CRM/Utils/System/Base.php
  CRM/Utils/System/WordPress.php
Labels: master, merge ready

#20215 Set html type of campaign fields
  CRM/Activity/DAO/Activity.php
  CRM/Campaign/DAO/CampaignGroup.php
  CRM/Campaign/DAO/Survey.php
  CRM/Contribute/DAO/Contribution.php
  CRM/Contribute/DAO/ContributionPage.php
  CRM/Contribute/DAO/ContributionRecur.php
  CRM/Event/DAO/Participant.php
  CRM/Mailing/DAO/Mailing.php
  CRM/Member/DAO/Membership.php
  CRM/Pledge/DAO/Pledge.php
  xml/schema/Activity/Activity.xml
  xml/schema/Campaign/CampaignGroup.xml
  xml/schema/Campaign/Survey.xml
  xml/schema/Contribute/Contribution.xml
  xml/schema/Contribute/ContributionPage.xml
  xml/schema/Contribute/ContributionRecur.xml
  xml/schema/Event/Participant.xml
  xml/schema/Mailing/Mailing.xml
  xml/schema/Member/Membership.xml
  xml/schema/Pledge/Pledge.xml
Labels: master

#20191 APIv4 - Setting api misc fixes & tests
  CRM/Core/BAO/Setting.php
  CRM/Core/SelectValues.php
  Civi/Api4/Action/Setting/AbstractSettingAction.php
  Civi/Api4/Action/Setting/Get.php
  Civi/Api4/Action/Setting/GetFields.php
  Civi/Api4/Generic/BasicGetFieldsAction.php
  Civi/Core/SettingsMetadata.php
  api/api.php
  tests/phpunit/api/v3/SettingTest.php
  tests/phpunit/api/v4/Entity/SettingTest.php
Labels: has-test, master

#20146 Fix enotice when Log service is swapped out
  CRM/Core/Error/Log.php
  Civi/API/LogObserver.php
Labels: master, merge on pass

#20218 REF Update Pear/log to fix issues with install CiviCRM on Drupal 9.2
  composer.json
  composer.lock
Labels: master, merge on pass

#20150 allow event transfer on backend when self-service transfer is disabled
  CRM/Event/BAO/Participant.php
  tests/phpunit/CRM/Event/BAO/ParticipantTest.php
Labels: has-test, master, merge ready

#20223 allow event transfer on backend when self-service transfer is disabled
  CRM/Event/BAO/Participant.php
  tests/phpunit/CRM/Event/BAO/ParticipantTest.php
Labels: 5.37, merge on pass

#20224 Set the smarty variables for mem_status and mem_join_date for back-end membership renewals
  CRM/Member/Form/MembershipRenewal.php
Labels: master

#20199 dev/core#2571: Add form function of utils/Recaptcha has been altered to avoid checking variable "isCaptcha"
  CRM/Contribute/Form/Contribution/Main.php
  ext/recaptcha/CRM/Utils/ReCAPTCHA.php
Labels: master

#20230 5.37.0 release notes: added late changes
  release-notes/5.37.0.md
Labels: 5.37

#20221 Api4 Services - Lazy-load subscriber-objects
  CRM/Api4/Services.php
  Civi/Core/CiviEventDispatcher.php
  Civi/Core/Event/ServiceListener.php
  tests/phpunit/Civi/Core/Event/ServiceListenerTest.php
Labels: has-test, master, merge ready

#20222 dev/core#2588 - Crash when sending to 3+ email recipients with an attachment in 5.36+
  CRM/Activity/BAO/Activity.php
Labels: 5.37

#20227 dev/core#2588 - failing test for PR 20222
  tests/phpunit/CRM/Activity/BAO/ActivityTest.php
Labels: 5.37

#20228 Afform - Set default position for contact layout editor
  ext/afform/core/afform.php
Labels: master

#20232 Merge forward (5.37 => master)
  CRM/Activity/BAO/Activity.php
  release-notes/5.37.0.md
  tests/phpunit/CRM/Activity/BAO/ActivityTest.php
Labels: master

#20225 dev/core#2586 fix failure to null thank you
  CRM/Contribute/Form/AdditionalInfo.php
  tests/phpunit/CRM/Contribute/Form/ContributionTest.php
Labels: 5.37, merge on pass

#20235 (5.37 merge into master) dev/core#2586 fix failure to null thank you
  CRM/Contribute/Form/AdditionalInfo.php
  tests/phpunit/CRM/Contribute/Form/ContributionTest.php
Labels: master, merge on pass

#20125 SearchKit - Fix updating Entity Ref fields
  Civi/Api4/Generic/Traits/DAOActionTrait.php
  ext/search_kit/ang/crmSearchActions/crmSearchActionUpdate.ctrl.js
  tests/phpunit/api/v4/Action/CustomContactRefTest.php
  tests/phpunit/api/v4/UnitTestCase.php
Labels: has-test, master

#20233 Extract sales tax test config to a trait
  tests/phpunit/CRMTraits/Financial/TaxTrait.php
  tests/phpunit/api/v3/ContributionTest.php
Labels: master

#20237 [NFC] code cleanups in test class
  CRM/Contribute/Exception/CheckLineItemsException.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/api/v3/OrderTest.php
Labels: master, merge on pass

#20240 [NFC] Code cleanup, docblocks, strict comparison, type hints
  CRM/Admin/Form/ScheduleReminders.php
Labels: master

#20145 Afform - Fix loading entities from url args
  ext/afform/core/ang/af/afForm.component.js
  ext/afform/core/ang/afCore.ang.php
Labels: master

#20244 dev/core#2593 [REF] Stop passing membership id into recur notify
  CRM/Contribute/BAO/ContributionPage.php
  CRM/Contribute/BAO/ContributionRecur.php
  CRM/Core/Payment/AuthorizeNetIPN.php
  CRM/Core/Payment/PayPalIPN.php
  CRM/Core/Payment/PayPalProIPN.php
Labels: master, merge on pass

#20245 dev/core#2575 remove / improve indexes
  CRM/Core/DAO/EntityFile.php
  CRM/Financial/DAO/FinancialType.php
  CRM/Price/DAO/LineItem.php
  xml/schema/Core/EntityFile.xml
  xml/schema/Financial/FinancialType.xml
  xml/schema/Price/LineItem.xml
Labels: master, merge on pass

#20152 Globally reset angular hashPrefix
  Civi/Angular/AngularLoader.php
  Civi/Angular/Page/Modules.php
  ang/crmApp.js
  ang/resetLocationProviderHashPrefix.js
Labels: master

#20144 hook_managed - do not try to disable managed entities if is_active is not available to api3.create
  CRM/Core/ManagedEntities.php
Labels: master, merge on pass, merge ready

#20248 Improve cleanup on contact test
  tests/phpunit/api/v3/ContactTest.php
Labels: master, merge on pass

#20250 Test fix - assertion fails when run with other tests (sometimes)
  tests/phpunit/api/v3/ContributionTest.php
Labels: master

#20121 Switch l10n.js from ajax callback to assetBuilder
  CRM/Admin/Form/Preferences.php
  CRM/Admin/Form/PreferencesDate.php
  CRM/Core/Config.php
  CRM/Core/Resources.php
  CRM/Core/Resources/Common.php
  CRM/Core/xml/Menu/Misc.xml
  Civi/Core/Container.php
  templates/CRM/common/l10n.js.tpl
Labels: master

#20255 dev/core#2602 - Installer doesn't check mysql version properly
  install/index.php
Labels: master

#20253 [Test] Improve cleanup of domain contacts
  tests/phpunit/CRM/Core/BAO/ActionScheduleTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/api/v3/ContactTest.php
  tests/phpunit/api/v3/ContributionTest.php
  tests/phpunit/api/v3/DomainTest.php
  tests/phpunit/api/v3/EntityBatchTest.php
Labels: master

#20242 [REF] Extract code determining list of groups requiring a refresh
  CRM/Contact/BAO/GroupContactCache.php
Labels: master

#20257 [NFC] Test - fix to use v3 api on postAsserts
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/api/v3/ACLCachingTest.php
  tests/phpunit/api/v3/DomainTest.php
Labels: master, merge on pass

#20262 Fix missing parent tearDown
  tests/phpunit/api/v3/EventTest.php
Labels: master

#20261 fix missing parent tearDown
  tests/phpunit/api/v3/CustomValueTest.php
Labels: master

#20254 Make APIv4 Subscribers Public to fix D9 install
  CRM/Api4/Services.php
Labels: 5.38

#20256 dev/core#2601 fix joomla permission regression
  CRM/Core/Permission/Base.php
  CRM/Utils/Hook.php
Labels: 5.38

#20266 5.38
  CRM/Api4/Services.php
  CRM/Core/Permission/Base.php
  CRM/Utils/Hook.php
Labels: master

#20267 dev/core#2601 fix joomla permission regression
  CRM/Core/Permission/Base.php
  CRM/Utils/Hook.php
Labels: 5.37, merge on pass

#20204 Freeze readonly fields
  CRM/Admin/Form/Generic.php
  CRM/Admin/Form/Setting.php
  CRM/Admin/Form/SettingTrait.php
Labels: master, merge ready

#20272 5.37.1 - Version bump. Add notes.
  release-notes.md
  release-notes/5.37.1.md
  sql/civicrm_generated.mysql
  sql/test_data_second_domain.mysql
  xml/version.xml
Labels: 5.37

#20258 [NFC] Test - Improve tearDown cleanup of domain contacts
  CRM/Contact/Form/Search/Custom/Group.php
  CRM/Core/BAO/ActionSchedule.php
  tests/phpunit/CRM/Contact/Form/Search/Custom/GroupTest.php
  tests/phpunit/CRM/Contact/Form/Search/Custom/GroupTestDataProvider.php
  tests/phpunit/CRM/Contact/Form/Search/Custom/SampleTest.php
  tests/phpunit/CRM/Contact/Form/Search/Custom/datasets/group-dataset.xml
  tests/phpunit/CRM/Contact/Form/Search/Custom/datasets/sample-dataset.xml
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: master, merge on pass

#20271 (REF) dev/core#2601 - Cleanup stale parameter
  CRM/Core/Permission.php
Labels: master

#20263 Afform - Drag & drop fixes
  ext/afform/admin/ang/afGuiEditor.js
  ext/afform/admin/ang/afGuiEditor/afGuiEditor.component.js
Labels: master

#20270 dev/core#2590 - Remove unused function CRM_Utils_File::relativeDirectory
  CRM/Utils/File.php
Labels: master

#20275 dev/core#2606 - Typo in rowCount variable in pager
  CRM/Utils/Pager.php
Labels: master

#20277 Fix money formatting opps
  CRM/Core/Payment.php
  CRM/Utils/Money.php
Labels: 5.38

#20208 [REF] Move ACLPermission Trait into Civi Folder so that it can be acc…
  Civi/Test/ACLPermissionTrait.php
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/SearchRunTest.php
  tests/phpunit/CRM/Core/Permission/BaseTest.php
  tests/phpunit/CRM/Event/BAO/EventPermissionsTest.php
  tests/phpunit/api/v3/ACLPermissionTest.php
  tests/phpunit/api/v3/EntityTagACLTest.php
  tests/phpunit/api/v3/ReportTemplateTest.php
Labels: master

#20276 Typo when retrieving help_pre textarea attributes for price field
  CRM/Price/Form/Field.php
Labels: master

#20280 5.38
  CRM/Core/Payment.php
  CRM/Utils/Money.php
Labels: master

#20279 Fix money formatting opps
  CRM/Core/Payment.php
  CRM/Utils/Money.php
Labels: 5.37, merge on pass

#20282 Version 5.37.2 - Add notes. Bump ver.
  release-notes.md
  release-notes/5.37.2.md
  sql/civicrm_generated.mysql
  sql/test_data_second_domain.mysql
  xml/version.xml
Labels: 5.37

#20283 Afform - hide disabled contact types & entities from disabled components/extensions
  ext/afform/admin/Civi/AfformAdmin/AfformAdminMeta.php
  ext/afform/admin/afformEntities/Activity.php
  ext/afform/admin/afformEntities/Household.php
  ext/afform/admin/afformEntities/Individual.php
  ext/afform/admin/afformEntities/Organization.php
Labels: master

#20264 Afform - Fix saving joined entities (email, address, phone, etc)
  ext/afform/core/Civi/Api4/Action/Afform/AbstractProcessor.php
  ext/afform/core/Civi/Api4/Action/Afform/Submit.php
Labels: 5.38

#20284 5.38
  ext/afform/core/Civi/Api4/Action/Afform/AbstractProcessor.php
  ext/afform/core/Civi/Api4/Action/Afform/Submit.php
Labels: master

#20259 Change the help text for Message Templates and Scheduled Reminders to include link to CiviCRM Token Documentation page
  templates/CRM/Admin/Form/MessageTemplates.tpl
  templates/CRM/Contact/Form/Task/Email.hlp
Labels: master, merge ready

#20077 Use order api when creating a recurring membership from the Membershi…
  CRM/Member/BAO/Membership.php
  CRM/Member/Form.php
  CRM/Member/Form/Membership.php
  api/v3/Order.php
  tests/phpunit/CRM/Member/Form/MembershipTest.php
Labels: master

#20286 5.38.0 release notes initial run
  release-notes.md
  release-notes/5.38.0.md
Labels: 5.38

#20289 5.37.{1|2} release notes
  release-notes.md
  release-notes/5.37.1.md
  release-notes/5.37.2.md
Labels: 5.38

#20246 dev/core#2593 [REF] Fix function signature to actually-used variables
  CRM/Contribute/BAO/Contribution.php
  CRM/Core/Payment/AuthorizeNetIPN.php
  CRM/Core/Payment/BaseIPN.php
  CRM/Core/Payment/PayPalIPN.php
  CRM/Core/Payment/PayPalProIPN.php
  CRM/Event/Form/Task/Batch.php
  api/v3/Contribution.php
Labels: master

#20290 5.38
  release-notes.md
  release-notes/5.37.1.md
  release-notes/5.37.2.md
  release-notes/5.38.0.md
Labels: master

#20288 [NFC/TEST] - Add unit test enforcing automatic chaining for financial type/account creation via api
  tests/phpunit/api/v3/FinancialTypeTest.php
Labels: has-test, master

#20287 Switch to non deprecated buildPermissionClause() for contact summary report
  CRM/Report/Form/Contact/Summary.php
Labels: master

#20295 [REF] Duplicate processMembership preliminary to cleanup
  CRM/Batch/Form/Entry.php
Labels: master, merge on pass

#20293 [REF] Use function to getContributionRecurID
  CRM/Core/Payment/PayPalIPN.php
Labels: master, merge on pass

#20299 Remove now-unused ids parameter from signature
  CRM/Core/Payment/PayPalIPN.php
Labels: master, merge on pass

#20216 Afform Gui - Add support for entityRef fields
  Civi/Api4/Generic/BasicGetFieldsAction.php
  Civi/Api4/Service/Spec/Provider/ActivitySpecProvider.php
  Civi/Api4/Service/Spec/SpecFormatter.php
  ext/afform/admin/Civi/AfformAdmin/AfformAdminMeta.php
  ext/afform/admin/afformEntities/Activity.php
  ext/afform/admin/ang/afGuiEditor.css
  ext/afform/admin/ang/afGuiEditor/afGuiEditor.component.js
  ext/afform/admin/ang/afGuiEditor/afGuiFieldValue.directive.js
  ext/afform/admin/ang/afGuiEditor/elements/afGuiButton.html
  ext/afform/admin/ang/afGuiEditor/elements/afGuiField-menu.html
  ext/afform/admin/ang/afGuiEditor/elements/afGuiField.component.js
  ext/afform/admin/ang/afGuiEditor/inputType/EntityRef.html
  ext/afform/core/Civi/Afform/AfformMetadataInjector.php
  ext/afform/core/ang/af/afField.component.js
  ext/afform/core/ang/af/fields/EntityRef.html
Labels: master

#20139 Remove defunct default return property
  CRM/Contact/BAO/Query.php
Labels: master

#20082 Add warning when url_site is not specified for paypal (it won't work if not set)
  CRM/Core/Payment/PayPalImpl.php
Labels: master, merge on pass

#20311 dev/core#2614 - Sample payment processor is the wrong id in the generated sample data for demos
  sql/civicrm_dummy_processor.mysql
  sql/civicrm_generated.mysql
Labels: master

#20304 Remove never-passed parameter from now unshared function
  CRM/Contribute/Form/Contribution/Confirm.php
  CRM/Member/BAO/Membership.php
Labels: master

#20312 Improve Sample data by ensuring all Credit Card Contributions have a …
  CRM/Core/CodeGen/GenerateData.php
  sql/civicrm_dummy_processor.mysql
  sql/civicrm_generated.mysql
Labels: master, merge on pass

#20205 Remove deprecation of order-must-be-pending
  api/v3/Order.php
Labels: master

#20211 [REF] Reverse if statement
  CRM/Contribute/Page/Tab.php
Labels: master

#20294 [REF] Provide standardised methods to get recurring contribution id & object
  CRM/Core/Payment/PayPalProIPN.php
Labels: master

#20300 dev/core#2593 stop calling loadRelatedObjects / fix for bug
  CRM/Core/Payment/PayPalIPN.php
Labels: master

#20209 Do not error on view contribution recur if not displaying contributions
  CRM/Contribute/Page/ContributionRecur.php
  templates/CRM/Contribute/Page/ContributionRecur.tpl
Labels: master

#20314 Switch to non deprecated buildPermissionClause() for contact detail report
  CRM/Report/Form/Contact/Detail.php
Labels: master

#20214 Separates the default language for contacts from the site language
  CRM/Admin/Form/Setting/Localization.php
  CRM/Contact/Form/Edit/CommunicationPreferences.php
  CRM/Contact/Form/Inline/CommunicationPreferences.php
Labels: master, merge ready

#20229 Activate user when no activation is required
  CRM/Utils/System/Drupal8.php
Labels: master

#20081 authx - Accept API keys by default
  ext/authx/settings/authx.setting.php
Labels: master

#20310 Cleanup tracking on group.load
  CRM/Contact/BAO/GroupContactCache.php
  tests/phpunit/CRM/Contact/BAO/GroupContactCacheTest.php
  tests/phpunit/CRM/Contact/BAO/GroupTest.php
  tests/phpunit/CRM/Contact/BAO/QueryTest.php
  tests/phpunit/CRM/Group/Page/AjaxTest.php
  tests/phpunit/CRM/Mailing/BAO/MailingTest.php
Labels: master, merge on pass

#20302 (dev/release#17) Extension UI - Show developmental icon for alpha/beta-stage extensions
  css/admin.css
  templates/CRM/Admin/Page/Extensions/AddNew.tpl
  templates/CRM/Admin/Page/Extensions/Main.tpl
Labels: master, merge on pass

#20317 [REF] Fully remove ids variable from paypal std
  CRM/Core/Payment/PayPalIPN.php
Labels: master

#20281 Afform drag n drop fixes
  ext/afform/admin/ang/afGuiEditor.css
  ext/afform/admin/ang/afGuiEditor.js
  ext/afform/admin/ang/afGuiEditor/afGuiEditor.component.js
  ext/afform/admin/ang/afGuiEditor/afGuiEditorCanvas.html
  ext/afform/admin/ang/afGuiEditor/afGuiEditorPalette.html
  ext/afform/admin/ang/afGuiEditor/afGuiEntity.html
  ext/afform/admin/ang/afGuiEditor/afGuiSearch.html
  ext/afform/admin/ang/afGuiEditor/elements/afGuiContainer.component.js
Labels: master

#20316 [REF] Switch to using getContributionRecurID function, remove now unused param
  CRM/Core/Payment/PayPalProIPN.php
Labels: master

#19840 Explicitly throw an error/status bounce on Edit/New if no types.
  CRM/Member/Page/Tab.php
Labels: master

#20320 Add unit test for #20144
  tests/phpunit/CRM/Core/ManagedEntitiesTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: master, merge on pass

#20313 [REF] Duplicate & deprecate processMembership
  CRM/Contribute/Form/Contribution/Confirm.php
  CRM/Member/BAO/Membership.php
  tests/phpunit/CRM/Member/BAO/MembershipTest.php
Labels: master

#20273 [REF] Make use of recently added default pager size setting in Reports
  CRM/Report/Form.php
  CRM/Report/Form/ActivitySummary.php
  CRM/Report/Form/Contact/Detail.php
  CRM/Report/Form/Contribute/DeferredRevenue.php
  CRM/Report/Form/Contribute/History.php
  CRM/Report/Form/Contribute/TopDonor.php
  CRM/Report/Form/Event/Income.php
Labels: master

#20269 APIv4 - Save custom fields in bulk
  CRM/Core/BAO/CustomField.php
  CRM/Core/DAO.php
  Civi/Api4/Generic/DAODeleteAction.php
  Civi/Api4/Generic/Traits/DAOActionTrait.php
Labels: master

#20303 dev/release#17 - Synchronize version#s for core and core-extensions
  distmaker/core-ext.txt
  distmaker/dists/common.sh
  ext/afform/admin/info.xml
  ext/afform/core/info.xml
  ext/afform/html/info.xml
  ext/afform/mock/info.xml
  ext/authx/info.xml
  ext/contributioncancelactions/info.xml
  ext/eventcart/info.xml
  ext/ewaysingle/info.xml
  ext/financialacls/info.xml
  ext/flexmailer/info.xml
  ext/greenwich/info.xml
  ext/oauth-client/info.xml
  ext/payflowpro/info.xml
  ext/recaptcha/info.xml
  ext/search_kit/info.xml
  ext/sequentialcreditnotes/info.xml
  tools/bin/scripts/set-version.php
Labels: master

#20309 get county fields populated via api call
  api/v3/Profile.php
Labels: master

#20322 Convert AuthorizeNet to doPayment()
  CRM/Core/Payment/AuthorizeNet.php
Labels: has-test, master

#20329 Correct copy-paste error in CustomField schema
  xml/schema/Core/CustomField.xml
Labels: master

#20323 Convert eway to doPayment
  ext/ewaysingle/CRM/Core/Payment/eWAY.php
Labels: master, merge on pass

#20328 Convert payflowpro to doPayment
  ext/payflowpro/CRM/Core/Payment/PayflowPro.php
Labels: master

#20327 Convert Realex to doPayment
  CRM/Core/Payment/Realex.php
Labels: master

#20324 Convert elavon to doPayment
  CRM/Core/Payment/Elavon.php
Labels: master

#20325 Convert FirstData to doPayment
  CRM/Core/Payment/FirstData.php
Labels: master

#20326 Convert payJunction to doPayment
  CRM/Core/Payment/PayJunction.php
Labels: master

#20243 [Ref] remove redundant call to clearGroupContactCache
  CRM/Contact/BAO/Group.php
  CRM/Contact/BAO/GroupContactCache.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/api/v3/SavedSearchTest.php
Labels: master

#20210 Fix old-ish regression on paypal standard self-service cancel links
  CRM/Contribute/Page/Tab.php
  CRM/Contribute/Page/UserDashboard.php
  CRM/Core/Session.php
  CRM/Member/Page/RecurringContributions.php
  tests/phpunit/CRM/Contribute/Page/TabTest.php
Labels: has-test, master

#20285 Fix CKEditor5 link editing in modal dialog
  js/Common.js
Labels: master

#20332 Core_DAO - fire links_callback for all entities
  CRM/Core/DAO.php
Labels: master, merge on pass

#20333 Fix case sensitive parameter for call to getCustomFieldTokens
  CRM/Core/SelectValues.php
Labels: master

#20337 (REF) Regen CRM/Core/DAO/CustomField.php
  CRM/Core/DAO/CustomField.php
Labels: master

#20336 SearchKit - Use default_pager_size setting
  ext/search_kit/Civi/Search/Admin.php
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdmin.component.js
  ext/search_kit/ang/crmSearchAdmin/displays/searchAdminDisplayList.component.js
  ext/search_kit/ang/crmSearchAdmin/displays/searchAdminDisplayTable.component.js
Labels: master, merge on pass

#20239 [REF] Cleanup BAO_ActionSchedule::getlist() signature
  CRM/Admin/Page/ScheduleReminders.php
  CRM/Core/BAO/ActionSchedule.php
  CRM/Event/Form/ManageEvent/ScheduleReminders.php
Labels: master, merge on pass

#20341 dev/core#2403 - Change Greenwich link color from gray to blue
  ext/greenwich/scss/_greenwich.scss
Labels: master, merge on pass

#20343 [NFC] Remove timecop function references from Cache Tiered Test
  tests/phpunit/E2E/Cache/TieredTest.php
Labels: master

#20307 SearchKit - Rename crmSearchActions module to crmSearchTasks & add hook
  ext/search_kit/Civi/Api4/Action/SearchDisplay/GetSearchTasks.php
  ext/search_kit/ang/crmSearchAdmin.ang.php
  ext/search_kit/ang/crmSearchAdmin/compose/controls.html
  ext/search_kit/ang/crmSearchDisplayTable.ang.php
  ext/search_kit/ang/crmSearchDisplayTable/crmSearchDisplayTable.html
  ext/search_kit/ang/crmSearchTasks.ang.php
  ext/search_kit/ang/crmSearchTasks.module.js
  ext/search_kit/ang/crmSearchTasks/crmSearchBatchRunner.component.js
  ext/search_kit/ang/crmSearchTasks/crmSearchBatchRunner.html
  ext/search_kit/ang/crmSearchTasks/crmSearchInput/boolean.html
  ext/search_kit/ang/crmSearchTasks/crmSearchInput/crmMultiSelectDate.directive.js
  ext/search_kit/ang/crmSearchTasks/crmSearchInput/crmSearchInput.component.js
  ext/search_kit/ang/crmSearchTasks/crmSearchInput/crmSearchInput.html
  ext/search_kit/ang/crmSearchTasks/crmSearchInput/crmSearchInputVal.component.js
  ext/search_kit/ang/crmSearchTasks/crmSearchInput/date.html
  ext/search_kit/ang/crmSearchTasks/crmSearchInput/entityRef.html
  ext/search_kit/ang/crmSearchTasks/crmSearchInput/float.html
  ext/search_kit/ang/crmSearchTasks/crmSearchInput/integer.html
  ext/search_kit/ang/crmSearchTasks/crmSearchInput/select.html
  ext/search_kit/ang/crmSearchTasks/crmSearchInput/text.html
  ext/search_kit/ang/crmSearchTasks/crmSearchTaskDelete.ctrl.js
  ext/search_kit/ang/crmSearchTasks/crmSearchTaskDelete.html
  ext/search_kit/ang/crmSearchTasks/crmSearchTaskUpdate.ctrl.js
  ext/search_kit/ang/crmSearchTasks/crmSearchTaskUpdate.html
  ext/search_kit/ang/crmSearchTasks/crmSearchTasks.component.js
  ext/search_kit/ang/crmSearchTasks/crmSearchTasks.html
  ext/search_kit/css/crmSearchTasks.css
  ext/search_kit/search_kit.php
Labels: master

#20274 Create User Record now hides the Password field and uses the check isUserRegistrationPermitted - which prevents Administrators from setting passwords for new Users
  CRM/Contact/Form/Task/Useradd.php
Labels: 5.38, merge on pass

#20344 5.38
  CRM/Contact/Form/Task/Useradd.php
Labels: master

#20301 [REF] Remove unused parameters
  CRM/Batch/Form/Entry.php
  tests/phpunit/CRM/Batch/Form/EntryTest.php
Labels: master

#20347 dev/core#2613 - Replace deprecated function in useradd task
  CRM/Contact/Form/Task/Useradd.php
Labels: master

#20319 Remove extraneous debug
  CRM/Core/Payment/PayPalIPN.php
Labels: master

#20350 CIVICRM-1737 Create User Record now hides the Password field and uses…
  CRM/Contact/Form/Task/Useradd.php
Labels: 5.37, merge on pass

#20346 [REF] Make previously unshared function protected
  CRM/Contribute/Form/Contribution/Confirm.php
  tests/phpunit/CRM/Contribute/Form/Contribution/ConfirmTest.php
  tests/phpunit/CRM/Member/BAO/MembershipTest.php
Labels: master, merge on pass

#20278 Give the custom css file a 'name' to make it easier to manipulate in hook_civicrm_alterBundle()
  CRM/Core/Resources/Common.php
  tests/phpunit/CRM/Core/Resources/BundleTest.php
Labels: has-test, master, merge ready

#20340 Fix extraneous white space in generated sql
  xml/templates/drop.tpl
  xml/templates/schema.tpl
Labels: master

#20351 [REF] Update Pear Validate Finance CreditCard to use latest tagged re…
  composer.json
  composer.lock
Labels: master, merge on pass

#20352 [NFC] Add in unit tests of credit card validation rules
  tests/phpunit/CRM/Utils/RuleTest.php
Labels: has-test, master, merge on pass

#20330 Fix form params for testEventPaymentForms
  tests/phpunit/CRM/Financial/Form/PaymentFormsTest.php
Labels: master

#20345 [REF] Make previous unshared function protected & Remove hard-coded params
  CRM/Batch/Form/Entry.php
Labels: master

#20318 [REF] Add getter for contributionID
  CRM/Core/Payment/PayPalProIPN.php
Labels: master

#20241 Add test for mixed Order data
  tests/phpunit/api/v3/OrderTest.php
Labels: master

#20354 [REF] Remove now-unused parameter
  CRM/Core/Payment/PayPalProIPN.php
Labels: master, merge on pass

#20356 [NFC] Update PHPUnit config to not cache results in phpunit8 and add …
  ext/afform/core/phpunit.xml.dist
  ext/afform/mock/phpunit.xml.dist
  ext/authx/phpunit.xml.dist
  ext/contributioncancelactions/phpunit.xml.dist
  ext/ewaysingle/phpunit.xml.dist
  ext/financialacls/phpunit.xml.dist
  ext/flexmailer/phpunit.xml.dist
  ext/oauth-client/phpunit.xml.dist
  ext/payflowpro/phpunit.xml.dist
  ext/payflowpro/tests/phpunit/CRM/Core/Payment/PayflowProTest.php
  ext/search_kit/phpunit.xml.dist
  ext/sequentialcreditnotes/phpunit.xml.dist
  phpunit.xml.dist
Labels: master, merge on pass

#20355 [REF] Extract getContributionObject
  CRM/Core/Payment/PayPalProIPN.php
Labels: master, merge on pass

#20342 Fix mandatory keys check fail for value of float 0.0 in a required key in an entity
  api/v3/utils.php
Labels: has-test, master

#20297 [REF] Extract function to build temporary table of members of group from Report_Form
  CRM/Contact/BAO/GroupContactCache.php
  CRM/Report/Form.php
  tests/phpunit/api/v3/ReportTemplateTest.php
Labels: master

#20361 Unit test for #20342
  tests/phpunit/CRM/Contribute/BAO/ContributionTest.php
  tests/phpunit/api/v3/LineItemTest.php
Labels: has-test, master

#20348 SearchKit and Afform UI improvements
  CRM/Contact/BAO/SavedSearch.php
  CRM/Contact/DAO/SavedSearch.php
  ext/afform/admin/ang/afAdmin.js
  ext/afform/admin/ang/afAdmin/afAdminList.controller.js
  ext/afform/admin/ang/afAdmin/afAdminList.html
  ext/afform/admin/ang/afGuiEditor.css
  ext/afform/admin/ang/afGuiEditor/config-form.html
  ext/afform/admin/ang/afGuiEditor/entityConfig/Contact.html
  ext/afform/admin/ang/afGuiEditor/entityConfig/Generic.html
  ext/afform/admin/ang/afGuiEditor/saveBlock.html
  ext/afform/core/Civi/Api4/Afform.php
  ext/search_kit/ang/crmSearchAdmin/compose/pager.html
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdmin.html
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdminDisplay.component.js
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdminDisplay.html
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdminDisplaySort.html
  ext/search_kit/ang/crmSearchAdmin/displays/colType/buttons.html
  ext/search_kit/ang/crmSearchAdmin/displays/colType/field.html
  ext/search_kit/ang/crmSearchAdmin/displays/colType/menu.html
  ext/search_kit/ang/crmSearchAdmin/displays/searchAdminDisplayList.html
  ext/search_kit/ang/crmSearchAdmin/displays/searchAdminDisplayTable.html
  ext/search_kit/ang/crmSearchAdmin/group.html
  ext/search_kit/ang/crmSearchAdmin/searchList.controller.js
  ext/search_kit/ang/crmSearchAdmin/searchList.html
  ext/search_kit/ang/crmSearchAdmin/tabs.html
  ext/search_kit/css/crmSearchAdmin.css
  ext/search_kit/css/crmSearchTasks.css
  xml/schema/Contact/SavedSearch.xml
Labels: master

#20365 [NFC] Add in voids to various setUpBeforeClass and tearDownAfterClass…
  ext/afform/mock/tests/phpunit/api/v4/AfformRoutingTest.php
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/SearchRunTest.php
  tests/phpunit/CRM/Utils/QueryFormatterTest.php
  tests/phpunit/Civi/Test/ExampleTransactionalTest.php
  tests/phpunit/CiviTest/CiviEndToEndTestCase.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/E2E/Cache/CacheTestCase.php
  tests/phpunit/api/v3/ContributionPageTest.php
  tests/phpunit/api/v3/PriceSetTest.php
Labels: master, merge on pass

#20349 SearchKit - Fix menu permission
  ext/search_kit/CRM/Search/Upgrader.php
  ext/search_kit/xml/Menu/search_kit.xml
Labels: master
