Repository civicrm/civicrm-core, pull requests merged in 2021-08, with the labels that each got.

#20988 Move/rename case export files for consistency
  CRM/Case/Export/Form/Map.php
  CRM/Case/Export/Form/Select.php
  CRM/Case/Task.php
Labels: master

#20986 Upgrade message is scrunched up next to the previous sentence
  CRM/Upgrade/Incremental/php/FiveFortyOne.php
Labels: master

#20978 Add upgrade routine to remove old action schedule token
  CRM/Contribute/Tokens.php
  CRM/Upgrade/Incremental/Base.php
  CRM/Upgrade/Incremental/MessageTemplates.php
  CRM/Upgrade/Incremental/php/FiveFortyOne.php
  tests/phpunit/CRM/Contribute/ActionMapping/ByTypeTest.php
  tests/phpunit/CRM/Upgrade/Incremental/BaseTest.php
Labels: master, merge on pass

#20921 Fix for failure (fatal error and silent failure) to clean up full text indices
  CRM/Core/InnoDBIndexer.php
Labels: master, merge on pass

#20958 Case Dashboard: fix labels on my/all radio buttons, and simplify label text
  templates/CRM/Case/Page/DashBoard.tpl
Labels: master, merge ready

#20993 Do not generate a notice when a vcard is downloaded with a non-primary email or non-primary phone number
  CRM/Contact/Page/View/Vcard.php
Labels: master, merge on pass

#20994 Fix upgrade message when nothing was changed
  CRM/Upgrade/Incremental/php/FiveFortyOne.php
Labels: master

#20998 Rename legacy token for contribution id to match sched reminder tokens
  CRM/Core/SelectValues.php
  tests/phpunit/CRM/Contribute/ActionMapping/ByTypeTest.php
Labels: has-test, master

#21002 Smarty warnings on Manage Case
  CRM/Case/Form/CaseView.php
  templates/CRM/Case/Form/CaseView.tpl
Labels: master, merge on pass

#21004 [NFC] Do a proper tear down of fts in QueryFormatterTest
  tests/phpunit/CRM/Utils/QueryFormatterTest.php
Labels: master, merge on pass

#20996 Afform - Use correct contact type when loading field options
  ext/afform/admin/ang/afGuiEditor/afGuiEntity.component.js
  ext/afform/admin/ang/afGuiEditor/afGuiEntity.html
Labels: master

#20990 [Ref] [Test] Move custom search tests to extension
  ext/legacycustomsearches/CRM/Contact/Form/Search/Custom/Base.php
  ext/legacycustomsearches/phpunit.xml.dist
  ext/legacycustomsearches/tests/phpunit/Civi/Searches/SampleTest.php
  ext/legacycustomsearches/tests/phpunit/bootstrap.php
  tests/phpunit/CRM/Contact/Form/Search/Custom/SampleTest.php
  tests/phpunit/CRM/Contact/Form/Search/Custom/SampleTestDataProvider.php
  tests/phpunit/CRM/Contact/Form/Search/Custom/datasets/sample-dataset.xml
Labels: has-test, master

#21003 Use template variable to add or remove swap button.
  CRM/Activity/Form/Activity.php
  templates/CRM/Activity/Form/Activity.tpl
Labels: master

#21008 enable paging if contact has more then 50 grants.
  templates/CRM/Grant/Form/Selector.tpl
Labels: master

#20929 dev/wordpress#109 fix bug when is_monetary is not checked
  CRM/Contribute/Form/ContributionBase.php
Labels: 5.40

#21013 [NFC] Fix APIv4 Utf8mb4 test to ensure no mixed collation errors
  tests/phpunit/api/v4/Action/ContactGetTest.php
Labels: master, merge on pass

#21007 Backport fix for core#2687 from 5.40 branch
  CRM/Contact/BAO/GroupContactCache.php
Labels: 5.39, merge on pass

#21015 5.40
  CRM/Contribute/Form/ContributionBase.php
Labels: master

#21016 Temporary revert of changes in 20002 which caused a regression
  CRM/Contact/BAO/Query.php
  tests/phpunit/CRM/Case/BAO/QueryTest.php
  tests/phpunit/CRM/Contact/BAO/QueryTest.php
  tests/phpunit/CRM/Contact/SelectorTest.php
Labels: 5.40, merge on pass

#21017 dev/core#2728 - ReCAPTCHA - Consistently present link to settings
  ext/recaptcha/recaptcha.php
  ext/recaptcha/xml/Menu/recaptcha.xml
Labels: 5.40, merge on pass

#21005 Afform - support default values for fields
  css/civicrm.css
  ext/afform/admin/ang/afGuiEditor.css
  ext/afform/admin/ang/afGuiEditor.js
  ext/afform/admin/ang/afGuiEditor/afGuiFieldValue.directive.js
  ext/afform/admin/ang/afGuiEditor/elements/afGuiField-menu.html
  ext/afform/admin/ang/afGuiEditor/elements/afGuiField.component.js
  ext/afform/admin/ang/afGuiEditor/inputType/CheckBox.html
  ext/afform/admin/ang/afGuiEditor/inputType/Radio.html
  ext/afform/admin/ang/afGuiEditor/inputType/Select.html
  ext/afform/core/ang/af/afField.component.js
Labels: master

#21018 dev/core#2728 - ReCAPTCHA - Consistently present link to settings
  ext/recaptcha/recaptcha.php
  ext/recaptcha/xml/Menu/recaptcha.xml
Labels: 5.39, merge on pass

#21022 dev/core#2735 fix for effective start & end date not updating
  CRM/Admin/Form/ScheduleReminders.php
Labels: 5.40, merge on pass

#21012 dev/core#2725 Fix regression permitting circular group resolution
  CRM/Contact/BAO/GroupContactCache.php
  tests/phpunit/CRM/Contact/BAO/GroupTest.php
Labels: 5.40, has-test, merge on pass

#21024 Backport #21016 to v5.39
  CRM/Contact/BAO/Query.php
  tests/phpunit/CRM/Case/BAO/QueryTest.php
  tests/phpunit/CRM/Contact/BAO/QueryTest.php
  tests/phpunit/CRM/Contact/SelectorTest.php
Labels: 5.39, merge on pass

#21014 dev/core#2739 - Fix contribution tasks using wrong IDs
  CRM/Contribute/Form/Task/TaskTrait.php
Labels: 5.40

#21020 [REGRESSION] Fix CRM.url to not encode hash on WP
  js/crm.ajax.js
Labels: 5.40, merge on pass

#21025 dev/core#2725 Fix regression permitting circular group resolution
  CRM/Contact/BAO/GroupContactCache.php
  tests/phpunit/CRM/Contact/BAO/GroupTest.php
Labels: 5.39, has-test, merge on pass

#21026 Fix CRM.url to not encode hash on WP (5.39)
  js/crm.ajax.js
Labels: 5.39, merge on pass

#21027 dev/core#2739 - Fix contribution tasks using wrong IDs (5.39 backport)
  CRM/Contribute/Form/Task/TaskTrait.php
Labels: 5.39, merge on pass

#21028 dev/event#62 - Expose all price fields to backend form (5.40)
  CRM/Event/Form/Participant.php
  CRM/Price/BAO/PriceSet.php
Labels: 5.40, merge on pass

#21029 dev/event#62 - Expose all price fields to backend form (5.39)
  CRM/Event/Form/Participant.php
  CRM/Price/BAO/PriceSet.php
Labels: 5.39, merge on pass

#21030 5.39.1 - Version bump. Notes.
  ext/afform/admin/info.xml
  ext/afform/core/info.xml
  ext/afform/html/info.xml
  ext/afform/mock/info.xml
  ext/authx/info.xml
  ext/contributioncancelactions/info.xml
  ext/eventcart/info.xml
  ext/ewaysingle/info.xml
  ext/financialacls/info.xml
  ext/flexmailer/info.xml
  ext/greenwich/info.xml
  ext/oauth-client/info.xml
  ext/payflowpro/info.xml
  ext/recaptcha/info.xml
  ext/search_kit/info.xml
  ext/sequentialcreditnotes/info.xml
  release-notes.md
  release-notes/5.39.1.md
  sql/civicrm_generated.mysql
  sql/test_data_second_domain.mysql
  xml/version.xml
Labels: 5.39

#21031 5.40.0 - Version bump. More release notes.
  ext/afform/admin/info.xml
  ext/afform/core/info.xml
  ext/afform/html/info.xml
  ext/afform/mock/info.xml
  ext/authx/info.xml
  ext/ckeditor4/info.xml
  ext/contributioncancelactions/info.xml
  ext/eventcart/info.xml
  ext/ewaysingle/info.xml
  ext/financialacls/info.xml
  ext/flexmailer/info.xml
  ext/greenwich/info.xml
  ext/oauth-client/info.xml
  ext/payflowpro/info.xml
  ext/recaptcha/info.xml
  ext/search_kit/info.xml
  ext/sequentialcreditnotes/info.xml
  release-notes.md
  release-notes/5.39.1.md
  release-notes/5.40.0.md
  sql/civicrm_generated.mysql
  sql/test_data_second_domain.mysql
  xml/version.xml
Labels: 5.40

#21032 5.40 up merge
  CRM/Admin/Form/ScheduleReminders.php
  CRM/Contact/BAO/GroupContactCache.php
  CRM/Contact/BAO/Query.php
  CRM/Contribute/Form/Task/TaskTrait.php
  CRM/Event/Form/Participant.php
  CRM/Price/BAO/PriceSet.php
  ext/recaptcha/recaptcha.php
  ext/recaptcha/xml/Menu/recaptcha.xml
  js/crm.ajax.js
  release-notes.md
  release-notes/5.39.1.md
  release-notes/5.40.0.md
  tests/phpunit/CRM/Case/BAO/QueryTest.php
  tests/phpunit/CRM/Contact/BAO/GroupTest.php
  tests/phpunit/CRM/Contact/BAO/QueryTest.php
  tests/phpunit/CRM/Contact/SelectorTest.php
Labels: master

#21033 Update contributor-key.yml
  contributor-key.yml
Labels: master

#21019 Fix bulk adding custom fields with logging on
  CRM/Core/BAO/CustomField.php
Labels: master

#20999 Switch contribution action schedule tokens to use advertised tokens for cancel_date & source
  CRM/Contribute/Tokens.php
  CRM/Upgrade/Incremental/php/FiveFortyOne.php
  tests/phpunit/CRM/Contribute/ActionMapping/ByTypeTest.php
Labels: master, has-test

#21000 Reconcile and upgrade tokens for payment instrument, financial type
  CRM/Contribute/Tokens.php
  CRM/Core/SelectValues.php
  CRM/Upgrade/Incremental/php/FiveFortyOne.php
  tests/phpunit/CRM/Contribute/ActionMapping/ByTypeTest.php
Labels: master, merge on pass, has-test

#21035 Update contribution_page_id token in sched reminders
  CRM/Contribute/BAO/Contribution.php
  CRM/Contribute/Tokens.php
  CRM/Upgrade/Incremental/php/FiveFortyOne.php
  tests/phpunit/CRM/Contribute/BAO/ContributionTest.php
Labels: master, merge on pass

#21037 Fix advertised token for source
  CRM/Core/SelectValues.php
  tests/phpunit/CRM/Contribute/ActionMapping/ByTypeTest.php
Labels: master, merge on pass

#21036 Reconcile contribution amount tokens
  CRM/Contribute/Tokens.php
  CRM/Core/EntityTokens.php
  Civi/Token/TokenRow.php
  tests/phpunit/CRM/Contribute/ActionMapping/ByTypeTest.php
Labels: master, merge on pass

#20989 Fix mailing task when there are no tasks
  CRM/Mailing/Task.php
Labels: master

#20752 Make report subtotals work for custom fields
  CRM/Report/Form.php
Labels: master

#21040 Enotice fix
  templates/CRM/Mailing/Form/Search.tpl
Labels: master, merge on pass

#21041 Enotice fix
  templates/CRM/Contact/Form/Search/Advanced.tpl
Labels: master

#21038 Switch to using apiv4 for metadata
  CRM/Contribute/Tokens.php
  CRM/Core/EntityTokens.php
Labels: master

#21039 Reconcile tokens misnamed or missing on legacy class
  CRM/Contribute/Tokens.php
  CRM/Core/EntityTokens.php
  CRM/Core/SelectValues.php
Labels: master

#21044 contributor-key.yml: updates for Symbiotic
  contributor-key.yml
Labels: master

#21045 SearchKit - Fix permission to access task list
  ext/search_kit/Civi/Api4/SearchDisplay.php
Labels: master, merge on pass, sig:regression, comp:search-kit

#21050 Tpl notice fixes
  templates/CRM/Contribute/Form/Search/Common.tpl
Labels: master, merge on pass

#21051 dev/core#2740 fix dashboard regression on links
  templates/CRM/Contact/Page/View/UserDashBoard.tpl
Labels: master

#21052 SearchKit - Fix permission to access task list (5.40)
  ext/search_kit/Civi/Api4/SearchDisplay.php
Labels: merge on pass, 5.40

#21053 dev/core#2742 fix group type on group create from form
  CRM/Contact/Form/Task/AddToGroup.php
Labels: master

#21054 dev/core#2740 fix dashboard regression on links
  templates/CRM/Contact/Page/View/UserDashBoard.tpl
Labels: merge on pass, 5.40

#21055 5.40.1 - Add notes. Bump version.
  ext/afform/admin/info.xml
  ext/afform/core/info.xml
  ext/afform/html/info.xml
  ext/afform/mock/info.xml
  ext/authx/info.xml
  ext/ckeditor4/info.xml
  ext/contributioncancelactions/info.xml
  ext/eventcart/info.xml
  ext/ewaysingle/info.xml
  ext/financialacls/info.xml
  ext/flexmailer/info.xml
  ext/greenwich/info.xml
  ext/oauth-client/info.xml
  ext/payflowpro/info.xml
  ext/recaptcha/info.xml
  ext/search_kit/info.xml
  ext/sequentialcreditnotes/info.xml
  release-notes.md
  release-notes/5.40.1.md
  sql/civicrm_generated.mysql
  sql/test_data_second_domain.mysql
  xml/version.xml
Labels: 5.40

#21001 [REF] Fix utf8mb4 test in APIv4 and re-enable the altering of databas…
  CRM/Contact/BAO/Query.php
  CRM/Core/DAO.php
  CRM/Utils/SQL.php
  tests/phpunit/api/v3/ContactTest.php
  tests/phpunit/api/v4/Action/ContactGetTest.php
Labels: merge on pass, has-test, 5.41

#21047 [Ref] cleanup alterActionSchedule
  CRM/Contribute/Tokens.php
  CRM/Core/EntityTokens.php
Labels: master

#21056 5.41
  CRM/Contact/BAO/Query.php
  CRM/Core/DAO.php
  CRM/Utils/SQL.php
  tests/phpunit/api/v3/ContactTest.php
  tests/phpunit/api/v4/Action/ContactGetTest.php
Labels: master

#21061 Remove unused assignment
  CRM/Contact/Form/Task/EmailCommon.php
Labels: master

#21066 [Ref] Move rule to email trait
  CRM/Contact/Form/Task/EmailCommon.php
  CRM/Contact/Form/Task/EmailTrait.php
Labels: master

#21060 dev/core#2730 - Replace fopen call in CRM_Utils_File::isIncludable with one that doesn't need error-supression to avoid problems in php8
  CRM/Utils/File.php
  tests/phpunit/CRM/Utils/FileTest.php
Labels: master, merge on pass, has-test

#20976 Fix Membership.create in BAO to respect passed in status_id
  CRM/Contribute/BAO/Contribution.php
  CRM/Member/BAO/Membership.php
  Civi/Test/ContactTestTrait.php
  api/v3/Order.php
  tests/phpunit/CRM/Export/BAO/ExportTest.php
  tests/phpunit/CRM/Member/Selector/SearchTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/api/v3/ContributionTest.php
  tests/phpunit/api/v3/MembershipStatusTest.php
Labels: master, has-test

#21049 [REF] SearchKit - display code refactor + pager options
  ext/search_kit/Civi/Api4/Action/SearchDisplay/Run.php
  ext/search_kit/ang/crmSearchAdmin.ang.php
  ext/search_kit/ang/crmSearchAdmin.module.js
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdminDisplay.component.js
  ext/search_kit/ang/crmSearchAdmin/displays/common/searchAdminPagerConfig.component.js
  ext/search_kit/ang/crmSearchAdmin/displays/common/searchAdminPagerConfig.html
  ext/search_kit/ang/crmSearchAdmin/displays/searchAdminDisplayList.component.js
  ext/search_kit/ang/crmSearchAdmin/displays/searchAdminDisplayList.html
  ext/search_kit/ang/crmSearchAdmin/displays/searchAdminDisplayTable.component.js
  ext/search_kit/ang/crmSearchAdmin/displays/searchAdminDisplayTable.html
  ext/search_kit/ang/crmSearchDisplay.module.js
  ext/search_kit/ang/crmSearchDisplay/Pager.html
  ext/search_kit/ang/crmSearchDisplay/traits/searchDisplayBaseTrait.service.js
  ext/search_kit/ang/crmSearchDisplay/traits/searchDisplaySortableTrait.service.js
  ext/search_kit/ang/crmSearchDisplayList/crmSearchDisplayList.component.js
  ext/search_kit/ang/crmSearchDisplayTable/crmSearchDisplayTable.component.js
  ext/search_kit/ang/crmSearchDisplayTable/crmSearchDisplayTable.html
  ext/search_kit/ang/crmSearchDisplayTable/crmSearchDisplayTableBody.html
  ext/search_kit/ang/crmSearchTasks/traits/searchDisplayTasksTrait.service.js
Labels: master

#21062 Move make-sure-single-set out of shared function
  CRM/Contact/Form/Task/EmailCommon.php
  CRM/Contact/Form/Task/EmailTrait.php
  CRM/Contact/Form/Task/PDFLetterCommon.php
Labels: master

#21070 Smarty notice - Explicitly set hideRelativeLabel var on Find Cases form
  templates/CRM/Case/Form/Search/Common.tpl
Labels: master

#21063 [Ref] Clarify what parameters are passed in
  CRM/Contribute/BAO/Contribution.php
Labels: master

#21057 dev/core#2747 REF] Move all the generic functions to the parent
  CRM/Contribute/Tokens.php
  CRM/Core/EntityTokens.php
Labels: master

#21069 SearchKit - Merge admin results table with searchDisplay code
  ext/search_kit/Civi/Api4/Action/SearchDisplay/Run.php
  ext/search_kit/ang/crmSearchAdmin.module.js
  ext/search_kit/ang/crmSearchAdmin/compose.html
  ext/search_kit/ang/crmSearchAdmin/compose/controls.html
  ext/search_kit/ang/crmSearchAdmin/compose/debug.html
  ext/search_kit/ang/crmSearchAdmin/compose/pager.html
  ext/search_kit/ang/crmSearchAdmin/compose/results.html
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdmin.component.js
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdmin.html
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdminDisplay.component.js
  ext/search_kit/ang/crmSearchAdmin/displays/common/searchButtonConfig.html
  ext/search_kit/ang/crmSearchAdmin/displays/searchAdminDisplayList.html
  ext/search_kit/ang/crmSearchAdmin/displays/searchAdminDisplayTable.html
  ext/search_kit/ang/crmSearchAdmin/resultsTable/crmSearchAdminResultsTable.component.js
  ext/search_kit/ang/crmSearchAdmin/resultsTable/crmSearchAdminResultsTable.html
  ext/search_kit/ang/crmSearchAdmin/resultsTable/debug.html
  ext/search_kit/ang/crmSearchDisplay/SearchButton.html
  ext/search_kit/ang/crmSearchDisplay/traits/searchDisplayBaseTrait.service.js
  ext/search_kit/ang/crmSearchDisplay/traits/searchDisplaySortableTrait.service.js
  ext/search_kit/ang/crmSearchDisplayList/crmSearchDisplayList.html
  ext/search_kit/ang/crmSearchDisplayTable/crmSearchDisplayTable.html
  ext/search_kit/ang/crmSearchTasks/traits/searchDisplayTasksTrait.service.js
  ext/search_kit/css/crmSearchAdmin.css
Labels: master

#21072 APIv4 - Throw exception instead of munging illegal join aliases
  Civi/Api4/Query/Api4SelectQuery.php
  tests/phpunit/api/v4/Action/FkJoinTest.php
Labels: master, merge on pass, has-test

#21073 MessageTemplate::sendTemplate() - Accept `array $messageTemplate` and `array $tokenContext`
  CRM/Core/BAO/MessageTemplate.php
  tests/phpunit/CRM/Core/BAO/MessageTemplateTest.php
Labels: master, has-test

#21067 [Ref] extract function to getEmailDefaults
  CRM/Contact/Form/Task/EmailCommon.php
  CRM/Contact/Form/Task/EmailTrait.php
  CRM/Core/BAO/Email.php
Labels: master, merge on pass

#21074 Remove no longer used variable in Email.tpl / smarty warning
  templates/CRM/Contact/Form/Task/Email.tpl
Labels: master

#21077 Fix the check to see if the financialAclExtension is installed
  CRM/Upgrade/Incremental/General.php
Labels: master

#21084 APIv4 - Silently ignore errors in CoreUtil::getInfoItem()
  Civi/Api4/Utils/CoreUtil.php
Labels: master, merge on pass

#21078 [Ref] Simplify IF clause
  CRM/Contribute/BAO/Contribution.php
Labels: master

#21085 Scheduled Reminders - Pass locale through to TokenProcessor
  CRM/Core/BAO/ActionSchedule.php
  CRM/Utils/AutoClean.php
  Civi/Token/TokenCompatSubscriber.php
  Civi/Token/TokenProcessor.php
  tests/phpunit/Civi/Token/TokenProcessorTest.php
Labels: master, merge on pass, has-test

#21087 Upgrade Pear/DB package to be version 1.11.0
  composer.json
  composer.lock
  tools/scripts/composer/pear_db_civicrm_changes.patch
Labels: master, merge on pass

#21086 CRM_Core_Component - Remove unused code
  CRM/Core/Component.php
  CRM/Core/Component/Info.php
Labels: master

#21090 (NFC) TokenProcessorTest - Add scenario inspired by dev/core#2673
  tests/phpunit/Civi/Token/TokenProcessorTest.php
Labels: master, merge on pass, has-test

#21092 (NFC) Expand test coverage for scheduled-reminders with `{activity.*}` tokens
  tests/phpunit/CRM/Core/BAO/ActionScheduleTest.php
Labels: master, merge on pass

#21081 Upgrade angular-file-uploader to v2.6.1
  ang/angularFileUpload.ang.php
  composer.json
  composer.lock
  karma.conf.js
Labels: master, merge on pass

#21089 [REF] Afform - Code cleanup in LoadAdminData API action
  ext/afform/admin/Civi/Api4/Action/Afform/LoadAdminData.php
Labels: master

#21091 Scheduled Reminders UI - Show more activity tokens in admin GUI
  CRM/Admin/Form/ScheduleReminders.php
Labels: master

#21088 ActionSchedule - Pass real batches into TokenProcessor. Simplify CRM_Activity_Tokens.
  CRM/Activity/Tokens.php
  CRM/Core/BAO/ActionSchedule.php
  Civi/Token/TokenProcessor.php
Labels: master

#21098 (NFC) MailingQueryEvent - Add more docblocks about query-writing and `tokenContext_*`
  Civi/ActionSchedule/Event/MailingQueryEvent.php
Labels: master, merge on pass

#21095 [REF] SearchKit - Use non-deprecated join syntax when loading standalone displays
  ext/search_kit/ang/crmSearchPage.module.js
Labels: master

#21080 (dev/core#2673) Email Tokens - Custom tokens in `subject` block similar tokens in `body`
  CRM/Activity/BAO/Activity.php
Labels: master, merge ready

#20991 dev/core#2719 [REF] Remove a couple more (tested) references to legacy contribution_invoice_settings
  CRM/Batch/Form/Entry.php
  CRM/Contribute/BAO/Contribution.php
  CRM/Contribute/BAO/ContributionPage.php
  CRM/Contribute/Form/AdditionalInfo.php
  CRM/Event/BAO/Event.php
  CRM/Event/Form/Participant.php
  CRM/Member/Form/Membership.php
  tests/phpunit/CRM/Core/Payment/PayPalIPNTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/api/v3/ContributionPageTest.php
Labels: master, merge on pass

#21076 Token Parser - Allow tokens with multiple dots (eg {contribution.contribution_recur_id.amount})
  CRM/Utils/Token.php
  tests/phpunit/Civi/Token/TokenProcessorTest.php
Labels: master, merge on pass, has-test

#20936 dev/core#2717 Use Same order ->payment flow for non recurring back of…
  CRM/Member/Form.php
  CRM/Member/Form/Membership.php
  tests/phpunit/CRM/Member/Form/MembershipTest.php
Labels: master

#21096 Respect http_timeout core setting for Guzzle HTTP requests
  CRM/Utils/Address/USPS.php
  CRM/Utils/Geocode/Google.php
  ext/recaptcha/lib/recaptcha/recaptchalib.php
Labels: master

#21094 Replace extension key with label during install/upgrade/disable/uninstall
  CRM/Admin/Form/Extensions.php
  templates/CRM/Admin/Page/ExtensionDetails.tpl
Labels: master

#21046 dev/core#2747 Reconcile remaining fields between scheduled reminders and legacy tokens
  CRM/Contribute/DAO/Contribution.php
  CRM/Contribute/Tokens.php
  CRM/Core/CodeGen/Specification.php
  CRM/Core/SelectValues.php
  tests/phpunit/CRM/Contribute/ActionMapping/ByTypeTest.php
  xml/schema/Contribute/Contribution.xml
Labels: master

#21100 dev/core#2749 remove exception when no payment processor configured when no payment processor configured
  CRM/Core/Form.php
  tests/phpunit/CRM/Contribute/Form/ContributionTest.php
Labels: 5.41

#21104 (NFC) release-notes - Fix typo
  release-notes/5.39.1.md
Labels: merge on pass, 5.41

#21111 5.41
  CRM/Core/Form.php
  release-notes/5.39.1.md
  tests/phpunit/CRM/Contribute/Form/ContributionTest.php
Labels: master

#21108 [REF] Upgrade CKEditor to 4.16.2
  composer.json
  composer.lock
Labels: merge on pass, 5.41

#21113 5.41
  composer.json
  composer.lock
Labels: master

#21112 5.41
  composer.json
  composer.lock
Labels: master

#21107 delocalize total amount before passing to setOverrideTotal
  CRM/Contribute/Form/Contribution.php
Labels: merge ready, 5.41

#21117 5.41 to master
  CRM/Contribute/Form/Contribution.php
Labels: master

#21115 MessageTemplate - Add renderTemplate(). Deprecate renderMessageTemplate().
  CRM/Core/BAO/MessageTemplate.php
  tests/phpunit/CRM/Core/BAO/MessageTemplateTest.php
Labels: master, has-test

#21121 Replace deprecated calls to `renderMessageTemplate()`
  CRM/Contribute/Form/Task/PDFLetter.php
  CRM/Core/BAO/MessageTemplate.php
  CRM/SMS/Form/Upload.php
  tests/phpunit/CRM/Core/BAO/MessageTemplateTest.php
Labels: master, merge on pass

#21103 dev/user-interface#38 Contact Edit: Only display signatures if contact has a CMS account
  CRM/Contact/Form/Edit/Email.php
  templates/CRM/Contact/Form/Edit/Email.tpl
Labels: master

#21116 [NFC] {Test} Minor cleanup
  tests/phpunit/api/v3/ContributionTest.php
Labels: master

#21124 fix crmValidate() not loading on event registration pages
  templates/CRM/Form/validate.tpl
Labels: 5.41

#21123 [REF] Upgrade CKEditor for 5.40
  composer.json
  composer.lock
Labels: 5.40

#21127 5.41 to master
  templates/CRM/Form/validate.tpl
Labels: master

#21118 5.40 contribution save regression
  CRM/Contribute/Form/Contribution.php
  CRM/Financial/BAO/Order.php
Labels: 5.40

#21099 dev/core#2743 fix api v3 to not unnecessarily load options
  api/v3/utils.php
  tests/phpunit/api/v3/ContributionTest.php
  tests/phpunit/api/v3/MembershipTest.php
Labels: merge ready, 5.41

#21125 NFC - Fix docblock in CRM_Core_Transaction
  CRM/Core/Transaction.php
Labels: master, merge on pass

#20907 dev/core#2691 - On logging detail civireport show words instead of numbers (part 2)
  CRM/Logging/ReportDetail.php
  tests/phpunit/api/v3/ReportTemplateTest.php
Labels: master, has-test

#21128 fix crmValidate() not loading on event registration pages
  templates/CRM/Form/validate.tpl
Labels: merge on pass, 5.40

#21130 Reinstate jQueryUI visible focus effect in quicksearch user-interface…
  js/crm.menubar.js
Labels: merge on pass, 5.40

#21129 5.41
  api/v3/utils.php
  js/crm.menubar.js
  tests/phpunit/api/v3/ContributionTest.php
  tests/phpunit/api/v3/MembershipTest.php
Labels: master

#21131 dev/core#2743 fix api v3 to not unnecessarily load options
  api/v3/utils.php
  tests/phpunit/api/v3/ContributionTest.php
  tests/phpunit/api/v3/MembershipTest.php
Labels: merge on pass, 5.40

#21132 dev/core#2749 remove exception when no payment processor configuredhe…
  CRM/Core/Form.php
  tests/phpunit/CRM/Contribute/Form/ContributionTest.php
Labels: merge on pass, 5.40

#21133 (NFC) release-notes/5.39.1.md - Fix typo
  release-notes/5.39.1.md
Labels: merge on pass, 5.40

#21114 (REF) ReflectionUtils - Add findStandardProperties() and findMethodHelpers()
  Civi/Api4/Utils/ReflectionUtils.php
  Civi/Schema/Traits/MagicGetterSetterTrait.php
  tests/phpunit/Civi/Schema/MagicGetterSetterTest.php
Labels: master, has-test

#21136 5.41.0 release notes initial run
  release-notes.md
  release-notes/5.41.0.md
Labels: merge on pass, 5.41

#21138 5.41
  release-notes.md
  release-notes/5.41.0.md
Labels: master

#20168 dev/search#63 Add recurring contributions to contribution reports
  CRM/Report/Form/Contribute/Summary.php
Labels: master

#21075 [Ref] Move id fetching to the classes
  CRM/Contact/Form/Task/EmailTrait.php
  CRM/Contribute/Form/Task/Email.php
Labels: master

#21140 Use convenience function for one-off token evaluations to avoid too-long filenames and possible privacy issues
  Civi/Token/TokenCompatSubscriber.php
Labels: master

#21146 [NFC] Update testCaseActivityCopyTemplate to provide variable that would usually be present
  tests/phpunit/CRM/Core/BAO/MessageTemplateTest.php
Labels: master, has-test

#21147 dev/core#2758 fix task tiles
  CRM/Core/Task.php
  CRM/Member/Task.php
Labels: 5.41

#21143 [REF] Fix e-notice in APIv3 Profile Test on PHP8
  api/v3/Profile.php
Labels: merge ready, 5.41

#21149 [REF] Fix e-notice in APIv3 Profile Test on PHP8
  api/v3/Profile.php
Labels: 5.40

#21148 5.41
  CRM/Core/Task.php
  CRM/Member/Task.php
  api/v3/Profile.php
Labels: master

#21151 Membership batch processing error
  CRM/Batch/Form/Entry.php
Labels: merge on pass, 5.41

#21154 5.41
  CRM/Batch/Form/Entry.php
Labels: master

#21155 [NFC] Update CRM_Core_RegionTest so it doesn't need the error-suppression operator
  tests/phpunit/CRM/Core/RegionTest.php
Labels: master, merge on pass

#21158 APIv4 - Add File entity
  Civi/Api4/File.php
Labels: master

#21153 Membership batch processing error
  CRM/Batch/Form/Entry.php
Labels: 5.40

#21162 5.40.2 - Add notes. Bump version.
  ext/afform/admin/info.xml
  ext/afform/core/info.xml
  ext/afform/html/info.xml
  ext/afform/mock/info.xml
  ext/authx/info.xml
  ext/ckeditor4/info.xml
  ext/contributioncancelactions/info.xml
  ext/eventcart/info.xml
  ext/ewaysingle/info.xml
  ext/financialacls/info.xml
  ext/flexmailer/info.xml
  ext/greenwich/info.xml
  ext/oauth-client/info.xml
  ext/payflowpro/info.xml
  ext/recaptcha/info.xml
  ext/search_kit/info.xml
  ext/sequentialcreditnotes/info.xml
  release-notes.md
  release-notes/5.40.2.md
  sql/civicrm_generated.mysql
  sql/test_data_second_domain.mysql
  xml/version.xml
Labels: 5.40

#21163 Add release-notes/5.40.2.md release-notes/5.40.1.md
  release-notes.md
  release-notes/5.40.1.md
  release-notes/5.40.2.md
Labels: 5.41

#21165 release-notes/5.40.2.md - Add reference to Gitlab issue
  release-notes/5.40.2.md
Labels: 5.40

#21164 5.41
  release-notes.md
  release-notes/5.40.1.md
  release-notes/5.40.2.md
Labels: master

#21156 [REF] SearchKit - Refactor search task code to share a trait
  ext/search_kit/ang/crmSearchAdmin/resultsTable/crmSearchAdminResultsTable.component.js
  ext/search_kit/ang/crmSearchDisplay/colType/field.html
  ext/search_kit/ang/crmSearchDisplay/traits/searchDisplayBaseTrait.service.js
  ext/search_kit/ang/crmSearchDisplayList/crmSearchDisplayList.component.js
  ext/search_kit/ang/crmSearchDisplayTable/crmSearchDisplayTable.component.js
  ext/search_kit/ang/crmSearchTasks/crmSearchTaskDelete.ctrl.js
  ext/search_kit/ang/crmSearchTasks/crmSearchTaskDelete.html
  ext/search_kit/ang/crmSearchTasks/crmSearchTaskUpdate.ctrl.js
  ext/search_kit/ang/crmSearchTasks/traits/searchDisplayTasksTrait.service.js
  ext/search_kit/ang/crmSearchTasks/traits/searchTaskBaseTrait.service.js
Labels: master

#21161 [Ref] remove unused variable
  CRM/Core/DAO/AllCoreTables.php
Labels: master

#21167 dev/core#2758 - Fix contribution activity campaign propagation
  CRM/Contribute/BAO/Contribution.php
  tests/phpunit/CRM/Contribute/BAO/ContributionTest.php
Labels: master, merge on pass, has-test

#21082 Fix search display access for non-admin users
  Civi/Api4/SavedSearch.php
  ext/search_kit/Civi/Api4/SearchDisplay.php
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/SearchRunTest.php
Labels: master, merge ready

#21071 APIv4 - Support multiple implicit joins to the same table
  Civi/Api4/Query/Api4SelectQuery.php
  Civi/Api4/Service/Schema/Joinable/Joinable.php
  Civi/Api4/Service/Schema/Joiner.php
  Civi/Api4/Service/Schema/SchemaMap.php
  tests/phpunit/api/v3/ContributionTest.php
  tests/phpunit/api/v4/Action/BasicCustomFieldTest.php
  tests/phpunit/api/v4/Service/Schema/SchemaMapperTest.php
Labels: master, has-test, comp:search-kit

#21170 Enotice fixes in tpl
  CRM/Member/Form/Membership.php
Labels: master, merge on pass

#21119 Update MembershipType.duration and MembershipStatus.name to be required
  CRM/Member/DAO/MembershipStatus.php
  CRM/Member/DAO/MembershipType.php
  ext/financialacls/tests/phpunit/Civi/Financialacls/MembershipTypesTest.php
  xml/schema/Member/MembershipStatus.xml
  xml/schema/Member/MembershipType.xml
Labels: master

#21172 SearchKit - Add placeholder to token select
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdminTokenSelect.component.js
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdminTokenSelect.html
Labels: master

#21171 dev/core#2758 - Fix contribution activity campaign propagation ...more
  CRM/Contribute/BAO/Contribution.php
Labels: master

#21160 dev/core#2762 Fix custom field edit form to set serialization correctly
  CRM/Custom/Form/Field.php
  tests/phpunit/CRM/Custom/Form/FieldTest.php
Labels: master, merge ready

#21168 closes core#2770: Dedupe by website
  CRM/Dedupe/BAO/DedupeRule.php
  CRM/Dedupe/BAO/DedupeRuleGroup.php
  tests/phpunit/CRM/Dedupe/BAO/RuleGroupTest.php
Labels: master, merge on pass
