Repository civicrm/civicrm-core, pull requests merged in 2021-02, with the labels that each got.

#19477 [NFC] Fix PHP 7.4 Syntax issue in Afform HTML Extension
  ext/afform/core/CRM/Afform/ArrayHtml.php
Labels: master, merge on pass

#19472 dev/core#2333 Fix issue when clicking on alpha links from 'amtg' search
  CRM/Utils/PagerAToZ.php
Labels: master

#19460 Afform - Fix form submit button
  ext/afform/core/ang/af/afForm.component.js
Labels: master

#19448 dev/core#2329 Add is_active field to Country/StateProvince/County
  CRM/Core/DAO/Country.php
  CRM/Core/DAO/County.php
  CRM/Core/DAO/StateProvince.php
  CRM/Upgrade/Incremental/php/FiveThirtyFive.php
  xml/schema/Core/Country.xml
  xml/schema/Core/County.xml
  xml/schema/Core/StateProvince.xml
Labels: master, merge ready

#19457 dev/core#2324 Update jquery-validaton to be 1.19.3
  composer.json
  composer.lock
Labels: 5.34

#19484 Merge 5.34 to master
  composer.json
Labels: master

#19480 [REF] Prelminary tidy up to support fix for dev/core#2344
  CRM/Contribute/Form/Task/PDFLetterCommon.php
  CRM/Utils/Token.php
  tests/phpunit/CRM/Contribute/Form/ContributionTest.php
  tests/phpunit/CRM/Contribute/Form/Task/PDFLetterCommonTest.php
Labels: 5.34, merge on pass

#19483 dev/core#2348 fix unreleased regression
  CRM/Event/Import/Parser/Participant.php
Labels: 5.34, merge on pass

#19479 Search Kit - Fix display pager and improve error handling
  ext/afform/core/Civi/Afform/AfformMetadataInjector.php
  ext/search/ang/crmSearchDisplay/Pager.html
Labels: master, merge on pass

#19488 [REF] Remove copy & paste code from Activity mapping form
  CRM/Activity/Import/Form/MapField.php
  CRM/Activity/Import/Parser.php
Labels: master

#19485 [NFC] Update composer.lock
  composer.lock
Labels: master, merge on pass

#19461 Greenwich: Fix BS3 conflict with html5 search clear button
  ext/greenwich/scss/_tweaks.scss
Labels: master

#19491 Issue #2352: fix Views integration suggestion
  CRM/Admin/Form/Setting/UF.php
Labels: master

#19487 5.34
  CRM/Contribute/Form/Task/PDFLetterCommon.php
  CRM/Event/Import/Parser/Participant.php
  CRM/Utils/Token.php
  tests/phpunit/CRM/Contribute/Form/ContributionTest.php
  tests/phpunit/CRM/Contribute/Form/Task/PDFLetterCommonTest.php
Labels: master

#19489 Search Kit: Misc bug fixes
  ext/afform/admin/ang/afAdmin/afAdminList.html
  ext/search/ang/crmSearchAdmin.module.js
  ext/search/ang/crmSearchAdmin/crmSearchAdmin.component.js
  ext/search/ang/crmSearchDisplayTable/crmSearchDisplayTable.component.js
Labels: master

#19490 Token Processor: fix PHP syntax for purifyHTML
  Civi/Token/TokenRow.php
Labels: master, merge on pass

#19481 dev/core#2344 unit test for fix regression affecting sending thank you letters when grouped
  CRM/Utils/PDF/Utils.php
  CRM/Utils/Token.php
  tests/phpunit/CRM/Contribute/Form/Task/PDFLetterCommonTest.php
Labels: 5.34

#19468 NFC Minor code cleanup to contribution pages
  CRM/Contribute/Form/Contribution/Main.php
  CRM/Contribute/Form/ContributionBase.php
  CRM/Price/BAO/PriceSet.php
Labels: Non-functional-change (NFC), master, merge on pass

#19497 Fix for ReportTest when launching a pdf
  CRM/Utils/PDF/Utils.php
Labels: 5.34

#19493 5.34
  CRM/Utils/PDF/Utils.php
  CRM/Utils/Token.php
  tests/phpunit/CRM/Contribute/Form/Task/PDFLetterCommonTest.php
Labels: master

#19289 dev/core#2206 Move cancel pledge into Contribution.create and fix
  CRM/Contribute/BAO/Contribution.php
  ext/contributioncancelactions/contributioncancelactions.php
  ext/contributioncancelactions/tests/phpunit/CancelTest.php
  tests/phpunit/CRM/Contribute/BAO/ContributionTest.php
Labels: master

#19499 Remove always true if
  CRM/Contribute/BAO/Contribution.php
Labels: master

#19503 Use exceptions when enabling case component / checking for 'CREATE VIEW' permissions
  CRM/Case/BAO/Case.php
  CRM/Core/DAO.php
Labels: master

#19502 CRM_Core_BAO_MessageTemplate::sendReminder() is not used anywhere
  CRM/Core/BAO/MessageTemplate.php
Labels: master

#19507 Comment intent to remove call to transition components
  CRM/Contribute/BAO/Contribution.php
  CRM/Contribute/Form/Contribution.php
Labels: master

#19500 dev/core#2206 Unhide contributioncancelactions core extension
  ext/contributioncancelactions/info.xml
Labels: master

#19505 Remove another use of loadRelatedObjects() function
  CRM/Contribute/BAO/Contribution.php
Labels: master

#19417 [REF] Standardise methods of determining isTest
  CRM/Member/Form/Membership.php
Labels: master

#19492 dev/core#2350 - Oauth extension - Setting a fatalErrorHandler might override the redirect url because typo
  ext/oauth-client/settings/OAuthClient.setting.php
Labels: master, merge ready

#19513 Move require once in api kernel to support edge cases
  Civi/API/Kernel.php
Labels: master, merge on pass

#19496 Afform - Misc tweaks, validation & bug fixes
  ext/afform/admin/CRM/AfformAdmin/Page/Base.php
  ext/afform/admin/CRM/AfformAdmin/Upgrader.php
  ext/afform/admin/Civi/AfformAdmin/AfformAdminMeta.php
  ext/afform/admin/Civi/Api4/Action/Afform/LoadAdminData.php
  ext/afform/admin/ang/afAdmin/afAdminList.controller.js
  ext/afform/admin/ang/afAdmin/afAdminList.html
  ext/afform/admin/ang/afGuiEditor/afGuiEditor.component.js
  ext/afform/admin/ang/afGuiEditor/config-form.html
  ext/afform/core/Civi/Api4/Action/Afform/Get.php
  ext/afform/core/Civi/Api4/Action/Afform/Submit.php
  ext/search/ang/crmSearchAdmin.module.js
  ext/search/ang/crmSearchAdmin/crmSearchAdmin.component.js
  ext/search/ang/crmSearchAdmin/searchList.html
Labels: master, merge on pass

#19515 dev/core#2355 - E_NOTICE on Manage Contribution and Manage Event listings
  CRM/Utils/PagerAToZ.php
Labels: master

#19498 [REF] Stop passing contributionPageID to isEmailReceipt
  CRM/Contribute/BAO/Contribution.php
  tests/phpunit/api/v3/ContributionPageTest.php
Labels: master

#19511 [REF] Remove invalid attempt to load contriution id from invoiceID
  CRM/Member/Form/Membership.php
Labels: master

#19443 [REF] Move sendNotification out of recur, remove unused related_contact
  CRM/Core/Payment/PayPalIPN.php
  CRM/Core/Payment/PayPalProIPN.php
Labels: master

#19510 [REF] Extract logical functions from sendTemplate
  CRM/Core/BAO/MessageTemplate.php
Labels: master

#19516 APIv4 - Enable getFields to find fields across implicit FK joins
  Civi/Api4/Generic/DAOGetFieldsAction.php
  Civi/Api4/Service/Spec/RequestSpec.php
  tests/phpunit/api/v4/Action/GetExtraFieldsTest.php
Labels: has-test, master, sig:search-kit

#19517 Override the DrupalBase getUserObject function with a Drupal8/9 compa…
  CRM/Utils/System/Drupal8.php
Labels: master, merge on pass

#19514 APIv4 - Fix bug when using relative date filters in ON clause of a join
  Civi/Api4/Query/Api4SelectQuery.php
  tests/phpunit/api/v4/Action/DateTest.php
Labels: has-test, master, sig:search-kit

#19464 dev/core#2340 Skip rather than fail on bad menu item
  CRM/Core/Menu.php
Labels: master

#19520 5.34.0 release notes: final edits and late changes
  release-notes/5.34.0.md
Labels: 5.34

#19519 Afform GUI - Fix errors when creating & saving blocks
  ext/afform/admin/Civi/Api4/Action/Afform/LoadAdminData.php
  ext/afform/admin/ang/afGuiEditor.js
  ext/afform/admin/ang/afGuiEditor/afGuiEditor.component.js
  ext/afform/admin/ang/afGuiEditor/afGuiEntity.component.js
  ext/afform/admin/ang/afGuiEditor/elements/afGuiContainer.component.js
Labels: master, merge on pass

#19521 5.34
  release-notes/5.34.0.md
Labels: master

#19526 APIv4 - AJAX errors should say *something* useful
  CRM/Api4/Page/AJAX.php
Labels: master

#19494 (REF) APIv4 - Add hook for whitelisting select AJAX API's for anonymous invocation
  CRM/Api4/Permission.php
  CRM/Core/xml/Menu/Api4.xml
  CRM/Utils/Hook.php
  ext/afform/core/afform.php
  sql/civicrm_generated.mysql
Labels: master, merge ready

#19522 [REF] Further extract the portion of sendTemplate that relates to rendering
  CRM/Core/BAO/MessageTemplate.php
Labels: master

#19527 [REF] Complete order Unset contribution once we have finished with it.
  CRM/Contribute/BAO/Contribution.php
  CRM/Core/Payment/AuthorizeNetIPN.php
Labels: master

#19528 5.34.0 release notes: Miscategorized item
  release-notes/5.34.0.md
Labels: 5.34

#19463 Remove campaign_id pseudoconstants
  CRM/Activity/DAO/Activity.php
  CRM/Campaign/DAO/CampaignGroup.php
  CRM/Campaign/DAO/Survey.php
  CRM/Contribute/DAO/Contribution.php
  CRM/Contribute/DAO/ContributionPage.php
  CRM/Contribute/DAO/ContributionRecur.php
  CRM/Event/DAO/Event.php
  CRM/Event/DAO/Participant.php
  CRM/Mailing/DAO/Mailing.php
  CRM/Member/DAO/Membership.php
  CRM/Pledge/DAO/Pledge.php
  tests/phpunit/CRM/Core/PseudoConstantTest.php
  tests/phpunit/CRM/Export/BAO/ExportTest.php
  xml/schema/Activity/Activity.xml
  xml/schema/Campaign/CampaignGroup.xml
  xml/schema/Campaign/Survey.xml
  xml/schema/Contribute/Contribution.xml
  xml/schema/Contribute/ContributionPage.xml
  xml/schema/Contribute/ContributionRecur.xml
  xml/schema/Event/Event.xml
  xml/schema/Event/Participant.xml
  xml/schema/Mailing/Mailing.xml
  xml/schema/Member/Membership.xml
  xml/schema/Pledge/Pledge.xml
Labels: master

#19529 5.35.0 release notes - initial run
  release-notes.md
  release-notes/5.35.0.md
Labels: 5.35

#19533 APIv4 - Fix HTTP status code selection
  CRM/Api4/Page/AJAX.php
Labels: master, merge on pass

#19534 5.35
  release-notes.md
  release-notes/5.35.0.md
Labels: master

#19508 Fix display of membership dates on receipts when lineitems do not have a price_set_id
  CRM/Contribute/BAO/Contribution.php
Labels: master

#19535 dev/core#2360 - Escape the word `rows` in sql query
  Civi/Api4/Query/Api4SelectQuery.php
Labels: master

#19537 APIv4 - Increase alias max length to 256
  Civi/Api4/Query/Api4SelectQuery.php
  Civi/Api4/Query/SqlExpression.php
Labels: master, sig:search-kit

#19541 afform_mock - Hide extension. Clearly indicate as development-only
  ext/afform/mock/info.xml
Labels: master, merge on pass

#19542 [REF] Fix array access on NULL error when running afform unit tests o…
  ext/afform/core/Civi/Api4/Utils/AfformSaveTrait.php
Labels: master, merge on pass

#19530 Afform Gui - Block editing enhancements
  ext/afform/admin/Civi/AfformAdmin/AfformAdminMeta.php
  ext/afform/admin/Civi/Api4/Action/Afform/LoadAdminData.php
  ext/afform/admin/ang/afAdmin/afAdminList.controller.js
  ext/afform/admin/ang/afAdmin/afAdminList.html
  ext/afform/admin/ang/afGuiEditor.js
  ext/afform/admin/ang/afGuiEditor/afGuiEntity.component.js
  ext/afform/admin/ang/afGuiEditor/afGuiEntity.html
  ext/afform/admin/ang/afGuiEditor/afGuiSearch.component.js
  ext/afform/admin/ang/afGuiEditor/afGuiSearch.html
  ext/afform/admin/ang/afGuiEditor/elements/afGuiContainer.component.js
Labels: master

#19540 [REF] [Repeattransaction] Remove loading contribution page id from passed in object
  CRM/Contribute/BAO/Contribution.php
Labels: master

#19539 [REF] [Repeattransaction] use financial_type_id from getTemplateContribution (which already has handling)
  CRM/Contribute/BAO/Contribution.php
Labels: master

#19538 [REF] [Repeattransaction] Stop setting contribution->id
  CRM/Contribute/BAO/Contribution.php
Labels: master

#18830 put asset rendering call into a try/catch - dev/core #2137
  Civi/Core/AssetBuilder.php
Labels: master, merge on pass

#19546 APIv4 - Fix label_field to use underscore instead of camelCase
  Civi/Api4/Entity.php
  Civi/Api4/Generic/AbstractEntity.php
Labels: 5.35

#19548 5.35 to master
  Civi/Api4/Entity.php
  Civi/Api4/Generic/AbstractEntity.php
Labels: master

#19545 php 7.4 - E_NOTICE on membership dashboard
  CRM/Member/Selector/Search.php
Labels: master

#19524 [REF] Simplify is_email_receipt handling
  CRM/Core/Form.php
  CRM/Member/Form.php
  CRM/Member/Form/Membership.php
Labels: master, merge on pass

#19552 php 7.4 E_NOTICE in Contact/BAO/Query
  CRM/Contact/BAO/Query.php
Labels: master

#19553 dev/core#2308 - Fix Activity Import Parser test and convert to civi statics
  CRM/Activity/BAO/Activity.php
  tests/phpunit/CRM/Activity/Import/Parser/ActivityTest.php
Labels: master, merge on pass

#19509 Correct sms numbers
  CRM/Contact/Form/Task/SMSCommon.php
  tests/phpunit/CRM/Contact/Form/Task/SMSCommonTest.php
Labels: has-test, master

#19551 Add unit test cover for the MessageTemplate::renderMessageTemplate function
  CRM/Core/BAO/MessageTemplate.php
  CRM/Utils/Token.php
  tests/phpunit/CRM/Core/BAO/MessageTemplateTest.php
Labels: has-test, master

#19556 [REF] Rename variable to clarify it's usage
  CRM/Event/Form/Registration.php
  CRM/Price/BAO/PriceSet.php
Labels: master, sig-Refactor

#19555 [NFC/Unit Test] dev/core#2308 - Tests for activity import
  tests/phpunit/CRM/Activity/Import/Parser/ActivityTest.php
Labels: master

#19554 SearchKit - Add implicit joins for displaying labels of related entities
  ext/search/Civi/Search/Admin.php
  ext/search/ang/crmSearchAdmin/crmSearchAdmin.component.js
Labels: master

#19536 Afform (et al) - Fetch more complete list of permissions via APIv4
  CRM/Admin/Form/Navigation.php
  CRM/Core/Permission/Backdrop.php
  CRM/Core/Permission/Drupal.php
  CRM/Core/Permission/List.php
  CRM/Report/Form/Instance.php
  ext/afform/admin/Civi/AfformAdmin/AfformAdminMeta.php
Labels: master

#19525 [REF] Remove unused pcp & soft credit handling from previously shared code
  CRM/Member/Form/Membership.php
Labels: master

#19547 [REF] Fully remove contribution object from repeattransaction function
  CRM/Contribute/BAO/Contribution.php
  CRM/Contribute/BAO/ContributionRecur.php
  tests/phpunit/api/v3/ContributionTest.php
Labels: master

#19421 Cleanup towards dev/core#2308
  CRM/Activity/Import/Parser/Activity.php
Labels: master

#19560 Fix 'Unsupported html-element' error on forms using EntityFormTrait
  CRM/Core/Form/EntityFormTrait.php
Labels: master

#19563 Fix unreleased regression from mistake extracting function
  CRM/Core/BAO/MessageTemplate.php
Labels: 5.35, merge on pass

#19567 Remove unused code
  CRM/Contribute/BAO/Contribution.php
Labels: master, merge on pass

#19568 dev/core#2370 - Installer - Bump up entropy for autogenerated cred keys
  setup/plugins/installFiles/GenerateCredKey.civi-setup.php
Labels: master, merge on pass

#19573 dev/core#2370 - Installer - Bump up entropy for autogenerated cred keys
  setup/plugins/installFiles/GenerateCredKey.civi-setup.php
Labels: 5.35, merge on pass

#19575 Fix angular error when user is not logged in.
  CRM/Core/BAO/Dashboard.php
Labels: master

#19576 serialize as boolean setting value for checkbox in CRM_Admin_Form_Gen…
  CRM/Admin/Form/SettingTrait.php
Labels: master

#19565 Delete repeated title and fix some labels
  xml/schema/Activity/Activity.xml
  xml/schema/Campaign/Campaign.xml
  xml/schema/Case/Case.xml
  xml/schema/Contact/Contact.xml
  xml/schema/Contact/ContactType.xml
  xml/schema/Contact/DashboardContact.xml
  xml/schema/Contribute/Contribution.xml
  xml/schema/Contribute/ContributionPage.xml
  xml/schema/Contribute/ContributionSoft.xml
  xml/schema/Contribute/Product.xml
  xml/schema/Core/ActionSchedule.xml
  xml/schema/Core/County.xml
  xml/schema/Core/CustomField.xml
  xml/schema/Core/CustomGroup.xml
  xml/schema/Core/Email.xml
  xml/schema/Core/Job.xml
  xml/schema/Core/LocationType.xml
  xml/schema/Core/MappingField.xml
  xml/schema/Core/Menu.xml
  xml/schema/Core/OptionValue.xml
  xml/schema/Core/Phone.xml
  xml/schema/Core/PreferencesDate.xml
  xml/schema/Core/PrintLabel.xml
  xml/schema/Core/Setting.xml
  xml/schema/Core/Tag.xml
  xml/schema/Core/UFField.xml
  xml/schema/Core/UFGroup.xml
  xml/schema/Cxn/Cxn.xml
  xml/schema/Event/Event.xml
  xml/schema/Financial/PaymentProcessorType.xml
  xml/schema/Mailing/Component.xml
  xml/schema/Mailing/Mailing.xml
  xml/schema/Member/Membership.xml
  xml/schema/Member/MembershipStatus.xml
  xml/schema/Member/MembershipType.xml
  xml/schema/PCP/PCP.xml
  xml/schema/Price/LineItem.xml
  xml/schema/Price/PriceField.xml
  xml/schema/Price/PriceFieldValue.xml
  xml/schema/Price/PriceSet.xml
  xml/schema/SMS/History.xml
Labels: master

#19577 Apply bootstrap theme to searchKit dashlets
  CRM/Contact/Page/DashBoard.php
  ext/search/ang/crmSearchDisplayList.ang.php
  ext/search/ang/crmSearchDisplayTable.ang.php
Labels: master

#19581 REF Regenerate DAOs and I18n Schema Structure following merge of #19565
  CRM/Activity/DAO/Activity.php
  CRM/Campaign/DAO/Campaign.php
  CRM/Case/DAO/Case.php
  CRM/Contact/DAO/Contact.php
  CRM/Contact/DAO/ContactType.php
  CRM/Contact/DAO/DashboardContact.php
  CRM/Contribute/DAO/Contribution.php
  CRM/Contribute/DAO/ContributionPage.php
  CRM/Contribute/DAO/Product.php
  CRM/Core/DAO/ActionSchedule.php
  CRM/Core/DAO/CustomField.php
  CRM/Core/DAO/CustomGroup.php
  CRM/Core/DAO/Email.php
  CRM/Core/DAO/Job.php
  CRM/Core/DAO/LocationType.php
  CRM/Core/DAO/MappingField.php
  CRM/Core/DAO/Menu.php
  CRM/Core/DAO/OptionValue.php
  CRM/Core/DAO/Phone.php
  CRM/Core/DAO/PreferencesDate.php
  CRM/Core/DAO/PrintLabel.php
  CRM/Core/DAO/Setting.php
  CRM/Core/DAO/Tag.php
  CRM/Core/DAO/UFField.php
  CRM/Core/DAO/UFGroup.php
  CRM/Core/I18n/SchemaStructure.php
  CRM/Cxn/DAO/Cxn.php
  CRM/Event/DAO/Event.php
  CRM/Financial/DAO/PaymentProcessorType.php
  CRM/Mailing/DAO/Mailing.php
  CRM/Mailing/DAO/MailingComponent.php
  CRM/Member/DAO/Membership.php
  CRM/Member/DAO/MembershipStatus.php
  CRM/Member/DAO/MembershipType.php
  CRM/PCP/DAO/PCP.php
  CRM/Price/DAO/LineItem.php
  CRM/Price/DAO/PriceField.php
  CRM/Price/DAO/PriceFieldValue.php
  CRM/Price/DAO/PriceSet.php
Labels: master, merge on pass

#19583 dev/drupal#156 - system_get_info() is gone in drupal 9
  CRM/Core/Permission/Drupal8.php
Labels: master

#19562 APIv4 - Improve handling of joins & custom fields
  CRM/Core/SelectValues.php
  Civi/Api4/Query/Api4SelectQuery.php
  Civi/Api4/Service/Schema/Joiner.php
  Civi/Api4/Service/Schema/SchemaMapBuilder.php
  Civi/Api4/Service/Spec/SpecGatherer.php
  Civi/Api4/Utils/CoreUtil.php
  ext/search/ang/crmSearchAdmin/compose/criteria.html
  ext/search/ang/crmSearchAdmin/crmSearchAdmin.component.js
  tests/phpunit/api/v4/Action/BasicCustomFieldTest.php
  tests/phpunit/api/v4/Action/FkJoinTest.php
  tests/phpunit/api/v4/DataSets/DefaultDataSet.json
Labels: has-test, master, sig:search-kit

#19582 Remove check for safe_mode/open_basedir on extension downloader because it triggers false positives
  CRM/Extension/Downloader.php
Labels: master

#19586 [NFC] First Pass at 5.35 release notes
  contributor-key.yml
  release-notes/5.35.0.md
Labels: 5.35

#19592 5.35 to master
  contributor-key.yml
  release-notes/5.35.0.md
Labels: master

#19578 [REF] replace deprecated calls with buildOptions
  CRM/Contribute/Form/Contribution.php
Labels: master

#19544 dev/core#2365 - Delayed drawing of contribution charts seems unnecessary
  templates/CRM/common/chart.tpl
Labels: master

#19570 Cleanup - Remove old unused schema/xml files.
  xml/schema/Bridge/OG.xml
  xml/schema/Bridge/Role.xml
  xml/schema/Bridge/files.xml
  xml/schema/Contact/Household.xml
  xml/schema/Contact/Individual.xml
  xml/schema/Contact/Organization.xml
  xml/schema/Core/Preferences.xml
Labels: master

#19596 APIv4 - Add option lists to getFields html_type and data_type
  Civi/Api4/Generic/BasicGetFieldsAction.php
Labels: master

#19572 event#48: Fix partially paid events in a modal dialog
  templates/CRM/Event/Form/Participant.tpl
Labels: master

#19600 HttpTestTrait - Define helper methods for E2E tests of Civi's HTTP routes
  CRM/Utils/EchoLogger.php
  CRM/Utils/GuzzleMiddleware.php
  Civi/Test/GuzzleTestTrait.php
  Civi/Test/HttpTestTrait.php
Labels: has-test, master, merge on pass

#19594 dev/mail#89 Fix unreleased regression where civimember is not permitted/enabled
  CRM/Contact/BAO/Contact.php
  CRM/Member/BAO/Membership.php
Labels: 5.35

#19601 5.35
  CRM/Contact/BAO/Contact.php
  CRM/Member/BAO/Membership.php
Labels: master

#19602 Use specific function when formatting money for a default
  CRM/Core/BAO/CustomField.php
  CRM/Core/BAO/CustomGroup.php
  CRM/Member/Form/Membership.php
  CRM/Member/Form/MembershipConfig.php
  CRM/Member/Page/AJAX.php
  CRM/Member/Tokens.php
  CRM/PCP/Form/Campaign.php
Labels: master

#19595 [NFC] Code cleanup - use use statements, hints
  CRM/Activity/Tokens.php
  CRM/Contribute/Tokens.php
  CRM/Core/TokenTrait.php
Labels: master

#19593 Fix Redis deprecated warning
  CRM/Core/PrevNextCache/Redis.php
Labels: 5.35

#19588 core#2379 - avoid validation error on saving geocodes
  CRM/Core/BAO/Address.php
  tests/phpunit/CRM/Core/BAO/AddressTest.php
Labels: master

#19606 5.35
  CRM/Core/PrevNextCache/Redis.php
Labels: master

#19607 [NFC/Unit Test] Fix passing test that should pass but also should fail
  tests/phpunit/CRM/Case/BAO/CaseTest.php
Labels: master

#19604 core#2309: Validate weight and weight threshold
  CRM/Contact/Form/DedupeRules.php
Labels: master, merge on pass

#19571 [REF] Stop passing contribution into completeOrder, id is enough
  CRM/Contribute/BAO/Contribution.php
  CRM/Core/Payment/AuthorizeNetIPN.php
  CRM/Core/Payment/BaseIPN.php
  CRM/Core/Payment/PayPalIPN.php
  CRM/Core/Payment/PayPalProIPN.php
  CRM/Event/Form/Task/Batch.php
  api/v3/Contribution.php
Labels: master

#19599 Crypto - Add support for signing and verifying JSON Web Tokens
  CRM/Upgrade/Incremental/php/FiveThirtySix.php
  Civi/Core/Container.php
  Civi/Crypto/CryptoJwt.php
  Civi/Crypto/CryptoRegistry.php
  composer.json
  composer.lock
  setup/plugins/installFiles/GenerateSignKey.civi-setup.php
  setup/plugins/installFiles/InstallSettingsFile.civi-setup.php
  setup/src/Setup/Model.php
  templates/CRM/common/civicrm.settings.php.template
  tests/phpunit/Civi/Crypto/CryptoJwtTest.php
  tests/phpunit/Civi/Crypto/CryptoTestTrait.php
Labels: master

#19585 Search Kit - Use wrapper api to run searches
  Civi/Api4/Query/Api4SelectQuery.php
  ext/afform/core/Civi/Afform/AfformMetadataInjector.php
  ext/search/CRM/Search/Upgrader.php
  ext/search/Civi/Api4/Action/SearchDisplay/Run.php
  ext/search/Civi/Api4/SearchDisplay.php
  ext/search/Civi/Search/AfformSearchMetadataInjector.php
  ext/search/Civi/Search/Display.php
  ext/search/ang/crmSearchAdmin.module.js
  ext/search/ang/crmSearchAdmin/crmSearchAdmin.component.js
  ext/search/ang/crmSearchAdmin/crmSearchAdminDisplay.component.js
  ext/search/ang/crmSearchAdmin/crmSearchAdminDisplay.html
  ext/search/ang/crmSearchAdmin/crmSearchAdminDisplaySort.html
  ext/search/ang/crmSearchAdmin/displays/searchAdminDisplayList.component.js
  ext/search/ang/crmSearchAdmin/displays/searchAdminDisplayList.html
  ext/search/ang/crmSearchAdmin/displays/searchAdminDisplayTable.component.js
  ext/search/ang/crmSearchAdmin/displays/searchAdminDisplayTable.html
  ext/search/ang/crmSearchDisplay.module.js
  ext/search/ang/crmSearchDisplay/Pager.html
  ext/search/ang/crmSearchDisplayList/crmSearchDisplayList.component.js
  ext/search/ang/crmSearchDisplayList/crmSearchDisplayListItems.html
  ext/search/ang/crmSearchDisplayTable/crmSearchDisplayTable.component.js
  ext/search/ang/crmSearchDisplayTable/crmSearchDisplayTable.html
  ext/search/ang/crmSearchPage.module.js
  tests/phpunit/api/v4/Action/SqlFunctionTest.php
Labels: master

#19611 Add contactlayouteditor to gitignore
  .gitignore
Labels: master, merge on pass

#19613 Fix on recently merged asset builder catch patch
  Civi/Core/AssetBuilder.php
Labels: master, merge on pass

#19612 Afform - SearchKit support for calculated fields
  Civi/Api4/Query/Api4SelectQuery.php
  ext/afform/admin/Civi/Api4/Action/Afform/LoadAdminData.php
  ext/afform/admin/ang/afGuiEditor/afGuiSearch.component.js
  ext/afform/admin/ang/afGuiEditor/afGuiSearch.html
  ext/afform/admin/ang/afGuiEditor/elements/afGuiField.component.js
  ext/search/Civi/Api4/Action/SearchDisplay/Run.php
Labels: master

#19566 Remove always-true-if
  CRM/Member/Form/Membership.php
Labels: master

#18299 dev/core#1750: Replace Tokens In Activity Content for Sent Emails
  CRM/Activity/BAO/Activity.php
  templates/CRM/Contact/Form/Task/Email.hlp
  templates/CRM/Contact/Form/Task/Email.tpl
  tests/phpunit/CRM/Activity/BAO/ActivityTest.php
Labels: has-test, master

#19622 Remove empty {ts}
  templates/CRM/Admin/Form/Setting/SettingForm.tpl
Labels: master, merge on pass

#19614 Ensure dispatcher has loaded listeners
  Civi/Core/Container.php
Labels: master, merge ready

#19621 dev/core#2392 - Deprecated url parameters in contribution dashboard detail links
  CRM/Contribute/Page/DashBoard.php
Labels: master

#19617 dev/core#2389 SearchKit - Show edit link to searchDisplay afforms
  ext/search/ang/crmSearchAdmin/searchList.controller.js
  ext/search/ang/crmSearchAdmin/searchList.html
Labels: master

#19615 Joomla - Implement getUfId(). Fix `@user:<name>`.
  CRM/Utils/System/Joomla.php
Labels: master

#19598 Convert Smarty & domain token processing to use token processor
  CRM/Core/BAO/MessageTemplate.php
  tests/phpunit/CRM/Core/BAO/MessageTemplateTest.php
  tests/phpunit/CRM/Event/Form/Registration/ConfirmTest.php
  tests/phpunit/api/v3/ContributionTest.php
Labels: master

#19579 Afform - Allow public submission (PUB-CONTACT). Expand E2E test coverage.
  ext/afform/admin/ang/afGuiEditor/afGuiEditor.component.js
  ext/afform/admin/ang/afGuiEditor/entityConfig/Generic.html
  ext/afform/core/CRM/Afform/ArrayHtml.php
  ext/afform/core/Civi/Afform/Event/AfformBaseEvent.php
  ext/afform/core/Civi/Afform/Event/AfformSubmitEvent.php
  ext/afform/core/Civi/Afform/FormDataModel.php
  ext/afform/core/Civi/Api4/Action/Afform/AbstractProcessor.php
  ext/afform/core/Civi/Api4/Action/Afform/Prefill.php
  ext/afform/core/Civi/Api4/Action/Afform/Submit.php
  ext/afform/core/tests/phpunit/Civi/Afform/FormDataModelTest.php
  ext/afform/mock/README.md
  ext/afform/mock/ang/mockPublicForm.aff.html
  ext/afform/mock/ang/mockPublicForm.aff.json
  ext/afform/mock/ang/mockPublicForm.test.php
  ext/afform/mock/phpunit.xml.dist
  ext/afform/mock/tests/phpunit/Civi/AfformMock/FormTestCase.php
  ext/afform/mock/tests/phpunit/api/v4/formatExamples/entity-security.php
Labels: master, merge on pass

#19634 dev/financial#166 Clean up money formatting in iif
  CRM/Financial/BAO/ExportFormat/IIF.php
Labels: master, merge on pass

#19625 Fix incorrect use of ts when setting custom data form title
  CRM/Contact/Form/CustomData.php
Labels: master

#19608 WordPress - If we hit a "permission denied" error, return HTTP 403
  CRM/Utils/System/WordPress.php
Labels: master, merge ready

#19597 [REF] simplify parameter, use preferred strict
  CRM/Activity/Tokens.php
Labels: master

#19620 Search kit select current user
  ang/api4Explorer/Explorer.js
  ext/search/ang/crmSearchActions/crmSearchInput/crmSearchInputVal.component.js
  ext/search/ang/crmSearchActions/crmSearchInput/entityRef.html
  js/Common.js
Labels: master

#19636 dev/core#2398 - Fix save'n'test button on mail account form
  CRM/Admin/Form/MailSettings.php
Labels: master

#19631 SearchKit - Enable links for implicit joins
  ext/search/Civi/Api4/Action/SearchDisplay/Run.php
  ext/search/Civi/Search/Admin.php
  ext/search/ang/crmSearchAdmin.module.js
  ext/search/ang/crmSearchAdmin/crmSearchAdmin.component.js
  ext/search/ang/crmSearchAdmin/crmSearchAdminLinkSelect.component.js
Labels: master

#19637 dev/event#50 - Non static function called statically for event ical downloads
  CRM/Event/ICalendar.php
Labels: master

#19348 Show Contact age on deceased date
  CRM/Contact/BAO/Contact.php
  CRM/Utils/Date.php
  templates/CRM/Contact/Page/Inline/Demographics.tpl
  tests/phpunit/CRM/Contact/BAO/ContactTest.php
Labels: has-test, master

#19609 [NFC/Unit Test] dev/core#2385 - Add test for getCaseActivityQuery
  tests/phpunit/CRM/Case/BAO/CaseTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: master

#19640 Remove single use of extraParams in CRM_Utils_Token::getTokenDetails()
  CRM/Contact/BAO/Contact/Utils.php
  CRM/Utils/Token.php
Labels: master

#19618 dev/core#2388 SearchKit - Fix display of pseudoconstant fields
  ext/search/ang/crmSearchAdmin/crmSearchAdmin.component.js
Labels: master

#19626 SearchKit - Add links to view multi-record custom data
  CRM/Contact/Page/View/CustomData.php
  Civi/Api4/Action/Entity/Get.php
Labels: master

#19605 dev/translation#65 Further remove moneyValueFormat
  CRM/Admin/Form/Setting/Localization.php
  CRM/Utils/Money.php
  api/v3/examples/Setting/GetFields.ex.php
  templates/CRM/Admin/Form/Setting/Localization.tpl
Labels: master

#19633 [Regression] campaign name no longer accepted
  api/v3/Generic.php
  api/v3/utils.php
  tests/phpunit/api/v3/MailingTest.php
Labels: master, merge on pass

#19647 Remove unreachable code & variable cleanup in membership back office form template
  templates/CRM/Member/Form/Membership.tpl
Labels: master, merge on pass

#19646 [REF] Remove unused variables
  templates/CRM/Member/Form/Membership.tpl
Labels: master

#19649 Mark Old Cividiscount hook support deprecated
  templates/CRM/Form/body.tpl
Labels: master

#19549 [REF] Use form property rather than formValues to pass generated invoice ID on membership forms
  CRM/Contribute/Form/AbstractEditPayment.php
  CRM/Member/Form/Membership.php
  CRM/Member/Form/MembershipRenewal.php
Labels: master

#19651 Fix i18n issue with changeLog in data templates
  xml/templates/civicrm_data.tpl
Labels: master

#19652 Use specific function when formatting money for a default
  CRM/Contribute/Form/Contribution.php
  CRM/Contribute/Form/Contribution/Main.php
  CRM/Contribute/Form/ContributionPage.php
  CRM/Contribute/Form/ContributionPage/Amount.php
  CRM/Contribute/Form/SoftCredit.php
  CRM/Event/Form/ManageEvent/Fee.php
  CRM/Member/Form/MembershipRenewal.php
  CRM/Pledge/Form/Pledge.php
  CRM/Price/Form/Field.php
Labels: master

#19653 dev/core#2360 - Escape the word `rows` in sql query
  Civi/Api4/Query/Api4SelectQuery.php
Labels: 5.35, merge on pass

#19648 dev/core#778 Do not increment tax on validation error
  CRM/Member/Form/Membership.php
  templates/CRM/Member/Form/Membership.tpl
Labels: master

#19654 [REF] Simplfy parameter
  CRM/Member/Form.php
  CRM/Member/Form/Membership.php
Labels: master

#19657 dev/core#2404 - Afform - Resolve ambiguity of omitted permissions
  ext/afform/admin/ang/afGuiEditor/config-form.html
  ext/afform/core/CRM/Afform/AfformScanner.php
Labels: master

#19645 Afform - Add 'View Page' link from afform edit screen
  ext/afform/admin/ang/afAdmin/afAdminList.html
  ext/afform/admin/ang/afGuiEditor/afGuiEditor.component.js
  ext/afform/admin/ang/afGuiEditor/afGuiEditorCanvas.html
  ext/afform/admin/ang/afGuiEditor/elements/afGuiContainer.html
  ext/afform/admin/ang/afGuiEditor/saveBlock.html
Labels: master

#19650 Enable-"Do-no-trade"-filter
  CRM/Report/Form.php
Labels: master

#19643 SearchKit - Don't save on enter key
  ext/search/ang/crmSearchAdmin/compose/controls.html
  ext/search/ang/crmSearchAdmin/compose/criteria.html
  ext/search/ang/crmSearchAdmin/crmSearchAdmin.html
  ext/search/ang/crmSearchAdmin/crmSearchClause.html
  ext/search/ang/crmSearchAdmin/displays/searchAdminDisplayList.html
  ext/search/ang/crmSearchAdmin/displays/searchAdminDisplayTable.html
  ext/search/ang/crmSearchAdmin/tabs.html
Labels: master
