Repository civicrm/civicrm-core, pull requests merged in 2021-04, with the labels that each got.

#19911 [REF] [Towards membership api] more consistent handling on amount
  CRM/Member/Form/Membership.php
Labels: master

#19949 [REF] Minor cleanup - strictness & formatting
  CRM/Dedupe/Merger.php
  api/v3/Contact.php
Labels: master

#19962 Fix for dev/core#2503
  CRM/Report/Form.php
Labels: master

#18982 dev/wordpress#82 Add support for creating WordPress accounts from the contact record
  CRM/Contact/Form/Task/Useradd.php
  CRM/Utils/System/WordPress.php
Labels: master, merge ready

#19963 Proposed fix for CORE-2164
  CRM/Export/BAO/ExportProcessor.php
  tests/phpunit/CRM/Export/BAO/ExportTest.php
Labels: master, merge on pass

#19948 dev/financial#172 - Warning when saving a contribution with a recognition date
  CRM/Contribute/Form/Contribution.php
Labels: master

#19920 Upgrader - Display note about token formatting
  CRM/Upgrade/Incremental/php/FiveThirtySeven.php
Labels: master

#19317 dev/core#2285 Fix civicrm_alterReportVar hook for contribute detail r…
  CRM/Report/Form/Contribute/Detail.php
  tests/phpunit/CRM/Report/Form/Contribute/DetailTest.php
  tests/phpunit/CRM/Report/Form/Contribute/fixtures/value_extension_tng55_table.sql
Labels: has-test, master

#19907 APIv4 - Add CiviCase, CaseType, CaseContact entities
  CRM/Case/BAO/Case.php
  CRM/Case/BAO/CaseType.php
  CRM/Case/DAO/CaseType.php
  CRM/Upgrade/Incremental/sql/5.37.alpha1.mysql.tpl
  Civi/Api4/Action/CiviCase/CiviCaseSaveTrait.php
  Civi/Api4/Action/CiviCase/Create.php
  Civi/Api4/Action/CiviCase/Save.php
  Civi/Api4/Action/CiviCase/Update.php
  Civi/Api4/Action/GetActions.php
  Civi/Api4/CaseContact.php
  Civi/Api4/CaseType.php
  Civi/Api4/CiviCase.php
  Civi/Api4/Generic/BasicGetFieldsAction.php
  Civi/Api4/Generic/Traits/DAOActionTrait.php
  Civi/Api4/Service/Spec/FieldSpec.php
  Civi/Api4/Service/Spec/Provider/CaseCreationSpecProvider.php
  Civi/Api4/Service/Spec/Provider/CaseTypeGetSpecProvider.php
  Civi/Api4/Utils/FormattingUtil.php
  api/v3/CaseType.php
  tests/phpunit/api/v4/DataSets/ConformanceTest.json
  tests/phpunit/api/v4/Entity/ConformanceTest.php
  tests/phpunit/api/v4/Service/TestCreationParameterProvider.php
  xml/schema/Case/CaseType.xml
Labels: master

#19961 dev/core#2502 Proposed fix/workaround for CORE-2502
  CRM/Contact/BAO/Query.php
Labels: master

#19959 SearchKit - Support implied operators in exposed search forms
  ext/afform/admin/Civi/AfformAdmin/AfformAdminMeta.php
  ext/afform/admin/ang/afGuiEditor.css
  ext/afform/admin/ang/afGuiEditor/afGuiEditor.component.js
  ext/afform/admin/ang/afGuiEditor/afGuiEntity.component.js
  ext/afform/admin/ang/afGuiEditor/afGuiSearch.component.js
  ext/afform/admin/ang/afGuiEditor/elements/afGuiButton-menu.html
  ext/afform/admin/ang/afGuiEditor/elements/afGuiContainer-menu.html
  ext/afform/admin/ang/afGuiEditor/elements/afGuiField-menu.html
  ext/afform/admin/ang/afGuiEditor/elements/afGuiField.component.js
  ext/afform/admin/ang/afGuiEditor/elements/afGuiMarkup-menu.html
  ext/afform/admin/ang/afGuiEditor/elements/afGuiText-menu.html
  ext/afform/admin/ang/afGuiEditor/inputType/CheckBox.html
  ext/afform/admin/ang/afGuiEditor/inputType/Date.html
  ext/afform/admin/ang/afGuiEditor/inputType/Number.html
  ext/afform/admin/ang/afGuiEditor/inputType/Radio.html
  ext/afform/admin/ang/afGuiEditor/inputType/Select.html
  ext/afform/admin/ang/afGuiEditor/inputType/Text.html
  ext/afform/core/Civi/Afform/AfformMetadataInjector.php
  ext/afform/core/ang/af/afField.component.js
  ext/afform/core/ang/af/afField.html
  ext/afform/core/ang/af/fields/ChainSelect.html
  ext/afform/core/ang/af/fields/CheckBox.html
  ext/afform/core/ang/af/fields/Date.html
  ext/afform/core/ang/af/fields/Number.html
  ext/afform/core/ang/af/fields/Radio.html
  ext/afform/core/ang/af/fields/RichTextEditor.html
  ext/afform/core/ang/af/fields/Select.html
  ext/afform/core/ang/af/fields/Text.html
  ext/afform/core/ang/afCore.css
  ext/search/Civi/Api4/Action/SearchDisplay/Run.php
  ext/search/phpunit.xml.dist
  ext/search/tests/phpunit/api/v4/SearchDisplay/SearchRunTest.php
  ext/search/tests/phpunit/bootstrap.php
Labels: has-test, master, merge ready, sig:search-kit

#19971 Remove empty setUp() functions
  tests/phpunit/CRM/Custom/Form/OptionTest.php
  tests/phpunit/CRM/Custom/Page/AJAXTest.php
  tests/phpunit/CRM/Event/Form/Registration/RegistrationTest.php
  tests/phpunit/CRM/Extension/BrowserTest.php
  tests/phpunit/CRM/Extension/Container/BasicTest.php
  tests/phpunit/CRM/Extension/Container/CollectionTest.php
  tests/phpunit/CRM/Extension/Container/StaticTest.php
  tests/phpunit/CRM/Financial/BAO/FinancialItemTest.php
  tests/phpunit/CRM/Financial/BAO/PaymentProcessorTest.php
  tests/phpunit/CRM/Financial/BAO/PaymentProcessorTypeTest.php
  tests/phpunit/CRM/Mailing/BAO/MailingTest.php
  tests/phpunit/CRM/Mailing/BAO/QueryTest.php
  tests/phpunit/CRM/Member/StatusOverrideTypesTest.php
  tests/phpunit/CRM/UF/Page/ProfileEditorTest.php
  tests/phpunit/CRM/Utils/AddressTest.php
  tests/phpunit/CRM/Utils/Check/Component/EnvTest.php
  tests/phpunit/CRM/Utils/Check/Component/OptionGroupsTest.php
  tests/phpunit/CRM/Utils/HtmlToTextTest.php
  tests/phpunit/CRM/Utils/RestTest.php
  tests/phpunit/CRM/Utils/RuleTest.php
  tests/phpunit/CRM/Utils/SignerTest.php
  tests/phpunit/CRM/Utils/StringTest.php
  tests/phpunit/CRM/Utils/SystemTest.php
  tests/phpunit/CRM/Utils/TypeTest.php
  tests/phpunit/Civi/API/Subscriber/WhitelistSubscriberTest.php
Labels: master, merge on pass

#19628 dev/core#2383 fix for contact custom data date field not working in scheduled reminder
  CRM/Core/BAO/ActionSchedule.php
Labels: master

#19904 [REF] [Search-kit-actions] Cleanup around contribution pdf common
  CRM/Contribute/Form/Task.php
  CRM/Contribute/Form/Task/PDF.php
  CRM/Contribute/Form/Task/PDFLetterCommon.php
  CRM/Contribute/Form/Task/TaskTrait.php
Labels: master

#19820 dev/core#2450 - Update source/target contacts on contribution updates
  CRM/Contribute/BAO/Contribution.php
  tests/phpunit/CRM/Contribute/BAO/ContributionTest.php
Labels: has-test, master

#19922 AngularJS - Allow loading multiple apps on a single page
  CRM/Api4/Page/Api4Explorer.php
  CRM/Contact/Page/DashBoard.php
  CRM/Core/Region.php
  CRM/Export/Form/Map.php
  Civi/Angular/AngularLoader.php
  Civi/Core/Container.php
  ang/crmDashboard.ang.php
  ext/afform/admin/CRM/AfformAdmin/Page/Base.php
  ext/search/CRM/Search/Page/Admin.php
  ext/search/CRM/Search/Page/Search.php
  js/crm-angularjs-loader.js
  templates/CRM/Export/Form/Map.tpl
Labels: master, merge ready

#19968 dev/user-interface#35 civicrm.css: add support for mobile devices on forms
  css/civicrm.css
Labels: master, merge ready

#19977 5.36.0 release notes initial run
  release-notes.md
  release-notes/5.36.0.md
Labels: 5.36

#19979 5.36 to master
  release-notes.md
  release-notes/5.36.0.md
Labels: master

#19974 Phpunit 8 support - add void to setup
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: master

#19970 dev/core#2488 - When setting default optionValue, limit query to specified domain
  CRM/Core/BAO/OptionValue.php
Labels: master

#19550 Convert token processing to use token processor
  CRM/Core/BAO/MessageTemplate.php
  tests/phpunit/CRM/Core/BAO/MessageTemplateTest.php
Labels: has-test, master

#19976 Fix re-calculation of payment dates on pledge
  CRM/Pledge/BAO/Pledge.php
Labels: master

#19946 (NFC) Add FUNDING.yml to display a SPONSOR link that directs to c.o
  .github/FUNDING.yml
Labels: master

#19934 dev/core#2487 Update defaults for civicrm_contribution_recur table
  CRM/Contribute/DAO/ContributionRecur.php
  CRM/Upgrade/Incremental/php/FiveThirtySeven.php
  xml/schema/Contribute/ContributionRecur.xml
Labels: master

#19980 [REF] Minor cleanup - remove unused variables
  CRM/Dedupe/MergeHandler.php
Labels: master, merge on pass

#19887 Embed afforms & search displays on contact summary screen as blocks and tabs
  ext/afform/admin/Civi/AfformAdmin/AfformAdminMeta.php
  ext/afform/admin/ang/afGuiEditor.js
  ext/afform/admin/ang/afGuiEditor/afGuiEditor.component.js
  ext/afform/admin/ang/afGuiEditor/config-form.html
  ext/afform/core/Civi/Api4/Afform.php
  ext/afform/core/afform.php
  ext/afform/core/templates/afform/contactSummary/AfformBlock.tpl
  ext/afform/core/templates/afform/contactSummary/AfformTab.tpl
  ext/search/Civi/Api4/Action/SearchDisplay/Run.php
  ext/search/ang/crmSearchDisplay.module.js
  ext/search/ang/crmSearchDisplayList/crmSearchDisplayList.component.js
  ext/search/ang/crmSearchDisplayTable/crmSearchDisplayTable.component.js
Labels: master

#19927 Add entity financial account bridge entity
  CRM/Financial/BAO/EntityFinancialAccount.php
  CRM/Financial/DAO/EntityFinancialAccount.php
  Civi/Api4/EntityFinancialAccount.php
  tests/phpunit/api/v3/PaymentProcessorTypeTest.php
  xml/schema/Financial/EntityFinancialAccount.xml
Labels: master

#19983 [NFC] 5.36 release notes
  contributor-key.yml
  release-notes/5.36.0.md
Labels: 5.36

#19985 5.36 to master
  contributor-key.yml
  release-notes/5.36.0.md
Labels: master

#19981 Fix scrollbars on fullscreen dashboard dashlet
  ang/crmDashboard/FullscreenDialog.html
Labels: master

#19978 dev/core#2425 - php 7.4 - E_NOTICE every time you save a contribution
  CRM/Contribute/Form/Contribution.php
  CRM/Financial/BAO/FinancialAccount.php
  tests/phpunit/CRM/Contribute/Form/ContributionTest.php
Labels: has-test, master

#19687 Afform - Support embedding forms via WP shortcodes.
  api/v3/Generic/Getlist.php
  ext/afform/core/afform.php
  ext/afform/core/api/v3/Afform.php
  js/Common.js
Labels: master

#19987 Activity type weights
  CRM/Upgrade/Incremental/sql/5.37.alpha1.mysql.tpl
  xml/templates/civicrm_data.tpl
Labels: master, merge on pass

#19990 Pledge - Fix re-calculation of payment dates
  CRM/Pledge/BAO/Pledge.php
Labels: 5.36

#19984 SearchKit - Apply filters to ON clause of EXCLUDE joins
  ext/search/Civi/Api4/Action/SearchDisplay/Run.php
Labels: master

#19993 APIv4 - Prevent api adding default join conditions when it shouldn't
  Civi/Api4/Query/Api4SelectQuery.php
Labels: master, merge on pass

#19992 dev/core#2442 - Missing sample data update for activity contact weights
  sql/civicrm_generated.mysql
Labels: master, merge on pass

#19969 E-notice fix on serialized setting
  CRM/Admin/Form/SettingTrait.php
Labels: master

#19967 Create reCAPTCHA core extension
  .gitignore
  CRM/Admin/Form/Setting/Miscellaneous.php
  CRM/Core/xml/Menu/Admin.xml
  CRM/Upgrade/Incremental/php/FiveThirtySeven.php
  bin/regen.sh
  ext/recaptcha/CRM/Utils/ReCAPTCHA.php
  ext/recaptcha/LICENSE.txt
  ext/recaptcha/README.md
  ext/recaptcha/info.xml
  ext/recaptcha/recaptcha.civix.php
  ext/recaptcha/recaptcha.php
  ext/recaptcha/settings/recaptcha.setting.php
  ext/recaptcha/templates/CRM/common/ReCAPTCHA.tpl
  ext/recaptcha/xml/Menu/recaptcha.xml
  settings/Core.setting.php
  sql/civicrm_generated.mysql
  templates/CRM/Admin/Form/Setting/Miscellaneous.tpl
  templates/CRM/Admin/Page/ConfigTaskList.tpl
  templates/CRM/Admin/Page/Setting.tpl
  templates/CRM/UF/Form/Group.hlp
  xml/templates/civicrm_data.tpl
  xml/templates/civicrm_navigation.tpl
Labels: master, merge on pass

#19543 replaceOrgTokens: Remove broken code
  CRM/Utils/Token.php
Labels: master, merge on pass

#19996 Rename 'Misc' menu item machine name to a safe string
  CRM/Upgrade/Incremental/php/FiveThirtySeven.php
  sql/civicrm_generated.mysql
  xml/templates/civicrm_navigation.tpl
Labels: master

#19995 dev/core#2501 - api uf_group.create overwrites existing fields when updating if they aren't specified
  CRM/Core/BAO/UFGroup.php
  tests/phpunit/api/v3/UFGroupTest.php
Labels: master

#19997 Afform - Fix endless spinner on "New Search Display" dropdown
  ext/afform/admin/ang/afAdmin/afAdminList.controller.js
  ext/afform/admin/ang/afAdmin/afAdminList.html
Labels: 5.37

#19998 Afform - Refresh assetBuilder when saving a form
  Civi/Angular/Manager.php
  ext/afform/core/Civi/Api4/Utils/AfformSaveTrait.php
Labels: 5.37, merge on pass

#19999 Add recaptcha to distmaker
  distmaker/dists/common.sh
Labels: 5.37, merge on pass

#20000 5.37
  Civi/Angular/Manager.php
  distmaker/dists/common.sh
  ext/afform/admin/ang/afAdmin/afAdminList.controller.js
  ext/afform/admin/ang/afAdmin/afAdminList.html
  ext/afform/core/Civi/Api4/Utils/AfformSaveTrait.php
Labels: master

#19890 File CustomField: avoid renaming an empty file
  CRM/Core/BAO/CustomField.php
Labels: master

#19966 [REF] [Towards membership api] extract getContributionSource
  CRM/Member/Form/Membership.php
Labels: master

#19848 Add support for receipt task outside the search process
  CRM/Contribute/Controller/Task.php
  CRM/Contribute/Form/Task/PDF.php
  CRM/Contribute/Selector/Search.php
  CRM/Contribute/Task.php
  CRM/Contribute/xml/Menu/Contribute.xml
  CRM/Core/Controller/Task.php
Labels: master

#19965 Remove reference to trxn_id, not on form, from previously shared code
  CRM/Member/Form/Membership.php
Labels: master

#19964 Membership form Remove check for installments as not on the form (copied from shared code)
  CRM/Member/Form/Membership.php
Labels: master

#20003 SearchKit - Fix broken export action
  ext/search/Civi/Api4/Action/SearchDisplay/GetSearchTasks.php
Labels: 5.37

#20005 5.37 to master
  ext/search/Civi/Api4/Action/SearchDisplay/GetSearchTasks.php
Labels: master

#20004 SearchKit - Make contribution tasks available as actions
  CRM/Contribute/Task.php
  ext/search/Civi/Api4/Action/SearchDisplay/GetSearchTasks.php
Labels: master, merge on pass

#19902 [REF] [Towards membership api] Simplify determination on contribution recur contact id
  CRM/Member/Form.php
  CRM/Member/Form/Membership.php
  CRM/Member/Form/MembershipRenewal.php
  tests/phpunit/CRM/Member/Form/MembershipRenewalTest.php
  tests/phpunit/CRM/Member/Form/MembershipTest.php
Labels: master

#20006 [NFC] [Test] Minor preliminary cleanup
  tests/phpunit/api/v3/PaymentTest.php
Labels: master, merge on pass

#20010 [Ref] One more place to use total fn
  CRM/Member/Form/Membership.php
Labels: master, merge on pass

#20009 dev/report#53 APIv4 - Add CaseActivity entity
  Civi/Api4/CaseActivity.php
Labels: 5.37, merge on pass

#20015 5.37 to master
  Civi/Api4/CaseActivity.php
Labels: master

#19718 dev/core#2436 On WordPress, redirect back to the event registration o…
  CRM/Utils/System/Base.php
  CRM/Utils/System/WordPress.php
Labels: master

#20013 Move tpl assignment to email function
  CRM/Member/Form/Membership.php
Labels: master, merge on pass

#20016 dev/core#2502 Add unit test to lock in fix on tag searching in search…
  tests/phpunit/CRM/Contact/SelectorTest.php
Labels: has-test, master, merge on pass

#20012 [NFC] [Test] Preliminary cleanup
  tests/phpunit/CRM/Member/BAO/MembershipTest.php
Labels: master

#20007 Extract out getReceiveDate
  CRM/Member/Form/Membership.php
Labels: master

#19903 [REF] [ipn] Simplification around contributionRecur ID
  CRM/Core/Payment/PayPalIPN.php
  tests/phpunit/CRM/Core/Payment/PayPalIPNTest.php
Labels: master

#19972 Add unit test for core#19628
  tests/phpunit/CRM/Core/BAO/ActionScheduleTest.php
Labels: has-test, master, merge on pass

#20011 Migrate current recaptcha library into extension and fix a couple of …
  ext/recaptcha/CRM/Utils/ReCAPTCHA.php
  ext/recaptcha/lib/recaptcha/LICENSE
  ext/recaptcha/lib/recaptcha/recaptchalib.php
Labels: 5.37

#20008 Fix Payment.create to update (recalculate) contribution fee_amount
  CRM/Financial/BAO/Payment.php
  tests/phpunit/api/v3/PaymentTest.php
Labels: has-test, master

#20025 Soft credit fails when membership is created using backend form
  CRM/Member/Form/Membership.php
  tests/phpunit/CRM/Member/Form/MembershipTest.php
Labels: 5.37

#20027 5.37 to master
  CRM/Member/Form/Membership.php
  ext/recaptcha/CRM/Utils/ReCAPTCHA.php
  ext/recaptcha/lib/recaptcha/LICENSE
  ext/recaptcha/lib/recaptcha/recaptchalib.php
  tests/phpunit/CRM/Member/Form/MembershipTest.php
Labels: master

#20021 Add payment_status in default doPayment per dev/financial#141
  CRM/Core/Payment.php
Labels: master

#20028 Soft credit fails when membership is created using backend form
  CRM/Member/Form/Membership.php
  tests/phpunit/CRM/Member/Form/MembershipTest.php
Labels: 5.36

#20031 SearchKit - Flush Angular cache when saving
  CRM/Contact/BAO/SavedSearch.php
Labels: 5.37

#20032 5.37 to master
  CRM/Contact/BAO/SavedSearch.php
Labels: master

#20022 Use propertyBag in doPayment
  CRM/Core/Payment.php
Labels: master

#20020 Make it clear that doDirectPayment/doTransferCheckout are deprecated …
  CRM/Core/Payment.php
Labels: master

#20033 dev/report#58 SearchKit - Rename 'Filters' to 'Having' for clarity
  ext/search/ang/crmSearchAdmin/compose/criteria.html
Labels: 5.37

#20034 5.37 to master
  ext/search/ang/crmSearchAdmin/compose/criteria.html
Labels: master

#20023 Add installments to propertyBag
  Civi/Payment/PropertyBag.php
Labels: master

#20030 Initial refactor of PayPal core processor to stop using doDirectPayment/doTransferCheckout
  CRM/Core/Payment/PayPalImpl.php
Labels: master

#20019 Use standard function to add reCAPTCHA to PCPAccount form
  CRM/PCP/Form/PCPAccount.php
Labels: 5.37

#20039 5.37
  CRM/PCP/Form/PCPAccount.php
Labels: master

#20037 Add amount as standard property to PaymentPropertyBag
  Civi/Payment/PropertyBag.php
Labels: master, merge on pass

#20017 [REF] Simplify interaction with contributionRecur
  CRM/Member/Form/Membership.php
Labels: master

#19917 [REF] Fix error where entryURL does not contain id of the contributio…
  CRM/Core/Controller.php
Labels: master

#20038 Suppress legacy warnings by default in propertyBag to allow transition to propertyBag without hitting legacy warnings on unconverted payment processors
  Civi/Payment/PropertyBag.php
  tests/phpunit/Civi/Payment/PropertyBagTest.php
Labels: master, merge on pass

#20029 Convert Dummy payment processor to use doPayment function
  CRM/Core/Payment/Dummy.php
  tests/phpunit/CRM/Contribute/Form/ContributionTest.php
  tests/phpunit/api/v3/ContributionPageTest.php
Labels: master, merge on pass

#20048 APIv4 - Fix unserialize settings
  Civi/Api4/Action/Setting/Get.php
  tests/phpunit/api/v4/Entity/SettingTest.php
Labels: has-test, master

#20042 Afform - Improve integration with ContactLayout editor
  CRM/Core/OptionValue.php
  Civi/Api4/Generic/BasicGetFieldsAction.php
  ext/afform/admin/Civi/AfformAdmin/AfformAdminMeta.php
  ext/afform/core/Civi/Api4/Afform.php
  ext/afform/core/afform.php
  ext/afform/core/managed/AfformType.mgd.php
Labels: master

#20045 Update WP permission page for new string array keys
  CRM/ACL/Form/WordPress/Permissions.php
Labels: master

#20050 Fix entity-ref search by id & update search prompt
  CRM/Core/Resources.php
  api/v3/Generic/Getlist.php
Labels: 5.37, merge on pass

#20052 Fix entity-ref search by id & update search prompt
  CRM/Core/Resources.php
  api/v3/Generic/Getlist.php
Labels: 5.36, merge on pass

#19975 dev/core#2512 Set membership's status properly when recording the payment
  CRM/Contribute/BAO/Contribution.php
  tests/phpunit/CRM/Contribute/Form/AdditionalPaymentTest.php
Labels: has-test, master

#20062 Revert "dev/core#2512 Set membership's status properly when recording the payment"
  CRM/Contribute/BAO/Contribution.php
  tests/phpunit/CRM/Contribute/Form/AdditionalPaymentTest.php
Labels: master

#20057 Fix issues with "Create User Record" process
  CRM/Utils/System/WordPress.php
Labels: 5.37, merge on pass, merge ready

#20060 dev/core#2509 - Search kit display link for grant view is wrong
  xml/schema/Grant/Grant.xml
Labels: master

#20054 When generating boilerplate code from xml, make error text more helpful and spelt correckly
  CRM/Core/CodeGen/Specification.php
Labels: master

#20061 Add pager to bottom of Manage Contribution Pages
  templates/CRM/Contribute/Page/ContributionPage.tpl
Labels: master

#20056 APIv4 - Improve entity name lookup
  Civi/Api4/Utils/CoreUtil.php
  tests/phpunit/api/v4/Utils/CoreUtilTest.php
Labels: has-test, master

#20051 5.37
  CRM/Core/Resources.php
  CRM/Utils/System/WordPress.php
  api/v3/Generic/Getlist.php
Labels: master

#20043 (REF) Payflow Pro - Migrate code into a core extension
  .gitignore
  CRM/Upgrade/Incremental/php/FiveThirtyEight.php
  distmaker/dists/common.sh
  ext/payflowpro/CRM/Core/Payment/PayflowPro.mgd.php
  ext/payflowpro/CRM/Core/Payment/PayflowPro.php
  ext/payflowpro/LICENSE.txt
  ext/payflowpro/README.md
  ext/payflowpro/images/screenshot.png
  ext/payflowpro/info.xml
  ext/payflowpro/payflowpro.civix.php
  ext/payflowpro/payflowpro.php
  ext/payflowpro/phpunit.xml.dist
  ext/payflowpro/tests/phpunit/CRM/Core/Payment/PayflowProTest.php
  ext/payflowpro/tests/phpunit/bootstrap.php
  sql/civicrm_generated.mysql
  xml/templates/civicrm_data.tpl
Labels: master

#20066 dev/core#2528 Set Modified date to be current timestamp in civicrm_co…
  CRM/Upgrade/Incremental/php/FiveThirtySeven.php
Labels: 5.37, merge on pass

#20040 dev/core#2493 Stop attempting to format money in the processor class
  CRM/Core/Payment.php
Labels: 5.37

#20069 Removed limit of 25 groups and past mailings
  ang/crmMailing/services.js
Labels: master, merge on pass

#20072 APIv4 - Fix Setting api to work with index param
  api/api.php
  tests/phpunit/api/v4/Entity/SettingTest.php
Labels: has-test, master, merge on pass

#20014 [Ref] Simplify getMembershipParameters
  CRM/Member/Form/Membership.php
Labels: master

#20073 dev/event#53 Fix issue where by Sold out option was not being properl…
  CRM/Price/BAO/PriceField.php
Labels: 5.37, merge on pass

#20074 REF Ensure that getAmount includes 0s in decimal places up to 2 places
  CRM/Core/Payment.php
Labels: 5.37, merge on pass

#20055 Fix AuthX Setting Labels
  ext/authx/settings/authx.setting.php
Labels: master

#20071 dev/core#2498 dedupe rule saving fix
  CRM/Contact/Form/DedupeRules.php
Labels: 5.37

#20075 dev/event#53 Fix issue where by Sold out option was not being properl…
  CRM/Price/BAO/PriceField.php
Labels: 5.36, merge on pass

#19886 Fix for importing preferred language (and other fields) by label
  CRM/Contact/Import/Parser/Contact.php
  CRM/Member/Import/Parser/Membership.php
  api/v3/utils.php
  tests/phpunit/CRM/Contact/Import/Parser/ContactTest.php
  tests/phpunit/CRM/Member/Import/Parser/MembershipTest.php
Labels: master

#20067 5.37
  CRM/Contact/Form/DedupeRules.php
  CRM/Core/Payment.php
  CRM/Price/BAO/PriceField.php
  CRM/Upgrade/Incremental/php/FiveThirtySeven.php
Labels: master

#20078 dev/core#2498 dedupe rule saving fix
  CRM/Contact/Form/DedupeRules.php
Labels: 5.36, merge on pass

#20064 dev/core#2536 Trim strings from info.xml in extensions
  CRM/Extension/Info.php
Labels: master, merge ready

#20080 dev/core#403 Fix Petition Confirmation Email template by removing the…
  CRM/Upgrade/Incremental/MessageTemplates.php
  xml/templates/message_templates/petition_confirmation_needed_html.tpl
Labels: master, merge on pass

#20079 community/feature-request#12 - Allow named logging channels
  Civi.php
  Civi/Core/Container.php
  Civi/Core/LogManager.php
Labels: master, merge on pass

#20018 dev/core#2522 Add in Submit Action and redirect handling post form su…
  ext/afform/admin/Civi/AfformAdmin/AfformAdminMeta.php
  ext/afform/admin/ang/afGuiEditor/config-form.html
  ext/afform/core/Civi/Api4/Afform.php
  ext/afform/core/afform.php
  ext/afform/core/ang/af/afForm.component.js
  ext/afform/core/api/v3/Afform.php
Labels: 5.37

#20084 5.37.0 release notes initial run
  release-notes.md
  release-notes/5.37.0.md
Labels: 5.37

#20083 dev/core#2543 Fix Membership Edit PHP fatal when no recorded payment
  CRM/Member/Form.php
Labels: 5.37

#20076 Simplify mailing check
  CRM/SMS/Form/Upload.php
Labels: master

#20087 dev/core#2543 Fix Membership Edit PHP fatal when no recorded payment
  CRM/Member/Form.php
Labels: 5.36, merge on pass

#20086 5.37
  CRM/Member/Form.php
  ext/afform/admin/Civi/AfformAdmin/AfformAdminMeta.php
  ext/afform/admin/ang/afGuiEditor/config-form.html
  ext/afform/core/Civi/Api4/Afform.php
  ext/afform/core/afform.php
  ext/afform/core/ang/af/afForm.component.js
  ext/afform/core/api/v3/Afform.php
  release-notes.md
  release-notes/5.37.0.md
Labels: master

#20088 (NFC) Fix possible flacky tests by splitting the parts of the checksu…
  tests/phpunit/CRM/Core/BAO/MessageTemplateTest.php
Labels: master

#20089 [NFC/Unit Test] - Help avoid problems when using assertApproxEquals with integers instead of fractions
  Civi/Test/GenericAssertionsTrait.php
Labels: master

#20036 Alter dedupe code to call api rather than bao->save()
  CRM/Dedupe/MergeHandler.php
  tests/phpunit/api/v3/ContactTest.php
Labels: master

#20098 Port https://github.com/civicrm/civicrm-core/pull/20040
  CRM/Core/Payment.php
Labels: 5.36, merge on pass

#20091 Extensions - Setup `<classloader>` during installation
  CRM/Extension/ClassLoader.php
  CRM/Extension/Manager/Module.php
Labels: master

#20100 Fix the MOST out-of-date parts of the afform readme
  ext/afform/README.md
Labels: master

#20094 [REF] Fix installation of the search display table on MySQL 5.36 in t…
  ext/search/sql/auto_install.sql
Labels: 5.37

#20058 dev/mail#90 - Allow re-use mailing on draft mailings and adhoc mailings
  CRM/Mailing/Controller/Send.php
  CRM/Mailing/Selector/Browse.php
Labels: master, merge ready

#20099 Remove unused functions
  CRM/Core/BAO/MessageTemplate.php
Labels: master

#20002 dev/report#53: search on relationship and case (2)
  CRM/Contact/BAO/Query.php
  tests/fixtures/case_types.json
  tests/phpunit/CRM/Case/BAO/QueryTest.php
  tests/phpunit/CRM/Contact/SelectorTest.php
Labels: has-test, master

#20104 [NFC] Regenerate Grant DAO
  CRM/Grant/DAO/Grant.php
Labels: master, merge on pass

#20103 5.37
  ext/search/sql/auto_install.sql
Labels: master

#20053 dev/core#2505 Fix formatLocaleNumeric
  CRM/Utils/Money.php
Labels: master

#20101 dev/core#2549 Fix undefined index when merging websites
  CRM/Dedupe/Merger.php
Labels: master

#20108 Add 'contact-actions-ribbon' region
  templates/CRM/Contact/Page/View/Summary.tpl
Labels: master

#19989 dev/core#2490 Drupal8: Fix CMS intergration table mapping
  CRM/Admin/Form/Setting/UF.php
Labels: master

#20110 Include more data in error message
  CRM/Core/ManagedEntities.php
Labels: master

#20107 Increase civicrm_queue_item.data field size
  CRM/Queue/DAO/QueueItem.php
  CRM/Upgrade/Incremental/sql/5.38.alpha1.mysql.tpl
  xml/schema/Queue/QueueItem.xml
Labels: master

#20106 dev/core#2509 - Remove unnecessary variable to make it easier to extract function that creates action links
  CRM/Activity/BAO/Activity.php
  CRM/Activity/Selector/Activity.php
Labels: master

#20105 Save entities created by api v4 to managed
  CRM/Core/ManagedEntities.php
  api/api.php
Labels: master

#20090 dev/core#2547 - Add base-upgrader to core
  CRM/Extension/Info.php
  CRM/Extension/Manager/Module.php
  CRM/Extension/Mapper.php
  CRM/Extension/Upgrader/Base.php
  CRM/Extension/Upgrader/IdentityTrait.php
  CRM/Extension/Upgrader/Interface.php
  CRM/Extension/Upgrader/QueueTrait.php
  CRM/Extension/Upgrader/RevisionsTrait.php
  CRM/Extension/Upgrader/TasksTrait.php
  CRM/Extension/Upgrades.php
  ext/oauth-client/CRM/OAuth/Upgrader/Base.php
  ext/oauth-client/info.xml
  ext/oauth-client/oauth_client.php
  ext/search/CRM/Search/Upgrader/Base.php
  ext/search/info.xml
  ext/search/search.php
  tests/extensions/test.extension.manager.moduleupgtest/CRM/Moduleupgtest/Upgrader.php
  tests/extensions/test.extension.manager.moduleupgtest/info.xml
  tests/extensions/test.extension.manager.moduleupgtest/moduleupgtest.php
  tests/phpunit/CRM/Extension/InfoTest.php
  tests/phpunit/CRM/Extension/Manager/ModuleUpgTest.php
Labels: master

#20114 dev/core#2509 - Remove duplicate setting of activity subject field and replace a few CRM_Utils_Array::value
  CRM/Activity/BAO/Activity.php
Labels: master

#20116 Extensions - Setup <classloader> during "enable" and "uninstall"
  CRM/Extension/Manager/Module.php
Labels: master, merge on pass

#20085 Fix Drupal8 CiviCRM menu translation on multilingual (and ajax calls)
  js/crm.ajax.js
  templates/CRM/common/l10n.js.tpl
  tests/karma/unit/crmMailingSpec.js
Labels: master, merge on pass

#20117 SearchKit - Fix display of contact reference fields (single-value)
  Civi/Api4/Service/Schema/SchemaMapBuilder.php
  ext/search/Civi/Search/Admin.php
  ext/search/ang/crmSearchAdmin.module.js
  tests/phpunit/api/v4/Action/CustomJoinTest.php
  tests/phpunit/api/v4/AllTests.php
Labels: has-test, master

#20119 5.37
  Civi/Api4/Query/Api4SelectQuery.php
  Civi/Api4/Service/Schema/Joiner.php
  release-notes.md
  release-notes/5.35.2.md
  release-notes/5.36.1.md
  tests/phpunit/api/v4/Query/PermissionCheckTest.php
Labels: master
