Repository civicrm/civicrm-core, pull requests merged in 2021-07, with the labels that each got.

#20732 dev/core#2604 Backport applying patch to fix single quotes in return …
  composer.json
  composer.lock
Labels: 5.38

#20717 [REF] Alter new Setup process to use CiviCRM's Event Dispatcher
  setup/src/Setup.php
Labels: master, merge ready

#20739 5.38.1 - Version bump. Release notes.
  release-notes.md
  release-notes/5.38.1.md
  sql/civicrm_generated.mysql
  sql/test_data_second_domain.mysql
  xml/version.xml
Labels: 5.38

#20740 Add release-notes/5.38.1.md
  release-notes.md
  release-notes/5.38.1.md
Labels: 5.39

#20735 Tpl enotice fix
  CRM/Contact/Import/Form/DataSource.php
  templates/CRM/Contact/Import/Form/DataSource.tpl
  templates/CRM/common/WizardHeader.tpl
Labels: master, merge on pass

#20737 Fix possibly undefined custom groupTree tpl variable
  templates/CRM/Activity/Form/Search/Common.tpl
  templates/CRM/Contact/Form/Search/Criteria/Location.tpl
  templates/CRM/Contact/Form/Search/Criteria/Relationship.tpl
  templates/CRM/Contribute/Form/Search/Common.tpl
  templates/CRM/Contribute/Form/Search/ContributionRecur.tpl
  templates/CRM/Grant/Form/Search/Common.tpl
  templates/CRM/Member/Form/Search/Common.tpl
  templates/CRM/Pledge/Form/Search/Common.tpl
Labels: master, merge on pass

#20741 5.39
  release-notes.md
  release-notes/5.38.1.md
Labels: master

#20731 APIv4 Explorer: show joins for write actions
  CRM/Api4/Page/Api4Explorer.php
  ang/api4Explorer.ang.php
  ang/api4Explorer/Explorer.js
  api/v3/Activity.php
  api/v3/Campaign.php
  api/v3/Event.php
  api/v3/MembershipType.php
  ext/afform/core/api/v3/Afform.php
Labels: master

#20734 [REF] Fix trying to access array offset from boolean value
  Civi/Api4/Query/Api4SelectQuery.php
Labels: master

#20742 Throw exception rather than fatal
  Civi/Api4/Service/Spec/SpecGatherer.php
Labels: master

#20676 Fix test to use valid financials
  tests/phpunit/CRM/Contribute/BAO/ContributionRecurTest.php
Labels: master

#20394 [REF] Extend testing on membership batch entry & minor cleanup
  CRM/Batch/Form/Entry.php
  tests/phpunit/CRM/Batch/Form/EntryTest.php
Labels: master

#20396 [REF] Remove isPayLater from membership batch screen
  CRM/Batch/Form/Entry.php
Labels: master

#20744 Support saving more than 25 records in Profile.submit api
  api/v3/Profile.php
Labels: master

#20627 dev/financial#175 - Unable to remove a currency once added
  CRM/Core/OptionGroup.php
  tests/phpunit/CRM/Admin/Form/Setting/LocalizationTest.php
Labels: has-test, master

#20602 Fix activity_date_time_relative filter when `preserve_activity_tab_fi…
  CRM/Activity/Page/AJAX.php
Labels: master, merge on pass, ok-without-test

#20745 [NFC] Unit test for 20602
  tests/phpunit/CRM/Activity/Page/AJAXTest.php
Labels: has-test, master

#20648 [NFC] Improve use of return parameters in ContributionPage test class
  tests/phpunit/api/v3/ContributionPageTest.php
Labels: master

#20586 APIv4 - add is_current as a pseudo (calculated) field
  Civi/Api4/Action/Campaign/Get.php
  Civi/Api4/Action/Event/Get.php
  Civi/Api4/Action/Relationship/Get.php
  Civi/Api4/Event/Subscriber/IsCurrentSubscriber.php
  Civi/Api4/Generic/DAOGetFieldsAction.php
  Civi/Api4/Generic/Traits/IsCurrentTrait.php
  Civi/Api4/Query/Api4SelectQuery.php
  Civi/Api4/Query/SqlField.php
  Civi/Api4/Service/Schema/Joinable/Joinable.php
  Civi/Api4/Service/Spec/FieldSpec.php
  Civi/Api4/Service/Spec/Provider/IsCurrentFieldSpecProvider.php
  Civi/Api4/Service/Spec/RequestSpec.php
  Civi/Api4/Service/Spec/SpecGatherer.php
  Civi/Test/Api3TestTrait.php
  tests/phpunit/api/v4/Action/CurrentFilterTest.php
Labels: has-test, master, merge on pass

#20747 [REF] Add in template guard for not being always set as per html format
  sql/civicrm_generated.mysql
  xml/templates/message_templates/event_online_receipt_text.tpl
Labels: master, merge on pass

#20750 Add missing "View Recurring Contribution" link to contribution view
  templates/CRM/Contribute/Form/ContributionView.tpl
Labels: master

#20754 Fix undefined tpl vars on contact summary page
  templates/CRM/Contact/Page/Inline/Demographics.tpl
  templates/CRM/Contact/Page/Inline/Phone.tpl
  templates/CRM/Contact/Page/View/CustomDataView.tpl
  templates/CRM/Custom/Page/CustomDataView.tpl
Labels: master

#20729 [REF] Remove unnecessary variable wrangling in case roles section
  templates/CRM/Case/Form/CaseView.tpl
Labels: master

#20759 dev/core#2634 [REF] Move membership date calc from v3 api to BAO
  CRM/Batch/Form/Entry.php
  CRM/Member/BAO/Membership.php
  api/v3/Membership.php
  tests/phpunit/api/v3/MembershipTest.php
Labels: master

#20748 [NFC] Update various npm depdencies used only in unit testing
  package-lock.json
  package.json
Labels: master

#20743 Improve api consistency on custom field creation
  CRM/Core/BAO/CustomField.php
  Civi/Test/Api3TestTrait.php
  api/v3/CustomField.php
  tests/phpunit/api/v3/CustomFieldTest.php
Labels: master

#20757 dev/core#27 Move check for phone function to a check
  CRM/Core/BAO/Phone.php
  CRM/Core/DAO.php
  CRM/Utils/Check/Component/Schema.php
Labels: master, merge on pass

#20749 APIv4 - Rename id_field to primary_key and make it an array
  CRM/Core/DAO.php
  Civi/Api4/CustomValue.php
  Civi/Api4/Entity.php
  Civi/Api4/Generic/AbstractEntity.php
  Civi/Api4/Generic/BasicEntity.php
  Civi/Api4/Query/Api4SelectQuery.php
  ext/afform/core/Civi/Api4/Afform.php
  ext/search_kit/Civi/Api4/Action/SearchDisplay/Run.php
  tests/phpunit/api/v4/Action/BasicActionsTest.php
  tests/phpunit/api/v4/Entity/ConformanceTest.php
  xml/templates/dao.tpl
Labels: master, merge on pass

#20760 Remove deprecated function
  CRM/Price/BAO/PriceSet.php
Labels: master

#20762 dev/core#2115 prep - Remove silly if, silly rename
  CRM/Member/Page/MembershipType.php
  templates/CRM/Member/Page/MembershipType.tpl
Labels: master

#20755 Afform - cosmetic fixes in palette panel
  ext/afform/admin/ang/afGuiEditor.css
  ext/afform/admin/ang/afGuiEditor/afGuiSearch.html
  ext/afform/core/Civi/Api4/Action/Afform/Get.php
Labels: master

#20761 dev/core#2115 Add test cover for membership type page
  ext/financialacls/tests/phpunit/Civi/Financialacls/BaseTestClass.php
  ext/financialacls/tests/phpunit/Civi/Financialacls/MembershipTypesTest.php
  tests/phpunit/CRM/Member/Page/MembershipTypeTest.php
Labels: master, merge on pass

#20763 SearchKit - use primary_key info instead of assuming 'id'
  ext/search_kit/Civi/Search/Admin.php
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdmin.component.js
Labels: master

#20656 [REF] Follow up clean up - remove contribution_mode
  CRM/Contribute/BAO/Contribution.php
  CRM/Contribute/Form/Contribution.php
  api/v3/Order.php
  tests/phpunit/api/v3/ContributionTest.php
Labels: master

#20681 Make Order api easier to use for default price set
  CRM/Contribute/BAO/Contribution.php
  CRM/Financial/BAO/Order.php
  api/v3/Order.php
  tests/phpunit/CRM/Contribute/BAO/ContributionTest.php
  tests/phpunit/api/v3/ContributionTest.php
Labels: master

#20733 [NFC] Add in unit test to lock in the fix for the is_deleted in where…
  tests/phpunit/api/v4/Action/ContactIsDeletedTest.php
Labels: has-test, master

#20772 smarty notice - confirm_message is usually irrelevant in report listings
  templates/CRM/Report/Page/InstanceList.tpl
Labels: master, merge on pass

#20771 smarty notice - title is only set for a list of existing report instances
  templates/CRM/Report/Page/InstanceList.tpl
Labels: master, merge on pass

#20769 dev/core#2115 Move financial acl code out of v3 Contribution create
  api/v3/Contribution.php
  ext/financialacls/financialacls.php
Labels: master

#20770 smarty notice - case dashboard when no upcoming/recent cases
  CRM/Case/Page/DashBoard.php
Labels: master, merge on pass

#20773 [NFC] First Stab at 5.39 Release Notes
  contributor-key.yml
  release-notes/5.39.0.md
Labels: 5.39

#20727 APIv4 - Deprecate Entity::getLinks action
  CRM/Api4/Page/Api4Explorer.php
  Civi/Api4/Action/Entity/GetLinks.php
  Civi/Api4/Entity.php
  Civi/Api4/Service/Schema/SchemaMapBuilder.php
  ang/api4Explorer/Explorer.html
  ang/api4Explorer/Explorer.js
  tests/phpunit/api/v4/Service/Schema/SchemaMapRealTableTest.php
Labels: master

#20774 5.39
  contributor-key.yml
  release-notes/5.39.0.md
Labels: master

#20672 dev/membership#29 Add civicrm_line_item.membership_num_terms
  CRM/Contribute/BAO/Contribution.php
  CRM/Price/DAO/LineItem.php
  CRM/Upgrade/Incremental/php/FiveForty.php
  xml/schema/Price/LineItem.xml
Labels: master

#20738 Enotice fix Remove references to savedFieldMapping in page 2 of the import
  templates/CRM/Activity/Import/Form/MapField.tpl
  templates/CRM/Contact/Import/Form/MapField.tpl
  templates/CRM/Contribute/Import/Form/MapField.tpl
  templates/CRM/Event/Import/Form/MapField.tpl
  templates/CRM/Member/Import/Form/MapField.tpl
Labels: master

#20728 Error when sorting case roles table by end date
  CRM/Activity/Page/AJAX.php
Labels: master

#20778 [REF] Tidy up param transforms
  CRM/Batch/Form/Entry.php
Labels: master

#20781 Fix undefined indexes in tpls
  templates/CRM/Activity/Form/ActivityLinks.tpl
  templates/CRM/Contact/Page/Inline/Demographics.tpl
  templates/CRM/Contact/Page/Inline/Email.tpl
  templates/CRM/Custom/Form/Preview.tpl
  templates/CRM/Custom/Page/Group.tpl
Labels: master, merge on pass

#20779 Clean up code to determine line items for membership batch entry
  CRM/Batch/Form/Entry.php
  CRM/Financial/BAO/Order.php
Labels: master

#20787 CRM_Utils_Array - Implement pathUnset() method
  CRM/Utils/Array.php
  tests/phpunit/CRM/Utils/ArrayTest.php
Labels: has-test, master, merge on pass

#20788 CRM_Utils_Array::asColumns() - Add helper to rotate a matrix (from rows to columns)
  CRM/Utils/Array.php
  tests/phpunit/CRM/Utils/ArrayTest.php
Labels: has-test, master, merge ready

#20783 dev#2861: Prevent duplicate names in mailing labels
  CRM/Utils/Address.php
Labels: master, merge ready

#20789 (REF) crmUi - Support onCrmUiSelect for using select2 as a picklist
  ang/crmUi.js
Labels: master

#20790 Handle participant payment create in line item
  CRM/Price/BAO/LineItem.php
  api/v3/Order.php
Labels: master, merge on pass

#20392 [REF] Extract CKEditor into its own core extension
  .gitignore
  CRM/Core/Resources/Common.php
  CRM/Core/xml/Menu/Admin.xml
  CRM/Upgrade/Incremental/php/FiveForty.php
  bin/regen.sh
  distmaker/core-ext.txt
  ext/ckeditor4/CRM/Ckeditor4/Form/CKEditorConfig.php
  ext/ckeditor4/CRM/Ckeditor4/Upgrader.php
  ext/ckeditor4/CRM/Ckeditor4/Upgrader/Base.php
  ext/ckeditor4/LICENSE.txt
  ext/ckeditor4/README.md
  ext/ckeditor4/ckeditor4.civix.php
  ext/ckeditor4/ckeditor4.php
  ext/ckeditor4/images/screenshot.png
  ext/ckeditor4/info.xml
  ext/ckeditor4/js/admin.ckeditor-configurator.js
  ext/ckeditor4/js/ck-options.json
  ext/ckeditor4/js/crm.ckeditor.js
  ext/ckeditor4/templates/CRM/Admin/Form/Preferences/Ckeditor.tpl
  ext/ckeditor4/templates/CRM/Ckeditor4/Form/CKEditorConfig.tpl
  ext/ckeditor4/xml/Menu/ckeditor4.xml
  sql/civicrm_generated.mysql
  templates/CRM/Admin/Form/Preferences/Display.tpl
  tools/bin/scripts/ckeditorConfigScraper.php
  xml/templates/civicrm_data.tpl
Labels: master, merge on pass

#18517 dev/financial#150: civicrm/payment/form url got empty currency argument in backoffice live CC form
  CRM/Contribute/Form/AbstractEditPayment.php
  templates/CRM/common/paymentBlock.tpl
Labels: master

#20793 [Ref] Remove (more) unreachable code from order api
  api/v3/Order.php
Labels: master

#20795 smarty notices - New case screen - Case.hlp
  templates/CRM/Case/Form/Case.hlp
Labels: master

#20796 Unused smarty variable
  templates/CRM/Activity/Form/ActivityLinks.tpl
Labels: master

#20797 Fix undefined tpl vars in CiviReport
  templates/CRM/Report/Form.tpl
  templates/CRM/Report/Form/Actions.tpl
  templates/CRM/Report/Form/Criteria.tpl
  templates/CRM/Report/Form/ErrorMessage.tpl
  templates/CRM/Report/Form/Fields.tpl
  templates/CRM/Report/Form/Grant/Statistics.tpl
  templates/CRM/Report/Form/Layout/Table.tpl
  templates/CRM/Report/Form/Statistics.tpl
  templates/CRM/Report/Form/Tabs/FieldSelection.tpl
  templates/CRM/Report/Form/Tabs/Filters.tpl
  templates/CRM/Report/Form/Tabs/Instance.tpl
  templates/CRM/Report/Page/InstanceList.tpl
  templates/CRM/Report/Page/TemplateList.tpl
Labels: master, merge on pass

#20719 Add calling function to deprecatedWarning log message
  CRM/ACL/API.php
  CRM/ACL/BAO/ACL.php
  CRM/Core/Error.php
Labels: master, merge on pass

#20798 5.39.0 release notes: added late changes
  release-notes/5.39.0.md
Labels: 5.39

#20802 5.39 to master
  release-notes/5.39.0.md
Labels: master

#20780 Fix test set up to user Order api
  api/v3/Order.php
  tests/phpunit/CRM/Core/Payment/PayPalIPNTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: has-test, master, merge on pass

#20746 dev/core#2676 SearchKit - Add LocBlock entity to display Event location data
  CRM/Core/DAO/LocBlock.php
  Civi/Api4/LocBlock.php
  ext/search_kit/Civi/Search/Admin.php
  xml/schema/Core/LocBlock.xml
Labels: master

#20785 Fix BaseIPN test to (mostly) pass invalid financials checks
  api/v3/Order.php
  tests/phpunit/CRM/Core/Payment/BaseIPNTest.php
  tests/phpunit/CRM/Event/BAO/ChangeFeeSelectionTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/api/v3/SyntaxConformanceTest.php
Labels: has-test, master

#20764 SearchKit - Add ability to join on multi-select ContactRef fields
  Civi/Api4/Generic/Traits/DAOActionTrait.php
  Civi/Api4/Query/Api4SelectQuery.php
  Civi/Api4/Service/Schema/Joinable/Joinable.php
  Civi/Api4/Service/Schema/Joiner.php
  Civi/Api4/Service/Schema/SchemaMapBuilder.php
  ext/afform/admin/Civi/AfformAdmin/AfformAdminMeta.php
  ext/afform/core/Civi/Afform/AfformMetadataInjector.php
  ext/search_kit/Civi/Api4/Action/SearchDisplay/Run.php
  ext/search_kit/Civi/Search/Admin.php
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdmin.component.js
  ext/search_kit/ang/crmSearchDisplay.module.js
  ext/search_kit/ang/crmSearchDisplay/colType/field.html
  ext/search_kit/ang/crmSearchDisplayList/crmSearchDisplayList.component.js
  ext/search_kit/ang/crmSearchDisplayTable/crmSearchDisplayTable.component.js
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/SearchRunTest.php
  tests/phpunit/api/v4/Action/CustomContactRefTest.php
Labels: has-test, master, merge on pass, merge ready

#20756 dev/core#2659 Move group cleanup to latest release
  CRM/Upgrade/Incremental/php/FiveThirtyNine.php
  CRM/Upgrade/Incremental/php/FiveTwenty.php
Labels: 5.39

#20600 Force cleanup of setting value type "checkboxes" when is empty
  CRM/Admin/Form/SettingTrait.php
Labels: master

#20808 5.39.0 - Final updates
  ext/afform/admin/info.xml
  ext/afform/core/info.xml
  ext/afform/html/info.xml
  ext/afform/mock/info.xml
  ext/authx/info.xml
  ext/contributioncancelactions/info.xml
  ext/eventcart/info.xml
  ext/ewaysingle/info.xml
  ext/financialacls/info.xml
  ext/flexmailer/info.xml
  ext/greenwich/info.xml
  ext/oauth-client/info.xml
  ext/payflowpro/info.xml
  ext/recaptcha/info.xml
  ext/search_kit/info.xml
  ext/sequentialcreditnotes/info.xml
  release-notes/5.39.0.md
  sql/civicrm_generated.mysql
  sql/test_data_second_domain.mysql
  tools/bin/scripts/set-version.php
  xml/version.xml
Labels: 5.39

#20803 SearchKit - Remove automatic filter from address
  Civi/Api4/Address.php
Labels: master

#20809 Merge forward 5.39 => master
  CRM/Upgrade/Incremental/php/FiveThirtyNine.php
  CRM/Upgrade/Incremental/php/FiveTwenty.php
  release-notes/5.39.0.md
  tools/bin/scripts/set-version.php
Labels: master

#20810 AssetBuilderTest - Raise threshold for timeout
  tests/phpunit/E2E/Core/AssetBuilderTest.php
Labels: master

#20806 Fix test to use order api & setup valid financials
  Civi/Test/ContactTestTrait.php
  tests/phpunit/api/v3/ContributionTest.php
Labels: master, merge on pass

#20786 crmMonaco - Multiple updates. Toward message-template editing.
  CRM/Utils/JS.php
  ang/crmMonaco.js
  composer.json
  composer.lock
  tests/phpunit/CRM/Utils/JSTest.php
Labels: master

#20758 SearchKit - Auto-apply filters passed in from Afform markup
  ext/afform/mock/ang/testContactEmailSearchForm.aff.html
  ext/afform/mock/ang/testContactEmailSearchForm.aff.json
  ext/search_kit/Civi/Api4/Action/SearchDisplay/Run.php
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/SearchAfformTest.php
Labels: has-test, master

#20794 dev/core#2652 - Civi\Report - Add is null / is not null to OP_MULTISE…
  CRM/Report/Form.php
Labels: master, merge ready

#20805 Add deprecation warning for modifiedDates
  CRM/Contact/BAO/Query.php
Labels: master

#20812 Update contributor-key.yml
  contributor-key.yml
Labels: master

#20782 Forward Mailing: remove duplicate buttons, cancel button
  CRM/Mailing/Form/ForwardMailing.php
  templates/CRM/Mailing/Form/ForwardMailing.tpl
Labels: master, merge ready

#20505 Add ContributionProduct and EntityBatch APIv4 Entity
  Civi/Api4/ContributionProduct.php
  Civi/Api4/EntityBatch.php
  tests/phpunit/api/v4/DataSets/ConformanceTest.json
  tests/phpunit/api/v4/Entity/ConformanceTest.php
Labels: master

#20813 Fix undefined tpl variables
  templates/CRM/Admin/Form/Setting/Debugging.tpl
  templates/CRM/Contact/Form/Task.tpl
  templates/CRM/Contact/Form/Task/EmailCommon.tpl
  templates/CRM/Form/attachment.tpl
Labels: master

#20814 dev/core#2680 Remove rows in the civicrm_contribution_product table t…
  CRM/Upgrade/Incremental/php/FiveForty.php
Labels: 5.40, merge on pass

#20815 5.40 to master
  CRM/Upgrade/Incremental/php/FiveForty.php
Labels: master

#20399 dev/core#2624 display line items from the template contribution at the view recurring contribution screen.
  CRM/Contribute/Page/ContributionRecur.php
  templates/CRM/Contribute/Page/ContributionRecur.tpl
Labels: master

#20816 PHP notice fixes on options page
  CRM/Admin/Page/Options.php
  templates/CRM/Admin/Page/Options.tpl
Labels: master, merge on pass

#20817 APIv4 - Fix dumb typo breaking color lookup
  CRM/Core/OptionValue.php
Labels: master, merge on pass

#20315 (REF) dev/core#2571 - Add helper functions for reCAPTCHA extension
  CRM/Campaign/Form/Petition/Signature.php
  CRM/Contribute/Form/Contribution/Main.php
  CRM/Contribute/Form/ContributionBase.php
  CRM/Core/Form.php
  CRM/Event/Form/Registration/AdditionalParticipant.php
  CRM/Event/Form/Registration/Register.php
  CRM/PCP/Form/PCPAccount.php
  CRM/Profile/Form.php
Labels: master

#20824 SearchKit - Fix reloading a search with an OR group in the WHERE clause
  ext/search_kit/ang/crmSearchAdmin/crmSearchClause.component.js
Labels: 5.40, sig:regression

#20818 Fix for issue 2685
  CRM/Core/Payment/AuthorizeNetIPN.php
Labels: 5.40

#20827 tpl enotice fix
  templates/CRM/common/success.tpl
Labels: master

#20826 Merge 5.40 to master
  CRM/Core/Payment/AuthorizeNetIPN.php
  ext/search_kit/ang/crmSearchAdmin/crmSearchClause.component.js
Labels: master

#20670 Fix transfer registration to transfer participant_payment row
  CRM/Event/Form/SelfSvcTransfer.php
  tests/phpunit/CRM/Event/Form/ParticipantTest.php
Labels: master

#20828 Fix undefined tpl vars
  CRM/Admin/Page/Access.php
  templates/CRM/ACL/Form/WordPress/Permissions.tpl
  templates/CRM/Contact/Form/Search/ResultTasks.tpl
  templates/CRM/Contact/Form/Selector.tpl
  templates/CRM/Custom/Form/Group.tpl
  templates/CRM/common/pagerAToZ.tpl
Labels: master

#20799 APIv4 - Fix pseudoconstant matching reliability across joins
  Civi/Api4/Generic/AbstractAction.php
  Civi/Api4/Generic/Traits/DAOActionTrait.php
  Civi/Api4/Query/Api4SelectQuery.php
  Civi/Api4/Utils/FormattingUtil.php
  tests/phpunit/api/v4/Action/ContactGetTest.php
Labels: has-test, master

#20650 Enable check on created participant payment rows
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: has-test, master, merge on pass

#20830 E-notice fix
  CRM/Report/Page/TemplateList.php
Labels: master, merge on pass

#20587 dev/core#2648 update redis class off deprecated functions
  CRM/Core/PrevNextCache/Redis.php
Labels: master

#20836 Resolve dev/rc#13 by permitting civi.setupui events to be dispatched …
  setup/src/Setup.php
Labels: 5.40, merge on pass

#20838 5.40
  setup/src/Setup.php
Labels: master

#20784 Fixes getTemplateContribution to use a more reliable way to load line items
  CRM/Contribute/BAO/Contribution.php
  CRM/Contribute/BAO/ContributionRecur.php
  CRM/Financial/BAO/Order.php
  tests/phpunit/CRM/Contribute/BAO/ContributionRecurTest.php
  tests/phpunit/CRM/Core/Payment/PayPalIPNTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/api/v3/ContributionTest.php
Labels: master

#20775 Deprecate guess work in line item handling
  CRM/Price/BAO/LineItem.php
Labels: master

#20831 Remove a couple of instances of 'contribution_mode' from tests
  tests/phpunit/CRM/Contribute/BAO/ContributionTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: master

#20834 [REF] Remove unused variables
  CRM/Activity/Form/Activity.php
  CRM/Campaign/Form/Campaign.php
  CRM/Campaign/Form/Petition/Signature.php
  CRM/Case/Form/Case.php
  CRM/Contact/Form/CustomData.php
  CRM/Contact/Import/Parser/Contact.php
  CRM/Event/Form/ParticipantView.php
  CRM/Grant/Form/Grant.php
  CRM/Pledge/Form/Pledge.php
Labels: master

#20833 CustomGroup - change admin permission to 'administer CiviCRM data'
  CRM/Core/Permission.php
Labels: master

#20839 Fix a typo in social networking buttons
  templates/CRM/common/SocialNetwork.tpl
Labels: master, merge on pass

#20821 Mark afform extensions as beta
  ext/afform/admin/info.xml
  ext/afform/core/info.xml
Labels: master, merge ready

#20842 Add to contributors file
  contributor-key.yml
Labels: master, merge on pass

#20768 dev/core#2115 Switch membership type browse page to use v4api for get, thus using acls properly
  CRM/Member/Page/MembershipType.php
  tests/phpunit/CRM/Member/Page/MembershipTypeTest.php
Labels: has-test, master

#20843 Smarty notices - Missing type on logging civireport
  CRM/Logging/ReportDetail.php
  templates/CRM/Logging/ReportDetail.tpl
Labels: master

#20846 CKEditor - Fix .tpl insertion on every form
  ext/ckeditor4/ckeditor4.php
Labels: 5.40, merge on pass, sig:regression

#20844 dev/core#2691 - On logging detail civireport show words instead of numbers
  CRM/Logging/Differ.php
Labels: master

#20718 [REF] Minor auth.net ipn simplification
  CRM/Core/Payment/AuthorizeNetIPN.php
Labels: master

#20847 Minor simplification - use casting
  CRM/ACL/API.php
Labels: master, merge on pass

#20849 5.40
  ext/ckeditor4/ckeditor4.php
Labels: master

#20852 [REF] [towards dev/core#2693] Use getter rather than passing variable
  CRM/Core/Payment/PayPalIPN.php
Labels: master, merge on pass

#20840 APIv4 - Fix output of membershipType auto_renew field
  CRM/Member/DAO/MembershipType.php
  tests/phpunit/CRM/Member/Form/MembershipRenewalTest.php
  tests/phpunit/CRM/Member/Form/MembershipTest.php
  tests/phpunit/api/v3/ContributionPageTest.php
  xml/schema/Member/MembershipType.xml
Labels: master, merge on pass

#20859 5.40.0 release notes initial run
  release-notes.md
  release-notes/5.40.0.md
Labels: 5.40

#20860 5.40 to master
  release-notes.md
  release-notes/5.40.0.md
Labels: master

#20578 Give administer CiviCRM data access to administer custom groups
  CRM/Core/xml/Menu/Admin.xml
Labels: master, merge ready

#20863 Fix v4 api to do custom field delete in tearDown
  tests/phpunit/api/v4/Action/BaseCustomValueTest.php
  tests/phpunit/api/v4/Action/BasicCustomFieldTest.php
Labels: master

#20829 [REF] Further order api cleanup
  CRM/Contribute/BAO/Contribution.php
  CRM/Financial/BAO/Order.php
  api/v3/Order.php
  tests/phpunit/CRM/Contribute/BAO/ContributionTest.php
Labels: master

#20820 dev/core#2684 Fix filters tpl in civi reports to permit more than one table in a grouping
  CRM/Report/Form.php
  templates/CRM/Report/Form/Tabs/Filters.tpl
Labels: master, merge on pass

#20791 [REF] Simplify isRenew handling on batch for membership
  CRM/Batch/Form/Entry.php
Labels: master

#20876 Api test cleanup fixes
  tests/phpunit/api/v4/Action/BaseCustomValueTest.php
  tests/phpunit/api/v4/Action/CreateWithOptionGroupTest.php
Labels: master, merge on pass

#20873 Remove deprecated lines of code
  CRM/Contribute/BAO/Contribution.php
Labels: master

#20801 Enotice fix on extensions page
  templates/CRM/Admin/Page/ExtensionDetails.tpl
  templates/CRM/Admin/Page/Extensions/Main.tpl
Labels: master

#20864 dev/core#2650 Add support for contribution_status_id to the token processor
  CRM/Contribute/Tokens.php
  tests/phpunit/CRM/Contribute/ActionMapping/ByTypeTest.php
Labels: has-test, master, merge ready

#20874 [REF] Remove some non-variable variables
  CRM/Batch/Form/Entry.php
Labels: master

#20871 [Ref] Remove never-passed parameter
  CRM/Contribute/BAO/Contribution.php
Labels: master

#20878 SearchKit - Fix pager count return value
  ext/search_kit/Civi/Api4/Action/SearchDisplay/Run.php
Labels: master, merge on pass

#20879 Fix onCrmUiSelect to use current scope and apply to the digest cycle
  ang/crmUi.js
Labels: master

#20881 Remove non-variable variables
  CRM/Batch/Form/Entry.php
Labels: master

#20853 Remove never-true-if
  CRM/Core/Payment/AuthorizeNetIPN.php
Labels: master

#20848 Remove deprecated code
  CRM/Admin/Form/ScheduleReminders.php
  CRM/Event/BAO/Event.php
  CRM/Event/Form/ManageEvent/Delete.php
Labels: master

#20850 Use type hinting for id
  CRM/ACL/BAO/ACL.php
  CRM/ACL/BAO/Cache.php
Labels: master

#20865 (REF) Civi/Schema - Extract MagicGetterSetterTrait. Add test coverage.
  Civi/Api4/Generic/AbstractAction.php
  Civi/Schema/Traits/MagicGetterSetterTrait.php
  tests/phpunit/Civi/Schema/MagicGetterSetterTest.php
Labels: has-test, master, merge on pass

#20890 dev/core#2666 - (Alternate) Don't repeatedly log about crm-l10n.js during upgrade
  CRM/Core/Resources/Common.php
Labels: 5.40

#20891 [NFC/Unit test] - Failing test demonstrating blank timestamp updates
  tests/phpunit/CRM/Core/DAOTest.php
Labels: has-test, master, merge on pass

#20894 5.40
  CRM/Core/Resources/Common.php
Labels: master

#20896 APIv4 - Better handling of output value using GROUP_CONCAT
  Civi/Api4/Query/SqlFunctionCONCAT.php
  Civi/Api4/Query/SqlFunctionGROUP_CONCAT.php
Labels: master

#20880 SearchKit - Support all fields as tokens
  ang/api4Explorer/Explorer.js
  ext/search_kit/Civi/Api4/Action/SearchDisplay/Run.php
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdminLinkGroup.html
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdminLinkSelect.html
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdminTokenSelect.component.js
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdminTokenSelect.html
  ext/search_kit/ang/crmSearchAdmin/displays/colType/field.html
  ext/search_kit/ang/crmSearchAdmin/displays/searchAdminDisplayList.html
  ext/search_kit/ang/crmSearchDisplay/colType/buttons.html
  ext/search_kit/ang/crmSearchDisplay/colType/links.html
  ext/search_kit/ang/crmSearchDisplay/colType/menu.html
  ext/search_kit/ang/crmSearchDisplayList/crmSearchDisplayList.component.js
  ext/search_kit/ang/crmSearchDisplayTable/crmSearchDisplayTable.component.js
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/SearchRunTest.php
Labels: has-test, master

#20869 [REF] Fix functions to be protected
  CRM/ACL/BAO/Cache.php
Labels: master

#20601 Added setup pcp page wordpress shortcode
  CRM/Core/Form/ShortCode.php
Labels: master, merge ready

#20875 (REF) APIv4 FieldSpec - Extract various traits (Civi\Schema\Traits\*)
  Civi/Api4/Service/Spec/FieldSpec.php
  Civi/Schema/Traits/ArrayFormatTrait.php
  Civi/Schema/Traits/BasicSpecTrait.php
  Civi/Schema/Traits/DataTypeSpecTrait.php
  Civi/Schema/Traits/GuiSpecTrait.php
  Civi/Schema/Traits/OptionsSpecTrait.php
  Civi/Schema/Traits/PhpDataTypeSpecTrait.php
  Civi/Schema/Traits/SqlSpecTrait.php
  tests/phpunit/api/v4/Entity/ConformanceTest.php
Labels: has-test, master, merge ready

#20897 some typo fixes
  CRM/Event/Form/SelfSvcTransfer.php
Labels: master, merge on pass

#20899 Fix PHP notice in recaptcha lib
  ext/recaptcha/lib/recaptcha/recaptchalib.php
Labels: master

#20901 [NFC/Unit test] dev/core#2699 - Fix intermittent api4 test (part 1)
  tests/phpunit/api/v4/Action/BaseCustomValueTest.php
Labels: has-test, master

#20902 APIv4 - Add test to ensure superfluous option groups are not created
  tests/phpunit/api/v4/Action/BasicCustomFieldTest.php
Labels: master

#20892 [REF] Add in smarty modifier to replcae the upper smarty modifier to …
  CRM/Core/Smarty/plugins/modifier.crmUpper.php
  templates/CRM/Event/Form/Participant.tpl
  templates/CRM/Report/Form/Contact/Detail.tpl
Labels: master, merge ready
