Repository civicrm/civicrm-core, pull requests merged in 2021-12, with the labels that each got.

#22164 Remove empty check previously commented to be meaningless
  templates/CRM/Tag/Form/Edit.tpl
Labels: master

#22184 [Smarty variables] Remove isset from add new group form
  CRM/Group/Form/Edit.php
  templates/CRM/Group/Form/GroupsCommon.tpl
Labels: master

#22174 Remove isset checks on isForm
  templates/CRM/Case/Form/ActivityTab.tpl
Labels: master

#22172 Avoid default escaping for blog titles
  templates/CRM/Dashlet/Page/Blog.tpl
Labels: master

#22180 Remove issets from Activity search screen
  templates/CRM/Activity/Form/Selector.tpl
Labels: master

#22175 [Smarty variable][Civicase] remove isset
  CRM/Case/BAO/Query.php
  templates/CRM/Case/Form/CaseFilter.tpl
Labels: master

#22188 ManagedEntities - Fix permission error during uninstallation (regression-fix)
  CRM/Core/ManagedEntities.php
Labels: master, merge on pass

#22197 DebugSubscriber - Fix test-suite compatibility with XDebug 3
  Civi/API/Subscriber/DebugSubscriber.php
Labels: master, merge on pass

#22165 Smarty variables] Prevent settings form assigned html from being escaped
  templates/CRM/Admin/Form/Setting/SettingField.tpl
Labels: master

#22196 [Smarty variables] The last isset....
  CRM/Report/Page/InstanceList.php
  templates/CRM/Report/Page/InstanceList.tpl
Labels: master, merge on pass

#22179 [Smarty variables] Fix contribution tab to work with escape by default
  CRM/Contact/BAO/Query.php
  templates/CRM/Contribute/Form/Selector.tpl
  templates/CRM/Contribute/Page/ContributionTotals.tpl
  tests/phpunit/CRM/Contact/BAO/QueryTest.php
Labels: master, merge on pass

#22185 [Smarty variables] - remove isset
  templates/CRM/Activity/Selector/Activity.tpl
Labels: master, merge on pass

#21751 dev/financial#184 Fix currency name for Ghana and Belarus
  CRM/Upgrade/Incremental/Base.php
  CRM/Upgrade/Incremental/php/FiveFortyFive.php
  sql/civicrm_generated.mysql
  xml/templates/civicrm_currency.tpl
Labels: master, merge on pass

#22173 APIv4 - Add fixes & tests for domain-specific managed entities
  Civi/Api4/Dashboard.php
  Civi/Api4/Generic/Traits/DAOActionTrait.php
  tests/phpunit/api/v4/Entity/ManagedEntityTest.php
Labels: master, has-test

#22176 [Smarty variables] [CiviCase] remove isset from case dashboard
  CRM/Case/BAO/Case.php
  CRM/Case/Page/DashBoard.php
  templates/CRM/Case/Page/DashBoard.tpl
  tests/phpunit/CRM/Core/FormTest.php
Labels: master, merge on pass

#22204 tools/mixin/bin/test-all - Fix guard for EXT_DIR
  tools/mixin/bin/test-all
Labels: master, merge on pass

#22202 5.44.0 release notes: added late changes
  release-notes/5.44.0.md
Labels: 5.44

#22182 fixes core#2974, overrides break membership update status when removed
  templates/CRM/Member/Form/Membership.tpl
Labels: 5.44

#22206 5.44.0 - Bump version. Tweak notes.
  ext/afform/admin/info.xml
  ext/afform/core/info.xml
  ext/afform/html/info.xml
  ext/afform/mock/info.xml
  ext/authx/info.xml
  ext/ckeditor4/info.xml
  ext/contributioncancelactions/info.xml
  ext/eventcart/info.xml
  ext/ewaysingle/info.xml
  ext/financialacls/info.xml
  ext/flexmailer/info.xml
  ext/greenwich/info.xml
  ext/legacycustomsearches/info.xml
  ext/message_admin/info.xml
  ext/oauth-client/info.xml
  ext/payflowpro/info.xml
  ext/recaptcha/info.xml
  ext/search_kit/info.xml
  ext/sequentialcreditnotes/info.xml
  release-notes/5.44.0.md
  sql/civicrm_generated.mysql
  sql/test_data_second_domain.mysql
  xml/version.xml
Labels: 5.44

#22210 PHP 8 compat - no optional param before required
  CRM/Mailing/Event/BAO/Resubscribe.php
  CRM/Mailing/Page/Common.php
  api/v3/MailingEventResubscribe.php
Labels: master, merge on pass

#22209 [NFC] Fix test failures for testRelativeDateRanges
  tests/phpunit/api/v4/Action/DateTest.php
Labels: 5.44

#22211 Merge forward 5.44 => master
  release-notes/5.44.0.md
  templates/CRM/Member/Form/Membership.tpl
  tests/phpunit/api/v4/Action/DateTest.php
Labels: master

#22215 (NFC) tools/mixin/bin/test-all - Work-around segfault in CI
  tools/mixin/bin/test-all
Labels: master

#22177 Smarty variables] Remove isset from relationship tab
  CRM/Contact/Page/View/Relationship.php
  CRM/Contact/Page/View/UserDashBoard.php
  templates/CRM/Contact/Page/View/RelationshipSelector.tpl
  tests/phpunit/CRM/Contact/Page/View/UserDashBoardTest.php
Labels: master, merge on pass

#22181 [Smarty variables] Remove another isset - user dashboard
  CRM/Contact/Page/View/UserDashBoard.php
  templates/CRM/Contact/Page/View/UserDashBoard.tpl
Labels: master

#22190 [Smarty variables] remove isset from Mail accounts
  CRM/Admin/Page/MailSettings.php
  templates/CRM/Admin/Page/MailSettings.tpl
Labels: master

#22191 Smarty variables] Remove isset from a.net
  CRM/Core/Payment/AuthorizeNet.php
  templates/CRM/Contribute/Form/Contribution/AuthorizeNetARB.tpl
Labels: master

#22207 [REF] - Switch BAOs to use standard delete function which calls hooks
  CRM/Case/BAO/CaseType.php
  CRM/Contact/BAO/ContactType.php
  CRM/Contact/BAO/RelationshipType.php
  CRM/Core/BAO/LocationType.php
  CRM/Core/BAO/Mapping.php
  CRM/Core/BAO/MessageTemplate.php
  CRM/Core/BAO/OptionGroup.php
  CRM/Core/BAO/WordReplacement.php
  CRM/Financial/BAO/FinancialAccount.php
  CRM/Financial/BAO/FinancialType.php
  CRM/Financial/BAO/PaymentProcessor.php
  CRM/Financial/BAO/PaymentProcessorType.php
  CRM/Member/BAO/MembershipStatus.php
  CRM/Member/BAO/MembershipType.php
  Civi/Api4/Generic/Traits/DAOActionTrait.php
  Civi/Api4/Service/Spec/Provider/FieldDomainIdSpecProvider.php
  tests/phpunit/api/v4/Action/BaseCustomValueTest.php
  tests/phpunit/api/v4/Entity/ContactTypeTest.php
  tests/phpunit/api/v4/Entity/WordReplacementTest.php
Labels: master

#22205 APIv4 ConformanceTest - Demonstrate entity APIs which fail to emit `hook_civicrm_post(delete)`
  tests/phpunit/api/v4/Entity/ConformanceTest.php
Labels: master, merge on pass

#22189 [Smarty variables] Consistently assign isAdmin at php layer
  CRM/Contact/Form/Task/EmailTrait.php
  CRM/Contact/Form/Task/SMS.php
  CRM/Contribute/Form/Task/Invoice.php
  CRM/Contribute/Page/DashBoard.php
  CRM/SMS/Form/Group.php
  templates/CRM/Admin/Form/MessageTemplates.tpl
  templates/CRM/Admin/Form/ScheduleReminders.tpl
Labels: master

#22218 SearchKit - Fix undefined variable for searches of Afforms etc.
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdmin.component.js
Labels: master, merge on pass

#22219 [NFC] Remove Selenium WebTest code from CiviMailUtils
  tests/phpunit/CiviTest/CiviMailUtils.php
Labels: master, merge on pass

#22201 APIv4 Export - Fix logic for exporting pseudoconstant syntax
  Civi/Api4/Generic/ExportAction.php
  tests/phpunit/api/v4/Entity/ManagedEntityTest.php
Labels: has-test, 5.45

#22221 [NFC] Update System Uft8mb4 check to handle for the fact that MySQL8 …
  tests/phpunit/api/v3/SystemTest.php
Labels: merge on pass, 5.45

#22222 5.45
  Civi/Api4/Generic/ExportAction.php
  tests/phpunit/api/v3/SystemTest.php
  tests/phpunit/api/v4/Entity/ManagedEntityTest.php
Labels: master

#18158 Initial refactor of createProfileContact groups
  CRM/Contact/BAO/Contact.php
  CRM/Contact/BAO/GroupContact.php
  api/v3/GroupContact.php
  tests/phpunit/CRM/Contact/BAO/ContactTest.php
Labels: master, merge ready, has-test, sig-Refactor

#22224 NFC - Cleanup messy boilerplate
  CRM/Upgrade/Incremental/php/FiveFortySix.php
Labels: master, merge on pass

#22217 dev/core#2982 - Deprecated warnings for money formatting in Repeat Contributions CiviReport
  CRM/Report/Form/Contribute/Repeat.php
  tests/phpunit/api/v3/ReportTemplateTest.php
Labels: master, has-test

#22192 [Smarty variables] Remove issets from payment processor form
  CRM/Admin/Page/PaymentProcessorType.php
  CRM/Core/Page/Basic.php
  templates/CRM/Admin/Page/PaymentProcessorType.tpl
Labels: master

#22230 5.45.0 release notes initial run
  contributor-key.yml
  release-notes.md
  release-notes/5.45.0.md
Labels: 5.45

#22195 [Smarty variables] Remove issets relating to auto_renew
  CRM/Contribute/Form/Contribution/Main.php
  templates/CRM/Contribute/Form/Contribution/MembershipBlock.tpl
  templates/CRM/Price/Form/PriceSet.tpl
Labels: master, merge on pass

#22194 [Smarty variables] Fix overzealous escaping with smarty default escaping
  templates/CRM/common/formButtons.tpl
Labels: master, merge on pass

#22214 (dev/core#2979) remove the limit of 15 max values for multiple values…
  CRM/Report/Utils/Get.php
Labels: master

#22203 Revert "Add permission metadata to contact is_deleted field"
  CRM/Contact/DAO/Contact.php
  xml/schema/Contact/Contact.xml
Labels: merge ready, 5.45

#22231 dev/core#2984 - Clarify API error when component is disabled
  Civi/API/Request.php
  tests/phpunit/api/v4/Entity/EntityTest.php
Labels: master

#22193 [Smarty variables] remove isset from merge screen
  CRM/Contact/Form/Merge.php
  templates/CRM/Contact/Form/Merge.tpl
Labels: master

#22234 Afform - Set date-range defaults
  Civi/Api4/Service/Spec/SpecFormatter.php
  js/crm.datepicker.js
Labels: master

#22187 Smarty variables] Remove isset from batch form
  CRM/Financial/Form/BatchTransaction.php
  templates/CRM/Financial/Form/Search.tpl
Labels: master

#22237 (REF) CRM/Upgrade - Remove unused entrypoint `verifyPreDBstate()`
  CRM/Upgrade/Form.php
  CRM/Upgrade/Incremental/Base.php
Labels: master

#22186 Smarty variables] Another isset bites the dust
  CRM/Event/Page/EventInfo.php
  templates/CRM/Event/Page/EventInfo.tpl
Labels: master

#22238 Upgrade - Bump minimum upgradable version to 4.6.12
  CRM/Core/BAO/RecurringEntity.php
  CRM/Upgrade/4.6.10.msg_template/civicrm_msg_template.tpl
  CRM/Upgrade/4.6.10.msg_template/message_templates/contribution_online_receipt_html.tpl
  CRM/Upgrade/4.6.10.msg_template/message_templates/test_preview_html.tpl
  CRM/Upgrade/4.6.3.msg_template/civicrm_msg_template.tpl
  CRM/Upgrade/4.6.3.msg_template/message_templates/event_online_receipt_html.tpl
  CRM/Upgrade/4.6.3.msg_template/message_templates/event_online_receipt_text.tpl
  CRM/Upgrade/4.6.9.msg_template/civicrm_msg_template.tpl
  CRM/Upgrade/4.6.9.msg_template/message_templates/contribution_invoice_receipt_html.tpl
  CRM/Upgrade/4.6.alpha1.msg_template/civicrm_msg_template.tpl
  CRM/Upgrade/4.6.alpha1.msg_template/message_templates/contribution_invoice_receipt_html.tpl
  CRM/Upgrade/4.6.alpha1.msg_template/message_templates/contribution_invoice_receipt_subject.tpl
  CRM/Upgrade/4.6.alpha1.msg_template/message_templates/contribution_invoice_receipt_text.tpl
  CRM/Upgrade/4.6.alpha1.msg_template/message_templates/contribution_offline_receipt_html.tpl
  CRM/Upgrade/4.6.alpha1.msg_template/message_templates/contribution_offline_receipt_text.tpl
  CRM/Upgrade/4.6.alpha1.msg_template/message_templates/contribution_online_receipt_html.tpl
  CRM/Upgrade/4.6.alpha1.msg_template/message_templates/contribution_online_receipt_text.tpl
  CRM/Upgrade/4.6.alpha1.msg_template/message_templates/event_offline_receipt_html.tpl
  CRM/Upgrade/4.6.alpha1.msg_template/message_templates/event_offline_receipt_text.tpl
  CRM/Upgrade/4.6.alpha1.msg_template/message_templates/event_online_receipt_html.tpl
  CRM/Upgrade/4.6.alpha1.msg_template/message_templates/event_online_receipt_text.tpl
  CRM/Upgrade/4.6.alpha1.msg_template/message_templates/membership_offline_receipt_html.tpl
  CRM/Upgrade/4.6.alpha1.msg_template/message_templates/membership_offline_receipt_text.tpl
  CRM/Upgrade/4.6.alpha1.msg_template/message_templates/membership_online_receipt_html.tpl
  CRM/Upgrade/4.6.alpha1.msg_template/message_templates/membership_online_receipt_text.tpl
  CRM/Upgrade/4.6.alpha4.msg_template/civicrm_msg_template.tpl
  CRM/Upgrade/4.6.alpha4.msg_template/message_templates/pcp_owner_notify_html.tpl
  CRM/Upgrade/4.6.alpha4.msg_template/message_templates/pcp_owner_notify_subject.tpl
  CRM/Upgrade/4.6.alpha4.msg_template/message_templates/pcp_owner_notify_text.tpl
  CRM/Upgrade/Form.php
  CRM/Upgrade/Incremental/php/FourSix.php
  CRM/Upgrade/Incremental/sql/4.4.7.mysql.tpl
  CRM/Upgrade/Incremental/sql/4.6.0.mysql.tpl
  CRM/Upgrade/Incremental/sql/4.6.1.mysql.tpl
  CRM/Upgrade/Incremental/sql/4.6.10.mysql.tpl
  CRM/Upgrade/Incremental/sql/4.6.11.mysql.tpl
  CRM/Upgrade/Incremental/sql/4.6.12.mysql.tpl
  CRM/Upgrade/Incremental/sql/4.6.2.mysql.tpl
  CRM/Upgrade/Incremental/sql/4.6.3.mysql.tpl
  CRM/Upgrade/Incremental/sql/4.6.4.mysql.tpl
  CRM/Upgrade/Incremental/sql/4.6.5.mysql.tpl
  CRM/Upgrade/Incremental/sql/4.6.6.mysql.tpl
  CRM/Upgrade/Incremental/sql/4.6.7.mysql.tpl
  CRM/Upgrade/Incremental/sql/4.6.8.mysql.tpl
  CRM/Upgrade/Incremental/sql/4.6.9.mysql.tpl
  CRM/Upgrade/Incremental/sql/4.6.alpha1.mysql.tpl
  CRM/Upgrade/Incremental/sql/4.6.alpha2.mysql.tpl
  CRM/Upgrade/Incremental/sql/4.6.alpha3.mysql.tpl
  CRM/Upgrade/Incremental/sql/4.6.alpha4.mysql.tpl
  CRM/Upgrade/Incremental/sql/4.6.alpha5.mysql.tpl
  CRM/Upgrade/Incremental/sql/4.6.alpha6.mysql.tpl
  CRM/Upgrade/Incremental/sql/4.6.alpha7.mysql.tpl
  CRM/Upgrade/Incremental/sql/4.6.beta1.mysql.tpl
  CRM/Upgrade/Incremental/sql/4.6.beta2.mysql.tpl
  CRM/Upgrade/Incremental/sql/4.6.beta3.mysql.tpl
  CRM/Upgrade/Incremental/sql/4.6.beta4.mysql.tpl
  CRM/Upgrade/Incremental/sql/4.6.beta5.mysql.tpl
Labels: master

#22225 Simplify autogenerated boilerplate upgrader class
  CRM/Upgrade/Incremental/Base.php
  CRM/Upgrade/Incremental/php/Template.php
  tools/bin/scripts/set-version.php
Labels: master, merge ready

#22096 (dev/core#2962) get contact id for the mailing along with display nam…
  CRM/Mailing/Event/BAO/Queue.php
Labels: master

#22213 [REF] Afform - Use APIv4 for managed dashboard
  ext/afform/core/afform.php
Labels: master

#22240 Contact/BAO/Query.php: fix searching for whitespace
  CRM/Contact/BAO/Query.php
  tests/phpunit/CRM/Contact/BAO/QueryTest.php
  tests/phpunit/api/v3/ContactTest.php
Labels: master, merge ready

#22247 Contribution Confirm: fix wording on the recurring
  templates/CRM/Contribute/Form/Contribution/Confirm.tpl
Labels: merge on pass, 5.45

#22246 Update Brick/Money to 0.5.3
  composer.json
  composer.lock
Labels: master

#22244 dev/core#2977 - For custom group creation, flip the default display settings
  CRM/Custom/Form/Group.php
Labels: master, merge on pass

#22248 Contributor key: Add Matt Trim
  contributor-key.yml
Labels: master, merge on pass

#22243 dev/core#2825 - Make source contact required for activities on the form
  CRM/Activity/Form/Activity.php
Labels: master, merge ready

#22252 Move require_once for smarty modifier due to order issues
  CRM/Core/Smarty.php
Labels: master, merge on pass

#22249 [NFC] Minor cleanup in test class
  tests/phpunit/CRM/Dedupe/MergerTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: master, merge on pass

#22251 [NFC] Test cleanup
  tests/phpunit/api/v3/RelationshipTest.php
Labels: master

#22253 [REF] Minor parameter simplification
  CRM/Contact/BAO/Relationship.php
Labels: master

#22256 Do not default-escape weight field on order
  templates/CRM/Admin/Page/Options.tpl
Labels: master

#22183 Smarty variables] Remove another isset - deferredFinancialType
  CRM/Event/Form/ManageEvent/Fee.php
  CRM/Member/Form/MembershipType.php
  templates/CRM/common/deferredFinancialType.tpl
Labels: master

#22257 (NFC) APIv4: Add help info for multi-record custom field sets
  Civi/Api4/Generic/DAOGetAction.php
Labels: master, merge on pass

#22254 [REF] Duplicate function to allow us to work it out of the code
  CRM/Dedupe/Merger.php
Labels: master

#22258 Remove never passed variables
  CRM/Dedupe/Merger.php
Labels: master, merge on pass

#22259 Rename protected function
  CRM/Dedupe/Merger.php
Labels: master, merge on pass

#22260 Remove handling for always-truthy var being false
  CRM/Dedupe/Merger.php
Labels: master, merge on pass

#22261 [REF] Remove more params that are unused now function is not shared
  CRM/Dedupe/Merger.php
Labels: master, merge on pass

#21762 Add system status warning to display scheduled job failures
  CRM/Utils/Check/Component/Env.php
Labels: master

#22236 Resources: set language-specific cacheCode, fixes AngularJS translation with multilingual
  CRM/Core/Resources.php
  tests/phpunit/CRM/Core/ResourcesTest.php
Labels: master

#22107 dev/core#2927 - Avoid warnings for is_dir() when open_basedir is in effect
  CRM/Admin/Page/APIExplorer.php
  CRM/Utils/File.php
  tests/phpunit/CRM/Utils/FileTest.php
Labels: master, has-test

#22270 Fix related contacts label in search kit
  Civi/Api4/RelationshipCache.php
Labels: sig:regression, 5.45

#22271 5.45
  Civi/Api4/RelationshipCache.php
  templates/CRM/Contribute/Form/Contribution/Confirm.tpl
Labels: master

#22233 APIv4 Explorer - Make selected language and format bookmarkable
  ang/api4Explorer/Explorer.js
Labels: master

#21927 Move two more functions to financialProcessor
  CRM/Contribute/BAO/Contribution.php
  CRM/Contribute/BAO/FinancialProcessor.php
Labels: master, merge on pass

#22272 [NFC] Cleanup in Authorize.net test class
  tests/phpunit/CRM/Core/Payment/AuthorizeNetIPNTest.php
Labels: master

#22279 Remove unnecessary pass-by-ref
  CRM/Contribute/Form/Contribution/Confirm.php
Labels: master, merge on pass

#22278 Remove unused function CRM/Utils/Mail/EmailProcessor::cleanupDir
  CRM/Utils/Mail/EmailProcessor.php
Labels: master, merge on pass

#22275 dev/core#567 Add test shell
  tests/phpunit/api/v3/ContributionPageTest.php
Labels: master, merge on pass

#22265 dev/core#2996 Increment php recommndations
  CRM/Upgrade/Incremental/General.php
Labels: master

#22282 CustomGroup - Add pseudoconstant for extends column
  CRM/Core/DAO/CustomGroup.php
  tests/phpunit/api/v3/ACLCachingTest.php
  xml/schema/Core/CustomGroup.xml
Labels: master, merge on pass

#22276 [REF] Duplicate & unshare processFormContribution
  CRM/Contribute/Form/Contribution.php
  CRM/Contribute/Form/Contribution/Confirm.php
Labels: master

#22283 Cleanup Smarty e-notices on campaign dashboard
  CRM/Campaign/Page/DashBoard.php
  templates/CRM/Campaign/Page/DashBoard.tpl
Labels: master, merge on pass

#22284 [REF] Remove now non-variable variables from previously shared code
  CRM/Contribute/Form/Contribution.php
  CRM/Contribute/Form/Contribution/Confirm.php
Labels: master, merge on pass

#22229 SearchKit - Import/Export saved search configuration
  Civi/Angular/Manager.php
  ang/crmDialog.ang.php
  ang/crmDialog.js
  ang/crmDialog.md
  ext/afform/core/Civi/Api4/Utils/AfformFormatTrait.php
  ext/message_admin/ang/crmDialog.ang.php
  ext/search_kit/ang/crmSearchAdmin.ang.php
  ext/search_kit/ang/crmSearchAdmin.module.js
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdminExport.component.js
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdminExport.html
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdminImport.component.js
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdminImport.html
  ext/search_kit/ang/crmSearchAdmin/searchListing/buttons.html
  ext/search_kit/ang/crmSearchAdmin/searchListing/crmSearchAdminSearchListing.component.js
  ext/search_kit/ang/crmSearchAdmin/searchListing/export.html
  ext/search_kit/ang/crmSearchAdmin/searchListing/import.html
  ext/search_kit/ang/crmSearchAdmin/searchListing/searchList.html
  ext/search_kit/css/crmSearchAdmin.css
Labels: master, merge ready

#21611 Add workflow template for recurring cancelled
  CRM/Contribute/Form/CancelSubscription.php
  CRM/Contribute/WorkflowMessage/RecurringCancelled.php
  CRM/Contribute/WorkflowMessage/RecurringEdit.php
  CRM/Contribute/WorkflowMessage/RecurringTrait.php
  tests/phpunit/CRM/Contribute/Form/CancelSubscriptionTest.php
Labels: master

#22287 [REF] Stop passing this as form, set in function
  CRM/Contribute/Form/Contribution/Confirm.php
Labels: master, merge on pass

#22289 Enotice fixes on ContributionPage dash
  CRM/Utils/PagerAToZ.php
  templates/CRM/common/pagerAToZ.tpl
Labels: master, merge on pass

#22228 Apiv4 - Make Groups a managed entity, fix 'null' bugs in BAO_Group
  CRM/Contact/BAO/Group.php
  CRM/Core/ManagedEntities.php
  Civi/Api4/Group.php
  tests/phpunit/api/v4/Entity/ManagedEntityTest.php
Labels: master, has-test

#22281 SearchKit - Fix "Combine Text" transformation
  ext/search_kit/ang/crmSearchAdmin/crmSearchFunction.component.js
Labels: sig:regression, 5.45

#22288 [REF] move code into the function
  CRM/Contribute/Form/Contribution/Confirm.php
Labels: master

#22293 SearchKit - Fix editable custom fields
  ext/search_kit/Civi/Api4/Action/SearchDisplay/AbstractRunAction.php
Labels: merge on pass, sig:regression, 5.45

#22296 Add recurring conributions to sample data
  CRM/Core/CodeGen/GenerateData.php
  sql/civicrm_generated.mysql
Labels: master

#22301 Follow up fix on recur data
  CRM/Core/CodeGen/GenerateData.php
  sql/civicrm_generated.mysql
Labels: master, merge on pass

#22299 SearchKit - better icon for packaged searches
  ext/search_kit/ang/crmSearchAdmin.module.js
Labels: 5.45

#22295 [NFC] First Pass at Release Notes for 5.45
  contributor-key.yml
  release-notes/5.45.0.md
Labels: 5.45

#22297 Merge 5.45 to master
  contributor-key.yml
  ext/search_kit/Civi/Api4/Action/SearchDisplay/AbstractRunAction.php
  ext/search_kit/ang/crmSearchAdmin.module.js
  ext/search_kit/ang/crmSearchAdmin/crmSearchFunction.component.js
  release-notes/5.45.0.md
Labels: master

#22290 Fix broken links in default modifier mode on manage contributions
  templates/CRM/Contribute/Page/ContributionPage.tpl
Labels: master

#22294 Do not apply default escaping to multiselects on currency form
  templates/CRM/Admin/Form/Setting/Localization.tpl
Labels: master

#22304 Display label before input elements on SMTP settings page
  templates/CRM/Admin/Form/Setting/Smtp.tpl
Labels: master, merge on pass

#22300 SearchKit - Tweak export explorer link icon + format
  ang/api4Explorer/Explorer.js
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdminExport.component.js
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdminExport.html
Labels: master

#22306 Fix char-set for default escaping
  CRM/Core/Smarty.php
Labels: master, merge on pass

#22308 E-notice fix (smarty)
  CRM/Contribute/Selector/Search.php
  templates/CRM/Contribute/Form/Selector.tpl
Labels: master, merge on pass

#22286 dev/core#3000 Fix database error when copying custom data fields from…
  CRM/Core/BAO/Address.php
  CRM/Core/BAO/CustomValueTable.php
  tests/phpunit/api/v3/AddressTest.php
Labels: merge on pass, 5.45

#22302 SearchKit - Add links for CustomField and CustomGroup entities
  CRM/Core/DAO/CustomField.php
  CRM/Core/DAO/CustomGroup.php
  ext/search_kit/Civi/Api4/Action/SearchDisplay/AbstractRunAction.php
  ext/search_kit/Civi/Search/Display.php
  xml/schema/Core/CustomField.xml
  xml/schema/Core/CustomGroup.xml
Labels: master

#22298 APIv3 - Fix overzealous pseudoconstant matching
  api/v3/MailingContact.php
  api/v3/utils.php
  tests/phpunit/CRM/Contact/BAO/ContactType/ContactSearchTest.php
Labels: master

#22317 5.45
  CRM/Core/BAO/Address.php
  CRM/Core/BAO/CustomValueTable.php
  tests/phpunit/api/v3/AddressTest.php
Labels: master

#22312 Event Registration: initialize array
  CRM/Event/Form/Registration.php
Labels: master

#22311 Allow text to be translated and fix URL paths in calls to docURL() function.
  templates/CRM/ACL/Header.tpl
  templates/CRM/Admin/Form/Setting/Component.hlp
  templates/CRM/Admin/Form/Setting/Event.tpl
  templates/CRM/Admin/Page/Access.tpl
  templates/CRM/Admin/Page/ConfigTaskList.tpl
  templates/CRM/Admin/Page/Job.tpl
  templates/CRM/Admin/Page/PaymentProcessor.hlp
  templates/CRM/Admin/Page/Setting.tpl
  templates/CRM/Case/Page/ConfigureError.tpl
  templates/CRM/Contact/Form/Contact.hlp
  templates/CRM/Contact/Form/OnBehalfOf.tpl
  templates/CRM/Contact/Form/Search/Builder.hlp
  templates/CRM/Contribute/Form/ContributionPage/Custom.hlp
  templates/CRM/Custom/Page/Group.hlp
  templates/CRM/Event/Form/ManageEvent/Registration.hlp
  templates/CRM/Group/Page/Group.hlp
  templates/CRM/Member/Form/MembershipBlock.tpl
  templates/CRM/Member/Page/DashBoard.hlp
  templates/CRM/common/footer.tpl
Labels: master

#22307 Demo sample data - Add in some mixed currency contributions
  CRM/Core/CodeGen/GenerateData.php
  sql/civicrm_generated.mysql
  xml/templates/civicrm_data.tpl
Labels: master

#22305 Enable more currencies by default
  xml/templates/civicrm_data.tpl
Labels: master, merge ready

#22292 Add authx_login() API for backend script authentication (alt)
  CRM/Utils/System/Drupal8.php
  ext/authx/Civi/Authx/Authenticator.php
  ext/authx/Civi/Authx/AuthxException.php
  ext/authx/authx.php
  ext/authx/settings/authx.setting.php
  ext/authx/tests/phpunit/Civi/Authx/AllFlowsTest.php
Labels: master, has-test

#22322 APIv4 - Set default status when creating GroupContact record
  Civi/Api4/Service/Spec/Provider/GroupContactCreationSpecProvider.php
  tests/phpunit/api/v4/Entity/GroupContactTest.php
  tests/phpunit/api/v4/UnitTestCase.php
Labels: master, has-test

#22328 APIv4 - Fix saving NULL as custom field value
  Civi/Api4/Generic/Traits/DAOActionTrait.php
  tests/phpunit/api/v4/Action/BasicCustomFieldTest.php
Labels: master, has-test

#22331 SearchKit - Fix column headers for custom fields in default display
  ext/search_kit/Civi/Api4/Action/SearchDisplay/GetDefault.php
Labels: master

#22310 Fix JS Error for Free event with multiple participant on registration…
  templates/CRM/Event/Form/Registration/Register.tpl
Labels: master, merge on pass

#22332 Remove unused method getGrantStatusOptGroup
  CRM/Grant/BAO/Grant.php
Labels: master, merge on pass

#22336 Fix typo. CRM_Core_Execption should be CRM_Core_Exception
  CRM/Mailing/BAO/MailingJob.php
Labels: master, merge on pass

#22335 Correctly mark updateStatusMessage method as static
  CRM/Event/BAO/Participant.php
Labels: master

#22334 Fix inaccuracies and mistakes in comments (especially phpdoc comments)
  CRM/Batch/BAO/Batch.php
  CRM/Core/BAO/CustomGroup.php
  CRM/Core/BAO/Website.php
  CRM/Core/Reference/Basic.php
  CRM/Event/BAO/Event.php
  CRM/Event/BAO/Participant.php
  CRM/Event/Form/ManageEvent/Registration.php
  CRM/Event/Form/Participant.php
  CRM/Event/Page/EventInfo.php
  CRM/Event/Selector/Search.php
  CRM/Extension/Browser.php
  CRM/Extension/Info.php
  CRM/Extension/Mapper.php
  CRM/Financial/BAO/ExportFormat.php
  CRM/Financial/Form/Export.php
  CRM/Logging/Schema.php
  CRM/Mailing/BAO/Mailing.php
  CRM/Mailing/Event/BAO/Forward.php
  CRM/Mailing/Page/Browse.php
  CRM/Member/Form/MembershipRenewal.php
  CRM/Member/Selector/Search.php
  CRM/Pledge/Selector/Search.php
  CRM/Price/BAO/LineItem.php
  CRM/Report/Form.php
  CRM/Utils/Type.php
Labels: master

#22315 Wrap another set of hardcoded strings in {ts}
  CRM/PCP/BAO/PCP.php
  CRM/Pledge/Form/Pledge.php
  CRM/Report/Form/Contribute/Summary.php
  CRM/UF/Form/Group.php
  templates/CRM/Contact/Form/Merge.tpl
  templates/CRM/Contact/Page/DedupeException.tpl
  templates/CRM/Mailing/Page/Report.tpl
  templates/CRM/Member/Form/MembershipView.tpl
  templates/CRM/UF/Form/AdvanceSetting.tpl
Labels: master

#22333 Fix Profile helptext menu reference to reCaptcha (by r4zoli)
  templates/CRM/UF/Form/Group.hlp
Labels: master

#22338 Fix params passed to setStatus method
  CRM/Admin/Form/PdfFormats.php
  CRM/Price/Form/DeleteSet.php
Labels: master

#22303 "Open in new tab" on .crm-summary-link icons should open contact page
  CRM/Contact/BAO/Contact/Utils.php
  CRM/Contact/Selector.php
  js/Common.js
  tests/phpunit/CRM/Activity/Form/SearchTest.php
  tests/phpunit/CRM/Financial/Page/AjaxTest.php
  tests/phpunit/CRM/Member/Selector/SearchTest.php
  tests/phpunit/CRM/Pledge/Form/SearchTest.php
Labels: master, merge ready

#21596 Find Activities Search, default search option for Activity Status will exclude Activities by default which do not have a status of Scheduled or Completed. Confuses and frustrates End Users.
  CRM/Activity/BAO/Query.php
Labels: master, merge ready

#22339 [NFC] CRM_Core_Exception incorrectly called without message
  CRM/Contact/BAO/Contact.php
Labels: master

#22321 SearchKit - Fix UI for configuring display pager limit
  ext/search_kit/ang/crmSearchAdmin/displays/common/searchAdminPagerConfig.component.js
  ext/search_kit/ang/crmSearchAdmin/displays/common/searchAdminPagerConfig.html
  ext/search_kit/css/crmSearchAdmin.css
Labels: master

#22341 fixes core#3013 - error when creating > 25 thank-you letters
  CRM/Contribute/Form/Task/PDFLetter.php
Labels: merge on pass, 5.45

#22342 5.45 to master
  CRM/Contribute/Form/Task/PDFLetter.php
Labels: master

#22280 [REF] Simplify getContributionStatuses
  CRM/Contribute/BAO/Contribution/Utils.php
  CRM/Core/BAO/UFGroup.php
  CRM/Event/Form/Participant.php
  CRM/Member/Form/Membership.php
  CRM/Member/Form/MembershipRenewal.php
Labels: master, merge on pass

#22285 dev/core#3001 escape single quotes when rendering tokens in html format
  Civi/Token/TokenRow.php
  tests/phpunit/CRM/Core/TokenSmartyTest.php
Labels: master, merge on pass

#22345 [REF] Deprecated old getContributionStatuses
  CRM/Contribute/BAO/Contribution/Utils.php
  CRM/Contribute/Form/Contribution.php
Labels: master, merge on pass

#21181 dev/core#2752 Use acl, not blanket permissions on FinancialAccount, FinancialType, EntityFinancialAccount
  CRM/Contribute/BAO/ContributionPage.php
  CRM/Core/Permission.php
  CRM/Event/BAO/Event.php
  CRM/Financial/BAO/FinancialType.php
  api/v3/Generic.php
  ext/financialacls/financialacls.php
  ext/financialacls/tests/phpunit/Civi/Financialacls/EntityFinancialAccountTest.php
  ext/financialacls/tests/phpunit/Civi/Financialacls/FinancialAccountTest.php
  ext/financialacls/tests/phpunit/Civi/Financialacls/FinancialTypeTest.php
  tests/phpunit/CRM/Financial/BAO/FinancialTypeTest.php
Labels: master

#22241 SearchKit - Allow functions in the WHERE clause
  Civi/Api4/Query/Api4SelectQuery.php
  css/crm-i.css
  ext/search_kit/Civi/Search/Admin.php
  ext/search_kit/ang/crmSearchAdmin.module.js
  ext/search_kit/ang/crmSearchAdmin/compose.html
  ext/search_kit/ang/crmSearchAdmin/crmSearchClause.component.js
  ext/search_kit/ang/crmSearchAdmin/crmSearchClause.html
  ext/search_kit/ang/crmSearchAdmin/crmSearchFunction.component.js
  ext/search_kit/ang/crmSearchAdmin/crmSearchFunction.html
  tests/phpunit/api/v4/Action/SqlFunctionTest.php
Labels: master, has-test

#22340 Add workflow template classes for contributions
  CRM/Contribute/Form/Task/Invoice.php
  CRM/Contribute/WorkflowMessage/ContributionInvoiceReceipt.php
  CRM/Contribute/WorkflowMessage/ContributionOfflineReceipt.php
  CRM/Contribute/WorkflowMessage/ContributionOnlineReceipt.php
  CRM/Contribute/WorkflowMessage/ContributionTrait.php
  tests/phpunit/CRM/Contribute/Form/Task/InvoiceTest.php
  tests/templates/message_templates/contribution_invoice_receipt_html.tpl
Labels: master, merge on pass

#22351 Fix membership test fail for Dec 31
  tests/phpunit/CRM/Member/Form/MembershipTest.php
Labels: master

#22348 Use JS escaping for {ts} calls in a JS context
  templates/CRM/Campaign/Form/Task/Interview.tpl
  templates/CRM/Contact/Form/Edit/Lock.tpl
  templates/CRM/Contact/Form/Merge.tpl
  templates/CRM/Contact/Form/ShareAddress.tpl
  templates/CRM/Contribute/Form/Contribution.tpl
  templates/CRM/Event/Form/SelfSvcUpdate.tpl
Labels: master, merge on pass

#22337 dev/drupal#172 - Deprecated function call in Drupal 9.3
  CRM/Utils/System/Drupal8.php
Labels: master, merge on pass

#22326 SqlParallel - Enable more tests. Fix compatiblity with `release_time`
  CRM/Queue/Queue/SqlParallel.php
  tests/phpunit/CRM/Queue/QueueTest.php
Labels: master, has-test
