Repository civicrm/civicrm-core, pull requests merged in 2022-12, with the labels that each got.

#25092 [php 8] Update pear/mail to 1.5
  composer.json
  composer.lock
Labels: master, merge on pass

#25095 [REF] Results of npm audit fix
  package-lock.json
Labels: 5.56

#25096 5.56
  package-lock.json
Labels: master

#25091 SearchKit - Fix crashy-ness when an Afform contains a deleted search
  ext/search_kit/Civi/Search/AfformSearchMetadataInjector.php
Labels: master

#25077 Add noisy deprecation to `getContactTokenReplacement`
  CRM/Utils/Token.php
Labels: master

#25085 Test cleanup, remove calls to deprecated financial BAO functions
  tests/phpunit/CRM/Contribute/BAO/ContributionTypeTest.php
  tests/phpunit/CRM/Financial/BAO/FinancialTypeTest.php
Labels: master

#25060 Remove deprecated PdfLetterCommon class - membership
  CRM/Member/Form/Task/PDFLetterCommon.php
Labels: master

#25076 Remove handling for legacy `preferred_mail_format`
  CRM/Mailing/Event/BAO/MailingEventReply.php
Labels: master

#25100 PHP8.1 - prices must be numbers, not strings for arithmetic
  CRM/Price/BAO/LineItem.php
Labels: 5.56

#25078 Add handling to token processor for double http in url tokens
  Civi/Core/Container.php
  Civi/Token/TidySubscriber.php
  Civi/Token/TokenProcessor.php
  tests/phpunit/Civi/Token/TokenProcessorTest.php
Labels: master, has-test

#25104 DebugSubscriber - Fix activation check
  Civi/API/Subscriber/DebugSubscriber.php
Labels: 5.51

#25105 DebugSubscriber - Fix activation check
  Civi/API/Subscriber/DebugSubscriber.php
Labels: 5.45

#25103 5.56
  CRM/Price/BAO/LineItem.php
Labels: master

#25088 Duplicate `Activity::importableFields` to upgrader & increase deprecation
  CRM/Activity/BAO/Activity.php
  CRM/Upgrade/Incremental/php/FiveFiftyOne.php
Labels: master

#25003 improve social sharing footer
  templates/CRM/common/SocialNetwork.tpl
Labels: master

#25107 Rename test class to reflect tested class
  tests/phpunit/CRM/Activity/Form/Task/PDFTest.php
Labels: master

#25112 dev/core#1634 Deprecate unused activity columns
  CRM/Activity/DAO/Activity.php
  xml/schema/Activity/Activity.xml
Labels: master, merge on pass

#25109 Remove further usage of 'preferred_mail_format'
  CRM/Mailing/Event/BAO/MailingEventResubscribe.php
  CRM/Mailing/Event/BAO/MailingEventUnsubscribe.php
Labels: master

#25101 Support multiple contact_type in hook_civicrm_tabset
  CRM/Contact/Page/View/Summary.php
  ext/afform/core/afform.php
  ext/afform/core/tests/phpunit/Civi/Afform/AfformContactSummaryTest.php
Labels: master

#25106 Remove unused, deprecated class `CRM_Activity_Form_Task_PDFLetterCommon`
  CRM/Activity/Form/Task/PDFLetterCommon.php
Labels: master

#25099 Metadata - Add default labelField to all DAO entities
  CRM/Batch/DAO/Batch.php
  CRM/Case/DAO/CaseType.php
  CRM/Contribute/DAO/Widget.php
  CRM/Core/CodeGen/Specification.php
  CRM/Core/DAO/ActionSchedule.php
  CRM/Core/DAO/Dashboard.php
  CRM/Core/DAO/Extension.php
  CRM/Core/DAO/Menu.php
  CRM/Core/DAO/OptionGroup.php
  CRM/Core/DAO/OptionValue.php
  CRM/Core/DAO/PrintLabel.php
  CRM/Core/DAO/UFField.php
  CRM/Core/DAO/UFGroup.php
  CRM/Dedupe/DAO/DedupeRuleGroup.php
  CRM/Event/DAO/ParticipantStatusType.php
  CRM/Financial/DAO/PaymentProcessor.php
  CRM/Financial/DAO/PaymentProcessorType.php
  CRM/Friend/DAO/Friend.php
  CRM/Price/DAO/LineItem.php
  CRM/Price/DAO/PriceField.php
  CRM/Price/DAO/PriceFieldValue.php
  CRM/Price/DAO/PriceSet.php
  CRM/Report/DAO/ReportInstance.php
  CRM/SMS/DAO/Provider.php
Labels: master

#25115 dev/core#4014 add ext-fileinto php extension to composer
  composer.json
  composer.lock
Labels: master

#25114 SearchKit - Prevent 'SearchSegment not found' errors during install/upgrade
  ext/search_kit/Civi/Api4/Service/Spec/Provider/SearchSegmentExtraFieldProvider.php
Labels: 5.56

#25111 APIv4 Explorer - autocomplete cleanup
  ang/api4Explorer/Explorer.js
  ext/afform/admin/ang/afGuiEditor/afGuiFieldValue.directive.js
  js/Common.js
Labels: master

#25117 5.56
  ext/search_kit/Civi/Api4/Service/Spec/Provider/SearchSegmentExtraFieldProvider.php
Labels: master

#25102 [NFC] 5.56 release notes
  contributor-key.yml
  release-notes/5.56.0.md
Labels: 5.56

#25118 5.56 to master
  contributor-key.yml
  release-notes/5.56.0.md
Labels: master

#25113 Hide deprecated fields from SearchKit & Afform
  CRM/Activity/DAO/Activity.php
  CRM/Contact/DAO/Contact.php
  CRM/Core/DAO/Address.php
  CRM/Core/DAO/Phone.php
  Civi/Api4/Generic/BasicGetFieldsAction.php
  Civi/Api4/Service/Spec/FieldSpec.php
  Civi/Api4/Service/Spec/SpecFormatter.php
  ext/afform/admin/Civi/AfformAdmin/AfformAdminMeta.php
  ext/search_kit/Civi/Api4/Action/SearchDisplay/GetSearchTasks.php
  ext/search_kit/Civi/Search/Admin.php
  ext/search_kit/ang/crmSearchTasks/crmSearchTaskUpdate.ctrl.js
  tests/phpunit/api/v4/Action/GetFieldsTest.php
  xml/templates/dao.tpl
Labels: master

#25098 dev/core#4020 Remove old recaptcha options
  CRM/Core/Config/MagicMerge.php
  CRM/Upgrade/Incremental/sql/5.57.alpha1.mysql.tpl
  api/v3/examples/Setting/GetFields.ex.php
  ext/recaptcha/CRM/Utils/ReCAPTCHA.php
  ext/recaptcha/settings/recaptcha.setting.php
  ext/recaptcha/templates/CRM/common/ReCAPTCHA.tpl
Labels: master, merge ready

#25121 remove unused code in Profile template
  templates/CRM/Profile/Form/Dynamic.tpl
Labels: master, merge on pass

#25119 dev/core#1532 - Upgrade message about old civicase activity revisions
  CRM/Activity/DAO/Activity.php
  CRM/Upgrade/Incremental/php/FiveFiftySeven.php
  xml/schema/Activity/Activity.xml
Labels: master, merge on pass

#25067 dev/core#4008 - alternate to 24998 - Avoid symbol scan errors
  ext/afform/core/Civi/Afform/Symbols.php
Labels: 5.56

#24998 Avoid symbol scan errors in oauth-client help text
  ext/oauth-client/ang/oauthClientCreateHelp.aff.html
Labels: master

#25128 Output of npm audit fix
  package-lock.json
Labels: merge on pass, 5.56

#25130 5.56
  ext/afform/core/Civi/Afform/Symbols.php
  package-lock.json
Labels: master

#25132 CRM_Utils_System_WordPress - Drop unused variable
  CRM/Utils/System/WordPress.php
Labels: master, merge on pass

#24911 [REF][PHP8.1] Fix a couple of issues where passing in NULL in string …
  CRM/Report/Page/InstanceList.php
Labels: 5.56

#25131 (NFC) dev/core#4008 - Afform - More coverage for symbol-scanner
  ext/afform/core/tests/phpunit/Civi/Afform/SymbolsTest.php
Labels: master, merge on pass

#25134 #24911 Forward port to master / 5.57
  CRM/Report/Page/InstanceList.php
Labels: master

#25110 Make flexmailer mandatory
  CRM/Upgrade/Incremental/php/FiveFiftySeven.php
  api/v3/examples/Setting/GetFields.ex.php
  ext/flexmailer/info.xml
  ext/flexmailer/settings/flexmailer.setting.php
  ext/flexmailer/src/Listener/Abdicator.php
  ext/flexmailer/tests/phpunit/Civi/FlexMailer/ClickTracker/HtmlClickTrackerTest.php
  ext/flexmailer/tests/phpunit/Civi/FlexMailer/ClickTracker/TextClickTrackerTest.php
  ext/flexmailer/tests/phpunit/Civi/FlexMailer/ConcurrentDeliveryTest.php
  ext/flexmailer/tests/phpunit/Civi/FlexMailer/FlexMailerSystemTest.php
  ext/flexmailer/tests/phpunit/Civi/FlexMailer/MailingPreviewTest.php
  ext/flexmailer/tests/phpunit/Civi/FlexMailer/ValidatorTest.php
  ext/flexmailer/xml/Menu/flexmailer.xml
  tests/phpunit/CRM/Mailing/BaseMailingSystemTest.php
  tests/phpunit/CRM/Mailing/MailingSystemTest.php
Labels: master, merge ready

#25129 Fix core#7016 in a second location
  templates/CRM/Financial/Form/Search.tpl
Labels: master

#24925 Fold `processGreetingTemplate` function only called from one place into caller, deprecate
  CRM/Contact/BAO/Contact/Utils.php
Labels: master

#25136 Remove always-true ifs
  CRM/Contact/Import/Parser/Contact.php
Labels: master

#25138 [NFC] Update instructions for running regen online
  .github/workflows/regen.yml
Labels: master

#25139 Cast membership object as array before passing to getMembershipStatusByDate()
  CRM/Member/BAO/Membership.php
Labels: master

#24798 ensure currency is included to avoid translation problems
  CRM/Financial/BAO/Payment.php
  sql/civicrm_generated.mysql
  xml/templates/message_templates/payment_or_refund_notification_html.tpl
  xml/templates/message_templates/payment_or_refund_notification_text.tpl
Labels: master

#25137 Stop using single hard-coded value array (clean up from previous refactors)
  CRM/Contact/Import/Parser/Contact.php
Labels: master, merge on pass

#25140 Fix enotice on user dash - when user has membership/s & debugging enabled
  templates/CRM/Member/Page/UserDashboard.tpl
Labels: master, merge on pass

#25108 Remove noisly deprecated function PDFLetterCommon::postProcess
  CRM/Contact/Form/Task/PDFLetterCommon.php
Labels: master

#25141 Enotice fixes, consolidation on Import datasource forms
  CRM/Contact/Import/Form/DataSource.php
  CRM/Import/Form/DataSource.php
  templates/CRM/Contact/Import/Form/DataSource.tpl
  templates/CRM/Import/Form/DataSource.tpl
Labels: master

#25142 Php layer consolidation on Import DataSource form
  CRM/Contact/Import/Form/DataSource.php
  CRM/Core/BAO/UserJob.php
  CRM/Import/Form/DataSource.php
  CRM/Import/Forms.php
Labels: master

#25150 [NFC] Update testGetSiteStats to match earlier name change
  tests/phpunit/CRM/Utils/versionCheckTest.php
Labels: 5.57

#25151 5.57
  tests/phpunit/CRM/Utils/versionCheckTest.php
Labels: master

#25152 Remove no-longer-used noisily deprecated function `CRM_Contact_Form_Task_PDFLetterCommon::createActivities`
  CRM/Contact/Form/Task/PDFLetterCommon.php
Labels: master

#25149 Flexmailer: Prevent broken urls containing hyphens when click tracking is enabled for plain text mailings
  ext/flexmailer/src/ClickTracker/TextClickTracker.php
  ext/flexmailer/tests/phpunit/Civi/FlexMailer/ClickTracker/TextClickTrackerTest.php
Labels: merge on pass, has-test, 5.57

#25157 5.57
  ext/flexmailer/src/ClickTracker/TextClickTracker.php
  ext/flexmailer/tests/phpunit/Civi/FlexMailer/ClickTracker/TextClickTrackerTest.php
Labels: master

#25158 getSiteStats - Use consistent report format
  CRM/Utils/VersionCheck.php
  tests/phpunit/CRM/Utils/versionCheckTest.php
Labels: 5.57

#25165 Fix smarty notices on Open Case
  CRM/Case/Form/Activity/OpenCase.php
  CRM/Case/Form/Case.php
  templates/CRM/Case/Form/Case.tpl
Labels: master, merge on pass

#25145 fixes core#4027 - don't crash when a contribution has no line items
  CRM/Financial/BAO/Order.php
Labels: 5.57

#25160 CRM_Utils_FileTest - Fix compatibility with private data folders
  tests/phpunit/CRM/Utils/FileTest.php
Labels: 5.57

#25168 (NFC) PrevNextTest - Fix warning about "@group"
  tests/phpunit/E2E/Core/PrevNextTest.php
Labels: master, merge on pass

#25166 Ports to stable
  CRM/Financial/BAO/Order.php
  ext/flexmailer/src/ClickTracker/TextClickTracker.php
  ext/flexmailer/tests/phpunit/Civi/FlexMailer/ClickTracker/TextClickTrackerTest.php
  templates/CRM/Financial/Form/Search.tpl
Labels: 5.56

#25143 Add Option Group descriptions from templates/CRM/Admin/Page/Options.tpl
  CRM/Core/DAO/OptionGroup.php
  CRM/Core/I18n/SchemaStructure.php
  CRM/Upgrade/Incremental/php/FiveFiftyEight.php
  xml/schema/Core/OptionGroup.xml
  xml/templates/civicrm_data.tpl
Labels: master

#25123 Add search/display details to searchKitTasks hook - allows for eg. filtering actions by search display
  ext/search_kit/Civi/Api4/Action/SearchDisplay/GetSearchTasks.php
  ext/search_kit/ang/crmSearchTasks/crmSearchTasks.component.js
  ext/search_kit/search_kit.php
Labels: master, merge on pass

#25172 Remove incorrect usages of {localize} in civicrm_data.tpl
  xml/templates/civicrm_data.tpl
Labels: merge on pass

#25144 Add Membership entity to formbuilder
  ext/afform/admin/afformEntities/Membership.php
Labels: master

#25182 Simplify params on now-private function
  CRM/Contribute/Form/Contribution/Main.php
Labels: master, merge on pass

#25161 Add datasource selector to generic import (so it can be used eg. with contribution import)
  CRM/Contact/Import/Form/DataSource.php
  CRM/Contribute/Import/Form/DataSource.php
  CRM/Custom/Import/Form/DataSource.php
  CRM/Event/Import/Form/DataSource.php
  CRM/Import/Form/DataSource.php
  CRM/Member/Import/Form/DataSource.php
  templates/CRM/Import/Form/DataSource.tpl
Labels: master

#25183 Remove conditionals that rely on NULL not being NULL
  CRM/Contribute/Form/Contribution/Main.php
Labels: master

#25177 Fix miscoordination between CiviUnitTestCase/CiviEnvBuilder. Fix flaky ConformanceTest.
  Civi/Test.php
  Civi/Test/CiviEnvBuilder.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/api/v4/Action/AutocompleteTest.php
  tests/phpunit/api/v4/Entity/ConformanceTest.php
Labels: merge on pass, 5.57

#25185 5.57
  Civi/Test.php
  Civi/Test/CiviEnvBuilder.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/api/v4/Action/AutocompleteTest.php
  tests/phpunit/api/v4/Entity/ConformanceTest.php
Labels: master, merge on pass

#25179 totten/civix#257 Fix Civix not correctly loading Mixinx
  mixin/polyfill.php
Labels: master

#25184 Divide & conquer, `initSet` no longer shared as much code is not
  CRM/Contribute/Form/ContributionBase.php
  CRM/Event/Form/Registration.php
  CRM/Price/BAO/PriceSet.php
Labels: master

#25189 Fix 'cannot determine default entity' error on New Batch page
  CRM/Batch/Form/Batch.php
Labels: merge on pass, 5.57

#25190 5.57
  CRM/Batch/Form/Batch.php
Labels: master

#25192 List of languages: Enable Croatian language by default
  xml/templates/languages.tpl
Labels: master, merge on pass

#25191 5.56 backports
  CRM/Batch/Form/Batch.php
  CRM/Price/BAO/PriceField.php
Labels: 5.56

#25154 CRM_Utils_Date - Get month names from IntlDateFormatter. Ignore timezones.
  CRM/Utils/Date.php
  tests/phpunit/CRM/Utils/DateTest.php
  tests/phpunit/Civi/Token/TokenProcessorTest.php
Labels: master

#25194 Post code-divide tidy-up
  CRM/Contribute/Form/ContributionBase.php
Labels: master

#25173 Standardise method of getting entity in imports
  CRM/Import/Form/DataSource.php
Labels: master, merge on pass

#25196 [REF] Fix a couple of errors in PHP8.2
  CRM/Extension/Info.php
  CRM/Utils/Request.php
Labels: master, merge on pass

#25120 Configure Event Fees tab
  CRM/Event/Form/ManageEvent/TabHeader.php
  CRM/Event/Page/ManageEvent.php
Labels: master

#25147 Bump min PHP version to 7.3.0
  CRM/Upgrade/Incremental/General.php
  composer.json
  composer.lock
Labels: master

#25197 SearchKit - Fix option loading & rendering for in-place edit
  ext/search_kit/ang/crmSearchAdmin.module.js
  ext/search_kit/ang/crmSearchTasks/crmSearchInput/crmSearchInputVal.component.js
Labels: 5.57

#25193 E_WARNING on bulk email activity view
  CRM/Activity/Form/ActivityView.php
Labels: master

#25198 SearchKit - Fix console error when loading options
  ext/search_kit/ang/crmSearchAdmin.module.js
Labels: 5.56

#25178 (REF) CiviUnitTestCase - Cleanup and simplify the DB-reset mechanism
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: master

#25200 PHP8: callback function on GOTV must be static
  CRM/Campaign/Page/AJAX.php
Labels: master, merge on pass

#25186 Remove reference to 'dataArray' from text version of contribution_online_receipt
  xml/templates/message_templates/contribution_online_receipt_text.tpl
Labels: master

#25203 [REF] Update Composer Compile Lib with latest version
  composer.lock
Labels: master, merge on pass

#25202 [REF][PHP8.2] Further resolve some deprecation issues around dynamic …
  CRM/Activity/Form/Activity.php
  CRM/Activity/Import/Parser/Activity.php
  CRM/Case/XMLProcessor/Report.php
  CRM/Contact/Form/Task/EmailTrait.php
  CRM/Contact/Page/View.php
  CRM/Core/CodeGen/Schema.php
  CRM/Core/CodeGen/Specification.php
  CRM/Core/Form/Search.php
  CRM/Core/Page.php
  CRM/Core/Selector/Controller.php
  CRM/Extension/Browser.php
  CRM/Extension/Info.php
  Civi/Test/CiviTestListenerPHPUnit7.php
  Civi/WorkflowMessage/FieldSpec.php
  ext/oauth-client/tests/phpunit/Civi/OAuth/AuthCodeFlowTest.php
  ext/oauth-client/tests/phpunit/api/v4/OAuthContactTokenTest.php
  tests/phpunit/CRM/ACL/ListTest.php
  tests/phpunit/CRM/Activity/BAO/ActivityTest.php
  tests/phpunit/CRM/Activity/Form/ActivityTest.php
  tests/phpunit/CRM/Activity/Form/SearchTest.php
  tests/phpunit/Civi/Core/CiviFacadeTest.php
  tests/phpunit/Civi/Core/SettingsBagTest.php
  tests/phpunit/CiviTest/CiviCaseTestCase.php
  tests/phpunit/CiviTest/CiviMailUtils.php
  tests/phpunit/CiviTest/CiviTestSMSProvider.php
Labels: master

#25205 NFC: Fix variable name in activity import
  CRM/Activity/Import/Parser/Activity.php
Labels: master, merge on pass

#23305 correct logic for handling empty-array values for checkboxes;
  api/v3/utils.php
Labels: master, merge on pass

#25204 dev/core#4038 import contribution fixes in update mode
  CRM/Contribute/Import/Parser/Contribution.php
Labels: 5.57

#25208 5.57
  CRM/Contribute/Import/Parser/Contribution.php
  ext/search_kit/ang/crmSearchAdmin.module.js
  ext/search_kit/ang/crmSearchTasks/crmSearchInput/crmSearchInputVal.component.js
Labels: master

#25209 import contribution fixes in update mode
  CRM/Contribute/Import/Parser/Contribution.php
Labels: 5.56

#25210 5.56.1 - Set version. Add notes.
  ext/afform/admin/info.xml
  ext/afform/core/info.xml
  ext/afform/html/info.xml
  ext/afform/mock/info.xml
  ext/authx/info.xml
  ext/civicrm_admin_ui/info.xml
  ext/civigrant/info.xml
  ext/civiimport/info.xml
  ext/ckeditor4/info.xml
  ext/contributioncancelactions/info.xml
  ext/elavon/info.xml
  ext/eventcart/info.xml
  ext/ewaysingle/info.xml
  ext/financialacls/info.xml
  ext/flexmailer/info.xml
  ext/greenwich/info.xml
  ext/legacycustomsearches/info.xml
  ext/message_admin/info.xml
  ext/oauth-client/info.xml
  ext/payflowpro/info.xml
  ext/recaptcha/info.xml
  ext/search_kit/info.xml
  ext/sequentialcreditnotes/info.xml
  release-notes.md
  release-notes/5.56.1.md
  sql/civicrm_generated.mysql
  sql/test_data_second_domain.mysql
  xml/version.xml
Labels: 5.56

#25201 [NFC] php8 - Unit test for empty checkbox array #23305
  tests/phpunit/api/v3/ContactTest.php
Labels: master, has-test

#25212 [REF][PHP8.2] Update Composer Patches to latest version to fix notice…
  composer.lock
Labels: master, merge on pass

#25213 dev/core#4039 - Restore ability to have fractional quantity for text price fields
  CRM/Price/BAO/LineItem.php
Labels: 5.57

#25216 5.57
  CRM/Price/BAO/LineItem.php
Labels: master

#25217 Only allow valid image types to be uploaded to image_URL field on profiles
  CRM/Core/BAO/UFGroup.php
Labels: master

#25223 Remove deprecated ids from OptionValue::add
  CRM/Core/BAO/OptionValue.php
Labels: master

#25225 5.57.0 release notes initial run
  release-notes.md
  release-notes/5.57.0.md
Labels: 5.57

#25228 5.57 to master
  release-notes.md
  release-notes/5.57.0.md
Labels: master

#25227 Support DedupeRules as Managed entities
  Civi/Api4/DedupeRule.php
  Civi/Api4/DedupeRuleGroup.php
Labels: master

#25233 Remove broken method CRM_Utils_File::isHtml()
  CRM/Utils/File.php
Labels: master, merge on pass

#25230 [REF] Fix strstr deprecation in CustomDataByType class
  CRM/Custom/Form/CustomDataByType.php
Labels: master, merge on pass

#25231 [NFC] first pass at 5.57 release notes
  release-notes/5.57.0.md
Labels: 5.57

#25236 [NFC] Fix @method documentation for shouldExitAfterFatal
  CRM/Utils/System.php
Labels: master

#25240 Remove legacy code payment processor handling
  CRM/Contribute/Form/ContributionBase.php
Labels: master

#25234 [NFC] Remove line that does nothing
  CRM/Activity/BAO/Query.php
Labels: master

#25242 (NFC) When using @var annotations, ensure type comes first
  CRM/Case/Info.php
  CRM/Core/BAO/File.php
  CRM/Extension/Mapper.php
  CRM/Extension/MixinLoader.php
  Civi/CCase/Events.php
  Civi/Test/CiviEnvBuilder/SqlFileStep.php
  Civi/Test/CiviEnvBuilder/SqlStep.php
  ext/legacycustomsearches/CRM/Contact/Form/Search/Custom/FullText.php
  tests/phpunit/CRM/Contribute/Form/Task/PDFLetterCommonTest.php
  tests/phpunit/CiviTest/CiviCaseTestCase.php
Labels: master

#25221 [REF] [merge custom fields function] Stop returning unaltered cFields parameter (good unit test cover)
  CRM/Dedupe/Merger.php
Labels: master

#25244 [REF][PHP8.2] Avoid dynamic properties in CRM_Utils_Signer
  CRM/Utils/Signer.php
Labels: master

#25243 [REF][PHP8.2] Avoid dynamic properties in mailstores
  CRM/Mailing/MailStore.php
  CRM/Mailing/MailStore/Imap.php
  CRM/Mailing/MailStore/Localdir.php
  CRM/Mailing/MailStore/Maildir.php
  CRM/Mailing/MailStore/Mbox.php
  CRM/Mailing/MailStore/Pop3.php
Labels: master

#25246 (NFC) Fix documented return type on getByClass method
  Civi/Payment/System.php
Labels: master
