Repository civicrm/civicrm-core, pull requests merged in 2022-04, with the labels that each got.

#23070 SearchKit - Fix broken group-by caused by non-aggregated id column
  ext/search_kit/Civi/Api4/Action/SearchDisplay/AbstractRunAction.php
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdmin.component.js
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/SearchRunTest.php
Labels: has-test, sig:regression, 5.48

#23037 Ensure soft credit types are assigned to the template
  CRM/Contribute/BAO/Contribution.php
Labels: master

#22972 Ensure some variables are assigned to the template
  CRM/Contribute/BAO/Contribution.php
Labels: master

#22971 Ensure pay_later variables assigned to template
  CRM/Contribute/Form/Contribution/Main.php
  CRM/Event/Form/Registration/Register.php
Labels: master

#23067 Add support for financial account custom fields
  CRM/Financial/BAO/FinancialAccount.php
  CRM/Financial/Form/FinancialAccount.php
  templates/CRM/Financial/Form/FinancialAccount.tpl
Labels: master

#23078 Ensure formType is assigned to the template
  CRM/Contribute/Form/Contribution.php
  CRM/Pledge/Form/Pledge.php
Labels: master, merge on pass

#23075 5.48
  ext/search_kit/Civi/Api4/Action/SearchDisplay/AbstractRunAction.php
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdmin.component.js
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/SearchRunTest.php
  tests/phpunit/CRM/Contribute/Form/ContributionTest.php
  xml/templates/message_templates/contribution_offline_receipt_html.tpl
  xml/templates/message_templates/contribution_offline_receipt_text.tpl
Labels: master

#23051 split sql select into two selects for performance reasons
  CRM/Mailing/Event/BAO/Unsubscribe.php
Labels: merge on pass, 5.48

#23069 Avoid trailing spaces in trigger output
  Civi/Core/Container.php
  Civi/Core/SqlTrigger/TimestampTriggers.php
Labels: master

#23042 Finish conversion of static function to non-static
  CRM/Contribute/Form/Contribution/Confirm.php
Labels: master

#23086 dev/core#3153 - Fix missing filter summary on CiviReports
  CRM/Report/Form.php
Labels: 5.48

#23085 5.48
  CRM/Mailing/Event/BAO/Unsubscribe.php
  CRM/Report/Form.php
Labels: master

#23088 [REF] Update Composer compile plugin
  composer.lock
Labels: master

#23049 Add membership_id as a reference to the row
  templates/CRM/Member/Page/UserDashboard.tpl
Labels: master

#22376 SearchKit - Allow creation of new records via in-place edit
  Civi/Api4/Query/Api4SelectQuery.php
  ext/search_kit/Civi/Api4/Action/SearchDisplay/AbstractRunAction.php
  ext/search_kit/ang/crmSearchDisplay/crmSearchDisplayEditable.component.js
Labels: master

#23073 Add civicrm_contact_type.icon column
  CRM/Contact/DAO/ContactType.php
  CRM/Upgrade/Incremental/php/FiveFortyNine.php
  CRM/Upgrade/Incremental/sql/5.49.alpha1.mysql.tpl
  sql/test_data.mysql
  tests/phpunit/CRM/Contact/BAO/ContactType/ContactTypeTest.php
  xml/schema/Contact/ContactType.xml
  xml/templates/civicrm_data.tpl
  xml/templates/civicrm_sample.tpl
Labels: master, merge ready, has-test

#23093 Avoid PHP notices in activity search
  CRM/Activity/Selector/Search.php
  tests/phpunit/CRM/Activity/Form/SearchTest.php
Labels: master

#23095 [REF] Create polyfill function for array_key_first which only exists …
  composer.json
  composer.lock
Labels: master

#23079 Cleanup FinancialAccount BAO to use `writeRecord` and deprecate `add`
  CRM/Core/DAO.php
  CRM/Financial/BAO/FinancialAccount.php
  CRM/Financial/DAO/FinancialAccount.php
  CRM/Upgrade/Incremental/php/FiveFortyNine.php
  xml/schema/Financial/FinancialAccount.xml
Labels: master

#23083 dev/core#3034
  CRM/Contact/Form/Task/PDFTrait.php
Labels: master, merge on pass

#23052 Don't lose search criteria for smart group built with search builder
  CRM/Core/BAO/Mapping.php
Labels: master, merge ready

#23041 Event Location fixes
  CRM/Event/Form/ManageEvent/Location.php
  templates/CRM/Event/Form/ManageEvent/Location.tpl
Labels: master, merge ready

#23094 dev/user-interface#26 Use font-awesome icons for contact types and recent items
  CRM/Admin/Form/ContactType.php
  CRM/Contact/BAO/Contact/Utils.php
  CRM/Contact/BAO/ContactType.php
  CRM/Utils/Check/Component/ContactTypes.php
  CRM/Utils/Check/Message.php
  CRM/Utils/Recent.php
  ang/crmStatusPage/StatusPage.html
  templates/CRM/Admin/Form/ContactType.tpl
  templates/CRM/Admin/Page/ContactType.hlp
  templates/CRM/Block/RecentlyViewed.tpl
  tests/phpunit/CRM/Activity/Form/SearchTest.php
  tests/phpunit/CRM/Financial/Page/AjaxTest.php
  tests/phpunit/CRM/Member/Selector/SearchTest.php
  tests/phpunit/CRM/Pledge/Form/SearchTest.php
Labels: master, merge ready

#23081 First recurring payment (paypal ipn) - remove redundant status set, start_date change
  CRM/Core/Payment/PayPalIPN.php
  tests/phpunit/CRM/Core/Payment/PayPalIPNTest.php
Labels: master

#22986 Afform - repeat block metadata update to fix errors when saving blocks
  ext/afform/admin/Civi/Api4/Action/Afform/LoadAdminData.php
  ext/afform/core/CRM/Afform/Upgrader.php
Labels: 5.48

#23100 5.48
  ext/afform/admin/Civi/Api4/Action/Afform/LoadAdminData.php
  ext/afform/core/CRM/Afform/Upgrader.php
Labels: master

#23018 SearchKit - Ensure filters work with multiple search displays on a form
  ext/afform/mock/ang/testMultipleSearchForm.aff.html
  ext/afform/mock/ang/testMultipleSearchForm.aff.json
  ext/search_kit/Civi/Api4/Action/SearchDisplay/AbstractRunAction.php
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/SearchAfformTest.php
Labels: master, has-test

#23096 Test usability fix
  tests/phpunit/CRM/Utils/TokenConsistencyTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: master

#23077 Prevent escaping on cancelInfo_show_ids
  templates/CRM/Contribute/Form/Contribution.tpl
Labels: master

#23038 Assign totalTaxAmount more consistently
  CRM/Event/Form/Participant.php
Labels: master

#23039 Access invoice_prefix setting directly
  CRM/Financial/BAO/ExportFormat/CSV.php
Labels: master

#22992 Fix smarty notices in billing form
  CRM/Core/Payment/Form.php
Labels: master

#23065 dev/core#3151 - backport 23063 - Don't localize event_tz field when backing up the field during upgrade
  CRM/Upgrade/Incremental/php/TimezoneRevertTrait.php
Labels: 5.47

#23008 Re-fix enotice on templateSelected
  templates/CRM/Mailing/Form/InsertTokens.tpl
Labels: master

#23040 Stop passing settings into getTaxLabel
  CRM/Event/Page/EventInfo.php
  CRM/Price/BAO/PriceField.php
Labels: master

#23105 CiviGrant - Remove non-functional setting for grants tab
  ext/civigrant/managed/OptionGroup_contact_view_options_OptionValue_CiviGrant.mgd.php
  settings/Core.setting.php
Labels: merge on pass, 5.48

#23076 dev/financial#186 Do not display partially paid & partially refunded for selection on edit
  CRM/Contribute/Form/Contribution.php
Labels: master

#23102 Update DOMPDF to 1.2.1 and update composer-compile-plugin as per master
  composer.json
  composer.lock
Labels: 5.48

#23109 5.48
  composer.json
  composer.lock
  ext/civigrant/managed/OptionGroup_contact_view_options_OptionValue_CiviGrant.mgd.php
  settings/Core.setting.php
Labels: master

#23107 5.48
  composer.json
  composer.lock
  ext/civigrant/managed/OptionGroup_contact_view_options_OptionValue_CiviGrant.mgd.php
  settings/Core.setting.php
Labels: master

#23103 Update DOMPDF to 1.2.1 and update composer-compile-plugin as per master
  composer.json
  composer.lock
Labels: 5.47

#23106 Test cleanup, deprecate ContributionSoft::retrieve
  CRM/Contribute/BAO/ContributionSoft.php
  tests/phpunit/CRM/Contribute/Import/Parser/ContributionTest.php
Labels: master, merge on pass

#23108 Remove double return statement
  CRM/Contribute/Import/Parser/Contribution.php
Labels: master, merge on pass

#23112 Test cleanup (minor)
  tests/phpunit/CRM/Contribute/Import/Parser/ContributionTest.php
Labels: master

#23113 Remove unused variable
  CRM/Contribute/Import/Form/DataSource.php
Labels: master

#23110 Remove unnecessary pass-by-ref
  CRM/Contribute/Import/Parser/Contribution.php
Labels: master

#23111 Cleanup unnecessary variables
  CRM/Contribute/Import/Parser/Contribution.php
Labels: master

#23114 Fix enotice, simplify text on Saved field mapping
  CRM/Contact/Import/Form/DataSource.php
  CRM/Custom/Import/Form/DataSource.php
  CRM/Import/Form/DataSource.php
  templates/CRM/Activity/Import/Form/DataSource.tpl
  templates/CRM/Contact/Import/Form/DataSource.tpl
  templates/CRM/Contribute/Import/Form/DataSource.tpl
  templates/CRM/Custom/Import/Form/DataSource.tpl
  templates/CRM/Event/Import/Form/DataSource.tpl
  templates/CRM/Member/Import/Form/DataSource.tpl
Labels: master

#23104 Afform - Fix regression editing a content block with no entity type
  ext/afform/admin/Civi/Api4/Action/Afform/LoadAdminData.php
  ext/afform/admin/ang/afGuiEditor/afGuiEditor.component.js
Labels: merge ready, sig:regression, 5.48

#23115 Fix broken civgrant shortcut link
  CRM/Contact/BAO/Contact.php
  CRM/Core/Block.php
  ext/civigrant/civigrant.php
  templates/CRM/common/TabHeader.js
Labels: merge on pass, merge ready, sig:regression, 5.48

#23118 CiviGrant - Fix missing column and translate headers in contact summary tab
  ext/civigrant/managed/SavedSearch_CiviGrant_Summary.mgd.php
Labels: merge on pass, sig:regression, 5.48

#23099 Add APIv4 for RecentItems
  CRM/Activity/BAO/Activity.php
  CRM/Contact/BAO/Contact.php
  CRM/Contact/Form/Contact.php
  CRM/Contact/Page/View.php
  CRM/Core/DAO.php
  CRM/Utils/Recent.php
  Civi/Api4/Generic/BasicEntity.php
  Civi/Api4/RecentItem.php
  sql/civicrm_generated.mysql
  tests/phpunit/api/v4/Action/RecentItemsTest.php
  tests/phpunit/api/v4/Entity/ConformanceTest.php
  tests/phpunit/api/v4/Entity/RecentItemTest.php
  tests/phpunit/api/v4/Service/TestCreationParameterProvider.php
Labels: master, merge on pass, has-test

#23117 Emit deprecated warning for typo version of hook_civicrm_links
  CRM/Core/Block.php
Labels: master, merge on pass

#23116 CiviGrant - Remove upgrade that adds removed option value
  CRM/Upgrade/Incremental/php/FiveFortySeven.php
Labels: 5.48

#23119 Notices on import - consolidate mapping variables
  CRM/Activity/Import/Form/MapField.php
  CRM/Activity/Import/Form/Preview.php
  CRM/Contact/Import/Form/Preview.php
  CRM/Contribute/Import/Form/Preview.php
  CRM/Custom/Import/Form/Preview.php
  CRM/Event/Import/Form/MapField.php
  CRM/Event/Import/Form/Preview.php
  CRM/Import/Form/MapField.php
  CRM/Member/Import/Form/MapField.php
  CRM/Member/Import/Form/Preview.php
  templates/CRM/Activity/Import/Form/MapTable.tpl
  templates/CRM/Contact/Import/Form/MapTable.tpl
  templates/CRM/Contribute/Import/Form/MapTable.tpl
  templates/CRM/Event/Import/Form/MapTable.tpl
  templates/CRM/Member/Import/Form/MapTable.tpl
Labels: master

#23120 Afform - Ensure upgrade fully converts content blocks
  ext/afform/core/CRM/Afform/Upgrader.php
Labels: merge on pass, 5.48

#23016 Respect zero value
  CRM/Admin/Form/Options.php
Labels: master, merge ready

#23122 Fix function calls to be non-static
  CRM/Contribute/Import/Parser/Contribution.php
Labels: master, merge on pass

#23123 Remove unused private variables
  CRM/Contribute/Import/Parser/Contribution.php
Labels: master, merge on pass

#22977 Ensure pay_later_text is always assigned
  CRM/Contribute/Form/Contribution/Main.php
Labels: master

#23121 Simplify class inheritance
  .toxic.json
  CRM/Contribute/Import/Form/Preview.php
  CRM/Contribute/Import/Form/Summary.php
  CRM/Contribute/Import/Parser.php
  CRM/Contribute/Import/Parser/Contribution.php
  tests/phpunit/CRM/Contribute/Import/Parser/ContributionTest.php
Labels: master, merge on pass

#23124 Tpl cleanup - whitespace, wrong closing tag
  templates/CRM/Contribute/Import/Form/MapTable.tpl
Labels: master, merge on pass

#23125 5.48.0 release notes: added late changes
  release-notes/5.48.0.md
Labels: 5.48

#23127 5.48
  release-notes/5.48.0.md
Labels: master

#23126 Remove good intentions
  CRM/Activity/Import/Parser.php
  CRM/Contact/Import/Parser.php
  CRM/Contribute/Import/Parser/Contribution.php
  CRM/Custom/Import/Parser.php
  CRM/Event/Import/Parser.php
  CRM/Member/Import/Parser.php
Labels: master

#23128 5.47.4 - Add notes. Bump version.
  ext/afform/admin/info.xml
  ext/afform/core/info.xml
  ext/afform/html/info.xml
  ext/afform/mock/info.xml
  ext/authx/info.xml
  ext/civigrant/info.xml
  ext/ckeditor4/info.xml
  ext/contributioncancelactions/info.xml
  ext/eventcart/info.xml
  ext/ewaysingle/info.xml
  ext/financialacls/info.xml
  ext/flexmailer/info.xml
  ext/greenwich/info.xml
  ext/legacycustomsearches/info.xml
  ext/message_admin/info.xml
  ext/oauth-client/info.xml
  ext/payflowpro/info.xml
  ext/recaptcha/info.xml
  ext/search_kit/info.xml
  ext/sequentialcreditnotes/info.xml
  release-notes.md
  release-notes/5.47.4.md
  sql/civicrm_generated.mysql
  sql/test_data_second_domain.mysql
  xml/version.xml
Labels: 5.47

#20437 core#2633 : Cannot remove Group Organisation selection in multisite setup
  CRM/Contact/BAO/Group.php
  CRM/Group/Form/Edit.php
Labels: needs-work-not-review-ready, master

#22941 Copy Clear value in batch update process for radio button field
  templates/CRM/common/batchCopy.tpl
Labels: master

#22850 Fixes issue with duplicate is_billing on inline address forms.
  CRM/Core/BAO/Address.php
  CRM/Core/BAO/Block.php
  tests/phpunit/CRM/Core/BAO/AddressTest.php
Labels: master, merge on pass

#23130 Fix OptionValue BAO to call pre/post hooks to prevent force-reset of managed option values
  CRM/Core/BAO/OptionValue.php
  tests/phpunit/api/v4/Entity/ManagedEntityTest.php
Labels: master, merge on pass

#23131 Fix OptionValue BAO to call pre/post hooks to prevent force-reset of …
  CRM/Core/BAO/OptionValue.php
  tests/phpunit/api/v4/Entity/ManagedEntityTest.php
Labels: merge on pass, 5.48

#23129 Add in APIv4 Logging Entity
  CRM/Core/BAO/Log.php
  Civi/Api4/Log.php
Labels: merge on pass

#23133 Remove 'in-between' class
  CRM/Member/Import/Form/Preview.php
  CRM/Member/Import/Form/Summary.php
  CRM/Member/Import/Parser.php
  CRM/Member/Import/Parser/Membership.php
Labels: master, merge on pass

#23134 (REF) Schema - Fix boolean fields in various tables - Split commits
  CRM/Upgrade/Incremental/php/FiveFortyNine.php
  CRM/Upgrade/Incremental/php/FiveFortyNine/ACL.bool.php
  CRM/Upgrade/Incremental/php/FiveFortyNine/Activity.bool.php
  CRM/Upgrade/Incremental/php/FiveFortyNine/Campaign.bool.php
  CRM/Upgrade/Incremental/php/FiveFortyNine/Case.bool.php
  CRM/Upgrade/Incremental/php/FiveFortyNine/Contact.bool.php
  CRM/Upgrade/Incremental/php/FiveFortyNine/Contribute.bool.php
  CRM/Upgrade/Incremental/php/FiveFortyNine/Core.bool.php
  CRM/Upgrade/Incremental/php/FiveFortyNine/Cxn.bool.php
  CRM/Upgrade/Incremental/php/FiveFortyNine/Dedupe.bool.php
  CRM/Upgrade/Incremental/php/FiveFortyNine/Event.bool.php
  CRM/Upgrade/Incremental/php/FiveFortyNine/Financial.bool.php
  CRM/Upgrade/Incremental/php/FiveFortyNine/Friend.bool.php
  CRM/Upgrade/Incremental/php/FiveFortyNine/Mailing.bool.php
  CRM/Upgrade/Incremental/php/FiveFortyNine/Member.bool.php
  CRM/Upgrade/Incremental/php/FiveFortyNine/PCP.bool.php
  CRM/Upgrade/Incremental/php/FiveFortyNine/Pledge.bool.php
  CRM/Upgrade/Incremental/php/FiveFortyNine/Price.bool.php
  CRM/Upgrade/Incremental/php/FiveFortyNine/Report.bool.php
  CRM/Upgrade/Incremental/php/FiveFortyNine/SMS.bool.php
Labels: master, merge ready

#23137 Remove unused property
  CRM/Import/Form/MapField.php
Labels: master

#23136 Enotice fix - membership search
  templates/CRM/Member/Form/Selector.tpl
Labels: master

#23138 Consolidate MapTable.tpl
  templates/CRM/Activity/Import/Form/MapField.tpl
  templates/CRM/Activity/Import/Form/MapTable.tpl
  templates/CRM/Activity/Import/Form/Preview.tpl
  templates/CRM/Event/Import/Form/MapField.tpl
  templates/CRM/Event/Import/Form/Preview.tpl
  templates/CRM/Import/Form/MapTable.tpl
  templates/CRM/Member/Import/Form/MapField.tpl
  templates/CRM/Member/Import/Form/MapTable.tpl
  templates/CRM/Member/Import/Form/Preview.tpl
Labels: master

#23132 Remove unnecessary pass-by-ref
  CRM/Activity/Import/Parser.php
  CRM/Contribute/Import/Parser/Contribution.php
  CRM/Custom/Import/Parser.php
  CRM/Event/Import/Parser.php
  CRM/Import/Form/DataSource.php
Labels: master

#23145 Fix incorrect use of icon argument for crmButton function
  templates/CRM/Admin/Page/Navigation.tpl
  templates/CRM/Badge/Page/Layout.tpl
  templates/CRM/Batch/Form/Search.tpl
  templates/CRM/Campaign/Form/Search/Campaign.tpl
  templates/CRM/Campaign/Page/SurveyType.tpl
Labels: master

#23146 APIv4 Explorer - Adjust 'Index' field to fit better on narrow screens
  css/api4-explorer.css
Labels: master, merge ready

#22967 [REF] Code cleanup on location entities for the Contact Summary screen
  CRM/Contact/Page/View/Summary.php
Labels: master, merge on pass

#23148 (dev/core#3166) "Metadata" cache - Strictly separate by version
  Civi/Core/Container.php
Labels: 5.49

#23151 Avoid PHP notices on FinancialAccount table
  CRM/Financial/Page/FinancialAccount.php
Labels: master

#23152 Don't overescape weights in default-escape mode
  templates/CRM/Admin/Page/LabelFormats.tpl
  templates/CRM/Admin/Page/ParticipantStatusType.tpl
  templates/CRM/Admin/Page/PdfFormats.tpl
  templates/CRM/Campaign/Page/SurveyType.tpl
  templates/CRM/Contribute/Page/Premium.tpl
  templates/CRM/Member/Page/MembershipStatus.tpl
  templates/CRM/Member/Page/MembershipType.tpl
  templates/CRM/Price/Page/Field.tpl
  templates/CRM/Price/Page/Option.tpl
  templates/CRM/Report/Page/Options.tpl
  templates/CRM/UF/Page/Field.tpl
Labels: master

#23154 5.49
  Civi/Core/Container.php
Labels: master

#23153 Add smarty:nodefaults to default.tpl form.
  templates/CRM/Form/default.tpl
Labels: master

#23150 Ensure deleteURL variable for ContactImage.tpl
  CRM/Contact/Page/View.php
  templates/CRM/Contact/Page/ContactImage.tpl
Labels: master

#23149 Add icons for SavedSearch and SearchDisplay entities
  CRM/Contact/DAO/SavedSearch.php
  ext/search_kit/CRM/Search/DAO/SearchDisplay.php
  ext/search_kit/xml/schema/CRM/Search/SearchDisplay.xml
  xml/schema/Contact/SavedSearch.xml
Labels: master

#23144 API4 Explorer - Remove confusing "Save" button
  CRM/Api4/Page/Api4Explorer.php
  ang/api4Explorer.ang.php
  ang/api4Explorer/Explorer.html
  ang/api4Explorer/Explorer.js
  ang/api4Explorer/SaveSearch.html
Labels: master

#22159 APIv4 - Add `is_active` extra field to Domain entity
  CRM/Core/Config.php
  Civi/Api4/Service/Spec/Provider/DomainGetSpecProvider.php
  tests/phpunit/api/v4/Entity/DomainTest.php
Labels: master, has-test

#23141 (dev/mail#107) CiviMail - Fix validation error (5.49)
  CRM/Mailing/BAO/Mailing.php
Labels: 5.49

#23155 Remove-single-value-loop
  CRM/Contact/Page/View/Summary.php
Labels: master

#23163 getSelfServiceEligibility: fix string translation
  CRM/Event/BAO/Participant.php
Labels: master, merge on pass

#23101 core#1836 - restrict scheduled reminder 'Also Include' to non-events
  templates/CRM/Admin/Form/ScheduleReminders.tpl
Labels: master, merge ready

#23142 (dev/mail#107) CiviMail - Fix validation error (5.48)
  CRM/Mailing/BAO/Mailing.php
Labels: 5.48

#23143 Release - Set version compatibility for core extensions when updating core
  tools/bin/scripts/set-version.php
Labels: master

#23165 Reduce use of reference
  CRM/Core/BAO/CustomGroup.php
Labels: master

#23167 (dev/core#3166) "Metadata" cache - Strictly separate by version (5.48)
  Civi/Core/Container.php
Labels: 5.48

#23166 Set limit to 0 when processing send sms task
  CRM/Contact/Form/Task/SMSCommon.php
Labels: merge on pass, 5.49

#23168 (Re-)Set version to 5.50.alpha1
  ext/afform/admin/info.xml
  ext/afform/core/info.xml
  ext/afform/html/info.xml
  ext/afform/mock/info.xml
  ext/authx/info.xml
  ext/civicrm_admin_ui/info.xml
  ext/civigrant/info.xml
  ext/ckeditor4/info.xml
  ext/contributioncancelactions/info.xml
  ext/eventcart/info.xml
  ext/ewaysingle/info.xml
  ext/financialacls/info.xml
  ext/flexmailer/info.xml
  ext/greenwich/info.xml
  ext/legacycustomsearches/info.xml
  ext/message_admin/info.xml
  ext/oauth-client/info.xml
  ext/payflowpro/info.xml
  ext/recaptcha/info.xml
  ext/search_kit/info.xml
  ext/sequentialcreditnotes/info.xml
Labels: master

#23135 Centralise skipColumnHeader to one function (fixes notices, cleans code)
  CRM/Activity/Import/Form/Preview.php
  CRM/Contact/Import/Form/Preview.php
  CRM/Contribute/Import/Form/Preview.php
  CRM/Custom/Import/Form/Preview.php
  CRM/Event/Import/Form/Preview.php
  CRM/Import/Form/Preview.php
  CRM/Import/Forms.php
  CRM/Member/Import/Form/Preview.php
Labels: master

#23169 (NFC) authx - Update descriptions and links in `info.xml`
  ext/authx/info.xml
Labels: master, merge on pass

#23171 Remove some copy & paste
  CRM/Event/Import/Form/MapField.php
  CRM/Member/Import/Form/MapField.php
Labels: master, merge on pass

#23175 Limit issue when printing pdf from contribution search
  CRM/Contribute/Form/Task/PDF.php
Labels: 5.49

#23176 5.49.0 release notes initial run
  release-notes.md
  release-notes/5.49.0.md
Labels: 5.49

#23178 5.49 to master
  CRM/Contact/Form/Task/SMSCommon.php
  CRM/Contribute/Form/Task/PDF.php
  CRM/Mailing/BAO/Mailing.php
  release-notes.md
  release-notes/5.49.0.md
Labels: master

#23174 Contribution dashboard links work in escape-on-output mode
  templates/CRM/Contribute/Page/DashBoard.tpl
Labels: master

#23140 CiviGrant - Cleanup managed entities - fixes dev/core#3161
  CRM/Upgrade/Incremental/php/FiveFortySeven.php
  CRM/Upgrade/Incremental/sql/5.48.1.mysql.tpl
  ext/afform/admin/info.xml
  ext/afform/core/info.xml
  ext/afform/html/info.xml
  ext/afform/mock/info.xml
  ext/authx/info.xml
  ext/civicrm_admin_ui/info.xml
  ext/civigrant/CRM/Grant/Upgrader.php
  ext/civigrant/info.xml
  ext/civigrant/managed/Navigation_Grants.mgd.php
  ext/civigrant/managed/OptionGroup_advanced_search_options_OptionValue_CiviGrant.mgd.php
  ext/civigrant/managed/OptionGroup_grant_status.mgd.php
  ext/civigrant/managed/OptionGroup_grant_type.mgd.php
  ext/civigrant/managed/OptionGroup_mapping_type_OptionValue_Export.mgd.php
  ext/civigrant/managed/OptionGroup_report_template_OptionValue_CRM_Report_Form_Grants.mgd.php
  ext/civigrant/managed/SavedSearch_CiviGrant_Summary.mgd.php
  ext/ckeditor4/info.xml
  ext/contributioncancelactions/info.xml
  ext/eventcart/info.xml
  ext/ewaysingle/info.xml
  ext/financialacls/info.xml
  ext/flexmailer/info.xml
  ext/greenwich/info.xml
  ext/legacycustomsearches/info.xml
  ext/message_admin/info.xml
  ext/oauth-client/info.xml
  ext/payflowpro/info.xml
  ext/recaptcha/info.xml
  ext/search_kit/info.xml
  ext/sequentialcreditnotes/info.xml
  sql/civicrm_generated.mysql
  sql/test_data_second_domain.mysql
  xml/version.xml
Labels: merge on pass, 5.48

#23082 🪲 🪳 Bug Fix: The option "Enable multiple bulk email address for a contact" does not apply when editing a Contact, only works for inline edit of email addresses
  CRM/Contact/Form/Edit/Email.php
Labels: master

#23179 (dev/core#3161) CiviGrant - Cleanup managed entities (5.49-rc)
  CRM/Upgrade/Incremental/php/FiveFortySeven.php
  CRM/Upgrade/Incremental/sql/5.48.1.mysql.tpl
  ext/civigrant/CRM/Grant/Upgrader.php
  ext/civigrant/managed/Navigation_Grants.mgd.php
  ext/civigrant/managed/OptionGroup_advanced_search_options_OptionValue_CiviGrant.mgd.php
  ext/civigrant/managed/OptionGroup_grant_status.mgd.php
  ext/civigrant/managed/OptionGroup_grant_type.mgd.php
  ext/civigrant/managed/OptionGroup_mapping_type_OptionValue_Export.mgd.php
  ext/civigrant/managed/OptionGroup_report_template_OptionValue_CRM_Report_Form_Grants.mgd.php
  ext/civigrant/managed/SavedSearch_CiviGrant_Summary.mgd.php
Labels: merge on pass, 5.49

#23181 5.49 to master
  CRM/Upgrade/Incremental/php/FiveFortySeven.php
  CRM/Upgrade/Incremental/sql/5.48.1.mysql.tpl
  ext/civigrant/CRM/Grant/Upgrader.php
  ext/civigrant/managed/Navigation_Grants.mgd.php
  ext/civigrant/managed/OptionGroup_advanced_search_options_OptionValue_CiviGrant.mgd.php
  ext/civigrant/managed/OptionGroup_grant_status.mgd.php
  ext/civigrant/managed/OptionGroup_grant_type.mgd.php
  ext/civigrant/managed/OptionGroup_mapping_type_OptionValue_Export.mgd.php
  ext/civigrant/managed/OptionGroup_report_template_OptionValue_CRM_Report_Form_Grants.mgd.php
  ext/civigrant/managed/SavedSearch_CiviGrant_Summary.mgd.php
Labels: master

#23182 5.48.1 - Add release-notes
  release-notes.md
  release-notes/5.48.1.md
Labels: 5.48

#23172 Further simplify variable retrieval
  CRM/Activity/Import/Form/MapField.php
  CRM/Activity/Import/Form/Preview.php
  CRM/Contribute/Import/Form/MapField.php
  CRM/Contribute/Import/Form/Preview.php
  CRM/Custom/Import/Form/MapField.php
  CRM/Custom/Import/Form/Preview.php
  CRM/Event/Import/Form/MapField.php
  CRM/Import/Form/DataSource.php
  CRM/Import/Form/MapField.php
  CRM/Import/Forms.php
  CRM/Member/Import/Form/MapField.php
  CRM/Member/Import/Form/Preview.php
Labels: master

#23180 dev/core#3172 Update phpleague/csv from 9.2 to 9.6 (supports php 8)
  composer.json
  composer.lock
Labels: master

#23188 Cleanup crmMailing/Templates.js
  ang/crmMailing/Templates.js
Labels: master, merge on pass

#23139 send group subscription welcome email only if template is enabled
  CRM/Mailing/Event/BAO/Confirm.php
Labels: master, merge ready

#23191 dev/core#3164 : Report Filter Statistics don't show filters with vaue of "0"
  CRM/Report/Form.php
Labels: master

#23189 [NFC] First Pass at Release notes for 5.49
  contributor-key.yml
  release-notes/5.49.0.md
Labels: merge on pass, 5.49

#23192 Fix FiveFortyNine is_public to default to 0
  CRM/Core/DAO/Menu.php
  CRM/Upgrade/Incremental/php/FiveFortyNine/Core.bool.php
  xml/schema/Core/Menu.xml
Labels: 5.49

#23196 5.49 to master
  CRM/Core/DAO/Menu.php
  CRM/Upgrade/Incremental/php/FiveFortyNine/Core.bool.php
  contributor-key.yml
  release-notes/5.49.0.md
  xml/schema/Core/Menu.xml
Labels: master

#22571 Improve financial trxn spec to require required fields
  CRM/Contribute/BAO/Contribution.php
  CRM/Core/BAO/FinancialTrxn.php
  Civi/Api4/Service/Spec/Provider/FinancialTrxnCreationSpecProvider.php
  tests/phpunit/api/v3/ContributionTest.php
Labels: master

#23158 [REF] Extract getContributionRecurID
  CRM/Core/Payment/AuthorizeNetIPN.php
Labels: master

#23197 [REF] Regenerate civicrm_generated data
  sql/civicrm_generated.mysql
  xml/templates/civicrm_sample.tpl
Labels: merge on pass, 5.49

#23201 5.49
  sql/civicrm_generated.mysql
  xml/templates/civicrm_sample.tpl
Labels: master

#23177 (REF) Schema - Correct boolean fields in various tables
  CRM/ACL/DAO/ACLEntityRole.php
  CRM/Upgrade/Incremental/php/FiveFortyNine/ACL.bool.php
  CRM/Upgrade/Incremental/php/FiveFortyNine/Report.bool.php
  xml/schema/ACL/ACLEntityRole.xml
  xml/schema/Event/ParticipantStatusType.xml
  xml/schema/Financial/PaymentProcessorType.xml
Labels: merge on pass, 5.49

#23203 5.49 to master
  CRM/ACL/DAO/ACLEntityRole.php
  CRM/Upgrade/Incremental/php/FiveFortyNine/ACL.bool.php
  CRM/Upgrade/Incremental/php/FiveFortyNine/Report.bool.php
  xml/schema/ACL/ACLEntityRole.xml
  xml/schema/Event/ParticipantStatusType.xml
  xml/schema/Financial/PaymentProcessorType.xml
Labels: master

#23157 Minor readability improvement
  CRM/Core/Payment/AuthorizeNetIPN.php
Labels: master

#23200 Remove unused function
  CRM/Core/BAO/FinancialTrxn.php
Labels: master

#23194 Remove unused parameter from private function
  CRM/Import/DataSource/CSV.php
Labels: master

#23204 (dev/core#3171) "Manage Extensions" - Tweak messaging for "Install" screen
  CRM/Admin/Form/Extensions.php
  templates/CRM/Admin/Form/Extensions.tpl
Labels: master, merge on pass

#23198 Move 5.49 update to beta
  CRM/Upgrade/Incremental/php/FiveFortyNine.php
Labels: merge ready, 5.49

#23205 Don't overescape tab links
  templates/CRM/Contact/Page/View/Summary.tpl
  templates/CRM/common/TabHeader.tpl
Labels: master, merge on pass

#23160 (REF) Fix test to use full flow
  CRM/Event/Form/Registration/Confirm.php
  tests/phpunit/CRM/Event/Form/Registration/ConfirmTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: master

#23206 Don't overescape links in pledge tab
  templates/CRM/Pledge/Page/Tab.tpl
Labels: master, merge on pass

#23212 Remove code only needed by Drupal6
  CRM/Core/Permission/Drupal6.php
  CRM/Utils/Hook/Drupal6.php
  CRM/Utils/Hook/WordPress.php
  CRM/Utils/System/Drupal6.php
  civicrm-version.php
  distmaker/dists/repo-report.sh
  install/civicrm.php
  install/index.php
  templates/CRM/common/civicrm.settings.php.template
  tests/phpunit/CRM/Core/Permission/GenericTest.php
Labels: master, merge on pass

#23209 5.49
  CRM/Upgrade/Incremental/php/FiveFortyNine.php
Labels: master

#23186 Standardize DataSource file for Contribution & Membership
  CRM/Import/Form/DataSource.php
  templates/CRM/Activity/Import/Form/DataSource.tpl
  templates/CRM/Contact/Import/Form/DataSource.tpl
  templates/CRM/Contribute/Import/Form/DataSource.tpl
  templates/CRM/Custom/Import/Form/DataSource.tpl
  templates/CRM/Event/Import/Form/DataSource.tpl
  templates/CRM/Member/Import/Form/DataSource.tpl
Labels: master

#23225 Add nodefaults to group edit form
  templates/CRM/Group/Form/Edit.tpl
Labels: master

#23208 Add nodefaults to access.tpl
  templates/CRM/Admin/Page/Access.tpl
Labels: master

#23207 Apply nodefaults to row actions
  templates/CRM/ACL/Page/EntityRole.tpl
  templates/CRM/Activity/Form/Selector.tpl
  templates/CRM/Activity/Selector/Activity.tpl
  templates/CRM/Admin/Page/ContactType.tpl
  templates/CRM/Admin/Page/EventTemplate.tpl
  templates/CRM/Admin/Page/Extensions/AddNew.tpl
  templates/CRM/Admin/Page/Extensions/Main.tpl
  templates/CRM/Admin/Page/Job.tpl
  templates/CRM/Admin/Page/LabelFormats.tpl
  templates/CRM/Admin/Page/LocationType.tpl
  templates/CRM/Admin/Page/MailSettings.tpl
  templates/CRM/Admin/Page/Mapping.tpl
  templates/CRM/Admin/Page/MessageTemplates.tpl
  templates/CRM/Admin/Page/Options.tpl
  templates/CRM/Admin/Page/ParticipantStatusType.tpl
  templates/CRM/Admin/Page/PaymentProcessor.tpl
  templates/CRM/Admin/Page/PdfFormats.tpl
  templates/CRM/Admin/Page/PreferencesDate.tpl
  templates/CRM/Admin/Page/RelationshipType.tpl
  templates/CRM/Admin/Page/Reminders.tpl
  templates/CRM/Badge/Page/Layout.tpl
  templates/CRM/Campaign/Page/SurveyType.tpl
  templates/CRM/Contact/Page/DedupeRules.tpl
  templates/CRM/Contribute/Page/ContributionType.tpl
  templates/CRM/Contribute/Page/ManagePremiums.tpl
  templates/CRM/Financial/Page/FinancialAccount.tpl
  templates/CRM/Financial/Page/FinancialType.tpl
  templates/CRM/Financial/Page/FinancialTypeAccount.tpl
  templates/CRM/Group/Page/GroupRows.tpl
  templates/CRM/Mailing/Page/Browse.tpl
  templates/CRM/Mailing/Page/Component.tpl
  templates/CRM/Member/Page/MembershipStatus.tpl
  templates/CRM/Member/Page/MembershipType.tpl
  templates/CRM/PCP/Page/PCP.tpl
  templates/CRM/Price/Page/Field.tpl
  templates/CRM/Price/Page/Option.tpl
  templates/CRM/Price/Page/Set.tpl
  templates/CRM/SMS/Page/Provider.tpl
  templates/CRM/UF/Page/Field.tpl
  templates/CRM/UF/Page/Group.tpl
Labels: master

#22664 Set default values on MembershipView to stop PHP notices
  CRM/Member/Form/MembershipView.php
Labels: master

#23199 dev/core#1307 Add civicrm_user_job table
  CRM/Core/BAO/Job.php
  CRM/Core/BAO/UserJob.php
  CRM/Core/DAO/AllCoreTables.data.php
  CRM/Core/DAO/UserJob.php
  CRM/Upgrade/Incremental/sql/5.50.alpha1.mysql.tpl
  Civi/Api4/UserJob.php
  tests/phpunit/CRM/Dedupe/MergerTest.php
  xml/schema/Core/UserJob.xml
  xml/schema/Core/files.xml
Labels: master

#23080 Always assign pay_later_receipt
  CRM/Event/Form/Registration/Confirm.php
Labels: master

#23184 (NFC) Skip CliRunnerTest on php80+drush+Backdrop
  tests/phpunit/E2E/Extern/CliRunnerTest.php
Labels: master

#23220 (REF) CryptoRegistry - Fix type declaration
  Civi/Core/Container.php
  Civi/Crypto/CryptoRegistry.php
Labels: master

#23226 restore using non-organizations as employers
  CRM/Contact/BAO/RelationshipType.php
Labels: merge on pass, 5.49

#23229 Limit issue fix
  CRM/Member/Form/Task/Label.php
Labels: master

#23231 5.49
  CRM/Contact/BAO/RelationshipType.php
Labels: master

#23232 Apply nodefaults to contact tabs for escape-on-output
  templates/CRM/Case/Page/Tab.tpl
  templates/CRM/Contribute/Page/Tab.tpl
  templates/CRM/Event/Page/Tab.tpl
Labels: master

#23223 [REF] [Import] [Contact] Remove in-between class
  .toxic.json
  CRM/Contact/Import/Form/DataSource.php
  CRM/Contact/Import/Form/MapField.php
  CRM/Contact/Import/Form/Preview.php
  CRM/Contact/Import/Form/Summary.php
  CRM/Contact/Import/ImportJob.php
  CRM/Contact/Import/Parser.php
  CRM/Contact/Import/Parser/Contact.php
  CRM/Custom/Import/Parser.php
  CRM/Custom/Import/Parser/Api.php
Labels: master
