Repository civicrm/civicrm-core, pull requests merged in 2022-11, with the labels that each got.

#24870 5.55
  CRM/Contact/Import/Parser/Contact.php
  CRM/Contribute/Import/Form/MapField.php
  contributor-key.yml
  release-notes/5.55.0.md
  tests/phpunit/CRM/Contact/Import/Form/data/individual_with_custom_checkbox_field.csv
  tests/phpunit/CRM/Contact/Import/Parser/ContactTest.php
  tests/phpunit/CRM/Contribute/Import/Parser/ContributionTest.php
  tests/phpunit/CRM/Contribute/Import/Parser/data/checkboxes.csv
Labels: master

#24869 5.55
  CRM/Contact/Import/Parser/Contact.php
  CRM/Contribute/Import/Form/MapField.php
  contributor-key.yml
  release-notes/5.55.0.md
  tests/phpunit/CRM/Contact/Import/Form/data/individual_with_custom_checkbox_field.csv
  tests/phpunit/CRM/Contact/Import/Parser/ContactTest.php
  tests/phpunit/CRM/Contribute/Import/Parser/ContributionTest.php
  tests/phpunit/CRM/Contribute/Import/Parser/data/checkboxes.csv
Labels: master

#24867 dev/financial#209 Stop disabled financial types showing on price fields
  CRM/Financial/BAO/FinancialType.php
Labels: master

#24863 Fix event template cache not updating. Replace some deprecated functions with API4
  CRM/Event/Form/ManageEvent.php
  CRM/Event/Form/ManageEvent/EventInfo.php
  CRM/Event/PseudoConstant.php
  CRM/Member/BAO/Membership.php
  Civi/ActionSchedule/Mapping.php
Labels: master

#24857 [REF][PHP8.2] Add patches to pear upstream packages to fix issues with PHP8.2
  composer.json
  composer.lock
Labels: master

#24878 Add as contributor
  contributor-key.yml
Labels: master, merge on pass

#24871 Import regression, fix loading of saved mapping with soft-credit email mapped
  CRM/Contribute/Import/Form/MapField.php
  CRM/Import/Forms.php
Labels: 5.55

#24874 SpecScanner - Fix installation error ("Class XyzSpecProvider does not exist")
  Civi/Api4/Service/LegacySpecScanner.php
  ext/search_kit/search_kit.php
Labels: 5.55

#24810 SearchKit - Expose SearchSegment fields as filters
  ext/search_kit/Civi/Api4/Service/Spec/Provider/SearchSegmentExtraFieldProvider.php
  ext/search_kit/tests/phpunit/api/v4/SearchSegment/SearchSegmentTest.php
Labels: master, has-test

#24860 Afform - Add support for ReCaptcha v2
  ext/recaptcha/CRM/Utils/ReCAPTCHA.php
  ext/recaptcha/Civi/AfformReCaptcha2.php
  ext/recaptcha/ang/afGuiRecaptcha2.ang.php
  ext/recaptcha/ang/afGuiRecaptcha2.module.js
  ext/recaptcha/ang/afGuiRecaptcha2/afGuiRecaptcha2-menu.html
  ext/recaptcha/ang/afGuiRecaptcha2/afGuiRecaptcha2.html
  ext/recaptcha/ang/crmRecaptcha2.ang.php
  ext/recaptcha/ang/crmRecaptcha2.module.js
  ext/recaptcha/ang/crmRecaptcha2/crmRecaptcha2.component.js
  ext/recaptcha/ang/crmRecaptcha2/crmRecaptcha2.html
  ext/recaptcha/ang/css/afGuiRecaptcha2.css
  ext/recaptcha/ang/css/rc2-dark.png
  ext/recaptcha/ang/css/rc2-light.png
  ext/recaptcha/info.xml
Labels: master, merge ready

#24877 Test - Fix backwards params to assertEquals
  tests/phpunit/Civi/Angular/PartialSyntaxTest.php
Labels: master, merge on pass

#24880 5.55
  CRM/Contribute/Import/Form/MapField.php
  CRM/Import/Forms.php
  Civi/Api4/Service/LegacySpecScanner.php
  ext/search_kit/search_kit.php
Labels: master

#24807 dev/core#3941 Fix import spec class loader issue
  ext/civiimport/Civi/Api4/Import/ImportSpecProvider.php
Labels: 5.55

#24879 [REF][PHP8.2] Fix some instances of properties not being declared on …
  CRM/Case/XMLProcessor/Process.php
  CRM/Core/Component/Info.php
  CRM/Core/Lock.php
  Civi/Core/DAO/Event/PostDelete.php
  Civi/Core/DAO/Event/PostUpdate.php
  Civi/Core/DAO/Event/PreDelete.php
  Civi/Core/DAO/Event/PreUpdate.php
Labels: master, merge on pass

#24875 Add DATEDIFF to calculate days between two dates
  Civi/Api4/Query/SqlFunctionDATEDIFF.php
  tests/phpunit/api/v4/Action/SqlFunctionTest.php
Labels: master, merge on pass, has-test, comp:search-kit

#24876 Add help text for event scheduled reminders relative and absolute dates
  templates/CRM/Admin/Form/ScheduleReminders.tpl
  templates/CRM/Admin/Page/ScheduleReminders.hlp
Labels: master

#24839 dev/core#3939 Fix import mandatory field validation regression
  CRM/Contribute/Import/Form/MapField.php
  tests/phpunit/CRM/Contribute/Import/Parser/ContributionTest.php
  tests/phpunit/CRM/Contribute/Import/Parser/data/checkboxes.csv
Labels: has-test, 5.54

#24882 Fix missing links in SearchKit results
  ext/search_kit/Civi/Api4/Action/SearchDisplay/GetDefault.php
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/SearchDisplayTest.php
Labels: has-test, sig:regression, 5.55

#24858 dev/core#3879 Fix failure to accept soft credit contact id
  CRM/Contribute/Import/Parser/Contribution.php
  tests/phpunit/CRM/Contribute/Import/Parser/ContributionTest.php
  tests/phpunit/CRM/Contribute/Import/Parser/data/contributions_amount_validate.csv
Labels: has-test, 5.55

#24872 dev/core#3952 Add in Upgrade script to fix up print labels where " wa…
  CRM/Upgrade/Incremental/php/FiveFiftyFive.php
  ext/afform/admin/info.xml
  ext/afform/core/info.xml
  ext/afform/html/info.xml
  ext/afform/mock/info.xml
  ext/authx/info.xml
  ext/civicrm_admin_ui/info.xml
  ext/civigrant/info.xml
  ext/civiimport/info.xml
  ext/ckeditor4/info.xml
  ext/contributioncancelactions/info.xml
  ext/elavon/info.xml
  ext/eventcart/info.xml
  ext/ewaysingle/info.xml
  ext/financialacls/info.xml
  ext/flexmailer/info.xml
  ext/greenwich/info.xml
  ext/legacycustomsearches/info.xml
  ext/message_admin/info.xml
  ext/oauth-client/info.xml
  ext/payflowpro/info.xml
  ext/recaptcha/info.xml
  ext/search_kit/info.xml
  ext/sequentialcreditnotes/info.xml
  sql/civicrm_generated.mysql
  sql/test_data_second_domain.mysql
  tests/phpunit/CRM/Upgrade/Incremental/php/FiveFiftyFiveTest.php
  xml/version.xml
Labels: has-test, 5.55

#24885 5.55
  CRM/Contribute/Import/Parser/Contribution.php
  CRM/Upgrade/Incremental/php/FiveFiftyFive.php
  ext/civiimport/Civi/Api4/Import/ImportSpecProvider.php
  ext/search_kit/Civi/Api4/Action/SearchDisplay/GetDefault.php
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/SearchDisplayTest.php
  tests/phpunit/CRM/Contribute/Import/Parser/ContributionTest.php
  tests/phpunit/CRM/Contribute/Import/Parser/data/contributions_amount_validate.csv
  tests/phpunit/CRM/Upgrade/Incremental/php/FiveFiftyFiveTest.php
Labels: master

#24886 5.55.0 release notes: added late changes
  release-notes/5.55.0.md
Labels: 5.55

#24887 5.55
  release-notes.md
  release-notes/5.54.1.md
  release-notes/5.55.0.md
Labels: master

#24889 SpecScanner - Fix installation error ('Class XyzSpecProvider does not…
  CRM/Api4/Services.php
  ext/search_kit/search_kit.php
Labels: merge on pass, 5.54

#24890 5.54
  CRM/Contact/Import/Parser/Contact.php
  CRM/Contribute/Import/Form/MapField.php
  CRM/Contribute/Import/Parser/Contribution.php
  CRM/Import/Forms.php
  tests/phpunit/CRM/Contact/Import/Form/data/individual_with_custom_checkbox_field.csv
  tests/phpunit/CRM/Contact/Import/Parser/ContactTest.php
  tests/phpunit/CRM/Contribute/Import/Parser/ContributionTest.php
  tests/phpunit/CRM/Contribute/Import/Parser/data/contributions_amount_validate.csv
Labels: 5.54

#24891 5.54.2 - Add notes. Bump version.
  ext/afform/admin/info.xml
  ext/afform/core/info.xml
  ext/afform/html/info.xml
  ext/afform/mock/info.xml
  ext/authx/info.xml
  ext/civicrm_admin_ui/info.xml
  ext/civigrant/info.xml
  ext/civiimport/info.xml
  ext/ckeditor4/info.xml
  ext/contributioncancelactions/info.xml
  ext/elavon/info.xml
  ext/eventcart/info.xml
  ext/ewaysingle/info.xml
  ext/financialacls/info.xml
  ext/flexmailer/info.xml
  ext/greenwich/info.xml
  ext/legacycustomsearches/info.xml
  ext/message_admin/info.xml
  ext/oauth-client/info.xml
  ext/payflowpro/info.xml
  ext/recaptcha/info.xml
  ext/search_kit/info.xml
  ext/sequentialcreditnotes/info.xml
  release-notes.md
  release-notes/5.54.2.md
  sql/civicrm_generated.mysql
  sql/test_data_second_domain.mysql
  xml/version.xml
Labels: 5.54

#24893 (dev/core#3136) Incorporate the domain id in the log file nomenclatur…
  CRM/Core/Error.php
  tests/phpunit/CRM/Core/ErrorTest.php
Labels: master

#24727 dev/core#3735 Fix for getlist retrieve with id
  api/v3/Generic/Getlist.php
  tests/phpunit/api/v3/ContactTest.php
Labels: master, has-test

#24899 SearchKit - Add clone button for search displays
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdmin.component.js
  ext/search_kit/ang/crmSearchAdmin/tabs.html
  ext/search_kit/css/crmSearchAdmin.css
Labels: master

#24901 [REF] Unused vars in the State Machine
  CRM/Core/StateMachine.php
Labels: master

#24905 Only show File Activity on Case success alert for 10s
  templates/CRM/Case/Form/ActivityToCase.tpl
Labels: master

#24904 avoid fatal error in PHP 8 in BAO/Navigation.php
  CRM/Core/BAO/Navigation.php
Labels: merge on pass, sig:regression, 5.56

#24908 5.56
  CRM/Core/BAO/Navigation.php
Labels: master

#24906 Don't crash ContributionView when participant fields are null
  CRM/Contribute/Form/ContributionView.php
Labels: master

#24909 composer.json - Update cacerts fallback
  composer.json
  composer.lock
Labels: merge on pass, 5.56

#24910 5.56
  composer.json
  composer.lock
Labels: master

#24913 [REF] Fix E2E_Core_ErrorTest on wordpress-clean builds
  tests/phpunit/E2E/Core/ErrorTest.php
Labels: master, merge on pass

#24914 added contributor Sebastian Lisken
  contributor-key.yml
Labels: master

#24912 avoid fatal error in PHP 8 in BAO/Navigation.php
  CRM/Core/BAO/Navigation.php
Labels: 5.55

#24895 dev/core#3960 Remove legacy ar key
  templates/CRM/Financial/Page/BatchTransaction.tpl
Labels: merge ready, 5.56

#24915 PHP8 fix - always define locations in event info template
  CRM/Event/Page/EventInfo.php
Labels: master, merge on pass

#24894 (dev/core#3918) Revert "Add missing country=>billingCountry to PropertyBag mapping"
  Civi/Payment/PropertyBag.php
Labels: 5.55

#24897 (dev/core#3918) Revert "Add missing country=>billingCountry to PropertyBag mapping"
  Civi/Payment/PropertyBag.php
Labels: 5.56

#24924 5.55.1 - Add notes. Bump version.
  ext/afform/admin/info.xml
  ext/afform/core/info.xml
  ext/afform/html/info.xml
  ext/afform/mock/info.xml
  ext/authx/info.xml
  ext/civicrm_admin_ui/info.xml
  ext/civigrant/info.xml
  ext/civiimport/info.xml
  ext/ckeditor4/info.xml
  ext/contributioncancelactions/info.xml
  ext/elavon/info.xml
  ext/eventcart/info.xml
  ext/ewaysingle/info.xml
  ext/financialacls/info.xml
  ext/flexmailer/info.xml
  ext/greenwich/info.xml
  ext/legacycustomsearches/info.xml
  ext/message_admin/info.xml
  ext/oauth-client/info.xml
  ext/payflowpro/info.xml
  ext/recaptcha/info.xml
  ext/search_kit/info.xml
  ext/sequentialcreditnotes/info.xml
  release-notes.md
  release-notes/5.55.1.md
  sql/civicrm_generated.mysql
  sql/test_data_second_domain.mysql
  xml/version.xml
Labels: 5.55

#24920 [NFC] Test class cleanup (JobTest)
  tests/phpunit/api/v3/JobTest.php
Labels: master

#24921 [NFC] Minor cleanup in test
  tests/phpunit/CRM/Utils/TokenTest.php
Labels: master

#24922 [NFC] Clean up in test class
  tests/phpunit/Civi/Token/TokenProcessorTest.php
Labels: master

#24930 [dev/backdrop#76] The control buttons in crm pop ups are all X's
  css/backdrop.css
Labels: merge on pass, 5.56

#24931 TabHeader: remove redundant history.replaceState
  templates/CRM/common/TabHeader.js
Labels: master, merge ready

#24939 Add new Organization Example contact (The Daily Bugle)
  Civi/Test/EntityExample.php
  Civi/Test/ExampleData/Contact/TheDailyBugle.php
Labels: master, merge on pass

#24938 Fix api handling of OptionValue defaults
  CRM/Admin/Form/Options.php
  CRM/Core/BAO/OptionValue.php
  tests/phpunit/CRM/Core/BAO/OptionValueTest.php
Labels: master

#24932 Remove unused private function `removeNullContactTokens`
  CRM/Utils/Token.php
Labels: master

#24898 Don't allow selection of deleted contacts as email recipients
  CRM/Contact/Page/AJAX.php
Labels: master

#24945 dev/core#3981 Fix Examples to use 0 rather than a possibly-real contact_id
  Civi/Test/ExampleData/Contact/Alex.php
  Civi/Test/ExampleData/Contact/Barb.php
  Civi/Test/ExampleData/Contact/TheDailyBugle.php
  tests/phpunit/api/v4/Entity/ExampleDataTest.php
Labels: master

#24941 SearchKit - Add unit test for multivalued custom fields
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/SearchRunWithCustomFieldTest.php
Labels: master, has-test

#24936 [dev/backdrop#76] The control buttons in crm pop ups are all X's
  css/backdrop.css
Labels: 5.55

#24933 Add noisy deprecation to unused functions `replaceContactTokens`, `replaceCaseTokens`
  CRM/Utils/Token.php
  tests/phpunit/CRM/Activity/BAO/ActivityTest.php
  tests/phpunit/CRM/Utils/TokenConsistencyTest.php
Labels: master

#24948 Simplify removing file extension when using basename function
  CRM/Upgrade/Incremental/Base.php
  mixin/ang-php@1/mixin.php
  mixin/case-xml@1/mixin.php
  mixin/theme-php@1/mixin.php
  tests/extensions/shimmy/tests/phpunit/E2E/Shimmy/LifecycleTest.php
Labels: master

#24944 Core extensions - Upgrade to civix 22.10.0
  ext/afform/admin/afform_admin.civix.php
  ext/afform/admin/info.xml
  ext/afform/core/afform.civix.php
  ext/afform/core/info.xml
  ext/afform/html/afform_html.civix.php
  ext/afform/html/info.xml
  ext/afform/mock/afform_mock.civix.php
  ext/afform/mock/info.xml
  ext/authx/authx.civix.php
  ext/authx/info.xml
  ext/civicrm_admin_ui/civicrm_admin_ui.civix.php
  ext/civicrm_admin_ui/info.xml
  ext/civigrant/civigrant.civix.php
  ext/civigrant/civigrant.php
  ext/civigrant/info.xml
  ext/civiimport/civiimport.civix.php
  ext/civiimport/info.xml
  ext/ckeditor4/ckeditor4.civix.php
  ext/ckeditor4/info.xml
  ext/contributioncancelactions/contributioncancelactions.civix.php
  ext/contributioncancelactions/info.xml
  ext/elavon/elavon.civix.php
  ext/elavon/info.xml
  ext/eventcart/eventcart.civix.php
  ext/eventcart/info.xml
  ext/ewaysingle/ewaysingle.civix.php
  ext/ewaysingle/info.xml
  ext/financialacls/financialacls.civix.php
  ext/financialacls/info.xml
  ext/flexmailer/flexmailer.civix.php
  ext/flexmailer/info.xml
  ext/greenwich/greenwich.civix.php
  ext/greenwich/info.xml
  ext/legacycustomsearches/info.xml
  ext/legacycustomsearches/legacycustomsearches.civix.php
  ext/message_admin/info.xml
  ext/message_admin/message_admin.civix.php
  ext/oauth-client/info.xml
  ext/oauth-client/oauth_client.civix.php
  ext/payflowpro/info.xml
  ext/payflowpro/payflowpro.civix.php
  ext/recaptcha/info.xml
  ext/recaptcha/recaptcha.civix.php
  ext/search_kit/info.xml
  ext/search_kit/search_kit.civix.php
  ext/sequentialcreditnotes/info.xml
  ext/sequentialcreditnotes/sequentialcreditnotes.civix.php
Labels: master

#24942 SearchKit - Expose SavedSearch descriptions to admins
  CRM/Contact/DAO/SavedSearch.php
  ext/search_kit/ang/crmSearchAdmin/searchListing/crmSearchAdminSearchListing.component.js
  ext/search_kit/ang/crmSearchAdmin/tabs.html
  xml/schema/Contact/SavedSearch.xml
Labels: master

#24952 Remove php8-specific coding pattern
  Civi/Payment/PropertyBag.php
Labels: master

#24951 Backport 24940 (socketio-parser)
  package-lock.json
Labels: 5.56

#24954 5.56 to master
  css/backdrop.css
  package-lock.json
Labels: master

#24821 Add Validate and Import search kit actions to import search displays
  ext/civiimport/Civi/Api4/Event/Subscriber/ImportSubscriber.php
  ext/civiimport/Civi/BAO/Import.php
  ext/civiimport/civiimport.php
Labels: master

#24957 Turn 'From' dropdown in 'Send Email' into a searchable select2
  CRM/Contact/Form/Task/EmailTrait.php
Labels: master, merge on pass

#24649 Make it clear that same email for event registrations allows multiple registrations per contact
  CRM/Event/Form/ManageEvent/Registration.php
  templates/CRM/Event/Form/ManageEvent/Registration.hlp
Labels: master

#24132 dev/core#2316 - Symfony EventDispatcher dispatch() signature kerfuffle - try 3
  Civi.php
  Civi/API/Event/Event.php
  Civi/API/Kernel.php
  Civi/ActionSchedule/Event/MailingQueryEvent.php
  Civi/ActionSchedule/Event/MappingRegisterEvent.php
  Civi/Api4/Event/PostSelectQueryEvent.php
  Civi/Api4/Event/SchemaMapBuildEvent.php
  Civi/Api4/Service/Schema/SchemaMapBuilder.php
  Civi/Core/CiviEventDispatcher.php
  Civi/Core/CiviEventDispatcherInterface.php
  Civi/Core/Container.php
  Civi/Core/DAO/Event/PostDelete.php
  Civi/Core/DAO/Event/PostUpdate.php
  Civi/Core/DAO/Event/PreDelete.php
  Civi/Core/DAO/Event/PreUpdate.php
  Civi/Core/Event/GenericHookEvent.php
  Civi/Core/Event/QueryEvent.php
  Civi/Core/Event/SmartyErrorEvent.php
  Civi/Core/Event/SystemInstallEvent.php
  Civi/Core/UnoptimizedEventDispatcher.php
  Civi/Token/Event/TokenEvent.php
  ext/afform/core/Civi/Afform/Event/AfformBaseEvent.php
  ext/flexmailer/src/Event/BaseEvent.php
  ext/flexmailer/src/Event/CheckSendableEvent.php
  ext/flexmailer/tests/phpunit/Civi/FlexMailer/FlexMailerSystemTest.php
  setup/src/Setup/Event/BaseSetupEvent.php
  setup/src/Setup/UI/Event/BaseUIEvent.php
  tests/phpunit/Civi/API/Event/PrepareEventTest.php
  tests/phpunit/Civi/API/KernelTest.php
  tests/phpunit/Civi/API/Subscriber/DynamicFKAuthorizationTest.php
  tests/phpunit/Civi/API/Subscriber/WhitelistSubscriberTest.php
  tests/phpunit/Civi/Token/TokenProcessorTest.php
  tests/phpunit/E2E/Core/AssetBuilderTest.php
Labels: master, merge on pass

#24961 Update psr0 paths to match current convention
  ext/afform/core/info.xml
  ext/legacycustomsearches/info.xml
  ext/oauth-client/info.xml
  ext/search_kit/info.xml
  tests/extensions/test.extension.manager.moduleupgtest/info.xml
Labels: 5.56

#24958 [NFC] Add @since annotation
  CRM/Extension/Upgrader/Base.php
Labels: master

#24962 [REF] Afform - Use autoservice for event subscribers
  ext/afform/core/Civi/Afform/Behavior/ContactDedupe.php
  ext/afform/core/Civi/Api4/Subscriber/AfformAutocompleteSubscriber.php
  ext/afform/core/afform.php
Labels: merge on pass, 5.56

#24960 FourSeven Upgrade: disable i18nrewrite to avoid multilingual fatal
  CRM/Upgrade/Incremental/php/FourSeven.php
Labels: master

#24935 Further cleanup on JobTest
  tests/phpunit/api/v3/JobTest.php
Labels: master

#24934 Remove deprecated token function `replaceComponentTokens`
  CRM/Utils/Token.php
Labels: master

#24964 Backport use AutoService for Afform AutocompleteSubscriber
  ext/afform/core/Civi/Api4/Subscriber/AutocompleteSubscriber.php
  ext/afform/core/afform.php
  ext/afform/core/info.xml
Labels: sig:regression, 5.55

#24950 Fix WP Clean Pages check when components are disabled
  CRM/Utils/System/WordPress.php
Labels: 5.56

#24965 [PHP 8.1 compat] Afform - Fix display of search filter fields
  ext/afform/core/Civi/Afform/AfformMetadataInjector.php
  ext/search_kit/Civi/Search/AfformSearchMetadataInjector.php
Labels: 5.56

#24973 5.56 to master
  CRM/Utils/System/WordPress.php
  ext/afform/core/Civi/Afform/AfformMetadataInjector.php
  ext/search_kit/Civi/Search/AfformSearchMetadataInjector.php
Labels: master

#24966 Afform - Fix multivalue entityRef fields
  ang/crmUi.js
  ext/afform/admin/ang/afGuiEditor/inputType/EntityRef.html
  ext/afform/core/ang/af/fields/EntityRef.html
Labels: master

#24972 Fix WP Clean Pages check when components are disabled
  CRM/Utils/System/WordPress.php
Labels: 5.55

#24760 AdminUI - Always cleanup saved searches during uninstall
  ext/civicrm_admin_ui/managed/SavedSearch_Administer_Assigned_Financial_Accounts.mgd.php
  ext/civicrm_admin_ui/managed/SavedSearch_Administer_Contact_Types.mgd.php
  ext/civicrm_admin_ui/managed/SavedSearch_Administer_Custom_Fields.mgd.php
  ext/civicrm_admin_ui/managed/SavedSearch_Administer_Custom_Groups.mgd.php
  ext/civicrm_admin_ui/managed/SavedSearch_Administer_Financial_Types.mgd.php
  ext/civicrm_admin_ui/managed/SavedSearch_Administer_ProfileFields.mgd.php
  ext/civicrm_admin_ui/managed/SavedSearch_Administer_Profiles.mgd.php
  ext/civicrm_admin_ui/managed/SavedSearch_Administer_Relationship_Types.mgd.php
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdminExport.component.js
Labels: master

#24967 Add html definition to schema for is_active (part 1)
  ext/oauth-client/xml/schema/CRM/OAuth/OAuthClient.xml
  xml/schema/ACL/ACL.xml
  xml/schema/ACL/ACLEntityRole.xml
  xml/schema/Campaign/Campaign.xml
  xml/schema/Campaign/Survey.xml
  xml/schema/Case/CaseType.xml
  xml/schema/Contact/ContactType.xml
  xml/schema/Contact/DashboardContact.xml
  xml/schema/Contact/Group.xml
  xml/schema/Contact/Relationship.xml
  xml/schema/Contact/RelationshipCache.xml
  xml/schema/Contact/RelationshipType.xml
  xml/schema/Contribute/ContributionPage.xml
Labels: master

#24968 Add html definition to schema for is_active (part 2)
  xml/schema/Contribute/Product.xml
  xml/schema/Contribute/Widget.xml
  xml/schema/Core/ActionSchedule.xml
  xml/schema/Core/Country.xml
  xml/schema/Core/County.xml
  xml/schema/Core/CustomField.xml
  xml/schema/Core/CustomGroup.xml
  xml/schema/Core/Dashboard.xml
  xml/schema/Core/Extension.xml
  xml/schema/Core/Job.xml
  xml/schema/Core/LocationType.xml
  xml/schema/Core/Menu.xml
  xml/schema/Core/MessageTemplate.xml
  xml/schema/Core/Navigation.xml
Labels: master

#24969 Add html definition to schema for is_active (part 3)
  xml/schema/Event/ParticipantStatusType.xml
  xml/schema/Financial/FinancialAccount.xml
  xml/schema/Financial/FinancialType.xml
  xml/schema/Financial/PaymentProcessor.xml
  xml/schema/Financial/PaymentProcessorType.xml
  xml/schema/Friend/Friend.xml
  xml/schema/Mailing/Component.xml
  xml/schema/Member/MembershipBlock.xml
  xml/schema/Member/MembershipStatus.xml
  xml/schema/Member/MembershipType.xml
  xml/schema/PCP/PCP.xml
  xml/schema/PCP/PCPBlock.xml
  xml/schema/Price/PriceField.xml
  xml/schema/Price/PriceFieldValue.xml
  xml/schema/Price/PriceSet.xml
  xml/schema/Report/ReportInstance.xml
  xml/schema/SMS/Provider.xml
Labels: master

#24970 Add html definition to schema for is_active (part 4)
  xml/schema/Core/OptionGroup.xml
  xml/schema/Core/OptionValue.xml
  xml/schema/Core/PrintLabel.xml
  xml/schema/Core/StateProvince.xml
  xml/schema/Core/StatusPreference.xml
  xml/schema/Core/UFField.xml
  xml/schema/Core/UFGroup.xml
  xml/schema/Core/UFJoin.xml
  xml/schema/Core/WordReplacement.xml
  xml/schema/Cxn/Cxn.xml
  xml/schema/Event/Event.xml
Labels: master

#24977 APIv3 - Use the Exception rather than the rule
  CRM/Core/Smarty/plugins/function.crmAPI.php
  CRM/Core/Smarty/plugins/function.crmSetting.php
  CRM/Utils/REST.php
Labels: master

#24979 Regen DAO
  CRM/ACL/DAO/ACL.php
  CRM/ACL/DAO/ACLEntityRole.php
  CRM/Campaign/DAO/Campaign.php
  CRM/Campaign/DAO/Survey.php
  CRM/Case/DAO/CaseType.php
  CRM/Contact/DAO/ContactType.php
  CRM/Contact/DAO/DashboardContact.php
  CRM/Contact/DAO/Group.php
  CRM/Contact/DAO/Relationship.php
  CRM/Contact/DAO/RelationshipCache.php
  CRM/Contact/DAO/RelationshipType.php
  CRM/Contribute/DAO/ContributionPage.php
  CRM/Contribute/DAO/Product.php
  CRM/Contribute/DAO/Widget.php
  CRM/Core/DAO/ActionSchedule.php
  CRM/Core/DAO/Country.php
  CRM/Core/DAO/County.php
  CRM/Core/DAO/CustomField.php
  CRM/Core/DAO/CustomGroup.php
  CRM/Core/DAO/Dashboard.php
  CRM/Core/DAO/Extension.php
  CRM/Core/DAO/Job.php
  CRM/Core/DAO/LocationType.php
  CRM/Core/DAO/Menu.php
  CRM/Core/DAO/MessageTemplate.php
  CRM/Core/DAO/Navigation.php
  CRM/Core/DAO/OptionGroup.php
  CRM/Core/DAO/OptionValue.php
  CRM/Core/DAO/PrintLabel.php
  CRM/Core/DAO/StateProvince.php
  CRM/Core/DAO/StatusPreference.php
  CRM/Core/DAO/UFField.php
  CRM/Core/DAO/UFGroup.php
  CRM/Core/DAO/UFJoin.php
  CRM/Core/DAO/WordReplacement.php
  CRM/Cxn/DAO/Cxn.php
  CRM/Event/DAO/Event.php
  CRM/Event/DAO/ParticipantStatusType.php
  CRM/Financial/DAO/FinancialAccount.php
  CRM/Financial/DAO/FinancialType.php
  CRM/Financial/DAO/PaymentProcessor.php
  CRM/Financial/DAO/PaymentProcessorType.php
  CRM/Friend/DAO/Friend.php
  CRM/Mailing/DAO/MailingComponent.php
  CRM/Member/DAO/MembershipBlock.php
  CRM/Member/DAO/MembershipStatus.php
  CRM/Member/DAO/MembershipType.php
  CRM/PCP/DAO/PCP.php
  CRM/PCP/DAO/PCPBlock.php
  CRM/Price/DAO/PriceField.php
  CRM/Price/DAO/PriceFieldValue.php
  CRM/Price/DAO/PriceSet.php
  CRM/Report/DAO/ReportInstance.php
  CRM/SMS/DAO/Provider.php
Labels: master

#24963 SearchKit - Fix campaign, event & primary address dropdowns
  CRM/Campaign/DAO/Campaign.php
  CRM/Core/I18n/SchemaStructure.php
  CRM/Event/DAO/Event.php
  Civi/Api4/Service/Autocomplete/CountryAutocompleteProvider.php
  ang/crmUi.js
  ext/search_kit/ang/crmSearchAdmin.module.js
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdmin.component.js
  ext/search_kit/ang/crmSearchTasks/crmSearchInput/crmSearchInputVal.component.js
  tests/phpunit/CRM/Utils/TokenConsistencyTest.php
  xml/schema/Campaign/Campaign.xml
  xml/schema/Event/Event.xml
Labels: master

#24978 (dev/core#3992) Expose created date column in contact reports
  CRM/Report/Form.php
Labels: master

#24983 [REF] DAO - Use class_alias for aliases of renamed classes
  CRM/ACL/DAO/EntityRole.php
  CRM/Dedupe/DAO/Exception.php
  CRM/Dedupe/DAO/Rule.php
  CRM/Dedupe/DAO/RuleGroup.php
Labels: master, merge on pass

#24926 dev/core#3685 Fix price sets in sample data
  sql/civicrm_generated.mysql
  xml/templates/civicrm_sample.tpl
Labels: 5.56

#24984 Add html for default field to schema
  xml/schema/Campaign/Survey.xml
  xml/schema/Core/LocationType.xml
  xml/schema/Core/MailSettings.xml
  xml/schema/Core/MessageTemplate.xml
  xml/schema/Core/OptionValue.xml
  xml/schema/Core/PrintLabel.xml
  xml/schema/Financial/FinancialAccount.xml
  xml/schema/Financial/PaymentProcessor.xml
  xml/schema/Financial/PaymentProcessorType.xml
  xml/schema/Mailing/Component.xml
  xml/schema/Member/MembershipStatus.xml
  xml/schema/Price/PriceFieldValue.xml
  xml/schema/SMS/Provider.xml
Labels: master, merge on pass

#24986 5.56
  sql/civicrm_generated.mysql
  xml/templates/civicrm_sample.tpl
Labels: master

#24990 Update DAOs after https://github.com/civicrm/civicrm-core/pull/24984
  CRM/Campaign/DAO/Survey.php
  CRM/Core/DAO/LocationType.php
  CRM/Core/DAO/MailSettings.php
  CRM/Core/DAO/MessageTemplate.php
  CRM/Core/DAO/OptionValue.php
  CRM/Core/DAO/PrintLabel.php
  CRM/Financial/DAO/FinancialAccount.php
  CRM/Financial/DAO/PaymentProcessor.php
  CRM/Financial/DAO/PaymentProcessorType.php
  CRM/Mailing/DAO/MailingComponent.php
  CRM/Member/DAO/MembershipStatus.php
  CRM/Price/DAO/PriceFieldValue.php
  CRM/SMS/DAO/Provider.php
Labels: master, merge on pass

#24993 Allow Joinables to be added to tables without specifying a base column
  Civi/Api4/Service/Schema/Joinable/Joinable.php
Labels: master

#24994 dev/core#3685 Fix price sets in sample data
  sql/civicrm_generated.mysql
  xml/templates/civicrm_sample.tpl
Labels: 5.55

#24995 5.55.2 - Add notes. Bump version.
  ext/afform/admin/info.xml
  ext/afform/core/info.xml
  ext/afform/html/info.xml
  ext/afform/mock/info.xml
  ext/authx/info.xml
  ext/civicrm_admin_ui/info.xml
  ext/civigrant/info.xml
  ext/civiimport/info.xml
  ext/ckeditor4/info.xml
  ext/contributioncancelactions/info.xml
  ext/elavon/info.xml
  ext/eventcart/info.xml
  ext/ewaysingle/info.xml
  ext/financialacls/info.xml
  ext/flexmailer/info.xml
  ext/greenwich/info.xml
  ext/legacycustomsearches/info.xml
  ext/message_admin/info.xml
  ext/oauth-client/info.xml
  ext/payflowpro/info.xml
  ext/recaptcha/info.xml
  ext/search_kit/info.xml
  ext/sequentialcreditnotes/info.xml
  release-notes.md
  release-notes/5.55.2.md
  sql/civicrm_generated.mysql
  sql/test_data_second_domain.mysql
  xml/version.xml
Labels: 5.55

#24923 dev/core#3962 Add 'boolean' as a filter for tokens
  Civi/Token/TokenProcessor.php
  tests/phpunit/Civi/Token/TokenProcessorTest.php
  tests/phpunit/api/v3/JobTest.php
Labels: master, has-test

#25000 Fix CiviCRM Home/Hide/Logout translation
  CRM/Core/BAO/Navigation.php
Labels: master, merge on pass

#25002 add legend to CMS user creation section
  templates/CRM/common/CMSUser.tpl
Labels: master

#25005 (alternate) Sentence runs together since period is inside the if block
  templates/CRM/common/CMSUser.tpl
Labels: master

#24989 Use fastArray cache for js_strings
  Civi/Core/Container.php
Labels: master

#25008 [NFC] Allow running tests/phpunit/CRM/Core/DAOTest.php on mariadb
  tests/phpunit/CRM/Core/DAOTest.php
Labels: master, merge on pass

#25007 php8 - don't pass null as string
  CRM/Core/DAO.php
  CRM/Utils/Type.php
Labels: master

#25011 Var type fix in comment
  CRM/Core/Resources.php
Labels: master, merge on pass

#25010 Menubar - fix height of quicksearch (Drupal9)
  css/crm-menubar.css
Labels: master

#25013 [NFC] UtilsTest - convert EventDispatcher to CiviEventDispatcher
  tests/phpunit/api/v3/UtilsTest.php
Labels: master, merge on pass

#25016 dev/core#3999 : Unable to delete price field
  CRM/Price/Page/Field.php
Labels: sig:regression, 5.56

#25015 dev/core#3999 : Unable to delete price field
  CRM/Price/Page/Field.php
Labels: sig:regression, 5.55

#24991 add event entity to formbuilder
  ext/afform/admin/afformEntities/Event.php
Labels: master

#24999 [REF] OptionValue - Deprecate del() function in favor of standard deleteRecord
  CRM/Core/BAO/OptionValue.php
Labels: master

#24985 SearchKit - Descriptions for search displays
  ext/search_kit/Civi/Api4/Event/Subscriber/DefaultDisplaySubscriber.php
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdminDisplayHeader.html
  ext/search_kit/ang/crmSearchAdmin/tabs.html
  ext/search_kit/ang/crmSearchDisplayGrid/crmSearchDisplayGrid.html
  ext/search_kit/ang/crmSearchDisplayList/crmSearchDisplayList.html
  ext/search_kit/ang/crmSearchDisplayTable/crmSearchDisplayTable.html
Labels: master

#25017 Deprecate `CRM_Contact_BAO_Relationship::del()` in favour of `deleteRecord()`
  CRM/Contact/BAO/Relationship.php
  CRM/Contact/Form/Relationship.php
  CRM/Contact/Page/View/Relationship.php
Labels: master, merge on pass

#25018 Deprecate `CRM_Event_BAO_Event::del()` in favour of `deleteRecord()`
  CRM/Event/BAO/Event.php
Labels: master, merge on pass

#25019 More BAO `del()` deprecations
  CRM/Contribute/BAO/ManagePremiums.php
  CRM/Contribute/BAO/Premium.php
  CRM/Core/BAO/Discount.php
  CRM/Core/BAO/PreferencesDate.php
  CRM/SMS/BAO/Provider.php
Labels: master, merge on pass

#25021 Add default label field for RelationshipType entity
  CRM/Contact/DAO/RelationshipType.php
  xml/schema/Contact/RelationshipType.xml
Labels: master, merge on pass

#25025 Fix Authorization failed on Event Registration - 5.56 RC regression
  CRM/Event/Form/Registration/Confirm.php
Labels: 5.56

#25022 Cleanup in test class
  tests/phpunit/CRM/Core/BAO/MessageTemplateTest.php
Labels: master

#25006 More del() deprecations in favour of standard deleteRecord()
  CRM/Core/BAO/Extension.php
  CRM/Core/BAO/UFGroup.php
  CRM/Core/BAO/Website.php
  CRM/Member/BAO/MembershipLog.php
Labels: master, merge on pass

#25027 5.56
  CRM/Event/Form/Registration/Confirm.php
  CRM/Price/Page/Field.php
Labels: master

#25029 ajax batchSave() method should be static, php8 compatibility
  CRM/Batch/Page/AJAX.php
Labels: master, merge on pass

#25031 default token filter
  Civi/Token/TokenProcessor.php
  tests/phpunit/Civi/Token/TokenProcessorTest.php
Labels: master, merge on pass, has-test, needs-documentation

#25032 Update location tokens for Contact to new apiv4 style
  CRM/Contact/Tokens.php
  CRM/Core/EntityTokens.php
  tests/phpunit/CRM/Core/BAO/MessageTemplateTest.php
Labels: master

#25024 Deprecate `CRM_Mailing_BAO_MailingAB::del()`
  CRM/Mailing/BAO/Mailing.php
  CRM/Mailing/BAO/MailingAB.php
  CRM/Mailing/Form/Browse.php
  CRM/Mailing/Page/Browse.php
Labels: master

#25012 Menubar - Fix buggy, slow loader
  js/crm.menubar.js
Labels: master

#24996 (dev/core#3979) Localization - Assign a locale for UF during negotiation
  Civi/Core/Locale.php
  tests/phpunit/E2E/Api4/LocaleTest.php
Labels: merge ready, 5.56

#25034 5.56
  Civi/Core/Locale.php
  tests/phpunit/E2E/Api4/LocaleTest.php
Labels: master

#25035 afform/oauth-client - don't call stat on null
  ext/afform/core/Civi/Afform/AngularDependencyMapper.php
Labels: master, merge on pass

#24992 Messagetemplate schema changes
  CRM/Core/DAO/MessageTemplate.php
  Civi/Api4/MessageTemplate.php
  Civi/Api4/Service/Spec/Provider/MessageTemplateGetSpecProvider.php
  tests/phpunit/CRM/Core/BAO/MessageTemplateTest.php
  xml/schema/Core/MessageTemplate.xml
Labels: master, merge on pass, has-test

#25036 EntityFinancialAccount - A tale of two BAO classes
  CRM/Contribute/BAO/Contribution.php
  CRM/Core/BAO/OptionValue.php
  CRM/Core/CodeGen/GenerateData.php
  CRM/Financial/BAO/EntityFinancialAccount.php
  CRM/Financial/BAO/FinancialType.php
  CRM/Financial/BAO/FinancialTypeAccount.php
  CRM/Financial/BAO/PaymentProcessor.php
  CRM/Financial/Form/FinancialAccount.php
  CRM/Financial/Form/FinancialTypeAccount.php
  CRM/Financial/Form/PaymentEdit.php
  CRM/Financial/Page/FinancialType.php
  CRM/Financial/Page/FinancialTypeAccount.php
  api/v3/utils.php
  tests/phpunit/CRM/Contribute/PseudoConstantTest.php
  tests/phpunit/CRM/Core/PseudoConstantTest.php
  tests/phpunit/CRM/Financial/BAO/FinancialTypeAccountTest.php
  tests/phpunit/CRMTraits/Financial/TaxTrait.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/api/v3/ContributionTest.php
  tests/phpunit/api/v3/TaxContributionPageTest.php
Labels: master, merge on pass

#24947 Add entity-types-php mixin
  ext/search_kit/info.xml
  ext/search_kit/search_kit.php
  mixin/entity-types-php@1/example/CRM/Shimmy/DAO/ShimThing.php
  mixin/entity-types-php@1/example/make-dao.php
  mixin/entity-types-php@1/example/tests/mixin/EntityTypesTest.php
  mixin/entity-types-php@1/example/xml/schema/CRM/Shimmy/ShimThing.entityType.php
  mixin/entity-types-php@1/example/xml/schema/CRM/Shimmy/ShimThing.xml
  mixin/entity-types-php@1/mixin.php
  tests/extensions/shimmy/tests/phpunit/E2E/Shimmy/LifecycleTest.php
Labels: master, merge on pass

#25038 Use search display to view errors when using Civi-import extension
  ext/civiimport/civiimport.php
  templates/CRM/Contact/Import/Form/Summary.tpl
Labels: master

#25042 REF: Replace CRM_Utils_Array::value in CRM/Event/Form/Registration
  CRM/Event/Form/Registration.php
Labels: master, merge on pass

#25043 DAOs are stale
  CRM/Mailing/DAO/MailingRecipients.php
  CRM/Mailing/Event/DAO/MailingEventBounce.php
  CRM/Mailing/Event/DAO/MailingEventClickThrough.php
  CRM/Mailing/Event/DAO/MailingEventConfirm.php
  CRM/Mailing/Event/DAO/MailingEventDelivered.php
  CRM/Mailing/Event/DAO/MailingEventForward.php
  CRM/Mailing/Event/DAO/MailingEventOpened.php
  CRM/Mailing/Event/DAO/MailingEventQueue.php
  CRM/Mailing/Event/DAO/MailingEventReply.php
  CRM/Mailing/Event/DAO/MailingEventSubscribe.php
  CRM/Mailing/Event/DAO/MailingEventUnsubscribe.php
Labels: master, merge on pass

#25045 REF: Consistent variables names in formRule for CRM/Event/Form/Register
  CRM/Event/Form/Registration/Confirm.php
Labels: master, merge on pass

#25044 REF: Convert CRM_Utils_Array::value in CRM/Event/Form/Confirm
  CRM/Event/Form/Registration/Confirm.php
Labels: master, merge on pass

#25037 Test fix - setup is incongruent
  tests/phpunit/api/v3/ContributionTest.php
Labels: master

#25046 Pass correct variable type to the hook
  CRM/Contact/Page/View/Relationship.php
Labels: master

#25049 Remove deprecated token function
  CRM/Utils/Token.php
Labels: master

#25050 Add noisy deprecation to deprecated contribution token functions
  CRM/Contribute/BAO/Contribution.php
  CRM/Utils/Token.php
  tests/phpunit/CRM/Contribute/ActionMapping/ByTypeTest.php
  tests/phpunit/CRM/Contribute/BAO/ContributionTest.php
Labels: master

#25051 Remove deprecated, probably long-broken function `replaceOrgTokens`
  CRM/Utils/Token.php
Labels: master

#25033 fixes dash line appended to the contribution amounts if label is empty
  CRM/Price/BAO/PriceField.php
Labels: master

#25055 Fix upgrader to safely run multiple times
  CRM/Upgrade/Incremental/php/FiveFiftyOne.php
Labels: 5.56

#25047 Fix Relationship to permit disabled relationships as duplicates & fix test
  CRM/Contact/BAO/Contact/Utils.php
  CRM/Contact/BAO/Relationship.php
  CRM/Contact/Import/Parser/Contact.php
  CRM/Core/BAO/Address.php
  tests/phpunit/api/v4/Entity/RelationshipTest.php
Labels: master, merge ready

#25057 Merge 5.56 to master
  CRM/Upgrade/Incremental/php/FiveFiftyOne.php
Labels: master

#25001 Afform - Autofill contacts by relationship
  ang/crmUi.js
  ext/afform/admin/Civi/AfformAdmin/AfformAdminMeta.php
  ext/afform/admin/ang/afGuiEditor/afGuiEntity.component.js
  ext/afform/admin/ang/afGuiEditor/afGuiEntity.html
  ext/afform/admin/ang/afGuiEditor/afGuiFieldValue.directive.js
  ext/afform/admin/ang/afGuiEditor/behaviors/afGuiDefaultBehaviorTemplate.html
  ext/afform/admin/ang/afGuiEditor/behaviors/autofillRelationshipBehavior.html
  ext/afform/admin/ang/afGuiEditor/behaviors/autofillRelationshipBehaviorForm.component.js
  ext/afform/admin/ang/afGuiEditor/behaviors/autofillRelationshipBehaviorForm.html
  ext/afform/core/Civi/Afform/AbstractBehavior.php
  ext/afform/core/Civi/Afform/Behavior/ContactAutofill.php
  ext/afform/core/Civi/Afform/BehaviorInterface.php
  ext/afform/core/Civi/Afform/Event/AfformEntitySortEvent.php
  ext/afform/core/Civi/Afform/Event/AfformEventEntityTrait.php
  ext/afform/core/Civi/Api4/Action/Afform/AbstractProcessor.php
  ext/afform/core/Civi/Api4/Action/AfformBehavior/Get.php
  ext/afform/core/Civi/Api4/AfformBehavior.php
  ext/afform/mock/tests/phpunit/api/v4/AfformRelationshipUsageTest.php
  ext/search_kit/Civi/Api4/Action/SearchDisplay/AbstractRunAction.php
  ext/search_kit/Civi/Api4/Action/SearchDisplay/Run.php
  ext/search_kit/ang/crmSearchTasks.module.js
Labels: master, has-test

#25056 Make MessageTemplate.master_id fully joinable
  Civi/Api4/Event/Subscriber/MessageTemplateSchemaMapSubscriber.php
  Civi/Api4/Service/Spec/Provider/MessageTemplateGetSpecProvider.php
  tests/phpunit/CRM/Core/BAO/MessageTemplateTest.php
  tests/phpunit/api/v4/Entity/MessageTemplateTest.php
Labels: master

#25061 Afform - fix empty search filters
  ext/search_kit/ang/crmSearchDisplay/traits/searchDisplayBaseTrait.service.js
Labels: 5.56

#25062 5.56 to master
  ext/search_kit/ang/crmSearchDisplay/traits/searchDisplayBaseTrait.service.js
Labels: master

#24987 SearchKit - Fix display count when updating items on the last page
  ext/search_kit/ang/crmSearchDisplay/traits/searchDisplayBaseTrait.service.js
Labels: master

#25064 [REF] ContactType BAO - Simplify getAllContactTypes
  CRM/Contact/BAO/ContactType.php
Labels: master, merge on pass
