Repository civicrm/civicrm-core, pull requests merged in 2022-05, with the labels that each got.

#23327 dev/core#3431 - Case activity only has 25 contacts listed from Case Resources in the Send Copy section
  CRM/Case/BAO/Case.php
  tests/phpunit/CRM/Case/BAO/CaseTest.php
Labels: master, merge on pass, has-test

#23262 [REF] [Import] Handle limit with more sanity
  CRM/Contact/Import/Parser/Contact.php
Labels: master

#23335 SearchKit - Ensure all date and timestamp fields are presented with datepicker
  ext/search_kit/ang/crmSearchTasks/crmSearchInput/crmSearchInputVal.component.js
Labels: master, merge on pass

#23329 Fix master-only regression on showing fields for contact type
  CRM/Contact/Import/Form/MapField.php
  CRM/Contact/Import/Form/Preview.php
  CRM/Contact/Import/Parser/Contact.php
  CRM/Import/Forms.php
  CRM/Import/ImportProcessor.php
  CRM/Import/Parser.php
  tests/phpunit/CRM/Contact/Import/Form/DataSourceTest.php
  tests/phpunit/CRM/Contact/Import/Form/MapFieldTest.php
  tests/phpunit/CRM/Contact/Import/Parser/ContactTest.php
  tests/phpunit/CRM/Import/DataSource/CsvTest.php
Labels: master

#23338 Add import function to parser
  CRM/Contact/Import/Parser/Contact.php
Labels: master, merge on pass

#23337 Master only import regression - fix contactSubType handling
  CRM/Contact/Import/Form/DataSource.php
  CRM/Contact/Import/Form/MapField.php
  CRM/Contact/Import/Form/Preview.php
  CRM/Contact/Import/MetadataTrait.php
  CRM/Contact/Import/Parser/Contact.php
  CRM/Import/Forms.php
  CRM/Import/Parser.php
  templates/CRM/Contact/Import/Form/DataSource.tpl
  tests/phpunit/CRM/Contact/Import/Form/MapFieldTest.php
  tests/phpunit/CRM/Contact/Import/Parser/ContactTest.php
Labels: master, merge on pass

#23334 AfformGui - Optional reset button for search and submit forms
  ext/afform/admin/Civi/AfformAdmin/AfformAdminMeta.php
  ext/afform/admin/ang/afGuiEditor/afGuiEntity.component.js
  ext/afform/admin/ang/afGuiEditor/afGuiSearch.component.js
Labels: master

#23324 🇦🇺 jira/browse/CRM-18217 On the website front-end, CiviCRM page heading should start from h2 and not h1
  templates/CRM/common/CMSPrint.tpl
Labels: master, merge ready

#23261 [REF] [Import] Remove another good intention from the import class
  CRM/Activity/Import/Parser/Activity.php
  CRM/Contact/Import/Parser/Contact.php
  CRM/Contribute/Import/Parser/Contribution.php
  CRM/Custom/Import/Parser/Api.php
  CRM/Event/Import/Parser/Participant.php
  CRM/Member/Import/Parser/Membership.php
Labels: master

#23347 [REF] [Import] Trivial - simplify variable
  CRM/Contact/Import/Parser/Contact.php
Labels: master, merge on pass

#23348 APIv4 - Support pseudoconstant suffixes in getFields
  Civi/Api4/Generic/DAOGetFieldsAction.php
  tests/phpunit/api/v4/Action/BasicCustomFieldTest.php
Labels: master, has-test

#23321 PR 22070 follow-up: reinstate respecting no_display on report column headers
  CRM/Report/Form.php
Labels: master

#23310 Api4 - minor fixes and updates
  Civi/Api4/Generic/AbstractAction.php
  Civi/Api4/Generic/AbstractSaveAction.php
Labels: master

#23350 IDE cheer - cast var explicitly to an int
  CRM/Contact/BAO/Contact/Utils.php
Labels: master

#23354 SearchKit - Consistently check for date field
  ext/search_kit/ang/crmSearchTasks/crmSearchInput/crmSearchInputVal.component.js
Labels: master, merge on pass

#23355 Fix 'Table already exists' error when running 5.50 upgrade twice
  CRM/Upgrade/Incremental/sql/5.50.alpha1.mysql.tpl
Labels: master, merge on pass

#23352 Remove unused variable
  CRM/Contact/BAO/Contact/Utils.php
Labels: master

#23349 [REF] [Import] Trivial - simplify variable
  CRM/Contact/Import/Parser/Contact.php
Labels: master

#23359 [NFC] Fix APIv4 docblock annotations for Managed API
  Civi/Api4/Action/Managed/Reconcile.php
  Civi/Api4/Managed.php
Labels: master, merge on pass

#23344 [Ref] [Import] Add extra functions to DataSource
  CRM/Import/DataSource.php
  CRM/Import/Forms.php
Labels: master

#23357 NFC Minor cleanup to Participant confirm
  CRM/Event/Form/Registration/Confirm.php
  CRM/Event/Form/Registration/ParticipantConfirm.php
Labels: master, merge on pass

#23345 Stop adding obsolete currencies to new installs
  xml/templates/civicrm_currency.tpl
Labels: master, merge ready

#23342 [Import] [Ref] [Contact] Extract row mapping and add test
  CRM/Contact/Import/Parser/Contact.php
  tests/phpunit/CRM/Contact/Import/Parser/ContactTest.php
Labels: master

#23340 [REF][Import] [Contact] Clean up preview screen
  CRM/Contact/Import/Form/MapField.php
  CRM/Contact/Import/Form/Preview.php
  templates/CRM/Contact/Import/Form/MapTable.tpl
Labels: master

#23288 [Import] Upgrade saved import names for contacts
  CRM/Contact/Import/Form/MapField.php
  CRM/Import/ImportProcessor.php
  CRM/Import/Parser.php
  CRM/Upgrade/Incremental/php/FiveFifty.php
  tests/phpunit/CRM/Contact/Import/Form/MapFieldTest.php
Labels: master

#23339 add missing Parishes of Bermuda (civicrm_state_province)
  CRM/Upgrade/Incremental/sql/5.50.alpha1.mysql.tpl
  sql/civicrm_generated.mysql
  xml/templates/civicrm_state_province.tpl
Labels: master, merge on pass

#23360 [REF] [Import] Trivial - simplify variable
  CRM/Contact/Import/Parser/Contact.php
Labels: master, merge on pass

#23362 DAOs out of date
  CRM/Campaign/DAO/Survey.php
  CRM/Financial/DAO/FinancialTrxn.php
Labels: master, merge on pass

#23361 Import - fix comment
  CRM/Contact/Import/Parser/Contact.php
Labels: master, merge on pass

#23313 Issue 3249: make casetype a managed entity
  Civi/Api4/CaseType.php
Labels: master

#23351 dev/core#3439 change batch geocode query to include events
  CRM/Utils/Address/BatchUpdate.php
Labels: master

#23276 [Ref] [Import] Cleanup cleanup on old tables for form re-submission
  CRM/Contact/Import/Form/DataSource.php
  CRM/Import/DataSource/CSV.php
  CRM/Import/DataSource/SQL.php
  CRM/Import/Forms.php
  tests/phpunit/CRM/Contact/Import/Form/DataSourceTest.php
Labels: master

#23364 Minor function simplification in private function
  CRM/Contact/BAO/Contact/Utils.php
Labels: master, merge on pass

#23336 CustomFields - Improve metadata about which custom groups belong to which entities
  CRM/Core/BAO/CustomGroup.php
  CRM/Core/DAO.php
  CRM/Core/DAO/AllCoreTables.php
  CRM/Core/DAO/CustomGroup.php
  CRM/Core/PseudoConstant.php
  CRM/Core/SelectValues.php
  CRM/Custom/Page/Group.php
  CRM/Upgrade/Incremental/sql/5.50.alpha1.mysql.tpl
  Civi/Api4/Service/Spec/Provider/CustomGroupSpecProvider.php
  Civi/Api4/Service/Spec/SpecFormatter.php
  Civi/Api4/Utils/CoreUtil.php
  Civi/Api4/Utils/FormattingUtil.php
  api/v3/CustomGroup.php
  api/v3/Rule.php
  api/v3/RuleGroup.php
  api/v3/utils.php
  ext/civigrant/managed/OptionValue_cg_extends_objects_grant.mgd.php
  tests/phpunit/CRM/Core/BAO/CustomGroupTest.php
  tests/phpunit/api/v3/SyntaxConformanceTest.php
  tests/phpunit/api/v4/Action/BasicCustomFieldTest.php
  tests/phpunit/api/v4/Entity/CaseTest.php
  xml/schema/Core/CustomGroup.xml
  xml/templates/civicrm_data.tpl
Labels: master

#23363 [REF] [Import] Trivial - simplify variables
  CRM/Contact/Import/Parser/Contact.php
Labels: master, merge on pass

#23367 [Ref][Import] Remove another good intention - random email counting
  CRM/Contact/Import/Parser/Contact.php
Labels: master, merge on pass

#23370 [Import] [Ref] [Minor] Simplify error handling with a try-catch block
  CRM/Contact/Import/Parser/Contact.php
Labels: master

#23328 548 backports
  CRM/Financial/BAO/Order.php
  Civi/Payment/PropertyBag.php
  tests/phpunit/CRM/Member/Form/MembershipTest.php
  tests/phpunit/CRMTraits/Financial/PriceSetTrait.php
Labels: 5.48

#23366 [REF] [Import] Remove unused tpl assign showColNames
  CRM/Contact/Import/Form/MapField.php
  CRM/Contact/Import/Form/Preview.php
  CRM/Custom/Import/Form/MapField.php
Labels: master, merge on pass

#23356 Ensure comma not formatted into amount
  CRM/Core/Payment.php
  Civi/Core/Format.php
  ext/payflowpro/tests/phpunit/CRM/Core/Payment/PayflowProTest.php
Labels: merge ready, has-test, 5.49

#23374 549 to master
  CRM/Core/Payment.php
  Civi/Core/Format.php
  ext/payflowpro/tests/phpunit/CRM/Core/Payment/PayflowProTest.php
Labels: master

#23368 [REF] Minor code simplifcation - reduce silly lines
  CRM/Contact/BAO/Contact/Utils.php
Labels: master

#23292 [Import] Output errors, duplicates csvs directly from the user job table
  CRM/Contact/Import/Form/DataSource.php
  CRM/Contact/Import/Form/MapField.php
  CRM/Contact/Import/Form/Preview.php
  CRM/Contact/Import/Form/Summary.php
  CRM/Contact/Import/ImportJob.php
  CRM/Contact/Import/Parser/Contact.php
  CRM/Core/xml/Menu/Import.xml
  CRM/Import/DataSource.php
  CRM/Import/DataSource/CSV.php
  CRM/Import/DataSource/SQL.php
  CRM/Import/Form/Summary.php
  CRM/Import/Forms.php
  templates/CRM/Contact/Import/Form/Preview.tpl
  templates/CRM/Contact/Import/Form/Summary.tpl
  tests/phpunit/CRM/Import/DataSource/CsvTest.php
Labels: master

#23282 [REF] Do not treat site having a default location type as optional
  CRM/Contact/Import/Form/MapField.php
Labels: master

#23375 [Ref] Get rid of private deprecated legacy function
  CRM/Contact/BAO/Contact/Utils.php
Labels: master

#23369 [REF] [Import] Trivial - simplify variables
  CRM/Contact/Import/Parser/Contact.php
Labels: master

#21993 ACLCache: Efficiency. Fix duplicate inserts
  CRM/Contact/BAO/Contact/Permission.php
  CRM/Contact/BAO/GroupContactCache.php
  CRM/Core/Lock.php
Labels: master, merge ready

#23379 Translation - distinguish between 'On' for date and 'On'/'Off'
  templates/CRM/Mailing/Page/Report.tpl
Labels: master, merge on pass

#23371 [REF] [Import] extract validation functionality
  CRM/Contact/Import/Parser/Contact.php
Labels: master

#23381 SearchKit - Add date pseudo-fields
  ext/search_kit/Civi/Api4/Action/SearchDisplay/AbstractRunAction.php
  ext/search_kit/ang/crmSearchAdmin.module.js
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdmin.component.js
Labels: master, merge on pass

#23380 [REF] [Import] Remove another good intention - import 'conflicts'
  CRM/Activity/Import/Form/Preview.php
  CRM/Activity/Import/Form/Summary.php
  CRM/Activity/Import/Parser/Activity.php
  CRM/Contact/Import/Form/Preview.php
  CRM/Contact/Import/Form/Summary.php
  CRM/Contact/Import/ImportJob.php
  CRM/Contact/Import/Parser/Contact.php
  CRM/Contribute/Import/Form/Preview.php
  CRM/Contribute/Import/Form/Summary.php
  CRM/Contribute/Import/Parser/Contribution.php
  CRM/Custom/Import/Form/Preview.php
  CRM/Custom/Import/Parser/Api.php
  CRM/Event/Import/Form/Preview.php
  CRM/Event/Import/Form/Summary.php
  CRM/Event/Import/Parser/Participant.php
  CRM/Import/Forms.php
  CRM/Import/Parser.php
  CRM/Member/Import/Form/Preview.php
  CRM/Member/Import/Form/Summary.php
  CRM/Member/Import/Parser/Membership.php
  templates/CRM/Activity/Import/Form/Preview.tpl
  templates/CRM/Activity/Import/Form/Summary.tpl
  templates/CRM/Contact/Import/Form/Preview.tpl
  templates/CRM/Contact/Import/Form/Summary.tpl
  templates/CRM/Contribute/Import/Form/Preview.tpl
  templates/CRM/Contribute/Import/Form/Summary.tpl
  templates/CRM/Event/Import/Form/Preview.tpl
  templates/CRM/Event/Import/Form/Summary.tpl
  templates/CRM/Member/Import/Form/Preview.tpl
  templates/CRM/Member/Import/Form/Summary.tpl
Labels: master, merge on pass

#23343 [REF] [Import] Stop passing submittedValues as parameters
  CRM/Contact/Import/Parser/Contact.php
  tests/phpunit/CRM/Contact/Import/Form/MapFieldTest.php
  tests/phpunit/CRM/Contact/Import/Parser/ContactTest.php
Labels: master

#23376 Update expired root certs for when retrieving messages from civicrm.org on civi dashboard
  composer.json
  composer.lock
Labels: 5.49

#23387 Update expired root certs (5.50)
  composer.json
  composer.lock
Labels: merge ready, 5.50

#23388 5.50
  composer.json
  composer.lock
Labels: master

#23384 [Import] [Ref] Iterate through the mapping of fields
  CRM/Contact/Import/Form/MapField.php
  CRM/Contact/Import/Parser/Contact.php
  tests/phpunit/CRM/Contact/Import/Form/MapFieldTest.php
  tests/phpunit/CRM/Contact/Import/Parser/ContactTest.php
Labels: master

#23389 APIv4 - Fix fatal error on getFields when passing in contact id
  Civi/Api4/Service/Spec/RequestSpec.php
  tests/phpunit/api/v4/Action/GetExtraFieldsTest.php
Labels: has-test, 5.50

#23390 [BP] APIv4 - Fix fatal error on getFields when passing in contact id
  Civi/Api4/Service/Spec/RequestSpec.php
  tests/phpunit/api/v4/Action/GetExtraFieldsTest.php
Labels: has-test, 5.49

#23391 5.50
  Civi/Api4/Service/Spec/RequestSpec.php
  tests/phpunit/api/v4/Action/GetExtraFieldsTest.php
Labels: master

#23386 [REF] [Import] Stop passing unused parameters
  CRM/Contact/Import/Form/DataSource.php
  CRM/Contact/Import/Form/MapField.php
  CRM/Contact/Import/ImportJob.php
  CRM/Contact/Import/Parser/Contact.php
Labels: master

#23392 5.49.1 - Set version. Add notes.
  ext/afform/admin/info.xml
  ext/afform/core/info.xml
  ext/afform/html/info.xml
  ext/afform/mock/info.xml
  ext/authx/info.xml
  ext/civicrm_admin_ui/info.xml
  ext/civigrant/info.xml
  ext/ckeditor4/info.xml
  ext/contributioncancelactions/info.xml
  ext/eventcart/info.xml
  ext/ewaysingle/info.xml
  ext/financialacls/info.xml
  ext/flexmailer/info.xml
  ext/greenwich/info.xml
  ext/legacycustomsearches/info.xml
  ext/message_admin/info.xml
  ext/oauth-client/info.xml
  ext/payflowpro/info.xml
  ext/recaptcha/info.xml
  ext/search_kit/info.xml
  ext/sequentialcreditnotes/info.xml
  release-notes.md
  release-notes/5.49.1.md
  sql/civicrm_generated.mysql
  sql/test_data_second_domain.mysql
  xml/version.xml
Labels: 5.49

#23396 5.50.alpha1.mysql.tpl - Escape `grouping` (reserved word in MySQL 8.0)
  CRM/Upgrade/Incremental/sql/5.50.alpha1.mysql.tpl
Labels: merge on pass, 5.50

#23394 Import 550
  CRM/Import/DataSource.php
Labels: 5.50

#23393 dev/core#3447 Fix for master-only-regression
  CRM/Contact/Import/Form/MapField.php
Labels: master

#23398 (E2E) testErrorChrome - Skip Backdrop and D8+ (much like D7)
  tests/phpunit/E2E/Core/ErrorTest.php
Labels: merge on pass, 5.50

#23397 (E2E) `testErrorChrome` - Update assertions for page-chrome
  tests/phpunit/E2E/Core/ErrorTest.php
Labels: merge on pass, 5.50

#23399 5.50
  CRM/Import/DataSource.php
  CRM/Upgrade/Incremental/sql/5.50.alpha1.mysql.tpl
  tests/phpunit/E2E/Core/ErrorTest.php
Labels: master

#23400 [Import] Reduce unused copy & paste
  CRM/Activity/Import/Form/Preview.php
  CRM/Activity/Import/Form/Summary.php
  CRM/Contribute/Import/Form/Preview.php
  CRM/Contribute/Import/Form/Summary.php
  CRM/Custom/Import/Form/Preview.php
  CRM/Event/Import/Form/Preview.php
  CRM/Event/Import/Form/Summary.php
  CRM/Member/Import/Form/Preview.php
  CRM/Member/Import/Form/Summary.php
  templates/CRM/Activity/Import/Form/Summary.tpl
  templates/CRM/Contribute/Import/Form/Summary.tpl
  templates/CRM/Event/Import/Form/Summary.tpl
  templates/CRM/Member/Import/Form/Summary.tpl
Labels: master

#23395 [Ref][Import] Remove now-unused code
  CRM/Contact/Import/Parser/Contact.php
Labels: master

#23296 Afform - support relationships
  CRM/Contact/DAO/Relationship.php
  ext/afform/admin/Civi/AfformAdmin/AfformAdminMeta.php
  ext/afform/admin/Civi/Api4/Action/Afform/LoadAdminData.php
  ext/afform/admin/afformEntities/Relationship.php
  ext/afform/admin/ang/afGuiEditor/afGuiEditor.component.js
  ext/afform/admin/ang/afGuiEditor/elements/afGuiContainer.component.js
  ext/afform/core/Civi/Afform/Event/AfformSubmitEvent.php
  ext/afform/core/Civi/Afform/FormDataModel.php
  ext/afform/core/Civi/Api4/Action/Afform/Submit.php
  ext/afform/core/afform.php
  ext/afform/core/tests/phpunit/Civi/Afform/FormDataModelTest.php
  ext/afform/mock/tests/phpunit/api/v4/AfformRelationshipUsageTest.php
  xml/schema/Contact/Relationship.xml
Labels: master

#23382 [REF] Import - make condition clearer
  CRM/Contact/Import/Parser/Contact.php
Labels: master

#23410 [TEST ONLY] APIv4 - Remove unused extras from ConformanceTest
  tests/phpunit/api/v4/Entity/ConformanceTest.php
Labels: master

#23411 5.50
  CRM/Contact/Import/Form/Summary.php
Labels: master

#23412 Afform - Fix RC regression of missing input types
  ext/afform/admin/ang/afGuiEditor/elements/afGuiField.component.js
Labels: 5.50

#23414 5.50 to master
  ext/afform/admin/ang/afGuiEditor/elements/afGuiField.component.js
Labels: master

#23401 (REF) Importer - Remove unused parameters. Simplify signature.
  CRM/Contact/Import/Form/DataSource.php
  CRM/Import/DataSource.php
  CRM/Import/DataSource/CSV.php
  CRM/Import/DataSource/SQL.php
  tests/phpunit/CRM/Contact/Import/Form/MapFieldTest.php
Labels: master

#23385 SearchKit - Default to search for individuals
  ext/search_kit/Civi/Search/Admin.php
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdmin.component.js
Labels: master, merge ready

#23317 [REF] Fix PHP8.1 issue with passing NULL to trim()
  CRM/Core/CodeGen/Specification.php
Labels: master, merge on pass

#23418 [Import] Use table rather than csvs for no-match & unparsed
  CRM/Contact/Import/Form/Preview.php
  CRM/Contact/Import/Form/Summary.php
  CRM/Contact/Import/Parser/Contact.php
  CRM/Import/DataSource.php
  templates/CRM/Contact/Import/Form/Summary.tpl
  tests/phpunit/CRM/Contact/Import/Form/data/individual_invalid_contact_sub_type.csv
  tests/phpunit/CRM/Contact/Import/Form/data/individual_invalid_email.csv
  tests/phpunit/CRM/Contact/Import/Form/data/individual_invalid_missing_name.csv
  tests/phpunit/CRM/Contact/Import/Form/data/individual_invalid_related_email.csv
  tests/phpunit/CRM/Contact/Import/Parser/ContactTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: master

#23415 [Ref][Import] Start adding testing to validation, simplify
  CRM/Contact/Import/Parser/Contact.php
  tests/phpunit/CRM/Contact/Import/Form/data/individual_invalid_missing_name.csv
  tests/phpunit/CRM/Contact/Import/Parser/ContactTest.php
Labels: master

#23416 [REF] [Import] Create user-job records for Memership imports
  CRM/Import/Form/DataSource.php
  CRM/Member/Import/Form/MapField.php
  CRM/Member/Import/Form/Preview.php
Labels: master

#23422 ManagedEntities - Update version number for mgd-php
  mixin/mgd-php@1/mixin.php
Labels: merge on pass, 5.50

#23423 (NFC) mixin/**.php - Add @since tags
  mixin/afform-entity-php@1/mixin.php
  mixin/ang-php@1/mixin.php
  mixin/case-xml@1/mixin.php
  mixin/menu-xml@1/mixin.php
  mixin/mgd-php@1/mixin.php
  mixin/setting-php@1/mixin.php
  mixin/theme-php@1/mixin.php
  tools/mixin/bin/mixer
Labels: merge on pass, 5.50

#23426 5.50 to master
  mixin/afform-entity-php@1/mixin.php
  mixin/ang-php@1/mixin.php
  mixin/case-xml@1/mixin.php
  mixin/menu-xml@1/mixin.php
  mixin/mgd-php@1/mixin.php
  mixin/setting-php@1/mixin.php
  mixin/theme-php@1/mixin.php
  tools/mixin/bin/mixer
Labels: master

#23425 [Ref] [Import][Member] Remove unused params
  CRM/Member/Import/Form/MapField.php
Labels: master, merge on pass

#23421 [Import] Stop passing unused parameter
  CRM/Contact/Import/Form/MapField.php
  CRM/Contact/Import/ImportJob.php
Labels: master

#23428 [REF] [Import] Remove unused field get action (death to copy & paste)
  CRM/Contribute/Import/Parser/Contribution.php
  CRM/Custom/Import/Parser/Api.php
  CRM/Event/Import/Form/MapField.php
  CRM/Event/Import/Parser/Participant.php
  CRM/Member/Import/Form/MapField.php
  CRM/Member/Import/Parser/Membership.php
Labels: master, merge on pass

#23433 Dashboard - Show full title when hovering an inactive dashlet
  ang/crmDashboard/InactiveDashlet.html
Labels: master, merge on pass

#23435 Translation: remove support for CiviCRM pre-4.5 l10n file locations
  CRM/Core/I18n.php
Labels: master, merge on pass

#23438 Dashboard - Sort available dashlets alphabetically, add search box
  ang/crmDashboard/Dashboard.html
  ang/crmDashboard/crmDashboard.component.js
Labels: master

#23437 SearchKit - Don't transform case for fieldsets on admin screen (more translation-friendly)
  ext/search_kit/css/crmSearchAdmin.css
Labels: master

#23409 dev/drupal#176 - Allow wider range of psr-log versions to be installed
  CRM/Core/Error/Log.php
  CRM/Utils/EchoLogger.php
  CRM/Utils/SystemLogger.php
  Civi/Api4/Action/System/RotateKey.php
  composer.json
Labels: master

#23439 Dashboard - Efficiency tweak
  ang/crmDashboard/Dashboard.html
  ang/crmDashboard/Dashlet.html
Labels: master, merge ready

#23427 [REF] [Import] Simplify if - exit loop early
  CRM/Contact/Import/Parser/Contact.php
Labels: master

#23440 (NFC) mixin/mgd-php@1 - Twiddle `@since`
  mixin/mgd-php@1/mixin.php
Labels: 5.50

#23436 SearchKit - Default to simple pager when creating new table display
  ext/search_kit/ang/crmSearchAdmin/displays/searchAdminDisplayTable.component.js
Labels: master

#23443 5.50
  mixin/mgd-php@1/mixin.php
Labels: master

#23441 [TEST ONLY] APIv4 - ensure test records are cleaned up in non-transaction tests
  tests/phpunit/api/v4/Action/AbstractActionFunctionTest.php
  tests/phpunit/api/v4/Action/GetExtraFieldsTest.php
  tests/phpunit/api/v4/Action/GetFromArrayTest.php
  tests/phpunit/api/v4/Action/IndexTest.php
  tests/phpunit/api/v4/Api4TestBase.php
  tests/phpunit/api/v4/Custom/BasicCustomFieldTest.php
  tests/phpunit/api/v4/Custom/CreateWithOptionGroupTest.php
  tests/phpunit/api/v4/Custom/CustomContactRefTest.php
  tests/phpunit/api/v4/Custom/CustomFieldAlterTest.php
  tests/phpunit/api/v4/Custom/CustomValuePerformanceTest.php
  tests/phpunit/api/v4/Custom/CustomValueTest.php
  tests/phpunit/api/v4/Custom/ExtendFromIndividualTest.php
  tests/phpunit/api/v4/Custom/PseudoconstantTest.php
  tests/phpunit/api/v4/Custom/UpdateCustomValueTest.php
  tests/phpunit/api/v4/Entity/EntityTest.php
  tests/phpunit/api/v4/Entity/ExampleDataTest.php
  tests/phpunit/api/v4/Service/Schema/SchemaMapperTest.php
  tests/phpunit/api/v4/Spec/SpecGathererTest.php
Labels: master, merge on pass

#23332 (REF) CRM_Dedupe_BAO_DedupeRule - Support third party fields and tables in rules
  CRM/Dedupe/BAO/DedupeRule.php
  tests/phpunit/CRM/Dedupe/BAO/RuleGroupTest.php
Labels: master, has-test

#23447 5.50.0 release notes initial run
  release-notes.md
  release-notes/5.50.0.md
Labels: 5.50

#23442 [REF] [Import] Parser cleanup
  CRM/Contact/Import/Form/DataSource.php
  CRM/Contact/Import/Form/MapField.php
  CRM/Contact/Import/Form/Preview.php
  CRM/Contact/Import/Form/Summary.php
  CRM/Contact/Import/Parser/Contact.php
  CRM/Import/DataSource.php
  CRM/Import/Forms.php
  CRM/Import/Parser.php
  tests/phpunit/CRM/Contact/Import/Form/data/individual_valid_with_related_email.csv
  tests/phpunit/CRM/Contact/Import/Form/data/individual_valid_with_related_no_email.csv
  tests/phpunit/CRM/Contact/Import/Parser/ContactTest.php
  tests/phpunit/CRM/Import/DataSource/CsvTest.php
Labels: master, merge ready, has-test

#23429 [REF] [Import] Parser cleanup - remove now unused
  CRM/Contact/Import/Form/Preview.php
  CRM/Contact/Import/Parser/Contact.php
Labels: master

#23448 (NFC) CRM_Utils_Hook - Typo
  CRM/Utils/Hook.php
Labels: master, merge on pass

#23450 (NFC) karma - Enable all Civi components (not just CiviCase)
  ang/crmUi.ang.php
  karma.conf.js
Labels: master

#23449 karma - Allow execution with debug_mode=1. Hide jsonFormatter.
  ang/crmUi.ang.php
  karma.conf.js
Labels: master

#23453 Remove sets for no-longer gotten vars
  CRM/Contact/Import/Form/DataSource.php
Labels: master

#23444 [REF] [Import] Minor code cleanup
  CRM/Contact/Import/Parser/Contact.php
Labels: master

#23420 Allow for custom base page in AJAX requests
  js/crm.ajax.js
  templates/CRM/common/l10n.js.tpl
  tests/karma/unit/crmMailingSpec.js
Labels: master, merge on pass

#23455 Import validate related contacts in the same way as the main contact
  CRM/Contact/Import/Parser/Contact.php
  CRM/Import/Parser.php
  tests/phpunit/CRM/Contact/Import/Form/data/individual_invalid_external_identifier_only.csv
  tests/phpunit/CRM/Contact/Import/Form/data/individual_invalid_with_related_phone.csv
  tests/phpunit/CRM/Contact/Import/Form/data/organization_email_no_organization_name.csv
  tests/phpunit/CRM/Contact/Import/Parser/ContactTest.php
Labels: master

#23424 [Import][REf] Cleanup required field checking
  CRM/Contact/Import/Parser/Contact.php
  CRM/Import/Parser.php
  tests/phpunit/CRM/Contact/Import/Form/data/individual_invalid_external_identifier_only.csv
  tests/phpunit/CRM/Contact/Import/Form/data/organization_email_no_organization_name.csv
  tests/phpunit/CRM/Contact/Import/Parser/ContactTest.php
Labels: master, has-test

#23460 dev/core#492 Fix Dedupe rule creation should display labels of contact types, in c…
  templates/CRM/Contact/Form/DedupeRules.tpl
Labels: master

#23462 [Import] [Ref] Remove unused variable
  CRM/Contact/Import/Parser/Contact.php
Labels: master

#23289 [REF] [Import] Activity - clean up copy & paste
  CRM/Activity/Import/Form/Summary.php
  CRM/Activity/Import/Parser/Activity.php
  templates/CRM/Activity/Import/Form/Summary.tpl
Labels: master

#23457 Consolidate datasource form - event import
  templates/CRM/Event/Import/Form/DataSource.tpl
Labels: master

#23463 [REF] [Import] Remove unused variable
  CRM/Contact/Import/Parser/Contact.php
Labels: master

#23459 dev/core#2300 Can not use Custom Fields defined on a contact_sub_type in dedupe…
  CRM/Dedupe/BAO/DedupeRuleGroup.php
  CRM/Dedupe/Finder.php
  tests/phpunit/CRM/Dedupe/BAO/RuleGroupTest.php
  tests/phpunit/CRM/Dedupe/DedupeFinderTest.php
Labels: master, has-test

#23464 [REF] [Import] Minor simplification
  CRM/Contact/Import/Parser/Contact.php
Labels: master

#23472 APIv4 - Respect max length for name with export action
  Civi/Api4/Generic/ExportAction.php
Labels: master

#23446 SearchKit - Pick better default for aggregate functions
  Civi/Api4/Query/SqlFunctionABS.php
  Civi/Api4/Query/SqlFunctionAVG.php
  Civi/Api4/Query/SqlFunctionBINARY.php
  Civi/Api4/Query/SqlFunctionRAND.php
  Civi/Api4/Query/SqlFunctionREPLACE.php
  Civi/Api4/Query/SqlFunctionROUND.php
  ext/search_kit/ang/crmSearchAdmin.module.js
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdmin.component.js
Labels: master

#23469 Fix Schema System Check translation and show missing Custom Field ID
  CRM/Utils/Check/Component/Schema.php
Labels: master

#23480 Remove extra question mark from url
  CRM/Utils/Check/Component/Schema.php
Labels: master, merge on pass

#23481 [NFC] First pass at 5.50 release notes
  contributor-key.yml
  release-notes/5.50.0.md
Labels: 5.50

#23452 APIv4 - Export options along with custom field
  Civi/Api4/Generic/ExportAction.php
  tests/phpunit/api/v4/Custom/ExportCustomGroupTest.php
Labels: master, has-test

#23475 [Import] Add tests for contact type & contact subtype handling
  CRM/Import/Parser.php
  tests/phpunit/CRM/Contact/Import/Parser/ContactTest.php
Labels: master

#23483 Painstaking unravelling of function
  CRM/Contact/Import/Parser/Contact.php
Labels: master, merge on pass

#23482 Remove always-true-if
  CRM/Contact/Import/Parser/Contact.php
Labels: master

#23470 [REF] [Import] Stop calling Parser in MapField mode (contact import)
  CRM/Contact/Import/Form/DataSource.php
  CRM/Contact/Import/Parser/Contact.php
Labels: master

#23461 [REF] [Import] Remove now-unused code
  CRM/Contact/Import/Form/MapField.php
  CRM/Contact/Import/ImportJob.php
  CRM/Import/ImportProcessor.php
  tests/phpunit/CRM/Contact/Import/Parser/ContactTest.php
Labels: master

#23484 Cleanup gender handling in contact import + add test
  CRM/Contact/BAO/Contact.php
  CRM/Contact/Import/Parser/Contact.php
  CRM/Import/Parser.php
  tests/phpunit/CRM/Contact/BAO/ContactTest.php
  tests/phpunit/CRM/Contact/Import/Form/data/individual_genders.csv
  tests/phpunit/CRM/Contact/Import/Parser/ContactTest.php
Labels: master, has-test

#23489 APIv4 - Filter custom fields based on supplied values
  CRM/Core/DAO/CustomGroup.php
  Civi/Api4/Service/Spec/RequestSpec.php
  Civi/Api4/Service/Spec/SpecGatherer.php
  Civi/Api4/Utils/CoreUtil.php
  tests/phpunit/api/v4/Custom/BasicCustomFieldTest.php
  tests/phpunit/api/v4/Custom/CustomFieldGetFieldsTest.php
  xml/schema/Core/CustomGroup.xml
Labels: master

#23476 [Import] Simplify checking contact type is valid
  CRM/Contact/Import/Parser/Contact.php
  tests/phpunit/CRM/Contact/Import/Parser/ContactTest.php
Labels: master, has-test

#23492 (REF) CRM_Upgrade_Form - Remove silly method `runQuery`
  CRM/Upgrade/Form.php
Labels: master, merge on pass

#23494 [Import] Remove `if (1) {` (whitespace intensive)
  CRM/Contact/Import/Parser/Contact.php
Labels: master, merge on pass

#23490 Restore `civicrm_action_schedule.limit_to` (5.49)
  CRM/Core/DAO/ActionSchedule.php
  CRM/Upgrade/Incremental/php/FiveFortyNine.php
  CRM/Upgrade/Incremental/php/FiveFortyNine/Core.bool.php
  ext/afform/admin/info.xml
  ext/afform/core/info.xml
  ext/afform/html/info.xml
  ext/afform/mock/info.xml
  ext/authx/info.xml
  ext/civicrm_admin_ui/info.xml
  ext/civigrant/info.xml
  ext/ckeditor4/info.xml
  ext/contributioncancelactions/info.xml
  ext/eventcart/info.xml
  ext/ewaysingle/info.xml
  ext/financialacls/info.xml
  ext/flexmailer/info.xml
  ext/greenwich/info.xml
  ext/legacycustomsearches/info.xml
  ext/message_admin/info.xml
  ext/oauth-client/info.xml
  ext/payflowpro/info.xml
  ext/recaptcha/info.xml
  ext/search_kit/info.xml
  ext/sequentialcreditnotes/info.xml
  sql/civicrm_generated.mysql
  sql/test_data_second_domain.mysql
  xml/schema/Core/ActionSchedule.xml
  xml/version.xml
Labels: merge on pass, 5.49

#23497 Restore `civicrm_action_schedule.limit_to` (5.50)
  CRM/Core/DAO/ActionSchedule.php
  CRM/Upgrade/Incremental/php/FiveFortyNine.php
  CRM/Upgrade/Incremental/php/FiveFortyNine/Core.bool.php
  xml/schema/Core/ActionSchedule.xml
Labels: merge on pass, 5.50

#23500 5.50 to master
  CRM/Core/DAO/ActionSchedule.php
  CRM/Upgrade/Incremental/php/FiveFortyNine.php
  CRM/Upgrade/Incremental/php/FiveFortyNine/Core.bool.php
  contributor-key.yml
  release-notes.md
  release-notes/5.50.0.md
  xml/schema/Core/ActionSchedule.xml
Labels: master

#23503 Add release-notes/5.49.2.md
  release-notes.md
  release-notes/5.49.2.md
Labels: 5.49

#23493 [Import] Remove silly param
  CRM/Contact/Import/Parser/Contact.php
Labels: master

#23495 [REF] [Import] Remove unused parameter
  CRM/Contact/Import/Parser/Contact.php
Labels: master

#23507 [REF] Remove unreachable code
  CRM/Contact/Import/Parser/Contact.php
Labels: master

#23510 fix to get around link issues in ckeditor when opening scheduled remi…
  CRM/Admin/Page/ScheduleReminders.php
Labels: master

#23501 Fix use of not-universally supported mysql field type
  CRM/Import/DataSource.php
Labels: master

#23499 (dev/core#3436) MultipleRecordFieldsListing.tpl - JS strings should us JS escaping
  templates/CRM/Profile/Page/MultipleRecordFieldsListing.tpl
Labels: merge on pass, 5.50

#23504 [Import] Remove svn whimsy - DUPLICATE_REPLACE
  CRM/Contact/Import/Form/Summary.php
  CRM/Contact/Import/Parser/Contact.php
  CRM/Import/Parser.php
Labels: master

#23512 Cleanup sql query
  CRM/Event/BAO/Event.php
Labels: master, merge on pass

#23498 Ref Extract import validation
  CRM/Contact/Import/Parser/Contact.php
  tests/phpunit/CRM/Contact/Import/Form/data/individual_dates_type1.csv
  tests/phpunit/CRM/Contact/Import/Parser/ContactTest.php
Labels: master

#23511 [Ref] [Import] Cleanup function return
  CRM/Contact/Import/Parser/Contact.php
Labels: master

#23513 (dev/core#3436) MultipleRecordFieldsListing.tpl - JS strings should us JS escaping
  templates/CRM/Profile/Page/MultipleRecordFieldsListing.tpl
Labels: 5.49

#23517 [NFC] Improve comment blocks for mapper
  CRM/Contact/Import/Parser/Contact.php
  tests/phpunit/CRM/Contact/Import/Form/MapFieldTest.php
  tests/phpunit/CRM/Contact/Import/Parser/ContactTest.php
Labels: master, merge on pass

#23518 [REF] Move list of fields that have been upgraded
  CRM/Contact/Import/Parser/Contact.php
  CRM/Import/Parser.php
Labels: master
