Repository civicrm/civicrm-core, pull requests merged in 2022-10, with the labels that each got.

#24645 (dev/core#3857) Only public custom groups should be shown in offline …
  CRM/Contribute/Form/AdditionalInfo.php
Labels: master

#24656 Bump dompdf to 2.0.1 (5.54 backport)
  composer.json
  composer.lock
Labels: merge on pass, 5.54

#24651 5.54.0 release notes initial run
  release-notes.md
  release-notes/5.54.0.md
Labels: 5.54

#24647 fix error for ended events in CRM_Event_ICalendar
  CRM/Event/BAO/Event.php
  CRM/Event/ICalendar.php
Labels: 5.54

#24655 dev/core#2535 Scheduled reminders: Add error if both absolute and relative date entered
  CRM/Admin/Form/ScheduleReminders.php
Labels: master

#24658 5.54
  CRM/Event/BAO/Event.php
  CRM/Event/ICalendar.php
  composer.json
  composer.lock
  release-notes.md
  release-notes/5.54.0.md
Labels: master

#24653 RecentItems - additional fix for inconsistent option values
  CRM/Upgrade/Incremental/sql/5.54.alpha1.mysql.tpl
Labels: 5.54

#24659 add as a contributor
  contributor-key.yml
Labels: master

#24661 Regenerate civicrm_generated
  sql/civicrm_generated.mysql
Labels: merge on pass, 5.54

#24664 5.54
  CRM/Upgrade/Incremental/sql/5.54.alpha1.mysql.tpl
  sql/civicrm_generated.mysql
Labels: master

#24663 Handle all from and to relative dates in API4
  Civi/Api4/Utils/FormattingUtil.php
  tests/phpunit/api/v4/Action/DateTest.php
Labels: master, merge on pass

#24667 prevent the get property from non-object error
  CRM/Utils/Mail/EmailProcessor.php
Labels: master

#24668 demoqueue - fix job_type parameter
  tools/extensions/org.civicrm.demoqueue/CRM/Demoqueue/Page/DemoQueue.php
Labels: master

#24564 Don't repeat email twice on the contribution confirm/thank-you pages
  CRM/Contribute/Form/ContributionBase.php
  templates/CRM/Contribute/Form/Contribution/Confirm.tpl
  templates/CRM/Contribute/Form/Contribution/ThankYou.tpl
Labels: master

#24334 Enotice & markup fixes to GeoCode, Postal blocks
  templates/CRM/Contact/Form/Edit/Address/city_postal_code.tpl
  templates/CRM/Contact/Form/Edit/Address/geo_code.tpl
Labels: master, sig:secure-smarty

#24666 .htaccess support for OpenLiteSpeed webservers.
  CRM/Utils/File.php
Labels: master

#24669 Add contributor info for release notes
  contributor-key.yml
Labels: master, merge on pass

#24673 add as a contributor
  contributor-key.yml
Labels: master

#24676 5.54 to master
  contributor-key.yml
  release-notes/5.54.0.md
Labels: master

#24677 Regen update
  sql/civicrm_generated.mysql
Labels: master

#24680 Stop using private static for tests
  Civi/Test/LocaleTestTrait.php
Labels: 5.54

#24679 5.54.0 release notes final updates
  release-notes.md
  release-notes/5.51.1.md
  release-notes/5.51.2.md
  release-notes/5.51.3.md
  release-notes/5.52.1.md
  release-notes/5.52.2.md
  release-notes/5.54.0.md
Labels: 5.54

#24682 [REF] Update Tplaner/when package to latest version
  composer.json
  composer.lock
Labels: master

#24670 Avoid confusion between contributors and contributor-key
  release-notes/CONTRIBUTORS-archive.txt
Labels: master

#24678 Crash when trying to retrieve a completed queue
  CRM/Queue/BAO/Queue.php
  tests/phpunit/CRM/Queue/QueueTest.php
Labels: master

#24598 (dev/core#3865) Fix css for price fields of html type Select with lon…
  CRM/Price/BAO/PriceField.php
Labels: master

#24687 SearchKit - Don't show custom fields from disabled field groups
  Civi/Api4/Service/Spec/SpecGatherer.php
  tests/phpunit/api/v4/Custom/CustomFieldGetFieldsTest.php
Labels: master

#24688 SearchKit - Expose 'is_current' field to the ON clause e.g. when join…
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdmin.component.js
Labels: master

#24691 Fix `testCreateWithPrimaryAndBilling`
  tests/phpunit/api/v4/Entity/ContactJoinTest.php
Labels: merge on pass, 5.54

#24686 Add icon for Country entity
  CRM/Core/DAO/Country.php
  sql/civicrm_generated.mysql
  xml/schema/Core/Country.xml
Labels: master, merge on pass

#24694 Afform - Fix console error when adding date field to form
  ext/afform/admin/ang/afGuiEditor/elements/afGuiField.component.js
Labels: master

#24690 dev/core#3892 Show each Associated Participant only once for contribution view
  CRM/Contribute/Form/ContributionView.php
Labels: master

#24695 dev/core#3829 Fix semi-recent regression on event badge
  CRM/Badge/BAO/Badge.php
  CRM/Badge/Form/Layout.php
  tests/phpunit/CRM/Event/Form/Task/BadgeTest.php
  xml/templates/civicrm_navigation.tpl
Labels: 5.55

#24700 5.55
  CRM/Badge/BAO/Badge.php
  CRM/Badge/Form/Layout.php
  tests/phpunit/CRM/Event/Form/Task/BadgeTest.php
  xml/templates/civicrm_navigation.tpl
Labels: master

#24701 civicrm_generated after #24695
  sql/civicrm_generated.mysql
Labels: 5.55

#24702 5.55
  sql/civicrm_generated.mysql
Labels: master

#24692 dev/core#3814 Use fastArray cache for extension system
  CRM/Extension/System.php
Labels: master

#24703 [REF] Update JQuery UI to 1.13.2
  composer.json
  composer.lock
Labels: merge on pass, 5.55

#24704 5.55
  composer.json
  composer.lock
Labels: master

#24696 Afform - Fix picking default value for date field
  ext/afform/admin/ang/afGuiEditor/elements/afGuiField-menu.html
Labels: master

#24710 🪥 Fix spelling mistake showHideSeletorSearch should be showHideSelectorSearch
  CRM/UF/Form/Field.php
  templates/CRM/UF/Form/Field.tpl
Labels: master, merge on pass

#24633 dev/core/#3849 Fix profile group add for events
  CRM/Event/Form/Registration/Confirm.php
Labels: master

#24684 Allow second participant registration with same email, when enabled
  CRM/Event/Form/Registration/AdditionalParticipant.php
Labels: master, merge ready

#24159 dev/core#3782 Remove rule that stops signing up for a membership if matched contact already has a cancelled on of that type
  CRM/Contribute/Form/Contribution/Main.php
  CRM/Utils/Hook.php
Labels: master, merge ready

#24708 SearchKit - Process tokens in the "Add new" button
  ext/civicrm_admin_ui/ang/afsearchAdminCustomFields.aff.html
  ext/civicrm_admin_ui/managed/SavedSearch_Administer_Custom_Fields.mgd.php
  ext/search_kit/ang/crmSearchDisplay/AddButton.html
  ext/search_kit/ang/crmSearchDisplay/traits/searchDisplayBaseTrait.service.js
  ext/search_kit/ang/crmSearchDisplayGrid/crmSearchDisplayGrid.html
  ext/search_kit/ang/crmSearchDisplayList/crmSearchDisplayList.html
  ext/search_kit/ang/crmSearchDisplayTable/crmSearchDisplayTable.html
Labels: master

#24698 Make mailing name and campaign editable in place on Find Mailings
  templates/CRM/Mailing/Page/Browse.tpl
Labels: master

#24714 Add psr0 to afform extensions
  ext/afform/admin/info.xml
  ext/afform/core/info.xml
Labels: 5.54

#24713 Add psr0 to afform extensions
  ext/afform/admin/info.xml
  ext/afform/core/info.xml
Labels: 5.55

#24711 Import summary field fix
  ext/civiimport/Managed/ImportSearches.mgd.php
Labels: 5.55

#24707 Import summary field fix
  ext/civiimport/Managed/ImportSearches.mgd.php
Labels: 5.54

#24706 [REF] Update Indian States as per ISO-3166-2
  CRM/Upgrade/Incremental/sql/5.56.alpha1.mysql.tpl
  sql/civicrm_generated.mysql
  xml/templates/civicrm_state_province.tpl
Labels: master

#24718 (dev/core#3905) Need to increase data size for 'data' column on 'civi…
  CRM/Core/DAO/JobLog.php
  CRM/Upgrade/Incremental/sql/5.56.alpha1.mysql.tpl
  xml/schema/Core/JobLog.xml
Labels: master

#24728 Use INSERT IGNORE when inserting new states on upgrade
  CRM/Upgrade/Incremental/sql/5.56.alpha1.mysql.tpl
Labels: master

#24724 APIv4 - Add titles to PCP and PCPBlock entities
  CRM/PCP/DAO/PCP.php
  CRM/PCP/DAO/PCPBlock.php
  Civi/Api4/PCP.php
  Civi/Api4/PCPBlock.php
  xml/schema/PCP/PCP.xml
  xml/schema/PCP/PCPBlock.xml
Labels: master

#24717 🩹 Fix incorrect civicrm_preferences_date description for activityDate and searchDate
  CRM/Upgrade/Incremental/sql/5.56.alpha1.mysql.tpl
  sql/civicrm_generated.mysql
  xml/templates/civicrm_data.tpl
Labels: master, merge on pass

#24723 Add APIv4 unit test for basic contact ACLs
  tests/phpunit/api/v4/Action/ContactGetTest.php
Labels: master

#24731 Regen
  sql/civicrm_generated.mysql
Labels: master, merge on pass

#24732 [REF] Fix passing null into string functions in translation BAO
  CRM/Core/BAO/Translation.php
Labels: 5.55

#24737 5.55
  CRM/Core/BAO/Translation.php
Labels: master

#24733 [REF][PHP8.1] Fix Extension Manager Module test failures on php8.1 du…
  Civi/Api4/Service/LegacySpecScanner.php
Labels: 5.55

#24741 5.55
  Civi/Api4/Service/LegacySpecScanner.php
Labels: master

#24738 [NFC] Add code comment about null locale
  CRM/Core/BAO/Translation.php
Labels: master

#24709 Migrate Relationship Type to Search kit
  CRM/Admin/Form/RelationshipType.php
  CRM/Admin/Page/RelationshipType.php
  CRM/Contact/DAO/RelationshipType.php
  CRM/Core/xml/Menu/Admin.xml
  contributor-key.yml
  ext/civicrm_admin_ui/ang/afsearchRelationshipTypes.aff.html
  ext/civicrm_admin_ui/ang/afsearchRelationshipTypes.aff.json
  ext/civicrm_admin_ui/managed/SavedSearch_Administer_Relationship_Types.mgd.php
  xml/schema/Contact/RelationshipType.xml
Labels: master

#24745 Add psr0 classloader to info.xml for core extensions
  ext/authx/info.xml
  ext/civicrm_admin_ui/info.xml
  ext/civigrant/info.xml
  ext/civiimport/info.xml
  ext/ckeditor4/info.xml
  ext/contributioncancelactions/info.xml
  ext/elavon/info.xml
  ext/eventcart/info.xml
  ext/ewaysingle/info.xml
  ext/financialacls/info.xml
  ext/greenwich/info.xml
  ext/message_admin/info.xml
  ext/payflowpro/info.xml
  ext/recaptcha/info.xml
Labels: master

#24749 dev/core#3778 Add 'Registered by Contact ID' (created_id) to civireport
  CRM/Report/Form/Event/ParticipantListing.php
Labels: master, merge ready

#24748 NFC: Fix a couple of typos in comments
  CRM/Core/ManagedEntities.php
  CRM/Member/BAO/Membership.php
Labels: master, merge on pass

#24722 AdminUI - Add SearchKit-based screen for Administer Location Types
  CRM/Admin/Form/LocationType.php
  CRM/Admin/Page/LocationType.php
  CRM/Core/DAO/LocationType.php
  CRM/Core/xml/Menu/Admin.xml
  ext/civicrm_admin_ui/ang/afsearchAdministerLocationTypes.aff.html
  ext/civicrm_admin_ui/ang/afsearchAdministerLocationTypes.aff.json
  ext/civicrm_admin_ui/managed/SavedSearch_Administer_Location_Types.mgd.php
  xml/schema/Core/LocationType.xml
Labels: master, merge on pass

#24753 [REF] Remove Reference to now moved CONTRIBUTORS.txt file blocking bu…
  distmaker/dists/common.sh
Labels: merge on pass, 5.55

#24726 Standardise names as camelcase for "SearchKit" and "FormBuilder"
  ext/afform/README.md
  ext/afform/admin/CRM/AfformAdmin/Page/Base.php
  ext/afform/admin/ang/afAdmin/afAdminList.html
  ext/afform/admin/ang/afGuiEditor/afGuiEditor.html
  ext/afform/admin/info.xml
  ext/afform/admin/managed/Navigation_afform_admin.mgd.php
  ext/afform/core/CRM/Afform/DAO/AfformSubmission.php
  ext/afform/core/CRM/Afform/Page/AfformBase.php
  ext/afform/core/afform.php
  ext/afform/core/info.xml
  ext/afform/core/xml/schema/CRM/Afform/AfformSubmission.xml
  ext/search_kit/CRM/Search/Page/Admin.php
  ext/search_kit/CRM/Search/Page/Search.php
  ext/search_kit/README.md
  ext/search_kit/ang/crmSearchAdmin/searchListing/crmSearchAdminSearchListing.component.js
  ext/search_kit/css/crmSearchDisplayGrid.css
  ext/search_kit/css/crmSearchDisplayTable.css
  ext/search_kit/info.xml
  ext/search_kit/managed/Navigation_search_kit.mgd.php
  ext/search_kit/search_kit.php
  ext/search_kit/xml/schema/CRM/Search/SearchDisplay.xml
Labels: master

#24720 Add paths in xml for FinancialType, Participant & Pledge
  CRM/Event/DAO/Participant.php
  CRM/Financial/DAO/FinancialType.php
  CRM/Pledge/DAO/Pledge.php
  xml/schema/Event/Participant.xml
  xml/schema/Financial/FinancialType.xml
  xml/schema/Pledge/Pledge.xml
Labels: master

#24754 5.55
  distmaker/dists/common.sh
Labels: master

#24756 Afform - Add eof newline to make files git-friendly
  ext/afform/core/Civi/Api4/Utils/AfformSaveTrait.php
  ext/civicrm_admin_ui/ang/afsearchAdministerLocationTypes.aff.json
Labels: master, merge on pass

#24719 dev/core#3908 Fix permissions for SubscriptionHistory in SearchKit
  Civi/Api4/SubscriptionHistory.php
  tests/phpunit/api/v4/Entity/SubscriptionHistoryTest.php
Labels: master

#24652 When running unit tests don't accidentally overwrite your db
  templates/CRM/common/civicrm.settings.php.template
Labels: master

#24413 Remove more front-end-only handling from back-office contribution form
  CRM/Contribute/Form/Contribution.php
Labels: master

#24755 SearchKit - Set button size default to `btn-xs` to match existing UI
  ext/civicrm_admin_ui/managed/SavedSearch_Administer_Contact_Types.mgd.php
  ext/civicrm_admin_ui/managed/SavedSearch_Administer_Relationship_Types.mgd.php
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdminDisplay.component.js
Labels: master

#24715 AdminUI - Add Financial Types and Assigned Financial Accounts screens
  CRM/Contribute/xml/Menu/Contribute.xml
  CRM/Financial/DAO/EntityFinancialAccount.php
  CRM/Financial/Page/FinancialType.php
  Civi/Api4/EntityFinancialAccount.php
  Civi/Api4/Service/Spec/SpecGatherer.php
  ext/civicrm_admin_ui/ang/afsearchAdminFinancialTypes.aff.html
  ext/civicrm_admin_ui/ang/afsearchAdminFinancialTypes.aff.json
  ext/civicrm_admin_ui/ang/afsearchAssignedFinancialAccounts.aff.html
  ext/civicrm_admin_ui/ang/afsearchAssignedFinancialAccounts.aff.json
  ext/civicrm_admin_ui/managed/SavedSearch_Administer_Assigned_Financial_Accounts.mgd.php
  ext/civicrm_admin_ui/managed/SavedSearch_Administer_Financial_Types.mgd.php
  ext/search_kit/Civi/Api4/Action/SearchDisplay/AbstractRunAction.php
  templates/CRM/Financial/Page/FinancialTypeAccount.tpl
  tests/phpunit/api/v4/Action/GetFieldsTest.php
  xml/schema/Financial/EntityFinancialAccount.xml
Labels: master, merge ready

#24725 Adds Profiles to civicrm_admin_ui
  CRM/Core/DAO/UFField.php
  CRM/Core/DAO/UFGroup.php
  CRM/Core/DAO/UFJoin.php
  CRM/Core/xml/Menu/Admin.xml
  CRM/UF/Form/Field.php
  CRM/UF/Form/Preview.php
  CRM/UF/Page/Field.php
  CRM/UF/Page/Group.php
  Civi/Api4/UFField.php
  Civi/Api4/UFGroup.php
  Civi/Api4/UFJoin.php
  ext/civicrm_admin_ui/ang/afsearchProfileFields.aff.html
  ext/civicrm_admin_ui/ang/afsearchProfileFields.aff.json
  ext/civicrm_admin_ui/ang/afsearchProfiles.aff.html
  ext/civicrm_admin_ui/ang/afsearchProfiles.aff.json
  ext/civicrm_admin_ui/managed/SavedSearch_Administer_ProfileFields.mgd.php
  ext/civicrm_admin_ui/managed/SavedSearch_Administer_Profiles.mgd.php
  xml/schema/Core/UFField.xml
  xml/schema/Core/UFGroup.xml
  xml/schema/Core/UFJoin.xml
Labels: master, merge ready

#24747 Add Job Entity to Api4
  Civi/Api4/Job.php
Labels: master, merge ready

#24759 AdminUI - Convert "Administer Payment Processors" to SearchKit
  CRM/Admin/Form/PaymentProcessor.php
  CRM/Admin/Page/PaymentProcessor.php
  CRM/Core/xml/Menu/Admin.xml
  CRM/Financial/DAO/PaymentProcessor.php
  Civi/Api4/PaymentProcessor.php
  Civi/Api4/Service/Spec/SpecFormatter.php
  Civi/Api4/Utils/FormattingUtil.php
  ext/civicrm_admin_ui/ang/afsearchAdministerPaymentProcessors.aff.html
  ext/civicrm_admin_ui/ang/afsearchAdministerPaymentProcessors.aff.json
  ext/civicrm_admin_ui/managed/SavedSearch_Administer_Payment_Processors.mgd.php
  templates/CRM/Admin/Page/PaymentProcessor.tpl
  tests/phpunit/api/v4/Entity/DomainTest.php
  xml/schema/Financial/PaymentProcessor.xml
Labels: master, has-test

#24757 dev/core#3917 display currency as configured on contribution page
  templates/CRM/Contribute/Form/Contribution/Confirm.tpl
  templates/CRM/Contribute/Form/Contribution/ThankYou.tpl
Labels: master

#24766 dev/core#3922 Fix fiscal year end when fiscal year starts on Jan 1.
  CRM/Utils/Date.php
Labels: master, merge on pass, has-test

#24752 Add previous before and previous 2 fiscal year options
  CRM/Upgrade/Incremental/sql/5.56.alpha1.mysql.tpl
  CRM/Upgrade/Incremental/sql/README.txt
  sql/civicrm_generated.mysql
  xml/templates/civicrm_data.tpl
Labels: master, merge on pass

#24769 dev/core#3922 - failing unit test for relative fiscal year
  CRM/Utils/Date.php
  tests/phpunit/CRM/Utils/DateTest.php
Labels: master, merge on pass, has-test

#24743 Ensure that class-index is up-to-date after toggling extensions (A)
  CRM/Extension/Manager/Module.php
  tests/phpunit/CRM/Contribute/Import/Parser/ContributionTest.php
Labels: merge on pass, 5.55

#24775 5.55 to master
  CRM/Extension/Manager/Module.php
  tests/phpunit/CRM/Contribute/Import/Parser/ContributionTest.php
Labels: master

#24771 dev/core#3702 - <af-field> tags are not valid html (ALTERNATE)
  ext/afform/core/Civi/Afform/Symbols.php
Labels: master, has-test

#24736 [REF][PHP8.1] Fix test failure on civiimport unit test because sequen…
  ext/civiimport/Civi/BAO/Import.php
Labels: merge on pass, 5.55

#24778 5.55
  ext/civiimport/Civi/BAO/Import.php
Labels: master

#24779 Event/registration PHP 8 compatibility improvements
  CRM/Core/BAO/CustomField.php
  CRM/Event/Page/ManageEvent.php
Labels: master

#23918 [NFC/Unit Test] dev/core#3702 - Failing test for af-tag
  ext/afform/core/tests/phpunit/Civi/Afform/SymbolsTest.php
Labels: master

#24773 Fix accidental revert of import batch size
  CRM/Import/Parser.php
Labels: 5.54

#24764 Fix language negotiation exception to be standard
  Civi/Core/Locale.php
Labels: 5.55

#24784 5.55
  CRM/Import/Parser.php
  Civi/Core/Locale.php
Labels: master

#24476 (REF) FileTest - Prevent test-interactions from testIsDirWithOpenBasedir
  tests/phpunit/CRM/Utils/FileTest.php
Labels: master

#24786 Fix upgrade for mariadb
  CRM/Upgrade/Incremental/sql/5.56.alpha1.mysql.tpl
Labels: master

#24790 Remove broken call to parent constructor (Issue #3932)
  CRM/Event/Import/Parser/Participant.php
Labels: 5.55

#24791 Update incremental sql readme per #24786
  CRM/Upgrade/Incremental/sql/README.txt
Labels: master, merge on pass

#24792 5.55
  CRM/Event/Import/Parser/Participant.php
Labels: master

#24491 Extensions - Limit depth of search for "info.xml"
  CRM/Admin/Form/Setting/Path.php
  CRM/Extension/Container/Basic.php
  CRM/Extension/System.php
  CRM/Upgrade/Incremental/php/FiveFiftySix.php
  CRM/Utils/File.php
  Civi/Core/SettingsManager.php
  settings/Extension.setting.php
  templates/CRM/Admin/Form/Setting/Path.tpl
  tests/phpunit/CRM/Utils/FileTest.php
Labels: master, merge ready

#24789 Use API4 to get message templates over DAO function
  CRM/Core/BAO/MessageTemplate.php
Labels: master, merge on pass

#24770 CRM_Admin_Form - Support standalone forms
  CRM/Admin/Form.php
  CRM/Admin/Form/ContactType.php
  CRM/Admin/Form/LocationType.php
  CRM/Admin/Form/PaymentProcessor.php
  CRM/Admin/Form/RelationshipType.php
  CRM/Tag/Form/Edit.php
Labels: master, merge ready

#24730 AdminUI - Add SearchKit-based screen for Administer Financial Accounts
  CRM/Contribute/xml/Menu/Contribute.xml
  CRM/Financial/DAO/FinancialAccount.php
  CRM/Financial/Page/FinancialAccount.php
  ext/civicrm_admin_ui/ang/afsearchFinancialAccounts.aff.html
  ext/civicrm_admin_ui/ang/afsearchFinancialAccounts.aff.json
  ext/civicrm_admin_ui/managed/SavedSearch_Administer_Financial_Accounts.mgd.php
  xml/schema/Financial/FinancialAccount.xml
Labels: master, merge on pass

#24788 deprecate FinancialType create/add in favor of writeRecord
  CRM/Financial/BAO/FinancialType.php
Labels: master, merge ready

#23910 allow bounce threshold to be 0 for bounces that you want to ignore like vacation auto reply
  CRM/Mailing/Event/BAO/Bounce.php
Labels: master

#24783 (REF) authx - Move listener to service class
  ext/authx/Civi/Authx/Authenticator.php
  ext/authx/Civi/Authx/LegacyRestAuthenticator.php
  ext/authx/authx.php
  ext/authx/info.xml
Labels: master

#24794 AdminUI - Fix links in Financial Accounts page
  ext/civicrm_admin_ui/ang/afsearchFinancialAccounts.aff.html
Labels: master, merge ready

#24795 AdminUi - Fix relationship screen to show names instead of labels
  ext/civicrm_admin_ui/managed/SavedSearch_Administer_Relationship_Types.mgd.php
Labels: master, merge on pass

#24797 Afform - Fix ability to add items to an empty fieldset
  ext/afform/core/CRM/Afform/ArrayHtml.php
  ext/afform/core/tests/phpunit/Civi/Afform/AfformGetTest.php
Labels: master, has-test

#24782 Contact Phone Edit: make it possible for extensions to hide the phone_ext field
  templates/CRM/Contact/Form/Edit/Phone.tpl
  templates/CRM/Contact/Form/Inline/Phone.tpl
Labels: master

#24801 Resolve Issue #3927: contact import failure of different related contact typess
  CRM/Contact/Import/Parser/Contact.php
  tests/phpunit/CRM/Contact/Import/Parser/ContactTest.php
Labels: 5.55

#24761 ClaimItems API - Optionally return the "run as" (contact ID/domain ID)
  Civi/Api4/Action/Queue/ClaimItems.php
  tests/phpunit/api/v4/Entity/QueueTest.php
Labels: master

#24806 Minor code cleanup in `Sql::claimItem`
  CRM/Queue/Queue/Sql.php
Labels: master

#24808 [REF] SearchKit - Cleanup option group mgd files and translate labels
  ext/search_kit/managed/SearchDisplayType.mgd.php
  ext/search_kit/managed/TagUsedFor.mgd.php
Labels: master, merge on pass

#24675 Afform - Ensure afField ids contain only allowed characters
  ext/afform/core/ang/af/afField.component.js
Labels: master

#24799 5.55.0 release notes initial run
  release-notes.md
  release-notes/5.55.0.md
Labels: 5.55

#24818 Add Backdrop to list of supported CMS's.
  README.md
Labels: master

#24815 [REF] Fix importing contributions with a campaign id rather than a t…
  CRM/Import/Parser.php
Labels: merge on pass, 5.55

#24817 Remove always true ifs (label code)
  CRM/Utils/Address.php
Labels: master, merge on pass

#24814 [REF] Add in Unit test to demonstrate error when trying to import a c…
  tests/phpunit/CRM/Contribute/Import/Parser/ContributionTest.php
  tests/phpunit/CRM/Contribute/Import/Parser/data/contributions.csv
Labels: merge on pass, 5.55

#24803 remove broken call to parent constructor
  CRM/Event/Import/Parser/Participant.php
Labels: 5.54

#24758 SearchKit - Add generic controller for ApiBatch action
  ext/search_kit/Civi/Api4/Action/SearchDisplay/GetSearchTasks.php
  ext/search_kit/ang/crmSearchTasks/crmSearchTaskApiBatch.ctrl.js
  ext/search_kit/ang/crmSearchTasks/crmSearchTaskApiBatch.html
  ext/search_kit/ang/crmSearchTasks/crmSearchTaskDelete.ctrl.js
  ext/search_kit/ang/crmSearchTasks/crmSearchTaskDelete.html
  ext/search_kit/ang/crmSearchTasks/crmSearchTasks.component.js
Labels: master

#24820 [NFC] Add missing space in membership search
  templates/CRM/Member/Form/Search/Common.tpl
Labels: master, merge on pass

#24793 APIv3 - Fix Case entityRef to exclude deleted cases & contacts
  CRM/Case/Form/ActivityToCase.php
  api/v3/Case.php
Labels: master

#24811 Minor code cleanup - use function to replace a few lines
  CRM/Contact/Form/Task/Label.php
  CRM/Contact/Form/Task/LabelCommon.php
Labels: master

#24805 Add runAs to import job Queue Task
  CRM/Import/Parser.php
  tests/phpunit/CRM/Contribute/Import/Parser/ContributionTest.php
  tests/phpunit/CRMTraits/Import/ParserTrait.php
Labels: master

#24823 Add organization to @bastienho
  contributor-key.yml
Labels: master

#24822 Modifying text fields to textarea to manipulate variables
  ext/search_kit/ang/crmSearchAdmin/displays/colType/field.html
  ext/search_kit/ang/crmSearchAdmin/displays/colType/html.html
  ext/search_kit/ang/crmSearchAdmin/displays/colType/image.html
Labels: master, merge on pass

#24816 Remove never-changing variable
  CRM/Utils/Address.php
  tests/phpunit/CRM/Utils/AddressTest.php
Labels: master, merge on pass

#24826 [REF] CiviGrant - Remove redundant icon from Afform entity file
  ext/civigrant/afformEntities/Grant.php
Labels: master

#24796 dev/joomla#41 [REF] Amend Joomla Bootstrapping code and hook code to …
  CRM/Utils/Hook/Joomla.php
  CRM/Utils/System/Joomla.php
Labels: master

#24813 Minor cleanup in label test, use `PrematureExitException`
  CRM/Contact/Form/Task/Label.php
  tests/phpunit/CRM/Contact/Form/Task/PrintMailingLabelTest.php
Labels: master

#24552 Afform - Add "AfformBehavior" entity & implement dedupe rules
  ext/afform/admin/Civi/Api4/Action/Afform/LoadAdminData.php
  ext/afform/admin/ang/afGuiEditor.js
  ext/afform/admin/ang/afGuiEditor/afGuiEntity.component.js
  ext/afform/admin/ang/afGuiEditor/afGuiEntity.html
  ext/afform/admin/ang/afGuiEditor/entityConfig/Contact.html
  ext/afform/admin/ang/afGuiEditor/entityConfig/Options.html
  ext/afform/core/Civi/Afform/AbstractBehavior.php
  ext/afform/core/Civi/Afform/Behavior/ContactAutofill.php
  ext/afform/core/Civi/Afform/Behavior/ContactDedupe.php
  ext/afform/core/Civi/Afform/BehaviorInterface.php
  ext/afform/core/Civi/Afform/Event/AfformEventEntityTrait.php
  ext/afform/core/Civi/Afform/Event/AfformPrefillEvent.php
  ext/afform/core/Civi/Afform/Event/AfformSubmitEvent.php
  ext/afform/core/Civi/Api4/Action/Afform/AbstractProcessor.php
  ext/afform/core/Civi/Api4/Action/AfformBehavior/Get.php
  ext/afform/core/Civi/Api4/AfformBehavior.php
  ext/afform/core/afform.php
  ext/afform/core/ang/af/afEntity.component.js
  ext/afform/core/ang/af/afForm.component.js
  ext/afform/core/info.xml
  ext/afform/core/tests/phpunit/Civi/Afform/AfformBehaviorTest.php
  ext/afform/mock/tests/phpunit/api/v4/AfformContactUsageTest.php
Labels: master, merge ready, has-test, needs-documentation

#24825 Petition Signature: add an Edit link for admins
  templates/CRM/Campaign/Form/Petition/Signature.tpl
Labels: master, merge ready

#24831 SearchKit - Show result count at top of table
  ext/search_kit/ang/crmSearchAdmin/resultsTable/crmSearchAdminResultsTable.html
  ext/search_kit/ang/crmSearchDisplay/Pager.html
  ext/search_kit/ang/crmSearchDisplay/ResultCount.html
  ext/search_kit/ang/crmSearchDisplayTable/crmSearchDisplayTable.html
Labels: master, merge ready

#24833 (REF) LocaleTestTrait- Fix error about private static
  Civi/Test/LocaleTestTrait.php
Labels: merge on pass, 5.55

#24835 5.55
  Civi/Test/LocaleTestTrait.php
Labels: master

#24827 NFC - minor Cleanup in test class
  tests/phpunit/CRM/Utils/AddressTest.php
Labels: master, merge on pass

#24776 (dev/core#3926) Need to increase data size for 'url' column on 'civic…
  CRM/Core/DAO/Website.php
  CRM/Upgrade/Incremental/sql/5.56.alpha1.mysql.tpl
  tests/phpunit/CRM/Export/BAO/ExportTest.php
  xml/schema/Core/Website.xml
Labels: master

#24774 Ensure that class-index is up-to-date after toggling extensions
  CRM/Extension/Manager.php
  CRM/Extension/Manager/Module.php
  Civi/Core/Container.php
  tests/phpunit/CRM/Contribute/Import/Parser/ContributionTest.php
Labels: 5.54

#24265 Add GroupTokens to replace WelcomeTokens
  CRM/Core/GroupTokens.php
  CRM/Mailing/Event/BAO/Confirm.php
  CRM/Mailing/Event/BAO/Subscribe.php
  Civi/Core/Container.php
  Civi/Test/ContactTestTrait.php
  tests/phpunit/CRM/Mailing/BAO/ConfirmTest.php
  tests/phpunit/CRM/Mailing/BAO/MailingJobTest.php
  tests/phpunit/CRM/Mailing/BAO/MailingTest.php
Labels: master, has-test

#24837 AdminUi - Update FinancialType paths to fix edit/delete links
  CRM/Financial/DAO/FinancialType.php
  xml/schema/Financial/FinancialType.xml
Labels: master, merge on pass

#24802 resolve import fail of diff related contact types
  CRM/Contact/Import/Parser/Contact.php
  tests/phpunit/CRM/Contact/Import/Parser/ContactTest.php
Labels: 5.54

#24840 5.54.1 - Add notes. Bump version.
  ext/afform/admin/info.xml
  ext/afform/core/info.xml
  ext/afform/html/info.xml
  ext/afform/mock/info.xml
  ext/authx/info.xml
  ext/civicrm_admin_ui/info.xml
  ext/civigrant/info.xml
  ext/civiimport/info.xml
  ext/ckeditor4/info.xml
  ext/contributioncancelactions/info.xml
  ext/elavon/info.xml
  ext/eventcart/info.xml
  ext/ewaysingle/info.xml
  ext/financialacls/info.xml
  ext/flexmailer/info.xml
  ext/greenwich/info.xml
  ext/legacycustomsearches/info.xml
  ext/message_admin/info.xml
  ext/oauth-client/info.xml
  ext/payflowpro/info.xml
  ext/recaptcha/info.xml
  ext/search_kit/info.xml
  ext/sequentialcreditnotes/info.xml
  release-notes.md
  release-notes/5.54.1.md
  sql/civicrm_generated.mysql
  sql/test_data_second_domain.mysql
  xml/version.xml
Labels: 5.54

#24836 Remove notice-causing do-nothing script
  CRM/Custom/Form/Group.php
  templates/CRM/Custom/Form/Group.tpl
Labels: master

#24847 Regenerate dao files
  CRM/Core/DAO/JobLog.php
  CRM/Core/DAO/Website.php
Labels: master, merge on pass

#24845 AdminUI - Fix pager settings to be consistent
  ext/civicrm_admin_ui/managed/SavedSearch_Administer_Assigned_Financial_Accounts.mgd.php
  ext/civicrm_admin_ui/managed/SavedSearch_Administer_Contact_Types.mgd.php
  ext/civicrm_admin_ui/managed/SavedSearch_Administer_Financial_Accounts.mgd.php
  ext/civicrm_admin_ui/managed/SavedSearch_Administer_Financial_Types.mgd.php
  ext/civicrm_admin_ui/managed/SavedSearch_Administer_Location_Types.mgd.php
  ext/civicrm_admin_ui/managed/SavedSearch_Administer_Payment_Processors.mgd.php
  ext/civicrm_admin_ui/managed/SavedSearch_Administer_ProfileFields.mgd.php
  ext/civicrm_admin_ui/managed/SavedSearch_Administer_Profiles.mgd.php
  ext/civicrm_admin_ui/managed/SavedSearch_Administer_Relationship_Types.mgd.php
Labels: master

#24828 [REF] Cleanup on CRM_Admin_Form_Options
  CRM/Admin/Form/Options.php
  templates/CRM/Admin/Form/Options.tpl
Labels: master

#24843 TypeError: call_user_func(): Argument #1 ($callback) must be a valid callback, non-static method CRM_Case_Page_AJAX::addClient() cannot be called statically
  CRM/Case/Page/AJAX.php
Labels: master

#24846 SearchKit - New setting to "Show Count in Header"
  ext/search_kit/ang/crmSearchAdmin/displays/common/searchAdminPagerConfig.html
  ext/search_kit/ang/crmSearchAdmin/displays/common/searchButtonConfig.html
  ext/search_kit/ang/crmSearchDisplay/traits/searchDisplayBaseTrait.service.js
  ext/search_kit/ang/crmSearchDisplayGrid/crmSearchDisplayGrid.html
  ext/search_kit/ang/crmSearchDisplayList/crmSearchDisplayList.html
  ext/search_kit/ang/crmSearchDisplayTable/crmSearchDisplayTable.html
Labels: master, merge ready
