Repository civicrm/civicrm-core, pull requests merged in 2022-06, with the labels that each got.

#23603 Fix createEmployerRelationship to work with the data it has when doing a lookup, test
  CRM/Contact/BAO/Contact/Utils.php
  tests/phpunit/CRM/Dedupe/MergerTest.php
  tests/phpunit/api/v3/RelationshipTest.php
Labels: master, has-test

#23644 dev/core#3482 mailing approval workflow fix
  CRM/Mailing/Form/Approve.php
Labels: 5.50

#23636 Import - ensure userID is set on parser
  CRM/Activity/Import/Form/MapField.php
  CRM/Activity/Import/Form/Preview.php
  CRM/Contact/Import/Form/DataSource.php
  CRM/Contribute/Import/Form/Preview.php
  CRM/Custom/Import/Form/Preview.php
  CRM/Event/Import/Form/Preview.php
  CRM/Import/Form/DataSource.php
Labels: master

#23654 5.50.0 release notes final
  release-notes.md
  release-notes/5.45.3.md
  release-notes/5.46.1.md
  release-notes/5.46.2.md
  release-notes/5.46.3.md
  release-notes/5.47.1.md
  release-notes/5.47.2.md
  release-notes/5.47.3.md
  release-notes/5.47.4.md
  release-notes/5.48.1.md
  release-notes/5.48.2.md
  release-notes/5.49.1.md
  release-notes/5.49.2.md
  release-notes/5.49.3.md
  release-notes/5.50.0.md
Labels: 5.50

#23647 Merge 5.50 to Master
  CRM/Mailing/Form/Approve.php
  release-notes.md
  release-notes/5.45.3.md
  release-notes/5.46.1.md
  release-notes/5.46.2.md
  release-notes/5.46.3.md
  release-notes/5.47.1.md
  release-notes/5.47.2.md
  release-notes/5.47.3.md
  release-notes/5.47.4.md
  release-notes/5.48.1.md
  release-notes/5.48.2.md
  release-notes/5.49.1.md
  release-notes/5.49.2.md
  release-notes/5.49.3.md
  release-notes/5.50.0.md
Labels: master

#23635 Simplify return from createContact
  CRM/Contact/Import/Parser/Contact.php
Labels: master, merge on pass

#23637 [Import] [Ref] [Contribution] Additional functions, typo fix
  CRM/Contribute/Import/Parser/Contribution.php
  CRM/Import/Parser.php
  templates/CRM/Contribute/Import/Form/MapField.tpl
Labels: master, merge on pass

#23588 [Import] Cleanup Contribution flow - esp with regards to soft credits
  CRM/Contribute/BAO/Contribution.php
  CRM/Contribute/Import/Form/MapField.php
  CRM/Contribute/Import/Form/Preview.php
  CRM/Contribute/Import/Parser/Contribution.php
  CRM/Import/Parser.php
  templates/CRM/Contribute/Import/Form/MapTable.tpl
  tests/phpunit/CRM/Contribute/Import/Parser/ContributionTest.php
Labels: master

#23657 [UNRELEASED REGRESSION] APIv4 - Fix GetFields to return custom fields with no sub-type
  Civi/Api4/Service/Spec/SpecGatherer.php
  tests/phpunit/api/v4/Custom/CustomFieldGetFieldsTest.php
Labels: master, has-test, sig:regression

#23616 Print report or export report if user have access report permission
  CRM/Report/Form.php
Labels: master, merge ready

#23667 (dev/core#1304) Queues - Define 'status' and 'error' columns
  CRM/Queue/BAO/Queue.php
  CRM/Queue/DAO/Queue.php
  CRM/Queue/Service.php
  CRM/Upgrade/Incremental/php/FiveFiftyOne.php
  Civi.php
  tests/phpunit/CRM/Queue/QueueTest.php
  xml/schema/Queue/Queue.xml
Labels: master

#23668 CiviGrant - Add prefix to permission label
  ext/civigrant/civigrant.php
Labels: master

#23646 [REF] Improve Get Coordinates by supporting other geocoding providers…
  CRM/Utils/GeocodeProvider.php
  Civi/Api4/Action/Address/GetCoordinates.php
  settings/Map.setting.php
  tests/phpunit/CRM/Utils/Geocode/TestProvider.php
  tests/phpunit/api/v3/AddressTest.php
  tests/phpunit/api/v4/Action/AddressGetCoordinatesTest.php
  tests/phpunit/api/v4/Entity/AddressTest.php
Labels: master, merge on pass, has-test

#23671 Fix issue #116 api3 chain check_permissions
  Civi/API/Subscriber/ChainSubscriber.php
  tests/phpunit/CRM/Utils/RestTest.php
Labels: master

#23673 APIv3 - Fix regression in handling chained calls with `sequential`
  Civi/API/Subscriber/ChainSubscriber.php
Labels: merge on pass, 5.50

#23672 APIv3 - Fix regression in handling chained calls with `sequential`
  Civi/API/Subscriber/ChainSubscriber.php
Labels: master, merge on pass

#23666 Contact Import cleanup - includes fixes to contact matchine
  CRM/Activity/Import/Form/Summary.php
  CRM/Activity/Import/Parser/Activity.php
  CRM/Contact/BAO/Contact.php
  CRM/Contact/Import/Form/MapField.php
  CRM/Contact/Import/ImportJob.php
  CRM/Contact/Import/Parser/Contact.php
  CRM/Contribute/Import/Form/Summary.php
  CRM/Contribute/Import/Parser/Contribution.php
  CRM/Custom/Import/Parser/Api.php
  CRM/Event/Import/Form/Summary.php
  CRM/Event/Import/Parser/Participant.php
  CRM/Import/Parser.php
  CRM/Member/Import/Form/Summary.php
  CRM/Member/Import/Parser/Membership.php
  tests/phpunit/CRM/Contact/Import/Form/data/individual_import_related_extid.csv
  tests/phpunit/CRM/Contact/Import/Form/data/individual_parse_failure.csv
  tests/phpunit/CRM/Contact/Import/Parser/ContactTest.php
Labels: master

#23674 [REF] Fix issue where forceing sequential broke webform API chained u…
  Civi/API/Subscriber/ChainSubscriber.php
Labels: merge on pass, 5.49

#23520 Deprecate stuff getting super deep into the BAO unformatted
  CRM/Contact/BAO/Individual.php
  tests/phpunit/CRM/Contact/BAO/ContactTest.php
Labels: master

#22762 (dev/core#1304) Queues - Allow background worker to drive tasks via APIv4
  CRM/Queue/BAO/Queue.php
  CRM/Queue/Queue.php
  CRM/Queue/Queue/BatchQueueInterface.php
  CRM/Queue/Queue/Memory.php
  CRM/Queue/Queue/Sql.php
  CRM/Queue/Queue/SqlParallel.php
  CRM/Queue/Queue/SqlTrait.php
  CRM/Queue/Runner.php
  CRM/Queue/TaskRunner.php
  CRM/Utils/Hook.php
  Civi/Api4/Action/Queue/ClaimItems.php
  Civi/Api4/Action/Queue/RunItems.php
  Civi/Api4/Queue.php
  tests/phpunit/CRM/Queue/QueueTest.php
  tests/phpunit/api/v4/Entity/QueueTest.php
Labels: master, has-test

#23675 [NFC] Failing test for api chain using sequential
  tests/phpunit/api/v3/CountryTest.php
Labels: master, merge on pass

#23681 5.49.5 - Add notes. Bump version.
  ext/afform/admin/info.xml
  ext/afform/core/info.xml
  ext/afform/html/info.xml
  ext/afform/mock/info.xml
  ext/authx/info.xml
  ext/civicrm_admin_ui/info.xml
  ext/civigrant/info.xml
  ext/ckeditor4/info.xml
  ext/contributioncancelactions/info.xml
  ext/eventcart/info.xml
  ext/ewaysingle/info.xml
  ext/financialacls/info.xml
  ext/flexmailer/info.xml
  ext/greenwich/info.xml
  ext/legacycustomsearches/info.xml
  ext/message_admin/info.xml
  ext/oauth-client/info.xml
  ext/payflowpro/info.xml
  ext/recaptcha/info.xml
  ext/search_kit/info.xml
  ext/sequentialcreditnotes/info.xml
  release-notes.md
  release-notes/5.49.5.md
  sql/civicrm_generated.mysql
  sql/test_data_second_domain.mysql
  xml/version.xml
Labels: 5.49

#23682 5.50.1 - Add notes. Bump version.
  ext/afform/admin/info.xml
  ext/afform/core/info.xml
  ext/afform/html/info.xml
  ext/afform/mock/info.xml
  ext/authx/info.xml
  ext/civicrm_admin_ui/info.xml
  ext/civigrant/info.xml
  ext/ckeditor4/info.xml
  ext/contributioncancelactions/info.xml
  ext/eventcart/info.xml
  ext/ewaysingle/info.xml
  ext/financialacls/info.xml
  ext/flexmailer/info.xml
  ext/greenwich/info.xml
  ext/legacycustomsearches/info.xml
  ext/message_admin/info.xml
  ext/oauth-client/info.xml
  ext/payflowpro/info.xml
  ext/recaptcha/info.xml
  ext/search_kit/info.xml
  ext/sequentialcreditnotes/info.xml
  release-notes.md
  release-notes/5.50.1.md
  sql/civicrm_generated.mysql
  sql/test_data_second_domain.mysql
  xml/version.xml
Labels: 5.50

#23283 [REF] Remove handling for non-existent 'savedMapping' field
  CRM/Contact/Import/Form/MapField.php
  CRM/Member/Import/Form/MapField.php
Labels: master

#23680 Contact import - extract common code, make tags & groups queue-friendly
  CRM/Contact/Import/Form/MapField.php
  CRM/Contact/Import/Form/Preview.php
  CRM/Contact/Import/Form/Summary.php
  CRM/Contact/Import/ImportJob.php
  CRM/Contact/Import/MetadataTrait.php
  CRM/Contact/Import/Parser/Contact.php
  CRM/Import/Form/MapField.php
  CRM/Import/Form/Preview.php
  CRM/Import/Forms.php
  CRM/Import/Parser.php
  templates/CRM/Contact/Import/Form/MapTable.tpl
  templates/CRM/Contact/Import/Form/Preview.tpl
  templates/CRM/Import/Form/MapTableCommon.tpl
  templates/CRM/common/highLightImport.tpl
Labels: master

#23686 dev/core#3481 - Don't translate css classes
  templates/CRM/Contact/Page/Inline/Email.tpl
Labels: master

#23685 [NFC] Mixin - update version tags and add comment for new version of mgd-php
  ext/afform/admin/info.xml
  ext/afform/core/info.xml
  ext/civicrm_admin_ui/info.xml
  ext/civigrant/info.xml
  ext/ewaysingle/info.xml
  ext/payflowpro/info.xml
  ext/search_kit/info.xml
  mixin/mgd-php@1/mixin.php
Labels: master

#23683 [Import] [Contribution] Cleanup templates & form variables, following contact pattern
  CRM/Contribute/Import/Form/MapField.php
  CRM/Contribute/Import/Form/Preview.php
  CRM/Contribute/Import/Parser/Contribution.php
  CRM/Import/Form/DataSource.php
  CRM/Import/Forms.php
  CRM/Import/Parser.php
  CRM/Upgrade/Incremental/php/FiveFiftyOne.php
  templates/CRM/Contribute/Import/Form/MapTable.tpl
  templates/CRM/Contribute/Import/Form/Preview.tpl
Labels: master, sig:regression

#23684 RelationshipCache - Set 'get' permissions
  CRM/Contact/BAO/RelationshipCache.php
  CRM/Core/Permission.php
Labels: master

#23670 SearchKit - Add "administer search_kit" permission
  Civi/Api4/Utils/CoreUtil.php
  ext/search_kit/CRM/Search/BAO/SearchDisplay.php
  ext/search_kit/CRM/Search/Upgrader.php
  ext/search_kit/Civi/Api4/Action/SearchDisplay/AbstractRunAction.php
  ext/search_kit/Civi/Api4/Action/SearchDisplay/GetDefault.php
  ext/search_kit/Civi/Api4/Event/Subscriber/SearchKitSubscriber.php
  ext/search_kit/Civi/Api4/SearchDisplay.php
  ext/search_kit/Civi/Api4/SearchSegment.php
  ext/search_kit/managed/Navigation_search_kit.mgd.php
  ext/search_kit/search_kit.php
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/SearchRunTest.php
  ext/search_kit/xml/Menu/search_kit.xml
Labels: master, merge on pass, has-test

#23690 APIv4 - Allow creator to read `UserJob` and `Queue` records
  CRM/Core/BAO/UserJob.php
  CRM/Queue/BAO/Queue.php
  Civi/Api4/Queue.php
Labels: master, merge on pass

#23696 Mailing List Subscription: remove the cancel button
  CRM/Mailing/Form/Subscribe.php
Labels: master, merge on pass

#23694 Add price set entity api4 support
  Civi/Api4/PriceSetEntity.php
Labels: master

#23693 Typo fix for Entity Id
  CRM/Price/DAO/PriceSetEntity.php
  xml/schema/Price/PriceSetEntity.xml
Labels: master

#23688 Contribution import - tests & fixes on dates, amount
  CRM/Activity/Import/Parser/Activity.php
  CRM/Contact/Import/Parser/Contact.php
  CRM/Contribute/Import/Form/MapField.php
  CRM/Contribute/Import/Parser/Contribution.php
  CRM/Custom/Import/Parser/Api.php
  CRM/Event/Import/Parser/Participant.php
  CRM/Import/Form/MapField.php
  CRM/Import/Parser.php
  CRM/Member/Import/Parser/Membership.php
  CRM/Utils/Rule.php
  api/v3/utils.php
  templates/CRM/Contribute/Import/Form/MapField.tpl
  templates/CRM/Contribute/Import/Form/MapTable.tpl
  tests/phpunit/CRM/Contribute/Import/Parser/ContributionTest.php
  tests/phpunit/CRM/Contribute/Import/Parser/data/contributions_amount_validate.csv
  tests/phpunit/CRM/Contribute/Import/Parser/data/contributions_date_validate.csv
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: master, has-test

#23691 Add not-yet-used function to allow the import to run in static (queue) context
  CRM/Activity/Import/Form/DataSource.php
  CRM/Contact/Import/Form/DataSource.php
  CRM/Contribute/Import/Form/DataSource.php
  CRM/Core/BAO/UserJob.php
  CRM/Custom/Import/Form/DataSource.php
  CRM/Event/Import/Form/DataSource.php
  CRM/Import/Forms.php
  CRM/Import/Parser.php
  CRM/Member/Import/Form/DataSource.php
Labels: master

#23687 Afform - Add 'administer afform' permission
  ext/afform/admin/CRM/AfformAdmin/Upgrader.php
  ext/afform/admin/ang/afAdminFormSubmissionList.aff.json
  ext/afform/admin/managed/Navigation_afform_admin.mgd.php
  ext/afform/admin/xml/Menu/afform_admin.xml
  ext/afform/core/Civi/Api4/Afform.php
  ext/afform/core/Civi/Api4/AfformSubmission.php
  ext/afform/core/afform.php
  ext/search_kit/ang/crmSearchAdmin.ang.php
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdmin.component.js
  ext/search_kit/ang/crmSearchAdmin/searchListing/crmSearchAdminSearchListing.component.js
Labels: master

#23698 [NFC] Fix Since version in Price Set Entity APIv4
  Civi/Api4/PriceSetEntity.php
Labels: master, merge on pass

#23669 Use UI Queue runner for import
  CRM/Contact/Import/Form/Preview.php
  CRM/Contact/Import/Form/Summary.php
  CRM/Contact/Import/Parser/Contact.php
  CRM/Core/xml/Menu/Import.xml
  CRM/Import/Parser.php
  templates/CRM/Contact/Import/Form/Preview.tpl
  tests/phpunit/CRM/Contact/Import/Parser/ContactTest.php
Labels: master, merge on pass

#23648 Afform - Add undo/redo buttons to the Admin UI
  ext/afform/admin/ang/afGuiEditor.css
  ext/afform/admin/ang/afGuiEditor/afGuiEditor.component.js
  ext/afform/admin/ang/afGuiEditor/afGuiEditorCanvas.html
  ext/afform/admin/ang/afGuiEditor/config-form.html
  ext/afform/admin/ang/afGuiEditor/inputType/ChainSelect.html
  ext/afform/admin/ang/afGuiEditor/inputType/Date.html
  ext/afform/admin/ang/afGuiEditor/inputType/EntityRef.html
  ext/afform/admin/ang/afGuiEditor/inputType/Number.html
  ext/afform/admin/ang/afGuiEditor/inputType/Select.html
  ext/afform/admin/ang/afGuiEditor/inputType/Text.html
  js/crm.menubar.js
Labels: master

#23689 [Import] [Membership] Cleanup, fix form breakage (unreleased regression)
  CRM/Contact/Import/Form/Summary.php
  CRM/Contact/Import/Parser/Contact.php
  CRM/Import/Form/DataSource.php
  CRM/Import/Form/MapField.php
  CRM/Import/Form/Preview.php
  CRM/Import/Form/Summary.php
  CRM/Import/Parser.php
  CRM/Member/Import/Form/MapField.php
  CRM/Member/Import/Form/Preview.php
  CRM/Member/Import/Form/Summary.php
  CRM/Member/Import/Parser/Membership.php
  CRM/Upgrade/Incremental/php/FiveFiftyOne.php
  templates/CRM/Member/Import/Form/MapField.tpl
  templates/CRM/Member/Import/Form/Preview.tpl
  tests/phpunit/CRM/Member/Import/Parser/MembershipTest.php
  tests/phpunit/CRM/Member/Import/Parser/data/memberships.csv
  tests/phpunit/CRM/Member/Import/Parser/data/memberships_invalid.csv
  tests/phpunit/CRM/Member/Import/Parser/data/memberships_update_custom_date.csv
  tests/phpunit/CRM/Member/Import/Parser/data/memberships_valid.csv
  tests/phpunit/CRM/Member/Import/Parser/data/memberships_valid.tsv
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: master, has-test, sig:regression

#23702 SearchKit - Make loading placeholders configurable
  ext/search_kit/Civi/Api4/Action/SearchDisplay/GetDefault.php
  ext/search_kit/ang/crmSearchAdmin/displays/common/searchAdminPlaceholderConfig.component.js
  ext/search_kit/ang/crmSearchAdmin/displays/common/searchAdminPlaceholderConfig.html
  ext/search_kit/ang/crmSearchAdmin/displays/searchAdminDisplayGrid.html
  ext/search_kit/ang/crmSearchAdmin/displays/searchAdminDisplayList.html
  ext/search_kit/ang/crmSearchAdmin/displays/searchAdminDisplayTable.html
  ext/search_kit/ang/crmSearchDisplay/traits/searchDisplayBaseTrait.service.js
  ext/search_kit/ang/crmSearchDisplayGrid/crmSearchDisplayGridLoading.html
  ext/search_kit/ang/crmSearchDisplayList/crmSearchDisplayListLoading.html
  ext/search_kit/ang/crmSearchDisplayTable/crmSearchDisplayTableLoading.html
  ext/search_kit/css/crmSearchDisplay.css
Labels: master

#23700 Make try-catch more catchy
  CRM/Contribute/Import/Parser/Contribution.php
Labels: master

#23701 Remove unused properties
  CRM/Contribute/Import/Form/MapField.php
Labels: master

#23692 Import - make tracking fields import-specific
  CRM/Activity/Import/Parser/Activity.php
  CRM/Contact/Import/Parser/Contact.php
  CRM/Import/DataSource.php
  CRM/Import/Parser.php
  CRM/Member/Import/Parser/Membership.php
  tests/phpunit/CRM/Activity/Import/Parser/ActivityTest.php
  tests/phpunit/CRM/Contact/Import/Form/data/individual_invalid_external_identifier_email_mismatch.csv
  tests/phpunit/CRM/Contact/Import/Form/data/organization_multiple_duplicates_invalid.csv
  tests/phpunit/CRM/Contact/Import/Parser/ContactTest.php
Labels: master, merge on pass, has-test

#23708 dev/core#2325 Fix handling of seconds on import
  CRM/Utils/Date.php
Labels: master

#23620 dev/backdrop#8 - Move session start into CMS-specific classes.
  CRM/Utils/System.php
  CRM/Utils/System/Drupal.php
  CRM/Utils/System/Drupal8.php
  CRM/Utils/System/Joomla.php
  CRM/Utils/System/Soap.php
  CRM/Utils/System/WordPress.php
Labels: master, merge ready

#23710 Minor simplification - use `$self->getContactType(),`
  CRM/Contribute/Import/Form/MapField.php
Labels: master

#23704 Expand try-catch to whole function
  CRM/Custom/Import/Parser/Api.php
Labels: master

#23713 PHP8.1 - Fix deprecated passing null to glob
  CRM/Core/Resources.php
Labels: master

#23703 Fix Participant import, add tests
  CRM/Event/BAO/Participant.php
  CRM/Event/Import/Form/MapField.php
  CRM/Event/Import/Form/Preview.php
  CRM/Event/Import/Form/Summary.php
  CRM/Event/Import/Parser/Participant.php
  CRM/Import/Form/MapField.php
  CRM/Import/Parser.php
  CRM/Upgrade/Incremental/php/FiveFiftyOne.php
  templates/CRM/Contact/Import/Form/DataSource.hlp
  templates/CRM/Event/Import/Form/MapField.tpl
  templates/CRM/Event/Import/Form/Preview.tpl
  templates/CRM/Import/Form/DataSource.tpl
  tests/phpunit/CRM/Event/Import/Parser/ParticipantTest.php
  tests/phpunit/CRM/Event/Import/Parser/data/participant.csv
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: master, merge on pass, has-test

#23711 Queue - When UserJob has no more tasks, update status & fire hook
  CRM/Core/BAO/UserJob.php
  CRM/Queue/Queue.php
  CRM/Queue/Runner.php
  CRM/Utils/Hook.php
  Civi/Api4/Action/Queue/RunItems.php
  tests/phpunit/CRM/Queue/QueueTest.php
  tests/phpunit/api/v4/Entity/QueueTest.php
  tools/extensions/org.civicrm.demoqueue/CRM/Demoqueue/Page/DemoQueue.php
Labels: master, has-test

#23707 Fix import activity & add tests
  CRM/Activity/Import/Form/MapField.php
  CRM/Activity/Import/Form/Preview.php
  CRM/Activity/Import/Form/Summary.php
  CRM/Activity/Import/Parser/Activity.php
  CRM/Event/Import/Form/MapField.php
  CRM/Import/Form/MapField.php
  CRM/Import/Form/Summary.php
  CRM/Member/Import/Form/MapField.php
  CRM/Upgrade/Incremental/php/FiveFiftyOne.php
  templates/CRM/Activity/Import/Form/MapField.tpl
  templates/CRM/Activity/Import/Form/Preview.tpl
  templates/CRM/Import/Form/MapField.tpl
  tests/phpunit/CRM/Activity/Import/Parser/ActivityTest.php
  tests/phpunit/CRM/Activity/Import/Parser/data/activity.csv
  tests/phpunit/CRM/Event/Import/Parser/ParticipantTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: master, merge on pass, has-test

#23714 Contribution import - simplify error handling
  CRM/Contribute/Import/Parser/Contribution.php
  tests/phpunit/CRM/Contribute/Import/Parser/ContributionTest.php
Labels: master

#23709 Trivial extraction - addFormButtons shared code
  CRM/Activity/Import/Form/MapField.php
  CRM/Contact/Import/Form/MapField.php
  CRM/Contribute/Import/Form/MapField.php
  CRM/Event/Import/Form/MapField.php
  CRM/Import/Form/MapField.php
  CRM/Member/Import/Form/MapField.php
Labels: master

#23716 (dev/core#3496) Missing extension leads to bootstrap error for "hook_civicrm_entityTypes"
  CRM/Extension/Manager.php
Labels: merge on pass, sig:regression, 5.50

#23718 (dev/core#3496) Missing extension leads to bootstrap error for "hook_civicrm_entityTypes"
  CRM/Extension/Manager.php
Labels: master, merge on pass

#23717 Fix Contribution import with pledge handling, add test
  CRM/Contribute/Import/Form/MapField.php
  CRM/Contribute/Import/Form/Preview.php
  CRM/Contribute/Import/Form/Summary.php
  CRM/Contribute/Import/Parser/Contribution.php
  CRM/Import/DataSource.php
  CRM/Import/Form/Summary.php
  CRM/Import/Parser.php
  tests/phpunit/CRM/Contribute/Import/Parser/ContributionTest.php
  tests/phpunit/CRM/Contribute/Import/Parser/data/.~lock.pledge.csv#
  tests/phpunit/CRM/Contribute/Import/Parser/data/contributions_amount_validate.csv.error.log
  tests/phpunit/CRM/Contribute/Import/Parser/data/pledge.csv
  tests/phpunit/CRM/Contribute/Import/Parser/data/pledge.csv.error.log
Labels: master, merge on pass

#23715 Remove a couple of non-test tests - syntax conformance
  tests/phpunit/api/v3/SyntaxConformanceTest.php
Labels: master

#23645 Enable ability to require tags in profiles
  CRM/Contact/Form/Edit/TagsAndGroups.php
  tests/phpunit/CRM/Profile/Form/EditTest.php
Labels: master, merge on pass, has-test

#23726 Added back 'Renewal Message' field on Membership renewal form
  templates/CRM/Member/Form/MembershipRenewal.tpl
Labels: master

#23719 Fix custom import to work again (broke in master)
  CRM/Contribute/Import/Form/Summary.php
  CRM/Custom/Import/Form/DataSource.php
  CRM/Custom/Import/Form/MapField.php
  CRM/Custom/Import/Form/Preview.php
  CRM/Custom/Import/Form/Summary.php
  CRM/Custom/Import/Parser/Api.php
  CRM/Event/Import/Form/MapField.php
  CRM/Import/Form/DataSource.php
  CRM/Import/Form/MapField.php
  CRM/Import/Forms.php
  CRM/Import/Parser.php
  templates/CRM/Custom/Import/Form/MapField.tpl
Labels: master, merge on pass

#23727 [NFC] Remove weird test data file
  tests/phpunit/CRM/Contribute/Import/Parser/data/.~lock.pledge.csv#
Labels: master

#23730 Issue #3483: parent_id not always available as index
  CRM/Note/Form/Note.php
Labels: master, merge on pass

#23733 Participant import fix - broken uniqueName fields, mapping saving, ev…
  CRM/Event/BAO/Participant.php
  CRM/Event/Import/Form/DataSource.php
  CRM/Event/Import/Form/MapField.php
  CRM/Event/Import/Form/Preview.php
  CRM/Event/Import/Parser/Participant.php
  CRM/Import/Form/MapField.php
  CRM/Import/Forms.php
  CRM/Import/Parser.php
  CRM/Upgrade/Incremental/php/FiveFiftyOne.php
  tests/phpunit/CRM/Event/Import/Parser/ParticipantTest.php
Labels: master, merge on pass, has-test

#23656 Afform - allow ids to be passed directly into the directive
  ext/afform/core/ang/af/afForm.component.js
Labels: master

#23735 Afform - Trigger 'crmFormSuccess' event after submission
  ext/afform/core/ang/af/afForm.component.js
Labels: master, merge on pass

#23734 Fix test to validate forms & remove some unused code
  .toxic.json
  CRM/Contribute/Import/Form/DataSource.php
  CRM/Contribute/Import/Form/MapField.php
  CRM/Contribute/Import/Form/Preview.php
  CRM/Contribute/Import/Parser/Contribution.php
  CRM/Export/BAO/Export.php
  CRM/Import/Forms.php
  tests/phpunit/CRM/Contribute/Import/Parser/ContributionTest.php
  tests/phpunit/CRMTraits/Import/ParserTrait.php
Labels: master, merge on pass

#23712 Enable QueueRunner for all imports
  CRM/Contact/Import/Form/Preview.php
  CRM/Contact/Import/Form/Summary.php
  CRM/Import/Form/Preview.php
  CRM/Member/Import/Form/MapField.php
  CRM/Member/Import/Form/Summary.php
  templates/CRM/Member/Import/Form/Preview.tpl
  templates/CRM/Member/Import/Form/Summary.tpl
  tests/phpunit/CRM/Activity/Import/Parser/ActivityTest.php
  tests/phpunit/CRM/Member/Import/Parser/MembershipTest.php
  tests/phpunit/CRMTraits/Import/ParserTrait.php
Labels: master

#23737 Add upgrade for label to name conversion in `civicrm_mapping_field` for multiple custom imports
  CRM/Upgrade/Incremental/php/FiveFiftyOne.php
Labels: master

#23740 Remove unused functions
  .toxic.json
  CRM/Contact/Import/Parser/Contact.php
Labels: master

#23742 Remove more obsolete import code
  CRM/Import/Parser.php
  CRM/Member/Import/Form/DataSource.php
  CRM/Member/Import/Parser/Membership.php
  tests/phpunit/CRM/Activity/Import/Parser/ActivityTest.php
Labels: master, merge on pass

#23743 CRM_Queue_Task - Track an optional `$runAs` property
  CRM/Queue/Task.php
Labels: master, merge on pass

#23744 Fix unrelease regression - malformed MapField without skipColumnHeaders
  CRM/Import/DataSource/CSV.php
  CRM/Import/Form/Preview.php
  CRM/Import/Forms.php
  templates/CRM/Import/Form/MapTableCommon.tpl
  templates/CRM/Member/Import/Form/MapField.tpl
Labels: master, merge on pass

#23679 Civi::queue() - Add support for 'template' queues
  CRM/Core/DAO/UserJob.php
  CRM/Queue/DAO/Queue.php
  CRM/Queue/Service.php
  CRM/Upgrade/Incremental/php/FiveFiftyOne.php
  tests/phpunit/CRM/Queue/QueueTest.php
  xml/schema/Core/UserJob.xml
  xml/schema/Queue/Queue.xml
Labels: master, merge on pass

#23746 CRM_Queue_Runner - Add basic/skeletal support for `runAllInteractively()`
  CRM/Admin/Form/Setting/Miscellaneous.php
  CRM/Queue/Menu.php
  CRM/Queue/Page/Monitor.php
  CRM/Queue/Runner.php
  Civi/Angular/Manager.php
  ang/crmQueueMonitor.ang.php
  ang/crmQueueMonitor.js
  settings/Core.setting.php
  templates/CRM/Admin/Form/Setting/Miscellaneous.tpl
  templates/CRM/Queue/Page/Monitor.tpl
  tools/extensions/org.civicrm.demoqueue/CRM/Demoqueue/Page/DemoQueue.php
Labels: master

#23751 Fix for failing test in master
  CRM/Member/Import/Parser/Membership.php
  tests/phpunit/CRM/Member/Import/Parser/MembershipTest.php
Labels: master

#23729 Added back 'Renewal Message' field on Membership renewal form
  templates/CRM/Member/Form/MembershipRenewal.tpl
Labels: 5.50

#23748 Update guzzle to 6.5.7
  composer.lock
Labels: master

#23750 Reduce test output spam
  tests/phpunit/api/v3/JobTest.php
Labels: master, merge on pass

#23747 Remove some more unused code
  CRM/Contribute/Import/Parser/Contribution.php
  templates/CRM/Contribute/Import/Form/Preview.tpl
Labels: master

#23738 Remove another no-run test from SyntaxConformance
  tests/phpunit/api/v3/SyntaxConformanceTest.php
Labels: master

#23755 dev/core#3505, dev/core#3506 dev/core#3052 Import fixes for unicode url, Côte d’Ivoire
  CRM/Import/Parser.php
  CRM/Utils/Rule.php
  tests/phpunit/CRM/Contact/Import/Form/data/individual_unicode.csv
  tests/phpunit/CRM/Contact/Import/Parser/ContactTest.php
Labels: has-test, 5.51

#23756 dev/core#3160 fix inability to import 'just contactid' and add to group
  CRM/Contact/Import/Parser/Contact.php
  CRM/Import/Parser.php
  tests/phpunit/CRM/Contact/Import/Form/data/contact_id_only.csv
  tests/phpunit/CRM/Contact/Import/Parser/ContactTest.php
Labels: has-test, 5.51

#23615 dev/core#1681 - Update requirements to MySQL 5.7+ and MariaDB 10.2+
  CRM/Upgrade/Form.php
  CRM/Upgrade/Incremental/General.php
  CRM/Utils/Check/Component/Env.php
Labels: master

#23471 Exceptions - What could possibly go wrong?
  CRM/Core/Exception.php
  Civi/API/Kernel.php
  api/Exception.php
Labels: master, merge ready

#23762 5.51 to master
  CRM/Contact/Import/Parser/Contact.php
  CRM/Import/Parser.php
  CRM/Utils/Rule.php
  tests/phpunit/CRM/Contact/Import/Form/data/contact_id_only.csv
  tests/phpunit/CRM/Contact/Import/Form/data/individual_unicode.csv
  tests/phpunit/CRM/Contact/Import/Parser/ContactTest.php
Labels: master

#23761 dev/core#3512 fix rc fatal error when state is invalid
  CRM/Contact/Import/Parser/Contact.php
  tests/phpunit/CRM/Contact/Import/Form/data/individual_country_state_county_with_related.csv
Labels: 5.51

#23760 dev/core#3511 Improve handling of invalid saved mapping fields
  CRM/Import/ImportProcessor.php
Labels: 5.51

#23758 Setup - Remove CiviGrant from available components
  setup/plugins/blocks/components.civi-setup.php
  setup/plugins/init/AvailableComponents.civi-setup.php
Labels: merge ready, 5.51

#23765 Catch & convert Guzzle exception
  CRM/Extension/Browser.php
Labels: 5.51

#21809 dev/drupal#167 - Deprecated service to be removed in Drupal 10
  setup/src/Setup/DrupalUtil.php
Labels: master

#23754 dev/core#2325 import second-handling fix
  CRM/Import/Parser.php
  CRM/Utils/Date.php
  tests/phpunit/CRM/Utils/DateTest.php
Labels: has-test, 5.51

#23759 [REGRESSION] SearchKit - Fix angular console error when totalCount is not given
  ext/search_kit/ang/crmSearchDisplayTable/crmSearchDisplayTable.component.js
Labels: sig:regression, 5.51

#23769 5.51
  CRM/Contact/Import/Parser/Contact.php
  CRM/Extension/Browser.php
  CRM/Import/ImportProcessor.php
  CRM/Import/Parser.php
  CRM/Utils/Date.php
  ext/search_kit/ang/crmSearchDisplayTable/crmSearchDisplayTable.component.js
  setup/plugins/blocks/components.civi-setup.php
  setup/plugins/init/AvailableComponents.civi-setup.php
  tests/phpunit/CRM/Contact/Import/Form/data/individual_country_state_county_with_related.csv
  tests/phpunit/CRM/Utils/DateTest.php
Labels: master

#23757 Deduepe - Fix form buttons (again)
  CRM/Contact/Form/Merge.php
Labels: sig:regression, 5.51

#23772 Fix import regression - contribution import borks on do_not_import
  CRM/Contribute/Import/Form/MapField.php
  CRM/Contribute/Import/Parser/Contribution.php
Labels: 5.51

#23773 5.51 to master
  CRM/Contact/Form/Merge.php
  CRM/Contribute/Import/Form/MapField.php
  CRM/Contribute/Import/Parser/Contribution.php
Labels: master

#23775 dev/core#3653 Fix on queue runner not working in upgrade
  CRM/Queue/Runner.php
Labels: 5.51

#23778 5.51
  CRM/Queue/Runner.php
Labels: master

#23777 fix disableUSPS since import running in separate context of Queue.
  CRM/Contact/Import/Form/DataSource.php
  CRM/Contact/Import/Form/Preview.php
  CRM/Contact/Import/Parser/Contact.php
  templates/CRM/Contact/Import/Form/DataSource.tpl
  tests/phpunit/CRM/Contact/Import/Parser/ContactTest.php
Labels: 5.51

#23766 dev/core#3513 Remove 'done' from sumary/import monitoring page
  CRM/Import/Form/Summary.php
  templates/CRM/Contact/Import/Form/Summary.tpl
Labels: merge ready, 5.51

#23776 (dev/core#2198) Switch to more maintained phpQuery
  composer.json
  composer.lock
Labels: master, merge ready

#23780 (dev/core#3653) CRM_Queue_Runner - Fix upgrade warnings. Extract disableBackgroundExecution().
  CRM/Queue/Runner.php
Labels: 5.51

#23771 dev/core#3651 dev/core#1337 Fix failure to show last column data in output, spaces in names
  CRM/Import/DataSource.php
  CRM/Import/DataSource/CSV.php
  CRM/Import/DataSource/SQL.php
  CRM/Import/Forms.php
Labels: merge ready, 5.51

#23781 5.51 to master
  CRM/Contact/Import/Form/DataSource.php
  CRM/Contact/Import/Form/Preview.php
  CRM/Contact/Import/Parser/Contact.php
  CRM/Import/DataSource.php
  CRM/Import/DataSource/CSV.php
  CRM/Import/DataSource/SQL.php
  CRM/Import/Form/Summary.php
  CRM/Import/Forms.php
  CRM/Queue/Runner.php
  templates/CRM/Contact/Import/Form/DataSource.tpl
  templates/CRM/Contact/Import/Form/Summary.tpl
  tests/phpunit/CRM/Contact/Import/Parser/ContactTest.php
Labels: master

#23783 FiveFiftyOne - Enable snapshots for data modified data
  CRM/Upgrade/Incremental/php/FiveFiftyOne.php
Labels: 5.51

#23786 dev/financial#199 Fix additional details on edit template contribution
  CRM/Contribute/Form/Contribution.php
Labels: merge on pass, 5.51

#23791 NFC: Fix PHP notice on ContributionRecurSelector.tpl
  CRM/Contribute/Page/Tab.php
  templates/CRM/Contribute/Form/Selector.tpl
Labels: master

#23788 only check batch currency match when adding a financial_trxn
  CRM/Batch/BAO/EntityBatch.php
Labels: 5.51

#23749 AngularJS - Remove UI-Utils library
  Civi/Angular/Manager.php
  ang/crmCaseType.ang.php
  ang/crmCaseType.js
  ang/crmCaseType/edit.html
  ang/crmCaseType/timelineTable.html
  ang/crmCxn.ang.php
  ang/crmMailing.ang.php
  ang/crmMailing/BlockHeaderFooter.html
  ang/crmMailing/BlockPublication.html
  ang/crmMailing/BlockResponses.html
  ang/crmMailingAB.ang.php
  ang/crmUi.ang.php
  ang/crmUi.js
  ang/crmUi/tabset.html
  ang/ui.utils.ang.php
  composer.json
  tests/phpunit/Civi/Angular/ManagerTest.php
Labels: master, merge on pass

#23764 dev/core#2706 dev/core#2308 fix activity import to update multi-select fields
  CRM/Activity/Import/Form/MapField.php
  CRM/Activity/Import/Parser/Activity.php
Labels: 5.51

#23763 Fix target contact label back to include target
  CRM/Activity/Import/Parser/Activity.php
Labels: 5.51

#23753 Add integer validation to import
  CRM/Import/Parser.php
Labels: 5.51

#23784 Update to guzzle 6.5.7 (5.50)
  composer.lock
Labels: 5.50

#23787 only check batch currency match when adding a financial_trxn
  CRM/Batch/BAO/EntityBatch.php
Labels: 5.50

#23739 dev/core#3502 - CiviEventDispatcher - Softer errors for `not-ready`. More comments.
  Civi/Core/CiviEventDispatcher.php
Labels: 5.50

#23785 dev/core#3502 - CiviEventDispatcher - Softer errors for not-ready. More comments.
  Civi/Core/CiviEventDispatcher.php
Labels: 5.51

#23794 5.50.2 - Add notes. Bump version.
  ext/afform/admin/info.xml
  ext/afform/core/info.xml
  ext/afform/html/info.xml
  ext/afform/mock/info.xml
  ext/authx/info.xml
  ext/civicrm_admin_ui/info.xml
  ext/civigrant/info.xml
  ext/ckeditor4/info.xml
  ext/contributioncancelactions/info.xml
  ext/eventcart/info.xml
  ext/ewaysingle/info.xml
  ext/financialacls/info.xml
  ext/flexmailer/info.xml
  ext/greenwich/info.xml
  ext/legacycustomsearches/info.xml
  ext/message_admin/info.xml
  ext/oauth-client/info.xml
  ext/payflowpro/info.xml
  ext/recaptcha/info.xml
  ext/search_kit/info.xml
  ext/sequentialcreditnotes/info.xml
  release-notes.md
  release-notes/5.50.2.md
  sql/civicrm_generated.mysql
  sql/test_data_second_domain.mysql
  xml/version.xml
Labels: 5.50

#23774 dev/financial#199 - Add failing test to demonstrate the problem
  tests/phpunit/CRM/Contribute/Form/UpdateSubscriptionTest.php
  tests/phpunit/CRMTraits/Contribute/RecurFormsTrait.php
Labels: master, merge on pass

#23797 [REF] Remove param that has a set value
  CRM/Contribute/Form/Contribution/Confirm.php
Labels: master, merge on pass

#23803 (NFC) Release Notes - Fix typo in version of Guzzle
  release-notes/5.50.2.md
Labels: 5.50

#23798 Fix Automatic renewal membership from front end contribution forms
  CRM/Contribute/Form/ContributionBase.php
  tests/phpunit/CRM/Contribute/Form/Contribution/MainTest.php
Labels: merge ready, sig:regression, 5.51

#23790 Add hook to modify 'contribution payment links'
  CRM/Contribute/BAO/Contribution.php
Labels: master

#23723 Allow UFMatch to be used in SearchKit - this allows you to filter by eg. 'has a CMS account'
  CRM/Core/DAO/UFMatch.php
  Civi/Api4/UFMatch.php
  xml/schema/Core/UFMatch.xml
Labels: master, merge on pass

#23768 dev/core#3542 Store extdir cache in sqlcache rather than the filesystem
  CRM/Extension/Browser.php
  CRM/Extension/System.php
  Civi/Core/Container.php
  tests/phpunit/CRM/Extension/BrowserTest.php
Labels: master, merge ready

#23801 Fix breakage in message preview on workflow contributions
  CRM/Contribute/WorkflowMessage/Contribution/BasicContribution.ex.php
  CRM/Contribute/WorkflowMessage/ContributionTrait.php
  CRM/Financial/BAO/Order.php
Labels: 5.51

#23814 5.51 to master
  CRM/Contribute/Form/ContributionBase.php
  CRM/Contribute/Form/UpdateSubscription.php
  CRM/Contribute/WorkflowMessage/Contribution/BasicContribution.ex.php
  CRM/Contribute/WorkflowMessage/ContributionTrait.php
  CRM/Financial/BAO/Order.php
  Civi/Core/CiviEventDispatcher.php
  tests/phpunit/CRM/Contribute/Form/Contribution/MainTest.php
Labels: master

#23810 message_admin - Enable another preview mode ("HTML (Raw)")
  ext/message_admin/ang/crmMsgadm/Edit.js
  ext/message_admin/ang/crmMsgadm/Preview.html
Labels: master, merge on pass

#23811 (REF) WorkflowMessageTest - Use dataProvider
  tests/phpunit/api/v4/Entity/WorkflowMessageTest.php
Labels: master, merge on pass

#23813 (REF) TokenProcessor - Tweak error message
  Civi/Token/TokenProcessor.php
Labels: master, merge on pass

#23697 dev/core#3495 - Fix fields with wildcards in Advanced Search
  CRM/Contact/BAO/Query.php
  CRM/Core/Form/Search.php
Labels: master

#23806 Invoice Workflow template - add domain tokens
  CRM/Contribute/Form/Task/Invoice.php
  CRM/Core/DomainTokens.php
  sql/civicrm_generated.mysql
  tests/phpunit/CRM/Contribute/Form/Task/InvoiceTest.php
  tests/phpunit/CRM/Utils/TokenConsistencyTest.php
  xml/templates/message_templates/contribution_invoice_receipt_html.tpl
Labels: master, merge on pass

#23815 [REF] Fix second output in customFormat function and extend unit test
  CRM/Utils/Date.php
  tests/phpunit/CRM/Utils/DateTest.php
Labels: merge on pass, 5.51

#23817 5.51 to master
  CRM/Utils/Date.php
  tests/phpunit/CRM/Utils/DateTest.php
Labels: master

#23419 Add crmRegions to contact headers and associated inline forms
  templates/CRM/Contact/Form/Edit/Household.tpl
  templates/CRM/Contact/Form/Edit/Individual.tpl
  templates/CRM/Contact/Form/Edit/Organization.tpl
  templates/CRM/Contact/Form/Inline/ContactName.tpl
  templates/CRM/Contact/Page/Inline/ContactName.tpl
Labels: master

#23800 [REF] [PHP8.1] Replace usage of smarty's date_filter to ensure we don't call s…
  CRM/Core/Smarty/plugins/modifier.crmDate.php
  CRM/Utils/Date.php
  templates/CRM/Activity/Calendar/ICal.tpl
  templates/CRM/Contribute/Form/Contribution/Main.tpl
  templates/CRM/Contribute/Form/Contribution/MembershipBlock.tpl
  templates/CRM/Core/Calendar/ICal.tpl
  templates/CRM/Core/Calendar/Rss.tpl
  templates/CRM/Event/Form/Registration/EventInfoBlock.tpl
  templates/CRM/Event/Form/Selector.tpl
  templates/CRM/Event/Form/Task/Print.tpl
  templates/CRM/Event/Page/EventInfo.tpl
  templates/CRM/Event/Page/List.tpl
  templates/CRM/Event/Page/UserDashboard.tpl
  templates/CRM/common/l10n.js.tpl
  templates/CRM/common/navigation.js.tpl
Labels: master

#23807 SearchKit - Only add filter values to Afform title if passed internally
  ext/afform/mock/ang/testContactEmailSearchForm.aff.html
  ext/search_kit/Civi/Api4/Action/SearchDisplay/AbstractRunAction.php
Labels: merge ready, 5.51

#23824 (dev/core#3660) Ensure that rebuildMenuAndCaches has current mixins+classloaders
  CRM/Core/Invoke.php
Labels: 5.51

#23827 Handle empty date token gracefully
  Civi/Token/TokenProcessor.php
Labels: merge on pass, 5.51

#23828 backports to stable
  CRM/Contribute/Form/ContributionBase.php
  CRM/Contribute/Form/UpdateSubscription.php
  Civi/Token/TokenProcessor.php
  tests/phpunit/CRM/Contribute/Form/Contribution/MainTest.php
Labels: merge on pass, 5.50

#23830 5.50.3 - Set version. Add notes.
  ext/afform/admin/info.xml
  ext/afform/core/info.xml
  ext/afform/html/info.xml
  ext/afform/mock/info.xml
  ext/authx/info.xml
  ext/civicrm_admin_ui/info.xml
  ext/civigrant/info.xml
  ext/ckeditor4/info.xml
  ext/contributioncancelactions/info.xml
  ext/eventcart/info.xml
  ext/ewaysingle/info.xml
  ext/financialacls/info.xml
  ext/flexmailer/info.xml
  ext/greenwich/info.xml
  ext/legacycustomsearches/info.xml
  ext/message_admin/info.xml
  ext/oauth-client/info.xml
  ext/payflowpro/info.xml
  ext/recaptcha/info.xml
  ext/search_kit/info.xml
  ext/sequentialcreditnotes/info.xml
  release-notes.md
  release-notes/5.50.3.md
  sql/civicrm_generated.mysql
  sql/test_data_second_domain.mysql
  xml/version.xml
Labels: 5.50

#23816 Fix double organization name in invoice, use token
  CRM/Contribute/Form/Task/Invoice.php
  sql/civicrm_generated.mysql
  xml/templates/message_templates/contribution_invoice_receipt_html.tpl
Labels: master

#23832 dev/core#2983 - Make static function static - AJAX::caseDetails()
  CRM/Case/Page/AJAX.php
Labels: master

#23818 Afform - fix dependency injection for autogenerated forms
  ext/afform/core/Civi/Api4/Action/Afform/Get.php
Labels: 5.51

#23825 APIv4 - Enable exporting profiles with custom fields
  CRM/Core/BAO/UFField.php
  CRM/Core/DAO/UFField.php
  Civi/Api4/Generic/ExportAction.php
  tests/phpunit/api/v4/Custom/CustomProfileFieldTest.php
  tests/phpunit/api/v4/Custom/ExportCustomGroupTest.php
  xml/schema/Core/UFField.xml
Labels: master, merge ready, has-test

#23823 dev/core#3663 fix output regression on csv output for import
  CRM/Core/CodeGen/Main.php
  CRM/Import/DataSource.php
  CRM/Import/DataSource/CSV.php
  CRM/Import/DataSource/SQL.php
  CRM/Import/Forms.php
  CRM/Import/Parser.php
  CRM/Utils/PDF/Document.php
  CRM/Utils/PDF/Utils.php
  Civi/Test.php
  tests/phpunit/CRM/Contact/Import/Form/data/column_names_casing.csv
  tests/phpunit/CRM/Contact/Import/Parser/ContactTest.php
  tests/phpunit/CRM/Report/Utils/ReportTest.php
Labels: 5.51

#23837 5.51 to master
  CRM/Core/CodeGen/Main.php
  CRM/Core/Invoke.php
  CRM/Import/DataSource.php
  CRM/Import/DataSource/CSV.php
  CRM/Import/DataSource/SQL.php
  CRM/Import/Forms.php
  CRM/Import/Parser.php
  CRM/Utils/PDF/Document.php
  CRM/Utils/PDF/Utils.php
  Civi/Test.php
  Civi/Token/TokenProcessor.php
  ext/afform/core/Civi/Api4/Action/Afform/Get.php
  ext/afform/mock/ang/testContactEmailSearchForm.aff.html
  ext/search_kit/Civi/Api4/Action/SearchDisplay/AbstractRunAction.php
  tests/phpunit/CRM/Contact/Import/Form/data/column_names_casing.csv
  tests/phpunit/CRM/Contact/Import/Parser/ContactTest.php
  tests/phpunit/CRM/Report/Utils/ReportTest.php
Labels: master

#23835 dev/core#3667 fix failure to match existing contacts in skip mode
  CRM/Contact/Import/Parser/Contact.php
  tests/phpunit/CRM/Contact/Import/Form/data/individual_related_create.csv
  tests/phpunit/CRM/Contact/Import/Parser/ContactTest.php
  tests/phpunit/CRMTraits/Import/ParserTrait.php
Labels: has-test, 5.51

#23821 dev/core#3662 increase length of import table status message
  CRM/Import/DataSource.php
Labels: 5.51
