Repository civicrm/civicrm-core, pull requests merged in 2022-03, with the labels that each got.

#22855 dev/core#3087- Grant menu appears twice
  sql/civicrm_generated.mysql
  xml/templates/civicrm_navigation.tpl
Labels: merge on pass, 5.47

#22857 5.47
  sql/civicrm_generated.mysql
  xml/templates/civicrm_navigation.tpl
Labels: master

#22858 [NFC] Update Contribution Recur DAO following regen
  CRM/Contribute/DAO/ContributionRecur.php
Labels: merge on pass, 5.47

#22812 (dev/core#1304) Queues - Define schema for runner, run_count, lease_time, et al
  CRM/Queue/BAO/QueueItem.php
  CRM/Queue/DAO/Queue.php
  CRM/Queue/DAO/QueueItem.php
  CRM/Queue/Service.php
  CRM/Upgrade/Incremental/php/FiveFortyEight.php
  sql/civicrm_queue_item.mysql
  xml/schema/Queue/Queue.xml
  xml/schema/Queue/QueueItem.xml
Labels: master, merge on pass

#22864 Add handling for civimember disabled
  ext/financialacls/financialacls.php
Labels: master

#22860 (NFC) Membership Tests - Update assertions to match behavior circa leap-day
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/api/v3/ContributionPageTest.php
Labels: master

#22866 php notices on contributionview
  CRM/Contribute/BAO/Contribution.php
  CRM/Contribute/Form/ContributionView.php
Labels: master, merge on pass

#22867 (NFC) LoggingDetailTest - Improve reliability of test
  tests/phpunit/CRM/Report/Form/Contact/LoggingDetailTest.php
Labels: master, merge on pass

#22438 Format money on transaction list
  CRM/Financial/Page/AJAX.php
  tests/phpunit/CRM/Financial/Page/AjaxTest.php
Labels: master

#22872 Call to undefined function civicrm_api3_create_error() in civicrm/civ…
  CRM/Core/Page/AJAX/Attachment.php
Labels: master

#22876 added as a contributor
  contributor-key.yml
Labels: master

#22869 php/smarty notices on contribution view part 2
  CRM/Contribute/Form/ContributionView.php
Labels: master

#22879 Fix undeclared javascript variables
  ang/crmMailing/RadioDate.js
  ang/crmMailing/Recipients.js
  ang/crmMailing/Templates.js
Labels: 5.47

#22884 5.47
  ang/crmMailing/RadioDate.js
  ang/crmMailing/Recipients.js
  ang/crmMailing/Templates.js
Labels: master

#22881 CiviGrant install fix second attempt
  CRM/Core/ManagedEntities.php
  CRM/Upgrade/Form.php
  CRM/Upgrade/Incremental/Base.php
  CRM/Upgrade/Incremental/php/FiveFortySeven.php
Labels: 5.47

#22888 5.47
  CRM/Core/ManagedEntities.php
  CRM/Upgrade/Form.php
  CRM/Upgrade/Incremental/Base.php
  CRM/Upgrade/Incremental/php/FiveFortySeven.php
Labels: master

#22883 ManagedEntities - Allow "match" param to convert existing records to …
  CRM/Core/ManagedEntities.php
  tests/phpunit/api/v4/Entity/ManagedEntityTest.php
Labels: master, has-test

#22885 dev/core#3095 Permit setting of format_locale, prefer if set
  CRM/Admin/Form/Setting/Localization.php
  CRM/Core/I18n.php
  Civi/Core/Format.php
  settings/Localization.setting.php
  templates/CRM/Admin/Form/Setting/Localization.tpl
Labels: merge on pass, 5.47

#22889 5.47.0 - Bump version. Add notes from RC period.
  ext/afform/admin/info.xml
  ext/afform/core/info.xml
  ext/afform/html/info.xml
  ext/afform/mock/info.xml
  ext/authx/info.xml
  ext/civigrant/info.xml
  ext/ckeditor4/info.xml
  ext/contributioncancelactions/info.xml
  ext/eventcart/info.xml
  ext/ewaysingle/info.xml
  ext/financialacls/info.xml
  ext/flexmailer/info.xml
  ext/greenwich/info.xml
  ext/legacycustomsearches/info.xml
  ext/message_admin/info.xml
  ext/oauth-client/info.xml
  ext/payflowpro/info.xml
  ext/recaptcha/info.xml
  ext/search_kit/info.xml
  ext/sequentialcreditnotes/info.xml
  release-notes.md
  release-notes/5.47.0.md
  sql/civicrm_generated.mysql
  sql/test_data_second_domain.mysql
  xml/version.xml
Labels: 5.47

#22891 5.47
  CRM/Admin/Form/Setting/Localization.php
  CRM/Core/I18n.php
  Civi/Core/Format.php
  release-notes.md
  release-notes/5.47.0.md
  settings/Localization.setting.php
  templates/CRM/Admin/Form/Setting/Localization.tpl
Labels: master

#22892 Avoid e-notices on pages with tabs
  CRM/Core/Form.php
  CRM/Core/Page.php
  CRM/Core/Smarty.php
Labels: master

#22895 Mark AJAX methods as static
  CRM/Campaign/Page/AJAX.php
  CRM/UF/Page/AJAX.php
Labels: master, merge on pass

#22894 smarty/php notices on contribution view part 4
  CRM/Contribute/Form/ContributionView.php
  CRM/Core/BAO/CustomGroup.php
Labels: master

#22896 APIv4 Explorer - Add "copy" button to quicly copy code to clipboard
  ang/api4Explorer/Explorer.html
  ang/api4Explorer/Explorer.js
Labels: master, merge on pass

#22868 Refresh entity list after updating custom group (self_hook_*)
  CRM/Core/BAO/CustomGroup.php
  tests/phpunit/api/v4/Action/CustomValueTest.php
Labels: master

#22853 [REF] APIv4 - Use new class_args metadata to remove special handing
  Civi/Api4/Event/Subscriber/CreateApi4RequestSubscriber.php
  Civi/Api4/Provider/CustomEntityProvider.php
Labels: master, merge on pass

#22897 dev/core#3104 - Crash when viewing a contact page - Call to undefined method CRM_Contact_Page_View_Summary::addExpectedSmartyVariables()
  CRM/Core/Page.php
Labels: merge on pass, 5.48

#22899 5.48
  CRM/Core/Page.php
Labels: master

#22826 APIv4 - Get dynamic list of entity types
  Civi/Api4/Entity.php
Labels: master

#22900 Expose payment processor error from PaymentProcessor.pay
  api/v3/PaymentProcessor.php
Labels: master, merge on pass

#22865 dev/core#3094 - Crash on contribution view when don't have event/participant permissions
  CRM/Contribute/Form/ContributionView.php
  tests/phpunit/CRM/Contribute/Form/ContributionViewTest.php
Labels: has-test, 5.48

#22901 5.48
  CRM/Contribute/Form/ContributionView.php
  tests/phpunit/CRM/Contribute/Form/ContributionViewTest.php
Labels: master

#22903 Rename test class to reflect form
  tests/phpunit/CRM/Event/Form/Registration/RegisterTest.php
Labels: master, merge on pass

#22907 [NFC] Superficial cleanup
  CRM/Contact/Page/View/Relationship.php
Labels: master, merge on pass

#22870 Only acl line items based on contribution
  CRM/Price/BAO/LineItem.php
Labels: merge on pass, 5.48

#22908 (dev/core#3106) Raise max# of editable websites (5 => 25)
  CRM/Contact/Form/Inline/Website.php
  templates/CRM/Contact/Form/Inline/Website.tpl
Labels: master, merge ready

#22910 5.48
  CRM/Price/BAO/LineItem.php
Labels: master

#22893 dev/core#3100 - Remove grant leftovers from core xml. Remove empty grant reports menu.
  CRM/Upgrade/Incremental/php/FiveFortySeven.php
  CRM/Upgrade/Incremental/sql/5.47.1.mysql.tpl
  ext/afform/admin/info.xml
  ext/afform/core/info.xml
  ext/afform/html/info.xml
  ext/afform/mock/info.xml
  ext/authx/info.xml
  ext/civigrant/info.xml
  ext/civigrant/managed/Navigation_Grants.mgd.php
  ext/ckeditor4/info.xml
  ext/contributioncancelactions/info.xml
  ext/eventcart/info.xml
  ext/ewaysingle/info.xml
  ext/financialacls/info.xml
  ext/flexmailer/info.xml
  ext/greenwich/info.xml
  ext/legacycustomsearches/info.xml
  ext/message_admin/info.xml
  ext/oauth-client/info.xml
  ext/payflowpro/info.xml
  ext/recaptcha/info.xml
  ext/search_kit/info.xml
  ext/sequentialcreditnotes/info.xml
  sql/civicrm_generated.mysql
  sql/test_data_second_domain.mysql
  xml/templates/civicrm_navigation.tpl
  xml/version.xml
Labels: merge on pass, 5.47

#22912 Add action links for group.
  CRM/Contact/DAO/Group.php
  xml/schema/Contact/Group.xml
Labels: master, merge on pass

#22830 dev/core#3082 enhance EntityRef to show create new link when contact listing is fil…
  js/Common.js
Labels: master, merge ready

#22911 dev/core#3100 - Remove grant leftovers from core xml. Remove empty grant reports menu
  CRM/Upgrade/Incremental/php/FiveFortySeven.php
  CRM/Upgrade/Incremental/sql/5.48.beta1.mysql.tpl
  ext/civigrant/managed/Navigation_Grants.mgd.php
  sql/civicrm_generated.mysql
  xml/templates/civicrm_navigation.tpl
Labels: merge ready, 5.48

#22905 CiviGrant - Don't auto-create any grant types
  CRM/Upgrade/Incremental/php/FiveFortySeven.php
  CRM/Upgrade/Incremental/sql/5.47.1.mysql.tpl
  ext/civigrant/managed/OptionGroup_grant_type.mgd.php
  ext/civigrant/tests/phpunit/api/v3/GrantTest.php
Labels: merge on pass, 5.47

#22913 CiviGrant - Don't auto-create any grant types
  CRM/Upgrade/Incremental/php/FiveFortySeven.php
  CRM/Upgrade/Incremental/sql/5.48.beta1.mysql.tpl
  ext/civigrant/managed/OptionGroup_grant_type.mgd.php
  ext/civigrant/tests/phpunit/api/v3/GrantTest.php
Labels: 5.48

#22882 Allow API4 match to match an empty value
  Civi/Api4/Generic/AbstractSaveAction.php
  tests/phpunit/api/v4/Action/SaveTest.php
Labels: master, merge on pass

#22914 5.48
  CRM/Upgrade/Incremental/php/FiveFortySeven.php
  CRM/Upgrade/Incremental/sql/5.48.beta1.mysql.tpl
  ext/civigrant/managed/Navigation_Grants.mgd.php
  ext/civigrant/managed/OptionGroup_grant_type.mgd.php
  ext/civigrant/tests/phpunit/api/v3/GrantTest.php
  sql/civicrm_generated.mysql
  xml/templates/civicrm_navigation.tpl
Labels: master

#22916 dev/core#3085 - Checkbox fields on profile admin page can't be unchecked
  CRM/UF/Form/AdvanceSetting.php
  CRM/UF/Form/Group.php
Labels: master, merge on pass

#22680 Add paymentstatus helpers for doPayment and separate return params
  CRM/Core/Payment.php
  CRM/Core/Payment/AuthorizeNet.php
  ext/eventcart/CRM/Event/Cart/Form/Checkout/Payment.php
Labels: master

#22917 regenerate civicrm_generated
  sql/civicrm_generated.mysql
Labels: master

#22898 Don't perform event timezone check if CiviEvent is disabled
  CRM/Utils/Check/Component/Event.php
Labels: merge on pass, 5.48

#22920 5.48
  CRM/Utils/Check/Component/Event.php
Labels: master

#22802 Remove use of overrideDefaultCurrency method from eventInfo page.
  CRM/Event/Page/EventInfo.php
  CRM/Price/BAO/PriceField.php
  templates/CRM/Event/Page/EventInfo.tpl
Labels: master

#22886 Simplify fix for smarty/php notice on contributionview
  CRM/Contribute/Form/ContributionView.php
  templates/CRM/Price/Page/LineItem.tpl
Labels: master

#22255 Calculate lifetime memberships more accurately
  CRM/Member/BAO/Membership.php
  tests/phpunit/CRM/Member/BAO/MembershipTest.php
Labels: master, has-test

#22291 [REF] Extract & stdise AmountBlockIsActive
  CRM/Contribute/Form/Contribution/Confirm.php
  CRM/Contribute/Form/Contribution/Main.php
  CRM/Contribute/Form/ContributionBase.php
Labels: master

#22316 Preserve selected tab when navigating between pages.
  templates/CRM/common/TabHeader.js
Labels: master

#22463 Split mailing label formatting out from main format
  CRM/Contact/Form/Task/Label.php
  CRM/Member/Form/Task/Label.php
  CRM/Utils/Address.php
  tests/phpunit/CRM/Utils/AddressTest.php
Labels: master

#22483 Fully deprecate `getTokenDetails`
  CRM/Utils/Token.php
  tests/phpunit/CRM/Mailing/MailingSystemTest.php
  tests/phpunit/CRM/Utils/TokenTest.php
  tests/phpunit/api/v3/MailingTest.php
Labels: master

#21945 Add page id and template type as data attributes in contribution templates
  templates/CRM/Contribute/Form/Contribution/Confirm.tpl
  templates/CRM/Contribute/Form/Contribution/Main.tpl
  templates/CRM/Contribute/Form/Contribution/ThankYou.tpl
Labels: master

#21467 dev/core#2833 Fix Contact Type change on Backend Membership Credit Ca…
  CRM/Contribute/Form/AbstractEditPayment.php
  tests/phpunit/CRM/Member/Form/MembershipTest.php
Labels: master

#22922 5.47.1 - Add release notes
  release-notes.md
  release-notes/5.47.1.md
Labels: 5.47

#22921 (NFC) contributor-key.yml - Fix syntax error
  contributor-key.yml
Labels: 5.48

#22923 5.48
  contributor-key.yml
Labels: master

#22808 SearchKit - Add CiviMail integration
  ext/search_kit/Civi/Api4/Action/SearchDisplay/GetSearchTasks.php
  ext/search_kit/ang/crmSearchTasks/crmSearchBatchRunner.component.js
  ext/search_kit/ang/crmSearchTasks/crmSearchTaskMailing.ctrl.js
  ext/search_kit/ang/crmSearchTasks/crmSearchTaskMailing.html
Labels: master, merge ready, needs-documentation

#22924 backport of 22898
  CRM/Utils/Check/Component/Event.php
Labels: 5.47

#22927 SearchKit - Fix page size size
  ext/search_kit/css/crmSearchDisplay.css
Labels: master, merge on pass

#22929 Afform Gui - Fix selecting html element of text box
  ext/afform/admin/ang/afGuiEditor/elements/afGuiText-menu.html
Labels: 5.48

#22932 dev/core#3112 Clear caches to avoid error on upgrade
  CRM/Upgrade/Incremental/php/FiveFortySeven.php
Labels: merge ready, 5.48

#22933 Fix backward-compatability for new method in CRM_Contact_BAO_Query_Hook
  CRM/Contact/BAO/Query/Hook.php
Labels: merge on pass, 5.48

#22937 dev/core#3112 Clear caches to avoid error on upgrade
  CRM/Upgrade/Incremental/php/FiveFortySeven.php
Labels: merge on pass, 5.47

#22938 Fix backward-compatability for new method in CRM_Contact_BAO_Query_Hook
  CRM/Contact/BAO/Query/Hook.php
Labels: 5.47

#22935 5.48
  CRM/Contact/BAO/Query/Hook.php
  CRM/Upgrade/Incremental/php/FiveFortySeven.php
  ext/afform/admin/ang/afGuiEditor/elements/afGuiText-menu.html
Labels: master

#22939 During upgrade log that it ran the sql when there is just a sql file and no corresponding task
  CRM/Upgrade/Form.php
Labels: master, merge on pass

#22934 Dev/core#2524 Fix seriazliation parameter exception in APIv3
  CRM/Core/DAO.php
  CRM/Core/SelectValues.php
  tests/phpunit/CRM/Core/DAOTest.php
  tests/phpunit/api/v3/CustomFieldTest.php
Labels: master, merge on pass

#22943 Optimise isCustomDateField
  CRM/Contact/BAO/Query.php
Labels: master

#22832 Enable APIv4 export action on UFGroup and UFField.
  Civi/Api4/UFField.php
  Civi/Api4/UFGroup.php
Labels: master

#22804 Core#2918 Implement new UI for configuring dedupe rule usage.
  CRM/Contact/Form/DedupeRules.php
  css/civicrm.css
  js/crm.dedupeRules.js
  templates/CRM/Contact/Form/DedupeRules.tpl
Labels: master, merge ready

#22944 [REF] Rename SoftDeleteEntity -> SoftDeleteActionTrait
  Civi/Api4/Action/Contact/Delete.php
  Civi/Api4/Generic/Traits/SoftDeleteActionTrait.php
Labels: 5.48

#22906 SearchKit - Improve checkbox UX for bulk actions
  ext/search_kit/ang/crmSearchAdmin/resultsTable/crmSearchAdminResultsTable.html
  ext/search_kit/ang/crmSearchDisplay/traits/searchDisplaySortableTrait.service.js
  ext/search_kit/ang/crmSearchDisplayTable/crmSearchDisplayTable.html
  ext/search_kit/ang/crmSearchDisplayTable/crmSearchDisplayTableBody.html
  ext/search_kit/ang/crmSearchDisplayTable/crmSearchDisplayTaskHeader.html
  ext/search_kit/ang/crmSearchTasks/traits/searchDisplayTasksTrait.service.js
  ext/search_kit/css/crmSearchAdmin.css
  ext/search_kit/css/crmSearchTasks.css
Labels: master

#22945 5.48
  Civi/Api4/Action/Contact/Delete.php
  Civi/Api4/Generic/Traits/SoftDeleteActionTrait.php
Labels: master

#21470 dev/financial#6 Fix creating of template contribution when it has custom data
  CRM/Contribute/BAO/ContributionRecur.php
  tests/phpunit/CRM/Contribute/BAO/ContributionRecurTest.php
Labels: master, merge ready, has-test

#22925 Schema - Fix boolean fields in civicrm_event and civicrm_contribution
  CRM/Contribute/DAO/Contribution.php
  CRM/Core/BAO/CustomGroup.php
  CRM/Event/DAO/Event.php
  CRM/Upgrade/Incremental/sql/5.49.alpha1.mysql.tpl
  xml/schema/Contribute/Contribution.xml
  xml/schema/Event/Event.xml
Labels: master

#22825 get membership type ID and number of terms from price_x fields
  CRM/Contribute/Form/ContributionBase.php
  CRM/Price/BAO/PriceSet.php
  tests/phpunit/CRM/Contribute/Form/Contribution/MainTest.php
  tests/phpunit/api/v3/ContributionPageTest.php
Labels: master, merge ready, has-test

#22947 Fixed fatal error on edit grant
  ext/civigrant/CRM/Grant/Form/Grant.php
Labels: 5.47

#22948 Return array for setdefaults
  CRM/Core/Form.php
Labels: 5.48

#22952 Search Kit - Auto-enable during normal installation
  setup/plugins/init/DefaultExtensions.civi-setup.php
Labels: master, merge on pass

#22950 REF - Split upgrade SQL into multiple tasks
  CRM/Upgrade/Incremental/php/FiveFortyNine.php
  CRM/Upgrade/Incremental/sql/5.49.alpha1.mysql.tpl
Labels: master

#22953 5.48
  CRM/Core/Form.php
Labels: master

#22956 Notice fixes in advanced search
  CRM/Contact/Form/Search/Criteria.php
  templates/CRM/Contact/Form/Search/Criteria/Basic.tpl
Labels: master

#22958 (dev/core#2122) CiviEvent - Add pre-upgrade warning
  CRM/Upgrade/Incremental/php/FiveFortySeven.php
  ext/afform/admin/info.xml
  ext/afform/core/info.xml
  ext/afform/html/info.xml
  ext/afform/mock/info.xml
  ext/authx/info.xml
  ext/civigrant/info.xml
  ext/ckeditor4/info.xml
  ext/contributioncancelactions/info.xml
  ext/eventcart/info.xml
  ext/ewaysingle/info.xml
  ext/financialacls/info.xml
  ext/flexmailer/info.xml
  ext/greenwich/info.xml
  ext/legacycustomsearches/info.xml
  ext/message_admin/info.xml
  ext/oauth-client/info.xml
  ext/payflowpro/info.xml
  ext/recaptcha/info.xml
  ext/search_kit/info.xml
  ext/sequentialcreditnotes/info.xml
  sql/civicrm_generated.mysql
  sql/test_data_second_domain.mysql
  xml/version.xml
Labels: 5.47

#22961 5.48
  CRM/Contribute/Form/ContributionView.php
  CRM/Core/Permission/Backdrop.php
  CRM/Core/Permission/Drupal.php
  CRM/Core/Permission/Drupal6.php
  CRM/Core/Permission/Drupal8.php
  CRM/Core/Permission/Joomla.php
  CRM/Core/Permission/WordPress.php
  CRM/Event/Import/Parser/Participant.php
  CRM/Utils/Check/Component/Security.php
  composer.json
  composer.lock
  tests/phpunit/E2E/Extern/CliRunnerTest.php
Labels: master

#22962 [NFC] - Compatibility for PHP-7.4/PHP-8
  Civi/Core/Event/EventPrinter.php
Labels: master, merge on pass

#22887 Afform - compose layouts with multiple SearchKit displays
  ext/afform/admin/Civi/Api4/Action/Afform/LoadAdminData.php
  ext/afform/admin/ang/afAdmin/afAdminList.controller.js
  ext/afform/admin/ang/afAdmin/afAdminList.html
  ext/afform/admin/ang/afGuiEditor.js
  ext/afform/admin/ang/afGuiEditor/afGuiEditor.component.js
  ext/afform/admin/ang/afGuiEditor/afGuiEditorPalette.html
  ext/afform/admin/ang/afGuiEditor/afGuiSearch.component.js
  ext/afform/admin/ang/afGuiEditor/afGuiSearch.html
  ext/afform/admin/ang/afGuiEditor/config-form.html
  ext/afform/admin/ang/afGuiEditor/elements/afGuiContainer-menu.html
  ext/afform/admin/ang/afGuiEditor/elements/afGuiContainer.component.js
  ext/afform/admin/ang/afGuiEditor/elements/afGuiContainer.html
  ext/afform/admin/ang/afGuiEditor/elements/afGuiField-menu.html
  ext/afform/admin/ang/afGuiEditor/elements/afGuiSearchContainer-menu.html
  ext/afform/admin/ang/afGuiEditor/elements/afGuiSearchDisplay.html
Labels: master

#22960 What if we stopped publishing Drupal 6 releases in 2022?
  distmaker/distmaker.conf.dist
  distmaker/distmaker.sh
  distmaker/dists/drupal6_php5.sh
  distmaker/dists/patchset.sh
  distmaker/utils/repo-report.php
Labels: master

#22965 Fix property declarations
  tests/phpunit/CRM/Contribute/Form/Contribution/MainTest.php
Labels: master

#22964 (Regression) - fixed tags form field display on New/Edit contact screen
  templates/CRM/Contact/Form/Edit/TagsAndGroups.tpl
Labels: 5.48

#22968 5.48
  templates/CRM/Contact/Form/Edit/TagsAndGroups.tpl
Labels: master

#22973 Add case ID and make subject optional for case detail report
  CRM/Report/Form/Case/Detail.php
Labels: master

#22974 REF Cleanup activity getBespokeTokens()
  CRM/Activity/Tokens.php
Labels: master

#22969 Do not default escape 'create new' links
  templates/CRM/Block/CreateNew.tpl
Labels: master

#22976 dev/core#3126 - CiviReport statistics appearing twice on page
  templates/CRM/Report/Form.tpl
  templates/CRM/Report/Form/Contact/Detail.tpl
  templates/CRM/Report/Form/Contribute/DeferredRevenue.tpl
  templates/CRM/Report/Form/Event/Income.tpl
Labels: 5.48

#22980 5.48 to master
  templates/CRM/Report/Form.tpl
  templates/CRM/Report/Form/Contact/Detail.tpl
  templates/CRM/Report/Form/Contribute/DeferredRevenue.tpl
  templates/CRM/Report/Form/Event/Income.tpl
Labels: master

#22978 Fix copy button float in APIv4 Explorer
  ang/api4Explorer/Explorer.html
Labels: master

#22979 false is true
  templates/CRM/Report/Form.tpl
  templates/CRM/Report/Form/Contact/Detail.tpl
  templates/CRM/Report/Form/Contribute/DeferredRevenue.tpl
  templates/CRM/Report/Form/Event/Income.tpl
Labels: merge on pass, 5.47

#22419 Group Contact create -> fix to use post hook for subscription records
  CRM/Contact/BAO/GroupContact.php
  CRM/Contact/BAO/SubscriptionHistory.php
  tests/phpunit/api/v3/GroupContactTest.php
Labels: master

#22963 Afform - Fix saving and editing entity blocks
  ext/afform/admin/ang/afGuiEditor/afGuiEditor.component.js
  ext/afform/admin/ang/afGuiEditor/elements/afGuiContainer.component.js
Labels: 5.48

#22984 5.48
  ext/afform/admin/ang/afGuiEditor/afGuiEditor.component.js
  ext/afform/admin/ang/afGuiEditor/elements/afGuiContainer.component.js
Labels: master

#22902 Cleanup variable assigns in ContributionPage confirm
  CRM/Contribute/Form/Contribution/Confirm.php
Labels: master

#22975 Afform - Easier layout creation with predefined container styles and built-in title
  ang/crmUI.css
  ang/crmUi.ang.php
  ang/crmUi.js
  ext/afform/admin/Civi/AfformAdmin/AfformAdminMeta.php
  ext/afform/admin/ang/afGuiEditor.css
  ext/afform/admin/ang/afGuiEditor.js
  ext/afform/admin/ang/afGuiEditor/afGuiEditor.component.js
  ext/afform/admin/ang/afGuiEditor/afGuiMenuItemCollapsible.component.js
  ext/afform/admin/ang/afGuiEditor/afGuiMenuItemCollapsible.html
  ext/afform/admin/ang/afGuiEditor/afGuiMenuItemStyle.component.js
  ext/afform/admin/ang/afGuiEditor/afGuiMenuItemStyle.html
  ext/afform/admin/ang/afGuiEditor/elements/afGuiContainer-menu.html
  ext/afform/admin/ang/afGuiEditor/elements/afGuiContainer.component.js
  ext/afform/admin/ang/afGuiEditor/elements/afGuiContainer.html
  ext/afform/admin/ang/afGuiEditor/elements/afGuiSearchContainer-menu.html
  ext/afform/admin/ang/afGuiEditor/elements/afGuiText-menu.html
  ext/afform/admin/ang/afGuiEditor/elements/afGuiText.component.js
  ext/afform/core/ang/af/afTitle.directive.js
  ext/afform/core/ang/afCore.css
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdmin.component.js
  ext/search_kit/css/crmSearchAdmin.css
Labels: master

#22993 Fix undefined index by making sure that is_template is always defined
  CRM/Contribute/Form/Contribution.php
Labels: master

#22987 Make note date required when creating note
  CRM/Note/Form/Note.php
Labels: master

#21514 Fix issues with case sorting/searching from case dashboard
  CRM/Case/BAO/Case.php
  CRM/Case/Selector/Search.php
Labels: master

#22991 Do not escape hierarchical select
  templates/CRM/Activity/Import/Form/MapTable.tpl
  templates/CRM/Contact/Import/Form/MapTable.tpl
  templates/CRM/Contact/Import/Form/Mapper.tpl
  templates/CRM/Contribute/Import/Form/MapTable.tpl
  templates/CRM/Custom/Form/Group.tpl
  templates/CRM/Event/Import/Form/MapTable.tpl
  templates/CRM/Member/Import/Form/MapTable.tpl
  templates/CRM/UF/Form/Field.tpl
Labels: master

#22998 [REF] Update Guzzlehttp/psr7 version to be 1.8.5
  composer.lock
Labels: merge on pass, 5.48

#22985 dev/core#3119 - Post-upgrade messages no longer being displayed
  CRM/Upgrade/Form.php
  CRM/Upgrade/Incremental/Base.php
Labels: merge ready, 5.48

#22995 dev/core#3119 - Post-upgrade messages no longer being displayed
  CRM/Upgrade/Form.php
  CRM/Upgrade/Incremental/Base.php
Labels: 5.47

#22990 Grumpy smarty - Never escape 'initHideBoxes'
  templates/CRM/Activity/Import/Form/MapField.tpl
  templates/CRM/Contact/Form/Search/Builder.tpl
  templates/CRM/Contact/Import/Form/MapField.tpl
  templates/CRM/Contribute/Form/AdditionalInfo/Premium.tpl
  templates/CRM/Contribute/Import/Form/MapField.tpl
  templates/CRM/Custom/Form/Group.tpl
  templates/CRM/Event/Import/Form/MapField.tpl
  templates/CRM/Member/Import/Form/MapField.tpl
  templates/CRM/UF/Form/Field.tpl
Labels: master

#22982 Remove use of deprecated FILTER_SANITIZE_STRING
  ext/search_kit/Civi/Api4/Action/SearchDisplay/Download.php
Labels: master

#22970 Enotice fix in grumpy smarty mode
  CRM/Contact/Form/Task/EmailTrait.php
Labels: master

#22957 Afform - reset managed entities when deleting a dashlet
  CRM/Core/ManagedEntities.php
  Civi/Api4/Generic/BasicBatchAction.php
  ext/afform/core/Civi/Api4/Action/Afform/Revert.php
  ext/afform/core/Civi/Api4/Afform.php
  ext/afform/core/Civi/Api4/Utils/AfformSaveTrait.php
  ext/afform/mock/tests/phpunit/api/v4/AfformTest.php
Labels: master, has-test

#23000 SampleData - Fix missing option value names
  sql/civicrm_sample_custom_data.mysql
Labels: master

#22904 Add workflow template for offline event
  CRM/Event/Form/Participant.php
  CRM/Event/Form/ParticipantFeeSelection.php
  CRM/Event/Tokens.php
  CRM/Event/WorkflowMessage/EventOfflineReceipt.php
  CRM/Event/WorkflowMessage/ParticipantTrait.php
  tests/phpunit/CRM/Event/Form/ParticipantTest.php
  tests/phpunit/CRM/Utils/TokenConsistencyTest.php
  tests/templates/message_templates/event_offline_receipt_text.tpl
Labels: master

#23001 5.48.0 release notes initial run
  release-notes.md
  release-notes/5.48.0.md
Labels: 5.48

#23009 dev/core#3132 Ensure that contacts are not placed in null island if g…
  CRM/Core/BAO/Address.php
  tests/phpunit/CRM/Utils/Geocode/TestProvider.php
  tests/phpunit/api/v3/AddressTest.php
Labels: master, has-test

#23004 Remove issets on pay_later_receipt
  sql/civicrm_generated.mysql
  xml/templates/message_templates/contribution_online_receipt_html.tpl
  xml/templates/message_templates/membership_online_receipt_html.tpl
  xml/templates/message_templates/membership_online_receipt_text.tpl
Labels: master

#23007 E-notice fix on pdfLetter
  templates/CRM/Contact/Form/Task/PDFLetterCommon.tpl
Labels: master

#23002 Keep "EntityFile" records until after Symfony "delete" hooks fire
  CRM/Core/BAO/File.php
Labels: master

#22981 Remove bad use of PHP assert, removed in PHP 8.0
  CRM/Case/Form/Activity/LinkCases.php
Labels: master, merge on pass

#23011 Afform - Fix collapsible style
  ext/afform/core/ang/afCore.css
Labels: master

#23010 SearchKit - mark stable
  ext/search_kit/info.xml
Labels: master

#23005 noexpand seems to never be assigned
  templates/CRM/Form/attachment.tpl
Labels: master

#23014 Remove grumpy-mode-incompatible isset in payment notification
  sql/civicrm_generated.mysql
  tests/phpunit/CRM/Contribute/Form/AdditionalPaymentTest.php
  tests/phpunit/api/v3/PaymentTest.php
  xml/templates/message_templates/payment_or_refund_notification_html.tpl
  xml/templates/message_templates/payment_or_refund_notification_text.tpl
Labels: master, merge on pass

#22930 dev/core#2122 - Revert event timezone
  CRM/Contribute/BAO/Contribution.php
  CRM/Core/CodeGen/GenerateData.php
  CRM/Core/SelectValues.php
  CRM/Event/BAO/Event.php
  CRM/Event/BAO/Participant.php
  CRM/Event/DAO/Event.php
  CRM/Event/Form/ManageEvent/EventInfo.php
  CRM/Event/Form/ManageEvent/Registration.php
  CRM/Event/Form/Participant.php
  CRM/Event/Form/ParticipantFeeSelection.php
  CRM/Event/Form/Registration.php
  CRM/Event/Form/SelfSvcTransfer.php
  CRM/Event/ICalendar.php
  CRM/Event/Page/EventInfo.php
  CRM/Event/Page/List.php
  CRM/Event/Page/ManageEvent.php
  CRM/Event/Tokens.php
  CRM/Financial/BAO/Payment.php
  CRM/Upgrade/Incremental/MessageTemplates.php
  CRM/Upgrade/Incremental/php/FiveFortySeven.php
  CRM/Upgrade/Incremental/sql/5.47.alpha1.mysql.tpl
  CRM/Utils/Check/Component/Env.php
  CRM/Utils/Check/Component/Event.php
  CRM/Utils/Date.php
  Civi/Api4/Service/Spec/Provider/EventCreationSpecProvider.php
  api/v3/Event.php
  sql/civicrm_generated.mysql
  templates/CRM/Core/Calendar/ICal.tpl
  templates/CRM/Event/Form/ManageEvent/EventInfo.tpl
  templates/CRM/Event/Form/ManageEvent/Registration.tpl
  templates/CRM/Event/Form/Registration/EventInfoBlock.tpl
  templates/CRM/Event/Page/EventInfo.tpl
  templates/CRM/Event/Page/List.tpl
  templates/CRM/Event/Page/ManageEvent.tpl
  tests/phpunit/CRM/Event/Form/ManageEvent/EventInfoTest.php
  tests/phpunit/CRM/Event/Form/ManageEvent/RegistrationTest.php
  tests/phpunit/CRM/Utils/DateTest.php
  tests/phpunit/CRM/Utils/TokenConsistencyTest.php
  tests/phpunit/api/v4/DataSets/ConformanceTest.json
  xml/schema/Event/Event.xml
  xml/templates/message_templates/event_offline_receipt_html.tpl
  xml/templates/message_templates/event_offline_receipt_text.tpl
  xml/templates/message_templates/event_online_receipt_html.tpl
  xml/templates/message_templates/event_online_receipt_text.tpl
  xml/templates/message_templates/participant_cancelled_html.tpl
  xml/templates/message_templates/participant_cancelled_text.tpl
  xml/templates/message_templates/participant_confirm_html.tpl
  xml/templates/message_templates/participant_confirm_text.tpl
  xml/templates/message_templates/participant_expired_html.tpl
  xml/templates/message_templates/participant_expired_text.tpl
  xml/templates/message_templates/participant_transferred_html.tpl
  xml/templates/message_templates/participant_transferred_text.tpl
  xml/templates/message_templates/payment_or_refund_notification_html.tpl
  xml/templates/message_templates/payment_or_refund_notification_text.tpl
Labels: 5.48

#23012 SearchKit - Fix multi-valued afform filters
  ext/afform/mock/ang/testContactEmailSearchForm.aff.html
  ext/search_kit/Civi/Api4/Action/SearchDisplay/AbstractRunAction.php
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/SearchAfformTest.php
Labels: has-test, sig:regression, 5.48

#23023 5.48
  CRM/Contribute/BAO/Contribution.php
  CRM/Core/CodeGen/GenerateData.php
  CRM/Core/SelectValues.php
  CRM/Event/BAO/Event.php
  CRM/Event/BAO/Participant.php
  CRM/Event/DAO/Event.php
  CRM/Event/Form/ManageEvent/EventInfo.php
  CRM/Event/Form/ManageEvent/Registration.php
  CRM/Event/Form/Participant.php
  CRM/Event/Form/ParticipantFeeSelection.php
  CRM/Event/Form/Registration.php
  CRM/Event/Form/SelfSvcTransfer.php
  CRM/Event/ICalendar.php
  CRM/Event/Page/EventInfo.php
  CRM/Event/Page/List.php
  CRM/Event/Page/ManageEvent.php
  CRM/Event/Tokens.php
  CRM/Financial/BAO/Payment.php
  CRM/Upgrade/Incremental/MessageTemplates.php
  CRM/Upgrade/Incremental/php/FiveFortySeven.php
  CRM/Upgrade/Incremental/sql/5.47.alpha1.mysql.tpl
  CRM/Utils/Check/Component/Env.php
  CRM/Utils/Check/Component/Event.php
  CRM/Utils/Date.php
  Civi/Api4/Service/Spec/Provider/EventCreationSpecProvider.php
  api/v3/Event.php
  ext/afform/mock/ang/testContactEmailSearchForm.aff.html
  ext/search_kit/Civi/Api4/Action/SearchDisplay/AbstractRunAction.php
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/SearchAfformTest.php
  release-notes.md
  release-notes/5.48.0.md
  sql/civicrm_generated.mysql
  templates/CRM/Core/Calendar/ICal.tpl
  templates/CRM/Event/Form/ManageEvent/EventInfo.tpl
  templates/CRM/Event/Form/ManageEvent/Registration.tpl
  templates/CRM/Event/Form/Registration/EventInfoBlock.tpl
  templates/CRM/Event/Page/EventInfo.tpl
  templates/CRM/Event/Page/List.tpl
  templates/CRM/Event/Page/ManageEvent.tpl
  tests/phpunit/CRM/Event/Form/ManageEvent/EventInfoTest.php
  tests/phpunit/CRM/Event/Form/ManageEvent/RegistrationTest.php
  tests/phpunit/CRM/Utils/DateTest.php
  tests/phpunit/CRM/Utils/TokenConsistencyTest.php
  tests/phpunit/api/v4/DataSets/ConformanceTest.json
  xml/schema/Event/Event.xml
  xml/templates/message_templates/event_offline_receipt_html.tpl
  xml/templates/message_templates/event_offline_receipt_text.tpl
  xml/templates/message_templates/event_online_receipt_html.tpl
  xml/templates/message_templates/event_online_receipt_text.tpl
  xml/templates/message_templates/participant_cancelled_html.tpl
  xml/templates/message_templates/participant_cancelled_text.tpl
  xml/templates/message_templates/participant_confirm_html.tpl
  xml/templates/message_templates/participant_confirm_text.tpl
  xml/templates/message_templates/participant_expired_html.tpl
  xml/templates/message_templates/participant_expired_text.tpl
  xml/templates/message_templates/participant_transferred_html.tpl
  xml/templates/message_templates/participant_transferred_text.tpl
  xml/templates/message_templates/payment_or_refund_notification_html.tpl
  xml/templates/message_templates/payment_or_refund_notification_text.tpl
Labels: master

#23013 SearchKit - Fix multi-valued afform filters
  ext/afform/mock/ang/testContactEmailSearchForm.aff.html
  ext/search_kit/Civi/Api4/Action/SearchDisplay/AbstractRunAction.php
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/SearchAfformTest.php
Labels: has-test, sig:regression, 5.47

#23024 Afform - fix missing submit actions
  ext/afform/admin/ang/afGuiEditor/config-form.html
Labels: sig:regression, 5.48

#23025 Afform - fix missing submit actions
  ext/afform/admin/ang/afGuiEditor/config-form.html
Labels: sig:regression

#22955 Add utils for managing schema to extension upgrader base class
  CRM/Extension/Upgrader/Base.php
  CRM/Extension/Upgrader/SchemaTrait.php
  ext/search_kit/CRM/Search/Upgrader.php
Labels: master

#23021 add classes to the membership userdashboard page
  templates/CRM/Member/Page/UserDashboard.tpl
Labels: master

#23003 SearchKit - Fix "all selected" checkbox when selecting a single page …
  ext/search_kit/ang/crmSearchTasks/traits/searchDisplayTasksTrait.service.js
Labels: master

#23027 dev/core#3134 Fix regression on unselected lineitem
  CRM/Financial/BAO/Order.php
Labels: 5.48

#22689 CiviMail - Remove deprecated variable only used by Mosaico
  CRM/Mailing/Info.php
Labels: master, merge ready

#23030 [NFC] First Pass at 5.48 release notes
  release-notes/5.48.0.md
Labels: 5.48

#22966 [REF] Deprecate BAO_Contact::retrieve
  CRM/Contact/BAO/Contact.php
  CRM/Contact/Form/Contact.php
  CRM/Contact/Page/View/Summary.php
Labels: master

#23043 Replace incorrect class comment
  CRM/Activity/Form/Task/AddToTag.php
Labels: master

#23044 Link to Google Maps over HTTPs
  templates/CRM/Contact/Form/Task/Map/Google.tpl
  templates/CRM/Contact/Form/Task/Map/OpenStreetMaps.tpl
Labels: master, merge on pass

#23028 5.48
  CRM/Financial/BAO/Order.php
  ext/afform/admin/ang/afGuiEditor/config-form.html
  release-notes/5.48.0.md
Labels: master

#23029 dev/core#3134 Fix regression on unselected lineitem
  CRM/Financial/BAO/Order.php
Labels: 5.47

#23035 Dedupe - Fix redirecting to contact after merge
  CRM/Contact/Form/Merge.php
Labels: 5.48

#23047 5.48
  CRM/Contact/Form/Merge.php
Labels: master
