Repository civicrm/civicrm-core, pull requests merged in 2022-07, with the labels that each got.

#23921 5.51 to master
  CRM/Utils/Rule.php
  tests/phpunit/CRM/Utils/RuleTest.php
Labels: master

#23923 [REF][PHP8.1] Upgrade Pear/mail_mime package to support php8.1
  composer.lock
Labels: master

#23926 [REF][PHP8.1] Fix default values which triggeres deprecation notices …
  CRM/Utils/GeocodeProvider.php
  Civi/Core/SqlTriggers.php
Labels: master

#23930 [NFC] Add code comment about triggerinfo "variables"
  Civi/Core/SqlTriggers.php
Labels: master

#23808 issues/2887 Enhancements to improve the iCal, Outlook and Google Calendar integration
  CRM/Core/Smarty/plugins/modifier.crmICalText.php
  CRM/Event/BAO/Event.php
  CRM/Event/ICalendar.php
  CRM/Utils/ICalendar.php
  templates/CRM/Core/Calendar/ICal.tpl
  templates/CRM/Event/Page/iCalLinks.tpl
  xml/templates/message_templates/event_offline_receipt_html.tpl
  xml/templates/message_templates/event_offline_receipt_text.tpl
  xml/templates/message_templates/event_online_receipt_html.tpl
  xml/templates/message_templates/event_online_receipt_text.tpl
  xml/templates/message_templates/participant_confirm_html.tpl
  xml/templates/message_templates/participant_confirm_text.tpl
Labels: master, merge ready

#23922 [REF][PHP8.1] Stop Passing NULL values into mb_strlen in DAO nad strp…
  CRM/Core/DAO.php
  CRM/Utils/API/HTMLInputCoder.php
  api/v3/Activity.php
  api/v3/Contact.php
  api/v3/utils.php
Labels: master, merge on pass

#23919 Afform - Allow picking icon for tab, add CrmUiIconPicker widget
  ang/crmUi.js
  ext/afform/admin/ang/afGuiEditor/afGuiEditor.component.js
  ext/afform/admin/ang/afGuiEditor/config-form.html
  ext/afform/core/Civi/Api4/Afform.php
  ext/afform/core/afform.php
  ext/civigrant/ang/afsearchGrants.aff.json
  ext/search_kit/ang/crmSearchAdmin/displays/common/searchAdminIcons.component.js
  ext/search_kit/ang/crmSearchAdmin/displays/common/searchAdminIcons.html
Labels: master

#23912 CRM_Report_Form: set _from and _where as public for the alterReportVar hook
  CRM/Report/Form.php
Labels: master

#23913 [REF][PHP8.1] Upgrade Symfony to 4.x for WP, Drupal7, Backdrop, Joomla
  composer.json
  composer.lock
  tests/phpunit/CRM/Core/ComposerConfigTest.php
Labels: master

#23904 dev/core#3503, dev/core#3492 Fix grant exports and relative dates
  CRM/Contact/BAO/Query/Hook.php
  CRM/Core/BAO/Mapping.php
  ext/civigrant/CRM/Grant/BAO/Query.php
Labels: merge ready, 5.51

#23938 [REF][PHP8.1] Update Brick/Math to a version that works with php8.1
  composer.lock
Labels: master, merge on pass

#23939 5.51
  CRM/Contact/BAO/Query/Hook.php
  CRM/Core/BAO/Mapping.php
  ext/civigrant/CRM/Grant/BAO/Query.php
Labels: master

#23935 [REF][PHP8.1] Another set of fixes for passing in NULL values to php …
  CRM/Activity/BAO/Activity.php
  CRM/Case/XMLRepository.php
  CRM/Contact/BAO/Contact.php
  CRM/Core/Action.php
  CRM/Core/BAO/CustomField.php
  CRM/Core/BAO/SchemaHandler.php
  CRM/Utils/Date.php
  CRM/Utils/String.php
  CRM/Utils/System.php
  Civi/Api4/Service/Spec/SpecFormatter.php
  Civi/Api4/Utils/FormattingUtil.php
  api/v3/Generic.php
Labels: master

#23927 dev/core#3707 Fix wordpress issue of page not refreshing after import
  CRM/Custom/Import/Form/DataSource.php
  CRM/Import/Form/DataSource.php
  CRM/Import/Form/Preview.php
Labels: 5.51

#23931 RepeatTransaction - separate out repeat pledge handling from completeOrder
  CRM/Contribute/BAO/Contribution.php
  CRM/Contribute/BAO/ContributionRecur.php
  CRM/Pledge/BAO/PledgePayment.php
  tests/phpunit/api/v3/ContributionTest.php
Labels: master

#23942 dev/core#3717 - Fix sorting by mapping type
  CRM/Admin/Page/Mapping.php
Labels: master

#23949 [NFC] 5.51 Release Notes - first pass
  contributor-key.yml
  release-notes/5.51.0.md
Labels: 5.51

#23951 5.51 to master
  contributor-key.yml
  release-notes/5.51.0.md
Labels: master

#23346 Fix calculation and assignment of taxAmount on contribution page confirmation
  CRM/Contribute/Form/Contribution/Confirm.php
  CRM/Contribute/Form/Contribution/Main.php
Labels: master

#23945 Enotice fix
  CRM/Admin/Page/Mapping.php
Labels: master

#23953 dev/core#3719 fix inconistent handling of job_type:label
  CRM/Core/BAO/UserJob.php
Labels: 5.51

#23934 dev/core#3713 Use front-end urls for event url tokens
  CRM/Event/Tokens.php
Labels: 5.51

#23933 Import fix - if there are no required fields validateRequiredFields should 'pass'
  CRM/Import/Parser.php
Labels: 5.51

#23956 5.51.0 release notes final changes
  release-notes.md
  release-notes/5.50.1.md
  release-notes/5.50.2.md
  release-notes/5.50.3.md
  release-notes/5.50.4.md
  release-notes/5.51.0.md
Labels: 5.51

#23958 5.51
  CRM/Core/BAO/UserJob.php
  CRM/Event/Tokens.php
  CRM/Import/Parser.php
  release-notes.md
  release-notes/5.50.1.md
  release-notes/5.50.2.md
  release-notes/5.50.3.md
  release-notes/5.50.4.md
  release-notes/5.51.0.md
Labels: master

#23084 Subscription Amount change not respected in Paypal
  CRM/Core/Payment/PayPalIPN.php
Labels: master, merge on pass

#23959 (NFC) case-xml@1 - Add example+assertions of new activity-type
  mixin/case-xml@1/example/tests/mixin/CaseTypeTest.php
  mixin/case-xml@1/example/xml/case/DuckDance.xml
Labels: master, merge on pass, has-test

#23960 [REF][PHP8.1] Fix deprecations where by calling trait static function…
  CRM/Core/Resources.php
  CRM/Core/Resources/CollectionTrait.php
  ext/search_kit/Civi/Api4/Action/SearchDisplay/AbstractRunAction.php
Labels: master, merge on pass

#23961 (NFC) mgd-php@1 - Add example+assertions for new case-type
  mixin/mgd-php@1/example/CRM/BunnyDance.mgd.php
  mixin/mgd-php@1/example/tests/mixin/ManagedCaseTypeTest.php
Labels: master, merge on pass, has-test

#23924 Angular - Support popping up an afform or other ang module via ajax modal
  Civi/Angular/AngularLoader.php
  ang/crmUi.js
  ext/afform/core/ang/af/afForm.component.js
  ext/afform/core/ang/afCore.js
  js/angular-crmResource/all.js
  js/crm.ajax.js
Labels: master

#23964 Do not escape error message
  templates/CRM/common/info.tpl
  templates/CRM/common/status.tpl
Labels: master

#23809 Fix bug whereby editing contribution_recur.amount was not updating single-line-item-template-contributions
  CRM/Contribute/BAO/ContributionRecur.php
  tests/phpunit/CRM/Contribute/BAO/ContributionRecurTest.php
Labels: master

#23925 [REF][PHP8.1] Add in type hints to fix deprecations and add in #[\Ret…
  CRM/Utils/LazyArray.php
  Civi/Api4/Generic/AbstractAction.php
  Civi/Api4/Generic/Result.php
  Civi/Api4/Service/Spec/RequestSpec.php
  Civi/Token/TokenProcessor.php
  Civi/Token/TokenRow.php
  ext/eventcart/CRM/Event/Cart/BAO/EventInCart.php
  tests/phpunit/CRM/Contact/BAO/QueryTestDataProvider.php
  tests/phpunit/CRM/Contact/Form/Search/Custom/GroupTestDataProvider.php
  tests/phpunit/CRM/Mailing/BAO/QueryTestDataProvider.php
Labels: master

#23965 Fixes core#3725 'Access CiviContribute' can't view a single contribution
  CRM/Contribute/Form/ContributionView.php
Labels: master

#23966 Fixes core#3725 'Access CiviContribute' can't view a single contribution
  CRM/Contribute/Form/ContributionView.php
Labels: merge on pass, 5.51

#23967 REF - Remove unneeded return from private fn, add comments
  Civi/Angular/AngularLoader.php
  js/crm.ajax.js
Labels: master

#23968 Fix import falling over when a note is included
  CRM/Contact/Import/Parser/Contact.php
  tests/phpunit/CRM/Contact/Import/Form/data/individual_with_note.csv
  tests/phpunit/CRM/Contact/Import/Parser/ContactTest.php
Labels: master

#23971 [REF] dev/core#3676 Add in html2text/html2text to replace usage of roundcube's version we have in packages
  CRM/Utils/String.php
  composer.json
  composer.lock
  tests/phpunit/CRM/Mailing/BaseMailingSystemTest.php
  tests/phpunit/CRM/Utils/HtmlToTextTest.php
  tools/scripts/composer/html2text_html2_text_php81_deprecation.patch
Labels: master, merge on pass

#23975 (NFC) SoapTest - Skip this test on Drupal8+ and Backdrop
  tests/phpunit/E2E/Extern/SoapTest.php
Labels: merge on pass, 5.52

#23976 5.52
  tests/phpunit/E2E/Extern/SoapTest.php
Labels: master

#23851 [REF][PHP8.1] Fix a couple of deprecations in php8.1 by specifying th…
  CRM/Core/I18n.php
  CRM/Utils/SQL/BaseParamQuery.php
Labels: master

#23946 [REF] Upgrade DOMPDF to 2.x branch
  composer.json
  composer.lock
  tools/scripts/composer/dompdf-cleanup.sh
Labels: master, merge ready

#22918 dev/drupal#171 - Allow guzzle 7 for drupal 10
  composer.json
Labels: master, merge ready

#20588 REF dev/core#2571 Move reCAPTCHA code to extension
  CRM/Campaign/Form/Petition/Signature.php
  CRM/Contribute/Form/Contribution/Main.php
  CRM/Contribute/Form/ContributionBase.php
  CRM/Event/Form/Registration.php
  CRM/Mailing/Form/Subscribe.php
  CRM/PCP/Form/PCPAccount.php
  CRM/Profile/Form.php
  ext/recaptcha/CRM/Utils/ReCAPTCHA.php
  ext/recaptcha/README.md
  ext/recaptcha/recaptcha.php
  ext/recaptcha/templates/CRM/common/ReCAPTCHA.tpl
  templates/CRM/Campaign/Form/Petition/Signature.tpl
  templates/CRM/Contribute/Form/Contribution/Main.tpl
  templates/CRM/Contribute/Form/PCP/PCPAccount.tpl
  templates/CRM/Event/Form/Registration/Register.tpl
  templates/CRM/Mailing/Form/Subscribe.tpl
  templates/CRM/PCP/Form/PCPAccount.tpl
  templates/CRM/Profile/Form/Dynamic.tpl
Labels: master, merge ready

#23977 [NFC] dompdf patch whitespace fix
  tools/scripts/composer/dompdf-cleanup.sh
Labels: master

#23978 [NFC] fix composer.lock hash
  composer.lock
Labels: master

#23932 Add support for multiple-selection of contact IDs in _civicrm_api3_custom_data_get()
  api/v3/utils.php
Labels: master

#23979 dev/core#3692 Comment fixes
  CRM/Activity/Tokens.php
Labels: master, merge on pass

#23981 dev/core#3692 Remove call to deprecated function
  tests/phpunit/Civi/CCase/SequenceListenerTest.php
Labels: master, merge on pass

#23982 dev/core#3692 Remove hard coded activity_type_id
  CRM/Contribute/BAO/Contribution.php
Labels: master, merge on pass

#23985 [NFC] Convert Deprecations in tests to exceptions
  phpunit.xml.dist
Labels: master

#23986 [NFC] Add in convertDeprecationsToExceptions='true' to core extension…
  ext/afform/core/phpunit.xml.dist
  ext/afform/mock/phpunit.xml.dist
  ext/authx/phpunit.xml.dist
  ext/civigrant/phpunit.xml.dist
  ext/contributioncancelactions/phpunit.xml.dist
  ext/ewaysingle/phpunit.xml.dist
  ext/financialacls/phpunit.xml.dist
  ext/flexmailer/phpunit.xml.dist
  ext/legacycustomsearches/phpunit.xml.dist
  ext/oauth-client/phpunit.xml.dist
  ext/payflowpro/phpunit.xml.dist
  ext/search_kit/phpunit.xml.dist
  ext/sequentialcreditnotes/phpunit.xml.dist
Labels: master

#22227 CiviCRM Standalone: base classes
  CRM/Core/CodeGen/Config.php
  CRM/Core/Permission/Standalone.php
  CRM/Utils/Hook/Standalone.php
  CRM/Utils/System/Standalone.php
  css/menubar-standalone.css
  setup/plugins/init/Standalone.civi-setup.php
  setup/res/finished.Standalone.php
  templates/CRM/common/standalone.tpl
Labels: master

#23969 Fix import falling over when a note is included
  CRM/Contact/Import/Parser/Contact.php
  tests/phpunit/CRM/Contact/Import/Form/data/individual_with_note.csv
  tests/phpunit/CRM/Contact/Import/Parser/ContactTest.php
Labels: 5.51

#23988 [NFC] Restore handling for deprecations in phpunit test runs
  ext/afform/core/phpunit.xml.dist
  ext/afform/mock/phpunit.xml.dist
  ext/authx/phpunit.xml.dist
  ext/civigrant/phpunit.xml.dist
  ext/contributioncancelactions/phpunit.xml.dist
  ext/ewaysingle/phpunit.xml.dist
  ext/financialacls/phpunit.xml.dist
  ext/flexmailer/phpunit.xml.dist
  ext/legacycustomsearches/phpunit.xml.dist
  ext/oauth-client/phpunit.xml.dist
  ext/payflowpro/phpunit.xml.dist
  ext/search_kit/phpunit.xml.dist
  ext/sequentialcreditnotes/phpunit.xml.dist
  phpunit.xml.dist
Labels: merge on pass, 5.52

#23984 [REF][PHP8.1] Upgrade oauth2-client,zetacomponents/base,htmlpurfier packages …
  composer.lock
Labels: master

#23991 Civi\Test - Fix leak in active module-list for headless test
  CRM/Core/I18n.php
  Civi/Test.php
  Civi/Test/Data.php
  setup/plugins/installDatabase/BootstrapCivi.civi-setup.php
  setup/plugins/installDatabase/Preboot.civi-setup.php
Labels: 5.52

#23992 5.52
  CRM/Core/I18n.php
  Civi/Test.php
  Civi/Test/Data.php
  setup/plugins/installDatabase/BootstrapCivi.civi-setup.php
  setup/plugins/installDatabase/Preboot.civi-setup.php
Labels: master

#23998 net_smtp upgrade to 1.10.0
  composer.json
  composer.lock
Labels: master, merge on pass

#23974 Afform - Allow groups and tags and age to be filters
  Civi/Api4/Service/Spec/Provider/ContactGetSpecProvider.php
  Civi/Api4/Service/Spec/Provider/EntityTagFilterSpecProvider.php
Labels: master

#23997 [REF][PHP8.1] Fix issues in core extensions where passing in NULL val…
  ext/afform/core/afform.php
  ext/legacycustomsearches/CRM/Contact/Form/Search/Custom/FullText.php
  ext/oauth-client/Civi/Api4/Action/OAuthContactToken/Create.php
  ext/search_kit/Civi/Api4/Action/SearchDisplay/AbstractRunAction.php
Labels: master

#24000 [REF][PHP8.1] Fix Return type hints and passing in NULL values causin…
  Civi/Payment/PropertyBag.php
Labels: master

#23995 Allow custom fields to have custom fields
  CRM/Core/BAO/CustomField.php
Labels: master

#23999 [REF][PHP8.1] A third batch of fixes where passing in NULL values cau…
  CRM/Case/XMLProcessor/Report.php
  CRM/Contact/BAO/GroupContact.php
  CRM/Contact/BAO/Relationship.php
  CRM/Contact/Form/Task/PDFTrait.php
  CRM/Core/BAO/Address.php
  CRM/Core/BAO/CustomField.php
  CRM/Core/BAO/File.php
  CRM/Core/Controller.php
  CRM/Core/Form/Renderer.php
  CRM/Core/Resources.php
  CRM/Custom/Form/CustomData.php
  CRM/Mailing/BAO/Mailing.php
  CRM/Report/Form.php
  CRM/Utils/Date.php
  CRM/Utils/File.php
  CRM/Utils/String.php
  CRM/Utils/System.php
  api/v3/utils.php
Labels: master

#24007 Fix test. Don't hide errors. (Followup to 23999)
  CRM/Contact/Form/Task/PDFTrait.php
  tests/phpunit/CRM/Contact/Form/Task/PDFLetterCommonTest.php
Labels: master

#23996 [REF][PHP8.1] Apply PR patch to fix issue in php8.1 where mysqli erro…
  composer.json
  composer.lock
Labels: master

#24004 dev/core#3736 - Fix uploaded file on message template form
  CRM/Admin/Form/MessageTemplates.php
Labels: master

#23954 Poly-fill-me-up
  composer.json
  composer.lock
Labels: master, merge on pass

#24012 add classes to the contribution view page
  templates/CRM/Contribute/Form/ContributionView.tpl
Labels: master, merge on pass

#24015 Update cweagans/composer-patches to 1.7.2 to fix delete-and-reinstall problem
  composer.lock
Labels: master, merge on pass

#24017 Lower minimum polyfill version since conflicts with drupal/core-recommended
  composer.json
  composer.lock
Labels: master, merge on pass

#24013 Afform - provide easy way to add navigation menu from the form
  CRM/Core/BAO/Navigation.php
  ext/afform/admin/ang/afGuiEditor.css
  ext/afform/admin/ang/afGuiEditor/afGuiEditor.component.js
  ext/afform/admin/ang/afGuiEditor/config-form.html
  ext/afform/core/Civi/Api4/Afform.php
  ext/afform/core/Civi/Api4/Utils/AfformSaveTrait.php
  ext/afform/core/afform.php
Labels: master

#24021 Use fontawesome icon helper for activity/Page/AJAX
  CRM/Activity/Page/AJAX.php
Labels: master, merge on pass

#24024 Add afform blocks to print summary
  ext/afform/core/afform.php
Labels: master

#24028 remove pledge status as mandatory in Pledge report
  CRM/Report/Form/Pledge/Detail.php
Labels: master

#23767 Afform - Require Authx
  ext/afform/core/info.xml
Labels: master, merge ready

#24018 [REF][PHP8.1] Batch 4 of fixing issues found in unit tests where pass…
  CRM/Contact/BAO/Contact.php
  CRM/Contact/Form/Edit/Address.php
  CRM/Core/BAO/Address.php
  CRM/Core/BAO/CustomField.php
  CRM/Core/DAO/AllCoreTables.php
  CRM/Core/Form/Task.php
  CRM/Core/Smarty/plugins/modifier.crmNumberFormat.php
  CRM/Financial/BAO/Payment.php
  CRM/Financial/BAO/PaymentProcessor.php
  CRM/Import/Parser.php
  CRM/Logging/ReportDetail.php
  CRM/Report/Form.php
  CRM/Utils/Date.php
  CRM/Utils/File.php
  CRM/Utils/Mail.php
  CRM/Utils/System.php
  api/v3/CustomValue.php
  api/v3/Mailing.php
  api/v3/Profile.php
  api/v3/utils.php
Labels: master

#24025 dev/core#3050 - (Alternate) Fix crash removing an entry from a batch
  CRM/Financial/Page/BatchTransaction.php
  templates/CRM/Financial/Page/BatchTransaction.tpl
Labels: master

#24031 Fix 'Pledge Made Date' display to show date and not time
  CRM/Report/Form/Pledge/Detail.php
Labels: master

#24027 Status Check - Report the overall status (accurately)
  CRM/Utils/Check.php
Labels: master, merge ready

#24035 Fix ActionLog BAO to not overwrite existing data
  CRM/Core/BAO/ActionLog.php
Labels: master, merge on pass

#23895 SearchKit - Switch to APIv4 for managed entities
  ext/search_kit/managed/SearchDisplayType.mgd.php
  ext/search_kit/managed/TagUsedFor.mgd.php
Labels: master

#23970 APIv4 - Fix mishandling of boolean custom values
  Civi/Api4/Generic/AbstractAction.php
  tests/phpunit/api/v4/Custom/FalseNotEqualsZeroTest.php
Labels: master

#24016 Afform - Post-submit redirect tokens
  ext/afform/admin/ang/afGuiEditor.css
  ext/afform/admin/ang/afGuiEditor/afGuiTokenSelect.html
  ext/afform/admin/ang/afGuiEditor/afGuiTokenSelect.js
  ext/afform/admin/ang/afGuiEditor/config-form.html
  ext/afform/core/Civi/Api4/Action/Afform/Submit.php
  ext/afform/core/ang/af/afForm.component.js
Labels: master

#24030 dev/core#3490 - Apply extension updates after core updates
  CRM/Extension/Upgrades.php
  CRM/Queue/Task.php
  CRM/Upgrade/DispatchPolicy.php
  CRM/Upgrade/Form.php
  CRM/Upgrade/Incremental/Base.php
  Civi/Core/CiviEventDispatcher.php
  Civi/Core/Container.php
Labels: master

#23896 Afform - Switch to APIv4 for managed afform_type option group
  ext/afform/core/managed/AfformType.mgd.php
Labels: master, merge on pass

#24038 [REF] Upgrade DOMPDF to 2.x branch
  composer.json
  composer.lock
  tools/scripts/composer/dompdf-cleanup.sh
Labels: 5.52

#24037 [REF] Upgrade DOMPDF to 2.x branch
  composer.json
  composer.lock
  tools/scripts/composer/dompdf-cleanup.sh
Labels: 5.51

#24044 composer.json - Update scssphp and related libraries (for PHP 8.1)
  composer.json
  composer.lock
Labels: master

#24043 (NFC) CRM_Core_Permission - More docblocks
  CRM/Core/Permission.php
  CRM/Core/Permission/Base.php
Labels: master

#23875 Set target="_blank" on external footer links
  templates/CRM/common/footer.tpl
Labels: master

#24045 [REF][PHP8.1] Update phpoffice/phpword and tecnickcom/tcpdf packages…
  composer.lock
Labels: master

#24046 [REF][PHP8.1] Apply patches from upstream to ensure league/csv can work on php8.1
  composer.json
  composer.lock
  tools/scripts/composer/leage_csv_fputcsv.patch
Labels: master

#24010 dev/core#3737 ensure tasks are loaded (notice fix)
  CRM/Contribute/Task.php
Labels: master, merge ready

#24040 dev/core#3490 - Upgrader - Show additional notice about running extension upgrades
  CRM/Upgrade/Form.php
Labels: 5.52

#24039 Upgrader - Add snapshots for 5.52's data modifications
  CRM/Upgrade/Incremental/php/FiveFiftyTwo.php
Labels: 5.52

#24041 Upgrader - Show additional notice about running extension upgrades
  CRM/Upgrade/Form.php
Labels: 5.51

#24048 remove start/end date as mandatory in Demographics report
  CRM/Report/Form/Case/Demographics.php
Labels: master

#24036 API - Consistently save custom data for v3 & v4
  CRM/ACL/BAO/ACLEntityRole.php
  CRM/Core/BAO/ActionSchedule.php
  CRM/Core/BAO/Domain.php
  CRM/Core/BAO/RecurringEntity.php
  CRM/Core/BAO/Website.php
  CRM/Mailing/BAO/Mailing.php
  CRM/Member/BAO/MembershipBlock.php
  CRM/Pledge/BAO/PledgeBlock.php
  api/v3/utils.php
Labels: master

#24047 dev/core#3751 - export error fixes for multi-select contact reference custom field
  CRM/Export/BAO/ExportProcessor.php
Labels: master

#24052 APIv4 - Allow values to start with a dollar sign in chaining
  Civi/Api4/Provider/ActionObjectProvider.php
Labels: master

#24055 (NFC) HookStyleListener - Comments
  Civi/Core/CiviEventDispatcher.php
  Civi/Core/Event/HookStyleListener.php
Labels: master

#24057 Add whitespace to exception message
  Civi/Api4/Service/Spec/SpecGatherer.php
Labels: master, merge on pass

#24068 Merge forward 5.52-rc => master
  CRM/Upgrade/Form.php
  CRM/Upgrade/Incremental/php/FiveFiftyTwo.php
  release-notes.md
  release-notes/5.51.0.md
  release-notes/5.52.0.md
Labels: master

#24050 dev/financial#201 Fix PaypalPro IPN to refer to correct option group
  CRM/Core/Payment/PayPalProIPN.php
Labels: master

#24065 Avoid sending blank invoices
  CRM/Core/BAO/MessageTemplate.php
Labels: master

#24032 [REF][PHP8.1][INTL] Remove dependency on strftime function by using t…
  CRM/Contribute/Form/ContributionCharts.php
  CRM/Core/Payment/Realex.php
  CRM/Utils/Date.php
  tests/phpunit/CRM/Utils/DateTest.php
Labels: master, has-test

#24064 Log a bit more deprecation info
  CRM/Core/Error.php
Labels: master

#23870 dev/core#3694 - get preview working & tested for offline-contribution receipt
  CRM/Contribute/WorkflowMessage/Contribution/BasicContribution.php
  CRM/Contribute/WorkflowMessage/ContributionTrait.php
  CRM/Financial/BAO/Order.php
  Civi/Test/ExampleData/Contribution/Euro5990.php
  sql/civicrm_generated.mysql
  tests/phpunit/CRM/Contribute/Form/ContributionTest.php
  tests/phpunit/api/v4/Entity/WorkflowMessageTest.php
  xml/templates/message_templates/contribution_offline_receipt_html.tpl
  xml/templates/message_templates/contribution_offline_receipt_text.tpl
Labels: master

#24066 [NFC] 5.52 Release notes first pass
  contributor-key.yml
  release-notes/5.52.0.md
Labels: 5.52

#24074 5.52 to master
  contributor-key.yml
  release-notes/5.52.0.md
Labels: master

#24073 Afform - show icon on button only if icon is selected
  ang/crmUi.js
Labels: master, merge on pass

#24072 Case custom field with clickable contact reference
  templates/CRM/Case/Page/CustomDataView.tpl
Labels: master

#24078 Update contributor-key.yml
  contributor-key.yml
Labels: master, merge on pass

#23413 Afform - Add "clear" button to non-required radios
  ext/afform/admin/ang/afGuiEditor/inputType/Radio.html
  ext/afform/core/ang/af/fields/Radio.html
Labels: master

#24059 dev/core#3749 Fix process pledges to throw exception when civiPledge disabled
  CRM/Pledge/BAO/Pledge.php
  api/v3/Job.php
Labels: master

#24077 Upgrade task to handle %A date format specifier change
  CRM/Upgrade/Incremental/php/FiveFiftyThree.php
Labels: master

#24008 [REF][PHP8.1] Replace usage of the date_format modifer with crmDate t…
  CRM/Utils/Date.php
  sql/civicrm_generated.mysql
  tests/phpunit/CRM/Contribute/Form/Task/PDFLetterCommonTest.php
  tests/phpunit/CRM/Utils/DateTest.php
  tests/templates/message_templates/event_online_receipt_text.tpl
  xml/templates/message_templates/event_offline_receipt_html.tpl
  xml/templates/message_templates/event_offline_receipt_text.tpl
  xml/templates/message_templates/event_online_receipt_html.tpl
  xml/templates/message_templates/event_online_receipt_text.tpl
  xml/templates/message_templates/event_registration_receipt_html.tpl
  xml/templates/message_templates/event_registration_receipt_text.tpl
  xml/templates/message_templates/participant_confirm_html.tpl
  xml/templates/message_templates/participant_confirm_text.tpl
  xml/templates/message_templates/participant_expired_html.tpl
  xml/templates/message_templates/participant_expired_text.tpl
  xml/templates/message_templates/participant_transferred_html.tpl
  xml/templates/message_templates/participant_transferred_text.tpl
  xml/templates/message_templates/payment_or_refund_notification_html.tpl
  xml/templates/message_templates/payment_or_refund_notification_text.tpl
Labels: master, merge on pass

#24084 fix broken url for wordpress in example code
  CRM/Api4/Page/Api4Explorer.php
Labels: master, merge on pass

#24089 APIv4 export action: find DAO by ID instead of just calling the constructor and setting the ID
  Civi/Api4/Generic/ExportAction.php
Labels: master, merge on pass

#24079 Fix Angular datepicker to keep up with $digest cycle
  ang/crmUi.js
  tests/karma/unit/crmMailingRadioDateSpec.js
Labels: master, merge on pass

#24091 [NFC] Resolve phpunit warning about using assertContains on strings
  tests/phpunit/CRM/Member/Import/Parser/MembershipTest.php
Labels: master, merge on pass

#24093 [REF][PHP8.1] Apply patch in PHPWord to fix passing in null value into strlen in validating locale
  composer.json
  composer.lock
  distmaker/dists/common.sh
  guzzle_php81_shim.php
  tools/scripts/composer/guzzle-mockhandler-fix.sh
  tools/scripts/composer/zetacomponents-php-81-civicrm-custom.patch
Labels: master

#24019 [REF][PHP8.1] Apply patches to pear/log and zetacomponents/mail packa…
  composer.json
  composer.lock
  tools/scripts/composer/zetacomponents-php-81-civicrm-custom.patch
Labels: master

#24092 [REF][PHP8.1] Do not set auto_detect_line_endings to true on php vers…
  templates/CRM/common/civicrm.settings.php.template
Labels: master

#24067 Fix #3756 hook_civicrm_geocoderFormat does not alter address components
  CRM/Utils/Geocode/Google.php
Labels: 5.52

#24083 [REF][PHP8.1] Permit single quotes within html attributes
  CRM/Core/Page.php
Labels: master

#24081 [NFC][PHP8.1] Ensure that Trait function is only accessed by classes …
  tests/phpunit/CRM/Core/Resources/CollectionTestTrait.php
Labels: master

#24094 Fix regex on windows
  tools/scripts/composer/guzzle-mockhandler-fix.sh
Labels: master

#24097 dev/core#3765 Ensure that CiviCRM's Guzzle shim does not conflict with Drupal's guzzle shim
  guzzle_php81_shim.php
Labels: master, merge on pass

#24095 5.52
  CRM/Utils/Geocode/Google.php
Labels: master

#24096 Fix grep in guzzle mock patch
  tools/scripts/composer/guzzle-mockhandler-fix.sh
Labels: master, merge on pass

#24100 [REF] Fix Test fails on import by ensuring that Month Abbreviations a…
  CRM/Utils/Date.php
Labels: master
