Repository civicrm/civicrm-core, pull requests merged in 2022-09, with the labels that each got.

#24419 Contribution import - test notes, cleanup notes, fix regression found in test writing
  CRM/Contribute/Import/Parser/Contribution.php
  tests/phpunit/CRM/Contribute/Import/Parser/ContributionTest.php
  tests/phpunit/CRM/Contribute/Import/Parser/data/contributions.csv
Labels: master, has-test

#24426 Deprecate preferred_mail_format column
  CRM/Contact/DAO/Contact.php
  xml/schema/Contact/Contact.xml
Labels: master, merge on pass

#24430 APIv4 - Promote option `$language` from DAOActionTrait to AbstractAction
  Civi/Api4/Generic/AbstractAction.php
  Civi/Api4/Generic/Traits/DAOActionTrait.php
  tests/phpunit/api/v4/Action/AbstractActionFunctionTest.php
Labels: master, merge on pass

#24439 Fix PHPDoc comment for CRM_Financial_BAO_FinancialItem::add
  CRM/Financial/BAO/FinancialItem.php
Labels: master, merge on pass

#24394 When updating userJob status to match queue status skip permission check
  CRM/Core/BAO/UserJob.php
Labels: master, merge on pass

#24440 dev/core#3833 Update CRM_Extension_Downloader to not use dynamic properties
  CRM/Queue/Runner.php
Labels: master

#24436 dev/core#3831 Deprecated string interpolation
  CRM/Core/CodeGen/Specification.php
  CRM/Event/BAO/Participant.php
  CRM/Extension/Container/Default.php
  CRM/Extension/Downloader.php
  CRM/Mailing/BAO/MailingJob.php
  CRM/Mailing/BAO/SMSJob.php
  CRM/Report/Form/Case/Summary.php
  Civi/API/Provider/MagicFunctionProvider.php
  tests/phpunit/CRM/Core/Payment/ProcessorFormTest.php
  tests/phpunit/CRM/Event/BAO/ChangeFeeSelectionTest.php
  tests/phpunit/CRM/Utils/SignerTest.php
Labels: master

#24425 Remove method getActionAttribute
  CRM/Core/Selector/Base.php
Labels: master

#24434 dev/financial#208 - Fix crash for invoice button
  CRM/Contribute/Form/Task/PDF.php
  tests/phpunit/CRM/Contribute/Form/ContributionViewTest.php
Labels: master, merge on pass, has-test

#24435 ManagedEntity - Ensure managed record is consistently deleted
  CRM/Core/ManagedEntities.php
Labels: master

#24438 dev/core#3833 Update CRM_Extension_Downloader to not use dynamic properties
  CRM/Extension/Downloader.php
Labels: master

#24174 Message Templates - Allow rendering & previewing of translated messages
  CRM/Core/BAO/MessageTemplate.php
  CRM/Core/BAO/TranslateGetWrapper.php
  CRM/Core/BAO/Translation.php
  Civi/Api4/Action/WorkflowMessage/Render.php
  Civi/Api4/Generic/DAOGetAction.php
  ext/message_admin/ang/crmMsgadm/Edit.js
  ext/message_admin/ang/crmMsgadm/Preview.js
  tests/events/hook_civicrm_alterMailParams.evch.php
  tests/phpunit/CRM/Core/BAO/MessageTemplateTest.php
  tests/phpunit/api/v4/Entity/ConformanceTest.php
  tests/phpunit/api/v4/Options/TranslationModeTest.php
Labels: master, merge on pass

#24443 Remove function after two years of noisy deprecation
  CRM/Case/XMLProcessor.php
Labels: master, merge on pass

#24235 Add support for Contact tokens in welcome email using TokenProcessor
  CRM/Mailing/Event/BAO/Confirm.php
  CRM/Mailing/Event/BAO/Resubscribe.php
  CRM/Mailing/Event/BAO/Subscribe.php
  CRM/Mailing/Event/BAO/Unsubscribe.php
Labels: master

#24316 Use preferred `{contact.email_greeting_display}` token over deprecated `{contact.email_greeting}` in ALL templates
  Civi/Test/ExampleData/Contact/Alex.php
  tests/phpunit/CRM/Case/WorkflowMessage/CaseActivityTest.php
  tests/phpunit/CRM/Upgrade/Incremental/BaseTest.php
  tests/phpunit/api/v4/Entity/ExampleDataTest.php
  xml/templates/message_templates/contribution_offline_receipt_html.tpl
  xml/templates/message_templates/contribution_offline_receipt_text.tpl
  xml/templates/message_templates/contribution_online_receipt_html.tpl
  xml/templates/message_templates/contribution_online_receipt_text.tpl
  xml/templates/message_templates/contribution_recurring_billing_html.tpl
  xml/templates/message_templates/contribution_recurring_billing_text.tpl
  xml/templates/message_templates/contribution_recurring_cancelled_html.tpl
  xml/templates/message_templates/contribution_recurring_cancelled_text.tpl
  xml/templates/message_templates/contribution_recurring_edit_html.tpl
  xml/templates/message_templates/contribution_recurring_edit_text.tpl
  xml/templates/message_templates/contribution_recurring_notify_html.tpl
  xml/templates/message_templates/contribution_recurring_notify_text.tpl
  xml/templates/message_templates/event_offline_receipt_html.tpl
  xml/templates/message_templates/event_offline_receipt_text.tpl
  xml/templates/message_templates/event_online_receipt_html.tpl
  xml/templates/message_templates/event_online_receipt_text.tpl
  xml/templates/message_templates/event_registration_receipt_html.tpl
  xml/templates/message_templates/event_registration_receipt_text.tpl
  xml/templates/message_templates/membership_autorenew_billing_html.tpl
  xml/templates/message_templates/membership_autorenew_billing_text.tpl
  xml/templates/message_templates/membership_autorenew_cancelled_html.tpl
  xml/templates/message_templates/membership_autorenew_cancelled_text.tpl
  xml/templates/message_templates/membership_offline_receipt_html.tpl
  xml/templates/message_templates/membership_offline_receipt_text.tpl
  xml/templates/message_templates/membership_online_receipt_html.tpl
  xml/templates/message_templates/membership_online_receipt_text.tpl
  xml/templates/message_templates/participant_transferred_html.tpl
  xml/templates/message_templates/participant_transferred_text.tpl
  xml/templates/message_templates/payment_or_refund_notification_html.tpl
  xml/templates/message_templates/pcp_owner_notify_html.tpl
  xml/templates/message_templates/pcp_owner_notify_text.tpl
  xml/templates/message_templates/pcp_supporter_notify_html.tpl
  xml/templates/message_templates/pcp_supporter_notify_text.tpl
  xml/templates/message_templates/petition_confirmation_needed_html.tpl
  xml/templates/message_templates/petition_confirmation_needed_text.tpl
  xml/templates/message_templates/petition_sign_html.tpl
  xml/templates/message_templates/petition_sign_text.tpl
  xml/templates/message_templates/sample/Sample Responsive Design Newsletter - Single Column.tpl
Labels: master, sig:performance

#24437 [REF] ManagedEntities - Move deprecated function
  CRM/Case/ManagedEntities.php
  CRM/Core/ManagedEntities.php
  tests/phpunit/CRM/Core/ManagedEntitiesTest.php
Labels: master, merge on pass

#24447 (NFC) Fix sprintf syntax
  Civi/Api4/Extension.php
Labels: master, merge on pass

#24451 Afform - Fix date range filters for search displays
  ext/search_kit/ang/crmSearchDisplay/traits/searchDisplayBaseTrait.service.js
Labels: master

#24442 Increase the deprecation on some unused functions
  CRM/Import/Parser.php
Labels: master, merge on pass

#24452 CRM_Queue_Queue - Add 'getStatistic($name)'. Deprecate 'numberOfItems()'
  CRM/Core/BAO/UserJob.php
  CRM/Queue/Queue.php
  CRM/Queue/Queue/Memory.php
  CRM/Queue/Queue/SqlTrait.php
  Civi/Test/QueueTestTrait.php
  templates/CRM/Queue/Page/Runner.tpl
  tests/phpunit/CRM/Queue/Queue/SqlTest.php
  tests/phpunit/CRM/Queue/QueueTest.php
  tests/phpunit/CRM/Queue/RunnerTest.php
  tests/phpunit/api/v4/Entity/QueueTest.php
Labels: master

#24408 Fix queue runner not progressing
  CRM/Queue/Queue/Memory.php
  CRM/Queue/Queue/SqlTrait.php
  templates/CRM/Queue/Page/Runner.tpl
Labels: master, merge on pass, merge ready

#24453 [NFC] Add in Unit test to test domain token replacement in Reply process
  tests/phpunit/CRM/Mailing/MailingSystemTest.php
Labels: master, merge on pass

#24427 Stop PHP warning on installations with no contributions
  CRM/Contribute/BAO/Contribution/Utils.php
  CRM/Contribute/Form/ContributionCharts.php
Labels: master, merge on pass

#24441 Fix Import metadata to use apiv4 for contact on contribution imports
  CRM/Contact/Import/Parser/Contact.php
  CRM/Contribute/Import/Form/MapField.php
  CRM/Contribute/Import/Parser/Contribution.php
  CRM/Import/DataSource.php
  CRM/Import/Parser.php
  CRM/Upgrade/Incremental/php/FiveFiftyFour.php
  tests/phpunit/CRM/Contribute/Import/Parser/ContributionTest.php
  tests/phpunit/CRMTraits/Custom/CustomDataTrait.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: master, has-test

#23604 Afform - Implement client-side validation of required fields
  ext/afform/core/Civi/Afform/AfformMetadataInjector.php
  ext/afform/core/ang/af/afField.html
  ext/afform/core/ang/af/afForm.component.js
  ext/afform/core/ang/af/fields/ChainSelect.html
  ext/afform/core/ang/af/fields/CheckBox.html
  ext/afform/core/ang/af/fields/Date.html
  ext/afform/core/ang/af/fields/EntityRef.html
  ext/afform/core/ang/af/fields/File.html
  ext/afform/core/ang/af/fields/Number.html
  ext/afform/core/ang/af/fields/Text.html
  ext/afform/core/ang/af/fields/TextArea.html
Labels: master

#24444 Languages - Dropdown lists should reflect supported languages
  Civi/Api4/Action/GetActions.php
  Civi/Api4/Generic/AbstractAction.php
  ext/message_admin/CRM/MessageAdmin/Settings.php
  ext/message_admin/ang/crmMsgadm/Workflow.js
Labels: master

#24304 dev/core#3778 Add code hook to set civicrm_participant.created_id
  CRM/Event/BAO/Participant.php
  tests/phpunit/CRM/Event/BAO/ParticipantTest.php
  tests/phpunit/CRM/Utils/TokenConsistencyTest.php
Labels: master, merge ready

#24429 Mark some more fields deprecated or readonly
  xml/schema/Contact/Contact.xml
  xml/schema/Core/Address.xml
  xml/schema/Core/Email.xml
  xml/schema/Core/Phone.xml
Labels: master

#24461 Re-run regen
  sql/civicrm_generated.mysql
Labels: master, merge on pass

#24462 [REF] Remove calls to settings from angularjs to php layer to assist …
  CRM/Core/Page/AJAX/Attachment.php
  CRM/Mailing/Info.php
  ang/crmAttachment.js
  ang/crmMailing/EditRecipCtrl.js
Labels: master, merge on pass

#24463 [Ref] [Import] Simplify form event MapField to use shared rule (Participant)
  CRM/Event/Import/Form/MapField.php
Labels: master, merge on pass

#24465 Remove silly constants for Contact Types (import)
  CRM/Contact/Import/Form/DataSource.php
  CRM/Contact/Page/AJAX.php
  CRM/Custom/Import/Form/DataSource.php
  CRM/Import/Form/DataSource.php
  CRM/Import/Forms.php
  CRM/Import/ImportProcessor.php
  CRM/Import/Parser.php
  ext/civiimport/tests/phpunit/CiviApiImportTest.php
  tests/phpunit/CRM/Activity/Import/Parser/ActivityTest.php
  tests/phpunit/CRM/Contact/Import/Form/DataSourceTest.php
  tests/phpunit/CRM/Contact/Import/Form/MapFieldTest.php
  tests/phpunit/CRM/Contact/Import/Parser/ContactTest.php
  tests/phpunit/CRM/Contribute/Import/Parser/ContributionTest.php
  tests/phpunit/CRM/Event/Import/Parser/ParticipantTest.php
  tests/phpunit/CRM/Import/DataSource/CsvTest.php
  tests/phpunit/CRM/Member/Import/Parser/MembershipTest.php
  tests/phpunit/CRMTraits/Import/ParserTrait.php
Labels: master, merge on pass

#24464 [Ref] [Import] Simplify form event MapField (Contact)
  CRM/Contact/Import/Form/MapField.php
Labels: master, merge on pass

#24473 Follow up code simplification - no need to map 'Individual' to 'Individual'
  CRM/Import/Parser.php
Labels: master, merge on pass

#24474 [REF] Extract rule-loading function
  CRM/Import/Parser.php
Labels: master, merge on pass

#24475 Adjust contribution metadata to filter at display not load
  CRM/Contribute/Import/Form/MapField.php
  CRM/Import/Forms.php
  CRM/Import/Parser.php
Labels: master, merge on pass

#24468 allow contact reference custom fields to have lengths greater than 255 characters
  CRM/Core/BAO/CustomField.php
Labels: master

#24471 Afform - Fix setting default value for date filter fields
  ext/afform/admin/ang/afGuiEditor/elements/afGuiField.component.js
  ext/afform/core/ang/af/afField.component.js
Labels: master

#24478 5.53.0 release notes late changes
  release-notes.md
  release-notes/5.51.1.md
  release-notes/5.51.2.md
  release-notes/5.51.3.md
  release-notes/5.52.1.md
  release-notes/5.52.2.md
  release-notes/5.53.0.md
Labels: 5.53

#24481 MailingSystemTest - Fix invalid PHP
  tests/phpunit/CRM/Mailing/MailingSystemTest.php
Labels: master, merge on pass

#24484 [REF] Cleanup code to getAvailableFields on Contribution MapField
  CRM/Contribute/Import/Form/MapField.php
  CRM/Import/Form/MapField.php
  CRM/Import/Parser.php
Labels: master

#24483 Remove remnant of the great psuedoconstant title fight
  CRM/Contribute/Import/Form/MapField.php
  CRM/Import/Form/MapField.php
  CRM/Import/Parser.php
Labels: master

#24409 Fix some notices on New Contribution page (smarty)
  templates/CRM/Contribute/Form/Contribution.tpl
Labels: master

#24480 ClassScanner - Fix guard for preboot cache scenario
  Civi/Core/ClassScanner.php
Labels: master

#24485 dev/core#1172 Fix Contribution import to handle ContributionSoft in a storable way
  CRM/Contact/Import/MetadataTrait.php
  CRM/Contribute/Import/Form/MapField.php
  CRM/Contribute/Import/Parser/Contribution.php
  CRM/Import/Form/MapField.php
  CRM/Import/Forms.php
  CRM/Import/Parser.php
  tests/phpunit/CRM/Contribute/Import/Parser/ContributionTest.php
  tests/phpunit/CRMTraits/Import/ParserTrait.php
Labels: master

#24486 Move header handling to the Form layer in import
  CRM/Contact/Import/MetadataTrait.php
  CRM/Contribute/Import/Parser/Contribution.php
  CRM/Import/Forms.php
  CRM/Import/Parser.php
Labels: master

#24490 File::findFiles - Save 200 million nanoseconds
  CRM/Utils/File.php
Labels: master, merge on pass

#24332 Fix email notices on email edit block
  CRM/Contact/Form/Edit/Email.php
  CRM/Contact/Form/Location.php
Labels: master, sig:secure-smarty

#24489 Adding better wording to Events page for matching dates
  templates/CRM/Event/Page/EventInfo.tpl
Labels: master, merge ready

#24428 dev/financial#192 Fallback to custom currency object for codes which Brick\Money does not support.
  CRM/Utils/Money.php
  Civi/Core/Format.php
  tests/phpunit/Civi/Core/FormatTest.php
Labels: master, merge ready

#24492 (dev/core#3790) Pledge status is missing on View Pledge page
  CRM/Pledge/Form/PledgeView.php
Labels: master

#24493 (REF) SettingsMetadata - Small cleanup to prevent duplicate slashes
  Civi/Core/SettingsMetadata.php
Labels: master

#24495 More PHPdoc fixes
  CRM/Contact/BAO/ContactType.php
  CRM/Core/Form/RecurringEntity.php
  CRM/Core/Key.php
  CRM/Core/OptionValue.php
  CRM/Core/Payment/Form.php
Labels: master, merge on pass

#24448 SearchKit - Better support for calculated fields as Afform filters
  Civi/Api4/Service/Spec/SpecFormatter.php
  ext/afform/admin/Civi/Api4/Action/Afform/LoadAdminData.php
  ext/afform/admin/ang/afGuiEditor/afGuiSearch.component.js
  ext/afform/admin/ang/afGuiEditor/afGuiSearch.html
  ext/afform/admin/ang/afGuiEditor/elements/afGuiContainer.component.js
  ext/afform/admin/ang/afGuiEditor/elements/afGuiField.component.js
  ext/afform/core/Civi/Afform/AfformMetadataInjector.php
  ext/afform/mock/ang/testContactEmailSearchForm.aff.html
  ext/search_kit/Civi/Search/AfformSearchMetadataInjector.php
  ext/search_kit/Civi/Search/Meta.php
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/SearchAfformTest.php
Labels: master, has-test

#24501 Improve contribution import error handling
  CRM/Contact/Import/Parser/Contact.php
  CRM/Contribute/Import/Parser/Contribution.php
Labels: master, merge on pass

#24149 🎁 CiviEvent, Event Dashboard, iCal links are inside the h3 styling move out and add spacing
  templates/CRM/Event/Page/DashBoard.tpl
Labels: master

#24503 report cleanup
  templates/CRM/Report/Form/Contact/Relationship.tpl
Labels: master

#24505 SearchKit - Show other FK fields in the bridge join selector
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdmin.component.js
Labels: master

#24504 report clean up templates
  templates/CRM/Report/Form/Member/ContributionDetail.tpl
  templates/CRM/Report/Form/Member/Detail.tpl
  templates/CRM/Report/Form/Member/Lapse.tpl
  templates/CRM/Report/Form/Member/Summary.tpl
  templates/CRM/Report/Form/Membership/Summary.tpl
Labels: master, merge on pass

#24506 dev/core#3837 - Error about form BAO deprecation when saving contact after checking a box for preferred communication method
  CRM/Contact/Form/Contact.php
Labels: merge on pass, 5.53

#24502 Fix unreleased regression on soft credit imports
  CRM/Contribute/Import/Parser/Contribution.php
  CRM/Import/Parser.php
  tests/phpunit/CRM/Contribute/Import/Parser/ContributionTest.php
  tests/phpunit/CRM/Contribute/Import/Parser/data/contributions_amount_validate.csv
Labels: master, has-test

#24507 BAO regen
  CRM/Contact/DAO/Contact.php
  CRM/Core/DAO/Address.php
  CRM/Core/DAO/Email.php
  CRM/Core/DAO/Phone.php
Labels: master, merge on pass

#24508 report clean up templates
  templates/CRM/Report/Form/Mailing/Bounce.tpl
  templates/CRM/Report/Form/Mailing/Clicks.tpl
  templates/CRM/Report/Form/Mailing/Detail.tpl
  templates/CRM/Report/Form/Mailing/Opened.tpl
  templates/CRM/Report/Form/Mailing/Summary.tpl
Labels: master, merge on pass

#24181 SearchKit - Allow aggreation by partial dates
  Civi/Api4/Query/SqlExpression.php
  Civi/Api4/Query/SqlFunction.php
  Civi/Api4/Query/SqlFunctionAVG.php
  Civi/Api4/Query/SqlFunctionCOUNT.php
  Civi/Api4/Query/SqlFunctionEXTRACT.php
  Civi/Api4/Query/SqlFunctionGROUP_CONCAT.php
  Civi/Api4/Query/SqlFunctionMAX.php
  Civi/Api4/Query/SqlFunctionMIN.php
  Civi/Api4/Query/SqlFunctionSUM.php
  ext/search_kit/ang/crmSearchAdmin.module.js
  ext/search_kit/ang/crmSearchAdmin/crmSearchClause.component.js
  ext/search_kit/ang/crmSearchAdmin/crmSearchFunction.component.js
  ext/search_kit/ang/crmSearchAdmin/crmSearchFunction.html
  ext/search_kit/ang/crmSearchAdmin/crmSearchFunctionFlag.component.js
  ext/search_kit/ang/crmSearchAdmin/crmSearchFunctionFlag.html
  tests/phpunit/api/v4/Action/SqlFunctionTest.php
Labels: master

#24513 dev/core#3838 - Addressee token evaluates middle_name as literal string null
  CRM/Contact/BAO/Contact.php
Labels: master

#24510 Add unit test & handling for processing from UserJob configuration rather than form submitted values
  CRM/Contribute/Import/Parser/Contribution.php
  tests/phpunit/CRM/Contribute/Import/Parser/ContributionTest.php
  tests/phpunit/CRM/Contribute/Import/Parser/data/soft_credit_extended.csv
Labels: master, has-test

#24512 AdminUI - Add SearchKit-based screen for Administer Contact Types
  CRM/Admin/Form/ContactType.php
  CRM/Admin/Page/ContactType.php
  CRM/Contact/BAO/ContactType.php
  CRM/Contact/DAO/ContactType.php
  CRM/Core/xml/Menu/Admin.xml
  CRM/Utils/Check/Component/ContactTypes.php
  Civi/Api4/ContactType.php
  Civi/Api4/Generic/DAODeleteAction.php
  ext/civicrm_admin_ui/ang/afsearchAdminContactTypes.aff.html
  ext/civicrm_admin_ui/ang/afsearchAdminContactTypes.aff.json
  ext/civicrm_admin_ui/managed/SavedSearch_Administer_Contact_Types.php
  ext/search_kit/Civi/Api4/Action/SearchDisplay/AbstractRunAction.php
  ext/search_kit/Civi/Search/Admin.php
  ext/search_kit/ang/crmSearchAdmin.module.js
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdminDisplay.component.js
  ext/search_kit/ang/crmSearchAdmin/displays/common/searchButtonConfig.html
  ext/search_kit/ang/crmSearchDisplay/AddButton.html
  ext/search_kit/ang/crmSearchDisplay/traits/searchDisplayBaseTrait.service.js
  ext/search_kit/ang/crmSearchDisplayGrid/crmSearchDisplayGrid.html
  ext/search_kit/ang/crmSearchDisplayList/crmSearchDisplayList.html
  ext/search_kit/ang/crmSearchDisplayTable/crmSearchDisplayTable.html
  xml/schema/Contact/ContactType.xml
Labels: master

#24514 SearchKit - Fix arithmetic in WHERE clause
  Civi/Api4/Query/Api4SelectQuery.php
  tests/phpunit/api/v4/Action/SqlExpressionTest.php
Labels: master, has-test

#24515 upmerge #24506 - got stuck in limbo between branches
  CRM/Contact/Form/Contact.php
Labels: merge on pass, 5.54

#24519 pledge template clean for reports
  templates/CRM/Report/Form/Pledge/Detail.tpl
  templates/CRM/Report/Form/Pledge/Pbnp.tpl
  templates/CRM/Report/Form/Pledge/Summary.tpl
Labels: master, merge on pass

#24521 Deprecate handling for removed silly constant
  CRM/Contact/Import/Form/MapField.php
  CRM/Import/ImportProcessor.php
  tests/phpunit/CRM/Contact/Import/Form/MapFieldTest.php
Labels: master

#24517 [REF] Update Zetacomponents/mail to be 1.9.4
  composer.json
  composer.lock
Labels: 5.54

#24523 5.54
  composer.json
  composer.lock
Labels: master

#24264 Afform - Store all values in submission record
  ext/afform/core/Civi/Afform/Event/AfformSubmitEvent.php
  ext/afform/core/Civi/Api4/Action/Afform/AbstractProcessor.php
  ext/afform/core/Civi/Api4/Action/Afform/Submit.php
  ext/afform/core/Civi/Api4/Action/Afform/SubmitFile.php
  ext/afform/mock/tests/phpunit/api/v4/AfformContactUsageTest.php
Labels: master, has-test

#24522 dev/core#3847 Display id of missing custom field in error message
  CRM/Core/BAO/CustomField.php
Labels: master, merge on pass

#23074 dev/financial#201 Do not add pledge statuses to Contribution statuses
  xml/templates/civicrm_data.tpl
Labels: master

#24527 Wording typo in pledge reminder message template
  xml/templates/message_templates/pledge_reminder_html.tpl
  xml/templates/message_templates/pledge_reminder_text.tpl
Labels: master, merge on pass

#24532 Remove references to old temp table names
  CRM/Admin/Form/Setting/UF.php
  CRM/Core/Config.php
  CRM/Core/DAO.php
  CRM/Logging/Schema.php
Labels: merge on pass, 5.54

#24533 Re run regen
  sql/civicrm_generated.mysql
Labels: master, merge on pass

#24534 Replace CRM_Core_Exception aliases - Civi dir
  Civi/API/Api3SelectQuery.php
  Civi/API/Provider/ProviderInterface.php
  Civi/API/Provider/ReflectionProvider.php
  Civi/API/Provider/StaticProvider.php
  Civi/API/Provider/WrappingProvider.php
  Civi/API/SelectQuery.php
  Civi/API/Subscriber/APIv3SchemaAdapter.php
  Civi/API/Subscriber/DynamicFKAuthorization.php
  Civi/API/Subscriber/I18nSubscriber.php
  Civi/API/WhitelistRule.php
  Civi/Api4/Action/Address/GetCoordinates.php
  Civi/Api4/Action/Contact/Delete.php
  Civi/Api4/Action/Contact/GetDuplicates.php
  Civi/Api4/Action/Queue/ClaimItems.php
  Civi/Api4/Action/Queue/RunItems.php
  Civi/Api4/Action/Setting/AbstractSettingAction.php
  Civi/Api4/Action/System/RotateKey.php
  Civi/Api4/CustomValue.php
  Civi/Api4/Event/Subscriber/ValidateFieldsSubscriber.php
  Civi/Api4/Event/ValidateValuesEvent.php
  Civi/Api4/Generic/AbstractAction.php
  Civi/Api4/Generic/AbstractCreateAction.php
  Civi/Api4/Generic/AbstractGetAction.php
  Civi/Api4/Generic/AbstractQueryAction.php
  Civi/Api4/Generic/AbstractSaveAction.php
  Civi/Api4/Generic/AbstractUpdateAction.php
  Civi/Api4/Generic/BasicGetAction.php
  Civi/Api4/Generic/BasicUpdateAction.php
  Civi/Api4/Generic/DAOCreateAction.php
  Civi/Api4/Generic/DAODeleteAction.php
  Civi/Api4/Generic/DAOGetAction.php
  Civi/Api4/Generic/DAOGetFieldsAction.php
  Civi/Api4/Generic/DAOUpdateAction.php
  Civi/Api4/Generic/ExportAction.php
  Civi/Api4/Generic/Result.php
  Civi/Api4/Generic/Traits/DAOActionTrait.php
  Civi/Api4/Generic/Traits/ManagedEntity.php
  Civi/Api4/Generic/Traits/SavedSearchInspectorTrait.php
  Civi/Api4/Generic/Traits/SelectParamTrait.php
  Civi/Api4/Provider/ActionObjectProvider.php
  Civi/Api4/Query/Api4SelectQuery.php
  Civi/Api4/Query/SqlExpression.php
  Civi/Api4/Query/SqlField.php
  Civi/Api4/Query/SqlFunction.php
  Civi/Api4/Service/Schema/Joinable/CustomGroupJoinable.php
  Civi/Api4/Service/Schema/Joiner.php
  Civi/Api4/Service/Schema/SchemaMap.php
  Civi/Api4/Service/Spec/SpecGatherer.php
  Civi/Api4/Utils/CoreUtil.php
  Civi/Api4/Utils/FormattingUtil.php
  Civi/CCase/SequenceListener.php
  Civi/Payment/System.php
  Civi/Test/Api3TestTrait.php
  Civi/Test/WorkflowMessageTestTrait.php
Labels: master, merge on pass

#24537 Replace CRM_Core_Exception aliases - ext,bin dir
  bin/ContributionProcessor.php
  ext/afform/admin/Civi/Api4/Action/Afform/LoadAdminData.php
  ext/afform/core/Civi/Afform/AfformMetadataInjector.php
  ext/afform/core/Civi/Api4/Action/Afform/AbstractProcessor.php
  ext/afform/core/Civi/Api4/Action/Afform/Get.php
  ext/afform/core/Civi/Api4/Action/Afform/GetOptions.php
  ext/afform/core/Civi/Api4/Action/Afform/Revert.php
  ext/afform/core/Civi/Api4/Action/Afform/Submit.php
  ext/afform/core/Civi/Api4/Action/Afform/SubmitFile.php
  ext/afform/core/Civi/Api4/Utils/AfformFormatTrait.php
  ext/afform/core/Civi/Api4/Utils/AfformSaveTrait.php
  ext/afform/core/afform.php
  ext/afform/mock/tests/phpunit/api/v4/AfformContactUsageTest.php
  ext/authx/tests/phpunit/Civi/Authx/AllFlowsTest.php
  ext/civigrant/CRM/Grant/BAO/Query.php
  ext/civigrant/CRM/Grant/Form/Search.php
  ext/civiimport/Civi/Api4/Import.php
  ext/contributioncancelactions/contributioncancelactions.php
  ext/contributioncancelactions/tests/phpunit/CancelTest.php
  ext/elavon/tests/phpunit/CRM/Core/Payment/ElavonTest.php
  ext/eventcart/CRM/Event/Cart/Form/Checkout/Payment.php
  ext/ewaysingle/tests/phpunit/CRM/Core/Payment/EwayTest.php
  ext/financialacls/financialacls.php
  ext/financialacls/tests/phpunit/Civi/Financialacls/BaseTestClass.php
  ext/financialacls/tests/phpunit/Civi/Financialacls/ContributionSoftTest.php
  ext/financialacls/tests/phpunit/Civi/Financialacls/EntityFinancialAccountTest.php
  ext/financialacls/tests/phpunit/Civi/Financialacls/FinancialAccountTest.php
  ext/financialacls/tests/phpunit/Civi/Financialacls/LineItemTest.php
  ext/financialacls/tests/phpunit/Civi/Financialacls/MembershipTypesTest.php
  ext/legacycustomsearches/tests/phpunit/Civi/Searches/SampleTest.php
  ext/oauth-client/Civi/Api4/Action/OAuthClient/AbstractGrantAction.php
  ext/oauth-client/Civi/Api4/Action/OAuthClient/Create.php
  ext/oauth-client/Civi/Api4/Action/OAuthClient/Update.php
  ext/oauth-client/Civi/Api4/OAuthProvider.php
  ext/oauth-client/Civi/OAuth/OAuthTokenFacade.php
  ext/oauth-client/tests/phpunit/api/v4/OAuthClientTest.php
  ext/payflowpro/tests/phpunit/CRM/Core/Payment/PayflowProTest.php
  ext/recaptcha/CRM/Utils/ReCAPTCHA.php
  ext/search_kit/Civi/Api4/Action/SearchDisplay/AbstractRunAction.php
  ext/search_kit/Civi/Api4/Action/SearchDisplay/Download.php
  ext/search_kit/Civi/Api4/Action/SearchDisplay/GetDefault.php
  ext/search_kit/Civi/Api4/Action/SearchDisplay/GetSearchTasks.php
  ext/search_kit/Civi/Api4/Action/SearchDisplay/Run.php
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/SearchRunTest.php
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/SearchRunWithCustomFieldTest.php
  ext/sequentialcreditnotes/sequentialcreditnotes.php
  ext/sequentialcreditnotes/tests/phpunit/SequentialcreditnotesTest.php
Labels: master, merge on pass

#24528 Remove call to deprecated `CRM_Contribute_PseudoConstant::contributionStatus`
  CRM/Member/BAO/Membership.php
  CRM/Member/Form/Membership.php
  CRM/Member/Form/MembershipView.php
  CRM/Member/Page/Tab.php
  CRM/Member/Selector/Search.php
  tests/phpunit/CRM/Member/Form/MembershipTest.php
Labels: master, merge on pass

#24158 dev/core#3779 add an ability to set a field as display only in formbuilder
  ext/afform/admin/ang/afGuiEditor/elements/afGuiField.component.js
  ext/afform/admin/ang/afGuiEditor/inputType/DisplayOnly.html
  ext/afform/core/ang/af/fields/DisplayOnly.html
Labels: master

#24539 5.54
  CRM/Admin/Form/Setting/UF.php
  CRM/Core/Config.php
  CRM/Core/DAO.php
  CRM/Logging/Schema.php
Labels: master

#24540 Remove usage of result from deprecated contributionStatus
  CRM/Contribute/BAO/Contribution.php
Labels: master

#24526 [REF] Cleanup unused references to CRM_Core_Exception aliases
  Civi/API/Exception/NotImplementedException.php
  Civi/API/Exception/UnauthorizedException.php
  Civi/API/Kernel.php
  tests/phpunit/api/v4/Api4TestBase.php
Labels: master, merge on pass

#24525 [REF] DAO - Add helper function to check if component is enabled
  CRM/Activity/BAO/Query.php
  CRM/Activity/Form/Activity.php
  CRM/Campaign/BAO/Campaign.php
  CRM/Case/BAO/Case.php
  CRM/Core/BAO/UFGroup.php
  CRM/Core/DAO.php
  CRM/Core/EntityTokens.php
  CRM/Core/Resources.php
  CRM/Mailing/Selector/Browse.php
  CRM/Utils/Check/Component/Case.php
  Civi/API/Request.php
  Civi/Api4/Action/Entity/Get.php
  templates/CRM/Activity/Form/ActivityView.tpl
  templates/CRM/Contribute/Page/ContributionPage.tpl
  templates/CRM/Event/Page/ManageEvent.tpl
  templates/CRM/Mailing/Page/Browse.tpl
Labels: master, merge ready

#24541 case template clean up for reports
  templates/CRM/Report/Form/Case/Demographics.tpl
  templates/CRM/Report/Form/Case/Detail.tpl
  templates/CRM/Report/Form/Case/Summary.tpl
  templates/CRM/Report/Form/Case/TimeSpent.tpl
Labels: master

#24524 SearchKit - Respect currency when formatting monetary fields
  Civi/Api4/Generic/Traits/SavedSearchInspectorTrait.php
  Civi/Api4/Query/SqlExpression.php
  ext/search_kit/Civi/Api4/Action/SearchDisplay/AbstractRunAction.php
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/SearchRunTest.php
  release-notes/5.18.0.md
Labels: master, has-test

#24520 Fix import to support entity_configuration
  CRM/Contribute/Import/Form/MapField.php
  CRM/Contribute/Import/Parser/Contribution.php
  CRM/Import/Form/MapField.php
  CRM/Import/Parser.php
  tests/phpunit/CRM/Activity/Import/Parser/ActivityTest.php
  tests/phpunit/CRM/Contribute/Import/Parser/ContributionTest.php
  tests/phpunit/CRM/Contribute/Import/Parser/data/soft_credit_extended.csv
  tests/phpunit/CRM/Custom/Import/Parser/ApiTest.php
  tests/phpunit/CRMTraits/Import/ParserTrait.php
Labels: has-test, 5.54

#24543 Pass correct variable type to CRM_Core_OptionValue::getValues
  CRM/Core/I18n.php
Labels: merge on pass, 5.54

#24548 5.54
  CRM/Contribute/Import/Form/MapField.php
  CRM/Contribute/Import/Parser/Contribution.php
  CRM/Core/I18n.php
  CRM/Import/Form/MapField.php
  CRM/Import/Parser.php
  tests/phpunit/CRM/Activity/Import/Parser/ActivityTest.php
  tests/phpunit/CRM/Contribute/Import/Parser/ContributionTest.php
  tests/phpunit/CRM/Contribute/Import/Parser/data/soft_credit_extended.csv
  tests/phpunit/CRM/Custom/Import/Parser/ApiTest.php
  tests/phpunit/CRMTraits/Import/ParserTrait.php
Labels: master

#24550 dev/core#3853 - Still need the exception aliases
  Civi/API/Kernel.php
Labels: master, merge on pass

#24549 dev/core#3852 - Classload extension test folders during tests
  CRM/Extension/ClassLoader.php
Labels: master

#24554 DebugSubscriber - Fix activation check
  Civi/API/Subscriber/DebugSubscriber.php
Labels: merge on pass, 5.54

#24553 AdminUi Extension - Translate strings
  ext/civicrm_admin_ui/managed/SavedSearch_Administer_Contact_Types.php
  ext/civicrm_admin_ui/managed/SavedSearch_Administer_Custom_Fields.mgd.php
  ext/civicrm_admin_ui/managed/SavedSearch_Administer_Custom_Groups.mgd.php
Labels: master, merge on pass

#24555 5.54
  Civi/API/Subscriber/DebugSubscriber.php
Labels: master

#24556 contribution template clean up for reports
  templates/CRM/Report/Form/Contribute/Bookkeeping.tpl
  templates/CRM/Report/Form/Contribute/Detail.tpl
  templates/CRM/Report/Form/Contribute/History.tpl
  templates/CRM/Report/Form/Contribute/HouseholdSummary.tpl
  templates/CRM/Report/Form/Contribute/Lybunt.tpl
  templates/CRM/Report/Form/Contribute/OrganizationSummary.tpl
  templates/CRM/Report/Form/Contribute/PCP.tpl
  templates/CRM/Report/Form/Contribute/Repeat.tpl
  templates/CRM/Report/Form/Contribute/SoftCredit.tpl
  templates/CRM/Report/Form/Contribute/Summary.tpl
  templates/CRM/Report/Form/Contribute/Sybunt.tpl
  templates/CRM/Report/Form/Contribute/TopDonor.tpl
Labels: master, merge on pass

#24542 APIv4 - Add Contact::mergeDuplicates action
  Civi/Api4/Action/Contact/GetDuplicates.php
  Civi/Api4/Action/Contact/MergeDuplicates.php
  Civi/Api4/Contact.php
  Civi/Test/Api3TestTrait.php
  api/v3/Contact.php
  tests/phpunit/api/v4/Action/ContactDuplicatesTest.php
Labels: master, has-test

#24420 Afform - basic support for creating event participant
  CRM/Event/DAO/Participant.php
  ext/afform/admin/afformEntities/Participant.php
  xml/schema/Event/Participant.xml
Labels: master

#24557 CiviCRM-Admin-UI - Fix Contact Types search display
  ext/civicrm_admin_ui/managed/SavedSearch_Administer_Contact_Types.mgd.php
  ext/search_kit/ang/crmSearchDisplay/AddButton.html
  ext/search_kit/ang/crmSearchDisplay/traits/searchDisplayBaseTrait.service.js
  ext/search_kit/ang/crmSearchDisplayGrid/crmSearchDisplayGrid.html
  ext/search_kit/ang/crmSearchDisplayList/crmSearchDisplayList.html
  ext/search_kit/ang/crmSearchDisplayTable/crmSearchDisplayTable.html
Labels: master, merge on pass

#24559 [REF] Afform - Extract string function to CRM_Utils_String
  CRM/Utils/String.php
  ext/afform/core/afform.php
Labels: master, merge on pass

#24547 Fix entity_id being saved to message field (only affects rc+)
  CRM/Contribute/Import/Parser/Contribution.php
Labels: merge on pass, 5.54

#24546 Flush old user jobs
  CRM/Core/Config.php
Labels: 5.54

#24538 Stop removing Import tables during cache clearing
  CRM/Core/Config.php
Labels: 5.54

#24560 Stop PHP notice on Find Mailings page
  CRM/Mailing/Page/Browse.php
Labels: master, merge on pass

#24563 Remove unused variable
  CRM/Contact/Form/Task/AddToParentClass.php
Labels: master

#24567 5.54 to master
  CRM/Contribute/Import/Parser/Contribution.php
  CRM/Core/Config.php
Labels: master

#24569 DebugSubscriber - Fix activation check
  Civi/API/Subscriber/DebugSubscriber.php
Labels: merge on pass, 5.53

#24570 [NFC] Fix Typo in Dismaker list of core exts
  distmaker/core-ext.txt
Labels: 5.54

#24568 (NFC) Add various comments (ClassScanner, Config)
  CRM/Core/Config.php
  Civi/Core/ClassScanner.php
Labels: master, merge on pass

#24571 5.54
  distmaker/core-ext.txt
Labels: master

#24565 Avoid PHP notices in Add Contacts to Household task
  CRM/Contact/Form/Task/AddToParentClass.php
  templates/CRM/Contact/Form/Task/AddToParentClass.tpl
Labels: master

#24551 Afform - Fix "Existing" autocomplete field and add tests
  ext/afform/admin/Civi/AfformAdmin/AfformAdminMeta.php
  ext/afform/core/Civi/Api4/Action/Afform/AbstractProcessor.php
  ext/afform/core/tests/phpunit/Civi/Afform/AfformGetFieldsTest.php
  ext/afform/core/tests/phpunit/Civi/Afform/AfformMetadataTest.php
  ext/afform/mock/tests/phpunit/api/v4/AfformAutocompleteUsageTest.php
Labels: has-test, sig:regression, 5.54

#24573 5.54 to master
  CRM/Contribute/Import/Parser/Contribution.php
  ext/afform/admin/Civi/AfformAdmin/AfformAdminMeta.php
  ext/afform/core/Civi/Api4/Action/Afform/AbstractProcessor.php
  ext/afform/core/tests/phpunit/Civi/Afform/AfformGetFieldsTest.php
  ext/afform/core/tests/phpunit/Civi/Afform/AfformMetadataTest.php
  ext/afform/mock/tests/phpunit/api/v4/AfformAutocompleteUsageTest.php
Labels: master

#24572 Add temporary file to help Joomla installers (5.54-rc)
  CRM/Contact/Import/Parser.php
  CRM/Utils/Check/Component/Source.php
Labels: merge on pass, 5.54

#24574 Fix some inconsistent key names, as used by civiimport
  CRM/Contribute/Import/Parser/Contribution.php
  CRM/Import/Form/MapField.php
  tests/phpunit/CRM/Contribute/Import/Parser/ContributionTest.php
Labels: merge on pass, 5.54

#24561 dev/drupal#174 - Don't use internal CMS identifier as a human label - Option 1
  CRM/Contact/Form/Search/Criteria.php
  templates/CRM/Admin/Form/CMSUser.tpl
Labels: master

#24575 Remove call to deprecated `CRM_Contribute_PseudoConstant::contributionStatus`
  CRM/Financial/BAO/FinancialItem.php
Labels: master

#24544 Remove call to deprecated function `CRM_Contribute_PseudoConstant::contributionStatus`
  CRM/Contribute/BAO/Contribution.php
Labels: master

#22686 No longer install the Contribution Cancel Actions, CiviCRM Core Extension by default on new CiviCRM sites
  xml/templates/civicrm_data.tpl
Labels: master, merge on pass

#24477 Add system check for clean URL configuration
  CRM/Utils/Check/Component/Cms.php
  CRM/Utils/System/Base.php
  CRM/Utils/System/WordPress.php
Labels: master, merge on pass

#24581 [REF] ExportUI - Convert Angular controller to component
  ang/exportui.css
  ang/exportui/exportui.js
  templates/CRM/Export/Form/Map.tpl
Labels: master

#24578 Regenerate civicrm_generated after #22686 and codegen params to in_array are backwards
  CRM/Core/CodeGen/GenerateData.php
  sql/civicrm_generated.mysql
Labels: master

#24579 5.54
  CRM/Contact/Import/Parser.php
  CRM/Contribute/Import/Parser/Contribution.php
  CRM/Import/Form/MapField.php
  CRM/Utils/Check/Component/Source.php
  tests/phpunit/CRM/Contribute/Import/Parser/ContributionTest.php
Labels: master

#24530 Code cleanup - remove unused fn call, prefer strict comparision
  CRM/Core/Payment/AuthorizeNet.php
Labels: master

#24393 closes #3745 Fixes Rewrite of Multi-Select Token in Search Kit
  ext/search_kit/Civi/Api4/Action/SearchDisplay/AbstractRunAction.php
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/AbstractRunActionTest.php
Labels: master

#24587 dev/core#3863 - Default email location on contact is always Billing
  CRM/Contact/Form/Location.php
Labels: merge on pass, 5.54

#24588 Fix warnings on upgrade when non-core message templates exist
  CRM/Upgrade/Incremental/MessageTemplates.php
Labels: merge on pass, 5.54

#24589 5.54
  CRM/Contact/Form/Location.php
  CRM/Upgrade/Incremental/MessageTemplates.php
Labels: master

#24545 Add angular form to civiimport extension
  CRM/Contribute/Import/Parser/Contribution.php
  CRM/Import/Forms.php
  CRM/Import/Parser.php
  ext/civiimport/ang/crmCiviimport.ang.php
  ext/civiimport/ang/crmCiviimport.css
  ext/civiimport/ang/crmCiviimport.js
  ext/civiimport/ang/crmCiviimport/Import.html
  ext/civiimport/civiimport.php
  ext/civiimport/info.xml
  ext/civiimport/templates/CRM/Import/MapField.tpl
  ext/civiimport/templates/CRM/crmCiviimport/ImportUiCtrl.hlp
  tests/phpunit/CRM/Contribute/Import/Parser/ContributionTest.php
  tests/phpunit/CRM/Contribute/Import/Parser/data/soft_credit_extended.csv
Labels: 5.54

#24580 Class scanner - do not throw runTime Exception if class not loaded
  Civi/Core/ClassScanner.php
Labels: merge on pass, 5.54

#24592 5.54 to master
  CRM/Contribute/Import/Parser/Contribution.php
  CRM/Import/Forms.php
  CRM/Import/Parser.php
  Civi/Core/ClassScanner.php
  ext/civiimport/ang/crmCiviimport.ang.php
  ext/civiimport/ang/crmCiviimport.css
  ext/civiimport/ang/crmCiviimport.js
  ext/civiimport/ang/crmCiviimport/Import.html
  ext/civiimport/civiimport.php
  ext/civiimport/info.xml
  ext/civiimport/templates/CRM/Import/MapField.tpl
  ext/civiimport/templates/CRM/crmCiviimport/ImportUiCtrl.hlp
  tests/phpunit/CRM/Contribute/Import/Parser/ContributionTest.php
  tests/phpunit/CRM/Contribute/Import/Parser/data/soft_credit_extended.csv
Labels: master

#24595 [REF] Minor extraction
  CRM/Group/Form/Edit.php
Labels: master

#24591 Remove `CRM_Core_Pseudoconstant::pcpStatus()` function after two-year noisy deprecation
  CRM/Contribute/PseudoConstant.php
Labels: master

#24584 Undo breakage of multi-primary key entities
  CRM/Core/DAO.php
Labels: merge ready, 5.54

#24599 5.54
  CRM/Core/DAO.php
Labels: master

#24601 Put back exception during class scanning
  Civi/Core/ClassScanner.php
Labels: 5.54

#24602 5.54 to master
  Civi/Core/ClassScanner.php
Labels: master

#24608 Add missing th element to note.tpl
  templates/CRM/Contact/Page/View/Note.tpl
Labels: master

#24593 dev/core#3826 Fix regression on contribution search tasks in search-kit
  ext/search_kit/Civi/Api4/Action/SearchDisplay/GetSearchTasks.php
Labels: 5.54

#24607 Ensure children key is always set in tag buildTree
  CRM/Core/BAO/Tag.php
Labels: master

#24611 5.54
  ext/search_kit/Civi/Api4/Action/SearchDisplay/GetSearchTasks.php
Labels: master

#24613 Ensure smarty variable editSmartGroupURL is always defined on group edit
  CRM/Group/Form/Edit.php
Labels: master

#24612 backport 24593
  ext/search_kit/Civi/Api4/Action/SearchDisplay/GetSearchTasks.php
Labels: 5.53

#24009 (dev/core#3732) Show billing address on Edit contribution screen as well
  CRM/Contribute/Form/Contribution.php
  templates/CRM/Contribute/Form/Contribution.tpl
Labels: master

#24615 dev/core#3862 - Crash when creating message template
  CRM/Core/DAO.php
  tests/phpunit/api/v4/Entity/MessageTemplateTest.php
Labels: has-test, 5.54

#24604 Return success from cleanup job
  api/v3/Job.php
Labels: master

#24616 dev/core#3825 - CiviReport - number of rows to show parameter not working
  CRM/Report/Form.php
Labels: master

#24614 Fix paypal subscription 'things don't seem to be working at the moment' if frequency_interval not specified
  CRM/Core/Payment/PayPalImpl.php
Labels: master
