Repository civicrm/civicrm-core, pull requests merged in 2023-09, with the labels that each got.

#27239 phpstorm - Prefer to store generated hints in source-tree
  .gitignore
  tools/extensions/phpstorm/.phpstorm.meta.php
  tools/extensions/phpstorm/Civi/PhpStorm/PhpStormMetadata.php
  tools/extensions/phpstorm/Civi/PhpStorm/StaticGenerator.php
  tools/extensions/phpstorm/phpstorm.civix.php
  tools/extensions/phpstorm/phpstorm.php
Labels: master

#27228 PHP8 date range not rendered correctly
  CRM/Utils/Date.php
Labels: master

#27236 APIv4 - Add missing input type options
  Civi/Api4/Generic/BasicGetFieldsAction.php
Labels: master

#27238 Superficial clean up in test class
  tests/phpunit/api/v3/JobProcessMembershipTest.php
Labels: master, merge on pass

#27243 [NFC] 5.65 Release Notes
  contributor-key.yml
  release-notes/5.65.0.md
Labels: merge on pass, 5.65

#27245 Participant Form Test fixes
  tests/phpunit/CRM/Event/Form/ParticipantTest.php
Labels: master

#27237 dev/core#4537 Ensure that Event Registration email works when CiviCon…
  CRM/Event/WorkflowMessage/ParticipantTrait.php
  Civi/Test/EventTestTrait.php
  Civi/Token/TokenCompatSubscriber.php
  tests/phpunit/CRM/Event/Form/Registration/ConfirmTest.php
Labels: merge on pass, merge ready, has-test, 5.65

#27247 dev/core#4537 Ensure that Event Registration email works when CiviCon…
  CRM/Event/WorkflowMessage/ParticipantTrait.php
  Civi/Test/EventTestTrait.php
  Civi/Token/TokenCompatSubscriber.php
  tests/phpunit/CRM/Event/Form/Registration/ConfirmTest.php
Labels: merge on pass, 5.64

#27246 5.64.3 - Set version. Add notes.
  ext/afform/admin/info.xml
  ext/afform/core/info.xml
  ext/afform/html/info.xml
  ext/afform/mock/info.xml
  ext/authx/info.xml
  ext/civi_campaign/info.xml
  ext/civi_case/info.xml
  ext/civi_contribute/info.xml
  ext/civi_event/info.xml
  ext/civi_mail/info.xml
  ext/civi_member/info.xml
  ext/civi_pledge/info.xml
  ext/civi_report/info.xml
  ext/civicrm_admin_ui/info.xml
  ext/civigrant/info.xml
  ext/civiimport/info.xml
  ext/ckeditor4/info.xml
  ext/contributioncancelactions/info.xml
  ext/elavon/info.xml
  ext/eventcart/info.xml
  ext/ewaysingle/info.xml
  ext/financialacls/info.xml
  ext/flexmailer/info.xml
  ext/greenwich/info.xml
  ext/legacycustomsearches/info.xml
  ext/message_admin/info.xml
  ext/oauth-client/info.xml
  ext/payflowpro/info.xml
  ext/recaptcha/info.xml
  ext/search_kit/info.xml
  ext/sequentialcreditnotes/info.xml
  ext/standaloneusers/info.xml
  release-notes.md
  release-notes/5.64.3.md
  sql/civicrm_generated.mysql
  sql/test_data_second_domain.mysql
  xml/version.xml
Labels: merge ready, 5.64

#27248 5.65
  CRM/Event/WorkflowMessage/ParticipantTrait.php
  Civi/Test/EventTestTrait.php
  Civi/Token/TokenCompatSubscriber.php
  contributor-key.yml
  release-notes/5.65.0.md
  tests/phpunit/CRM/Event/Form/Registration/ConfirmTest.php
Labels: master, merge on pass

#27226 dev/core#444 Default to blank for required multi-lingual fields
  CRM/Core/CodeGen/I18n.php
  CRM/Core/I18n/SchemaStructure.php
  tests/phpunit/CRM/Contribute/Form/ContributionPageTranslationTest.php
  tests/phpunit/CRM/Core/I18n/SchemaTest.php
Labels: master

#27250 Fix forms to call full form flow
  tests/phpunit/CRM/Event/Form/ParticipantTest.php
Labels: master

#27249 Add sorting options on Membership Details report
  CRM/Report/Form/Member/Detail.php
Labels: master, merge on pass

#26993 Ensure tax_amount is not null
  CRM/Contribute/DAO/Contribution.php
  CRM/Price/DAO/LineItem.php
  CRM/Upgrade/Incremental/php/FiveSixtySix.php
  CRM/Upgrade/Incremental/sql/5.66.alpha1.mysql.tpl
  sql/civicrm_generated.mysql
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  xml/schema/Contribute/Contribution.xml
  xml/schema/Price/LineItem.xml
Labels: master

#27253 SearchKit - Fix autocomplete filters on in-place-edit fields
  ext/search_kit/ang/crmSearchDisplay/crmSearchDisplayEditable.component.js
Labels: master, merge ready

#26841 dev/core#3049 - Update autocomplete custom fields to use APIv4
  CRM/Core/BAO/CustomField.php
  Civi/Api4/Event/Subscriber/AutocompleteFieldSubscriber.php
  Civi/Api4/Service/Autocomplete/OptionValueAutocompleteProvider.php
  Civi/Api4/Service/Spec/SpecFormatter.php
Labels: master

#27231 Add weights to membership type links
  CRM/Member/Page/MembershipType.php
  CRM/PCP/BAO/PCP.php
  CRM/Utils/Hook.php
  ext/financialacls/financialacls.php
  ext/financialacls/tests/phpunit/Civi/Financialacls/MembershipTypesTest.php
Labels: master, merge on pass

#27256 Further fix forms to full form flow
  tests/phpunit/CRM/Event/Form/ParticipantTest.php
Labels: master, merge on pass

#27257 Add API-based EntityLookupTrait
  Civi/API/EntityLookupTrait.php
  Civi/Test/EntityTrait.php
  tests/phpunit/Civi/API/EntityLookupTest.php
Labels: master

#26676 Switch menubar search to use APIv4 & delete deprecated v3 'getquick' action
  CRM/Core/BAO/CustomField.php
  CRM/Core/Permission.php
  CRM/Core/SelectValues.php
  CRM/Upgrade/Incremental/php/FiveSixtySix.php
  CRM/Utils/API/AbstractFieldCoder.php
  Civi/Api4/Service/Autocomplete/ContactAutocompleteProvider.php
  api/v3/Contact.php
  js/crm.menubar.js
  settings/Search.setting.php
  tests/phpunit/api/v3/ContactTest.php
Labels: master, merge ready

#27260 Fix participantTest to not use transactions
  tests/phpunit/CRM/Event/Form/ParticipantTest.php
  tests/templates/message_templates/event_offline_receipt_html.tpl
Labels: master

#27251 avoid double clicks on petition page
  CRM/Campaign/Form/Petition/Signature.php
Labels: master

#27265 standaloneusers: logout function must be static
  ext/standaloneusers/CRM/Standaloneusers/Page/Login.php
Labels: master, merge ready, comp:standalone

#27263 Menubar Quicksearch - Followup fixes
  CRM/Upgrade/Incremental/php/FiveSixtySix.php
  js/crm.menubar.js
Labels: master

#27264 Fix fatal on Manage Extensions caused by financialacls links
  ext/financialacls/financialacls.php
Labels: master, sig:unreleased-regression

#27261 EntityLookupTrait - Skip queries when looking up id
  Civi/API/EntityLookupTrait.php
Labels: master

#27262 [NFC] PhpStorm - Add more APIv4 function argument hints
  tools/extensions/phpstorm/Civi/PhpStorm/Api4Generator.php
Labels: master

#27267 Add form helper for tests
  Civi/Test/FormTrait.php
  Civi/Test/FormWrapper.php
  Civi/Test/FormWrappers/EventFormParticipant.php
  tests/phpunit/CRM/Event/Form/ParticipantTest.php
Labels: master, merge on pass

#27199 SearchKit - Fix broken totals row and query output
  ext/search_kit/ang/crmSearchAdmin/resultsTable/crmSearchAdminResultsTable.component.js
  ext/search_kit/ang/crmSearchDisplayTable/crmSearchDisplayTable.component.js
Labels: sig:regression, 5.65

#27269 ajax.js - Fix undeclared variable
  js/crm.ajax.js
Labels: master

#27202 SearchKit - Improve handling of money currency
  Civi/Api4/Query/Api4SelectQuery.php
  ext/search_kit/Civi/Api4/Action/SearchDisplay/AbstractRunAction.php
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/SearchRunTest.php
Labels: master, has-test

#27275 EntityLookupTrait - Add isDefined and getDefinition methods
  Civi/API/EntityLookupTrait.php
  tests/phpunit/Civi/API/EntityLookupTest.php
Labels: master, merge on pass, has-test

#27233 Delete probably-unused TrackingFields.tpl
  ext/eventcart/templates/CRM/Event/Cart/Form/Checkout/ConferenceEvents.tpl
  ext/eventcart/templates/CRM/Event/Cart/Form/Checkout/ParticipantsAndPrices.tpl
  ext/eventcart/templates/CRM/Event/Cart/Form/Checkout/Payment.tpl
  ext/eventcart/templates/CRM/Event/Cart/Form/Checkout/ThankYou.tpl
  templates/CRM/Contribute/Form/Contribution/Confirm.tpl
  templates/CRM/Contribute/Form/Contribution/Main.tpl
  templates/CRM/Contribute/Form/Contribution/ThankYou.tpl
  templates/CRM/Event/Form/Registration/AdditionalParticipant.tpl
  templates/CRM/Event/Form/Registration/Confirm.tpl
  templates/CRM/Event/Form/Registration/Register.tpl
  templates/CRM/Event/Form/Registration/ThankYou.tpl
  templates/CRM/common/TrackingFields.tpl
  tests/templates/message_templates/contribution_online_receipt_html.tpl
  xml/templates/message_templates/contribution_online_receipt_html.tpl
  xml/templates/message_templates/contribution_online_receipt_text.tpl
  xml/templates/message_templates/event_offline_receipt_html.tpl
  xml/templates/message_templates/event_offline_receipt_text.tpl
  xml/templates/message_templates/event_online_receipt_html.tpl
  xml/templates/message_templates/event_online_receipt_text.tpl
  xml/templates/message_templates/membership_online_receipt_html.tpl
  xml/templates/message_templates/membership_online_receipt_text.tpl
Labels: master, merge ready

#27197 SearchKit - Expose sql functions provided by extensions
  Civi/Api4/Utils/CoreUtil.php
Labels: master

#27273 Remove some unnecessary variables & pass by ref
  CRM/Contribute/BAO/Contribution.php
  tests/phpunit/CRM/Core/Payment/BaseIPNTest.php
Labels: master

#26987 Fix Financial Items incorrectly recorded when using Payment API
  CRM/Financial/BAO/Payment.php
Labels: master

#27276 Add pre-upgrade message about the removed TrackingFields.tpl
  CRM/Upgrade/Incremental/php/FiveSixtySix.php
Labels: master, merge on pass

#27140 API - Switched to cached function for looking up pemissioned groups
  CRM/Contact/BAO/Group.php
  CRM/Core/Permission/Base.php
  tests/phpunit/api/v3/ContactTest.php
  tests/phpunit/api/v3/GroupTest.php
  tests/phpunit/api/v3/MailingTest.php
  tests/phpunit/api/v3/ReportTemplateTest.php
Labels: master, has-test

#27277 Update one of our complex confirm tests to use full form flow, fix discovered failure to send to additional participants
  CRM/Contribute/BAO/Contribution.php
  CRM/Event/Form/Registration/AdditionalParticipant.php
  CRM/Event/Form/Registration/Register.php
  Civi/Test/FormTrait.php
  Civi/Test/FormWrapper.php
  Civi/Test/FormWrappers/EventFormOnline.php
  tests/phpunit/CRM/Event/Form/Registration/ConfirmTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: master

#27280 Fix bug exposed by invalid data warning
  CRM/Event/Form/SelfSvcTransfer.php
Labels: 5.65

#27282 Minor cleanup in test
  tests/phpunit/CRM/Event/Form/SearchTest.php
Labels: master

#27286 5.65
  CRM/Event/Form/SelfSvcTransfer.php
  ext/search_kit/ang/crmSearchAdmin/resultsTable/crmSearchAdminResultsTable.component.js
  ext/search_kit/ang/crmSearchDisplayTable/crmSearchDisplayTable.component.js
Labels: master

#27279 Update further tests to additional form flow, lock in bug fix
  Civi/Test/Api3TestTrait.php
  tests/phpunit/CRM/Event/Form/Registration/ConfirmTest.php
Labels: master

#27285 [test] [cleanup] Move _REQUEST cleanup to tearDown
  tests/phpunit/CRM/Core/FormTest.php
Labels: master

#27284 Add weights to links on multipleRecordFieldsListing
  CRM/Custom/Page/AJAX.php
  CRM/Profile/Page/MultipleRecordFieldsListing.php
Labels: master

#27274 Pass specific ids rather than ids array
  CRM/Contribute/BAO/Contribution.php
  tests/phpunit/CRM/PCP/BAO/PCPTest.php
Labels: master

#27150 Remove unused profiles from offline event receipts
  xml/templates/message_templates/event_offline_receipt_html.tpl
  xml/templates/message_templates/event_offline_receipt_text.tpl
Labels: master, merge on pass

#27159 Fix incorrect event receipt regression
  tests/phpunit/CRM/Event/Form/ParticipantTest.php
  xml/templates/message_templates/event_offline_receipt_html.tpl
Labels: master, merge on pass

#27283 Add weights to scheduled jobs
  CRM/Admin/Page/Job.php
  CRM/Event/Selector/Search.php
Labels: master

#27289 Fixes for setting defaults for custom data field of type file
  CRM/Core/BAO/CustomGroup.php
Labels: 5.64

#27290 Fixes for setting defaults for custom data field of type file
  CRM/Core/BAO/CustomGroup.php
Labels: 5.65

#27270 SearchKit - Fix assigning searchDisplay tab count
  ext/search_kit/ang/crmSearchAdmin/searchSegmentListing/crmSearchAdminSegmentListing.component.js
  ext/search_kit/ang/crmSearchDisplay/traits/searchDisplayBaseTrait.service.js
  ext/search_kit/ang/crmSearchDisplayGrid/crmSearchDisplayGrid.component.js
  ext/search_kit/ang/crmSearchDisplayList/crmSearchDisplayList.component.js
  ext/search_kit/ang/crmSearchDisplayTable/crmSearchDisplayTable.component.js
Labels: 5.65

#27211 Afform - Allow submissions to be disabled and limited
  CRM/Api4/Page/AJAX.php
  Civi/Api4/Generic/BasicGetAction.php
  ext/afform/admin/ang/afAdmin.js
  ext/afform/admin/ang/afAdmin/afAdminList.controller.js
  ext/afform/admin/ang/afAdmin/afAdminList.html
  ext/afform/admin/ang/afGuiEditor/afGuiEditor.component.js
  ext/afform/admin/ang/afGuiEditor/config-form.html
  ext/afform/core/Civi/Api4/Action/Afform/AbstractProcessor.php
  ext/afform/core/Civi/Api4/Action/Afform/Get.php
  ext/afform/core/Civi/Api4/Afform.php
  ext/afform/core/ang/af/afForm.component.js
  ext/afform/mock/tests/phpunit/api/v4/AfformContactUsageTest.php
  ext/afform/mock/tests/phpunit/api/v4/AfformTest.php
Labels: master, merge on pass, has-test

#27291 Merge 5.65 to master
  CRM/Core/BAO/CustomGroup.php
  ext/search_kit/ang/crmSearchAdmin/searchSegmentListing/crmSearchAdminSegmentListing.component.js
  ext/search_kit/ang/crmSearchDisplay/traits/searchDisplayBaseTrait.service.js
  ext/search_kit/ang/crmSearchDisplayGrid/crmSearchDisplayGrid.component.js
  ext/search_kit/ang/crmSearchDisplayList/crmSearchDisplayList.component.js
  ext/search_kit/ang/crmSearchDisplayTable/crmSearchDisplayTable.component.js
Labels: master

#27254 [REF] - Cleanup managed entities to all go through `hook_civicrm_managed` and deprecate unnamed entities
  CRM/Case/Info.php
  CRM/Core/Component/Info.php
  CRM/Core/ManagedEntities.php
  ext/civi_case/civi_case.php
Labels: master

#27297 Remove, extraneous: punctuation?
  CRM/Upgrade/Incremental/php/FiveFiftyOne.php
  tests/phpunit/CRM/Contact/Page/View/UserDashBoardTest.php
  tests/phpunit/CRM/Import/DataSource/FormsTest.php
Labels: master

#27301 Remove unused CONST
  CRM/Mailing/Page/View.php
Labels: master

#27105 SearchKit - In-place edit without refreshing results
  ext/search_kit/Civi/Api4/Action/SearchDisplay/AbstractRunAction.php
  ext/search_kit/ang/crmSearchDisplay/colType/field.html
  ext/search_kit/ang/crmSearchDisplay/crmSearchDisplayEditable.component.js
  ext/search_kit/ang/crmSearchDisplay/traits/searchDisplayBaseTrait.service.js
  ext/search_kit/css/crmSearchTasks.css
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/SearchRunTest.php
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/SearchRunWithCustomFieldTest.php
  js/Common.js
Labels: master, merge ready

#27268 CiviCampaign - Refactor civicrm_survey.recontact_interval
  CRM/Campaign/BAO/Query.php
  CRM/Campaign/DAO/Survey.php
  CRM/Campaign/Form/Survey/Main.php
  CRM/Campaign/Form/Survey/Results.php
  CRM/Campaign/Page/AJAX.php
  CRM/Upgrade/Incremental/php/FiveSixtySix.php
  xml/schema/Campaign/Survey.xml
Labels: master, merge ready

#27302 APIv4 - Fix setting nullable/required/default_value field metadata
  Civi/Api4/Service/Spec/Provider/ACLEntityRoleCreationSpecProvider.php
  Civi/Api4/Service/Spec/Provider/CustomValueSpecProvider.php
  Civi/Api4/Service/Spec/Provider/EmailCreationSpecProvider.php
  Civi/Api4/Service/Spec/Provider/GetActionDefaultsProvider.php
  Civi/Api4/Service/Spec/SpecFormatter.php
  Civi/Api4/Service/Spec/SpecGatherer.php
  tests/phpunit/api/v4/Action/GetFieldsTest.php
  tests/phpunit/api/v4/Custom/CustomValueTest.php
Labels: master, has-test

#27300 Unconditionally assign smarty variable
  CRM/Mailing/Page/Browse.php
Labels: master

#27299 Move function to only form that calls it
  CRM/Contribute/Form/AbstractEditPayment.php
  CRM/Contribute/Form/Contribution.php
Labels: master

#27201 Add contribution page tokens to contribution tokens
  CRM/Contact/Tokens.php
  CRM/Contribute/DAO/ContributionPage.php
  CRM/Contribute/Tokens.php
  CRM/Core/EntityTokens.php
  CRM/Core/I18n/SchemaStructure.php
  tests/phpunit/CRM/Activity/Form/Task/PDFTest.php
  tests/phpunit/CRM/Contribute/ActionMapping/ByTypeTest.php
  tests/phpunit/CRM/Utils/TokenConsistencyTest.php
  xml/schema/Contribute/ContributionPage.xml
Labels: master, merge ready

#27306 Declare CRM_Core_Exception in cleanDir, add type hints
  CRM/Utils/File.php
Labels: master

#27308 Make function private to reflect usage
  CRM/Utils/Mail/Incoming.php
Labels: master

#27307 Trivial cleanup in EmailProcessorTest
  tests/phpunit/CRM/Utils/Mail/EmailProcessorTest.php
Labels: master

#27203 Convert new lines to page breaks when rendering text tokens to html
  Civi/Token/TokenRow.php
Labels: master, merge ready

#27311 [BACKPORT] Fix upgrader SQL (5.60) that updates civicrm_job_log
  CRM/Upgrade/Incremental/php/FiveSixty.php
Labels: sig:regression, 5.64

#27313 [NFC] Be more confident and informative in the comment for CRM_Core_Session::set()
  CRM/Core/Session.php
Labels: master

#27081 dev/core#2644 Add Scheduled Communications extension
  .gitignore
  CRM/Activity/ActionMapping.php
  CRM/Activity/Tokens.php
  CRM/Contact/ActionMapping.php
  CRM/Core/BAO/ActionSchedule.php
  CRM/Core/EntityTokens.php
  CRM/Event/ActionMapping.php
  CRM/Event/ParticipantTokens.php
  CRM/Member/ActionMapping.php
  CRM/Utils/SQL/Select.php
  Civi/ActionSchedule/MappingBase.php
  Civi/ActionSchedule/MappingInterface.php
  Civi/ActionSchedule/RecipientBuilder.php
  Civi/Api4/Generic/Traits/SavedSearchInspectorTrait.php
  Civi/Api4/Query/Api4EntitySetQuery.php
  Civi/Api4/Query/Api4SelectQuery.php
  Civi/Api4/Query/SqlBool.php
  Civi/Api4/Query/SqlEquation.php
  Civi/Api4/Query/SqlExpression.php
  Civi/Api4/Query/SqlField.php
  Civi/Api4/Query/SqlFunction.php
  Civi/Api4/Query/SqlFunctionDAYSTOANNIV.php
  Civi/Api4/Query/SqlFunctionGROUP_CONCAT.php
  Civi/Api4/Query/SqlNull.php
  Civi/Api4/Query/SqlNumber.php
  Civi/Api4/Query/SqlString.php
  Civi/Api4/Query/SqlWild.php
  Civi/Api4/Utils/FormattingUtil.php
  distmaker/core-ext.txt
  ext/scheduled_communications/Civi/Search/ActionMapping.php
  ext/scheduled_communications/info.xml
  ext/scheduled_communications/scheduled_communications.civix.php
  ext/scheduled_communications/scheduled_communications.php
  ext/search_kit/Civi/Api4/Action/SearchDisplay/GetDefault.php
  ext/search_kit/ang/crmSearchAdmin/searchListing/communications.html
  ext/search_kit/ang/crmSearchAdmin/searchListing/crmSearchAdminSearchListing.component.js
  tests/phpunit/Civi/ActionSchedule/AbstractMappingTest.php
  tests/phpunit/Civi/ActionSchedule/SavedSearchMappingTest.php
  tests/phpunit/api/v4/Action/SqlFunctionTest.php
Labels: master, merge on pass

#27295 Switch to using token for trxn_id, online contribution receipt
  xml/templates/message_templates/contribution_online_receipt_html.tpl
  xml/templates/message_templates/contribution_online_receipt_text.tpl
Labels: master, merge ready

#27314 Fix token consistency test with new lines and <br>s
  tests/phpunit/CRM/Utils/TokenConsistencyTest.php
Labels: master, merge on pass

#27255 [REF] Convert from session status to deprecation warning
  CRM/Event/WorkflowMessage/ParticipantTrait.php
Labels: master, merge on pass

#27298 Remove some unused undefined properties from participant export
  CRM/Event/Import/Parser/Participant.php
Labels: master, merge on pass

#27312 5.65
  CRM/Upgrade/Incremental/php/FiveSixty.php
Labels: master

#27304 Make splitjob function static & private, Remove a couple of unused variables
  CRM/Mailing/BAO/MailingJob.php
Labels: master, merge on pass

#26243 Let unset weights give an e-notice
  CRM/Core/Action.php
Labels: master

#27173 Show Contribution Page receipt text in offline contribution receipt
  tests/phpunit/CRM/Contribute/ActionMapping/ByTypeTest.php
  xml/templates/message_templates/contribution_offline_receipt_html.tpl
  xml/templates/message_templates/contribution_offline_receipt_text.tpl
Labels: master, merge on pass, has-test

#27281 Fix financial transfer test to use form flow, allow all pending to transfer
  CRM/Event/BAO/Participant.php
  Civi/Test/FormWrapper.php
  tests/phpunit/CRM/Event/Form/ParticipantTest.php
Labels: master

#27288 dev/3410#3410 Show 0 rather than nothing when paid amount is zero
  xml/templates/message_templates/event_offline_receipt_html.tpl
  xml/templates/message_templates/event_offline_receipt_text.tpl
Labels: master, merge ready

#27315 Fix dev/core#4550 - Crash when saving repeating event
  CRM/Core/Form/RecurringEntity.php
  CRM/Upgrade/Incremental/sql/5.66.alpha1.mysql.tpl
  ext/civicrm_admin_ui/managed/SavedSearch_Administer_Scheduled_Reminders.mgd.php
Labels: master, sig:regression

#27259 Use new lookup trait to eliminate use of undefined properties `userDisplayName`
  CRM/Contribute/Form/AbstractEditPayment.php
  CRM/Contribute/Form/AdditionalPayment.php
  CRM/Event/Form/Participant.php
  CRM/Pledge/Form/Pledge.php
  tests/phpunit/CRM/Event/Form/ParticipantTest.php
Labels: master, merge ready

#27318 Finish CiviCRM 2.1 deprecation - old style verp
  CRM/Utils/Mail/EmailProcessor.php
Labels: master

#27317 Remove long-broken function
  CRM/Utils/Mail/EmailProcessor.php
Labels: master, merge ready

#27324 Fix enotice (possible regression)
  CRM/Event/Form/Participant.php
Labels: 5.65

#27326 5.65 to master
  CRM/Event/Form/Participant.php
Labels: master

#27323 Define weight for links on extensions page, financial types, financial accounts
  CRM/Admin/Page/Extensions.php
  CRM/Contribute/Page/ContributionPage.php
  CRM/Contribute/Selector/Search.php
  CRM/Contribute/Task.php
  CRM/Event/Page/ManageEvent.php
  CRM/Financial/Page/FinancialAccount.php
  CRM/Financial/Page/FinancialType.php
  CRM/Financial/Page/FinancialTypeAccount.php
Labels: master

#27320 Remove unused parameter, pass by reference in private function with one caller
  CRM/Utils/Mail/Incoming.php
Labels: master

#27327 Set link weight on manage case
  CRM/Activity/Selector/Activity.php
Labels: master, merge on pass

#27305 Remove unreachable page
  CRM/Mailing/Page/Preview.php
  CRM/Mailing/xml/Menu/Mailing.xml
Labels: master

#27335 Fix missing event pay later receipt text
  xml/templates/message_templates/event_online_receipt_html.tpl
  xml/templates/message_templates/event_online_receipt_text.tpl
Labels: merge on pass, 5.65

#27334 SearchKit - Don't crash afforms with non-dao entities
  ext/search_kit/Civi/Search/Meta.php
Labels: merge on pass, sig:regression, 5.65

#27336 5.65 to master
  ext/search_kit/Civi/Search/Meta.php
  xml/templates/message_templates/event_online_receipt_html.tpl
  xml/templates/message_templates/event_online_receipt_text.tpl
Labels: master

#27338 Revert "Update CRM.status for compatability with native js promises"
  ext/search_kit/ang/crmSearchDisplay/crmSearchDisplayEditable.component.js
  js/Common.js
Labels: master, merge on pass, sig:unreleased-regression

#27339 5.65.0 release notes: added late changes
  release-notes/5.65.0.md
Labels: 5.65

#27321 Improve error handling by using civicrm_api3 not civicrm_api
  CRM/Utils/Mail/EmailProcessor.php
  CRM/Utils/Mail/Incoming.php
Labels: master

#27341 5.65
  release-notes/5.65.0.md
Labels: master

#27331 SearchKit - Fix default search columns
  ext/search_kit/Civi/Search/Admin.php
Labels: master, sig:unreleased-regression

#27340 [REF] Regen after civicrm/civicrm-core#27335
  sql/civicrm_generated.mysql
Labels: merge on pass, 5.65

#27342 5.65
  sql/civicrm_generated.mysql
Labels: master

#27337 Move regex processing in EmailProcessor to handling class
  CRM/Utils/Mail/EmailProcessor.php
  CRM/Utils/Mail/IncomingMail.php
Labels: master

#27333 dev/core#4551 Fix escaping on token event.title
  CRM/Core/EntityTokens.php
  CRM/Core/I18n/SchemaStructure.php
  CRM/Event/DAO/Event.php
  CRM/Event/Tokens.php
  xml/schema/Event/Event.xml
Labels: merge ready, 5.65

#26861 (dev/core#4433) - Implement Civi::url() with prefixes and OOP enhancements
  CRM/Core/Invoke.php
  CRM/Core/Menu.php
  CRM/Core/Smarty/plugins/block.url.php
  CRM/Core/xml/Menu/Misc.xml
  CRM/Utils/System/Base.php
  Civi.php
  Civi/Core/Url.php
  tests/phpunit/CRM/Core/MenuTest.php
  tests/phpunit/CRM/Core/Smarty/plugins/UrlTest.php
  tests/phpunit/Civi/Core/UrlTest.php
  tests/phpunit/E2E/Core/PathUrlTest.php
Labels: master, has-test

#27343 5.65
  CRM/Core/EntityTokens.php
  CRM/Core/I18n/SchemaStructure.php
  CRM/Event/DAO/Event.php
  CRM/Event/Tokens.php
  xml/schema/Event/Event.xml
Labels: master

#27346 Correct Credit card month description in release notes
  release-notes/5.65.0.md
Labels: merge on pass, 5.65

#27348 5.65
  CRM/Campaign/Page/DashBoard.php
  CRM/Contact/BAO/Contact.php
  CRM/Contact/Form/Contact.php
  CRM/Core/BAO/UFGroup.php
  CRM/Core/OptionGroup.php
  CRM/Core/PseudoConstant.php
  CRM/Event/BAO/Event.php
  CRM/PCP/Form/PCPAccount.php
  CRM/Utils/System.php
  api/v3/Activity.php
  api/v3/Case.php
  composer.json
  composer.lock
  js/Common.js
  release-notes/5.65.0.md
  templates/CRM/Event/Form/Selector.tpl
  templates/CRM/Event/Page/ManageEvent.tpl
  templates/CRM/Report/Form/Event/Income.tpl
  templates/CRM/Report/Form/Layout/Table.tpl
  templates/CRM/common/SocialNetwork.tpl
  tests/phpunit/CRM/Core/OptionGroupTest.php
Labels: master

#27347 5.65
  CRM/Campaign/Page/DashBoard.php
  CRM/Contact/BAO/Contact.php
  CRM/Contact/Form/Contact.php
  CRM/Core/BAO/UFGroup.php
  CRM/Core/OptionGroup.php
  CRM/Core/PseudoConstant.php
  CRM/Event/BAO/Event.php
  CRM/PCP/Form/PCPAccount.php
  CRM/Utils/System.php
  api/v3/Activity.php
  api/v3/Case.php
  composer.json
  composer.lock
  js/Common.js
  release-notes/5.65.0.md
  templates/CRM/Event/Form/Selector.tpl
  templates/CRM/Event/Page/ManageEvent.tpl
  templates/CRM/Report/Form/Event/Income.tpl
  templates/CRM/Report/Form/Layout/Table.tpl
  templates/CRM/common/SocialNetwork.tpl
  tests/phpunit/CRM/Core/OptionGroupTest.php
Labels: master

#27344 [REF] Update Zetacomponents/mail to be 1.9.5 to fix email validation …
  composer.json
  composer.lock
Labels: master, merge on pass

#27345 Fold deprecated function back into the caller
  CRM/Utils/Mail/EmailProcessor.php
Labels: master, merge on pass

#27330 dev/core#4555 When using a Contribution Page with a Membership Price Set, the contribution amount information never shows on the thank you page
  templates/CRM/Contribute/Form/Contribution/Confirm.tpl
  templates/CRM/Contribute/Form/Contribution/ThankYou.tpl
Labels: master

#27353 rtrim when converting text tokens to html to avoid trailing newlines
  Civi/Token/TokenRow.php
Labels: master

#27354 Port handling for NULL label
  Civi/ActionSchedule/MappingBase.php
Labels: 5.65

#27350 Remove unused variable
  CRM/Utils/Mail/Incoming.php
  tests/phpunit/CRM/Utils/Mail/IncomingTest.php
Labels: 5.66

#27357 APIv4 Explorer - Fix yml input values
  ang/api4Explorer/Explorer.js
Labels: master

#27287 Fix offline event form validation bug when switching events
  CRM/Event/Form/Participant.php
Labels: master, merge ready

#27358 PseudoConstant - Prevent fatal when entity not available
  CRM/Core/PseudoConstant.php
Labels: 5.66

#27349 Event tokens clean up
  CRM/Core/EntityTokens.php
  CRM/Event/Tokens.php
  Civi/Token/TokenRow.php
  tests/phpunit/CRM/Utils/TokenConsistencyTest.php
  xml/templates/message_templates/event_online_receipt_html.tpl
Labels: master

#27361 5.66
  CRM/Core/PseudoConstant.php
  CRM/Utils/Mail/Incoming.php
  tests/phpunit/CRM/Utils/Mail/IncomingTest.php
Labels: master

#27360 PseudoConstant - Prevent fatal when entity not available
  CRM/Core/PseudoConstant.php
Labels: merge on pass, 5.64

#27359 PseudoConstant - Prevent fatal when entity not available
  CRM/Core/PseudoConstant.php
Labels: merge on pass, 5.65

#27362 FiveSixtyFour: disable i18n rewrite on cancel_URL
  CRM/Upgrade/Incremental/php/FiveSixtyFour.php
Labels: merge on pass, 5.65

#27363 Ensure event ID is an integer
  CRM/Event/Tokens.php
Labels: merge on pass, 5.66

#27364 FiveSixtyFour: disable i18n rewrite on cancel_URL
  CRM/Upgrade/Incremental/php/FiveSixtyFour.php
Labels: merge on pass, 5.66

#27128 Support retention of locale on links
  CRM/Utils/System/WordPress.php
Labels: merge on pass, 5.66

#27365 5.66
  CRM/Event/Tokens.php
  CRM/Upgrade/Incremental/php/FiveSixtyFour.php
  CRM/Utils/System/WordPress.php
Labels: master

#27149 hook_civicrm_config: Add extra information to distinguish invocations
  CRM/Core/Config.php
  CRM/Utils/Hook.php
  CRM/Utils/System/Backdrop.php
  CRM/Utils/System/Base.php
  CRM/Utils/System/Drupal.php
  CRM/Utils/System/Drupal8.php
  CRM/Utils/System/DrupalBase.php
  CRM/Utils/System/Joomla.php
  CRM/Utils/System/Standalone.php
  CRM/Utils/System/UnitTests.php
  CRM/Utils/System/WordPress.php
  tests/events/hook_civicrm_config.evch.php
Labels: master

#27368 [REF] Ensure that any NULL values in the title field are fixed prior …
  CRM/Upgrade/Incremental/sql/5.63.alpha1.mysql.tpl
Labels: merge on pass, 5.66

#27293 Afform - Make Afform Core extension required
  CRM/Upgrade/Incremental/php/FiveSixtySeven.php
  bin/regen.sh
  ext/afform/core/Civi/Api4/Afform.php
  ext/afform/core/Civi/Api4/AfformBehavior.php
  ext/afform/core/Civi/Api4/AfformSubmission.php
  ext/afform/core/info.xml
  ext/authx/info.xml
  setup/plugins/init/DefaultExtensions.civi-setup.php
  tests/phpunit/CRM/Contribute/Import/Parser/ContributionTest.php
  tests/phpunit/CRM/Dedupe/MergerTest.php
Labels: master, merge on pass

#27234 Cleanup presentation of total to improve code & reduce notices
  CRM/Contribute/Form/ContributionBase.php
  CRM/Event/Form/Registration.php
  CRM/Price/BAO/PriceSet.php
  templates/CRM/Contribute/Form/Contribution.tpl
  templates/CRM/Contribute/Form/Contribution/Main.tpl
  templates/CRM/Contribute/Form/Contribution/MainMembershipBlock.tpl
  templates/CRM/Event/Form/EventFees.tpl
  templates/CRM/Event/Form/ParticipantFeeSelection.tpl
  templates/CRM/Event/Form/Registration/AdditionalParticipant.tpl
  templates/CRM/Event/Form/Registration/Register.tpl
  templates/CRM/Member/Form/Membership.tpl
  templates/CRM/Price/Form/Calculate.tpl
  templates/CRM/Price/Form/Preview.tpl
Labels: master

#27371 Stop checking contributeMode in ContributionPage confirm.tpl before displaying billingName
  templates/CRM/Contribute/Form/Contribution/ThankYou.tpl
Labels: master, merge on pass

#27370 5.66
  CRM/Upgrade/Incremental/sql/5.63.alpha1.mysql.tpl
Labels: master

#27367 Fix notice on unpaid event
  CRM/Event/Form/Participant.php
  tests/phpunit/CRM/Event/Form/ParticipantTest.php
Labels: 5.66

#27373 5.66 to master
  CRM/Event/Form/Participant.php
  tests/phpunit/CRM/Event/Form/ParticipantTest.php
Labels: master

#27372 Expose fee_label for event tokens
  CRM/Event/Tokens.php
  tests/phpunit/CRM/Utils/TokenConsistencyTest.php
Labels: merge on pass, 5.66

#27376 5.66 to master
  CRM/Event/Tokens.php
  tests/phpunit/CRM/Utils/TokenConsistencyTest.php
Labels: master

#27375 Expose fee_label for event tokens
  CRM/Event/Tokens.php
  tests/phpunit/CRM/Utils/TokenConsistencyTest.php
Labels: 5.65

#27325 Standardise fee_label in event workflow messages
  tests/templates/message_templates/event_online_receipt_text.tpl
  xml/templates/message_templates/event_offline_receipt_html.tpl
  xml/templates/message_templates/event_offline_receipt_text.tpl
  xml/templates/message_templates/event_online_receipt_text.tpl
Labels: master, merge ready

#27374 5.65.1 - Set version. Add notes.
  ext/afform/admin/info.xml
  ext/afform/core/info.xml
  ext/afform/html/info.xml
  ext/afform/mock/info.xml
  ext/authx/info.xml
  ext/civi_campaign/info.xml
  ext/civi_case/info.xml
  ext/civi_contribute/info.xml
  ext/civi_event/info.xml
  ext/civi_mail/info.xml
  ext/civi_member/info.xml
  ext/civi_pledge/info.xml
  ext/civi_report/info.xml
  ext/civicrm_admin_ui/info.xml
  ext/civicrm_search_ui/info.xml
  ext/civigrant/info.xml
  ext/civiimport/info.xml
  ext/ckeditor4/info.xml
  ext/contributioncancelactions/info.xml
  ext/elavon/info.xml
  ext/eventcart/info.xml
  ext/ewaysingle/info.xml
  ext/financialacls/info.xml
  ext/flexmailer/info.xml
  ext/greenwich/info.xml
  ext/legacycustomsearches/info.xml
  ext/message_admin/info.xml
  ext/oauth-client/info.xml
  ext/payflowpro/info.xml
  ext/recaptcha/info.xml
  ext/search_kit/info.xml
  ext/sequentialcreditnotes/info.xml
  ext/standaloneusers/info.xml
  release-notes.md
  release-notes/5.65.1.md
  sql/civicrm_generated.mysql
  sql/test_data_second_domain.mysql
  xml/version.xml
Labels: merge on pass, 5.65

#27369 Remove unnecessary contributeMode reference - just present trxn_id if defined
  templates/CRM/Contribute/Form/Contribution/ThankYou.tpl
Labels: master

#27382 GettingStarted: add token for System Status
  CRM/Dashlet/Page/GettingStarted.php
Labels: master

#27381 dev/core#4542 Fix priority handling in ACLs when dealing with objects…
  CRM/ACL/BAO/ACL.php
  tests/phpunit/api/v3/ACLPermissionTest.php
Labels: 5.66

#27383 dev/core#4559 Don't include test, template, deleted entities in SearchDisplay totals
  Civi/Api4/Generic/AbstractGetAction.php
  ext/search_kit/Civi/Api4/Action/SearchDisplay/Run.php
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/SearchRunTest.php
Labels: has-test, 5.66

#27384 Add email helper to new form test helper
  Civi/Test/FormWrapper.php
  tests/phpunit/CRM/Event/Form/ParticipantTest.php
  tests/phpunit/CRM/Event/Form/Registration/ConfirmTest.php
Labels: merge on pass, 5.66

#27386 5.66
  CRM/ACL/BAO/ACL.php
  Civi/Api4/Generic/AbstractGetAction.php
  Civi/Test/FormWrapper.php
  ext/search_kit/Civi/Api4/Action/SearchDisplay/Run.php
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/SearchRunTest.php
  tests/phpunit/CRM/Event/Form/ParticipantTest.php
  tests/phpunit/CRM/Event/Form/Registration/ConfirmTest.php
  tests/phpunit/api/v3/ACLPermissionTest.php
Labels: master

#27388 Disable broken unit test
  Civi/Api4/Event/AuthorizeRecordEvent.php
  tests/phpunit/api/v4/Entity/ConformanceTest.php
Labels: master

#27240 Use internal variable rather than undeclared property
  CRM/Contact/Form/CustomData.php
  CRM/Custom/Form/CustomData.php
Labels: master

#27385 VersionCheck: replace hash by sid, add the environment
  CRM/Utils/VersionCheck.php
Labels: master

#27356 dev/core#2800 Fix bounce processing to handle verp emails
  CRM/Utils/Mail/EmailProcessor.php
  CRM/Utils/Mail/Incoming.php
  CRM/Utils/Mail/IncomingMail.php
  tests/phpunit/CRM/Utils/Mail/EmailProcessorInboundTest.php
  tests/phpunit/CRM/Utils/Mail/EmailProcessorTest.php
  tests/phpunit/CRM/Utils/Mail/data/inbound/test_broken_from.eml
Labels: 5.66

#27393 APIv4 - Fix conformance test for entities with multiple primary keys
  tests/phpunit/api/v4/Entity/ConformanceTest.php
Labels: master, merge on pass

#27394 Revert "[REF] Update Zetacomponents/mail to be 1.9.5 to fix email validation handling"
  composer.json
  composer.lock
Labels: merge on pass, 5.66
