Repository civicrm/civicrm-core, pull requests merged in 2023-05, with the labels that each got.

#26134 Remove notices on group_by i reports (eg pledge report)
  CRM/Report/Form.php
Labels: master

#26132 Contribution reports, specify type for is pledge payment
  CRM/Report/Form.php
  CRM/Report/Form/Contribute/Detail.php
  CRM/Report/Form/Contribute/Summary.php
  templates/CRM/Report/Form/Layout/Table.tpl
Labels: master

#26124 dev/core#4115 Afform - Handle decimal number fields
  Civi/Api4/Service/Spec/SpecFormatter.php
  ext/afform/admin/ang/afGuiEditor/elements/afGuiField-menu.html
  ext/afform/core/ang/af/fields/Number.html
Labels: master

#26137 Add target contact custom data to activity report
  CRM/Report/Form/Activity.php
Labels: master

#26136 dev/core#4262 - Upgrade message about obsolete civicrm.settings.php setting that generates php warnings
  CRM/Upgrade/Incremental/php/FiveSixtyTwo.php
Labels: master

#26138 Expire notifications for adding and removing groups, tags and relationships
  CRM/Activity/Form/Task/AddToTag.php
  CRM/Activity/Form/Task/RemoveFromTag.php
  CRM/Contact/Form/Task/AddToGroup.php
  CRM/Contact/Form/Task/AddToParentClass.php
  CRM/Contact/Form/Task/AddToTag.php
  CRM/Contact/Form/Task/RemoveFromGroup.php
  CRM/Contact/Form/Task/RemoveFromTag.php
  CRM/Event/Form/Task/AddToGroup.php
Labels: master, merge on pass

#26091 dev/core#4220 - Don't make case activity revisions anymore when file-on-case
  CRM/Activity/Page/AJAX.php
  tests/phpunit/CRM/Activity/Page/AJAXTest.php
Labels: master, merge ready, has-test

#26090 dev/core#4248 - Fix missing price-set usage table
  CRM/Price/Page/Field.php
  templates/CRM/Price/Page/Field.tpl
  templates/CRM/Price/Page/Set.tpl
  templates/CRM/Price/Page/table.tpl
Labels: master, merge ready

#26139 dev/core#4262 - Drop auto_detect_line_endings from civicrm.settings.php.template
  templates/CRM/common/civicrm.settings.php.template
Labels: master, merge on pass

#26125 Importer - Add system-setting for batch size
  CRM/Admin/Form/Setting/Miscellaneous.php
  CRM/Import/Parser.php
  settings/Core.setting.php
Labels: master, merge ready

#26121 Use settings::get instead of $config object to retrieve enabled components
  CRM/Admin/Page/Admin.php
  CRM/Core/Component.php
  CRM/Core/OptionGroup.php
  CRM/Utils/VersionCheck.php
Labels: master

#26131 Further notice fixes on Constituent report
  CRM/Report/Form.php
Labels: master

#26141 dev/core#4272 Fix unreleased regression on Membership form validation
  CRM/Contribute/Form/ContributionBase.php
Labels: 5.61

#26147 5.61
  CRM/Contribute/Form/ContributionBase.php
  contributor-key.yml
  release-notes/5.61.0.md
Labels: master

#26146 fixes core#4269 - Import "fill" doesn't fill phone/email
  CRM/Contact/Import/Parser/Contact.php
  tests/phpunit/CRM/Contact/Import/Parser/ContactTest.php
Labels: 5.61

#26140 dev/core#4225 Add test & fix for new regression - contact update fails when relationship exists & CiviMember disabled
  CRM/Contact/BAO/Relationship.php
  tests/phpunit/api/v3/RelationshipTest.php
Labels: 5.61

#26150 FiveSixtyTwo - Improve detection of identical configurations
  CRM/Upgrade/Incremental/php/FiveSixtyTwo.php
Labels: master, merge on pass

#26152 5.61
  CRM/Contact/BAO/Relationship.php
  CRM/Contact/Import/Parser/Contact.php
  tests/phpunit/CRM/Contact/Import/Parser/ContactTest.php
  tests/phpunit/api/v3/RelationshipTest.php
Labels: master

#26108 Importer - Ensure mapping ID is set in all places using import templates
  CRM/Import/Form/DataSource.php
Labels: merge on pass, 5.61

#26153 release-notes/5.61.0.md - Last minute additions
  release-notes/5.61.0.md
Labels: 5.61

#26155 Bump engine.io and socket.io versions
  package-lock.json
Labels: 5.61

#26156 5.61
  CRM/Import/Form/DataSource.php
  package-lock.json
  release-notes/5.61.0.md
Labels: master

#26144 (dev/core#2855) Preserve pristine ids' for further manipulation via h…
  CRM/Report/Form.php
Labels: master

#26133 Use purify rather than escape to preserve currency
  CRM/Report/Form/Contribute/Summary.php
  templates/CRM/Report/Form/Statistics.tpl
Labels: master

#26158 fixes #4278 - Import fill on email/phone respects location type
  CRM/Contact/Import/Parser/Contact.php
  tests/phpunit/CRM/Contact/Import/Parser/ContactTest.php
Labels: master

#26103 dev/core#4103 Don't show admin only price fields on Registration or Contribution page previews
  templates/CRM/Price/Form/PriceSet.tpl
Labels: master, merge on pass

#26157 mixin/scan-classes - Don't scan extension-tests automatically
  mixin/scan-classes@1/mixin.php
Labels: master, merge on pass

#26159 Upgrade message for drupal9 sites to advise to clear drupal cache
  CRM/Upgrade/Incremental/php/FiveSixtyOne.php
Labels: merge on pass, 5.62

#26160 Upgrade message for drupal9 sites to advise to clear drupal cache
  CRM/Upgrade/Incremental/php/FiveSixtyOne.php
  ext/afform/admin/info.xml
  ext/afform/core/info.xml
  ext/afform/html/info.xml
  ext/afform/mock/info.xml
  ext/authx/info.xml
  ext/civicrm_admin_ui/info.xml
  ext/civigrant/info.xml
  ext/civiimport/info.xml
  ext/ckeditor4/info.xml
  ext/contributioncancelactions/info.xml
  ext/elavon/info.xml
  ext/eventcart/info.xml
  ext/ewaysingle/info.xml
  ext/financialacls/info.xml
  ext/flexmailer/info.xml
  ext/greenwich/info.xml
  ext/legacycustomsearches/info.xml
  ext/message_admin/info.xml
  ext/oauth-client/info.xml
  ext/payflowpro/info.xml
  ext/recaptcha/info.xml
  ext/search_kit/info.xml
  ext/sequentialcreditnotes/info.xml
  sql/civicrm_generated.mysql
  sql/test_data_second_domain.mysql
  xml/version.xml
Labels: 5.61

#26161 Add release-notes/5.61.1.md
  release-notes.md
  release-notes/5.61.1.md
Labels: 5.61

#26162 5.62
  CRM/Upgrade/Incremental/php/FiveSixtyOne.php
Labels: master

#26129 APIv4 - Simplify bridge joins
  Civi/Api4/Query/Api4SelectQuery.php
Labels: master

#26116 Add default payment method for additional payment or refund
  CRM/Contribute/Form/AdditionalPayment.php
  templates/CRM/Contribute/Form/AdditionalPayment.tpl
Labels: master

#26165 Fix PHP8 warnings for AddToGroup
  CRM/Contact/Form/Task/AddToGroup.php
  templates/CRM/Contact/Form/Task/AddToGroup.tpl
Labels: master

#26044 Authx - Add APIv4 support for creating and validating credentials
  ext/authx/Civi/Api4/Action/AuthxCredential/Create.php
  ext/authx/Civi/Api4/Action/AuthxCredential/Validate.php
  ext/authx/Civi/Api4/AuthxCredential.php
  ext/authx/Civi/Authx/Authenticator.php
  ext/authx/authx.php
  ext/authx/tests/phpunit/api/v4/AuthxCredentialTest.php
Labels: master

#25992 Authx - Add in new JWT Entity with Create and Validate methods to permi…
  ext/authx/Civi/Api4/Action/JWT/Create.php
  ext/authx/Civi/Api4/Action/JWT/Validate.php
  ext/authx/Civi/Api4/JWT.php
  ext/authx/authx.php
  ext/authx/tests/phpunit/api/v4/JwtApiTest.php
Labels: master, has-test

#25987 😵 Disambiguate "Source" field by showing the context of the source, ie. Membership, Participant, Contribution, Contact etc.
  CRM/Admin/Form/MailSettings.php
  CRM/Contact/Form/Edit/Household.php
  CRM/Contribute/Form/Contribution.php
  CRM/Contribute/Selector/Search.php
  CRM/Member/BAO/Query.php
  CRM/Member/DAO/Membership.php
  CRM/Member/Form/Membership.php
  CRM/Member/Selector/Search.php
  CRM/Report/Form/Contribute/Bookkeeping.php
  CRM/Report/Form/Contribute/DeferredRevenue.php
  CRM/Report/Form/Contribute/Detail.php
  CRM/Report/Form/Contribute/Summary.php
  CRM/Report/Form/Event/ParticipantListing.php
  CRM/Report/Form/Member/Detail.php
  ext/legacycustomsearches/templates/CRM/Contact/Form/Search/Custom/FullText.tpl
  templates/CRM/Admin/Page/MailSettings.tpl
  templates/CRM/Contact/Page/Inline/ContactInfo.tpl
  templates/CRM/Contribute/Form/ContributionView.tpl
  templates/CRM/Contribute/Form/Task/Print.tpl
  templates/CRM/Contribute/Form/Task/Status.tpl
  templates/CRM/Event/Form/ParticipantView.tpl
  templates/CRM/Member/Form/MembershipView.tpl
  templates/CRM/Member/Form/Task/Print.tpl
  templates/CRM/Member/Form/Task/SearchTaskHookSample.tpl
  templates/CRM/Member/Page/Tab.tpl
  xml/templates/civicrm_data.tpl
Labels: master, merge ready

#26168 Stop escaping tableHeader in secure smarty mode
  templates/CRM/Report/Form/Layout/Table.tpl
Labels: master

#26171 Notice fix on isHonor on contribution page
  CRM/Contribute/Form/Contribution/Main.php
  templates/CRM/Contribute/Form/Contribution/Main.tpl
Labels: master

#26170 Fix regression whereby membership does not submit
  CRM/Contribute/Form/Contribution/Main.php
  CRM/Contribute/Form/ContributionBase.php
  CRM/Price/BAO/PriceSet.php
  templates/CRM/Contribute/Form/Contribution/Main.tpl
  templates/CRM/Contribute/Form/Contribution/MembershipBlock.tpl
Labels: 5.62

#26143 (REF) CRM_Core_Config - Simplify dependencies between MagicMerge and Runtime
  CRM/Core/Config/MagicMerge.php
  CRM/Core/Config/Runtime.php
Labels: master, merge ready

#26175 CiviMember - Fix regression whereby membership does not submit
  CRM/Contribute/Form/Contribution/Main.php
  CRM/Contribute/Form/ContributionBase.php
  CRM/Price/BAO/PriceSet.php
  templates/CRM/Contribute/Form/Contribution/Main.tpl
  templates/CRM/Contribute/Form/Contribution/MembershipBlock.tpl
Labels: 5.61

#26173 Regenerate civicrm generated after #25987 and membership xml
  CRM/Member/DAO/Membership.php
  sql/civicrm_generated.mysql
  tests/phpunit/CRM/Export/BAO/ExportTest.php
  tests/phpunit/CRM/Utils/TokenConsistencyTest.php
  xml/schema/Member/Membership.xml
Labels: master

#26176 5.61.2 - Add notes. Bump version.
  ext/afform/admin/info.xml
  ext/afform/core/info.xml
  ext/afform/html/info.xml
  ext/afform/mock/info.xml
  ext/authx/info.xml
  ext/civicrm_admin_ui/info.xml
  ext/civigrant/info.xml
  ext/civiimport/info.xml
  ext/ckeditor4/info.xml
  ext/contributioncancelactions/info.xml
  ext/elavon/info.xml
  ext/eventcart/info.xml
  ext/ewaysingle/info.xml
  ext/financialacls/info.xml
  ext/flexmailer/info.xml
  ext/greenwich/info.xml
  ext/legacycustomsearches/info.xml
  ext/message_admin/info.xml
  ext/oauth-client/info.xml
  ext/payflowpro/info.xml
  ext/recaptcha/info.xml
  ext/search_kit/info.xml
  ext/sequentialcreditnotes/info.xml
  release-notes.md
  release-notes/5.61.2.md
  sql/civicrm_generated.mysql
  sql/test_data_second_domain.mysql
  xml/version.xml
Labels: 5.61

#26177 Added composerjk to contributor-key.yml
  contributor-key.yml
Labels: master

#26078 REF: Small cleanup on contribution receipt code
  CRM/Contribute/BAO/Contribution.php
  api/v3/Contribution.php
Labels: master

#25563 dev/core#4123 Support contribution recur tokens when accessing from a…
  CRM/Contribute/Tokens.php
  CRM/Core/EntityTokens.php
  CRM/Member/Tokens.php
  tests/phpunit/CRM/Contribute/ActionMapping/ByTypeTest.php
  tests/phpunit/CRM/Utils/TokenConsistencyTest.php
  tests/phpunit/Civi/Token/TokenProcessorTest.php
Labels: master

#26167 dev/core#3920 Improve footer and support menu
  CRM/Upgrade/Incremental/sql/5.63.alpha1.mysql.tpl
  css/civicrm.css
  templates/CRM/common/footer.tpl
  xml/templates/civicrm_navigation.tpl
Labels: master, merge ready

#26123 Afform - Ensure checkboxes and radios are validated client-side
  ext/afform/core/ang/af/fields/CheckBox.html
  ext/afform/core/ang/af/fields/Radio.html
Labels: master

#26187 Preserve participant status when transferring
  CRM/Event/Form/SelfSvcTransfer.php
Labels: master

#26188 Fix authorization failed on self-service participant transfer
  CRM/Event/Form/SelfSvcTransfer.php
Labels: master

#26189 Prevent prohibited self service cancellation by using is_backoffice=1 in URL
  CRM/Event/Form/SelfSvcTransfer.php
  CRM/Event/Form/SelfSvcUpdate.php
Labels: master

#26178 Fix config is null on hooks
  CRM/Utils/System/Drupal8.php
  CRM/Utils/System/Standalone.php
Labels: master

#26184 crmMailingAB/services: catch exception, report error and rethrow
  ang/crmMailingAB/services.js
Labels: master

#26194 Title case Register Your Site in support menu
  CRM/Upgrade/Incremental/sql/5.63.alpha1.mysql.tpl
  xml/templates/civicrm_navigation.tpl
Labels: master

#26192 proper EntityRef joins
  ext/search_kit/Civi/Search/Admin.php
  ext/search_kit/tests/phpunit/Civi/Search/AdminTest.php
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/SearchRunWithCustomFieldTest.php
Labels: master

#26195 dev/core#4279 - Add support for ECMAScript Modules (ESM, part 1)
  CRM/Core/Region.php
  CRM/Core/Resources/CollectionAdderInterface.php
  CRM/Core/Resources/CollectionAdderTrait.php
  CRM/Core/Resources/CollectionInterface.php
  tests/phpunit/CRM/Core/RegionTest.php
  tests/phpunit/CRM/Core/Resources/CollectionTestTrait.php
Labels: master, merge on pass

#26199 Regression: Fatal error when importing membership
  CRM/Member/Import/Parser/Membership.php
Labels: 5.62

#26201 5.62
  CRM/Contribute/Form/Contribution/Main.php
  CRM/Contribute/Form/ContributionBase.php
  CRM/Member/Import/Parser/Membership.php
  CRM/Price/BAO/PriceSet.php
  templates/CRM/Contribute/Form/Contribution/Main.tpl
  templates/CRM/Contribute/Form/Contribution/MembershipBlock.tpl
Labels: master

#26202 flexmailer remove cruft code
  ext/flexmailer/flexmailer.php
Labels: master

#26203 Remove unused constants
  CRM/Event/Form/Registration.php
Labels: master, merge on pass

#26036 dev/core#3961 Create stub extensions for all components
  .gitignore
  CRM/Core/BAO/ConfigSetting.php
  CRM/Core/Component.php
  CRM/Core/Component/Info.php
  CRM/Extension/Upgrader/Component.php
  CRM/Upgrade/Incremental/php/FiveSixtyThree.php
  CRM/Upgrade/Incremental/php/FiveSixtyTwo.php
  Civi/Core/SettingsBag.php
  api/v3/examples/Setting/GetFields.ex.php
  distmaker/core-ext.txt
  ext/civi_campaign/civi_campaign.civix.php
  ext/civi_campaign/civi_campaign.php
  ext/civi_campaign/info.xml
  ext/civi_case/civi_case.civix.php
  ext/civi_case/civi_case.php
  ext/civi_case/info.xml
  ext/civi_contribute/civi_contribute.civix.php
  ext/civi_contribute/civi_contribute.php
  ext/civi_contribute/info.xml
  ext/civi_event/civi_event.civix.php
  ext/civi_event/civi_event.php
  ext/civi_event/info.xml
  ext/civi_mail/civi_mail.civix.php
  ext/civi_mail/civi_mail.php
  ext/civi_mail/info.xml
  ext/civi_member/civi_member.civix.php
  ext/civi_member/civi_member.php
  ext/civi_member/info.xml
  ext/civi_pledge/civi_pledge.civix.php
  ext/civi_pledge/civi_pledge.php
  ext/civi_pledge/info.xml
  ext/civi_report/civi_report.civix.php
  ext/civi_report/civi_report.php
  ext/civi_report/info.xml
  settings/Core.setting.php
  tests/phpunit/CRM/Activity/BAO/ActivityTest.php
  tests/phpunit/CRM/Core/BAO/NavigationTest.php
  tests/phpunit/CRM/Extension/ManagerTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/api/v3/ACLPermissionTest.php
  tests/phpunit/api/v3/ExtensionTest.php
  tests/phpunit/api/v3/MailingTest.php
Labels: master, has-test

#26204 Add missing deprecated tag
  CRM/Price/BAO/PriceSet.php
Labels: master

#26172 dev/core#4227 Fix import to not blank birth_date etc on update
  CRM/Contact/Import/Parser/Contact.php
  tests/phpunit/CRM/Contact/Import/Parser/ContactTest.php
Labels: merge ready, 5.62

#26206 Extract sendEmail function
  CRM/Event/Form/Participant.php
Labels: master

#26209 Don't show send broken confirmation description if registering multiple contacts
  templates/CRM/Event/Form/EventFees.tpl
Labels: master

#26205 Further separate register task from participant form
  CRM/Event/Form/Participant.php
  CRM/Event/Form/Task/Register.php
Labels: master

#26210 5.62
  CRM/Contact/Import/Parser/Contact.php
  tests/phpunit/CRM/Contact/Import/Parser/ContactTest.php
Labels: master

#26213 AbstractAction: Drop `@throws` from phpdoc of `__construct()` because it's not thrown
  Civi/Api4/Generic/AbstractAction.php
Labels: master

#26217 Minor cleanup on function
  CRM/Event/BAO/Participant.php
Labels: master, merge on pass

#26222 Remove unreachable validation
  CRM/Event/Form/Participant.php
Labels: master

#26220 Fix Participant tests to use full form flow
  CRM/Event/Form/EventFees.php
  CRM/Event/Form/Participant.php
  CRM/Event/Form/Task/Register.php
  ext/contributioncancelactions/tests/phpunit/CancelTest.php
  tests/phpunit/CRM/Event/Form/ParticipantTest.php
  tests/phpunit/CRM/Event/Form/Registration/RegisterTest.php
  tests/phpunit/CRM/Utils/TokenConsistencyTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: master

#26219 Improve test consistency on capitalisation
  ext/contributioncancelactions/tests/phpunit/CancelTest.php
  tests/phpunit/CRM/Event/Form/ParticipantTest.php
  tests/phpunit/CRM/Event/Form/Registration/RegisterTest.php
  tests/phpunit/CRM/Utils/TokenConsistencyTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: master

#26221 Make some internal functions protected
  CRM/Event/Form/Participant.php
Labels: master

#26145 dev/core#1403 - CRM/Contribute - Change "Date Received" to "Contribution Date"
  CRM/Contribute/DAO/Contribution.php
  CRM/Contribute/Form/AdditionalPayment.php
  CRM/Contribute/Selector/Search.php
  CRM/Core/BAO/Mapping.php
  CRM/Core/BAO/UFField.php
  CRM/Event/Form/Participant.php
  CRM/Export/BAO/ExportProcessor.php
  CRM/Financial/Page/AJAX.php
  CRM/Member/Form/Membership.php
  CRM/Member/Form/MembershipRenewal.php
  CRM/Report/Form/Contribute/Bookkeeping.php
  CRM/Report/Form/Contribute/Detail.php
  CRM/Report/Form/Member/Detail.php
  ext/civiimport/tests/phpunit/CiviApiImportTest.php
  ext/legacycustomsearches/templates/CRM/Contact/Form/Search/Custom/FullText.tpl
  sql/civicrm_generated.mysql
  templates/CRM/Contribute/Form/Contribution.tpl
  templates/CRM/Contribute/Form/ContributionView.tpl
  templates/CRM/Contribute/Form/PaymentInfoBlock.tpl
  templates/CRM/Contribute/Form/Task/Print.tpl
  templates/CRM/Contribute/Page/ContributionRecurPayments.tpl
  templates/CRM/Contribute/Page/ContributionSoft.tpl
  templates/CRM/Contribute/Page/UserDashboard.tpl
  tests/phpunit/CRM/Contact/Page/View/UserDashBoardTest.php
  tests/phpunit/CRM/Contribute/ActionMapping/ByTypeTest.php
  tests/phpunit/CRM/Contribute/Form/ContributionTest.php
  tests/phpunit/CRM/Contribute/Form/SearchTest.php
  tests/phpunit/CRM/Contribute/Import/Parser/data/checkboxes.csv
  tests/phpunit/CRM/Contribute/Import/Parser/data/soft_credit_extended.csv
  tests/phpunit/CRM/Export/BAO/ExportTest.php
  xml/schema/Contribute/Contribution.xml
  xml/templates/civicrm_data.tpl
  xml/templates/message_templates/contribution_offline_receipt_html.tpl
  xml/templates/message_templates/contribution_offline_receipt_text.tpl
  xml/templates/message_templates/membership_offline_receipt_html.tpl
  xml/templates/message_templates/membership_offline_receipt_text.tpl
  xml/templates/message_templates/pcp_owner_notify_html.tpl
  xml/templates/message_templates/pcp_owner_notify_text.tpl
Labels: master

#26196 [REF] dev/core#1777 - Skip checking vendor provided orphaned files if the vendor directory is not within the CiviCRM root
  CRM/Utils/Check/Component/Source.php
Labels: master, merge ready

#26225 Added Olayiwola Odunsi to contributor-key.yml
  contributor-key.yml
Labels: master

#26223 Clarify sent & not sent variables
  CRM/Event/Form/Participant.php
Labels: master

#26068 dev/core#1321 - SearchKit - Limit operator list for array fields
  ext/search_kit/ang/crmSearchAdmin/crmSearchCondition.component.js
Labels: master

#26230 Upgrader - Use generic (non-api4) code in upgrader
  CRM/Upgrade/Incremental/php/FiveSixtyOne.php
Labels: master

#26214 Speed up Download Spreadsheet from SearchKit results
  ext/search_kit/Civi/Api4/Action/SearchDisplay/Download.php
Labels: master, merge ready

#26235 dev/core#4295 SearchKit: check controller class for qfKey when loading legacy search actions for contributions
  ext/search_kit/Civi/Api4/Action/SearchDisplay/GetSearchTasks.php
Labels: master

#26238 Notice fix on edit Household
  templates/CRM/Contact/Form/Edit/Household.tpl
Labels: master, merge on pass

#26233 Add weight to links spec
  CRM/Contribute/Selector/Search.php
  CRM/Core/Action.php
  tests/phpunit/CRM/Activity/BAO/ActivityTest.php
Labels: master

#26239 setup - Fix uninstall on MySQL 8.0
  setup/src/Setup/DbUtil.php
Labels: 5.62

#26240 5.62
  setup/src/Setup/DbUtil.php
Labels: master

#26193 Fix code handling to pre-5.61 for membership block
  CRM/Contribute/Form/Contribution/Main.php
Labels: 5.62

#26242 5.62
  CRM/Contribute/Form/Contribution/Main.php
Labels: master

#26241 Add some weights to menu link items
  CRM/ACL/Page/ACL.php
  CRM/ACL/Page/EntityRole.php
  CRM/Activity/Selector/Activity.php
  CRM/Admin/Page/RelationshipType.php
  CRM/Case/Selector/Search.php
  CRM/Contact/Page/View/Note.php
  CRM/Contact/Page/View/Relationship.php
  CRM/Contact/Selector.php
  CRM/Contribute/BAO/ContributionSoft.php
  CRM/Contribute/Page/Tab.php
  CRM/Custom/Page/Option.php
  CRM/Event/Selector/Search.php
  CRM/Member/Selector/Search.php
  ext/civigrant/CRM/Grant/Selector/Search.php
  tests/phpunit/CRM/Core/Payment/AuthorizeNetIPNTest.php
  tests/phpunit/CRM/Core/Payment/PayPalIPNTest.php
  tests/phpunit/CRM/Core/Payment/PayPalProIPNTest.php
  tests/phpunit/CRM/Export/BAO/ExportTest.php
  tests/phpunit/CRM/Member/Selector/SearchTest.php
  tests/phpunit/CRMTraits/Financial/OrderTrait.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: master, merge on pass

#26244 Add weight to a couple more links
  CRM/Mailing/BAO/Mailing.php
  tests/phpunit/api/v3/JobProcessMailingTest.php
Labels: master

#26252 Import help text gone missing
  templates/CRM/Import/Form/DataSource.tpl
Labels: 5.62

#26253 5.62
  templates/CRM/Import/Form/DataSource.tpl
Labels: master

#26200 Following PR-25994 and PR-26074
  CRM/Contact/BAO/Group.php
  CRM/Group/Form/Edit.php
Labels: master, merge on pass

#26250 Add a couple more weights
  CRM/Case/Selector/Search.php
  tests/phpunit/CRM/Case/BAO/CaseTest.php
Labels: master, merge on pass

#26216 Additional event tokens
  CRM/Event/Tokens.php
  tests/phpunit/CRM/Event/Form/ParticipantTest.php
  tests/phpunit/CRM/Utils/TokenConsistencyTest.php
  tests/templates/message_templates/event_offline_receipt_text.tpl
Labels: master

#26211 dev/core#4031 Export dates from SearchKit to spreadsheet in SQL format
  ext/search_kit/Civi/Api4/Action/SearchDisplay/AbstractRunAction.php
  ext/search_kit/Civi/Api4/Action/SearchDisplay/Download.php
Labels: master, merge on pass

#26255 Add is_active to link spec
  CRM/Core/Action.php
Labels: master

#26256 dev/core#3961 - Modify psr-0 namespaces of component extensions to match core
  ext/civi_campaign/civi_campaign.civix.php
  ext/civi_campaign/civi_campaign.php
  ext/civi_campaign/info.xml
  ext/civi_case/civi_case.civix.php
  ext/civi_case/civi_case.php
  ext/civi_case/info.xml
  ext/civi_contribute/civi_contribute.civix.php
  ext/civi_contribute/civi_contribute.php
  ext/civi_contribute/info.xml
  ext/civi_event/civi_event.civix.php
  ext/civi_event/civi_event.php
  ext/civi_event/info.xml
  ext/civi_mail/civi_mail.civix.php
  ext/civi_mail/civi_mail.php
  ext/civi_mail/info.xml
  ext/civi_member/civi_member.civix.php
  ext/civi_member/civi_member.php
  ext/civi_member/info.xml
  ext/civi_pledge/civi_pledge.civix.php
  ext/civi_pledge/civi_pledge.php
  ext/civi_pledge/info.xml
  ext/civi_report/civi_report.civix.php
  ext/civi_report/civi_report.php
  ext/civi_report/info.xml
Labels: master

#26257 Remove unneeded descriptions or replace with help text from Edit Contribution Page & Event
  CRM/Contribute/Form/ContributionPage/Amount.php
  templates/CRM/Contribute/Form/ContributionPage/Amount.hlp
  templates/CRM/Contribute/Form/ContributionPage/Amount.tpl
  templates/CRM/Contribute/Form/ContributionPage/Custom.tpl
  templates/CRM/Contribute/Form/ContributionPage/Premium.tpl
  templates/CRM/Contribute/Form/ContributionPage/Settings.hlp
  templates/CRM/Contribute/Form/ContributionPage/Settings.tpl
  templates/CRM/Contribute/Form/ContributionPage/Widget.tpl
  templates/CRM/Event/Form/ManageEvent/EventInfo.tpl
  templates/CRM/Event/Form/ManageEvent/Fee.hlp
  templates/CRM/Event/Form/ManageEvent/Fee.tpl
  templates/CRM/Friend/Form/Friend.tpl
  templates/CRM/Member/Form/MembershipBlock.hlp
  templates/CRM/Member/Form/MembershipBlock.tpl
Labels: master

#26251 APIv4 - Fix html encoding of rich-text fields
  CRM/Core/BAO/CustomField.php
  CRM/Utils/API/AbstractFieldCoder.php
  CRM/Utils/API/HTMLInputCoder.php
  tests/phpunit/api/v4/Custom/BasicCustomFieldTest.php
Labels: master, has-test

#26164 dev/core#4281 - Fix help bubbles on windows when file param not specified
  CRM/Core/Page/Inline/Help.php
Labels: master

#26254 Fix token boolean filter to work with money & use in templates
  CRM/Core/EntityTokens.php
  Civi/Token/TokenProcessor.php
  tests/phpunit/CRM/Event/Form/Task/BadgeTest.php
  tests/phpunit/CRM/Utils/TokenConsistencyTest.php
  xml/templates/message_templates/contribution_offline_receipt_html.tpl
  xml/templates/message_templates/contribution_offline_receipt_text.tpl
  xml/templates/message_templates/contribution_online_receipt_html.tpl
  xml/templates/message_templates/contribution_online_receipt_text.tpl
  xml/templates/message_templates/membership_offline_receipt_html.tpl
  xml/templates/message_templates/membership_offline_receipt_text.tpl
Labels: master, has-test

#26263 dev/core#3805 Fix handling of minimum_fee token when not set
  CRM/Member/Tokens.php
Labels: master

#26262 Create export mappings without admin perms
  CRM/Core/Permission.php
  ang/exportui.ang.php
  ang/exportui/export.html
  ang/exportui/exportui.js
Labels: master

#26266 Remove BOM from Registration.hlp
  templates/CRM/Event/Form/ManageEvent/Registration.hlp
Labels: master, merge on pass

#26264 Remove unused variables from previously-shared function
  CRM/Contribute/Form/Contribution/Confirm.php
  CRM/Contribute/Form/Contribution/ThankYou.php
Labels: master

#26269 More tests fixed to use fullFormFlow
  tests/phpunit/CRM/Event/Form/ParticipantTest.php
Labels: master

#26267 Enotice fix on frontend_title
  CRM/Financial/BAO/PaymentProcessor.php
Labels: 5.62

#26268 dev/core#4282 Fix isShowMembershipBlock Regression
  CRM/Contribute/Form/ContributionBase.php
  templates/CRM/Contribute/Form/Contribution/Main.tpl
  templates/CRM/Contribute/Form/Contribution/MembershipBlock.tpl
Labels: 5.62

#26273 Resize mailing preview modal
  ang/crmMailing/services.js
Labels: master

#26198 dev/core#4284 Allow deletion of primary email inline on contact
  templates/CRM/Contact/Form/Inline/Email.tpl
  templates/CRM/Contact/Page/View/Summary.js
Labels: master

#26275 SchemaHandler - Cleanup string handling and fix syntax error
  CRM/Core/BAO/SchemaHandler.php
Labels: master

#26271 dev/core#4302 Revert "Remove old deprecated class aliases"
  CRM/ACL/BAO/EntityRole.php
  CRM/Dedupe/BAO/Exception.php
  CRM/Dedupe/BAO/Rule.php
  CRM/Dedupe/BAO/RuleGroup.php
  CRM/Mailing/BAO/Component.php
Labels: 5.62

#26277 dev/core#4282 Fix isShowMembershipBlock & notice fix
  CRM/Contribute/Form/ContributionBase.php
  CRM/Financial/BAO/PaymentProcessor.php
  templates/CRM/Contribute/Form/Contribution/Main.tpl
  templates/CRM/Contribute/Form/Contribution/MembershipBlock.tpl
Labels: 5.61

#26261 Alternate Manage groups in Admin UI extension
  ext/civicrm_admin_ui/ang/afsearchManageGroups.aff.html
  ext/civicrm_admin_ui/ang/afsearchManageGroups.aff.json
  ext/civicrm_admin_ui/managed/SavedSearch_Administer_Manage_Group.mgd.php
Labels: master, merge on pass

#26278 5.62 to master
  CRM/ACL/BAO/EntityRole.php
  CRM/Contribute/Form/ContributionBase.php
  CRM/Dedupe/BAO/Exception.php
  CRM/Dedupe/BAO/Rule.php
  CRM/Dedupe/BAO/RuleGroup.php
  CRM/Financial/BAO/PaymentProcessor.php
  CRM/Mailing/BAO/Component.php
  templates/CRM/Contribute/Form/Contribution/Main.tpl
  templates/CRM/Contribute/Form/Contribution/MembershipBlock.tpl
Labels: master

#24937 AdminUI: add Manage Contribution Pages
  CRM/Contribute/DAO/ContributionPage.php
  ext/civicrm_admin_ui/ang/afsearchManageContributionPages.aff.html
  ext/civicrm_admin_ui/ang/afsearchManageContributionPages.aff.json
  ext/civicrm_admin_ui/managed/SavedSearch_Manage_Contribution_Pages.mgd.php
  xml/schema/Contribute/ContributionPage.xml
Labels: master

#26279 5.61.3 - Add notes. Bump version.
  ext/afform/admin/info.xml
  ext/afform/core/info.xml
  ext/afform/html/info.xml
  ext/afform/mock/info.xml
  ext/authx/info.xml
  ext/civicrm_admin_ui/info.xml
  ext/civigrant/info.xml
  ext/civiimport/info.xml
  ext/ckeditor4/info.xml
  ext/contributioncancelactions/info.xml
  ext/elavon/info.xml
  ext/eventcart/info.xml
  ext/ewaysingle/info.xml
  ext/financialacls/info.xml
  ext/flexmailer/info.xml
  ext/greenwich/info.xml
  ext/legacycustomsearches/info.xml
  ext/message_admin/info.xml
  ext/oauth-client/info.xml
  ext/payflowpro/info.xml
  ext/recaptcha/info.xml
  ext/search_kit/info.xml
  ext/sequentialcreditnotes/info.xml
  release-notes.md
  release-notes/5.61.3.md
  sql/civicrm_generated.mysql
  sql/test_data_second_domain.mysql
  xml/version.xml
Labels: 5.61

#26215 Use balanceAmount token to remove isset in offline_event_receipt
  CRM/Event/Form/Participant.php
  CRM/Event/WorkflowMessage/EventExamples.php
  CRM/Event/WorkflowMessage/EventOfflineReceipt.php
  tests/phpunit/CRM/Event/Form/ParticipantTest.php
  tests/templates/message_templates/event_offline_receipt_text.tpl
  xml/templates/message_templates/event_offline_receipt_html.tpl
  xml/templates/message_templates/event_offline_receipt_text.tpl
Labels: master, has-test

#26281 Standardise casing on ids in WorkflowMessages
  CRM/Batch/Form/Entry.php
  CRM/Contribute/WorkflowMessage/ContributionTrait.php
  CRM/Event/Form/Participant.php
  CRM/Member/Form/Membership.php
  CRM/Member/Form/MembershipRenewal.php
  Civi/WorkflowMessage/GenericWorkflowMessage.php
  tests/phpunit/CRM/Core/BAO/MessageTemplateTest.php
  tests/phpunit/Civi/WorkflowMessage/ExampleWorkflowMessageTest.php
Labels: master

#26280 Add weight to pledges links
  CRM/Pledge/Selector/Search.php
Labels: master

#26185 Drupal 7, refuse the possibility to execute the REST API with blocked users
  CRM/Utils/System/Drupal.php
Labels: master, merge ready

#26284 GenCode on Contribution DAO
  CRM/Contribute/DAO/ContributionPage.php
Labels: master

#26285 [NFC] Belatedly add test for #26164
  tests/phpunit/CRM/Core/Page/Inline/HelpTest.php
Labels: master, merge on pass, has-test

#26286 dev/core#4305 - Fix pluses being turned into spaces in hook_alterAngular
  ext/search_kit/ang/crmSearchAdmin/searchListing/buttons.html
  tests/phpunit/Civi/Angular/ChangeSetTest.php
Labels: master, has-test

#26288 [REF][PHP8.2] Remove seemingly unused write to dynamic property
  tests/phpunit/api/v3/MembershipStatusTest.php
Labels: master

#26287 [REF][PHP8.2] Remove unused entity dynamic property
  tests/phpunit/CRM/Upgrade/Incremental/BaseTest.php
Labels: master

#26293 [REF][PHP8.2] Declare campaigns property
  CRM/Report/Form.php
  CRM/Report/Form/Event/ParticipantListing.php
Labels: master

#26289 [REF][PHP8.2] Only clear cache values if property exists
  tests/phpunit/CRM/Core/BAO/CacheTest.php
Labels: master

#26149 dev/core/#1532 - Adds warning similar to 5.57 if Activity Revisions are present.
  CRM/Upgrade/Incremental/php/FiveSixtyTwo.php
Labels: 5.62

#26295 5.62
  CRM/Upgrade/Incremental/php/FiveSixtyTwo.php
Labels: master

#26228 Only call transitionComponents when transitioning pending/pay later to completed
  CRM/Contribute/BAO/Contribution.php
  CRM/Contribute/Form/Contribution.php
  CRM/Contribute/Form/Task/Batch.php
Labels: master

#26283 Clarify isPrimary, isPaidEvent variables
  CRM/Event/Form/Participant.php
  CRM/Event/Form/ParticipantFeeSelection.php
  xml/templates/message_templates/event_offline_receipt_html.tpl
  xml/templates/message_templates/event_offline_receipt_text.tpl
Labels: master

#26300 dev/core#2486: Add BounceType and BouncePattern APIv4 entities
  Civi/Api4/BouncePattern.php
  Civi/Api4/BounceType.php
Labels: master

#26304 Make sql function IFNULL available in APIv4 and SearchKit
  Civi/Api4/Query/SqlFunctionIFNULL.php
  tests/phpunit/api/v4/Action/SqlFunctionTest.php
Labels: master

#26307 dev/core#4302 Add deprecation warning to functions in renamed classes
  CRM/ACL/BAO/EntityRole.php
  CRM/Dedupe/BAO/DedupeRuleGroup.php
  CRM/Dedupe/BAO/Exception.php
  CRM/Dedupe/BAO/Rule.php
  CRM/Dedupe/BAO/RuleGroup.php
Labels: master

#26071 FormBuilder: add 'Copy' button
  ext/afform/admin/ang/afGuiEditor/afGuiEntity.component.js
  ext/afform/admin/ang/afGuiEditor/elements/afGuiContainer.component.js
  ext/afform/admin/ang/afGuiEditor/elements/afGuiContainer.html
  ext/afform/core/ang/af/afRepeat.directive.js
  ext/afform/core/ang/af/afRepeat.html
Labels: master

#26247 Fix invoice being sent instead of receipt if contribution 'is_pay_later' is true
  xml/templates/message_templates/contribution_online_receipt_subject.tpl
  xml/templates/message_templates/membership_online_receipt_subject.tpl
Labels: master

#26298 (dev/core#4303) Allow {htxt} guard to accommodate variable ID
  CRM/Core/Smarty/plugins/prefilter.htxtFilter.php
  tests/phpunit/CRM/Core/Smarty/plugins/HtxtTest.php
Labels: 5.62

#26310 [NFC] typo fixes
  CRM/Admin/Form/Setting/Miscellaneous.php
Labels: master

#26306 REF - Cleanup unused variable and comment in SearchKit
  ext/search_kit/ang/crmSearchAdmin/displays/crmSearchDisplayAutocomplete.component.js
  ext/search_kit/ang/crmSearchDisplayTable/crmSearchDisplayTable.component.js
Labels: master

#26308 Fix show_public regression
  CRM/Core/BAO/CustomGroup.php
Labels: merge on pass, 5.62

#26312 Port {htxt} fixes to 5.61
  CRM/Core/Smarty/plugins/prefilter.htxtFilter.php
  templates/CRM/Mailing/MailingUI.hlp
  templates/CRM/SMS/Form/Group.hlp
  tests/phpunit/CRM/Core/Smarty/plugins/HtxtTest.php
Labels: 5.61

#26314 5.62 to master
  CRM/Core/BAO/CustomGroup.php
  CRM/Core/Smarty/plugins/prefilter.htxtFilter.php
  tests/phpunit/CRM/Core/Smarty/plugins/HtxtTest.php
Labels: master

#26313 Api4: add calculated field `contact_count` to Group
  Civi/Api4/Service/Spec/Provider/GroupGetSpecProvider.php
  tests/phpunit/api/v4/Entity/GroupContactTest.php
Labels: master, merge on pass, has-test

#26276 (NFC) CiviEventDispatcher - Update type declaration. Add test demonstion
  Civi/Core/CiviEventDispatcherInterface.php
  tests/phpunit/Civi/Core/CiviEventDispatcherTest.php
Labels: master, merge ready

#26319 Addt Fix PHP8 warnings on Participant.tpl
  CRM/Event/Form/Participant.php
Labels: master, merge on pass

#26321 [REF] Bump socket.io-parser to 4.2.3
  package-lock.json
Labels: merge on pass

#26320 dev/core#4310 Fix layout regression in MembershipBlock for Contribution pages
  templates/CRM/Contribute/Form/Contribution/MembershipBlock.tpl
Labels: 5.62

#26322 5.62
  package-lock.json
  templates/CRM/Contribute/Form/Contribution/MembershipBlock.tpl
Labels: master
