Repository civicrm/civicrm-core, pull requests merged in 2023-03, with the labels that each got.

#25695 Pull over a few more deprecations + blockDelete deprecation
  CRM/Badge/BAO/Layout.php
  CRM/Badge/Form/Layout.php
  CRM/Batch/BAO/EntityBatch.php
  CRM/Case/BAO/CaseType.php
  CRM/Contact/BAO/GroupContact.php
Labels: master

#25696 Delete long-deprecated functions
  CRM/Contact/BAO/Contact.php
  CRM/Contact/BAO/Contact/Location.php
  CRM/Core/DAO.php
  CRM/Core/OptionGroup.php
  api/v3/utils.php
Labels: master, merge on pass

#25639 dev/core#4132 Fix import for multi-custom boxes
  CRM/Contact/Import/Parser/Contact.php
  CRM/Import/Parser.php
  ext/civiimport/Civi/Api4/Import/Import.php
  ext/civiimport/Civi/Api4/Import/ImportProcessTrait.php
Labels: 5.59

#25697 5.59.0 releasenotes initial run
  release-notes.md
  release-notes/5.59.0.md
Labels: 5.59

#25699 5.59 to master
  CRM/Contact/Import/Parser/Contact.php
  CRM/Import/Parser.php
  ext/civiimport/Civi/Api4/Import/Import.php
  ext/civiimport/Civi/Api4/Import/ImportProcessTrait.php
  release-notes.md
  release-notes/5.59.0.md
Labels: master

#25701 [NFC] 5.59 release notes sorting and annotating
  contributor-key.yml
  release-notes/5.59.0.md
Labels: 5.59

#25698 Remove deprecated use of $ids
  CRM/Core/BAO/OptionGroup.php
Labels: master, merge ready

#25702 5.59
  contributor-key.yml
  release-notes/5.59.0.md
Labels: master

#25706 Stricter typing in Apiv4
  Civi/Api4/Service/Spec/RequestSpec.php
  Civi/Api4/Service/Spec/SpecGatherer.php
  Civi/Api4/Utils/CoreUtil.php
Labels: master, merge on pass

#25710 Deprecated code removal
  CRM/Event/BAO/Participant.php
  CRM/Event/Form/Participant.php
  CRM/Utils/PDF/Utils.php
  CRM/Utils/System.php
Labels: master

#25708 [NFC] Superficial cleanup in test class
  tests/phpunit/api/v3/ContributionTest.php
Labels: master, merge on pass

#25713 Worldregion - For API-entity-naming, prefer "WorldRegion"
  CRM/Core/DAO/AllCoreTables.data.php
  CRM/Core/DAO/Worldregion.php
  xml/schema/Core/Worldregion.xml
Labels: master

#25689 Php8.2 stop accessing undefined form Property isQuickConfig in `PriceField:addQuickFormElement`
  CRM/Price/BAO/PriceField.php
  CRM/Price/BAO/PriceSet.php
Labels: master

#25704 (dev/core#4147) Add test and fix for various flaky tokens
  CRM/Contact/Tokens.php
  CRM/Core/DAO/AllCoreTables.data.php
  CRM/Core/DAO/Worldregion.php
  CRM/Core/EntityTokens.php
  Civi/Api4/WorldRegion.php
  tests/phpunit/CRM/Core/BAO/MessageTemplateTest.php
  xml/schema/Core/Worldregion.xml
Labels: 5.60

#25634 Add new `\Civi\Exception\DBQueryException` & throw that rather than a `PEAR_Exception`
  CRM/Core/DAO.php
  CRM/Core/Error.php
  CRM/Core/Exception.php
  CRM/Import/DataSource/SQL.php
  CRM/Import/Form/DataSource.php
  Civi/API/Kernel.php
  Civi/Core/Exception/DBQueryException.php
  tests/phpunit/CRM/Core/ErrorTest.php
Labels: master

#25707 Fix bug in tax calculation when recurring overrides with a different value
  CRM/Contribute/BAO/Contribution.php
  tests/phpunit/api/v3/ContributionTest.php
Labels: master, has-test

#25574 dev/core#4127 move standalone profile modification to userSystem
  CRM/UF/Page/Group.php
  CRM/Utils/System/Base.php
  CRM/Utils/System/DrupalBase.php
  CRM/Utils/System/Joomla.php
  CRM/Utils/System/WordPress.php
Labels: master, merge on pass

#25721 Pager missing on Aggregate By Relationship civireport
  CRM/Report/Form/Contribute/History.php
Labels: master

#25718 dev/core#4153 Extend the fields available for PrimaryContact on search
  ext/search_kit/Civi/Search/Admin.php
Labels: master

#25717 (dev/core#4147) Add test and fix for various flaky tokens
  CRM/Contact/Tokens.php
  CRM/Core/DAO/AllCoreTables.data.php
  CRM/Core/DAO/Worldregion.php
  CRM/Core/EntityTokens.php
  Civi/Api4/WorldRegion.php
  tests/phpunit/CRM/Core/BAO/MessageTemplateTest.php
  xml/schema/Core/Worldregion.xml
Labels: 5.59

#25727 (dev/core#4137) Tokens - Filters should be HTML-sensitive
  CRM/Utils/XML.php
  Civi/Token/StandardFilters.php
  Civi/Token/TokenProcessor.php
  tests/phpunit/CRM/Utils/XMLTest.php
  tests/phpunit/Civi/Token/TokenProcessorTest.php
Labels: master, has-test

#25729 Contribution pages crash for logged-in users when CiviMember is disabled
  CRM/Member/BAO/Membership.php
Labels: merge on pass, 5.60

#25728 dev/core#3438 Drupal: Prevent cv fatal if logging before CMS bootstrap
  CRM/Utils/System/Drupal8.php
Labels: master

#25716 Fix for 5.59 upgrade on multilingual
  CRM/Upgrade/Incremental/Base.php
Labels: 5.59

#25730 Fix typing, comments in new StandardFilters class
  Civi/Token/StandardFilters.php
Labels: master, merge on pass

#25731 Fix regression on contribution pages when CiviMember is not enabled
  CRM/Member/BAO/Membership.php
Labels: 5.59

#25733 Fix for 5.59 upgrade on multilingual
  CRM/Upgrade/Incremental/Base.php
Labels: 5.60

#25734 5.59.1 - Add notes. Set version.
  ext/afform/admin/info.xml
  ext/afform/core/info.xml
  ext/afform/html/info.xml
  ext/afform/mock/info.xml
  ext/authx/info.xml
  ext/civicrm_admin_ui/info.xml
  ext/civigrant/info.xml
  ext/civiimport/info.xml
  ext/ckeditor4/info.xml
  ext/contributioncancelactions/info.xml
  ext/elavon/info.xml
  ext/eventcart/info.xml
  ext/ewaysingle/info.xml
  ext/financialacls/info.xml
  ext/flexmailer/info.xml
  ext/greenwich/info.xml
  ext/legacycustomsearches/info.xml
  ext/message_admin/info.xml
  ext/oauth-client/info.xml
  ext/payflowpro/info.xml
  ext/recaptcha/info.xml
  ext/search_kit/info.xml
  ext/sequentialcreditnotes/info.xml
  release-notes.md
  release-notes/5.59.1.md
  sql/civicrm_generated.mysql
  sql/test_data_second_domain.mysql
  xml/version.xml
Labels: 5.59

#25725 Update Import fix to leverage the new exception
  ext/civiimport/Civi/BAO/Import.php
Labels: master

#25735 remove extra field separator field
  templates/CRM/Contact/Import/Form/CSV.tpl
Labels: master

#25711 Filter 'My imports' to only show non-expired
  ext/civiimport/Managed/UserJobSearches.mgd.php
Labels: master

#25740 SearchKit - Add next_birthday calc field
  Civi/Api4/Service/Spec/Provider/ContactGetSpecProvider.php
  tests/phpunit/api/v4/Action/ContactGetTest.php
Labels: master

#25676 Stop passing invariable variables to private function
  CRM/Dedupe/Merger.php
Labels: master

#25743 APIv4 - Don't link to non-existent API entities
  Civi/Api4/Service/Spec/SpecFormatter.php
  Civi/Api4/Utils/CoreUtil.php
Labels: master, merge on pass

#25739 SearchKit - Add select options for MONTH date filter
  CRM/Api4/Page/Api4Explorer.php
  Civi/Api4/Generic/BasicGetFieldsAction.php
  Civi/Api4/Query/SqlFunction.php
  Civi/Api4/Query/SqlFunctionEXTRACT.php
  Civi/Api4/Query/SqlFunctionMONTH.php
  Civi/Api4/Utils/CoreUtil.php
  ext/search_kit/Civi/Search/Admin.php
  ext/search_kit/Civi/Search/Meta.php
  tests/phpunit/api/v4/Action/SqlFunctionTest.php
Labels: master, merge on pass, has-test

#25748 5.60 to master
  CRM/Core/Payment/PayPalProIPN.php
  CRM/Upgrade/Incremental/Base.php
  tests/phpunit/CRM/Core/Payment/PayPalProIPNTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/api/v3/ContributionTest.php
  tests/phpunit/api/v3/JobTest.php
Labels: master

#25745 Remove unvariable variables `toReturn` & `subName` from `Merger`
  CRM/Dedupe/Merger.php
Labels: master

#25746 Remove some deprecated del calls
  CRM/Admin/Form/ContactType.php
  CRM/Contact/BAO/ContactType.php
  CRM/Core/Form/RecurringEntity.php
  CRM/Extension/Manager/Report.php
  CRM/Extension/Manager/Search.php
  CRM/Report/BAO/ReportInstance.php
  CRM/Report/Form/Register.php
  api/v3/ActivityType.php
Labels: master

#25747 Stop using deprecated methods, `ufField::del`
  CRM/Admin/Form/Job.php
  CRM/Core/BAO/Domain.php
  CRM/Core/BAO/OpenID.php
  CRM/Core/BAO/UFField.php
  CRM/Core/BAO/UFGroup.php
  CRM/Core/BAO/WordReplacement.php
  CRM/UF/Form/Field.php
  CRM/UF/Form/Group.php
  api/v3/UFField.php
Labels: master

#25719 Unconditionally assign `quickConfig`, add helper for `getPriceSetID`
  CRM/Contribute/Form/ContributionBase.php
Labels: master

#25753 Remove the correct extraneous field separator field
  templates/CRM/Contact/Import/Form/DataSource.tpl
Labels: merge on pass, 5.60

#25755 5.60
  templates/CRM/Contact/Import/Form/DataSource.tpl
Labels: master

#25756 revert 25735
  templates/CRM/Contact/Import/Form/CSV.tpl
Labels: master, merge on pass

#25294 Afform - Show file field values for existing entities
  ext/afform/core/Civi/Api4/Action/Afform/AbstractProcessor.php
  ext/afform/core/ang/af/fields/File.html
Labels: master

#25750 APIv4 - Add ParticipantStatusType entity
  Civi/Api4/ParticipantStatusType.php
Labels: master

#25700 Change title of is_primary fields consistent with Email
  CRM/Core/DAO/Address.php
  CRM/Core/DAO/IM.php
  CRM/Core/DAO/OpenID.php
  CRM/Core/DAO/Phone.php
  xml/schema/Core/Address.xml
  xml/schema/Core/IM.xml
  xml/schema/Core/OpenID.xml
  xml/schema/Core/Phone.xml
Labels: master

#25751 Relationship Cache check
  CRM/Utils/Check/Component/Schema.php
Labels: master

#25757 Code cleanup: Use `parent::buildForm` in contact import dataSource screen
  CRM/Contact/Import/Form/DataSource.php
  CRM/Import/Form/DataSource.php
Labels: master

#25681 dev/core#4149 Change CKEditor 4 default to not encode HTML entities by default which breaks Smarty syntax and prevents use of crmDate function
  ext/ckeditor4/CRM/Ckeditor4/Form/CKEditorConfig.php
Labels: master, merge ready

#25758 Load submitted `fieldSeparator` on back on `Import Datasource` screen
  CRM/Import/DataSource/CSV.php
Labels: merge on pass, 5.60

#25760 5.60 to master
  CRM/Import/DataSource/CSV.php
Labels: master

#24735 🪥 Fix inconsistent terminology used when referring to Member Since, Membership Start Date and Membership Expiration Date
  CRM/Core/SelectValues.php
  CRM/Member/ActionMapping.php
  CRM/Member/Form/Membership.php
  CRM/Member/Form/MembershipRenewal.php
  CRM/Member/Selector/Search.php
  CRM/Report/Form/Contact/Detail.php
  CRM/Report/Form/Member/ContributionDetail.php
  CRM/Report/Form/Member/Detail.php
  CRM/Report/Form/Member/Summary.php
  ext/legacycustomsearches/templates/CRM/Contact/Form/Search/Custom/FullText.tpl
  templates/CRM/Member/Form/Membership.tpl
  templates/CRM/Member/Form/MembershipRenewal.tpl
  templates/CRM/Member/Form/MembershipStatus.tpl
  templates/CRM/Member/Form/MembershipView.tpl
  templates/CRM/Member/Form/Task/Print.tpl
  templates/CRM/Member/Form/Task/SearchTaskHookSample.tpl
  templates/CRM/Member/Page/Tab.tpl
  templates/CRM/Member/Page/UserDashboard.tpl
  tests/phpunit/CRM/Core/PseudoConstantTest.php
  tests/phpunit/CRM/Member/Form/MembershipTest.php
  tests/phpunit/CRM/Member/Form/Task/PDFLetterTest.php
  xml/templates/civicrm_data.tpl
  xml/templates/civicrm_navigation.tpl
  xml/templates/message_templates/membership_autorenew_cancelled_html.tpl
  xml/templates/message_templates/membership_autorenew_cancelled_text.tpl
  xml/templates/message_templates/membership_offline_receipt_html.tpl
  xml/templates/message_templates/membership_offline_receipt_text.tpl
  xml/templates/message_templates/membership_online_receipt_html.tpl
  xml/templates/message_templates/membership_online_receipt_text.tpl
Labels: master, merge ready

#25761 Regen after civicrm-core#24735
  sql/civicrm_generated.mysql
Labels: master

#25752 Remove remaining non-variable variables
  CRM/Dedupe/Merger.php
Labels: master

#25674 APIv4 - Add 'Update' to conformanceTest
  CRM/Case/BAO/CaseContact.php
  CRM/Case/Form/Activity/OpenCase.php
  CRM/Case/Page/AJAX.php
  CRM/Core/BAO/EntityTag.php
  CRM/Core/BAO/UFJoin.php
  Civi/Api4/Action/CiviCase/CiviCaseSaveTrait.php
  Civi/Api4/Action/EntityTag/Create.php
  Civi/Api4/Action/EntityTag/EntityTagSaveTrait.php
  Civi/Api4/Action/EntityTag/Save.php
  Civi/Api4/Action/EntityTag/Update.php
  Civi/Api4/EntityTag.php
  api/v3/Case.php
  tests/phpunit/CRM/Case/BAO/CaseTest.php
  tests/phpunit/api/v4/Entity/ConformanceTest.php
Labels: master, has-test

#25762 Noisily deprecate unused function
  CRM/Case/BAO/CaseContact.php
Labels: master, merge on pass

#25765 Deprecate relationship::del
  CRM/Admin/Form/RelationshipType.php
  CRM/Contact/BAO/RelationshipType.php
  CRM/Contact/Form/Relationship.php
  CRM/Contact/Page/View/Relationship.php
  api/v3/Relationship.php
Labels: master

#25766 Remove deprecated calls from contribute, financial, remove ManagePremiums deprecated BAO
  CRM/Contribute/BAO/ManagePremiums.php
  CRM/Contribute/BAO/Premium.php
  CRM/Contribute/BAO/Product.php
  CRM/Contribute/Form/ManagePremiums.php
  CRM/Extension/Manager.php
  CRM/Financial/BAO/EntityFinancialAccount.php
  CRM/Financial/BAO/FinancialAccount.php
  CRM/Financial/BAO/FinancialType.php
  CRM/Financial/Form/FinancialAccount.php
  CRM/Financial/Form/FinancialType.php
Labels: master

#25763 Deprecate pledge_payment::del
  CRM/Pledge/BAO/PledgePayment.php
  api/v3/PledgePayment.php
Labels: master

#25769 5.60.0 release notes initial run
  release-notes.md
  release-notes/5.60.0.md
Labels: 5.60

#25772 Smarty notice fix on Merge
  CRM/Dedupe/Merger.php
  templates/CRM/Contact/Form/Merge.tpl
Labels: master

#25771 Consolidate `DataSource.tpl`
  templates/CRM/Contact/Import/Form/DataSource.tpl
  templates/CRM/Import/Form/DataSource.tpl
Labels: master

#25767 More deprecations of `del`
  CRM/Admin/Form/MessageTemplates.php
  CRM/Admin/Form/PaymentProcessor.php
  CRM/Core/BAO/Extension.php
  CRM/Core/BAO/Job.php
  CRM/Core/BAO/MessageTemplate.php
  CRM/Core/BAO/Note.php
  CRM/Core/BAO/OptionGroup.php
  CRM/Core/BAO/OptionValue.php
  CRM/Core/BAO/RecurringEntity.php
  CRM/Core/BAO/Tag.php
  CRM/Financial/BAO/PaymentProcessor.php
Labels: master

#25773 All your base are deleted
  CRM/Core/Base.php
Labels: merge on pass

#25028 Don't crash API4 if pseudoconstant lookups return nothing
  Civi/Api4/Query/Api4SelectQuery.php
  tests/phpunit/api/v4/Action/ContactGetTest.php
Labels: master, merge ready, has-test

#25768 Remove function deprecated noisly in 2020
  CRM/Core/Form/Date.php
Labels: master, merge on pass

#25770 APIv4 - Support `match` in replaceAction
  Civi/Api4/Generic/AbstractSaveAction.php
  Civi/Api4/Generic/BasicReplaceAction.php
  Civi/Api4/Generic/Traits/MatchParamTrait.php
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdmin.component.js
  tests/phpunit/api/v4/Action/ReplaceTest.php
Labels: master

#25749 [REF] Improve function signature for `retrieve()` in `PaypalProIPN` , add test for when trxn_id is present
  CRM/Core/Payment/PayPalProIPN.php
  tests/phpunit/CRM/Core/Payment/PayPalProIPNTest.php
Labels: master

#25677 BAO - Noisily deprecate and stop using deprecated functions
  CRM/Price/BAO/PriceFieldValue.php
  CRM/Price/Form/Option.php
Labels: master, merge on pass

#25187 CiviUnitTestCase - More aggressive simplifications
  ext/civigrant/tests/phpunit/api/v3/GrantTest.php
  tests/phpunit/CRM/Core/Page/HookTest.php
  tests/phpunit/CRM/Core/Payment/BaseIPNTest.php
  tests/phpunit/CRM/Mailing/BaseMailingSystemTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/api/v3/ACLCachingTest.php
  tests/phpunit/api/v3/ACLPermissionTest.php
  tests/phpunit/api/v3/APITest.php
  tests/phpunit/api/v3/APIWrapperTest.php
  tests/phpunit/api/v3/CampaignTest.php
  tests/phpunit/api/v3/ContactTest.php
  tests/phpunit/api/v3/ContributionRecurTest.php
  tests/phpunit/api/v3/CustomValueTest.php
  tests/phpunit/api/v3/DomainTest.php
  tests/phpunit/api/v3/EntityBatchTest.php
  tests/phpunit/api/v3/ImTest.php
  tests/phpunit/api/v3/JobProcessMailingTest.php
  tests/phpunit/api/v3/JobProcessMembershipTest.php
  tests/phpunit/api/v3/MailSettingsTest.php
  tests/phpunit/api/v3/MappingFieldTest.php
  tests/phpunit/api/v3/MappingTest.php
  tests/phpunit/api/v3/MultilingualTest.php
  tests/phpunit/api/v3/OpenIDTest.php
  tests/phpunit/api/v3/ParticipantStatusTypeTest.php
  tests/phpunit/api/v3/PaymentTokenTest.php
  tests/phpunit/api/v3/PcpTest.php
  tests/phpunit/api/v3/PriceFieldValueTest.php
  tests/phpunit/api/v3/PriceSetTest.php
  tests/phpunit/api/v3/SavedSearchTest.php
  tests/phpunit/api/v3/SurveyTest.php
  tests/phpunit/api/v3/SyntaxConformanceTest.php
  tests/phpunit/api/v3/UserTest.php
  tests/phpunit/api/v3/UtilsTest.php
  tests/phpunit/api/v3/WebsiteTest.php
Labels: master

#25775 dev/core#4158 Fix for recurring double ups
  CRM/Core/Payment/PayPalImpl.php
Labels: merge on pass, 5.60

#25777 dev/core#4158 Fix for recurring double ups & dev/core#4105 notes on import
  CRM/Contribute/Import/Parser/Contribution.php
  CRM/Core/Payment/PayPalImpl.php
Labels: merge on pass, 5.59

#25474 Hyphenate Civi-Import in the title/label
  ext/civiimport/info.xml
Labels: master

#25712 Import link - fix search Import SearchDisplays to link to the created contact
  CRM/Core/BAO/UserJob.php
  ext/civiimport/Civi/Api4/Event/Subscriber/ImportSubscriber.php
  ext/civiimport/Civi/Api4/Import/ImportSpecProvider.php
  ext/civiimport/Civi/BAO/Import.php
  ext/civiimport/Managed/ImportSearches.mgd.php
  ext/civiimport/civiimport.php
Labels: master, merge on pass

#25527 Fix dedupe finder performance issue on looking up table size
  CRM/Core/BAO/SchemaHandler.php
  CRM/Core/DAO.php
  CRM/Dedupe/BAO/DedupeRuleGroup.php
  tests/phpunit/CRM/Core/BAO/SchemaHandlerTest.php
  tests/phpunit/CRM/Dedupe/DedupeFinderTest.php
Labels: master, merge on pass

#25774 Fix cache clearing when import table is changed
  ext/civiimport/Civi/Api4/Event/Subscriber/ImportSubscriber.php
  ext/civiimport/tests/phpunit/CiviApiImportTest.php
Labels: master, merge ready, has-test

#25778 dev/core#4156 Fix failure to update organization_name on employees during merge
  CRM/Dedupe/Merger.php
  tests/phpunit/CRM/Dedupe/MergerTest.php
Labels: 5.60

#25783 [NFC] Fix PHP8.2 issues in the Mailing Contact Test
  tests/phpunit/api/v3/MailingContactTest.php
Labels: master

#25781 APIv4 - Deprecate unnecessary constants
  Civi/Api4/Event/Events.php
  Civi/Api4/Event/Subscriber/ActivitySchemaMapSubscriber.php
  Civi/Api4/Event/Subscriber/ContactSchemaMapSubscriber.php
  Civi/Api4/Event/Subscriber/MessageTemplateSchemaMapSubscriber.php
  Civi/Api4/Service/Schema/SchemaMapBuilder.php
Labels: master

#25785 5.59.2 - Add notes. Set version.
  ext/afform/admin/info.xml
  ext/afform/core/info.xml
  ext/afform/html/info.xml
  ext/afform/mock/info.xml
  ext/authx/info.xml
  ext/civicrm_admin_ui/info.xml
  ext/civigrant/info.xml
  ext/civiimport/info.xml
  ext/ckeditor4/info.xml
  ext/contributioncancelactions/info.xml
  ext/elavon/info.xml
  ext/eventcart/info.xml
  ext/ewaysingle/info.xml
  ext/financialacls/info.xml
  ext/flexmailer/info.xml
  ext/greenwich/info.xml
  ext/legacycustomsearches/info.xml
  ext/message_admin/info.xml
  ext/oauth-client/info.xml
  ext/payflowpro/info.xml
  ext/recaptcha/info.xml
  ext/search_kit/info.xml
  ext/sequentialcreditnotes/info.xml
  release-notes.md
  release-notes/5.59.2.md
  sql/civicrm_generated.mysql
  sql/test_data_second_domain.mysql
  xml/version.xml
Labels: 5.59

#25657 dev/core#4144 Fix smarty notice on isDuplicate
  CRM/Profile/Form.php
  templates/CRM/Profile/Form/Dynamic.tpl
Labels: master, merge on pass

#25789 [REF][PHP8.2] Declare property on CRM_Event_Import_Parser_ParticipantTest
  tests/phpunit/CRM/Event/Import/Parser/ParticipantTest.php
Labels: master

#25788 [REF][PHP8.2] Declare property on CRM_Core_ErrorTest
  tests/phpunit/CRM/Core/ErrorTest.php
Labels: master

#25786 set-version.php - Fix warning on PHP 8.1
  tools/bin/scripts/set-version.php
Labels: master, merge on pass

#25791 [REF][PHP8.2] Fix use of self in callables deprecation
  CRM/Dedupe/BAO/DedupeRuleGroup.php
Labels: master

#25794 (REF) Remove unused onPopupClose variables
  CRM/Profile/Form/Edit.php
  templates/CRM/Profile/Page/MultipleRecordFieldsListing.tpl
Labels: master

#25793 [REF][PHP8.2] Refactor api_v3_PriceFieldValueTest with primary aim of improving PHP 8.2 compatiability
  tests/phpunit/api/v3/PriceFieldValueTest.php
Labels: master

#25792 [REF][PHP8.2] Refactor api_v3_ImTest with primary aim of improving PHP 8.2 compatiability
  tests/phpunit/api/v3/ImTest.php
Labels: master

#25795 [REF][PHP8.2] Refactor use of pageParams properties
  tests/phpunit/CRM/Contribute/Form/ContributionTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/E2E/Extern/WidgetTest.php
  tests/phpunit/api/v3/ContributionTest.php
  tests/phpunit/api/v3/FinancialTypeACLTest.php
Labels: master, merge on pass

#25798 [NFC] cleanup in `ChangeFeeSelectionTest`
  CRM/Price/BAO/LineItem.php
  tests/phpunit/CRM/Event/BAO/ChangeFeeSelectionTest.php
Labels: master

#25797 Php8.2 fixes in unit tests
  tests/phpunit/CRM/Pledge/Form/SearchTest.php
Labels: master

#25800 Php8.2 fixes in report `addToDeveloperTab` function
  CRM/Report/Form.php
  api/v3/ReportTemplate.php
Labels: master, merge on pass

#25742 Afform - Fix editing search filters nested within multiple containers
  ext/afform/admin/ang/afGuiEditor/elements/afGuiContainer.component.js
  ext/afform/admin/ang/afGuiEditor/elements/afGuiField.component.js
Labels: 5.60

#24819 SearchKit - POC help text
  ext/search_kit/ang/crmSearchAdmin/compose.html
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdmin.component.js
  ext/search_kit/ang/crmSearchAdmin/crmSearchClause.component.js
  ext/search_kit/ang/crmSearchAdmin/crmSearchClause.html
  ext/search_kit/ang/crmSearchAdmin/displays/colType/field.html
  ext/search_kit/ang/crmSearchAdmin/displays/colType/html.html
  ext/search_kit/ang/crmSearchAdmin/displays/searchAdminDisplayGrid.component.js
  ext/search_kit/ang/crmSearchAdmin/displays/searchAdminDisplayList.component.js
  ext/search_kit/ang/crmSearchAdmin/displays/searchAdminDisplayTable.component.js
  ext/search_kit/templates/CRM/Search/Help/Compose.hlp
  ext/search_kit/templates/CRM/Search/Help/Display.hlp
Labels: master, merge on pass

#25796 Remove dependence on cache/integration-tests
  CRM/Core/ClassLoader.php
  composer.json
  composer.lock
  tests/phpunit/CiviTest/CiviSimpleCacheTest.php
  tests/phpunit/E2E/Cache/CacheTestCase.php
Labels: master

#25803 Case start_date/end_date are not datetime
  CRM/Case/DAO/Case.php
  xml/schema/Case/Case.xml
Labels: master

#25805 Logging ReportDetail: update breadcrumb to use CiviCRM Home for disambiguation
  CRM/Logging/ReportDetail.php
Labels: master

#25787 Import data source Re-use already uploaded data, optionally on use of 'back' button
  CRM/Import/DataSource/CSV.php
  CRM/Import/Form/DataSource.php
  CRM/Import/Forms.php
  ext/civiimport/Civi/Api4/Event/Subscriber/ImportSubscriber.php
  templates/CRM/Import/Form/DataSource.tpl
Labels: master

#25738 field separator is a required field
  CRM/Import/DataSource/CSV.php
Labels: master

#25809 [REF][PHP8.2] Tidy up properties in api_v3_CaseContactTest
  tests/phpunit/api/v3/CaseContactTest.php
Labels: master, merge on pass

#25736 don't show USPS warning when USPS lookup disabled
  CRM/Contact/Import/Form/DataSource.php
Labels: master

#25812 [PHP8.2] (Ref) Remove unused dynamic property in report form class
  CRM/Report/Form.php
Labels: master, merge on pass

#25813 dev/core#4186 regression for Contact Reference Autocomplete
  CRM/Core/BAO/CustomField.php
Labels: merge on pass, 5.60

#25814 [REF] Fix issue where the strict typing was causing false notices to …
  CRM/Core/Payment/PayPalIPN.php
Labels: master, merge on pass

#25759 Fix really annoying notice on mispelt variable name `$isCheked`
  CRM/Contact/Import/Form/MapField.php
  CRM/Import/Form/MapField.php
  templates/CRM/Contact/Import/Form/MapField.tpl
  templates/CRM/Import/Form/MapTableCommon.tpl
Labels: master

#25810 dev/core#4184 Fix Import over-authorization
  ext/civiimport/Civi/Api4/Event/Subscriber/ImportSubscriber.php
Labels: merge on pass, 5.60

#25815 Merge 5.60 to master
  CRM/Core/BAO/CustomField.php
  CRM/Core/Payment/PayPalImpl.php
  CRM/Dedupe/Merger.php
  ext/afform/admin/ang/afGuiEditor/elements/afGuiContainer.component.js
  ext/afform/admin/ang/afGuiEditor/elements/afGuiField.component.js
  ext/civiimport/Civi/Api4/Event/Subscriber/ImportSubscriber.php
  release-notes.md
  release-notes/5.60.0.md
  tests/phpunit/CRM/Dedupe/MergerTest.php
Labels: master

#25816 Add links to search kits to import preview screen, when Civ-Import is enabled
  CRM/Import/Form/Preview.php
  ext/civiimport/civiimport.php
  templates/CRM/Contribute/Import/Form/Preview.tpl
Labels: master, merge on pass

#25802 [PHP8.2] declare deleteMessage on `entityFormTrait`
  CRM/Admin/Form/RelationshipType.php
  CRM/Core/Form/EntityFormTrait.php
  CRM/Financial/Form/FinancialType.php
  CRM/Member/Form/MembershipType.php
  CRM/Price/Form/Set.php
  CRM/UF/Form/Group.php
  templates/CRM/Member/Form/Membership.tpl
Labels: master

#25817 Fix typo that causes e-notice in just-merged commit
  CRM/Import/Form/Preview.php
Labels: master

#25687 (dev/core#4124) Past campaigns are not to be assigned via batch updat…
  CRM/Core/BAO/UFGroup.php
Labels: master, merge ready

#25820 Do not report missing triggers if the user cannot check them
  CRM/Utils/Check/Component/Schema.php
  settings/Core.setting.php
Labels: master, merge on pass

#25790 [REF][PHP8.2] Only set properties which exist within ArrayFormatTrait->loadArray()
  Civi/Schema/Traits/ArrayFormatTrait.php
Labels: master, merge ready

#25806 dev/core#4166 Fix Contribute Import Parser fatal when soft-credit is empty
  CRM/Contribute/Import/Parser/Contribution.php
Labels: 5.60

#25825 5.60 to master
  CRM/Contribute/Import/Parser/Contribution.php
Labels: master

#25782 Fix profile search listings columns are sometimes blank.
  CRM/Profile/Selector/Listings.php
Labels: master

#25828 [REF][PHP8.2] Don't use a property where a variable will do (CRM_Contact_Page_View_Summary)
  CRM/Contact/Page/View/Summary.php
Labels: master, merge on pass

#25818 WorkflowMessage - Enable strict parsing of annotations
  Civi/WorkflowMessage/Traits/ReflectiveWorkflowTrait.php
Labels: master

#25834 [REF][PHP8.2] Declare property in CRM_Contact_Form_DedupeFind
  CRM/Contact/Form/DedupeFind.php
Labels: master, merge on pass

#25836 (REF) PHPUnit - Allow env-var to specify version
  tools/mixin/bin/mixer
  tools/scripts/phpunit
Labels: master, merge on pass

#25826 Backports of Import fix, dedupe fix
  CRM/Contribute/Import/Parser/Contribution.php
  CRM/Dedupe/Merger.php
  tests/phpunit/CRM/Dedupe/MergerTest.php
Labels: 5.59

#25835 Remove require_dev yoast/phpunit-polyfills
  composer.json
  composer.lock
Labels: merge ready, 5.60

#25837 5.59.3 - Set version. Add notes.
  ext/afform/admin/info.xml
  ext/afform/core/info.xml
  ext/afform/html/info.xml
  ext/afform/mock/info.xml
  ext/authx/info.xml
  ext/civicrm_admin_ui/info.xml
  ext/civigrant/info.xml
  ext/civiimport/info.xml
  ext/ckeditor4/info.xml
  ext/contributioncancelactions/info.xml
  ext/elavon/info.xml
  ext/eventcart/info.xml
  ext/ewaysingle/info.xml
  ext/financialacls/info.xml
  ext/flexmailer/info.xml
  ext/greenwich/info.xml
  ext/legacycustomsearches/info.xml
  ext/message_admin/info.xml
  ext/oauth-client/info.xml
  ext/payflowpro/info.xml
  ext/recaptcha/info.xml
  ext/search_kit/info.xml
  ext/sequentialcreditnotes/info.xml
  release-notes.md
  release-notes/5.59.3.md
  sql/civicrm_generated.mysql
  sql/test_data_second_domain.mysql
  xml/version.xml
Labels: merge on pass, 5.59

#25832 Afform - set multi-select values from url
  ext/afform/core/ang/af/afField.component.js
Labels: master

#25839 Merge 5.60 to master
  composer.json
  composer.lock
Labels: master

#25838 5.60
  composer.json
  composer.lock
Labels: master

#25822 Afform - Fix validateBySavedSearch
  ext/afform/core/Civi/Api4/Action/Afform/AbstractProcessor.php
Labels: 5.60

#25843 5.60 to master
  ext/afform/core/Civi/Api4/Action/Afform/AbstractProcessor.php
Labels: master

#25840 5.60 to master
  ext/afform/core/Civi/Api4/Action/Afform/AbstractProcessor.php
Labels: master

#25824 Afform - Allow contact created/modified date fields to be used as filters
  CRM/Contact/DAO/Contact.php
  xml/schema/Contact/Contact.xml
Labels: master, merge on pass

#25841 Remove un-used, un-displayed button
  CRM/Contribute/Import/Form/DataSource.php
Labels: master

#25842 Deprecated `buildSavedMappingFields` noisily
  CRM/Import/Form/MapField.php
Labels: master

#25827 SearchKit - Handle comma-separated values passed from Afform url
  ext/search_kit/Civi/Api4/Action/SearchDisplay/AbstractRunAction.php
Labels: master

#25776 dev/core#4000 Fix (old) regression - ensure only template contribution updates update recur
  CRM/Contribute/BAO/Contribution.php
  CRM/Contribute/BAO/ContributionRecur.php
  CRM/Upgrade/Incremental/php/FiveSixtyOne.php
  tests/phpunit/CRM/Contribute/BAO/ContributionRecurTest.php
Labels: master

#25829 [REF] [php8.2] Remove unused parameters from `Contribute_PDFLetter::buildContributionArray`
  CRM/Contribute/Form/Task/PDFLetter.php
  tests/phpunit/CRM/Contribute/Form/Task/PDFLetterCommonTest.php
Labels: master

#25831 [PHP8.2] Remove unused setting on undeclared properties
  CRM/Case/Form/Task/PDF.php
  CRM/Contact/Form/Task/PDF.php
Labels: master

#25850 PHP8 - Update symfony/var-dumper
  composer.json
  composer.lock
Labels: master, merge on pass

#25849 dev/core#4190 Fix issue where defaultValues needs to be an array not …
  CRM/Case/Form/Case.php
Labels: merge on pass, 5.60

#25847 5.60
  CRM/Case/Form/Case.php
  CRM/Contribute/BAO/ContributionSoft.php
Labels: master

#25848 dev/core#4187 Fix errors when sorting by contributor name or receive date in the soft credit table
  CRM/Contribute/BAO/ContributionSoft.php
Labels: 5.59

#25811 dev/core#4184 Permit access to template user jobs (imports)
  CRM/Core/BAO/UserJob.php
Labels: master, merge on pass

#25853 Avoid type error in CRM_Core_Form on php 8
  CRM/Case/Form/Case.php
  CRM/Core/Form.php
Labels: master

#25799 [PHP8.2] [Test] Remove use of (often undeclared) property `_invoiceID` in tests & one instance of `paymentProcessorID2`
  tests/phpunit/CRM/Core/Payment/AuthorizeNetIPNTest.php
  tests/phpunit/CRM/Core/Payment/PayPalIPNTest.php
  tests/phpunit/CRM/Core/Payment/PayPalProIPNTest.php
  tests/phpunit/CRM/Export/BAO/ExportTest.php
  tests/phpunit/CRM/Member/Selector/SearchTest.php
  tests/phpunit/CRMTraits/Financial/OrderTrait.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: master

#25801 [PHP8.2] Clean up in `apiv3_ParticipantTest` with view to 8.2 compatibility
  tests/phpunit/api/v3/ParticipantTest.php
Labels: master

#25856 CiviUnitTestCase - During teardown, ensure that we cleanup locks
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: master

#25858 AutoClean - Optionally allow explicit cleanup
  CRM/Utils/AutoClean.php
Labels: master, merge on pass

#25844 [REF][PHP8.2] Get rid of dynamic properties in CRM_Core_Payment_ProcessorFormTest
  tests/phpunit/CRM/Core/Payment/ProcessorFormTest.php
Labels: master

#25860 [REF] Replace use of legacy `$dao->query()` with `CRM_Core_DAO::executeQuery()`
  CRM/Dedupe/Finder.php
Labels: master

#25865 [REF][PHP8.2] Refactor getParticipantOrderParams to never write a dynamic property
  tests/phpunit/CRM/Contact/Form/Search/Custom/PriceSetTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: master, merge on pass

#25864 [REF][PHP8.2] Refactor api_v3_ParticipantPaymentTest
  tests/phpunit/api/v3/ParticipantPaymentTest.php
Labels: master
