Repository civicrm/civicrm-core, pull requests merged in 2023-07, with the labels that each got.

#26692 Typo correct for MailingEventReply.php
  ext/civi_mail/Civi/Api4/MailingEventReply.php
Labels: master, merge on pass

#26693 Don't check for PHP 5 on Mapping Settings
  CRM/Admin/Form/Setting/Mapping.php
Labels: master

#26689 Add calculated fields to API 4 for total mailing stats
  Civi/Api4/Service/Spec/Provider/MailingGetSpecProvider.php
  tests/phpunit/api/v4/Entity/MailingEvent.php
Labels: master

#26694 Add calculated optout & unsub mailing stats to API 4
  Civi/Api4/Service/Spec/Provider/MailingGetSpecProvider.php
  tests/phpunit/api/v4/Entity/MailingEvent.php
Labels: master

#25224 APIv4, Case API, configure options and suffixes for medium_id field
  ext/civi_case/Civi/Api4/Service/Spec/Provider/CaseCreationSpecProvider.php
Labels: master

#26697 Put link first in SearchDisplay Links options
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdminLinkGroup.html
Labels: master, merge on pass

#26672 Standalone - Track logged-in user object
  CRM/Utils/System/Standalone.php
  ext/standaloneusers/Civi/Authx/Standalone.php
  ext/standaloneusers/Civi/Standalone/Security.php
Labels: master, merge ready

#26701 [Tests] Fix a few more places to use eventTrait & remove `legacyEventCreate`
  tests/phpunit/CRM/Event/Form/Registration/ConfirmTest.php
  tests/phpunit/CRM/Upgrade/SnapshotTest.php
  tests/phpunit/Civi/Token/ImpliedContextSubscriberTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: master, merge on pass

#26704 Test cleanup in BAO_ParticipantTest
  tests/phpunit/CRM/Event/BAO/ParticipantTest.php
  tests/phpunit/CRM/Event/Form/ParticipantTest.php
  tests/phpunit/CRM/Event/Form/Registration/RegisterTest.php
  tests/phpunit/CRM/Event/Form/SearchTest.php
Labels: master, merge on pass

#26702 Fix debug permissions for API 4 Explorer debug
  ang/api4Explorer.ang.php
  ang/api4Explorer/Explorer.html
  ang/api4Explorer/Explorer.js
Labels: master, merge on pass

#26703 Allow Drupal webstest user to view debug output
  tools/drupal/modules/civicrm_webtest/civicrm_webtest.install
Labels: master, merge on pass

#26695 [NFC] First pass at 5.63 release notes
  contributor-key.yml
  release-notes/5.63.0.md
Labels: 5.63

#26706 5.63
  contributor-key.yml
  release-notes/5.63.0.md
Labels: master

#26707 Fix ACLPermissionTrait to use EventTest create function
  CRM/Core/DAO/AllCoreTables.php
  Civi/Test/ACLPermissionTrait.php
  Civi/Test/ContactTestTrait.php
  Civi/Test/EventTestTrait.php
  tests/phpunit/CRM/Core/BAO/ActionScheduleTest.php
  tests/phpunit/CRM/Core/BAO/FinancialTrxnTest.php
  tests/phpunit/CRM/Core/Permission/BaseTest.php
  tests/phpunit/CRM/Event/BAO/EventPermissionsTest.php
  tests/phpunit/CRM/Event/Form/SearchTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/api/v3/ReportTemplateTest.php
Labels: master, merge on pass

#26708 Use eventCreateUnpaid in participantCreate
  tests/phpunit/CRM/Event/ActionMappingTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: master

#26698 SearchKit - Allow custom fields in join conditions
  Civi/Api4/Query/Api4SelectQuery.php
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdmin.component.js
  tests/phpunit/api/v4/Custom/ContactCustomJoinTest.php
Labels: master, has-test

#26711 Don't show SQL text in SK if user does not have view debug permission
  ext/search_kit/ang/crmSearchAdmin.ang.php
  ext/search_kit/ang/crmSearchAdmin/resultsTable/crmSearchAdminResultsTable.component.js
  ext/search_kit/ang/crmSearchAdmin/resultsTable/debug.html
Labels: master

#26713 CRM_Mailing_Form_Optout, CRM_Mailing_Form_Unsubscribe: change properties to protected from private
  CRM/Mailing/Form/Optout.php
  CRM/Mailing/Form/Unsubscribe.php
Labels: master, merge on pass

#26696 clearTempTables: fix condition for user_job check
  CRM/Core/Config.php
Labels: master

#26712 Install SK as part of headless test baseline
  Civi/Test.php
  tests/phpunit/api/v4/Api4TestBase.php
Labels: master, merge on pass

#26714 [REF] Code cleanup; remove unused vars and remove CRM_Utils_Array::value
  CRM/Core/BAO/CustomField.php
  CRM/Core/BAO/CustomQuery.php
  CRM/Utils/Address.php
Labels: master

#26710 APIv4 - Add more metadata to CustomValue entities; use AutoService
  Civi/Api4/CustomValue.php
  Civi/Api4/Provider/CustomEntityProvider.php
  Civi/Core/Container.php
  tests/phpunit/api/v4/Custom/CustomValueTest.php
Labels: master

#26709 Fix ChangeFeeSelectionTest to use eventCreatePaid
  CRM/Price/BAO/LineItem.php
  tests/phpunit/CRM/Event/BAO/ChangeFeeSelectionTest.php
Labels: master

#26505 Reduce PHP warnings with paymentBlock
  templates/CRM/common/paymentBlock.tpl
Labels: master

#26716 SearchKit - Provide context information to subscribers
  Civi/Api4/Generic/Traits/SavedSearchInspectorTrait.php
  ext/search_kit/Civi/Api4/Action/SearchDisplay/GetDefault.php
Labels: master

#26718 Add weight to Group Links
  CRM/Contact/BAO/Group.php
  tests/phpunit/CRM/Group/Page/AjaxTest.php
Labels: master, merge on pass

#26646 Drop unused table civicrm_action_mapping
  CRM/Core/DAO/ActionMapping.php
  CRM/Core/DAO/AllCoreTables.data.php
  CRM/Upgrade/Incremental/Base.php
  CRM/Upgrade/Incremental/php/FiveSixtyFour.php
  Civi/ActionSchedule/Mapping.php
  sql/civicrm_data/civicrm_action_mapping.sqldata.php
  sql/civicrm_generated.mysql
  xml/schema/Core/ActionMapping.xml
  xml/templates/civicrm_data.tpl
Labels: master

#26720 Remove some unused test functions
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: master, merge on pass

#26715 Include `entityTrait` in `ContactTestTrait`
  Civi/Test/ContactTestTrait.php
  ext/legacycustomsearches/tests/phpunit/Civi/Searches/FullTextTest.php
  tests/phpunit/CRM/Core/Payment/BaseIPNTest.php
Labels: master, merge on pass

#26721 Add frontend_title to various data set up places
  CRM/Case/xml/configuration.sample/case_sample.mysql.tpl
  CRM/Core/CodeGen/GenerateData.php
  tests/phpunit/CRM/Contact/BAO/SavedSearchDataSets/242_email_on_hold.sql
  tests/phpunit/CRM/Contact/BAO/SavedSearchDataSets/251_empty_email_on_hold.sql
  tests/phpunit/CRM/Contact/BAO/SavedSearchDataSets/801_pre44_billing_email_smartgroup.sql
  tests/phpunit/CRM/Contact/BAO/SavedSearchDataSets/94_legacy_state_province.sql
  tests/phpunit/CRM/Contact/BAO/SavedSearchDataSets/primary_multiple_state_province.sql
  xml/templates/case_sample.tpl
Labels: master, merge on pass

#26705 Render Email input as type="email"
  CRM/Core/DAO/Email.php
  Civi/Api4/Generic/BasicGetFieldsAction.php
  ext/afform/admin/ang/afGuiEditor/inputType/Email.html
  ext/afform/core/ang/af/fields/Email.html
  ext/search_kit/ang/crmSearchTasks/crmSearchInput/crmSearchInputVal.component.js
  ext/search_kit/ang/crmSearchTasks/crmSearchInput/email.html
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/SearchRunTest.php
  xml/schema/Core/Email.xml
Labels: master

#23724 Towards consistency for displaying test entities. Stop hiding test entities on some dashboards
  CRM/Activity/Form/Search.php
  CRM/Contribute/Form/Search.php
  CRM/Event/Form/Search.php
  CRM/Member/Form/Search.php
  CRM/Pledge/Form/Search.php
  CRM/Pledge/Selector/Search.php
Labels: master, merge ready

#26717 Remove now unsed createEvent test function from test baseClass
  tests/phpunit/CRM/Upgrade/SnapshotTest.php
  tests/phpunit/CRM/Utils/TokenConsistencyTest.php
  tests/phpunit/Civi/Token/ImpliedContextSubscriberTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: master, merge on pass

#26669 #4360 #4384 fixing multiple regressions with path civicrm/contact/search
  ext/civicrm_admin_ui/CRM/CivicrmAdminUi/Upgrader.php
  ext/civicrm_admin_ui/ang/afsearchContactSearch.aff.json
  ext/civicrm_admin_ui/civicrm_admin_ui.civix.php
  ext/civicrm_admin_ui/info.xml
Labels: master, merge on pass

#26699 dev/joomla#51 Fix Joomla permissions warning
  CRM/Core/Permission/Joomla.php
Labels: master

#26724 [REF] Autoformat php short array syntax
  CRM/Campaign/Form/Search.php
  CRM/Case/Audit/AuditConfig.php
  CRM/Contribute/Form/UpdateBilling.php
  CRM/Contribute/Page/ContributionPage.php
  CRM/Core/BAO/CustomField.php
  CRM/Core/BAO/Note.php
  CRM/Core/BAO/Setting.php
  CRM/Core/BAO/Tag.php
  CRM/Core/Block.php
  CRM/Core/Region.php
  CRM/Event/Import/Form/MapField.php
  CRM/Event/Page/ParticipantListing.php
  CRM/Extension/Browser.php
  CRM/Extension/Container/Default.php
  CRM/Extension/Downloader.php
  CRM/Group/Form/Edit.php
  CRM/Import/Form/MapField.php
  CRM/Mailing/Event/BAO/MailingEventBounce.php
  CRM/Member/Import/Form/MapField.php
  CRM/Member/Page/DashBoard.php
  CRM/Pledge/BAO/PledgeBlock.php
  CRM/Report/Form.php
  CRM/Report/Form/Campaign/SurveyDetails.php
  CRM/Report/Form/Contact/Summary.php
  CRM/Report/Form/Contribute/Repeat.php
  CRM/Report/Form/Event/ParticipantListing.php
  CRM/SMS/Page/Provider.php
  CRM/SMS/Provider.php
  CRM/Upgrade/Incremental/php/FiveSixteen.php
  CRM/Upgrade/Incremental/php/TimezoneRevertTrait.php
  CRM/Utils/Check/Component.php
  CRM/Utils/Hook/Joomla.php
  CRM/Utils/Hook/UnitTests.php
  CRM/Utils/Hook/WordPress.php
  CRM/Utils/System/Drupal8.php
  CRM/Utils/System/WordPress.php
  Civi/Core/Themes.php
  Civi/Core/Themes/Resolvers.php
  Civi/Test/MailingTestTrait.php
  Civi/Test/TAP7.php
  Civi/Test/TAP9.php
  Civi/Test/TAPLegacy.php
  ext/ewaysingle/CRM/Core/Payment/eWAY.mgd.php
  ext/legacycustomsearches/CRM/Contact/Form/Search/Custom.php
  ext/oauth-client/tests/phpunit/CRM/OAuth/MailSetupTest.php
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/AbstractRunActionTest.php
  install/civicrm.php
  install/index.php
Labels: master, merge on pass

#26726 Update Api.php to correct external_identifier to type STRING
  CRM/Custom/Import/Parser/Api.php
Labels: master

#26728 Merged #26726 into master.
  contributor-key.yml
Labels: master

#26730 SearchKit - Fix check for smarty syntax in rewrite output
  ext/search_kit/Civi/Api4/Action/SearchDisplay/AbstractRunAction.php
Labels: master

#26731 REF - Replace CRM_Utils_Array::value with ??
  CRM/Campaign/Page/DashBoard.php
  CRM/Campaign/Page/SurveyType.php
  CRM/Case/BAO/Case.php
  CRM/Case/XMLProcessor/Report.php
  CRM/Contact/BAO/Query.php
  CRM/Contact/Form/Task/SMSCommon.php
  CRM/Core/BAO/Navigation.php
  CRM/Core/Form.php
  CRM/Event/Form/Participant.php
  CRM/Event/Page/EventInfo.php
  CRM/Financial/BAO/EntityFinancialAccount.php
  CRM/Financial/Form/FinancialAccount.php
  CRM/Financial/Form/FinancialTypeAccount.php
  CRM/Logging/Schema.php
  CRM/PCP/Page/PCPInfo.php
  CRM/Pledge/Form/Pledge.php
  CRM/Profile/Form.php
  CRM/Report/Form.php
  CRM/Report/Form/Contribute/Detail.php
  CRM/Report/Form/Instance.php
  CRM/UF/Form/Field.php
  CRM/Utils/Date.php
  CRM/Utils/Pager.php
Labels: master

#26725 [NFC] Update test that's no longer doing what it was doing
  tests/phpunit/CRM/Core/BAO/SchemaHandlerTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/api/v3/RelationshipTest.php
Labels: master

#26719 Add weights to contact search actions
  CRM/Contact/BAO/Contact.php
  CRM/Contact/Form/Search.php
  CRM/Contact/Selector.php
  CRM/Core/Action.php
Labels: master

#26732 AdminUI: Convert Job Log page civicrm/admin/joblog
  ext/civicrm_admin_ui/ang/afsearchScheduledJobsLog.aff.html
  ext/civicrm_admin_ui/ang/afsearchScheduledJobsLog.aff.json
  ext/civicrm_admin_ui/managed/SavedSearch_Scheduled_Jobs_Log.mgd.php
Labels: master, merge on pass

#26734 Remove unused variables, fix a couple of ==
  CRM/Contact/Selector.php
Labels: master

#26736 Fix another place weight is not passed
  CRM/Contact/Selector.php
Labels: master

#26735 Fix recent regression - Use consistent value for checkPermissions in merger
  CRM/Dedupe/Merger.php
Labels: 5.63

#26738 5.63
  CRM/Dedupe/Merger.php
Labels: master

#26737 Update related contribution trxn_id before sending email [must go into 5.64]
  CRM/Financial/BAO/Payment.php
Labels: master

#26733 AdminUI: Convert Mail Accounts page civicrm/admin/mailSettings
  CRM/Mailing/xml/Menu/Mailing.xml
  ext/civi_mail/Civi/Api4/MailSettings.php
  ext/civicrm_admin_ui/ang/afsearchMailAccounts.aff.html
  ext/civicrm_admin_ui/ang/afsearchMailAccounts.aff.json
  ext/civicrm_admin_ui/managed/SavedSearch_Manage_Mail_Accounts.mgd.php
Labels: master

#26740 Fix apiv4 bug on custom fields with spaces in name
  Civi/Api4/Query/Api4Query.php
  Civi/Api4/Query/Api4SelectQuery.php
  tests/phpunit/api/v4/Custom/ContactCustomJoinTest.php
Labels: has-test

#26190 Fix Translation to load related language more reliably
  CRM/Core/BAO/TranslateGetWrapper.php
  CRM/Core/BAO/Translation.php
  tests/phpunit/CRM/Core/BAO/MessageTemplateTest.php
Labels: master, has-test

#26739 Use consistent value for checkPermissions in merger
  CRM/Dedupe/Merger.php
Labels: 5.62

#26743 (dev/core#4391) Prohibit uninstallation of core components
  CRM/Extension/Manager.php
  ext/civi_campaign/info.xml
  ext/civi_case/info.xml
  ext/civi_contribute/info.xml
  ext/civi_event/info.xml
  ext/civi_mail/info.xml
  ext/civi_member/info.xml
  ext/civi_pledge/info.xml
  ext/civi_report/info.xml
Labels: 5.63

#26744 dev/core#4413 Don't remove core component permissions when disabled
  CRM/Core/Config.php
Labels: master

#26745 Make the `recur_id` field of Contributions available to FormBuilder
  CRM/Contribute/DAO/Contribution.php
  xml/schema/Contribute/Contribution.xml
Labels: master

#26690 Split MembershipBlock.tpl into 2
  templates/CRM/Contribute/Form/Contribution/Confirm.tpl
  templates/CRM/Contribute/Form/Contribution/Main.tpl
  templates/CRM/Contribute/Form/Contribution/MainMembershipBlock.tpl
  templates/CRM/Contribute/Form/Contribution/MembershipBlock.tpl
  templates/CRM/Contribute/Form/Contribution/ThankYou.tpl
Labels: master

#26751 Remove unneeded and strange profile field save success alert
  CRM/UF/Form/Field.php
Labels: master

#26747 🌶️ dev/core/-/issues/4416 CiviCRM 5.63.0 - Regression, Mailing click tracking now returns: Error 500 malformed header from script 'url.php': Bad header for all tracked URLs
  extern/url.php
Labels: 5.63

#26754 [REF] Use writeRecord in the revert function of MessageTemplate to en…
  CRM/Core/BAO/MessageTemplate.php
Labels: master, merge on pass

#26753 5.63 late / after release changes
  CRM/Extension/Manager.php
  ext/civi_campaign/info.xml
  ext/civi_case/info.xml
  ext/civi_contribute/info.xml
  ext/civi_event/info.xml
  ext/civi_mail/info.xml
  ext/civi_member/info.xml
  ext/civi_pledge/info.xml
  ext/civi_report/info.xml
  extern/url.php
Labels: master

#26756 (dev/core#4413) Don't remove core component permissions when disabled
  CRM/Core/Config.php
Labels: merge on pass, 5.63

#26749 crmCaseType: fix New Case Type link visiblity in obscure circumstances
  ang/crmCaseType/list.html
Labels: master, merge ready

#26757 dev/core#4419 - Crash on membership tab of contribution page config (should go into 5.64)
  templates/CRM/Member/Form/MembershipBlock.tpl
Labels: master, merge on pass

#26755 dev/core#4418 Fix Payment Processor accepted_credit_cards regression
  CRM/Admin/Form/PaymentProcessor.php
Labels: master

#26759 backport of 26757
  templates/CRM/Member/Form/MembershipBlock.tpl
Labels: 5.63

#26762 dev/core#4418 Fix Payment Processor accepted_credit_cards regression (backport to 5.63)
  CRM/Admin/Form/PaymentProcessor.php
Labels: 5.63

#26758 [REF] dev/core#4418 Add in Unit test of submitting the form to ensure…
  CRM/Financial/BAO/PaymentProcessor.php
  tests/phpunit/CRM/Admin/Form/PaymentProcessorTest.php
Labels: master

#26760 dev/core#4418 Add in Upgrade script to fix double json encoding
  CRM/Upgrade/Incremental/php/FiveSixtyFour.php
  tests/phpunit/CRM/Upgrade/Incremental/php/FiveSixtyFourTest.php
Labels: master, merge on pass

#26232 dev/core#4409 Use translation for default language, if exists
  CRM/Core/BAO/Translation.php
  tests/phpunit/CRM/Core/BAO/MessageTemplateTest.php
Labels: master

#26594 [REF] CiviGrant - Switch to writeRecord/deleteRecord + BAO hooks
  ext/civigrant/CRM/Grant/BAO/Grant.php
  ext/civigrant/CRM/Grant/Form/Grant.php
  ext/civigrant/CRM/Grant/Form/Task/Update.php
Labels: master

#26748 add `contactId` to params array in EmailTrait
  CRM/Contact/Form/Task/EmailTrait.php
Labels: master

#26765 5.64
  templates/CRM/Contact/Form/Task/Batch.tpl
  templates/CRM/Custom/Form/Preview.tpl
  templates/CRM/Event/Form/Task/Batch.tpl
  templates/CRM/Profile/Form/Dynamic.tpl
  templates/CRM/UF/Form/Fields.tpl
Labels: master

#26766 Remove meaningless header in batch update participants
  CRM/Event/Form/Task/Batch.php
  templates/CRM/Event/Form/Task/Batch.tpl
Labels: master, merge on pass

#26764 backport 26763
  templates/CRM/Contact/Form/Task/Batch.tpl
  templates/CRM/Custom/Form/Preview.tpl
  templates/CRM/Event/Form/Task/Batch.tpl
  templates/CRM/Profile/Form/Dynamic.tpl
  templates/CRM/UF/Form/Fields.tpl
Labels: 5.63

#26761 dev/core#4418 Add in Upgrade Script for point release to fix bad data…
  CRM/Upgrade/Incremental/php/FiveSixtyThree.php
  ext/afform/admin/info.xml
  ext/afform/core/info.xml
  ext/afform/html/info.xml
  ext/afform/mock/info.xml
  ext/authx/info.xml
  ext/civi_campaign/info.xml
  ext/civi_case/info.xml
  ext/civi_contribute/info.xml
  ext/civi_event/info.xml
  ext/civi_mail/info.xml
  ext/civi_member/info.xml
  ext/civi_pledge/info.xml
  ext/civi_report/info.xml
  ext/civicrm_admin_ui/info.xml
  ext/civigrant/info.xml
  ext/civiimport/info.xml
  ext/ckeditor4/info.xml
  ext/contributioncancelactions/info.xml
  ext/elavon/info.xml
  ext/eventcart/info.xml
  ext/ewaysingle/info.xml
  ext/financialacls/info.xml
  ext/flexmailer/info.xml
  ext/greenwich/info.xml
  ext/legacycustomsearches/info.xml
  ext/message_admin/info.xml
  ext/oauth-client/info.xml
  ext/payflowpro/info.xml
  ext/recaptcha/info.xml
  ext/search_kit/info.xml
  ext/sequentialcreditnotes/info.xml
  sql/civicrm_generated.mysql
  sql/test_data_second_domain.mysql
  xml/version.xml
Labels: 5.63

#26769 5.63.1 - Add release-notes
  release-notes.md
  release-notes/5.63.1.md
Labels: 5.63

#26767 Edit Manage Job: remove double-title, top buttons, help only on the main job page
  CRM/Admin/Form/Job.php
  CRM/Admin/Page/Job.php
  templates/CRM/Admin/Form/Job.tpl
  templates/CRM/Admin/Page/Job.tpl
Labels: master

#26770 Debounce SK title
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdmin.component.js
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdmin.html
Labels: master

#26768 Change default input format for credit card expiration month to NN
  sql/civicrm_data/civicrm_preferences_date.sqldata.php
  sql/civicrm_generated.mysql
Labels: master

#26774 Remove unvariable variables from previously shared function
  CRM/Contribute/Form/Contribution.php
Labels: master, merge on pass

#26777 Fix recent breakage on membershipBlock.tpl
  templates/CRM/Contribute/Form/Contribution/MainMembershipBlock.tpl
Labels: 5.64

#26779 5.64
  templates/CRM/Contribute/Form/Contribution/MainMembershipBlock.tpl
Labels: master

#26781 [NFC] setup/plugins/init/StandaloneUsers: fix missing closing quote in log message
  setup/plugins/init/StandaloneUsers.civi-setup.php
Labels: master, merge on pass

#26784 Re-remove TRUE and true IF
  templates/CRM/Contribute/Form/Contribution/MainMembershipBlock.tpl
Labels: master

#26786 admin_ui: Sched Jobs language tweaks and add button
  ext/civicrm_admin_ui/ang/afsearchManageScheduledJobs.aff.html
Labels: master

#26783 Scheduled Job Admin: fix breadcrumb
  CRM/Admin/Form/Job.php
Labels: master

#26782 Standalone: implement basic breadcrumb
  CRM/Utils/System/Standalone.php
  css/menubar-standalone.css
Labels: sig:standalone

#26787 Extension Browser: there are no standalone-specific modules
  templates/CRM/Admin/Page/Extensions/About.tpl
Labels: master, sig:standalone

#26789 Standalone: do not show the Hide Menu option
  CRM/Core/BAO/Navigation.php
Labels: sig:standalone

#26785 (dev/core#4409) Fix failure to fall back to site default language, if configured
  CRM/Core/BAO/Translation.php
  Civi/WorkflowMessage/Traits/LocalizationTrait.php
  ext/message_admin/ang/crmMsgadm/ListCtrl.js
  ext/message_admin/ang/crmMsgadm/Workflow.js
  ext/message_admin/ang/crmMsgadm/WorkflowTranslated.html
  tests/phpunit/CRM/Core/BAO/MessageTemplateTest.php
Labels: 5.64

#26793 menubar: hide toggleButton when using Standalone
  js/crm.menubar.js
Labels: master, merge on pass

#26788 5.64.0 release notes initial run
  release-notes.md
  release-notes/5.64.0.md
Labels: 5.64

#26790 dev/core#4427 - Fix broken deleted filter checkbox on Manage Case
  CRM/Case/Form/CaseView.php
Labels: 5.64

#26795 5.64 to master
  CRM/Case/Form/CaseView.php
  CRM/Core/BAO/Translation.php
  Civi/WorkflowMessage/Traits/LocalizationTrait.php
  ext/message_admin/ang/crmMsgadm/ListCtrl.js
  ext/message_admin/ang/crmMsgadm/Workflow.js
  ext/message_admin/ang/crmMsgadm/WorkflowTranslated.html
  release-notes.md
  release-notes/5.64.0.md
  tests/phpunit/CRM/Core/BAO/MessageTemplateTest.php
Labels: master

#26796 Fix two more broken checkboxes - PCP pages
  CRM/Contribute/Form/Contribution/Main.php
  CRM/PCP/BAO/PCP.php
Labels: 5.64

#26797 5.64 to master
  CRM/Contribute/Form/Contribution/Main.php
  CRM/PCP/BAO/PCP.php
Labels: master

#26792 Add escape=htmlattribute option to the ts function
  CRM/Activity/Page/AJAX.php
  CRM/Campaign/Page/DashBoard.php
  CRM/Core/BAO/CustomGroup.php
  CRM/Core/Form/Renderer.php
  CRM/Core/I18n.php
  CRM/Report/Form/Contribute/HouseholdSummary.php
  CRM/Utils/Check/Component/Schema.php
Labels: master, merge ready

#26799 System Requirements - Raise minimum recommended PHP to 7.4
  CRM/Upgrade/Incremental/General.php
Labels: merge on pass, 5.64

#26800 System Requirements - Raise minimum recommended PHP to 7.4
  CRM/Upgrade/Incremental/General.php
Labels: 5.63

#26803 [REF] Add a note in documentation of CRM_Utils_Mail::send to clarify …
  CRM/Utils/Mail.php
Labels: master, merge on pass

#26802 dev/core#4430 Fix regression on searching for emails
  CRM/Core/Form.php
Labels: merge ready, 5.64

#26807 Undefined property fix
  CRM/Member/Form.php
Labels: master, merge on pass

#26805 5.64
  CRM/Core/Form.php
  CRM/Upgrade/Incremental/General.php
Labels: master

#26798 SearchKit - Remove irrelevant link from default display
  ext/search_kit/Civi/Search/Display.php
Labels: master

#26809 Move turning logging off to the tearDown
  tests/phpunit/api/v3/ReportTemplateTest.php
Labels: master, merge on pass

#26811 Add start date back to recurring contributions display on contact - RC
  templates/CRM/Contribute/Page/ContributionRecurSelector.tpl
  templates/CRM/Member/Page/RecurringContributions.tpl
Labels: merge on pass, 5.64

#26812 5.64 to master
  templates/CRM/Contribute/Page/ContributionRecurSelector.tpl
  templates/CRM/Member/Page/RecurringContributions.tpl
Labels: master

#26546 dev/core#4213 Make frontend_title, name required for Group entity
  CRM/Campaign/BAO/Petition.php
  CRM/Contact/BAO/Group.php
  CRM/Contact/DAO/Group.php
  CRM/Core/I18n/SchemaStructure.php
  CRM/Group/Form/Edit.php
  CRM/Mailing/Event/BAO/MailingEventConfirm.php
  CRM/Mailing/Event/BAO/MailingEventUnsubscribe.php
  CRM/Mailing/Form/Subscribe.php
  CRM/Upgrade/Incremental/MessageTemplates.php
  CRM/Upgrade/Incremental/php/FiveSixtyFive.php
  CRM/Upgrade/Incremental/sql/5.65.alpha1.mysql.tpl
  CRM/Utils/Token.php
  Civi/Api4/Service/Spec/Provider/TitleFieldSpecProvider.php
  sql/civicrm_data/civicrm_mailing_component.sqldata.php
  templates/CRM/Group/Form/Edit.tpl
  tests/phpunit/CRM/Campaign/BAO/PetitionTest.php
  xml/schema/Contact/Group.xml
  xml/templates/message_templates/petition_sign_html.tpl
  xml/templates/message_templates/petition_sign_subject.tpl
  xml/templates/message_templates/petition_sign_text.tpl
Labels: master

#26778 [REF] Clarify loading of PriceSetID
  CRM/Contribute/Form/Contribution/Main.php
  CRM/Contribute/Form/ContributionBase.php
Labels: master

#26806 Standardize title as Administer in breadcrumbs and on main Administer page
  CRM/Admin/Page/Job.php
  CRM/Admin/Page/JobLog.php
  CRM/Admin/Page/PaymentProcessor.php
  CRM/Contact/Form/Domain.php
  CRM/Core/xml/Menu/Admin.xml
  ext/afform/core/CRM/Afform/Page/AfformBase.php
Labels: master

#26813 (NFC) Civi\ESM - Doc cleanups
  Civi/Esm/BasicLoaderTrait.php
  Civi/Esm/README.md
  Civi/Esm/ShimLoader.php
Labels: master

#26814 [Ref] Use `isQuickConfig` function, rather than repetitively looking it up
  CRM/Contribute/Form/Contribution/Main.php
Labels: master, merge on pass

#26808 ReportTemplate data provider - skip rather than mark incomplete event/income
  tests/phpunit/api/v3/ReportTemplateTest.php
Labels: master

#26815 [REF][PHP8.2] Move declaration of _actionButtonName from CRM_Core_Form_Search…
  CRM/Core/Form.php
  CRM/Core/Form/Search.php
Labels: master, merge on pass

#26816 Run regen, with data fix to allow it to run
  sql/civicrm_data/civicrm_uf_group.sqldata.php
  sql/civicrm_generated.mysql
  xml/templates/civicrm_acl.tpl
Labels: master

#26818 Reduce test fails on edge for Contact_Detail report
  CRM/Report/Form/Contact/Detail.php
Labels: master, merge on pass

#26819 [PHP8.x] Stop setting undeclared, unused property in test
  tests/phpunit/CRM/Member/Form/Task/LabelTest.php
Labels: master, merge on pass

#26821 [REF][PHP8.2] Apply PR patch to mimetyper to fix deprecated dynamic p…
  composer.json
  composer.lock
Labels: master

#26822 [NFC] Replace nonstandard copyright headers with the standard one
  CRM/Admin/Form/LabelFormats.php
  CRM/Admin/Form/PdfFormats.php
  CRM/Admin/Page/LabelFormats.php
  CRM/Admin/Page/PdfFormats.php
  CRM/Contact/BAO/GroupNesting.php
  CRM/Core/BAO/LabelFormat.php
  CRM/Core/BAO/PaperSize.php
  CRM/Core/BAO/PdfFormat.php
  CRM/Core/QuickForm/GroupMultiSelect.php
  CRM/Core/QuickForm/NestedAdvMultiSelect.php
  api/v3/SavedSearch.php
  api/v3/SurveyRespondant.php
  bin/cli.class.php
  bin/cli.php
  bin/csv/delete.php
  bin/csv/export.php
  bin/csv/import.php
  ext/ewaysingle/lib/eWAY/eWAY_GatewayRequest.php
  ext/ewaysingle/lib/eWAY/eWAY_GatewayResponse.php
  tests/phpunit/api/v3/SavedSearchTest.php
Labels: master

#26817 Fix undeclared property in SyntaxConformanceTests
  tests/phpunit/api/v3/SyntaxConformanceTest.php
Labels: master, merge on pass

#26820 Fix mis-cased apiVersion causing php8.x fails in SavedSearchTest
  tests/phpunit/api/v3/SavedSearchTest.php
Labels: master, merge on pass

#26823 [REF] Ensure that getActions respects any modifications by event list…
  Civi/Api4/Action/GetActions.php
  tests/phpunit/api/v4/Action/GetActionsTest.php
Labels: master

#26824 backport 26517 - fix crash for radio custom fields
  templates/CRM/Custom/Form/Edit/CustomField.tpl
Labels: 5.63

#26826 Clean up CaseSummary Report removing undeclared properties and minor fixes
  CRM/Report/Form/Case/Summary.php
Labels: master

#26827 [REF][PHP8.2] Fix Dynamic Property Deprecation notice in MultiRecordListing
  CRM/Profile/Page/MultipleRecordFieldsListing.php
Labels: master, merge on pass

#26775 [Ref] Minor cleanup on handling of financial type
  CRM/Contribute/Form/Contribution.php
  CRM/Contribute/Form/Contribution/Confirm.php
Labels: master

#26776 [REF] Stop passing `result` into `getContributionParams` to get one value from it, in one code path
  CRM/Contribute/Form/Contribution/Confirm.php
Labels: master

#26829 [Ref] [php8] Unshare shared function `CRM_Custom_Form_CustomData::setGroupTree` in order to clean-up
  CRM/Contact/Form/Task/AddToGroup.php
  CRM/Custom/Form/CustomData.php
  CRM/Custom/Form/CustomDataByType.php
  tests/phpunit/CRM/Contact/Form/Task/AddToGroupTest.php
Labels: master

#26828 [REF][PHP8.2] Fix deprecated dynamic properties in Logging Report Detail
  CRM/Logging/ReportDetail.php
Labels: master, merge on pass

#26830 [REF][PHP8.2] Fix Deprectation notice due to dynamic properties on th…
  CRM/Report/Form/Contribute/History.php
Labels: master, merge on pass

#26833 [REF] [PHP8.2]Treat subType as a internal varible, not a form property
  CRM/Contact/Form/Edit/CustomData.php
  CRM/Custom/Form/CustomData.php
Labels: master

#26832 [REF] [PHP8.2] Post unshare cleanup
  CRM/Custom/Form/CustomDataByType.php
Labels: master

#26834 [REF] Use internal variable rather than property to pass variable
  CRM/Contact/Form/Edit/CustomData.php
Labels: master, merge on pass

#26835 Ensure that we only check permissions if we want to in getActions fol…
  Civi/Api4/Action/GetActions.php
  tests/phpunit/api/v4/Action/GetActionsTest.php
Labels: master

#26838 [REF][PHP8.2] Ref fix deprecation in PHP8.2 about dynamic property _ssID
  CRM/Activity/Form/Search.php
  CRM/Core/Form/Search.php
  CRM/Event/Form/Search.php
Labels: master

#26836 Remove last reference to undefined property `_subType`
  CRM/Custom/Form/CustomDataByType.php
Labels: master

#26837 Fold `preProcess` into `run`
  CRM/Contact/Page/View/CustomData.php
Labels: master

#26791 hide view only custom fields on merge screen
  CRM/Dedupe/Merger.php
  tests/phpunit/CRM/Dedupe/MergerTest.php
  tests/phpunit/api/v3/JobTest.php
Labels: master

#26844 Fold private `setGroupTree` function back into caller
  CRM/Custom/Form/CustomDataByType.php
Labels: master

#26846 Notice fix - ensure extends_entity_column_value isset
  CRM/Custom/Page/Group.php
Labels: master

#26848 [NFC] New Event: remove empty table row
  templates/CRM/Event/Form/ManageEvent/EventInfo.tpl
Labels: master, merge on pass

#26839 Search kit action links cleanup
  ext/search_kit/Civi/Api4/Action/SearchDisplay/AbstractRunAction.php
  ext/search_kit/Civi/Api4/Action/SearchDisplay/GetSearchTasks.php
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdminDisplay.component.js
  ext/search_kit/ang/crmSearchTasks/traits/searchDisplayTasksTrait.service.js
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/SearchRunTest.php
Labels: master, has-test

#26771 Standalone - Add support for development-friendly file-layouts
  .gitignore
  CRM/Utils/Check/Component/Security.php
  setup/plugins/init/Standalone.civi-setup.php
  setup/res/civicrm.config.php.standalone.txt
  setup/res/htaccess.txt
  setup/res/index.php.txt
  setup/src/Setup/StandaloneScaffold.php
  tools/standalone/bin/scaffold
  tools/standalone/bin/serve
  tools/standalone/router.php
Labels: master, merge ready

#26851 Follow up fix (master only regression)
  CRM/Custom/Form/CustomDataByType.php
Labels: master

#26850 (REF) CMSUser::create - Rename misleading parameter
  CRM/Core/BAO/CMSUser.php
  CRM/Utils/System/Backdrop.php
  CRM/Utils/System/Base.php
  CRM/Utils/System/Drupal.php
  CRM/Utils/System/Drupal8.php
  CRM/Utils/System/Joomla.php
  CRM/Utils/System/Standalone.php
  CRM/Utils/System/WordPress.php
Labels: master

#26843 SearchKit - fix min-width of buttons
  ext/search_kit/css/crmSearchAdmin.css
Labels: master

#26856 [NFC][PHP8.2] Fix dynamic property _loggedInUser
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: master

#26845 Remove `_subName` property
  CRM/Custom/Form/CustomData.php
Labels: master

#26858 Remove never-true-if
  CRM/Custom/Form/CustomDataByType.php
Labels: master

#26859 [php8.2] Fix undeclared properties on case custom data form
  CRM/Case/Form/CustomData.php
  tests/phpunit/CRM/Case/Form/CustomDataTest.php
Labels: master
