Repository civicrm/civicrm-core, pull requests merged in 2023-12, with the labels that each got.

#28384 Remove some calls to deprecated function
  ext/legacycustomsearches/CRM/Contact/Form/Search/Custom/ActivitySearch.php
  ext/legacycustomsearches/CRM/Contact/Form/Search/Custom/FullText.php
Labels: master, merge on pass

#27934 set extension browser timeout to minimum of 10 seconds.
  CRM/Extension/Browser.php
Labels: master, merge ready

#28391 [REF] Use Token Processor to generate sort name and display name for individuals
  CRM/Contact/BAO/Individual.php
  Civi/Token/TokenCompatSubscriber.php
  tests/phpunit/CRM/Contact/BAO/IndividualTest.php
  tests/phpunit/CRM/Utils/TokenConsistencyTest.php
Labels: master, merge on pass

#28389 Use getSubmittedValues() rather than ad-hoc money 'cleaning' on membershipType form
  CRM/Member/Form/MembershipType.php
Labels: master

#24699 Afform: Support conditional logic
  ext/afform/admin/ang/afGuiEditor.ang.php
  ext/afform/admin/ang/afGuiEditor.css
  ext/afform/admin/ang/afGuiEditor.js
  ext/afform/admin/ang/afGuiEditor/afGuiClause.component.js
  ext/afform/admin/ang/afGuiEditor/afGuiClause.html
  ext/afform/admin/ang/afGuiEditor/afGuiCondition.component.js
  ext/afform/admin/ang/afGuiEditor/afGuiCondition.html
  ext/afform/admin/ang/afGuiEditor/afGuiConditionalDialog.ctrl.js
  ext/afform/admin/ang/afGuiEditor/afGuiConditionalDialog.html
  ext/afform/admin/ang/afGuiEditor/afGuiEditor.component.js
  ext/afform/admin/ang/afGuiEditor/afGuiFieldValue.directive.js
  ext/afform/admin/ang/afGuiEditor/elements/afGuiButton-menu.html
  ext/afform/admin/ang/afGuiEditor/elements/afGuiButton.component.js
  ext/afform/admin/ang/afGuiEditor/elements/afGuiConditionalMenu.directive.js
  ext/afform/admin/ang/afGuiEditor/elements/afGuiConditionalMenu.html
  ext/afform/admin/ang/afGuiEditor/elements/afGuiContainer-menu.html
  ext/afform/admin/ang/afGuiEditor/elements/afGuiField-menu.html
  ext/afform/admin/ang/afGuiEditor/elements/afGuiMarkup-menu.html
  ext/afform/admin/ang/afGuiEditor/elements/afGuiMarkup.component.js
  ext/afform/admin/ang/afGuiEditor/elements/afGuiText-menu.html
  ext/afform/admin/ang/afGuiEditor/elements/afGuiText.component.js
  ext/afform/core/ang/af/afForm.component.js
  ext/afform/core/ang/af/afIf.directive.js
Labels: master, merge ready

#28392 Fix for intermittent test fail on checksum time
  tests/phpunit/CRM/Core/BAO/CustomFieldTest.php
  tests/phpunit/CRM/Core/BAO/MessageTemplateTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: master

#28394 Fix online membership receipt to be form-independent
  CRM/Financial/BAO/Order.php
  CRM/Member/WorkflowMessage/Membership/Membership.php
  xml/templates/message_templates/membership_online_receipt_html.tpl
Labels: master

#28402 Add getParticipantID() to register
  CRM/Event/Form/Registration.php
Labels: master

#28412 Standalone - Add button to add user role
  ext/standaloneusers/CRM/Standaloneusers/DAO/Role.php
  ext/standaloneusers/managed/SavedSearch_Administer_Roles.mgd.php
  ext/standaloneusers/sql/auto_uninstall.sql
  ext/standaloneusers/xml/schema/CRM/Standaloneusers/Role.xml
Labels: master

#28407 dev/core#2998 - Fix JWT cookie test in standalone
  ext/authx/tests/phpunit/Civi/Authx/AbstractFlowsTest.php
Labels: master, comp:standalone

#28415 Adds an accessible accordion, applies to news-feed dashlet
  css/civicrm.css
  js/Common.js
  templates/CRM/Dashlet/Page/Blog.tpl
Labels: master, sig:user interfacing improvement, sig:accessibility

#28417 [REF][PHP8.2] Remove unused dynamic property
  CRM/Admin/Page/Job.php
Labels: master

#28416 [REF][PHP8.2] Declare properties in CRM_Activity_Page_Tab
  CRM/Activity/Page/Tab.php
Labels: master

#28408 LocalizedDataTest - Fix for standalone
  tests/phpunit/E2E/Core/LocalizedDataTest.php
Labels: master, comp:standalone

#28410 LegacyRestTest - No need to test `extern/rest.php` on `Standalone`
  tests/phpunit/E2E/Extern/LegacyRestTest.php
Labels: comp:standalone

#28432 [REF][PHP8.2] Declare properties in HouseholdSummary report
  CRM/Report/Form/Contribute/HouseholdSummary.php
Labels: master

#28404 Stop forcing apiVersion to 3 in setUp
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/api/v3/ActivityContactTest.php
Labels: master

#28422 Standalone - Flush cache when saving user role
  ext/standaloneusers/CRM/Standaloneusers/BAO/Role.php
Labels: master

#28439 dev/core#2998 - Fix standalone throwing exception when fetching unkno…
  ext/standaloneusers/Civi/Standalone/Security.php
  ext/standaloneusers/tests/phpunit/Civi/Standalone/SecurityTest.php
Labels: master, merge on pass, comp:standalone

#28431 Remove text version of payment_or_refund notification
  tests/phpunit/CRM/Contribute/Form/AdditionalPaymentTest.php
  tests/phpunit/api/v3/PaymentTest.php
  xml/templates/message_templates/payment_or_refund_notification_text.tpl
Labels: master

#28447 Standalone - give admin role super permission
  setup/plugins/init/StandaloneUsers.civi-setup.php
Labels: master

#28427 Standalone - bootstrap script fixes
  CRM/Utils/System/Standalone.php
Labels: master

#28443 Asset builder test
  CRM/Core/Resources.php
  CRM/Core/Resources/Common.php
  tests/phpunit/E2E/Core/PathUrlTest.php
Labels: master, merge on pass

#28418 Applies accessible accordion to Advanced Search
  templates/CRM/Contact/Form/Search/Advanced.tpl
  templates/CRM/Contact/Form/Search/AdvancedCriteria.tpl
Labels: master

#28435 Fix notices on view membership
  CRM/Contact/Form/Inline.php
  CRM/Member/Page/Tab.php
  templates/CRM/Member/Page/Tab.tpl
  templates/CRM/common/formButtons.tpl
Labels: master

#28450 regen
  sql/civicrm_generated.mysql
Labels: master

#28451 Standalone - Protect admin and everyone roles
  ext/standaloneusers/CRM/Standaloneusers/BAO/Role.php
Labels: master, merge on pass

#28453 dev/core#4411 fix issue with user language
  ext/standaloneusers/CRM/Standaloneusers/BAO/User.php
  ext/standaloneusers/CRM/Standaloneusers/DAO/User.php
  ext/standaloneusers/Civi/Standalone/Security.php
  ext/standaloneusers/ang/afformEditUserAccount.aff.html
  ext/standaloneusers/standaloneusers.php
  ext/standaloneusers/xml/schema/CRM/Standaloneusers/User.xml
Labels: master

#28457 [REF][PHP8.2] Declare property in CRM_Admin_Form_ParticipantStatusType
  CRM/Admin/Form/ParticipantStatusType.php
Labels: master, merge on pass

#28458 Merge 5.68 to master
  ext/civigrant/CRM/Grant/DAO/Grant.php
  ext/civigrant/CRM/Grant/Form/GrantView.php
  ext/civigrant/CRM/Grant/Selector/Search.php
  ext/civigrant/templates/CRM/Grant/Form/Grant.tpl
  ext/civigrant/xml/Menu/Grant.xml
  ext/civigrant/xml/schema/CRM/Grant/Grant.xml
  ext/search_kit/Civi/Api4/Action/SearchDisplay/Run.php
Labels: master

#28460 SearchKit - Ensure result autocompleted by id is excluded from subsequent pages
  Civi/Api4/Generic/AutocompleteAction.php
  tests/phpunit/api/v4/Action/AutocompleteTest.php
Labels: master, merge on pass

#28321 dev/core#4811 AngularJs - Load on every page
  CRM/Core/Form.php
  CRM/Core/Resources.php
Labels: master

#27496 Fix activity view bug where an activity type id in the url overrides …
  CRM/Activity/Form/Activity.php
  CRM/Activity/Form/ActivityFormTrait.php
  Civi/Test/FormWrapper.php
  templates/CRM/Activity/Form/Activity.tpl
  templates/CRM/Activity/Form/ActivityView.tpl
  templates/CRM/Case/Form/Activity.tpl
  templates/CRM/Case/Form/Case.tpl
  tests/phpunit/CRM/Activity/Form/ActivityTest.php
  tests/phpunit/CRM/Case/BAO/CaseTest.php
Labels: master

#28463 Add warnings to processAmount
  CRM/Price/BAO/PriceSet.php
Labels: master

#28449 Applies accessible accordion to FormBuilder's 'collapsible' output
  ext/afform/admin/ang/afGuiEditor/afGuiMenuItemCollapsible.component.js
  ext/afform/admin/ang/afGuiEditor/afGuiMenuItemCollapsible.html
  ext/afform/admin/ang/afGuiEditor/elements/afGuiContainer-menu.html
  ext/afform/admin/ang/afGuiEditor/elements/afGuiContainer.component.js
  ext/afform/admin/ang/afGuiEditor/elements/afGuiSearchContainer-menu.html
  ext/afform/core/ang/af/afTitle.directive.js
  ext/civicrm_search_ui/ang/afsearchFindContributions.aff.html
Labels: master

#28470 Use buttons instead of buttons, but only when not 4, but also if it's 4
  templates/CRM/Custom/Form/Field.tpl
Labels: master

#28419 Standalone PathUrlTest
  tests/phpunit/E2E/Core/PathUrlTest.php
Labels: master

#26227 Use payment create rather than transitionComponents
  CRM/Contribute/BAO/Contribution.php
  CRM/Contribute/Form/Contribution.php
  tests/phpunit/CRM/Member/Form/MembershipTest.php
  tests/phpunit/api/v3/ContributionTest.php
Labels: master

#28425 Update language download during install to use existing folder if present
  setup/plugins/installFiles/l10nDownload.civi-setup.php
Labels: master

#28398 ensure exception class supports getErrorData
  CRM/Api4/Page/AJAX.php
Labels: master, merge on pass

#28486 Update contributor-key.yml
  contributor-key.yml
Labels: master

#28478 Standalone - Make active field required and labelled enabled
  ext/standaloneusers/CRM/Standaloneusers/DAO/Role.php
  ext/standaloneusers/CRM/Standaloneusers/DAO/User.php
  ext/standaloneusers/managed/SavedSearch_Administer_Roles.mgd.php
  ext/standaloneusers/managed/SavedSearch_Administer_Users.mgd.php
  ext/standaloneusers/sql/auto_install.sql
  ext/standaloneusers/xml/schema/CRM/Standaloneusers/Role.xml
  ext/standaloneusers/xml/schema/CRM/Standaloneusers/User.xml
Labels: master

#28499 convert .aff.json to .aff.php and add ts()
  ext/afform/core/ang/afblockContactAddress.aff.json
  ext/afform/core/ang/afblockContactAddress.aff.php
  ext/afform/core/ang/afblockContactEmail.aff.json
  ext/afform/core/ang/afblockContactEmail.aff.php
  ext/afform/core/ang/afblockContactIM.aff.json
  ext/afform/core/ang/afblockContactIM.aff.php
  ext/afform/core/ang/afblockContactNote.aff.json
  ext/afform/core/ang/afblockContactNote.aff.php
  ext/afform/core/ang/afblockContactPhone.aff.json
  ext/afform/core/ang/afblockContactPhone.aff.php
  ext/afform/core/ang/afblockContactWebsite.aff.json
  ext/afform/core/ang/afblockContactWebsite.aff.php
  ext/afform/core/ang/afblockNameHousehold.aff.json
  ext/afform/core/ang/afblockNameHousehold.aff.php
  ext/afform/core/ang/afblockNameIndividual.aff.json
  ext/afform/core/ang/afblockNameIndividual.aff.php
  ext/afform/core/ang/afblockNameOrganization.aff.json
  ext/afform/core/ang/afblockNameOrganization.aff.php
  ext/afform/html/ang/afHtmlAdmin.aff.json
  ext/afform/html/ang/afHtmlAdmin.aff.php
  ext/afform/mock/ang/afex.aff.json
  ext/afform/mock/ang/afex.aff.php
  ext/afform/mock/ang/mock-weird-name.aff.json
  ext/afform/mock/ang/mock-weird-name.aff.php
  ext/afform/mock/ang/mockFoo.aff.json
  ext/afform/mock/ang/mockFoo.aff.php
  ext/afform/mock/ang/mockPage.aff.json
  ext/afform/mock/ang/mockPage.aff.php
  ext/afform/mock/ang/mockPublicForm.aff.json
  ext/afform/mock/ang/mockPublicForm.aff.php
  ext/afform/mock/ang/testAfform.aff.json
  ext/afform/mock/ang/testAfform.aff.php
  ext/afform/mock/ang/testContactEmailSearchForm.aff.json
  ext/afform/mock/ang/testContactEmailSearchForm.aff.php
  ext/afform/mock/ang/testMultipleSearchForm.aff.json
  ext/afform/mock/ang/testMultipleSearchForm.aff.php
  ext/civi_mail/ang/afsearchEmailBounceHistory.aff.json
  ext/civi_mail/ang/afsearchEmailBounceHistory.aff.php
Labels: master

#27162 Add userEnteredText as generic workflow template smarty variable
  CRM/Contribute/Form/Task/Invoice.php
  CRM/Core/BAO/MessageTemplate.php
  CRM/Event/Form/Participant.php
  CRM/Member/Form/Membership.php
  CRM/Member/Form/MembershipRenewal.php
  CRM/Member/WorkflowMessage/MembershipOfflineReceipt.php
  Civi/WorkflowMessage/GenericWorkflowMessage.php
  api/v3/Contribution.php
  api/v3/MessageTemplate.php
  tests/phpunit/CRM/Event/Form/ParticipantTest.php
  tests/phpunit/CRM/Member/Form/MembershipRenewalTest.php
  xml/templates/message_templates/contribution_invoice_receipt_html.tpl
  xml/templates/message_templates/event_offline_receipt_html.tpl
  xml/templates/message_templates/membership_offline_receipt_html.tpl
  xml/templates/message_templates/membership_offline_receipt_text.tpl
  xml/templates/message_templates/membership_online_receipt_html.tpl
Labels: master

#28510 Add SMS provider API 4 Support
  Civi/Api4/Provider.php
Labels: master, merge on pass

#28452 APIv4 - Pass form values to autocomplete field
  Civi/Api4/Generic/AutocompleteAction.php
  ext/afform/core/ang/af/fields/EntityRef.html
Labels: master

#28516 Regen
  sql/civicrm_generated.mysql
Labels: master

#28490 Clarify doRefund() signature
  CRM/Core/Payment.php
Labels: master, merge on pass

#28441 Applies accessible accordion to SearchKit, adds fallbacks
  css/civicrm.css
  ext/search_kit/ang/crmSearchAdmin/compose.html
  ext/search_kit/ang/crmSearchAdmin/resultsTable/debug.html
Labels: master, merge on pass

#28500 Changed the URL path for DatePreference screen
  CRM/Admin/Form/PreferencesDate.php
  CRM/Core/DAO/PreferencesDate.php
  CRM/Core/xml/Menu/Admin.xml
  xml/schema/Core/PreferencesDate.xml
Labels: master

#28472 Add MailingComponent.php
  CRM/Mailing/BAO/MailingComponent.php
  ext/civi_mail/Civi/Api4/MailingComponent.php
Labels: master, merge on pass

#28526 Fix ID retrieval for MailingComponent edit page
  CRM/Mailing/DAO/MailingComponent.php
  CRM/Mailing/Form/Component.php
  CRM/Mailing/xml/Menu/Mailing.xml
  xml/schema/Mailing/MailingComponent.xml
Labels: master

#28522 (dev/core#4839) WorkflowMessage - Send email. Don't overwrite $to.
  Civi/WorkflowMessage/Traits/AddressingTrait.php
  tests/phpunit/CRM/Core/BAO/MessageTemplateTest.php
Labels: merge on pass, has-test, sig:regression, 5.68

#28524 TemplateTrait - Fix references to CRM_Core_Exception
  Civi/WorkflowMessage/Traits/TemplateTrait.php
Labels: master, merge on pass

#28515 SearchKit: Don't assume a comparison value when none exists
  ext/search_kit/Civi/Api4/Action/SearchDisplay/AbstractRunAction.php
Labels: master

#28396 SearchKit - Fix Search Segments for contact type entities
  ext/search_kit/Civi/Api4/Service/Spec/Provider/SearchSegmentExtraFieldProvider.php
  ext/search_kit/tests/phpunit/api/v4/SearchSegment/SearchSegmentTest.php
Labels: 5.68

#28508 make Mapping entity available on searchkit
  Civi/Api4/Mapping.php
Labels: master

#28509 Added Export Mapping search kit UI
  ext/civicrm_admin_ui/ang/afsearchImportExportMappings.aff.html
  ext/civicrm_admin_ui/ang/afsearchImportExportMappings.aff.php
  ext/civicrm_admin_ui/managed/SavedSearch_Import_Export_Mappings.mgd.php
Labels: master

#28498 Remove notice from main donate page
  templates/CRM/Contribute/Form/Contribution/Main.tpl
Labels: master

#28485 Add deprecation to transition components
  CRM/Contribute/BAO/Contribution.php
Labels: master

#28479 Clean up parameters in add payment form
  CRM/Contribute/Form/AdditionalPayment.php
Labels: master

#28482 Adding PreferencesDate API
  Civi/Api4/PreferencesDate.php
Labels: master

#28483 Added DatePreference admin UI
  ext/civicrm_admin_ui/ang/afsearchSettingsDatePreferences.aff.html
  ext/civicrm_admin_ui/ang/afsearchSettingsDatePreferences.aff.php
  ext/civicrm_admin_ui/managed/SavedSearch_Settings_Date_Preferences.mgd.php
Labels: master

#28491 Update CustomField default_value to NULL instead of '' for floats
  CRM/Upgrade/Incremental/sql/5.69.alpha1.mysql.tpl
Labels: master

#28493 Consolidate invoice determination
  CRM/Event/Form/Participant.php
Labels: master

#28487 dev/core#3083 Add a warning about price fields where non_deductible amount potentially misconfigured
  CRM/Utils/Check/Component/PriceFields.php
Labels: master

#28386 Use apv4 rather than V3 for cached membershipTypes retrieval
  CRM/Member/BAO/MembershipType.php
  tests/phpunit/CRM/Member/BAO/MembershipTest.php
Labels: master

#28388 Formbuilder: support rows and columns values for Note (textarea) custom field type
  Civi/Api4/Service/Spec/SpecFormatter.php
  ext/afform/core/ang/af/fields/TextArea.html
Labels: master

#28344 Move form specific code out of shared function
  CRM/Event/Form/Participant.php
  CRM/Event/Form/ParticipantFeeSelection.php
  CRM/Event/Form/Registration.php
Labels: master

#28531 5.68
  Civi/WorkflowMessage/Traits/AddressingTrait.php
  ext/search_kit/Civi/Api4/Service/Spec/Provider/SearchSegmentExtraFieldProvider.php
  ext/search_kit/tests/phpunit/api/v4/SearchSegment/SearchSegmentTest.php
  tests/phpunit/CRM/Core/BAO/MessageTemplateTest.php
Labels: master

#28528 Standalone - Improve administer user screen
  ext/standaloneusers/ang/afsearchAdministerUserAccounts.aff.html
  ext/standaloneusers/managed/SavedSearch_Administer_Users.mgd.php
Labels: master

#28525 standaloneusers - Fix tokens+docblocks for "Password reset" email
  ext/standaloneusers/CRM/Standaloneusers/WorkflowMessage/PasswordReset.php
  ext/standaloneusers/Civi/Api4/Action/User/SendPasswordReset.php
Labels: master

#28513 searchui : new screen label format
  ext/civicrm_search_ui/ang/afsearchLabelFormat.aff.html
  ext/civicrm_search_ui/ang/afsearchLabelFormat.aff.php
  ext/civicrm_search_ui/managed/SavedSearch_label_format.mgd.php
Labels: master

#28468 dev/core#4410: fixed timezone support for standalone
  CRM/Utils/System/Standalone.php
  ext/standaloneusers/CRM/Standaloneusers/BAO/User.php
  ext/standaloneusers/CRM/Standaloneusers/DAO/User.php
  ext/standaloneusers/ang/afformEditUserAccount.aff.html
  ext/standaloneusers/xml/schema/CRM/Standaloneusers/User.xml
Labels: master

#28547 [NFC] 5.68 release note late changes
  release-notes/5.68.0.md
Labels: 5.68

#28497 Sample data fixes for contribution pages
  xml/templates/civicrm_sample.tpl
Labels: master, merge on pass

#27107 dev/core#4232 Afform: Allow manual processing of submission
  CRM/Core/DAO/MessageTemplate.php
  ang/crmUi.js
  ext/afform/admin/Civi/AfformAdmin/AfformAdminMeta.php
  ext/afform/admin/ang/afGuiEditor/afGuiEditor.component.js
  ext/afform/admin/ang/afGuiEditor/config-form.html
  ext/afform/admin/managed/FormSubmissionSavedSearch.mgd.php
  ext/afform/core/CRM/Afform/DAO/AfformSubmission.php
  ext/afform/core/CRM/Afform/Page/Verify.php
  ext/afform/core/Civi/Afform/Event/AfformEventEntityTrait.php
  ext/afform/core/Civi/Afform/Event/AfformSubmitEvent.php
  ext/afform/core/Civi/Afform/Tokens.php
  ext/afform/core/Civi/Api4/Action/Afform/AbstractProcessor.php
  ext/afform/core/Civi/Api4/Action/Afform/Process.php
  ext/afform/core/Civi/Api4/Action/Afform/Submit.php
  ext/afform/core/Civi/Api4/Action/Afform/SubmitFile.php
  ext/afform/core/Civi/Api4/Afform.php
  ext/afform/core/afform.php
  ext/afform/core/ang/af/afForm.component.js
  ext/afform/core/ang/afSearchTasks.ang.php
  ext/afform/core/ang/afSearchTasks.module.js
  ext/afform/core/ang/afSearchTasks/afformSubmissionProcessTask.ctrl..js
  ext/afform/core/ang/afSearchTasks/afformSubmissionProcessTask.html
  ext/afform/core/info.xml
  ext/afform/core/templates/CRM/Afform/Page/Verify.tpl
  ext/afform/core/xml/Menu/afform.xml
  ext/afform/core/xml/schema/CRM/Afform/AfformSubmission.xml
  ext/afform/mock/tests/phpunit/api/v4/Afform/AfformContactUsageTest.php
  tests/phpunit/CRM/Core/BAO/MessageTemplateTest.php
  xml/schema/Core/MessageTemplate.xml
Labels: master

#28495 Add support for spreadsheet format in imports
  CRM/Contact/Import/Parser/Contact.php
  CRM/Import/DataSource.php
  CRM/Import/DataSource/CSV.php
  CRM/Import/DataSource/SQL.php
  CRM/Import/DataSource/Spreadsheet.php
  CRM/Import/Form/DataSourceConfig.php
  CRM/Import/Forms.php
  CRM/Utils/Number.php
  Civi/Import/DataSource/DataSourceInterface.php
  Civi/Import/DataSource/DataSourceTrait.php
  ext/civiimport/Civi/Import/DataSource/Spreadsheet.php
  ext/civiimport/templates/CRM/Import/DataSource/Spreadsheet.tpl
  templates/CRM/Contact/Import/Form/Spreadsheet.tpl
  tests/phpunit/CRM/Contact/Import/Parser/ContactTest.php
Labels: master

#28541 Accordions css – tidies up / bug fixes / simplifies theming / adds two utility classes
  css/civicrm.css
Labels: master

#28546 SearchUI - Updates to Label Format display
  ext/civicrm_search_ui/ang/afsearchLabelFormat.aff.html
  ext/civicrm_search_ui/ang/afsearchLabelFormat.aff.php
  ext/civicrm_search_ui/managed/SavedSearch_label_format.mgd.php
Labels: master

#28496 dev/core#4447 fix inability to import to master_id
  CRM/Core/BAO/Address.php
  tests/phpunit/CRM/Contact/Import/Parser/ContactTest.php
  tests/phpunit/CRM/Export/BAO/ExportTest.php
Labels: master

#28543 Fixes Advanced Search regression in #28418
  css/civicrm.css
  templates/CRM/Contact/Form/Search/Advanced.tpl
  templates/CRM/Contact/Form/Search/AdvancedCriteria.tpl
Labels: master, merge on pass

#28551 Regen
  CRM/Core/DAO/MessageTemplate.php
  CRM/Mailing/DAO/MailingComponent.php
  install/langs.php
  package-lock.json
  sql/civicrm_generated.mysql
Labels: master, merge on pass

#28532 Standalone - prevent users from deleting own user
  ext/standaloneusers/CRM/Standaloneusers/BAO/User.php
Labels: master

#28562 [NFC] Fix typo in `Localization.tpl` file.
  templates/CRM/Admin/Form/Setting/Localization.tpl
Labels: master, merge on pass

#28561 add Query to AssetBuilder test to fix WP E2E test failures
  tests/phpunit/E2E/Core/PathUrlTest.php
Labels: master

#28521 Add system check encouraging Smarty3
  CRM/Utils/Check/Component/Smarty.php
Labels: master, merge on pass

#28474 POC: toward dev/core#4833: this does fix the problem.
  CRM/Core/Payment/AuthorizeNetIPN.php
Labels: master

#28576 Do not suppress appropriate notices
  CRM/Core/Form.php
Labels: master

#28572 remove unused variable
  CRM/Contact/BAO/Contact/Utils.php
Labels: master

#28571 Remove unused variable
  CRM/Member/Form/Task/PDFLetter.php
Labels: master

#28570 Remove unused variable
  CRM/Member/Form/Task/Label.php
Labels: master, merge on pass

#28301 dev/core#4796 - Fix Cancel button on the "unsubscribe mailing"
  CRM/Mailing/Page/Common.php
Labels: master

#28575 dev/core#4833 Add unit test for legacy invoice number format
  tests/phpunit/CRM/Core/Payment/AuthorizeNetIPNTest.php
Labels: master, merge on pass

#28555 Copy functions back from metadata trait to only caller
  CRM/Contact/Import/Parser/Contact.php
Labels: master

#28338 Fix support for DB logging with multilingual
  CRM/Core/I18n/Schema.php
  CRM/Logging/Schema.php
Labels: master

#28578 Split `CRM_Utils_Address::format()` into 2 functions
  CRM/Core/BAO/Address.php
  CRM/Utils/Address.php
Labels: master

#28553 Simplify setDefaults function on contact import mapfields
  CRM/Contact/Import/Form/MapField.php
  tests/phpunit/CRM/Contact/Import/Form/MapFieldTest.php
Labels: master

#28530 Change URL for edit/create/delete SMS provider to support Searchkit admin ui over-ride
  CRM/Core/xml/Menu/Admin.xml
  CRM/SMS/DAO/Provider.php
  CRM/SMS/Form/Provider.php
  xml/schema/SMS/Provider.xml
Labels: master

#28567 E-notice fix when no template exists
  CRM/Import/Forms.php
Labels: master

#28586 [php8] dev/core#4807 - Move $_entityTagValues to where it's used
  CRM/Core/Form.php
  CRM/Core/Form/Tag.php
Labels: master

#28564 path changes for PDFFormat
  CRM/Admin/Page/PdfFormats.php
  CRM/Core/xml/Menu/Admin.xml
Labels: master

#28592 fix json version file (5.69)
  js/version.json
Labels: sig:unreleased-regression, 5.69

#28591 fix json version file
  js/version.json
Labels: master, sig:unreleased-regression

#28550 AdminUI: Migrate LabelFormat from SearchUI to AdminUI
  ext/civicrm_admin_ui/ang/afsearchLabelFormats.aff.html
  ext/civicrm_admin_ui/ang/afsearchLabelFormats.aff.php
  ext/civicrm_admin_ui/managed/SavedSearch_Label_Formats.mgd.php
  ext/civicrm_search_ui/ang/afsearchLabelFormat.aff.html
  ext/civicrm_search_ui/ang/afsearchLabelFormat.aff.php
Labels: master, merge on pass

#28598 Remove unused function deprecated a year ago
  CRM/Contact/BAO/Contact/Utils.php
Labels: master

#28503 Standalone - user edit pop-up and entity link
  ext/standaloneusers/managed/SavedSearch_Administer_Users.mgd.php
Labels: master

#28600 [REF][PHP8.2] address dynamic properties in CRM_Event_Form_SearchEvent
  CRM/Event/Form/SearchEvent.php
Labels: master

#28599 [REF][PHP8.2] Switch dynamic property to local variable
  CRM/Event/Form/Registration.php
Labels: master

#28593 [NFC] Remove unused variable
  CRM/Core/BAO/Address.php
Labels: master, merge on pass

#28604 Standalone - Remove unused reference to nonexistent file
  templates/CRM/common/standalone.tpl
Labels: master

#28565 Standalone - anonymous user access denied handling
  CRM/Utils/System/Standalone.php
  ext/standaloneusers/CRM/Standaloneusers/Page/Login.php
  ext/standaloneusers/templates/CRM/Standaloneusers/Page/Login.tpl
Labels: master, merge ready

#28595 Standalone - Add UserRole table
  ext/standaloneusers/CRM/Standaloneusers/BAO/Role.php
  ext/standaloneusers/CRM/Standaloneusers/BAO/User.php
  ext/standaloneusers/CRM/Standaloneusers/DAO/User.php
  ext/standaloneusers/CRM/Standaloneusers/DAO/UserRole.php
  ext/standaloneusers/Civi/Api4/Service/Spec/Provider/UserSpecProvider.php
  ext/standaloneusers/Civi/Api4/UserRole.php
  ext/standaloneusers/sql/auto_install.sql
  ext/standaloneusers/sql/auto_uninstall.sql
  ext/standaloneusers/xml/schema/CRM/Standaloneusers/User.xml
  ext/standaloneusers/xml/schema/CRM/Standaloneusers/UserRole.entityType.php
  ext/standaloneusers/xml/schema/CRM/Standaloneusers/UserRole.xml
Labels: master, merge on pass, comp:standalone

#28601 Allow API4 Job to be a ManagedEntity
  Civi/Api4/Job.php
Labels: master, merge on pass

#28596 [REF][PHP8.2] Change from dynamic property to local variable
  CRM/Campaign/Page/Petition/ThankYou.php
Labels: master, merge on pass

#28606 Afform - Remove unused css for collapsible containers
  ext/afform/core/ang/afCore.css
Labels: 5.69

#28590 5.69.0 release notes initial run
  release-notes.md
  release-notes/5.69.0.md
Labels: merge ready, 5.69

#28608 Clarify handling of is_email_receipt
  CRM/Contribute/Form/AdditionalPayment.php
Labels: master

#28584 [REF][PHP8.2] Survey details report - dynamic properties
  CRM/Report/Form/Campaign/SurveyDetails.php
Labels: master, merge on pass

#28610 5.69
  ext/afform/core/ang/afCore.css
  release-notes.md
  release-notes/5.69.0.md
Labels: master

#28603 Joomla - Remove old link format
  CRM/Dedupe/Merger.php
Labels: master

#28594 [REF][PHP8.2] Tidy up use of properties in CRM_Campaign_Form_Task_Release
  CRM/Campaign/Form/Task/Release.php
Labels: master

#28587 [REF][PHP8.2] Declare properties in CRM_Contribute_Form_ContributionPage_Widget
  CRM/Contribute/Form/ContributionPage/Widget.php
Labels: master, merge on pass

#28467 Ang - Change crmUiAccordion to use summary/details markup
  ang/crmUi.js
Labels: master, merge ready

#28609 Fix additional payment form to create billing address
  CRM/Contribute/Form/AdditionalPayment.php
  templates/CRM/Contribute/Form/AdditionalPayment.tpl
  tests/phpunit/CRM/Contribute/Form/AdditionalPaymentTest.php
  xml/templates/message_templates/payment_or_refund_notification_html.tpl
Labels: master

#28574 Fix MailingLabels to use token processor
  CRM/Utils/Address.php
  Civi/Token/TokenCompatSubscriber.php
  tests/phpunit/CRM/Contact/Form/Task/PrintMailingLabelTest.php
Labels: master

#28580 Add token {membership.membership_status_id.is_new}
  CRM/Core/EntityTokens.php
  CRM/Member/Tokens.php
  tests/phpunit/CRM/Member/Form/Task/PDFLetterTest.php
  tests/phpunit/CRM/Utils/TokenConsistencyTest.php
Labels: master

#28614 Fix dev/core#4852 - View notes renders as form instead of page
  CRM/Note/Form/Note.php
  templates/CRM/Note/Form/Note.tpl
Labels: 5.69

#28618 Fix dev/core#4852 - View notes renders as form instead of page
  CRM/Note/Form/Note.php
  templates/CRM/Note/Form/Note.tpl
Labels: 5.68

#28615 5.69
  CRM/Note/Form/Note.php
  templates/CRM/Note/Form/Note.tpl
Labels: master

#28622 set-version.php - Autocommit changes for version.json
  tools/bin/scripts/set-version.php
Labels: merge on pass, 5.69

#28623 ContactType - Ensure stable order
  CRM/Contact/BAO/ContactType.php
Labels: master

#28502 Standalone - consistent naming for user/role admin forms/searches
  ext/standaloneusers/ang/afsearchAdministerRoles.aff.html
  ext/standaloneusers/ang/afsearchAdministerRoles.aff.php
  ext/standaloneusers/managed/SavedSearch_Administer_Roles.mgd.php
  ext/standaloneusers/managed/SavedSearch_Administer_UserAccounts.mgd.php
Labels: master, merge on pass

#28625 5.69
  tools/bin/scripts/set-version.php
Labels: master

#28611 Fix notice regression on contact edit
  CRM/Contact/Form/Contact.php
Labels: merge on pass, 5.69

#28612 Address notice in 5.68 contact edit
  CRM/Contact/Form/Contact.php
Labels: merge on pass, 5.68

#28628 dev/core#4855 - Avoid errors on contact relationships and notes tabs in stricter environments
  ext/afform/core/CRM/Afform/ArrayHtml.php
  ext/afform/core/tests/phpunit/CRM/Afform/PageTest.php
Labels: merge on pass, 5.69

#28501 expose User Contact in standaloneusers UI
  ext/standaloneusers/CRM/Standaloneusers/DAO/User.php
  ext/standaloneusers/ang/afformEditUserAccount.aff.html
  ext/standaloneusers/managed/SavedSearch_Administer_UserAccounts.mgd.php
  ext/standaloneusers/xml/schema/CRM/Standaloneusers/User.xml
Labels: master, merge on pass

#28629 5.69
  CRM/Contact/Form/Contact.php
  ext/afform/core/CRM/Afform/ArrayHtml.php
  ext/afform/core/tests/phpunit/CRM/Afform/PageTest.php
Labels: master

#28619 PHP - Remove unneeded polyfills for php 7.3 & 7.4
  composer.json
  composer.lock
Labels: master, merge ready

#28634 Handle NULL in table name check
  ext/civiimport/civiimport.php
Labels: master

#28637 MailingSystemTest - Fix string concatenation
  tests/phpunit/CRM/Mailing/MailingSystemTest.php
Labels: master, merge on pass

#28635 dev/drupal#133 - Remove bad and unnecessary breadcrumb on Domain Contact info form
  CRM/Contact/Form/Domain.php
Labels: master

#28624 dev/user-interface#49 SearchKit default label
  ext/search_kit/Civi/Search/Admin.php
  ext/search_kit/ang/crmSearchAdmin.module.js
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdmin.component.js
Labels: master

#28627 Use standard order class to get amounts on backoffice participant form (card flow)
  CRM/Event/Form/Participant.php
Labels: master

#28589 [REF][PHP8.2] Add PHP8.2 support to CRM_Contact_Page_View_Summary
  CRM/Contact/Page/View/Summary.php
Labels: master

#28639 Remove unused function variable
  CRM/Event/Form/Participant.php
Labels: master

#28643 Deploy Package updates for DomPDF and PHP SVG Lib
  composer.json
  composer.lock
Labels: merge on pass, 5.69

#28644 5.69
  composer.json
  composer.lock
Labels: master

#28650 Fix rc-only regression where submitting back office contribution with a price set selected fatals
  CRM/Contribute/Form/Contribution.php
  CRM/Core/Form.php
  CRM/Price/BAO/PriceSet.php
Labels: 5.69
