Repository civicrm/civicrm-core, pull requests merged in 2024-12, with the labels that each got.

#31552 [REF][PHP8.2] Declare missing properties: CRM_Admin_Form_MessageTemplates
  CRM/Admin/Form/MessageTemplates.php
Labels: master

#31554 Remove unreachable code in CRM_Report_Form_Mailing_Summary
  CRM/Report/Form/Mailing/Summary.php
Labels: master

#31545 Updates RiverLea (v1.80.11) - new version numbering, fixes hidden input regression, contact merge bg cols & others
  ext/riverlea/CHANGELOG.md
  ext/riverlea/README.md
  ext/riverlea/core/css/_base.css
  ext/riverlea/core/css/_cms.css
  ext/riverlea/core/css/_core.css
  ext/riverlea/core/css/components/_accordion.css
  ext/riverlea/core/css/components/_alerts.css
  ext/riverlea/core/css/components/_form.css
  ext/riverlea/core/css/components/_icons.css
  ext/riverlea/core/css/components/_tables.css
  ext/riverlea/streams/empty/css/_variables.css
  ext/riverlea/streams/walbrook/css/_variables.css
Labels: merge ready, 5.80

#31560 dev/core#5611 - exclude ext tests from tarball
  distmaker/dists/common.sh
Labels: run-distmaker

#31559 Fix dev/core#5592 - Ensure master_id is not lost when updating master address
  CRM/Core/BAO/Address.php
  tests/phpunit/api/v4/Entity/AddressTest.php
Labels: merge on pass, has-test, sig:regression, 5.80

#31561 Fix dev/core#5592 - Ensure master_id is not lost when updating master…
  CRM/Core/BAO/Address.php
  tests/phpunit/api/v4/Entity/AddressTest.php
Labels: 5.79

#31562 5.80
  CRM/Core/BAO/Address.php
  ext/riverlea/CHANGELOG.md
  ext/riverlea/README.md
  ext/riverlea/core/css/_base.css
  ext/riverlea/core/css/_cms.css
  ext/riverlea/core/css/_core.css
  ext/riverlea/core/css/components/_accordion.css
  ext/riverlea/core/css/components/_alerts.css
  ext/riverlea/core/css/components/_form.css
  ext/riverlea/core/css/components/_icons.css
  ext/riverlea/core/css/components/_tables.css
  ext/riverlea/streams/empty/css/_variables.css
  ext/riverlea/streams/walbrook/css/_variables.css
  tests/phpunit/api/v4/Entity/AddressTest.php
Labels: master

#31564 Updates RiverLea (v1.80.12) - updates Inter font, fixes collapse regression, crm-status page
  ext/riverlea/CHANGELOG.md
  ext/riverlea/core/ang/crmStatusPage.css
  ext/riverlea/core/css/_base.css
  ext/riverlea/core/css/_core.css
  ext/riverlea/core/css/_fixes.css
  ext/riverlea/core/css/_variables.css
  ext/riverlea/fonts/InterDisplay-Italic.woff2
  ext/riverlea/fonts/InterDisplay-Regular.woff2
  ext/riverlea/fonts/InterDisplay-SemiBold.woff2
  ext/riverlea/fonts/inter-v18-latin-600.woff2
  ext/riverlea/fonts/inter-v18-latin-italic.woff2
  ext/riverlea/fonts/inter-v18-latin-regular.woff2
  ext/riverlea/streams/walbrook/css/civicrm.css
Labels: 5.80

#31565 5.80
  ext/riverlea/CHANGELOG.md
  ext/riverlea/core/ang/crmStatusPage.css
  ext/riverlea/core/css/_base.css
  ext/riverlea/core/css/_core.css
  ext/riverlea/core/css/_fixes.css
  ext/riverlea/core/css/_variables.css
  ext/riverlea/fonts/InterDisplay-Italic.woff2
  ext/riverlea/fonts/InterDisplay-Regular.woff2
  ext/riverlea/fonts/InterDisplay-SemiBold.woff2
  ext/riverlea/fonts/inter-v18-latin-600.woff2
  ext/riverlea/fonts/inter-v18-latin-italic.woff2
  ext/riverlea/fonts/inter-v18-latin-regular.woff2
  ext/riverlea/streams/walbrook/css/civicrm.css
Labels: master

#31514 Api4 - Case-insensitive matching for arrayQuery entities
  Civi/Api4/Generic/Traits/ArrayQueryActionTrait.php
  ext/afform/core/ang/af/afForm.component.js
  ext/afform/mock/tests/phpunit/api/v4/Afform/AfformConditionalUsageTest.php
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/SearchRunTest.php
  tests/phpunit/api/v4/Action/GetFromArrayTest.php
Labels: master, merge ready

#31536 SearchKit - Set acl_bypass=false when cloning a display
  ext/search_kit/ang/crmSearchAdmin.module.js
Labels: master

#31508 Api4 CustomGroup.get - use in-memory cache to answer simple calls
  Civi/Api4/Action/CustomGroup/Get.php
  Civi/Api4/CustomGroup.php
  Civi/Api4/Generic/BasicGetAction.php
  Civi/Api4/Generic/Traits/PseudoconstantOutputTrait.php
  tests/phpunit/api/v4/Action/CachedGetTest.php
Labels: master, has-test

#31567 RiverLea (1.80.13): Message Template afform cleanup, .crm-pager layout, Joomla underline bug, Thames tables
  ext/riverlea/CHANGELOG.md
  ext/riverlea/core/css/_core.css
  ext/riverlea/core/css/_fixes.css
  ext/riverlea/core/css/_variables.css
  ext/riverlea/core/css/components/_buttons.css
  ext/riverlea/core/css/components/_components.css
  ext/riverlea/core/css/components/_nav.css
  ext/riverlea/core/css/components/_page.css
  ext/riverlea/core/css/components/_tables.css
  ext/riverlea/core/css/joomla.css
Labels: 5.80

#31547 [NFC] 5.80 release notes
  contributor-key.yml
  release-notes/5.80.0.md
Labels: 5.80

#31330 dev/core#5541 Prevent generation of numeric hashes
  CRM/Contact/BAO/Contact/Utils.php
Labels: master, merge ready

#31570 Api4 - Fix CustomField.delete to perform all postprocessing
  CRM/Core/BAO/CustomField.php
  CRM/Core/BAO/Mapping.php
  CRM/Core/BAO/UFField.php
  tests/phpunit/api/v4/Custom/CustomFieldAlterTest.php
Labels: master, has-test

#31473 CRM_Utils_System::isSSL - support X_FORWARDED_PROTO to work behind reverse proxy
  CRM/Utils/System.php
Labels: master, merge ready

#31573 Exclude IPN URLs from IDS
  CRM/Core/IDS.php
Labels: master, merge on pass

#31528 SearchKit - Add search templates feature
  CRM/Upgrade/Incremental/php/FiveEightyOne.php
  Civi/Api4/Generic/AbstractGetAction.php
  Civi/Schema/SqlEntityMetadata.php
  ext/afform/admin/ang/afGuiEditor.js
  ext/afform/core/Civi/Api4/Subscriber/AfformAutocompleteSubscriber.php
  ext/search_kit/ang/crmSearchAdmin.module.js
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdmin.component.js
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdmin.html
  ext/search_kit/ang/crmSearchAdmin/searchListing/buttons.html
  ext/search_kit/ang/crmSearchAdmin/searchListing/crmSearchAdminSearchListing.component.js
  ext/search_kit/ang/crmSearchAdmin/searchListing/searchList.html
  ext/search_kit/ang/crmSearchAdmin/tabs.html
  schema/Contact/SavedSearch.entityType.php
  tests/phpunit/api/v4/Entity/SavedSearchTest.php
Labels: master, merge ready

#31574 RiverLea: 1.80.14, fixes regression extensions/riverlea/#91
  ext/riverlea/CHANGELOG.md
  ext/riverlea/core/css/_core.css
  ext/riverlea/core/css/components/_tables.css
Labels: merge on pass, 5.80

#31575 5.80
  Civi/Schema/LegacySqlEntityMetadata.php
  contributor-key.yml
  ext/riverlea/CHANGELOG.md
  ext/riverlea/core/css/_core.css
  ext/riverlea/core/css/_fixes.css
  ext/riverlea/core/css/_variables.css
  ext/riverlea/core/css/components/_buttons.css
  ext/riverlea/core/css/components/_components.css
  ext/riverlea/core/css/components/_nav.css
  ext/riverlea/core/css/components/_page.css
  ext/riverlea/core/css/components/_tables.css
  ext/riverlea/core/css/joomla.css
  release-notes/5.80.0.md
Labels: master

#31577 5.79.2 - Add notes. Set version.
  js/version.json
  release-notes.md
  release-notes/5.79.2.md
  sql/civicrm_generated.mysql
  sql/test_data_second_domain.mysql
  xml/version.xml
Labels: 5.79

#31569 Api4 - Generalise CustomGroup.get caching approach and use for CustomField also
  Civi/Api4/Action/CustomField/Get.php
  Civi/Api4/CustomField.php
  Civi/Api4/CustomGroup.php
  Civi/Api4/Generic/CachedDAOGetAction.php
  tests/phpunit/api/v4/Action/CachedGetTest.php
Labels: master, has-test

#31548 Afform - Add (no placeholder) placeholder in FormBuilder
  ext/afform/admin/ang/afGuiEditor/inputType/Email.html
  ext/afform/admin/ang/afGuiEditor/inputType/Text.html
Labels: master

#31405 Remove another use of api3 contribution.completetransaction
  CRM/Contribute/Form/Contribution/Confirm.php
Labels: master, merge ready

#31576 dev/core#5541 Shift Mailing View page away from using is_numeric and …
  CRM/Mailing/Page/View.php
  tests/phpunit/CRM/Mailing/Page/ViewTest.php
Labels: master, merge on pass

#31581 (dev/core#5606) user_dashboard - Fix upgrade error
  ext/user_dashboard/ang/afsearchUserDashboard.aff.php
  ext/user_dashboard/ang/afsearchUserDashboard.alterLayout.php
  ext/user_dashboard/user_dashboard.php
Labels: 5.81

#31582 (dev/core#5606) user_dashboard - Fix upgrade error
  ext/user_dashboard/ang/afsearchUserDashboard.aff.php
  ext/user_dashboard/ang/afsearchUserDashboard.alterLayout.php
  ext/user_dashboard/user_dashboard.php
Labels: 5.80

#31584 Add `\DateTime` and `\Brick\Money\Money` to parameter type hint of `TokenRow::tokens()`
  Civi/Token/TokenRow.php
Labels: 5.81

#31587 (dev/core#5591) HTMLPurifier - Allow image widths to use percentages
  CRM/Utils/String.php
Labels: 5.81

#31555 dev/core#5626 SMS messages incorrectly contain header and footer
  CRM/Mailing/BAO/Mailing.php
  tests/phpunit/CRM/Mailing/MailingHeaderFooterTest.php
Labels: merge ready, 5.81

#31556 Standaloneusers - split the public and private bits of User.SendPasswordReset into separate actions
  ext/standaloneusers/CRM/Standaloneusers/BAO/User.php
  ext/standaloneusers/CRM/Standaloneusers/Page/ResetPassword.php
  ext/standaloneusers/CRM/Standaloneusers/WorkflowMessage/PasswordReset.php
  ext/standaloneusers/Civi/Api4/Action/User/PasswordReset.php
  ext/standaloneusers/Civi/Api4/Action/User/RequestPasswordResetEmail.php
  ext/standaloneusers/Civi/Api4/Action/User/SendPasswordReset.php
  ext/standaloneusers/Civi/Api4/Action/User/SendPasswordResetEmail.php
  ext/standaloneusers/Civi/Api4/User.php
  ext/standaloneusers/Civi/Standalone/Security.php
  ext/standaloneusers/ang/crmResetPassword.js
  ext/standaloneusers/ang/crmResetPassword/crmResetPassword.html
  ext/standaloneusers/tests/phpunit/Civi/Standalone/SecurityTest.php
Labels: merge ready, run-standalone, 5.81

#31588 5.81
  CRM/Mailing/BAO/Mailing.php
  CRM/Utils/String.php
  Civi/Token/TokenRow.php
  ext/standaloneusers/CRM/Standaloneusers/BAO/User.php
  ext/standaloneusers/CRM/Standaloneusers/Page/ResetPassword.php
  ext/standaloneusers/CRM/Standaloneusers/WorkflowMessage/PasswordReset.php
  ext/standaloneusers/Civi/Api4/Action/User/PasswordReset.php
  ext/standaloneusers/Civi/Api4/Action/User/RequestPasswordResetEmail.php
  ext/standaloneusers/Civi/Api4/Action/User/SendPasswordReset.php
  ext/standaloneusers/Civi/Api4/Action/User/SendPasswordResetEmail.php
  ext/standaloneusers/Civi/Api4/User.php
  ext/standaloneusers/Civi/Standalone/Security.php
  ext/standaloneusers/ang/crmResetPassword.js
  ext/standaloneusers/ang/crmResetPassword/crmResetPassword.html
  ext/standaloneusers/tests/phpunit/Civi/Standalone/SecurityTest.php
  ext/user_dashboard/ang/afsearchUserDashboard.aff.php
  ext/user_dashboard/ang/afsearchUserDashboard.alterLayout.php
  ext/user_dashboard/user_dashboard.php
  tests/phpunit/CRM/Mailing/MailingHeaderFooterTest.php
Labels: master

#31563 composer.json - Lighten up the load from bower_components/monaco-editor
  Civi/ComposerTasks.php
  composer.compile.json
  composer.json
Labels: master, merge ready

#31589 (dev/core#5626) SMS messages incorrectly contain header and footer
  CRM/Mailing/BAO/Mailing.php
  tests/phpunit/CRM/Mailing/MailingHeaderFooterTest.php
Labels: 5.80

#31590 (dev/core#5585) CiviContribute - Consistently encode/decode the value for "Product Options"
  CRM/Contribute/BAO/Premium.php
  CRM/Contribute/Form/ManagePremiums.php
  CRM/Core/DAO.php
  CRM/Utils/CommaKV.php
  schema/Contribute/Product.entityType.php
  tests/phpunit/CRM/Utils/CommaKVTest.php
Labels: 5.81

#31591 (dev/core#5585) CiviContribute - Consistently encode/decode the value for "Product Options"
  CRM/Contribute/BAO/Premium.php
  CRM/Contribute/Form/ManagePremiums.php
  CRM/Core/DAO.php
  CRM/Utils/CommaKV.php
  schema/Contribute/Product.entityType.php
  tests/phpunit/CRM/Utils/CommaKVTest.php
Labels: 5.80

#31595 (dev/core#5585) CiviContribute - Fix display of premium on confirmation page
  CRM/Contribute/Form/ContributionBase.php
Labels: 5.80

#31594 (dev/core#5585) CiviContribute - Fix display of "Premium/Thank You Gift" on confirmation page
  CRM/Contribute/Form/ContributionBase.php
Labels: 5.81

#31599 5.80.1 - Add notes. Set version.
  js/version.json
  release-notes.md
  release-notes/5.80.1.md
  sql/civicrm_generated.mysql
  sql/test_data_second_domain.mysql
  xml/version.xml
Labels: 5.80

#30943 Afform Admin: allow multi-select default values on more input types
  ext/afform/admin/Civi/Api4/Action/Afform/LoadAdminData.php
  ext/afform/admin/ang/afGuiEditor/afGuiFieldValue.directive.js
Labels: master

#31001 [REF] Ensure that _fid property is updated following save so extensio…
  CRM/Price/Form/Field.php
Labels: master

#31459 dev/core#5179 Afform - Enable file downloads
  Civi/Api4/Service/Spec/Provider/FileGetSpecProvider.php
  ext/afform/core/Civi/Api4/Action/Afform/AbstractProcessor.php
  ext/afform/core/ang/af/fields/DisplayOnly.html
  ext/afform/core/ang/af/fields/File.html
  tests/phpunit/api/v4/Custom/CustomFileTest.php
Labels: master, has-test

#31602 Send Email: rename HTML Format to Message Body, tweak help
  templates/CRM/Contact/Form/Task/Email.hlp
  templates/CRM/Contact/Form/Task/EmailCommon.tpl
Labels: sig:user interfacing improvement

#31578 Api4 - Improve CachedDAOGetAction to handle simple implicit joins
  Civi/Api4/Action/CustomField/Get.php
  Civi/Api4/Generic/CachedDAOGetAction.php
  tests/phpunit/api/v4/Action/CachedGetTest.php
Labels: master

#31566 [REF] Set backOffice Parameter on Payment Processor when on the back …
  CRM/Contribute/Form/Contribution.php
  CRM/Event/Form/Participant.php
  CRM/Member/Form/Membership.php
  CRM/Member/Form/MembershipRenewal.php
Labels: master, merge ready

#31604 Revert "afform tabs - use CRM_Core_BAO_CustomGroup cache"
  ext/afform/core/Civi/Api4/Action/CustomGroup/GetAfforms.php
  ext/afform/core/afform.php
  ext/civicrm_admin_ui/Civi/Api4/Action/CustomGroup/GetSearchKit.php
Labels: master, merge on pass

#31036 dev/core#5320 [REF] Respond with a 400 for Event Registration and Info pages to reduce log overload from bots
  CRM/Event/Form/Registration.php
  CRM/Event/Page/EventInfo.php
  CRM/Event/StateMachine/Registration.php
  CRM/Mailing/Form/Optout.php
  CRM/Mailing/Form/Unsubscribe.php
  CRM/Mailing/Page/Open.php
  CRM/Mailing/Page/Unsubscribe.php
  CRM/Utils/System.php
Labels: master, merge on pass

#30740 (dev/core#5365) Extension Upgrade - Pass-through status-result for custom upgraders
  ext/afform/core/CRM/Afform/Upgrader.php
  ext/afform/core/sql/upgrade_1001.sql
  mixin/lib/civimix-schema/src/AutomaticUpgrader.php
  mixin/lib/civimix-schema/src/SqlGenerator.php
Labels: merge ready, 5.81

#31607 (dev/core#5365) Extension Upgrade - Pass-through status-result for custom upgraders
  ext/afform/core/CRM/Afform/Upgrader.php
  ext/afform/core/sql/upgrade_1001.sql
  mixin/lib/civimix-schema/src/AutomaticUpgrader.php
  mixin/lib/civimix-schema/src/SqlGenerator.php
Labels: 5.80

#31411 Remove remaining calls to (deprecated) cache()->flush
  CRM/Core/BAO/CustomGroup.php
  CRM/Core/BAO/OptionValue.php
  CRM/Price/BAO/PriceField.php
  CRM/Upgrade/Incremental/php/FiveFortySeven.php
  CRM/Utils/Cache/ArrayCache.php
Labels: master, merge on pass

#31610 (NFC) Test cases should cleanup HTTP_X_REQUESTED_WITH consistently.
  Civi/Test/CiviTestListener.php
  Civi/Test/CiviTestListenerPHPUnit7.php
  Civi/Test/Legacy/CiviTestListener.php
  tests/phpunit/CRM/Core/Page/AJAXTest.php
Labels: 5.80

#31609 (NFC) Test cases should cleanup HTTP_X_REQUESTED_WITH consistently.
  Civi/Test/CiviTestListener.php
  Civi/Test/CiviTestListenerPHPUnit7.php
  Civi/Test/Legacy/CiviTestListener.php
  tests/phpunit/CRM/Core/Page/AJAXTest.php
Labels: 5.81

#31612 (NFC) tests/phpunit/api/v4 - Fix inconsistent namespace
  tests/phpunit/api/v4/Action/AutocompleteQuicksearchTest.php
  tests/phpunit/api/v4/Action/FieldsCallbackTest.php
  tests/phpunit/api/v4/Entity/CampaignTest.php
Labels: master

#31613 [NFC] Remove override of CiviUnitTestCase::runTests
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: master, merge on pass

#31614 (NFC) RegionTest, SmartyTest - Restore performance
  tests/phpunit/CRM/Core/RegionTest.php
  tests/phpunit/CRM/Core/Smarty/plugins/CrmMoneyTest.php
  tests/phpunit/CRM/Core/Smarty/plugins/CrmPermissionTest.php
  tests/phpunit/CRM/Core/Smarty/plugins/CrmRSSPubDateTest.php
  tests/phpunit/CRM/Core/Smarty/plugins/CrmScopeTest.php
  tests/phpunit/CRM/Core/Smarty/plugins/CrmUpperTest.php
  tests/phpunit/CRM/Core/Smarty/plugins/HtxtTest.php
  tests/phpunit/CRM/Core/Smarty/plugins/UrlTest.php
  tests/phpunit/CRM/Core/SmartyTest.php
Labels: master

#31616 FieldsCallbackTest - Behave more consistently
  tests/phpunit/api/v4/Action/FieldsCallbackTest.php
Labels: 5.81

#31598 RiverLea 1.2-5.81: regression fixes, adds crm-designer.css
  ext/riverlea/CHANGELOG.md
  ext/riverlea/core/css/_cms.css
  ext/riverlea/core/css/_core.css
  ext/riverlea/core/css/components/_dropdowns.css
  ext/riverlea/core/css/components/_tables.css
  ext/riverlea/core/css/crm.designer.css
  ext/riverlea/info.xml
  ext/riverlea/streams/thames/css/civicrm.css
Labels: 5.81

#31605 AdminUI: tweak TabMember markup and translation
  ang/afform/afsearchTabRel.aff.html
  ext/civicrm_admin_ui/ang/afformTabMember.aff.html
  ext/civicrm_admin_ui/ang/afsearchTabMember.aff.html
  ext/civicrm_admin_ui/managed/SavedSearch_Contact_Summary_Memberships.mgd.php
Labels: master, merge ready, sig:user interfacing improvement

#31622 dev/core#4448 - SearchKit: Support relative dates in HAVING clause
  Civi/Api4/Query/Api4Query.php
  Civi/Api4/Query/SqlFunction.php
  ext/search_kit/ang/crmSearchAdmin/crmSearch-conditions.html
  ext/search_kit/ang/crmSearchAdmin/crmSearchClause.component.js
  tests/phpunit/api/v4/Action/DateTest.php
Labels: master, merge ready, has-test

#31623 NFC - Simplify api4 docblock
  Civi/Api4/Query/Api4Query.php
Labels: master

#31615 [NFC] first pass at 5.81 release notes
  contributor-key.yml
  release-notes/5.81.0.md
Labels: 5.81

#31627 PHPUnit 10 - Various fix for scheduled-reminder tests (et al)
  tests/phpunit/CRM/Activity/ActionMappingTest.php
  tests/phpunit/CRM/Contribute/ActionMapping/ByTypeTest.php
  tests/phpunit/CRM/Event/ActionMappingTest.php
  tests/phpunit/Civi/ActionSchedule/AbstractMappingTestCase.php
  tests/phpunit/Civi/ActionSchedule/SavedSearchMappingTest.php
  tests/phpunit/api/v4/Custom/CustomFileTest.php
Labels: master

#31624 fixes core/5635 - Job params are ignored when job.execute is called
  CRM/Core/JobManager.php
Labels: merge ready, 5.81

#31626 PHPUnit 10 - Various fixes for "E2E" suite
  CRM/Core/ClassLoader.php
  tests/phpunit/CiviTest/CiviSimpleCacheTestCase.php
  tests/phpunit/E2E/AllTests.php
  tests/phpunit/E2E/Api4/LocaleTest.php
  tests/phpunit/E2E/Cache/CacheTestCase.php
  tests/phpunit/E2E/Cache/TwoInstancesTest.php
  tests/phpunit/E2E/Core/AssetBuilderTest.php
  tests/phpunit/E2E/Core/ErrorTest.php
  tests/phpunit/E2E/Core/PrevNextTest.php
  tests/phpunit/E2E/Core/SmartyStringTest.php
  tests/phpunit/E2E/Extern/AuthxRestTest.php
  tests/phpunit/E2E/Extern/CliRunnerTest.php
  tests/phpunit/E2E/Extern/LegacyRestTest.php
  tests/phpunit/E2E/Extern/RestTestCase.php
Labels: master

#31611 Riverlea - disable dark mode by default
  ext/riverlea/settings/riverlea.setting.php
Labels: master

#31629 5.81
  CRM/Core/JobManager.php
  contributor-key.yml
  ext/riverlea/CHANGELOG.md
  ext/riverlea/core/css/_cms.css
  ext/riverlea/core/css/_core.css
  ext/riverlea/core/css/components/_dropdowns.css
  ext/riverlea/core/css/components/_tables.css
  ext/riverlea/core/css/crm.designer.css
  ext/riverlea/info.xml
  ext/riverlea/streams/thames/css/civicrm.css
  release-notes/5.81.0.md
Labels: master

#31631 [NFC] Backport 31616 - FieldsCallbackTest - Behave more consistently
  tests/phpunit/api/v4/Action/FieldsCallbackTest.php
Labels: 5.80

#31618 SearchKit - Improve behavior of appending (copy) to cloned searches
  CRM/Tag/Form/Edit.php
  ext/search_kit/ang/crmSearchAdmin.module.js
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdmin.component.js
Labels: master

#31633 Enable Riverlea extension (*not* theme) + dark mode on new Standalone installs
  setup/plugins/init/StandaloneRiverlea.civi-setup.php
Labels: master

#31628 WordPress Permissions: code cleanup, use cycle and odd-row css classes
  templates/CRM/ACL/Form/WordPress/Permissions.tpl
Labels: master

#31636 [REF] use common helper to set expected keys for tabs in Summary.tpl and TabHeader.tpl
  CRM/Campaign/Form/Survey.php
  CRM/Campaign/Form/Survey/TabHeader.php
  CRM/Campaign/Page/Vote.php
  CRM/Contact/Page/View/Summary.php
  CRM/Contribute/Form/ContributionPage/TabHeader.php
  CRM/Core/Form.php
  CRM/Core/Page.php
  CRM/Core/Smarty.php
  CRM/Event/Form/ManageEvent.php
  CRM/Event/Form/ManageEvent/TabHeader.php
Labels: master

#31641 Notice fix
  CRM/Event/Page/EventInfo.php
Labels: master, merge on pass

#31639 Smarty Notice fix
  templates/CRM/Tag/Form/Tagtree.tpl
Labels: master

#31621 Api4 - Fix dataType of IF functions
  Civi/Api4/Query/SqlFunctionIF.php
  Civi/Api4/Query/SqlFunctionIFNULL.php
Labels: master

#31480 Afform - Add action modes for joins
  ext/afform/admin/ang/afGuiEditor.css
  ext/afform/admin/ang/afGuiEditor/elements/afGuiContainer-menu.html
  ext/afform/admin/ang/afGuiEditor/elements/afGuiContainer.component.js
  ext/afform/core/CRM/Afform/ArrayHtml.php
  ext/afform/core/Civi/Api4/Action/Afform/AbstractProcessor.php
  ext/afform/core/Civi/Api4/Action/Afform/Submit.php
  ext/afform/mock/tests/phpunit/api/v4/Afform/AfformJoinActionUsageTest.php
Labels: master, has-test

#31644 [backport] Riverlea dark mode default
  ext/riverlea/settings/riverlea.setting.php
Labels: 5.80

#31637 dev/core#5655 Contribute fee amount
  CRM/Contribute/Form/AdditionalPayment.php
Labels: master

#31643 [backport] Riverlea dark mode default
  ext/riverlea/settings/riverlea.setting.php
Labels: 5.81

#31645 update deleted files list to fix "old files" status check warning
  deleted-files-list.json
Labels: 5.81

#31647 5.81
  deleted-files-list.json
Labels: master

#31648 Update deleted files list to fix "old files" status check warning (master version)
  deleted-files-list.json
Labels: master

#31654 Smarty notice fix on campaign
  templates/CRM/Mailing/Page/Report.tpl
Labels: master

#31653 Fix Smarty notice - never assigned `$fieldHandle`
  templates/CRM/Price/Form/PriceSet.tpl
Labels: master, merge on pass

#31608 "Domain not found" error (error code 450 - class 4.1.2) is not a temporary error
  CRM/Admin/Form/Preferences/Mailing.php
  ext/flexmailer/src/Listener/DefaultSender.php
  settings/Mailing.setting.php
  templates/CRM/Admin/Form/Preferences/Mailing.hlp
Labels: master

#31657 [REF][PHP8.2] Fix typo in property name
  CRM/Mailing/Selector/Event.php
Labels: master

#30618 Fix mis-allocation of is_primary when Primary and Billing emails on profiles on an event
  CRM/Contact/BAO/Contact.php
Labels: master

#31659 (NFC) Cast null to string for explode
  CRM/Member/Form/MembershipBlock.php
Labels: master

#31634 dev/drupal#200: Performance improvement
  CRM/Utils/System/Drupal8.php
Labels: master, merge ready

#31663 dev/core#5660 - Fix various recently introduced crashes
  CRM/Campaign/Form/Survey.php
  CRM/Campaign/Form/Survey/TabHeader.php
  CRM/Contribute/Form/ContributionPage/TabHeader.php
  CRM/Event/Form/ManageEvent.php
  CRM/Event/Form/ManageEvent/TabHeader.php
Labels: master

#31662 dev/core#4782 - alternate 2 to 28191 - Allow turning off use of memory engine
  CRM/Admin/Form/Setting/Miscellaneous.php
  CRM/Utils/SQL/TempTable.php
  settings/Core.setting.php
  tests/phpunit/CRM/Utils/SQLTest.php
Labels: master

#31667 Ensure null is not passed to htmlentities
  CRM/Activity/BAO/ActivityContact.php
Labels: master

#31666 Afform - Fix default showing literal 'undefined'
  ext/afform/admin/ang/afGuiEditor/elements/afGuiField.component.js
Labels: master, merge on pass

#31635 Admin ACLs: remove report class on table
  templates/CRM/Admin/Page/Access.tpl
Labels: master

#31596 standaloneusers - add search kit task to send password reset email
  ext/standaloneusers/managed/SavedSearch_Administer_UserAccounts.mgd.php
  ext/standaloneusers/standaloneusers.php
Labels: merge ready, 5.81

#31606 dev/core#5603 Support multi-record CustomGroups for Events using Afform tab display
  CRM/Core/BAO/CustomGroup.php
  CRM/Custom/Form/Group.php
  ang/afform/afsearchTabNote.aff.html
  ang/afform/afsearchTabRel.aff.html
  ext/afform/core/Civi/Api4/Action/CustomGroup/GetAfforms.php
  ext/afform/core/afform.php
  ext/afform/core/templates/afform/InlineAfform.tpl
  ext/afform/core/templates/afform/contactSummary/AfformTab.tpl
  ext/afform/core/templates/afform/customGroups/afblock.tpl
  ext/afform/core/templates/afform/customGroups/afformEdit.tpl
  ext/afform/core/templates/afform/customGroups/afformView.tpl
  ext/afform/core/templates/afform/customGroups/afsearchTab.tpl
  ext/civicrm_admin_ui/Civi/Api4/Action/CustomGroup/GetSearchKit.php
  ext/civicrm_admin_ui/Civi/Api4/Event/Subscriber/CustomGroupEntityLinks.php
  ext/civicrm_admin_ui/ang/afformTabMember.aff.html
  ext/civicrm_admin_ui/ang/afsearchTabActivity.aff.html
  ext/civicrm_admin_ui/ang/afsearchTabMember.aff.html
  ext/civicrm_admin_ui/ang/afsearchTabParticipant.aff.html
  ext/civicrm_admin_ui/civicrm_admin_ui.php
  ext/civigrant/ang/afsearchTabGrant.aff.html
  templates/CRM/Contact/Page/View/Summary.tpl
  templates/CRM/Custom/Form/Group.hlp
  templates/CRM/Custom/Form/Group.tpl
  templates/CRM/Event/Page/DashBoard.tpl
  templates/CRM/common/TabHeader.tpl
Labels: master, merge ready

#31449 Removes contact_id condition around 'including yourself' text
  templates/CRM/Event/Form/Registration/Register.tpl
Labels: master, merge ready, sig:user interfacing improvement

#31656 dev/core#5653 - Add screen tip for URL filter to show format should be "#/?field=value"
  ext/afform/admin/ang/afGuiEditor/afGuiSearch.html
Labels: master, merge ready

#31670 SearchKit - Fix missing pseudofield label
  Civi/Api4/Generic/Traits/SavedSearchInspectorTrait.php
Labels: master

#31649 SearchKit - Enable rewrite in footer totals
  ext/search_kit/Civi/Api4/Action/SearchDisplay/AbstractRunAction.php
  ext/search_kit/Civi/Api4/Action/SearchDisplay/Run.php
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdminTokenSelect.component.js
  ext/search_kit/ang/crmSearchAdmin/displays/searchAdminDisplayTable.component.js
  ext/search_kit/ang/crmSearchAdmin/displays/searchAdminDisplayTable.html
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/SearchRunTest.php
Labels: master, has-test

#31583 SearchKit - Add 'whole row' and 'add row' editable features
  CRM/Utils/String.php
  ext/civicrm_admin_ui/ang/afsearchCustomFieldOptions.aff.html
  ext/civicrm_admin_ui/ang/afsearchCustomFieldOptions.aff.php
  ext/civicrm_admin_ui/civicrm_admin_ui.civix.php
  ext/civicrm_admin_ui/info.xml
  ext/civicrm_admin_ui/managed/SavedSearch_Administer_Custom_Field_Options.mgd.php
  ext/civicrm_admin_ui/managed/SavedSearch_Administer_Custom_Fields.mgd.php
  ext/search_kit/Civi/Api4/Action/SearchDisplay/AbstractRunAction.php
  ext/search_kit/Civi/Api4/Action/SearchDisplay/InlineEdit.php
  ext/search_kit/Civi/Api4/Action/SearchDisplay/Run.php
  ext/search_kit/ang/crmSearchAdmin/displays/searchAdminDisplayTable.component.js
  ext/search_kit/ang/crmSearchAdmin/displays/searchAdminDisplayTable.html
  ext/search_kit/ang/crmSearchAdmin/searchListing/crmSearchAdminSearchListing.component.js
  ext/search_kit/ang/crmSearchDisplay/colType/field.html
  ext/search_kit/ang/crmSearchDisplay/crmSearchDisplayEditable.component.js
  ext/search_kit/ang/crmSearchDisplay/crmSearchDisplayEditable.html
  ext/search_kit/ang/crmSearchDisplay/traits/searchDisplayBaseTrait.service.js
  ext/search_kit/ang/crmSearchDisplay/traits/searchDisplayEditableTrait.service.js
  ext/search_kit/ang/crmSearchDisplayTable/crmSearchDisplayTable.component.js
  ext/search_kit/ang/crmSearchDisplayTable/crmSearchDisplayTable.html
  ext/search_kit/ang/crmSearchDisplayTable/crmSearchDisplayTableBody.html
  ext/search_kit/ang/crmSearchDisplayTable/crmSearchDisplayTableCreateNew.html
  ext/search_kit/ang/crmSearchTasks/crmSearchInput/crmSearchInput.component.js
  ext/search_kit/css/crmSearchAdmin.css
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/EditableSearchTest.php
Labels: master, merge ready

#31395 dev/core#5567 Api4 - Ignore 'null' when validating param data type
  Civi/Api4/Generic/AbstractAction.php
  Civi/Api4/Utils/ReflectionUtils.php
Labels: master

#31673 CiviImport - Remove redundant function
  CRM/Import/Parser.php
Labels: master

#31658 [REF][PHP8.2] Decalare properties - CRM_Contact_Form_Merge
  CRM/Contact/Form/Merge.php
Labels: master

#31655 Fix missing membershiplog entries and add tests following #30493
  CRM/Member/BAO/Membership.php
  tests/phpunit/CRM/Member/BAO/MembershipTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/api/v3/MembershipTest.php
Labels: master

#31620 RiverLea: 1.2.2-5.81 - fixes four regressions, one visual change
  ext/riverlea/CHANGELOG.md
  ext/riverlea/README.md
  ext/riverlea/core/css/_core.css
  ext/riverlea/core/css/components/_alerts.css
  ext/riverlea/core/css/components/_form.css
  ext/riverlea/core/css/components/_tables.css
  ext/riverlea/core/css/contactSummary.css
  ext/riverlea/info.xml
Labels: 5.81

#31671 SearchKit - Fix regression rendering relationship custom fields with options
  Civi/Schema/Entity/RelationshipCacheMetadata.php
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/SearchRunTest.php
  schema/Contact/RelationshipCache.entityType.php
Labels: has-test, sig:regression, 5.81

#31665 [NFC] 5.81 release notes late changes
  release-notes/5.81.0.md
Labels: 5.81

#31674 Merge 5.81 => Master
  Civi/Schema/Entity/RelationshipCacheMetadata.php
  ext/riverlea/CHANGELOG.md
  ext/riverlea/README.md
  ext/riverlea/core/css/_core.css
  ext/riverlea/core/css/components/_alerts.css
  ext/riverlea/core/css/components/_form.css
  ext/riverlea/core/css/components/_tables.css
  ext/riverlea/core/css/contactSummary.css
  ext/riverlea/info.xml
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/SearchRunTest.php
  ext/standaloneusers/managed/SavedSearch_Administer_UserAccounts.mgd.php
  ext/standaloneusers/standaloneusers.php
  release-notes/5.81.0.md
  schema/Contact/RelationshipCache.entityType.php
Labels: master
