Repository civicrm/civicrm-core, pull requests merged in 2024-04, with the labels that each got.

#29858 asofDate gets used as constructor to DateTime which wants a string
  CRM/Contact/BAO/Query.php
Labels: master

#29820 Post split cleanup - fold private function back into caller
  CRM/Contact/Form/Inline/CustomData.php
Labels: master

#29795 Stop calling complex function to just add a field
  CRM/Contact/Form/Domain.php
Labels: master

#29853 Add check for whether SMARTY_DIR is defined
  CRM/Core/Form/Renderer.php
  CRM/Utils/String.php
Labels: master

#29861 Simplify a ts
  CRM/Contact/Form/Domain.php
Labels: master

#29827 Fix deprecation notice
  CRM/Admin/Page/Extensions.php
  CRM/Extension/Mapper.php
Labels: master

#29797 Remove a handling for CRM_Core_Error returned
  CRM/Event/BAO/Participant.php
Labels: master

#29868 Fix for `TypeError: array_key_exists(): Argument #2 ($array) must be …
  CRM/Core/DAO.php
Labels: master

#29865 Clarify join type
  CRM/Dedupe/BAO/DedupeRule.php
Labels: master

#24450 dev/core#3836 : Searching by phone in Advanced Search
  CRM/Contact/BAO/Query.php
  tests/phpunit/CRM/Contact/BAO/QueryTest.php
Labels: master

#29870 Fix bug where fields is not present
  api/v3/utils.php
Labels: 5.72

#29864 Extract isUseReservedQuery
  CRM/Dedupe/BAO/DedupeRuleGroup.php
Labels: master

#29866 Pass contact Type into sql lookup
  CRM/Dedupe/BAO/DedupeRuleGroup.php
Labels: master, merge on pass

#29874 Update Smarty3 check to refer to Smarty4
  CRM/Utils/Check/Component/Smarty.php
Labels: master, merge on pass

#29873 [REF] Extract function to get the ContactIDFieldName
  CRM/Dedupe/BAO/DedupeRuleGroup.php
  tests/phpunit/api/v3/ContactTest.php
Labels: master

#29875 Fix dev/core#5108 - Show tag label instead of name in contact summary…
  CRM/Core/BAO/Tag.php
  templates/CRM/Tag/Form/Tagtree.tpl
  tests/phpunit/CRM/Core/BAO/TagTest.php
Labels: master, merge on pass, sig:regression

#29876 Extract code to build table-level filter
  CRM/Dedupe/BAO/DedupeRuleGroup.php
Labels: master, merge on pass

#29828 dev/core#5106 - Fix visibility of afforms & saved searches for disabled components
  CRM/Core/Permission.php
  CRM/Utils/System/UnitTests.php
  ext/afform/core/afform.php
  ext/civicrm_admin_ui/managed/SavedSearch_Administer_Assigned_Financial_Accounts.mgd.php
  ext/civicrm_admin_ui/managed/SavedSearch_Administer_Financial_Accounts.mgd.php
  ext/civicrm_admin_ui/managed/SavedSearch_Administer_Financial_Types.mgd.php
  ext/civicrm_admin_ui/managed/SavedSearch_Administer_Payment_Processors.mgd.php
  ext/civicrm_admin_ui/managed/SavedSearch_Contact_Summary_Events.mgd.php
  ext/civicrm_admin_ui/managed/SavedSearch_Contact_Summary_Membership_Type.mgd.php
  ext/civicrm_admin_ui/managed/SavedSearch_Contact_Summary_Memberships.mgd.php
  ext/civicrm_admin_ui/managed/SavedSearch_Manage_Contribution_Pages.mgd.php
  ext/civicrm_admin_ui/managed/SavedSearch_Manage_Mail_Accounts.mgd.php
  tests/phpunit/api/v3/MultilingualTest.php
  tests/phpunit/api/v4/Entity/GroupTest.php
Labels: sig:regression, 5.72

#29877 Extract code to determine rule filter
  CRM/Dedupe/BAO/DedupeRuleGroup.php
Labels: master

#29817 dev/core#5110 - AfformAdmin - Fix 'Remember Filters' checkbox
  ext/afform/admin/ang/afGuiEditor/afGuiSearch.component.js
  ext/afform/admin/ang/afGuiEditor/afGuiSearch.html
Labels: 5.72

#29878 5.72.0 release notes
  contributor-key.yml
  release-notes.md
  release-notes/5.71.0.md
  release-notes/5.71.1.md
  release-notes/5.71.2.md
  release-notes/5.72.0.md
Labels: 5.72

#29831 dev/core#5104 Afform - improve relative date support
  ext/afform/admin/ang/afGuiEditor/elements/afGuiField-menu.html
  ext/afform/admin/ang/afGuiEditor/elements/afGuiField.component.js
  ext/afform/core/ang/af/afField.component.js
Labels: 5.72

#29880 Merge forward (5.72-rc => master)
  CRM/Core/Permission.php
  CRM/Utils/System/UnitTests.php
  contributor-key.yml
  ext/afform/admin/ang/afGuiEditor/afGuiSearch.component.js
  ext/afform/admin/ang/afGuiEditor/afGuiSearch.html
  ext/afform/admin/ang/afGuiEditor/elements/afGuiField-menu.html
  ext/afform/admin/ang/afGuiEditor/elements/afGuiField.component.js
  ext/afform/core/afform.php
  ext/afform/core/ang/af/afField.component.js
  ext/civicrm_admin_ui/managed/SavedSearch_Administer_Assigned_Financial_Accounts.mgd.php
  ext/civicrm_admin_ui/managed/SavedSearch_Administer_Financial_Accounts.mgd.php
  ext/civicrm_admin_ui/managed/SavedSearch_Administer_Financial_Types.mgd.php
  ext/civicrm_admin_ui/managed/SavedSearch_Administer_Payment_Processors.mgd.php
  ext/civicrm_admin_ui/managed/SavedSearch_Contact_Summary_Events.mgd.php
  ext/civicrm_admin_ui/managed/SavedSearch_Contact_Summary_Membership_Type.mgd.php
  ext/civicrm_admin_ui/managed/SavedSearch_Contact_Summary_Memberships.mgd.php
  ext/civicrm_admin_ui/managed/SavedSearch_Manage_Contribution_Pages.mgd.php
  ext/civicrm_admin_ui/managed/SavedSearch_Manage_Mail_Accounts.mgd.php
  release-notes.md
  release-notes/5.71.0.md
  release-notes/5.71.1.md
  release-notes/5.71.2.md
  release-notes/5.72.0.md
  tests/phpunit/api/v3/MultilingualTest.php
  tests/phpunit/api/v4/Entity/GroupTest.php
Labels: master

#29881 StandaloneCivicrmFilesPath - Fix WP installation. Focus on Standalone
  setup/plugins/installFiles/StandaloneCivicrmFilesPath.civi-setup.php
Labels: merge on pass, 5.72

#29833 dev/core#5078 FormBuilder - Fix saving when file upload is present
  ext/afform/core/Civi/Api4/Action/Afform/AbstractProcessor.php
  ext/afform/core/Civi/Api4/Action/Afform/Submit.php
  ext/afform/core/ang/af/fields/File.html
  ext/afform/mock/tests/phpunit/api/v4/Afform/AfformFileUploadTest.php
Labels: master, sig:regression

#29767 ContributionProduct - Add serialize metadata
  CRM/Contribute/DAO/Product.php
  CRM/Contribute/Form/ContributionBase.php
  xml/schema/Contribute/Product.xml
Labels: master

#29691 Premium Products: allow key=val format for product options
  CRM/Contribute/BAO/Premium.php
  CRM/Contribute/Form/AdditionalInfo.php
  CRM/Contribute/Form/Contribution.php
  CRM/Contribute/Form/ContributionView.php
  templates/CRM/Contribute/Form/ContributionView.tpl
  templates/CRM/Contribute/Form/ManagePremiums.tpl
  tests/phpunit/CRM/Contribute/Form/ContributionTest.php
Labels: master

#29884 dev/core#5078 FormBuilder - Fix saving when file upload is present
  ext/afform/core/Civi/Api4/Action/Afform/AbstractProcessor.php
  ext/afform/core/Civi/Api4/Action/Afform/Submit.php
  ext/afform/core/ang/af/fields/File.html
  ext/afform/mock/tests/phpunit/api/v4/Afform/AfformFileUploadTest.php
Labels: merge on pass, port

#29883 dev/core#5123 Membership dashboard not shown (fix in api4)
  Civi/Api4/Service/Schema/Joinable/Joinable.php
Labels: master

#29851 Fix Smarty help function to not call fetchWith
  CRM/Core/Smarty/plugins/function.help.php
Labels: master

#29852 Use getters & setters to interact with Smarty properties, where possible
  CRM/Core/Smarty.php
Labels: master

#29882 dev/core#5123: Membership Dashboard not shown
  CRM/Member/BAO/Membership.php
Labels: master, merge on pass

#29869 Additional Payments form: Use submitted trxn_id if payment result doesn't exist
  CRM/Contribute/Form/AdditionalPayment.php
Labels: master, merge ready

#29888 Fix master only regression - email showing as not available, help crashing Smarty on new contribution page
  CRM/Contribute/Form/Contribution.php
  templates/CRM/Contact/Form/Task/Email.tpl
  templates/CRM/Contribute/Form/AdditionalPayment.tpl
  templates/CRM/Contribute/Form/Contribution.tpl
  templates/CRM/Contribute/Form/Task/Invoice.tpl
  templates/CRM/Contribute/Form/Task/PDF.tpl
  templates/CRM/Event/Form/EventFees.tpl
  templates/CRM/Event/Form/ParticipantFeeSelection.tpl
  templates/CRM/Member/Form/Membership.tpl
  templates/CRM/Member/Form/MembershipRenewal.tpl
  templates/CRM/Pledge/Form/Pledge.tpl
Labels: master

#29894 Fix wrong function in error message
  CRM/Contribute/Form/ContributeFormTrait.php
Labels: master

#29891 (dev/translation#85) CiviMail/CiviCase - Fix string loading (5.73-rc)
  ext/civi_case/ang/crmCaseType.js
  ext/civi_mail/ang/crmMailing/BlockPreview.js
  ext/civi_mail/ang/crmMailing/BlockReview.js
  ext/civi_mail/ang/crmMailing/EditMailingCtrl.js
  ext/civi_mail/ang/crmMailing/EditRecipCtrl.js
  ext/civi_mail/ang/crmMailing/EditRecipOptionsDialogCtrl.js
  ext/civi_mail/ang/crmMailing/EmailAddrCtrl.js
  ext/civi_mail/ang/crmMailing/EmailBodyCtrl.js
  ext/civi_mail/ang/crmMailing/MsgTemplateCtrl.js
  ext/civi_mail/ang/crmMailing/PreviewComponentCtrl.js
  ext/civi_mail/ang/crmMailing/PreviewComponentDialogCtrl.js
  ext/civi_mail/ang/crmMailing/PreviewMailingDialogCtrl.js
  ext/civi_mail/ang/crmMailing/PreviewRecipCtrl.js
  ext/civi_mail/ang/crmMailing/SaveMsgTemplateDialogCtrl.js
  ext/civi_mail/ang/crmMailing/services.js
  ext/civi_mail/ang/crmMailingAB/BlockMailing.js
  ext/civi_mail/ang/crmMailingAB/BlockSetup.js
  ext/civi_mail/ang/crmMailingAB/EditCtrl.js
  ext/civi_mail/ang/crmMailingAB/ListCtrl.js
  ext/civi_mail/ang/crmMailingAB/ReportCtrl.js
  ext/civi_mail/ang/crmMailingAB/Slider.js
  ext/civi_mail/ang/crmMailingAB/WinnerDialogCtrl.js
Labels: merge ready, 5.73

#29890 (dev/translation#85) CiviMail/CiviCase - Fix string loading (5.72-stable)
  ext/civi_case/ang/crmCaseType.js
  ext/civi_mail/ang/crmMailing/BlockPreview.js
  ext/civi_mail/ang/crmMailing/BlockReview.js
  ext/civi_mail/ang/crmMailing/EditMailingCtrl.js
  ext/civi_mail/ang/crmMailing/EditRecipCtrl.js
  ext/civi_mail/ang/crmMailing/EditRecipOptionsDialogCtrl.js
  ext/civi_mail/ang/crmMailing/EmailAddrCtrl.js
  ext/civi_mail/ang/crmMailing/EmailBodyCtrl.js
  ext/civi_mail/ang/crmMailing/MsgTemplateCtrl.js
  ext/civi_mail/ang/crmMailing/PreviewComponentCtrl.js
  ext/civi_mail/ang/crmMailing/PreviewComponentDialogCtrl.js
  ext/civi_mail/ang/crmMailing/PreviewMailingDialogCtrl.js
  ext/civi_mail/ang/crmMailing/PreviewRecipCtrl.js
  ext/civi_mail/ang/crmMailing/SaveMsgTemplateDialogCtrl.js
  ext/civi_mail/ang/crmMailing/services.js
  ext/civi_mail/ang/crmMailingAB/BlockMailing.js
  ext/civi_mail/ang/crmMailingAB/BlockSetup.js
  ext/civi_mail/ang/crmMailingAB/EditCtrl.js
  ext/civi_mail/ang/crmMailingAB/ListCtrl.js
  ext/civi_mail/ang/crmMailingAB/ReportCtrl.js
  ext/civi_mail/ang/crmMailingAB/Slider.js
  ext/civi_mail/ang/crmMailingAB/WinnerDialogCtrl.js
Labels: merge ready, 5.72

#29898 Move logic from tpl to php layer (extension page)
  CRM/Admin/Page/Extensions.php
  templates/CRM/Admin/Page/Extensions/Main.tpl
Labels: merge on pass, 5.73

#29902 5.73 to master
  CRM/Admin/Page/Extensions.php
  ext/civi_case/ang/crmCaseType.js
  ext/civi_mail/ang/crmMailing/BlockPreview.js
  ext/civi_mail/ang/crmMailing/BlockReview.js
  ext/civi_mail/ang/crmMailing/EditMailingCtrl.js
  ext/civi_mail/ang/crmMailing/EditRecipCtrl.js
  ext/civi_mail/ang/crmMailing/EditRecipOptionsDialogCtrl.js
  ext/civi_mail/ang/crmMailing/EmailAddrCtrl.js
  ext/civi_mail/ang/crmMailing/EmailBodyCtrl.js
  ext/civi_mail/ang/crmMailing/MsgTemplateCtrl.js
  ext/civi_mail/ang/crmMailing/PreviewComponentCtrl.js
  ext/civi_mail/ang/crmMailing/PreviewComponentDialogCtrl.js
  ext/civi_mail/ang/crmMailing/PreviewMailingDialogCtrl.js
  ext/civi_mail/ang/crmMailing/PreviewRecipCtrl.js
  ext/civi_mail/ang/crmMailing/SaveMsgTemplateDialogCtrl.js
  ext/civi_mail/ang/crmMailing/services.js
  ext/civi_mail/ang/crmMailingAB/BlockMailing.js
  ext/civi_mail/ang/crmMailingAB/BlockSetup.js
  ext/civi_mail/ang/crmMailingAB/EditCtrl.js
  ext/civi_mail/ang/crmMailingAB/ListCtrl.js
  ext/civi_mail/ang/crmMailingAB/ReportCtrl.js
  ext/civi_mail/ang/crmMailingAB/Slider.js
  ext/civi_mail/ang/crmMailingAB/WinnerDialogCtrl.js
  templates/CRM/Admin/Page/Extensions/Main.tpl
Labels: master

#29901 avoid deprecation notice if header is null
  CRM/Report/Utils/Report.php
Labels: master

#29899 [NFC] APIv4 - Add documentation comments to addJoin() function
  Civi/Api4/Generic/DAOGetAction.php
Labels: master

#29906 Fix test to use full form flow
  tests/phpunit/CRM/Member/Form/MembershipTest.php
Labels: master

#29900 Fix Event register form to call buildAmount exactly once
  CRM/Event/Form/Registration.php
Labels: 5.73

#29911 dev/core#5130 - Don't load smarty2's own plugins if running smarty3/4
  CRM/Core/Smarty.php
Labels: 5.73

#29910 5.73
  CRM/Core/Smarty.php
  CRM/Event/Form/Registration.php
Labels: master

#29915 Fix some tests to not rely on natural sort (implicit id)
  tests/phpunit/api/v3/PaymentTest.php
Labels: master

#29917 distmaker - Add `iframe` and `oembed` (5.73-rc)
  distmaker/core-ext.txt
Labels: 5.73

#29918 distmaker - Add `iframe` and `oembed` (5.72-stable)
  distmaker/core-ext.txt
Labels: 5.72

#29920 5.72.1 - Set version. Add notes.
  ext/afform/admin/info.xml
  ext/afform/core/info.xml
  ext/afform/html/info.xml
  ext/afform/mock/info.xml
  ext/authx/info.xml
  ext/civi_campaign/info.xml
  ext/civi_case/info.xml
  ext/civi_contribute/info.xml
  ext/civi_event/info.xml
  ext/civi_mail/info.xml
  ext/civi_member/info.xml
  ext/civi_pledge/info.xml
  ext/civi_report/info.xml
  ext/civicrm_admin_ui/info.xml
  ext/civicrm_search_ui/info.xml
  ext/civigrant/info.xml
  ext/civiimport/info.xml
  ext/ckeditor4/info.xml
  ext/contributioncancelactions/info.xml
  ext/elavon/info.xml
  ext/eventcart/info.xml
  ext/ewaysingle/info.xml
  ext/financialacls/info.xml
  ext/flexmailer/info.xml
  ext/greenwich/info.xml
  ext/iframe/info.xml
  ext/legacycustomsearches/info.xml
  ext/message_admin/info.xml
  ext/oauth-client/info.xml
  ext/oembed/info.xml
  ext/payflowpro/info.xml
  ext/recaptcha/info.xml
  ext/scheduled_communications/info.xml
  ext/search_kit/info.xml
  ext/sequentialcreditnotes/info.xml
  ext/standaloneusers/info.xml
  ext/user_dashboard/info.xml
  js/version.json
  release-notes.md
  release-notes/5.72.1.md
  sql/civicrm_generated.mysql
  sql/test_data_second_domain.mysql
  xml/version.xml
Labels: 5.72

#29923 dev/core#5136 - errors in .hlp files that contain php functions
  templates/CRM/Core/Form/RecurringEntity.hlp
  templates/CRM/Core/Form/RecurringEntity.tpl
Labels: 5.73

#29924 5.73 to master
  distmaker/core-ext.txt
  templates/CRM/Core/Form/RecurringEntity.hlp
  templates/CRM/Core/Form/RecurringEntity.tpl
Labels: master

#29862 Consolidate some of the subtype wrangling code in dedupe finder
  CRM/Dedupe/Finder.php
Labels: master

#29897 Update tests to orderBy amount rather than rely on id order
  tests/phpunit/CRM/Contribute/BAO/ContributionTest.php
Labels: master

#29925 UtilsArray - Refactor out deprecated value() in array assignments
  CRM/Contact/BAO/Group.php
  CRM/Contribute/Form/Contribution/Main.php
  CRM/Contribute/Form/ContributionBase.php
  CRM/Contribute/Form/ContributionPage.php
  CRM/Event/Form/ManageEvent.php
  CRM/Event/Form/Registration/Register.php
  CRM/Price/BAO/PriceField.php
  CRM/Price/BAO/PriceFieldValue.php
  CRM/Price/Form/Field.php
  CRM/Report/Form.php
  CRM/Utils/Money.php
  api/v3/Contribution.php
  ext/eventcart/CRM/Event/Cart/Form/Cart.php
  ext/eventcart/CRM/Event/Cart/Form/Checkout/Payment.php
Labels: master

#29905 Remove deprecated functions that were on their final notice
  CRM/Mailing/BAO/Mailing.php
Labels: master

#29926 (dev/core#4919) Prefer new versions of PHPGitIgnore / DownloadsPlugin
  composer.json
  composer.lock
Labels: merge ready, 5.73

#29930 [REF] Use standard DeleteMessage functionality from EntityFormTrait f…
  CRM/Admin/Form/Options.php
  templates/CRM/Admin/Form/Options.tpl
Labels: master

#29931 5.73
  composer.json
  composer.lock
Labels: master

#29903 Fix test to use full form flow
  tests/phpunit/CRM/Contribute/Form/ContributionTest.php
Labels: master

#29907 Fix test to test form, not a deprecated function
  CRM/Member/Form/Membership.php
  ext/financialacls/tests/phpunit/Civi/Financialacls/BuildAmountHookTest.php
Labels: master

#29929 Add support for saving custom data on option values
  CRM/Admin/Form/Options.php
  CRM/Core/BAO/OptionValue.php
  templates/CRM/Admin/Form/Options.tpl
Labels: master, merge on pass

#29933 [REF] Refactor out deprecated CRM_Utils_Array from some BAO classes
  CRM/Core/BAO/Block.php
  CRM/Core/BAO/Country.php
  CRM/Core/BAO/LabelFormat.php
  CRM/Core/BAO/Navigation.php
  CRM/Core/BAO/PaperSize.php
  CRM/Core/BAO/PdfFormat.php
  CRM/Core/BAO/UFMatch.php
Labels: master

#29932 [REF] Refactor out deprecated CRM_Utils_Array from UFGroup class
  CRM/Core/BAO/UFField.php
  CRM/Core/BAO/UFGroup.php
Labels: master

#29935 [REF] Autocleanup - Remove redundant conditions
  CRM/Activity/Selector/Search.php
  CRM/Admin/Page/AJAX.php
  CRM/Campaign/BAO/Survey.php
  CRM/Campaign/Page/AJAX.php
  CRM/Case/ManagedEntities.php
  CRM/Case/Selector/Search.php
  CRM/Contact/Form/Merge.php
  CRM/Contact/Form/Task/AddToParentClass.php
  CRM/Contact/Selector.php
  CRM/Contribute/BAO/Contribution.php
  CRM/Contribute/Selector/Search.php
  CRM/Core/BAO/ActionSchedule.php
  CRM/Core/Form.php
  CRM/Core/I18n.php
  CRM/Core/IDS.php
  CRM/Core/Payment/PayPalImpl.php
  CRM/Event/Form/Registration.php
  CRM/Event/Selector/Search.php
  CRM/Mailing/BAO/Mailing.php
  CRM/Mailing/Event/BAO/MailingEventOpened.php
  CRM/Mailing/Event/BAO/MailingEventUnsubscribe.php
  CRM/Mailing/Selector/Search.php
  CRM/Member/Selector/Search.php
  CRM/PCP/Form/Campaign.php
  CRM/PCP/Page/PCP.php
  CRM/Pledge/Selector/Search.php
  CRM/Profile/Selector/Listings.php
  CRM/Report/Form.php
  CRM/Utils/Mail/EmailProcessor.php
  CRM/Utils/SQL/TempTable.php
  CRM/Utils/Schema.php
  CRM/Utils/Time.php
Labels: master

#29934 PHP8 - Fix wordReplacement function to always return an array
  CRM/Core/BAO/WordReplacement.php
Labels: master

#29937 Fold function back into only caller
  CRM/Member/Form/Membership.php
  CRM/Price/BAO/PriceSet.php
Labels: master

#29919 Afform - enable autocomplete id filter on search forms
  ext/afform/admin/Civi/AfformAdmin/AfformAdminMeta.php
  ext/afform/admin/ang/afGuiEditor/elements/afGuiField.component.js
  ext/afform/core/Civi/Afform/FormDataModel.php
Labels: master

#29567 SMS Provider searchkit admin ui
  CRM/SMS/Form/Provider.php
  ext/civicrm_admin_ui/ang/afsearchSMSProvider.aff.html
  ext/civicrm_admin_ui/ang/afsearchSMSProvider.aff.php
  ext/civicrm_admin_ui/managed/SavedSearch_SMS_Provider.mgd.php
Labels: master, merge ready

#29909 Switch default smarty for localhost, demo to Smarty5
  templates/CRM/common/civicrm.settings.php.template
Labels: master, merge on pass

#29938 don't try to load smarty2 plugins when not smarty2
  CRM/Core/Smarty.php
Labels: 5.72

#29913 Further cleanup on arrays in payment create.
  CRM/Financial/BAO/Payment.php
Labels: master

#29942 AdminUI - Remove redundant conditionals
  ext/civicrm_admin_ui/managed/SavedSearch_SMS_Provider.mgd.php
Labels: master

#29928 (dev/core#2994) IFrame Connector - Add support for Backdrop
  ext/iframe/Civi/Iframe/EntryPoint/Backdrop.php
Labels: master

#29940 Permissions - Allow hooks/extensions to declare implied permissions
  CRM/Core/Permission.php
  CRM/Core/Permission/Base.php
  Civi/Api4/Generic/Traits/SavedSearchInspectorTrait.php
  ext/afform/admin/ang/afAdminFormSubmissionList.aff.php
  ext/afform/admin/managed/Navigation_afform_admin.mgd.php
  ext/afform/admin/xml/Menu/afform_admin.xml
  ext/afform/core/Civi/Api4/Afform.php
  ext/afform/core/Civi/Api4/AfformBehavior.php
  ext/afform/core/Civi/Api4/AfformSubmission.php
  ext/afform/core/Civi/Api4/Subscriber/AfformAutocompleteSubscriber.php
  ext/afform/core/afform.php
  ext/search_kit/CRM/Search/BAO/SearchDisplay.php
  ext/search_kit/Civi/Api4/SKEntity.php
  ext/search_kit/Civi/Api4/SearchDisplay.php
  ext/search_kit/Civi/Api4/SearchSegment.php
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdmin.component.js
  ext/search_kit/ang/crmSearchAdmin/searchListing/crmSearchAdminSearchListing.component.js
  ext/search_kit/managed/Navigation_search_kit.mgd.php
  ext/search_kit/search_kit.php
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/SearchRunTest.php
Labels: master, has-test

#29943 Switch function to apiv4, minor cleanup
  CRM/Contribute/BAO/Contribution.php
Labels: master, merge on pass

#29939 Joomla: fixes broken mobile menu and a small regression.
  css/joomla.css
  css/menubar-joomla.css
Labels: merge ready, 5.73

#29949 5.73 to master
  css/joomla.css
  css/menubar-joomla.css
Labels: master

#29945 Standalone - Add permission implications
  ext/standaloneusers/standaloneusers.php
Labels: master, merge on pass

#29944 Fold function back into the main scope, simplify, use apiv4
  CRM/Financial/BAO/Payment.php
Labels: master

#29951 Unravel variable variables
  CRM/Contact/BAO/Individual.php
Labels: master, merge on pass

#29952 Fix some CRM_Utils_array to ... not be
  CRM/Contact/BAO/Individual.php
Labels: master, merge on pass

#29955 5.73.0 release notes initial run
  release-notes.md
  release-notes/5.73.0.md
Labels: 5.73

#29953 Remove a few more variable variables
  CRM/Contact/BAO/Individual.php
Labels: master, merge on pass

#29946 add missing cms: prefix to permission check
  CRM/Profile/Form.php
  CRM/Profile/Page/Dynamic.php
Labels: master

#29745 SearchKit - Add conditional rule for membershipStatus links
  ext/civi_member/Civi/Api4/Service/Links/MembershipStatusLinksProvider.php
Labels: master

#29747 SearchKit - Move search tasks to their respective component-extensions
  ext/civi_contribute/Civi/Api4/Service/ContributionTasksProvider.php
  ext/civi_mail/Civi/Api4/Service/MailTasksProvider.php
  ext/search_kit/Civi/Api4/Action/SearchDisplay/GetSearchTasks.php
Labels: master

#29947 Fix calculation on amount allocation for tax line to happen in main loop
  CRM/Financial/BAO/Payment.php
Labels: master

#29959 [NFC] UtilsCheck - Improve docblock comments
  CRM/Utils/Check/Message.php
Labels: master

#29958 Drupal 10 - Fix breadcrumbs with id tokens
  CRM/Utils/System/Drupal8.php
Labels: master

#29965 Fix broken user account profile tab in drupal 10
  CRM/Core/Permission/Drupal8.php
Labels: master

#29941 Remove always true if from previously shared code
  CRM/Member/Form/Membership.php
Labels: master

#29895 Standalone - ensure id value is an int for comparison check when changing password
  ext/standaloneusers/Civi/Api4/Action/User/WriteTrait.php
Labels: master

#29796 Remove deprecated function
  CRM/Contribute/BAO/Contribution.php
Labels: master

#29896 dev/core#5125 Standalone cms permissions are civi permissions
  CRM/Core/Permission/Backdrop.php
  CRM/Core/Permission/Base.php
  CRM/Core/Permission/Drupal.php
  CRM/Core/Permission/Drupal8.php
  CRM/Core/Permission/List.php
  CRM/Core/Permission/Standalone.php
  CRM/Core/Permission/WordPress.php
  ext/standaloneusers/standaloneusers.php
  ext/standaloneusers/tests/phpunit/Civi/Api4/Action/UserTest.php
  setup/plugins/init/StandaloneUsers.civi-setup.php
Labels: master, merge on pass

#29968 Smarty3/4 compatibility for Address.tpl
  templates/CRM/Admin/Form/Preferences/Address.hlp
  templates/CRM/Admin/Form/Preferences/Address.tpl
Labels: master

#29969 Bump TCPDF to 6.7.4
  composer.json
  composer.lock
Labels: 5.73

#29972 [php8] Update compile-plugin to v0.20
  composer.lock
Labels: merge on pass, 5.73

#29973 backport 29969 (tcpdf)
  composer.json
  composer.lock
Labels: 5.72

#29936 Improve loading of PriceField metadata on Contribution Form to avoid notice
  CRM/Contribute/Form/Contribution.php
Labels: master

#29975 5.73
  composer.lock
Labels: master

#29976 Assign highlighted fields as json
  CRM/Contact/Import/Form/MapField.php
  CRM/Import/Form/MapField.php
  templates/CRM/common/highLightImport.tpl
Labels: master

#29832 dev/core#5094 Afform - Fix prefill of one entity overwriting 'current user'
  ext/afform/core/Civi/Afform/Behavior/ContactAutofill.php
Labels: master

#29982 dev/core#5147 Fix master-only regression on selecting price set
  CRM/Member/Form.php
  CRM/Member/Form/Membership.php
Labels: master

#29977 Add expires_date as an editable field to "my imports" and "all imports" SK
  ext/civiimport/Managed/UserJobSearches.mgd.php
  ext/civiimport/ang/afsearchMyImports.aff.html
Labels: master

#29983 dev/core#5149 - Fix customGroup function overwriting extends data
  CRM/Core/BAO/CustomGroup.php
  tests/phpunit/api/v4/Custom/CustomGroupTest.php
Labels: has-test, 5.73

#29987 5.73 to master
  CRM/Core/BAO/CustomGroup.php
  tests/phpunit/api/v4/Custom/CustomGroupTest.php
Labels: master

#29985 [REF] CustomGroup BAO function cleanup
  CRM/Core/BAO/CustomGroup.php
Labels: master

#29974 Fix comments
  CRM/PCP/StateMachine/PCP.php
Labels: master

#29980 Remove unused properties
  CRM/Import/Parser.php
Labels: master

#29887 Call hooks when recording mailing open
  CRM/Mailing/Event/BAO/MailingEventOpened.php
Labels: master

#29966 Switch from apv3 to apiv4 within Payment.create
  CRM/Financial/BAO/Payment.php
Labels: master

#29964 Use Apiv4 rather than funky function to get line items
  CRM/Financial/BAO/Payment.php
  CRM/Price/BAO/LineItem.php
Labels: master

#29970 [NFC] space error in a ts in the event receipt template
  CRM/Upgrade/Incremental/MessageTemplates.php
  sql/civicrm_generated.mysql
  tests/phpunit/CRM/Core/Payment/BaseIPNTest.php
  tests/phpunit/CRM/Event/Form/Registration/ConfirmTest.php
  xml/templates/message_templates/event_online_receipt_html.tpl
Labels: master, merge on pass

#29986 Afform - Allow 'Current Date' as a value option for date fields
  ext/afform/admin/ang/afGuiEditor.css
  ext/afform/admin/ang/afGuiEditor/afGuiEntity.component.js
  ext/afform/admin/ang/afGuiEditor/afGuiEntity.html
Labels: master

#29990 Use loaded balance_amount
  CRM/Financial/BAO/Payment.php
Labels: master

#29988 SQL Escape - Reconcile CRM_Core_DAO::escapeString() and CRM_Core_I18n::escape()
  CRM/Core/DAO.php
  CRM/Core/I18n.php
  CRM/Utils/SQL/EscapeStringTrait.php
  Civi/Test.php
  setup/plugins/installDatabase/BootstrapCivi.civi-setup.php
  setup/plugins/installDatabase/Preboot.civi-setup.php
Labels: master, merge on pass

#29927 SearchKit - Fix SearchSegment state/province
  ext/search_kit/ang/crmSearchAdmin/searchSegment/crmSearchAdminSegment.component.js
  ext/search_kit/ang/crmSearchAdmin/searchSegment/crmSearchAdminSegment.html
Labels: master

#29984 SampleData - Add missing customGroup weights
  sql/civicrm_sample_custom_data.mysql
Labels: master

#29950 OAuth - Add permission implications
  ext/oauth-client/CRM/OAuth/BAO/OAuthContactToken.php
  ext/oauth-client/Civi/Api4/OAuthContactToken.php
  ext/oauth-client/oauth_client.php
Labels: master, merge ready

#29885 Angular Datepicker - Default to +-100 year range
  ang/crmUi.js
  ext/search_kit/ang/crmSearchTasks/crmSearchInput/date.html
Labels: master, merge ready

#29978 Reduce import controller boiler plate
  CRM/Contact/Import/Controller.php
  CRM/Contribute/Import/Controller.php
  CRM/Core/Invoke.php
  CRM/Core/xml/Menu/Import.xml
  CRM/Custom/Import/Controller.php
  CRM/Event/Import/Controller.php
  CRM/Event/xml/Menu/Event.xml
  CRM/Import/Controller.php
  CRM/Import/StateMachine.php
  CRM/Member/Import/Controller.php
  CRM/Member/xml/Menu/Member.xml
  Civi/Test/FormWrapper.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: master

#29997 Fix regen - resource cache is sometimes now cleared when cms is not bootstrapped
  CRM/Utils/System/Backdrop.php
  CRM/Utils/System/Drupal8.php
  CRM/Utils/System/DrupalBase.php
Labels: 5.73

#29999 no wysiwyg editor for system worklow messages (dev/core#5154)
  CRM/Admin/Form/MessageTemplates.php
Labels: master

#30001 backport 29997
  CRM/Utils/System/Backdrop.php
  CRM/Utils/System/Drupal8.php
  CRM/Utils/System/DrupalBase.php
Labels: merge on pass, 5.72

#29998 regen.sh - Fix warnings on PHP 8.2
  CRM/Core/CodeGen/GenerateData.php
Labels: merge on pass, 5.73

#30002 5.73
  CRM/Core/CodeGen/GenerateData.php
Labels: master

#29989 Move the code to generate payableItems back into getPayableItems
  CRM/Financial/BAO/Payment.php
Labels: master

#29981 Update UserJob status & date fields as it progresses
  CRM/Core/BAO/UserJob.php
  CRM/Import/Parser.php
Labels: master

#30005 Switch to already loaded paid_amount
  CRM/Financial/BAO/Payment.php
Labels: master, merge on pass

#30006 Fix function to use apiv4
  CRM/Financial/BAO/Payment.php
Labels: master, merge on pass

#30003 Stop setting now-already-set id
  CRM/Financial/BAO/Payment.php
Labels: master, merge on pass

#30008 Clean up some no-longer-used properties
  CRM/Contribute/Import/Parser/Contribution.php
  CRM/Event/Import/Parser/Participant.php
Labels: master

#29994 Fix related memberships
  ext/civicrm_admin_ui/managed/SavedSearch_Contact_Summary_Memberships.mgd.php
  ext/search_kit/Civi/Search/Admin.php
Labels: 5.73

#30013 DAO - Add getter function for labelField
  CRM/Core/CRM/Core/DAO/Base.php
  CRM/Core/DAO.php
  CRM/Logging/ReportDetail.php
  Civi/Api4/Generic/AbstractEntity.php
  Civi/Schema/LegacySqlEntityMetadata.php
Labels: master

#30009 Fix double passing of same params to private function
  CRM/Contribute/Import/Parser/Contribution.php
Labels: master

#30015 dev/core#5158 fix crm database prefix
  CRM/Utils/System/Backdrop.php
Labels: master, merge on pass

#30010 [REF] Payment.create - Combine the 2 calls to LineItem.get
  CRM/Financial/BAO/Payment.php
Labels: master

#30016 (dev/core#4999) mixin - Fix PHP syntax for backportability
  mixin/lib/civimix-schema/src/SqlGenerator.php
Labels: master, merge on pass

#30021 (dev/core#4999) AutomaticUpgrader - Fix delegation for queued upgrade tasks
  mixin/lib/civimix-schema/src/AutomaticUpgrader.php
Labels: master, merge on pass

#30018 dev/core#5159 SearchKit - Fix broken NOT CONTAINS operator
  Civi/Api4/Query/Api4Query.php
  tests/phpunit/api/v4/Entity/ParticipantTest.php
Labels: merge ready, sig:regression, 5.73

#30019 SearchKit - Fix broken NOT CONTAINS operator
  Civi/Api4/Query/Api4Query.php
  tests/phpunit/api/v4/Entity/ParticipantTest.php
Labels: sig:regression, 5.72, port

#30020 [NFC] 5.73 release notes first pass
  contributor-key.yml
  release-notes/5.73.0.md
Labels: 5.73

#30024 5.73
  Civi/Api4/Query/Api4Query.php
  contributor-key.yml
  ext/civicrm_admin_ui/managed/SavedSearch_Contact_Summary_Memberships.mgd.php
  ext/search_kit/Civi/Search/Admin.php
  release-notes/5.73.0.md
  tests/phpunit/api/v4/Entity/ParticipantTest.php
Labels: master

#30012 AdminUI - Fix missing translation
  ext/civicrm_admin_ui/managed/SavedSearch_Contact_Summary_Memberships.mgd.php
  ext/civicrm_search_ui/managed/SavedSearch_Find_Memberships.mgd.php
Labels: 5.73

#29705 Clean up smarty notices on pledge view
  CRM/Pledge/Form/PledgeView.php
  templates/CRM/Pledge/Form/PledgeView.tpl
Labels: master, merge ready

#30026 dev/core#4846 Fix call to deprecated function
  CRM/Mailing/Form/Component.php
Labels: master

#30027 Update tcpdf to 6.7.5
  composer.lock
Labels: 5.73

#30028 backport 30027
  composer.lock
Labels: 5.72

#30032 Remove some unreachable legacy code
  CRM/Event/Import/Parser/Participant.php
Labels: master, merge on pass

#30033 Remove function deprecated in 2022, after universe search
  CRM/Activity/BAO/Activity.php
Labels: master, merge on pass
