Repository civicrm/civicrm-core, pull requests merged in 2024-05, with the labels that each got.

#30090 Remove deprecated function
  CRM/Member/BAO/Membership.php
Labels: master

#30098 5.72.3 - Add notes. Set version.
  ext/afform/admin/info.xml
  ext/afform/core/info.xml
  ext/afform/html/info.xml
  ext/afform/mock/info.xml
  ext/authx/info.xml
  ext/civi_campaign/info.xml
  ext/civi_case/info.xml
  ext/civi_contribute/info.xml
  ext/civi_event/info.xml
  ext/civi_mail/info.xml
  ext/civi_member/info.xml
  ext/civi_pledge/info.xml
  ext/civi_report/info.xml
  ext/civicrm_admin_ui/info.xml
  ext/civicrm_search_ui/info.xml
  ext/civigrant/info.xml
  ext/civiimport/info.xml
  ext/ckeditor4/info.xml
  ext/contributioncancelactions/info.xml
  ext/elavon/info.xml
  ext/eventcart/info.xml
  ext/ewaysingle/info.xml
  ext/financialacls/info.xml
  ext/flexmailer/info.xml
  ext/greenwich/info.xml
  ext/iframe/info.xml
  ext/legacycustomsearches/info.xml
  ext/message_admin/info.xml
  ext/oauth-client/info.xml
  ext/oembed/info.xml
  ext/payflowpro/info.xml
  ext/recaptcha/info.xml
  ext/scheduled_communications/info.xml
  ext/search_kit/info.xml
  ext/sequentialcreditnotes/info.xml
  ext/standaloneusers/info.xml
  ext/user_dashboard/info.xml
  js/version.json
  release-notes.md
  release-notes/5.72.3.md
  sql/civicrm_generated.mysql
  sql/test_data_second_domain.mysql
  xml/version.xml
Labels: 5.72

#30062 Partially convert recur updateOnNewPayment to API4
  CRM/Contribute/BAO/Contribution.php
  CRM/Contribute/BAO/ContributionRecur.php
Labels: master

#30095 CRM_Utils_Cache_Tiered - Fix test failure on Standalone
  CRM/Utils/Cache/Tiered.php
Labels: master

#30100 dev/core#5118 Add support for trailing conditional bracket
  CRM/Contact/BAO/Individual.php
  Civi/Token/TokenCompatSubscriber.php
  tests/phpunit/CRM/Contact/BAO/IndividualTest.php
Labels: 5.73

#30101 Port change already made in master
  tests/phpunit/CRM/Contribute/Form/Task/PDFLetterCommonTest.php
Labels: merge on pass, 5.73

#30102 TokenCompatSubscriber - Consolidate chained regex. Use more singular …
  Civi/Token/TokenCompatSubscriber.php
Labels: merge on pass, 5.73

#30103 Fix customDataBlock to convert false to 'false'
  templates/CRM/common/customDataBlock.tpl
Labels: 5.73

#30097 Sort by register_date Contact Summary Events tab with Admin UI
  ext/civicrm_admin_ui/managed/SavedSearch_Contact_Summary_Events.mgd.php
Labels: 5.73

#30079 Fix notice on membership form by loading price field information in standardised way
  CRM/Member/Form/Membership.php
Labels: master

#30110 5.73 to master (conflicts in test resolved)
  Civi/Token/TokenCompatSubscriber.php
  ext/civicrm_admin_ui/managed/SavedSearch_Contact_Summary_Events.mgd.php
  templates/CRM/common/customDataBlock.tpl
  tests/phpunit/CRM/Contact/BAO/IndividualTest.php
Labels: master

#30108 Assign weights on membership tab
  CRM/Member/Page/Tab.php
Labels: master

#30107 dev/core#5165, dev/core#5181 - backport 30053
  CRM/Contact/Form/Task/Delete.php
Labels: 5.73

#30096 ensure civisms adds SMS delivery activity
  CRM/Mailing/BAO/Mailing.php
  CRM/Mailing/BAO/SMSJob.php
  CRM/Mailing/Service/ListUnsubscribe.php
  tests/phpunit/CRM/Contact/Form/Task/SMSCommonTest.php
  tests/phpunit/CRM/SMS/ProviderTest.php
  tests/phpunit/CiviTest/CiviTestSMSProvider.php
Labels: 5.73

#30004 dev/core#5126 - Fix searchKit crash with smarty rewrite
  ext/search_kit/Civi/Api4/Action/SearchDisplay/AbstractRunAction.php
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/SearchRunTest.php
Labels: has-test, sig:regression, 5.73

#30111 (dev/core#5183) Search Tasks - Actions incorrectly apply to all records in database
  templates/CRM/Contact/Form/Search/AdvancedCriteria.tpl
Labels: 5.73

#30117 dev/user-interface#72 remove html that got superceded
  templates/CRM/Financial/Form/FinancialAccount.tpl
Labels: merge on pass, 5.73

#30082 Fix old merge conflict mis-resolution, superficial tidy up
  CRM/Batch/Form/Entry.php
Labels: master

#30089 support 'current user' as value in FB
  Civi/Api4/Generic/Traits/DAOActionTrait.php
Labels: master

#30119 dev/core#5145 Fix regression deleting contact images
  CRM/Contact/BAO/Contact.php
Labels: merge on pass, 5.73

#30120 Merge 5.73 to master
  CRM/Contact/BAO/Contact.php
  ext/search_kit/Civi/Api4/Action/SearchDisplay/AbstractRunAction.php
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/SearchRunTest.php
  release-notes.md
  release-notes/5.73.0.md
  templates/CRM/Contact/Form/Search/AdvancedCriteria.tpl
  templates/CRM/Financial/Form/FinancialAccount.tpl
Labels: master

#30088 Move some CRM tests to use apiv4
  tests/phpunit/CRM/ACL/ListTest.php
  tests/phpunit/CRM/Activity/BAO/ActivityAssignmentTest.php
  tests/phpunit/CRM/Activity/BAO/ActivityTest.php
  tests/phpunit/CRM/Activity/BAO/ActivityTypeTest.php
  tests/phpunit/CRM/Activity/Form/ActivityTest.php
  tests/phpunit/CRM/Activity/Form/ActivityViewTest.php
  tests/phpunit/CRM/Activity/Form/SearchTest.php
  tests/phpunit/CRM/Activity/Form/Task/PDFTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: master, merge on pass

#30104 dev/core#5185 Fix smart group error with deleted custom fields
  CRM/Contact/BAO/Query.php
Labels: merge on pass, 5.74

#30121 Call hooks when recording a trackable URL open
  CRM/Mailing/Event/BAO/MailingEventTrackableURLOpen.php
Labels: master

#30113 Rationalise renewal date in membership renew
  CRM/Member/Form/MembershipRenewal.php
Labels: master

#30114 Stop assigning no-longer used membership template variables
  CRM/Batch/Form/Entry.php
  CRM/Contribute/BAO/Contribution.php
  CRM/Contribute/Form/Contribution/Confirm.php
  CRM/Contribute/Form/Contribution/ThankYou.php
  CRM/Member/Form/Membership.php
  CRM/Member/Form/MembershipRenewal.php
  CRM/Upgrade/Incremental/php/FiveSeventyFive.php
  CRM/Utils/Token.php
Labels: master

#30115 Start using getMembershipValue in offline renewal form
  CRM/Member/Form.php
  CRM/Member/Form/MembershipRenewal.php
  templates/CRM/Member/Form/MembershipRenewal.tpl
Labels: master

#30116 Remove calls to deprecated core function from event cart
  CRM/Contact/BAO/Contact.php
  ext/eventcart/CRM/Event/Cart/BAO/Cart.php
  ext/eventcart/CRM/Event/Cart/BAO/EventInCart.php
  ext/eventcart/CRM/Event/Cart/Form/Cart.php
  ext/eventcart/CRM/Event/Cart/Form/Checkout/ConferenceEvents.php
  ext/eventcart/CRM/Event/Cart/Form/Checkout/ParticipantsAndPrices.php
  ext/eventcart/CRM/Event/Cart/Form/Checkout/Payment.php
  ext/eventcart/CRM/Event/Cart/Form/Checkout/ThankYou.php
  ext/eventcart/CRM/Event/Cart/StateMachine/Checkout.php
Labels: master

#30122 Add getContributionID() function to Confirm form
  CRM/Contribute/Form/Contribution/Confirm.php
Labels: master

#30130 5.74 to master
  CRM/Contact/BAO/Query.php
Labels: master

#30128 Fix smart group error with deleted custom fields
  CRM/Contact/BAO/Query.php
Labels: 5.73

#25636 Populate custom fields URL params when the custom group extends only …
  CRM/Core/BAO/CustomGroup.php
Labels: master, merge ready

#30131 dev/core#5116 - Fix missing language selector for scheduled reminders
  CRM/Admin/Form/ScheduleReminders.php
Labels: sig:regression, 5.74

#30134 5.74
  CRM/Admin/Form/ScheduleReminders.php
Labels: master

#29186 Afform - Format DisplayOnly fields as view value
  Civi/Api4/Utils/CoreUtil.php
  ext/afform/core/Civi/Afform/AfformMetadataInjector.php
  ext/afform/core/Civi/Afform/FormDataModel.php
  ext/afform/core/Civi/Afform/Utils.php
  ext/afform/core/Civi/Api4/Action/Afform/AbstractProcessor.php
  ext/afform/core/Civi/Api4/Action/Afform/Prefill.php
  ext/afform/core/ang/af/afField.component.js
  ext/afform/mock/tests/phpunit/api/v4/Afform/AfformPrefillUsageTest.php
Labels: merge on pass, has-test

#30135 dev/core#5116 - (backport 30131) Fix missing language selector for scheduled reminders
  CRM/Admin/Form/ScheduleReminders.php
Labels: 5.73

#30125 dev/core#5187 - Fix smart group alert for deleted custom fields
  CRM/Utils/Check/Component/Schema.php
Labels: master

#30124 dev/core#5168 Do not block people from confirming free event registrations
  CRM/Event/Form/Registration/Register.php
Labels: 5.74

#30127 Do not block people from confirming free event registrations
  CRM/Event/Form/Registration/Register.php
Labels: 5.73

#30138 5.73.1 - Add notes. Set version.
  ext/afform/admin/info.xml
  ext/afform/core/info.xml
  ext/afform/html/info.xml
  ext/afform/mock/info.xml
  ext/authx/info.xml
  ext/civi_campaign/info.xml
  ext/civi_case/info.xml
  ext/civi_contribute/info.xml
  ext/civi_event/info.xml
  ext/civi_mail/info.xml
  ext/civi_member/info.xml
  ext/civi_pledge/info.xml
  ext/civi_report/info.xml
  ext/civicrm_admin_ui/info.xml
  ext/civicrm_search_ui/info.xml
  ext/civigrant/info.xml
  ext/civiimport/info.xml
  ext/ckeditor4/info.xml
  ext/contributioncancelactions/info.xml
  ext/elavon/info.xml
  ext/eventcart/info.xml
  ext/ewaysingle/info.xml
  ext/financialacls/info.xml
  ext/flexmailer/info.xml
  ext/greenwich/info.xml
  ext/iframe/info.xml
  ext/legacycustomsearches/info.xml
  ext/message_admin/info.xml
  ext/oauth-client/info.xml
  ext/oembed/info.xml
  ext/payflowpro/info.xml
  ext/recaptcha/info.xml
  ext/scheduled_communications/info.xml
  ext/search_kit/info.xml
  ext/sequentialcreditnotes/info.xml
  ext/standaloneusers/info.xml
  ext/user_dashboard/info.xml
  js/version.json
  release-notes.md
  release-notes/5.73.1.md
  sql/civicrm_generated.mysql
  sql/test_data_second_domain.mysql
  xml/version.xml
Labels: 5.73

#30141 (dev/translation#84) LocalizedDataTest - Reduce noise
  tests/phpunit/E2E/Core/LocalizedDataTest.php
Labels: 5.74

#30137 update PermissionTest for Standalone case
  tests/phpunit/E2E/Api4/PermissionTest.php
Labels: master, merge on pass

#30144 5.74
  CRM/Event/Form/Registration/Register.php
  tests/phpunit/E2E/Core/LocalizedDataTest.php
Labels: master

#30142 php8 - Fix undefined class variable notices in report InstanceList
  CRM/Report/Page/InstanceList.php
Labels: master

#30136 Standalone installer - fix admin not getting admin role
  setup/plugins/init/StandaloneUsers.civi-setup.php
Labels: almost merge on pass, 5.74

#30143 dev/core#5141 - Fix non-selectable select2 in 'Clone Report' popup
  CRM/Report/Form/Instance.php
Labels: sig:regression, 5.74

#30145 Authx - Fix stateful logins on D9/D10
  CRM/Utils/System/Drupal8.php
Labels: master

#30147 Fix dev/core#5139 incorrect Date Preferences link
  CRM/Core/xml/Menu/Admin.xml
Labels: sig:regression, 5.74

#30146 5.74
  CRM/Core/xml/Menu/Admin.xml
  CRM/Report/Form/Instance.php
  setup/plugins/init/StandaloneUsers.civi-setup.php
Labels: master

#30148 Smarty 3/4 - Fix prepending extension template directories
  mixin/smarty-v2@1/mixin.php
  mixin/smarty@1/mixin.php
Labels: 5.74

#30149 Add self to contributor list
  contributor-key.yml
Labels: master

#29962 Default Smarty version on new installs to 4
  templates/CRM/common/civicrm.settings.php.template
Labels: master, merge ready, run-extended-tests

#30152 Merge 5.74 to master
  mixin/smarty-v2@1/mixin.php
  mixin/smarty@1/mixin.php
Labels: master

#30151 Smarty 3/4 - Fix prepending extension template directories
  mixin/smarty-v2@1/mixin.php
  mixin/smarty@1/mixin.php
Labels: port, 5.73

#30047 Fold deprecated function back into only caller
  CRM/Event/BAO/Participant.php
  CRM/Event/BAO/Query.php
  tests/phpunit/CRM/Event/BAO/ParticipantTest.php
Labels: master

#30150 Include schema in tarball - so that civicrm can be installed
  distmaker/dists/common.sh
Labels: 5.74

#30030 Remove empty function & the test which is it's only caller
  CRM/Contact/BAO/Contact.php
  tests/phpunit/CRM/Contact/BAO/ContactTest.php
Labels: master

#30123 Fix smarty notice when viewing a participant with no contribution (unpaid)
  templates/CRM/Event/Form/Participant.tpl
Labels: master

#30161 [REF] CiviCampaign code cleanup
  CRM/Campaign/Form/Search.php
  CRM/Campaign/Form/Task/Reserve.php
  CRM/Campaign/Page/Vote.php
  CRM/Contribute/Form/Contribution.php
  CRM/Contribute/Form/ContributionPage/Settings.php
  CRM/Pledge/Form/Pledge.php
Labels: master

#30160 E_NOTICE when viewing a participant with no payment
  templates/CRM/Event/Form/ParticipantView.tpl
Labels: master

#30126 Separate handlePledge back to calling forms, no universe usage
  CRM/Contribute/Form/Contribution.php
  CRM/Contribute/Form/Contribution/Confirm.php
Labels: master

#29380 (dev/core#4984) Display issue on membership view for relationships
  CRM/Member/Form/MembershipView.php
Labels: master

#30167 [REF] DAO - Outside parties should use `getTableName()` instead of `$_tableName`
  CRM/Mailing/Event/BAO/MailingEventUnsubscribe.php
  ext/standaloneusers/CRM/Standaloneusers/BAO/Session.php
Labels: master, merge on pass

#30164 dev/core#5190 Smarty3/4 compatibility
  templates/CRM/Admin/Form/Preferences/Address.hlp
  templates/CRM/Admin/Form/Preferences/Address.tpl
Labels: 5.73

#30168 dev/core#5202 "Submit Credit Card Membership" form does not show Membership Types if the minimum fee is 0.00 and auto renew option is no
  CRM/Member/Form/Membership.php
Labels: master

#30165 dev/core#5070 Fix failure to set is_pay_later on back office
  CRM/Contribute/Form/Contribution.php
  tests/phpunit/CRM/Contribute/Form/ContributionTest.php
Labels: 5.74

#30171 5.74
  CRM/Contribute/Form/Contribution.php
  distmaker/dists/common.sh
  tests/phpunit/CRM/Contribute/Form/ContributionTest.php
Labels: master

#30166 skip custom word replacements check during installer
  CRM/Core/I18n.php
Labels: master, merge on pass

#30159 [REF] Fix Contribution Detail Report add to Group when using custom f…
  CRM/Report/Form/Contribute/Detail.php
Labels: master, merge ready

#30129 ensure shared address is updated in reverse
  CRM/Core/BAO/Address.php
  tests/phpunit/CRM/Core/BAO/AddressTest.php
Labels: master, has-test

#30174 [REF] CRM - Refactor out CRM_Utils_Array::value
  CRM/Core/BAO/Country.php
  CRM/Core/BAO/CustomGroup.php
  CRM/Core/BAO/Dashboard.php
  CRM/Core/BAO/MessageTemplate.php
  CRM/Core/BAO/UFMatch.php
  CRM/Member/BAO/MembershipPayment.php
Labels: master

#30175 [NFC] Oauth - Remove unused boilerplate
  ext/oauth-client/CRM/OAuth/BAO/OAuthClient.php
  ext/oauth-client/CRM/OAuth/BAO/OAuthSysToken.php
  ext/oauth-client/oauth_client.php
Labels: master

#30181 SearchKit - Allow searching for search displays
  ext/search_kit/Civi/Api4/SearchDisplay.php
Labels: master

#30077 Ensure error handler always restored
  CRM/Price/BAO/PriceField.php
  CRM/Utils/String.php
  ext/eventcart/CRM/Event/Cart/Form/Checkout/ParticipantsAndPrices.php
  ext/eventcart/CRM/Event/Cart/Form/Checkout/Payment.php
  tests/phpunit/CRM/Core/Smarty/plugins/HtxtTest.php
Labels: master

#30173 Test clean up, use apiv4 more, considate tracking
  tests/phpunit/CRM/Contribute/Form/ContributionTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/api/v3/ContributionPageTest.php
  tests/phpunit/api/v3/ContributionTest.php
Labels: master

#30185 Fix missing opening <p> tag
  templates/CRM/Contribute/Form/Contribution/Confirm.tpl
Labels: master, merge on pass

#30186 dev/core#1735 Reports: Expose all custom fields, not just the indexed ones
  CRM/Report/Form.php
Labels: master

#30187 CiviReport - Use cached function to get custom fields
  CRM/Report/Form.php
Labels: master, merge on pass

#29813 handle multilingual + advanced logging in a separate db
  CRM/Core/I18n/Schema.php
Labels: master

#30189 Case custom fields no longer appearing on print report
  CRM/Case/XMLProcessor/Report.php
Labels: 5.74

#30190 Similar to 30189 - customgroup::getGroupDetail is case-sensitive now
  CRM/Event/BAO/Event.php
Labels: 5.74

#30158 Use addPluginsDir rather than non-public property
  CRM/Core/Smarty.php
Labels: merge ready, 5.74

#30192 5.74 to master
  CRM/Case/XMLProcessor/Report.php
  CRM/Core/Smarty.php
  CRM/Event/BAO/Event.php
Labels: master

#30193 ScheduledReminders - Fix hiding irrelevant fields
  templates/CRM/Admin/Form/ScheduleReminders.tpl
Labels: master

#30198 [NFC] civicrm.settings.php.template: consistent whitespace
  templates/CRM/common/civicrm.settings.php.template
Labels: master, merge on pass

#30199 Fix rendering default value of autocomplete fields
  CRM/Core/Form/Renderer.php
Labels: sig:regression, 5.74

#30200 5.74
  CRM/Core/Form/Renderer.php
Labels: master

#30191 Regression: Custom field file type not saved on entity
  CRM/Custom/Form/CustomDataTrait.php
Labels: 5.74

#30203 5.73 backport of 30191
  CRM/Custom/Form/CustomDataTrait.php
Labels: 5.73

#30204 dev/core#5176 - Don't purify from_email addresses
  CRM/Admin/Form/Options.php
Labels: 5.74

#30206 Backport of #30204 don't purify email address
  CRM/Admin/Form/Options.php
Labels: 5.73

#30202 5.74
  CRM/Admin/Form/Options.php
  CRM/Custom/Form/CustomDataTrait.php
Labels: master

#30205 Afform - Fix edit links permission for multiple users
  ext/afform/admin/Civi/AfformAdmin/AfformAdminInjector.php
  ext/afform/core/afform.php
  ext/afform/core/ang/afCore.js
Labels: merge ready, 5.74

#30211 Type safety in Standalone currentPath
  CRM/Utils/System/Standalone.php
Labels: master, merge on pass

#30196 dev/core#5208 - Undo change that prevents editing multiple emails on a contact
  CRM/Contact/Form/Contact.php
  CRM/Contact/Form/Edit/Email.php
  CRM/Contact/Form/Location.php
Labels: 5.74

#30197 5.73 backport of 30196
  CRM/Contact/Form/Contact.php
  CRM/Contact/Form/Edit/Email.php
  CRM/Contact/Form/Location.php
Labels: 5.73

#30195 CRM_Admin_Form_MessageTemplates - Fix disabling user message templates via the edit form
  CRM/Admin/Form/MessageTemplates.php
Labels: master, merge on pass

#30213 find financial acl warning amongst other messages
  ext/financialacls/tests/phpunit/Civi/Financialacls/FinancialTypeTest.php
Labels: master, merge on pass

#30212 Fix Standalone core source storage url double slash
  CRM/Utils/System/Standalone.php
Labels: master, merge on pass

#30216 5.73.2 - Add notes. Set version.
  ext/afform/admin/info.xml
  ext/afform/core/info.xml
  ext/afform/html/info.xml
  ext/afform/mock/info.xml
  ext/authx/info.xml
  ext/civi_campaign/info.xml
  ext/civi_case/info.xml
  ext/civi_contribute/info.xml
  ext/civi_event/info.xml
  ext/civi_mail/info.xml
  ext/civi_member/info.xml
  ext/civi_pledge/info.xml
  ext/civi_report/info.xml
  ext/civicrm_admin_ui/info.xml
  ext/civicrm_search_ui/info.xml
  ext/civigrant/info.xml
  ext/civiimport/info.xml
  ext/ckeditor4/info.xml
  ext/contributioncancelactions/info.xml
  ext/elavon/info.xml
  ext/eventcart/info.xml
  ext/ewaysingle/info.xml
  ext/financialacls/info.xml
  ext/flexmailer/info.xml
  ext/greenwich/info.xml
  ext/iframe/info.xml
  ext/legacycustomsearches/info.xml
  ext/message_admin/info.xml
  ext/oauth-client/info.xml
  ext/oembed/info.xml
  ext/payflowpro/info.xml
  ext/recaptcha/info.xml
  ext/scheduled_communications/info.xml
  ext/search_kit/info.xml
  ext/sequentialcreditnotes/info.xml
  ext/standaloneusers/info.xml
  ext/user_dashboard/info.xml
  js/version.json
  release-notes.md
  release-notes/5.73.2.md
  sql/civicrm_generated.mysql
  sql/test_data_second_domain.mysql
  xml/version.xml
Labels: 5.73

#30218 [NFC] Use correct syntax for writing to arrays
  CRM/Event/BAO/ParticipantStatusType.php
  CRM/Utils/File.php
  tests/phpunit/CRM/Core/BAO/MessageTemplateTest.php
Labels: master

#30220 Remove Civi/ActionSchedule/Mapping workaround
  Civi/ActionSchedule/Mapping.php
  deleted-files-list.json
Labels: master, merge on pass

#30221 Delete old placeholder files
  CRM/Contact/Import/Parser.php
  Civi/Api4/Event/Events.php
  Civi/Api4/Event/PostSelectQueryEvent.php
Labels: master, merge on pass

#30217 Fix rendering default value of autocomplete fields
  CRM/Core/Form/Renderer.php
Labels: 5.73

#30215 Fix PHP warnings on contribute confirm when membership is not enabled
  CRM/Contribute/Form/Contribution/Confirm.php
Labels: master

#30223 Use pan_truncation where present on form
  CRM/Contribute/Form/AdditionalPayment.php
Labels: 5.74

#30226 dev/core#5226 Fix cancel contributions when CiviMember not enabled (5.74)
  CRM/Contribute/Form/ContributionRecur.php
Labels: 5.74

#30228 Update deleted files list again
  deleted-files-list.json
Labels: master, merge on pass

#30176 dev/core#5206 Fix additional participant multiple profiles
  CRM/Event/Form/Registration.php
  templates/CRM/Event/Form/Registration/AdditionalParticipant.tpl
Labels: master

#30184 dev/core#5210 Add deceased date to contact reports
  CRM/Report/Form.php
Labels: master, merge on pass

#30232 Remove some unused variables
  CRM/Contribute/Form/Contribution/Confirm.php
Labels: master, merge on pass

#30229 dev/core#5226 (backport) Fix cancel contributions when CiviMember not enabled
  CRM/Contribute/Form/ContributionRecur.php
Labels: 5.73

#30233 dev/core#5212 Fix handling of non membership checkbox line items when…
  CRM/Contribute/Form/Contribution/Confirm.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/api/v3/ContributionPageTest.php
Labels: merge on pass, 5.74

#30236 dev/core#5212 Fix handling of non membership checkbox line items when…
  CRM/Contribute/Form/Contribution/Confirm.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/api/v3/ContributionPageTest.php
Labels: merge on pass, 5.73

#30237 5.74
  CRM/Contribute/Form/Contribution/Confirm.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/api/v3/ContributionPageTest.php
Labels: master

#30230 Fix PHP warning when event has no end date
  templates/CRM/Event/Form/Selector.tpl
Labels: master

#30224 dev/core#5224 Disable PDF invoice setting when conditionally hidden
  templates/CRM/Admin/Form/Preferences/Contribute.tpl
Labels: master

#30133 Remove mailing_backend_store, confusingly set when we switch the environment to Development
  CRM/Admin/Page/Job.php
  CRM/Core/BAO/Setting.php
  CRM/Core/JobManager.php
  tests/phpunit/api/v3/JobProcessMailingTest.php
Labels: master, merge on pass

#30183 [NFC] Make tests fail when any error handlers don't clean themselves up
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/api/v3/ExtensionTest.php
Labels: master

#30031 Fold function back to only caller
  CRM/Contact/BAO/Contact/Utils.php
  CRM/Contact/Form/RelatedContact.php
Labels: master

#30029 Remove deprecated handling for invalid value
  CRM/Contact/BAO/Contact.php
  CRM/Core/Error.php
Labels: master

#29879 Pass parameters to dedupe fill table
  CRM/Dedupe/BAO/DedupeRuleGroup.php
  CRM/Dedupe/Finder.php
Labels: master

#29743 Fix notice on Membership form custom data loading
  templates/CRM/Member/Form/Membership.tpl
Labels: master

#29482 Stop calling run when loading multipleParticipantListing
  CRM/Profile/Form.php
  CRM/Profile/Page/MultipleRecordFieldsListing.php
Labels: master

#29701 Clean up notices on pledge dashboard
  CRM/Pledge/BAO/Pledge.php
  CRM/Pledge/Page/DashBoard.php
  templates/CRM/Pledge/Page/DashBoard.tpl
Labels: master

#28744 Fix error on relation-add where acl check fails
  CRM/Contact/Form/Relationship.php
Labels: master

#28967 Standardise implementation of financial type acl in query object
  CRM/Contact/BAO/Query.php
  ext/financialacls/financialacls.php
  ext/financialacls/tests/phpunit/Civi/Financialacls/LineItemTest.php
  tests/phpunit/CRM/Contact/BAO/QueryTest.php
  tests/phpunit/CRM/Contribute/BAO/ContributionTest.php
Labels: master, merge on pass

#30247 SearchKit - Always use backend links for tasks
  ext/search_kit/ang/crmSearchTasks/traits/searchDisplayTasksTrait.service.js
Labels: master

#30248 [REF] Update Civi Log channel in dreprecation function to match depre…
  CRM/Core/Error.php
Labels: master, merge on pass

#30251 5.73.3 - Add notes. Set version.
  deleted-files-list.json
  ext/afform/admin/info.xml
  ext/afform/core/info.xml
  ext/afform/html/info.xml
  ext/afform/mock/info.xml
  ext/authx/info.xml
  ext/civi_campaign/info.xml
  ext/civi_case/info.xml
  ext/civi_contribute/info.xml
  ext/civi_event/info.xml
  ext/civi_mail/info.xml
  ext/civi_member/info.xml
  ext/civi_pledge/info.xml
  ext/civi_report/info.xml
  ext/civicrm_admin_ui/info.xml
  ext/civicrm_search_ui/info.xml
  ext/civigrant/info.xml
  ext/civiimport/info.xml
  ext/ckeditor4/info.xml
  ext/contributioncancelactions/info.xml
  ext/elavon/info.xml
  ext/eventcart/info.xml
  ext/ewaysingle/info.xml
  ext/financialacls/info.xml
  ext/flexmailer/info.xml
  ext/greenwich/info.xml
  ext/iframe/info.xml
  ext/legacycustomsearches/info.xml
  ext/message_admin/info.xml
  ext/oauth-client/info.xml
  ext/oembed/info.xml
  ext/payflowpro/info.xml
  ext/recaptcha/info.xml
  ext/scheduled_communications/info.xml
  ext/search_kit/info.xml
  ext/sequentialcreditnotes/info.xml
  ext/standaloneusers/info.xml
  ext/user_dashboard/info.xml
  js/version.json
  release-notes.md
  release-notes/5.73.3.md
  sql/civicrm_generated.mysql
  sql/test_data_second_domain.mysql
  xml/version.xml
Labels: 5.73

#30252 Minor test improvements/ standardisation
  ext/financialacls/tests/phpunit/Civi/Financialacls/BaseTestClass.php
  tests/phpunit/CRMTraits/Financial/PriceSetTrait.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: master

#30249 Remove some unreachable code
  CRM/Event/Import/Parser/Participant.php
  Civi/Test/EventTestTrait.php
  tests/phpunit/CRM/Event/Import/Parser/ParticipantTest.php
  tests/phpunit/CRM/Event/Import/Parser/data/participant_with_event_id.csv
Labels: has-test

#30257 [php8] undeclared class vars on event online registration tab
  CRM/Event/Form/ManageEvent/Registration.php
Labels: master

#30256 [php8] Undeclared class variable in event fees
  CRM/Event/Form/ManageEvent/Fee.php
Labels: master

#30255 [php8] Undefined array key when editing event templates
  CRM/Event/Form/ManageEvent/EventInfo.php
  CRM/Event/Form/ManageEvent/Registration.php
  tests/phpunit/CRM/Event/Form/ManageEvent/EventInfoTest.php
  tests/phpunit/CRM/Event/Form/ManageEvent/RegistrationTest.php
Labels: master

#30259 dev/core#5230 Switch confirm_text on backoffice event to html
  CRM/Event/Form/Participant.php
Labels: 5.74

#30261 5.74
  CRM/Event/Form/Participant.php
Labels: master

#30219 Fix duplicate array key issue in CRM_Core_BAO_CustomQueryTest
  tests/phpunit/CRM/Core/BAO/CustomQueryTest.php
Labels: master

#30260 dev/core#5207 Add event_id in the cancel url for paypalStd (& similar)
  CRM/Core/Payment.php
Labels: 5.74

#30182 Api4 - Handle EMPTY operators correctly with boolean fields
  Civi/Api4/Query/Api4Query.php
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/SearchRunTest.php
Labels: master, has-test

#30264 5.74
  CRM/Core/Payment.php
Labels: master

#30007 SearchKit - Convert to entity-types-php@v2
  ext/search_kit/CRM/Search/DAO/SearchDisplay.php
  ext/search_kit/CRM/Search/DAO/SearchSegment.php
  ext/search_kit/CRM/Search/Upgrader.php
  ext/search_kit/info.xml
  ext/search_kit/schema/SearchDisplay.entityType.php
  ext/search_kit/schema/SearchSegment.entityType.php
  ext/search_kit/search_kit.civix.php
  ext/search_kit/sql/auto_install.sql
  ext/search_kit/sql/auto_uninstall.sql
  ext/search_kit/xml/schema/CRM/Search/SearchDisplay.entityType.php
  ext/search_kit/xml/schema/CRM/Search/SearchDisplay.xml
  ext/search_kit/xml/schema/CRM/Search/SearchSegment.entityType.php
  ext/search_kit/xml/schema/CRM/Search/SearchSegment.xml
Labels: master, merge ready

#30244 (dev/core#5235) Add deprecation for use of $mem_type_id in receipts
  CRM/Utils/Token.php
Labels: master, merge on pass

#30258 Fix membership import url
  CRM/Member/xml/Menu/Member.xml
  CRM/Upgrade/Incremental/php/FiveSeventyFour.php
  CRM/Upgrade/Incremental/sql/5.74.beta1.mysql.tpl
  sql/civicrm_generated.mysql
  sql/test_data_second_domain.mysql
  xml/templates/civicrm_navigation.tpl
Labels: 5.74

#30266 5.74
  CRM/Member/xml/Menu/Member.xml
  CRM/Upgrade/Incremental/php/FiveSeventyFour.php
  CRM/Upgrade/Incremental/sql/5.74.beta1.mysql.tpl
  sql/civicrm_generated.mysql
  sql/test_data_second_domain.mysql
  xml/templates/civicrm_navigation.tpl
Labels: master

#30267 SearchKit - Fix `str_starts_with()` error on php74
  ext/search_kit/info.xml
  ext/search_kit/search_kit.civix.php
Labels: master

#30270 [php8] Undeclared vars on manage events
  CRM/Event/Page/ManageEvent.php
Labels: master

#28559 dev/core#3130 : Replace sql to delete file and entityfile entries with DAO::deleteRecord sequentially, based on each entityfile entry
  CRM/Core/BAO/File.php
Labels: master

#30271 dev/core#5241 - Don't drop tables during install
  CRM/Core/CodeGen/PhpSchema.php
Labels: master, merge ready

#30282 Remove unused variable
  CRM/Contribute/Form/Contribution/Confirm.php
Labels: master, merge on pass
