Repository civicrm/civicrm-core, pull requests merged in 2024-01, with the labels that each got.

#28812 APIv4 - Hide 'contact_type' from Individual,Organization,Household getFields
  Civi/Api4/Generic/BasicGetFieldsAction.php
  Civi/Api4/Service/Autocomplete/ContactAutocompleteProvider.php
  tests/phpunit/api/v4/Action/GetExtraFieldsTest.php
  tests/phpunit/api/v4/Action/GetFieldsTest.php
Labels: master, has-test

#28811 SearchKit - Fix wrong column being removed from displays
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdminDisplay.component.js
Labels: master, sig:unreleased-regression

#28718 dev/core#3810 dev/core#3339 Fix handling of auto renew memberships where frequency_interval > 1
  CRM/Contribute/Form/ContributionBase.php
Labels: 5.69

#28818 Merge forward (5.69-rc to master)
  CRM/Contribute/Form/ContributionBase.php
Labels: master

#28808 SearchKit - Allow aggregate functions to be used without GroupBy
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdmin.component.js
Labels: master

#28821 Fix error due to merges co-inciding
  CRM/Event/Form/Registration/AdditionalParticipant.php
Labels: master

#28556 Fully deprecate MetadataTrait
  CRM/Contact/Import/MetadataTrait.php
Labels: master

#28823 Use constants for date formats
  CRM/Utils/Date.php
Labels: master

#28822 Extend date formats being tested
  tests/phpunit/CRM/Utils/DateTest.php
Labels: master

#28825 Remove function use of reference
  CRM/Utils/Date.php
Labels: master, merge on pass

#28789 Update `MessageTemplates` generation to work with Smarty3
  CRM/Core/CodeGen/Util/MessageTemplates.php
  CRM/Core/Smarty/plugins/block.ts.php
  setup/src/Setup/Template.php
  xml/templates/civicrm_msg_template.tpl
Labels: master

#27973 SearchKit - New getLinks API action for advanced link handling
  CRM/Activity/Form/ActivityLinks.php
  CRM/Core/Action.php
  CRM/Utils/String.php
  Civi/API/Event/RespondEvent.php
  Civi/Api4/Action/GetLinks.php
  Civi/Api4/CustomValue.php
  Civi/Api4/Event/Subscriber/PermissionCheckSubscriber.php
  Civi/Api4/Generic/AbstractEntity.php
  Civi/Api4/Generic/Traits/GetSetValueTrait.php
  Civi/Api4/Generic/Traits/SavedSearchInspectorTrait.php
  Civi/Api4/Service/Links/ActivityLinksProvider.php
  Civi/Api4/Service/Links/ContactLinksProvider.php
  Civi/Api4/Service/Links/LinksProviderTrait.php
  Civi/Api4/Service/Links/RelationshipCacheLinksProvider.php
  ext/civi_case/Civi/Api4/Service/Links/CaseLinksProvider.php
  ext/search_kit/Civi/Api4/Action/SearchDisplay/AbstractRunAction.php
  ext/search_kit/Civi/Api4/Action/SearchDisplay/Run.php
  ext/search_kit/Civi/Search/Display.php
  ext/search_kit/ang/crmSearchDisplay/toolbar.html
  ext/search_kit/ang/crmSearchDisplayGrid/crmSearchDisplayGrid.html
  ext/search_kit/ang/crmSearchDisplayList/crmSearchDisplayList.html
  ext/search_kit/ang/crmSearchDisplayTable/crmSearchDisplayTable.html
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/SearchRunTest.php
  tests/phpunit/api/v4/Action/GetLinksTest.php
  tests/phpunit/api/v4/Custom/CustomValueTest.php
Labels: master, has-test

#28826 Use distinct test workflow message for workflow message tests
  tests/phpunit/CRM/Case/WorkflowMessage/CaseActivityTest.php
  tests/phpunit/CRM/Case/WorkflowMessage/CaseActivityTestWorkflow.php
  tests/phpunit/CRM/Case/WorkflowMessage/CaseActivityTestWorkflow/CaseAdhocExample.php
  tests/phpunit/CRM/Case/WorkflowMessage/CaseActivityTestWorkflow/CaseModelExample.php
  tests/phpunit/CRM/Core/BAO/MessageTemplateTest.php
  tests/phpunit/api/v4/Entity/WorkflowMessageTest.php
Labels: master, merge on pass, has-test

#28784 civicrm.css: replace button float:left by inline-block
  css/civicrm.css
Labels: master, merge ready

#28830 Replace getTemplateVars() in test, assignTemplateVariables
  CRM/Core/Smarty.php
  tests/extensions/test.extension.manager.reporttest/main.php
Labels: master

#28829 Use getTemplateVars in smarty help function
  CRM/Core/Smarty/plugins/function.help.php
Labels: master

#28831 Remove smarty2 functions from sample code
  templates/CRM/Campaign/Page/Petition/SocialNetwork.drupal
Labels: master

#28838 Issue 4879 second attempt
  CRM/Import/Parser.php
  CRM/Mailing/Event/BAO/MailingEventForward.php
Labels: master

#28786 dev/core#4674 - Add Oauth links for AdminUi MailSettings
  ext/civi_mail/Civi/Api4/Service/Links/MailSettingsLinksProvider.php
Labels: master

#28837 Fix e-notice on contact create for low-permissioned user
  CRM/Contact/Form/Contact.php
Labels: master

#28834 [NFC] Add 'getLinks' action to phpStorm extension
  tools/extensions/phpstorm/Civi/PhpStorm/Api4Generator.php
Labels: master

#28828 Fix time validation for iso date format
  CRM/Utils/Date.php
  tests/phpunit/CRM/Utils/DateTest.php
Labels: master, has-test

#28824 Extract date regex validation
  CRM/Utils/Date.php
Labels: master, has-test

#28668 REF - Swap CRM_Utils_Array::collect with vanilla array_column
  CRM/Case/BAO/CaseType.php
  CRM/Contact/Form/Edit/TagsAndGroups.php
  Civi/Api4/Action/Queue/RunItems.php
  Civi/Api4/Generic/BasicReplaceAction.php
  tests/phpunit/CRM/Activity/Form/Task/PDFTest.php
Labels: master

#28647 Move implementation of financial type acl out of core (leverage existing extension hooks)
  CRM/Contribute/Form/Contribution.php
  CRM/Contribute/Form/Task/Delete.php
  CRM/Contribute/Selector/Search.php
  CRM/Event/Form/Registration.php
  CRM/Financial/BAO/FinancialType.php
  ext/financialacls/financialacls.php
  ext/financialacls/tests/phpunit/Civi/Financialacls/FinancialTypeTest.php
Labels: master, merge on pass

#28842 Price field and value weights not respected
  CRM/Price/BAO/PriceSet.php
  tests/phpunit/CRM/Price/BAO/PriceSetTest.php
Labels: merge on pass, has-test, 5.69

#28843 5.69
  CRM/Price/BAO/PriceSet.php
  tests/phpunit/CRM/Price/BAO/PriceSetTest.php
Labels: master

#28844 Fix handling of non-padded day in import date in dd/mm/yyy format
  CRM/Utils/Date.php
  tests/phpunit/CRM/Utils/DateTest.php
Labels: master, merge on pass, has-test

#28841 Fix import time handling handling for US formats of dates
  CRM/Utils/Date.php
  tests/phpunit/CRM/Utils/DateTest.php
Labels: master, has-test

#28846 Regenerate ext DAO files using updated civix
  ext/afform/core/CRM/Afform/DAO/AfformSubmission.php
  ext/civigrant/CRM/Grant/DAO/Grant.php
  ext/oauth-client/CRM/OAuth/DAO/OAuthClient.php
  ext/oauth-client/CRM/OAuth/DAO/OAuthContactToken.php
  ext/oauth-client/CRM/OAuth/DAO/OAuthSysToken.php
  ext/oauth-client/sql/auto_uninstall.sql
  ext/search_kit/CRM/Search/DAO/SearchDisplay.php
  ext/standaloneusers/CRM/Standaloneusers/DAO/User.php
  ext/standaloneusers/CRM/Standaloneusers/DAO/UserRole.php
Labels: master, merge on pass

#28849 Minor cleanup in test class
  tests/phpunit/api/v3/ContributionTest.php
Labels: master

#28852 [NFC] Fix docblock reference in _checkAccess functions
  CRM/Contact/AccessTrait.php
  CRM/Contact/BAO/Contact.php
  CRM/Contact/BAO/ContactType.php
  CRM/Contact/BAO/Group.php
  CRM/Contact/BAO/Relationship.php
  CRM/Core/DynamicFKAccessTrait.php
  CRM/Event/BAO/Event.php
  ext/oauth-client/CRM/OAuth/BAO/OAuthContactToken.php
  ext/standaloneusers/CRM/Standaloneusers/BAO/Role.php
  ext/standaloneusers/CRM/Standaloneusers/BAO/User.php
Labels: master

#28851 [NFC] Cleanup dummy DAO in ruleGroupTest class
  tests/phpunit/CRM/Dedupe/BAO/RuleGroupTest.php
Labels: master

#28856 Correct jcalendar.tpl
  templates/CRM/common/jcalendar.tpl
Labels: 5.69

#28857 5.69 to master
  templates/CRM/common/jcalendar.tpl
Labels: master

#28854 [NFC] 5.69 release note late changes
  release-notes/5.69.0.md
Labels: 5.69

#28519 [REF] Rewrite PCP enumeration to avoid caching bug
  CRM/Contribute/PseudoConstant.php
  tests/phpunit/CRM/Contribute/PseudoConstantTest.php
Labels: master

#28757 (dev/core#3581) composer.json - Allow newer version of oauth2-google
  composer.json
  composer.lock
Labels: master, merge on pass

#28858 dev/core#4881 Do not fatal if params is not an array
  CRM/Contribute/BAO/ContributionSoft.php
Labels: 5.69

#28820 CiviContribute - Do not delete price_set_entity record while page supports payment
  CRM/Contribute/Form/ContributionPage.php
  CRM/Contribute/Form/ContributionPage/Amount.php
Labels: 5.69

#28819 (dev/core#4877) CiviContribute - Re-calculate prices when using "Go Back"
  CRM/Contribute/Form/Contribution/Main.php
  CRM/Financial/BAO/Order.php
Labels: merge on pass, 5.69

#28859 Fix notice on civi-report display
  templates/CRM/Report/Form/Layout/Table.tpl
Labels: master, merge on pass

#28847 Fix time handling for dd_mon_yy format date strings
  CRM/Utils/Date.php
  tests/phpunit/CRM/Utils/DateTest.php
Labels: master, has-test

#28845 Fix import date formatting - time portion dropped for dd_mm_yy input format
  CRM/Utils/Date.php
  tests/phpunit/CRM/Utils/DateTest.php
Labels: master, has-test

#28848 Fix notice in workflow message examples when no price set present
  CRM/Member/WorkflowMessage/Membership/Membership.php
Labels: master

#28862 [REF] Fix Smarty Notices on Find Grants search
  ext/civigrant/templates/CRM/Grant/Form/Search/Common.tpl
  ext/civigrant/templates/CRM/Grant/Form/Selector.tpl
Labels: master, merge on pass

#28850 APIv4 - Add fk_column to getFields metadata
  Civi/Api4/Generic/DAOGetFieldsAction.php
  Civi/Api4/Service/Spec/SpecFormatter.php
  Civi/Schema/Traits/DataTypeSpecTrait.php
  tests/phpunit/api/v4/Action/GetFieldsTest.php
  tests/phpunit/api/v4/Custom/CustomEntityReferenceTest.php
Labels: master, merge on pass, has-test

#28769 Declare amount private - use magic method to provide access to the old value
  CRM/Event/Form/Registration/Confirm.php
Labels: master

#28861 [REF] Fix grant_report_received column to be not null and default to 0
  ext/civigrant/CRM/Grant/DAO/Grant.php
  ext/civigrant/CRM/Grant/Form/Grant.php
  ext/civigrant/CRM/Grant/Upgrader.php
  ext/civigrant/sql/auto_install.sql
  ext/civigrant/xml/schema/CRM/Grant/Grant.xml
Labels: master, merge on pass

#28860 CoreForm - Add noisy deprecation to addDate & addDateTime functions
  CRM/Core/Form.php
Labels: master

#28865 5.69
  CRM/Contribute/BAO/ContributionSoft.php
  CRM/Contribute/Form/Contribution/Main.php
  CRM/Contribute/Form/ContributionPage.php
  CRM/Contribute/Form/ContributionPage/Amount.php
  CRM/Financial/BAO/Order.php
  release-notes/5.69.0.md
Labels: master

#28641 Dashboard Fullscreen dashlet improvements
  ang/crmDashboard/Dashboard.html
  ang/crmDashboard/crmDashboard.component.js
  css/dashboard.css
Labels: master

#28866 Minor cleanup in ReportInstance BAO
  CRM/Report/BAO/ReportInstance.php
Labels: master, merge on pass

#28722 CiviMember - Fix checkbox for optional auto-renewals
  CRM/Contribute/Form/Contribution/Confirm.php
  CRM/Contribute/Form/Contribution/Main.php
  CRM/Contribute/Form/Contribution/ThankYou.php
  CRM/Contribute/Form/ContributionBase.php
  CRM/Financial/BAO/Order.php
  templates/CRM/Contribute/Form/Contribution/Confirm.tpl
  templates/CRM/Contribute/Form/Contribution/MainMembershipBlock.tpl
  templates/CRM/Contribute/Form/Contribution/MembershipBlock.tpl
  templates/CRM/Contribute/Form/Contribution/ThankYou.tpl
  templates/CRM/Price/Form/PriceSet.tpl
Labels: 5.69

#28867 Move report test to civi_report
  ext/civi_report/phpunit.xml.dist
  ext/civi_report/tests/phpunit/ReportTest.php
  ext/civi_report/tests/phpunit/bootstrap.php
  tests/phpunit/CRM/Report/Utils/ReportTest.php
Labels: master, merge on pass

#28868 5.69 to master
  CRM/Contribute/Form/Contribution/Confirm.php
  CRM/Contribute/Form/Contribution/Main.php
  CRM/Contribute/Form/Contribution/ThankYou.php
  CRM/Contribute/Form/ContributionBase.php
  CRM/Financial/BAO/Order.php
  templates/CRM/Contribute/Form/Contribution/Confirm.tpl
  templates/CRM/Contribute/Form/Contribution/MainMembershipBlock.tpl
  templates/CRM/Contribute/Form/Contribution/MembershipBlock.tpl
  templates/CRM/Contribute/Form/Contribution/ThankYou.tpl
  templates/CRM/Price/Form/PriceSet.tpl
Labels: master

#28863 Add system check to warn if CiviReport disabled & logging enabled
  CRM/Utils/Check/Component/Env.php
  tests/phpunit/CRM/Utils/Check/Component/EnvTest.php
Labels: master, merge on pass, has-test

#28870 5.69.0 - Add last-minute notes. Update version.
  ext/afform/admin/info.xml
  ext/afform/core/info.xml
  ext/afform/html/info.xml
  ext/afform/mock/info.xml
  ext/authx/info.xml
  ext/civi_campaign/info.xml
  ext/civi_case/info.xml
  ext/civi_contribute/info.xml
  ext/civi_event/info.xml
  ext/civi_mail/info.xml
  ext/civi_member/info.xml
  ext/civi_pledge/info.xml
  ext/civi_report/info.xml
  ext/civicrm_admin_ui/info.xml
  ext/civicrm_search_ui/info.xml
  ext/civigrant/info.xml
  ext/civiimport/info.xml
  ext/ckeditor4/info.xml
  ext/contributioncancelactions/info.xml
  ext/elavon/info.xml
  ext/eventcart/info.xml
  ext/ewaysingle/info.xml
  ext/financialacls/info.xml
  ext/flexmailer/info.xml
  ext/greenwich/info.xml
  ext/legacycustomsearches/info.xml
  ext/message_admin/info.xml
  ext/oauth-client/info.xml
  ext/payflowpro/info.xml
  ext/recaptcha/info.xml
  ext/scheduled_communications/info.xml
  ext/search_kit/info.xml
  ext/sequentialcreditnotes/info.xml
  ext/standaloneusers/info.xml
  ext/user_dashboard/info.xml
  js/version.json
  release-notes/5.69.0.md
  sql/civicrm_generated.mysql
  sql/test_data_second_domain.mysql
  xml/version.xml
Labels: 5.69

#28871 Ensure auto renew is set on Membership price set
  CRM/Financial/BAO/Order.php
Labels: merge on pass, 5.69

#28874 Ensure auto renew is set on Membership price set
  CRM/Financial/BAO/Order.php
Labels: master

#28872 Handle auto-renew correctly on original-price-sets
  CRM/Contribute/Form/Contribution/Main.php
  CRM/Price/BAO/PriceField.php
Labels: 5.69

#28875 Handle auto-renew correctly on original-price-sets
  CRM/Contribute/Form/Contribution/Main.php
  CRM/Price/BAO/PriceField.php
Labels: master

#27717 AdminUI - Replace Contact Summary Activities tab
  CRM/Activity/Form/Activity.php
  CRM/Contribute/Form/Contribution.php
  ext/afform/core/Civi/Afform/AfformMetadataInjector.php
  ext/afform/core/afform.php
  ext/afform/core/ang/af/afFieldWithSearchOperator.html
  ext/afform/core/ang/afCore.css
  ext/civicrm_admin_ui/ang/afsearchTabActivity.aff.html
  ext/civicrm_admin_ui/ang/afsearchTabActivity.aff.php
  ext/civicrm_admin_ui/managed/SavedSearch_Contact_Summary_Activities.mgd.php
  ext/search_kit/Civi/Api4/Action/SearchDisplay/Run.php
  templates/CRM/common/TabHeader.js
Labels: master, merge ready

#28529 faster activity counting
  CRM/Contact/BAO/Contact.php
Labels: master

#28732 Remove text version on online event receipt
  tests/phpunit/CRM/Core/Payment/BaseIPNTest.php
  tests/phpunit/CRM/Event/Form/Registration/ConfirmTest.php
  tests/phpunit/api/v3/ContributionTest.php
  tests/phpunit/api/v3/PaymentTest.php
  xml/templates/message_templates/event_online_receipt_text.tpl
Labels: master

#28778 Consolidate participant creation into 1 place
  CRM/Event/Form/Participant.php
Labels: master

#28880 dev/core#4886 fix syntax error in contact summary template
  templates/CRM/Contact/Import/Form/Summary.tpl
Labels: master, merge on pass

#28876 Support creating payment methods that can be hidden from user
  CRM/Contribute/BAO/Contribution.php
  CRM/Contribute/Form/AdditionalPayment.php
  CRM/Contribute/Form/Contribution.php
Labels: master

#28881 dev/core#4886 fix syntax error in contact summary template
  templates/CRM/Contact/Import/Form/Summary.tpl
Labels: merge on pass, 5.69

#28716 Fix month date string format support in imports
  CRM/Utils/Date.php
  tests/phpunit/CRM/Utils/DateTest.php
Labels: master

#28873 Add report instance permission check & test
  CRM/Report/BAO/ReportInstance.php
  ext/civi_report/Civi/Api4/ReportInstance.php
  ext/civi_report/tests/phpunit/ReportInstanceTest.php
  ext/civi_report/tests/phpunit/ReportTest.php
Labels: master

#28882 [NFC] Product - Fix duplicated key in xml file
  CRM/Contribute/DAO/Product.php
  xml/schema/Contribute/Product.xml
Labels: master

#28879 Fixes Backdrop summary/detail admin theme clash
  css/backdrop.css
Labels: 5.69

#28887 Fixes Backdrop summary/detail admin theme clash
  css/backdrop.css
Labels: master, merge on pass

#28888 dev/core#4841 Ensure that APIv4 have same default values which ensure…
  CRM/Mailing/BAO/Mailing.php
  CRM/Mailing/PseudoConstant.php
  api/v3/Mailing.php
Labels: 5.69

#28884 Fix Smarty3 error in online event registration
  CRM/Event/WorkflowMessage/ParticipantTrait.php
  xml/templates/message_templates/event_online_receipt_html.tpl
Labels: master

#28886 Fix Smarty3 error in online event registration
  CRM/Event/WorkflowMessage/ParticipantTrait.php
  xml/templates/message_templates/event_online_receipt_html.tpl
Labels: 5.69

#28892 Update release-notes/5.69.0.md
  release-notes/5.69.0.md
Labels: 5.69

#20970 dev/core#2719 [REF] Deprecate legacy references to contribution_invoice_settings
  Civi/Core/SettingsBag.php
  api/v3/Setting.php
  tests/phpunit/CRM/Core/BAO/SettingTest.php
  tests/phpunit/Civi/Core/SettingsBagTest.php
Labels: master

#28900 Add html types to Participant schema
  CRM/Event/DAO/Participant.php
  xml/schema/Event/Participant.xml
Labels: master

#28901 Smarty Syntax fix - UFGroup help file
  templates/CRM/UF/Form/Group.hlp
Labels: 5.70

#28902 Smarty Syntax fix - UFGroup help file
  templates/CRM/UF/Form/Group.hlp
Labels: 5.69

#28903 5.70
  templates/CRM/UF/Form/Group.hlp
Labels: master

#28897 Corrupted version.js file
  js/version.json
  tools/bin/scripts/set-version.php
Labels: merge on pass, 5.70

#28800 Add preliminary previewability and token support to case-activity
  CRM/Case/BAO/Case.php
  CRM/Case/WorkflowMessage/ActivityExamples.php
  CRM/Case/WorkflowMessage/CaseActivity.php
  tests/phpunit/api/v4/Entity/WorkflowMessageTest.php
  xml/templates/message_templates/case_activity_html.tpl
  xml/templates/message_templates/case_activity_text.tpl
Labels: master

#28905 backport 28897
  js/version.json
  tools/bin/scripts/set-version.php
Labels: merge on pass, 5.69

#28909 (alternate 2) Fix bad smarty3 compile filenames
  CRM/Core/Form/Renderer.php
Labels: merge on pass, 5.70

#28895 Fix pay-later receipt token in shipped version
  CRM/Upgrade/Incremental/php/FiveSeventy.php
  xml/templates/message_templates/membership_online_receipt_html.tpl
Labels: 5.70

#28914 Fix pay-later receipt token in shipped version (backport)
  CRM/Upgrade/Incremental/php/FiveSixtyNine.php
  sql/civicrm_generated.mysql
  xml/templates/message_templates/membership_online_receipt_html.tpl
Labels: 5.69

#28918 Add release-notes/5.69.1.md
  release-notes.md
  release-notes/5.69.1.md
Labels: 5.69

#28919 Run regen
  sql/civicrm_generated.mysql
Labels: 5.70

#28920 5.70 to master (inc regen)
  CRM/Core/Form/Renderer.php
  CRM/Upgrade/Incremental/php/FiveSeventy.php
  js/version.json
  sql/civicrm_generated.mysql
  tools/bin/scripts/set-version.php
  xml/templates/message_templates/membership_online_receipt_html.tpl
Labels: master

#28906 5.70
  CRM/Core/Form/Renderer.php
  CRM/Upgrade/Incremental/php/FiveSeventy.php
  js/version.json
  sql/civicrm_generated.mysql
  tools/bin/scripts/set-version.php
  xml/templates/message_templates/membership_online_receipt_html.tpl
Labels: master

#28680 Restore membership types in tearDown
  tests/phpunit/api/v3/ContributionTest.php
Labels: master

#28907 dev/user-interface#64 civicrm.css: fix cancel/done button alignment
  css/civicrm.css
Labels: merge ready, sig:user interfacing improvement, 5.70

#28916 Copy buildAmount back to form to avoid unhelpful sharing
  CRM/Event/Form/ParticipantFeeSelection.php
  CRM/Event/Form/Registration/Register.php
Labels: master

#28899 Fix Profile set up in test configuration
  CRM/Event/Form/Registration/Confirm.php
  Civi/Test/EventTestTrait.php
  tests/phpunit/CRM/Event/Form/Registration/ConfirmTest.php
  tests/phpunit/api/v3/ContributionTest.php
  tests/phpunit/api/v3/PaymentTest.php
Labels: master

#28917 Prevent notice on non-monetary event
  CRM/Event/Form/Registration/Confirm.php
Labels: master

#28924 Make function non-static, protected
  CRM/Event/Form/Registration.php
  CRM/Event/Form/Registration/AdditionalParticipant.php
  CRM/Event/Form/Registration/Confirm.php
  CRM/Event/Form/Registration/Register.php
Labels: master

#28889 [Ref] Minor cleanup in handling of additional participants when sending mail + improve test
  CRM/Contribute/BAO/Contribution.php
  CRM/Event/BAO/Event.php
  CRM/Event/Form/Registration.php
  CRM/Event/Form/Registration/Confirm.php
  tests/phpunit/CRM/Event/Form/Registration/ConfirmTest.php
Labels: master

#28922 dev/core#4889 - Exclude tools & tests from deleted-files-list.json
  deleted-files-list.json
  tools/scripts/generate-deleted-files-list.php
Labels: merge on pass, 5.70

#28927 Merge 5.70 to master
  css/civicrm.css
  deleted-files-list.json
  tools/scripts/generate-deleted-files-list.php
Labels: master

#28932 dev/core#4892 dev/core#4891 fix weight notices
  CRM/Admin/Page/Mapping.php
  CRM/Contact/Selector.php
Labels: 5.69

#28925 REF Move paymentProcessorAuthorizeNetCreate test function to authorizenet test trait
  tests/phpunit/CRM/Core/Payment/AuthorizeNetIPNTest.php
  tests/phpunit/CRM/Core/Payment/AuthorizeNetTrait.php
  tests/phpunit/CRM/Core/Payment/BaseIPNTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/api/v3/ContributionTest.php
Labels: master

#28935 5.70
  CRM/Admin/Page/Mapping.php
  CRM/Contact/Selector.php
Labels: master

#28891 Add test cover for event additional profiles
  Civi/Test/EventTestTrait.php
  tests/phpunit/CRM/Event/Form/Registration/ConfirmTest.php
  tests/phpunit/CRMTraits/Event/ScenarioTrait.php
Labels: master

#28937 Switch confirmTest to use the form wrapper
  Civi/Test/FormTrait.php
  tests/phpunit/CRM/Event/Form/Registration/ConfirmTest.php
Labels: master

#28930 DeletedFilesCheck - Include renamed as well as deleted files
  deleted-files-list.json
  tools/scripts/generate-deleted-files-list.php
Labels: master, merge on pass

#28939 Remove unused variable
  CRM/Event/Form/Registration.php
Labels: master

#28923 Stop setting unused key
  CRM/Event/Form/Registration/Register.php
Labels: master

#28885 Remove un-used noticey function
  templates/CRM/Price/Page/LineItem.tpl
Labels: master

#28940 APIv4 - Improve getFields internal value lookups
  Civi/Api4/Service/Spec/RequestSpec.php
  tests/phpunit/api/v4/Custom/CustomFieldGetFieldsTest.php
Labels: master, merge on pass, has-test

#28936 Add system checks for civicrm.settings performance options
  CRM/Utils/Check/Component/Env.php
Labels: master, merge on pass

#28942 Bump follow-redirects from 1.14.8 to 1.15.4
  package-lock.json
Labels: merge on pass, 5.70

#28913 Make fail-heavy test as ornery
  tests/phpunit/E2E/Core/AssetBuilderTest.php
Labels: 5.70

#28943 5.70
  package-lock.json
  tests/phpunit/E2E/Core/AssetBuilderTest.php
Labels: master

#28928 dev/core#4893 Fix failure to send event emails on non-monetary events with no confirm page
  CRM/Event/Form/Registration.php
  Civi/Test/FormTrait.php
  tests/phpunit/CRM/Event/Form/Registration/ConfirmTest.php
Labels: 5.70

#28929 dev/core#4893 Fix failure to send event emails on non-monetary events with no confirm page
  CRM/Event/Form/Registration.php
  Civi/Test/FormTrait.php
  tests/phpunit/CRM/Event/Form/Registration/ConfirmTest.php
Labels: 5.69

#28944 dev/core#4897 Fix Search Kit row link conditions
  ext/search_kit/Civi/Api4/Action/SearchDisplay/AbstractRunAction.php
Labels: merge on pass, 5.70

#28948 5.70 to master
  CRM/Event/Form/Registration.php
  Civi/Test/FormTrait.php
  ext/search_kit/Civi/Api4/Action/SearchDisplay/AbstractRunAction.php
  tests/phpunit/CRM/Event/Form/Registration/ConfirmTest.php
Labels: master

#28950 hook_links - Identify more quirks
  CRM/Report/Page/InstanceList.php
  tests/events/hook_civicrm_links.evch.php
Labels: master

#28946 dev/core#4897 Fix Search Kit row link conditions
  ext/search_kit/Civi/Api4/Action/SearchDisplay/AbstractRunAction.php
Labels: 5.69

#28938 Copy formatFieldsForOptionFull to not share backoffice & front end
  CRM/Event/Form/ParticipantFeeSelection.php
  CRM/Event/Form/Registration/Register.php
Labels: master

#28952 dev/core#4898 Add getLinks to Import api
  ext/civiimport/Civi/Api4/Import.php
Labels: merge on pass, 5.70

#28949 Unconditionally assign priceSet on event forms to avoid notices
  CRM/Event/Form/Registration/AdditionalParticipant.php
  CRM/Event/Form/Registration/Register.php
Labels: master

#28953 5.70
  ext/civiimport/Civi/Api4/Import.php
Labels: master

#28955 dev/core#4888 - Location field on case activity is misaligned
  templates/CRM/Case/Form/Activity.tpl
Labels: master, merge on pass

#28958 [REF] SearchKit - minor code cleanup/clarification
  ext/search_kit/Civi/Api4/Event/Subscriber/DefaultDisplaySubscriber.php
  ext/search_kit/Civi/Search/Admin.php
Labels: master

#28956 Followup to 28936
  CRM/Utils/Check/Component/Env.php
Labels: master

#28549 PCP - Add metadata for SearchKit dynamic joins
  CRM/Core/Reference/Dynamic.php
  CRM/PCP/BAO/PCP.php
  CRM/PCP/DAO/PCP.php
  Civi/Api4/Service/Spec/SpecFormatter.php
  Civi/Api4/Service/Spec/SpecGatherer.php
  Civi/Schema/Traits/DataTypeSpecTrait.php
  Civi/Test/Api4TestTrait.php
  ext/search_kit/Civi/Search/Admin.php
  tests/phpunit/api/v4/Action/GetFieldsTest.php
  tests/phpunit/api/v4/Entity/PCPTest.php
  xml/schema/PCP/PCP.xml
Labels: master

#28962 dev/core#4903 - undefined variable in New Individual on-the-fly popup
  CRM/Profile/Form/Edit.php
Labels: merge on pass, 5.70

#28957 CiviCase - Fix crash when fetching status_id pseudoconstant
  CRM/Case/BAO/Case.php
Labels: 5.70

#28890 [REF] Convert _checkAccess to event listener
  CRM/Contact/AccessTrait.php
  CRM/Contact/BAO/Contact.php
  CRM/Contact/BAO/ContactType.php
  CRM/Contact/BAO/Group.php
  CRM/Contact/BAO/Relationship.php
  CRM/Core/BAO/CustomValue.php
  CRM/Core/BAO/EntityTag.php
  CRM/Core/BAO/Website.php
  CRM/Core/DynamicFKAccessTrait.php
  CRM/Event/BAO/Event.php
  Civi/Api4/Utils/CoreUtil.php
  Civi/Core/Container.php
  ext/oauth-client/CRM/OAuth/BAO/OAuthContactToken.php
  ext/search_kit/CRM/Search/BAO/SearchDisplay.php
  ext/search_kit/search_kit.php
  ext/standaloneusers/CRM/Standaloneusers/BAO/Role.php
  ext/standaloneusers/CRM/Standaloneusers/BAO/User.php
Labels: master, merge ready

#28972 Make error message more traceable
  CRM/Event/Selector/Search.php
Labels: master

#28965 5.70
  CRM/Case/BAO/Case.php
  CRM/Profile/Form/Edit.php
Labels: master

#28970 Regression: fix CMS creation issue from profile
  CRM/Profile/Form.php
Labels: merge on pass, 5.70

#28974 backport 28970
  CRM/Profile/Form.php
Labels: 5.69

#28973 5.70
  CRM/Profile/Form.php
Labels: master

#28933 dev/core#4781 Handle invalid deprecated fields with more grace
  CRM/Import/Form/MapField.php
  CRM/Member/Import/Form/MapField.php
Labels: 5.70

#28399 Warn when undefined php properties in mail text
  CRM/Contribute/Form/Contribution/Confirm.php
  CRM/Core/Smarty.php
  CRM/Event/BAO/Participant.php
  CRM/Event/WorkflowMessage/ParticipantConfirm.php
  CRM/Event/WorkflowMessage/ParticipantExpired.php
  CRM/Utils/Mail.php
  xml/templates/message_templates/participant_cancelled_html.tpl
  xml/templates/message_templates/participant_confirm_html.tpl
  xml/templates/message_templates/participant_expired_html.tpl
  xml/templates/message_templates/participant_transferred_html.tpl
Labels: master

#28976 PHP 8.3 support - port
  CRM/Import/Parser.php
  CRM/Mailing/Event/BAO/MailingEventForward.php
Labels: 5.69

#28934 dev/core#4781 Handle invalid deprecated fields with more grace
  CRM/Import/Form/MapField.php
  CRM/Member/Import/Form/MapField.php
Labels: 5.69

#28959 [REF] Fix Hard Fail when loading back office add membership form with membe…
  CRM/Member/Form/Membership.php
Labels: 5.70

#28979 Remove arguable statement about refunds
  xml/templates/message_templates/participant_confirm_html.tpl
Labels: master, merge on pass

#28977 Fix Hard Fail when loading back office add membership form with membe…
  CRM/Member/Form/Membership.php
Labels: 5.69

#28985 5.69.2 - Add notes. Raise version.
  ext/afform/admin/info.xml
  ext/afform/core/info.xml
  ext/afform/html/info.xml
  ext/afform/mock/info.xml
  ext/authx/info.xml
  ext/civi_campaign/info.xml
  ext/civi_case/info.xml
  ext/civi_contribute/info.xml
  ext/civi_event/info.xml
  ext/civi_mail/info.xml
  ext/civi_member/info.xml
  ext/civi_pledge/info.xml
  ext/civi_report/info.xml
  ext/civicrm_admin_ui/info.xml
  ext/civicrm_search_ui/info.xml
  ext/civigrant/info.xml
  ext/civiimport/info.xml
  ext/ckeditor4/info.xml
  ext/contributioncancelactions/info.xml
  ext/elavon/info.xml
  ext/eventcart/info.xml
  ext/ewaysingle/info.xml
  ext/financialacls/info.xml
  ext/flexmailer/info.xml
  ext/greenwich/info.xml
  ext/legacycustomsearches/info.xml
  ext/message_admin/info.xml
  ext/oauth-client/info.xml
  ext/payflowpro/info.xml
  ext/recaptcha/info.xml
  ext/scheduled_communications/info.xml
  ext/search_kit/info.xml
  ext/sequentialcreditnotes/info.xml
  ext/standaloneusers/info.xml
  ext/user_dashboard/info.xml
  js/version.json
  release-notes.md
  release-notes/5.69.2.md
  sql/civicrm_generated.mysql
  sql/test_data_second_domain.mysql
  xml/version.xml
Labels: 5.69

#28981 Minor clean up in test class
  tests/phpunit/CRM/Event/BAO/ParticipantTest.php
  tests/phpunit/CRM/Event/Form/Task/BadgeTest.php
  tests/phpunit/CRM/Utils/TokenConsistencyTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/api/v3/ParticipantTest.php
Labels: master, merge on pass

#28986 CiviCRM APIv4, Extension::get - expose more Extension properties
  Civi/Api4/Extension.php
Labels: master, merge on pass

#28975 dev/core#4905 - More efficient loading and caching of custom field metadata
  CRM/Contact/BAO/ContactType.php
  CRM/Core/BAO/CustomGroup.php
  CRM/Core/DAO.php
  Civi/Api4/Generic/Traits/DAOActionTrait.php
  Civi/Api4/Provider/CustomEntityProvider.php
  Civi/Api4/Service/Schema/Joinable/CustomGroupJoinable.php
  Civi/Api4/Service/Schema/SchemaMapBuilder.php
  Civi/Api4/Service/Spec/SpecFormatter.php
  Civi/Api4/Service/Spec/SpecGatherer.php
  tests/phpunit/CRM/Contact/BAO/ContactType/ContactTypeTest.php
  tests/phpunit/CRM/Core/BAO/CustomGroupTest.php
  tests/phpunit/api/v4/Spec/SpecFormatterTest.php
Labels: master, merge on pass

#28969 Add comments to settings definition to clarify that this is not the preferred method
  CRM/Admin/Form/Setting.php
  CRM/Admin/Form/Setting/Case.php
  CRM/Admin/Form/Setting/Component.php
  CRM/Admin/Form/Setting/Date.php
  CRM/Admin/Form/Setting/Debugging.php
  CRM/Admin/Form/Setting/Localization.php
  CRM/Admin/Form/Setting/Mail.php
  CRM/Admin/Form/Setting/Mapping.php
  CRM/Admin/Form/Setting/Miscellaneous.php
  CRM/Admin/Form/Setting/Path.php
  CRM/Admin/Form/Setting/Smtp.php
  CRM/Admin/Form/Setting/UF.php
  CRM/Admin/Form/Setting/Url.php
Labels: master
