Repository civicrm/civicrm-core, pull requests merged in 2024-02, with the labels that each got.

#29178 5.70
  CRM/Contribute/Form/Contribution/Main.php
  Civi/Crypto/CryptoJwt.php
  ext/afform/core/ang/af/afField.component.js
  ext/afform/core/ang/af/fields/EntityRef.html
  js/Common.js
  templates/CRM/ACL/Header.tpl
Labels: master

#29103 Return determination of title to the only user
  CRM/Contribute/Form/AbstractEditPayment.php
  CRM/Contribute/Form/AdditionalPayment.php
Labels: master

#29094 [REF] dev/core#4905 ContactType - Use cache to get custom fields
  CRM/Contact/BAO/ContactType.php
Labels: master

#29110 Fix notices on Additional Payment Form
  CRM/Contribute/Form/AdditionalPayment.php
  CRM/Event/Form/EventFormTrait.php
  templates/CRM/Contribute/Form/AdditionalPayment.tpl
Labels: master

#29181 Core/DAO - Add boilerplate import/export functions to base class
  CRM/Core/DAO.php
  CRM/Core/DAO/AllCoreTables.php
  mixin/entity-types-php@1/example/CRM/Shimmy/DAO/ShimThing.php
Labels: master

#29188 dev/core#4957 [REF][PHP8.2] Local variable for tagGroup
  CRM/Contact/Form/Edit/TagsAndGroups.php
Labels: merge on pass, 5.69

#29189 dev/user-interface#65 Remove top set of buttons which only show up in…
  templates/CRM/Contribute/Form/ContributionView.tpl
Labels: merge on pass, 5.70

#29191 5.70
  templates/CRM/Contribute/Form/ContributionView.tpl
Labels: master

#29138 Fix apiv4 Mailing Api to not do scheduling
  CRM/Mailing/BAO/Mailing.php
  ext/civi_mail/Civi/Api4/Action/Mailing/CreateAction.php
  ext/civi_mail/Civi/Api4/Action/Mailing/MailingSaveTrait.php
  ext/civi_mail/Civi/Api4/Action/Mailing/SaveAction.php
  ext/civi_mail/Civi/Api4/Action/Mailing/UpdateAction.php
  ext/civi_mail/Civi/Api4/Mailing.php
  tests/phpunit/CRM/Mailing/BAO/MailingTest.php
  tests/phpunit/api/v3/JobProcessMailingTest.php
  tests/phpunit/api/v3/MailingTest.php
Labels: master, merge ready

#29161 Remove unused properties, make internal function private
  CRM/Mailing/BAO/SMSJob.php
Labels: master

#29180 SearchKit - Fix switching to nonexistent tab
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdmin.component.js
Labels: sig:unreleased-regression, 5.70

#29203 dev/core#4962 Fix Smarty fatal on resource url page
  templates/CRM/Admin/Form/Setting/Url.hlp
Labels: 5.70

#29198 Move function to shared parent & make non-static
  CRM/Event/Form/Registration.php
  CRM/Event/Form/Registration/AdditionalParticipant.php
  CRM/Event/Form/Registration/Register.php
Labels: master

#29201 SearchKit - Hide invalid links and prevent error
  Civi/Api4/Action/GetLinks.php
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/SearchRunTest.php
Labels: master, has-test, sig:unreleased-regression

#29206 SearchKit - Hide invalid links and prevent error
  Civi/Api4/Action/GetLinks.php
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/SearchRunTest.php
Labels: 5.70

#29192 Fix 5.67 regression on loading custom data defaults on contribution page
  CRM/Contribute/Form/Contribution/Main.php
Labels: merge on pass, sig:regression, 5.70

#29207 Move static function to parent, make non-static
  CRM/Event/Form/Registration.php
  CRM/Event/Form/Registration/Confirm.php
  CRM/Event/Form/Registration/Register.php
Labels: master, merge on pass

#29210 Pass variables into validatePriceSet rather than getting from the form
  CRM/Event/Form/Registration.php
  CRM/Event/Form/Registration/AdditionalParticipant.php
  CRM/Event/Form/Registration/Confirm.php
  CRM/Event/Form/Registration/Register.php
Labels: master

#29200 dev/core#4960 Make Case menu link in relationship tab conditional
  managed/contactSummary/SavedSearch_Contact_Summary_Relationships.mgd.php
Labels: merge on pass, sig:unreleased-regression, 5.70

#29209 dev/core#4950 - Disable SearchUI version of ContactSummary Activity tab
  ext/civicrm_admin_ui/ang/afsearchTabActivity.aff.php
Labels: 5.70

#29208 SearchKit - Remove irrelevant links from default display
  ext/search_kit/Civi/Api4/Action/SearchDisplay/GetDefault.php
  ext/search_kit/Civi/Search/Display.php
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/SearchRunTest.php
Labels: has-test, sig:unreleased-regression, 5.70

#29211 Unshare initFee function
  CRM/Event/Form/ParticipantFeeSelection.php
  CRM/Event/Form/Registration.php
Labels: master

#29215 Pass fee block into validatePriceset rather than looking up property
  CRM/Event/Form/Registration.php
  CRM/Event/Form/Registration/Confirm.php
Labels: master, merge on pass

#29174 Permissions - Make implied permissions declarative
  CRM/Core/Permission.php
  CRM/Core/Permission/Base.php
  CRM/Core/Permission/List.php
  CRM/Utils/Hook.php
  Civi/Api4/Permission.php
  tests/phpunit/CRM/Core/Permission/BaseTest.php
  tests/phpunit/api/v4/Entity/PermissionTest.php
Labels: master, merge ready, has-test

#29216 Make previously shared function non-static
  CRM/Event/Form/Registration.php
Labels: master, merge on pass

#29217 Unshare another function with over-sharing
  CRM/Event/Form/ParticipantFeeSelection.php
Labels: master, merge on pass

#29219 Use standardised function to get PriceFieldMetadata
  CRM/Event/Form/Registration.php
Labels: master

#29218 CorePermission - Declare more implied permissions explicitly
  CRM/Core/Permission.php
Labels: master

#29182 DAO - Remove buggy caching from import/export
  CRM/Core/DAO/AllCoreTables.php
Labels: master, merge ready

#29227 Declare some public variables on ChangeCaseStatus
  CRM/Case/Form/Activity/ChangeCaseStatus.php
Labels: master

#28733 Clean up code to add custom data to forms, implement on back office participant form
  CRM/Core/BAO/CustomGroup.php
  CRM/Core/Form.php
  CRM/Custom/Form/CustomDataTrait.php
  CRM/Event/Form/Participant.php
Labels: master

#29223 APIv4 - Add type hints to FieldSpec functions
  Civi/Api4/Service/Spec/FieldSpec.php
Labels: master

#29224 FIx show-hide notices on event confirm
  CRM/Core/ShowHideBlocks.php
  templates/CRM/Event/Form/Registration/Confirm.tpl
Labels: master

#29230 Remove call to silly non-php8.2 compliant function
  CRM/Contact/Form/Task/EmailCommon.php
  CRM/Contribute/Form/Task/PDF.php
Labels: master

#29242 Disable failing test in PR runs for now
  tests/phpunit/E2E/Core/LocalizedDataTest.php
Labels: master

#29237 Event cart - stop using undeclared property cid
  ext/eventcart/CRM/Event/Cart/Form/Checkout/ParticipantsAndPrices.php
Labels: master

#29220 Fix Participant fee selection to use standardised getPriceFieldMetadata
  CRM/Event/Form/ParticipantFeeSelection.php
Labels: master

#29221 Stop calculating optionsCountDetails in non-unshared function on participantFeeSelection
  CRM/Event/Form/ParticipantFeeSelection.php
Labels: master

#29236 Afform - Remove guesswork from fk lookups
  ext/afform/core/Civi/Api4/Action/Afform/AbstractProcessor.php
Labels: master

#29247 Make form-specific function protected, non-static
  CRM/Event/Form/Registration.php
  CRM/Event/Form/Registration/AdditionalParticipant.php
  CRM/Event/Form/Registration/Register.php
Labels: master, merge on pass

#29234 Notice fixes on AdditionalParticipant page
  CRM/Event/Form/Registration.php
  CRM/Event/Form/Registration/AdditionalParticipant.php
  CRM/Event/Form/Registration/Register.php
  templates/CRM/Event/Form/Registration/AdditionalParticipant.tpl
Labels: master, merge on pass

#29232 Fold functions that only support one form back into that form (survey)
  CRM/Campaign/Form/Survey.php
  CRM/Campaign/Form/Survey/TabHeader.php
Labels: master

#29240 Fix notices & php8.2 compatibility on Manage Event Info page
  CRM/Event/Form/ManageEvent.php
  CRM/Event/Form/ManageEvent/EventInfo.php
  templates/CRM/Event/Form/ManageEvent/EventInfo.tpl
Labels: master

#29248 Unshare another function to permit code cleanup
  CRM/Event/Form/ParticipantFeeSelection.php
  CRM/Event/Form/Registration.php
Labels: master, merge on pass

#29250 Update template deprecation text, add one more string
  CRM/Event/Form/Registration/Confirm.php
  CRM/Utils/Token.php
Labels: master, merge on pass

#29212 don't create duplicate contacts when sending test emails
  api/v3/Mailing.php
  ext/civi_mail/ang/crmMailing/services.js
  tests/phpunit/api/v3/MailingTest.php
Labels: master, has-test

#29261 Move messageTemplate call out of create smarty
  CRM/Core/CodeGen/Schema.php
  CRM/Core/CodeGen/Util/MessageTemplates.php
  CRM/Core/CodeGen/Util/Smarty.php
  CRM/Core/CodeGen/Util/Template.php
  setup/src/Setup/SmartyUtil.php
Labels: master

#29184 Remove getTemplateVars() override now that it happens in Smarty2
  CRM/Core/SmartyCompatibility.php
Labels: master

#29259 dev/core#4905 - Use new customField getter in a few more places
  CRM/Core/BAO/CustomGroup.php
  CRM/Core/Permission.php
  Civi/Api4/Query/Api4SelectQuery.php
  ext/afform/admin/Civi/AfformAdmin/AfformAdminMeta.php
Labels: master

#29185 Update Smarty autoload constant to be version agnostic
  CRM/Core/Smarty.php
  CRM/Core/SmartyCompatibility.php
  CRM/Utils/Check/Component/Smarty.php
  templates/CRM/common/civicrm.settings.php.template
Labels: master

#29183 dev/core#4951 Add support for smarty debugging
  CRM/Utils/String.php
Labels: master

#29252 [php8.x] Clarify what `optionsMaxValueTotal` means
  CRM/Event/Form/Registration.php
Labels: master

#29255 [php8.x] Minor cleanup in priceSetOptionsCount
  CRM/Event/BAO/Participant.php
Labels: master

#29262 [Smarty-gencode] Try removing clearTemplateVars hack from test
  tests/phpunit/CRM/Contribute/Form/AdditionalPaymentTest.php
Labels: master

#29263 [Smarty-gencode] Remove clearAllVars from SessionTest
  tests/phpunit/CRM/Core/SessionTest.php
Labels: master

#29226 Php 8.x notice fix on tags & groups fields
  CRM/Contact/Form/Contact.php
  CRM/Contact/Form/Edit/TagsAndGroups.php
  CRM/Profile/Form.php
Labels: 5.70

#29266 [Smarty gencode] Clean up resourcesTest for Smarty3
  tests/phpunit/CRM/Core/ResourcesTest.php
Labels: master, merge on pass

#29264 don't send an extra receipt when completing pending contributions
  CRM/Contribute/Form/Contribution.php
Labels: merge on pass, merge ready, 5.70

#29267 5.70 to master
  CRM/Contact/Form/Contact.php
  CRM/Contact/Form/Edit/TagsAndGroups.php
  CRM/Contribute/Form/Contribution.php
  CRM/Profile/Form.php
Labels: master

#29265 [Smarty Gencode] Fixes on clearAllAssign
  CRM/Contribute/Form/Task/Invoice.php
  CRM/Core/Smarty.php
Labels: master, merge on pass

#29268 [REF] Cleanup - Replace illegible nested CRM_Utils_Array::value with ??
  CRM/Contribute/Form/ContributionBase.php
  CRM/Contribute/Form/Task/Invoice.php
  CRM/Core/BAO/UFGroup.php
  CRM/SMS/Form/Group.php
Labels: master

#29254 [php8.x] Clean up max value functionality
  CRM/Event/Form/Registration.php
  CRM/Event/Form/Registration/AdditionalParticipant.php
  CRM/Event/Form/Registration/Confirm.php
  CRM/Event/Form/Registration/Register.php
Labels: master, merge ready

#29276 Disable failing test in PR runs for now
  tests/phpunit/E2E/Core/LocalizedDataTest.php
Labels: 5.69

#29271 don't send an extra receipt when completing pending contributions
  CRM/Contribute/Form/Contribution.php
Labels: merge on pass, 5.69

#29277 Disable failing test in PR runs for now
  tests/phpunit/E2E/Core/LocalizedDataTest.php
Labels: 5.70

#29279 [Smarty-gencode] Switch createSmarty to use functions that work on v2,v3,v4
  CRM/Core/CodeGen/Util/Smarty.php
  CRM/Core/Smarty.php
  CRM/Core/Smarty/plugins/function.crmSqlData.php
  CRM/Core/Smarty/plugins/modifier.crmEscapeSingleQuotes.php
  CRM/Core/SmartyCompatibility.php
  setup/src/Setup/SmartyUtil.php
  tests/phpunit/CRM/Core/Smarty/plugins/CrmRSSPubDateTest.php
  tests/phpunit/CRM/Core/Smarty/plugins/HtxtTest.php
  xml/templates/dao.tpl
Labels: master

#29078 composer.json: Use current SPDX license identifier
  composer.json
Labels: master

#29197 [online-event] Fix misbehaving waitlist in master (unreleased regression)
  CRM/Event/Form/Registration/Confirm.php
  CRM/Event/Form/Registration/Register.php
  templates/CRM/Event/Form/Registration/Confirm.tpl
  templates/CRM/Event/Form/Registration/DisplayProfile.tpl
  templates/CRM/Event/Form/Registration/EventInfoBlock.tpl
  templates/CRM/Event/Form/Registration/Register.tpl
Labels: master

#29272 569 tag
  CRM/Contact/Form/Contact.php
  CRM/Contact/Form/Edit/TagsAndGroups.php
  CRM/Profile/Form.php
  templates/CRM/UF/Form/Fields.tpl
Labels: 5.69

#29281 ContributionBase - Remove unused code
  CRM/Contribute/Form/ContributionBase.php
Labels: master

#29283 [REF] Cleanup - Replace more nested CRM_Utils_Array::value with ??
  CRM/Contact/BAO/Query.php
  CRM/Contact/BAO/Relationship.php
  CRM/Contribute/BAO/Contribution.php
  CRM/Contribute/Form/Contribution.php
  CRM/Contribute/Form/Contribution/Confirm.php
  CRM/Member/Form/Membership.php
  CRM/Price/BAO/LineItem.php
  CRM/Report/Form.php
  CRM/Report/Utils/Report.php
Labels: master

#28735 Consolidate handling of line items in back office participant form
  CRM/Contribute/Form/AbstractEditPayment.php
  CRM/Event/Form/Participant.php
Labels: master

#28774 [Smarty-gencode] Load smarty3 in Gencode too
  CRM/Contribute/BAO/ContributionPage.php
  CRM/Contribute/BAO/ContributionSoft.php
  CRM/Core/CodeGen/Util/Smarty.php
  CRM/Core/CodeGen/Util/Template.php
  CRM/Core/Smarty.php
  CRM/Core/Smarty/plugins/block.crmScope.php
  setup/src/Setup/SmartyUtil.php
  templates/CRM/Price/Page/LineItem.tpl
  tests/phpunit/CRM/Contact/Page/View/UserDashBoardTest.php
  tests/phpunit/CRM/Core/RegionTest.php
  tests/phpunit/CRM/Core/Smarty/plugins/CrmScopeTest.php
  tests/phpunit/CRM/Core/Smarty/plugins/CrmUpperTest.php
  tests/phpunit/CRM/Core/Smarty/plugins/UrlTest.php
  tests/phpunit/CRM/Core/SmartyTest.php
  tests/phpunit/CRM/Utils/StringTest.php
  tests/phpunit/Civi/Core/UrlTest.php
Labels: master, merge on pass

#29193 Fix wonkyness if contribution page includes a profile with both groups & tags
  CRM/Contact/Form/Edit/TagsAndGroups.php
  templates/CRM/UF/Form/Fields.tpl
Labels: 5.70

#28492 Make name, title, frontend_title fields on UFGroup consistent with ContributionPage, Group
  CRM/Core/BAO/UFGroup.php
  CRM/Core/DAO/UFGroup.php
  CRM/Core/I18n/SchemaStructure.php
  CRM/UF/Form/Group.php
  CRM/Upgrade/Incremental/php/FiveSeventyOne.php
  CRM/Upgrade/Incremental/sql/5.71.alpha1.mysql.tpl
  Civi/Api4/Service/Spec/Provider/TitleFieldSpecProvider.php
  tests/phpunit/api/v3/UFGroupTest.php
  xml/schema/Core/UFGroup.xml
Labels: master

#29287 Clean up on clear_assign
  CRM/Core/Smarty.php
  CRM/Core/Smarty/plugins/block.crmScope.php
Labels: master, merge on pass

#29249 [php8.x] [online-event] [test] Use Order object rather than passed parameter to figure out if price field values use participant count
  CRM/Event/Form/Registration.php
  CRM/Financial/BAO/Order.php
  Civi/Test/FormWrapper.php
  tests/phpunit/CRM/Event/Form/Registration/ConfirmTest.php
Labels: master, merge on pass, comp-online-event-form

#29295 5.70
  CRM/Contact/Form/Edit/TagsAndGroups.php
  templates/CRM/UF/Form/Fields.tpl
Labels: master

#29260 dev/core#4969 Simplify AngularManager loading/caching system
  Civi/Angular/Manager.php
Labels: sig:regression, 5.70

#29280 [BACKPORT] dev/core#4969 Simplify AngularManager loading/caching system
  Civi/Angular/Manager.php
Labels: sig:regression, 5.69

#29105 dev/core#4918 On back office form check if participants are limited before eventFull check
  CRM/Event/Form/Participant.php
Labels: master, sig:unreleased-regression

#29251 dev/core#3381 [online-event] Fix wrong currency for online event[s
  templates/CRM/Event/Form/Registration/Confirm.tpl
  templates/CRM/Event/Form/Registration/ThankYou.tpl
Labels: master, comp-online-event-form

#29289 Register native php functions that we use as smarty plugins
  CRM/Core/CodeGen/Util/Smarty.php
  CRM/Core/Smarty.php
  setup/src/Setup/SmartyUtil.php
Labels: master

#29301 Fix master-only regression on saving event info when no custom data applies
  CRM/Custom/Form/CustomDataTrait.php
Labels: master, merge on pass, sig:unreleased-regression

#29244 [online-event] PHP8.2 stop unnecessarily setting undefined Properties in event thankyou
  CRM/Event/Form/Registration/Confirm.php
  CRM/Event/Form/Registration/ThankYou.php
Labels: master

#29297 WP - Handle updated permissions format
  CRM/ACL/Form/WordPress/Permissions.php
Labels: master

#29258 APIv4 - Add type hints to Result object
  Civi/Api4/Generic/Result.php
Labels: master

#29304 Fix notices on event info page
  templates/CRM/Event/Page/EventInfo.tpl
Labels: master, merge on pass

#29303 Drupal.civi-setup: setAuthorized if running via drush
  setup/plugins/init/Drupal.civi-setup.php
Labels: master, merge on pass

#29239 [online-event] Fix typing on fee level
  CRM/Contribute/BAO/Contribution.php
  CRM/Event/BAO/Participant.php
  CRM/Event/Form/Participant.php
  CRM/Event/Form/Registration/Confirm.php
Labels: master, merge on pass, comp-online-event-form

#29296 Fix dev/core#4959 - Handle extra whitespace in scheduled job params
  CRM/Core/BAO/Job.php
Labels: sig:regression, 5.70

#29300 dev/core#4980 Ensure payment processor object is returned
  CRM/Financial/Form/PaymentProcessorFormTrait.php
Labels: 5.70

#29316 Afform - Reduce noise in mgd.php file
  ext/afform/core/managed/AfformType.mgd.php
Labels: master, merge on pass

#29312 dev/core#4973 Fix credit card info not showing up in ThankYou & Confirm
  CRM/Event/Form/Registration.php
Labels: 5.70

#29302 Deprecate a couple of backward compatibility Smarty functions
  CRM/Core/Smarty.php
  CRM/Core/SmartyCompatibility.php
Labels: master, merge on pass

#29309 dev/core#4974 Fix total fees over-sharing
  CRM/Event/Form/Registration/Register.php
  templates/CRM/Event/Page/EventInfo.tpl
Labels: master

#29317 [BACKPORT] Fix dev/core#4959 - Handle extra whitespace in scheduled job params
  CRM/Core/BAO/Job.php
Labels: merge on pass, 5.69

#29319 5.70
  CRM/Core/BAO/Job.php
  CRM/Event/Form/Registration.php
  CRM/Financial/Form/PaymentProcessorFormTrait.php
  Civi/Angular/Manager.php
Labels: master

#29314 dev/core#4980 Ensure payment processor object is returned
  CRM/Financial/Form/PaymentProcessorFormTrait.php
Labels: 5.69

#29320 dev/core#4973 Fix credit card info not showing up in ThankYou & Confirm (5.69)
  CRM/Event/Form/Registration.php
Labels: merge on pass, 5.69

#29293 Fix dev/core#4971 - Skip redundant permission checks in ScheduleReminder form
  CRM/Admin/Form/ScheduleReminders.php
Labels: 5.70

#29322 setting-admin@1 - Bump version
  mixin/setting-admin@1/mixin.php
Labels: master

#29294 [BACKPORT] Fix dev/core#4971 - Skip redundant permission checks in ScheduleReminder form
  CRM/Admin/Form/ScheduleReminders.php
Labels: sig:regression, 5.69

#29310 Fix Smarty Notices on Event confirm & thank you pages
  CRM/Event/Form/Registration/Confirm.php
  templates/CRM/Event/Form/Registration/Confirm.tpl
  templates/CRM/Event/Form/Registration/EventInfoBlock.tpl
  templates/CRM/Event/Form/Registration/ThankYou.tpl
Labels: master, merge on pass

#29290 Fix dev/core#4949 ScheduleReminder form required field error
  templates/CRM/Admin/Form/ScheduleReminders.tpl
Labels: sig:regression, 5.70

#29291 [BACKPORT] Fix dev/core#4949 ScheduleReminder form required field error
  templates/CRM/Admin/Form/ScheduleReminders.tpl
Labels: sig:regression, 5.69

#29323 Stop using intval in smarty
  templates/CRM/Contact/Form/Contact.tpl
  templates/CRM/Price/Page/LineItem.tpl
Labels: master

#29321 Use upper not strtoupper in Smarty as that is supported going forwards
  xml/templates/dao.tpl
Labels: master

#29306 Stop burying the lead
  templates/CRM/Event/Form/ManageEvent/EventInfo.tpl
Labels: master

#29141 Fix misunderstanding about return value of getKeyId
  CRM/Core/BAO/CustomField.php
  CRM/Core/BAO/UFGroup.php
Labels: master, merge ready

#29324 5.70.0 release notes
  release-notes.md
  release-notes/5.70.0.md
Labels: 5.70

#29292 dev/core#4951 Remove text version of online event receipt in 5.69 - known to cause errors with Smarty3
  tests/phpunit/CRM/Core/Payment/BaseIPNTest.php
  tests/phpunit/CRM/Event/Form/Registration/ConfirmTest.php
  tests/phpunit/api/v3/ContributionTest.php
  tests/phpunit/api/v3/PaymentTest.php
  xml/templates/message_templates/event_online_receipt_text.tpl
Labels: merge ready, 5.69

#29222 Fix a couple of notices on event dashboard
  templates/CRM/Event/Form/Selector.tpl
Labels: master, merge on pass

#29195 dev/core#4948 Fix online_receipt template to include receipt text
  CRM/Contribute/BAO/Contribution.php
  CRM/Contribute/BAO/ContributionPage.php
  api/v3/Contribution.php
  api/v3/MessageTemplate.php
  xml/templates/message_templates/contribution_online_receipt_html.tpl
Labels: 5.70

#29273 Fix online_receipt template to include receipt text
  CRM/Contribute/BAO/Contribution.php
  CRM/Contribute/BAO/ContributionPage.php
  api/v3/Contribution.php
  api/v3/MessageTemplate.php
  xml/templates/message_templates/contribution_online_receipt_html.tpl
Labels: 5.69

#29275 dev/core#4963 Fix validation error on membership renew with auto-renew
  CRM/Contribute/Form/Contribution/Confirm.php
  CRM/Contribute/Form/Contribution/Main.php
  CRM/Core/Form.php
  CRM/Price/BAO/LineItem.php
Labels: 5.70

#29326 Ensure currency is set on back office participant form
  CRM/Event/Form/Participant.php
Labels: 5.70

#29315 Ensure currency is set on back office participant form
  CRM/Core/Payment/Dummy.php
  CRM/Event/Form/Participant.php
Labels: 5.69

#29190 dev/core#4953 Fix failure to show existing membership type in renewal mode
  CRM/Contribute/Form/Contribution/Main.php
Labels: merge on pass, 5.70

#29274 dev/core#4953 Fix failure to show existing membership type in renewal mode
  CRM/Contribute/Form/Contribution/Main.php
Labels: merge on pass, 5.69

#29202 Fix 5.67 regression on loading custom data defaults on contribution page
  CRM/Contribute/Form/Contribution/Main.php
Labels: 5.69

#29331 5.70
  CRM/Admin/Form/ScheduleReminders.php
  CRM/Contribute/BAO/Contribution.php
  CRM/Contribute/BAO/ContributionPage.php
  CRM/Contribute/Form/Contribution/Confirm.php
  CRM/Contribute/Form/Contribution/Main.php
  CRM/Core/Form.php
  CRM/Event/Form/Participant.php
  CRM/Price/BAO/LineItem.php
  api/v3/Contribution.php
  api/v3/MessageTemplate.php
  release-notes.md
  release-notes/5.70.0.md
  templates/CRM/Admin/Form/ScheduleReminders.tpl
  xml/templates/message_templates/contribution_online_receipt_html.tpl
Labels: master

#29284 Remove incorrectly placed ChangeCaseStatus class properties and convert one of them to a local var
  CRM/Case/Form/Activity.php
  CRM/Case/Form/Activity/ChangeCaseStatus.php
  tests/phpunit/CRM/Case/BAO/CaseTest.php
Labels: master

#29330 Ensure currency is set various forms
  CRM/Contribute/Form/Contribution/Confirm.php
  CRM/Contribute/Form/ContributionBase.php
  CRM/Member/Form/MembershipRenewal.php
Labels: 5.70

#29327 Backport fix on currency not set
  CRM/Contribute/Form/ContributionBase.php
Labels: 5.69

#29333 5.70
  CRM/Contribute/Form/Contribution/Confirm.php
  CRM/Contribute/Form/ContributionBase.php
  CRM/Member/Form/MembershipRenewal.php
Labels: master

#29332 5.70
  CRM/Contribute/Form/Contribution/Confirm.php
  CRM/Contribute/Form/ContributionBase.php
  CRM/Member/Form/MembershipRenewal.php
Labels: master

#29334 5.69.5 - Add notes. Set version.
  ext/afform/admin/info.xml
  ext/afform/core/info.xml
  ext/afform/html/info.xml
  ext/afform/mock/info.xml
  ext/authx/info.xml
  ext/civi_campaign/info.xml
  ext/civi_case/info.xml
  ext/civi_contribute/info.xml
  ext/civi_event/info.xml
  ext/civi_mail/info.xml
  ext/civi_member/info.xml
  ext/civi_pledge/info.xml
  ext/civi_report/info.xml
  ext/civicrm_admin_ui/info.xml
  ext/civicrm_search_ui/info.xml
  ext/civigrant/info.xml
  ext/civiimport/info.xml
  ext/ckeditor4/info.xml
  ext/contributioncancelactions/info.xml
  ext/elavon/info.xml
  ext/eventcart/info.xml
  ext/ewaysingle/info.xml
  ext/financialacls/info.xml
  ext/flexmailer/info.xml
  ext/greenwich/info.xml
  ext/legacycustomsearches/info.xml
  ext/message_admin/info.xml
  ext/oauth-client/info.xml
  ext/payflowpro/info.xml
  ext/recaptcha/info.xml
  ext/scheduled_communications/info.xml
  ext/search_kit/info.xml
  ext/sequentialcreditnotes/info.xml
  ext/standaloneusers/info.xml
  ext/user_dashboard/info.xml
  js/version.json
  release-notes.md
  release-notes/5.69.5.md
  sql/civicrm_generated.mysql
  sql/test_data_second_domain.mysql
  xml/version.xml
Labels: 5.69

#29285 SMS tasks, use shared trait, move some functions to it
  CRM/Activity/Form/Task/SMS.php
  CRM/Contact/Form/Task/SMS.php
  CRM/Contact/Form/Task/SMSTrait.php
Labels: master

#29238 Fix Smarty notice when a single contact is deleted (not from search)
  CRM/Contact/Form/Task/Delete.php
Labels: master

#29147 Remove unused paramter (was to support email forward deprecated function - but that no longer calls this)
  CRM/Mailing/ActionTokens.php
  CRM/Mailing/BAO/Mailing.php
  CRM/Mailing/Event/BAO/MailingEventResubscribe.php
  CRM/Mailing/Event/BAO/MailingEventUnsubscribe.php
  ext/flexmailer/src/Listener/BasicHeaders.php
  ext/flexmailer/src/Listener/BounceTracker.php
Labels: master

#29245 Fix php8.x issues in payment form
  CRM/Core/Payment/ProcessorForm.php
  CRM/Financial/Form/Payment.php
Labels: master

#29336 [NFC] Remove redundant deprecated checks for assertObjectHasAttribute
  tests/phpunit/CRM/Case/BAO/CaseTest.php
  tests/phpunit/CRM/Core/BAO/NavigationTest.php
Labels: master, merge on pass

#29288 Run tests on Smarty4 instead of 3
  CRM/Core/CodeGen/Util/Smarty.php
  setup/src/Setup/SmartyUtil.php
  xml/templates/dao.tpl
Labels: master, merge ready

#29299 dev/core#3381 Fix currency display on total fees
  CRM/Event/Form/Registration.php
Labels: master

#29335 [NFC] Deprecated class name for abstract classes in phpunit
  ext/flexmailer/tests/phpunit/Civi/FlexMailer/FlexMailerSystemTest.php
  tests/phpunit/CRM/Mailing/MailingSystemTest.php
  tests/phpunit/CRM/Mailing/MailingSystemTestBase.php
  tests/phpunit/CRM/Mailing/MultilingualSystemTest.php
Labels: master, merge on pass

#29337 Add str_starts_with modifier to Smarty
  CRM/Core/Smarty.php
  CRM/Event/BAO/Event.php
  templates/CRM/Event/Form/Registration/ThankYou.tpl
  templates/CRM/UF/Form/Fields.tpl
Labels: master, merge on pass

#29325 dev/core#4821 - APIv4: Allow custom field to reference value in bridge joins
  CRM/Core/Reference/Basic.php
  CRM/Core/Reference/Dynamic.php
  Civi/Api4/Query/Api4SelectQuery.php
  Civi/Api4/Service/Schema/Joinable/ExtraJoinable.php
  Civi/Api4/Service/Schema/Joinable/Joinable.php
  tests/phpunit/api/v4/Custom/ContactCustomJoinTest.php
Labels: master, has-test

#29339 Unshare the SMSCommon::preProcess function between the
  CRM/Activity/Form/Task/SMS.php
  CRM/Contact/Form/Task/SMS.php
  CRM/Contact/Form/Task/SMSCommon.php
  CRM/Contact/Form/Task/SMSTrait.php
Labels: master, merge on pass

#29340 [NFC] CoreExt - Cleanup boilerplate from extension readmes
  ext/afform/html/README.md
  ext/afform/html/images/screenshot.png
  ext/authx/images/screenshot.png
  ext/civiimport/README.md
  ext/civiimport/images/screenshot.png
  ext/ckeditor4/README.md
  ext/ckeditor4/images/screenshot.png
  ext/eventcart/images/screenshot.png
  ext/ewaysingle/README.md
  ext/ewaysingle/images/screenshot.png
  ext/financialacls/README.md
  ext/financialacls/images/screenshot.png
  ext/legacycustomsearches/README.md
  ext/legacycustomsearches/images/screenshot.png
  ext/message_admin/README.md
  ext/message_admin/images/screenshot.png
  ext/payflowpro/README.md
  ext/payflowpro/images/screenshot.png
Labels: master, merge on pass

#29341 EventCart - Update readme to reflect current state
  ext/eventcart/README.md
Labels: master, merge ready

#29346 5.70 to master
  CRM/Core/Smarty.php
Labels: master

#29344 Fix clearAssign for php8.x
  CRM/Core/Smarty.php
Labels: merge on pass, 5.69

#29345 CryptoJwt - Fix detection of firebase/php-jwt APIs
  Civi/Crypto/CryptoJwt.php
Labels: 5.70

#29348 Fix BackOffice Membership forms getPriceSetID() to be standard
  CRM/Core/Form.php
  CRM/Member/Form.php
  CRM/Member/Form/Membership.php
  ext/contributioncancelactions/tests/phpunit/CancelTest.php
  tests/phpunit/CRM/Event/Form/ParticipantTest.php
Labels: master

#29358 dev/core#4390 remove unused code that results in errors for multiple participant registration
  CRM/Event/BAO/Event.php
Labels: merge on pass, 5.71

#29359 5.71 to master
  CRM/Event/BAO/Event.php
Labels: master

#29364 dev/core#4999 [REF] - Extract some methods from CodeGen into a utility class
  CRM/Core/CodeGen/Specification.php
  CRM/Utils/Schema.php
  xml/templates/dao.tpl
Labels: master, merge ready

#29365 dev/core#4999 - [REF] Add DAO::getExtensionName() and DAO:: getTableAddVersion()
  CRM/Core/DAO.php
Labels: master

#29367 [REF] DAO - Consolidate redundant functions keys() and getPrimaryKey()
  CRM/Core/DAO.php
  ext/civiimport/Civi/BAO/Import.php
  ext/search_kit/Civi/BAO/SK_Entity.php
Labels: master
