Repository civicrm/civicrm-core, pull requests merged in 2024-08, with the labels that each got.

#30784 Fully switch unit tests over to Smarty5
  CRM/Core/CodeGen/Util/MessageTemplates.php
  CRM/Core/CodeGen/Util/Smarty.php
  setup/src/Setup/SmartyUtil.php
  templates/CRM/common/civicrm.settings.php.template
Labels: 5.76

#30783 dev/core#5063 - Show backend title instead of internal name when configuring payment processor on events
  CRM/Event/Form/ManageEvent/Fee.php
Labels: master

#30779 Upgrade Font Awesome v4 => v6
  CRM/Core/Resources/Common.php
  Civi/Standalone/WebEntrypoint.php
  composer.json
  css/crm-i-v4-shims.css
  css/crm-i.css
  css/crm-iconPicker.css
  css/crm-menubar.css
  css/dashboard.css
  js/jquery/jquery.crmIconPicker.js
  tools/standalone/router.php
Labels: master, merge ready

#30781 Make `civicrm_queue.name` & `civicrm_queue.name` field longer
  CRM/Upgrade/Incremental/php/FiveSeventySeven.php
  schema/Queue/Queue.entityType.php
  schema/Queue/QueueItem.entityType.php
Labels: master, merge on pass

#30789 fixes incorrect display of tag field label in profiles
  CRM/Contact/Form/Edit/TagsAndGroups.php
Labels: master

#30790 Adding custom multi-value record leads to fatal "no valid value for tableId"
  CRM/Contact/Form/CustomData.php
Labels: master, merge on pass

#30791 Bring hash in composer.lock up to date
  composer.lock
Labels: master

#30795 Afform - Add a unit test for creating event from a template
  ext/afform/core/Civi/Api4/Action/Afform/Prefill.php
  ext/afform/mock/tests/phpunit/api/v4/Afform/AfformEventUsageTest.php
Labels: master

#30782 Add missing provinces for Moldova
  CRM/Upgrade/Incremental/sql/5.77.alpha1.mysql.tpl
  xml/templates/civicrm_state_province.tpl
Labels: master

#30799 Regen after 30782
  sql/civicrm_generated.mysql
Labels: master

#30800 dev/core#5373 Do not round Amount field on quick configuartion on bac…
  CRM/Event/Form/ManageEvent/Fee.php
Labels: master, merge on pass

#30802 [REF] Fix link when copying a mass SMS to not create a new mailing an…
  CRM/Mailing/Selector/Browse.php
Labels: master, merge on pass

#30804 dev/core#5381 Do not round Amounts on quick config fees on Contributio…
  CRM/Contribute/Form/ContributionPage/Amount.php
Labels: master, merge on pass

#30805 I am Dave (A bit more obvious deprecation)
  templates/CRM/common/jcalendar.tpl
Labels: master, merge on pass

#30808 Stop passing variable that is not in function signature
  CRM/Export/BAO/Export.php
Labels: master

#30810 Update contributor-key.yml
  contributor-key.yml
Labels: master

#30787 Trigger search kit refresh for non-popup form submits
  ext/search_kit/ang/crmSearchDisplay/traits/searchDisplayBaseTrait.service.js
  ext/search_kit/ang/crmSearchTasks/traits/searchDisplayTasksTrait.service.js
Labels: master, merge ready

#30807 dev/core#5370 Fix Civi-import import-mapping saving issues
  CRM/Contribute/Import/Form/MapField.php
  CRM/Import/Forms.php
  ext/civiimport/ang/crmCiviimport.js
Labels: 5.76

#30815 5.76 to master
  CRM/Contribute/Import/Form/MapField.php
  CRM/Import/Forms.php
  ext/civiimport/ang/crmCiviimport.js
Labels: master

#30818 dev/core#5370 Fix bug handling soft credits in civi-import
  ext/civiimport/ang/crmCiviimport.js
Labels: merge on pass, 5.75

#30821 Installer - Fix activation for new defaults
  setup/plugins/init/DefaultExtensions.civi-setup.php
  sql/civicrm_data/civicrm_extension.sqldata.php
  sql/civicrm_generated.mysql
  tests/phpunit/CRM/Contribute/Import/Parser/ContributionTest.php
Labels: run-extended-tests, 5.76

#30823 Merge forward 5.76=>master
  setup/plugins/init/DefaultExtensions.civi-setup.php
  sql/civicrm_data/civicrm_extension.sqldata.php
  sql/civicrm_generated.mysql
  tests/phpunit/CRM/Contribute/Import/Parser/ContributionTest.php
Labels: master

#30813 [REF] Standardise is_bulk_mail select
  CRM/Contact/Form/Edit/Email.php
  templates/CRM/Contact/Form/Edit/Email.tpl
  templates/CRM/Contact/Page/View/Summary.js
  templates/CRM/common/additionalBlocks.tpl
Labels: master

#30822 Update contributor-key.yml
  contributor-key.yml
Labels: master

#30825 Upgrade crash on mailing backfill
  CRM/Upgrade/Incremental/php/FiveSeventySix.php
Labels: 5.77

#30826 upgrade crash
  CRM/Upgrade/Incremental/php/FiveSeventySix.php
Labels: merge on pass, 5.76

#30827 5.77
  CRM/Upgrade/Incremental/php/FiveSeventySix.php
Labels: master

#30830 prevent grant dashboard URLs leading to data loss
  ext/civigrant/CRM/Grant/BAO/Query.php
  ext/civigrant/CRM/Grant/Form/Search.php
  ext/civigrant/templates/CRM/Grant/Page/DashBoard.tpl
Labels: master

#30831 Backdrop - Fix MockPublicFormTest. Ensure session is committed during redirect.
  CRM/Utils/System/Backdrop.php
Labels: master

#30820 Settings form tidy-ups (apiv3-v4, `CRM_Utils_Array::value()`, save integers as integers)
  CRM/Admin/Form/SettingTrait.php
Labels: master

#30735 ensure we get correct resourceurl in backdrop
  CRM/Utils/System/Backdrop.php
Labels: master, run-extended-tests

#30798 dev/core#5336 Remove non active groups from cloned mailing #5336
  CRM/Mailing/Controller/Send.php
Labels: master, merge ready

#30837 Backport 30834
  CRM/Member/BAO/Membership.php
Labels: 5.76

#30836 5.77
  CRM/Member/BAO/Membership.php
Labels: master

#30838 (dev/core#5386) Fix translation for relationship types on Membership …
  CRM/Member/Form/MembershipView.php
Labels: master

#30839 Fix crash on membership view for related memberships
  CRM/Member/Form/MembershipView.php
Labels: 5.77

#30842 5.77 to master
  CRM/Member/Form/MembershipView.php
Labels: master

#30832 Remove default escaping for Smarty2
  CRM/Core/Smarty.php
Labels: master

#30846 Backport 30839 - crash on membership view
  CRM/Member/Form/MembershipView.php
Labels: 5.76

#30852 Fix LabelTest to use full form flow
  tests/phpunit/CRM/Contact/Form/Task/PrintMailingLabelTest.php
Labels: master, merge on pass

#30864 Remove function with noisy deprecation since 2022: replaceCaseTokens
  CRM/Utils/Token.php
Labels: master

#30855 Remove unused private function
  CRM/Mailing/BAO/Mailing.php
Labels: master

#30858 [PHP8.x] Ensure value is a string (not NULL) before passing to trim
  CRM/Core/BAO/Address.php
Labels: master

#30859 Notice fixes
  CRM/Core/BAO/Address.php
Labels: master

#30865 Stop passing value to unused function within tests
  tests/phpunit/CRM/Mailing/MultilingualSystemTest.php
  tests/phpunit/api/v3/MailingTest.php
Labels: master

#30814 Api4 Explorer - Document new 2nd param to column() function
  ang/api4Explorer/Explorer.js
Labels: master

#30850 provide correct collation to SK entities
  CRM/Core/BAO/CustomField.php
  CRM/Core/BAO/SchemaHandler.php
  tests/phpunit/CRM/Core/BAO/CustomFieldTest.php
Labels: master

#30861 Remove unreachable code
  CRM/Contact/Form/Task/Label.php
Labels: master

#30851 Stop passing unused variables not in the function signature
  CRM/Contact/Form/Task/Label.php
  CRM/Member/Form/Task/Label.php
Labels: master

#30872 (dev/core#5398) distmaker - Add tellafriend
  distmaker/core-ext.txt
Labels: merge on pass, 5.77

#30873 (dev/core#5398) distmaker - Add tellafriend
  distmaker/core-ext.txt
Labels: 5.76

#30875 5.77 to master
  distmaker/core-ext.txt
Labels: master

#30854 [NFC] Label test update to allow more tests to be added
  tests/phpunit/CRM/Contact/Form/Task/PrintMailingLabelTest.php
Labels: master, has-test

#30868 dev/core#5388 don't create a logging table for SearchKit entities
  CRM/Logging/Schema.php
Labels: master

#30671 SearchKit - Support joins from DB Entity Displays (using EntityRepository for metadata)
  Civi/Api4/Generic/Traits/EntityBridge.php
  Civi/Api4/Query/SqlExpression.php
  Civi/Api4/Query/SqlFunctionGROUP_CONCAT.php
  Civi/Api4/Service/Schema/SchemaMapBuilder.php
  Civi/Api4/Service/Spec/SpecFormatter.php
  Civi/Api4/Service/Spec/SpecGatherer.php
  Civi/Schema/EntityProvider.php
  Civi/Schema/LegacySqlEntityMetadata.php
  ext/civiimport/Civi/Api4/Import/ImportSpecProvider.php
  ext/civiimport/Civi/BAO/Import.php
  ext/search_kit/Civi/Api4/Event/Subscriber/SKEntitySubscriber.php
  ext/search_kit/Civi/Api4/Service/Spec/Provider/SKEntitySpecProvider.php
  ext/search_kit/Civi/Schema/SkEntityMetaProvider.php
  ext/search_kit/Civi/Search/Admin.php
  ext/search_kit/search_kit.php
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/EntityDisplayTest.php
  tests/phpunit/api/v4/Action/GetFieldsTest.php
  tests/phpunit/api/v4/Spec/SpecFormatterTest.php
Labels: master, has-test

#30881 5.77.0 release notes initial run
  release-notes.md
  release-notes/5.77.0.md
Labels: 5.77

#30882 5.77 to master
  release-notes.md
  release-notes/5.77.0.md
Labels: master

#30835 Update distmaker for flat standalone tarball
  distmaker/dists/standalone.sh
Labels: master, merge ready

#30876 (REF) distmaker - Generate live list of core extensions
  distmaker/core-ext.txt
  distmaker/dists/common.sh
  tools/bin/scripts/ls-core-ext
  tools/bin/scripts/set-version.php
Labels: master

#30879 Fix saving entity display with money calculated field
  ext/search_kit/Civi/Api4/Event/Subscriber/SKEntitySubscriber.php
Labels: master

#30729 [REF] Fix empty headers in schedule reminders and dedupe rules page
  templates/CRM/Admin/Page/Reminders.tpl
  templates/CRM/Contact/Page/DedupeRules.tpl
Labels: master, sig:accessibility

#30728 APIv4 - Ensure custom fields are always correctly serialized (with cleanup)
  CRM/Core/BAO/CustomValueTable.php
  CRM/Core/DAO.php
  tests/phpunit/api/v4/Custom/CreateCustomValueTest.php
  tests/phpunit/api/v4/Custom/CustomValueTest.php
Labels: master, has-test

#30794 Afform - Fix missing labels
  ext/afform/core/ang/af/afField.html
Labels: sig:unreleased-regression, 5.77

#30895 5.76.2 - Add notes. Set version.
  ext/afform/admin/info.xml
  ext/afform/core/info.xml
  ext/afform/html/info.xml
  ext/afform/mock/info.xml
  ext/authx/info.xml
  ext/civi_campaign/info.xml
  ext/civi_case/info.xml
  ext/civi_contribute/info.xml
  ext/civi_event/info.xml
  ext/civi_mail/info.xml
  ext/civi_member/info.xml
  ext/civi_pledge/info.xml
  ext/civi_report/info.xml
  ext/civicrm_admin_ui/info.xml
  ext/civicrm_search_ui/info.xml
  ext/civigrant/info.xml
  ext/civiimport/info.xml
  ext/ckeditor4/info.xml
  ext/contributioncancelactions/info.xml
  ext/elavon/info.xml
  ext/eventcart/info.xml
  ext/ewaysingle/info.xml
  ext/financialacls/info.xml
  ext/flexmailer/info.xml
  ext/greenwich/info.xml
  ext/iframe/info.xml
  ext/legacycustomsearches/info.xml
  ext/message_admin/info.xml
  ext/oauth-client/info.xml
  ext/oembed/info.xml
  ext/payflowpro/info.xml
  ext/recaptcha/info.xml
  ext/scheduled_communications/info.xml
  ext/search_kit/info.xml
  ext/sequentialcreditnotes/info.xml
  ext/standaloneusers/info.xml
  ext/tellafriend/info.xml
  ext/user_dashboard/info.xml
  js/version.json
  release-notes.md
  release-notes/5.76.2.md
  sql/civicrm_generated.mysql
  sql/test_data_second_domain.mysql
  xml/version.xml
Labels: 5.76

#30896 Tell-a-friend fixes to Manage event
  CRM/Event/Form/ManageEvent.php
  CRM/Event/Form/ManageEvent/TabHeader.php
  CRM/Event/Page/ManageEvent.php
  ext/tellafriend/tellafriend.php
Labels: merge on pass, 5.77

#30897 Tell-a-friend fixes to Manage event
  CRM/Event/Form/ManageEvent.php
  CRM/Event/Form/ManageEvent/TabHeader.php
  CRM/Event/Page/ManageEvent.php
  ext/tellafriend/tellafriend.php
Labels: merge on pass, 5.76

#30892 Remove function whose only remaining caller is itself
  CRM/Mailing/BAO/Mailing.php
Labels: master

#30853 Fix object type in comment
  CRM/Contact/Form/Task.php
Labels: master

#30894 Add update link for pcp
  schema/PCP/PCP.entityType.php
Labels: master

#30690 [REF] Fix Screen reader accessibility of attachment fields
  templates/CRM/Form/attachment.tpl
Labels: master, sig:accessibility

#30883 dev/core#5395 ensure number assigned
  CRM/Member/Form/Membership.php
Labels: merge ready, 5.77

#30743 [NFC] Add test to demonstrate error passing in empty array for checkb…
  tests/phpunit/api/v4/Custom/CreateCustomValueTest.php
Labels: master, merge on pass

#30903 5.77 to master
  CRM/Event/Form/ManageEvent.php
  CRM/Event/Form/ManageEvent/TabHeader.php
  CRM/Event/Page/ManageEvent.php
  CRM/Member/Form/Membership.php
  ext/afform/core/ang/af/afField.html
  ext/tellafriend/tellafriend.php
Labels: master

#30886 Remove unused functions
  CRM/Contact/Form/Task/PDFLetterCommon.php
  CRM/Core/Form/Task/PDFLetterCommon.php
  CRM/Core/SelectValues.php
  settings/Core.setting.php
Labels: master

#30754 avoid openlayers error: string literal contains an unescaped line break
  CRM/Contact/BAO/Contact/Location.php
Labels: master

#30889 Unwind legacy flexmailer hack of specifying functions in a define
  CRM/Mailing/BAO/MailingJob.php
  CRM/Mailing/Info.php
  CRM/Utils/Token.php
  api/v3/Mailing.php
  ext/flexmailer/flexmailer.php
Labels: master

#30905 distmaker - My eyes! My eyes are bleeding! Make it stop!
  distmaker/distmaker.sh
  distmaker/dists/backdrop_php5.sh
  distmaker/dists/common.sh
  distmaker/dists/drupal7_dir_php5.sh
  distmaker/dists/drupal_php5.sh
  distmaker/dists/drupal_sk_php5.sh
  distmaker/dists/joomla_php5.sh
  distmaker/dists/l10n.sh
  distmaker/dists/patchset.sh
  distmaker/dists/repo-report.sh
  distmaker/dists/standalone.sh
  distmaker/dists/wordpress_php5.sh
Labels: master, merge ready, run-distmaker

#30904 distmaker - Rename root-folder for civicrm-X.Y.Z-standalone.tar.gz
  distmaker/dists/standalone.sh
Labels: master, run-distmaker

#30890 Remove unreachable code.
  CRM/Mailing/BAO/Mailing.php
  ext/flexmailer/src/Listener/Abdicator.php
Labels: master

#30884 dev/core#5395 ensure number assigned
  CRM/Member/Form/Membership.php
Labels: 5.76

#30909 Remove unused deprecated token function
  CRM/Utils/Token.php
Labels: master

#30908 Deprecate unused token function
  CRM/Utils/Token.php
Labels: master

#30910 Update CRM_Core_Resources::isAjaxMode to handle more ajax paths
  CRM/Core/Resources.php
  tests/phpunit/CRM/Core/ResourcesTest.php
Labels: master, has-test

#30869 Add test for groups assigned to unsubscribe, minor clean up
  CRM/Mailing/Event/BAO/MailingEventUnsubscribe.php
  CRM/Mailing/Form/Unsubscribe.php
  Civi/Test/FormTrait.php
  Civi/Test/MailingTestTrait.php
  tests/phpunit/CRM/Mailing/Form/UnsubscribeTest.php
Labels: master, has-test

#30849 Extract lines to add Address custom data to view
  CRM/Contact/Page/View/Summary.php
Labels: master

#30848 Extract the custom data template part for the address
  templates/CRM/Contact/Page/Inline/Address.tpl
  templates/CRM/Contact/Page/Inline/BlockCustomData.tpl
Labels: master

#30857 Add unit test for token rendering in Labels
  tests/phpunit/CRM/Contact/Form/Task/PrintMailingLabelTest.php
Labels: master, has-test

#30891 Deprecate tokenIsFound check
  CRM/Contact/Form/Task/Label.php
  CRM/Contact/Form/Task/LabelCommon.php
Labels: master

#30844 Standalone installation UI: matches confirmation page fonts & panel with pre-install page
  setup/res/finished.Standalone.php
  setup/res/template.css
Labels: master

#30880 SearchKit - Refresh entity list after saving a DB entity display
  ext/search_kit/CRM/Search/Page/AJAX.php
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdminImport.component.js
  ext/search_kit/ang/crmSearchAdmin/displays/searchAdminDisplayEntity.decorator.js
  ext/search_kit/xml/Menu/search_kit.xml
Labels: master

#30843 Add ability to edit email custom data to Email inline edit
  CRM/Contact/Form/Edit/BlockCustomDataTrait.php
  CRM/Contact/Form/Edit/EmailBlockTrait.php
  CRM/Contact/Form/Inline.php
  CRM/Contact/Form/Inline/Email.php
  templates/CRM/Contact/Form/Inline/BlockCustomData.tpl
  templates/CRM/Contact/Form/Inline/Email.tpl
  templates/CRM/Contact/Page/View/Summary.js
Labels: master

#30888 Add deprecation notices to a couple more token functions with no undeprecated core callers
  CRM/Utils/Token.php
Labels: master

#30893 Remove legacy handling for Joomla not supporting permissions
  CRM/PCP/Page/PCPInfo.php
Labels: master

#30812 Determine instance more transparently
  CRM/Contact/Form/Contact.php
Labels: master

#30900 dev/core#5390 enable UI setting admin for standaloneusers
  ext/standaloneusers/info.xml
  ext/standaloneusers/managed/SavedSearch_Administer_UserAccounts.mgd.php
  ext/standaloneusers/settings/standaloneusers.setting.php
Labels: master

#30914 [NFC] Fix typo in function description
  Civi/Api4/Query/SqlFunctionTIME.php
Labels: master

#30915 Afform - Fix display value in select & autocomplete widgets
  ext/afform/admin/ang/afGuiEditor/afGuiFieldValue.directive.js
Labels: sig:unreleased-regression, 5.77

#30917 5.77 to master
  ext/afform/admin/ang/afGuiEditor/afGuiFieldValue.directive.js
Labels: master

#30860 Add tests for tokens & address merge in label test
  tests/phpunit/CRM/Contact/Form/Task/PrintMailingLabelTest.php
Labels: master, has-test

#30913 dev/core#5403 fix crash installing an extension that provides an EntityBridge
  CRM/Core/Config.php
Labels: master, sig:unreleased-regression, run-extended-tests

#30916 Stop calculating unused variable
  CRM/Contact/Form/Task/Label.php
Labels: master

#30920 Afform - Fix new test-failures on php74
  ext/afform/core/Civi/Afform/Utils.php
Labels: 5.77

#30926 Fix just-merged rebase error
  CRM/Contact/Page/View/Summary.php
Labels: master, merge on pass

#30921 Use Smarty5 by default on new installs
  CRM/Utils/Check/Component/Smarty.php
  templates/CRM/common/civicrm.settings.php.template
Labels: master, merge on pass, run-extended-tests

#30928 5.77 to master
  ext/afform/core/Civi/Afform/Utils.php
Labels: master

#30927 [REF] Allow System Admins to override the file permissions set by Pea…
  CRM/Core/Error.php
  templates/CRM/common/civicrm.settings.php.template
Labels: master, merge ready

#30931 Update zeta-components/mail (1.9.4->1.9.6) & zeta-components/base (19.3->1.9.4)
  composer.lock
Labels: master

#30923 Load Smarty4 instead of Smarty3 where upgraded off Smarty2
  CRM/Core/SmartyCompatibility.php
Labels: master

#30933 Update zeta components/mail to 1.9.7
  composer.lock
Labels: master

#30934 smarty5 - implode is deprecated
  CRM/Case/Form/CaseView.php
  CRM/Tag/Page/Tag.php
  templates/CRM/Case/Form/CaseView.tpl
  templates/CRM/Tag/Page/Tag.tpl
Labels: master

#30870 Extract code to get the relevant mailing_id
  CRM/Mailing/Event/BAO/MailingEventUnsubscribe.php
Labels: master

#30937 Comment fix
  templates/CRM/common/civicrm.settings.php.template
Labels: master, merge on pass

#30140 dev/core#5053 Afform - Add support for saving event location
  Civi/Api4/Action/LocBlock/Create.php
  Civi/Api4/Action/LocBlock/LocBlockSaveTrait.php
  Civi/Api4/Action/LocBlock/Save.php
  Civi/Api4/Action/LocBlock/Update.php
  Civi/Api4/Generic/Traits/DAOActionTrait.php
  Civi/Api4/LocBlock.php
  Civi/Api4/Utils/CoreUtil.php
  ext/afform/admin/Civi/AfformAdmin/AfformAdminMeta.php
  ext/afform/admin/afformEntities/LocBlock.php
  ext/afform/admin/ang/afGuiEditor/afGuiEntity.component.js
  ext/afform/admin/ang/afGuiEditor/elements/afGuiContainer.component.js
  ext/afform/admin/ang/afGuiEditor/elements/afGuiContainer.html
  ext/afform/core/Civi/Afform/Behavior/ContactAutofill.php
  ext/afform/core/Civi/Afform/Behavior/GroupSubscription.php
  ext/afform/core/Civi/Api4/Action/Afform/AbstractProcessor.php
  ext/afform/core/Civi/Api4/Action/Afform/Prefill.php
  ext/afform/core/Civi/Api4/Action/Afform/Submit.php
  ext/afform/core/Civi/Api4/Subscriber/AfformAutocompleteSubscriber.php
  ext/afform/core/ang/af/afField.component.js
  ext/afform/core/ang/af/afForm.component.js
  ext/afform/core/ang/afblockEventLocBlock.aff.html
  ext/afform/core/ang/afblockEventLocBlock.aff.php
  ext/afform/core/tests/phpunit/Civi/Afform/AfformMetadataTest.php
  ext/afform/mock/tests/phpunit/api/v4/Afform/AfformAutocompleteUsageTest.php
  ext/afform/mock/tests/phpunit/api/v4/Afform/AfformCustomFieldUsageTest.php
  ext/afform/mock/tests/phpunit/api/v4/Afform/AfformEventUsageTest.php
  ext/afform/mock/tests/phpunit/api/v4/Afform/AfformGroupSubscriptionUsageTest.php
  ext/afform/mock/tests/phpunit/api/v4/Afform/AfformUsageTestCase.php
  tests/phpunit/api/v4/Entity/LocBlockTest.php
  tools/extensions/phpstorm/Civi/PhpStorm/Api4Generator.php
Labels: master, has-test

#30885 Increment min recommended & recommended php versions
  CRM/Upgrade/Incremental/General.php
Labels: master

#30941 Revert "Add deprecation notice to hook_civicrm_links used by search forms"
  CRM/Core/Action.php
Labels: master, merge on pass

#30942 Update deleted files list
  deleted-files-list.json
Labels: master

#30817 AfformScanner - Allow altering search paths with internal event
  ext/afform/core/CRM/Afform/AfformScanner.php
Labels: master, merge on pass

#30947 Fixed not of the type Float when a number has comma
  CRM/Contact/Form/CustomData.php
Labels: 5.77

#30797 Add chart_kit to core extensions directory
  .gitignore
  composer.json
  ext/chart_kit/Civi/ChartKit/Bundle.php
  ext/chart_kit/README.md
  ext/chart_kit/ang/crmChartKit.ang.php
  ext/chart_kit/ang/crmChartKit.css
  ext/chart_kit/ang/crmChartKit.js
  ext/chart_kit/ang/crmChartKit/chartKitAdminCanvas.html
  ext/chart_kit/ang/crmChartKit/chartKitAdminColumns.html
  ext/chart_kit/ang/crmChartKit/chartKitAdminLegend.html
  ext/chart_kit/ang/crmChartKit/chartKitCanvas.html
  ext/chart_kit/ang/crmChartKit/chartKitColumnConfig.service.js
  ext/chart_kit/ang/crmChartKit/chartKitTypes.service.js
  ext/chart_kit/ang/crmChartKit/chartTypes/chartKitComposite.service.js
  ext/chart_kit/ang/crmChartKit/chartTypes/chartKitCompositeAdmin.html
  ext/chart_kit/ang/crmChartKit/chartTypes/chartKitPie.service.js
  ext/chart_kit/ang/crmChartKit/chartTypes/chartKitPieAdmin.html
  ext/chart_kit/ang/crmChartKit/chartTypes/chartKitRow.service.js
  ext/chart_kit/ang/crmChartKit/chartTypes/chartKitRowAdmin.html
  ext/chart_kit/ang/crmChartKit/chartTypes/chartKitStack.service.js
  ext/chart_kit/ang/crmChartKit/chartTypes/chartKitStackAdmin.html
  ext/chart_kit/ang/crmChartKit/crmSearchDisplayChartKit.component.js
  ext/chart_kit/ang/crmChartKit/searchAdminDisplayChartKit.component.js
  ext/chart_kit/ang/crmChartKit/searchAdminDisplayChartKit.html
  ext/chart_kit/chart_kit.civix.php
  ext/chart_kit/chart_kit.php
  ext/chart_kit/info.xml
  ext/chart_kit/managed/ChartKitDisplays.mgd.php
Labels: master

#30952 dev/core#5405 - Domain Org form - remove old code that doesn't do anything and smarty doesn't like
  templates/CRM/Contact/Form/Domain.tpl
Labels: master

#30953 5.77
  CRM/Contact/Form/CustomData.php
Labels: master

#30558 civimix-schema: Define backportable DAO class
  mixin/lib/civimix-schema/src/CiviMixSchema.php
  mixin/lib/civimix-schema/src/DAO.php
Labels: master

#30566 Update CRM_Core_Smarty::escape not to call smarty function
  CRM/Core/Smarty.php
Labels: master

#30954 [REF] Fix undefined constant on closed batches
  CRM/Batch/BAO/Batch.php
Labels: merge on pass, 5.77

#30955 sweep away an old TODO
  templates/CRM/Admin/Page/Navigation.tpl
Labels: master, merge on pass

#30939 dev/core#5409 Update Brick Money/Math
  composer.lock
Labels: master

#30948 Change button type to upload to upload files
  CRM/Admin/Form/Options.php
Labels: master

#30957 5.77
  CRM/Batch/BAO/Batch.php
Labels: master

#30963 Only run buildSubTypes ajax call if contact type is set
  templates/CRM/Import/Form/DataSource.tpl
Labels: master

#30965 [REF][PHP8.2] Declare parentID property
  CRM/Admin/Form/ContactType.php
Labels: master

#30887 dev/core#5392 Standalone - set PHP timezone as well as MySQL timezone
  CRM/Core/Config.php
  CRM/Utils/System/Standalone.php
Labels: master, run-standalone

#30951 change standaloneusers session lifetime setting units to minutes
  CRM/Utils/System/Standalone.php
  ext/standaloneusers/Civi/Standalone/SessionHandler.php
  ext/standaloneusers/settings/standaloneusers.setting.php
Labels: master, run-standalone

#30967 dev/user-interface#54 Move Contact Delete under the Actions menu
  CRM/Contact/BAO/Contact.php
  templates/CRM/Contact/Page/View/Summary.tpl
Labels: master, sig:user interfacing improvement

#30964 EntityRepository - Add getCustomFields() method
  CRM/Core/BAO/CustomField.php
  CRM/Core/BAO/CustomValueTable.php
  CRM/Core/Form.php
  Civi/Api4/Event/Subscriber/AutocompleteFieldSubscriber.php
  Civi/Api4/Service/Spec/SpecFormatter.php
  Civi/Api4/Service/Spec/SpecGatherer.php
  Civi/Schema/EntityMetadataBase.php
  Civi/Schema/EntityMetadataInterface.php
  Civi/Schema/EntityProvider.php
  ext/afform/mock/tests/phpunit/api/v4/Afform/AfformAutocompleteUsageTest.php
  schema/Contact/Contact.entityType.php
  tests/phpunit/api/v4/Custom/CustomFieldGetFieldsTest.php
  tests/phpunit/api/v4/Spec/SpecFormatterTest.php
Labels: master, has-test

#30968 [NFC] CRM_Contact_Page_View: Remove unused dashboardURL variable
  CRM/Contact/Page/View.php
Labels: master, merge on pass

#30961 [REF][PHP8.2] Fix deprecated property on CRM_Contact_Page_View_Log
  CRM/Contact/Page/View/Log.php
Labels: master, merge on pass

#30960 [PHP8.4] Don't implicitly mark params as null
  ext/afform/core/Civi/Afform/Event/AfformEventEntityTrait.php
  ext/search_kit/Civi/Api4/Action/SearchDisplay/AbstractRunAction.php
  ext/search_kit/Civi/Search/Admin.php
  mixin/lib/civimix-schema/src/DAO.php
Labels: master, merge on pass

#30949 Afform - Fix FK selects of form entities
  ext/afform/admin/ang/afGuiEditor/afGuiFieldValue.directive.js
  ext/afform/admin/ang/afGuiEditor/behaviors/autofillRelationshipBehaviorForm.component.js
Labels: sig:unreleased-regression, 5.77

#30959 php 8.4 Update phpword 0.18.3 to 1.2.0
  composer.json
  composer.lock
Labels: master

#30945 dev/core#3769 Change default font family to sans-serif in print.css
  css/print.css
Labels: master, merge ready

#30936 Add type hints, comment fix to `createIndexes()`
  CRM/Core/BAO/SchemaHandler.php
Labels: master

#30874 [REF] Add in standalone urls for restore from trash and delete perman…
  CRM/Contact/Form/Task/Delete.php
  CRM/Contact/Task.php
  CRM/Core/xml/Menu/Misc.xml
Labels: master

#30845 Installation UI: Aligns header block, matches h1 colour.
  setup/res/template.css
Labels: master, merge ready

#30841 dev/core#2357 Improve clarity on Dedupe rule names
  sql/civicrm_data/civicrm_dedupe_rule/HouseholdSupervised.sqldata.php
  sql/civicrm_data/civicrm_dedupe_rule/IndividualGeneral.sqldata.php
  sql/civicrm_data/civicrm_dedupe_rule/IndividualSupervised.sqldata.php
  sql/civicrm_data/civicrm_dedupe_rule/OrganizationSupervised.sqldata.php
Labels: master

#30741 Follow up to #30415 - restrict permissions on Price Set Editing page
  CRM/Core/xml/Menu/Admin.xml
Labels: master

#30669 Update SavedSearch_Manage_Mail_Accounts.mgd.php
  ext/civicrm_admin_ui/managed/SavedSearch_Manage_Mail_Accounts.mgd.php
Labels: master

#30628 dev/core#5335 - Only show pcp section on online receipt if there is a pcp
  CRM/Contribute/BAO/Contribution.php
  tests/phpunit/CRM/Core/Payment/AuthorizeNetIPNTest.php
Labels: master, has-test

#30567 Add nofilter to templates for avoiding default escaping
  ext/afform/core/templates/afform/AfformAngularModule.tpl
  templates/CRM/Activity/Form/Activity.tpl
  templates/CRM/Admin/Form/ScheduleReminders.tpl
  templates/CRM/Contact/Form/ShareAddress.tpl
  templates/CRM/Contact/Page/Inline/Address.tpl
  templates/CRM/Contribute/Form/Contribution.tpl
  templates/CRM/UF/Form/Field.tpl
  templates/CRM/common/l10n.js.tpl
Labels: master

#30595 Call new 'civi.core.clearcache' event on CRM_Utils_System:flushCache()
  CRM/Utils/System.php
Labels: master

#30625 Improve UX for "Print Name Badges" and "PDF letter - print for participant"
  CRM/Event/Form/Task/Badge.php
  CRM/Event/Form/Task/PDF.php
  CRM/Event/xml/Menu/Event.xml
  ext/civicrm_admin_ui/managed/SavedSearch_Contact_Summary_Events.mgd.php
  templates/CRM/Event/Form/ParticipantView.tpl
Labels: master
