Repository civicrm/civicrm-core, pull requests merged in 2024-09, with the labels that each got.

#31018 Ensure CKEditor config screen loads with Smarty 5
  ext/ckeditor4/templates/CRM/Ckeditor4/Form/CKEditorConfig.tpl
Labels: master, merge on pass

#31020 dev/core#5421 - Backport of 31011 Fix 404 error with core recaptcha
  ext/recaptcha/lib/recaptcha/recaptchalib.php
Labels: 5.77

#31027 5.77 to master
  ext/recaptcha/lib/recaptcha/recaptchalib.php
Labels: master

#31019 regen after 31003
  sql/civicrm_generated.mysql
Labels: master

#31010 Update php spreadsheet to latest 1.x version (1.18.0 => 1.29.0)
  composer.lock
Labels: master

#31009 Update Select2 library to latest tagged version
  composer.json
  composer.lock
Labels: master

#30993 Fix master-only regression on import fields
  CRM/Dedupe/BAO/DedupeRuleGroup.php
  CRM/Import/Parser.php
  schema/Core/Address.entityType.php
Labels: master, sig:regression, sig:unreleased-regression

#30998 Event Info: copy the checksum to the registerURL
  CRM/Event/Page/EventInfo.php
Labels: master

#31024 Pseudoconstant - Use preferred lookup function
  CRM/Activity/BAO/Query.php
  CRM/Batch/Form/Entry.php
  CRM/Case/BAO/Query.php
  CRM/Case/Form/ActivityView.php
  CRM/Contact/Import/Form/Preview.php
  CRM/Core/BAO/File.php
  CRM/Core/BAO/UFGroup.php
  CRM/Event/BAO/Event.php
  ext/legacycustomsearches/CRM/Contact/Form/Search/Custom/Basic.php
  ext/legacycustomsearches/CRM/Contact/Form/Search/Custom/Group.php
  ext/legacycustomsearches/CRM/Contact/Form/Search/Custom/MultipleValues.php
  ext/legacycustomsearches/CRM/Contact/Form/Search/Custom/Proximity.php
  ext/legacycustomsearches/CRM/Contact/Form/Search/Custom/TagContributions.php
Labels: master

#31014 Fix a few more smarty:nodefaults to use nofilter
  templates/CRM/Event/Page/ManageEvent.tpl
  templates/CRM/Event/Page/Tab.tpl
  templates/CRM/UF/Form/Field.tpl
  templates/CRM/UF/Page/Field.tpl
  templates/CRM/common/showHide.tpl
Labels: master

#30982 Switch contribution search to use Smarty5 nofilter not older` smarty:nodefaults`
  CRM/Core/Form/EntityFormTrait.php
  CRM/Core/Smarty.php
  templates/CRM/Contribute/Page/ContributionTotals.tpl
  templates/CRM/Report/Form/Layout/Table.tpl
  templates/CRM/common/civicrm.settings.php.template
  templates/CRM/common/displaySearchCriteria.tpl
  templates/CRM/common/formButtons.tpl
  templates/CRM/common/pager.tpl
Labels: master

#30977 [REF] Assign values to variables before the loop, prepare extraction
  CRM/Core/BAO/CustomGroup.php
Labels: master

#30944 Fix incorrect CSS in contribution invoice template
  xml/templates/message_templates/contribution_invoice_receipt_html.tpl
Labels: master

#31028 FormBuilder: afform date field required attribute
  ext/afform/core/ang/af/fields/Date.html
Labels: master

#31032 dev/core#5407 - Multiselect custom field can't be blanked out
  CRM/Custom/Form/CustomDataTrait.php
Labels: sig:regression, 5.77

#31034 Symfony update 5.4.43 (from recent update to 5.4.42 but now .43 is out)
  composer.lock
Labels: master

#31035 5.77
  CRM/Custom/Form/CustomDataTrait.php
Labels: master

#31030 Afform - Fix autofill-current-user
  ext/afform/core/Civi/Afform/Behavior/ContactAutofill.php
  ext/afform/core/Civi/Api4/Action/Afform/AbstractProcessor.php
  ext/afform/core/ang/af/afForm.component.js
  ext/afform/mock/tests/phpunit/api/v4/Afform/AfformContactUsageTest.php
  ext/afform/mock/tests/phpunit/api/v4/Afform/AfformEventUsageTest.php
  ext/afform/mock/tests/phpunit/api/v4/Afform/AfformGroupSubscriptionUsageTest.php
  ext/afform/mock/tests/phpunit/api/v4/Afform/AfformPrefillUsageTest.php
  ext/afform/mock/tests/phpunit/api/v4/Afform/AfformRelationshipUsageTest.php
Labels: master

#31013 Remove unpassed variables for function with 1 universe caller
  CRM/Core/BAO/UFGroup.php
Labels: master

#30979 [REF] Extract the chunk of code that gets the custom data to disply for each field
  CRM/Core/BAO/CustomGroup.php
Labels: master

#30940 Add some noise to legacy callers of tokenValues, tokens
  CRM/Contact/Tokens.php
  CRM/Utils/Hook.php
Labels: master

#31038 [REF] Ensure that if original id is passed to hook::copy it is dispat…
  CRM/Utils/Hook.php
Labels: master

#30775 REF: Membership renewal form: Simplify pending check
  CRM/Member/Form/MembershipRenewal.php
Labels: master

#31039 [NFC] 5.77 release notes late changes
  release-notes/5.77.0.md
Labels: master

#31033 EventCart - Remove setting, unhide extension, uninstall if unused
  CRM/Event/BAO/Event.php
  CRM/Event/BAO/Participant.php
  CRM/Event/Page/List.php
  CRM/Upgrade/Incremental/Base.php
  CRM/Upgrade/Incremental/php/FiveSeventyEight.php
  api/v3/System/setting-whitelist.txt
  ext/eventcart/CRM/Event/Cart/PageCallback.php
  ext/eventcart/CRM/Event/Cart/Upgrader.php
  ext/eventcart/README.md
  ext/eventcart/eventcart.php
  ext/eventcart/info.xml
  ext/eventcart/settings/Eventcart.setting.php
  ext/eventcart/sql/install.sql
  ext/eventcart/sql/uninstall.sql
  templates/CRM/Event/Page/List.tpl
Labels: master

#31037 Remove blank place holders for text versions of messages
  CRM/Core/CodeGen/Util/MessageTemplates.php
  CRM/Upgrade/Incremental/MessageTemplates.php
  xml/templates/civicrm_msg_template.tpl
  xml/templates/message_templates/case_activity_text.tpl
  xml/templates/message_templates/contribution_dupalert_text.tpl
  xml/templates/message_templates/contribution_invoice_receipt_text.tpl
  xml/templates/message_templates/contribution_offline_receipt_text.tpl
  xml/templates/message_templates/contribution_online_receipt_text.tpl
  xml/templates/message_templates/contribution_recurring_billing_text.tpl
  xml/templates/message_templates/contribution_recurring_cancelled_text.tpl
  xml/templates/message_templates/contribution_recurring_edit_text.tpl
  xml/templates/message_templates/contribution_recurring_notify_text.tpl
  xml/templates/message_templates/event_offline_receipt_text.tpl
  xml/templates/message_templates/event_online_receipt_text.tpl
  xml/templates/message_templates/friend_text.tpl
  xml/templates/message_templates/membership_autorenew_billing_text.tpl
  xml/templates/message_templates/membership_autorenew_cancelled_text.tpl
  xml/templates/message_templates/membership_offline_receipt_text.tpl
  xml/templates/message_templates/membership_online_receipt_text.tpl
  xml/templates/message_templates/participant_cancelled_text.tpl
  xml/templates/message_templates/participant_confirm_text.tpl
  xml/templates/message_templates/participant_expired_text.tpl
  xml/templates/message_templates/participant_transferred_text.tpl
  xml/templates/message_templates/payment_or_refund_notification_text.tpl
  xml/templates/message_templates/pcp_notify_text.tpl
  xml/templates/message_templates/pcp_owner_notify_text.tpl
  xml/templates/message_templates/pcp_status_change_text.tpl
  xml/templates/message_templates/pcp_supporter_notify_text.tpl
  xml/templates/message_templates/petition_confirmation_needed_text.tpl
  xml/templates/message_templates/petition_sign_text.tpl
  xml/templates/message_templates/pledge_acknowledge_text.tpl
  xml/templates/message_templates/pledge_reminder_text.tpl
  xml/templates/message_templates/test_preview_text.tpl
  xml/templates/message_templates/uf_notify_text.tpl
Labels: master

#31044 Fatal Errors - Fix display of error icon (FontAwesome 6)
  templates/CRM/common/fatal.tpl
Labels: 5.77

#31031 Afform - hacky fix for select2 failing to update chainselect value
  ext/afform/core/ang/af/afField.component.js
Labels: master

#31047 Tell me which entity when silently ignoring it on form submission
  ext/afform/core/Civi/Api4/Action/Afform/Submit.php
Labels: master

#30721 dev/core#5356 dev/core#5379 Fix space comparison for multiple participants
  CRM/Event/Form/Registration/AdditionalParticipant.php
Labels: 5.77

#31050 dev/core#5435 Strip hex char before template assign
  CRM/Contribute/Form/ContributionBase.php
Labels: merge on pass, 5.77

#31042 dev/core#5432 Fix missing delete message on options form
  CRM/Admin/Form/Options.php
Labels: merge on pass, sig:regression, 5.77

#31045 (dev/core#4267) Afform - Simplify registration of scanner service. Fix inconsistency.
  ext/afform/core/CRM/Afform/AfformScanner.php
  ext/afform/core/afform.php
Labels: master

#31051 5.77
  CRM/Admin/Form/Options.php
  CRM/Contribute/Form/ContributionBase.php
  CRM/Event/Form/Registration/AdditionalParticipant.php
  templates/CRM/common/fatal.tpl
Labels: master

#31053 Replace hex with space
  CRM/Contribute/Form/ContributionBase.php
Labels: merge on pass, 5.77

#31054 (NFC) testHttpUnsubscribe - Add more comments
  tests/phpunit/CRM/Mailing/MailingSystemTestBase.php
Labels: master

#31029 dev/core#5422 Fix no full message showing up for logged in registered users
  CRM/Event/Form/Registration/ParticipantConfirm.php
  CRM/Event/Form/Registration/Register.php
  CRM/Event/Form/SelfSvcUpdate.php
  CRM/Event/Page/EventInfo.php
  Civi/Test/PageTrait.php
  Civi/Test/PageWrapper.php
  tests/phpunit/CRM/Event/Form/ManageEvent/EventInfoTest.php
  tests/phpunit/CRM/Event/Page/EventInfoTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: has-test, sig:regression, 5.77

#31055 dev/financial#224: Empty tax term on front end donation form
  CRM/Contribute/Form/Contribution/Main.php
Labels: master

#31056 5.77
  CRM/Contribute/Form/ContributionBase.php
  CRM/Event/Form/Registration/ParticipantConfirm.php
  CRM/Event/Form/Registration/Register.php
  CRM/Event/Form/SelfSvcUpdate.php
  CRM/Event/Page/EventInfo.php
  Civi/Test/PageTrait.php
  Civi/Test/PageWrapper.php
  tests/phpunit/CRM/Event/Form/ManageEvent/EventInfoTest.php
  tests/phpunit/CRM/Event/Page/EventInfoTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: master

#31059 5.78
  templates/CRM/Import/Form/DataSource.tpl
Labels: master

#30877 [ext/financialacls] Add constraint for `contribution_id` in SQL clause for unavailable financial types
  ext/financialacls/financialacls.php
Labels: master

#31060 (REF) CRM_Core_Invoke - Cleanup old experiment circa Symfony 2
  CRM/Core/Invoke.php
Labels: master, merge on pass

#31046 (dev/core#5434) Installer - Automatically synchronize contacts<=>users
  setup/plugins/blocks/sync-users.civi-setup.php
  setup/plugins/blocks/sync-users.tpl.php
  setup/plugins/installDatabase/SyncUsers.civi-setup.php
  setup/src/Setup/Model.php
Labels: master, merge ready, run-extended-tests, run-distmaker

#31066 Delete a dinosaur
  templates/CRM/Widget/widget.tpl
Labels: master, merge on pass

#31067 Move 'Manage Custom Searches' menu item to extension
  CRM/Core/xml/Menu/Admin.xml
  ext/legacycustomsearches/xml/Menu/Search.xml
Labels: master, merge on pass

#31070 CiviGrant - Translate untranslated strings in mgd.php files
  ext/civigrant/managed/OptionGroup_grant_type.mgd.php
  ext/civigrant/managed/OptionGroup_report_template_OptionValue_CRM_Report_Form_Grants.mgd.php
Labels: master, merge on pass

#31071 Update hook_civicrm_entityTypes docblock to match updated dev docs
  CRM/Utils/Hook.php
Labels: master, merge on pass

#31068 Always restore error handler when extension download glitches, a.k.a. avoid intermittent test fails
  CRM/Extension/Browser.php
Labels: 5.78

#31073 5.78
  CRM/Extension/Browser.php
Labels: master

#31077 Activity - Remove unused variables
  CRM/Activity/BAO/Query.php
Labels: master, merge on pass

#31069 dev/core#5447 - Crash on backend event registration
  templates/CRM/Event/Page/Tab.tpl
Labels: 5.78

#31086 5.78 to master
  templates/CRM/Event/Page/Tab.tpl
Labels: master

#31080 Annotate CRM_Core_PseudoConstant::get as @deprecated
  CRM/Core/DAO.php
  CRM/Core/PseudoConstant.php
Labels: master

#31085 dev/core#5451 Fix regression on location type default
  CRM/Contact/Form/Contact.php
Labels: merge on pass, 5.78

#31088 Invoice message template additional text is squished
  sql/civicrm_generated.mysql
  xml/templates/message_templates/contribution_invoice_receipt_html.tpl
Labels: master, merge on pass

#31089 5.78 to master
  CRM/Contact/Form/Contact.php
Labels: master

#31079 AllCoreTables - Handle tableless and classless entities without crashing
  CRM/Core/DAO/AllCoreTables.php
  Civi/Schema/EntityRepository.php
  mixin/lib/civimix-schema/src/SqlGenerator.php
Labels: master

#31092 Stop including vine as a website type on new installs
  sql/civicrm_data/civicrm_option_group/website_type.sqldata.php
  sql/civicrm_generated.mysql
Labels: master, merge on pass

#31087 dev/core#5440 fix admin-only price field display
  CRM/Contribute/Form/ContributionBase.php
  CRM/Event/Form/Registration.php
  templates/CRM/Contribute/Form/Contribution.tpl
  templates/CRM/Event/Form/EventFees.tpl
  templates/CRM/Event/Form/ParticipantFeeSelection.tpl
  templates/CRM/Member/Form/Membership.tpl
  templates/CRM/Price/Form/Preview.tpl
  templates/CRM/Price/Form/PriceSet.tpl
Labels: merge ready, 5.78

#31098 dev/core#5440 - 5.77 version of fix admin-only price field display
  CRM/Contribute/Form/ContributionBase.php
  CRM/Event/Form/Registration.php
  templates/CRM/Contribute/Form/Contribution.tpl
  templates/CRM/Event/Form/EventFees.tpl
  templates/CRM/Event/Form/ParticipantFeeSelection.tpl
  templates/CRM/Member/Form/Membership.tpl
  templates/CRM/Price/Form/Preview.tpl
  templates/CRM/Price/Form/PriceSet.tpl
Labels: merge on pass, 5.77

#31096 Schema - Add 'default_fallback' for fields
  CRM/Core/DAO.php
  Civi.php
  Civi/Api4/Service/Spec/Provider/GroupCreationSpecProvider.php
  Civi/Api4/Service/Spec/SpecFormatter.php
  Civi/Schema/EntityMetadataBase.php
  Civi/Schema/LegacySqlEntityMetadata.php
  Civi/Schema/SqlEntityMetadata.php
  schema/Contact/Group.entityType.php
  schema/Contribute/ContributionPage.entityType.php
  schema/Core/UFGroup.entityType.php
  schema/Financial/PaymentProcessor.entityType.php
  tests/phpunit/CRM/Contribute/Form/Task/BatchTest.php
  tests/phpunit/CRM/Member/Form/Task/BatchTest.php
  tests/phpunit/Civi/Schema/EntityTest.php
  tests/phpunit/api/v4/Entity/GroupTest.php
  tests/phpunit/api/v4/Entity/PaymentProcessorTest.php
  tools/extensions/phpstorm/Civi/PhpStorm/EntityGenerator.php
Labels: master

#31091 Aren't links supposed to be in quotes?
  CRM/Financial/Page/AJAX.php
  tests/phpunit/CRM/Financial/Page/AjaxTest.php
Labels: master, merge on pass

#31099 AllCoreTables - allow multiple entities per table when filtering out …
  CRM/Core/DAO/AllCoreTables.php
Labels: master, merge on pass, run-standalone

#31102 Standalone login screen: tidies padding, input height, label margin, fixes duplicate semi-colon
  ext/standaloneusers/css/standalone.css
Labels: master

#31093 Standalone - allow creating a homepage at `/civicrm/home`
  Civi/Standalone/WebEntrypoint.php
Labels: master

#31094 Remove brand names from website types
  sql/civicrm_data/civicrm_option_group/website_type.sqldata.php
  tests/phpunit/CRM/Contact/Import/Parser/ContactTest.php
  tests/phpunit/CRM/Core/PseudoConstantTest.php
Labels: master

#31097 5.78
  CRM/Contribute/Form/ContributionBase.php
  CRM/Event/Form/Registration.php
  templates/CRM/Contribute/Form/Contribution.tpl
  templates/CRM/Event/Form/EventFees.tpl
  templates/CRM/Event/Form/ParticipantFeeSelection.tpl
  templates/CRM/Member/Form/Membership.tpl
  templates/CRM/Price/Form/Preview.tpl
  templates/CRM/Price/Form/PriceSet.tpl
Labels: master

#31108 SearchKit - Hide tally loading placholders when search hasn't run yet
  ext/search_kit/ang/crmSearchDisplayTable/crmSearchDisplayTable.html
Labels: master, merge on pass

#31113 extdir: remove cms=uf parameter to reduce the number of cache entries
  distmaker/dists/common.sh
  settings/Extension.setting.php
Labels: master, merge on pass

#31115 Scales login box padding down at smaller screen widths
  ext/standaloneusers/css/standalone.css
Labels: master

#30780 SearchKit - Format footer tally values according to data type
  Civi/Api4/Query/SqlFunction.php
  Civi/Api4/Query/SqlFunctionDAYSTOANNIV.php
  Civi/Api4/Query/SqlFunctionGROUP_FIRST.php
  Civi/Api4/Query/SqlFunctionNEXTANNIV.php
  ext/search_kit/Civi/Api4/Action/SearchDisplay/AbstractRunAction.php
  ext/search_kit/Civi/Api4/Action/SearchDisplay/Run.php
  ext/search_kit/ang/crmSearchDisplayTable/crmSearchDisplayTally.html
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/SearchRunTest.php
Labels: master

#31112 dev/core#5455 Reduce severity of extension download error
  CRM/Admin/Page/Extensions.php
  CRM/Extension/Browser.php
  CRM/Utils/Check/Component/Env.php
Labels: master, merge on pass

#31107 SettingsField.tpl - move help swatch next to label
  templates/CRM/Admin/Form/Setting/SettingField.tpl
Labels: master

#31119 dev/core#5460 - adminUI - fix permission for viewing job log
  ext/civicrm_admin_ui/ang/afsearchScheduledJobsLog.aff.php
Labels: master, merge on pass

#31118 fix 'invalid character in regex' error
  ext/afform/admin/ang/afGuiEditor/config-form.html
Labels: master

#31008 Civi::url() - Multiple fixes and test improvements
  .gitignore
  CRM/Core/Page/RemoteTestFunction.php
  CRM/Core/xml/Menu/Misc.xml
  CRM/Utils/Url.php
  Civi/Core/Url.php
  Civi/Test/RemoteTestFunction.php
  composer.json
  composer.lock
  tests/phpunit/Civi/Core/UrlTest.php
  tests/phpunit/E2E/Core/PathUrlTest.php
  tests/phpunit/E2E/Core/UrlFacadeTest.php
  tests/phpunit/E2E/Extern/CliRunnerTest.php
  tests/phpunit/E2E/Extern/WidgetTest.php
Labels: master, run-extended-tests

#31121 ManagedEntities - Remove unused function
  CRM/Core/ManagedEntities.php
Labels: master

#31110 Add timestamp as a crmDate option
  CRM/Core/Smarty/plugins/modifier.crmDate.php
Labels: master, merge ready

#31100 SearchKit - Selectable option-value format
  CRM/Api4/Page/Api4Explorer.php
  CRM/Core/SelectValues.php
  Civi/Api4/Generic/BasicGetAction.php
  Civi/Api4/Service/Spec/SpecFormatter.php
  Civi/Api4/Utils/FormattingUtil.php
  Civi/Schema/EntityMetadataBase.php
  ext/search_kit/Civi/Api4/Action/SearchDisplay/AbstractRunAction.php
  ext/search_kit/Civi/Search/Admin.php
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdminDisplay.component.js
  ext/search_kit/ang/crmSearchAdmin/displays/colType/field.html
Labels: master, merge ready

#31120 Add missing help text for mailer settings screen
  settings/Mailing.setting.php
Labels: master

#31126 ChartKit - fix legend item vertical alignment on Chrome
  ext/chart_kit/ang/crmChartKit/crmSearchDisplayChartKit.component.js
Labels: master, merge on pass

#31122 dev/core#5468 Do not output event contact details if empty
  templates/CRM/Event/Form/Registration/EventInfoBlock.tpl
Labels: master, merge on pass

#31111 dev/core#5416 - Fix missing dates in FormBuilder
  Civi/Api4/Service/Spec/SpecFormatter.php
  Civi/Schema/EntityMetadataBase.php
  tests/phpunit/api/v4/Action/GetFieldsTest.php
Labels: has-test, 5.78

#31123 Remove extraneous angular module dependency from chart_kit
  ext/chart_kit/ang/crmChartKit.ang.php
Labels: master, merge on pass

#31128 Merge 5.78 to Master
  Civi/Api4/Service/Spec/SpecFormatter.php
  Civi/Schema/EntityMetadataBase.php
  tests/phpunit/api/v4/Action/GetFieldsTest.php
Labels: master

#31061 dev/core#3035 Add New Extension: Display all stable extensions (not just reviewed ones)
  CRM/Admin/Page/Extensions.php
  CRM/Extension/Browser.php
  CRM/Extension/Info.php
  css/admin.css
  templates/CRM/Admin/Page/ExtensionDetails.tpl
  templates/CRM/Admin/Page/Extensions/About.tpl
  templates/CRM/Admin/Page/Extensions/AddNew.tpl
  templates/CRM/Admin/Page/Extensions/Main.tpl
Labels: master, sig:user interfacing improvement, sig:extension support

#31129 respect Custom Group collapse on Activity and Case search forms
  templates/CRM/Custom/Form/Search.tpl
Labels: master

#31131 Extra bracket showing in custom field label on search screen
  templates/CRM/Custom/Form/Search.tpl
Labels: merge on pass, 5.78

#31065 dev/core#5443 - Fix crash when using a saved import mapping with a file with more columns
  CRM/Contribute/Import/Form/MapField.php
Labels: 5.78

#31104 dev/core#5459 - Fix one of the bad timestamp columns from the schema changes
  CRM/Upgrade/Incremental/php/FiveSeventyEight.php
  CRM/Upgrade/Incremental/sql/5.78.beta1.mysql.tpl
  schema/Core/JobLog.entityType.php
Labels: 5.78

#31134 5.78 to master
  CRM/Contribute/Import/Form/MapField.php
  CRM/Upgrade/Incremental/php/FiveSeventyEight.php
  CRM/Upgrade/Incremental/sql/5.78.beta1.mysql.tpl
  schema/Core/JobLog.entityType.php
  templates/CRM/Custom/Form/Search.tpl
Labels: master

#31136 Avoid JS error when user does not have permission to save the template
  templates/CRM/Contact/Form/Task/PDFLetterCommon.tpl
Labels: master, merge on pass

#31132 Schema - Make 'multiple' input_attr a true boolean
  schema/Contact/Contact.entityType.php
  schema/Contribute/ContributionPage.entityType.php
  schema/Core/ActionSchedule.entityType.php
  schema/Event/Participant.entityType.php
  tests/phpunit/api/v4/Action/GetFieldsTest.php
Labels: master, merge on pass, has-test

#30796 Visual bundle consolidation / cleanup
  CRM/Contribute/Form/ContributionCharts.php
  CRM/Report/Form.php
  Civi/Core/Container.php
  Civi/Visual/Bundle.php
  ang/crmD3.ang.php
  ang/crmDashboard.ang.php
  composer.json
  ext/civi_mail/ang/crmMailingAB.ang.php
  ext/civi_mail/ang/crmMailingAB/Stats.js
  ext/civigrant/CRM/Report/Form/Grant/Statistics.php
  js/crm.visual.createChart.js
  karma.conf.js
  templates/CRM/Contact/Page/DashBoardDashlet.tpl
  templates/CRM/Contribute/Form/ContributionCharts.tpl
  templates/CRM/Report/Form/Layout/Graph.tpl
  templates/CRM/common/chart.tpl
Labels: master

#30533 Use SettingsManager for boot time settings to enable reading from environment variables
  CRM/Core/BAO/ConfigSetting.php
  CRM/Core/Config.php
  Civi/Core/SettingsBag.php
  Civi/Core/SettingsManager.php
  Civi/Core/SettingsMetadata.php
  settings/Core.setting.php
  settings/Database.boot.setting.php
  settings/Directory.boot.setting.php
  settings/Extension.boot.setting.php
  settings/System.boot.setting.php
  settings/Url.boot.setting.php
  setup/res/civicrm.standalone.php.txt
  tests/phpunit/Civi/Core/SettingsManagerTest.php
Labels: master, run-extended-tests, run-distmaker

#31137 [NFC] Fix some references to old exception aliases in code comments
  CRM/Case/WorkflowMessage/ActivityExamples.php
  CRM/Import/Parser.php
  Civi/Api4/CustomValue.php
  ext/civiimport/Civi/Api4/Import.php
  tests/phpunit/Civi/Token/TokenProcessorTest.php
Labels: master

#30367 Create a Joomla 5 build
  distmaker/distmaker.sh
  distmaker/dists/joomla5_php.sh
Labels: master, run-distmaker

#31138 ChartKit - add week as a date rounding option
  ext/chart_kit/ang/crmChartKit/chartKitColumnConfig.service.js
  ext/chart_kit/ang/crmChartKit/crmSearchDisplayChartKit.component.js
Labels: master

#31135 WebsiteType - Delete branded website-type options that are not in use
  CRM/Upgrade/Incremental/php/FiveSeventyNine.php
Labels: master

#31142 regen after 31094
  sql/civicrm_generated.mysql
Labels: master, merge on pass

#31139 dev/core#5443 - (5.77 backport) Fix crash when using a saved import mapping with a file with more columns
  CRM/Contribute/Import/Form/MapField.php
Labels: 5.77

#31143 composer.lock hash out of date
  composer.lock
Labels: master

#30585 (dev/core#4462) Afform - Add support for page-level authentication links
  CRM/Utils/GuzzleMiddleware.php
  ext/afform/core/CRM/Afform/Utils.php
  ext/afform/core/Civi/Afform/PageTokenCredential.php
  ext/afform/core/Civi/Afform/Tokens.php
  ext/afform/core/info.xml
  ext/afform/core/settings/Afform.setting.php
  ext/afform/mock/ang/mockPublicForm.aff.html
  ext/afform/mock/ang/mockPublicForm.aff.php
  ext/afform/mock/tests/phpunit/E2E/AfformMock/MockPublicFormBrowserTest.php
  ext/afform/mock/tests/phpunit/E2E/AfformMock/MockPublicFormTest.php
  ext/authx/Civi/Authx/Authenticator.php
  ext/authx/Civi/Authx/CheckCredentialEvent.php
Labels: master

#31151 (dev/core#4462) Afform - Session-level login-links are moving out
  CRM/Upgrade/Incremental/php/FiveSeventyNine.php
  ext/afform/core/CRM/Afform/AfformScanner.php
  ext/afform/core/CRM/Afform/Utils.php
  ext/afform/core/Civi/Afform/Tokens.php
  ext/afform/core/afform.php
  ext/afform/core/settings/Afform.setting.php
  ext/afform/mock/tests/phpunit/E2E/AfformMock/MockPublicFormBrowserTest.php
  ext/afform/mock/tests/phpunit/E2E/AfformMock/MockPublicFormTest.php
Labels: master

#31145 sybunt report cleanup
  CRM/Report/Form/Contribute/Sybunt.php
Labels: master

#31040 fix using REGEXP with contact ID
  Civi/Api4/Utils/FormattingUtil.php
  tests/phpunit/api/v4/Action/ContactGetTest.php
Labels: master, merge on pass

#31156 Remove some legacy copy & paste from mailing labels
  CRM/Contact/Form/Task/Label.php
  CRM/Member/Form/Task/Label.php
Labels: master, almost merge on pass

#31095 [REF] Replace create with writeRecord in Group
  CRM/Campaign/Form/Task/Reserve.php
  CRM/Contact/BAO/Group.php
  CRM/Contact/Form/Task.php
  CRM/Contact/Form/Task/AddToGroup.php
  CRM/Contact/Form/Task/SaveSearch.php
  CRM/Core/DAO.php
  CRM/Event/Form/Task/AddToGroup.php
  CRM/Event/Form/Task/SaveSearch.php
  CRM/Group/Form/Edit.php
  schema/Contact/Group.entityType.php
  tests/phpunit/CRM/Contact/BAO/GroupContactCacheTest.php
  tests/phpunit/CRM/Contact/BAO/GroupTest.php
  tests/phpunit/CRM/Mailing/MultilingualSystemTest.php
  tests/phpunit/api/v4/Entity/GroupTest.php
Labels: master

#31026 SearchKit - Improve appearance and usability of pager
  ext/search_kit/ang/crmSearchDisplay/Pager.html
Labels: master

#31160 5.78.0 release notes initial run
  release-notes.md
  release-notes/5.78.0.md
Labels: 5.78

#31158 dev/core#5459 - fix remaining timestamp columns
  CRM/Upgrade/Incremental/sql/5.78.beta1.mysql.tpl
  schema/Contribute/ContributionRecur.entityType.php
  schema/Core/Cache.entityType.php
  schema/Core/Note.entityType.php
  schema/Core/SystemLog.entityType.php
  schema/Financial/PaymentToken.entityType.php
Labels: 5.78

#31148 Add unit test for getDuplicates behaviour on Register task
  CRM/Event/Form/Task/Register.php
  tests/phpunit/CRM/Event/Form/Task/RegisterTest.php
Labels: master

#31116 dev/core#5419: Add FinancialType and FinancialAccount label field
  CRM/Contact/BAO/Query.php
  CRM/Contribute/PseudoConstant.php
  CRM/Core/DAO.php
  CRM/Financial/BAO/EntityFinancialAccount.php
  CRM/Financial/Form/FinancialAccount.php
  CRM/Financial/Form/FinancialType.php
  CRM/Financial/Page/AJAX.php
  CRM/Financial/Page/FinancialAccount.php
  CRM/Upgrade/Incremental/php/FiveSeventyNine.php
  CRM/Upgrade/Incremental/sql/5.79.alpha1.mysql.tpl
  schema/Contribute/Contribution.entityType.php
  schema/Contribute/ContributionPage.entityType.php
  schema/Contribute/ContributionProduct.entityType.php
  schema/Contribute/ContributionRecur.entityType.php
  schema/Contribute/PremiumsProduct.entityType.php
  schema/Contribute/Product.entityType.php
  schema/Event/Event.entityType.php
  schema/Financial/FinancialAccount.entityType.php
  schema/Financial/FinancialType.entityType.php
  schema/Member/MembershipType.entityType.php
  schema/Pledge/Pledge.entityType.php
  schema/Price/LineItem.entityType.php
  schema/Price/PriceFieldValue.entityType.php
  schema/Price/PriceSet.entityType.php
  sql/civicrm_data/civicrm_financial_account.sqldata.php
  sql/civicrm_data/civicrm_financial_type.sqldata.php
  templates/CRM/Financial/Form/FinancialAccount.tpl
  templates/CRM/Financial/Page/FinancialAccount.tpl
  templates/CRM/Financial/Page/FinancialType.tpl
  tests/phpunit/CRM/Export/BAO/ExportTest.php
  tests/phpunit/api/v3/FinancialTypeTest.php
Labels: master

#31164 Add Regions to the Case View template
  templates/CRM/Case/Form/CaseView.tpl
Labels: master, merge on pass

#31144 Update warning shown when installing unreviewed extensions
  templates/CRM/Admin/Page/ExtensionDetails.tpl
Labels: master

#31166 Don't clobber financial label changes if upgrade is rerun
  CRM/Upgrade/Incremental/php/FiveSeventyNine.php
  CRM/Upgrade/Incremental/sql/5.79.alpha1.mysql.tpl
Labels: master

#31048 API4: Abstract resolveContactID and ensure that formatCustomField receives a valid contact ID
  Civi/Api4/Generic/Traits/DAOActionTrait.php
  Civi/Api4/Utils/FormattingUtil.php
Labels: master

#31167 dev/core#5465 - Fix deselect entityReference
  ext/afform/core/ang/af/afField.component.js
Labels: sig:regression, 5.78

#31170 Merge 5.78 to master
  CRM/Upgrade/Incremental/sql/5.78.beta1.mysql.tpl
  ext/afform/core/ang/af/afField.component.js
  release-notes.md
  release-notes/5.78.0.md
  schema/Contribute/ContributionRecur.entityType.php
  schema/Core/Cache.entityType.php
  schema/Core/Note.entityType.php
  schema/Core/SystemLog.entityType.php
  schema/Financial/PaymentToken.entityType.php
Labels: master

#31161 dev/core#5459 - (5.77 backport) - fix timestamp columns
  CRM/Upgrade/Incremental/php/FiveSeventySeven.php
  CRM/Upgrade/Incremental/sql/5.77.1.mysql.tpl
  schema/Contribute/ContributionRecur.entityType.php
  schema/Core/Cache.entityType.php
  schema/Core/JobLog.entityType.php
  schema/Core/Note.entityType.php
  schema/Core/SystemLog.entityType.php
  schema/Financial/PaymentToken.entityType.php
Labels: 5.77

#31173 PHP8 - Fix undeclared var in batch form
  CRM/Financial/Form/BatchTransaction.php
Labels: master

#31172 Schema - Add support for default_callback functions
  CRM/Campaign/BAO/Campaign.php
  CRM/Core/BAO/File.php
  CRM/Core/DAO.php
  Civi/Api4/Service/Spec/SpecFormatter.php
  schema/Campaign/Campaign.entityType.php
  schema/Core/File.entityType.php
  tests/phpunit/api/v3/CampaignTest.php
Labels: master, has-test

#31179 Add release-notes/5.77.1.md
  release-notes.md
  release-notes/5.77.1.md
Labels: 5.77

#31175 5.78
  CRM/Upgrade/Incremental/sql/5.78.beta1.mysql.tpl
Labels: master, merge on pass

#31177 Batch - Fix default values of columns
  CRM/Batch/BAO/Batch.php
  CRM/Upgrade/Incremental/sql/5.79.alpha1.mysql.tpl
  Civi/Api4/Service/Spec/Provider/BatchCreationSpecProvider.php
  api/v3/Batch.php
  schema/Batch/Batch.entityType.php
Labels: master

#31182 regen after 31116
  sql/civicrm_generated.mysql
Labels: master

#31049 fix for displaying submission data
  ext/afform/core/Civi/Api4/Action/Afform/AbstractProcessor.php
Labels: master

#31183 ext/*/info.xml - Use a short expressions instead of constantly revising files
  CRM/Extension/Info.php
  CRM/Utils/System.php
  ext/afform/admin/info.xml
  ext/afform/core/info.xml
  ext/afform/html/info.xml
  ext/afform/mock/info.xml
  ext/authx/info.xml
  ext/chart_kit/info.xml
  ext/civi_campaign/info.xml
  ext/civi_case/info.xml
  ext/civi_contribute/info.xml
  ext/civi_event/info.xml
  ext/civi_mail/info.xml
  ext/civi_member/info.xml
  ext/civi_pledge/info.xml
  ext/civi_report/info.xml
  ext/civicrm_admin_ui/info.xml
  ext/civicrm_search_ui/info.xml
  ext/civigrant/info.xml
  ext/civiimport/info.xml
  ext/ckeditor4/info.xml
  ext/contributioncancelactions/info.xml
  ext/elavon/info.xml
  ext/eventcart/info.xml
  ext/ewaysingle/info.xml
  ext/financialacls/info.xml
  ext/flexmailer/info.xml
  ext/greenwich/info.xml
  ext/iframe/info.xml
  ext/legacycustomsearches/info.xml
  ext/message_admin/info.xml
  ext/oauth-client/info.xml
  ext/oembed/info.xml
  ext/payflowpro/info.xml
  ext/recaptcha/info.xml
  ext/scheduled_communications/info.xml
  ext/search_kit/info.xml
  ext/sequentialcreditnotes/info.xml
  ext/standaloneusers/info.xml
  ext/tellafriend/info.xml
  ext/user_dashboard/info.xml
  tools/bin/scripts/set-version.php
  tools/extensions/event_check/info.xml
  xml/version.xml
Labels: master

#31178 Schema - IDE-friendly formatting of callbacks
  ext/afform/core/schema/AfformSubmission.entityType.php
  ext/search_kit/schema/SearchSegment.entityType.php
  ext/standaloneusers/schema/Role.entityType.php
  ext/standaloneusers/schema/User.entityType.php
  schema/ACL/ACL.entityType.php
  schema/ACL/ACLEntityRole.entityType.php
  schema/Campaign/CampaignGroup.entityType.php
  schema/Contact/ACLContactCache.entityType.php
  schema/Contact/Contact.entityType.php
  schema/Contact/Group.entityType.php
  schema/Contact/GroupContact.entityType.php
  schema/Contact/Relationship.entityType.php
  schema/Contact/RelationshipCache.entityType.php
  schema/Contact/SavedSearch.entityType.php
  schema/Contact/SubscriptionHistory.entityType.php
  schema/Contribute/Premium.entityType.php
  schema/Contribute/Product.entityType.php
  schema/Core/ActionSchedule.entityType.php
  schema/Core/CustomField.entityType.php
  schema/Core/CustomGroup.entityType.php
  schema/Core/Dashboard.entityType.php
  schema/Core/Discount.entityType.php
  schema/Core/Email.entityType.php
  schema/Core/EntityFile.entityType.php
  schema/Core/Extension.entityType.php
  schema/Core/Job.entityType.php
  schema/Core/Managed.entityType.php
  schema/Core/MappingField.entityType.php
  schema/Core/Navigation.entityType.php
  schema/Core/OptionGroup.entityType.php
  schema/Core/StatusPreference.entityType.php
  schema/Core/Translation.entityType.php
  schema/Core/UFField.entityType.php
  schema/Core/UFJoin.entityType.php
  schema/Core/UserJob.entityType.php
  schema/Core/WordReplacement.entityType.php
  schema/Dedupe/DedupeRuleGroup.entityType.php
  schema/Event/ParticipantStatusType.entityType.php
  schema/Financial/EntityFinancialAccount.entityType.php
  schema/Financial/EntityFinancialTrxn.entityType.php
  schema/Financial/FinancialItem.entityType.php
  schema/Financial/PaymentProcessorType.entityType.php
  schema/Mailing/Mailing.entityType.php
  schema/Mailing/MailingAB.entityType.php
  schema/Mailing/MailingComponent.entityType.php
  schema/Mailing/MailingGroup.entityType.php
  schema/Mailing/MailingJob.entityType.php
  schema/Member/MembershipStatus.entityType.php
  schema/Member/MembershipType.entityType.php
  schema/PCP/PCP.entityType.php
  schema/Price/LineItem.entityType.php
  schema/Price/PriceField.entityType.php
  schema/Price/PriceSet.entityType.php
  schema/Queue/Queue.entityType.php
  schema/Report/ReportInstance.entityType.php
Labels: master

#31174 Move template selection field when adding a new event to the top
  templates/CRM/Event/Form/ManageEvent/EventInfo.tpl
Labels: master, merge on pass

#31186 dev/core#5465 - Fix Afform clearing entity when deselecting join
  ext/afform/core/ang/af/afForm.component.js
Labels: 5.78

#31141 Event Settings: rename labels for public listing, calendar links
  CRM/Event/Form/ManageEvent/EventInfo.php
  templates/CRM/Event/Form/ManageEvent/EventInfo.hlp
  templates/CRM/Event/Form/ManageEvent/EventInfo.tpl
Labels: master, sig:user interfacing improvement

#31168 SearchKit - JS cleanup, use const for constants
  ext/search_kit/ang/crmSearchTasks/crmSearchBatchRunner.component.js
Labels: master

#31090 Batch - Update deprecated pseudocontant getter calls
  CRM/Batch/BAO/Batch.php
  CRM/Financial/Form/BatchTransaction.php
  CRM/Financial/Form/Search.php
  CRM/Financial/Page/AJAX.php
Labels: master

#31185 [REF] Output of running npm audit fix
  package-lock.json
Labels: 5.78

#31076 Pseudoconstant - Improve currency dropdowns & use non-deprecated functions
  CRM/Admin/Form/Setting/Localization.php
  CRM/Contribute/BAO/Query.php
  CRM/Utils/Money.php
  CRM/Utils/Rule.php
  ext/civigrant/CRM/Report/Form/Grant/Statistics.php
  ext/civigrant/schema/Grant.entityType.php
  schema/Contribute/Contribution.entityType.php
  schema/Contribute/ContributionPage.entityType.php
  schema/Contribute/ContributionRecur.entityType.php
  schema/Contribute/ContributionSoft.entityType.php
  schema/Contribute/Product.entityType.php
  schema/Event/Event.entityType.php
  schema/Event/Participant.entityType.php
  schema/Financial/FinancialItem.entityType.php
  schema/Financial/FinancialTrxn.entityType.php
  schema/PCP/PCP.entityType.php
  schema/Pledge/Pledge.entityType.php
  schema/Pledge/PledgePayment.entityType.php
Labels: master, sig:user interfacing improvement

#31184 dev/core#5489 - IIF export fatal error in smarty 5
  CRM/Financial/BAO/ExportFormat/IIF.php
  templates/CRM/Financial/ExportFormat/IIF.tpl
Labels: master

#31176 Financial ACLs broken in 5.75+ when a line item with no contribution ID exists
  ext/financialacls/financialacls.php
Labels: 5.78

#31194 Notice fix
  templates/CRM/Admin/Form/Setting/SettingField.tpl
Labels: master

#31106 Display Preferences screen - use settings metadata as much as possible
  CRM/Admin/Form/Preferences/Display.php
  settings/Core.setting.php
  templates/CRM/Admin/Form/Preferences/Display.hlp
  templates/CRM/Admin/Form/Preferences/Display.tpl
Labels: master, sig:user interfacing improvement

#31201 [NFC] Api4 - Settings test code cleanup
  tests/phpunit/api/v4/Entity/SettingTest.php
Labels: merge on pass

#31204 Metadata - Add default_callback to Group & SavedSearch entities
  CRM/Contact/BAO/Group.php
  CRM/Contact/BAO/SavedSearch.php
  schema/Contact/Group.entityType.php
  schema/Contact/SavedSearch.entityType.php
Labels: master

#31191 RolePermission - Ensure implied permissions cascade > 1 depth
  ext/standaloneusers/Civi/Api4/Action/RolePermission/Get.php
  ext/standaloneusers/tests/phpunit/Civi/Api4/Action/RolePermissionTest.php
Labels: master, has-test, run-standalone

#31205 Update ContrabutionPage schema/bao to use best-practices
  CRM/Contribute/BAO/ContributionPage.php
  CRM/Contribute/Form/ContributionPage/Amount.php
  CRM/Contribute/Form/ContributionPage/Settings.php
  CRM/Contribute/Form/ContributionPage/ThankYou.php
  CRM/Upgrade/Incremental/sql/5.79.alpha1.mysql.tpl
  schema/Contribute/ContributionPage.entityType.php
  tests/phpunit/CRM/Contribute/BAO/ContributionPageTest.php
  tests/phpunit/CRM/Contribute/Form/ContributionPageTranslationTest.php
Labels: master

#31206 SqlGenerator - Always specify NULL or NOT NULL in DDL
  mixin/lib/civimix-schema/src/SqlGenerator.php
Labels: master

#31006 Fix implicit TIMESTAMP default generating invalid DDL
  CRM/Core/BAO/SchemaHandler.php
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/EntityDisplayTest.php
  tests/phpunit/CRM/Core/BAO/SchemaHandlerTest.php
Labels: master, almost merge on pass

#31195 [NFC] first pass at 5.78 release notes
  release-notes/5.78.0.md
Labels: 5.78

#31208 SearchKit - Fix creating smart group from Individual/Organization/Household base entity
  ext/search_kit/ang/crmSearchAdmin.module.js
Labels: sig:regression, 5.78

#31193 Add Unit test to demonstrate & remove code cruft
  CRM/Contact/Form/Task/Label.php
  CRM/Contact/Form/Task/LabelCommon.php
  tests/phpunit/CRM/Contact/Form/Task/PrintMailingLabelTest.php
Labels: master

#31133 ChartKit - add new chart type: Series Chart
  ext/chart_kit/ang/crmChartKit/chartKitTypes.service.js
  ext/chart_kit/ang/crmChartKit/chartTypes/chartKitSeries.service.js
  ext/chart_kit/ang/crmChartKit/chartTypes/chartKitSeriesAdmin.html
  ext/chart_kit/ang/crmChartKit/crmSearchDisplayChartKit.component.js
Labels: master
