Repository civicrm/civicrm-core, pull requests merged in 2025-03, with the labels that each got.

#32268 SearchKit - Fix hiding buttons when downloading spreadsheet
  ext/search_kit/ang/crmSearchTasks/crmSearchTaskDownload.ctrl.js
Labels: 6.0

#32210 Api4 - Use global cache for entityFields
  Civi/API/Subscriber/SiteEmailLegacyOptionValueAdapter.php
  Civi/Api4/Generic/AbstractAction.php
  Civi/Api4/Service/Spec/SpecGatherer.php
Labels: master

#32250 Convert custom data import to apiv4
  CRM/Activity/Import/Form/MapField.php
  CRM/Activity/Import/Parser/Activity.php
  CRM/Custom/Import/Parser/Api.php
  CRM/Import/Parser.php
  CRM/Upgrade/Incremental/php/SixOne.php
  tests/phpunit/CRM/Activity/Import/Parser/ActivityTest.php
  tests/phpunit/CRM/Custom/Import/Parser/ApiTest.php
Labels: master

#32234 Activity import - convert to apiv4
  CRM/Activity/Import/Form/MapField.php
  CRM/Activity/Import/Parser/Activity.php
  CRM/Import/Parser.php
  CRM/Upgrade/Incremental/php/SixOne.php
  tests/phpunit/CRM/Activity/Import/Parser/ActivityTest.php
Labels: master

#32265 Remove redundant custom field handling in contact import
  CRM/Contact/Import/Parser/Contact.php
Labels: master

#32267 [NFC] First Pass at 6.0 Release Notes
  contributor-key.yml
  release-notes/6.0.0.md
Labels: 6.0

#32273 Remove unused functions, old comments
  CRM/Contact/Import/Parser/Contact.php
Labels: master, merge on pass

#32275 6.0
  contributor-key.yml
  ext/search_kit/ang/crmSearchTasks/crmSearchTaskDownload.ctrl.js
  release-notes/6.0.0.md
Labels: master

#32280 remove duplicate contributor
  contributor-key.yml
Labels: merge on pass, 6.0

#32271 SearchKit - Fix permission check error
  ext/search_kit/Civi/Search/Meta.php
Labels: merge on pass, 6.0

#32274 Remove some contact_type wrangling from previously shared code
  CRM/Contact/Import/Parser/Contact.php
Labels: master

#32261 [REF] Faster pseudoconstant name lookups
  CRM/Contact/BAO/Query.php
Labels: master, merge on pass

#32279 6.0
  CRM/Financial/BAO/FinancialType.php
  contributor-key.yml
  ext/search_kit/Civi/Search/Meta.php
  tests/phpunit/CRM/Financial/BAO/FinancialTypeTest.php
Labels: master

#32276 Add test for opt out handling on import, ready for cleanup
  tests/phpunit/CRM/Contact/Import/Form/data/individual_external_identifier_opt_out.csv
  tests/phpunit/CRM/Contact/Import/Parser/ContactTest.php
Labels: master, merge on pass

#32231 Add function for setting max query execution time to core
  CRM/Core/DAO.php
  CRM/Utils/AutoClean.php
  tests/phpunit/CRM/Core/DAOTest.php
Labels: master, merge on pass

#32283 Move query code to the FinderOptimizer class
  CRM/Dedupe/BAO/DedupeRuleGroup.php
  CRM/Dedupe/FinderQueryOptimizer.php
  tests/phpunit/CRM/Dedupe/DedupeFinderTest.php
Labels: master

#32282 Fix dedupe lookup to use optimizer to combine queries
  CRM/Dedupe/BAO/DedupeRuleGroup.php
  CRM/Dedupe/FinderQueryOptimizer.php
  tests/phpunit/CRM/Dedupe/DedupeFinderTest.php
Labels: master, has-test

#32255 issue#5726 : Repeat Activity triggers an error
  Civi/Api4/Service/Spec/Provider/ActionScheduleSpecProvider.php
Labels: sig:regression, 6.0

#32272 [REF] Api4 - Performance tweak: less looping in selectArray()
  Civi/Api4/Generic/Traits/ArrayQueryActionTrait.php
Labels: master, merge ready

#32284 Further clean up in dedupe query builder
  CRM/Dedupe/FinderQueryOptimizer.php
Labels: master

#32277 Tidy up opt out handling in contact import
  CRM/Contact/Import/Parser/Contact.php
  CRM/Import/Parser.php
  CRM/Utils/Hook.php
Labels: master, has-test

#32293 Fix comment for getCMSPermissionsUrlParams
  CRM/Utils/System.php
Labels: master

#32292 Remove legacy handling for empty values on contact import
  CRM/Contact/Import/Parser/Contact.php
Labels: master

#32290 Core/File - Decouple file download links from the entityFile table
  CRM/Core/BAO/File.php
  CRM/Core/Page/File.php
  ext/search_kit/Civi/Api4/Action/SearchDisplay/AbstractRunAction.php
  tests/phpunit/CRM/Core/BAO/FileTest.php
  tests/phpunit/api/v3/AttachmentTest.php
Labels: master

#32295 Fix error message for invalid step
  Civi/Test/CiviEnvBuilder.php
Labels: master

#32256 Revert "Fix ActionSchedule save on repeat events"
  Civi/Api4/Service/Spec/Provider/ActionScheduleSpecProvider.php
Labels: sig:regression, 5.82

#32278 [REF] Ensure that Reply-To header is appropriately quoted if copying …
  CRM/Utils/Mail.php
Labels: master, merge on pass

#32301 Minor test cleanups
  tests/phpunit/CRM/Activity/Form/SearchTest.php
  tests/phpunit/CRM/Campaign/Form/CampaignTest.php
  tests/phpunit/CRM/Contribute/BAO/ContributionTest.php
  tests/phpunit/CRM/Mailing/BAO/SpoolTest.php
  tests/phpunit/api/v3/ContributionTest.php
  tests/phpunit/api/v3/LoggingTest.php
Labels: master

#32300 Fix recent updates to import member to align with import activity
  CRM/Activity/Import/Parser/Activity.php
  CRM/Custom/Import/Parser/Api.php
  CRM/Event/Import/Parser/Participant.php
  CRM/Import/Form/MapField.php
  CRM/Import/Forms.php
  CRM/Import/Parser.php
  CRM/Member/Import/Form/MapField.php
  CRM/Member/Import/Parser/Membership.php
  CRM/Upgrade/Incremental/php/SixOne.php
  tests/phpunit/CRM/Event/Import/Parser/ParticipantTest.php
  tests/phpunit/CRM/Member/Import/Parser/MembershipTest.php
Labels: master

#31893 dev/core#5387 add CiviCRM Maintenance Mode
  CRM/Api4/Page/AJAX.php
  CRM/Core/Invoke.php
  CRM/Core/Permission/Backdrop.php
  CRM/Core/Permission/Base.php
  CRM/Core/Permission/Drupal.php
  CRM/Core/Permission/Drupal8.php
  CRM/Utils/System.php
  CRM/Utils/System/Backdrop.php
  CRM/Utils/System/Base.php
  CRM/Utils/System/Drupal.php
  CRM/Utils/System/Drupal8.php
  api/v3/Job.php
  ext/standaloneusers/standaloneusers.php
  settings/Core.boot.setting.php
  tests/phpunit/api/v3/JobTest.php
  tests/phpunit/api/v4/Request/AjaxTest.php
Labels: master, merge on pass, has-test

#32303 Api4 - Update file url formatting
  Civi/Api4/Service/Spec/Provider/FileGetSpecProvider.php
  tests/phpunit/api/v4/Action/EntityFileTest.php
  tests/phpunit/api/v4/Custom/CustomFileTest.php
Labels: master

#32304 Optimize dedupe query in finder flow - speed improvement
  CRM/Dedupe/BAO/DedupeRuleGroup.php
  CRM/Dedupe/FinderQueryOptimizer.php
  tests/phpunit/CRM/Dedupe/DedupeFinderTest.php
Labels: has-test

#32308 Fix undefined array key error in Smarty
  CRM/Mailing/BAO/Mailing.php
Labels: master, merge on pass

#32285 (dev/core#5700) Extensions - Implement more robust downloader
  CRM/Admin/Form/Extensions.php
  CRM/Extension/Browser.php
  CRM/Extension/Downloader.php
  CRM/Extension/Manager.php
  CRM/Extension/QueueDownloader.php
  api/v3/Extension.php
  extension-compatibility.json
Labels: master

#32299 Update comments on setting property on admin forms
  CRM/Admin/Form/Preferences.php
  CRM/Admin/Form/Preferences/Address.php
  CRM/Admin/Form/Preferences/Display.php
  CRM/Admin/Form/Preferences/Member.php
Labels: master

#32312 [REF] Config - Clarify that directories have trailing slashes
  CRM/Core/BAO/File.php
  CRM/Core/Config.php
  CRM/Mailing/MailStore.php
  Civi/Core/AssetBuilder.php
  api/v3/Attachment.php
  schema/Core/File.entityType.php
  tests/phpunit/CRM/Activity/BAO/ActivityTest.php
  tests/phpunit/api/v3/AttachmentTest.php
Labels: master

#32306 Standalone - Remove crashy debug code
  CRM/Utils/System/Standalone.php
Labels: merge ready, run-standalone, 6.0

#32288 Afform - Prevent saving draft after submitting form
  ext/afform/core/ang/af/afForm.component.js
Labels: sig:unreleased-regression, 6.0

#31580 dev/core#5634 Add ImportTemplateField entity
  CRM/Core/DAO/ImportTemplateField.php
  CRM/Upgrade/Incremental/php/SixOne.php
  CRM/Upgrade/Incremental/schema/6.1.alpha1.ImportTemplateField.entityType.php
  Civi/Api4/ImportTemplateField.php
  schema/Core/ImportTemplateField.entityType.php
Labels: master

#32298 Fix a few test clean places
  tests/phpunit/CRM/Contact/BAO/ContactTest.php
  tests/phpunit/CRM/Contribute/Import/Parser/ContributionTest.php
  tests/phpunit/CRM/Core/BAO/ActionScheduleTest.php
  tests/phpunit/api/v3/ProfileTest.php
  tests/phpunit/api/v3/ReportTemplateTest.php
Labels: master

#32309 Follow on fix with a test
  CRM/Dedupe/FinderQueryOptimizer.php
  tests/phpunit/CRM/Dedupe/DedupeFinderTest.php
Labels: master, merge on pass

#32318 MixinTestCase - Run all operations the same way. Fix recent test-failure.
  Civi/Test/MixinTestCase.php
Labels: 6.0

#32313 6.0
  CRM/Utils/System/Standalone.php
  Civi/Api4/Service/Spec/Provider/ActionScheduleSpecProvider.php
  Civi/Test/MixinTestCase.php
  ext/afform/core/ang/af/afForm.component.js
  ext/riverlea/core/css/components/_components.css
  ext/riverlea/core/org.civicrm.search_kit-css/crmSearchAdmin.css
Labels: master

#32316 (Backport) "Scheduled Communications" - Fix test-only failures
  CRM/Core/DAO.php
  CRM/Utils/Time.php
  ext/scheduled_communications/tests/phpunit/Civi/ScheduledCommunications/SendTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/api/v4/Api4TestBase.php
Labels: 6.0

#32320 5.82.1 - Add notes. Set version.
  deleted-files-list.json
  js/version.json
  release-notes.md
  release-notes/5.82.1.md
  sql/civicrm_generated.mysql
  sql/test_data_second_domain.mysql
  xml/version.xml
Labels: 5.82

#32296 standaloneusers - remove unused password attribute from afform User entity
  ext/standaloneusers/afformEntities/User.php
  ext/standaloneusers/ang/afformEditUserAccount.aff.html
Labels: 6.1

#31944 FormBuilder - Now you can make Tab Sets 🎉
  ang/crmUi.js
  ang/crmUi/tabset.html
  ext/afform/admin/Civi/AfformAdmin/AfformAdminMeta.php
  ext/afform/admin/ang/afGuiEditor.css
  ext/afform/admin/ang/afGuiEditor/elements/afGuiContainer.component.js
  ext/afform/admin/ang/afGuiEditor/elements/afGuiContainer.html
  ext/afform/admin/ang/afGuiEditor/elements/afGuiTab-menu.html
  ext/afform/admin/ang/afGuiEditor/elements/afGuiTabset-menu.html
  ext/afform/admin/ang/afGuiEditor/elements/afGuiTabset.component.js
  ext/afform/admin/ang/afGuiEditor/elements/afGuiTabset.html
  ext/afform/core/CRM/Afform/ArrayHtml.php
  ext/afform/core/ang/af/afTabset.component.js
  ext/afform/core/ang/af/afTabset.html
  ext/afform/core/ang/afCore.css
  ext/civi_campaign/ang/afsearchCampaignDashboard.aff.html
Labels: master, merge ready

#32323 dev/core#5779 - Don't crash when a cg_extends option is disabled, like civigrant
  CRM/Core/BAO/CustomGroup.php
Labels: merge on pass, 6.1

#32324 backport 32323
  CRM/Core/BAO/CustomGroup.php
Labels: merge on pass, 6.0

#32325 6.1
  CRM/Core/BAO/CustomGroup.php
  ext/standaloneusers/afformEntities/User.php
  ext/standaloneusers/ang/afformEditUserAccount.aff.html
Labels: master

#31808 Smarty notice fix on tell-a-friend
  CRM/Event/Form/Registration/ThankYou.php
  templates/CRM/Event/Form/Registration/ThankYou.tpl
Labels: master

#32310 PHAR Loading - Enable PharStreamWrapper on Backdrop CMS
  CRM/Core/ClassLoader.php
  CRM/Core/Invoke.php
  Civi/Core/Security/PharLoader.php
  tests/phpunit/E2E/Core/PharTest.php
  tests/phpunit/E2E/Core/greeter.phar
Labels: merge ready, has-test, run-drupal-x, run-wordpress, run-backdrop, 6.1

#32327 Drupal8::isMaintenceMode() - Don't crash on new/clean sites
  CRM/Utils/System/Drupal8.php
Labels: run-drupal-x, 6.1

#32328 6.1
  CRM/Core/ClassLoader.php
  CRM/Core/Invoke.php
  CRM/Utils/System/Drupal8.php
  Civi/Core/Security/PharLoader.php
  tests/phpunit/E2E/Core/PharTest.php
  tests/phpunit/E2E/Core/greeter.phar
Labels: master

#32326 File - Fix links that do not include entityId
  CRM/Core/Page/File.php
Labels: sig:unreleased-regression, 6.1

#32330 6.1
  CRM/Core/Page/File.php
Labels: master

#32249 [REF] Update to release version 1.14.5 for pear/log to fix implicit nullable deprecation i....
  composer.json
  composer.lock
Labels: master

#32332 File - set default in sql for upload_date
  CRM/Upgrade/Incremental/php/SixTwo.php
  schema/Core/File.entityType.php
Labels: master

#32333 File - consistently set created_id
  CRM/Core/BAO/File.php
Labels: master

#32334 core-5773 Prevent survey from wrongly setting checkboxes
  templates/CRM/Campaign/Form/Task/Interview.tpl
Labels: master

#32339 Upgrader - Ensure rebuildMenuAndCaches() runs with fresh container
  CRM/Upgrade/Form.php
Labels: master

#32343 Fix Financial Type wrench on select
  CRM/Core/PseudoConstant.php
Labels: sig:regression

#32340 Pacify SqlFunctionTest. Encode limitations of APIv4 TIMESTAMPDIFF().
  tests/phpunit/api/v4/Action/SqlFunctionTest.php
Labels: 6.1

#32346 6.1
  tests/phpunit/api/v4/Action/SqlFunctionTest.php
Labels: master

#32347 Allow using "abbr" for domain.state_province_id token
  CRM/Core/DomainTokens.php
  tests/phpunit/CRM/Utils/TokenConsistencyTest.php
Labels: master

#32263 riverlea - fix is_active to allow streams from external extensions
  ext/riverlea/riverlea.php
Labels: master

#31495 Do not add custom fields of custom groups with style other than "Inline" to forms where in the UI those fields are loaded via Ajax
  CRM/Custom/Form/CustomDataTrait.php
Labels: 6.0

#32337 (dev/core#5788) Revert "Api3 - Delete mailing_group_event* APIs"
  api/v3/MailingGroup.php
Labels: merge on pass, 6.1

#32350 (dev/core#5788) Revert "Api3 - Delete mailing_group_event* APIs"
  api/v3/MailingGroup.php
Labels: 6.0

#32353 Advanced Search: standardize labels (singular, no question mark)
  CRM/Activity/BAO/Query.php
  CRM/Contact/Form/Search/Criteria.php
  CRM/Mailing/BAO/Query.php
  templates/CRM/Activity/Form/Search.tpl
  templates/CRM/Activity/Form/Search/Common.tpl
  templates/CRM/Campaign/Form/Search/Common.tpl
  templates/CRM/Contact/Form/Search/Criteria/Fields/group.tpl
  templates/CRM/Contact/Form/Search/Criteria/Fields/sort_name.tpl
Labels: master, sig:user interfacing improvement

#32352 Do not add custom fields of custom groups with style other than "Inli…
  CRM/Custom/Form/CustomDataTrait.php
Labels: merge on pass

#32354 Comment fix - remove experimental on well used code
  CRM/Queue/Runner.php
Labels: master

#32345 (Performance) ManagedEntities - Only update an entity if its declaration has changed
  CRM/Case/BAO/CaseType.php
  CRM/Core/DAO/Managed.php
  CRM/Core/ManagedEntities.php
  CRM/Upgrade/Incremental/php/SixTwo.php
  CRM/Utils/Array.php
  schema/Core/Managed.entityType.php
  tests/phpunit/CRM/Utils/ArrayTest.php
Labels: master

#32358 dev/core#5791 Extract function to update mapping
  CRM/Upgrade/Incremental/php/SixOne.php
Labels: 6.1

#32364 EntityTag - Remove redundant deletes already handled by hook
  CRM/Activity/Form/Activity.php
  CRM/Case/Form/Activity.php
  CRM/Core/BAO/File.php
  tests/phpunit/api/v4/Action/EntityFileTest.php
Labels: master

#32365 Queue.run API - Log an alert for unhandled exceptions
  Civi/Api4/Action/Queue/Run.php
Labels: master

#32367 Catch throwable (e.g typehint) in queue handler
  CRM/Queue/BasicHandlerTrait.php
Labels: master, merge on pass

#32335 (dev/core#5787) ClassScanner - Ignore stale files during Joomla upgrade
  Civi/Core/ClassScanner.php
Labels: run-distmaker, 6.1

#32336 (dev/core#5787) ClassScanner - Ignore stale files during Joomla upgrade
  Civi/Core/ClassScanner.php
Labels: run-distmaker, 6.0

#32355 dev/core#5790 Added API4 query function IS NOT NULL
  Civi/Api4/Query/SqlFunctionISNOTNULL.php
  tests/phpunit/api/v4/Action/SqlFunctionTest.php
Labels: master, merge on pass, has-test

#32291 dev/core#5770 SK edit-in-place: focus appropriately when inline editing is initiated
  ext/search_kit/ang/crmSearchDisplay/colType/editable.html
  ext/search_kit/ang/crmSearchDisplay/crmSearchDisplayEditable.component.js
  ext/search_kit/ang/crmSearchDisplay/crmSearchDisplayEditable.html
  ext/search_kit/ang/crmSearchDisplay/traits/searchDisplayEditableTrait.service.js
  ext/search_kit/ang/crmSearchTasks/crmSearchInput/crmSearchInputFocus.directive.js
  js/Common.js
Labels: master, merge ready

#32374 6.0.1 - Add notes. Set version.
  deleted-files-list.json
  js/version.json
  release-notes.md
  release-notes/6.0.1.md
  sql/civicrm_generated.mysql
  sql/test_data_second_domain.mysql
  xml/version.xml
Labels: merge on pass, 6.0

#32362 CustomGroup - Make `name`, `extends`, and `style` required.
  CRM/Core/Smarty/plugins/block.localize.php
  CRM/Upgrade/Incremental/php/SixTwo.php
  CRM/Upgrade/Incremental/sql/5.63.alpha1.mysql.tpl
  CRM/Upgrade/Incremental/sql/5.65.alpha1.mysql.tpl
  CRM/Upgrade/Incremental/sql/5.71.alpha1.mysql.tpl
  CRM/Upgrade/Incremental/sql/6.2.alpha1.mysql.tpl
  Civi/Api4/Service/Spec/Provider/CustomGroupCreationSpecProvider.php
  deleted-files-list.json
  schema/Core/CustomGroup.entityType.php
Labels: master

#32130 Remove the Mailing Forward feature
  CRM/Contact/Form/Search.php
  CRM/Core/SelectValues.php
  CRM/Mailing/BAO/Mailing.php
  CRM/Mailing/BAO/Query.php
  CRM/Mailing/Event/BAO/Forward.php
  CRM/Mailing/Event/BAO/MailingEventForward.php
  CRM/Mailing/Event/DAO/Forward.php
  CRM/Mailing/Event/DAO/MailingEventForward.php
  CRM/Mailing/Form/ForwardMailing.php
  CRM/Mailing/Selector/Event.php
  CRM/Mailing/xml/Menu/Mailing.xml
  CRM/Report/Form/Mailing/Detail.php
  CRM/SMS/Form/Upload.php
  CRM/Utils/Check/Component/Timestamps.php
  CRM/Utils/Token.php
  api/v3/Mailing.php
  ext/civi_mail/Civi/Api4/MailingEventForward.php
  ext/civi_mail/ang/crmMailing/services.js
  schema/Mailing/MailingEventForward.entityType.php
  sql/civicrm_generated.mysql
  templates/CRM/Mailing/Form/ForwardMailing.tpl
  templates/CRM/Mailing/Form/Search/Common.tpl
  templates/CRM/Mailing/Page/Report.tpl
  tests/phpunit/CRM/Mailing/MailingSystemTest.php
  tests/phpunit/api/v3/JobProcessMailingTest.php
  tests/phpunit/api/v3/MailingTest.php
  tests/phpunit/api/v4/Entity/MailingEventTest.php
Labels: master, merge ready

#32360 dev/core#5791 Address rc regression on handling ambigous 'source' in contribution import
  CRM/Contribute/Import/Form/MapField.php
  CRM/Contribute/Import/Parser/Contribution.php
  CRM/Event/Import/Form/MapField.php
  CRM/Event/Import/Parser/Participant.php
  CRM/Import/Form/MapField.php
  CRM/Import/Parser.php
  CRM/PCP/BAO/PCP.php
  CRM/Upgrade/Incremental/php/SixOne.php
  tests/phpunit/CRM/Contribute/Import/Parser/ContributionTest.php
  tests/phpunit/CRM/Event/Import/Parser/ParticipantTest.php
Labels: merge on pass, 6.1

#32377 (dev/core#5794) Financial ACLs - Fix upgrade error
  ext/financialacls/financialacls.php
Labels: merge on pass, 6.1

#32378 (dev/core#5794) Financial ACLs - Fix upgrade error
  ext/financialacls/financialacls.php
Labels: merge on pass, 6.0

#32322 Event dashboard slow on large site
  CRM/Event/Page/DashBoard.php
Labels: master, merge ready

#32331 File - deprecate 'document' field from File entity.
  schema/Core/File.entityType.php
  tests/phpunit/CRM/Core/BAO/FileTest.php
Labels: master

#32314 additional dedupe finder test
  tests/phpunit/CRM/Dedupe/DedupeFinderTest.php
Labels: master

#32357 don't allow payment on a canceled invoice
  CRM/Contribute/Form/Contribution/Main.php
Labels: master

#32286 specify light mode for civicrm.css to fix Standalone logo in Greenwich
  css/civicrm.css
Labels: 6.1

#32351 RiverLea 1.4.0: GL116, GL117, GL119: UX improvements
  ext/riverlea/CHANGELOG.md
  ext/riverlea/README.md
  ext/riverlea/core/css/_core.css
  ext/riverlea/core/css/components/_tables.css
  ext/riverlea/core/css/contactSummary.css
  ext/riverlea/core/org.civicrm.afform_admin-ang/afGuiEditor.css
  ext/riverlea/info.xml
Labels: master

#32373 dev/core#5781 Afform - Prevent jquery validate from messing everything up
  CRM/Core/Resources/Common.php
Labels: master

#32386 Remove invalid table markup on event tab
  templates/CRM/Event/Page/Tab.tpl
Labels: master

#32382 Upgrades - Port civicrm-upgrade-test to PHPUnit
  Civi/Core/Container.php
  Civi/Test/Exception/ProcessErrorException.php
  Civi/Test/ProcessHelper.php
  Civi/Test/Schema.php
  tests/phpunit/CiviTest/bootstrap.php
  tests/phpunit/Upgrade/UpgradeSnapshotTest.php
Labels: master

#32380 dev/core#5716 Fix Regression with CheckBox custom fields not respecti…
  CRM/Core/BAO/CustomField.php
  CRM/Core/Form.php
  CRM/Core/QuickForm/AdvCheckBoxWithDiv.php
Labels: merge ready, 6.1

#32379 Fix Membership import inline with fixes on participant, contribution
  CRM/Custom/Import/Form/MapField.php
  CRM/Import/Form/MapField.php
  CRM/Member/Import/Parser/Membership.php
  tests/phpunit/CRM/Custom/Import/Parser/ApiTest.php
Labels: merge on pass, 6.1

#32381 RiverLea Thames Dark Mode / Extensions colour fix
  ext/riverlea/streams/thames/css/_dark.css
Labels: 6.0

#32219 Display error for API4 batch action
  ext/search_kit/ang/crmSearchTasks/crmSearchBatchRunner.component.js
Labels: master

#32341 dev/core#5418 - Fix Missing Translation for Self Service Event Cancelation
  CRM/Event/BAO/Participant.php
  templates/CRM/Event/Form/SelfSvcTransfer.tpl
  templates/CRM/Event/Form/SelfSvcUpdate.tpl
Labels: master

#32387 6.1
  CRM/Core/BAO/CustomField.php
  CRM/Core/Form.php
  CRM/Core/QuickForm/AdvCheckBoxWithDiv.php
  CRM/Custom/Import/Form/MapField.php
  CRM/Import/Form/MapField.php
  CRM/Member/Import/Parser/Membership.php
  css/civicrm.css
  ext/financialacls/financialacls.php
  tests/phpunit/CRM/Custom/Import/Parser/ApiTest.php
Labels: master

#32393 RiverLea Thames Dark Mode / Extensions colour fix
  ext/riverlea/streams/thames/css/_dark.css
Labels: 6.1

#32390 [NFC] riverlea - remove some double definitions
  ext/riverlea/streams/hackneybrook/css/_dark.css
  ext/riverlea/streams/minetta/css/_dark.css
  ext/riverlea/streams/thames/css/_variables.css
  ext/riverlea/streams/thames/css/civicrm.css
  ext/riverlea/streams/walbrook/css/_dark.css
Labels: master

#32385 [REF][PHP8.2] Declare property on CRM_PCP_Form_PCP
  CRM/PCP/Form/PCP.php
Labels: master, merge on pass

#32392 dev/core#5797 standalone - implement minimal header in maintenance mode
  CRM/Utils/System/Standalone.php
Labels: sig:regression, 6.0

#32398 (dev/core#5797) Standalone - Implement minimal header in maintenance mode
  CRM/Utils/System/Standalone.php
Labels: 6.1

#32389 riverlea - fix checkbox-list in hackneybrook dark mode
  ext/riverlea/streams/hackneybrook/css/_dark.css
Labels: 6.1

#32388 [backport] riverlea - fix checkbox-list in hackneybrook dark mode
  ext/riverlea/streams/hackneybrook/css/_dark.css
Labels: 6.0

#32397 Use get permissions for getMergedTo, getMergedFrom
  CRM/Core/Permission.php
  Civi/Api4/Action/Contact/GetMergedFrom.php
  Civi/Api4/Action/Contact/GetMergedTo.php
Labels: master

#32399 6.1
  CRM/Utils/System/Standalone.php
  ext/riverlea/streams/hackneybrook/css/_dark.css
Labels: master

#32403 Add peetcreative to colaborators
  contributor-key.yml
Labels: master

#32395 Add new Contact api actions to discoverable list
  Civi/Api4/Contact.php
Labels: master

#32396 Use merged to contact if attempt is made to import to a merged contact
  CRM/Import/Parser.php
  tests/phpunit/CRM/Contribute/Import/Parser/ContributionTest.php
Labels: master

#32405 6.0.2 - Add notes. Set version.
  js/version.json
  release-notes.md
  release-notes/6.0.2.md
  sql/civicrm_generated.mysql
  sql/test_data_second_domain.mysql
  xml/version.xml
Labels: 6.0

#32406 Fix notice in help text on settings pages
  CRM/Core/Smarty/plugins/function.help.php
  templates/CRM/Core/Form/Field.tpl
Labels: master

#32404 Fix validation regression on 6.1
  CRM/Contribute/Import/Form/MapField.php
Labels: 6.1

#32361 Allow `hook_civicrm_pre()` delete on a contact to delete a CMS user
  CRM/Contact/BAO/Contact.php
Labels: master, merge ready

#32417 Extensions - Fix new error in cv's ExtensionLifecycleTest
  CRM/Extension/Manager.php
  CRM/Extension/Mapper.php
  CRM/Extension/System.php
Labels: master

#32414 Civi-Import UI permissions
  ext/civiimport/Civi/Api4/Event/Subscriber/ImportSubscriber.php
Labels: master

#32431 Increase length of display_name in SiteEmailAddress
  CRM/Upgrade/Incremental/php/SixOne.php
  CRM/Upgrade/Incremental/schema/6.0.alpha1.SiteEmailAddress.entityType.php
  schema/Core/SiteEmailAddress.entityType.php
Labels: 6.1

#32430 Enable Civiimport for membership import
  CRM/Contribute/Import/Parser/Contribution.php
  CRM/Import/Form/MapField.php
  CRM/Import/Parser.php
  CRM/Member/Import/Form/MapField.php
  CRM/Member/Import/Parser/Membership.php
  ext/civiimport/civiimport.php
Labels: master, merge on pass

#32425 Check contribution tab exists before marking it as valid
  CRM/Contribute/Form/ContributionPage/TabHeader.php
Labels: sig:regression, 6.1

#32408 dev/core#5801 Form Builder: repeating with join gives an error
  ext/afform/core/Civi/Api4/Action/Afform/AbstractProcessor.php
Labels: master

#32441 Check contribution tab exists before marking it as valid
  CRM/Contribute/Form/ContributionPage/TabHeader.php
Labels: merge on pass, sig:regression, 6.0

#32437 dev/core#5708 Fix failure to save Custom fields on backoffice submit card membership
  CRM/Core/BAO/CustomField.php
  CRM/Custom/Form/CustomDataTrait.php
  CRM/Member/Form/Membership.php
Labels: merge on pass, sig:regression, 6.1

#32440 6.1 to master
  CRM/Contribute/Form/ContributionPage/TabHeader.php
  CRM/Core/BAO/CustomField.php
  CRM/Custom/Form/CustomDataTrait.php
  CRM/Import/Parser.php
  CRM/Member/Form/Membership.php
  CRM/Upgrade/Incremental/php/SixOne.php
  CRM/Upgrade/Incremental/schema/6.0.alpha1.SiteEmailAddress.entityType.php
  schema/Core/SiteEmailAddress.entityType.php
  tests/phpunit/CRM/Contribute/Import/Parser/ContributionTest.php
  tests/phpunit/CRMTraits/Import/ParserTrait.php
Labels: master

#32439 CustomGroup - Simplify getShortNameFromLongName
  CRM/Core/BAO/CustomField.php
  tests/phpunit/CRM/Core/BAO/CustomFieldTest.php
Labels: master, merge on pass

#32411 dev/core#5798 - fix contrast on standaloneusers role display
  ext/standaloneusers/managed/SavedSearch_Permissions.mgd.php
Labels: 6.0

#32448 standaloneusers - use only circle icons on permissions display
  ext/standaloneusers/managed/SavedSearch_Permissions.mgd.php
Labels: master

#32434 dev/core#5780 Fix tell-a-friend not rendering on Manage events
  ext/tellafriend/tellafriend.php
Labels: merge on pass, 6.1

#32450 SearchKit - Fix 'Select Current User' selection
  ext/search_kit/ang/crmSearchTasks/crmSearchInput/crmSearchInput.component.js
Labels: sig:regression, 6.1

#32451 SearchKit - Fix 'Select Current User' selection
  ext/search_kit/ang/crmSearchTasks/crmSearchInput/crmSearchInput.component.js
Labels: sig:regression, 6.0

#32436 Api4 - Improve efficiency of FormattingUtil::formatOutputValues
  Civi/Api4/Generic/Traits/CustomValueActionTrait.php
  Civi/Api4/Generic/Traits/DAOActionTrait.php
  Civi/Api4/Generic/Traits/PseudoconstantOutputTrait.php
  Civi/Api4/Query/Api4EntitySetQuery.php
  Civi/Api4/Query/Api4SelectQuery.php
  Civi/Api4/Utils/FormattingUtil.php
  ext/civi_contribute/Civi/Api4/Action/Payment/Create.php
  ext/search_kit/Civi/Api4/Action/SearchDisplay/GetDefault.php
Labels: master, merge ready

#32453 dev/core#5718 [REF] Catch Exceptions caused by CRM_Utils_Array::single() if there i…
  CRM/Custom/Page/CustomDataTrait.php
Labels: 6.1

#32454 [REF] Catch Exceptions caused by CRM_Utils_Array::single() if there i…
  CRM/Custom/Page/CustomDataTrait.php
Labels: 6.0

#32432 Increase length of display_name in SiteEmailAddress
  CRM/Upgrade/Incremental/php/SixZero.php
  CRM/Upgrade/Incremental/schema/6.0.alpha1.SiteEmailAddress.entityType.php
  js/version.json
  schema/Core/SiteEmailAddress.entityType.php
  sql/civicrm_generated.mysql
  sql/test_data_second_domain.mysql
  xml/version.xml
Labels: merge on pass, sig:regression, 6.0

#32415 Fix fatal error when a user with limited permissions edits their own contact using the contact summary interface
  CRM/Contact/Form/Contact.php
Labels: master, merge on pass

#32438 dev/core#5708 Fix failure to save Custom fields on backoffice submit …
  CRM/Core/BAO/CustomField.php
  CRM/Custom/Form/CustomDataTrait.php
  CRM/Member/Form/Membership.php
Labels: 6.0

#32460 (NFC) Fix typo in periodically
  CRM/Core/xml/Menu/Admin.xml
  sql/civicrm_generated.mysql
Labels: master

#32458 [REF][PHP8.2] Replace undeclared property with local variable (CRM_Grant_Form_Grant)
  ext/civigrant/CRM/Grant/Form/Grant.php
Labels: master

#32455 dev/core#5806 Fix fatal error regression on custom data save
  CRM/Custom/Form/CustomDataTrait.php
Labels: merge on pass, 6.0

#32456 dev/core#5806 Fix fatal error regression on custom data save
  CRM/Custom/Form/CustomDataTrait.php
Labels: 6.1

#32445 dev/core#5715 check civicontribute is enabled before loading Payment Processor admin
  CRM/Admin/Page/PaymentProcessor.php
Labels: 6.1

#32447 [NFC] 6.1 release notes first pass
  contributor-key.yml
  release-notes/6.1.0.md
Labels: 6.1

#32449 fix invalid key errors
  CRM/Core/Controller.php
  CRM/Core/Page.php
Labels: 6.1

#32452 Notice fix, use local variable
  CRM/Profile/Page/Dynamic.php
Labels: master

#32459 [REF][PHP8.2] Declare properties CRM_Campaign_Selector_Search
  CRM/Campaign/Selector/Search.php
Labels: master

#32461 Sessions - Fix TypeError when detecting an invalid key
  CRM/Core/Controller.php
  CRM/Core/Page.php
Labels: 6.0

#32435 dev/core#5780 Fix tell-a-friend not rendering on Manage events
  ext/tellafriend/tellafriend.php
Labels: 6.0
