Repository civicrm/civicrm-core, pull requests merged in 2025-02, with the labels that each got.

#31921 (dev/core#5712) Debug Mode - Provide consistent behavior for BD/D7
  CRM/Core/Region.php
Labels: master

#31917 [REF] Migrate determining the connection details to use from Drupal8 …
  setup/plugins/init/Drupal8.civi-setup.php
  setup/src/Setup/DrupalUtil.php
Labels: master, merge ready, run-drupal-x

#31923 Fix escaping relationship display name
  CRM/Contact/Form/Relationship.php
Labels: sig:unreleased-regression, 5.82

#31925 5.82
  CRM/Contact/Form/Relationship.php
  contributor-key.yml
  ext/afform/core/afform.php
  ext/afform/mock/tests/phpunit/E2E/AfformMock/MockPublicFormTest.php
  release-notes/5.82.0.md
Labels: master

#31460 (dev/core#5464) Iframe - Add support for hosting Civi IFRAMEs on WordPress
  ext/iframe/Civi/Iframe/Iframe.php
  ext/iframe/Civi/Iframe/Router.php
  ext/iframe/Civi/Iframe/ScriptManager.php
Labels: master, merge ready

#31929 A11y - Add aria roles to tablists
  ang/api4Explorer/Explorer.html
  ang/crmUi.js
  ang/crmUi/tabset.html
  ext/afform/admin/ang/afAdmin/afAdminList.html
  ext/afform/admin/ang/afGuiEditor/afGuiEditorCanvas.html
  ext/afform/admin/ang/afGuiEditor/afGuiEditorPalette.html
  ext/message_admin/ang/crmMsgadm/ListNav.html
  ext/oauth-client/ang/oauthProviderDetail.aff.html
  ext/search_kit/ang/crmSearchAdmin/searchListing/searchList.html
  templates/CRM/Admin/Page/APIExplorer.tpl
  templates/CRM/Admin/Page/Extensions.tpl
  templates/CRM/Admin/Page/MessageTemplates.tpl
  templates/CRM/Contribute/Page/DashBoard.tpl
  templates/CRM/Report/Form/Fields.tpl
  templates/CRM/Report/Form/Tabs/Developer.tpl
  templates/CRM/Report/Form/Tabs/FieldSelection.tpl
  templates/CRM/Report/Form/Tabs/Filters.tpl
  templates/CRM/Report/Form/Tabs/GroupBy.tpl
  templates/CRM/Report/Form/Tabs/Instance.tpl
  templates/CRM/Report/Form/Tabs/OrderBy.tpl
  templates/CRM/Report/Form/Tabs/ReportOptions.tpl
  templates/CRM/Tag/Page/Tag.tpl
  templates/CRM/UF/Page/Group.tpl
  templates/CRM/common/TabHeader.tpl
Labels: master

#31926 [NFC] 5.82 release note late changes
  release-notes/5.82.0.md
Labels: 5.82

#31940 Break variable assignment into 2 rows
  CRM/Import/Parser.php
Labels: master

#31939 Remove unreachable code
  CRM/Activity/Import/Parser/Activity.php
Labels: master

#31938 Stop setting unused variable
  CRM/Activity/Import/Parser/Activity.php
Labels: master

#31935 5.82 to master
  release-notes/5.82.0.md
Labels: master

#31942 Minor clean up in test class
  tests/phpunit/CRM/Member/BAO/MembershipTest.php
Labels: master

#31945 release notes update - add info that was in master but not 5.82
  contributor-key.yml
  release-notes/5.82.0.md
Labels: 5.82

#30034 dev/core#4389 Display ID field on imports for all modes
  CRM/Contact/Import/Form/MapField.php
  CRM/Import/Forms.php
Labels: master

#31937 Remove unused properties, duplicate catch
  CRM/Member/Import/Parser/Membership.php
Labels: master

#31918 Profile - Fix e-notice when displaying website field with no value
  CRM/Utils/System.php
Labels: master

#31930 RiverLea 1.3.4: 3 Thames & 1 core fix, ref MR #49
  ext/riverlea/CHANGELOG.md
  ext/riverlea/core/css/_core.css
  ext/riverlea/core/css/contactSummary.css
  ext/riverlea/info.xml
  ext/riverlea/streams/thames/css/_variables.css
  ext/riverlea/streams/thames/css/civicrm.css
Labels: master

#31946 update phpspreadsheet
  composer.lock
Labels: 5.82

#31947 5.82
  composer.lock
  contributor-key.yml
  release-notes/5.82.0.md
Labels: master

#31934 Deprecate a couple of old bits of format wrangling
  CRM/Dedupe/Finder.php
Labels: master

#31936 Move helper function from test to shared test trait
  tests/phpunit/CRM/Contribute/Import/Parser/ContributionTest.php
  tests/phpunit/CRMTraits/Import/ParserTrait.php
Labels: master

#31951 [NFC] remove duplicate from contributor-key.yml
  contributor-key.yml
Labels: master

#31933 Fold copy of getTree back into only caller
  CRM/Dedupe/Finder.php
Labels: master

#31932 Remove BAO_CustomGroup::postProcess deprecated in 5.71
  CRM/Core/BAO/CustomGroup.php
Labels: master

#31955 Remove unused parameter from private function
  CRM/Contribute/Form/Contribution.php
Labels: master, merge on pass

#31948 Use shared getContactMatchingFields from membership import metadata
  CRM/Import/Parser.php
  CRM/Member/Import/Parser/Membership.php
Labels: master, merge on pass

#31906 Afform - Improve UX for batch-processing submissions
  ext/afform/admin/managed/FormSubmissionSavedSearch.mgd.php
  ext/afform/core/afform.php
  ext/afform/core/ang/afSearchTasks.ang.php
  ext/afform/core/ang/afSearchTasks.module.js
  ext/afform/core/ang/afSearchTasks/afformSubmissionProcessTask.ctrl..js
  ext/afform/core/ang/afSearchTasks/afformSubmissionProcessTask.html
  ext/afform/core/managed/AfformSubmissionStatus.mgd.php
  ext/search_kit/Civi/Api4/Action/SearchDisplay/AbstractRunAction.php
  ext/search_kit/Civi/Api4/Action/SearchDisplay/GetSearchTasks.php
  ext/search_kit/ang/crmSearchTasks/crmSearchBatchRunner.component.js
  ext/search_kit/ang/crmSearchTasks/traits/searchDisplayTasksTrait.service.js
Labels: master

#31953 dev/core#5717 Ensure `getProfiles()` always returns an array
  CRM/Core/WorkflowMessage/ProfileTrait.php
Labels: merge on pass, 5.82

#31957 Remove assigns from previously shared code
  CRM/Contribute/Form/Contribution.php
Labels: master

#31958 Discourage accessing `$form->_values`
  CRM/Contribute/Form/Contribution.php
Labels: master

#31952 Stop using deprecated constant
  CRM/Activity/Form/Task/SMS.php
Labels: master, merge on pass

#31941 Minor test cleanup on setUp & tearDown
  tests/phpunit/CRM/Member/Import/Parser/MembershipTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/api/v3/MembershipTest.php
Labels: master, merge on pass

#31778 Remove deprecated SMSCommon.php
  CRM/Contact/Form/Task/SMSCommon.php
  deleted-files-list.json
Labels: master

#31960 Address deprecation notice
  CRM/Member/Import/Form/MapField.php
Labels: master

#31961 RiverLea 1.3.5: Contact dashboard inline edit - fixes lab/#107 - and delete icon colour.
  ext/riverlea/CHANGELOG.md
  ext/riverlea/core/css/_core.css
  ext/riverlea/core/css/_fixes.css
  ext/riverlea/core/css/components/_icons.css
  ext/riverlea/core/css/contactSummary.css
  ext/riverlea/info.xml
Labels: master

#31963 i18n: throw an exception if an invalid escape mode is used
  CRM/Core/I18n.php
Labels: master, merge on pass

#31916 [REF] Chart kit - move reduce types to a separate service
  ext/chart_kit/README.md
  ext/chart_kit/ang/crmChartKit/chartKitChartTypes.service.js
  ext/chart_kit/ang/crmChartKit/chartKitColumnConfig.service.js
  ext/chart_kit/ang/crmChartKit/chartKitReduceTypes.service.js
  ext/chart_kit/ang/crmChartKit/crmSearchDisplayChartKit.component.js
  ext/chart_kit/ang/crmChartKit/searchAdminDisplayChartKit.component.js
Labels: master

#30427 Membership renewal form: Clarify "Date renewal entered"
  CRM/Member/Form/MembershipRenewal.php
  templates/CRM/Member/Form/MembershipRenewal.tpl
Labels: master, merge on pass, sig:user interfacing improvement

#31956 Move remaining 'build' functions from AdditionalInfo to only caller
  CRM/Contribute/Form/AdditionalInfo.php
  CRM/Contribute/Form/Contribution.php
Labels: master, merge on pass

#29541 Add Personal Campaign Page Admin UI Screen
  ext/civicrm_admin_ui/ang/afsearchPersonalCampaignPages.aff.html
  ext/civicrm_admin_ui/ang/afsearchPersonalCampaignPages.aff.php
  ext/civicrm_admin_ui/managed/SavedSearch_Personal_Campaign_Pages.mgd.php
Labels: master

#31962 Remove unreachable & do-nothing code
  CRM/Member/Import/Parser/Membership.php
  tests/phpunit/CRM/Member/Import/Parser/MembershipTest.php
  tests/phpunit/CRM/Member/Import/Parser/data/memberships_with_id.csv
Labels: master, merge on pass, has-test

#31966 Developer settings page - switch to generating from meta
  CRM/Admin/Form/Setting/Debugging.php
  settings/Developer.setting.php
  templates/CRM/Admin/Form/Setting/Debugging.hlp
  templates/CRM/Admin/Form/Setting/Debugging.tpl
Labels: master

#31950 Fix mail settings page to use metadata
  CRM/Admin/Form/Preferences/Mailing.php
  settings/Mailing.setting.php
Labels: master, merge on pass

#31968 [REF] Add back in support to buildOptions for fields with pseudoconst…
  CRM/Core/DAO.php
Labels: 5.82

#31970 5.82
  CRM/Core/DAO.php
  CRM/Core/WorkflowMessage/ProfileTrait.php
Labels: master

#31969 Clarify function parameter
  CRM/Contribute/Form/Contribution/Confirm.php
Labels: master

#31972 Move parameter standardisation to before the hook, add test
  CRM/Contact/BAO/Contact.php
  CRM/Dedupe/Finder.php
  tests/phpunit/CRM/Dedupe/DedupeFinderTest.php
Labels: master, merge on pass

#31973 Standardise parameter type (bool)
  CRM/Contact/BAO/Contact.php
Labels: master, merge on pass

#31332 Add TIMESTAMPDIFF function to searchkit so you can show time between two dates
  Civi/Api4/Query/SqlExpression.php
  Civi/Api4/Query/SqlFunction.php
  Civi/Api4/Query/SqlFunctionTIMESTAMPDIFF.php
  ext/search_kit/ang/crmSearchAdmin.module.js
  ext/search_kit/ang/crmSearchAdmin/crmSearchFunction.component.js
  tests/phpunit/api/v4/Action/SqlFunctionTest.php
Labels: master, merge ready

#31910 SqlGenerator - Ensure FK index names are not too long
  mixin/lib/civimix-schema@5/src/SqlGenerator.php
Labels: master, merge ready

#31885 Upgrade core extensions to civix v25.01.1
  ext/afform/admin/afform_admin.civix.php
  ext/afform/admin/info.xml
  ext/afform/core/info.xml
  ext/afform/html/info.xml
  ext/afform/login_token/info.xml
  ext/afform/mock/info.xml
  ext/authx/info.xml
  ext/chart_kit/info.xml
  ext/civi_campaign/civi_campaign.civix.php
  ext/civi_campaign/info.xml
  ext/civi_case/civi_case.civix.php
  ext/civi_case/info.xml
  ext/civi_contribute/civi_contribute.civix.php
  ext/civi_contribute/info.xml
  ext/civi_event/civi_event.civix.php
  ext/civi_event/info.xml
  ext/civi_mail/civi_mail.civix.php
  ext/civi_mail/info.xml
  ext/civi_member/civi_member.civix.php
  ext/civi_member/info.xml
  ext/civi_pledge/civi_pledge.civix.php
  ext/civi_pledge/info.xml
  ext/civi_report/civi_report.civix.php
  ext/civi_report/info.xml
  ext/civicrm_admin_ui/civicrm_admin_ui.civix.php
  ext/civicrm_admin_ui/info.xml
  ext/civicrm_search_ui/civicrm_search_ui.civix.php
  ext/civicrm_search_ui/info.xml
  ext/civigrant/info.xml
  ext/civiimport/info.xml
  ext/ckeditor4/ckeditor4.civix.php
  ext/ckeditor4/info.xml
  ext/contributioncancelactions/info.xml
  ext/elavon/info.xml
  ext/eventcart/info.xml
  ext/ewaysingle/info.xml
  ext/financialacls/info.xml
  ext/flexmailer/info.xml
  ext/greenwich/info.xml
  ext/iframe/info.xml
  ext/legacycustomsearches/info.xml
  ext/message_admin/info.xml
  ext/oembed/info.xml
  ext/payflowpro/info.xml
  ext/recaptcha/info.xml
  ext/riverlea/info.xml
  ext/scheduled_communications/info.xml
  ext/search_kit/info.xml
  ext/search_kit_reports/info.xml
  ext/sequentialcreditnotes/info.xml
  ext/standaloneusers/info.xml
  ext/tellafriend/info.xml
  ext/user_dashboard/info.xml
Labels: master

#31924 CiviGrant - Remove multi-domain from grant_type option group
  CRM/Core/OptionGroup.php
  ext/civigrant/CRM/Grant/Upgrader.php
Labels: master

#31977 5.81.2 - Add notes. Set version.
  js/version.json
  release-notes.md
  release-notes/5.81.2.md
  sql/civicrm_generated.mysql
  sql/test_data_second_domain.mysql
  xml/version.xml
Labels: 5.81

#31975 Improve legibilty by using mysql alias rather than long variable name
  CRM/Dedupe/BAO/DedupeRuleGroup.php
Labels: master

#31974 Consolidate dupesByParam
  CRM/Contact/BAO/Contact.php
  CRM/Dedupe/Finder.php
  tests/phpunit/CRM/Dedupe/DedupeFinderTest.php
Labels: master

#31689 dev/core#5433 Add legacydedupefinder
  .gitignore
  CRM/Contact/BAO/Contact.php
  CRM/Dedupe/BAO/DedupeRuleGroup.php
  CRM/Dedupe/Finder.php
  CRM/Upgrade/Incremental/php/SixZero.php
  CRM/Utils/Hook.php
  bin/regen.sh
  ext/legacydedupefinder/CRM/Dedupe/BAO/QueryBuilder.php
  ext/legacydedupefinder/CRM/Dedupe/BAO/QueryBuilder/IndividualGeneral.php
  ext/legacydedupefinder/CRM/Dedupe/BAO/QueryBuilder/IndividualSupervised.php
  ext/legacydedupefinder/CRM/Dedupe/BAO/QueryBuilder/IndividualUnsupervised.php
  ext/legacydedupefinder/Civi/LegacyFinder/Finder.php
  ext/legacydedupefinder/LICENSE.txt
  ext/legacydedupefinder/README.md
  ext/legacydedupefinder/info.xml
  ext/legacydedupefinder/legacydedupefinder.civix.php
  ext/legacydedupefinder/legacydedupefinder.php
  ext/legacydedupefinder/phpunit.xml.dist
  ext/legacydedupefinder/tests/phpunit/Civi/LegacyFinderTest.php
  ext/legacydedupefinder/tests/phpunit/bootstrap.php
  tests/phpunit/CRM/Dedupe/DedupeFinderTest.php
  tests/phpunit/CRM/Dedupe/MergerTest.php
Labels: master, merge on pass

#31980 [REF] Return tempTable name from fillTable
  CRM/Dedupe/BAO/DedupeRuleGroup.php
  ext/legacydedupefinder/Civi/LegacyFinder/Finder.php
Labels: master

#31909 Move `from_email_address` options to new SiteEmailAddresses entity
  CRM/Admin/Form/Options.php
  CRM/Admin/Form/Setting/Smtp.php
  CRM/Admin/Page/Options.php
  CRM/Contact/Form/Task/PDFTrait.php
  CRM/Core/BAO/Domain.php
  CRM/Core/BAO/Email.php
  CRM/Core/BAO/OptionValue.php
  CRM/Core/BAO/SiteEmailAddress.php
  CRM/Core/BAO/UFGroup.php
  CRM/Core/DAO/SiteEmailAddress.php
  CRM/Core/OptionGroup.php
  CRM/Core/xml/Menu/Admin.xml
  CRM/Event/Form/SelfSvcTransfer.php
  CRM/Mailing/BAO/Mailing.php
  CRM/Mailing/xml/Menu/Mailing.xml
  CRM/PCP/BAO/PCP.php
  CRM/PCP/Form/Campaign.php
  CRM/Pledge/BAO/Pledge.php
  CRM/Upgrade/Incremental/php/SixZero.php
  CRM/Upgrade/Incremental/schema/6.0.alpha1.SiteEmailAddress.entityType.php
  CRM/Upgrade/Incremental/sql/6.0.alpha1.mysql.tpl
  CRM/Utils/API/HTMLInputCoder.php
  CRM/Utils/Check/Component/Env.php
  CRM/Utils/Mail.php
  Civi/API/Subscriber/SiteEmailLegacyOptionValueAdapter.php
  Civi/Api4/Generic/AbstractAction.php
  Civi/Api4/SiteEmailAddress.php
  ang/afform/afformSiteEmailAddress.aff.html
  ang/afform/afformSiteEmailAddress.aff.php
  ang/afform/afsearchSiteEmailAddresses.aff.html
  ang/afform/afsearchSiteEmailAddresses.aff.php
  api/v3/Mailing.php
  api/v3/SiteEmailAddress.php
  ext/eventcart/CRM/Event/Cart/Form/Checkout/Payment.php
  managed/administer/SavedSearch_Site_Email_Addresses.mgd.php
  schema/Core/SiteEmailAddress.entityType.php
  sql/civicrm_data/civicrm_option_group/from_email_address.sqldata.php
  sql/civicrm_data/civicrm_site_email_address.sqldata.php
  sql/civicrm_generated.mysql
  sql/test_data_second_domain.mysql
  templates/CRM/Admin/Form/Options.tpl
  templates/CRM/Admin/Form/ScheduleReminders.hlp
  templates/CRM/Admin/Form/Setting/Smtp.hlp
  templates/CRM/Admin/Page/ConfigTaskList.tpl
  templates/CRM/Admin/Page/Options.tpl
  templates/CRM/Contact/Form/Task/Help/Email/id-from_email.hlp
  templates/CRM/Mailing/MailingUI.hlp
  tests/phpunit/CRM/Contact/Form/Task/EmailTest.php
  tests/phpunit/CRM/Core/BAO/OptionValueTest.php
  tests/phpunit/CRM/Core/OptionGroupTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/api/v3/ContributionTest.php
  tests/phpunit/api/v3/OptionValueTest.php
  tests/phpunit/api/v4/Entity/OptionValueTest.php
  xml/templates/civicrm_data.tpl
  xml/templates/civicrm_navigation.tpl
Labels: master, merge on pass, has-test

#31416 Switch long & angular caches to use fast-array
  Civi/Core/Container.php
Labels: master

#31984 dev/core#5722 AdminUI - Fix Manage ACLs mode column
  ext/civicrm_admin_ui/managed/SavedSearch_Manage_ACLs.mgd.php
Labels: master

#31990 UtilsArray - Refactor out uses of deprecated CRM_Utils_Array::value
  CRM/Activity/BAO/Query.php
  CRM/Contact/BAO/Query.php
  CRM/Contact/Form/Merge.php
  CRM/Contact/Page/AJAX.php
  CRM/Core/Permission.php
  CRM/Event/Form/Registration/Register.php
  CRM/Export/BAO/ExportProcessor.php
  CRM/Utils/REST.php
  CRM/Utils/Rule.php
  CRM/Utils/VersionCheck.php
Labels: master

#31988 Update existing navigation labels to match new 'Site Email Address' l…
  CRM/Upgrade/Incremental/sql/6.0.beta1.mysql.tpl
Labels: merge on pass, 6.0

#31997 Add guard around CIVICRM_IFRAME constant
  ext/iframe/Civi/Iframe/Cosession.php
Labels: master

#31989 OptionGroup - Deprecate isDomainOptionGroup function
  CRM/Admin/Form/Options.php
  CRM/Campaign/Form/SurveyType.php
  CRM/Core/BAO/OptionValue.php
  CRM/Core/OptionGroup.php
  CRM/Core/OptionValue.php
  CRM/Utils/Rule.php
  Civi/Schema/EntityMetadataBase.php
  schema/Core/OptionValue.entityType.php
Labels: master

#31996 Decommission thresholdQuery, only call legacy hook from backward compat extension
  CRM/Dedupe/BAO/DedupeRuleGroup.php
  ext/legacydedupefinder/Civi/LegacyFinder/Finder.php
Labels: master

#31999 [REF] Api3 - Refactor out uses of deprecated CRM_Utils_Array::value.
  api/v3/Contact.php
  api/v3/Contribution/Transact.php
  api/v3/Domain.php
  api/v3/Generic.php
  api/v3/GroupContact.php
Labels: master

#32001 [REF] Bin - Refactor out uses of deprecated CRM_Utils_Array::value
  bin/ContributionProcessor.php
Labels: master

#32002 [REF] CRM/Activity - Refactor out uses of deprecated CRM_Utils_Array::value.
  CRM/Activity/Form/ActivityFilter.php
  CRM/Activity/Form/ActivityView.php
  CRM/Activity/Page/AJAX.php
Labels: master

#32003 [REF] Admin - Refactor out uses of deprecated CRM_Utils_Array::value
  CRM/Admin/Form/Options.php
  CRM/Admin/Form/PaymentProcessor.php
  CRM/Admin/Form/Setting/Localization.php
  CRM/Admin/Form/Setting/Mail.php
  CRM/Admin/Form/Setting/Smtp.php
  CRM/Admin/Form/SettingTrait.php
  CRM/Admin/Page/AJAX.php
Labels: master

#32025 [REF] ext/misc - Refactor out uses of deprecated CRM_Utils_Array::value
  ext/flexmailer/src/API/MailingPreview.php
  ext/legacydedupefinder/CRM/Dedupe/BAO/QueryBuilder/IndividualSupervised.php
  ext/legacydedupefinder/CRM/Dedupe/BAO/QueryBuilder/IndividualUnsupervised.php
  ext/tellafriend/CRM/Friend/Form.php
Labels: master

#32026 [REF] ext/legacycustomsearches - Refactor out uses of deprecated CRM_…
  ext/legacycustomsearches/CRM/Contact/BAO/SearchCustom.php
  ext/legacycustomsearches/CRM/Contact/Form/Search/Custom/ContribSYBNT.php
  ext/legacycustomsearches/CRM/Contact/Form/Search/Custom/ContributionAggregate.php
  ext/legacycustomsearches/CRM/Contact/Form/Search/Custom/DateAdded.php
  ext/legacycustomsearches/CRM/Contact/Form/Search/Custom/EventAggregate.php
  ext/legacycustomsearches/CRM/Contact/Form/Search/Custom/FullText/AbstractPartialQuery.php
  ext/legacycustomsearches/CRM/Contact/Form/Search/Custom/Group.php
  ext/legacycustomsearches/CRM/Contact/Form/Search/Custom/MultipleValues.php
  ext/legacycustomsearches/CRM/Contact/Form/Search/Custom/PostalMailing.php
  ext/legacycustomsearches/CRM/Contact/Form/Search/Custom/PriceSet.php
  ext/legacycustomsearches/CRM/Contact/Form/Search/Custom/Sample.php
  ext/legacycustomsearches/CRM/Contact/Form/Search/Custom/ZipCodeRange.php
Labels: master

#32004 [REF] Badge - Refactor out uses of deprecated CRM_Utils_Array::value.
  CRM/Badge/BAO/Badge.php
  CRM/Badge/Form/Layout.php
Labels: master

#32022 [REF] ext/ckeditor4 - Refactor out uses of deprecated CRM_Utils_Array::value
  ext/ckeditor4/CRM/Ckeditor4/Form/CKEditorConfig.php
Labels: master

#32013 [REF] CRM/Misc - Refactor out uses of deprecated CRM_Utils_Array::value.
  CRM/Dedupe/Merger.php
  CRM/Export/BAO/ExportProcessor.php
  CRM/Import/Parser.php
  CRM/Logging/Schema.php
  CRM/Upgrade/Page/Upgrade.php
Labels: master

#32021 [REF] ext/civigrant - Refactor out uses of deprecated CRM_Utils_Array::value
  ext/civigrant/CRM/Report/Form/Grant/Statistics.php
Labels: master

#32009 [REF] CRM/Contribute - Refactor out uses of deprecated CRM_Utils_Arra…
  CRM/Contribute/BAO/Contribution.php
  CRM/Contribute/BAO/Contribution/Utils.php
  CRM/Contribute/BAO/FinancialProcessor.php
  CRM/Contribute/BAO/Query.php
  CRM/Contribute/Form/AbstractEditPayment.php
  CRM/Contribute/Form/Contribution.php
  CRM/Contribute/Form/Contribution/ThankYou.php
  CRM/Contribute/Form/ContributionBase.php
  CRM/Contribute/Form/ContributionPage.php
  CRM/Contribute/Form/ContributionPage/Amount.php
  CRM/Contribute/Form/ContributionView.php
  CRM/Contribute/Form/Task/PDFLetter.php
  CRM/Contribute/Page/ContributionPage.php
Labels: master

#32005 [REF] Batch - Refactor out uses of deprecated CRM_Utils_Array::value.
  CRM/Batch/Form/Entry.php
Labels: master

#32019 [REF] CRM/Tag - Refactor out uses of deprecated CRM_Utils_Array::value
  CRM/Tag/Page/Tag.php
Labels: master

#32017 [REF] CRM/Report - Refactor out uses of deprecated CRM_Utils_Array::value
  CRM/Report/Form.php
  CRM/Report/Utils/Get.php
  CRM/Report/Utils/Report.php
Labels: master

#32016 [REF] CRM/Utils - Refactor out uses of deprecated CRM_Utils_Array::value
  CRM/Queue/Queue/SqlTrait.php
  CRM/Queue/Runner.php
  CRM/Utils/API/MatchOption.php
  CRM/Utils/Cache.php
  CRM/Utils/Cache/SqlGroup.php
  CRM/Utils/Chart.php
  CRM/Utils/File.php
  CRM/Utils/Mail.php
  CRM/Utils/Sort.php
Labels: master

#32000 Use local variable instead of protected property
  CRM/Dedupe/BAO/DedupeRuleGroup.php
Labels: master

#32020 [REF] CRM/SMS - Refactor out uses of deprecated CRM_Utils_Array::value
  CRM/SMS/BAO/SmsProvider.php
  CRM/SMS/Form/Upload.php
Labels: master, merge on pass

#32024 [REF] ext/eventcart - Refactor out uses of deprecated CRM_Utils_Array::value
  ext/eventcart/CRM/Event/Cart/Form/Checkout/Payment.php
Labels: master

#32018 [REF] CRM/Report/Form/* - Refactor out uses of deprecated CRM_Utils_Array::value
  CRM/Report/Form/Campaign/SurveyDetails.php
  CRM/Report/Form/Contact/Relationship.php
  CRM/Report/Form/Contribute/Lybunt.php
  CRM/Report/Form/Event/Income.php
  CRM/Report/Form/Mailing/Summary.php
Labels: master

#32014 [REF] CRM/Member - Refactor out uses of deprecated CRM_Utils_Array::v…
  CRM/Member/BAO/Query.php
  CRM/Member/Form.php
  CRM/Member/Form/Membership.php
  CRM/Member/Form/MembershipBlock.php
  CRM/Member/Form/MembershipStatus.php
  CRM/Member/Form/MembershipType.php
  CRM/Member/Form/Task/Batch.php
  CRM/Member/Form/Task/PDFLetter.php
Labels: master

#32006 [REF] Campaign - Refactor out uses of deprecated CRM_Utils_Array::value
  CRM/Campaign/Form/Task/Interview.php
  CRM/Campaign/Form/Task/Release.php
  CRM/Campaign/Page/Petition/ThankYou.php
Labels: master

#31995 Fix membership import to update without requiring membership_type_id
  CRM/Member/Import/Parser/Membership.php
  tests/phpunit/CRM/Member/Import/Parser/MembershipTest.php
Labels: has-test

#32007 [REF] Relationship - Refactor out uses of deprecated CRM_Utils_Array::value
  CRM/Contact/BAO/Relationship.php
  CRM/Contact/Form/Relationship.php
  CRM/Contact/Page/View/Relationship.php
Labels: master, merge ready

#32015 [REF] CRM/Price - Refactor out uses of deprecated CRM_Utils_Array::value
  CRM/PCP/Form/Contribute.php
  CRM/PCP/Form/Event.php
  CRM/Pledge/BAO/Pledge.php
  CRM/Price/BAO/LineItem.php
  CRM/Price/BAO/PriceField.php
  CRM/Price/BAO/PriceFieldValue.php
  CRM/Price/Form/Field.php
  CRM/Price/Form/Set.php
  CRM/Price/Page/Set.php
Labels: master

#32008 [REF] Contact - Refactor out uses of deprecated CRM_Utils_Array::value
  CRM/Contact/BAO/Query.php
  CRM/Contact/Form/Contact.php
  CRM/Contact/Form/DedupeRules.php
  CRM/Contact/Form/Search.php
  CRM/Contact/Form/Search/Builder.php
  CRM/Contact/Form/Search/Criteria.php
  CRM/Contact/Form/Task/EmailTrait.php
  CRM/Contact/Form/Task/PDFTrait.php
  CRM/Contact/Import/Form/MapField.php
  CRM/Contact/Page/AJAX.php
  CRM/Contact/Selector.php
Labels: master

#32030 Do legacy param setting in the legacy callers
  CRM/Dedupe/BAO/DedupeRuleGroup.php
  ext/legacydedupefinder/Civi/LegacyFinder/Finder.php
Labels: master

#32033 Upgrader tasks should not have ts
  CRM/Upgrade/Incremental/php/SixZero.php
Labels: merge on pass, 6.0

#32023 [REF] ext/payments - Refactor out uses of deprecated CRM_Utils_Array::value
  ext/elavon/CRM/Core/Payment/Elavon.php
  ext/ewaysingle/CRM/Core/Payment/eWAY.php
  ext/payflowpro/CRM/Core/Payment/PayflowPro.php
Labels: master

#32035 6.0
  CRM/Upgrade/Incremental/php/SixZero.php
  CRM/Upgrade/Incremental/sql/6.0.beta1.mysql.tpl
Labels: master

#32011 [REF] CRM/Custom - Refactor out uses of deprecated CRM_Utils_Array::value
  CRM/Custom/Form/Option.php
  CRM/Custom/Form/Preview.php
Labels: master

#32010 [REF] CRM/Core - Refactor out uses of deprecated CRM_Utils_Array::value
  CRM/Core/BAO/Mapping.php
  CRM/Core/BAO/Navigation.php
  CRM/Core/BAO/PdfFormat.php
  CRM/Core/BAO/RecurringEntity.php
  CRM/Core/BAO/UFMatch.php
  CRM/Core/Config/Runtime.php
  CRM/Core/Error.php
  CRM/Core/Form.php
  CRM/Core/Form/RecurringEntity.php
  CRM/Core/Form/ShortCode.php
  CRM/Core/Form/Task/Batch.php
  CRM/Core/Form/Task/PDFLetterCommon.php
  CRM/Core/JobManager.php
  CRM/Core/OptionValue.php
  CRM/Core/Page/AJAX.php
  CRM/Core/Page/Redirect.php
  CRM/Core/Payment/AuthorizeNet.php
  CRM/Core/Payment/FirstData.php
  CRM/Core/Payment/PayPalIPN.php
  CRM/Core/Payment/PayPalProIPN.php
  CRM/Core/Payment/Realex.php
  CRM/Core/Smarty/plugins/block.crmRegion.php
  CRM/Core/Smarty/plugins/function.crmAPI.php
  CRM/Core/Task.php
Labels: master

#32012 [REF] CRM/Event - Refactor out uses of deprecated CRM_Utils_Array::value
  CRM/Event/BAO/Event.php
  CRM/Event/Form/ManageEvent/Fee.php
  CRM/Event/Form/ManageEvent/Registration.php
  CRM/Event/Form/Participant.php
  CRM/Event/Form/ParticipantFeeSelection.php
  CRM/Event/Form/ParticipantView.php
  CRM/Event/Form/Registration.php
  CRM/Event/Form/Registration/AdditionalParticipant.php
  CRM/Event/Form/Registration/Register.php
  CRM/Event/Form/Registration/ThankYou.php
  CRM/Event/Page/EventInfo.php
Labels: master

#32042 Api4 - Fix typo in code
  Civi/Api4/Utils/FormattingUtil.php
Labels: merge on pass

#32039 Fix notice by switching to apiv4
  CRM/Dedupe/Merger.php
Labels: master, merge on pass

#32041 Standalone - Fix syntax error typo in conditional
  CRM/Utils/System/Standalone.php
Labels: 6.0

#32045 [REF] Remove unused variables
  CRM/Contact/Form/RelatedContact.php
Labels: master

#32037 Avoid fatal error editing CiviMail when current user missing email
  CRM/Mailing/Info.php
Labels: master

#31985 Installer - Use Riverlea's Minetta by default
  setup/plugins/init/DefaultExtensions.civi-setup.php
Labels: 6.0

#32047 [REF] CRM/Report - Refactor out uses of deprecated CRM_Utils_Array::value
  CRM/Report/Form.php
  CRM/Report/Form/Activity.php
  CRM/Report/Form/ActivitySummary.php
  CRM/Report/Form/Case/Detail.php
  CRM/Report/Form/Pledge/Detail.php
  CRM/Report/Form/Pledge/Summary.php
  CRM/Report/Page/Report.php
  CRM/Report/Utils/Get.php
  CRM/Report/Utils/Report.php
Labels: master

#32048 [REF] CRM/Event - Refactor out uses of deprecated CRM_Utils_Array::value
  CRM/Event/BAO/Event.php
  CRM/Event/Form/ParticipantFeeSelection.php
  CRM/Event/Form/Registration/Register.php
  CRM/Event/Page/EventInfo.php
Labels: master

#32044 [REF] Refactor redundant `isset()`s to use null coalescing operator (??)
  CRM/Core/BAO/CMSUser.php
  CRM/Event/Form/ManageEvent.php
  CRM/Event/Form/ManageEvent/TabHeader.php
  CRM/Utils/Mail.php
  CRM/Utils/SameSite.php
  CRM/Utils/System/WordPress.php
  Civi/Core/CiviEventDispatcher.php
  Civi/Pipe/PublicMethods.php
  ext/afform/mock/tests/phpunit/api/v4/Afform/AfformTest.php
  ext/flexmailer/src/FlexMailerTask.php
  ext/flexmailer/src/Listener/DefaultComposer.php
Labels: master

#32049 [REF] CRM/Activity - Refactor out uses of deprecated CRM_Utils_Array::value
  CRM/Activity/BAO/Query.php
  CRM/Activity/Selector/Activity.php
  CRM/Activity/Selector/Search.php
Labels: master

#32051 [REF] CRM/Case - Refactor out uses of deprecated CRM_Utils_Array::value
  CRM/Case/BAO/Case.php
  CRM/Case/XMLProcessor/Report.php
Labels: master

#32046 [REF] api/v3 - Refactor out uses of deprecated CRM_Utils_Array::value
  api/v3/Domain.php
  api/v3/utils.php
Labels: master

#32053 [REF] CRM/Misc - Refactor out uses of deprecated CRM_Utils_Array::value
  CRM/Contact/Selector.php
  CRM/Core/BAO/WordReplacement.php
  CRM/Core/Invoke.php
  CRM/Core/Page/AJAX/Location.php
  CRM/Import/Parser.php
  CRM/UF/Form/Field.php
  CRM/Utils/Migrate/ImportJSON.php
Labels: master

#32050 [REF] CiviContribute - Refactor out uses of deprecated CRM_Utils_Array::value
  CRM/Batch/Form/Entry.php
  CRM/Contribute/Form/Contribution.php
  CRM/Contribute/Form/ContributionPage/Amount.php
  CRM/Financial/Page/AJAX.php
Labels: master

#32057 Fix typo in release notes
  release-notes.md
Labels: merge on pass, 6.0

#31987 dev/core#5720 - Ensure default site email address is respected
  CRM/Contact/Form/Task/EmailTrait.php
  CRM/Contact/Form/Task/PDFTrait.php
  CRM/Contribute/Form/Task/Invoice.php
  CRM/Contribute/Form/Task/PDF.php
  CRM/Core/BAO/Email.php
Labels: 6.0

#32059 Standalone - Fix crash when viewing afform
  CRM/Utils/System/Standalone.php
  ext/afform/core/CRM/Afform/Page/AfformBase.php
Labels: 6.0

#32060 6.0 to master
  CRM/Contact/Form/Task/EmailTrait.php
  CRM/Contact/Form/Task/PDFTrait.php
  CRM/Contribute/Form/Task/Invoice.php
  CRM/Contribute/Form/Task/PDF.php
  CRM/Core/BAO/Email.php
  CRM/Utils/System/Standalone.php
  ext/afform/core/CRM/Afform/Page/AfformBase.php
  release-notes.md
Labels: master

#32061 Run regen
  sql/civicrm_generated.mysql
Labels: 6.0

#32063 6.0
  sql/civicrm_generated.mysql
Labels: master

#32058 CiviCase - Fix links and breadcrumbs when viewing case without cid in url
  CRM/Case/Form/CaseView.php
  CRM/Case/Page/Tab.php
Labels: master, merge ready

#31983 [REF] Use tokenProcessor to render display name
  CRM/Core/BAO/Address.php
Labels: master

#32062 dev/financial#230 - don't send email receipt when changing payment method on a contribution
  CRM/Financial/Form/PaymentEdit.php
  tests/phpunit/CRM/Financial/Form/PaymentEditTest.php
Labels: master, has-test

#31579 dev/core#5578 Adding Recurring tokens to Contribution/Membership toke…
  CRM/Contribute/Tokens.php
  CRM/Member/Tokens.php
  tests/phpunit/CRM/Contribute/ActionMapping/ByTypeTest.php
  tests/phpunit/CRM/Utils/TokenConsistencyTest.php
Labels: master, merge on pass

#32054 dev/core#5725 ScheduledCommunications - Increase length of fields used by SearchKit
  CRM/Upgrade/Incremental/php/SixZero.php
  schema/Core/ActionSchedule.entityType.php
Labels: merge on pass, 6.0

#31982 Deprecate legacy parameters to Address::format()
  CRM/Utils/Address.php
Labels: master, merge on pass

#32064 Ensure modelProps has contributionID
  CRM/Contribute/BAO/ContributionPage.php
Labels: master

#32052 [REF] Member/Pledge - Refactor out uses of deprecated CRM_Utils_Array::value
  CRM/Member/Form/Membership.php
  CRM/Member/Form/MembershipRenewal.php
  CRM/Pledge/BAO/PledgeBlock.php
  CRM/Pledge/Form/Pledge.php
Labels: master, merge on pass

#32040 Afform - Use entity-specific filter key, revert entity_id generic key
  CRM/Utils/Array.php
  ang/afform/afsearchTabNote.aff.html
  ang/afform/afsearchTabRel.aff.html
  ext/afform/admin/Civi/AfformAdmin/AfformAdminMeta.php
  ext/afform/admin/ang/afGuiEditor/afGuiEditor.component.js
  ext/afform/admin/ang/afGuiEditor/afGuiSearch.html
  ext/afform/core/Civi/Afform/Behavior/ContactAutofill.php
  ext/afform/core/Civi/Api4/Action/CustomGroup/GetAfforms.php
  ext/afform/core/afform.php
  ext/afform/core/managed/AfformPlacement.mgd.php
  ext/afform/core/templates/afform/customGroups/afsearchTab.tpl
  ext/afform/core/tests/phpunit/Civi/Afform/AfformContactSummaryTest.php
  ext/civicrm_admin_ui/ang/afformTabMember.aff.html
  ext/civicrm_admin_ui/ang/afsearchTabActivity.aff.html
  ext/civicrm_admin_ui/ang/afsearchTabMember.aff.html
  ext/civicrm_admin_ui/ang/afsearchTabParticipant.aff.html
  ext/civicrm_admin_ui/civicrm_admin_ui.php
  ext/civigrant/ang/afsearchTabGrant.aff.html
Labels: merge ready, 6.0

#32071 Merge 6.0 to master
  CRM/Utils/Array.php
  ang/afform/afsearchTabNote.aff.html
  ang/afform/afsearchTabRel.aff.html
  ext/afform/admin/Civi/AfformAdmin/AfformAdminMeta.php
  ext/afform/admin/ang/afGuiEditor/afGuiEditor.component.js
  ext/afform/admin/ang/afGuiEditor/afGuiSearch.html
  ext/afform/core/Civi/Afform/Behavior/ContactAutofill.php
  ext/afform/core/Civi/Api4/Action/CustomGroup/GetAfforms.php
  ext/afform/core/afform.php
  ext/afform/core/managed/AfformPlacement.mgd.php
  ext/afform/core/templates/afform/customGroups/afsearchTab.tpl
  ext/afform/core/tests/phpunit/Civi/Afform/AfformContactSummaryTest.php
  ext/civicrm_admin_ui/ang/afformTabMember.aff.html
  ext/civicrm_admin_ui/ang/afsearchTabActivity.aff.html
  ext/civicrm_admin_ui/ang/afsearchTabMember.aff.html
  ext/civicrm_admin_ui/ang/afsearchTabParticipant.aff.html
  ext/civicrm_admin_ui/civicrm_admin_ui.php
  ext/civigrant/ang/afsearchTabGrant.aff.html
Labels: master

#32076 Update tplanner/when for type hints
  composer.lock
Labels: master

#32072 Fix notices when rendering advanced search as contributions
  CRM/Contact/Form/Search.php
  CRM/Contribute/BAO/Query.php
  templates/CRM/Contribute/Page/ContributionTotals.tpl
Labels: master

#32027 dev/core#4923 CustomField - Don't index disabled fields
  CRM/Core/BAO/CustomField.php
  tests/phpunit/api/v4/Custom/CustomFieldAlterTest.php
Labels: master, merge ready, has-test

#32078 dev/core#5731 TabHeader - Fix adding count asynchronously
  templates/CRM/common/TabHeader.js
Labels: sig:regression, 6.0

#32080 dev/core#5731 TabHeader - Fix adding count asynchronously
  templates/CRM/common/TabHeader.js
Labels: sig:regression, 5.82

#32082 AdminUI - Fix custom field tabs appearing for wrong contact subtype
  ext/afform/core/Civi/Api4/Action/CustomGroup/GetAfforms.php
Labels: sig:regression, port

#32068 FormBuilder - Fix fatal crash with ContactLayout summary blocks
  ext/afform/core/afform.php
  ext/afform/core/templates/afform/InlineAfform.tpl
  templates/CRM/common/TabHeader.tpl
Labels: sig:unreleased-regression, 6.0

#32083 AdminUI - Fix custom field tabs appearing for wrong contact subtype
  ext/afform/core/Civi/Api4/Action/CustomGroup/GetAfforms.php
Labels: sig:regression, 6.0

#32031 Extract part of function that is shared between old path & new
  CRM/Dedupe/BAO/DedupeRuleGroup.php
Labels: master

#32086 6.0
  ext/afform/core/Civi/Api4/Action/CustomGroup/GetAfforms.php
  ext/afform/core/afform.php
  ext/afform/core/templates/afform/InlineAfform.tpl
  ext/riverlea/CHANGELOG.md
  ext/riverlea/core/css/_base.css
  ext/riverlea/core/css/_core.css
  ext/riverlea/core/css/components/_form.css
  ext/riverlea/core/css/contactSummary.css
  ext/riverlea/core/css/dashboard.css
  ext/riverlea/info.xml
  ext/riverlea/streams/hackneybrook/css/_dark.css
  templates/CRM/common/TabHeader.js
  templates/CRM/common/TabHeader.tpl
Labels: master

#32087 issue#5370: Relationship Update Screen Not Showing Existing Start/End Dates
  CRM/Contact/Form/Relationship.php
Labels: merge on pass, sig:regression, 6.0

#32089 issue#5370: Relationship Update Screen Not Showing Existing Start/End Dates
  CRM/Contact/Form/Relationship.php
Labels: sig:regression, 5.82

#32091 6.0
  CRM/Contact/Form/Relationship.php
Labels: master

#32043 [REF] - Simplify redundant calls to `empty()` function
  CRM/Admin/Form/WordReplacements.php
  CRM/Contact/BAO/ProximityQuery.php
  CRM/Contact/Form/Edit/Address.php
  CRM/Contribute/BAO/Contribution.php
  CRM/Contribute/BAO/ContributionRecur.php
  CRM/Core/BAO/Dashboard.php
  CRM/Core/BAO/UFGroup.php
  CRM/Core/Payment/ProcessorForm.php
  CRM/Dedupe/Merger.php
  CRM/Event/Form/ManageEvent/Fee.php
  CRM/Event/Form/Registration/Confirm.php
  CRM/Mailing/Controller/Send.php
  CRM/Mailing/Page/Report.php
  CRM/Price/BAO/PriceField.php
  CRM/Report/Form.php
  CRM/Report/Form/Contribute/Lybunt.php
  CRM/Utils/Schema.php
  api/class.api.php
  api/v3/Case.php
  api/v3/CaseType.php
  api/v3/Domain.php
  ext/flexmailer/src/Listener/OpenTracker.php
Labels: master

#32106 [REF] CRM/Misc - Use str_starts_with instead of strpos
  CRM/Contact/BAO/Group.php
  CRM/Dedupe/Merger.php
  CRM/Import/Parser.php
  CRM/Member/BAO/Membership.php
  CRM/Member/Form.php
Labels: master

#32105 [REF] CRM/Event - Use str_starts_with instead of strpos
  CRM/Event/Form/Registration.php
  CRM/Event/Form/SelfSvcTransfer.php
  CRM/Event/Tokens.php
Labels: master

#32107 dev/core#5556 Update the packaged version of league/csv to be 9.8.0 b…
  composer.json
  composer.lock
Labels: master, merge on pass, run-drupal-x

#32101 [REF] Ext/misc - Use str_starts_with instead of strpos
  ext/ckeditor4/CRM/Ckeditor4/Form/CKEditorConfig.php
  ext/financialacls/tests/phpunit/Civi/Financialacls/FinancialTypeTest.php
  ext/legacycustomsearches/CRM/Contact/Form/Search/Custom/MultipleValues.php
Labels: master

#31965 Standalone: more user friendly error when credentials are invalid
  ext/standaloneusers/CRM/Standaloneusers/Page/Login.php
  ext/standaloneusers/templates/CRM/Standaloneusers/Page/Login.tpl
Labels: master, merge ready, run-standalone

#32109 Upgrader - Fix upgrade error with i18n-enabled databases
  CRM/Upgrade/Incremental/php/FiveThirtyFour.php
Labels: 6.0

#32104 [REF] CRM/Financial - Use str_starts_with instead of strpos
  CRM/Batch/BAO/Batch.php
  CRM/Batch/Form/Entry.php
  CRM/Contribute/BAO/Contribution.php
  CRM/Contribute/Import/Form/MapField.php
  CRM/Financial/BAO/Order.php
Labels: master

#32093 [REF] Api3 - Use str_starts_with instead of strpos
  api/v3/Activity.php
  api/v3/Case.php
  api/v3/CustomField.php
  api/v3/Generic/Setvalue.php
  api/v3/utils.php
Labels: master

#32095 [REF] Civi/misc - Use str_starts_with instead of strpos
  Civi/API/Provider/MagicFunctionProvider.php
  Civi/API/SelectQuery.php
  Civi/Core/SqlTriggers.php
  Civi/Test/Api3TestTrait.php
Labels: master
