Repository civicrm/civicrm-core, pull requests merged in 2025-04, with the labels that each got.

#32547 SearchKit - Fix php warning when an entity has no fields
  ext/search_kit/Civi/Search/Admin.php
Labels: master

#32546 [NFC] Add Unit test of changing FT in quick config changes Line item FT as well
  tests/phpunit/CRM/Contribute/Form/ContributionTest.php
Labels: master

#32548 RiverLea regression: FormBuilder drag/drop grab region had shrunk, this returns it to original size.
  ext/riverlea/core/org.civicrm.afform_admin-ang/afGuiEditor.css
Labels: 6.1

#32549 Update regions in Denmark
  CRM/Upgrade/Incremental/sql/6.2.alpha1.mysql.tpl
  xml/templates/civicrm_state_province.tpl
Labels: master

#32555 Update contributor-key.yml
  contributor-key.yml
Labels: master

#32518 Fix orphaned form label for afform radio buttons
  ext/afform/core/ang/af/fields/Radio.html
Labels: master, sig:accessibility

#32557 avoid errors with canary table when using READ-COMMITTED
  Civi/Core/InstallationCanary.php
Labels: master

#32560 Search UI: Open links in same tab
  ext/civicrm_search_ui/managed/SavedSearch_Contact_Search.mgd.php
Labels: master

#32561 Api - Fix 'required' setting of legacyArrayToField
  Civi/Api4/Service/Spec/Provider/DAOFieldsCallbackAdapterSpecProvider.php
Labels: master

#32568 EFv2 - Implement $entity->getReferenceCounts
  CRM/Core/DAO.php
  CRM/Core/Reference/Dynamic.php
  Civi/Api4/Utils/CoreUtil.php
  Civi/Schema/EntityProvider.php
  Civi/Schema/EntityStorageInterface.php
  Civi/Schema/SqlEntityStorage.php
  tests/phpunit/api/v4/Custom/CustomContactRefTest.php
Labels: master, merge on pass, has-test

#32569 SearchKit: fix inline editing with ACL bypass enabled
  ext/search_kit/Civi/Api4/Action/SearchDisplay/AbstractRunAction.php
  ext/search_kit/Civi/Api4/Action/SearchDisplay/InlineEdit.php
Labels: 6.1

#32570 [REF] CiviCase - Move component quasi-hook to real hook
  CRM/Case/Info.php
  CRM/Core/Component/Info.php
  CRM/Core/DAO.php
  Civi/Schema/SqlEntityStorage.php
  ext/civi_case/civi_case.php
Labels: master

#32507 RiverLea 1.4.3: emphasis colours rework, changed & new variables
  ext/riverlea/CHANGELOG.md
  ext/riverlea/core/css/_base.css
  ext/riverlea/core/css/_bootstrap.css
  ext/riverlea/core/css/_core.css
  ext/riverlea/core/css/_fixes.css
  ext/riverlea/core/css/_variables.css
  ext/riverlea/core/css/admin.css
  ext/riverlea/core/css/api4-explorer.css
  ext/riverlea/core/css/components/_accordion.css
  ext/riverlea/core/css/components/_alerts.css
  ext/riverlea/core/css/components/_components.css
  ext/riverlea/core/css/components/_form.css
  ext/riverlea/core/css/components/_icons.css
  ext/riverlea/core/css/components/_tables.css
  ext/riverlea/info.xml
  ext/riverlea/streams/empty/css/_dark.css
  ext/riverlea/streams/empty/css/_variables.css
  ext/riverlea/streams/hackneybrook/css/_dark.css
  ext/riverlea/streams/hackneybrook/css/_variables.css
  ext/riverlea/streams/minetta/css/_dark.css
  ext/riverlea/streams/thames/css/_dark.css
  ext/riverlea/streams/thames/css/_variables.css
  ext/riverlea/streams/walbrook/css/_dark.css
  ext/riverlea/streams/walbrook/css/_variables.css
Labels: master, merge ready

#32571 6.2
  ext/riverlea/core/org.civicrm.afform_admin-ang/afGuiEditor.css
  ext/riverlea/core/org.civicrm.search_kit-css/crmSearchAdmin.css
  ext/search_kit/Civi/Api4/Action/SearchDisplay/AbstractRunAction.php
  ext/search_kit/Civi/Api4/Action/SearchDisplay/InlineEdit.php
  release-notes.md
  release-notes/6.1.0.md
Labels: 6.2

#32556 dev/core#5818 Fix for ugliness of Radio buttons in form builder
  ext/afform/core/ang/af/fields/Radio.html
Labels: master, merge on pass

#32576 [NFC] stricter linting for chart kit
  ext/chart_kit/ang/crmChartKit/chartKitAdminCanvas.html
  ext/chart_kit/ang/crmChartKit/chartKitAdminColumns.html
  ext/chart_kit/ang/crmChartKit/chartKitAdminLegend.html
  ext/chart_kit/ang/crmChartKit/chartKitCanvas.html
  ext/chart_kit/ang/crmChartKit/chartKitColumnConfig.service.js
  ext/chart_kit/ang/crmChartKit/chartKitReduceTypes.service.js
  ext/chart_kit/ang/crmChartKit/chartTypes/chartKitComposite.service.js
  ext/chart_kit/ang/crmChartKit/chartTypes/chartKitCompositeAdmin.html
  ext/chart_kit/ang/crmChartKit/chartTypes/chartKitPie.service.js
  ext/chart_kit/ang/crmChartKit/chartTypes/chartKitPieAdmin.html
  ext/chart_kit/ang/crmChartKit/chartTypes/chartKitRow.service.js
  ext/chart_kit/ang/crmChartKit/chartTypes/chartKitRowAdmin.html
  ext/chart_kit/ang/crmChartKit/chartTypes/chartKitSeries.service.js
  ext/chart_kit/ang/crmChartKit/chartTypes/chartKitStack.service.js
  ext/chart_kit/ang/crmChartKit/chartTypes/chartKitStackAdmin.html
  ext/chart_kit/ang/crmChartKit/crmSearchDisplayChartKit.component.js
  ext/chart_kit/ang/crmChartKit/searchAdminDisplayChartKit.component.js
  ext/chart_kit/ang/crmChartKit/searchAdminDisplayChartKit.html
Labels: master

#32562 Tags - Fix tagging files
  CRM/Core/BAO/File.php
Labels: master

#32577 6.2
  ext/riverlea/core/org.civicrm.afform_admin-ang/afGuiEditor.css
  ext/riverlea/core/org.civicrm.search_kit-css/crmSearchAdmin.css
  ext/search_kit/Civi/Api4/Action/SearchDisplay/AbstractRunAction.php
  ext/search_kit/Civi/Api4/Action/SearchDisplay/InlineEdit.php
  release-notes.md
  release-notes/6.1.0.md
Labels: master, merge on pass

#32575 Allow JobLog date to be used as formbuilder filter
  schema/Core/JobLog.entityType.php
Labels: master

#32540 Fix Custom import to use civiimport
  CRM/Custom/Import/Form/MapField.php
  CRM/Custom/Import/Parser/Api.php
  CRM/Event/Import/Form/MapField.php
  CRM/Event/Import/Parser/Participant.php
  CRM/Import/Form/MapField.php
  CRM/Import/Parser.php
  CRM/Member/Import/Form/MapField.php
  ext/civiimport/CRM/CiviImport/Form/MapField.php
  ext/civiimport/civiimport.php
  tests/phpunit/CRM/Contribute/Import/Parser/ContributionTest.php
  tests/phpunit/CRM/Custom/Import/Parser/ApiTest.php
  tests/phpunit/CRM/Event/Import/Parser/ParticipantTest.php
  tests/phpunit/CRM/Member/Import/Parser/MembershipTest.php
  tests/phpunit/CRMTraits/Import/ParserTrait.php
Labels: master, merge on pass

#32578 [REF] Chartkit minor code improvements
  ext/chart_kit/ang/crmChartKit/chartTypes/chartKitPie.service.js
  ext/chart_kit/ang/crmChartKit/chartTypes/chartKitSeries.service.js
  ext/chart_kit/ang/crmChartKit/crmSearchDisplayChartKit.component.js
  ext/chart_kit/ang/crmChartKit/searchAdminDisplayChartKit.component.js
Labels: master

#32558 Remove entity_field_prefix
  CRM/Activity/Import/Parser/Activity.php
  CRM/Contribute/Import/Parser/Contribution.php
  CRM/Event/Import/Parser/Participant.php
  CRM/Import/Parser.php
  CRM/Member/Import/Parser/Membership.php
  ext/civiimport/ang/crmCiviimport.js
Labels: master, merge on pass

#32565 DAO - Remove unused debugging function
  CRM/Core/DAO.php
Labels: master

#32581 Fix rejection of activity import if id not mapped
  CRM/Activity/Import/Form/MapField.php
Labels: 6.2

#32580 Fix rejection of activity import if id not mapped
  CRM/Activity/Import/Form/MapField.php
Labels: 6.1

#32516 dev/core#5812 Fixes missing and duplicate recipients from mailings
  CRM/Mailing/BAO/MailingRecipients.php
Labels: master

#32566 dev/core#5824 Misleading System Status message when CIVICRM_MAIL_LOG_AND_SEND is set
  CRM/Utils/Check/Component/Env.php
Labels: master

#32582 [REF] Cleanup uses of deprecated CRM_Utils_Array::value
  CRM/Activity/Form/Activity.php
  CRM/Core/BAO/Tag.php
  CRM/Event/Form/Registration/Register.php
  CRM/Event/Form/Task/Batch.php
  CRM/Queue/Runner.php
  CRM/Report/Form.php
  CRM/Report/Form/Campaign/SurveyDetails.php
Labels: master

#32402 (dev/core#5594) Upgrade - Don't drop the current user ID after upgrade
  CRM/Core/Session.php
  CRM/Upgrade/Form.php
Labels: 6.2

#32585 6.2
  CRM/Activity/Import/Form/MapField.php
  CRM/Core/Session.php
  CRM/Upgrade/Form.php
Labels: master, merge on pass

#32574 Make it easier to extract totals from LineItems client-side
  templates/CRM/Price/Page/LineItem.tpl
  tests/phpunit/CRM/Contribute/Form/ContributionViewTest.php
Labels: master

#32579 Pass info in modelProps
  CRM/Contribute/Form/AdditionalInfo.php
Labels: master

#32593 dev#issues/5831 : EntityReference Custom field in export causes DB error : data too long
  CRM/Export/BAO/ExportProcessor.php
Labels: master, merge on pass

#32592 dev/core#5830 CaseType api (v4) returns empty definition
  Civi/Api4/Utils/FormattingUtil.php
  tests/phpunit/api/v4/Entity/CaseTest.php
Labels: master, merge on pass

#32586 ChartKit - fix priority of text color setting
  ext/chart_kit/ang/crmChartKit/crmSearchDisplayChartKit.component.js
Labels: master

#32588 ChartKit - fallback if no format settings are set
  ext/chart_kit/ang/crmChartKit/crmSearchDisplayChartKit.component.js
Labels: master

#32597 (NFC) SchemaTrait - Flag as deprecated
  CRM/Extension/Upgrader/SchemaTrait.php
Labels: master, merge on pass

#32383 Afform: Confirmation message
  ext/afform/admin/Civi/AfformAdmin/AfformAdminMeta.php
  ext/afform/admin/ang/afGuiEditor/afGuiEditor.component.js
  ext/afform/admin/ang/afGuiEditor/config-form.html
  ext/afform/core/Civi/Api4/Afform.php
  ext/afform/core/afform.php
  ext/afform/core/ang/af/afForm.component.js
  ext/afform/core/managed/AfformConfirmationType.mgd.php
Labels: master, merge ready

#32605 CustomGroup - Allow `cg_extend_objects` to override hardcoded list of entities
  CRM/Core/BAO/CustomGroup.php
Labels: master, merge ready

#32036 Offline Membership creation and renewal does not attach Invoice to emails
  CRM/Core/BAO/MessageTemplate.php
Labels: master

#32606 Alternate to 32595 - fix for legacydedupefinder
  ext/legacydedupefinder/Civi/LegacyFinder/Finder.php
Labels: 6.2

#32595 Unhide legacydedupefinder so that it can be disabled
  ext/legacydedupefinder/info.xml
Labels: master

#32608 RiverLea: fixes inline checkbox regression
  ext/riverlea/core/css/components/_front.css
Labels: 6.2

#32604 RiverLea: fixes inline checkbox regression
  ext/riverlea/core/css/components/_front.css
Labels: 6.1

#32603 Ext - Move new upgrade functions to SchemaHelper
  CRM/Extension/Upgrader/SchemaTrait.php
  mixin/lib/civimix-schema@5/src/SchemaHelper.php
Labels: 6.2

#32611 backport 32606
  ext/legacydedupefinder/Civi/LegacyFinder/Finder.php
Labels: merge on pass, 6.1

#32612 Migrate HookInterface references from class_alias
  Civi/Test/HookInterface.php
  Civi/Test/Legacy/CiviTestListener.php
  ext/civi_contribute/tests/phpunit/Civi/Entity/ContributionRecurTest.php
  ext/civi_report/tests/phpunit/ReportInstanceTest.php
  ext/civi_report/tests/phpunit/ReportTest.php
  ext/civiimport/tests/phpunit/CiviApiImportTest.php
  ext/contributioncancelactions/tests/phpunit/CancelTest.php
  ext/elavon/tests/phpunit/CRM/Core/Payment/ElavonTest.php
  ext/ewaysingle/tests/phpunit/CRM/Core/Payment/EwayTest.php
  ext/financialacls/tests/phpunit/Civi/Financialacls/BaseTestClass.php
  ext/flexmailer/tests/phpunit/Civi/FlexMailer/ClickTrackerTest.php
  ext/legacycustomsearches/tests/phpunit/CRM/Core/InnoDBIndexerTest.php
  ext/legacycustomsearches/tests/phpunit/CRM/Utils/QueryFormatterTest.php
  ext/legacycustomsearches/tests/phpunit/Civi/Searches/FullTextTest.php
  ext/legacycustomsearches/tests/phpunit/Civi/Searches/GroupTest.php
  ext/legacycustomsearches/tests/phpunit/Civi/Searches/PriceSetTest.php
  ext/legacycustomsearches/tests/phpunit/Civi/Searches/SampleTest.php
  ext/legacydedupefinder/tests/phpunit/Civi/LegacyFinderTest.php
  ext/oauth-client/tests/phpunit/CRM/OAuth/MailSetupTest.php
  ext/oauth-client/tests/phpunit/Civi/OAuth/AuthCodeFlowTest.php
  ext/oauth-client/tests/phpunit/Civi/OAuth/CiviGenericProviderTest.php
  ext/oauth-client/tests/phpunit/api/v4/OAuthClientGrantTest.php
  ext/oauth-client/tests/phpunit/api/v4/OAuthClientTest.php
  ext/oauth-client/tests/phpunit/api/v4/OAuthContactTokenTest.php
  ext/oauth-client/tests/phpunit/api/v4/OAuthProviderTest.php
  ext/oauth-client/tests/phpunit/api/v4/OAuthSessionTokenTest.php
  ext/oauth-client/tests/phpunit/api/v4/OAuthSysTokenTest.php
  ext/oembed/tests/phpunit/CRM/Oembed/Page/OembedDiscoveryTest.php
  ext/oembed/tests/phpunit/CRM/Oembed/Page/OembedTest.php
  ext/payflowpro/tests/phpunit/CRM/Core/Payment/PayflowProTest.php
  ext/scheduled_communications/tests/phpunit/Civi/ScheduledCommunications/SendTest.php
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/ManagedSearchTest.php
  ext/sequentialcreditnotes/tests/phpunit/SequentialcreditnotesTest.php
  tests/events/civi_region_render.evch.php
  tests/events/hook_civicrm_alterMailParams.evch.php
  tests/events/hook_civicrm_config.evch.php
  tests/events/hook_civicrm_links.evch.php
  tests/phpunit/api/v4/Action/AutocompleteTest.php
  tests/phpunit/api/v4/Action/BasicActionsTest.php
  tests/phpunit/api/v4/Action/GetActionsTest.php
  tests/phpunit/api/v4/Entity/ConformanceTest.php
  tests/phpunit/api/v4/Entity/ManagedEntityTest.php
Labels: master

#32613 SchemaHelper - Tweak compatibility and docblocks
  mixin/lib/civimix-schema@5/src/SchemaHelper.php
  mixin/lib/civimix-schema@5/src/SchemaHelperInterface.php
Labels: 6.2

#32618 6.2
  mixin/lib/civimix-schema@5/src/SchemaHelper.php
  mixin/lib/civimix-schema@5/src/SchemaHelperInterface.php
Labels: master

#32621 Notice fix
  templates/CRM/Contribute/Page/ContributionRecurSelector.tpl
Labels: master, merge on pass

#32617 Release Notes - Maintenance Mode is not Standalone specific
  release-notes/6.1.0.md
Labels: 6.1

#32622 release notes - Maintenance Mode is not Standalone specific
  release-notes/6.1.0.md
Labels: merge on pass, 6.2

#32591 (dev/core#5700) Extensions - "Add New" is supposed to install new extensions
  CRM/Admin/Form/Extensions.php
  CRM/Extension/Manager.php
  CRM/Extension/QueueDownloader.php
  CRM/Extension/QueueTasks.php
  CRM/Utils/File.php
  tests/phpunit/CRM/Utils/FileTest.php
Labels: 6.2

#32619 Fix 6.1 regression, type error on invalid fields
  CRM/Contribute/Import/Parser/Contribution.php
  CRM/Import/Parser.php
  tests/phpunit/CRM/Contribute/Import/Parser/ContributionTest.php
Labels: 6.1

#32620 Add test cover for 6.1 regression, type error on invalid fields
  tests/phpunit/CRM/Contribute/Import/Parser/ContributionTest.php
Labels: 6.2

#32623 (dev/core#5700) Extensions - "Add New" is supposed to install new extensions
  CRM/Admin/Form/Extensions.php
  CRM/Extension/Manager.php
  CRM/Extension/QueueDownloader.php
  CRM/Extension/QueueTasks.php
  CRM/Utils/File.php
  tests/phpunit/CRM/Utils/FileTest.php
Labels: 6.1

#32624 6.1.1 - Add notes. Set version.
  deleted-files-list.json
  js/version.json
  release-notes.md
  release-notes/6.1.1.md
  sql/civicrm_generated.mysql
  sql/test_data_second_domain.mysql
  xml/version.xml
Labels: 6.1

#32625 Standalone: minor tweak to some strings
  ext/standaloneusers/ang/crmChangePassword/crmChangePassword.html
  ext/standaloneusers/ang/crmResetPassword.js
Labels: 6.2

#32626 [NFC] 6.2 release notes first pass
  contributor-key.yml
  release-notes/6.2.0.md
Labels: 6.2

#32628 6.2 to master
  CRM/Admin/Form/Extensions.php
  CRM/Extension/Manager.php
  CRM/Extension/QueueDownloader.php
  CRM/Extension/QueueTasks.php
  CRM/Utils/File.php
  contributor-key.yml
  ext/standaloneusers/ang/crmChangePassword/crmChangePassword.html
  ext/standaloneusers/ang/crmResetPassword.js
  release-notes/6.1.0.md
  release-notes/6.2.0.md
  tests/phpunit/CRM/Contribute/Import/Parser/ContributionTest.php
  tests/phpunit/CRM/Utils/FileTest.php
Labels: master

#32629 dev/core#5846 Re-fix isTableBigger
  ext/legacydedupefinder/Civi/LegacyFinder/Finder.php
  ext/legacydedupefinder/tests/phpunit/Civi/LegacyFinderTest.php
Labels: 6.2

#32630 (dev/core#5846) Legacy Dedupe - Refix `isTableBigger()`
  ext/legacydedupefinder/Civi/LegacyFinder/Finder.php
  ext/legacydedupefinder/tests/phpunit/Civi/LegacyFinderTest.php
Labels: 6.1

#32631 6.2
  ext/legacydedupefinder/Civi/LegacyFinder/Finder.php
  ext/legacydedupefinder/tests/phpunit/Civi/LegacyFinderTest.php
Labels: master

#32634 Additional dedupe test + early return for when parameters are not pas…
  CRM/Dedupe/BAO/DedupeRuleGroup.php
  tests/phpunit/CRM/Dedupe/DedupeFinderTest.php
Labels: 6.1

#32601 don't emit error on wordpress if using symlinked web dir
  CRM/Utils/System/WordPress.php
Labels: master, merge ready

#32636 6.2
  CRM/Dedupe/BAO/DedupeRuleGroup.php
  tests/phpunit/CRM/Dedupe/DedupeFinderTest.php
Labels: master

#32637 6.1.2 - Add notes. Set version.
  js/version.json
  release-notes.md
  release-notes/6.1.2.md
  sql/civicrm_generated.mysql
  sql/test_data_second_domain.mysql
  xml/version.xml
Labels: 6.1

#32638 Upgrader - Ensure rebuildMenuAndCaches() runs with fresh container
  CRM/Upgrade/Form.php
Labels: 6.1

#32635 ChartKit - fix secondary grouping columns missing from legend text
  ext/chart_kit/ang/crmChartKit/chartTypes/chartKitPie.service.js
Labels: master

#32646 UserDashboard.tpl typo
  templates/CRM/Member/Page/UserDashboard.tpl
Labels: master

#26804 Record fee amount financial transaction line items
  CRM/Financial/BAO/Payment.php
Labels: master

#32649 iframe - Fix PHP error about `print` function
  ext/iframe/Civi/Iframe/Iframe.php
  ext/iframe/Civi/Iframe/Router.php
  ext/iframe/phpunit.xml.dist
  ext/iframe/tests/phpunit/CRM/Iframe/IframeTest.php
  ext/iframe/tests/phpunit/bootstrap.php
Labels: merge on pass, 6.2

#32651 (NFC) IframeTest - Fix test-failure on wp
  ext/iframe/tests/phpunit/CRM/Iframe/IframeTest.php
Labels: 6.2

#32650 6.2
  ext/iframe/Civi/Iframe/Iframe.php
  ext/iframe/Civi/Iframe/Router.php
  ext/iframe/phpunit.xml.dist
  ext/iframe/tests/phpunit/CRM/Iframe/IframeTest.php
  ext/iframe/tests/phpunit/bootstrap.php
Labels: master

#32632 update tcpdf
  composer.lock
Labels: 6.2

#32639 Merging tags update the name instead of the label
  CRM/Tag/Form/Merge.php
  templates/CRM/Tag/Form/Merge.tpl
Labels: master

#32652 6.2
  composer.lock
Labels: master

#32654 ensure api4 dedupe uses numeric phone
  Civi/Api4/Action/Contact/GetDuplicates.php
  tests/phpunit/api/v4/Action/ContactDuplicatesTest.php
Labels: master

#32627 dev/core#5845 setup: move Sample Data lower, tweak the wording
  setup/plugins/blocks/header.tpl.php
  setup/plugins/blocks/sample-data.civi-setup.php
  setup/plugins/blocks/sample-data.tpl.php
  setup/plugins/blocks/sync-users.tpl.php
  setup/res/template.css
Labels: master, merge ready, sig:user interfacing improvement

#32657 Switch 'smtp' form to use metadata rather than legacy method
  CRM/Admin/Form/Setting/Smtp.php
  settings/Mailing.setting.php
  templates/CRM/Admin/Form/Setting/SettingField.tpl
  templates/CRM/Admin/Form/Setting/Smtp.hlp
  templates/CRM/Admin/Form/Setting/Smtp.tpl
Labels: master

#32659 fix viewing PCP info page
  CRM/PCP/BAO/PCP.php
Labels: merge on pass, 6.2

#32655 Installer - Tweak prose for "Sample Data" and "Users"
  CRM/Import/Parser.php
  setup/plugins/blocks/sample-data.tpl.php
  setup/plugins/blocks/sync-users.tpl.php
  setup/res/template.css
Labels: master, merge ready

#32656 Api4 - More efficient ACL clause handling
  Civi/Api4/Query/Api4SelectQuery.php
  tests/phpunit/api/v4/Action/HookSelectWhereTest.php
Labels: master, has-test

#32610 infra/ops#1014 Move localized default settings into civicrm-core
  .gitignore
  Civi/Core/Container.php
  settings/l10n/bg_BG/settings.default.json
  settings/l10n/ca_ES/settings.default.json
  settings/l10n/de_DE/settings.default.json
  settings/l10n/el_GR/settings.default.json
  settings/l10n/en_AU/settings.default.json
  settings/l10n/en_GB/settings.default.json
  settings/l10n/es_ES/settings.default.json
  settings/l10n/fr_CA/settings.default.json
  settings/l10n/fr_FR/settings.default.json
  settings/l10n/hu_HU/settings.default.json
  settings/l10n/it_IT/settings.default.json
  settings/l10n/ja_JP/settings.default.json
  settings/l10n/nl_NL/settings.default.json
  settings/l10n/pl_PL/settings.default.json
  settings/l10n/ro_RO/settings.default.json
  setup/plugins/blocks/l10n.tpl.php
  setup/plugins/installDatabase/Localization.civi-setup.php
  setup/plugins/installFiles/l10nDownload.civi-setup.php
  setup/src/Setup/Event/CheckRequirementsEvent.php
Labels: master, sig:user interfacing improvement, run-distmaker

#32661 (Un)Installer - Fix testing issue on D7
  setup/plugins/uninstallDatabase/CleanupDrupalSession.civi-setup.php
Labels: 6.2

#32660 6.2
  CRM/PCP/BAO/PCP.php
  setup/plugins/uninstallDatabase/CleanupDrupalSession.civi-setup.php
Labels: master

#32642 Add support to ISO8601 time formatting supported for imports
  CRM/Utils/Date.php
  tests/phpunit/CRM/Utils/DateTest.php
Labels: master

#32614 Standalone - avoid redirect loops in permissionDenied
  CRM/Utils/System/Standalone.php
Labels: master, merge ready, run-standalone

#32653 When merging tags the form field is added with the wrong number of params to add()
  CRM/Tag/Form/Merge.php
Labels: master

#32662 [REF] CiviImport - Pass full values array to import function
  CRM/Activity/Import/Parser/Activity.php
  CRM/Contact/Import/Parser/Contact.php
  CRM/Contribute/Import/Parser/Contribution.php
  CRM/Custom/Import/Parser/Api.php
  CRM/Event/Import/Parser/Participant.php
  CRM/Import/Parser.php
  CRM/Member/Import/Parser/Membership.php
Labels: master

#32658 Use non-deprecated smarty5 syntax for join/implode modifier [requires civicrm/civicrm-packages#423 to keep smarty2 support and civicrm-packages#424 for smarty4]
  templates/CRM/Case/Page/CustomDataView.tpl
  templates/CRM/Contact/Form/Merge.tpl
  templates/CRM/Contact/Page/View/CustomDataFieldView.tpl
  templates/CRM/Custom/Page/CustomDataView.tpl
  templates/CRM/Tag/Form/Merge.tpl
Labels: master

#32664 dev/core#5843 Move full space trim to DataSource on write
  CRM/Import/DataSource/CSV.php
  Civi/Import/DataSource/DataSourceTrait.php
  ext/civiimport/Civi/Import/DataSource/Spreadsheet.php
  tests/phpunit/CRM/Contribute/Import/Parser/ContributionTest.php
  tests/phpunit/CRM/Contribute/Import/Parser/data/contributions_need_trim.csv
Labels: master, merge on pass

#32663 SK: Rewrite tokens in 'Link' metadata correctly
  ext/search_kit/Civi/Api4/Action/SearchDisplay/AbstractRunAction.php
Labels: master
