Repository civicrm/civicrm-core, pull requests merged in 2025-01, with the labels that each got.

#31661 Update tecnickcom/tcpdf (6.7.7 => 6.8.0)
  composer.json
  composer.lock
Labels: merge on pass, 5.81

#31678 5.81 to master
  composer.json
  composer.lock
Labels: master

#31625 eventcart: on EventInfo, show checkout/viewcart buttons
  ext/eventcart/CRM/Event/Cart/PageCallback.php
  ext/eventcart/templates/CRM/Event/Cart/eventinfo.tpl
Labels: master

#31586 Support csv_importer import jobs in searchkit import report
  ext/civiimport/civiimport.php
Labels: master

#31682 Fix default property value: CRM_Contact_Form_Merge->criteria
  CRM/Contact/Form/Merge.php
Labels: master

#31668 Afform - Add maxlength validation and character count
  ext/afform/admin/ang/afGuiEditor/elements/afGuiField-menu.html
  ext/afform/core/Civi/Api4/Action/Afform/Submit.php
  ext/afform/core/afform.php
  ext/afform/core/ang/af/afCharacterCount.component.js
  ext/afform/core/ang/af/afCharacterCount.html
  ext/afform/core/ang/af/fields/Text.html
  ext/afform/core/ang/af/fields/TextArea.html
  ext/afform/mock/tests/phpunit/api/v4/Afform/AfformContactUsageTest.php
Labels: master

#31672 CommunicationPreferences form code cleanup
  CRM/Contact/Form/Edit/CommunicationPreferences.php
  CRM/Core/SelectValues.php
  templates/CRM/Contact/Form/Contact.hlp
  templates/CRM/Contact/Form/Edit/CommunicationPreferences.tpl
  templates/CRM/Contact/Form/Inline/CommunicationPreferences.tpl
Labels: master

#31684 Cast null description to string
  ext/legacycustomsearches/CRM/Contact/Page/CustomSearch.php
Labels: master

#31683 [REF][PHP8.2] Declare missing properties on CRM_PCP_Form_PCPAccount
  CRM/PCP/Form/PCPAccount.php
Labels: master

#31676 Update searchTest to not call form class in legacy way
  CRM/Batch/Form/Entry.php
  tests/phpunit/CRM/Contribute/Form/SearchTest.php
Labels: master, merge on pass

#31568 REF: Simplify URL params for relationship form and don't require 'rtype' when updating a relationship
  CRM/Contact/Form/Relationship.php
Labels: master

#31572 dev/core#5629 - case activity send copy has blank details on the email activity filed on the case
  CRM/Case/BAO/Case.php
Labels: master

#31687 Move flushing of activityType static to OptionValue:create
  CRM/Core/PseudoConstant.php
  tests/phpunit/CiviTest/CiviCaseTestCase.php
  tests/phpunit/api/v3/ActivityTypeTest.php
  tests/phpunit/api/v3/MembershipPaymentTest.php
  tests/phpunit/api/v3/MembershipTest.php
Labels: master

#31686 Standardise setUp for CiviCase shared code
  CRM/Case/XMLProcessor/Process.php
  tests/fixtures/case_relationships.json
  tests/fixtures/contacts.json
  tests/phpunit/CRM/Activity/Page/AJAXTest.php
  tests/phpunit/CRM/Case/BAO/CaseTest.php
  tests/phpunit/CRM/Case/Form/CaseViewTest.php
  tests/phpunit/CRM/Case/XMLProcessor/ProcessTest.php
  tests/phpunit/CRM/Case/XMLProcessorTest.php
  tests/phpunit/CRM/Contact/BAO/ContactType/ContactTypeTest.php
  tests/phpunit/CRM/Core/PseudoConstantTest.php
  tests/phpunit/CRM/Dedupe/DedupeFinderTest.php
  tests/phpunit/Civi/CCase/SequenceListenerTest.php
  tests/phpunit/CiviTest/CiviCaseTestCase.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/api/v3/ActivityCaseTest.php
  tests/phpunit/api/v3/CaseTest.php
Labels: master, merge on pass

#31688 (NFC) Civi\Test::execute() - Raise exception for SQL error
  Civi/Test.php
Labels: master

#31690 Remove deprecated code
  CRM/Dedupe/Finder.php
Labels: master

#31691 Remove deprecated code
  CRM/Dedupe/Finder.php
Labels: master

#31693 Sloppy Test Detector - Add option to complain about test junk
  Civi/Test/CiviEnvBuilder.php
  Civi/Test/SloppyTestChecker.php
Labels: master

#31557 standaloneusers - translate password reset page titles
  ext/standaloneusers/ang/crmResetPassword/crmResetPassword.html
Labels: master, merge on pass

#31694 Fix unix timestamp bug in deferred revenue report
  CRM/Report/Form/Contribute/DeferredRevenue.php
  tests/phpunit/api/v3/ReportTemplateTest.php
Labels: master

#31679 Cleanups in MembershipTest
  tests/phpunit/CRM/Member/BAO/MembershipTest.php
Labels: master

#31696 revert accidental end date change on Deferred Revenue Report
  CRM/Report/Form/Contribute/DeferredRevenue.php
Labels: master

#31619 Riverlea - set color-scheme in DynamicCss so system elements respect dark_mode setting
  ext/riverlea/Civi/riverlea/DynamicCss.php
  ext/riverlea/streams/thames/css/_variables.css
Labels: master

#31702 Fix test to remove option value in tearDown
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/api/v3/CaseTypeTest.php
  tests/phpunit/api/v3/JobTest.php
Labels: master

#31680 (dev/core#5665) CiviTest/bootstrap.php - Don't try to init DB before tests
  CRM/Core/Smarty.php
  CRM/Core/Smarty/UserContentPolicy.php
  CRM/Core/Smarty/plugins/function.crmSqlData.php
  Civi/Test.php
  Civi/Test/CiviEnvBuilder.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/CiviTest/bootstrap.php
  tests/phpunit/api/v3/SyntaxConformanceTest.php
  tests/phpunit/api/v4/Entity/ConformanceTest.php
Labels: master, merge ready

#31403 CRM_Utils_Cache - Use more consistent group names
  CRM/Extension/System.php
  CRM/Utils/Cache.php
  Civi/Core/Container.php
  tests/phpunit/CRM/Core/BAO/CacheTest.php
  tests/phpunit/Civi/Core/Service/AutoDefinitionTest.php
Labels: master, merge ready, run-extended-tests

#31703 Remove a couple of cases of the old NULL array
  CRM/Case/Page/Tab.php
  CRM/Core/BAO/ConfigSetting.php
  CRM/UF/Form/Field.php
  bin/cron.php
Labels: master

#31704 Remove some crud tests that are well covered elsewhere
  tests/phpunit/api/v3/CampaignTest.php
  tests/phpunit/api/v3/ImTest.php
Labels: master, merge on pass

#31546 Add value check in DisplayProfile.tpl
  templates/CRM/Event/Form/Registration/DisplayProfile.tpl
Labels: master

#31707 [REF] Update PHPSpreadseet from 1.29.4 to 1.29.7
  composer.lock
Labels: merge on pass, 5.81

#31708 Backport Package updates to 5.80
  composer.json
  composer.lock
Labels: 5.80

#31709 5.81
  composer.lock
Labels: master

#31651 dev/core#5581 Expose php & smarty compatibility
  CRM/Extension/Info.php
  templates/CRM/Admin/Page/ExtensionDetails.tpl
Labels: merge ready, 5.81

#31710 [REF][PHP8.2] Declare properties on CRM_Contribute_Page_PaymentInfo
  CRM/Contribute/Page/PaymentInfo.php
Labels: master

#31711 [REF] Fix notice error if accepted credit cards field IS NULL
  CRM/Admin/Form/PaymentProcessor.php
Labels: master

#31712 5.81
  CRM/Extension/Info.php
  templates/CRM/Admin/Page/ExtensionDetails.tpl
Labels: master

#31664 SearchKit - Add labels for joins
  CRM/Contact/BAO/SavedSearch.php
  CRM/Upgrade/Incremental/SmartGroups.php
  Civi/Api4/Generic/Traits/SavedSearchInspectorTrait.php
  ext/afform/admin/Civi/Api4/Action/Afform/LoadAdminData.php
  ext/afform/admin/ang/afGuiEditor/afGuiSearch.component.js
  ext/search_kit/ang/crmSearchAdmin.module.js
  ext/search_kit/ang/crmSearchAdmin/crmSearch-for.html
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdmin.component.js
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdminDisplay.component.js
  ext/search_kit/ang/crmSearchAdmin/resultsTable/crmSearchAdminResultsTable.component.js
  ext/search_kit/ang/crmSearchAdmin/resultsTable/crmSearchAdminResultsTable.html
  tests/phpunit/CRM/Upgrade/Incremental/BaseTest.php
Labels: master

#31695 Api - Adjust permissions for custom field metadata
  CRM/Core/Permission.php
Labels: master

#31716 Update info.xml for search_kit_reports and fix links in search_kit chart_kit
  ext/chart_kit/info.xml
  ext/search_kit/info.xml
  ext/search_kit_reports/info.xml
Labels: master

#31715 Check if property is set before using
  Civi/Api4/Generic/AbstractAction.php
Labels: master

#31718 dev/core#5652 - country list is wrong
  Civi/Schema/Entity/AddressMetadata.php
  schema/Core/Address.entityType.php
  tests/phpunit/CRM/Core/BAO/AddressTest.php
Labels: 5.81

#31720 Afform - Fix bad jQuery-validation in popups
  js/crm.ajax.js
Labels: master, sig:unreleased-regression

#31719 SearchKit - Fix multiple bugs in tally function
  ext/search_kit/Civi/Api4/Action/SearchDisplay/Run.php
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/SearchRunTest.php
Labels: master, merge on pass, has-test, sig:unreleased-regression

#31721 5.81
  Civi/Schema/Entity/AddressMetadata.php
  schema/Core/Address.entityType.php
  tests/phpunit/CRM/Core/BAO/AddressTest.php
Labels: master

#31722 dev/core#5652 - backport 31718 - fix country list
  Civi/Schema/Entity/AddressMetadata.php
  schema/Core/Address.entityType.php
  tests/phpunit/CRM/Core/BAO/AddressTest.php
Labels: merge on pass, 5.80

#31724 Backport fix for dev/core#5674
  ext/search_kit/Civi/Api4/Action/SearchDisplay/Run.php
Labels: 5.81

#31726 Backport fix for dev/core#5674
  ext/search_kit/Civi/Api4/Action/SearchDisplay/Run.php
Labels: merge on pass, 5.80

#31731 financialacls: it's OK to disable the extension
  ext/financialacls/info.xml
Labels: master

#31729 [REF] Api4 - Custom field auto-cleanup improvements
  CRM/Core/BAO/CustomField.php
  Civi/Test/Api4TestTrait.php
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/SearchRunTest.php
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/SearchRunWithCustomFieldTest.php
  tests/phpunit/api/v4/Action/ContactDuplicatesTest.php
  tests/phpunit/api/v4/Api4TestBase.php
  tests/phpunit/api/v4/Custom/BasicCustomFieldTest.php
  tests/phpunit/api/v4/Custom/ContactCustomJoinTest.php
  tests/phpunit/api/v4/Custom/CoreUtilTest.php
  tests/phpunit/api/v4/Custom/CreateCustomValueTest.php
  tests/phpunit/api/v4/Custom/CreateWithOptionGroupTest.php
  tests/phpunit/api/v4/Custom/CustomContactRefTest.php
  tests/phpunit/api/v4/Custom/CustomEntityReferenceTest.php
  tests/phpunit/api/v4/Custom/CustomFieldAlterTest.php
  tests/phpunit/api/v4/Custom/CustomFieldGetFieldsTest.php
  tests/phpunit/api/v4/Custom/CustomFileTest.php
  tests/phpunit/api/v4/Custom/CustomGroupACLTest.php
  tests/phpunit/api/v4/Custom/CustomGroupTest.php
  tests/phpunit/api/v4/Custom/CustomProfileFieldTest.php
  tests/phpunit/api/v4/Custom/CustomTestBase.php
  tests/phpunit/api/v4/Custom/CustomValueTest.php
  tests/phpunit/api/v4/Custom/ExportCustomGroupTest.php
  tests/phpunit/api/v4/Custom/ExtendFromIndividualTest.php
  tests/phpunit/api/v4/Custom/FalseNotEqualsZeroTest.php
  tests/phpunit/api/v4/Custom/PseudoconstantTest.php
  tests/phpunit/api/v4/Custom/UpdateCustomValueTest.php
Labels: master, has-test

#31732 CustomFields - Enforce ACLs in all API get calls
  CRM/Core/BAO/CustomGroup.php
  CRM/Core/Permission.php
  Civi/Api4/Action/CustomField/Get.php
  Civi/Api4/CustomGroup.php
  Civi/Api4/Generic/CachedDAOGetAction.php
  tests/phpunit/api/v4/Custom/CustomGroupACLTest.php
Labels: master, has-test

#31733 Rename in-template variable for clarity
  templates/CRM/Profile/Form/Dynamic.tpl
Labels: 5.81

#31706 dev/core#5571 dev/core#5566 Fix regressions on radio options rendering in profiles
  CRM/Core/BAO/CustomField.php
  CRM/Core/Form.php
  CRM/Core/QuickForm/GroupWithDiv.php
  CRM/Core/QuickForm/RadioWithDiv.php
  templates/CRM/Profile/Form/Dynamic.tpl
  templates/CRM/UF/Form/Fields.tpl
Labels: 5.81

#31738 (dev/core#5602) CiviAccount - Fix "Close Batch" on older Smarty
  templates/CRM/Financial/Page/BatchTransaction.tpl
Labels: merge on pass, 5.81

#31736 dev/core#5580 Fix ActionSchedule save on repeat events
  CRM/Core/Form/RecurringEntity.php
  Civi/Api4/Service/Spec/Provider/ActionScheduleSpecProvider.php
Labels: 5.81

#31734 5.81
  CRM/Core/BAO/CustomField.php
  CRM/Core/Form.php
  CRM/Core/Form/RecurringEntity.php
  CRM/Core/QuickForm/GroupWithDiv.php
  CRM/Core/QuickForm/RadioWithDiv.php
  Civi/Api4/Service/Spec/Provider/ActionScheduleSpecProvider.php
  templates/CRM/Financial/Page/BatchTransaction.tpl
  templates/CRM/Profile/Form/Dynamic.tpl
  templates/CRM/UF/Form/Fields.tpl
Labels: master

#31730 fix appendBreadCrumb calls when deleting PriceSet / PriceField
  CRM/Price/Page/Field.php
  CRM/Price/Page/Option.php
  CRM/Price/Page/Set.php
  CRM/Utils/System/Base.php
  CRM/Utils/System/Standalone.php
Labels: master, merge on pass

#31739 riverlea - remove margin from search col buttons, we have gap
  ext/riverlea/core/org.civicrm.afform-ang/afCore.css
Labels: master

#31741 Use escaping in SQL query for best practice
  CRM/Core/BAO/CustomField.php
Labels: master, merge on pass

#31740 (dev/core#2941) Drop CiviConnect files
  CRM/Cxn/ApiRouter.php
  CRM/Cxn/BAO/Cxn.php
  CRM/Cxn/CiviCxnHttp.php
  CRM/Cxn/CiviCxnStore.php
  CRM/Cxn/DAO/Cxn.php
  CRM/Utils/Check/Component/Security.php
  CRM/Utils/System.php
  Civi/Core/Container.php
  ang/crmCxn.ang.php
  ang/crmCxn.css
  ang/crmCxn.js
  ang/crmCxn/AboutCtrl.html
  ang/crmCxn/AboutCtrl.js
  ang/crmCxn/AdvTable.html
  ang/crmCxn/AdvTable.js
  ang/crmCxn/CheckAddress.js
  ang/crmCxn/ConfirmConnectCtrl.html
  ang/crmCxn/ConfirmConnectCtrl.js
  ang/crmCxn/ConfirmReconnectCtrl.html
  ang/crmCxn/ConfirmReconnectCtrl.js
  ang/crmCxn/Connectivity.html
  ang/crmCxn/LinkDialogCtrl.html
  ang/crmCxn/LinkDialogCtrl.js
  ang/crmCxn/ManageCtrl.html
  ang/crmCxn/ManageCtrl.js
  ang/crmCxn/PermTable.html
  ang/crmCxn/PermTable.js
  api/v3/Cxn.php
  api/v3/CxnApp.php
  composer.json
  composer.lock
  extern/cxn.php
  schema/Cxn/Cxn.entityType.php
  sql/civicrm_generated.mysql
  tests/phpunit/Civi/Angular/ManagerTest.php
  tests/phpunit/api/v3/MultilingualTest.php
  tests/phpunit/api/v3/SyntaxConformanceTest.php
Labels: master, merge on pass

#31743 Add name to contributor-key.yml
  contributor-key.yml
Labels: master

#31742 dev/core#4827 - Afform - Update page route after saving a new form
  ext/afform/admin/ang/afGuiEditor/afGuiEditor.component.js
Labels: master

#31744 Undeleted file in deleted file list (5.80.2 only)
  deleted-files-list.json
Labels: merge on pass, 5.80

#31746 Minor cleanups in test classes
  tests/phpunit/CRM/Core/BAO/ActionScheduleTest.php
  tests/phpunit/CRM/Core/BAO/LocationTest.php
  tests/phpunit/CRM/Core/BAO/MessageTemplateTest.php
  tests/phpunit/CRM/Core/FieldOptionsTest.php
Labels: master, merge on pass

#31359 Api4 - Enable managed, hierarchical traits for Campaign entities
  ext/civi_campaign/Civi/Api4/Campaign.php
  ext/civi_campaign/Civi/Api4/Survey.php
Labels: master

#31692 [REF] Ensure that Privacy (single checkbox) fields show up on Event R…
  templates/CRM/UF/Form/Fields.tpl
Labels: master

#31748 Add name to contributor-key.yml
  contributor-key.yml
Labels: master

#31747 Minor clean up in test classes
  tests/phpunit/CRM/Campaign/BAO/PetitionTest.php
  tests/phpunit/CRM/Core/BAO/CustomValueTableSetGetTest.php
  tests/phpunit/CRM/Pledge/Form/SearchTest.php
Labels: master

#31632 Search Kit - For "Entity" displays, provide TABLE/VIEW options
  CRM/Core/BAO/SchemaHandler.php
  Civi/Api4/Generic/AbstractGetAction.php
  ext/search_kit/Civi/Api4/Action/SKEntity/Refresh.php
  ext/search_kit/Civi/Api4/Event/Subscriber/SKEntitySubscriber.php
  ext/search_kit/Civi/BAO/SK_Entity.php
  ext/search_kit/Civi/Schema/SkEntityMetaProvider.php
  ext/search_kit/Civi/Search/Admin.php
  ext/search_kit/Civi/Search/SKEntityGenerator.php
  ext/search_kit/ang/crmSearchAdmin/displays/searchAdminDisplayEntity.component.js
  ext/search_kit/ang/crmSearchAdmin/displays/searchAdminDisplayEntity.html
  ext/search_kit/templates/CRM/Search/Help/DisplayTypeEntity.hlp
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/EntityDisplayTest.php
Labels: master

#31750 PHPUnit Bootstrap - Minor workflow improvement re:xdebug
  tests/phpunit/CiviTest/bootstrap.php
Labels: master, merge on pass

#31751 5.80.3 - Add notes. Set version.
  js/version.json
  release-notes.md
  release-notes/5.80.3.md
  sql/civicrm_generated.mysql
  sql/test_data_second_domain.mysql
  xml/version.xml
Labels: 5.80

#31749 Reduce the hard-codedness of test data
  tests/phpunit/CRM/Report/Form/Contribute/DetailTest.php
  tests/phpunit/CRM/Report/Form/Contribute/fixtures/dataset-ascii.sql
  tests/phpunit/CiviTest/CiviReportTestCase.php
Labels: master

#31752 Minor clean ups in test classes
  tests/phpunit/api/v3/GroupNestingTest.php
  tests/phpunit/api/v3/LineItemTest.php
  tests/phpunit/api/v3/MailingContactTest.php
Labels: master

#31753 Some test clean up
  tests/phpunit/CRM/Dedupe/MergerTest.php
  tests/phpunit/CRM/PCP/BAO/PCPTest.php
  tests/phpunit/CRM/Pledge/BAO/PledgePaymentTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: master

#31755 Test clean up on campaign
  tests/phpunit/CRM/Contribute/Form/Task/PDFLetterCommonTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: master, merge on pass

#31754 Minor clean ups in test classes
  tests/fixtures/case_types.json
  tests/phpunit/CRM/Case/BAO/CaseTypeForkTest.php
  tests/phpunit/CRM/Upgrade/Incremental/php/FiveTwentyTest.php
  tests/phpunit/CiviTest/CiviCaseTestCase.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/api/v3/ActivityCaseTest.php
  tests/phpunit/api/v3/CaseTest.php
  tests/phpunit/api/v3/CaseTypeTest.php
Labels: master, merge on pass

#31717 SearchKit - Improve the UI for sql functions
  Civi/Api4/Query/SqlFunction.php
  Civi/Api4/Query/SqlFunctionCOALESCE.php
  Civi/Api4/Query/SqlFunctionCONCAT_WS.php
  Civi/Api4/Query/SqlFunctionIF.php
  Civi/Api4/Query/SqlFunctionIFNULL.php
  Civi/Api4/Query/SqlFunctionLEAST.php
  Civi/Api4/Query/SqlFunctionREPLACE.php
  ext/search_kit/ang/crmSearchAdmin/crmSearchFunction.component.js
  ext/search_kit/ang/crmSearchAdmin/crmSearchFunction.html
Labels: master

#31756 SearchKit - Fix loading and saving options in the UI
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdmin.component.js
  ext/search_kit/ang/crmSearchTasks/crmSearchInput/crmSearchInput.component.js
Labels: sig:regression, 5.82

#31757 5.82
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdmin.component.js
  ext/search_kit/ang/crmSearchTasks/crmSearchInput/crmSearchInput.component.js
Labels: master

#31758 dev/core#5679 - Fix autocomplete for savedSearch filter on join entity
  ext/afform/core/Civi/Afform/AfformMetadataInjector.php
  ext/afform/core/Civi/Afform/FormDataModel.php
  ext/afform/core/Civi/Api4/Subscriber/AfformAutocompleteSubscriber.php
  ext/afform/mock/tests/phpunit/api/v4/Afform/AfformAutocompleteUsageTest.php
  ext/afform/mock/tests/phpunit/api/v4/Afform/AfformUsageTestCase.php
  ext/search_kit/Civi/Search/AfformSearchMetadataInjector.php
Labels: master, merge on pass

#31675 Remove pointless price set wrangling from batch data entry form
  CRM/Batch/Form/Entry.php
  CRM/Price/BAO/PriceSet.php
  tests/phpunit/CRM/Batch/Form/EntryTest.php
Labels: master

#31759 minor test cleanup
  tests/phpunit/CRM/Contact/Form/Task/EmailTest.php
  tests/phpunit/CRM/Dedupe/MergerTest.php
  tests/phpunit/CRM/Report/Form/ActivityTest.php
  tests/phpunit/CRM/SMS/BAO/ProviderTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/api/v3/CaseTypeTest.php
  tests/phpunit/api/v3/ContributionTest.php
Labels: master

#31761 Afform - Test cleanup
  Civi/Test/Api4TestTrait.php
  ext/afform/mock/tests/phpunit/api/v4/Afform/AfformAutocompleteUsageTest.php
  ext/afform/mock/tests/phpunit/api/v4/Afform/AfformConditionalUsageTest.php
  ext/afform/mock/tests/phpunit/api/v4/Afform/AfformContactUsageTest.php
  ext/afform/mock/tests/phpunit/api/v4/Afform/AfformCustomFieldUsageTest.php
  ext/afform/mock/tests/phpunit/api/v4/Afform/AfformFileUploadTest.php
  ext/afform/mock/tests/phpunit/api/v4/Afform/AfformGroupSubscriptionUsageTest.php
  ext/afform/mock/tests/phpunit/api/v4/Afform/AfformRelationshipUsageTest.php
  ext/afform/mock/tests/phpunit/api/v4/Afform/AfformTest.php
  ext/afform/mock/tests/phpunit/api/v4/Afform/AfformTestCase.php
  ext/afform/mock/tests/phpunit/api/v4/Afform/AfformUsageTestCase.php
  tests/phpunit/api/v4/Api4TestBase.php
Labels: master

#31762 SearchKit - Fix testTallyWithGroupBy intermittent test fail
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/SearchRunTest.php
Labels: 5.82

#31769 Fixes white trash icon bug that could trigger accidental delete
  ext/riverlea/core/css/components/_icons.css
Labels: 5.81

#31770 [forward merge #31769] Fixes white trash icon bug that could trigger accidental delete
  ext/riverlea/core/css/components/_icons.css
Labels: 5.82

#31771 5.82
  ext/riverlea/core/css/components/_icons.css
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/SearchRunTest.php
Labels: master

#31766 CustomGroup: provide a more helpful message when a extendsChildType fails to validate
  CRM/Core/BAO/CustomGroup.php
Labels: master

#31772 SearchKit - Correctly format numeric custom fields
  Civi/Api4/Event/Subscriber/HierarchicalEntitySubscriber.php
  Civi/Api4/Generic/CachedDAOGetAction.php
  Civi/Api4/Generic/DAOGetFieldsAction.php
  Civi/Api4/Utils/FormattingUtil.php
  ext/search_kit/Civi/Api4/Action/SearchDisplay/AbstractRunAction.php
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/EditableSearchTest.php
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/SearchRunTest.php
  ext/search_kit/tests/phpunit/api/v4/SearchSegment/SearchSegmentTest.php
Labels: master, merge on pass, has-test

#31774 CRM_Import_Parser - Delete unused deprecated functions
  CRM/Import/Parser.php
Labels: master

#31775 Delete unused TabHeader.php
  CRM/Campaign/Form/Survey/TabHeader.php
Labels: master

#31776 Delete unused Location.php
  CRM/Contact/Form/Location.php
Labels: master

#31764 DeletedFiles - Always use case-sensitivity when generating list
  deleted-files-list.json
  tools/scripts/generate-deleted-files-list.php
Labels: master

#31603 ContributionView: show the contrib id, remove some buttons, layout changes
  CRM/Contribute/Form/ContributionView.php
  CRM/Contribute/Selector/Search.php
  css/civicrm.css
  templates/CRM/Contribute/Form/ContributionView.tpl
  templates/CRM/Contribute/Form/PaymentInfoBlock.tpl
  templates/CRM/Contribute/Page/ContributionTotals.tpl
  templates/CRM/Contribute/Page/PaymentInfo.tpl
  templates/CRM/Event/Form/ParticipantView.tpl
  templates/CRM/Pledge/Page/Payment.tpl
  templates/CRM/Price/Page/LineItem.tpl
  tests/phpunit/CRM/Contribute/Form/ContributionViewTest.php
Labels: master, sig:user interfacing improvement

#31638 dev/core#5610 Simplifying the session cookie message to make it more readable
  CRM/Core/Controller.php
  CRM/Core/Page.php
  templates/CRM/common/fatal.tpl
Labels: master, merge ready, sig:user interfacing improvement

#31760 minor test cleanup
  tests/phpunit/api/v3/CustomFieldTest.php
  tests/phpunit/api/v3/FinancialTypeTest.php
Labels: master

#31773 Api3 - Remove old functions deprecated since 2014
  api/v3/ActivityType.php
  api/v3/Case.php
  api/v3/Constant.php
  api/v3/CustomValue.php
  api/v3/GroupContact.php
  api/v3/MailingGroup.php
  api/v3/Profile.php
  api/v3/SurveyRespondant.php
  deleted-files-list.json
  tests/phpunit/api/v3/ActivityTest.php
  tests/phpunit/api/v3/ActivityTypeTest.php
  tests/phpunit/api/v3/ConstantTest.php
  tests/phpunit/api/v3/GroupContactTest.php
  tests/phpunit/api/v3/MultilingualTest.php
  tests/phpunit/api/v3/ProfileTest.php
  tests/phpunit/api/v3/SurveyRespondantTest.php
  tests/phpunit/api/v3/SyntaxConformanceTest.php
Labels: master, merge ready

#31779 Navigation - Get 'delete' link working
  CRM/Admin/Form/Navigation.php
  CRM/Core/BAO/Navigation.php
  templates/CRM/Admin/Form/Navigation.tpl
Labels: master

#31780 SearchKit - Fix task links after an inline-edit
  ext/search_kit/Civi/Api4/Action/SearchDisplay/AbstractRunAction.php
Labels: sig:regression, 5.82

#31429 many relative dates aren't going to 11:59:59
  CRM/Utils/Date.php
  tests/phpunit/CRM/Utils/DateTest.php
Labels: master, merge ready

#31782 Merge 5.82 -> master
  ext/search_kit/Civi/Api4/Action/SearchDisplay/AbstractRunAction.php
Labels: master

#31783 Add missing PR 31671 to release notes for 5.81.0
  release-notes/5.81.0.md
Labels: master

#31765 Bump min php version to 8.0
  CRM/Upgrade/Incremental/General.php
  composer.json
  composer.lock
Labels: master

#31767 SearchKit - Refresh DB entities via table-swap
  ext/search_kit/Civi/Api4/Action/SKEntity/Refresh.php
  ext/search_kit/Civi/Search/Exception/RefreshInProgressException.php
Labels: master, merge ready

#31777 Standalone - explicitly set $appRootPath and $settingsPath as globals in boot file
  setup/res/civicrm.standalone.php.txt
Labels: master, merge ready

#31787 Minor test cleanups
  tests/phpunit/CiviTest/CiviCaseTestCase.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/api/v3/CaseTypeTest.php
  tests/phpunit/api/v3/ContributionTest.php
  tests/phpunit/api/v3/CustomFieldTest.php
  tests/phpunit/api/v3/MailingABTest.php
  tests/phpunit/api/v3/MailingContactTest.php
  tests/phpunit/api/v3/MailingTest.php
Labels: master

#31788 See if this test data is all used....
  tests/phpunit/api/v3/dataset/group_admins.xml
  tests/phpunit/api/v3/dataset/group_contact_admins_1.xml
  tests/phpunit/api/v3/dataset/group_nesting.xml
  tests/phpunit/api/v3/dataset/group_subscribers.xml
  tests/phpunit/api/v3/dataset/option_value_acl_roles.xml
  tests/phpunit/api/v3/dataset/option_value_activity.xml
  tests/phpunit/api/v3/dataset/option_value_case.xml
  tests/phpunit/api/v3/dataset/option_value_case_activity.xml
  tests/phpunit/api/v3/dataset/option_value_contribution_status.xml
  tests/phpunit/api/v3/dataset/option_value_email_greeting.xml
  tests/phpunit/api/v3/dataset/option_value_from_email_address.xml
  tests/phpunit/api/v3/dataset/option_value_mail_protocol.xml
  tests/phpunit/api/v3/dataset/option_value_phone_type.xml
Labels: master, merge ready

#31792 Bump cookie and socket.io
  package-lock.json
Labels: 5.82

#31763 Change version to 6.0.alpha1
  CRM/Core/I18n/SchemaStructure.php
  CRM/Upgrade/Incremental/Base.php
  CRM/Upgrade/Incremental/php/SixZero.php
  CRM/Upgrade/Incremental/sql/5.83.alpha1.mysql.tpl
  CRM/Upgrade/Incremental/sql/6.0.alpha1.mysql.tpl
  js/version.json
  mixin/lib/civimix-schema@5/pathload.main.php
  mixin/lib/civimix-schema@5/src/AutomaticUpgrader.php
  mixin/lib/civimix-schema@5/src/CiviMixSchema.php
  mixin/lib/civimix-schema@5/src/DAO.php
  mixin/lib/civimix-schema@5/src/SchemaHelper.php
  mixin/lib/civimix-schema@5/src/SchemaHelperInterface.php
  mixin/lib/civimix-schema@5/src/SqlGenerator.php
  mixin/lib/pathload.index.php
  sql/civicrm_generated.mysql
  sql/test_data_second_domain.mysql
  tools/mixin/bin/build-lib
  xml/version.xml
Labels: master

#31797 (REF) Api4TestBase - Each test starts with default list of components
  Civi/Test.php
  tests/phpunit/api/v4/Api4TestBase.php
Labels: master

#31795 (REF) Tests - Sundry cleanups
  tests/phpunit/CRM/Utils/FileTest.php
  tests/phpunit/api/v4/Action/ContactIsDeletedTest.php
  tests/phpunit/api/v4/Action/ReplaceTest.php
Labels: master

#31727 dev/core#5640 explicitly disable mod_negotiation MultiViews in default Standalone apache config
  setup/res/htaccess.txt
Labels: master, run-standalone

#31800 CRM_Utils_System_Base::url() has 6 parameters not 7
  CRM/Utils/System/Base.php
Labels: master

#31793 5.82
  package-lock.json
Labels: master

#31804 SearchKit - Fix failing test
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/SearchRunTest.php
Labels: master

#31805 SearchKit - Fix unit test assumptions
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/SearchRunTest.php
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/SearchRunWithCustomFieldTest.php
Labels: master

#31802 5.82
  templates/CRM/Contact/Form/Selector.tpl
Labels: master

#31790 Try removing more of the old test dataset
  tests/phpunit/api/v3/dataset/acl_1_all.xml
  tests/phpunit/api/v3/dataset/activity_1_emailed.xml
  tests/phpunit/api/v3/dataset/activity_4_created.xml
  tests/phpunit/api/v3/dataset/activity_email
  tests/phpunit/api/v3/dataset/activity_email_unparseable
  tests/phpunit/api/v3/dataset/activity_target_1_emailed.xml
  tests/phpunit/api/v3/dataset/activity_type_5.xml
  tests/phpunit/api/v3/dataset/case_types.xml
  tests/phpunit/api/v3/dataset/contact_1.xml
  tests/phpunit/api/v3/dataset/contact_17.xml
  tests/phpunit/api/v3/dataset/contact_hld.xml
  tests/phpunit/api/v3/dataset/contact_hld_upd.xml
  tests/phpunit/api/v3/dataset/contact_ind.xml
  tests/phpunit/api/v3/dataset/contact_ind_upd.xml
  tests/phpunit/api/v3/dataset/contact_org.xml
  tests/phpunit/api/v3/dataset/contact_org_upd.xml
  tests/phpunit/api/v3/dataset/contribution_types.xml
  tests/phpunit/api/v3/dataset/custom_group_activity_type.xml
  tests/phpunit/api/v3/dataset/financial_types_account.xml
  tests/phpunit/api/v3/dataset/location_type_data.xml
  tests/phpunit/api/v3/dataset/mailing_bounced.xml
  tests/phpunit/api/v3/dataset/mailing_contact.xml
  tests/phpunit/api/v3/dataset/mailing_delivered.xml
  tests/phpunit/api/v3/dataset/openid.xml
  tests/phpunit/api/v3/dataset/option_group_acl_role.xml
  tests/phpunit/api/v3/dataset/option_group_activity.xml
  tests/phpunit/api/v3/dataset/option_group_case.xml
  tests/phpunit/api/v3/dataset/option_group_contribution_status.xml
  tests/phpunit/api/v3/dataset/option_group_email_greeting.xml
  tests/phpunit/api/v3/dataset/option_group_from_email_address.xml
  tests/phpunit/api/v3/dataset/option_group_mail_protocol.xml
  tests/phpunit/api/v3/dataset/option_group_phone_type.xml
  tests/phpunit/api/v3/dataset/sample_case.xml
  tests/phpunit/api/v3/dataset/uf_group_contact_activity_26.xml
Labels: master, merge on pass

#31807 Smarty notice fix
  templates/CRM/Event/Form/Selector.tpl
Labels: master, merge on pass

#31796 (REF) CiviUnitTestCase - Plug more leaks
  CRM/Admin/Form/Setting/Localization.php
  CRM/Core/BAO/PreferencesDate.php
  CRM/Core/Component.php
  Civi/Core/SettingsBag.php
  tests/phpunit/CRM/Activity/BAO/ActivityTest.php
  tests/phpunit/CRM/Contact/Page/View/UserDashBoardTest.php
  tests/phpunit/CRM/Contribute/Form/Task/PDFLetterCommonTest.php
  tests/phpunit/CRM/Group/Page/AjaxTest.php
  tests/phpunit/CiviTest/CiviUnitTestCase.php
  tests/phpunit/api/v3/GroupTest.php
  tests/phpunit/api/v4/Query/PermissionCheckTest.php
Labels: master, merge on pass

#31806 [REF][PHP8.2] Declare properties on CRM_Admin_Form_WordReplacements
  CRM/Admin/Form/WordReplacements.php
Labels: master

#31809 dev/core#5539 Stop removing dejaVu fonts
  composer.json
  composer.lock
  tools/scripts/composer/dompdf-cleanup.sh
Labels: master

#31814 CRM_Report_Form::_aliases set public
  CRM/Report/Form.php
Labels: master

#31816 MixinTestCase - Small usability tweaks
  Civi/Test/MixinTestCase.php
  tests/extensions/shimmy/tests/phpunit/E2E/Shimmy/LifecycleTest.php
Labels: master

#31817 [REF][PHP8.2] Declare tabs property in CRM_Campaign_Page_Vote
  CRM/Campaign/Page/Vote.php
Labels: master

#31815 SettingsAdminTest - Relax assertion re: permissions on disabled extenions
  mixin/setting-admin@1/example/tests/mixin/SettingsAdminTest.php
Labels: master, merge ready

#31818 [REF][PHP8.2] Declare fields property in CRM_Contact_Form_Task_Batch
  CRM/Contact/Form/Task/Batch.php
Labels: master

#31819 [REF][PHP8.2] Declare property in CRM_Mailing_Form_ForwardMailing
  CRM/Mailing/Form/ForwardMailing.php
Labels: master

#31799 Convert MembershipLog.modified_date from date to timestamp so we record time as well
  CRM/Member/BAO/Membership.php
  CRM/Upgrade/Incremental/php/SixZero.php
  schema/Member/MembershipLog.entityType.php
  tests/phpunit/CRM/Member/Form/MembershipRenewalTest.php
Labels: master, merge on pass

#31820 [NFC] Simplify function call in test
  tests/phpunit/CRM/Member/Form/MembershipRenewalTest.php
Labels: master, merge on pass

#31821 Fix PHP Warning in getAdditionalParticipants
  CRM/Event/BAO/Participant.php
Labels: master

#31812 dev/core#5688 restore contact summary tab keys
  CRM/Contact/Page/View/Summary.php
Labels: master

#31822 dev/core#5688 restore contact tab keys
  CRM/Contact/Page/View/Summary.php
Labels: 5.82

#31823 ContactSummary - Fix missing tabs
  CRM/Contact/Page/View/Summary.php
Labels: sig:regression, 5.82

#31825 5.82
  CRM/Contact/Page/View/Summary.php
Labels: master

#31827 Cast to string for explode in CRM_Utils_CommaKV
  CRM/Utils/CommaKV.php
Labels: master

#31829 CiviCampaign - Remove hard-coded reference to unused custom fields
  CRM/Campaign/BAO/Query.php
  templates/CRM/Campaign/Form/Search/Common.tpl
Labels: master

#31826 Api3 - Restore groupContact.delete action
  api/v3/GroupContact.php
Labels: master, merge on pass

#31810 Finish deprecating PDFLetterCommon class
  CRM/Contact/Form/Task/PDFTrait.php
  CRM/Core/Form/Task/PDFLetterCommon.php
Labels: master

#31831 Update Miscellaneous admin form to mostly use settings
  CRM/Admin/Form/Setting/Miscellaneous.php
  settings/Core.setting.php
  settings/Search.setting.php
  templates/CRM/Admin/Form/Setting/Miscellaneous.tpl
Labels: master, merge on pass

#31835 Fix position of closing icon tags
  ang/api4Explorer/Explorer.html
  ext/message_admin/ang/crmMsgadm/EditContent.html
Labels: master, merge on pass

#31840 (NFC) mixin/polyfill.php - Tweak boolean notation
  mixin/polyfill.php
Labels: master, merge on pass

#31841 REF - Remove some uses of deprecated `CRM_Utils_Array::value`
  CRM/Admin/Form/LabelFormats.php
  CRM/Admin/Form/PdfFormats.php
  CRM/Case/BAO/Case.php
  CRM/Case/XMLProcessor/Process.php
  CRM/Contact/BAO/Query.php
  CRM/Core/Action.php
  CRM/Core/BAO/LabelFormat.php
  CRM/Core/BAO/PaperSize.php
  CRM/Core/BAO/PdfFormat.php
  CRM/Core/Controller.php
  CRM/Core/DAO.php
  CRM/Core/DAO/permissions.php
  CRM/Core/Form.php
  CRM/Core/Form/Search.php
  CRM/PCP/Form/Contribute.php
  CRM/SMS/BAO/SmsProvider.php
  CRM/UF/Form/Field.php
Labels: master

#31845 standaloneusers - fix send password reset action on Administer Users
  ext/standaloneusers/managed/SavedSearch_Administer_UserAccounts.mgd.php
Labels: run-standalone, 5.81

#31836 Afform - Fully deprecate `contact_id` and remove AfformBlock.tpl
  ext/afform/admin/ang/afGuiEditor/afGuiSearch.html
  ext/afform/core/afform.php
  ext/afform/core/templates/afform/contactSummary/AfformBlock.tpl
  ext/afform/core/tests/phpunit/Civi/Afform/AfformContactSummaryTest.php
Labels: master, merge on pass

#31848 standaloneusers - fix send password reset action on Administer Users
  ext/standaloneusers/managed/SavedSearch_Administer_UserAccounts.mgd.php
Labels: merge on pass, run-standalone, 5.82

#31847 Install script - minor code cleanup
  setup/plugins/blocks/sample-data.tpl.php
Labels: master

#31837 Afform - Fix reading urlHash
  ext/afform/core/ang/afCore.js
Labels: master

#31852 CRM_Core_BAO_MessageTemplate::getMessageTemplates throws API Request Authorization failed because check permissions is enforced
  CRM/Core/BAO/MessageTemplate.php
Labels: master, merge on pass

#31853 Online regen script needs sendmail now
  .github/workflows/regen.yml
Labels: master

#31854 5.81.1 - Add notes. Set version.
  deleted-files-list.json
  js/version.json
  release-notes.md
  release-notes/5.81.1.md
  sql/civicrm_generated.mysql
  sql/test_data_second_domain.mysql
  xml/version.xml
Labels: 5.81
