Repository civicrm/civicrm-core, pull requests merged in 2025-08, with the labels that each got.

#33318 CustomField - Add method to retrieve custom field by name
  CRM/Contact/BAO/Query.php
  CRM/Core/BAO/CustomField.php
  CRM/Report/Form.php
  tests/phpunit/CRM/Core/BAO/CustomFieldTest.php
Labels: master, has-test

#33319 Follow up on #33309: Never show pay later option when disabled
  CRM/Event/Form/Registration/Confirm.php
Labels: master, merge on pass

#33326 Riverlea, fixes colour issue on disabled table row buttons and icons
  ext/riverlea/core/css/_base.css
Labels: master

#33304 dev/core#6018 SearchKit - Fix dragging in Safari
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdminLinkGroup.component.js
  ext/search_kit/ang/crmSearchDisplayTable/crmSearchDisplayTable.component.js
Labels: master

#33327 CustomField - Add code comments to clarify shortName and longName
  CRM/Core/BAO/CustomField.php
Labels: master

#33332 fix bottom margin for dialogs with buttonpane
  ext/riverlea/core/css/components/_dialogs.css
Labels: master

#33329 Import: do not crash if importing an invalid country
  CRM/Contact/Import/Parser/Contact.php
Labels: master

#33337 [NFC] 6.5 release note late changes
  release-notes/6.5.0.md
Labels: 6.5

#33339 6.5
  ext/riverlea/CHANGELOG.md
  ext/riverlea/core/css/_core.css
  ext/riverlea/info.xml
  release-notes/6.5.0.md
Labels: master

#33342 dev/core#6043 QuickSearch - Ensure UNION does not return duplicate results
  Civi/Api4/Generic/AutocompleteAction.php
  Civi/Api4/Query/Api4EntitySetQuery.php
  Civi/Api4/Query/Api4Query.php
  tests/phpunit/api/v4/Action/AutocompleteQuicksearchTest.php
Labels: master, has-test, sig:unreleased-regression

#33345 6.5
  ext/afform/core/ang/af/afField.component.js
Labels: master

#33341 AdminUI - Consistently set 'disabled' class on table row, not cell
  ext/civicrm_admin_ui/managed/SavedSearch_Manage_Contribution_Pages.mgd.php
  ext/civicrm_admin_ui/managed/SavedSearch_Manage_Scheduled_Jobs.mgd.php
Labels: master

#33355 Fix for deprecation notice when updating older UserJobs
  ext/civiimport/CRM/CiviImport/Form/Generic/GenericTrait.php
  ext/civiimport/CRM/CiviImport/Form/Generic/MapField.php
Labels: master

#33352 [NFC] Update Doc Block comment now that function referenced is in a t…
  js/Common.js
Labels: master

#33348 [REF] SearchKit - Code cleanup in ApiBatch tasks
  ext/search_kit/ang/crmSearchTasks/crmSearchTaskApiBatch.ctrl.js
  ext/search_kit/ang/crmSearchTasks/crmSearchTaskApiBatch.html
  ext/search_kit/ang/crmSearchTasks/traits/searchDisplayTasksTrait.service.js
Labels: master

#33356 Fix Message Preview crash on sites with only quick config pricesets
  CRM/Contribute/WorkflowMessage/Contribution/BasicContribution.php
Labels: master

#25823 Return a more helpful server side validation message
  ext/afform/core/Civi/Api4/Action/Afform/Submit.php
  ext/afform/mock/tests/phpunit/api/v4/Afform/AfformAutocompleteUsageTest.php
  ext/afform/mock/tests/phpunit/api/v4/Afform/AfformConditionalUsageTest.php
  ext/afform/mock/tests/phpunit/api/v4/Afform/AfformContactUsageTest.php
Labels: master, merge on pass

#33331 Standalone - print "Path not found" for non-civicrm routes
  Civi/Standalone/WebEntrypoint.php
Labels: master

#33354 Use default Redis handler if configured
  CRM/Utils/System/Standalone.php
Labels: master, merge ready

#33364 (dev/core#6022) Upgrade - Final rebuild should have clean entity list
  CRM/Upgrade/Form.php
Labels: 6.5

#33366 (dev/core#6022) Upgrade - Final rebuild should have clean entity list
  CRM/Upgrade/Form.php
Labels: 6.4

#33367 6.5
  CRM/Upgrade/Form.php
Labels: master

#33344 Update pear/db to latest (1.12.2) - Remove overly aggressive patching
  composer.json
  composer.lock
  tools/patches/raw/pear/db/pear_db_civicrm_changes.patch
Labels: master

#33378 Add php & smarty compatibility info to core extensions
  ext/afform/admin/info.xml
  ext/afform/core/info.xml
  ext/afform/html/info.xml
  ext/afform/login_token/info.xml
  ext/afform/mock/info.xml
  ext/authx/info.xml
  ext/chart_kit/info.xml
  ext/civi_campaign/info.xml
  ext/civi_case/info.xml
  ext/civi_contribute/info.xml
  ext/civi_event/info.xml
  ext/civi_mail/info.xml
  ext/civi_member/info.xml
  ext/civi_pledge/info.xml
  ext/civi_report/info.xml
  ext/civicrm_admin_ui/info.xml
  ext/civicrm_search_ui/info.xml
  ext/civigrant/info.xml
  ext/civiimport/info.xml
  ext/ckeditor4/info.xml
  ext/contributioncancelactions/info.xml
  ext/elavon/info.xml
  ext/eventcart/info.xml
  ext/ewaysingle/info.xml
  ext/financialacls/info.xml
  ext/flexmailer/info.xml
  ext/greenwich/info.xml
  ext/iframe/info.xml
  ext/legacycustomsearches/info.xml
  ext/legacydedupefinder/info.xml
  ext/legacyprofiles/info.xml
  ext/message_admin/info.xml
  ext/oauth-client/info.xml
  ext/oembed/info.xml
  ext/payflowpro/info.xml
  ext/recaptcha/info.xml
  ext/riverlea/info.xml
  ext/scheduled_communications/info.xml
  ext/search_kit/info.xml
  ext/search_kit_reports/info.xml
  ext/sequentialcreditnotes/info.xml
  ext/standaloneusers/info.xml
  ext/tellafriend/info.xml
  ext/user_dashboard/info.xml
  tools/extensions/event_check/info.xml
  tools/extensions/org.civicrm.demoqueue/info.xml
  tools/extensions/phpstorm/info.xml
Labels: master, merge on pass

#33381 Unshare import getDedupeRule function
  CRM/Contact/Import/Parser/Contact.php
  CRM/Import/Parser.php
  ext/civiimport/Civi/Import/ImportParser.php
Labels: 6.6

#33295 [REF] crmUi - Cleanup js code
  ang/crmUi.js
Labels: master, merge ready

#33382 Riverlea is enabled for all new installs, remove Standalone-specific enabler
  setup/plugins/init/StandaloneRiverlea.civi-setup.php
Labels: master

#33384 FormBuilder Admin: set stability to Stable
  ext/afform/admin/info.xml
Labels: master, merge on pass

#33383 [NFC] Remove method from doc block
  CRM/Utils/System.php
Labels: merge on pass, 6.6

#33385 Strengthen api3 contact merge test; make assumptions more explicit
  tests/phpunit/api/v3/ContactTest.php
Labels: master

#33388 Api4 Explorer - Fix debug param showing in generated code
  ang/api4Explorer/Explorer.html
  ang/api4Explorer/Explorer.js
Labels: master

#33389 dev/core#6053 revert static cache in AbstractEntity::getInfo
  CRM/Upgrade/Form.php
  Civi/Api4/Generic/AbstractEntity.php
Labels: 6.6

#33390 dev/core#6053 revert static cache in AbstractEntity::getInfo
  CRM/Upgrade/Form.php
  Civi/Api4/Generic/AbstractEntity.php
Labels: 6.5

#33391 dev/core#6053 revert static cache in AbstractEntity::getInfo
  CRM/Upgrade/Form.php
  Civi/Api4/Generic/AbstractEntity.php
Labels: 6.4

#33399 Alpha order financial types
  CRM/Financial/BAO/FinancialType.php
Labels: master, merge on pass

#33400 Don't show "My billing address is the same as above" for event payments on confirm
  templates/CRM/Core/BillingBlock.tpl
Labels: master

#33401 [NFC] Follow up to #33400 ensure that showPaymentOnConfirm is always …
  templates/CRM/Contribute/Form/AdditionalInfo/CreditCard.tpl
  templates/CRM/Contribute/Form/AdditionalInfo/DirectDebit.tpl
  templates/CRM/Contribute/Form/AdditionalPayment.tpl
  templates/CRM/Contribute/Form/Contribution.tpl
  templates/CRM/Contribute/Form/Contribution/Main.tpl
  templates/CRM/Contribute/Form/UpdateBilling.tpl
  templates/CRM/Core/BillingBlockWrapper.tpl
  templates/CRM/Event/Form/EventFees.tpl
  templates/CRM/Event/Form/Registration/Confirm.tpl
  templates/CRM/Event/Form/Registration/Register.tpl
  templates/CRM/Financial/Form/Payment.tpl
  templates/CRM/Member/Form/MembershipCommon.tpl
Labels: master, merge on pass

#33403 Fix Smarty Notice errors on Event Location tab
  templates/CRM/Event/Form/ManageEvent/Location.tpl
Labels: master, merge on pass

#33402 Ensure that if an Event is configured to show a map and that he map p…
  CRM/Core/BAO/Address.php
Labels: master, merge on pass

#33308 Add (basic) import actions
  CRM/Import/Form/DataSource.php
  CRM/Import/Forms.php
  ext/civiimport/CRM/CiviImport/Form/MapField.php
  ext/civiimport/Civi/Api4/Event/Subscriber/ImportSubscriber.php
  ext/civiimport/Civi/Import/ActivityParser.php
  ext/civiimport/Civi/Import/ContributionParser.php
  ext/civiimport/Civi/Import/CustomValueParser.php
  ext/civiimport/Civi/Import/GenericParser.php
  ext/civiimport/Civi/Import/ImportParser.php
  ext/civiimport/Civi/Import/MembershipParser.php
  ext/civiimport/Civi/Import/ParticipantParser.php
  ext/civiimport/ang/crmCiviimport.js
  ext/civiimport/ang/crmCiviimport/Import.html
  ext/civiimport/tests/phpunit/CiviApiImportTest.php
Labels: 6.6

#33371 avoid duplication in Api4 LegacyEntityScanner
  Civi/Api4/Service/LegacyEntityScanner.php
Labels: master, merge ready

#33405 6.6
  CRM/Import/Form/DataSource.php
  CRM/Import/Forms.php
  ext/civiimport/CRM/CiviImport/Form/MapField.php
  ext/civiimport/Civi/Api4/Event/Subscriber/ImportSubscriber.php
  ext/civiimport/Civi/Import/ActivityParser.php
  ext/civiimport/Civi/Import/ContributionParser.php
  ext/civiimport/Civi/Import/CustomValueParser.php
  ext/civiimport/Civi/Import/GenericParser.php
  ext/civiimport/Civi/Import/ImportParser.php
  ext/civiimport/Civi/Import/MembershipParser.php
  ext/civiimport/Civi/Import/ParticipantParser.php
  ext/civiimport/ang/crmCiviimport.js
  ext/civiimport/ang/crmCiviimport/Import.html
  ext/civiimport/tests/phpunit/CiviApiImportTest.php
Labels: master

#33406 CiviImport - Add icons & labels on import screen
  ext/civiimport/ang/crmCiviimport/Import.html
Labels: merge on pass, 6.6

#33271 dev/financial#234 Update the Financial Type of linked Price Field Val…
  CRM/Contribute/Form/ContributionPage/Settings.php
Labels: master, merge ready

#33416 6.6
  deleted-files-list.json
  ext/afform/admin/ang/afGuiEditor/elements/afGuiField.component.js
  ext/riverlea/managed/RiverleaStream_HackneyBrook.mgd.php
  ext/riverlea/managed/RiverleaStream_Minetta.mgd.php
  ext/riverlea/managed/RiverleaStream_Thames.mgd.php
  ext/riverlea/managed/RiverleaStream_Walbrook.mgd.php
  ext/riverlea/streams/empty/_dark.css
  ext/riverlea/streams/empty/_variables.css
  ext/riverlea/streams/hackneybrook/_dark.css
  ext/riverlea/streams/hackneybrook/_variables.css
  ext/riverlea/streams/minetta/_dark.css
  ext/riverlea/streams/minetta/_variables.css
  ext/riverlea/streams/thames/_dark.css
  ext/riverlea/streams/thames/_variables.css
  ext/riverlea/streams/walbrook/_dark.css
  ext/riverlea/streams/walbrook/_variables.css
Labels: master

#33417 Fix fatal error when event is free
  templates/CRM/Event/Form/Selector.tpl
Labels: 6.6

#33418 6.6 to master
  templates/CRM/Event/Form/Selector.tpl
Labels: master

#33411 dev/core#4859 SearchKit - Fix restoring options for date select fields
  ext/afform/admin/ang/afGuiEditor/afGuiEditOptions.component.js
  ext/afform/admin/ang/afGuiEditor/elements/afGuiField.component.js
Labels: master

#33421 CustomField - Avoid crash when blank value is passed to format date
  CRM/Core/BAO/CustomField.php
  tests/phpunit/CRM/Core/BAO/CustomFieldTest.php
Labels: has-test, sig:regression, 6.6

#33423 dev/core#6059 - backport 33421
  CRM/Core/BAO/CustomField.php
  tests/phpunit/CRM/Core/BAO/CustomFieldTest.php
Labels: merge on pass, 6.5

#33427 Update soft credit exception check
  ext/civiimport/Civi/Import/ContributionParser.php
Labels: 6.6

#33430 Fix Smarty2/3/4 Notices on missing value and type on some statistics …
  CRM/Report/Form/Contribute/Repeat.php
Labels: master, merge on pass

#33377 APIv4 - Ensure custom field default values are respected on new records
  Civi/Api4/Generic/Traits/DAOActionTrait.php
  tests/phpunit/api/v4/Custom/CreateCustomValueTest.php
Labels: master, merge ready

#33435 dev/core#6065 Ensure that when using the Update Contacts option on a …
  ext/civiimport/Civi/Import/MembershipParser.php
  ext/civiimport/Civi/Import/ParticipantParser.php
Labels: 6.6

#33438 6.6
  ext/civiimport/Civi/Import/MembershipParser.php
  ext/civiimport/Civi/Import/ParticipantParser.php
  tests/phpunit/CRM/Member/Import/Parser/MembershipTest.php
Labels: master

#33439 Fix modified_date not updating on delete-to-trash
  CRM/Contact/BAO/Contact.php
  tests/phpunit/CRM/Contact/BAO/ContactTest.php
Labels: master, has-test

#33434 Add apiv4 support to Dedupe.getduplicates
  CRM/Core/BAO/PrevNextCache.php
  tests/phpunit/CRM/Dedupe/MergerTest.php
Labels: master, has-test

#33442 Afform - Fix permission fallback check
  ext/afform/admin/ang/afAdmin/afAdminList.controller.js
Labels: master, merge ready

#33324 RiverLea: fixes layout bug on FormBuilder inline layout inside Details
  ext/riverlea/core/org.civicrm.afform-ang/afCore.css
Labels: master

#33456 RiverLea: datepicker inactive dates, fix alignment & dark-mode contrast
  ext/riverlea/core/css/components/_form.css
Labels: master, merge on pass

#33446 Api4 - Fix DAO fields_callback handling of default value
  Civi/Api4/Service/Spec/Provider/DAOFieldsCallbackAdapterSpecProvider.php
  tests/phpunit/api/v4/Action/FieldsCallbackTest.php
Labels: merge ready, has-test, 6.6

#33461 Afform: Fix admin links to properly check permissions
  ext/afform/admin/Civi/AfformAdmin/AfformAdminInjector.php
  ext/afform/core/afform.php
  ext/afform/core/ang/afCore.ang.php
  ext/afform/core/ang/afCore.js
Labels: master, merge ready

#33457 Prevent CiviCRM upgrade routine interfering with non-CiviCRM permissions on Joomla
  CRM/Core/Permission/Joomla.php
Labels: master

#33447 EntityProvider - Add new 'civi.entity.fields' event
  CRM/Core/DAO/Base.php
  Civi/Api4/Service/Spec/Provider/DAOFieldsCallbackAdapterSpecProvider.php
  Civi/Schema/EntityMetadataBase.php
  Civi/Schema/EntityMetadataInterface.php
  Civi/Schema/EntityProvider.php
  tests/phpunit/CRM/Core/DAO/AllCoreTablesTest.php
  tests/phpunit/Civi/Schema/EntityTest.php
  tests/phpunit/api/v4/Action/FieldsCallbackTest.php
Labels: master, has-test

#33450 Payment Processor - Admin screen quietly copies live credentials to testing
  CRM/Admin/Form/PaymentProcessor.php
Labels: master, merge ready

#33458 Afform: Fix multivalued hidden fields
  ext/afform/core/Civi/Afform/FormDataModel.php
  ext/afform/core/ang/af/afField.component.js
  ext/afform/core/ang/af/fields/Hidden.html
Labels: master, merge ready

#33454 SearchKit - Fix inline-edit when using groupBy
  ext/search_kit/Civi/Api4/Action/SearchDisplay/AbstractRunAction.php
  ext/search_kit/Civi/Api4/Action/SearchDisplay/InlineEdit.php
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/EditableSearchTest.php
Labels: master, has-test

#33464 RiverLea: SearchKit display - centre aligns table cells with multiple buttons
  ext/riverlea/core/org.civicrm.search_kit-css/crmSearchDisplayTable.css
Labels: master

#33441 dev/core#6054: Custom fields for contact subtype also required for parent contact type
  CRM/Contact/Form/Contact.php
Labels: merge ready, 6.6

#33449 FormBuilder: render display-only entityref fields client-side
  ext/afform/core/ang/af/afField.component.js
Labels: merge ready, 6.6

#33469 CustomField - Clear cache when updating weight
  CRM/Utils/Weight.php
Labels: master

#33475 6.6
  Civi/Api4/Service/Spec/Provider/MailingGetSpecProvider.php
  composer.lock
Labels: master

#33476 dev/core#6069 - ext/eventcart - fix Event Cart checkout participant registration failure
  ext/eventcart/CRM/Event/Cart/Form/Cart.php
  ext/eventcart/CRM/Event/Cart/Form/Checkout/ParticipantsAndPrices.php
Labels: master

#33477 SearchKit - Hide search functions from entities that don't support it.
  ext/search_kit/ang/crmSearchAdmin/crmSearch-conditions.html
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdmin.component.js
  ext/search_kit/ang/crmSearchAdmin/crmSearchAdminFields.html
  ext/search_kit/ang/crmSearchAdmin/crmSearchFunction.component.js
Labels: master

#33459 ensure we show unique contacts on survey interview page
  CRM/Campaign/Form/Task/Interview.php
Labels: master, merge ready

#33488 ensure adding wildcard to "quick search -> advanced search workflow" works when automatic wildcard setting is enabled
  CRM/Core/Resources/Common.php
  js/crm.menubar.js
Labels: master

#33481 dev/core#6070 Fix quicksearch includes deleted contacts
  Civi/Api4/Service/Autocomplete/ContactAutocompleteProvider.php
  tests/phpunit/api/v4/Action/AutocompleteQuicksearchTest.php
Labels: merge on pass, sig:unreleased-regression, 6.6
