Repository civicrm/civicrm-core, pull requests merged in 2025-06, with the labels that each got.

#32906 SearchKit - Handle REGEXP operator as string in data type checks
  ext/afform/admin/ang/afGuiEditor/afGuiFieldValue.directive.js
  ext/search_kit/ang/crmSearchTasks/crmSearchInput/crmSearchInput.component.js
Labels: sig:regression, 6.3

#32905 Followup to 32903 - undefined var
  CRM/Case/Form/CustomData.php
Labels: master

#32907 6.3
  ext/afform/admin/ang/afGuiEditor/afGuiFieldValue.directive.js
  ext/search_kit/ang/crmSearchTasks/crmSearchInput/crmSearchInput.component.js
Labels: master

#30446 Add test for api4 Product.get options unserialize
  tests/phpunit/api/v4/Entity/ProductTest.php
Labels: master, merge on pass, has-test

#32899 [NFC] 6.3 Release notes first pass
  contributor-key.yml
  release-notes/6.3.0.md
Labels: 6.3

#30681 [REF] Set outer tr of a custom field row to be a radiogroup role for …
  templates/CRM/Custom/Form/Edit/CustomField.tpl
Labels: master, sig:accessibility

#31082 Manage Premiums: remove the tiny thumbnail
  CRM/Contribute/Form/ManagePremiums.php
  templates/CRM/Contribute/Form/ManagePremiums.tpl
Labels: master, merge ready, sig:user interfacing improvement

#32911 Add 'add' to field metadata
  schema/Core/UserJob.entityType.php
Labels: 6.3

#32917 Add 'add' metadata to civicrm_user_job.search_display_id
  schema/Core/UserJob.entityType.php
Labels: merge on pass, 6.3

#32918 6.3
  schema/Core/UserJob.entityType.php
Labels: master

#32916 SearchKit - Selectable mailing type
  CRM/Mailing/BAO/Mailing.php
  ext/search_kit/ang/crmSearchTasks/crmSearchTaskMailing.ctrl.js
  ext/search_kit/ang/crmSearchTasks/crmSearchTaskMailing.html
Labels: master

#32904 SearchKit - Inline-edit fixes
  ext/search_kit/Civi/Api4/Action/SearchDisplay/AbstractRunAction.php
Labels: master

#32910 Update Preview template to match changes made in #30681 to fix the ra…
  templates/CRM/Custom/Form/Preview.tpl
Labels: master, sig:accessibility

#32924 6.3 to master
  CRM/Utils/PDF/Document.php
  composer.json
  composer.lock
  ext/search_kit/Civi/Api4/Action/SearchDisplay/CreateBatch.php
  ext/search_kit/ang/crmSearchDisplayBatch/crmSearchDisplayBatch.component.js
  ext/search_kit/ang/crmSearchDisplayBatch/crmSearchDisplayBatch.html
  ext/search_kit/tests/phpunit/api/v4/SearchBatch/SearchBatchTest.php
  sql/civicrm_generated.mysql
  xml/templates/message_templates/sample/Sample Responsive Design Newsletter - Single Column.tpl
  xml/templates/message_templates/sample/Sample Responsive Design Newsletter - Two Column.tpl
Labels: master

#32909 Fixes a failure to upgrade Import Mappings in the SixTwo and SixOne scripts.
  CRM/Upgrade/Incremental/php/SixOne.php
  CRM/Upgrade/Incremental/php/SixThree.php
  CRM/Upgrade/Incremental/php/SixTwo.php
  deleted-files-list.json
  js/version.json
  sql/civicrm_generated.mysql
  sql/test_data_second_domain.mysql
  tests/phpunit/CRM/Upgrade/Incremental/php/SixOneTest.php
  tests/phpunit/CRM/Upgrade/Incremental/php/SixTwoTest.php
  xml/version.xml
Labels: run-distmaker, 6.3

#32921 dev/core#5930 Fix incorrect processing of line items on Contribution update
  CRM/Contribute/Form/Contribution.php
  CRM/Financial/BAO/Order.php
  tests/phpunit/CRM/Contribute/Form/ContributionTest.php
Labels: 6.3

#32928 Notice fix in import
  CRM/Import/Forms.php
Labels: 6.3

#32929 6.3
  CRM/Contribute/Form/Contribution.php
  CRM/Financial/BAO/Order.php
  CRM/Import/Forms.php
  tests/phpunit/CRM/Contribute/Form/ContributionTest.php
Labels: master

#32931 RiverLea regression: fixes rendering of ul/ol in text regions
  ext/riverlea/core/ang/crmStatusPage.css
  ext/riverlea/core/css/_base.css
  ext/riverlea/core/css/_cms.css
  ext/riverlea/core/css/components/_alerts.css
Labels: 6.3

#32934 6.4list fixes
  ext/riverlea/core/ang/crmStatusPage.css
  ext/riverlea/core/css/_base.css
  ext/riverlea/core/css/_cms.css
  ext/riverlea/core/css/components/_alerts.css
Labels: merge on pass, 6.4

#32932 fix phpoffice requiring dev stability for drupal 8 installs
  composer.json
  composer.lock
Labels: 6.4

#32800 fix warning in Setting::getFields when passed non-existent name filter
  Civi/Api4/Action/Setting/GetFields.php
Labels: master

#32938 6.4
  composer.json
  composer.lock
Labels: master

#32901 Remove deprecated DateRange.tpl
  templates/CRM/Core/DateRange.tpl
  templates/CRM/common/jcalendar.tpl
Labels: master, merge ready

#32902 Riverlea - Reset details css for consistency
  ext/riverlea/core/css/_base.css
Labels: 6.4

#32942 RiverLea regression: css input size modifiers oftenbeing over-ridden
  ext/riverlea/core/css/components/_form.css
Labels: 6.4

#32948 NFC Fix comment to match type hint
  ext/standaloneusers/Civi/Standalone/SessionHandler.php
Labels: master

#32926 Remove noisily deprecated date functions file
  CRM/Core/Form/Date.php
Labels: master

#32946 Show cancelled participants in Also registered by
  CRM/Event/BAO/Participant.php
  templates/CRM/Event/Form/Participant.tpl
  templates/CRM/Event/Form/ParticipantView.tpl
Labels: master, merge ready

#32950 dev/core#5936 - duplicate draft statuses appearing in mailing search form
  CRM/Mailing/Form/Search.php
Labels: 6.4

#32952 6.4 to master
  CRM/Mailing/Form/Search.php
  ext/riverlea/core/css/_base.css
  ext/riverlea/core/css/_variables.css
  ext/riverlea/core/css/components/_form.css
  ext/riverlea/core/css/contactSummary.css
  ext/riverlea/streams/empty/css/_variables.css
Labels: master

#32953 Only create table if not exists
  mixin/lib/civimix-schema@5/src/SqlGenerator.php
Labels: merge on pass, 6.4

#32954 SiteEmail - Remove redundant label from "Site Email Address" form
  ang/afform/afformSiteEmailAddress.aff.html
Labels: master

#32955 Remove any existing ForeignKey before adding one
  CRM/Core/BAO/SchemaHandler.php
  mixin/lib/civimix-schema@5/src/SqlGenerator.php
Labels: merge on pass, merge ready, 6.4

#32969 RiverLea: fixes variable name typo for padding on new/edit contact
  ext/riverlea/core/css/_fixes.css
Labels: 6.4

#32958 dev/core#5932 - Bump select2 to v3.5-civicrm-1.3
  composer.json
  composer.lock
Labels: master

#32956 Update standalone install to be non-destructive
  CRM/Core/BAO/SchemaHandler.php
  ext/standaloneusers/CRM/Standaloneusers/Upgrader.php
  mixin/lib/civimix-schema@5/src/SqlGenerator.php
Labels: master, merge on pass, merge ready, run-standalone

#32912 issue#5922: FormBuilder: Can't submit form with required date field with alternate format
  ang/crmUi.js
Labels: master, merge ready

#32979 Standalone login with email
  ext/standaloneusers/Civi/Api4/Action/User/Login.php
  ext/standaloneusers/templates/CRM/Standaloneusers/Page/Login.tpl
Labels: master

#32980 Fix file custom fields on contribution pages
  CRM/Contribute/Form/ContributionPage.php
  js/crm.ajax.js
Labels: master, merge ready

#32989 [NFC] [PHPUNIT10] - dev/core#5944 - make some test dataproviders static 2
  tests/phpunit/CRM/Activity/BAO/ActivityTest.php
  tests/phpunit/CRM/Activity/Form/ActivityViewTest.php
  tests/phpunit/CRM/Activity/Form/SearchTest.php
  tests/phpunit/CRM/Activity/Import/Parser/ActivityTest.php
Labels: master

#32990 [NFC] [PHPUNIT10] - dev/core#5944 - make some test dataproviders static 3
  tests/phpunit/CRM/Case/BAO/CaseTest.php
  tests/phpunit/CRM/Case/BAO/CaseTypeTest.php
  tests/phpunit/CRM/Case/Form/CustomDataTest.php
  tests/phpunit/CRM/Case/Form/TaskTest.php
  tests/phpunit/CRM/Case/XMLProcessor/ProcessTest.php
  tests/phpunit/CRM/Case/XMLProcessor/ReportTest.php
Labels: master

#32995 Remove extraneous ts
  CRM/Core/xml/Menu/Admin.xml
  CRM/Event/xml/Menu/Event.xml
Labels: master

#32997 [NFC] [PHPUNIT10] - dev/core#5944 - typo in test envbuilder
  Civi/Test/CiviEnvBuilder.php
Labels: master, merge on pass

#32987 Api4 - Catch errors with pseudoconstant lookups
  Civi/Api4/Generic/DAOGetFieldsAction.php
Labels: master

#32993 (REF) Swap rebuildMenuAndCaches() with Civi::rebuild()
  CRM/ACL/Form/WordPress/Permissions.php
  CRM/Core/Invoke.php
  CRM/Extension/Manager.php
  CRM/Extension/QueueTasks.php
  CRM/Upgrade/Form.php
  CRM/Upgrade/Incremental/Base.php
  Civi/Api4/Action/System/Flush.php
  api/v3/Extension.php
  api/v3/System.php
Labels: master

#30990 Add custom fields for email to the event manage location form
  CRM/Contact/Form/Edit/EmailBlockTrait.php
  CRM/Event/Form/ManageEvent/Location.php
  templates/CRM/Event/Form/ManageEvent/Location.tpl
  tests/phpunit/CRM/Event/Form/ManageEvent/LocationTest.php
Labels: master

#32965 Afform - compute redirects and confirmation messages server side
  ext/afform/core/Civi/Api4/Action/Afform/AbstractProcessor.php
  ext/afform/core/Civi/Api4/Action/Afform/Submit.php
  ext/afform/core/ang/af/afForm.component.js
Labels: master

#33006 Afform.submit - better check for whether redirect/message is already set
  ext/afform/core/Civi/Api4/Action/Afform/Submit.php
Labels: master

#33009 Use checkPermissions = FALSE for retrieving weight
  Civi/Api4/Generic/Traits/DAOActionTrait.php
Labels: merge on pass, 6.4

#33014 Escape HML characters in parameters for `{help}` smarty tag
  CRM/Core/Smarty/plugins/function.help.php
Labels: master

#33007 dev/core#5945 Add in count of Recipients for the mailing as apposed t…
  CRM/Mailing/BAO/Mailing.php
  api/v3/Mailing.php
  ext/civi_mail/ang/crmMailing/services.js
  ext/civi_mail/ang/crmMailingAB/EditCtrl/report.html
  templates/CRM/Mailing/Page/Report.tpl
  tests/phpunit/api/v3/MailingTest.php
Labels: master

#33018 dev/core#5955 - fix error in help bubble
  templates/CRM/Admin/Form/Setting/Miscellaneous.hlp
Labels: 6.4

#33010 [backport] fix User afform entity meta for formbuilder
  ext/standaloneusers/afformEntities/User.php
Labels: 6.3

#33017 CustomGroup - Ensure table exists before referencing it
  CRM/Core/BAO/CustomGroup.php
  Civi/Schema/EntityRepository.php
Labels: master

#33015 Allow extra detail to be passed through to validate
  CRM/Core/DAO.php
Labels: master, merge ready

#32998 Make Smarty default to version 5
  CRM/Core/SmartyCompatibility.php
  CRM/Upgrade/Incremental/php/SixFive.php
  CRM/Utils/Check/Component/Smarty.php
Labels: master

#33023 RiverLea Regressions: as found in deduper extension: .panel-body and .btn-block issues
  ext/riverlea/core/css/components/_buttons.css
  ext/riverlea/core/css/components/_components.css
Labels: merge on pass, 6.4

#33026 Add dot to end of sentence in just merged upgrade message
  CRM/Upgrade/Incremental/php/SixFive.php
Labels: master

#33035 [REF] For DB Query Exceptions when generating the Yellow Screen data …
  CRM/Core/Error.php
Labels: master, merge on pass

#33032 SearchKit - Fix undefined variable 'requestId'
  ext/search_kit/ang/crmSearchDisplay/traits/searchDisplayBaseTrait.service.js
Labels: sig:regression, 6.4

#33016 RiverLea Responsive Tables bug - fixes /dev/core/5948 & tidies related css
  ext/riverlea/core/css/_fixes.css
  ext/riverlea/core/css/components/_tabs.css
  ext/riverlea/core/org.civicrm.search_kit-css/crmSearchAdmin.css
Labels: 6.4

#33037 Rebuilder - Also, Angular
  Civi/Core/Rebuilder.php
Labels: master, merge on pass

#33038 (REF) Simplify calls to `Civi::rebuild()`
  CRM/Extension/Manager.php
  CRM/Extension/QueueTasks.php
  api/v3/Extension.php
Labels: master

#33024 RiverLea: Make FormBuilder edit buttons the same across streams, and subtler
  ext/riverlea/core/org.civicrm.afform-ang/afCore.css
Labels: master

#32329 SearchKit - Save to file rather than browser download.
  CRM/Core/BAO/File.php
  ext/search_kit/Civi/Api4/Action/SearchDisplay/Download.php
  ext/search_kit/Civi/Api4/Action/SearchDisplay/ResultDataTrait.php
  ext/search_kit/Civi/Api4/Action/SearchDisplay/SaveFile.php
  ext/search_kit/Civi/Api4/SearchDisplay.php
  ext/search_kit/tests/phpunit/api/v4/SearchDisplay/SearchSaveFileTest.php
Labels: master, merge ready

#33041 Fully hide pricesetTotal div when not needed
  templates/CRM/Price/Form/Calculate.tpl
Labels: master

#33044 Fix jQuery selector for jQuery 3 support
  js/crm.ajax.js
Labels: master

#33030 i18n - Flush relevant caches after changing multilingual configuration
  CRM/Core/I18n/Schema.php
Labels: master

#33048 Redirect skip postprocess hook, replaced it with replaceUserContext
  CRM/Admin/Form/Job.php
Labels: master

#33055 (NFC) Riverlea - Fix linting issue in _form.css
  ext/riverlea/core/css/components/_form.css
Labels: master

#33058 api_v3_SystemTest - Fix for newer MySQL and MariaDB versions
  CRM/Core/BAO/SchemaHandler.php
  tests/phpunit/api/v3/SystemTest.php
Labels: master, merge on pass

#33060 fix warning in Setting::getFields when non-existent name filter is …
  Civi/Api4/Action/Setting/GetFields.php
Labels: 6.4

#33065 distmaker - Update build-report for Joomla 5
  distmaker/dists/repo-report.sh
  distmaker/utils/repo-report.php
Labels: master

#33062 [NFC] first pass at 6.4 release notes
  contributor-key.yml
  release-notes/6.4.0.md
Labels: 6.4

#33066 6.4
  contributor-key.yml
  release-notes/6.4.0.md
Labels: master

#33068 [NFC] remove duplicate contributor
  contributor-key.yml
Labels: 6.4

#33027 add a relativeDate hook
  CRM/Utils/Date.php
  CRM/Utils/Hook.php
  tests/phpunit/CRM/Utils/DateTest.php
Labels: master, needs-documentation

#33000 Replace getCRMDatabasePrefix() with simpler/more sensible functions getCMSDatabaseName()/getCRMDatabaseName()
  CRM/Utils/System/Backdrop.php
  CRM/Utils/System/Base.php
  CRM/Utils/System/Drupal.php
Labels: master, merge ready

#33050 Fix UserJob templates to load without optional keys
  CRM/Import/DataSource.php
  CRM/Import/Forms.php
  CRM/Import/Parser.php
Labels: 6.4

#33070 umm...
  tests/phpunit/CiviTest/CiviUnitTestCase.php
Labels: master

#33071 6.4
  CRM/Import/DataSource.php
  CRM/Import/Forms.php
  CRM/Import/Parser.php
Labels: master

#32200 Fix token labels for custom fields with colons in their labels
  CRM/Core/EntityTokens.php
Labels: master

#33052 RiverLea: add fallback font-family and size for iframes
  ext/riverlea/core/css/_base.css
Labels: master, merge on pass

#33080 Add Upgrade message for WP User Creation Change
  CRM/Upgrade/Incremental/php/SixFour.php
Labels: 6.4

#33081 [NFC] 6.4 release notes late changes
  release-notes/6.4.0.md
Labels: 6.4

#33082 6.4
  CRM/Upgrade/Incremental/php/SixFour.php
  release-notes/6.4.0.md
Labels: master
